### ISSUE TITLE
Just want to say 'Thank You'.

### ISSUE THREAD

**Issue by taoeffect** [ElementsProject/lightning#1]
Thanks for the work you're putting into this, it's very much needed. And although you're using C, you seem to have managed to avoid C++. I guess thank you as well for that. :)

**Comment by taoeffect** [comment]
Sidenote: dear Rusty, there is [a language](http://www.rust-lang.org/) that seems inspired by your name, you may want to consider it if you haven't already. ;)

**Comment by rustyrussell** [comment]
I am deeply interested in rust, but this is not the project to be My First Program :)
