### ISSUE TITLE
Restarting lightningd repeats "Adding block 507526" and up

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#1002]
Current block height is 509182. Every time I call `lightning-cli stop` and then relaunch, it repeats more than 1600 blocks. Not sure if this is intended or if it indicates a problem.

**Comment by cdecker** [comment]
That's as expected currently. We do not yet store any real blockchain related state so we just replay the blockchain since the creation of the first block. We'll implement an independent UTXO tracking soon allowing us to resume tailing the blockchain from the last time we were online.

**Comment by jochemin** [comment]
Mine always starts from block 370312, it takes more than 3 days to sync again so everytime I stop lightning I can't use it again in 3 days. (Bitcoin Core 15.0.1 + v0.5.2-2016-11-21-1932-gfe670b9a

**Comment by cdecker** [comment]
Working on it :wink: 

You can reduce it by removing channels that were opened a long time ago.

**Comment by Sjors** [comment]
I don't know if it's a recent change or a result of my machine having crashed, but it's now adding blocks all the way from genesis.

**Comment by jochemin** [comment]
My problem was in the lightning.sqlite3 file, there was a corrupted record in the channels table. After deleting It everything works fine.

**Comment by Sjors** [comment]
> adding blocks all the way from genesis

Turns out I accidentally launched in testnet mode. Restarting with `--network=bitcoin` only reset to ~504563.

**Comment by cdecker** [comment]
Oh ok, will re-close then 😉

**Comment by robtex** [comment]
i have this issue as well, however i've never used it on testnet. My node never catches up though.
