### ISSUE TITLE
Cannot pay to yalls.org, due to fee rate is higher than 0.5%

### ISSUE THREAD

**Issue by andronoob** [ElementsProject/lightning#1006]
### Issue and Steps to Reproduce
1.Attempted to pay for an article on https://mainnet.yalls.org
2.`lightning-cli pay [BOLT11]` told me this:
```
{ "code" : 206, "message" : "Fee 2102 is 1.401333% of payment 150000; max fee requested is 0.500000%", "data" : { "fee" : 2102, "feepercent" : 1.401333, "msatoshi" : 150000, "maxfeepercent" : 0.500000 } }
```

### `getinfo` output
```
{ "id" : "029c84efc179604981e24234b12025adfb4cec56de68f19ea32323170e03c3af28", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "108.61.162.115", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1932-gfe670b9", "blockheight" : 509300, "network" : "bitcoin" }
```

**Comment by cdecker** [comment]
That is a safety fuse so you don't spend more than 0.5% with the automatically found route. If you are happy to pay more, you can override the maxfeerate with the following:

```
lightning-cli pay -k bolt11=[BOLT11] maxfeepercent=1.23
```

This would allow up to 1.23% fees.

**Comment by andronoob** [comment]
@cdecker Thanks.
BTW, I have some additional questions:
Why did I receive this error? Does that mean that any payment should have a minimum fee of 2 satoshis? If that's true, paying merely several satoshis seems not to be appropriate with LN.

**Comment by ZmnSCPxj** [comment]
> Why did I receive this error?

The nodes between you and mainnet.yalls.org are charging high rates for forwarding your payment.

>Does that mean that any payment should have a minimum fee of 2 satoshis?

No. It means the nodes between you and mainnet.yalls.org are exorbitant. If you do not want to pay more than the default 0.5% as fees and can afford the onchain fees, connect directly to mainnet.yalls.org instead.

**Comment by andronoob** [comment]
Currently, I have only one channel, which connects my node to Blockstream's `02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432`.
I wonder if this something by design (e.g. mitigate DoS attacks), or just something like untouched default configuration.

**Comment by andronoob** [comment]
@ZmnSCPxj It seems that if I pay much more than 150 sat, the fee rate will be below 0.5%, so that lightingd won't complain.

**Comment by cdecker** [comment]
@andronoob yep, that's one way to reduce the feerate, by increasing the amount transferred you can amortize the base fee each node asks for.

**Comment by cdecker** [comment]
Indeed each of the hops asks for a 1 satoshi fee to forward a payment:

```
{ "route" : 
	[ 
		{ "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "channel" : "509280:460:0", "msatoshi" : 3001, "delay" : 181 }, 
		{ "id" : "0397e4088b4c7e3e2bda8597e21f12b6affa2eae7145b0d68df405b9b2d394e29a", "channel" : "508388:1355:0", "msatoshi" : 2001, "delay" : 167 }, 
		{ "id" : "035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8", "channel" : "505148:223:0", "msatoshi" : 1001, "delay" : 153 }, 
		{ "id" : "03457d3e97da4e6a01739f56c0cd168cb14962b91fb44dc3d647816c70e05e9b93", "channel" : "509161:1124:1", "msatoshi" : 1, "delay" : 9 } ] }
```

**Comment by cdecker** [comment]
It seems this is resolved now? @andronoob can you close the issue?

**Comment by andronoob** [comment]
@cdecker Thanks a lot!
