### ISSUE TITLE
The first basic interoperable feature is missing 

### ISSUE THREAD

**Issue by molxyz** [ElementsProject/lightning#1022]
Hello Rusty,

May I ask you to change the first basic command to connect a c-lightning node to other nodes so that we can have the same thing to make our lives easier.  Here's the problem: 

`$ lightning-cli connect 02ca1f8792292fd2ad4001b578e962861cc1120f0140d050e87ce1d143f7179031@52.18.61.50:9735
{ "code" : -1, "message" : "id 02ca1f8792292fd2ad4001b578e962861cc1120f0140d050e87ce1d143f7179031@52.18.61.50:9735 not valid" }`

That would be valid with the other LN implementations. The target address is expected in format: `pubkey@host:port`, which is well known to most of us LN testers/users by now. I would appreciate it if you make this to be the same rule for c-lightning, which would make it less annoying for us the testers who want to help test c-lightning and help us all.  

Thank you.

**Comment by ZmnSCPxj** [comment]
Duplicates: #636
