### ISSUE TITLE
Option to disallow inbound channels

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#1025]
This would be useful for decommissioning a node gracefully. I don't want new nodes to connect to me while I'm waiting for `ONCHAIND_OUR_UNILATERAL`'s to finish. I suppose I could simply not set `--ipaddress` but that seems a bit of a hack.

**Comment by cdecker** [comment]
Great point. I usually set `--port=<something-random>` and `--dev-no-reconnect` when I want to isolate a node, but having a command line option would be nice.

**Comment by rustyrussell** [comment]
`--port=0` should do this, actually:

```
--port                         Port to bind to (0 means don't listen) (default: 9735)
```

Just tested, it works.

**Comment by Sjors** [comment]
--port=0 seems a good enough solution for me
