### ISSUE TITLE
Feature Request:  pay command offer solutions

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1040]
### Issue and Steps to Reproduce

I just tried to do a "pay" command, which gave me the error that it could not find a route.  It gave no diagnostics, such as whether or not the node or channel even exists, and whether or not there was a path of any value to it.  I'd like for pay to give diagnostics and an option to fix whatever needs to be fixed in order to make a payment happen.

### `getinfo` output
Three nodes gave the same error:
```
{ "id" : "031c527494f295220d26a1814c18e7db3f4f03203ce1a53a0b74b52ed570a3972a", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "24.4.228.213", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2017-g4fccbba", "blockheight" : 507976, "network" : "bitcoin" }
```

```
{ "id" : "03a3c1fc0a489e2872a2afe8fa16c2714b5fe80d52d8c1ce8ecc4361a77391da82", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "138.68.252.183", "port" : 9735 }, 
                { "type" : "ipv6", "address" : "2604:a880:2:d0::662:c001", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1926-gcb97dfe", "blockheight" : 509932, "network" : "bitcoin" }
```

testnet:
```
{ "id" : "036b98986cbf991d2fa41559b7baf35556d3f79adc43d236c6f9444404d96f38af", "port" : 19735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "24.4.228.213", "port" : 19735 } ], "version" : "v0.5.2-2016-11-21-1926-gcb97dfe", "blockheight" : 1283678, "network" : "testnet" }
```

**Comment by cdecker** [comment]
Not sure if there is anything besides "open more channels" that we can add at this point. @ZmnSCPxj has implemented the retry logic, which you seem to have included in your clients, so any failure to route a payment is final, and can only be fixed by waiting for more capacity or a topology change.

**Comment by Ulmo** [comment]
I like your initial idea:  open more channels.  I knew I was asking for that as one of the possible offered solutions.  It would be a flag, such as default say how to fix, option to say nothing but failure, and another option to just go ahead and fix it.

The other diagnostic I'd like is whether or not the node or channel I'm trying to pay even exists in this tree.  Since my node has a nodelist, it can at least look it up and tell me diagnostics about that.  Since I tried paying the invoice on two different chains (testnet and mainnet), obviously, at least one of the nodes failed to tell me that the destination didn't even exist.  I don't know if that's a function it can do in the future with more nodes.

**Comment by ZmnSCPxj** [comment]
If it does not exist, that will lead to a routing failure code 205.  "Exists" is somewhat difficult to judge --- if the node once had channels, but has all the channels closed it will still appear in routemaps.  Nodes will still "exist" on routemaps even if they are offline --- and we cannot really tell if the "offline" is permanent (the node will never come up again) or temporary (the owner is just saving electricity while sleeping).

This is edging towards moving to autopilot mode, which I have not begun to consider yet other than "maybe later".  Opening a new channel in autopilot requires some consideration, and probably statistics of who you commonly pay to...

And yes, "best" possible fix is to just open a new channel, so...

**Comment by darosior** [comment]
@Ulmo I think it can be closed ? :)

**Comment by Ulmo** [comment]
Since it's part of a bigger autopilot function (regardless of that function's existence), that seems reasonable.

Note that I haven't used it lately to know the current status.  (I'm waiting until MbS & Trump are done running down the enemies of humanity (terrorists and drug dealers) before I get back into crypto, since for now they're unsophisticated enough to not know how to counteract crypto-using enemies, and I'm not trying to work against them; after that, though, I totally want to revisit crypto and get back in it once our guys are at a better stage.)
