### ISSUE TITLE
Put node alias and other human readable things in listpeers

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1042]
### Issue and Steps to Reproduce

listnodes command gives the alias of the node, which is nice.  I recently was able to find out that a peer ID I was having trouble with is named VIOLENTROUTE, which we all know is a problematic peer.  However, when I saw it in listpeers, it didn't occur to me until later to look up its alias, and since its alias wasn't in listpeers, it didn't automatically alert me to that issue.

Also, it would just be nice to see aliases in listpeers.

Downside:  this could be an attack vector (it's easy to spoof an alias).  If we think it is a huge attack vector, exclude it.

### `getinfo` output
{ "id" : "031c527494f295220d26a1814c18e7db3f4f03203ce1a53a0b74b52ed570a3972a", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "24.4.228.213", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2017-g4fccbba", "blockheight" : 509937, "network" : "bitcoin" }

**Comment by jBarz** [comment]
I can have a go at this

**Comment by cdecker** [comment]
Sounds great @jBarz, go for it :-)

**Comment by jBarz** [comment]
Fix is merged in c870505

**Comment by jb55** [comment]
I was looking to add a PR for this feature and found this one...

It looks like this was added at one point, but I don't see alias in listpeers anymore?

**Comment by Ulmo** [comment]
It was nice while they had it, but remember, those aliases can be chosen by anyone; there's no confirmation that the one you see in your list is the one you want.  I think that's why they want you to use the numeric identifications.

**Comment by JavierRSobrino** [comment]
Please don't overprotect programmers by removing aliases from the `listpeers`. Everybody programming this should already know that aliases can be freely chosen and repeated. But this information is very useful to inform the users about, and simplify many things.
