### ISSUE TITLE
Crash due to null-pointer in log

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1043]
### Issue and Steps to Reproduce

[fatal.txt](https://github.com/ElementsProject/lightning/files/1737210/fatal.txt)

### `getinfo` output
{ "id" : "031c527494f295220d26a1814c18e7db3f4f03203ce1a53a0b74b52ed570a3972a", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "24.4.228.213", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2017-g4fccbba", "blockheight" : 509947, "network" : "bitcoin" }

**Comment by rustyrussell** [comment]
Weird, I can't reproduce this, even stressing the pruning logic.

Is there anything in crash.log?
