### ISSUE TITLE
Payment forwarding statistics

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#1049]
It may be useful for some applications ("hubs", cough) to know if a channel is getting used or not for forwarding.

So I propose, that we add statistics on each channel, to indicate the number of attempted and successful forwarding attempts ("success" being if an HTLC-out is resolved, and the HTLC-out is not a payment from us, and "attempt" being an HTLC-out being created in the first place, and the HTLC-out is not a payment from us).

For instance, a hubbing service might want to close a channel that is tying up much of its funds if that channel is not very active (i.e. few users).

I propose that `listpeers` should include, for each channel, a `attempted_forwards` and `succeeded_forwards`.

**Comment by rustyrussell** [comment]
"ZmnSCPxj, ZmnSCPxj jxPCSmnZ" <notifications@github.com> writes:
> It may be useful for some applications ("hubs", cough) to know if a channel is getting used or not for forwarding.
>
> So I propose, that we add statistics on each channel, to indicate the number of attempted and successful forwarding attempts ("success" being if an HTLC-out is resolved, and the HTLC-out is not a payment from us, and "attempt" being an HTLC-out being created in the first place, and the HTLC-out is not a payment from us).
>
> For instance, a hubbing service might want to close a channel that is tying up much of its funds if that channel is not very active (i.e. few users).
>
> I propose that `listpeers` should include, for each channel, a `attempted_forwards` and `succeeded_forwards`.

Perhaps we want stats in both directions?  Say 'total_htlcs',
'total_amount', 'htlcs_fulfilled', 'amount_fulfilled' for in and out?

But I haven't thought about how hard that would be to wire up...

**Comment by cdecker** [comment]
Should be trivial to wire up, except if we want to persist across restarts, at which point we'd need to stuff that into the DB as well.

**Comment by ZmnSCPxj** [comment]
`in_forwards_total`, `in_forwardfees_total`, `in_forwards_fulfilled`, `in_forwardfees_fulfilled`, `out_forwards_total`, `out_forwardfees_total`, `out_forwards_fulfilled`, `out_forwardfees_fulfilled`?

Well maybe we can `s/forwards/somethingelse/` and `s/forwardfees/somethingelse/`, but perhaps the general pattern `in/out_whatever_total/fulfilled`?

**Comment by ZmnSCPxj** [comment]
Hmm, not so much forwarding perhaps: we would want to know how useful a channel is for incoming payments terminating to our own node, and outgoing payments sourced from our own node.

So: `in/out` `payments/amount` `attempted/fulfilled`.
