### ISSUE TITLE
broken macOS compilation

### ISSUE THREAD

**Issue by isghe** [ElementsProject/lightning#1059]
commit [bd95aba7a5f9bad8f447bf3de8f7e8cfe83751af](https://github.com/ElementsProject/lightning/commit/bd95aba7a5f9bad8f447bf3de8f7e8cfe83751af) brakes `macOS` compilation, resulting in:

```
if ccan/tools/configurator/configurator cc -static > ccan/config.h.new; then mv ccan/config.h.new ccan/config.h; else rm ccan/config.h.new; exit 1; fi
ccan/tools/configurator/configurator: Test for HAVE_BIG_ENDIAN did not compile:
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

To reproduce `make clean` then `make`.

**Comment by Sjors** [comment]
I'm seeing the same issue. Doing a `git revert` makes it go away.
