### ISSUE TITLE
Payment stuck with "lightning_channeld died / received ERROR channel ALL: Internal error"

### ISSUE THREAD

**Issue by realart** [ElementsProject/lightning#1065]
I funded 2 channels and when I tried to pay to Blockstream store my payment operation got stuck indefinitely until I Ctr+C'ed it. I am confused about what to do next?

```
2018-02-21T22:03:11.339Z lightningd(1810): Server started with public key 0241f5216abc3c804261e7347dd4228c3b885d3dc29970083f2ddfe6d1607c3023, alias LATVIA (color #77353d) and lightningd v0.5.2-2016-11-21-2040-g3dbace3
2018-02-21T22:22:43.559Z lightningd(1810): 035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8 chan #2: Opening channel: received ERROR channel 5848a4db92d3cc99bf974d6d024263f8c64dc32f1c27acff71408c4a1b73df4e: Unacceptable channel constraints: minimum HTLC value is too large: 0
2018-02-21T22:26:22.622Z lightningd(1810): lightning_openingd-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 chan #3: Peer connection lost
2018-02-21T22:26:22.623Z lightningd(1810): 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 chan #3: Owning subdaemon lightning_openingd died (62208)
2018-02-21T22:27:06.466Z lightningd(1810): lightning_openingd-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 chan #4: Peer connection lost
2018-02-21T22:27:06.466Z lightningd(1810): 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 chan #4: Owning subdaemon lightning_openingd died (62208)
2018-02-21T22:28:22.814Z lightningd(1810): lightning_openingd-02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 chan #5: Peer connection lost
2018-02-21T22:28:22.814Z lightningd(1810): 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 chan #5: Owning subdaemon lightning_openingd died (62208)
2018-02-21T22:31:48.669Z lightningd(1810):jcon fd 0: Abandoning command
2018-02-21T22:52:24.392Z lightningd(1810): Command failed after jcon close
2018-02-21T23:04:03.384Z lightningd(1810): 03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1 chan #1: State changed from CHANNELD_AWAITING_LOCKIN to CHANNELD_NORMAL
2018-02-21T23:07:45.878Z lightningd(1810): 0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 chan #6: State changed from CHANNELD_AWAITING_LOCKIN to CHANNELD_NORMAL
2018-02-21T23:20:10.045Z lightningd(1810): Sending 66667289 over 2 hops to deliver 66667222
2018-02-21T23:20:10.117Z lightningd(1810): Sending 66669021 over 4 hops to deliver 66667222
2018-02-21T23:20:10.616Z lightningd(1810): lightning_channeld-0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 chan #6: Peer connection lost
2018-02-21T23:20:10.616Z lightningd(1810): 0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 chan #6: Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (62208)
2018-02-21T23:20:10.807Z lightningd(1810): 0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 chan #6: Peer permanent failure in CHANNELD_NORMAL: lightning_channeld: received ERROR channel ALL: Internal error
2018-02-21T23:20:10.807Z lightningd(1810):       (tx 8663d74b6e98ef405ad2ad9ed3f1824eb6a358985a21b96b7b5047af91b52674)
2018-02-21T23:23:13.725Z lightningd(1810): 0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 chan #6: Peer permanent failure in CHANNELD_NORMAL: Funding transaction spent
2018-02-21T23:23:13.725Z lightningd(1810):       (tx 8663d74b6e98ef405ad2ad9ed3f1824eb6a358985a21b96b7b5047af91b52674)
2018-02-21T23:23:13.737Z lightningd(1810): 0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 chan #6: State changed from CHANNELD_NORMAL to FUNDING_SPEND_SEEN
2018-02-21T23:23:14.120Z lightningd(1810): 0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 chan #6: State changed from FUNDING_SPEND_SEEN to ONCHAIND_OUR_UNILATERAL
2018-02-21T23:25:09.313Z lightningd(1810):jcon fd 0: Abandoning command

```

This is listpeers:

```
{ "peers" :
        [
                { "id" : "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1", "connected" : true, "netaddr" :
                        [ "45.55.47.17:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "510308:736:0", "funding_txid" : "f7b8fb121511965f97b104a152c45f089abc7cbf2b047d777801140dd25485ea", "msatoshi_to_us" : 11000000, "msatoshi_total" : 11000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },
                { "id" : "0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917", "connected" : false, "channels" :
                        [
                                { "state" : "ONCHAIND_OUR_UNILATERAL", "owner" : "lightning_onchaind", "short_channel_id" : "510310:1454:1", "funding_txid" : "8c6daf93b164561f14f549f63a35388307d89b87fcbf21d16eede2497084a7f3", "msatoshi_to_us" : 110000000, "msatoshi_total" : 110000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },
                { "state" : "GOSSIPING", "id" : "035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8", "netaddr" :
                        [ "78.63.23.25:9735" ], "connected" : true, "owner" : "lightning_gossipd" } ] }
```

**Comment by ZmnSCPxj** [comment]
It looks like the connection was lost just after `pay` command dispatched to the peer `0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917`.  lightningd got paranoid and force-closed the channel with that peer (which is why it become `ONCHAIND_OUR_UNILATERAL`).

However, the channel state is strange to me... the channel with `0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917` has `"msatoshi_to_us": 110000000`, which is the same as the total amount on the channel, meaning it has not sent the payment (or that the payment was forwarded but was rejected before the channel was closed).  If we had forwarded the payment, then it was rejected, we should have received a message and `pay` would have either retried a different route or given up and returned an error to you.  @rustyrussell may be more helpful about how the payment sending works at the channel level...

**Comment by cdecker** [comment]
Yes, I think the connection was lost right after the payment was initiated, which caused your node to drop to chain. Transaction [8663d74b6e98ef405ad2ad9ed3f1824eb6a358985a21b96b7b5047af91b52674](https://www.smartbit.com.au/tx/8663d74b6e98ef405ad2ad9ed3f1824eb6a358985a21b96b7b5047af91b52674) closed the channel. It has two P2SH outputs, so the HTLC was registered in the channel, and not cleared. You will have to wait for 144 confirmations, then your node will automatically claim the our_unilateral/to_us output, and then some more blocks for the HTLC to be claimed as well. So in a bit over 12 hours you'll get all of your funds (minus on-chain fees) back.

@ZmnSCPxj iirc the balance is only updated for settled HTLCs not for in-flight HTLCs.

**Comment by ZmnSCPxj** [comment]
Payment timeouts could take longer. We should probably store in the db and log the total CLTV of a payment, as that is the maximum blockheight that a payment can take to resolve in the worst case that the direct peer dies/disconnects after it forwards.  Also maybe add a maximum CLTV delta.

The second output of https://www.smartbit.com.au/tx/8663d74b6e98ef405ad2ad9ed3f1824eb6a358985a21b96b7b5047af91b52674 is the payment you sent.  It ***will*** get refunded, but it is currently timelocked... not sure what you can query to check its status though.

**Comment by cdecker** [comment]
When starting with `--log-level=debug` `onchaind` should actually tell you how many blocks until it'll do something.

**Comment by realart** [comment]
Here is the relevant line:

`2018-02-23T19:20:01.212Z lightningd(16361): lightning_onchaind-0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 chan #6: Propose handling OUR_UNILATERAL/OUR_HTLC by OUR_HTLC_TIMEOUT_TX (020000000001017426b591af47507b6bb9215a9858a3b64e82f1d39eadd25a40ef986e4bd76386010000000000000000018b030100000000002200209bdd15b6cafdad3c98eb1b323936f1d4cb1d121ccb006a042b31f90c84cdb7b3050047304402206061a5a760efb9517d21b8315a2015c3bb098e4a59575f13d1aa0cd678a04e5f022057e35e330f807c19720319448adac9cc061308abcba66b0490d4b5fcd6b9e9be01483045022100e52dbd6dc4f1eb726223bb84b75a392f87543bf665efb91028ebd20ea063d974022060f9ea2ded6fe5b82f5c5600efc37ec522833b54fc1d16e9cda4a76dee1a8b5801008576a914bed8baaef303cf7f3daa4c136b6a28e8130594b68763ac6721021986aa9a122947813fd08ecde147ed3887e60f497f2ccd4815214bbc7c83228b7c820120876475527c2102dfe7f1f4c92ae30f8348ea02ca740f7a16c6a425427c8905b86ac200b5bb953d52ae67a914da9026d248ce09bdaee26d267527a8b231fe161588ac6868a0ca0700) in 310 blocks`

Two dumb questions:

1) Why are these "timeouts" so long (144 and 310 blocks)?
2) Can I "add" funds to one of my existing channels or do I have to fund a new channel if I want to add these funds back into circulation?

I will try the purchase again tomorrow.

**Comment by cdecker** [comment]
Whoa, 310 blocks is really huge, that must have been a strange route. The timeouts currently are a bit on the defensive side, and can be tweaked later if we see the parameters are overly cautious.

Re: adding funds back: the channel is currently closing, once it is closed you'll have the funds back in your internal wallet (which you can see with `listfunds`), at which point you can open a new channel with them. In the meantime you can open another channel with other funds if you have some.

**Comment by cdecker** [comment]
@realart I just saw your HTLC output move, so it seems this is slowly moving forward :-) Once `454d4d156c08f32ec0baccae2867bd294d188f946de6ba59dc0363c48db0ddac` confirms it'll be re-spent one final time to one of the internal wallet's addresses, and you should have your funds back :smiley:

**Comment by realart** [comment]
I tried again after money returned. Funded a different channel, tried "pay", but operation got stuck like last time and I had to abort with CTR+C. Payment (013d7d934e78f9efcfec31f47077124853a858df1138caca0dac818dbf798678) is in "pending" state for 2 days, but this time, unlike last time, "listpeers" shows this channel in status "CHANNELD_NORMAL", not "ONCHAIND_OUR_UNILATERAL".

```
{

 "peers" :
        [
                { "id" : "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1", "connected" : false, "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "short_channel_id" : "510308:736:0", "funding_txid" : "f7b8fb121511965f97b104a152c45f089abc7cbf2b047d777801140dd25485ea", "msatoshi_to_us" : 11000000, "msatoshi_total" : 11000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
                                        [ "CHANNELD_NORMAL:Reconnected, and reestablished." ] } ] },
                { "id" : "03f8d1ae8e36d19ed96fefa02f6f6c33fe69ed2fff5ece582b013a92c9077ee396", "connected" : true, "netaddr" :
                        [ "159.89.127.22:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "510855:1485:1", "funding_txid" : "30e1473ac9918660c6354a606ddb9f21551f1944c03521dfab6d6f1bac22fddc", "msatoshi_to_us" : 120000000, "msatoshi_total" : 120000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
                                        [ "CHANNELD_NORMAL:Reconnected, and reestablished.", "CHANNELD_NORMAL:Funding transaction locked. They need our announcement signatures." ] } ] } ] }
```

This is "listpayments". My previous attempt is now appropriately in "failed" state.

```
{ "payments" :
        [
                { "id" : 1, "payment_hash" : "3b27357d6ecc32c8d655add8ab49996391791696d01512ef43dc1087dd1dddb9", "destination" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "msatoshi" : 66667222, "timestamp" : 1519255210, "created_at" : 1519255210, "status" : "failed" },
                { "id" : 2, "payment_hash" : "013d7d934e78f9efcfec31f47077124853a858df1138caca0dac818dbf798678", "destination" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "msatoshi" : 94324270, "timestamp" : 1519568850, "created_at" : 1519568850, "status" : "pending" } ] }
```

"listfunds":

```
{ "outputs" :
        [
                { "txid" : "866db8bc78256f159e25cfd523d8479691966c58b5f3ee2340f7400c2fd43545", "output" : 0, "value" : 65333 },
                { "txid" : "30e1473ac9918660c6354a606ddb9f21551f1944c03521dfab6d6f1bac22fddc", "output" : 0, "value" : 1039 } ], "channels" :
        [
                { "peer_id" : "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1", "short_channel_id" : "510308:736:0", "channel_sat" : 11000, "channel_total_sat" : 11000, "funding_txid" : "f7b8fb121511965f97b104a152c45f089abc7cbf2b047d777801140dd25485ea" },
                { "peer_id" : "03f8d1ae8e36d19ed96fefa02f6f6c33fe69ed2fff5ece582b013a92c9077ee396", "short_channel_id" : "510855:1485:1", "channel_sat" : 120000, "channel_total_sat" : 120000, "funding_txid" : "30e1473ac9918660c6354a606ddb9f21551f1944c03521dfab6d6f1bac22fddc" } ] }
```

Log file: http://f.zelcs.com/lightninglog.txt

**Comment by realart** [comment]
Update: status for my second failed payment changed to "failed" after ~3 days. I tried another time, with the same channel and funding. It returned "could not find route", despite "getroute" showing a route.

I executed the same pay command again and it worked! So finally I get my first Lightning payment!

The log for last attempt: http://f.zelcs.com/lightningsuccesslog.txt

I did recompile to latest commit between now and since my first attempts. Maybe something that was causing "pay" to get stuck is now fixed...

**Comment by ZmnSCPxj** [comment]
Or it could be network state also --- `getroute` does not know if the returned route will actually successfully push through (some channel along the way may have depleted in the direction you wanted to use it in), while `pay` learns about such temporary channel errors and routes around them.  Then when you retried, the temporary error had cleared up (it *is* a temporary error) and it could succeed.

**Comment by cdecker** [comment]
It's rather unfortunate, but we won't be able to make `getroute` more reliable, since it can't actively probe the channel state, but we can make sure that what we think the state of the network is more consistent. I think the `channel_update` injection into `gossipd` that @ZmnSCPxj already uses the same entrypoint as normal messages, so they'd be included in the normal gossip updates, and should inform the rest of the network about any issue. The problem now is that too few nodes actually do this, so we end up with inconsistencies that make `getroute` unreliable and `pay` slow, due to many broken channels that we don't know about. This'll get better as users upgrade their clients :wink: 

@realart shall we close this issue?

**Comment by realart** [comment]
@cdecker Yes, close.
