### ISSUE TITLE
Double-check chain from bitcoin-cli

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#1074]
Related to: #678 

We should abort early if our net settings do not match the result of `bitcoin-cli getblockchaininfo` . https://bitcoin.org/en/developer-reference#getblockchaininfo

We should check if the resulting `chain` is `"main"` for mainnet, `"test"` for testnet, `"regtest"` for regtest.

**Comment by practicalswift** [comment]
As part of that self-test we could perhaps also add a more user-friendly error message on how to setup `bitcoind` in a way that makes `c-lightning` happy in the case that the `bitcoin-cli` communication fails.

**Comment by cdecker** [comment]
Wasn't this solved with #1019?

**Comment by ZmnSCPxj** [comment]
Perhaps not quite? I believe #1019 checks if the `lightningd` is configured with the same network as its db. This is intended to check if the `lightningd` is configured with the same network as the `bitcoind` it is talking to.

**Comment by cdecker** [comment]
Oh, I see, that makes sense :+1: Leaving this open for now.
