### ISSUE TITLE
Setting alias in config file not changing alias

### ISSUE THREAD

**Issue by ZMeridianZ** [ElementsProject/lightning#1079]
My .lightning is located in my overlay2 folder, which seems strange, but when I create a config file as the docs say to do - "To use a configuration file, create a file named "config" within your ".lightning" directory. Usually this will be ~/.lightning/config" - my alias doesn't change according to what I've set in config.

**Comment by cdecker** [comment]
Sorry, I'm not following, what's an "overlay2" folder? I just checked and if there is a `$HOME/.lightning/config` file with the following content:

```
alias=happyhippo
```

then the alias is changed as expected.

**Comment by ZMeridianZ** [comment]
It's a storage driver for docker, and where I was able to find .lightning/. But I guess that's the issue. I don't have a .lightning folder in my $HOME.

Also, are we able to expose our node's URI using a setting in the config file or must that be done via the command line?

**Comment by cdecker** [comment]
Oh I see, you're running from the docker image. I'd strongly suggest doing the following:

```
docker run -v $HOME/.lightning:/root/.lightning ...
```

since otherwise your private key and DB would also be wiped whenever you wipe the container (to update for example). The config file is only loaded upon startup, so changing it while running will not have any effect. Were you trying to `docker start` an existing container?

**Comment by ZMeridianZ** [comment]
Ah I see. No I created a new one from the image provided by dougvk in his medium guide.

**Comment by cdecker** [comment]
That's the image I created yes :-)

So is this solved?

**Comment by ZMeridianZ** [comment]
Yes, thanks very much for the help

**Comment by cdecker** [comment]
No problem, glad we figured it out :wink:
