### ISSUE TITLE
Error in `lightningd': double free or corruption (out) 

### ISSUE THREAD

**Issue by FeedTheWeb** [ElementsProject/lightning#1105]
Lightningd crashed. 
log, and crash.log : https://dpaste.de/KLvX

Node had 1 channel in state CHANNELD_AWAITING_LOCKIN for some days. 
Crash happened some time after the other side of the channel closed using 'dev-fail' (not sure if related #968 )

**Comment by cdecker** [comment]
@rustyrussel could this be related to the `bcli` retry logic?

**Comment by rustyrussell** [comment]
@cdecker No, because judging from the line numbers in the backtrace, this predates that change.

@FeedTheWeb Is there a crash.log file in `~/.lightning/crash.log` ? Looks like there should be, and it might contain clues as to what it was doing when we failed.

**Comment by FeedTheWeb** [comment]
crash.log is at the end of that link ^^  https://dpaste.de/KLvX
