### ISSUE TITLE
JSON RPC hangs on special characters

### ISSUE THREAD

**Issue by bitonic-cjp** [ElementsProject/lightning#1108]
### Issue and Steps to Reproduce
I discovered that adding a newline to a command argument value in the Python RPC interface makes it hang. I first discovered this on the bolt11 argument of the decodepay command (not very important - it's not supposed to contain a newline), but it seems to be the case for all arguments of all commands. I tested the description argument of the invoice command, and the problem appears there too. This is a bigger issue: in my view, descriptions are likely to contain newline characters.

Looking at the logging, the Python RPC client says:

> 2018-02-26 15:36:06,958 DEBUG: Calling decodepay with payload {'description': None, 'bolt11': '\n'}

Note: it does not log anything about return data; apparently it hangs, waiting for a reply.
Meanwhile, lightningd logs:

> 2018-02-26T14:36:06.958Z lightningd(3239): Invalid token in json input: '{"method": "decodepay", "params": {"bolt11": "\n"}, "id": 0}'

Note that, while the RPC client hangs, lightningd does not hang.

Looking at the code, it seems the Python client side correctly escapes special characters, turning a newline into \n. I think lightningd rejects special characters because of the code added in commit 5502a19d1ecf7517535d995ccbc95d201e67d318. This includes the backspace added by the escaped newline character.

Instead of directly making a bug fix, I'd like to discuss what the desired behavior should be. Following BOLT-11, any valid UTF-8 string should be a valid description, right? On the RPC-level, it may be required to escape certain characters to turn any UTF-8 string into a JSON-encoded string. The Python-RPC client side already does this - I think the lightningd server side should also support it.

Is this the desired behavior for all command arguments?

### `getinfo`  output
getinfo
{ 'address': [],
  'blockheight': 1286431,
  'id': '03f3b0a454583f712318a0c9023423b3093ce534dff288907107b3ec337ccda10f',
  'network': 'testnet',
  'port': 9700,
  'version': 'v0.5.2-2016-11-21-2014-g46534935'}

**Comment by ZmnSCPxj** [comment]
Duplicates: #607 

Duplicates: #387
