### ISSUE TITLE
lightningd not listen on ipv4 only ipv6

### ISSUE THREAD

**Issue by dru0** [ElementsProject/lightning#1115]
System Ubuntu 16.04.3 LTS
lightningd not listen on ipv4 only ipv6
adding --ipaddr=192.168.1.100 to daemon nothing change
ipaddr/ip in config do the same

netstat -ln|grep 9735
tcp6       0      0 :::9735                :::*                    LISTEN

.lightning/config
alias=.....
rgb=d08000
port=9735
network=bitcoin
ipaddr=192.168.1.100

getinfo output
port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "192.168.1.100", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2126-gb7ed567", "blockheight" : 511097, "network" : "bitcoin" }

**Comment by cdecker** [comment]
@dru0 the `--ipaddr` parameter only informs `lightningd` which IP to report to the outside world, not which IPs to bind to. `lightningd` does bind to both IPv4 and IPv6, but `netstat` reports them as one entry only.

Try `telnet 127.0.0.1 9735` and it should be able to open a connection over the IPv4 loopback interface.

**Comment by dru0** [comment]
Ok, this work, i just dont see node in https://lnmainnet.gaben.win/ but this could be something else.

**Comment by cdecker** [comment]
For it to show up there you'll need to open a channel and wait for 6 confirmations. We do not allow nodes without channels be announced in the network in order to prevent spam.
