### ISSUE TITLE
CHANNELD_AWAITING_LOCKIN Problem

### ISSUE THREAD

**Issue by ozguruzden** [ElementsProject/lightning#1119]
### Issue and Steps to Reproduce

Hello everyone,
I know there is same problem of different people is written in here a lot of times but still I could not solve my problem so that is why I am asking again.

My node does not connect to other node. When I hit the lightning-cli listpeers, output like this;

> 
> { "peers" :
>         [
>                 { "id" : "02ee1050616916748f4a21e0a9bc658da1d68a35c8344c051f3949894ceb9d0cfc", "connected" : false, "channels" :
>                         [
>                                 { "state" : "CHANNELD_AWAITING_LOCKIN", "short_channel_id" : "509659:1307:1", "funding_txid" : "015cdf3b8c3d224f53ba51c3196a2434a28993dfac6f8c7481c47bb0f11b3bfb", "msatoshi_to_us" : 0, "msatoshi_total" : 200000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }
> 

I tried to close channel with this command and I got this output: 

> lightning-cli close 02ee1050616916748f4a21e0a9bc658da1d68a35c8344c051f3949894ceb9d0cfc
> { "code" : -1, "message" : "Peer is in state ONCHAIND_OUR_UNILATERAL" }

What I am trying to do is, close channel, get my fund back and create another channel by funding another node. But I am stucked.

I will really appreciate your help as I am not very experienced about this issue,

**Comment by ozguruzden** [comment]
Since I checked in 2 minutes my output changed now

> root@ip-172-31-30-192:~# lightning-cli listpeers
> { "peers" :
>         [
>                 { "id" : "02ee1050616916748f4a21e0a9bc658da1d68a35c8344c051f3949894ceb9d0cfc", "connected" : false, "channels" :
>                         [
>                                 { "state" : "ONCHAIND_OUR_UNILATERAL", "owner" : "lightning_onchaind", "short_channel_id" : "509659:1307:1", "funding_txid" : "015cdf3b8c3d224f53ba51c3196a2434a28993dfac6f8c7481c47bb0f11b3bfb", "msatoshi_to_us" : 0, "msatoshi_total" : 200000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }

Am I doing something wrong?

**Comment by ZmnSCPxj** [comment]
The other side `02ee1050616916748f4a21e0a9bc658da1d68a35c8344c051f3949894ceb9d0cfc` is not responding properly, which is why it is in `AWAITING_LOCKIN` mode: the other side is not yet confirmed that it has seen lockin.  C-lightning gave up because the other side is not responding and did a unilateral close `ONCHAIND_OUR_UNILATERAL`.  By the time you did the `close` it was already closed by c-lightning due to other side inactivity, hence the `Peer is in state ONCHAIND_OUR_UNILATERAL`.

For our-side unilateral closes, you need to wait for 144 blocks to reclaim your funds.

**Comment by ozguruzden** [comment]
Ah thank you very much. As ı see, I did something correct without awareness :)
Now, peer connection closed as you said. And I am waiting for my funds back - 144 blocks.

Thank you again

**Comment by ZmnSCPxj** [comment]
Well, better monitor it for 144 blocks; we have had problems with this some time ago. They should be fixed now, but keep an eye out.  They should appear, after 144 blocks, in `listfunds` as a new onchain UTXO.

**Comment by ozguruzden** [comment]
Dear @ZmnSCPxj , thank you for your answer and info.

As I see - if I am not wrong - 144blocks should be already passed and my fund is not appear yet.

> root@ip-172-31-30-192:~# lightning-cli listfunds
> { "outputs" :
>         [
>                 { "txid" : "852e197e14b362f6f74210f900d51969b7c733690d4c7610a9bfc418b76bf856", "output" : 0, "value" : 2568 },
>                 { "txid" : "d5493b68b1b36f99c1c6b822ccab44dffdad9232675b7659a72ed3b8c6c07209", "output" : 1, "value" : 137189 } ] }
> 

Are there any solution or something to do on my side? Or do I have to wait some more time?

**Comment by cdecker** [comment]
Did you perform a payment over the channel, for say 0.00199426 BTC?

The channel was closed on-chain via a unilateral close transaction [fe0d45668aaeeb3a145c702095556ab5c0e13fb54581d834ef1ad310b1fd7bbc](https://blockchain.info/tx/fe0d45668aaeeb3a145c702095556ab5c0e13fb54581d834ef1ad310b1fd7bbc), but it had only a single output, that was a P2WKH. If you had any remaining balance in the channel it would have created a second P2WSH output, but it not being created indicates that the close transaction creator didn't have a balance in the channel.

Now this could either be your close transaction, in which case the remaining 0.00000574 BTC  went to on-chain fees, or it could be the other side's close transaction which should result in you getting a new output added to `listfunds`.

**Comment by mocmocamoc** [comment]
All of the outputs above show msatoshi_to_us as zero so I don't think you should expect any funds back...

**Comment by cdecker** [comment]
Good catch @mocmocamoc seems the other side opened the channel and we decided to close, so yeah, no funds incoming I guess.

**Comment by ozguruzden** [comment]
I am really confused, sorry.
I funded 200000000 msatoshi to open channel then I close this channel but I lost my fund in this case, is this correct?

Thank you for your patience.

**Comment by ZmnSCPxj** [comment]
> `"msatoshi_to_us" : 0, `

This indicates the other side opened the channel, not you.

**Comment by ozguruzden** [comment]
Okay I understand this @ZmnSCPxj, but I funded sleepyark to 200000000 msatoshi and sometime later I had problem with channel and I lost connection that is why I closed channel. 

I am trying to understand that, what happened to my funds to use open channel. :(

**Comment by ZmnSCPxj** [comment]
Well, that is strange.  If you funded it, normally `msatoshi_to_us` would equal `msatoshi_total`.  The alternative is that you did a `push_msat`, but that is not yet implemented (I think...?).  The channel got closed while still in awaiting-lockin so no transfer could have been possible (and non-`push_msat` transfers would not let either side have an `msatoshi_to_us` of 0).

**Comment by ozguruzden** [comment]
I used lightning-cli fundchannel command to fund channel.
Everything works perfect some time then I lost sync with bitcoin network and started bitcoind again. After it is syncronised, I started lightning then it never connected to node or channel again, stucked in awaiting-locking. Then I closed channel and I lost some of my funds. 

This is strange for me too and I am not sure if this is my mistake or something to fix this by dev team.

**Comment by cdecker** [comment]
The node you were connected (node_id: 02ee1050616916748f4a21e0a9bc658da1d68a35c8344c051f3949894ceb9d0cfc) to is not SLEEPYARK (node_id: 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432), are you sure you are not mixing two different tests here?

**Comment by ozguruzden** [comment]
Dear @cdecker ,
Yes I am very sure, I connected to Sleepyark and my node was on the mainnet node map to connected. I am also aware and confused of node id's. 

After everything works perfect for a while, I needed to restart node, bitcoind and lightning. It took some time to sync bitcoin. I checked with listpeers and CHANNELD_AWAITING_LOCKIN problem occured for 2 or 3 days. Then I come here. 

I have all my test records and I checked again, my command and funding to sleepyark but then node id was different.

**Comment by cdecker** [comment]
@ozguruzden sorry to hear, let's try anyway to recover. Let's see if we can figure out if the withdrawal transaction made it into the network, what's the output of:
```
sqlite3 ~/.lightning/lightningd.sqlite3 "SELECT hex(prev_out_tx), prev_out_index, status FROM outputs"
```
That should tell us what outputs you have/had and what their current state is. From there we can check if they have been marked as spent and look on-chain for the spending transactions. If the withdrawal transaction did not make it to the network we can just use `dev-rescan-outputs` to reset their state and try again.

**Comment by ozguruzden** [comment]
I appreciate your help @cdecker , thank you. Here is the output.

```
root@ip-172-31-30-192:~# sqlite3 /scratch/bitcoin/mainnet/clightning/lightningd.sqlite3 "SELECT hex(prev_out_tx), prev_out_index, status FROM outputs"
3831A2D2F63082571DA69594C6292593FC4BF70677D7B7DCDFB47F9AEBD31D1A|15|2
56F86BB718C4BFA910764C0D6933C7B76919D500F91042F7F662B3147E192E85|0|1
0972C0C6B8D32EA759765B673292ADFDDF44ABCC22B8C6C1996FB3B1683B49D5|1|1
```

**Comment by cdecker** [comment]
The two lines with `status=1` are just marked as reserved, you should be able to unreserve them using `dev-rescan-outputs` and then do another `withdraw`. That should get you your funds back.

**Comment by ozguruzden** [comment]
@cdecker I think I am doing something wrong again;

```
root@ip-172-31-30-192:~# lightning-cli dev-rescan-outputs
{ "code" : -1, "message" : "Unknown command 'dev-rescan-outputs'" }
```

**Comment by cdecker** [comment]
Just checked your version, it predates the introduction of that rpc call. Updating to `master` and recompiling should help :-)

**Comment by ozguruzden** [comment]
@cdecker Okay, I will do my best in order to not waste your help and kind assistance but I need more help =) 
I built with docker but I don't know how to update to master and recompile :/

I looked around but I could not find guide for update with docker - maybe I missed.

**Comment by cdecker** [comment]
I assume you are using the `cdecker/lightning:latest` image? In that case the following is sufficient:

```
docker pull cdecker/lightning:latest
```
and then restart the daemon.

**Comment by ozguruzden** [comment]
Actually I was using c

> decker/lightningd:master

Then I am going with  docker pull cdecker/lightning:master

**Comment by ozguruzden** [comment]
@cdecker :(

> root@ip-172-31-30-192:~# docker pull cdecker/lightning:master
> Error response from daemon: manifest for cdecker/lightning:master not found

**Comment by cdecker** [comment]
Yep, I removed the redundant image, you can just switch out `:master` with `:latest` when starting the docker container and it should work. Could you share the command line used to start the container, if not?

**Comment by ozguruzden** [comment]
@cdecker 
Thank you all of you guys, it was small amount but this Q&A topic was very useful for me to understand many things.

I really appreciated your help!
