### ISSUE TITLE
payments only possible in 1 direction when there's just 1 channel

### ISSUE THREAD

**Issue by FeedTheWeb** [ElementsProject/lightning#1124]
### Issue and Steps to Reproduce
I have 2 nodes, **A** and **B**  , they have a direct connection/channel .
Node **A** has funded that side of the channel, and is able to pay invoices from **B** (yay!).
Now **B** has some balance and should be able to pay invoices coming from **A**,
however it fails with message 

> { "code" : 205, "message" : "Could not find a route" }

but there must be a route, because earlier **A** already paid **B**, right? 

Node **B** _getroute_  shows it is able to find a route :
`{ "id" : "03ec6c583cd7cadd7c03ecba4042ee4cca35d4f56cae49c2fd7abf71380ba04043", "channel" : "1286463:137:0", "msatoshi" : 10000, "delay" : 9 } ] }`

_note1:_
This is only when there are no other channels.
It is able to find a route (and pay) when both  have _another_ channel to a 3rd  node ('endurance').

_note2:_
Only node **B** has a public IP

**B:**
```
"channels": [
        {
          "state": "CHANNELD_NORMAL",
          "owner": "lightning_channeld",
          "short_channel_id": "1286463:137:0",
          "funding_txid": "753f9a4ffdf66a1f7f28d1f0cc64b023e97838090b569aac798ea2cfcc0ce514",
          "msatoshi_to_us": 2713265,
          "msatoshi_total": 1000000000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709552000,
          "channel_reserve_satoshis": 0,
          "htlc_minimum_msat": 0,
          "to_self_delay": 2,
          "max_accepted_htlcs": 483,
          "status": [
            "CHANNELD_NORMAL:Reconnected, and reestablished.",
            "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
          ]
        }
      ]
    },
```

**Comment by ZmnSCPxj** [comment]
How much is B paying A?  There is also a "reserve" required, and while B can start with their share below the reserve, B cannot pay if its share is below that reserve, and it cannot pay more than `share - reserve` if its share is above the reserve.

If B has not sufficient capacity, `pay` will temporarily disable low-capacity channels it finds for 20 seconds.  This will lead the route-finder to not find a route it can use, which is correct if you are paying more than the share of B minus the required reserve.

**Comment by FeedTheWeb** [comment]
@ZmnSCPxj  no amount works. I tried many invoices, with different amounts. 
Once an extra channel is created to some other node, suddenly the _same invoice_ is payable  .

**Comment by ZmnSCPxj** [comment]
Hmm, looks like we need the logs then.  Can you try `lightning-cli getlog debug`?

You could also be within 20 seconds of when `pay` banned that channel.

**Comment by FeedTheWeb** [comment]
all node **B** reports is:

> $ lightning-cli pay  lntb10n1pdfv7h9pp5eqf53rqrtxu3svln6.... 
> { "code" : 205, "message" : "Could not find a route" }
> 

>lightningd(18115): Sending 1000 over 1 hops to deliver 1000
>
and  of course, **A** reports nothing since it doesn't know about the attempted transaction

(btw, isnt that a off-by-one error? I think it should say 0 hops, since there are  no other nodes in between )

**Comment by ZmnSCPxj** [comment]
Each "hop" is a channel it passes through.  Since you are sending money via 1 channel (the channel between A and B) then that is 1 hop.

> >lightningd(18115): Sending 1000 over 1 hops to deliver 1000

Is this really all that B prints in the logs?  There is nothing about e.g. `WIRE_TEMPORARY_CHANNEL_FAILURE`, "Reporting route failure to gossipd", and so on?  Can you execute `lightning-cli getlogs debug`?

**Comment by FeedTheWeb** [comment]
no, I've already been very clear, and I'm not going to repeat myself for the 3rd time.
scroll up and re-read it if you missed some info.

**Comment by ZmnSCPxj** [comment]
Can you search these strings in the logs? (or better yet give the entire logs so that I can search as necessary for myself?)

    Invalid cltv_expiry
    Duplicate HTLC
    Maximum value exceeded
    Capacity exceeded
    HTLC too small
    Too many HTLCs

Also can you provide output of `lightning-cli getinfo`?

**Comment by FeedTheWeb** [comment]
got it.
You were right about the `reserve`, that was the issue. Thanks.
Apparently the default is 100000000.

This does not show up using `lightning-cli getlogs debug` , but found some clues using `--log-level=debug`.
Perhaps CHANNEL_ERR_CHANNEL_CAPACITY_EXCEEDED or similar message could be used for this?  (I guess it should be possible to detect this for its own channel(s))

[close]
