### ISSUE TITLE
Payment between two nodes leads to loop

### ISSUE THREAD

**Issue by hkjn** [ElementsProject/lightning#1136]
### Issue and Steps to Reproduce

Two nodes, A and B, with an established channel in `CHANNELD_NORMAL` state with funds on both sides between them, earlier able to send payments between each other. Both running version https://github.com/ElementsProject/lightning/commit/3dbace.

I sent several payments between the nodes (`lightning-cli invoice` on one node, then `lightning-cli pay` on the other), but today they were for some reason not connected (`connected: false` in `listpeers`) when I tried to pay an invoice generated by A with node B. This made the `pay` command exit with `{ "code" : 205, "message" : "Could not find a route" }`, so I did `connect` from node A to node B and then retried the `pay`.

This seems to have caused a looping behavior, logging messages like `htlc 463 failed from 0th node with code 0x0011 (WIRE_FINAL_EXPIRY_TOO_SOON)` for increasing `htlc N` values several times per second, reaching 900+ before I took down node B.

~~After this issue, it seems that the nodes are unable to connect to each other.~~ Edit: disregard this, it was an unrelated iptables misconfiguration issue.
 
Payment command:

```
$ lightning-cli pay lnbc25n1pdfd275pp5jaqc5ad7s9n5r7j4lg00jtd45tea5xcwdczkw8c36yx9lhn3yxvsdqvw3jhxapqw3uqcqpgazzelex374lkxrflu0uqlzm9ejwjspk9emmwnzd4sdk5u9yjetvqmpfqxzlln8v26mjtgaugarpwp9kzr4dd5kn447vp47zrl4ylgvqpn6py20
```

Node A:

```
lightningd(26148): lightning_channeld-02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084 chan #53: Sending commit_sig: HTLC REMOTE 218 = SENT_REMOVE_ACK_REVOCATION/RCVD_REMOVE_ACK_REVOCATION
lightningd(26148): lightning_channeld-02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084 chan #53: Sending commit_sig: HTLC REMOTE 311 = SENT_REMOVE_ACK_REVOCATION/RCVD_REMOVE_ACK_REVOCATION
lightningd(26148): lightning_channeld-02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084 chan #53: Sending commit_sig: HTLC REMOTE 284 = SENT_REMOVE_ACK_REVOCATION/RCVD_REMOVE_ACK_REVOCATION
lightning_gossipd(26156): req: type WIRE_GOSSIP_GETCHANNELS_REQUEST len 4
lightningd(26148): lightning_channeld-02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084 chan #53: Sending commit_sig: HTLC REMOTE 101 = SENT_REMOVE_ACK_REVOCATION/RCVD_REMOVE_ACK_REVOCATION
lightningd(26148): lightning_channeld-02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084 chan #53: Sending commit_sig: HTLC REMOTE 372 = SENT_REMOVE_ACK_REVOCATION/RCVD_REMOVE_ACK_REVOCATION
lightning_gossipd(26156): REPLY WIRE_GOSSIP_GETCHANNELS_REPLY with 0 fds
[ ... loops similar messages for each htlc logged in node B ... ]
```

Node B:

```
lightningd(1):jcon fd 15: Abandoning command
lightningd(1): Command returned result after jcon close
lightningd(1): Sending 2500 over 1 hops to deliver 2500
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #3: htlc 0 failed from 0th node with code 0x0011 (WIRE_FINAL_EXPIRY_TOO_SOON)
lightningd(1): Sending 2500 over 1 hops to deliver 2500
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #3: htlc 1 failed from 0th node with code 0x0011 (WIRE_FINAL_EXPIRY_TOO_SOON)
[... loops ... ]
lightningd(1): Sending 2500 over 1 hops to deliver 2500
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #3: htlc 462 failed from 0th node with code 0x0011 (WIRE_FINAL_EXPIRY_TOO_SOON)
lightningd(1): Sending 2500 over 1 hops to deliver 2500
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #3: htlc 463 failed from 0th node with code 0x0011 (WIRE_FINAL_EXPIRY_TOO_SOON)
lightningd(1): Sending 2500 over 1 hops to deliver 2500
```

Decoded payment:

```
$ lightning-cli decodepay lnbc25n1pdfd275pp5jaqc5ad7s9n5r7j4lg00jtd45tea5xcwdczkw8c36yx9lhn3yxvsdqvw3jhxapqw3uqcqpgazzelex374lkxrflu0uqlzm9ejwjspk9emmwnzd4sdk5u9yjetvqmpfqxzlln8v26mjtgaugarpwp9kzr4dd5kn447vp47zrl4ylgvqpn6py20
{ "currency" : "bc", "timestamp" : 1519823828, "created_at" : 1519823828, "expiry" : 3600, "payee" : "0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510", "msatoshi" : 2500, "description" : "test tx", "min_final_cltv_expiry" : 8, "payment_hash" : "97418a75be816741fa55fa1ef92db5a2f3da1b0e6e05671f11d10c5fde712199", "signature" : "3045022100e8859fe4d1f57f630d3fe3f80f8b65cc9d2806c5cef6e989b5836d4e1492cad802200d852030bff99d8ad6e4b47788e8c2e096c21d5ada5a75af981af843fd49f430" }
```

After restarting node B I increased log level from `info` to `debug`, and saw some log messages that might be related:

```
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #3: Got depth change 0->130 for 4bf50d50029781a7a50ec430cecc4d3df0ede41690b127100967377665816062                      
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #3: Funding tx 4bf50d50029781a7a50ec430cecc4d3df0ede41690b127100967377665816062 depth 130 of 3                        
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #3: Funding tx confirmed, but channel state CHANNELD_NORMAL unowned     
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #3: Funding tx announce ready, but channel state CHANNELD_NORMAL owned by none        
lightning_gossipd(12): Failed connected out for 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510, will try again
```

Node B shows the payment as `failed`:

```
$ lightning-cli listpayments
{ "payments" : 
        [ 
                { "id" : 1, "payment_hash" : "97418a75be816741fa55fa1ef92db5a2f3da1b0e6e05671f11d10c5fde712199", "destination" : "0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510", "msatoshi" : 2500, "timestamp" : 1519825815, "created_at" : 1519825815, "status" : "failed" } ] }
```

### `getinfo` output

Node A:

```
$ lightning-cli getinfo
{ "id" : "0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "163.172.162.18", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2040-g3dbace34", "blockheight" : 511325, "network" : "bitcoin" }
```

Node B:

```
$ lightning-cli getinfo
{ "id" : "02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084", "port" : 9735, "address" :
        [
                { "type" : "ipv6", "address" : "::ffff:174.138.11.8", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2040-g3dbace34", "blockheight" : 511252, "network" : "bitcoin" }
```

**Comment by ZmnSCPxj** [comment]
The two nodes seem to disagree about block height. The paying node thinks the block height is lower than the payee node. So it gives a final timeout that the payee thinks is too near in the future for its own safety. Then the `pay` autorepeat just retries without doing any further waiting.

Maybe we should at least throttle retries, but we cannot throttle too slowly either.

**Comment by hkjn** [comment]
Ah, thanks, hadn't noticed that.. node B might have been rewinding blocks after a restart (via IRC I understand that restarting a node leads it to fetch block / txout info from bitcoind back to the oldest tx creating a channel). I'll try connecting them again once both have caught up to the latest block.

But even if this explains the behavior, retrying indefinitely as fast as possible seems suboptimal, no? If indefinite retries are appropriate in this situation, maybe randomized exponential backoff or similar would make sense?

**Comment by ZmnSCPxj** [comment]
I am coding up something with 3 seconds delay for the 3 failures that involve block height (`WIRE_EXPIRY_TOO_SOON`, `WIRE_EXPIRY_TOO_FAR`, `WIRE_FINAL_EXPIRY_TOO_SOON`).  That may be enough for a first try.  Exponential backoff is possible too.

**Comment by practicalswift** [comment]
Thanks for an excellent bug report @hkjn!

**Comment by hkjn** [comment]
Apologies, the connection issues between A and B I mentioned earlier are entirely unrelated to any issues with this payment loop; I had messed up some iptables rules. Please disregard that part; the nodes can connect to each other fine once I fixed that unrelated issue.

**Comment by hkjn** [comment]
And just to confirm that @ZmnSCPxj found the right explanation, payments between nodes as expected go through fine now that both node A and node B have caught up to the latest block.
