### ISSUE TITLE
{ "code" : 205, "message" : "Could not find a route" }

### ISSUE THREAD

**Issue by Jfigs101** [ElementsProject/lightning#1139]
I am attempting to pay an invoice for the blockstream store and receive the following message when I run ./cli/lightning-cli pay bolt11_string >
```
{ "code" : 205, "message" : "Could not find a route" } 
```
### `getinfo` output
```
{ "id" : "03f45a99b30cadba3de6954e3c2f0c38ebf524665d9c299d4e0d389ffd61396f63", "│
port" : 9735, "address" :                                                       │
        [                                                                       │
                { "type" : "ipv4", "address" : "138.68.17.106", "port" : 9735 } │
], "version" : "v0.5.2-2016-11-21-2126-gb7ed5670", "blockheight" : 511354, "netw│
ork" : "bitcoin" } 
```
Can I get some troubleshooting assistance? I am guessing that I should have this output and may be part of the problem, I don't think I should have 2 : 
```
./cli/lightning-cli listchannels | grep 03f45a99b30cadba3de6954e3c2f0c38ebf524665d9c299d4e0d389ffd61396f63                 │
                { "source" : "03f45a99b30cadba3de6954e3c2f0c38ebf524665d9c299d4e│
0d389ffd61396f63", "destination" : "02f6725f9c1c40333b67faea92fd211c183050f28df3│
2cac3f9d69685fe9665432", "short_channel_id" : "511294:1402:1", "flags" : 1, "act│
ive" : true, "public" : true, "last_update" : 1519830949, "base_fee_millisatoshi│
" : 1000, "fee_per_millionth" : 10, "delay" : 14 },                             │
                { "source" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f│
9d69685fe9665432", "destination" : "03f45a99b30cadba3de6954e3c2f0c38ebf524665d9c│
299d4e0d389ffd61396f63", "short_channel_id" : "511294:1402:1", "flags" : 0, "act│
ive" : true, "public" : true, "last_update" : 1519830949, "base_fee_millisatoshi│
" : 1000, "fee_per_millionth" : 10, "delay" : 14 }, 
```

**Comment by cdecker** [comment]
Why are you grepping for your own node ID in the listchannels output? This way it doesn't include the channel status and all the other information.

**Comment by Jfigs101** [comment]
I ended up closing the channel and will try again. I will close this out and create more detailed issue if it arises again.

**Comment by nperalez** [comment]
This happened to me as well. Closing the channel and reopening helped. I was unable to troubleshoot root cause.

**Comment by ZmnSCPxj** [comment]
>Can I get some troubleshooting assistance? I am guessing that I should have this output and may be part of the problem, I don't think I should have 2 

You *should* have two.  There are two directions to each channel, one from you to the peer, the other from the peer to you.  They could have different fees (`base_fee_millisatoshi`, `fee_per_millionth`) and different CLTV deltas (`delay`); it just so happens that "nobody" changes the default settings so they look the same (in principle, they *could* be different; I am uncertain if we even have flags to change those...).  Notice how the `source` and `destination` get flipped between them.

-------

`02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432` is blockstream?  If so it is a direct channel.  Can you do `lightning-cli listpeers` and show the entire output?

**Comment by LNAPI** [comment]
Same problem.

**Comment by cdecker** [comment]
@LNAPI please open a new issue in future, I almost missed this in the notifications :wink: 

According to my own attempt just now there is a route:

```
{
   "route" : [
      {
         "id" : "02a54deb8d0f11d47c6f55cec5e673063c9fad2619559e8d87ae3eb4c381668449",
         "channel" : "573762x1393x1",
         "direction" : 0,
         "msatoshi" : 600000,
         "amount_msat" : "600000msat",
         "delay" : 153
      },
      {
         "id" : "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
         "channel" : "560523x2358x0",
         "direction" : 0,
         "msatoshi" : 600000,
         "amount_msat" : "600000msat",
         "delay" : 9
      }
   ]
}
```

Notice however that a route existing doesn't mean we can perform a payment along the route. The complete route would be going through 2 channels: 573762x1393x1 from your node to your peer, and 560523x2358x0 from your peer to the destination.

The first channel has sufficient capacity and is connected, so that'll work. However the second channel may not be connected, or may not have sufficient capacity to transfer the amount in the desired direction.

Upon failing the first attempt with this path the `pay` plugin will re-attempt using a different path, but if all paths fail it'll just report the last failure, which in this case is "Could not find a route".
