### ISSUE TITLE
Minimum HTLC Value is too large.

### ISSUE THREAD

**Issue by realcryptominer** [ElementsProject/lightning#1152]
I am receiving following error after trying to fund channels. I have tried dozens of nodes after connecting with them but I am unable to fund the channels.

root@vmi168564:~/builds/lightning# cli/lightning-cli fundchannel 039cc950286a8
                                                                              │fa99218283d1adc2456e0d5e81be558da77dd6e85ba9a1fff5ad3 10000
                                                                              │{ "code" : -1, "message" : "received ERROR channel 66d419415b93b412620a17121a7
                                                                              │74c155c766a1260a37f7882773171c60db3d1: Unacceptable channel constraints: minim
                                                                              │um HTLC value is too large: 0" }

**Comment by ZmnSCPxj** [comment]
Duplicates: #997 

This is a known bug in lnd: https://github.com/lightningnetwork/lnd/pull/779

See also: https://github.com/cdecker/lightning-integration/issues/11 which shows the same "minimum HTLC value is too large: 0" message, and acknowledges that it is an lnd bug.

Closing as `wontfix` as we cannot do anything on our side.

**Comment by jsarenik** [comment]
Just for reference: https://github.com/lightningnetwork/lnd/issues/836
