### ISSUE TITLE
Error 206 - Payment is stucked...

### ISSUE THREAD

**Issue by realcryptominer** [ElementsProject/lightning#1153]
I have freshly installed testnet lightning node on Linux Ubuntu 16.04 VPS.

Bitcoind testnet blockheight, lightning cli blockheight and testnet blockheight are matching.

However, I am unable to buy coffee from Starblocks. The payment is stucked. First of all it showed error code 206 so I increased the max percent fees and then the payment is stucked.

Here is a video of this error.

https://youtu.be/JppYvhCs7zg

Kindly help me to buy starblocks Coffee!

**Comment by ZmnSCPxj** [comment]
Is this not the same as #1135?

I cannot watch videos on youtube due to bandwidth capacity issues, sorry.

**Comment by Saibato** [comment]
@ZmnSCPxj  watched video for u.
what one can see
is that the funding channel id's shown by  @realcryptominer listfunds are not the starblocks id 
starblocks has ID
035b55e3e08538afeef6ff9804e3830293eec1c4a6a9570f1e96a478dad1c86fed
Starblocks sits behind an other node.
i myself often cant even pay with e-clair app or HTLC.me account  
it says to his invoice fees are 0.00 mBtc and then stucks too

**Comment by realcryptominer** [comment]
Yeahh... Its the same one....

I have re-installed Ubuntu 16.04 Linux and still I am not able to buy a coffee... I am not an expert developer. I am just a general public who have installed bitcoind testnet and Lightningnode on Linux and want to buy starvlocks coffee on testnet.

Here is my LN status on Linux.

-------------
root@vmi168564:~/builds/lightning# bitcoin-cli -testnet getblockcount
1287107
root@vmi168564:~/builds/lightning# cli/lightning-cli dev-blockheight
{ "blockheight" : 1287107 }
root@vmi168564:~/builds/lightning# cli/lightning-cli listfunds
{ "outputs" :
        [
                { "txid" : "17a37728c765c78f7ad6cf6ac8e717bdf7d611468814e0fecf22d94b43fc6af2", "output" : 1, "value" : 109996822 },
                { "txid" : "6ae4e6efed26644f19f03e26b434d77b39c3cf7df3ade106b48666e5fe2de68c", "output" : 1, "value" : 99974514 } ], "channels" :
        [
                { "peer_id" : "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134", "short_channel_id" : "1287067:119:0", "channel_sat" : 10000, "channel_total_sat" : 10000, "funding_txid" : "2afadbcfd4826909f2397441dba92c7c5ce81a163e8fc17d2383a80bd5189daa" },
                { "peer_id" : "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134", "short_channel_id" : "1287089:189:0", "channel_sat" : 10000, "channel_total_sat" : 10000, "funding_txid" : "ae93f69ef5ff9308dfaf8b661a9eb841b6c6a7834d078d98c33428512697f654" },
                { "peer_id" : "03e5f9d1935c67a029bf0a26af5f63109f4f4c45993a8f45177a8f2f39bcb46144", "short_channel_id" : "1287089:188:0", "channel_sat" : 3000, "channel_total_sat" : 3000, "funding_txid" : "17a37728c765c78f7ad6cf6ac8e717bdf7d611468814e0fecf22d94b43fc6af2" },
                { "peer_id" : "0315c5d0d75a6557d6378afe948911983d48886fe1542478a7493e8685dc7b5ef8", "short_channel_id" : "1287090:114:0", "channel_sat" : 5000, "channel_total_sat" : 5000, "funding_txid" : "6ae4e6efed26644f19f03e26b434d77b39c3cf7df3ade106b48666e5fe2de68c" } ] }
root@vmi168564:~/builds/lightning#
-----------

I have open and funded channels now. These channels are apart from the issue in #1135 as I have re-installed everything after formatting my Linux VPS. Now when I try to pay for Starblocks coffee, here is what it says.

-------------
cli/lightning-cli pay lntb17u1pdfj26app5kyzxv5pgcxyezcukxc687y5qtazzny7du8q7zndg7zvnselwnm2qdpzxysy2umswfjhxum0yppk76twypgxzmnwvyyalkz54hnczjnphl3nx6k7xqcaf7pk80rh9le5l7scrqcs29mk7rvmnwzmyh4qcvzjj09d22e0w9w0jyzetx6vt7dftfm9606dh7fmgpz3ymee

Now this gets code error 206 and says that the default maxfee percentages is set to 0.5 and this route has fees of 0.65, 0.95, 1.25 or something like that so what I do is, I do

cli/lightning-cli pay lntb17u1pdfj26app5kyzxv5pgcxyezcukxc687y5qtazzny7du8q7zndg7zvnselwnm2qdpzxysy2umswfjhxum0yppk76twypgxzmnwvyyalkz54hnczjnphl3nx6k7xqcaf7pk80rh9le5l7scrqcs29mk7rvmnwzmyh4qcvzjj09d22e0w9w0jyzetx6vt7dftfm9606dh7fmgpz3ymee 'null' 'null' 'null' '3'

And then It stucks there forever and I cannot buy a coffee with it.

---------------
@ZmnSCPxj 

All I need as a general public is to buy starblocks coffee on testnet as just few weeks ago I did not what is SSH, Ubuntu, Putty, tmux and so on and so forth...
It's just the lightning network which boost my enthusiasim to learn all these things and now I am proud that I have successfully installed testnet and lightning node on Linux/Ubuntu 16.04 VPS.

Can you guess that who am I in the real world?
Well, I am a doctor seeing patients whole day in my OPD. So these error codes are like rocket science for me.... : )

If you can only let me know that on which testnet node I should connect and fund the channel so that I can buy the starblocks coffee then it will be your great help... : )

It will give me immense feeling of satisfaction... : )

Cheers...

**Comment by realcryptominer** [comment]
@Saibato 

Yes correct. Listfunds are basically other well connected nodes on the testnet through which I want to buy starblocks coffee. But I am getting code error 206 with it.

So now I have formatted my VPS and freshly installed Ubuntu 16.04, Bitcoind -testnet and LN on it and connected with fresh new nodes and created and funded channels with them. All these channels are now active and funded but I am still unable to buy a coffee with it.

Can u tell me that where exactly I should connect and fund the channel so that I can buy this starblocks coffee?

Its now the question of my satisfaction, ego and status!.... lolz... ; )

**Comment by realcryptominer** [comment]
See. Just right now this is what I get while trying to buy starblocks coffee..

root@vmi168564:~/builds/lightning# cli/lightning-cli pay lntb19u1pdfjvzvpp5605pjq0hfq6544vnpydlg9eedyxg4xqm5yw6j50r05wtppanqvqqdp8xys9xcmpd3sjqsmgd9czq3njv9c8qatrvd5kumc2nhdlgehlquqhrtnmzks66zve4npuxqn8rcny63mltsw3upstrrhq9h7g4g5haucxg3kflpyr8r3unru23tla9pz9sfyt6amnkn3vtqqq6yrvx
{ "code" : 206, "message" : "Fee 11191 is 0.589000% of payment 1900000; max fee requested is 0.500000%", "data" : { "fee" : 11191, "feepercent" : 0.589000, "msatoshi" : 1900000, "maxfeepercent" : 0.500000, "getroute_tries" : 6, "sendpay_tries" : 0 } }

So I have entered the new parameters and increase the fees. And here is what I get...

root@vmi168564:~/builds/lightning# cli/lightning-cli pay lntb19u1pdfjvzvpp5605pjq0hfq6544vnpydlg9eedyxg4xqm5yw6j50r05wtppanqvqqdp8xys9xcmpd3sjqsmgd9czq3njv9c8qatrvd5kumc2nhdlgehlquqhrtnmzks66zve4npuxqn8rcny63mltsw3upstrrhq9h7g4g5haucxg3kflpyr8r3unru23tla9pz9sfyt6amnkn3vtqqq6yrvx 'null' 'null' 'null' '3'

And its 10 mins now and the payment is stucked there. Its not going through nor Starblocks page shows the payment success.

**Comment by Saibato** [comment]
i found a well connected node direct behind starblocks    alias  endurance  at
03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134  34.250.234.192  9735
Please try to fund this peer to open a direct channel 

and please try to buy at your first order more then one coffee ;-)
Testnet difficulty is high so blocktime might be over 20min

**Comment by ZmnSCPxj** [comment]
Ah, the endurance-starblocks thing.  I am not sure, but I think there are known problems with paying on starblocks via endurance, and starblocks refuses direct connections to their node (everybody has to go through endurance).  Sometimes endurance gets overloaded or something and it is impossible to pay starblocks, so we simply keep failing no matter what.  Others might have more perspective on this: @cdecker @rustyrussell .

**Comment by cdecker** [comment]
@ZmnSCPxj endurance is the entry point into ACINQ's network, and the starblocks backend is not directly reachable, yes. Payments to starblocks need to go through endurance. I myself did a demo just 2 days ago with Starblocks and it worked like a charm, though that may not be the case now.

**Comment by realcryptominer** [comment]
@cdecker 

3 Days back first time when I did payment to starblocks, it worked. And it was my first and last time. After that till today I am unable to buy starblocks coffee.

Also I am unable to make payments to yalls.org

See this video. I am unable to make both these payments even with fully funded active channels.

https://youtu.be/NGE6cFSz9EM

In short, for me I get 206 error while making payments for both Starblocks and Yalls.org even after installing fresh Bitcoin testnet node and LN testnet node!

Can u suggest/share the nodes with which you are connecting? I can try them.
I am on high speed internet plus this LN node setup is on Linux Ubuntu 16.04 VPS with 6GB RAM and Quad core processor and 500GB hard disk.

**Comment by realcryptominer** [comment]
Success...!!!.... : )

I just did successful payment for starblocks and purchased blockaccino and Express coin panna.

https://ibb.co/grTJv7

It took a split of second to complete this payment.

Amazing Feeling... : )

Long Live Lightning Network & its all Developers... : )

Update: There is definitely something wrong with endurance/starblocks..etc...
Because buying coffee is not consistent. Now I get Error 205.

root@vmi168564:~/builds/lightning# cli/lightning-cli pay lntb32u1pdfn2tupp5k6v9nd29zw086d2akgwwdefy25srdrek6x862x82xzzayh62p0usdp6xysyymr0vd4kzcmrd9hx7tpqxysy2umswfjhxum0yppk76twypgxzmnwvycc99dstj9vm634uv7lfaxfzv3eqs7n96fy56f55knqjq3ux8mrjkh26wdwjkp6sp8n6s39rkj6declw8rmaprmfv5hthyt79ttaus5cqv3kr6a
{ "code" : 205, "message" : "Could not find a route", "data" : { "getroute_tries" : 2, "sendpay_tries" : 1 } }

**Comment by ZmnSCPxj** [comment]
Yes, I believe there are intermittent times when starblocks and endurance cannot reliably be paid over.  Sometimes it works, sometimes it dos not.

The 206 error is irrelevant to starblocks being intermittently payable/unpayable; it simply means most of the routes available to you are beyond the fee rate you told c-lightning to use (or beyond 0.5%, if you told c-lightning nothing about the feerate).  People expect low fees over lightning so if we start getting high fees on routes (because people are paying tiny amounts) we should properly inform users.  206 is how we inform them and confirm if it is OK to spend so much on fees.

**Comment by realcryptominer** [comment]
@ZmnSCPxj Yes. I agree 100%.

**Comment by realcryptominer** [comment]
Update....

I am now able to successfully buy starblocks coffee without any type of error consecutively.
I am not encountering any kind of error at the moment to buy the starblocks coffee.

The transaction is going on smoothly and takes just few miliseconds to complete.

I have screenrecorded everything if you want to have a look.

https://youtu.be/bqxJtxK0mMQ

https://www.youtube.com/watch?v=H8QPi4wGf_4

Long Live LN & its all Developers!

Cheers... : )

**Comment by cdecker** [comment]
Glad it worked. Closing as a temporary issue between endurance and starblocks, and not related to c-lightning.

@realcryptominer please don't do videos when reporting bugs, it's really hard to extract the necessary information.
