### ISSUE TITLE
lightningd crashed after awhile

### ISSUE THREAD

**Issue by redstorm1** [ElementsProject/lightning#1162]
### Issue and Steps to Reproduce
Have lightningd running with two channels open. crashed after a period of time (possibly days as i hadnt checked it for a while)

### `getinfo` output
{ "id" : "0392419c02fbca83ae8d541cd2f48b662b2238ed8e1e92a93547c23ba32f0d64c6", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "203.86.204.88", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2124-gfba2bdb", "blockheight" : 1262560, "network" : "testnet" }

crash.log (only tailed that last 1000 lines as its 30M in size.
[http://paste.ubuntu.com/p/58kss85cV5/](url)

**Comment by CryptoChronicus** [comment]
the link to the log that you provided is dead sir.

**Comment by cdecker** [comment]
The relevant lines are:

```
+1058.416594561 lightningd(28334):BROKEN: wallet_channel_insert: UNIQUE constraint failed: peers.node_id
+1058.932678040 lightningd(28334):BROKEN: FATAL SIGNAL 6 RECEIVED
+1058.938182398 lightningd(28334):BROKEN: backtrace: lightningd/log.c:503 (log_crash) 0x412264
+1058.938561508 lightningd(28334):BROKEN: backtrace: (null):0 ((null)) 0x7f8c40c5b4af
+1058.938568220 lightningd(28334):BROKEN: backtrace: (null):0 ((null)) 0x7f8c40c5b428
+1058.938581396 lightningd(28334):BROKEN: backtrace: (null):0 ((null)) 0x7f8c40c5d029
+1058.938586304 lightningd(28334):BROKEN: backtrace: lightningd/log.c:592 (fatal) 0x41269e
+1058.938696515 lightningd(28334):BROKEN: backtrace: wallet/db.c:219 (db_exec_prepared_) 0x44ec0b
+1058.938900762 lightningd(28334):BROKEN: backtrace: wallet/wallet.c:898 (wallet_channel_insert) 0x454161
+1058.939332162 lightningd(28334):BROKEN: backtrace: lightningd/peer_control.c:2272 (wallet_commit_channel) 0x41fdbe
+1058.939340049 lightningd(28334):BROKEN: backtrace: lightningd/peer_control.c:2384 (opening_funder_finished) 0x420487
+1058.939643427 lightningd(28334):BROKEN: backtrace: lightningd/subd.c:307 (sd_msg_reply) 0x4271dc
+1058.939649949 lightningd(28334):BROKEN: backtrace: lightningd/subd.c:435 (sd_msg_read) 0x427768
+1058.939663116 lightningd(28334):BROKEN: backtrace: lightningd/subd.c:328 (read_fds) 0x4272d9
+1058.939748284 lightningd(28334):BROKEN: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x45ee3d
+1058.939752407 lightningd(28334):BROKEN: backtrace: ccan/ccan/io/io.c:387 (do_plan) 0x45f914
+1058.939765598 lightningd(28334):BROKEN: backtrace: ccan/ccan/io/io.c:397 (io_ready) 0x45f952
+1058.939843661 lightningd(28334):BROKEN: backtrace: ccan/ccan/io/poll.c:310 (io_loop) 0x461221
+1058.939950327 lightningd(28334):BROKEN: backtrace: lightningd/lightningd.c:373 (main) 0x41099c
+1058.939955098 lightningd(28334):BROKEN: backtrace: (null):0 ((null)) 0x7f8c40c4682f
+1058.939967690 lightningd(28334):BROKEN: backtrace: (null):0 ((null)) 0x4032d8
+1058.939970724 lightningd(28334):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

This should have been addressed in PR #1066, but your `getinfo` suggests you client includes that revision?

**Comment by redstorm1** [comment]
I've updated to the latest (git pull) and re compiled, with the latest build a channel i had stuck in "CHANNELD_SHUTTING_DOWN" (for weeks) has now changed to "ONCHAIN:Tracking our own unilateral close" so looks like it will release the funds in x number of blocks. happy if you want to close this one, if it dies again ill re post a new log.

**Comment by redstorm1** [comment]
might have another issue: Lightningd console output is reporting this:
2018-03-04T12:11:48.363Z lightningd(7536): Broadcasting tx 02000000000101e2afa4c5c55cc871cff96310b6255f28504b0610b97cf045fb05abf79e7c03520000000000928bb280027607000000000000160014a7d01a3ff174558daeb9af4dc3177edf0a77055e5ccd0400000000002200200146c612501afa6dee9d18be9c34a5933259a43bc7b89636e85f40369ebc0797040047304402202c4c60aba958c6cf7b9f98cff54e66b15271d025ee51c1d66e008a2ca3bcd1ac022058296fafa7e0504a986cc6c530fe3de77503815772d5757e3dd2ac575b2e0ad301483045022100de6601896e7918534c24cca2666971c1194221780e73b04f0003fe7684758496022044994de791e30c2bf7e272a1322aea37b6b44afbbe9687453a6050fbd86ad2040147522103afff28ab2f65ffd8d6f89bc45a8857a3b4be6e8074651a8e85904e0b66a996b42103ead1ab5bfe52a2fdb9be39463d9cced7e40f37f8884eaaa7baaff9a222c3456152ae7bab5120: 25 error code: -25?error message:?Missing inputs?

That channel wont close due to the missing inputs

**Comment by cdecker** [comment]
That's quite alright, it just means that a previous broadcast already claimed the outputs: [deb99da2bdf9495ee0938cddf71216967c94a5f521e9630b93bb508ed2bac4cf](https://testnet.smartbit.com.au/tx/deb99da2bdf9495ee0938cddf71216967c94a5f521e9630b93bb508ed2bac4cf). Since the output values between the P2WPKH and the P2WSH are flipped I think this one's the other endpoint's unilateral close so you should have the output `deb99da2bdf9495ee0938cddf71216967c94a5f521e9630b93bb508ed2bac4cf:1` in your `listfunds` output.

**Comment by redstorm1** [comment]
Yes present in listfunds
{ "txid" : "deb99da2bdf9495ee0938cddf71216967c94a5f521e9630b93bb508ed2bac4cf", "output" : 1, "value" : 314716 }

**Comment by cdecker** [comment]
Congratulations, you got your funds back :-)

How is the crash behaving, any luck in opening a new channel with the peer?

**Comment by redstorm1** [comment]
I have reopened the channel with endurance. so ill close this ticket and monitor the behavour.
