### ISSUE TITLE
Proper realloc failure handling

### ISSUE THREAD

**Issue by dongcarl** [ElementsProject/lightning#1169]
Looking through the codebase, I see several places where realloc is called, but most of them don't handle the case where `realloc` fails and returns a null pointer. (see http://www.iso-9899.info/wiki/Realloc)

Is there reason for this xor should I fix it?

**Comment by cdecker** [comment]
I think we currently consider all allocation failures as deadly, and do not attempt to recover from them. `realloc` may fail if the allocation fails, but we still have the `tal` context that'd allow us to free the original allocation if we wanted to.

Maybe @rustyrussell can add some more color to this?

**Comment by rustyrussell** [comment]
As @cdecker says, all allocation failures should be fatal; if there are any which aren't that should be fixed.  For example, tal_resize() will call abort.

**Comment by dongcarl** [comment]
Makes sense :smile:
