### ISSUE TITLE
Can't reconnect to a peer after getting STATE_ERR_INFORMATION_LEAK

### ISSUE THREAD

**Issue by takaya-imai** [ElementsProject/lightning#117]
What kind of status is STATE_ERR_INFORMATION_LEAK?
I think this is occurred in case that closing a channel fails or peer breaks a channel forcedly according to https://github.com/ElementsProject/lightning/blob/e5b44ff23245267c0e54633acc9982ebe48c2a0c/daemon/state_types.h . 

So I try to recreate a channel.
The connecting peer is booted successfully but `connect` command returns "peer breakdown".

How could I reconnect to the peer?

The peer side logs are like below.

```
IN-::ffff:1.55.46.187:21667: Connected in from ::ffff:1.55.46.187:21667 id 02d837e5fd98da358f8af239eedb7ea46d85400c088d10f018d3783c22800b1848, changing prefix
02c5bcc81e7953d90997be23f44f23f6b6086ddc239c26afc468ad2c1123085d07: Reconnected in from ::ffff:1.55.46.187:21579
02c5bcc81e7953d90997be23f44f23f6b6086ddc239c26afc468ad2c1123085d07: Sending PKT_ERROR: In error state STATE_ERR_INFORMATION_LEAK
02c5bcc81e7953d90997be23f44f23f6b6086ddc239c26afc468ad2c1123085d07: Disconnected
02c5bcc81e7953d90997be23f44f23f6b6086ddc239c26afc468ad2c1123085d07: Reconnected in from ::ffff:1.55.46.187:32081
02c5bcc81e7953d90997be23f44f23f6b6086ddc239c26afc468ad2c1123085d07: Sending PKT_ERROR: In error state STATE_ERR_INFORMATION_LEAK
02c5bcc81e7953d90997be23f44f23f6b6086ddc239c26afc468ad2c1123085d07: Disconnected
```

**Comment by cdecker** [comment]
We are currently limited to one connection per peer, so until the broken down connection is purged from our memory (should take a couple of blocks until we clear it from the database) you will not be able to open another connection to the same peer. This is a limitation on how we currently handle the channels, and we will eventually remove this limit. For now waiting is the only option.

**Comment by takaya-imai** [comment]
@cdecker I got it. Thanks a lot for your comment.
