### ISSUE TITLE
crash.log not cleared before being written to

### ISSUE THREAD

**Issue by sadilek** [ElementsProject/lightning#1173]
crash.log is not cleared before it's being written to. This means if your daemon crashes two times, and for the second crash, the output in crash.log is shorter than the output for the first crash, crash.log contains the output of the second crash, followed by the tail of the output of the first crash.

**Comment by ZmnSCPxj** [comment]
I would suggest making this an appendable log, so that multiple crashes accumulate in case you have some kind of auto-restart for daemons.

**Comment by ZmnSCPxj** [comment]
Closed in #1197.
