### ISSUE TITLE
"CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures." and loops

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1174]
### Issue and Steps to Reproduce

For security purposes, I did replace some data with generic strings.

I have a channel in the following state, excerpted from _listpeers_:

                     { "id" : "aaaaaaRedactedNodeId", "connected" : true, "netaddr" : 
                             [ "1.2.3.4:9735" ], "alias" : "@@", "color" : "000000", "channels" : 
                             [ 
                                     { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "1:22:1", "funding_txid" : "abcdef", "msatoshi_to_us" : 100000, "msatoshi_total" : 100000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" : 
                                             [ "CHANNELD_NORMAL:Reconnected, and reestablished.", "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures." ] } ] }, 

Here's the loop of something that says "revoke" in the logs for that channel:
[waitcensor.txt](https://github.com/ElementsProject/lightning/files/1780418/waitcensor.txt)

It seems to keep looping with some sort of "revoke" procedure.  What is it doing, and what should I do?  Just wait?  Is that safe?

### `getinfo` output
I'm on "v0.5.2-2016-11-21-2207-g31b9b6b"

**Comment by cdecker** [comment]
That's alright, the regular commitments are simply feerate changes which adjust the feerate to what is expected for on-chain transactions. The "waiting for announcement signature" message just means that the remote end has not given us the signatures needed for the `channel_announcement` yet. We won't be able to announce the channel to others, but it is usable for us.

**Comment by cdecker** [comment]
@Ulmo, was that the question you had, or did I misunderstand? If it was feel free to close the issue :-)

**Comment by Ulmo** [comment]
Thank you for answering.  I was doing a reconciliation of why I was missing around BTC.16, but ran out of time to look into it, and today, it showed back up, so I'm not as worried any more.

**Comment by cdecker** [comment]
Great, thanks for the update @Ulmo
