### ISSUE TITLE
Should we autoclear output reservations after some blocks?

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#1203]
This is what we created `dev-rescan-outputs` for in the first place, i.e., we reserve some funds for a funding tx or a withdrawal tx, but then something on-chain goes wrong (most likely some fees being estimated incorrectly). Currently we use `dev-rescan-outputs` to sync the output state with what `bitcoind` believes to be correct.

Since I'd like to switch to `DEVELOPER=0` as default soon, I think we need a more robust way of doing this. My proposal therefore would be to introduce a `reserved_height` into the output, and clear its state if `spend_height` is `NULL` after `reserved_height + 144`, that way we automatically get those coins back into the rotation after a while.

It goes against what other wallets do, namely insist on that transaction becoming valid. This is basically an automated `dev-rescan-outputs` after 1 day without the need for user interaction.

**Comment by ZmnSCPxj** [comment]
Going against what other wallets do is a double-whammy: presumably other wallets do it that way for good reason, and users of other wallets may be used to how other wallets do things, leading to bad expectations.

**Comment by cdecker** [comment]
I see your point, then again wallets provide users with similar options: `-zapwallettxs` does allow you to discard and rescan just like `dev-rescan-outputs` does. One key difference I see is that the funding transactions are sort of time-critical, i.e., they need to confirm in a reasonable time for the channel to become usable, so recovering from a partial failure to broadcast is important for us.

The main reason I want to get rid of `dev-rescan-outputs` is that it can cause a cascade of errors, with some outputs being used and then reclaimed while the tx is still in flight, and subsequent transactions failing because they build on top of the doublespent coins or the change output of failed transactions.

**Comment by whitslack** [comment]
In the case of a locally failed channel funding (e.g., because fee was too low for the local node to accept), doesn't the peer know the fully signed funding transaction too? If so, then it isn't safe to simply reset the outputs to unspent, as the peer could broadcast the funding transaction at any time, potentially leading to that whole "cascade of errors" you mentioned, @cdecker.

**Comment by cdecker** [comment]
I'm not sure there is a clean solution to this Problem, that doesn't involve moving the funds into new outputs using an on-chain transaction which might be costly and unexpected. We could offer a manual way to the user to unreserved using a higher fee on-chain transaction, and maybe combine it with some sort of consolidation of UTXOs.

You guys convinced me that doing anything automatically may be disruptive and unexpected to the user.
