### ISSUE TITLE
Lightningd should have -conf option like bitcoin-cli and bitcoind

### ISSUE THREAD

**Issue by ghost** [ElementsProject/lightning#1204]
### Issue and Steps to Reproduce

We run `bitcoind` with the configuration file `/etc/bitcoin.conf` and the data dir is `/var/bitcoin`:

    [Unit]
    Description=The Bitcoin Core daemon
    Wants=network.target

    [Service]
    ExecStart=/opt/bitcoin-core/0.15.0.1/bin/bitcoind -conf=/etc/bitcoin.conf
    ExecReload=/bin/kill -HUP $MAINPID
    KillSignal=TERM
    User=bitcoin

We'd also like to run `lightningd` with the same set up but we can't find an option to get `lightningd` to read `/etc/bitcoin.conf`.  It's possible to change the bitcoin data dir, but not the config file.

It would be great if `lightningd` had a `-conf` option like `bitcoin-cli` and `bitcoind`. It could be called `--bitcoin-conf`.

**Comment by ZmnSCPxj** [comment]
One issue with this feature proposal is that there is the possibility that some day we may have changeable blockchain backends; that is, we might want to some day support something other than bitcoind (alternate implementations, or far more likely some SPV implementation).

However perhaps it can be done with appropriate namespacing of options.

**Comment by grobinson-blockchain** [comment]
Hmm, one question is that `lightningd` has Bitcoin specific options in its current version, so those would  have to break/change regardless?

    --bitcoin-datadir <arg>        -datadir arg for bitcoin-cli
    --bitcoin-rpcuser <arg>        bitcoind RPC username
    --bitcoin-rpcpassword <arg>    bitcoind RPC password
    --bitcoin-rpcconnect <arg>     bitcoind RPC host to connect to

**Comment by grobinson-blockchain** [comment]
It just seems a little unusual to support `--bitcoin-datadir` and the like and not support `--bitcoin-conf`?

**Comment by FeedTheWeb** [comment]
( workaround:  make a symlink  to `/etc/bitcoin.conf` )

**Comment by grobinson-blockchain** [comment]
That's an optional we have been considering, but it's quite a hack. Is there no interest to support this upstream?

**Comment by cdecker** [comment]
We could consider it, but that'd definitely force us to keep `bitcoin-cli` as the lifeline to talk to `bitcoind`. I was planning to eventually implement the RPC client in `lightningd` itself in order to avoid shelling out to `bitcoin-cli`.

**Comment by cdecker** [comment]
We now have the `--conf` flag.

**Comment by ZmnSCPxj** [comment]
@cdecker I think `--conf` only sets *our own* configuration file.  From my understanding of the below text:

> We'd also like to run `lightningd` with the same set up but we can't find an option to get `lightningd` to read `/etc/bitcoin.conf`.

It seems to me that what is being asked here is for `lightningd` to read the `bitcoind` configuration file somehow, which is ***not*** what `--conf` does.

That said I have no interest in implementing this, so will add `wontfix` unless you or rusty or lisa reopen this issue.
