### ISSUE TITLE
My channels are lost?

### ISSUE THREAD

**Issue by Nododot** [ElementsProject/lightning#1211]
### Issue and Steps to Reproduce

I have created a new node on mainnet, and opened a bunch of channels, single-funded with small amounts between 10000-30000 sats.

See my 16 channels listed by #recksplorer on https://lnmainnet.gaben.win/
Search for 030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9

Now I have lost most of them when I list peers and funds.
I have only 5 channels left, and one is dying.
What has happened?

Some things I have done:
- Fund my wallet
- Open channels, fund channels
- Try to send a 1000 sats donation to #recksplorer (failed)
- Update c-lightning version
- Withdraw remaining sats to my BTC wallet

### commands output

> $ lightning-cli getinfo
> { "id" : "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9", "                                                                                        port" : 9735, "address" :
>         [
>                 { "type" : "ipv4", "address" : "79.143.187.131", "port" : 9735 }                                                                                        ,
>                 { "type" : "ipv6", "address" : "2a02:c205:2017:254::1", "port" :                                                                                         9735 } ], "version" : "v0.5.2-2016-11-21-2269-g249464cc", "blockheight" : 51337                                                                                        8, "network" : "bitcoin" }
> 
> $ lightning-cli listfunds
> { "outputs" :
>         [  ], "channels" :
>         [
>                 { "peer_id" : "023c5f2b69161742cc49da5be6cb7c940465fc608ff216bafc7573eb31121b22d2", "short_channel_id" : "512451:1341:0", "channel_sat" : 20000, "channel_total_sat" : 20000, "funding_txid" : "024e199969bb2dc4c94372010754fdfe55a8f92231371bb36c5bb8c553773790" },
>                 { "peer_id" : "02dcdd7e18b80dc7fd51af34e871901c13f574e4b82325dc74c0beeada5771e8e9", "short_channel_id" : "512490:2094:0", "channel_sat" : 20000, "channel_total_sat" : 20000, "funding_txid" : "8af8bf65e7cc46d75004f16120c92a907e93e74c2449857b9c2cf569f7264e65" },
>                 { "peer_id" : "0347ffcb271ef54fa6103fc6392370ce398d1bc98460829f7046cf64026253a68e", "short_channel_id" : "512490:2097:0", "channel_sat" : 20000, "channel_total_sat" : 20000, "funding_txid" : "fdcba1ae587e3dff41159ed59997a62b74ae7e46ce6f48db727d3e9bf7d82ac6" },
>                 { "peer_id" : "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1", "short_channel_id" : "512557:1341:0", "channel_sat" : 30000, "channel_total_sat" : 30000, "funding_txid" : "75b646de560d031b65e3655c719caeb85df3ad3b54bdf94e2b408b86e0c4a056" },
>                 { "peer_id" : "022b662aa03cf4db4820bcf4f47f1006d2bfae9bee416a926fb8bdba16e088d7f6", "short_channel_id" : "512658:2154:0", "channel_sat" : 0, "channel_total_sat" : 10000, "funding_txid" : "f054596ef9cb17ad1837290aa69028516f2f3dc55cf82538ea02e75b8267b75f" } ] }
> 
> $ lightning-cli listpeers
> { "peers" :
>         [
>                 { "id" : "023c5f2b69161742cc49da5be6cb7c940465fc608ff216bafc7573eb31121b22d2", "connected" : false, "channels" :
>                         [
>                                 { "state" : "CHANNELD_NORMAL", "short_channel_id" : "512451:1341:0", "funding_txid" : "024e199969bb2dc4c94372010754fdfe55a8f92231371bb36c5bb8c553773790", "msatoshi_to_us" : 20000000, "msatoshi_total" : 20000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
>                                         [ "Loaded from database" ] } ] },
>                 { "id" : "02dcdd7e18b80dc7fd51af34e871901c13f574e4b82325dc74c0beeada5771e8e9", "connected" : false, "channels" :
>                         [
>                                 { "state" : "CHANNELD_NORMAL", "short_channel_id" : "512490:2094:0", "funding_txid" : "8af8bf65e7cc46d75004f16120c92a907e93e74c2449857b9c2cf569f7264e65", "msatoshi_to_us" : 20000000, "msatoshi_total" : 20000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
>                                         [ "Loaded from database" ] } ] },
>                 { "id" : "0347ffcb271ef54fa6103fc6392370ce398d1bc98460829f7046cf64026253a68e", "connected" : false, "channels" :
>                         [
>                                 { "state" : "CHANNELD_NORMAL", "short_channel_id" : "512490:2097:0", "funding_txid" : "fdcba1ae587e3dff41159ed59997a62b74ae7e46ce6f48db727d3e9bf7d82ac6", "msatoshi_to_us" : 20000000, "msatoshi_total" : 20000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
>                                         [ "Loaded from database" ] } ] },
>                 { "id" : "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1", "connected" : true, "netaddr" :
>                         [ "[::ffff:45.55.47.17]:39226" ], "alias" : "LND.rompert.com", "color" : "0000ff", "channels" :
>                         [
>                                 { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "512557:1341:0", "funding_txid" : "75b646de560d031b65e3655c719caeb85df3ad3b54bdf94e2b408b86e0c4a056", "msatoshi_to_us" : 30000000, "msatoshi_total" : 30000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
>                                         [ "CHANNELD_NORMAL:Reconnected, and reestablished.", "CHANNELD_NORMAL:Funding transaction locked." ] } ] },
>                 { "id" : "022b662aa03cf4db4820bcf4f47f1006d2bfae9bee416a926fb8bdba16e088d7f6", "connected" : false, "channels" :
>                         [
>                                 { "state" : "ONCHAIN", "owner" : "lightning_onchaind", "short_channel_id" : "512658:2154:0", "funding_txid" : "f054596ef9cb17ad1837290aa69028516f2f3dc55cf82538ea02e75b8267b75f", "msatoshi_to_us" : 0, "msatoshi_total" : 10000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
>                                         [ "CHANNELD_NORMAL:update_fee 25153 outside range 1232-13850", "ONCHAIN:Tracking their unilateral close", "ONCHAIN:All outputs resolved: waiting 82 more blocks before forgetting channel" ] } ] },
>                 { "state" : "GOSSIPING", "id" : "0350052352bbf3d13cafe5217d1d9d63bf32fd881cbef62675b4b271ecc357cee4", "alias" : "elec.luggs.co", "color" : "6b1321", "netaddr" :
>                         [ "[::ffff:95.211.185.14]:54648" ], "connected" : true, "owner" : "lightning_gossipd" } ] }

**Comment by cdecker** [comment]
Where all channels funded by your node `030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9`? It seems that at least some of the channels were closed unilaterally, but since you don't have any unspent outputs I'm curious why you didn't get any funds back.

One example is the channel with funding tx [461b431320292a2b398f96fa0ee12f7245ee4e809af96d0e9d4c10523053fbad](https://www.smartbit.com.au/tx/461b431320292a2b398f96fa0ee12f7245ee4e809af96d0e9d4c10523053fbad) which was closed with tx [9a8eb21ba53043306b2fec17a66678453248dbf8946f8fd30eb0129ae22296e2](https://www.smartbit.com.au/tx/9a8eb21ba53043306b2fec17a66678453248dbf8946f8fd30eb0129ae22296e2) and finally claimed in [970312a9668fc69c7ce59296a904efc56c72dd5df524814d24746977624e250f](https://www.smartbit.com.au/tx/970312a9668fc69c7ce59296a904efc56c72dd5df524814d24746977624e250f) by the closing party. It could just be that the channels are too tiny to produce any usable outputs after the entire settlement process.

**Comment by Nododot** [comment]
Thank you for the reply.

Yes I funded all the channels.
On #recksplorer I see many channels funded with 10000 sats or less, it seems not an issue for them?

Could it be that my node has published a "previous state" on the channels, and cause the other nodes to claim the funds?

The fact is I don't know where to search. I don't care for the funds lost, but I really would like to understand what happened.

**Comment by Nododot** [comment]
Also note that I find 10 of my channels when executing listchannels, of which 8 are "active".

> $ lightning-cli listchannels | grep 030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9

All this makes no sense to me...

**Comment by cdecker** [comment]
@Nododot the `listchannels` output lists both directions independently. So for every one of your 4 channels that appear in `listpeers`, you'll have one entry that lists your node as the `source`:

```
$ lightning-cli listchannels | jq '.channels[] | select(.source == "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9")'
{
  "source": "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9",
  "destination": "023c5f2b69161742cc49da5be6cb7c940465fc608ff216bafc7573eb31121b22d2",
  "short_channel_id": "512451:1341:0",
  "flags": 1,
  "active": true,
  "public": true,
  "last_update": 1520631566,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 10,
  "delay": 14
}
{
  "source": "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9",
  "destination": "02dcdd7e18b80dc7fd51af34e871901c13f574e4b82325dc74c0beeada5771e8e9",
  "short_channel_id": "512490:2094:0",
  "flags": 1,
  "active": true,
  "public": true,
  "last_update": 1520498834,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 10,
  "delay": 14
}
{
  "source": "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9",
  "destination": "0347ffcb271ef54fa6103fc6392370ce398d1bc98460829f7046cf64026253a68e",
  "short_channel_id": "512490:2097:0",
  "flags": 0,
  "active": true,
  "public": true,
  "last_update": 1520631566,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 10,
  "delay": 14
}
{
  "source": "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9",
  "destination": "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1",
  "short_channel_id": "512557:1341:0",
  "flags": 0,
  "active": true,
  "public": true,
  "last_update": 1520880215,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 10,
  "delay": 14
}
```

and 4 entries that list you as the destination:

```
lightning-cli listchannels | jq '.channels[] | select(.destination == "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9")'
{
  "source": "023c5f2b69161742cc49da5be6cb7c940465fc608ff216bafc7573eb31121b22d2",
  "destination": "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9",
  "short_channel_id": "512451:1341:0",
  "flags": 0,
  "active": true,
  "public": true,
  "last_update": 1520957878,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 1,
  "delay": 144
}
{
  "source": "02dcdd7e18b80dc7fd51af34e871901c13f574e4b82325dc74c0beeada5771e8e9",
  "destination": "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9",
  "short_channel_id": "512490:2094:0",
  "flags": 0,
  "active": true,
  "public": true,
  "last_update": 1520498834,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 10,
  "delay": 14
}
{
  "source": "0347ffcb271ef54fa6103fc6392370ce398d1bc98460829f7046cf64026253a68e",
  "destination": "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9",
  "short_channel_id": "512490:2097:0",
  "flags": 1,
  "active": true,
  "public": true,
  "last_update": 1520631566,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 10,
  "delay": 14
}
{
  "source": "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1",
  "destination": "030c37134dc506e6d2adfdf39be62aec7a637ad5a35b663d60101ec0bbcdc9f5d9",
  "short_channel_id": "512557:1341:0",
  "flags": 1,
  "active": true,
  "public": true,
  "last_update": 1520937590,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 1,
  "delay": 144
}
```

Hence the 8 entries in `listchannels`. This is a further hint that the other channels either never made it to be established, or were closed cleanly.

**Comment by cdecker** [comment]
Digging a bit deeper I checked the channels shown on https://lnmainnet.gaben.win/ by looking up the funding transactions on the blockchain:

```
Channel 512449:1489:0 does not exist (outpoint: 078afc41c4a56fa9c66d0844dd4644f20aebaaaa92c150fc906ee6915ea4e534:0)
Channel 512451:1341:0 is active
Channel 512490:2094:0 is active
Channel 512490:2095:0 does not exist (outpoint: 461b431320292a2b398f96fa0ee12f7245ee4e809af96d0e9d4c10523053fbad:0)
Channel 512490:2096:0 does not exist (outpoint: 94f94dc6999c670f5214a99b166db106234c06f23de77573b87e9cc1abaaf5e8:0)
Channel 512490:2097:0 is active
Channel 512490:2098:0 does not exist (outpoint: c4a1f714a009ba4a6e28e2547c2e53e415940856ab58d16fd8a7f79358670a01:0)
Channel 512557:1340:0 does not exist (outpoint: 5ac50460bed3c96330c0452f1cc115bd37d6539c383f18cf96d2e01069c28fae:0)
Channel 512557:1341:0 is active
Channel 512557:1346:0 does not exist (outpoint: 7d1b60b5f77306437dcde65d27ceb94c5e69cbcab3be01427202b58cf1e3c549:0)
Channel 512559:869:0 does not exist (outpoint: 0532c2350efe25d52a74873bea251a4b9306e0b9a492bcb3a9ba70224768f861:0)
Channel 512658:2154:0 does not exist (outpoint: f054596ef9cb17ad1837290aa69028516f2f3dc55cf82538ea02e75b8267b75f:0)
Channel 512787:730:1 does not exist (outpoint: 235284edb76ff41e375da1426061892a81a5c2bb61064d57cf4baa4b3c867924:1)
Channel 512797:921:0 does not exist (outpoint: 9668250e885d40eb34e6b3138f0d855fbd2642c5b9d93c0814f5de6622b0705a:0)
Channel 512860:213:0 does not exist (outpoint: a6b1496ff8bfa5fdcfa747fe0654a390bb70b4bdb4ce04c35c3f869b8d00a7bd:0)
Channel 512896:1640:1 does not exist (outpoint: 2188788066c39861e3ca8b198a29fd396c20fe7f2fa5d255c9eae436a1a38511:1)
```

We can see that all but 4 channels were closed. Taking the last channel in the list for example, the funding transaction [2188788066c39861e3ca8b198a29fd396c20fe7f2fa5d255c9eae436a1a38511](https://www.smartbit.com.au/tx/2188788066c39861e3ca8b198a29fd396c20fe7f2fa5d255c9eae436a1a38511) was spent by a unilateral close transaction [aab99ea4aa13e4e8af930852eae17bb217b0abe022aba6414fb6d9537b11e709](https://www.smartbit.com.au/tx/aab99ea4aa13e4e8af930852eae17bb217b0abe022aba6414fb6d9537b11e709) (unilateral because it pays to scripthash) and finally returned to singlesig in [cb5e0f684940f994c9a1c9799596477d972fc55546e37cba237433e1e0d54f37](https://www.smartbit.com.au/tx/cb5e0f684940f994c9a1c9799596477d972fc55546e37cba237433e1e0d54f37). That output is then again collected into a new P2WSH, potentially a new channel.

I think the big confusion comes from https://lnmainnet.gaben.win/ showing outdated and long closed channels.

**Comment by Nododot** [comment]
Hi,
Thank you very much for the analysis.
Maybe there is some logic in this mess after all!

Ok so the 12 missing channels have been closed.
I didn't close them, so I guess the other party did it.
I have no idea why, I don't know them and never contacted them.

Then my last question is, why didn't I receive my funds back?
How can I check this?

**Comment by cdecker** [comment]
Let's see for some of these channels:

`512449:1489:0`

 - Spent in `fbbe75bd4fe0f7ebbedacdce52dbae404dbbc86d0c7551845b758ce596eb1688` creates 2 outputs:
   - `512849:2458:0` P2PKH (return funds to closee)
   -  `512849:2458:1` P2WSH (return funds to closer), later claimed by `99090df67f543f1eb31f8454f605c32318f313fde6526b267ff4817881c34698`, but output is too small ($0.85), and is consumed by fees.

`512490:2095:0`

 - Unilaterally closed in `9a8eb21ba53043306b2fec17a66678453248dbf8946f8fd30eb0129ae22296e2`, just one output to closer
 - Timelocked output reclaimed by `970312a9668fc69c7ce59296a904efc56c72dd5df524814d24746977624e250f`
 - Collected into a non-segwit P2PKH in `945bcb4805bf52fbb3fa2af3ffa90620dcf27d141da0d621ea3a33c6be1daf10`
 - Currently sitting as outputs 0 and 1 of tx `92f46c277bcfb1b80c9536f899899529c42974d3e877e2b1f7ebf9ed241113dd`

This may have been a withdraw to an external address?

`512490:2096:0`

 - Collaboratively closed in `839337efb1406ebd4ff9fba2c5cf61d9823c4ba7b3a0cc16f671c19c3d4d5a92` funds returned to the internal wallet
 - Also collected into `945bcb4805bf52fbb3fa2af3ffa90620dcf27d141da0d621ea3a33c6be1daf10`

The other channels also pretty much follow either the to-null or the collect pattern so I'll omit the exact trace here.
