### ISSUE TITLE
`listfunds` should also display the address that onchain funds are in

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#1227]
Inspired by #1226

**Comment by izgzhen** [comment]
I'd like to pick up this issue :)

**Comment by izgzhen** [comment]
@ZmnSCPxj I wonder whether the `struct ext_key* bip32_base` represent the address where the on-chain funds get deposited? or maybe some keys derived from this key?

**Comment by ZmnSCPxj** [comment]
Your guess is probably better than mine, as I have not actually looked at any of the code....
