### ISSUE TITLE
sending `funding_locked` after both `channel_reestablish.next_local_commitment_number == 1`

### ISSUE THREAD

**Issue by nayuta-ueno** [ElementsProject/lightning#1228]
### Issue and Steps to Reproduce

commit id: 4ffd5e213b9099a676cf417c2a00d940cedd7e80

1. (no channel)
2. connect nodes, `init`, `open_channel/accept_channel/funding_created/funding_signed` and broadcast funding transaction
3. wait `minimum_depth` ...
4. disconnect our node if confirmation reach `minimum_depth` and exchange `funding_locked`.
5. connect and exchange `init` message
6. exchange `channel_reestablish`
7. both `channel_reestablish.next_local_commitment_number == 1`, so I send `funding_locked` to c-lightning.

`c-lightning` returns `error` message:

```
bad reestablish msg: WIRE_FUNDING_LOCKED ...
```

[BOLT#2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements-14)

```
A node:
    if next_local_commitment_number is 1 in both the channel_reestablish it sent and received:
        MUST retransmit funding_locked.
```

### `getinfo` output

```
after error message

{
  "id": "02216cd312fb0de20397fd11ed720bea75dec3e3369357a8b30b12839feb81e821",
  "port": 9735,
  "address": [],
  "version": "v0.5.2-2016-11-21-2347-g4ffd5e2",
  "blockheight": 1288341,
  "network": "testnet"
}
```

**Comment by ZmnSCPxj** [comment]
This is likely to be the point where we send the error to you: https://github.com/ElementsProject/lightning/blob/4ffd5e213b9099a676cf417c2a00d940cedd7e80/channeld/channel.c#L1826-L1835

Note that c-lightning performs the above check after it sends its own `channel_reestablish`.  Thus, at the point that the error happened, c-lightning was still at the "exchanging `channel_reestablish`" stage, suggesting that ucoind did not send `channel_reestablish`.

Setting the c-lightning log to `io` level should show exactly what messages got received and sent by the peers.  Could you show the c-lightning log at `io` level?

**Comment by nayuta-ueno** [comment]
Thank you @ZmnSCPxj .

>  Thus, at the point that the error happened, c-lightning was still at the "exchanging channel_reestablish" stage, suggesting that ucoind did not send channel_reestablish.

Sorry !
I send `funding_locked` before `channel_reestablish`.

close this.
