### ISSUE TITLE
LN Mainnet - CHANNELED AWAITING LOCKIN...

### ISSUE THREAD

**Issue by realcryptominer** [ElementsProject/lightning#1243]
Hello,
I have successfully installed and synced Bitcoind & C-Lightning node on Linux Ubuntu 17.10 VPS.
```
root@vmi168564:~/builds/lightning# bitcoin-cli getblockcount
514176
root@vmi168564:~/builds/lightning# cli/lightning-cli dev-blockheight
{ "blockheight" : 514176 }
```

I have funded the channel with US$10 i.e. 0.0013102

https://blockchain.info/address/3HeSsWiscn7wjxCdc6knKyfi2vaXmGWPzu

I have created channel with a node and funded it with 40000 Satoshis.

Its been now more than 15 hours and still the channel state is awaiting lockin only. On blockchain if you see above then it has already get 80+ Confirmations.
Here is what it says.
```
root@vmi168564:~/builds/lightning# cli/lightning-cli listpeers
{ "peers" :
        [
                { "id" : "024bd94f0425590434538fd21d4e58982f7e9cfd8f339205a73deb9c0e0341f5bd", "connected" : true, "netaddr" :
                        [ "165.227.69.151:9735" ], "alias" : "CL.rompert.com🔵 ", "color" : "0000ff", "channels" :
                        [
                                { "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "short_channel_id" : "514097:798:0", "funding_txid" : "3b10a79a607bbfa37ff9367b494f40c215b1bc08ef626166b65695f573dec240", "msatoshi_to_us" : 40000000, "msatoshi_total" : 40000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "their_to_self_delay" : 144, "our_to_self_delay" : 144, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
                                        [ "CHANNELD_AWAITING_LOCKIN:Reconnected, and reestablished.", "CHANNELD_AWAITING_LOCKIN:We've confirmed funding, they haven't yet." ] } ] } ] }
```

Kindly give your opinion.
Thank You

**Comment by ZmnSCPxj** [comment]
The other side has not confirmed they have seen the funding transaction.  See `status` field: `[ "CHANNELD_AWAITING_LOCKIN:Reconnected, and reestablished.", "CHANNELD_AWAITING_LOCKIN:We've confirmed funding, they haven't yet." ] `

The other side might not have caught up with the blockchain, or is buggy.

**Comment by realcryptominer** [comment]
okk.. I see....

So what are my options now? How should I ideally deal with this situation?

**Comment by cdecker** [comment]
There's very little we can do on our end. The daemon running on cl.rompert.com apparently is not sending the lockin message. This could either be because they are running an outdated version, or a reconnect incompatibility with `lnd`
