### ISSUE TITLE
Fund lost when I withdraw outside wallet

### ISSUE THREAD

**Issue by bigstonebtc** [ElementsProject/lightning#1244]
### Issue and Steps to Reproduce
Fund lost happened when I tried to withdraw my funds to another wallet.
$  lightning-cli withdraw 3MYbtcaddressxxxxxxxxxxxx  all
There was no response for a minute, so I killed process with Ctl-C to try again.
No withdrawal tx has issued. 
After killing process, the funds lost.
I can not see any funds with "listfunds" command.

### `getinfo` output

$ lightning-cli listfunds
{ "outputs" : 
	[  ] }

**Comment by ZmnSCPxj** [comment]
Try `dev-rescan-outputs` command and see `listfunds` again.

**Comment by bigstonebtc** [comment]
solved !
