### ISSUE TITLE
UNIQUE constraint failed: utxoset.txid, utxoset.outnum

### ISSUE THREAD

**Issue by sui77** [ElementsProject/lightning#1280]
### Issue and Steps to Reproduce
lightningd always dies after "Adding block 515255", guess it's trying to insert some duplicate dataset into sqlite or something? log => https://gist.github.com/sui77/6aace6500b5d3244553b26f2d755a7ea

### `getinfo` output
{ "id" : "0318971cae109776f58101f07a6c1d1e68c4780a05960b5cbfff1620d3c06cb50c", "port" : 9735, "address" :
	[
		{ "type" : "ipv4", "address" : "148.251.19.39", "port" : 9735 },
		{ "type" : "ipv6", "address" : "2a01:4f8:201:8026::2", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2368-g489d8d0", "blockheight" : 513764, "network" : "bitcoin" }

**Comment by cdecker** [comment]
That shouldn't happen. Can you share the outputs of this in a gist:

```
sqlite3 $HOME/.lightning/lightningd.sqlite3 "SELECT hex(txid), outnum blockheight, spendheight FROM utxoset"
```

Hopefully that tells us if there is a real duplicate and where it came from.

**Comment by sui77** [comment]
https://gist.github.com/sui77/81999a79fbfef30e8b6b83227ce40ab3

**Comment by danielalexiuc** [comment]
I'm getting the same thing today, can provide the same dump if it helps.

**Comment by cdecker** [comment]
@danielalexiuc are you getting the error at the same blockchain height?

**Comment by sui77** [comment]
I wanted to add some log_debug()'s to log the affected txid but I've no experience in C. Can you advice? https://gist.github.com/sui77/6f8dd646d6d14d301aeb3dcf60b17767

Anyways, at least I logged the amount so I can assume it's failing with this tx: https://blockchain.info/de/tx/466b8ee63d1f150088f4eb5ee534e9528d6ec4bb9ad3dcad9d4c3cfff1deebb5 but that txid is not in my lightningd.sqlite database...


> 2018-03-27T13:31:21.573Z lightningd(21843): Adding block 515256: 0000000000000000003cf0db073748440360c56367a6376f5e211a7625dfb12a
2018-03-27T13:31:21.574Z lightningd(21843): j: 1
2018-03-27T13:31:21.574Z lightningd(21843): height: 515256
2018-03-27T13:31:21.574Z lightningd(21843): i: 37
2018-03-27T13:31:21.574Z lightningd(21843): script:
2018-03-27T13:31:21.574Z lightningd(21843): amount: 936736
2018-03-27T13:31:21.574Z lightningd(21843): wallet_utxoset_add: UNIQUE constraint failed: utxoset.txid, utxoset.outnum
2018-03-27T13:31:21.574Z lightningd(21843): FATAL SIGNAL 6 RECEIVED

**Comment by cdecker** [comment]
That's excellent work @sui77, it appears that when adding tx outppint 515256:37:1, it fails since the DB already contains that outpoint. The tx hash is `466b8ee63d1f150088f4eb5ee534e9528d6ec4bb9ad3dcad9d4c3cfff1deebb5`, but in the sqlite3 output you need to look for `b5ebdef1ff3c4c9daddcd39abbc46e8d52e934e55eebf48800151f3de68e6b46` since we store hashes in their non-inverted form.

Is this the first block that is being added or does it crash later in the process? We are using foreign key constraints to cascade block deletions to outpoints when rewinding the blocks:

https://github.com/ElementsProject/lightning/blob/master/wallet/db.c#L220-L228

What version of sqlite3 are you compiling against?

**Comment by sui77** [comment]
> sqlite3 $HOME/.lightning/lightningd.sqlite3 "SELECT hex(txid), txindex, satoshis, outnum, blockheight, spendheight FROM utxoset where hex(txid) like 'B5EB%'"
B5EBDEF1FF3C4C9DADDCD39ABBC46E8D52E934E55EEBF48800151F3DE68E6B46|27|936736|1|515256|

same amount but txid=27 instead of 37 as in the logs. if i'm not wrong the 27th tx in that block is b67efb33a464482f09b9f8081cfbd8b08c13af8ba6d6a461ed700b280c2ee96e (how do i figure out the other doubleSHAwhatever form?) - looks quite impossible to have that row in the db :)

> What version of sqlite3 are you compiling against?
libsqlite3-dev is already the newest version (3.11.0-1ubuntu1). (?)

**Comment by sui77** [comment]
I think I will just delete the existing row and see what happens. What do you think?

**Comment by sui77** [comment]
I think all txs with height 515256 (https://gist.github.com/sui77/81999a79fbfef30e8b6b83227ce40ab3#file-lightningsql-L3024-L3057) were somehow saved wrong, deleting them all fixed it. Thanks for helping @cdecker  👍

**Comment by cdecker** [comment]
Happy it worked, but I'd still like to understand why that happened, especially because @danielalexiuc reported the same issue.

**Comment by cdecker** [comment]
For context: I think this may be built against a sqlite3 version prior to 3.6.9 which [introduced foreign key](https://sqlite.org/foreignkeys.html) support including the support for cascade, or the library was compiled without foreign key support (very unlikely I think).

**Comment by danielalexiuc** [comment]
@cdecker Yes, at the same height:

https://gist.github.com/danielalexiuc/2ec39b7f5f88f74fd2af54d41a342f2e

**Comment by danielalexiuc** [comment]
@sui77 What exactly did you do to fix this?

**Comment by cdecker** [comment]
@danielalexiuc if you don't have a channel open, could you share the sqlite3 file? I'm having a bit of trouble reconstructing the issue on my end. Also which OS are you using (asking because of my suspicion that this is related to the libsqlite3-dev version)?

**Comment by sui77** [comment]
@danielalexiuc make a backup of your $HOME/.lightning/lightningd.sqlite3 first + no guarantee :)
`sqlite3 $HOME/.lightning/lightningd.sqlite3 "DELETE FROM utxoset WHERE blockheight= 515256"`

@cdecker how do I find which libsql version I have? I've set up the node as stated in the docs on a fresh ubuntu xenial server. And if you want I can also provide you a backup of my sqlite3.

**Comment by danielalexiuc** [comment]
@cdecker I've got a bunch of channels open: https://lightning.team/nodes/03d6ebe2c68d4f7647dfcf56b22efa144f0c92e94b7c3aaa353615946d7c390c12

Is it still safe to share the sqlite3 file?

I'm using: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64)

**Comment by sui77** [comment]
fun fact: @danielalexiuc we had a channel together, my node is ln.sui.li :)

**Comment by danielalexiuc** [comment]
@sui77 haha good times :)

**Comment by cdecker** [comment]
Maybe I can debug the binary you guys created. Could you send me the compiled `lightningd/lightningd` binary? What blockheight do the syncs start when you start the daemon? I'll try to sync from the lowest height in your DB, then stop and then resync from the start height at which it is failing, that should be sufficient.

**Comment by danielalexiuc** [comment]
[lightningd.zip](https://github.com/ElementsProject/lightning/files/1865042/lightningd.zip)

Hmm I didn't record where the blockheight sync started - hopefully you can reproduce the error.

**Comment by FeedTheWeb** [comment]
2 CL nodes today crashed at the same time

v0.5.2-2016-11-21-2431-ge25297d
```
+192638.245207567 lightningd(7424):DEBUG: Adding block 1289780: 000000002aad804dc10ade59cdcd953dd0455520849a5416075180072f32bf76
+192638.246492741 lightningd(7424):BROKEN: wallet_utxoset_add: UNIQUE constraint failed: utxoset.txid, utxoset.outnum
+192638.801334264 lightningd(7424):BROKEN: FATAL SIGNAL 6 RECEIVED
+192638.824131529 lightningd(7424):BROKEN: backtrace: lightningd/log.c:494 (log_crash) 0x415dfc
+192638.824218572 lightningd(7424):BROKEN: backtrace: (null):0 ((null)) 0x7f4b6826b4af
+192638.824242364 lightningd(7424):BROKEN: backtrace: (null):0 ((null)) 0x7f4b6826b428
+192638.824260326 lightningd(7424):BROKEN: backtrace: (null):0 ((null)) 0x7f4b6826d029
+192638.824278942 lightningd(7424):BROKEN: backtrace: lightningd/log.c:592 (fatal) 0x41624d
+192638.824649217 lightningd(7424):BROKEN: backtrace: wallet/db.c:296 (db_exec_prepared_) 0x45223a
+192638.825804380 lightningd(7424):BROKEN: backtrace: wallet/wallet.c:2077 (wallet_utxoset_add) 0x45b1f5
+192638.826364003 lightningd(7424):BROKEN: backtrace: lightningd/chaintopology.c:427 (topo_add_utxos) 0x40738b
+192638.826390952 lightningd(7424):BROKEN: backtrace: lightningd/chaintopology.c:444 (add_tip) 0x407474
+192638.826412083 lightningd(7424):BROKEN: backtrace: lightningd/chaintopology.c:507 (have_new_block) 0x407825
+192638.826946243 lightningd(7424):BROKEN: backtrace: lightningd/bitcoind.c:417 (process_rawblock) 0x404a8a
+192638.826972348 lightningd(7424):BROKEN: backtrace: lightningd/bitcoind.c:189 (bcli_finished) 0x404044
+192638.827233304 lightningd(7424):BROKEN: backtrace: ccan/ccan/io/poll.c:183 (destroy_conn) 0x465e95
+192638.827259804 lightningd(7424):BROKEN: backtrace: ccan/ccan/io/poll.c:189 (destroy_conn_close_fd) 0x465eb5
+192638.827779880 lightningd(7424):BROKEN: backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x470504
+192638.827804417 lightningd(7424):BROKEN: backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x4709b5
+192638.827824860 lightningd(7424):BROKEN: backtrace: ccan/ccan/tal/tal.c:511 (tal_free) 0x470de7
+192638.828142775 lightningd(7424):BROKEN: backtrace: ccan/ccan/io/io.c:443 (io_close) 0x464aa2
+192638.828166564 lightningd(7424):BROKEN: backtrace: ccan/ccan/io/poll.c:314 (io_loop) 0x4662a4
+192638.828526323 lightningd(7424):BROKEN: backtrace: lightningd/lightningd.c:407 (main) 0x4145ac
+192638.828551175 lightningd(7424):BROKEN: backtrace: (null):0 ((null)) 0x7f4b6825682f
+192638.828567745 lightningd(7424):BROKEN: backtrace: (null):0 ((null)) 0x403448
+192638.828581627 lightningd(7424):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff

```

v0.5.2-2016-11-21-2371-gcbe0b2d :

```
+469735.245631413 lightningd(31660):DEBUG: Adding block 1289780: 000000002aad804dc10ade59cdcd953dd0455520849a5416075180072f32bf76
+469735.256032827 lightningd(31660):BROKEN: wallet_utxoset_add: UNIQUE constraint failed: utxoset.txid, utxoset.outnum
+469736.184201022 lightningd(31660):BROKEN: FATAL SIGNAL 6 RECEIVED
+469736.200178807 lightningd(31660):BROKEN: backtrace: lightningd/log.c:493 (log_crash) 0x415b6f
+469736.200251400 lightningd(31660):BROKEN: backtrace: (null):0 ((null)) 0x7f6cdfb944af
+469736.200271892 lightningd(31660):BROKEN: backtrace: (null):0 ((null)) 0x7f6cdfb94428
+469736.200286930 lightningd(31660):BROKEN: backtrace: (null):0 ((null)) 0x7f6cdfb96029
+469736.200302430 lightningd(31660):BROKEN: backtrace: lightningd/log.c:586 (fatal) 0x415fc0
+469736.200547388 lightningd(31660):BROKEN: backtrace: wallet/db.c:277 (db_exec_prepared_) 0x451d09
+469736.201244540 lightningd(31660):BROKEN: backtrace: wallet/wallet.c:2044 (wallet_utxoset_add) 0x45aa47
+469736.201609462 lightningd(31660):BROKEN: backtrace: lightningd/chaintopology.c:427 (topo_add_utxos) 0x407349
+469736.201632170 lightningd(31660):BROKEN: backtrace: lightningd/chaintopology.c:444 (add_tip) 0x407432
+469736.201650225 lightningd(31660):BROKEN: backtrace: lightningd/chaintopology.c:507 (have_new_block) 0x4077e5
+469736.201995287 lightningd(31660):BROKEN: backtrace: lightningd/bitcoind.c:414 (process_rawblock) 0x404a4d
+469736.202017363 lightningd(31660):BROKEN: backtrace: lightningd/bitcoind.c:186 (bcli_finished) 0x404007
+469736.202204315 lightningd(31660):BROKEN: backtrace: ccan/ccan/io/poll.c:183 (destroy_conn) 0x4656e7
+469736.202226281 lightningd(31660):BROKEN: backtrace: ccan/ccan/io/poll.c:189 (destroy_conn_close_fd) 0x465707
+469736.202552856 lightningd(31660):BROKEN: backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x46fd56
+469736.202573879 lightningd(31660):BROKEN: backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x470207
+469736.202591885 lightningd(31660):BROKEN: backtrace: ccan/ccan/tal/tal.c:511 (tal_free) 0x470639
+469736.202806086 lightningd(31660):BROKEN: backtrace: ccan/ccan/io/io.c:443 (io_close) 0x4642f4
+469736.202826899 lightningd(31660):BROKEN: backtrace: ccan/ccan/io/poll.c:314 (io_loop) 0x465af6
+469736.203069090 lightningd(31660):BROKEN: backtrace: lightningd/lightningd.c:407 (main) 0x41431f
+469736.203090294 lightningd(31660):BROKEN: backtrace: (null):0 ((null)) 0x7f6cdfb7f82f
+469736.203105242 lightningd(31660):BROKEN: backtrace: (null):0 ((null)) 0x403448
+469736.203116992 lightningd(31660):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

**Comment by cdecker** [comment]
@FeedTheWeb do you have any channels open? If not, could you share the DB with me?

**Comment by cdecker** [comment]
@FeedTheWeb shared his DB with me and I am able to reproduce the crash, but not what it took to create the crashing DB. I might have a lead however: did you (@FeedTheWeb, @danielalexiuc, @sui77) use the `--daemon` command line option?

**Comment by FeedTheWeb** [comment]
yes, I probably used the `--daemon` option.  

My guess (not sure) is that it happened after trying to create a invoice with a too large amount.

**Comment by sui77** [comment]
running with --daemon, yes.

Still wondering about the cause that all the tx nums were wrong in the database. Could it be that all those transactions were inserted with a later to be orphaned block and then failing with the real one?

**Comment by cdecker** [comment]
Could you try PR #1310? It should not only make sure that `--daemon` opens connections correctly, it also includes a cleanup migration to fix your DBs.

**Comment by danielalexiuc** [comment]
Yes I used the --daemon option too.
