### ISSUE TITLE
Auto-reconnect to peers we have channels to

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#1281]
#1274 brings up that our peers with whom we have channels to, often end up having `connected: false`.

One way to help this is to have a periodic auto-reconnect every 5 to 10 minutes, to all known peers with whom we have channels to.

1.  Modify `connect` so it can be invoked internally.  See what I did in `lightningd/pay.c` to `sendpay` command: I made a public `send_payment` function that is given a callback for completion or failure, as well as a `struct sendpay_result` for the result of payment.  This is needed so that `connect` can be invoked internally by lightningd.
2.  Set up a tweakable autoconnect system (can set autoonnect cycle time range by command line, default 5 to 10 minutes).  Make sure to randomize the time between autoconnect attempts to reduce network spike.  Pay attention to `addr_unknown` field from the gossip connection failure message: if this is true then we really cannot connect to the peer due to lack of knowledge of address.

**Comment by CubicEarth** [comment]
I can see how invoking ```connect``` can make sense for now, in the name of simplicity. Longer term, it seems like the periodic check would be better if it happened more frequently (every minute or two), but with a smaller number of pings, perhaps 2, rather than the 10 tries that ```connect``` currently makes.

**Comment by ZmnSCPxj** [comment]
A better solution would be to let `connect` specify how many tries max to make and how long between each try as optional extra args. Then the autoreconnect can give values reasonable for its operation.
