### ISSUE TITLE
`tmpctx` leaked?

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#1287]
Hi, although we use `setup_tmpctx` and `clean_tmpctx` now, I am uncertain, how often these are actually cleared.

* gossipd:
    * We never call `setup_tmpctx` in gossipd code (we do call `setup_tmpctx` in its tests).
    * We never call `clean_tmpctx` in gossipd code.
* lightningd
    * We never call `clean_tmpctx` in lightningd code.
* hsmd
    * We never call `setup_tmpctx` or `clean_tmpctx` in hsmd code.

The comment for the new `tmpctx` system suggests that it is cleared in the IO loop, but I am uncertain about how this hooks into the IO loop at say `ccan/io/io.c`.  `setup_tmpctx` does not do anything other than set `tmpctx`.  The `io_loop` based daemons seem not to use `clean_tmpctx` in particular: the concerning thing here is that `io_loop` blocks until there are no more events, `io_break` is done, or some timer fires.  So it is not sufficient to call `clean_tmpctx` in the loop that calls `io_loop` unless we have some regular timer that triggers and forces `clean_tmpctx` to execute.

**Comment by cdecker** [comment]
It's cleared in `debug_poll` which overrides the `poll` function in the `io_loop`. For example this registers `debug_poll` in `gossipd` to be run before every call to `poll`:

https://github.com/ElementsProject/lightning/blob/master/gossipd/gossip.c#L2091

Admittedly `debug_poll` is a misnomer now that it's no longer running solely in the `DEVELOPER=1` configuration :wink:

**Comment by ZmnSCPxj** [comment]
I understand.  hsmd, lightningd, and gossipd all perform this setup. But how about the lack of `setup_tmpctx` in hsmd and gossipd?

**Comment by rustyrussell** [comment]
setup_daemon() calls setup_tmpctx(), so this is indeed called for all subdaemons.  Only lightningd has to do this manually.

Now, it's interesting that valgrind doesn't complain about the leak of tmpctx: I'll add subdaemon_shutdown() for this.

**Comment by ZmnSCPxj** [comment]
Okay, thank you. My understanding, valgrind by default will not treat objects referred to directly or indirectly from global variables as a "failing" memory leak -- they only get reported as "possibly leaked".  Since `tmpctx` is global, and its content has a hidden header that is essentially a list of its children, then valgrind most likely treated as "possibly leaked" and not definitely leaked and will not raise an error (I think).
