### ISSUE TITLE
Invoices with integer labels error on searching -  "label '25' is not a string"

### ISSUE THREAD

**Issue by redstorm1** [ElementsProject/lightning#1291]
### Issue and Steps to Reproduce
Create a invoice with a integer label
lightning-cli invoice 3333 25 25 600 <- this now fails also, however if you add a single character like "i25" it allows it.
amount 3333
label 25
description 25
timeout 600s

query this invoice by:
lightning-cli listinvoices 25

affects invoice, delinvoice as well. i

Now returns an error instead of the status of the queried invoice.
{ "code" : -1, "message" : "label '25' is not a string" }

### `getinfo` output
{ "id" : "0392419c02fbca83ae8d541cd2f48b662b2238ed8e1e92a93547c23ba32f0d64c6", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "203.86.204.88", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2422-g286cfef", "blockheight" : 1289335, "network" : "testnet" }

**Comment by rustyrussell** [comment]
That was me; we no longer allow numbers as labels (nor null). I can fix this though, by treating them as strings, but be warned that it means label 1 is different from 01 because they're not really numbers.

Is that ok?

**Comment by redstorm1** [comment]
I have modified my app to now prepend invoice_ to the id i was assigning from a DB to track invoices, effectively using the label field as an invoice number.

Would make life easier if the spec included a invoice number field seeing as we are dealing with invoices...

I would be happy with treating numbers as strings in the label field, searching for 01 is different from 1 so wouldn't have broken my app.

**Comment by redstorm1** [comment]
using invoice_25 for label and description now appears to create non valid bolt11 invoices.

./lightning-cli decodepay lntb2m1pdt4ckwpp5m2jljl2x90hh8sx66v4vv045ryu0nvsh6yytzgvw00e82r7c5dmqdqsd9h8vmmfvdj47dp4xqzjccqpxzjw69wd46vrr8ekrefjq3gl3lmrfgqy5cxzrsv2qpmucxhlwrh7kydt93gyjltmvuphp8a32yy4dhrkaa00c2aughzgg850hk0svkqs
{ "code" : -1, "message" : "Invalid bolt11: Bad bech32 string" }

and from lightning labs lncli
 lncli payinvoice lntb2m1pdt4ckwpp5m2jljl2x90hh8sx66v4vv045ryu0nvsh6yytzgvw00e82r7c5dmqdqsd9h8vmmfvdj47dp4xqzjccqpxzjw69wd46vrr8ekrefjq3gl3lmrfgqy5cxzrsv2qpmucxhlwrh7kydt93gyjltmvuphp8a32yy4dhrkaa00c2aughzgg850hk0svkqs
[lncli] rpc error: code = Unknown desc = checksum failed. Expected jen2ye, got 0svkqs.

is underscore allowed in these fields?

**Comment by ZmnSCPxj** [comment]
>  it means label 1 is different from 01 because they're not really numbers.

https://json.org/ shows that `01` in the formal JSON spec is not allowed: if the number starts with 0, the next character should be a a period, or it should be the entire number (it does allow `-0`, though).  So this should not be an issue.  Whether `lightning-cli` conforms correctly is a different issue, but one which might be somewhat relevant.  Unsure how jsmn treats `01`, though: will it error on this?
