### ISSUE TITLE
Fee setting issues

### ISSUE THREAD

**Issue by sumBTC** [ElementsProject/lightning#1300]
EDIT: Oops, Christian Decker was right (of course) it's dev-setfees,  "fee" was my own shell alias :-)

When opening a channel I often set the fee by hand. for example:
> lightning-cli dev-setfees 

{ "immediate" : 1900, "normal" : 500, "slow" : 400}

> lightning-cli dev-setfees 3000 3000 3000 
> lightning-cli fundchannel 020b751f34...

I think there should then be the possibility to set the fee back to the original dynamic values, like:
> lightning-cli dev-setfees default

If that possibility already exists, it should be added to "lightning-cli help".

Also, when I set the fee by hand, I get the impression that fee setting is also used when negotiating a channel close. Is that right? If so, shouldn't these two fee settings be independent of each other or have the possibility to be independent of each other.

**Comment by cdecker** [comment]
I think you mean the `dev-setfees` RPC call. It's a developer-only RPC call that should not be used in normal operation. Setting the `wontfix` tag.

**Comment by sumBTC** [comment]
Maybe the fee RPC call has been changed into dev-setfees but in the version I was using it was still fee. Even if it's a developer-only RPC call, a developer should be able to turn it off again, in my opinion. Also, automatically guessing the correct fee isn't (always) easy, so wanting to set it by hand shouldn't be such an unusual case.
