### ISSUE TITLE
Feature: Add fee field on listpayments JSON response

### ISSUE THREAD

**Issue by szollo** [ElementsProject/lightning#1306]
### Issue and Steps to Reproduce

On the output of `lightning-cli listpayments`, it'd be good to see how much was paid in fees, possibly denominated in msatoshi. Currently the JSON response only shows:
```
{
  "payments": [
    {
      "id":,
      "payment_hash": "",
      "destination": "",
      "msatoshi":,
      "timestamp":,
      "created_at":,
      "status": "",
      "payment_preimage": ""
    }
  ]
}
```

**Comment by ZmnSCPxj** [comment]
#1261 added `msatoshi_sent`, which is the total paid.  Fees are `msatoshi_sent - msatoshi`.  Is that not sufficient?

(#1261 was added last week, what version are you on?)

**Comment by szollo** [comment]
Thanks @ZmnSCPxj, I'll upgrade - I'm running`v0.5.2-2016-11-21-1822-gf21cb57` and my mainnet payment was done back in early February.

```
# lightning-cli --version
v0.5.2-2016-11-21-1822-gf21cb57
aka. Bitcoin Savings & Trust Daily Interest II
Built with:
```

**Comment by ZmnSCPxj** [comment]
Well, it will not have been recorded in the database if so --- post-upgrade you will see `msatoshi_sent == msatoshi` for payments made before the upgrade.  The information was never recorded then and not reconstructible.

Payments after upgrading will correctly record the `msatoshi_sent`, however.
