### ISSUE TITLE
98% CPU usage

### ISSUE THREAD

**Issue by mehmetaksoy** [ElementsProject/lightning#1337]
Hi, my node has 4vcpu 8gb ram and my CPU usage is 98%. Is there a mistake?

```
instance-1:~# lightning-cli listconfigs
{
  "# version": "v0.5.2-2016-11-21-2367-g5737853",
  "port": 9735,
  "rgb": "0000ff",
  "alias": "www.bankofcrypto.info",
  "pid-file": "lightningd-bitcoin.pid",
  "channel-update-interval": 604800,
  "log-level": "DEBUG",
  "log-prefix": "lightningd(1):",
  "lightning-dir": "/root/.lightning",
  "rpc-file": "lightning-rpc",
  "daemon": "false",
  "ignore-fee-limits": false,
  "locktime-blocks": 144,
  "max-locktime-blocks": 432,
  "anchor-onchain": 10,
  "anchor-confirms": 3,
  "max-anchor-confirms": 10,
  "commit-fee-min": 200,
  "commit-fee-max": 2000,
  "commit-fee": 500,
  "default-fee-rate": 40000,
  "cltv-delta": 14,
  "cltv-final": 8,
  "max-htlc-expiry": 720,
  "bitcoind-poll": "30s",
  "commit-time": "10ms",
  "fee-base": 1000,
  "fee-per-satoshi": 10,
  "ipaddr": "35.231.87.119:9735",
  "network": "bitcoin",
  "allow-deprecated-apis": true,
  "autocleaninvoice-cycle": 0,
  "autocleaninvoice-expired-by": 0,
  "dev-no-reconnect": "false",
  "dev-fail-on-subdaemon-fail": "false",
  "dev-broadcast-interval": 60000
}
```

also, Also, when you enter the dev-listaddrs command, hundreds of wallets come out. Is this normal? (currently there are 751 wallets)

```
instance-1:~# lightning-cli dev-listaddrs
{ "addresses" : 
        [ 
                { "keyidx" : 0, "pubkey" : 
                   .
                   .
                   . 
                { "keyidx" : 751, "pubkey" : "", "p2sh" : "", "p2sh_redeemscript" : "", "bech32" : "", "bech32_redeemscript" : "" } ] 
```
                
is my version up to date? and update command? Is there a command that will default to all settings?

**Comment by cdecker** [comment]
Thanks for reporting this @mehmetaksoy, my guess is that the node is attempting to catch up with the blockchain (`lightning-cli dev-blockheight` might return a height that is lower than `bitcoin-cli getblockchaininfo`), and that the large number of addresses is slowing down processing.

I wonder where the addresses come from, since we only generate new ones when funding a channel, when `newaddr` is called, or when we `withdraw`. Did you perform any of these a large number of times? As to the cpu consumption: the wallet is not optimized currently, but given time we will get to that as well :wink: 

Any chance you have experience collecting `perf` details? The following would create traces that allow us to figure out where most of the time is spent:

```
perf record -F 250 -a -g -- lightningd/lightningd --log-level=debug --network=bitcoin
```

**Comment by ZmnSCPxj** [comment]
Is this the same node you reported for #1285? I believe you had a large number of 100 bit and 200 bit channels then, so it seems likely that you closed them and now have ~750 txouts you can spend onchain.

**Comment by mehmetaksoy** [comment]
instance-1:~# lightning-cli dev-blockheight
{ "blockheight" : 517120 }

instance-1:~# bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 517120,
  "headers": 517120,
  "bestblockhash": "00000000000000000033f630985edfe8652b682e5a1f0596549807e0b06d
d361",
  "difficulty": 3511060552899.72,
  "mediantime": 1523128560,
  "verificationprogress": 0.9999891243393534,
  "initialblockdownload": false,
  "chainwork": "000000000000000000000000000000000000000001728eda864f84d45ee500e9
",
  "size_on_disk": 186897490492,
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 1462060800,
      "timeout": 1493596800,
      "since": 419328
    },
    "segwit": {
      "status": "active",
      "startTime": 1479168000,
      "timeout": 1510704000,
      "since": 481824
    }
  },
  "warnings": ""
}
root@instance-1:~#



I did not run perf command.



..........instance-1:~$ sudo -s
root@instance-1:~# echo 0 | sudo tee
0
root@instance-1:~# /proc/sys/kernel/kptr_restrict
bash: /proc/sys/kernel/kptr_restrict: Permission denied
root@instance-1:~# perf record -F 250 -a -g -- lightningd/lightningd --log-level
=debug --network=bitcoin
Workload failed: No such file or directory

**Comment by mehmetaksoy** [comment]
yes 1285 same node. but I did not turn off any channels. The wallet is constantly increasing when I do not do anything.

**Comment by ZmnSCPxj** [comment]
Do you track channels using `listpeers`?  Channels are shared-ownership, and if the other side decides to close it, it will get closed without needing your approval.  So one possibility is other people closing your channels with them.

**Comment by cdecker** [comment]
```
root@instance-1:~# perf record -F 250 -a -g -- lightningd/lightningd --log-level
=debug --network=bitcoin
Workload failed: No such file or directory
```

This indicates that your `lightningd` binary is not at `lightningd/lightnind`, you should replace that with the real location :-)
