### ISSUE TITLE
absurd fees

### ISSUE THREAD

**Issue by FeedTheWeb** [ElementsProject/lightning#1344]
### Issue and Steps to Reproduce
Keep getting these absurd fees errors  when trying to pay more than what is currently my balance  

> {
>   "code": 206,
>   "message": "Fee 18446743931975630848 is 12932592384.904261% of payment 142637635077; max fee requested is 0.500000%.",
>   "data": {
>     "msatoshi": 142637635077,
>     "fee": 18446743931975630000,
>     "feepercent": 12932592384.90426,
>     "maxfeepercent": 0.5,
>     "delay": 6,
>     "maxdelay": 500,
>     "getroute_tries": 6,
>     "sendpay_tries": 0,
>     "route": [
>       {
>         "id": "03ec6c583cd7cadd7c03ecba4042ee4cca35d4f56cae49c2fd7abf71380ba04043",
>         "channel": "1291977:56:0",
>         "msatoshi": 903714309,
>         "delay": 6
>       }
>     ],
>     "failures": []
>   }
> }
>

**Comment by FeedTheWeb** [comment]
nevermind... my seems to be because of something in my scripts

**Comment by ZmnSCPxj** [comment]
Strange. Paying with too little money should have led to an eventual exhaustion of available routes (since channels with too little money will be marked as unuseable and thus not-routable-over), and a route-not-found 205 error.  Did you modify `lightningd`?

The reason for the ridiculous fee is an underflow of the computation `route[0].msatoshi - payment`.  `route[0].msatoshi` is 903714309, and `payment` is 142637635077.  The difference is -141733920768.  In unsigned 64-bit that is 18446743931975630848.

However the routing component will target exactly the `payment` you gave it, not the amount in the channel.  So it seems the `route[0].msatoshi` value was modified after the routing component returned it, which is not the programmed behavior and the reason I ask if you modified `lightningd`.  Can you give version and the BOLT11 invoice?

**Comment by FeedTheWeb** [comment]
it is a direct connect between 2 CL nodes. 
I just created a new invoice with the same amount ($10k) , which is obviously too much

1.   v0.5.2-2016-11-21-2493-g723b640
```
lightning-cli invoice 142637635077 test test
{
  "payment_hash": "4d3db6135c5b0100dfbe656dd07007a6323a3257f287db0a3fa087210702a7ed", 
  "expiry_time": 1523264293, 
  "expires_at": 1523264293, 
  "bolt11": "lntb1426376350770p1pdvk8g4pp5f57mvy6utvqspha7v4kaquq85cer5vjh72rakz3l5zrjzpcz5lksdq8w3jhxaqcqpx78x6fwgkj3snq0kt62mdngjaz0lm7ztyvwzvdrwz5jh78ukwtry58g7walfskvklkn3sx6vjjllg3p37zqyqa032fqq943p00shl37gp89x2h8"
}


```
2.  v0.5.2-2016-11-21-2493-g723b640
```
 lightning-cli pay lntb1426376350770p1pdvk8g4pp5f57mvy6utvqspha7v4kaquq85cer5vjh72rakz3l5zrjzpcz5lksdq8w3jhxaqcqpx78x6fwgkj3snq0kt62mdngjaz0lm7ztyvwzvdrwz5jh78ukwtry58g7walfskvklkn3sx6vjjllg3p37zqyqa032fqq943p00shl37gp89x2h8
{ "code" : 206, "message" : "Fee 18446743931975630848 is 12932592384.904261% of payment 142637635077; max fee requested is 0.500000%.", "data" : 
{
  "msatoshi": 142637635077, 
  "fee": 18446743931975630848, 
  "feepercent": 12932592384.904261, 
  "maxfeepercent": 0.500000, 
  "delay": 6, 
  "maxdelay": 500, 
  "getroute_tries": 6, 
  "sendpay_tries": 0, 
  "route": [
    {
      "id": "03ec6c583cd7cadd7c03ecba4042ee4cca35d4f56cae49c2fd7abf71380ba04043", 
      "channel": "1291977:56:0", 
      "msatoshi": 903714309, 
      "delay": 6
    }
  ], 
  "failures": [
  ]
} }

```

**Comment by cdecker** [comment]
Can you share the output of `listpeers` from the sending node? It might be some error in the configuration of the node, or a misread gossip message.

**Comment by FeedTheWeb** [comment]
2. 
```
{
  "peers": [
    {
      "id": "03ec6c583cd7cadd7c03ecba4042ee4cca35d4f56cae49c2fd7abf71380ba04043", 
      "connected": true, 
      "netaddr": [
        "[::ffff:95.91.214.87]:65274"
      ], 
      "alias": "stat ", 
      "color": "03ec6c", 
      "channels": [
        {
          "state": "CHANNELD_NORMAL", 
          "owner": "lightning_channeld", 
          "short_channel_id": "1291977:56:0", 
          "channel_id": "484ac13bb21e9490464da1bb796bb571e41003a92a30f4478cea31d463f99698", 
          "funding_txid": "9896f963d431ea8c47f4302aa90310e471b56b79bba14d4690941eb23bc14a48", 
          "msatoshi_to_us": 70459524, 
          "msatoshi_to_us_min": 0, 
          "msatoshi_to_us_max": 210508006, 
          "msatoshi_total": 1000000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 0, 
          "our_channel_reserve_satoshis": 10000, 
          "channel_reserve_satoshis": 0, 
          "spendable_msatoshi": 60459524, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 2, 
          "our_to_self_delay": 2, 
          "to_self_delay": 2, 
          "max_accepted_htlcs": 483, 
          "status": [
            "CHANNELD_NORMAL:Reconnected, and reestablished.", 
            "CHANNELD_NORMAL:Funding transaction locked."
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }
  ]
}

```

**Comment by ZmnSCPxj** [comment]
Looks like an overflow somewhere in the fee computation in the routing component, not in the payment algorithm.  Also looks like `listpeers` does not display on-Lightning feerates.  Can you try `listchannels`? The output will be long so maybe capture in a file and put in a gist.

**Comment by FeedTheWeb** [comment]
so you do not get the same when trying to pay that invoice ?
here is a new one (expires after 4 days)

`lntb1426376350770p1pdvk06fpp54m32t7vekaz3p8ysgrvnq7f3mc0saprrmrw6dsng9c8dqlgphzxsdqgw3jhxaphxqryugcqpxvhxxn6t6mgn2646r3h7n2dnz090dasy7zxe22gauxdnyhqr3sluyvryvr067ywg4kmcqs7vh56ex4tsltqy7zr5cuejl2mgqqxvznwqq5sumx8
`

listchannels:  https://dpaste.de/tLXY

-------------
The amount seems to be the issue :

lightning-cli invoice 142637635077 test7 test7
results in 
```
{ "code" : 206, "message" : "Fee 18446743931975630848 is 12932592384.904261% of payment 142637635077; max fee requested is 0.500000%.", "data" : 
{
  "msatoshi": 142637635077, 
  "fee": 18446743931975630848, 
  "feepercent": 12932592384.904261, 
  "maxfeepercent": 0.500000, 
...
```

lightning-cli invoice 100000000000 test8 test8
```
{ "code" : 203, "message" : "failed: WIRE_INCORRECT_PAYMENT_AMOUNT (reply from remote)", "data" : 
{
  "erring_index": 1, 
  "failcode": 16400, 
  "erring_node": "03ec6c583cd7cadd7c03ecba4042ee4cca35d4f56cae49c2fd7abf71380ba04043", 
  "erring_channel": "0:0:0", 
...
```

btw, Eclair wallet tells me "This is not a valid payment address" . Perhaps an issue with the amount notation?

**Comment by ZmnSCPxj** [comment]
Ah, looks like an overflow of a 64-bit value from the main lightningd to the routing component.

The value 142,637,635,077 when truncated to 32-bits is 903,714,309.  Notice the line below:

>    "msatoshi": 903714309,

That is the route returned by the routing component.  So it looks like we are converting a 64-bit value to a 32-bit value in the routing component.

**Comment by ZmnSCPxj** [comment]
Here is what the routing component inputs:

https://github.com/ElementsProject/lightning/blob/0ba687732f4f00a8dd3bbad7a3656aff142e5866/gossipd/gossip_wire.csv#L107

And here is what the routing component outputs:

https://github.com/ElementsProject/lightning/blob/0ba687732f4f00a8dd3bbad7a3656aff142e5866/gossipd/routing.h#L179

So 32-bit input, 32-bit output, but the payment algorithm uses 64-bit:

https://github.com/ElementsProject/lightning/blob/0ba687732f4f00a8dd3bbad7a3656aff142e5866/lightningd/payalgo.c#L102
