### ISSUE TITLE
Creating a new invoice is unbelievably slow

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#1346]
Creating a new lightning invoice is taking around 5 seconds, causing noticeable delay to customers during checkout.

Is there some low hanging fruits to optimize this?

**Comment by rustyrussell** [comment]
Hmm, how many invoices do you have?  It's completely unoptimized code, but I'd like to know where to look to benchmark.

**Comment by NicolasDorier** [comment]
@rustyrussell on regtest, new instance.

**Comment by NicolasDorier** [comment]
Woops I tried doing it as well in command line and it was instant. Problem is on my code!

**Comment by rustyrussell** [comment]
Phew thanks!
