### ISSUE TITLE
Add the ability to sign a message

### ISSUE THREAD

**Issue by fixone** [ElementsProject/lightning#1347]
not a bug, but (maybe) a missing feature: is there a way to sign a message with lightning-cli and using the node's key? for instance htlc.me allows you to "claim" your node by having you sign a message using the node's identity

**Comment by darosior** [comment]
Fixed-By https://github.com/ElementsProject/lightning/pull/3150

**Comment by ZmnSCPxj** [comment]
Closed as fixed.
