### ISSUE TITLE
Chill out if you can't immediately bind to port 9375

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#1349]
macOS will prompt for firewall permission when a new application tries to listen to a port. This causes a crash.

Perhaps macOS offers some kind of callback that you can wait for, or perhaps the daemon can just retry every ten seconds?

**Comment by Sjors** [comment]
I still get the above behavior as of f083a699.

Usually, upon the first launch after a recompile, MacOS briefly flashes the permission dialog, but it goes away as the app crashes.

`ps aux | grep lightningd` returns nothing. Last log entry is ``

Second launch shows the dialog again, this time things - such as inbound connections - seem to work after I give permission.

**Comment by ZmnSCPxj** [comment]
Sorry, but possibly none of the developers are using any version of MacOs (I am not running on one, for example).

Could you give version of MacOs? Searching "macos bind port permissions" gives results for fixing problems with binding to port < 1024 (i.e. run as root), but Lightning is 9735.  I do not know of any other nix-like that requires this behavior or any POSIX interface that would provide a callback for binding or listening to a port.  It may be a new behavior from a newer version of the OS?

Can you step it in gdb and see whether it is  `bind`, `listen`, or `accept`  that launches the dialog box?

**Comment by Sjors** [comment]
macOS 10.13.4 with firewall enabled. I'll do some digging.

**Comment by Sjors** [comment]
I'm currently only able to reproduce this behavior in `--daemon` mode.

The change in #1447 seems to make this worse. Rather than briefly flashing the permission dialog, it doesn't appear at all and it just crashes. However now I' able to get more info from lldb:

```
lightningd: lightning_gossipd failed (signal 126), exiting
Process 93067 exited with status = 1 (0x00000001) 
```

I don't know how to get more useful info than that though:

```
(lldb) bt
error: invalid thread
(lldb) th i
error: Process must be launched.
```

**Comment by Sjors** [comment]
I just got it to crash without `--daemon` and with `lldb` running. Though the same issue as above regarding getting more detail.

**Comment by ZmnSCPxj** [comment]
Hmm, that is interesting.  `gossip_activate` in `lightningd/` is what starts the creation of the listening socket in `gossipd`.

You could make a breakpoint in `lightningd/lightningd.c` just after the `gossip_init` call, then look for a `lightning_gossipd` process in `ps` or `top` (`ps waux | grep "lightning_gossipd"` works on Linux but not certain for MacOs).  Then you can launch ANOTHER lldb that binds to the `lightning_gossipd` that got started, and set the breakpoints there, then `cont` the original lldb and wait for the `lightning_gossipd` to crash.

**Comment by ZmnSCPxj** [comment]
Debugging `--daemon` seems to be a bit of a headache since the double-fork also seems to screw with debuggers, haha.

**Comment by cdecker** [comment]
You can start `lightningd` with `--dev-debugger=gossipd`, then `gossipd` will start and wait for a debugger to connect (and give you instructions on how to proceed). It's meant to be used with `gdb` but I'm sure it can also work for `lldb`. Another thing that might be interesting is `strace` and related tools, that'd give you some more information on how the socket fails to bind to the port.

**Comment by Sjors** [comment]
I haven't seen this problem anymore with more recent versions. Perhaps related the recent change to `--bind-addr` + `--announce-addr`? I'll reopen if it happens again.
