### ISSUE TITLE
Fee calculations incompatibility with LND result in unilaterally closed channels

### ISSUE THREAD

**Issue by azhmur** [ElementsProject/lightning#1351]
Steps to reproduce:

1) lnd open channel to clighting
2) after some blocks lnd update fee
3) clighting consider this fee less than min_fee and unilaterally close the channel.

In my exact case LND proposed 250 and clighting has range 253-6785:
https://github.com/lightningnetwork/lnd/issues/1058

https://github.com/ElementsProject/lightning/blob/8a9fef21273b6535a3b4e2fdc3b7d52cf3613f22/lightningd/peer_control.c#L152

PS I don't sure who is wrong side in this case. But it is impossible to maintain channels between lnd and clighting right now.

**Comment by ZmnSCPxj** [comment]
This seems a consequence of @rustyrussell's infamous `omg-bitcoind-vbytes-must-die-die-die` PR: #1251.  We hardcode a minimum feerate of 253 even if bitcoind gives us 250, because we calculate fees more sanely than bitcoind does.

**Comment by LightningK0ala** [comment]
I'm still having a lot of issues with this.

**Comment by niftynei** [comment]
per a convo on IRC today, it looks like lnd has a bug with `update_fee` which may be related

> roasbeef: lnd has a fixed for an update_fee related bug, might explain some of the random force closes even between ourselves, should land in this week and we'll follow up with a minor release to get ppl on the network updated

**Comment by darosior** [comment]
I think it has finally been fixed by https://github.com/ElementsProject/lightning/pull/3215, @azhmur maybe we can now close the issue ?
