### ISSUE TITLE
manpages

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#1360]
As we already have manpages for many commands, we should go whole-hog and make manpages for all commands.

We even have manpages for obscure commands (`autocleaninvoice`) but some important commands are missing description!

* [x] `fundchannel` #1463
* [x] `connect` #1427
* [x] `disconnect`
* [x] `listpeers`
* [x] `listchannels`
* [x] `close`  #1355 
* [x] `withdraw` #1427 
* [x] `newaddr` #1427
* [x] `listfunds` #1427
* [x] `lightningd` itself #2899

**Comment by wythe** [comment]
Agreed, this is something I've had my eye on.  I've wound down some of my other activities and plan to spend a lot more time on this project.

**Comment by fixone** [comment]
I've created PR #1406 that covers 2 of the 8 still needed manpages

**Comment by wythe** [comment]
As far as I can tell, the actual JSON RPC interface is not documented anywhere (I figured it out using printf).  Maybe we could use a `lightning-rpc` manpage. Or, the yet to be written `lightningd` page will define it.

**Comment by ZmnSCPxj** [comment]
We are supposedly following this spec for JSON-RPC: http://www.jsonrpc.org/specification

Note however that we do not support batch command processing as far as I can tell.

**Comment by wythe** [comment]
That makes sense.  Thanks.  I knew I was missing something.

**Comment by wythe** [comment]
So far we just point everyone to this issue instead of opening a new one for each.  I suggest you just write them one at a time, making a PR for each.  `disconnect` looks like a good one to start with.

And yes, `lightningd` is a bit daunting!

**Comment by wythe** [comment]
For the initial lightningd manpage, my thoughts are that it might be best to just present a concise overview with pointers to other manpages for the details.  Take a look at the git manpage for inspiration. 

It also might be a good place to walk the reader through the steps of opening a channel and processing payments.  This would be similar to giteveryday(7), but I don't think requires a separate manpage yet.

I agree that lightningd-config could/should be reworked like @host and @hawkmauk suggests, but maybe that can be done in a later step.

My two cents!

**Comment by hawkmauk** [comment]
Thanks for the feedback, I like the idea of including steps for actions such as opening channels and making payments.  I would expect the man page to include command line args though which would only serve to duplicate what is in lighningd-config which is my main concern.

**Comment by ZmnSCPxj** [comment]
The `lightningd` could ahow the more likely of interest config options, then point to `lightningd-config` for details

**Comment by ZmnSCPxj** [comment]
Only one manpage left, hopefully we can complete before 0.7.2.
