### ISSUE TITLE
Alice pays Bob through Carol failing

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#1365]
Alice pays to Bob works fine, but now I am trying to benchmark clightning (will make this work public once I am done) for Alice pays Bob through Carol scenario.

Alice is having: `02f1ee2743293b6f64246cd3a7cf228119969f38d982ca465a1c8e8e04a6416042`
Carol is having `028ce28f626d73a94b4e111de0f6e4c386bea78e0c0c6ce624aaff7b11cdf5b1c9`
Bob is having `0200fa9463efca0e9f5aec911e649aa5cca2a3528016f5e298db9c1a0fdda27766`

I pasted the logs of the three peers here : https://pastebin.com/7973kQ95

Interesting parts are:

* Line 476: Alice receive money
* Line 489: Alice opens with Carol
* Line 667: Carol receive money
* Line 700: Carol opens with Bob
* Line 866: Alice does not find route to Bob

Am I missing something ? I tried as well in another test to connect Alice and Bob directly (gossiping) and could not route the payment.

**Comment by NicolasDorier** [comment]
Confirmed, after some mining it worked. Is there a way right now to speed up the hop propagation?

If Alice is connected to Bob directly, there is no need to wait 30 seconds on top of the 6 blocks depth?

**Comment by NicolasDorier** [comment]
Closing this as it solved by issue.

**Comment by cdecker** [comment]
Yes, we have the `--dev-broadcast-interval` flag (it's hidden in `utils.py` since we apply it in all tests) which specifies the timer in milliseconds between consecutive flushes of the broadcast, very useful for testing indeed :wink:
