### ISSUE TITLE
Umask for creating socket should be available as cmd param

### ISSUE THREAD

**Issue by analogic** [ElementsProject/lightning#1366]
Right now there is no way to set up rights on rpc socket, everytime lightningd is restarted new rpc socket is created with rw only for running user and thus making very hard to communicate between different users reliably.

**Comment by Sjors** [comment]
Just ran into that as well. Although there's currently no way to constrain RPC permissions. I'd like to be able to install RPC consumers as a separate users. This would be especially useful if there's a way to constrain RPC permissions (perhaps per socket?). E.g. a limited ability to create and check the status of invoices.

**Comment by ZmnSCPxj** [comment]
@Sjors, it seems you are proposing that we impose some kind of capabilities system to particular RPC sockets? I think that would be useful, but is complex enough to deserve a separate issue/feature request here.

**Comment by Sjors** [comment]
@ZmnSCPxj done in #1535
