### ISSUE TITLE
Delay (locktime) is 576 blocks; max delay requested is 500.

### ISSUE THREAD

**Issue by redstorm1** [ElementsProject/lightning#1382]
### Issue and Steps to Reproduce
Compatibility between LND and Clightning

create an invoice with lncli addinvoice --amt=50000
attempt to pay invoice with lightning-cli pay [invoice]

fails with
Delay (locktime) is 576 blocks; max delay requested is 500.

### `getinfo` output
http://paste.ubuntu.com/p/npzmQYHqkZ/

**Comment by ZmnSCPxj** [comment]
If you are willing to risk waiting for a long time (4 days for 576 blocks) to have your money locked and unspendable in case Something Bad happens (i.e. a direct peer dying after you forward but before it can confirm receipt) then you can just boost `maxdelay` in the `pay` command to what you consider safe.

**Comment by ZmnSCPxj** [comment]
Hi @redstorm1, has your question been satisfactorily answered?
