### ISSUE TITLE
error code: -25 missing inputs

### ISSUE THREAD

**Issue by redstorm1** [ElementsProject/lightning#1387]
### Issue and Steps to Reproduce
Sorry no idea how to reproduce this, re sending the raw transaction with bitcoin-cli returns the same error as reported by lightningd

{
      "type": "UNUSUAL",
      "time": "23900.805487808",
      "source": "lightningd(12776):",
      "log": "Broadcasting tx 02000000000101611134c1be5b01ab746851a5c4362bda2b216c946e6d7a6b5e1e66cac84d8419000000000011f858800136b34b000000000016001456a76cb2135531b6b6afd0b50966bd3eebfbb6980400483045022100ccafdafd28c1b27c07d60d3e53adea02e64542acb831c31601390be94a581a17022029e89083bb43a9b937654ca18455c7fe2ad934906247b5a4c252fb0b66cd332b014730440220193d35187588b4636ae1c865bd2f6d5398cdcb2339e29849b300db79dc231dd102205106b35d45d9fc8237db75d9a444e502c3075a9903fa6aeb8e7f7a6969d930a80147522102f0d2619640dea1d7cfb2d86150e655fea8e39abf63bad3b07d4e12ed53779d302103a4dadc90a7c69bce4aa2b835e5412e2681928a96641561a01a238b6754530f1652aee3dcf420: 25 error code: -25?error message:?Missing inputs?"
    }

### `getinfo` output
{
  "id": "0392419c02fbca83ae8d541cd2f48b662b2238ed8e1e92a93547c23ba32f0d64c6",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "203.86.204.88",
      "port": 9735
    }
  ],
  "version": "v0.5.2-2016-11-21-2528-g11ca729",
  "blockheight": 1293201,
  "network": "testnet"
}

 bitcoin-cli -testnet sendrawtransaction 02000000000101611134c1be5b01ab746851a5c4362bda2b216c946e6d7a6b5e1e66cac84d8419000000000011f858800136b34b000000000016001456a76cb2135531b6b6afd0b50966bd3eebfbb6980400483045022100ccafdafd28c1b27c07d60d3e53adea02e64542acb831c31601390be94a581a17022029e89083bb43a9b937654ca18455c7fe2ad934906247b5a4c252fb0b66cd332b014730440220193d35187588b4636ae1c865bd2f6d5398cdcb2339e29849b300db79dc231dd102205106b35d45d9fc8237db75d9a444e502c3075a9903fa6aeb8e7f7a6969d930a80147522102f0d2619640dea1d7cfb2d86150e655fea8e39abf63bad3b07d4e12ed53779d302103a4dadc90a7c69bce4aa2b835e5412e2681928a96641561a01a238b6754530f1652aee3dcf420
error code: -25
error message:
Missing inputs

bitcoin-cli -testnet decoderawtransaction 02000000000101611134c1be5b01ab746851a5c4362bda2b216c946e6d7a6b5e1e66cac84d8419000000000011f858800136b34b000000000016001456a76cb2135531b6b6afd0b50966bd3eebfbb6980400483045022100ccafdafd28c1b27c07d60d3e53adea02e64542acb831c31601390be94a581a17022029e89083bb43a9b937654ca18455c7fe2ad934906247b5a4c252fb0b66cd332b014730440220193d35187588b4636ae1c865bd2f6d5398cdcb2339e29849b300db79dc231dd102205106b35d45d9fc8237db75d9a444e502c3075a9903fa6aeb8e7f7a6969d930a80147522102f0d2619640dea1d7cfb2d86150e655fea8e39abf63bad3b07d4e12ed53779d302103a4dadc90a7c69bce4aa2b835e5412e2681928a96641561a01a238b6754530f1652aee3dcf420
{
  "txid": "371347fbd4fd3b0a78e37558c2b99afea65b4358d20343699803aa3c8ab96182",
  "hash": "17d71189d8f2f85e54c32ce05f0ffdca951a03f9e34fb661ba846fa7f580fa74",
  "version": 2,
  "size": 303,
  "vsize": 138,
  "locktime": 552918243,
  "vin": [
    {
      "txid": "19844dc8ca661e5e6b7a6d6e946c212bda2b36c4a5516874ab015bbec1341161",
      "vout": 0,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "",
        "3045022100ccafdafd28c1b27c07d60d3e53adea02e64542acb831c31601390be94a581a17022029e89083bb43a9b937654ca18455c7fe2ad934906247b5a4c252fb0b66cd332b01",
        "30440220193d35187588b4636ae1c865bd2f6d5398cdcb2339e29849b300db79dc231dd102205106b35d45d9fc8237db75d9a444e502c3075a9903fa6aeb8e7f7a6969d930a801",
        "522102f0d2619640dea1d7cfb2d86150e655fea8e39abf63bad3b07d4e12ed53779d302103a4dadc90a7c69bce4aa2b835e5412e2681928a96641561a01a238b6754530f1652ae"
      ],
      "sequence": 2153314321
    }
  ],
  "vout": [
    {
      "value": 0.04961078,
      "n": 0,
      "scriptPubKey": {
        "asm": "0 56a76cb2135531b6b6afd0b50966bd3eebfbb698",
        "hex": "001456a76cb2135531b6b6afd0b50966bd3eebfbb698",
        "reqSigs": 1,
        "type": "witness_v0_keyhash",
        "addresses": [
          "tb1q26nkevsn25cmdd406z6sje4a8m4lhd5cmgd3q8"
        ]
      }
    }
  ]
}

**Comment by redstorm1** [comment]
What about this?

2018-04-16T20:05:28.735Z lightningd(12776): 020eb65488c223bd589b10c84b241809999cc621879a63321bbeac994d4ebe4041 chan #34: Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (62208)

**Comment by cdecker** [comment]
Any messages above that? It could just have lost its connection.
