### ISSUE TITLE
Is it possible to open multiple channels?

### ISSUE THREAD

**Issue by ennethouse-darhsic** [ElementsProject/lightning#1389]
### Issue and Steps to Reproduce
I already have one channel open and would like to add more. Is there a setting to make this possible?

```
$ ./cli/lightning-cli listpeers
{
  "peers": [
    {
      "id": "02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed", 
      "connected": false, 
      "channels": [
        {
          "state": "CHANNELD_NORMAL", 
          "short_channel_id": "518633:1332:1", 
          "channel_id": "3672ff8d5337b39686251e008532a999b152d7b204a8ab1c7f6b432ce8dbd152", 
          "funding_txid": "...", 
          ...
        }
      ]
    }, 
    {
      "state": "GOSSIPING", 
      "id": "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", 
      "alias": "SLEEPYARK-th-local-modifications", 
      "color": "02f672", 
      "netaddr": [
        "104.198.32.198:9735"
      ], 
      "connected": true, 
      "owner": "lightning_gossipd"
    }
```

```
$ ./cli/lightning-cli fundchannel 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 120000
{ "code" : -1, "message" : "received ERROR channel e796b25ca689cf2b8d5f8a96c46950831429a09d2c955c878531e4534ea011a1: Multiple channels unsupported" }
```

```

$ ./cli/lightning-cli getinfo
{
  "id": "0383833f156304e98fb1be1e85ca93eac09a521c1620173c3f76e7f031ecefcb97", 
  "port": 9735, 
  "address": [
  ], 
  "version": "v0.5.2-2016-11-21-2520-gf27cd3e4", 
  "blockheight": 518637, 
  "network": "bitcoin"
}
```

**Comment by cdecker** [comment]
We currently only support a single active channel per peer. You can however open a new one as soon as you close the old channel. Multiple channels going to multiple peers are of course possible.

**Comment by ZmnSCPxj** [comment]
Actually the condition above is strange.  @ennethouse-darhsic is trying to open a channel to `02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432`.  According to `listpeers` that peer has no channel and is currently just gossiping with us.  But apparently SLEEPYARK thinks there is already a channel with it.  Maybe @cdecker can check at SLEEPYARK end?

**Comment by ennethouse-darhsic** [comment]
I tried reconnecting to SLEEPYARK and it does not show up in `listpeers` as gossiping. From the log file, it seems to be responding with an error message preventing the connection:

```
$ ./cli/lightning-cli listpeers
{
  "peers": [
    {
      "id": "02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed", 
      "connected": true, 
      "netaddr": [
        "78.63.23.25:9735"
      ], 
      "alias": "#RECKSPLORER", 
      "color": "891aff", 
      "channels": [
        {
          "state": "CHANNELD_NORMAL",
.....
```

Log file after connection request:
```
$ ./cli/lightning-cli connect 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 104.198.32.198 9735
{
  "id": "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432"
}
```

```
2018-04-18T08:44:25.052Z lightningd(3987): Connected json input
2018-04-18T08:44:25.226Z lightning_gossipd(3996): Connected out for 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432
2018-04-18T08:44:25.397Z lightning_gossipd(3996): peer_out WIRE_INIT
2018-04-18T08:44:25.566Z lightning_gossipd(3996): peer_in WIRE_INIT
2018-04-18T08:44:25.566Z lightning_gossipd(3996): UPDATE WIRE_GOSSIP_PEER_CONNECTED
2018-04-18T08:44:25.567Z lightning_gossipd(3996): UPDATE WIRE_GOSSIP_PEER_CONNECTED
2018-04-18T08:44:25.567Z lightningd(3987):jcon fd 16: Success
2018-04-18T08:44:25.567Z lightning_gossipd(3996): Handing back peer 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 to master
2018-04-18T08:44:25.568Z lightning_gossipd(3996): hand_back_peer 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432: now local again
2018-04-18T08:44:31.892Z lightningd(3987): lightning_channeld-02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed chan #3: peer_in WIRE_PING
2018-04-18T08:44:31.893Z lightningd(3987): lightning_channeld-02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed chan #3: Got ping, sending WIRE_PONG
2018-04-18T08:44:31.893Z lightningd(3987): lightning_channeld-02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed chan #3: peer_out WIRE_PONG
2018-04-18T08:44:32.267Z lightning_gossipd(3996): peer_in WIRE_ERROR
2018-04-18T08:44:32.267Z lightning_gossipd(3996): 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 sent ERROR channel fa7ac57b25a979bd956dcb2d5949dc6541c03bdda84fb17a30083622b8c0a1c3: lightning_channeld: received ERROR channel fa7ac57b25a979bd956dcb2d5949dc6541c03bdda84fb17a30083622b8c0a1c3: Unexpected message 136 for peer
2018-04-18T08:44:32.554Z lightningd(3987): Connected json input
2018-04-18T08:44:32.554Z lightning_gossipd(3996): REPLY WIRE_GOSSIP_GETPEERS_REPLY with 0 fds
2018-04-18T08:44:32.555Z lightningd(3987):jcon fd 16: Success
```

**Comment by ennethouse-darhsic** [comment]
Strange, I am not showing any connection in my `listpeers` or `listfunds` outputs. Do you think I should do `close` or `dev-fail` with the sleepyark node? If closing it works that would be great, but in the future how would I get this `channel_reestablish` info from the cli since my `listpeers` isn't showing any connection?

```
$ ./cli/lightning-cli listpeers
{
  "peers": [
    {
      "id": "02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed", 
      "connected": true, 
      "netaddr": [
        "78.63.23.25:9735"
      ], 
      "alias": "#RECKSPLORER", 
      "color": "891aff", 
      "channels": [
        {
          "state": "CHANNELD_NORMAL", 
          "owner": "lightning_channeld", 
          "short_channel_id": "518633:1332:1", 
          "channel_id": "3672ff8d5337b39686251e008532a999b152d7b204a8ab1c7f6b432ce8dbd152", 
          "funding_txid": "53d1dbe82c436b7f1caba804b2d752b199a93285001e258696b337538dff7236", 
          "msatoshi_to_us": 60000000, 
          "msatoshi_to_us_min": 60000000, 
          "msatoshi_to_us_max": 60000000, 
          "msatoshi_total": 60000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 0, 
          "our_channel_reserve_satoshis": 600, 
          "channel_reserve_satoshis": 0, 
          "spendable_msatoshi": 59400000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 144, 
          "our_to_self_delay": 144, 
          "to_self_delay": 144, 
          "max_accepted_htlcs": 483, 
          "status": [
            "CHANNELD_NORMAL:Reconnected, and reestablished.", 
            "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }
  ]
}
```

```
$ ./cli/lightning-cli listfunds
{
  "outputs": [
    {
      "txid": "<txid>", 
      "output": 0, 
      "value": 114276, 
      "address": "<bc1...>", 
      "status": "confirmed"
    }, 
    {
      "txid": "<txid>", 
      "output": 0, 
      "value": 646110, 
      "address": "<bc1...>", 
      "status": "confirmed"
    }, 
    {
      "txid": "<txid>", 
      "output": 0, 
      "value": 57373, 
      "address": "<bc1...>", 
      "status": "confirmed"
    }
  ], 
  "channels": [
    {
      "peer_id": "02e9fa6b495d07ce19796b06b5c0f51a401dbb48935c3aafe54067c89299add0ed", 
      "short_channel_id": "518633:1332:1", 
      "channel_sat": 60000, 
      "channel_total_sat": 60000, 
      "funding_txid": "53d1dbe82c436b7f1caba804b2d752b199a93285001e258696b337538dff7236"
    }
  ]
}
```

**Comment by cdecker** [comment]
So just to be sure, you're not missing any funds, right?

**Comment by ennethouse-darhsic** [comment]
No,nothing is missing

**Comment by cdecker** [comment]
Great, closing now, should be good to open a new channel now ^^

**Comment by ennethouse-darhsic** [comment]
Thanks, I have a new channel open. Is there a way to prevent my node from forgetting connections like that? If it happens again, is there a way to fix the problem without action from the other node?

**Comment by cdecker** [comment]
It shouldn't ever forget about a channel in any scenario, and I'm still unsure how this could have happened. You didn't use `dev-forget-channel`, did you?

**Comment by cdecker** [comment]
Hm, what bothers me is that you say you had a successful channel, which you then closed, but the channel that sleepyark thought it had never confirmed.

**Comment by ennethouse-darhsic** [comment]
I think I found it, not related to the successful channel or the recent one. I remembered the txid from your `listpeers` output above (ending in 'afa'), and it was from another attempt at opening a channel with fees set too low.

The transaction never made it on chain. Perhaps when `dev-rescan-outputs` returned the UTXO to my wallet it also forgot the connection with sleepyark?

See: https://github.com/ElementsProject/lightning/issues/1226

**Comment by ZmnSCPxj** [comment]
@ennethouse-darhsic , @cdecker , has this been resolved? I believe the real issue here is that a channel funding transaction was never confirmed, one side forgot it and the other side remembered it forever.

The BOLT spec requires the fundee to forget about a channel if it is not confirmed quickly enough (a simple DoS protection as it is never given the funding transaction), and the funder should not forget it until it is confirmed (and if the fundee has forgotten it, should use its commitment transaction to recover).

**Comment by ennethouse-darhsic** [comment]
@ZmnSCPxj , this has been resolved in the short term, in that @cdecker manually forgot my connection and I successfully opened a new channel.

However, if that is the desired behavior from the BOLT spec, is there a problem on the sleepyark side? After an unconfirmed channel the funder (me) forgot about its connection, while the fundee (sleepyark) was still waiting for a transaction to fund the channel.

**Comment by ZmnSCPxj** [comment]
Indeed, there is problem in both sides, so we should probably fix something here.  Note that the funder should never forget it once it has broadcast the funding transaction, since even if it drops off all mempools, somebody could have still recorded it and then rebroadcast it when the mempool clears.  And the fundee should forget it after a few days of it not getting confirmed, since it would be trivial for a DoS attacker to launch a few hundred thousand nodes and make up funding transactions with random ID that they never broadcast (because random txid) but which a victim node would keep waiting for forever.

**Comment by ennethouse-darhsic** [comment]
Sorry for the late response - let me know if you prefer that I close this issue as my node is working or leave it open until there is a general fix.

**Comment by ZmnSCPxj** [comment]
#1468 fixes this for SLEEPYARK side. I do not know where to start for your side (i.e. apparently you funded a channel, it did not confirm, and your node forgot about it) --- it may be a bug that has been fixed since then.

**Comment by ennethouse-darhsic** [comment]
My guess is that it forgot about the channel after `dev-rescan-outputs` returned the funding tx to my wallet, but unfortunately I was not saving my log file to disk at that time. I will close for now as it's fixed on the fundee side and monitor if I see this behavior on the funder side again.
