### ISSUE TITLE
channel stuck in CHANNELD_AWAITING_LOCKIN state

### ISSUE THREAD

**Issue by vuraltuna** [ElementsProject/lightning#1390]
{ "id" : "02a8bb290596e5cb990e0292ac9165fba869c3202c8d96594ce2b20bf5bf452ca0", "connected" : false,
 "channels" : 
                        [ 
                                { "state" : "CHANNELD_AWAITING_LOCKIN", "short_channel_id" : "517426:1418:1", "chan
nel_id" : "843ea54f36808ce812b00a251fb4e4d167da153e23d2b8319f994343a0527e23", "funding_txid" : "227e52a04343999f31b
8d2233e15da67d1e4b41f250ab012e88c80364fa53e84", "msatoshi_to_us" : 50000000, "msatoshi_total" : 50000000, "dust_lim
it_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_m
inimum_msat" : 0, "their_to_self_delay" : 144, "our_to_self_delay" : 144, "to_self_delay" : 144, "max_accepted_htlc
s" : 483, "status" : 
                                        [  ], "in_payments_offered" : 0, "in_msatoshi_offered" : 0, "in_payments_fu
lfilled" : 0, "in_msatoshi_fulfilled" : 0, "out_payments_offered" : 0, "out_msatoshi_offered" : 0, "out_payments_fu
lfilled" : 0, "out_msatoshi_fulfilled" : 0 } ] } ] }

**Comment by ZmnSCPxj** [comment]
The peer is not connected. It may be down.  Try using `connect` command to explicitly connect. Nothing we can do if the peer is down.
