### ISSUE TITLE
Channel stuck shutting down - "log": "Funding tx announce ready, but channel state CHANNELD_SHUTTING_DOWN owned by none"

### ISSUE THREAD

**Issue by redstorm1** [ElementsProject/lightning#1393]
### Issue and Steps to Reproduce
close channel using lightning-cli close peer id

"log": "Got depth change 0->3633 for a4bf0c302a7c506c796adc1c39556157276a0b1712f36d2e53d92e641d6199cb"
"log": "Funding tx a4bf0c302a7c506c796adc1c39556157276a0b1712f36d2e53d92e641d6199cb depth 3633 of 1"
"log": "Funding tx confirmed, but channel state CHANNELD_SHUTTING_DOWN unowned"
"log": "Funding tx announce ready, but channel state CHANNELD_SHUTTING_DOWN owned by none"

### `getinfo` output
{
  "id": "0392419c02fbca83ae8d541cd2f48b662b2238ed8e1e92a93547c23ba32f0d64c6",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "203.86.204.88",
      "port": 9735
    }
  ],
  "version": "v0.5.2-2016-11-21-2529-g774af5f",
  "blockheight": 1293461,
  "network": "testnet"
}

lightning-cli listpeers 02c4b8c95105135a4a89c8bfeb8f7262d12d2d4b395ea996060705880152ab7d3f debug

http://paste.ubuntu.com/p/mfxdJMQJWV/

**Comment by ZmnSCPxj** [comment]
"connected": false,

This means the peer is not connected.  Since the peer is not connected, we cannot proceed with a bilateral close.

If you really want a unilateral close, you can use `dev-fail`, or wait for #1355 and set `force=true` (`lightning-cli close peerid=02c4b8c95105135a4a89c8bfeb8f7262d12d2d4b395ea996060705880152ab7d3f force=true timeout=0`) to force close immediately.

**Comment by ZmnSCPxj** [comment]
You could try explicit connecting: `lightning-cli connect 02c4b8c95105135a4a89c8bfeb8f7262d12d2d4b395ea996060705880152ab7d3f` to see if there is just some temporary connect failure.

**Comment by redstorm1** [comment]
peer 02c4b8c95105135a4a89c8bfeb8f7262d12d2d4b395ea996060705880152ab7d3f is an eclair node that does not publish a public IP so i can initiate the connection has to always come from their side. I'll fail channel and wait 144.

**Comment by ZmnSCPxj** [comment]
Hi @redstorm1, has it resolved?

**Comment by redstorm1** [comment]
Yes that channel has now closed, and is just gossiping now.

I'm going to dev-fail this channel as its been stuck like this for weeks.

http://paste.ubuntu.com/p/5SpqDSb5HB/

**Comment by ZmnSCPxj** [comment]
Hmm, looks like something went wrong during unilateral close, where our HTLC could not be reclaimed.  Would you mind filing http://paste.ubuntu.com/p/5SpqDSb5HB/ as a new issue and closing this one?

**Comment by redstorm1** [comment]
Will do, i have not failed that channel yet if it will prove usefill to solve for
