### ISSUE TITLE
Build fails with: lightningd/pay.c:1:17: fatal error: pay.h: No such file or directory

### ISSUE THREAD

**Issue by mmgen** [ElementsProject/lightning#140]
$ cd lightning
$ make
...
fstack-protector -I ccan -I libwally-core/src/secp256k1/include/ -I libwally-core/include/ -I libsodium/src/libsodium/include/ -I .   -DSHACHAIN_BITS=48   -c -o lightningd/pay.o lightningd/pay.c
lightningd/pay.c:1:17: fatal error: pay.h: No such file or directory
compilation terminated.

lightningd/pay.c:1: #include "pay.h"

$ git ls-files | grep pay.h
daemon/pay.h

**Comment by rustyrussell** [comment]
Sorry, I rebased badly without doing clean rebuild!

Fixed by https://github.com/ElementsProject/lightning/commit/018c1d932dcb4568aec54f70fb933f878401d93c

Thanks!

**Comment by mmgen** [comment]
Thanks.  Build went OK!
