### ISSUE TITLE
`invoice` should optionally let caller provide the preimage

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#1402]
In #1401 @fixone asks if it is possible for the caller of `invoice` to provide the preimage.  This is useful to support various ZKCP protocols.

~~Of note is that we do not currently even provide a way to query the payment preimage of an invoice; considering that payments provide the payment preimage, this seems an oversight.~~ Nobody requested for this, so we will not provide it.

* [ ] Allow `invoice` caller to provide a specific payment preimage.

**Comment by cdecker** [comment]
Showing the preimage on completed payment may be a good idea, but I'd not add it to the invoice display. Otherwise there might be people giving out that info as well, which can result in payments stopping at intermediate hops.

**Comment by ZmnSCPxj** [comment]
How about as a separate command? `getinvoicepreimage`?

In ZKCP protocols we need to encrypt the digital good using the preimage that will be revealed after payment (and also provide a proof that the digital good was indeed encrypted using the preimage of a given hash, but that requires zkSNARKs in the usual case). If there is no way to extract the preimage *before* payment, there is no way to encrypt the digital good.

**Comment by cdecker** [comment]
Isn't that the whole point of being able to specify the preimage during invoice creation? Encrypt the data you're transferring with a random secret, then create an invoice with the secret as preimage and then send the invoice to the user.

**Comment by cdecker** [comment]
Well if they can't generate a 32 byte random secret, should they really be doing any fiddling with cryptography anyway? :wink:
Generally speaking I don't like exposing information to all users that may be misused, for something that can be achieved in another way. Let's maybe hold off on exposing that until somebody actually needs it, or guard it behind a compiler flag that disables by default (`EXPERIMENTAL=1`?).

**Comment by ZmnSCPxj** [comment]
> Well if they can't securely generate a 32 byte random secret, should they really be doing any fiddling with cryptography anyway?

The issue may not be a technical inability to create one, but rather the recognition that the available libraries are insecure and the decision that proper implementation of such libraries should be left to dedicated cryptographers.  Presumably the secret generated by lightningd is secure enough for LN work, so reusing that rather than implementing a cryptographically secure PRNG may be a better business decision.

But then the request by @fixone, strictly, is to add a `preimage` parameter to `invoice`, so I will restrict this issue to that only.
