### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by Yasujizr** [ElementsProject/lightning#1410]
![asset 1](https://user-images.githubusercontent.com/36993664/39135293-48405dae-4721-11e8-8a7c-a46e99be597b.png)

Hi,

I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you want to reach me, you can look at the my profile. I can give you all the formats of the design free. If you want a change please specify.

![untitled-5](https://user-images.githubusercontent.com/36993664/39146959-eaba16f0-4740-11e8-9668-70c0b76457b6.jpg)

*I typed wrong. It can be changed to lightning.*

**Comment by NicolasDorier** [comment]
Same proposition from me, got my girl friend to design one for LN: https://ibukingdom.themedia.jp/posts/3341701 I am using it in BTCPayServer.

![image](https://user-images.githubusercontent.com/3020646/39138292-936187e8-475a-11e8-804e-3237bacb4c87.png)
