### ISSUE TITLE
LTC LN node will not sync

### ISSUE THREAD

**Issue by bigbryan98** [ElementsProject/lightning#1415]
### Issue and Steps to Reproduce
Using a BTCPay server on top of the C-Lightning node.  The BTC LN node is working perfectly and accepting payments.   The LTC node is fully synced.  The LTC LN node (now renamed Sisyphus) starts syncing from the genesis block and after getting to the current block, starts back over at the genesis, never reaching a fully synced status.  This process takes about 2 days (i think because of low numbers of LTC LN nodes relaying data, but not sure).   I ran the updater and let it sync again, to no avail. 

Duplicate of issue here:  [(https://github.com/btcpayserver/btcpayserver-docker/issues/7)](url)
@NicolasDorier  says it is not an issue on the BTCPay side.   Requested I repost here.

Additional Feature Request:
Add `.when_lightning_became_cool` for LTC if possible, to reduce LTC LN node sync times

Standing by to provide additional info

### `getinfo` output

BTC LN Node GetInfo
```
`{
  "id": "0214382bdce7750dfcb8126df8e2b12de38536902dc36abcebdaeefdeca1df8284",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "52.168.166.221",
      "port": 9735
    }
  ],
  "version": "v0.0.0.5-dev-with-local-modifications",
  "blockheight": 519758,
  "network": "bitcoin"
}'
```

LTC Node GetInfo
```
{
  "deprecation-warning": "WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16",
  "version": 150100,
  "protocolversion": 70015,
  "walletversion": 139900,
  "balance": 0.00000000,
  "blocks": 1409594,
  "timeoffset": 0,
  "connections": 9,
  "proxy": "",
  "difficulty": 8376784.507713992,
  "testnet": false,
  "keypoololdest": 1523252116,
  "keypoolsize": 2000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
```

LTC LN Node Get Info
```
{
  "id": "03dda598d8c08cb02ae51e9dd6e2f236239610f2bd2e99230fa66acf69721983b4",
  "port": 9736,
  "address": [
    {
      "type": "ipv4",
      "address": "52.168.166.221",
      "port": 9736
    }
  ],
  "version": "v0.0.0.5-dev-with-local-modifications",
  "blockheight": 470120,
  "network": "litecoin"
}
`
```

**Comment by bigbryan98** [comment]
There is a variable  called `.when_lightning_became_cool` in the chain parameters [https://github.com/ElementsProject/lightning/blob/bdd11e07fee70de61079f109aba70dee0ee039ec/bitcoin/chainparams.c](url)  that tells the LN nodes when to start.  The LN nodes have "blocks" (could be the wrong term) that load, but BTC LN start at 504500 while LTC and the test nets start at 1

**Comment by bigbryan98** [comment]
I have no idea how to change that variable.  The link shows it set into the code of chainparams.c.  all the chains except btc are set to 0.

I'm already in way over my head here though, so all of that could be wrong. I stumbled across that variable a couple of .months  ago while crawling through the code.

Crazy that yours stops.  What would be different?

**Comment by NicolasDorier** [comment]
@cdecker I think this PR should fix this issue? https://github.com/ElementsProject/lightning/commit/89ff46f1e68d6e5eb8a8bfafbb58ae2f367ed082

**Comment by NicolasDorier** [comment]
So once https://github.com/ElementsProject/lightning/issues/1423 fix is merged we can give another try.

**Comment by NicolasDorier** [comment]
@bigbryan98 can you run `btcpay-update.sh` this bug might have been fixed by latest clightning.

**Comment by bigbryan98** [comment]
OK.  Update complete,  Of course, the LTC LN node started over again, so I'll let you guys know the status in a couple of days.

**Comment by rustyrussell** [comment]
I propose we remove LTC support.

**Comment by NicolasDorier** [comment]
oh no please! There is not that much difference between shitcoins should be low hanging fruit to support all. I guess only updating `when_lightning_became_cool` would probably help a lot.

I tried to create a new BTCPay server. And indeed `745061 blocks` left. Will try to sync to the end.

**Comment by bigbryan98** [comment]
updating `when_lightning_became_cool` will cut sync time down dramatically.    Thanks @NicolasDorier 

`576024 blocks`

**Comment by cdecker** [comment]
I merged the `when_lightning_became_cool`, so if you're not above that height yet you may be able to restart and cut down on sync time :-)

**Comment by bigbryan98** [comment]
@cdecker of course, it was already past 1,320,000 when I woke up!   Thanks for the help!

**Comment by NicolasDorier** [comment]
@bigbryan98 it worked?

**Comment by NicolasDorier** [comment]
I updated clightning for btcpay so if you run `btcpay-update.sh` you should have latest clightlining commits.

**Comment by bigbryan98** [comment]
I was also surprised it didn't restart... computers a funny things!

**Comment by NicolasDorier** [comment]
My clightning also correctly synched.

**Comment by babikpatient6** [comment]
> BTC LN Node GetInfo
> 
> ```
> `{
>   "id": "0214382bdce7750dfcb8126df8e2b12de38536902dc36abcebdaeefdeca1df8284",

I am helping someone to recover funds and one of his zombie channels is with your old node. If you still have seed or original node's hsm_secret (assuming cln.. xprv can be extracted from it). We can "close" that channel with chantools.
Pls respond here or send me email to bambim1959@gmail.com ASAP.
