### ISSUE TITLE
Add sha256 to gossip store

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#1436]
Since it's a best-effort store, it'd be nice (and cheap) to add a SHA256 to each entry.  It's probably overkill, since the unmarshalling code will probably catch it, but it's easy.

**Comment by cdecker** [comment]
Not a big fan to be honest, this adds about 10% in size on top of my `gossip_store` for testnet (6161362 bytes without, 6752210 bytes with hashes), while I am expecting mostly truncation issues. We could use a truncated hash or a checksum to check for random bitflips or similar.
