### ISSUE TITLE
peer returns after disconnect

### ISSUE THREAD

**Issue by sfmcnally** [ElementsProject/lightning#1438]
when calling `lightning-cli disconnect` for a given peer, the peer disappears, according to `listpeers`and then returns a few minutes later in state "gossiping" when `listpeers` is called

**Comment by ZmnSCPxj** [comment]
Can you check the logs? Arr we connecting out or are they connecting in?

Did you have a channel with the peer before? How did it get closed if there was?

**Comment by cdecker** [comment]
It might just be reconnecting from the remote peer if this was an incoming connection.

**Comment by darosior** [comment]
I think that if the peer isn't banned then it's the intended behavior, so maybe this can be closed ?
