### ISSUE TITLE
Error starting lightningd

### ISSUE THREAD

**Issue by Deadlyelder** [ElementsProject/lightning#144]
Not sure what the error is but whenever I try to start lightnind the following error is thrown:

```
DATABASE NEEDS UPDATE.  Can't access VERSION: SQL logic error or missing database:no such table: version
lightningd(18306): DATABASE NEEDS UPDATE.  Can't access VERSION: SQL logic error or missing database:no such table: version
Log dumped in crash.log
```

Tried troubleshooting by reinstalling the libsqlite library but didnt worked.
bitcoind is configured for testnet and works normally.
OS: Ubuntu 16.04 LTS

For reference tried looking up for crash.log but unable to find its location.

**Comment by bjd** [comment]
It keeps some files under $HOME/.lightningd, this is where you should be able to find the crash.log file.
There is also a lightning.sqlite3 database file there, it seems something is wrong with that file.
Try removing that database file or remove just the whole directory to be sure as README suggests:
> If you're running a previous version, you'll need to shut it down (maybe close channels first) and delete the $HOME/.lightning directory.

**Comment by cdecker** [comment]
You may want to try starting with `--ignore-dbversion`, that should skip the version check, though as @bjd points out you should remove the database, since we don't yet have DB migrations.

**Comment by Deadlyelder** [comment]
Thank you for the comments. 
I tried deleting the ~/.lightning and then running LN which doesn't seems to be working. In this case, it outputs about creating lightning dir and trying to create new database file as unable to find one. But it is followed by the same error mentioned earlier.

Running it with parameters suggested by @cdecker seems to work nicely. 

Furthermore, removing the bitcoin.conf and testnet folder from ~/.bitcoin seems to make it work without requiring the additional parameter. Perhaps there was conflict in database there?

**Comment by cdecker** [comment]
That's rather strange, we only pick up the parameters to contact `bitcoind` from `bitcoin.conf`, I don't see how these could be mixed in. Do you still have a copy of `bitcoin.conf`? If yes, can you remove the passwords and post it somewhere (https://gist.github.com/)?

**Comment by Deadlyelder** [comment]
Sorry for late reply. I will try to check if I still have the copy of `bitcoin.conf` on the machine. Since I did ended up deleting the whole folder am not much confident about its existence. 

Furthermore, to replicate the same error message I will try it again on an older instance of the machine state which might provide more information. 

@cdecker Yes thats why I am curious regarding the nature of the error.

**Comment by cdecker** [comment]
Hi @Deadlyelder, just wanted to check in and ask whether this problem still persists, if you had solved it (and how) or if this it was a one off and we can close this issue :smiley:

**Comment by Deadlyelder** [comment]
Hi @cdecker 

The problem didn't persisted after removing the `bitcoin.conf` and the folder `testnet`. I made attempts to replicate the error again but didn't had any luck on that yet. I also tried checking with the older instances of the machine for a copy of the whole bitcoin folder but they were overwritten.

I believe you can close the issue off. In the unlikely event of the error reoccurrence, I will be sure to pen down detailed steps that led toward such error.

**Comment by cdecker** [comment]
Thanks for the update @Deadlyelder, and thanks for your efforts to recreate the problem. I'll close the issue for now, but feel free to reopen should it manifest itself again :wink:
