### ISSUE TITLE
Is the "libsodium-dev" requrement in Ubuntu install?

### ISSUE THREAD

**Issue by Perlover** [ElementsProject/lightning#1451]
Question only:

I see in your docs if INSTALL: 

To Build on Ubuntu: `sudo apt-get install -y ... libsodium-dev`
But i see in your git repo submodule as in `external/libsodium`. So i think you use your own repo's version.

May be it (`libsodium-dev`) should be removed in docs as requirement?

P.S. I can make pull request if you will agree that it should be removed

**Comment by cdecker** [comment]
Good catch, need to check whether it is still a requirement.

**Comment by cdecker** [comment]
Indeed the docker builder image does not add `libsodium-dev` as a dependency, so this should be dropped from the dependency list.
