### ISSUE TITLE
won't start with error "SQLITE version mismatch: compiled 3011000, now 3022000" after OS upgrade

### ISSUE THREAD

**Issue by freerko** [ElementsProject/lightning#1497]
Hi,

I upgraded a box with an about 1-2 week old commit of c-lightning from Ubuntu 16.04 to 18.04. After the upgrade I did a "make clean; git pull; make" and now c-lightning won't start with the error "SQLITE version mismatch: compiled 3011000, now 3022000".

On bitcointalk.org someone [reported the same error message](https://bitcointalk.org/index.php?topic=3415497.0).

**Comment by cdecker** [comment]
You compiled the daemon with the old version, and now the library was updated. You need to recompile using the new library.

**Comment by cdecker** [comment]
@freerko any news on this?

**Comment by freerko** [comment]
After two weeks off I did a "make clean; git pull; make" again and got another compiler error about the HSM.
In another issue I found the hint to use "make distclean", and afterwards I was able to compile lightningd again.
So now everything works, closing this issue.

**Comment by georgevaccaro** [comment]
I have the opposite message when trying to run c-lightning v0.7.0.

lightningd: SQLITE version mismatch: compiled 3022000, now 3011000

My last version was clightning-v0.6.1.

Any ideas?

**Comment by cdecker** [comment]
Did you compile the daemon on the same machine? Did you install this from the PPA, and are you up to date with sqlite3 update from your distro repo?

**Comment by georgevaccaro** [comment]
I just checked and I'm running Ubuntu 16.04.  And... that is probably the problem.  I just now realized I wasn't using 18.04 since I've had this node a while, but I grabbed the binary for 18.04...

Sorry to bother you. :/  Thanks for the reply.
