### ISSUE TITLE
Feature Request: timeout parameter for connect

### ISSUE THREAD

**Issue by vogelito** [ElementsProject/lightning#1504]
Title is self explanatory, but I'm having a hard time because sometimes the `connect` command hangs indefinitely and never times out. Would love it to have a timeout parameter.

**Comment by teenkung** [comment]
Ok

**Comment by cdecker** [comment]
Which version is this? `connect` should attempt to connect 10 times if I'm not mistaken and then report failiure. But that code changed a lot lately so we might have added a regression.

**Comment by vogelito** [comment]
I built this from the `master` branch on commit `1125682cebd906632423a3cdaa4a125debec448a`

**Comment by vogelito** [comment]
The behavior i'm seeing is the command hanging indefinitely.

I'm away this weekend, but next week i'll try to ping the peer as this happens.

**Comment by vogelito** [comment]
I waited for 5 minutes but nothing.

```
root@c-lightning:/home/ubuntu# ping 35.188.113.18
PING 35.188.113.18 (35.188.113.18) 56(84) bytes of data.
64 bytes from 35.188.113.18: icmp_seq=1 ttl=109 time=50.0 ms
64 bytes from 35.188.113.18: icmp_seq=2 ttl=109 time=49.4 ms
64 bytes from 35.188.113.18: icmp_seq=3 ttl=109 time=49.5 ms
^C
--- 35.188.113.18 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 49.449/49.691/50.099/0.342 ms
root@c-lightning:/home/ubuntu# runuser -l bitcoin -c '/home/ubuntu/builds/lightning//cli/lightning-cli connect 028ffea132e7e1d8e5191f7f4dfaa6b5c20509a6c668111b62c21670ce53139560@35.188.113.18:9735'
^C
Session terminated, killing shell...^[[A ...killed.

root@c-lightning:/home/ubuntu# time runuser -l bitcoin -c '/home/ubuntu/builds/lightning//cli/lightning-cli connect 028ffea132e7e1d8e5191f7f4dfaa6b5c20509a6c668111b62c21670ce53139560@35.188.113.18:9735'
^C
Session terminated, killing shell... ...killed.


real	5m3.568s
user	0m0.000s
sys	0m0.000s
```

**Comment by cdecker** [comment]
Can you share the output of the `lightningd` process (possibly with `--log-level=debug` turned on)?

**Comment by vogelito** [comment]
Thanks. Do you mean the output of `lightningd` as I issue the command? I currently see the output going to syslog. Is there a way to get that to go elsewhere that's less noisy?

**Comment by cdecker** [comment]
We don't really log to syslog currently, just the terminal you start `lightningd` in. You can do:

```
lightningd/lightningd --network=bitcoin --log-level=debug | tee lightningd.log
```

That'll create a file `lightningd.log` that will contain the log output.

**Comment by ZmnSCPxj** [comment]
Is this still an issue?

**Comment by vogelito** [comment]
Hi, I stopped playing with c-lightning 2 years ago and don’t know if this is still an issue, unfortunately :(

Happy to close this issue as it’s most likely stale.
