### ISSUE TITLE
Creating invoice + making payment is slower and slower

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#1506]
I am benchmarking the simplest case where Alice pays Bob:

```
var invoice = await Bob.RPC.CreateInvoice(LightMoney.Satoshis(100));
await Alice.RPC.SendAsync(invoice.BOLT11);
```

It seems it takes more and more time. I guess auto clean invoice would solve the issue... but still, it should not be linear.

![benchmarks-runalicepaysbob-facettimeline](https://user-images.githubusercontent.com/3020646/40040663-18230b4e-5856-11e8-9432-9759e11bd8bb.png)

This is one 100 iterations, where each iteration is 16 run of 3 concurrent payments.

**Comment by ZmnSCPxj** [comment]
It could be the number of payments on Alice, not just the number of invoices on Bob.

**Comment by NicolasDorier** [comment]
Ok so to check this, I create 3 differents Alice instead of 3 concurrent payment by the same Alice:

![benchmarks4-runalicespaybob-facettimeline](https://user-images.githubusercontent.com/3020646/40051086-7583802a-5874-11e8-8737-37fffca4b9b6.png)

There seems to have also some contention for in the case of 3 payments of the same Alice at same time costing around 400 ms.

It seems there is indeed improvement, but I am surprised it is not a 3 times improvement. I would have expected the slope to get 3 times slower.

**Comment by NicolasDorier** [comment]
Slope:

Alice pays Bob: 2495
Alices pay Bob: 1120.75

**Comment by NicolasDorier** [comment]
You are probably right here is 1, 3, 7 alices paying same time.

![benchmarks0-runalicepaysbob-density](https://user-images.githubusercontent.com/3020646/40049077-b220d38a-586e-11e8-96d3-3c580082faab.png)


Here is 1 alices paying 1, 3, 7 times at once.

![benchmarks3-runalicespaybob-density](https://user-images.githubusercontent.com/3020646/40049078-b24e3c30-586e-11e8-9129-979d21ab9a48.png)

I will do one more test, same graph as above, 100 iterations but spread on 3 different alices instead of 3 concurrent payment by single alice.

**Comment by ZmnSCPxj** [comment]
Possibly the remaining part is Bob getting overloaded, too. Hence not the three times improvement.  Invoice payment lookup should be O(log n), but payment lookup is probably much less efficient (not as certain, I am more familiar with the invoice side than the payment side, despite practically writing the current `pay` command implementation).

If you are doing multiple `pay` commands in parallel, in particular, some lookups are performed which are O(n) in number of payments (payments getting completed or failed in particular have a linear lookup).

https://github.com/ElementsProject/lightning/blob/11ca729d85da173d93eedde4bc9f3167ac3eaf0d/lightningd/pay.c#L75-L92

**Comment by NicolasDorier** [comment]
is there a way to purge this data?

**Comment by ZmnSCPxj** [comment]
The linear list above is purged when a payment resolves: everything waiting for the payment to resolve is remove from the list, leaving only the payments that have not resolved yet.  However there is still a database table on-disk that contains payments, and is also looked up when a payment resolves (succeeds or fails).  The database table has an index on the `payment_hash`, so should be O(log n), though.

We would do better with concrete profiling information, though --- would that be possible to provide?  `gcc` should have an option to create profiling information in particular.  Especially it would be a good way to determine if the Alices or the Bob is slower.

**Comment by NicolasDorier** [comment]
What do you mean by "waiting payment to resolve"? I am not only creating invoice here, I am also paying them.

**Comment by NicolasDorier** [comment]
I am creating a project to easily benchmark some scenaris https://github.com/dgarage/LightningBenchmarks (it will also support other implementation) though GCC profiling would give better idea about particular code causing real issues.

**Comment by ZmnSCPxj** [comment]
The `pay` command (which is the command that understands bolt11 invoices and executes the algorithm to ensure the payment completes) waits for an individual payment attempt to complete, then if it fails, asks for another route and tries a new payment attempt.  When the first HTLC in the routed payment is sent it is "waiting for payment to resolve".  Multiple such `pay` commands to various invoice payment preimages are put in a list that the above quoted code queries using an O(n) algorithm (basically it just iterates over the list until it finds the `pay` command that is executing that payment attempt).

Payments are resolved if they are known to have succeeded, or known to have failed or timed out.

Note that in C-lightning, a "payment" is an object on the payer that tracks an individual payment attempt (an attempt at getting the preimage for a payment hash in exchange for an amount), while an "invoice" is an object on the payee that has a preimage and its hash and which is resolved when it releases the preimage in exchange for receiving money.  So when I say "waiting for payment to resolve" I mean an object on the payer that is waiting for the routed payment to return a success or failure.

**Comment by NicolasDorier** [comment]
Yes but what I don't undesrtand is that this list of awaiting payments should be purged when `pay` get successfully routed. And they all are successfully routed, but still the time it takes increase.

**Comment by ZmnSCPxj** [comment]
I probably need to audit the database tables then... maybe we forgot to index something we are using as key in that table.

We are also using raw 32-byte blobs as keys in the database table, so maybe SQLITE does not handle those well...

**Comment by rockstardev** [comment]
@NicolasDorier I've just done similar rudimentary test with `lnd` I have as part of that [docker integration I'm doing for BtcPayServer](https://github.com/rockstardev/btcpayserver/commits/dev-lndrpc)... and payment time does seem to stay constant.

So as @ZmnSCPxj says this may likely be problem with indexing or something similar that increases search time as number of transactions grow.

**Comment by NicolasDorier** [comment]
@cdecker suggested I use perftrace to find out where is the issue. I will do during next week.

I never used it though, so if someone can give me pointer it would help me a lot.

**Comment by ZmnSCPxj** [comment]
@NicolasDorier quick question, does Bob perform any `waitinvoice` or `waitanyinvoice`?

**Comment by NicolasDorier** [comment]
I generated the flamegraph when Alice was continuously doing 7 payments at same time to Bob @cdecker although I am unsure how to interpret this as there is no lightning specific calls.

Alice https://svgshare.com/i/6jj.svg
Bob https://svgshare.com/i/6jk.svg

Is there so magic build command I must know to get more relevant information?

**Comment by NicolasDorier** [comment]
Here are the files

[flamegraph.zip](https://github.com/ElementsProject/lightning/files/2022076/flamegraph.zip)

**Comment by NicolasDorier** [comment]
```
perf record -F 99 -g -a --pid $(pidof lightning_hsmd lightning_gossipd lightning_channeld lightningd | sed -e 's/\s/,/g') -o "$TRACE_LOCATION/perf.data" -- sleep 60
perf script -i "$TRACE_LOCATION/perf.data" > "$TRACE_LOCATION/output.trace"
cd /FlameGraph
./stackcollapse-perf.pl "$TRACE_LOCATION/output.trace" > "$TRACE_LOCATION/output.trace.folded"
./flamegraph.pl "$TRACE_LOCATION/output.trace.folded" > "$TRACE_LOCATION/output.trace.svg"
```

**Comment by NicolasDorier** [comment]
Managed to get the function name for kernel calls. But still lightningd function missing :/

**Comment by NicolasDorier** [comment]
Ok so I managed to get more info in the stack traces. Sadly I don't think it help.
alice2 and bob2 svgs have been taken some time after alice1 and alice2 svgs. There is not really any change.

[traces.zip](https://github.com/ElementsProject/lightning/files/2022556/traces.zip)

If the issue is related to IO, would we see it in those graphs? I would assume we won't as the calls are asynchronous.

**Comment by ZmnSCPxj** [comment]
Looks like a good part is logging. Hmm. That and `fork`.

**Comment by NicolasDorier** [comment]
I am wondering if this is the full picture. 

Because when you do a request to the DB, I don't think you block the thread so it would not show on the flamegraph, but it would still make the call slow.

**Comment by ZmnSCPxj** [comment]
We are using sqlite3, which to my understanding has its code execute in the same process as the caller. All our db calls block rather than have a result callback.

**Comment by NicolasDorier** [comment]
Trying to have more data point... running the script for longer taking flamegraph along the way... hopefully we can also see what is taking more and more time.

**Comment by NicolasDorier** [comment]
I am concerned also about why I don't see any call trace in `pay` or create invoice that I call by RPC.

**Comment by NicolasDorier** [comment]
I let it run for like 10-15 minutes.

At beginning (Alice1 and Bob1) 7 concurrent payments took 700ms, at the end (Alice3 and Bob3) took 3 seconds.

By opening the traces of different tab of the browser and switching via CTLR+TAB you can see the evolution over time Bob1, Bob2, Bob3 or Alice.

I am disappointed. While `log_status_msg` takes more and more time, it really does not stand that much out, so I don't think this is the cause of the slowdown. (However, it should be improved)

[traces.zip](https://github.com/ElementsProject/lightning/files/2023252/traces.zip)

Also, why I can't see any call to the RPC methods?
I am using `socat` to talk to Bob and Alice RPC from the host, this is probably adding some overhead so I will try to remove this part tomorrow. I doubt this is the cause though.

**Comment by cdecker** [comment]
The logging subsystem was never this taxing in any of my traces, that's surprising. Is the same true if you redirect to `/dev/null`? Any special shell you are using?

What bothers me is that the `sqlite3_*` calls are nowhere close to what I was expecting (they're really hard to find at all). But that's an issue I had in my own testing as well, anybody have a good idea on how to make these stacks include them?

**Comment by NicolasDorier** [comment]
Yes, that surprise me as well. I will turn off logging and run again.

**Comment by NicolasDorier** [comment]
I am using `docker-compose`. The output is not shown at all on the screen actually.

**Comment by cdecker** [comment]
Oh that could be an issue, since docker will append the log to an in-memory buffer. That could also explain the gradual slow-down over time, which I couldn't explain with just the logs themselves.

**Comment by NicolasDorier** [comment]
@cdecker trying again, will post soon... I doubt this is why, if you open all Bob and Alice side by side and switch to one another you see that it does not increase that much.

Alice1/Bob1 = 600ms for 7 concurrent Alice
Alice3/Bob3 = 3 sec for 7 concurrent Alice after 10~15 minutes.

While the log is taking more time I don't think it can explain that much difference by itself.

**Comment by NicolasDorier** [comment]
Ok so, using `debug-level=broken` increased considerably the perfs (2x faster). But there is still a linear increase.

My CPU and IO is mainly unused.

Log stuff are still taking lot's of time. I am running `lightningd &`. Tomorrow I will try /dev/null if it improves anything...

I will also remove `socat` from the equation. Probably not the problem but it definitively add overhead.

Those are the last traces... and they are pretty boring, almost similar to previous one, with a bit less time on logging.

[traces.zip](https://github.com/ElementsProject/lightning/files/2023462/traces.zip)

**Comment by NicolasDorier** [comment]
Ok. So I can't really remove `socat` from equation without massive headaches.

However, I refactored my code to limit the number of time I connect to a socket.
It improved the performances.

`docker stats` show I am near 100% CPU. While my Hyper-V VM hosting docker is using like 10% of CPU, and my host CPU is around 60% only... long story short I will run my tests on a separate hosted VM (digital ocean or Azure) so I can convince myself about the performances.

I still present my finding here:

The linear issue outlined is still unsolved. I let Alice and Bob mind their own business for 30 minutes while taking a flamegraph every 5 minutes.

My finding are:

Logs functions are suspiciously taking way more time than they should, culprits:

* `status_fmt`
* `log_status_msg`
* `tal_vfmt`
* `get_first`

I could not pin point any big issues aside https://github.com/ElementsProject/lightning/pull/1518
It seems things come from `ccan` lib (ping @rustyrussell )

Also, huge amount of time is spent in `__clone`. I have no idea what it is.

I have still not identified the linear time issue.

Here are the latest flamegraphs I ran.
[traces.zip](https://github.com/ElementsProject/lightning/files/2025466/traces.zip)

**Comment by ZmnSCPxj** [comment]
`__clone` is most likely the Linux `clone` syscall, or a wrapper thereof.  It implements both the process-level `fork` and the thread-level `pthread_create`.  We do not use threads explicitly, only `fork`.  But the large amount of time it spends in `__clone` is very strange --- we do not expect modern OSs to have slow `fork`.

**Comment by NicolasDorier** [comment]
I am using alpine3.7 with some hacks for glib compat.

**Comment by NicolasDorier** [comment]
`fork` isn't suppose to create a child process? Because I seen nothing like it being created by running `ps`.

**Comment by ZmnSCPxj** [comment]
I suddenly remembered that we also `fork` out calls to `bitcoin-cli`.  The call itself is relatively transient, but we make a large number of those while tracking the chain.  Hmm.  Presumably we can ignore the `__clone` if so.

**Comment by NicolasDorier** [comment]
If so, why do you call `bitcoin-cli` so much when doing a payment? Normally making an invoice or payment does not involve anything on chain.

**Comment by NicolasDorier** [comment]
I am starting to wonder if the reason I don't find anything relevant increasing in the flamegraph is because the slowdown is coming from `bitcoin-cli`.

**Comment by NicolasDorier** [comment]
@ZmnSCPxj I inserted a printf to see all bitcoin-cli commands. This is not the problem, no command is sent.

**Comment by NicolasDorier** [comment]
I throw in the sponge. Let me know if I can try anything else to find out more info.
I will gather all the benchs and docs to reproduce it in a git repo as well as current results.

Feel free to close this issue except if you have idea where I can dig more about this.

**Comment by ZmnSCPxj** [comment]
Okay. I will try to find some time to analyze your gathered data in detail.  This makes me wonder if there are some threads going on in the background in some library we are using; I begin to suspect sqlite3.  Hmm.

**Comment by NicolasDorier** [comment]
Tried to take a look with htop while it is running. `lightningd` and `channeld` seems to leak.

**Comment by NicolasDorier** [comment]
Ok so I tried to `gdb` inside `lightning_chann` but `warning: process 17 is a zombie - the process has already terminated`. What? so why it appears in `ps` Oo...

**Comment by NicolasDorier** [comment]
I just don't understand... I added a breakpoint through gdb on `__clone` of `lightningd_channel`. At same time I run a perftrace... my breakpoint does not get hit but `__clone` show on the trace.

**Comment by ZmnSCPxj** [comment]
It is possible that the perftrace gets confused with regards to OS calls.  OS calls might be using a completely separate stack, for example, so it appears to root from the original `__clone` that started up `lightningd` itself. I suggest that we should pay more attention to OS calls like `poll`, `read`, and `write` than on `__clone`.

Interesting tidbit is `timer_earliest`, which is somewhat fatter on the `Alice_traces/33min.svg` than in the `Alice_traces/9min.svg`.  The `pay` RPC command, on starting, sets up a timer that will stop the payment attempt.  Timers apparently use some sort of hierarchy of lists that I do not understand right now (summon @rustyrussell for help).  There is a single `struct timers` used to handle all timers inside `lightningd` --- perhaps the complicated hierarchy of lists is getting more difficult to traverse as more individual `struct timer` objects are registered onto it.  Indeed one of the fat parts is `brute_force_first`, which even helpfully has this comment: https://github.com/ElementsProject/lightning/blob/8d641456a1167452cd0df20e6fb115702227b41a/ccan/ccan/timer/timer.c#L198

Another thing fatter in `Alice_traces/33min.svg` than in `Alice_traces/9min.svg` is the flame starting off `timer_expired`, which is called when we want to actually commit the set of HTLCs we were building into an actual commitment transaction (we do this every 10ms, so that multiple HTLCs incoming/outgoing have a chance of being put together in the same commitment).  Fat parts on top of that include `status_fmt`, similar to `log_*` functions.  The problem is that log filtering is implemented in the main `lightningd`, and `status_*` functions always send to the main `lightningd` regardless of your log level.  Indeed it seems to me, naively, that a good part of the time spent in `status_vfmt` is `towire_status_log` and possibly the `write` system call (which we can see rooted from `__clone`).

So it seems to me that a good part of the delay on Alice is indeed logging due to the `status_` system, with the log filtering done in `lightningd` rather than in the subdaemon (so that `log-level=broken` has no effect on the load).

Indeed, under `__clone` we see a good part of the time is from `write` on the `lightning_channeld` --- most likely from the `status_*` dumps --- and `read` on the main `lightningd`.  It is very likely their communication channel since under `sys_write` and `sys_read` we see a good part go into `sock_` related communications, then into something that starts with `unix_`, probably UNIX local sockets (which are what we use to communicate between subdaemons).

**Comment by NicolasDorier** [comment]
So it seems that we can gain some nice improvement by filtering log at the child level instead of reporting back to `ligthningd`. I don't think the logs are causing the linear issue, but still it would be good improvement.

I noticed with `htop` that there is something leaking as well. Maybe those timers are not properly cleanup after expiration. This might explain the linear time issue. (Although I think there is something else, `brute_force_first` might increase but it still seems not the biggest perf issue)

**Comment by NicolasDorier** [comment]
Left column Alice, Right Bob. Vertical time (every 5 minutes)
![Traces](https://aois.blob.core.windows.net/public/CLightningBenchmarkResults/traces.jpg)

**Comment by NicolasDorier** [comment]
Raw data on all the tests I did.

* [flamegraphs.zip](https://aois.blob.core.windows.net/public/CLightningBenchmarkResults/flamegraphs.zip)
* [AlicePaysBob.zip](https://aois.blob.core.windows.net/public/CLightningBenchmarkResults/AlicePaysBob.zip)
* [AlicesPayBob.zip](https://aois.blob.core.windows.net/public/CLightningBenchmarkResults/AlicesPayBob.zip)
* [AlicePaysBobViaCarol.zip](https://aois.blob.core.windows.net/public/CLightningBenchmarkResults/AlicePaysBobViaCarol.zip)

**Comment by Saibato** [comment]
`dump_htlcs` is called in` channel.c` when calculating the signature
which yield's to n(htlc's) call's of status_trace 
so additional log get's bigger by n(htlc's) which consumes an by n increasing amount of  time.
Can you try to comment out the call in channel.c and rerun test's?
Maybe  `dump_htlcs`  should be anyway SUPERVERBOSE
  

https://github.com/ElementsProject/lightning/blob/7f437715d5f6007d579fcc150bfa1c50008522f4/channeld/full_channel.c#L95-L124

**Comment by ZmnSCPxj** [comment]
Thank you @Saibato, that is probably indeed the cause of the linear increase of processing time proportional to the number of payments done in parallel.

Probably the best thing to do in response is to propagate the loglevel to daemons somehow, and to suppress call to `dump_htlcs` if loglevel is too high.  As a first cut, just sending the loglevel to `channeld` in the `channel_init` message, and making the subdaemon-level `status_*` functions include a new `status_set_loglevel` function, which will suppress the lower loglevel `status_*` functions (not make them send `STATUS_*` messages to `lightningd`).  We would still have the filter at the `lightningd` level.  Succeeding cuts could include this loglevel to other subdaemons as we identify cases where the logging greatly increases processing time.

**Comment by NicolasDorier** [comment]
Will try today sorry for the delay!

**Comment by NicolasDorier** [comment]
@Saibato it worked. I just commented `dump_htlcs`.

**Comment by NicolasDorier** [comment]
Closing this as the problem is identified.

Moving conversation to https://github.com/ElementsProject/lightning/pull/1530

**Comment by NicolasDorier** [comment]
Just reporting the landscape now

![image](https://user-images.githubusercontent.com/3020646/40824000-5cd1e42c-65ad-11e8-9d05-940362213ced.png)
https://aois.blob.core.windows.net/public/temp/Alice.svg

![image](https://user-images.githubusercontent.com/3020646/40824008-63e55a96-65ad-11e8-8892-1a25e9006e38.png)
https://aois.blob.core.windows.net/public/temp/Bob.svg

Seems better! Still can't get past 20 tx per second but at least it is stable. Does not seem to be bottlenecked by IO.
