### ISSUE TITLE
pytest failing on home machine, cannot run make check

### ISSUE THREAD

**Issue by wythe** [ElementsProject/lightning#1508]
After a recent update with the master, and running make check, I got the message:

     py.test is required to run the integration tests, please install using 'pip3 install -r tests/requirements.txt

Fair enough, I ran the above command and tried again.  I got the above message again.  

There was no pytest in my path, so this Makefile line wasn't finding anything:

    PYTEST := $(shell command -v pytest 2> /dev/null)

I added `~/.local/bin` to my path. Then running `make check` gave me:

<pre>
PYTHONPATH=contrib/pylightning:$PYTHONPATH TEST_DEBUG=1 DEVELOPER=0 /home/wythe/.local/bin/pytest -vx tests/ --test-group=1 --test-group-count=1 -v -x
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --test-group=1 --test-group-count=1
  inifile: None
  rootdir: /home/wythe/work/temp/lightning
Makefile:213: recipe for target 'pytest' failed

</pre>

Obviously there is something dreadfully wrong with my environment.  And I'm not much of a python guy.  Any help getting me up and running would be appreciated.

I did all this from a fresh clone of master.

**Comment by cdecker** [comment]
Yeah, sorry that's my fault. requirements.txt is missing one dependency. I'll update that asap. For now you can just run `pip install pytest-test-groups`. I'll probably remove that dependency for non Travis runs though.

**Comment by wythe** [comment]
Thanks. I can run individual tests now, so I am back up and running. Things like this:

<pre>
PYTHONPATH=contrib/pylightning DEVELOPER=1 NO_VALGRIND=1 python3 tests/test_lightningd.py -f LightningDTests.test_funding_all
</pre>

But `make check` results in:

<pre>
=========================================================== test session starts ============================================================
platform linux2 -- Python 2.7.14, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /home/wythe/work/lightning, inifile:
plugins: test-groups-1.0.3
collecting 0 items / 1 errors                                                                                                              
================================================================== ERRORS ==================================================================
__________________________________________________ ERROR collecting tests/test_closing.py __________________________________________________
../../.local/lib/python2.7/site-packages/_pytest/python.py:412: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../.local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
../../.local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
tests/test_closing.py:1: in <module>
    from fixtures import *  # noqa: F401,F403
E     File "/home/wythe/work/lightning/tests/fixtures.py", line 136
E       print(l, end='')
E                   ^
E   SyntaxError: invalid syntax
========================================================= 1 error in 0.04 seconds ==========================================================
Makefile:213: recipe for target 'pytest' failed
make[1]: *** [pytest] Error 1
make[1]: Leaving directory '/home/wythe/work/lightning'
Makefile:205: recipe for target 'check' failed
make: *** [check] Error 2
</pre>

Maybe a python version issues?  But I'm back and running so no rush.

**Comment by wythe** [comment]
Ok got it.  Tests are running fine now. Thanks.

**Comment by cdecker** [comment]
I have a patch under review that'll disable test groups if not explicitly desired.

**Comment by dictatethepace** [comment]
What was the final verdict / solve on this? Having identical issue with a clean install of master on MacOS 10.13.6. Was it a python3 directory issue?

**Comment by cdecker** [comment]
It seems you are running the test suite with `/usr/bin/python`, can you make sure that it is a version 3.x interpreter? `python --version` should tell you.

**Comment by wythe** [comment]
Yes @dictatethepace, it was a python version issue.  But it was on Linux.  

@cdecker is `make check` suppose to work on MacOS? It has never worked on my Mackbook Air and I just figured it wasn't supported.   It fails on `test_closing`.

**Comment by cdecker** [comment]
What's the error on `test_closing`?
