### ISSUE TITLE
trouble connecting to other nodes

### ISSUE THREAD

**Issue by alibora** [ElementsProject/lightning#1509]
I funded my channel. But I am having trouble connecting to other nodes
![adsiz1](https://user-images.githubusercontent.com/38211517/40117577-02609dce-5920-11e8-863d-b3c6e3efe1bc.jpg)
. I funded them.

lightning-cli listfunds
{"outputs":
        [
                {"txid": "48853e4adf8e0d03d0f6563069393c3ae948155fc21a1c81101c0364ff7d405a", "output": 1, "value": 73747, "status": "unconfirmed"
                {"txid": "ad9691bafd34ce0308b335ded5276331996ffc57cfe05c50693ea73f684f9059", "output": 0, "value": 2398, "status": "unconfirmed"},
                {"txid": "201e992dc6a5b5c5fabc2d4c15f1fb762a1808cc13dd3593227af97b528364fe", "output": 0, "value": 2398, "status": "unconfirmed"},
                {"txid": "e3ecaa4ac946652c17a1d4ccd2f2f4601e8890fb6ae78dfab97fcc57bd414de5", "output": 0, "value": 2398, "status": "unconfirmed"},
                {"txid": "426a0d020e10035e385337328b1228c6a0b02ecd31b8f788e5623715692bbceb", "output": 0, "value": 10317, "status": "unconfirmed"
                {"txid": "221171c8dd53f4e60f99e90e8082907de47198d8b00fe622dec06667e249ef49", "output": 0, "value": 2398, "status": "unconfirmed"
        []}

All unconfirmed. I can not turn it off because the channel is not open. And when I check the wallet, the balance is zero.

https://lnmainnet.gaben.win/

When I check on this site I see "URI: Unknow"

In addition:

my alias is "exchange" but it is written "loudwater" on the site.

root@instance-1:~# lightning-cli listconfigs

{ "# version" : "v0.5.2-2016-11-21-2422-g286cfef", "port" : 9735, "rgb" : "00008b", "alias" : "exchange", "pid-file" : "lightningd-bitcoin.pid", "channel-update-interval" : 604800, "l
og-level" : "DEBUG", "log-prefix" : "lightningd(1):", "lightning-dir" : "/root/.lightning", "rpc-file" : "lightning-rpc", "daemon" : "false", "ignore-fee-limits" : false, "locktime-bl
ocks" : 144, "max-locktime-blocks" : 432, "anchor-onchain" : 10, "anchor-confirms" : 3, "max-anchor-confirms" : 10, "commit-fee-min" : 200, "commit-fee-max" : 2000, "commit-fee" : 500
, "default-fee-rate" : 40000, "cltv-delta" : 14, "cltv-final" : 8, "max-htlc-expiry" : 720, "bitcoind-poll" : "30s", "commit-time" : "10ms", "fee-base" : 1000, "fee-per-satoshi" : 10,
 "ipaddr" : "35.196.254.121:9735", "network" : "bitcoin", "allow-deprecated-apis" : true, "autocleaninvoice-cycle" : 0, "autocleaninvoice-expired-by" : 0, "dev-no-reconnect" : "false"
, "dev-fail-on-subdaemon-fail" : "false", "dev-broadcast-interval" : 60000 }

root@instance-1:~# lightning-cli getinfo

{ "id" : "0230c8826852e2a39883f36233483419e9c139b644c696b8dbcca38fef7303ee95", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "35.196.254.121", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2422-g286cfef", "blockheight" : 522949, "network" : "bitcoin" }

**Comment by ZmnSCPxj** [comment]
Yes, you need to wait, and it will take at least one hour (specifically at least 6 blocks) for the channel to fully open, and if the mempool is full it is possible that you need to wait for more time if the funding transaction does not confirm immediately.

Viewers are not always up-to-date.  Again, just wait.

**Comment by ZmnSCPxj** [comment]
Looking in more detail, does your `listfunds` command output have an empty `"channels"` field?

**Comment by Xian001** [comment]
Sorry to be "that guy", but, WHAT THE F@$K ARE YOU DOING RUNNING AS ROOT @alibora ?!??

**Comment by alibora** [comment]
listpeers command output,

root@instance-1:~# lightning-cli listpeers
{ "peers" : 
        [  ] }

**Comment by ZmnSCPxj** [comment]
You have not funded a channel, or if you have, then your counterparties closed them already.  If you had direct channels open, you would have had a non-empty `"peers"` in `listpeers`.

Did you run `fundchannel` command?

**Comment by alibora** [comment]
channels I funded..

lightning-cli listfunds
{"outputs":
        [
                {"txid": "48853e4adf8e0d03d0f6563069393c3ae948155fc21a1c81101c0364ff7d405a", "output": 1, "value": 73747, "status": "unconfirmed"
                {"txid": "ad9691bafd34ce0308b335ded5276331996ffc57cfe05c50693ea73f684f9059", "output": 0, "value": 2398, "status": "unconfirmed"},
                {"txid": "201e992dc6a5b5c5fabc2d4c15f1fb762a1808cc13dd3593227af97b528364fe", "output": 0, "value": 2398, "status": "unconfirmed"},
                {"txid": "e3ecaa4ac946652c17a1d4ccd2f2f4601e8890fb6ae78dfab97fcc57bd414de5", "output": 0, "value": 2398, "status": "unconfirmed"},
                {"txid": "426a0d020e10035e385337328b1228c6a0b02ecd31b8f788e5623715692bbceb", "output": 0, "value": 10317, "status": "unconfirmed"
                {"txid": "221171c8dd53f4e60f99e90e8082907de47198d8b00fe622dec06667e249ef49", "output": 0, "value": 2398, "status": "unconfirmed"
        []}

can you please check

https://1ml.com/node/0230c8826852e2a39883f36233483419e9c139b644c696b8dbcca38fef7303ee95

and https://lnmainnet.gaben.win/

When I check on this site I see "URI: Unknow"

In addition:

my alias is "exchange" but it is written "loudwater" on the site.

**Comment by ZmnSCPxj** [comment]
`"outputs"` in `listfunds` are onchain funds, not onLightning channeled funds.

If you had channels, you would have seen them in `listpeers`.  You have no channels.

So you have no channels, and viewers will not get your updates because you have no channels. LN requires that you commit to using LN by putting money into channels, so that things like node name and so on are propagated across the network.  If you have no channels, your new node name and so on are not propagated and viewers will not know you.

`connect` to other peers again, then `fundchannel` to them.

**Comment by alibora** [comment]
but because I'm funded, the wallet looks zero. and I made this funding on 3/22/2018.

https://lnmainnet.gaben.win/

When I check on this site I see "URI: Unknow". I guess I need to fix it. But I do not know how to do it.


PubKey : 0230c8826852e2a39883f36233483419e9c139b644c696b8dbcca38fef7303ee95-- | --
Alias : LOUDWATER-16-11-21-2367-g5737853
URI : unknown
Last Update : April 3rd 2018, 4:24:59 am
Color : #0230c8

it should look like this:
URI: 0230c8826852e2a39883f36233483419e9c139b644c696b8dbcca38fef7303ee95@35.196.254.121:9735

**Comment by ZmnSCPxj** [comment]
> When I check on this site I see "URI: Unknow". I guess I need to fix it. But I do not know how to do it.

I already told you:

>So you have no channels, and viewers will not get your updates because you have no channels. LN requires that you commit to using LN by putting money into channels, so that things like node name and so on are propagated across the network. If you have no channels, your new node name and so on are not propagated and viewers will not know your correct name.
>
>`connect` to other peers again, then `fundchannel` to them.

You *have no channels*, that is what `listpeers` is telling you.

**Comment by ZmnSCPxj** [comment]
1.  There should be some amount of satoshi in your ***channels***.  These are ***NOT*** the same as onchain funds.
2.  YES.
3.  You only funded the ***onchain*** funds.  You need to have ***channels***, which are ***NOT*** the same as ***onchain*** funds.  Your recent funds are still onchain and can be moved to another onchain address.  They are not lost, you just have them as ***onchain*** funds, you want them to be as ***channel*** funds.

**Comment by alibora** [comment]
ok. thanks. 
I will try this and I will give you information.

**Comment by Xian001** [comment]
> I guess I need to fix it. But I do not know how to do it.

At the risk of coming off as an asshole, this statement, coupled with you running as root, will likely lead to financial disaster for you.

**Comment by alibora** [comment]
I do not understand what you mean, can you please tell me more clearly?

**Comment by cdecker** [comment]
> At the risk of coming off as an asshole, this statement, coupled with you running as root, will likely lead to financial disaster for you.

Please be civil, he might be running in a docker container or have some other good reason to run as root.

**Comment by Xian001** [comment]
>Please be civil

My bad. Sorry dude. Nuked.

**Comment by alibora** [comment]
@ZmnSCPxj I have added some money, what do I have to do now

**Comment by alibora** [comment]
@ZmnSCPxj 
root@instance-1:~# lightning-cli listfunds
{ "outputs" : 
        [ 
                { "txid" : "48853e4adf8e0d03d0f6563069393c3ae948155fc21a1c81101c0364ff7d405a", "output" : 1, "value" : 73747, "status" : "unconfirmed" }, 
                { "txid" : "ad9691bafd34ce0308b335ded5276331996ffc57cfe05c50693ea73f684f9059", "output" : 0, "value" : 2398, "status" : "unconfirmed" }, 
                { "txid" : "201e992dc6a5b5c5fabc2d4c15f1fb762a1808cc13dd3593227af97b528364fe", "output" : 0, "value" : 2398, "status" : "unconfirmed" }, 
                { "txid" : "e3ecaa4ac946652c17a1d4ccd2f2f4601e8890fb6ae78dfab97fcc57bd414de5", "output" : 0, "value" : 2398, "status" : "unconfirmed" }, 
                { "txid" : "426a0d020e10035e385337328b1228c6a0b02ecd31b8f788e5623715692bbceb", "output" : 0, "value" : 10317, "status" : "unconfirmed" }, 
                { "txid" : "221171c8dd53f4e60f99e90e8082907de47198d8b00fe622dec06667e249ef49", "output" : 0, "value" : 2398, "status" : "unconfirmed" }, 
                { "txid" : "e4affe7d72c7ef2c2d9a49318e98df8183c8d3d034f87877115e8d74376937ea", "output" : 41, "value" : 150000, "status" : "confirmed" } ], "channels" : 
        [  ] }

**Comment by ZmnSCPxj** [comment]
[I told you already](https://github.com/ElementsProject/lightning/issues/1509#issuecomment-389772640)

> `connect` to other peers again, then `fundchannel` to them.

**Comment by alibora** [comment]
@ZmnSCPxj @cdecker Is there a problem here? (exit status 242)

root@instance-1:~# docker run --rm --name lightning --network container:bitcoind_mainnet -v /scratch/bitcoin/mainnet/bitcoind:/root/.bitcoin -v /scratch/bitcoin/mainnet/clightning:/ro
ot/.lightning --entrypoint /usr/bin/lightningd cdecker/lightningd:latest --network=bitcoin --rgb=00008B --alias=exchange --ipaddr=35.196.254.121 --log-level=debug
2018-05-18T10:28:37.854Z lightningd(1): --ipaddr has been deprecated, use --addr
2018-05-18T10:28:37.901Z lightningd(1): testing /usr/bin/lightning_channeld
2018-05-18T10:28:37.903Z lightningd(1): testing /usr/bin/lightning_closingd
2018-05-18T10:28:37.904Z lightningd(1): testing /usr/bin/lightning_gossipd
2018-05-18T10:28:37.905Z lightningd(1): testing /usr/bin/lightning_hsmd
2018-05-18T10:28:37.906Z lightningd(1): testing /usr/bin/lightning_onchaind
2018-05-18T10:28:37.907Z lightningd(1): testing /usr/bin/lightning_openingd
2018-05-18T10:28:38.039Z lightningd(1): Updating database from version 69 to 83
2018-05-18T10:28:41.658Z lightningd(1): Client: Received message 11 from client
2018-05-18T10:28:41.659Z lightningd(1): Client: Received message 9 from client
2018-05-18T10:28:41.660Z lightning_gossipd(12): pid 12, msgfd 12
2018-05-18T10:28:41.662Z lightningd(1): Loaded 0 channels from DB
2018-05-18T10:28:42.790Z lightningd(1): Adding block 523214: 00000000000000000036466cd9e7aafb8f06b07ebef30178d56e65d4592c1a73
2018-05-18T10:28:42.802Z lightningd(1): Listening on 'lightning-rpc'
2018-05-18T10:28:48.068Z lightning_gossipd(12): Channel 516774:1453:0(0) massive proportional fee 1000000000: disabling.
2018-05-18T10:28:48.068Z lightning_gossipd(12): gossip_store: Read 10748/573696/5244/0 cannounce/cupdate/nannounce/cdelete from store in 84812273 bytes
2018-05-18T10:28:48.068Z lightning_gossipd(12): STATUS_FAIL_INTERNAL_ERROR: Failed to bind on 2 socket: Cannot assign requested address
lightningd: lightning_gossipd failed (exit status 242), exiting.

**Comment by ZmnSCPxj** [comment]
Are you using some kind of network address translation?  If so, be aware that we have changed the network handling recently.

See this: https://github.com/rustyrussell/lightning/blob/d7a487785ac01d63dd825a542d6876f82ce6dbda/doc/lightningd-config.5.txt

Search for the text `*addr*`, as well as `*bind-addr*` and `*announce-addr*`.

You may need to provide your address as `--announce-addr=35.196.254.121:9735`, then use `--bind-addr=127.0.0.1:9735`.  Remove the `--ipaddr` flag as it is deprecated and will be removed completely soon.  How do you forward from 35.196.254.121 to your `lightningd` computer? Does it have a public address or do you have it over LAN?  How did you get the 35.196.254.121 address?

You could also quickly try without any `--ipaddr` or other address flags: in that case, c-lightning will try to autodetect the public IP address, though you will need to pay close attention to the logs to do so.

**Comment by alibora** [comment]
I am using console.cloud.google.com. You can see in the attachment. I got an external IP here.
![1](https://user-images.githubusercontent.com/38211517/40233389-6eb8a57a-5aab-11e8-882b-7c01c3f20e1f.jpg)

**Comment by ZmnSCPxj** [comment]
You may(?) need to *bind* to the internal IP and *announce* the external IP, i.e. `--bind-addr=10.142.0.2` `--announce-addr=35.196.254.121`.

Are you using `tmux` or GNU `screen` on your cloud instance? If not, the `lightningd` will die when your control PC disconnects from the cloud instance, unless you use the `--daemon` flag (which has recently been somewhat flaky and might be frustrating to you) or the `&` command modifier that most shells support. You may want to learn about `tmux` and GNU `screen` if you intend to keep your `lightningd` permanently on (which is the most likely reason you are using a cloud instance).

**Comment by lockhartheavyindustries** [comment]
I also ran into the same "_Failed to bind on 2 socket: Cannot assign requested address_" error after updating to get the latest network handling changes. I'm running in a VM with an internal IP address + port forwarding to my external IP address, which I had set in my config file.

Commenting out the --ipaddr line in my config file worked for me / c-lightning was able to autodetect my public IP address just fine and I'm back up and running. Might want to try that first before messing around with bindings / internal/external settings.

**Comment by alibora** [comment]
@ZmnSCPxj @lockhartheavyindustries 

thanks for your interest. I am very new to these issues. Can you write me step by step and basically how to do this to me?

**Comment by cdecker** [comment]
That's rather simple: `lightningd` is running inside a container, that does not have access to the physical device (actually also a virtual device since it's running on GCP). So you won't be able to bind to that specific interface unless you start the container with `--net=host`. But that's not your actual problem, you should start without a `--bind-addr` and it'll bind to all interfaces available to the docker container. You then need to also forward the host port into the docker container with `-p 9735:9735` and it'll become reachable over the NATed IP you see in the console.

I know, these are rather a lot of indirections for your connections, but it'll work :-)

**Comment by cdecker** [comment]
Just to give an example of how that'd look:

```
docker run \
  --rm \
  --name lightning \
  --network container:bitcoind_mainnet \
  -p 9735:9735 \
  -v /scratch/bitcoin/mainnet/bitcoind:/root/.bitcoin \
  -v /scratch/bitcoin/mainnet/clightning:/root/.lightning \
  --entrypoint /usr/bin/lightningd \
  cdecker/lightningd:latest --network=bitcoin --rgb=00008B --alias=exchange --announce-addr=35.196.254.121 --log-level=debug
```

Notice that I split up the docker-related options, and the last line only contains the `lightningd`-related options.

**Comment by cdecker** [comment]
I'd also like to close this issue, since it's not technically a dev issue, but rather a support issue, that is better suited for other outlets. In addition we've wandered off rather a long way from the original question.
