### ISSUE TITLE
make check: lightningd --dev-allow-localhost: unrecognized option

### ISSUE THREAD

**Issue by jsarenik** [ElementsProject/lightning#1514]
### Issue and Steps to Reproduce

When I run

    make DEVELOPER=1 NO_VALGRIND=1 check

I get following error:

```
...
DEBUG:root:Starting 'lightningd/lightningd --addr=127.0.0.1:38889 --allow-deprecated-apis=false --bitcoin-datadir=/tmp/ltests-bx5x7229/test_closing_id_1 --bitcoind-poll=1s --cltv-delta=6 --cltv-final=5 --dev-allow-localhost --dev-broadcast-interval=1000 --dev-fail-on-subdaemon-fail --dev-no-reconnect --ignore-fee-limits=false --lightning-dir=/tmp/ltests-bx5x7229/test_closing_id_1/lightning-2/ --locktime-blocks=5 --log-level=debug --network=regtest --override-fee-rates=15000/7500/1000 --rescan=1'
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Waiting for ['Server started with public key'] in the logs
----------------------------- Captured stderr call -----------------------------
lightningd/lightningd: --dev-allow-localhost: unrecognized option
lightningd/lightningd: --dev-allow-localhost: unrecognized option
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 2 failures !!!!!!!!!!!!!!!!!!!!
====================== 1 failed, 1 error in 7.37 seconds =======================
make[1]: *** [Makefile:214: pytest] Error 2
make[1]: Leaving directory '/home/jasan/src/lightning'
make: *** [Makefile:207: check] Error 2
```

### `getinfo` output

Not related.

**Comment by jsarenik** [comment]
@rustyrussell - not even d40d22b6 works for me so I suppose I might be doing something wrong here - should it be possible to run the `make check` the way I do it?

**Comment by cdecker** [comment]
Can you try `make DEVELOPER=1 clean check`? If you compiled without `DEVELOPER=1` then defining it when running `make check` it'll use that option even though it wasn't compiled in.

**Comment by jsarenik** [comment]
Thank you Christian! That sounds like the root cause. I'll try it and
update.

**Comment by cdecker** [comment]
@rustyrussell mentioned a while ago that we might add a `./configure` script that'll customize those variables to your setup, so you don't have to specify them everywhere.

**Comment by jsarenik** [comment]
Yes. Everything works well when I already compile the main binaries with `DEVELOPER=1`. Closing.

Follow-up PR is #1519 - @cdecker have a look please.
