### ISSUE TITLE
Travis should test in parallel

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#1515]
Our tests run much faster in parallel, particularly due to polling delays, etc.  I run -n10 on my laptop (without valgrind) with no problems.

That would allow us to re-enable some non-developer tests, for example.

**Comment by cdecker** [comment]
I have a patch that allows a travis instance to configure the number of parallel tests via env var. Currently hunting down the flaky tests that fail due to slower test runs.

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> I have a patch that allows a travis instance to configure the number of parallel tests via env var. Currently hunting down the flaky tests that fail due to slower test runs.

Try with the gossip fixes branch, which gets some: #1512

**Comment by cdecker** [comment]
Mostly having issues with `test_autocleaninvoices`, which assumes that RPC calls take no time, and similar things. Currently testing with `-n 5`, but probably the sweetspot is more like `-n 4`. It's a good way of shaking out the flaky tests :wink:

**Comment by ZmnSCPxj** [comment]
Is this not fixed by #1516?

**Comment by cdecker** [comment]
The test are still rather flaky, so I'm keeping this open for now until we have good pass-rate.
