### ISSUE TITLE
Custom path for config file

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#1526]
Currently the configuration is assumed to be in `~/.lightning/config`. I'd like to be able to put a config file in `/etc/lightning/config` and have that file owned by a different user, while keeping the datadir in `~/.lightning`.

I think this is different from what's being discussed in #1204, which seems to be about access to Bitcoin's config.

**Comment by rustyrussell** [comment]
Sjors Provoost <notifications@github.com> writes:
> Currently the configuration is assumed to be in `~/.lightning/config`. I'd like to be able to put a config file in `/etc/lightning/config` and have that file owned by a different user.
>
> I think this is different from what's being discussed in #1204, which seems to be about access to Bitcoin's config.

I'm tempted to add an include directive, and then make the default
<lightningdir>/config-<netname> (with fallback to just "config" if that DNE).

I think that's more flexible, and allows you to include some global
config file like this.

Thoughts?

**Comment by Sjors** [comment]
That would still allow the lightning user to just point the include somewhere else though.

**Comment by benthecarman** [comment]
This issue should be closed
