### ISSUE TITLE
Unable to compile c-lightning

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#1527]
Hello, I did `make` and I get 
`
gossipd/tor_autoservice.c: In function ‘tor_autoservice’:
gossipd/tor_autoservice.c:178:3: error: ‘cookiefileerrno’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   status_failed(STATUS_FAIL_INTERNAL_ERROR,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          "Could not open Tor cookie file '%s': %s",
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          cookiefile, strerror(cookiefileerrno));
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gossipd/tor_autoservice.c:123:6: note: ‘cookiefileerrno’ was declared here
  int cookiefileerrno;
      ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: gossipd/tor_autoservice.o] Error 1
`
How do I fix this? Thanks.

**Comment by ZmnSCPxj** [comment]
The compiler is wrong in this case: the code sets `cookiefile`, then it either returns immediately, or set s `cookiefileerrno` to some value.

My instinct is to suppress the compiler warning for this line, like here: https://stackoverflow.com/a/48569874

**Comment by Sgt-Miller** [comment]
Thanks

**Comment by jb55** [comment]
was there a patch for this? I'm getting this as well.
