### ISSUE TITLE
Warnings during compilation

### ISSUE THREAD

**Issue by jsarenik** [ElementsProject/lightning#1540]
### Issue and Steps to Reproduce
Following warnings can be seen while compiling lightning on recent Linux distributions.

```
$ make
...
  CC       ccan/ccan/crypto/sha512/libwallycore_la-sha512.lo
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
...
copying selected object files to avoid basename conflicts...
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
...
```

I am trying to compile rustyrussell/lightning@408dabbc1c035439f307a87535b20e7f9bd34ef9

### `getinfo` output
not relevant

**Comment by jsarenik** [comment]
See #1543 for a full log which includes mentioned warnings.

**Comment by jsarenik** [comment]
So I did a git-bisect on Ubuntu 18.04. Here is the result:

```
cc1: all warnings being treated as errors
<builtin>: recipe for target 'gossipd/gossip.o' failed
make: *** [gossipd/gossip.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
94581c6e0725575e490ed84c4a028112d263b6fb is the first bad commit
commit 94581c6e0725575e490ed84c4a028112d263b6fb
Author: Rusty Russell <rusty@rustcorp.com.au>
Date:   Mon Jun 4 13:52:25 2018 +0930

    gossipd: wire up infrastructure to generate query_short_channel_ids msg.
    
    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

:040000 040000 09de552302c29346a6e6793a36af5a449055c8f5 18bb780f5ec650eea4d65eed3c170fa3807fcbe1 M      gossipd
:040000 040000 e7b93ef2648d0a8aff6f3f65a3f137d36a403cfc aefd9250c4b30a0225b314388fe75264ed6ab900 M      lightningd
bisect run success
```

I did it like this:

```
cat > ~/bisect.sh <<EOF
#!/bin/sh

{
git clean -xfd
git submodule deinit --all -f
./configure || true
make -j4
} >/dev/null 2>&1 && echo Success || { echo FAIL; exit 1; }
EOF
chmod a+x ~/bisect.sh
git clone https://github.com/ElementsProject/lightning
cd lightning
git remote add rusty https://github.com/rustyrussell/lightning
git fetch rusty
git checkout guilt/configure
git bisect start HEAD 27a186b --
git bisect run ~/bisect.sh
git bisect reset
```

Your mileage may vary. I still think this is a race condition so the bisect is not really showing when it was introduced and will oscillate on multiple commits. But one thing is clear to me, the latest commit on rustyrussel/lightning@guilt/configure is failing a lot. Try it please.

I used `debootstrap` to set up a fresh Ubuntu 18.04 chroot directory and [chsys](https://gist.github.com/jsarenik/fae7451d4ebebd96cad86d33798ed4e2) script to get into it.

```
mkdir ubuntu18
debootstrap --variant=buildd --arch=amd64 \
  bionic ./ubuntu18 http://archive.ubuntu.com/ubuntu/
./chsys ubuntu18 /bin/bash
# then as root in chroot
apt install autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev python python3 net-tools zlib1g-dev
```

**Comment by cdecker** [comment]
Seems to me like a dependency throwing some warnings, not much we can do about it on our end.

**Comment by jsarenik** [comment]
Thanks for pointing out it was in external dependency. I was just focusing on seeing the warnings instead of reading the context.

**Comment by jsarenik** [comment]
https://github.com/ElementsProject/libwally-core/pull/36

**Comment by cdecker** [comment]
Thanks @jsarenik the upstream fix got merged and we'll upgrade libwally as soon as possible.
