### ISSUE TITLE
Data loss protection is not provided by this peer

### ISSUE THREAD

**Issue by corbimos** [ElementsProject/lightning#1541]
trying to open a channel using the[ bitcoin lightning wallet](https://play.google.com/store/apps/details?id=com.lightning.walletapp&hl=en_US) app on android with my c-lightning node and I get the "data loss protection is not provided by this peer" and the app closes. 

What must I do on my node to allow other users on mobile to connect?

Thanks!

Node info:
{
  "id": "036dc6c5fc1a16171f182f48794cf3833654e8018cce0bde540854b19854448f5f",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "23.100.30.211",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv4",
      "address": "0.0.0.0",
      "port": 9735
    }
  ],
  "version": "v0.0.0.16-dev-modded",
  "blockheight": 526008,
  "network": "bitcoin"

**Comment by ZmnSCPxj** [comment]
The feature ("data loss protection") is not supported yet, so as of now, it is not possible to do anything to "turn it on", it is not implemented at all yet.

**Comment by rustyrussell** [comment]
Which the bitcoin lightning app?

Thanks!
Rusty.

**Comment by cdecker** [comment]
This is when talking to eclair I think.

**Comment by corbimos** [comment]
Its the bitcoin + lightning application on android. It was just realeased.

ECLAIR works fine connecting to my node. Someone stated that data loss is not available on c-lightning yet. The app seems to require this feature for security reasons.

**Comment by cdecker** [comment]
@pm47 and @sstone do you guys require this feature by default now, or is this someone else's project? Just to know how to prioritize this :wink:

**Comment by pm47** [comment]
No we don't, feature is still [optional by default](https://github.com/ACINQ/eclair/blob/a85ba9ceef9dd68150237ab0f2a86672182a6a73/eclair-core/src/main/resources/reference.conf#L43) in eclair.

**Comment by shesek** [comment]
He's referring to @btcontract's https://github.com/btcontract/lnwallet.

**Comment by btcontract** [comment]
Yes, data loss protection is mandatory in BLW.

@corbimos 
> I get the "data loss protection is not provided by this peer" and the app closes

Does it close entierly (which is not expected) or just refuses to proceed with peer?

**Comment by corbimos** [comment]
It just refuses the peer. Connets to the recommended peers just fine. 

Thanks!

**Comment by BCsRock** [comment]
Why closed? The issue is still there, isn't it?
