### ISSUE TITLE
Python dev test in non-dev mode failure: test_closing_while_disconnected

### ISSUE THREAD

**Issue by jsarenik** [ElementsProject/lightning#1548]
### Issue and Steps to Reproduce

EDIT: Testing on latest `master` - i.e. 56046d47 as of today (2018-06-11)

When I configure without parameters and then `make check` there is a test error which is trying to run a developer test in a (default) non-developer mode. See the full log.

```
DEBUG:root:Calling dev-memleak with payload None
DEBUG:root:lightningd-2: 2018-06-11T13:31:42.945Z lightningd(29222): Adding block 184: 0985104458bb7daaedb4b70cb5130ba3f758c233f0b74014a9f0c148ab39e1ae
DEBUG:root:lightningd-1: 2018-06-11T13:31:43.169Z lightningd(29095):jcon fd 15: Failing: Unknown command 'dev-memleak'
DEBUG:root:Received response for dev-memleak call: {'jsonrpc': '2.0', 'error': {'code': -32601, 'message': "Unknown command 'dev-memleak'"}, 'id': 0}
DEBUG:root:Calling stop with payload None
```

### `getinfo` output

Not relevant.

**Comment by jsarenik** [comment]
Full log from Alpine Linux at https://gist.github.com/jsarenik/36611568a1645b3ce1dea98aadf3797b though I have just noticed it is not the `--dev-*` thing here, but I will send a log from that as well.

**Comment by cdecker** [comment]
Have you tried rerunning it? Some of these tests are rather flaky.

**Comment by jsarenik** [comment]
Yes, tried and it's always the same.

Here's what I am doing:

```
#!/bin/sh

set -x
rm -rf lightning
git clone https://github.com/rustyrussell/lightning -b guilt/configure
cd lightning
./configure --disable-developer --disable-valgrind
make -j4
make check
```

And here's the full log (after running above with `2>&1 | tee log`): https://pastebin.com/dGfbyawM

**Comment by jsarenik** [comment]
And the same happens also on Ubuntu 18.04.

**Comment by cdecker** [comment]
On ubuntu do you have `bitcoind` installed?

```
FileNotFoundError: [Errno 2] No such file or directory: 'bitcoind': 'bitcoind'
```

And on alpine you seem to be executing with `DEVELOPER=1`, but didn't compile it with that flag:

```
DEBUG:root:lightningd-2: 2018-06-06T16:11:06.501Z lightningd(5123):jcon fd 15: Failing: Unknown command 'dev-memleak'
```

That can be fixed by running `make DEVELOPER=1 clean default`

**Comment by jsarenik** [comment]
Yes, it's there: https://gist.github.com/jsarenik/557f9b2240461369579e76ad4ac91ce8#file-ubuntu-full-log-txt-L3234 and it means that in non-developer mode a test is run which requires developer mode. The same will show up in Alpine log when it finishes...

**Comment by jsarenik** [comment]
I am adding `TIMEOUT=120` to the `make check` line as @rustyrussell suggested.

**Comment by jsarenik** [comment]
Here is latest Alpine Linux log (still without `TIMEOUT=120`): https://gist.github.com/jsarenik/e07be20339fb34f6710838a730b9b5a1

**Comment by jsarenik** [comment]
Rusty, BTW it seems to me that the `TIMEOUT` variable is not propagated in the environment of Python tests.

**Comment by cdecker** [comment]
Do you have mismatching environment variables and config.vars? That could be the issue, since the pytest scripts take the env-vars instead of the config.vars.

**Comment by jsarenik** [comment]
Yes, that's the point of this issue actually.

**Comment by jsarenik** [comment]
Sure. Checking now. Thank you for comment!

**Comment by jsarenik** [comment]
@cdecker Now I see an issue with `test_lockin_between_restart`. Both on [Alpine](https://gist.github.com/jsarenik/b8e5ec2d2245fc481452ea100fecc57a#file-alpine-full-log-txt-L1650) and [Ubuntu](https://gist.github.com/jsarenik/b8e5ec2d2245fc481452ea100fecc57a#file-ubuntu-full-log-txt-L1655).

Shall I start a new issue and close this #1548 or continue here?

**Comment by jsarenik** [comment]
I am rerunning with `TIMEOUT=120`...

**Comment by jsarenik** [comment]
Closing. The `lockin_between_restart` test is not failing with increased `TIMEOUT`. Closing this issue and excuse me for false-positive noise.

**Comment by cdecker** [comment]
No problem :-)
