### ISSUE TITLE
./lightningd --mainnet --help shows commit-fee-min/max default: 0

### ISSUE THREAD

**Issue by SimonVrouwe** [ElementsProject/lightning#1554]
### Issue and Steps to Reproduce
```
./lightningd --mainnet --help
Usage: ./lightningd 
A bitcoin lightning daemon.
--help|-h                            Print this message.
...
--commit-fee-min=<percent>           Minimum percentage of fee to accept for commitment (default: 0)
--commit-fee-max=<percent>           Maximum percentage of fee to accept for commitment (0 for unlimited) (default: 0)
--commit-fee=<percent>               Percentage of fee to request for their commitment (default: 500)
--default-fee-rate <arg>             Satoshis per kw if can't estimate fees (default: 40000)
...
```
Shouldn't the defaults for `mainnet` be `200` and `2000`?

### `getinfo` output
build today from 294c76e749996bd5d035d0bcc72dad12d63113dd

**Comment by SimonVrouwe** [comment]
ok, it looks like "testnet" is the default network and the defaults printed in the --help message are for testnet
https://github.com/ElementsProject/lightning/blob/56046d470b24d52c959cc2c558040720c907fd49/lightningd/bitcoind.c#L800

**Comment by valuead** [comment]
wait, does it means c-lightning not charging any transaction fees on bitcoin network??
Please advise.

**Comment by SimonVrouwe** [comment]
Fees are ok, it is just the help message that shows the wrong default values. When you type `./lightningd --mainnet --help` you expect to see default values behind the options for `mainnet` not for `testnet`.
