### ISSUE TITLE
channeld crash from bad gossip message

### ISSUE THREAD

**Issue by v0l** [ElementsProject/lightning#1568]
Log file: https://void.cat/555dea3a08005f7c57cc55c3165493fa8fe7e5b0

This peer reconnecting before the crash was an Eclair mobile client, 
`02062554cfc23db630c2db9b45df71c65e2839a70042464546ddfa01e975937dd0`

### lightningd --version
`v0.5.2-2016-11-21-2836-g8bfdc582`

### lightning-cli getinfo 
`{"id":"021deedd44ba443c655d454b0d8f90791e12a0ffe07dbaa52016dc40f2d310c55c","port":9735,"address":[],"binding":[],"version":"v0.5.2-2016-11-21-2836-g8bfdc582","blockheight":527091,"network":"bitcoin"}`

## Channel is open with ACINQ
https://www.robtex.com/lightning/channel/575432709004787712

**Comment by v0l** [comment]
I guess this is 2 issues, the bad gossip message and the crash when trying to `add_reconnecting_peer`

**Comment by cdecker** [comment]
That looks like a double-free/dangling pointer issue. I could find commit 8bfdc582, was this modified in some way, and if yes on what commit is this based?

**Comment by v0l** [comment]
I took a branch and removed newlines from the json, thats the only change i made. https://github.com/ElementsProject/lightning/commit/35dc854ab78938007b9ec9d5784d9c9ed0e97816

**Comment by cdecker** [comment]
Ok, I see this is based on b28d71a9a575dc3a814b73849f868b3a03013637. Not too familiar with the reconnect structure, so I'll assign @rustyrussell

**Comment by lodotek** [comment]
Anyone know how to fix "lightningd: lightning_gossipd failed (exit status 242), exiting."  ?
