### ISSUE TITLE
c-lightning rejects a `channel_reestablish` on new connection

### ISSUE THREAD

**Issue by pm47** [ElementsProject/lightning#1580]
### Issue and Steps to Reproduce

This happened on a channel between our node and satoshis.place.

nodeid= `024655b768ef40951b20053a5c4b951606d4d86085d51238f2c67c7dec29c792ca`
channelid=`5f22f6cd8e00ccdb954311cd7a4cd58c4ab80a8d9859f0690c7f6c5615ea353c`

It seems the node has been restarted, then eclair has tried mutiple times to resume the channel: at first, connection attempts just failed (node probably offline), then we could open a connection and we were able to send a `channel_reestablish` but then connection kept getting closed.

Eventually after the nth reconnection, c-lightning sends us an error `Unexpected message 136 for peer`, and we unilaterally close the channel.

I'm creating the issue here and not in eclair because I have made sure that we had indeed just sent one `channel_reestablish` (and also possibly multiple BOLT7 messages) on this particular connection and everything seems normal on our end.

Attached [relevant eclair logs](https://github.com/ElementsProject/lightning/files/2101673/5f22f6cd8e00ccdb954311cd7a4cd58c4ab80a8d9859f0690c7f6c5615ea353c.log.gz) for reference.

### `getinfo` output

Unknown.  Hopefully @LightningK0ala can provide some logs from c-lightning side?

**Comment by pm47** [comment]
A seemingly unrelated error that also appears in these logs are invalid `node_annoucements` sent by c-lightning, eg: `0101d5bfb0be26412eed9bbab186772bd3885610e289ed305e729869a5bcbd97ea431863b6fa884b021162ed5e66264c4087630e4403669bab29f3c533c4089e508c00005ab521eb030e9226f19cd3ba8a58fb280d00f5f94f3c10f1b4618a5f9bffd43534c966ebd4030e9256495247494e41574f4c465f3200000000000000000000000000000000000000000f03cec0cb03c68094bbb48792002608`

This is related to tor, looks very much like a bug on an [old non-merged PR](https://github.com/ElementsProject/lightning/pull/1175#pullrequestreview-111994441), and doesn't seem to be on current master so I'm a bit confused as to which version @LightningK0ala is running: https://github.com/ElementsProject/lightning/blob/d9a672ab02faf0eef3d388c00e5230800b84b87b/common/wireaddr.h#L42-L44

**Comment by cdecker** [comment]
Could this be related to the, still unmerged, commit bb98b2a31c71300c7c85a1fdf7c66cf8180f49c6, which also attempts to fix reestablish, but what c-lightning believes to be spurious re-establish messages?

**Comment by pm47** [comment]
I suppose if we had c-lightning logs we could tell?

**Comment by cdecker** [comment]
Sorry, my mistake, that commit is about resending commitments not the `channel_reestablish`. But logs would indeed be useful.

**Comment by Saibato** [comment]
@pm47  this is how it should lock like not the same node but and typ 3 tor
`0101b23c72f569a6bc144e3fe172ef687d134b5ce0e261e83d948b030fe0556400897c1aec114cc97a80b42d860117ff63e146e4a17b76c6921bc2d2174367da2cac00005b22915303e15692ca46526395ba405bf89787a69d8854cf105394f013f98863ab9e38194703e156534c49434b45525355434b45522d000000000000000000000000000000000000000d0370df9ab4881c065e9c702607`
so we have  a ...........000**0d**0370df9ab4881c065e9c702607   not a **0f**

what you get there must be an announcement to an old tor test-node    
to hunt for answers, can we  be sure that  the message came from www.satoshis.place?
as the message itself refers to a  node that does not send such tor messages.

@cdecker   you are right not related to active commits 
they are indeed old 37 len tor message, so no direct  code issue, but wrong formated messages that linger around from caches for ever?

**Comment by rustyrussell** [comment]
Announce is corrupt, for VIRGINAWOLF_2.  But you *should* be ignoring it (it looks like address type 08, which is undefined).

Complaining about reestablish packet is possible if other node has dropped channel to onchain, for example, but I'll check...

**Comment by Saibato** [comment]
@rustyrussell  VIRGINAWOLF_2 talked to her should be updated by now ;-) 
the messages must come from old stores or caches @pm47  are the still broadcasted?

**Comment by pm47** [comment]
@Saibato yes I'm positive the invalid message comes from the satoshis.place node. Indeed the announcement you pasted is valid.

@rustyrussell 

> Announce is corrupt, for VIRGINAWOLF_2. But you should be ignoring it (it looks like address type 08, which is undefined).

We do ignore it, to be clear I'm pretty sure this is completely unrelated to the main issue here. 

It is not a type 08 but a type 03?

```
0101 // type=node_announcement
d5bfb0be26412eed9bbab186772bd3885610e289ed305e729869a5bcbd97ea431863b6fa884b021162ed5e66264c4087630e4403669bab29f3c533c4089e508c // sig
0000 // features
5ab521eb // timestamp
030e9226f19cd3ba8a58fb280d00f5f94f3c10f1b4618a5f9bffd43534c966ebd4 // node_id
030e92 // rgb_color
56495247494e41574f4c465f3200000000000000000000000000000000000000 // alias
000f // addrlen
03 cec0cb03c68094bbb487 9200 2608 // tor v2 address with bad length (2 bytes in excess)
```

> Complaining about reestablish packet is possible if other node has dropped channel to onchain, for example, but I'll check...

The `channel_reestablish` error is what caused us to close the channel, not the other way around.

**Comment by cdecker** [comment]
There are a number of ways to forget a channel in c-lightning. The first is simply forgetting a channel because it took too long to confirm (as outlined by [BOLT 02](https://github.com/lightningnetwork/lightning-rfc/blob/42a2963a3da2225576e1fedd9038b169eadcc741/02-peer-protocol.md#requirements-4):

> A non-funding node (fundee):
>
> SHOULD forget the channel if it does not see the funding transaction after a reasonable timeout.

Notice that we might end up doing this even after a short period of time if the node was still syncing (from its view x blocks were found between it seeing the `channel_open` and forgetting it, even though it was just catching up >>x blocks from current head).

Another way to forget a channel is by calling `dev-forget-channel`, which is highly discouraged.
