### ISSUE TITLE
Really strange stuff in my logs re:  Uncompressed 13219 into 26520 bytes Spam

### ISSUE THREAD

**Issue by Xian001** [ElementsProject/lightning#1581]
### Issue and Steps to Reproduce

Just running my node as normal.

Did establish a route to satoshis.place, which I figure might have something to do with this ?

Strange stuff...

> 2018-06-14T14:11:27.734Z lightning_gossipd(22958): Uncompressed 13219 into 26520 bytes (07b00800053f000107b155000464000007b1d7000375000107b1f6000953000107b1f70007c9000007b1fd000456000007b23f00034d000107b272000415000107b2a1000277000107b30e0005cb000007b31d0003d5000107b33c0004af000007b3f10002ac000107b4130003c1000107b42a000709000007b4400003b1000007b4a0000526000107b4ad000124000007b4ae000551000007b4bd00032a000007b4d4000427000007b4d400042a000007b4d400042b000007b4d400042c000007b4d500019a000007b4d500019d000007b4dc00009c000107b53b0005c5000007b53c0000df000007b544000206000007b56e000473000107b57600042a000107b577000968000107b5970005f9000007b599000391000107b5a800050b000007b5b40001ec000007b5b9000273000107b5c8000167000107b5fd00008a000007b6020004c5000007b60600012a000107b60600012b000007b6230003d0000007b6230003ed000007b6230003ee000007b62a00023d000107b6470003c0000007b6850000d7000007b696000774000007b69c000361000107b6a900047c000007b6ac0001e8000107b6e400047e000107b6e60005b6000107b6f50002df000007b6f50002e...e0001)
[strange shit in muh logs.txt](https://github.com/ElementsProject/lightning/files/2102683/strange.shit.in.muh.logs.txt)

It's been like that for the last 18 hours, best I can tell.

### `getinfo` output
```
./lc getinfo
{
  "id": "021f2cbffc4045ca2d70678ecf8ed75e488290874c9da38074f6d378248337062b", 
  "version": "v0.5.2-2016-11-21-2867-g56046d4", 
  "blockheight": 527296, 
  "network": "bitcoin"
}
```

**Comment by Xian001** [comment]
Upgraded today. Issue persists. Issues channel close for strange peer.

Unrelated: Re-established closed channel with satoshis.place and will see if it sticks. Got prematurely closed sometime over the last 24 hours.

`"version": "v0.5.2-2016-11-21-2882-gf8da37f"`

**Comment by rustyrussell** [comment]
2018-06-14T14:11:26.756Z lightning_gossipd(22958): Compacting gossip_store with 19688 entries, 18446744073709551605 of which are stale

^ This is concerning, @cdecker ?
