### ISSUE TITLE
Delay (locktime) is 576 blocks; max delay requested is 500.

### ISSUE THREAD

**Issue by windsok** [ElementsProject/lightning#1586]
### Issue and Steps to Reproduce
`Delay (locktime) is 576 blocks; max delay requested is 500.`
I've received this error quite a few times when trying to make payments from c-lightning.

Some observations:
* It seems to be mostly when the payment route was 4+ hops
* I mostly received it when the first peer in the route was rompert.com (not sure if they have some custom settings, or just LND defaults)
* Changing the maxdelay setting on the pay API resolves the issue, but must be set for every payment (there does not seem to be a server level setting to change the value, the obvious setting "max-locktime-blocks" seems to be a separate setting not related to this.)

Sorry for the vague issue... hoping @rustyrussell  can add more relevant information :)

```
{ "code" : 206, "message" : "Delay (locktime) is 576 blocks; max delay requested is 500.", "data" :
{
  "msatoshi": 1797000,
  "fee": 1005,
  "feepercent": 0.055927,
  "maxfeepercent": 0.500000,
  "delay": 576,
  "maxdelay": 500,
  "getroute_tries": 6,
  "sendpay_tries": 0,
  "route": [
    {
      "id": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b",
      "channel": "526727:555:0",
      "msatoshi": 1798005,
      "delay": 576
    },
    {
      "id": "02d539692f55b6d61847dc432bb78166bf52318e80e6b33733bb75f76645656e27",
      "channel": "525293:1573:1",
      "msatoshi": 1798003,
      "delay": 432
    },
    {
      "id": "02e6b17c5a7a2461df38d0a571d92660f38ed5bbc847166ee655a1d0f83c1aa5ac",
      "channel": "525718:869:0",
      "msatoshi": 1798001,
      "delay": 288
    },
    {
      "id": "038118e0490f8d3df07b6bdc5e7034dee90d769012764d31bfeb167269866824f0",
      "channel": "527502:2243:1",
      "msatoshi": 1797000,
      "delay": 144
    }
  ],
  "failures": [
  ]
} }
```

**Comment by rustyrussell** [comment]
We should set default to max-locktime-blocks, agreed.
