### ISSUE TITLE
Closing a channel put our server on fire

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#1612]
We were doing some tests on testnet when @anditto tried to close a channel.

Immediately after channel closure, the server became unresponsive.

![image](https://user-images.githubusercontent.com/3020646/41702775-43363b20-756c-11e8-8330-ae0364e77f5d.png)

While I can't be 100% sure it is from clightning as I can't even access my VM anymore, the timing was really perfect.

It was based on https://github.com/NicolasDorier/lightning/commits/v0.0.0.21 (from 5 days ago)

I am now rebasing on latest commits to see if we can replicate on latest commits.

**Comment by NicolasDorier** [comment]
Our mainnet server got similar issue yestersday on same commit:

![image](https://user-images.githubusercontent.com/3020646/41703322-d909d0ac-756d-11e8-940a-a0575de51a53.png)

Note that I don't remember https://github.com/NicolasDorier/lightning/commits/v0.0.0.20 being impacted.

**Comment by NicolasDorier** [comment]
Killed the server, restarted the VM

```
2018-06-21T07:18:28.517Z lightningd(11): Waiting for bitcoind to warm up...
lightningd: Fatal signal 11 (version v0.0.0.21-bench-modded)
0x55b50fd8168a crashdump
        common/daemon.c:37
0x7fd1b292e0dc ???
        ???:0
./entrypoint.sh: line 84:    11 Segmentation fault      (core dumped) lightningd
```

**Comment by cdecker** [comment]
Any particular reason you are tagging your own version? I was wondering a few days ago where an issue reporter had gotten v0.0.0.20 from.

**Comment by NicolasDorier** [comment]
yes. BTCPay is 99% of the time deployed via a docker-compose file where all the images have pinned versions.

When I want to update an image on which BTCPay depend, I just need to push a new image to docker hub, then I bump the version in docker-compose file.

When merchants want to update btcpay, they run `btcpay-update.sh`, which just pull the latest docker compose of BTCPay, and run `docker-compose up`. This reboot only the containers impacted by the version change.

**Comment by cdecker** [comment]
Ah ok, where you able to recover more of the logs from `docker logs`?

**Comment by NicolasDorier** [comment]
Not yet. I updated the nodes to latest commit, trying to replicate the bug with newest.

**Comment by NicolasDorier** [comment]
Ah I forgot to mention: Actually I did checked the log for the server which got lot's of disk write. (mainnet one)

I had RPC working queue issues at bitcoind level. Unsure what command was doing this though.

**Comment by shesek** [comment]
@NicolasDorier how about using c-lightning's original version and appending it with your own? i.e. something like `v0.5.2.11` for your 11th update to `v0.5.2`.

**Comment by NicolasDorier** [comment]
yes this is good idea. Another alternative is to just put the commit I am based on.

**Comment by NicolasDorier** [comment]
Closing this for now, I am not able to reproduce because now I can't even pay the invoice even with the two clightning properly connected together with direct channel. :(

Will reopen if same things happen again.
