### ISSUE TITLE
Gossiping not working for some LND nodes

### ISSUE THREAD

**Issue by sumBTC** [ElementsProject/lightning#1621]
Maybe it's a LND thing and already reported but still want to report this issue here.

I got an e-mail from BlackSheep2[LND] that he wanted to open a channel with me but couldn't connect to my node (running correctly as discussed in the previous issue with `--bind-addr=192.168.178.20:9735 --announce-addr=82.217.214.215:9735`)

If I try to connect to BlackSheep2[LND] (his address: 87.27.157.110)
`lightning-cli connect 036a33e92cda2679ac91ac0467acb1ba33396c0df1119521653e0f269c275dd6bf`
I get: 
```
{
  "id": "036a33e92cda2679ac91ac0467acb1ba33396c0df1119521653e0f269c275dd6bf"
}
```

which looks fine but GOSSIPING state of that node it's not visible in lightning-cli listpeers
The same is true for another LND node: 🚀🌑lnd.TrueVision.club
`025e77156e4c5e1ed62f9ad113ac2115a981ee99fa05d95be9e43add7f785a9b4d`

If I connect to some other random node like LightningPlatinum
`022d73890548be3625f822f0294d1c30934c6063df8904bafc70224920e14f10e7`
it works just fine and he's visible in `lightning-cli listpeers`

BlackSheep2[LND] told me in an e-mail correspondence that he couldn't connect to my node and sent me this output:

> it dont work... i send u log if can help
> ```
> 2018-06-19 21:52:03.549 [INF] SRVR: Established connection to: 82.217.214.215:9735
> 2018-06-19 21:52:03.549 [INF] SRVR: finalizing connection to 02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0, inbound=false
> 2018-06-19 21:52:03.606 [INF] SRVR: Negotiated chan series queries with 02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0
> 2018-06-19 21:52:03.606 [INF] DISC: Creating new gossipSyncer for peer=02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0
> 2018-06-19 21:52:03.606 [INF] DISC: gossipSyncer(02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0): requesting new chans from height=528066 and 4294439229 blocks after
> 2018-06-19 21:52:03.716 [WRN] DISC: unable to apply gossip filter for peer=02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0: edge not found
> 2018-06-19 21:52:03.777 [INF] PEER: unable to read message from 82.217.214.215:9735: unknown short chan id encoding: 1
> 2018-06-19 21:52:03.777 [INF] DISC: Removing gossipSyncer for peer=02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0
> 2018-06-19 21:52:03.777 [ERR] SRVR: unable to get channel links: unable to locate channel link by destination hop id 02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0
> ```
> 
> I also can not connect to your peer...
> 

Here is my `getinfo`
```
{
  "id": "02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0", 
  "port": 9735, 
  "address": [
    {
      "type": "ipv4", 
      "address": "82.217.214.215", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "192.168.178.20", 
      "port": 9735
    }
  ], 
  "version": "v0.6rc2", 
  "blockheight": 528867, 
  "network": "bitcoin"
}
```

**Comment by ccdle12** [comment]
@sumBTC 
Moving my comment from the previous issue as I think it's more relevant here.

I was having a similar problem in starting the node with the new --bind-addr and --announce. I've connected to your node successfully and can find it on #recksplorer.

```
{
      "state": "GOSSIPING",
      "id": "02c5371591b640da03f9a645e2ddfa5620d8537388b03ddd524d36766c0f550db0",
      "alias": "Bight.nl",
      "color": "23354d",
      "netaddr": [
        "82.217.214.215:9735"
      ],
      "connected": true,
      "owner": "lightning_gossipd"
    }
```

I'm having trouble finding my node on #recksplorer but it seems like I can connect to your node and other nodes. 

Would appreaciate if someone could try to connect to my node below
021187f1f8ceaeb33e933fef27a3097f42c503c14d38a4f109cb5bdf59ce2ccd9d@35.237.28.239:9735

**Comment by sumBTC** [comment]
I'm confused shouldn't this discussion be posted in How to start lightning node now that --ipaddr is gone? #1620?

**Comment by ccdle12** [comment]
@sumBTC 

Apologies for the confusion. No i'm not running LND, but had the same issue with --ipaddr

**Comment by sumBTC** [comment]
If you post in #1620? only that you had the same issue with --ipaddr that's useful. Since it's working let us remove all posts here.

**Comment by sumBTC** [comment]
If you post that you had the same issue with -ipaddr in #1620 that's useful. Let's remove all posts here.

**Comment by cdecker** [comment]
```
unable to read message from 82.217.214.215:9735: unknown short chan id encoding: 1
```

That seems to suggest that `lnd` doesn't support the zlib encoded channel ID exchange yet (https://github.com/lightningnetwork/lightning-rfc/pull/392/commits/b7d0549344024c1496aa0200e6006a78f8d81ec6).

**Comment by cdecker** [comment]
lightningnetwork/lnd#1399 was merged and the issue should be addressed by that.
