### ISSUE TITLE
Why channels closed automatically?

### ISSUE THREAD

**Issue by asocjal** [ElementsProject/lightning#1622]
### Issue and Steps to Reproduce
I have few clightning nodes. Some of them with the same version. I opened few channels between them as well as to some other (not mine) nodes. What I saw is, that after some time, some I no longer have some of my channels. What could be the reason of such auto-closeing channel? 

### `getinfo` output
{
  "id": "035a71a8d2e36f5ff894fd6f97225a493e0cdf013c60c3b1c6992be19bd901a9ca", 
  "port": 9735, 
  "address": [
    {
      "type": "ipv4", 
      "address": "176.107.130.62", 
      "port": 9735
    }
  ], 
  "version": "v0.5.2-2016-11-21-2610-g91d149b", 
  "blockheight": 529002, 
  "network": "bitcoin"
}

**Comment by SimonVrouwe** [comment]
there was a fee [spike](https://p2sh.info/dashboard/db/fee-estimation?orgId=1&from=now-30d&to=now&var-source=bitcoind) yesterday (25th) that closed one of my channels also and another one was closed for same reason on the 19th
plotting the ratio between subsequent `bitcoind` `estimatesmartfee` taken at 2m interval shows that even 10x fee range multiplier seems not high enough

![estimatesmartfee](https://user-images.githubusercontent.com/3152756/41981859-99172444-7a32-11e8-96f3-09cb03be88d9.png)

**Comment by cdecker** [comment]
We are thinking about smoothing the fee estimation using an EWMA, over multiple calls to `estimatefee`. The issue is more about one node seeing the spike, and the other one not seeing it, so the EWMA should give the second node more time to also adjust it's estimate.
