### ISSUE TITLE
Implement the optional data loss protection feature

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#1634]
Some users have been complaining because one of the android wallets derived from Eclair (but not ACINQs own android wallet) now requires that feature to work at all (see #1541 for example).

So we should probably implement that as well. See spec at https://github.com/lightningnetwork/lightning-rfc/commit/046f5acb1619bccf167e5539f144433495f1486b.

**Comment by rustyrussell** [comment]
OK, I'm working on this; it's queued behind the HSM changes to separate the payment key (which channeld et al do *not* need) from the other keys.

**Comment by cdecker** [comment]
This was addressed in #1854
