### ISSUE TITLE
ValueError exception thrown by LIghtningRpc is extremely difficult to parse

### ISSUE THREAD

**Issue by marzig76** [ElementsProject/lightning#1638]
When a ValueError is thrown, for instance when you're paying an invoice but the locktime exceeds the max delay, the resulting error is extremely difficult to parse.

Here's an example of one (I stripped it down to be easier to read):

`RPC call failed: {u'message': u'Delay (locktime) is 734 blocks; max delay requested is 500.', u'getroute_tries': 8}, method: pay, payload: {'bolt11': u'lnbc1...x'}`

It's essentially a single string with keys like "RPC call failed", "method" and "payload", but each of the values associated with those keys are string representations of a dict.

In order to use one of those dicts in a meaningful way, you'd have to extract that portion of the string out, then use something like the ast.literal_eval class.

I've tried to implement something to parse it [here](https://github.com/marzig76/fulmo/blob/13f748a82586e9555f945260725b5d07fc41c1a4/fulmo.py#L214), but it doesn't always work because the depth of nested dicts seems to change from case to case, making it hard to extract the exact portion of the string that is a dict.

If I'm going about this the wrong way, please let me know.  But I feel it would be much easier to use if the whole exception message was just a JSON object or even a single dict, which could then easily be used.

**Comment by cdecker** [comment]
Agreed, I had a branch somewhere that gave access to the parsed JSON error. Will try to recover it :-)

**Comment by marzig76** [comment]
@cdecker 

That would be great.  Thank you.
