### ISSUE TITLE
CI: a2x missing in test container on travis

### ISSUE THREAD

**Issue by jsarenik** [ElementsProject/lightning#1642]
### Issue and Steps to Reproduce

https://travis-ci.org/ElementsProject/lightning/jobs/397907209

@cdecker please try to clear cache or have a look what could be the cause (surely not my patches which have nothing to do with `a2x`).

**Comment by cdecker** [comment]
OK, with `--no-install-recommends` we can exclude the `latex` dependency, which would have blown up the image by several GB. So I'll push new builder images to fix this.

**Comment by cdecker** [comment]
See PR #1647, also new images pushed on docker hub, so Travis should be happy now ^^
