### ISSUE TITLE
Problems establishing a channel with globee.com ?

### ISSUE THREAD

**Issue by Xian001** [ElementsProject/lightning#1643]
### Issue and Steps to Reproduce
https://www.robtex.com/lightning/node/022c699df736064b51a33017abfc4d577d133f7124ac117d3d9f9633b6297a3b6a

Trying to connect to this node, and establishing a channel. Every time I try to fundchannel, it comes back with "Peer not connected"

### `getinfo` output
"version": "v0.6-1-ge59489f",

**Comment by cdecker** [comment]
Can you share the relevant logs when trying to `fundchannel`?

**Comment by cdecker** [comment]
Seems that this may be caused by `lnd` not implementing `libz`. That has been addressed recently on their end, so upgrading the `lnd` node should get rid of this issue.

**Comment by Xian001** [comment]
Confirmed I was able to establish a channel with globee now. Thanks !
