### ISSUE TITLE
"Peer not connected" right after connecting to the peer

### ISSUE THREAD

**Issue by martinbehrens** [ElementsProject/lightning#1645]
Very similar to #677.

Funding a channel fails with "Peer not connected" although connecting to the peer earlier seems successful.

### Issue and Steps to Reproduce
1. Connect to a peer

`[u@box ~]$ lightning-cli connect 02ab16f790c7727eac2048771cbe95cbcc1aa93931558c0fd87c06d5c389475a7b $ip $port
{
  "id": "02ab16f790c7727eac2048771cbe95cbcc1aa93931558c0fd87c06d5c389475a7b"
}`

(no message in debug.log)

2. Try to fund the channel

`
[u@box ~]$ lightning-cli fundchannel  02ab16f790c7727eac2048771cbe95cbcc1aa93931558c0fd87c06d5c389475a7b $sat
{ "code" : -1, "message" : "Peer not connected" }
`

debug.log:

`
2018-06-29T09:51:49.145Z lightningd(1681): Connected json input
2018-06-29T09:51:49.518Z lightning_gossipd(1690): release_peer: peer 02ab16f790c7727eac2048771cbe95cbcc1aa93931558c0fd87c06d5c389475a7b not found
2018-06-29T09:51:49.518Z lightning_gossipd(1690): REPLY WIRE_GOSSIPCTL_RELEASE_PEER_REPLYFAIL with 0 fds
2018-06-29T09:51:49.518Z lightningd(1681):jcon fd 4: Failing: Peer not connected
`

### `getinfo` output

` "version": "v0.6rc2-1-ge59489f",
  "blockheight": 529729,
  "network": "bitcoin"`

**Comment by cdecker** [comment]
Could you check whether between the `connect` and the `fundchannel` call you're connected? Calling `listpeers` should show that peer as "gossiping".

Also could you share the output of `lightningd` while doing connecting and attempting to fund?

**Comment by cdecker** [comment]
I would guess that this is a duplicate of #1643 and related to `lnd` not implementing the compressed channel ID sync.

**Comment by martinbehrens** [comment]
@cdecker I second that guess. Someone running LND had a problem connecting just now and the error message on their end was the one mentioned in #1621 "unknown short chan id encoding".

I'm not sure of the version they're running but they will upgrade to latest code in master branch on Monday. I'll keep an eye on this and close if it solves the issue.

**Comment by cdecker** [comment]
Thanks for the update @martinbehrens, indeed the `libz` encoding was recently merged in `lnd` so upgrading should get rid of the error :+1:

**Comment by martinbehrens** [comment]
Confirmed, updating to latest LND code resolves the issue. Closing ticket. Thanks @cdecker !
