### ISSUE TITLE
Provide more obvious status message when syncing blocks?

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#1652]
I loaded up an old lightning node from ~6 months ago and opened a new channel. I was trying to figure out why my node was not confirming: 

`CHANNELD_AWAITING_LOCKIN:They've confirmed funding, we haven't yet.`

I turned on debug logging and only then I noticed it was still syncing blocks from bitcoin (I assume to catch up with the latest utxo state).

with bitcoin-cli it's very obvious when the blockchain is syncing, as cli commands return an error/warning message. Perhaps we could have some type of general "status" or "state" that lightningd is in, such as "syncing", so that the cli can provide helpful feedback?

**Comment by cdecker** [comment]
There are two places that I think this might be sensible: the output of `getinfo` and the output of `listpeers`. Excellent idea!

**Comment by jb55** [comment]
I'm working on this here: https://github.com/jb55/lightning/compare/b5682a773bac208bef1e1442b76f961e6dc604b5...jb55:lightning-status-flags
