### ISSUE TITLE
Specify minimum channel size ?

### ISSUE THREAD

**Issue by Xian001** [ElementsProject/lightning#1664]
### Issue and Steps to Reproduce
I could not seem to find it in the documentation, and hope I am overlooking something, but is it possible to currently specify a minimum channel value for nodes looking to connect to me ?

Looking to pare down my connections to clear out any low-value channels, and would like to specify at least a bare minimum value for others looking to connect to me.

Was trying to connect to a node, and got this neato spiffy message;

$ ./lc fundchannel 03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e 250000
{ "code" : -1, "message" : "received ERROR channel 6f1988624a300ce6bcea6fac655e08e984427a7933f514b86eee2df5ecb828a8: chan size of 0.0025 BTC is below min chan size of 0.003 BTC" }

### `getinfo` output
"version": "v0.6-1-ge59489f"

**Comment by cdecker** [comment]
As far as I know this is currently not implemented, but it can easily be. We'd need to add a command line, pass the value to `openingd` and check the value against the proposed funding output.

**Comment by darosior** [comment]
This is now implemented as the `min-capacity-sat` configuration option (https://lightning.readthedocs.io/lightningd-config.5.html#lightning-node-customization-options) so I think this can be closed ?

**Comment by Xian001** [comment]
Thank you kindly.
