### ISSUE TITLE
Question about how it works

### ISSUE THREAD

**Issue by hxsquid** [ElementsProject/lightning#1665]
Hello, Are y'all with knowledge of this project willing to assist - I'm working on a wallet implementation. 

The problem: I construct the commitment tx per specs, sign it, send funding open msg, and get back an error response containing "bad signature" along with a serialized tx. That tx contains only one p2wkh (remote) output -- I was expecting to see a local output. Also the hash in that p2kwh ouput doesn't correspond to the remote funding key. 

Hmmm ...

**Comment by ZmnSCPxj** [comment]
Closing, seems moot?
