### ISSUE TITLE
I did a stupid: "Updating database from version 35 to 83" - Restored old .lightning dir

### ISSUE THREAD

**Issue by Xian001** [ElementsProject/lightning#1666]
### Issue and Steps to Reproduce

I did a really stupid thing, and sent some BTC to an old address that was used in a previous incarnation of my node.

Tried to load up the last backup I had of the .lightning directory, and got the following errors when trying to launch with latest.

> 2018-07-06T03:13:04.801Z lightningd(25930): testing /mnt/md0/lightning/lightningd/lightning_channeld
> 2018-07-06T03:13:04.802Z lightningd(25930): testing /mnt/md0/lightning/lightningd/lightning_closingd
> 2018-07-06T03:13:04.802Z lightningd(25930): testing /mnt/md0/lightning/lightningd/lightning_gossipd
> 2018-07-06T03:13:04.803Z lightningd(25930): testing /mnt/md0/lightning/lightningd/lightning_hsmd
> 2018-07-06T03:13:04.803Z lightningd(25930): testing /mnt/md0/lightning/lightningd/lightning_onchaind
> 2018-07-06T03:13:04.804Z lightningd(25930): testing /mnt/md0/lightning/lightningd/lightning_openingd
> 2018-07-06T03:13:04.805Z lightningd(25930): Updating database from version 35 to 83
> db_migrate:SQL logic error or missing database:CREATE TABLE htlc_sigs (channelid INTEGER REFERENCES channels(id) ON DELETE CASCADE, signature BLOB);:table htlc_sigs already exists

Any suggestions on how to unfsck this situation ?

### `getinfo` output
"version": "v0.6-44-g13796f0"

EDIT: Think I might have the old binaries around. Will try a swaparoo shortly and see if that doesn't help.
EDIT2: Crap. Went back to something that was running database version 40, and that failed to update version  35 as well...

**Comment by cdecker** [comment]
It seems the migration numbering was changed at some point. We need to manually migrate a few of them.

1. Make a backup so if anything goes wrong we can recover that
2. Look at the failing migration and see if it was already applied (in this case check the output of `.schema` to see if the table `htlc_sigs` already exists).
3.  Bump the version number of the DB (`UPDATE version SET version=version+1` should do that)
4. Exit and try to restart `lightningd`, if it works, congrats, otherwise go back to 2.

My guess is that you'll need this at least twice since the `CREATE TABLE` and the following `CREATE INDEX` were likely created in the same commit.

**Comment by Xian001** [comment]
Thank you very kindly for this info.

I'll attempt fscking around with the db later on this evening, and see if things don't get resolved.

Cheers.

**Comment by Xian001** [comment]
Ok, got the db up to v40, and launching with the binaries I have around, produce the following error now;

> db_migrate:SQL logic error or missing database:INSERT INTO db_upgrades VALUES (40, 'v0.5.2-2016-11-21-2073-gd499c34');:no such table: db_upgrades

<3

**Comment by NicolasDorier** [comment]
Why not just re-compiling an old version of clightning so you can get your money out?

**Comment by Xian001** [comment]
>Why not just re-compiling an old version of clightning so you can get your money out?

I tried pulling down a .zip of an earlier build I thought might work, but when I unzipped it and tried to compile things, it was getting hung up trying to resolve downloading dependancies :( 

I'm open to suggestions. Probably did something wrong here with github ?

eg:

```
:/mnt/md0/recovery/lightning$ make
if git submodule status external/libwally-core | grep -q '^[-+]'; then rm -rf external/libwally-core; git submodule update --init external/libwally-core; fi
fatal: Not a git repository (or any parent up to mount point /mnt/md0)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cd external/libwally-core && ./tools/autogen.sh && ./configure CC="cc" --enable-static=yes --enable-module-recovery --enable-shared=no --libdir=`pwd`/.. && make
/bin/sh: 1: ./tools/autogen.sh: not found
external/Makefile:44: recipe for target 'external/libwally-core/src/libwallycore.la' failed
make: *** [external/libwally-core/src/libwallycore.la] Error 127
```
Thank you.

**Comment by cdecker** [comment]
Was that in a git clone? It seems that it can't find the libwally repo. Try a clean clone and build in there.

**Comment by Xian001** [comment]
>Try a clean clone and build in there.

I need to sheepishly admit, I am new to this github thing, and am not sure about how to clone a particular version via the git command. Some further insight/commands would be most appreciated.

It was not clear how to clone an older version, when I went to track down a candidate.

I wgot a .zip from a link that github produced, for a build on Feb.10

**Comment by cdecker** [comment]
```
git clone https://github.com/ElementsProject/lightning.git /tmp/lightning
cd /tmp/lightning
git checkout 68639db7dbc194a64fee0c10bc6b5a02b1564637 # Last commit on Feb. 10th
make
```

Afterwards you'll have the binaries in `/tmp/lightning/lightningd` :wink:

**Comment by Xian001** [comment]
I love you, man. Thanks ! 

She's syncing now.

Closing out. Have an awesome one !

**Comment by cdecker** [comment]
Glad it worked out, but this should not have happened. I suggest draining (`close` channels and `withdraw` funds to another wallet) the node and setting up a new one. Sorry for the complications :unamused:

**Comment by Xian001** [comment]
Dude, not a problem at all, and I appreciate all your help. I know this is a situation of "this should not have happened", but it was a dumb move on my part with how I initially was learning about setting things up.

I totally went into this clightning testing thing fully aware of the mindset of "you might lose coins" - Not testing with any more than I'd blow on a weekend in Vegas - but having said that, the OCD geek in me wants to resolve this outstanding-funds issue with the latest Master branch not building, so, perfect timing all-in-all.

I will withdraw back to the main wallet and move the funds back to the "Live" node when things are all closed down.

I understand "close"ing channels does take some time.

Is "dev-fail"ing them absolutely verboten, and I'm at risk of losing funds if I do so, if "close" is being stubborn ?

Also, I guess there is no way to tell lightning-cli to close-all at once ? Just need to be patient to wait for things to clear out, once "listfunds" shows no peers ?

Thanks again.

Enjoying my early retirement playing around with your project ;)

**Comment by cdecker** [comment]
`dev-fail` should be ok, but it'll directly start the 144 block timeout, whereas `close` has a chance to do a collaborative close which doesn't have that timeout.
