### ISSUE TITLE
Removing the legacy daemon

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#167]
Since we have almost reached feature parity it's time to remove the legacy daemon from the source tree. I think the following features are missing before we can do that:

 - [x] Support re-establishing connections on disconnect
 - [ ] Support re-establishing connections after restarts
 - [x] Track funds across restarts
 - [x] Closing negotiation
 - [ ] On-chain unilateral close
 - [ ] On-chain penalty transaction

This being a rather large change, I would also propose a reorganization of the source tree:

 - Remove source files that are not in use by the new daemon
 - Remove `protobuf-c` as a dependency
 - Rename the `lightningd` directory to `src`, and move all other source directories into that directory. This results in a clean top level directory with README.md with associated documentation, and the `contrib` directory.

Did I miss something @rustyrussell?

**Comment by rustyrussell** [comment]
Ok, added some points.  I'm working on connection re-establishment, which means cleaning up the state transitions so we can tell exactly where we are when a reconnect comes in.

Then I'll need the database parts to restart the daemon, and do similar logic.

The closing and on-chain handling are almost orthogonal, and can be done in parallel.
