### ISSUE TITLE
Open node so others can join

### ISSUE THREAD

**Issue by laz666** [ElementsProject/lightning#1671]
### Issue and Steps to Reproduce

Hi guys, I am struggling to allow others to connect to my node. I am using Ubuntu.

I have tried the below firewall settings, but others still cannot connect. Is there anything else I need to do? Thanks.

# Install firewall

$ sudo apt-get install ufw 

# Create firewall rules

$ sudo ufw default deny incoming

$ sudo ufw default allow outgoing

$ sudo ufw allow from <IP_ADDR> to any port 22 comment ‘allow SSH from specific host or network’

$ sudo ufw allow 8333 comment ‘allow Bitcoin’

$ sudo ufw allow 9735 comment ‘allow Lightning’

# Enable firewall and check status

$ sudo ufw enable

$ sudo ufw status

# Enable firewall on boot

$ sudo systemctl enable ufw

### `getinfo` output

**Comment by Xian001** [comment]
Do you have port-forwarding properly set up from your router to your Ubuntu box ?

Can you provide further details of how your network is configured ?

**Comment by Xian001** [comment]
>Can you provide further details of how your network is configured ?

**Comment by cdecker** [comment]
Please ask for help at a help forum, this is an issue tracker for development.
