### ISSUE TITLE
gossipd/gossip.c:1702:7: error: implicit declaration of function ‘structeq’

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1674]
Duplicate of comment https://github.com/ElementsProject/lightning/pull/1618#issuecomment-403248725 in closed entry.

### Issue and Steps to Reproduce

$ make
...
cc -DBINTOPKGLIBEXECDIR='"'../libexec/c-lightning'"' -Werror -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -std=gnu11 -g -fstack-protector -I ccan -I external/libsodium/src/libsodium/include -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbase58/ -I external/libbacktrace/ -I external/libbacktrace-build -I . -I/usr/local/include    -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DBINTOPKGLIBEXECDIR='"'../libexec/c-lightning'"'  -c -o gossipd/gossip.o gossipd/gossip.c
gossipd/gossip.c: In function ‘find_local_update’:
gossipd/gossip.c:1702:7: error: implicit declaration of function ‘structeq’ [-Werror=implicit-function-declaration]
   if (structeq(scid, &i->scid))
       ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'gossipd/gossip.o' failed
make: *** [gossipd/gossip.o] Error 1
rm external/libwally-core/src/secp256k1/libsecp256k1.la
$

**Comment by robbaltzer** [comment]
Getting the same here. Maybe a different branch will work better?

**Comment by robbaltzer** [comment]
Yeah - the branch `issue-1587` seems to compile fine.

**Comment by cdecker** [comment]
Two concurrently merged PRs caused a regression. #1678 will solve that.
