### ISSUE TITLE
Node on testnet can connect and gossip with node on mainnet ?

### ISSUE THREAD

**Issue by BobleChinois** [ElementsProject/lightning#1677]
### Issue and Steps to Reproduce
I currently run a node with lnd on mainnet. I want to make some tests with c-lightning and lightning charge, so I run testnet c-lightning on another laptop. 

I typed
``$ ./lightning-cli connect [my-lnd-node-on-mainnet-pubkey]@[my-public-IP-and-port]
``
and succeed to connect, now ``listpeers`` gives : 
``{
  "peers": [
    {
      "state": "GOSSIPING", 
      "id": "[my-other-node-ID]", 
      "netaddr": [
        "[my-other-node-IP-and-port]"
      ], 
      "connected": true, 
      "owner": "lightning_gossipd"
    }
  ]
}
``
Is it normal that two nodes on different networks can connect and gossip ? It doesn't feel right to me...

### `getinfo` output
``{
  "id": "025b04618a2b31ceabcf5fb70872ff8be7b8de74f3d9d72ff18382cd8671a9b72e", 
  "alias": "SILENTROUTE-", 
  "color": "025b04", 
  "port": 9735, 
  "address": [
    {
      "type": "ipv4", 
      "address": "[my-IP]", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "127.0.0.1", 
      "port": 9735
    }
  ], 
  "version": "v0.6-45-ga9cf733", 
  "blockheight": 1352010, 
  "network": "testnet"
}
``
and the `getinfo` of my LND node :
``{
    "identity_pubkey": "0306ea2f621073076c33f190eb8843e79653d5fc1375c2196f8c90875434d4aa74",
    "alias": "MYNODE",
    "num_pending_channels": 0,
    "num_active_channels": 3,
    "num_peers": 7,
    "block_height": 531029,
    "block_hash": "00000000000000000024b753372ba4472ae874c9ead62b34e68ca6edfdc7643f",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "0306ea2f621073076c33f190eb8843e79653d5fc1375c2196f8c90875434d4aa74@[my-IP]"
    ],
    "best_header_timestamp": "1531051553",
    "version": "0.4.2-beta commit=b5a228808b0446d6758a23e24d6c686aab9936fc"
}
``

**Comment by cdecker** [comment]
That's perfectly fine. The reason we allow this is mainly that we'll eventually want to make `lightningd` a multi-currency daemon. Don't worry, it's impossible to mix bitcoins and testcoins.

It's also the reason why we don't differentiate by port or have a magic header like Bitcoin.
