### ISSUE TITLE
Dockerfile and other updates

### ISSUE THREAD

**Issue by Deadlyelder** [ElementsProject/lightning#168]
# Issue

* The Dockerfile is based on Ubuntu which tends to be a bit heavy on the storage. 
* Multiple installation over different instances of Lighting can be time-consuming processes.

# Solution

Hence as a next step forward from the issue #167 maybe the following should be addressed:

- [ ] Update the Dockerfile to Alpine or similar distribution
- [ ] Automated script for 'one-click' installation of LN and its dependencies

Not exactly issues but feel it needs to be addressed for make it easier for people to play with the implementation. 

P.S. Was unable of find the correct title :P

**Comment by cdecker** [comment]
Thanks @Deadlyelder, these are all valid points, however I think it is a bit premature to think about facilitating deployment (either in a docker image or on OS without compiling from source). The docker images in particular are mainly used for our CI to build, and I think it's not worth it to slim them down and try to get them to work on another distro. Once we have releases that are to be rolled out to users, then yes, it makes sense to create slim docker images and set up a PPA (incidentally I have registered a PPA already: https://launchpad.net/lightning-network).

So I'm closing this for now, but I'll reopen it once a more or less stable version is ready :wink:

**Comment by Deadlyelder** [comment]
Ah thats great! Didn't knew PPA was already there for Lightning Network 👍
