### ISSUE TITLE
close command does not work on short channel id

### ISSUE THREAD

**Issue by Xian001** [ElementsProject/lightning#1687]
### Issue and Steps to Reproduce

> 2018-07-12T14:59:44.086Z lightning_gossipd(2839): Received channel_update for channel 517684:1977:1(1) now ACTIVE was ACTIVE (from subdaemon)
> 
> $ ./lc close 517684:1977:1
> { "code" : -32602, "message" : "Short channel ID not found: '517684:1977:1'" }

### `getinfo` output
  "id": "0211ad124eaecaf2b223bad2f5381e81b3639f2a652b5aa7a0ceffc8593931fc30", 
  "alias": "ThrobbingOFFLINE2", 
  "color": "ff00ff", 
  "port": 9735, 
  "address": [
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "127.0.0.1", 
      "port": 9735
    }
  ], 
  "version": "v0.6-64-g14c6310", 
  "blockheight": 531625, 
  "network": "bitcoin"

**Comment by cdecker** [comment]
Can you share the output of `listpeers`? Are you sure that this channel is connected and in state normal?

**Comment by Xian001** [comment]
>Can you share the output of listpeers? 

Sadly, I cannot, at this time. Chicken/egg situation with the listpeers crash.
