### ISSUE TITLE
error in short channel id format ?

### ISSUE THREAD

**Issue by sstone** [ElementsProject/lightning#169]
It seems that the 8-bytes  short channel id format used in announcements is 4 bytes (block height) + 3 bytes (tx index) + 1 byte (tx output index), shouldn't it be 3+3+2 instead ?

**Comment by rustyrussell** [comment]
Fabrice Drouin <notifications@github.com> writes:
> It seems that the 8-bytes  short channel id format used in announcements is 4 bytes (block height) + 3 bytes (tx index) + 1 byte (tx output index), shouldn't it be 3+3+2 instead ?

That would have been nice idea :(

But I think this comes under our "no changes" rule?

Rusty.

**Comment by sstone** [comment]
I meant that lightning-c seems to be using 4+3+1 but the specs says 3+3+2 (maybe I've misread the code)

**Comment by rustyrussell** [comment]
Fabrice Drouin <notifications@github.com> writes:
> I meant that lightning-c seems to be using 4+3+1 but the specs says 3+3+2 (maybe I've misread the code)

Oops; I misread this as a spec bug report :)

I believe @cdecker is fixing this right now...

Thanks!
Rusty.

**Comment by cdecker** [comment]
I really shouldn't add a reference to the issue in the commit log, it duplicates notifications in the referenced issue on every rebase, sorry about that. But #173 should fix this.
