### ISSUE TITLE
low chan_satoshi amount lost when closing channel

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#1691]
as described in #1690 there was an unwanted channel close. at the time before the close I had 250 satoshi on my side of the channel which was not payed out to me (c.f.: https://www.blockchain.com/en/btc/tx/329e36c37970f66b7113c2a3be3947ddecb3e12651895d9152068f27cad98adc
and
```
{
...
    {
      "peer_id": "024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365",
      "short_channel_id": "530191:1724:0",
      "channel_sat": 250,
      "channel_total_sat": 1337000,
      "funding_txid": "71c3795d5252eb7277e548b7e3295d24549e05943ea8421fcb08c7c7028aa708"
    },
...
}
```
Actually I had received the 250 satoshi as a micro payment from a third party that was not involved with the channel. 

I guess the reason should be that dust transactions / outputs within bitcoin should not be allowed. this however yields a problem on a bigger scope when APMs come. it could happen that I receive a large payment routed via various channels with 1 statoshi payload through each route. later when channels close the funds did not arrive. (I know it is a bit hypothetical but still it's an issue)

**Comment by cdecker** [comment]
I think this should better be discussed on https://github.com/lightningnetwork/lightning-rfc, since this is part of the protocol.
