### ISSUE TITLE
What's the purpose of the initial transaction in lightning-open-channel being a segwit tx?

### ISSUE THREAD

**Issue by benma** [ElementsProject/lightning#170]
Hi

I am browsing through the code and trying to make an example work etc., and saw those lines:

https://github.com/ElementsProject/lightning/blob/811e14ff6606d5bbe5e6ebb460d56cae429a3ad5/contrib/lightning-open-channel#L12-L13

As far as I can tell, this is not the funding tx of the payment channel, but an input to it.

`newaddr` creates a p2wsh address using the custom wallet implementation. What is the reason for why this needs to be a segwit output? Or could it be a P2SH output as well? The funds are only used after they are confirmed after all, so malleability etc. shouldn't be an issue.

**Comment by cdecker** [comment]
It's actually a [P2SH-P2WPKH](https://github.com/ElementsProject/lightning/blob/811e14ff6606d5bbe5e6ebb460d56cae429a3ad5/lightningd/build_utxos.c#L47-L49) :wink: 

We could have used any other format as well (P2PKH, P2SH-P2PKH, ...), however we have the witness script machinery in place so why not use that? It just makes the wallet code a lot easier, not having to differentiate various script types.

(closing, in the hope to have addressed the question, feel free to follow up if I didn't :wink:)
