### ISSUE TITLE
Implement Autopilot

### ISSUE THREAD

**Issue by jimgolian** [ElementsProject/lightning#1705]
I want to easily and fund x channels to various nodes with a certain amount of bitcoins easily.  Implement autopilot to let c-lightning handle the connections instead of choosing them manually.

**Comment by jb55** [comment]
Related mailing list thread: 

https://lists.ozlabs.org/pipermail/c-lightning/2018-March/000014.html

```
id:EtW4eQJ6o4no8cpfQV4xmit4vqq9cnOoVhOiveKaSEFk4A8pAQAT73ZR8vGZTsV5XIZT9U-vskh5ZqvHyMux0ReIjoIhicsCtUhDx3lrmp0=@protonmail.com
```

**Comment by bjacquin** [comment]
https://lnroute.com/2019/05/17/autopilot-for-c-lightning/

**Comment by ZmnSCPxj** [comment]
https://github.com/lightningd/plugins/tree/master/autopilot

I have no idea how well the above autopilot works in practice, maybe @renepickhardt can inform.

**Comment by cdecker** [comment]
This should be / has been addressed by a plugin :-)
