### ISSUE TITLE
Missing Funds

### ISSUE THREAD

**Issue by valuead** [ElementsProject/lightning#1720]
![screen shot 2018-07-19 at 9 49 50 am](https://user-images.githubusercontent.com/9205462/42928005-ce305a70-8b3e-11e8-9360-a7f8d8368860.png)
Created new address got 343Cy7xyAkmcZ2utFaeimdc2292Z3PbpGP
funded with 0.2 btc https://www.blockchain.com/en/btc/tx/aa71f44dbe4d70b1d32ca91604407c936cdba6f5f14a540bd3c9416c4700e379
Connected to 9 nodes and want to fund all 9 channels with 1400000 satoshis each
after I funded 4 channels on my 5th lighting software was not responding for a long time.
OUTPUT back with the balance as its now empty but there was like $1000 left, how can I get OUTPUTS to show the Satoshi and continue fund channels

```
cli/lightning-cli listfunds
{
  "outputs": [
  ],
  "channels": [
    {
      "peer_id": "02529db69fd2ebd3126fb66fafa234fc3544477a23d509fe93ed229bb0e92e4fb8", 
      "short_channel_id": "532586:2203:0", 
      "channel_sat": 1400000, 
      "channel_total_sat": 1400000, 
      "funding_txid": "4c37e78067db70e967529ea36f3cafdee026f9087b48c2a7071263d0c0f703f9"
    }, 
    {
      "peer_id": "02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b", 
      "short_channel_id": "532586:2216:0", 
      "channel_sat": 1400000, 
      "channel_total_sat": 1400000, 
      "funding_txid": "8a7cf8af040bca6281e1d3d3870e9bd626098a46c029aa1e48cdec55106a74d9"
    }, 
    {
      "peer_id": "02a456b816697c6b8407ee2176475d74b790a96143bc30e896e8bf7a8852a8b637", 
      "short_channel_id": "532586:2217:0", 
      "channel_sat": 1400000, 
      "channel_total_sat": 1400000, 
      "funding_txid": "a90e6ff0fdcc9d7eb9784e33cb388bd24b06080eaebd9bc7ad90394e1b986bca"
    }, 
    {
      "peer_id": "036b32ac6acf6d178f47c2139b7327ab85bd3d5f5c40681a9a48109ea21f53e1e5", 
      "short_channel_id": "532586:2218:0", 
      "channel_sat": 1400000, 
      "channel_total_sat": 1400000, 
      "funding_txid": "8cbcd85eeb854e3ccde8731f3fd8ac0cf8fdb16d31be94e4c3ae3c7443a857e8"
    }
  ]
}
```

**Comment by valuead** [comment]
Thank you 
sqllight update did fix and I do see funds now
funds showing up in the output

**Comment by valuead** [comment]
thanks to  @cdecker the issue was resolved and all funds moved away safely. 
Question is open about Output #2 
I have one channel closed by its self but I never found funds from that channel 1400000 Satoshi.
Could it be that this is an output#2 
How can I look at the second output?

**Comment by cdecker** [comment]
The output refers to the output index in the transaction, not the database index. So you can see that transaction [`e74762946bf545b52dbd3a098b2c76c44b3998142ca695c24f005210d104a87c`](https://www.blockchain.com/en/btc/tx/e74762946bf545b52dbd3a098b2c76c44b3998142ca695c24f005210d104a87c) has many outputs, the third (starting to count from 0) goes to address `343Cy7xyAkmcZ2utFaeimdc2292Z3PbpGP` which is the wallet's address.
