### ISSUE TITLE
Docs refer to lightning-listpeers(7) but this file does not yet exist.

### ISSUE THREAD

**Issue by wintercooled** [ElementsProject/lightning#1727]
Docs such as [lightning-connect.7.txt](https://github.com/ElementsProject/lightning/blob/master/doc/lightning-connect.7.txt) refer to doc lightning-listpeers(7) but this file does not exist.

**Comment by wythe** [comment]
Just a few more to go: #1360.

**Comment by wintercooled** [comment]
Ah sorry, wasn't aware this was ongoing! :-)
