### ISSUE TITLE
Channel stuck in status "Loaded from database"

### ISSUE THREAD

**Issue by iemwill** [ElementsProject/lightning#1728]
For testing mainnet i opened a few channels to different nodes with different total SAT. Except of two channels, everything worked fine.

After opening the channels i did nothing (no tx) and once or twice my wifi broke and the node was offline. With the two following channels i have no the Problem since more than 2-3 weeks that they are stucked in the CHANNELD_SHUTTING_DOWN state and with the status "Loaded from database" . I dont know what to do, and dont see the funds in listfunds...

It happened with the version before 0.6 and in between i updated to 0.6...

### listchannels:
....
    {
      "id": "03ce15213fc42f04132edc0acb73d5830371970bebd7e25ba4a3ca2552d1ae6fdf",
      "connected": false,
      "channels": [
        {
          "state": "CHANNELD_SHUTTING_DOWN",
          "short_channel_id": "521573:871:0",
          "channel_id": "7697d4ea7d4779c33f0b45b7b5224a0d09a25f1026995864bd958ebfbedbe5da",
          "funding_txid": "dae5dbbebf8e95bd64589926105fa2090d4a22b5b7450b3fc379477dead49776",
          "msatoshi_to_us": 5000000,
          "msatoshi_to_us_min": 5000000,
          "msatoshi_to_us_max": 5000000,
          "msatoshi_total": 5000000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709551615,
          "their_channel_reserve_satoshis": 0,
          "our_channel_reserve_satoshis": 546,
          "channel_reserve_satoshis": 0,
          "spendable_msatoshi": 4454000,
          "htlc_minimum_msat": 0,
          "their_to_self_delay": 144,
          "our_to_self_delay": 144,
          "to_self_delay": 144,
          "max_accepted_htlcs": 483,
          "status": [
            "Loaded from database"
          ],
          "in_payments_offered": 0,
          "in_msatoshi_offered": 0,
          "in_payments_fulfilled": 0,
          "in_msatoshi_fulfilled": 0,
          "out_payments_offered": 0,
          "out_msatoshi_offered": 0,
          "out_payments_fulfilled": 0,
          "out_msatoshi_fulfilled": 0
        }
      ]
    },
    {
      "id": "036487e0bd981617c674c2856fc0050472a0182838e0a4a1a67545c6cdee9f49a0",
      "connected": false,
      "channels": [
        {
          "state": "CHANNELD_SHUTTING_DOWN",
          "short_channel_id": "521573:872:0",
          "channel_id": "c63549359f2ee91f843586678f96ac824238635b301b0c56d630f03818514505",
          "funding_txid": "0545511838f030d6560c1b305b63384282ac968f678635841fe92e9f354935c6",
          "msatoshi_to_us": 5000000,
          "msatoshi_to_us_min": 5000000,
          "msatoshi_to_us_max": 5000000,
          "msatoshi_total": 5000000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709551615,
          "their_channel_reserve_satoshis": 0,
          "our_channel_reserve_satoshis": 546,
          "channel_reserve_satoshis": 0,
          "spendable_msatoshi": 4454000,
          "htlc_minimum_msat": 0,
          "their_to_self_delay": 144,
          "our_to_self_delay": 144,
          "to_self_delay": 144,
          "max_accepted_htlcs": 483,
          "status": [
            "Loaded from database"
          ],
          "in_payments_offered": 0,
          "in_msatoshi_offered": 0,
          "in_payments_fulfilled": 0,
          "in_msatoshi_fulfilled": 0,
          "out_payments_offered": 0,
          "out_msatoshi_offered": 0,
          "out_payments_fulfilled": 0,
          "out_msatoshi_fulfilled": 0
        }
      ]
    }, 
....
### listfunds
...
  "channels": [
    {
      "peer_id": "03ce15213fc42f04132edc0acb73d5830371970bebd7e25ba4a3ca2552d1ae6fdf",
      "short_channel_id": "521573:871:0",
      "channel_sat": 5000,
      "channel_total_sat": 5000,
      "funding_txid": "dae5dbbebf8e95bd64589926105fa2090d4a22b5b7450b3fc379477dead49776"
    },
    {
      "peer_id": "036487e0bd981617c674c2856fc0050472a0182838e0a4a1a67545c6cdee9f49a0",
      "short_channel_id": "521573:872:0",
      "channel_sat": 5000,
      "channel_total_sat": 5000,
      "funding_txid": "0545511838f030d6560c1b305b63384282ac968f678635841fe92e9f354935c6"
    }
  ]

### getinfo
{
  "id": "03573d821ac340980ea15ae2e84bfd0365690b459f0192c946fe49fb5bdda8736a",
  "port": 9735,
  "address": [
    {
      "type": "ipv6",
      "address": "2003:ce:7f01:4400:f627:fd78:7947:909b",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv6",
      "address": "::",
      "port": 9735
    }
  ],
  "version": "v0.6",
  "blockheight": 532929,
  "network": "bitcoin"
}

**Comment by cdecker** [comment]
That's quite ok, the peer is disconnected, waiting for an incoming connection, or us to connect. The peer is not reachable, but as soon as it comes back it will proceed normally.

**Comment by iemwill** [comment]
OK, thx for the answer. So if i fund with someone a channel and he takes his node offline i have no chance to get the funds back, except he takes his node online again?

**Comment by cdecker** [comment]
You can always close the channel, it should do a unilateral close after a while. It seems that the channel was closed successfully by tx `de3152429d0b01dcc4a515af5564330d06146b2d1bcba57275424ad21114c0ec` which was a unilateral close, causing a 144 block delay, and indeed tx `878f610549eced1918881bad231d077785fe1fde8aa710727137937c234b4c9a` swept the funds back into the internal wallet. The channel should eventually disappear (it'll stick around for a number of blocks to make sure closure was ok) and you should have an entry in `listfunds` with the latter transaction ID.

**Comment by iemwill** [comment]
Perfect, i see the funds and the status changed. Seems like i had to set the force flag for the close command.
