### ISSUE TITLE
Is it correct to default to bech32 addresses?

### ISSUE THREAD

**Issue by wythe** [ElementsProject/lightning#1729]
### Issue and Steps to Reproduce
`cli/lightning-cli newaddr `

Result is bech32.

We used to default to `p2sh-segwit` and our manpage and variable names still reflect that.  But the code is different. I started to update the code and manpage to reflect bech32 as a the default, but wanted to check here first. Is bech32 correct?

The var I'm talking about is `is_p2wpkh` in `json_newaddr`.

**Comment by cdecker** [comment]
The following seems to suggest that p2wpkh is still the default:

https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/wallet/walletrpc.c#L228-L231

**Comment by jb55** [comment]
not sure if the switch to bech32 was intentional but I'm ok with a bech32 default.
