### ISSUE TITLE
Can you connect to a remote bitcoin node instead of a local one

### ISSUE THREAD

**Issue by JBaczuk** [ElementsProject/lightning#1741]
### Issue and Steps to Reproduce
I tried connecting to a bitcoin node on my local network using:

`./lightningd/lightningd --bitcoin-rpcconnect 192.168.1.25`

### output
```
bitcoin-cli not found. Is bitcoin-cli (part of Bitcoin Core) available in your PATH?

Make sure you have bitcoind running and that bitcoin-cli is able to connect to bitcoind.

You can verify that your Bitcoin Core installation is ready for use by running:

    $ bitcoin-cli -testnet -rpcconnect=192.168.1.25 echo 'hello world'
```

I see this feature was added in [#849](https://github.com/ElementsProject/lightning/pull/849), but this appears to still be looking for the `cli` locally.

**Comment by rustyrussell** [comment]
You need the `bitcoin-cli` binary locally, but you can make it connect to a remote node.

**Comment by JBaczuk** [comment]
That worked for me, thank you. I installed `bitcoin-cli` by building from source, and then started lightning like this: `lightning/lightningd/./lightningd --daemon`. The configuration was stored in `~/.lightning/config` with the following contents:

```
bitcoin-rpcconnect=192.168.1.25
bitcoin-rpcport=8332
bitcoin-rpcuser=<username>
bitcoin-rpcpassword=<password>
alias=<alias>
network=testnet
```
