### ISSUE TITLE
Peer not connected

### ISSUE THREAD

**Issue by valuead** [ElementsProject/lightning#1749]
![screen shot 2018-07-25 at 9 23 03 am](https://user-images.githubusercontent.com/9205462/43183088-76f2f724-8fec-11e8-9f2e-08613f269fc4.png)

{ "code" : -1, "message" : "Peer not connected" }

**Comment by cdecker** [comment]
I'm guessing the remote peer is an old `lnd` node that didn't update to include the `gzip` compressed gossip. See https://github.com/lightningnetwork/lnd/pull/1399 for details.
