### ISSUE TITLE
Received error from peer: Internal Error

### ISSUE THREAD

**Issue by valuead** [ElementsProject/lightning#1753]
![screen shot 2018-07-25 at 7 10 11 pm](https://user-images.githubusercontent.com/9205462/43213105-66e69636-903e-11e8-8745-de79bce3b42e.png)

**Comment by cdecker** [comment]
Not much we can do here, the remote peer didn't specify what the error is.

btw: screenshots are really bad for debugging and searchability, please don't do that

btw2: These issues you are filing are incredibly not useful, please provide more context and what you think is wrong here...

**Comment by valuead** [comment]
thanks, I agree with you on screenshots. When I see errors in logs or interfaces or when things not connected or funds missing I do report them. Going forward I'll be more vocal on my bug reports.
