### ISSUE TITLE
fixing '/* FIXME: Crazy Slow! */' for struct htlc_out *find_htlc_out_by_ripemd(const struct channel *channel,

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#1757]
Studying the code in lightningd I stumbled upon this line (according to git blame created by @rustyrussell ) : 

https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/lightningd/peer_htlcs.c#L790

This looks for me like a good issue to get my hands dirty. I don't think it is utterly important to fix, but I have the feeling I would get a better understanding of the data structures used and how data flow in lightningd occurs. In the following there are a couple of observations and questions. Would be great if someone with more experience could elaborate in order to give me better on boarding opportunities (: 

## What I understand so far:

* A little bit counterintuitively (at least for me) HTLCs are not stored per channel but as a hash_map in struct lightning d c.f.:  https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/lightningd/lightningd.h#L148
* The `htlc_out` struct has a field `htlc_key` which has two fields (a `struct channel *channel;` and `u64 id;` (which I guess should be the same as `dbid` within `struct channel`?)) 
* throwing away all htlcs which do not belong to the channel seems to become slow once a node is very well connected c.f.: https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/lightningd/peer_htlcs.c#L803 I am not sure however if that is really the bottleneck or was meant by the FIXME statement
* calculating the ripemd160 hash for (statistically seen) half the htlcs in the channel seems to be inefficient since the calculation of the hash also seems to be rather slow c.f.: https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/lightningd/peer_htlcs.c#L806

## So here are the potential solutions 
Each of which yields quite some code refectoring therefor I would love to get your feedback which one should be pursued and why:

1. the function `find_htlc_out_by_ripemd` is only called twice. e.g. here: https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/lightningd/peer_htlcs.c#L819  One could try to change the argument to pass an htlc instead of the ripemd160 hash. However this seems cumbersome since the variable htlc is just an `htlc_stub` so comparing pointers for htlcs within `find_htlc_out_by_ripemd` would not work out of the box. Of course once could refactor all those `htlc_stub`s but I guess that is missleading
2. Organize the code in the way that htlcs are not stored in the lightningd but rather in the channeld. I guess there will be some good reasons - which I am not aware of yet - to not store the htlc in channeld. However it could be possible to change the `htlc_out` and `htlc_in` maps in `lightningd` to be organized by channels.
3. instead of calculating the ripemd160 hash of `hout->paymenthash` one could also include a `ripemd160` field to `struct htlc_out` at https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/lightningd/htlc_end.h#L51 In that way the Hash only has to by calculated once the htlc_out struct is being initialized. This might however be bad since it is often used temporarily and makes the code even more inefficient (idk)
4. Use a different key for the `htlc_out` map currently it is: https://github.com/ElementsProject/lightning/blob/f85084948678177199cf44bdb9f991cfba3edf2a/lightningd/htlc_end.h#L10 which actually makes sense to me, so refactoring this doesn't look as too good of an idea. 

## Question: 
Do I understand that the solutions are preferable in the following order `3 > 2 > 1 > 4` or did I not even understand the problem correctly and there is need for another solution?

**Comment by ZmnSCPxj** [comment]
Code in question no longer exists in master HEAD, presumably it has been mooted.
