### ISSUE TITLE
non-descriptive error message: Cryptographic handshake: Operation now in progress

### ISSUE THREAD

**Issue by jarret** [ElementsProject/lightning#1760]
I accidentally copy-pasted in the wrong node ID for what I was trying to `connect` to and this is what it was giving me:
```
$./lightning-cli --lightning-dir=lightning-dir connect <WRONG-NODE-ID> <correct-IP-address>
{ "code" : -1, "message" : "Cryptographic handshake: Operation now in progress" }
```

It was a user error, but the error message reads strangely and there aren't helpful search engine results for this error message. (was from running `v0.6` on both ends of this connection attempt)

**Comment by bteitelb** [comment]
I ran into this today as well. The message text makes it sound like progress is being made, when in fact, the requested connection has failed.

**Comment by darosior** [comment]
Hello @jarret, have you encountered this lately ? If not I think it can be closed

**Comment by jarret** [comment]
The 'thing' encountered was user error. Filing this issue was to highlighting that the error message wasn't very good for something that  I suspect is easy to provide a better error for to help usability.

If a node connects to an IP and finds a node with a different node id, it would be helpful to say something more direct. It would also be good to not say something like "....now in progress" which sounds like something else is happening, when it is not.

**Comment by darosior** [comment]
I can't reproduce :
```
$ lc connect 024eb5049c4776de53d390ec8c4d415dfc2bf476c672eeeecf76b4ce00dea63592@35.193.213.82
{
   "code": -1,
   "message": "35.193.213.82:9735: Connection establishment: Connection timed out. "
}
```
@jarret could you give repro instructions ?

**Comment by jarret** [comment]
The node at a given IP must answer the connection but it not match the provided node id on the `connect` command:

I gave it a try on `v0.7.2.1` and this happened:

```
$ ./lightning//cli/lightning-cli --lightning-dir=./lightning-dir connect 0235d84a787db3f58b30696a9ae3dfcd97a58b6ed0600177eb0fa2c2375f119ce2 88.130.222.19
{
   "code": -1,
   "message": "88.130.222.19:9735: Cryptographic handshake: peer closed connection (wrong key?). nu4wh7syzwzse4cc.onion:9735: opening -1 socket gave Protocol not supported. "
}
```

This is a different result than I originally filed with `v0.6`

Did a quick dig into the history and commit 09b33015c46f5eff32b610c202c8967d23e35509 added the error message a few months after this issue was filed. This appears to be done to address this same concern and the error message is better for hinting what went wrong.
Closing.
