### ISSUE TITLE
Channels stuck in CHANNELD_AWAITING_LOCKIN and CHANNELD_SHUTTING_DOWN

### ISSUE THREAD

**Issue by ronaldmannak** [ElementsProject/lightning#1776]
### Issue and Steps to Reproduce
I noticed that some channels I opened two weeks ago never reached state `CHANNELD_NORMAL` and instead got stuck in either `CHANNELD_AWAITING_LOCKIN` or `CHANNELD_SHUTTING_DOWN`. My node has 95 working channels, and about 20 channels are still in one of the two stuck states.

Trying to close a channel stuck in either state using `lightning-cli close 468d...` results in error `{ "code" : -1, "message" : "Channel close negotiation not finished before timeout" }`. I am unable to force close the channel, I might misunderstand the syntax of that command.

The channels haven't closed or opened by itself after two weeks, and I'm unable to close the channels manually.

```json
{
  "state": "CHANNELD_AWAITING_LOCKIN",
  "channel_id": "468d0fd8d3f5a769f85fd90c188db9620374cf99a387c9d277a2f8a94f9ee5b2",
  "funding_txid": "b2e59e4fa9f8a277d2c987a399cf740362b98d180cd95ff869a7f5d3d80f8d46",
  "msatoshi_to_us": 318000000,
  "msatoshi_to_us_min": 318000000,
  "msatoshi_to_us_max": 318000000,
  "msatoshi_total": 318000000,
  "dust_limit_satoshis": 546,
  "max_htlc_value_in_flight_msat": 18446744073709552000,
  "their_channel_reserve_satoshis": 0,
  "our_channel_reserve_satoshis": 3180,
  "channel_reserve_satoshis": 0,
  "spendable_msatoshi": 314820000,
  "htlc_minimum_msat": 0,
  "their_to_self_delay": 144,
  "our_to_self_delay": 144,
  "to_self_delay": 144,
  "max_accepted_htlcs": 483,
  "status": [],
  "in_payments_offered": 0,
  "in_msatoshi_offered": 0,
  "in_payments_fulfilled": 0,
  "in_msatoshi_fulfilled": 0,
  "out_payments_offered": 0,
  "out_msatoshi_offered": 0,
  "out_payments_fulfilled": 0,
  "out_msatoshi_fulfilled": 0
}
{
  "state": "CHANNELD_SHUTTING_DOWN",
  "channel_id": "94f92739ae0a514522bbb5aae11b460a03fca2b5d79a29e2997e240303920fbc",
  "funding_txid": "bd0f920303247e99e2299ad7b5a2fc030a461be1aab5bb2245510aae3927f994",
  "msatoshi_to_us": 318000000,
  "msatoshi_to_us_min": 318000000,
  "msatoshi_to_us_max": 318000000,
  "msatoshi_total": 318000000,
  "dust_limit_satoshis": 546,
  "max_htlc_value_in_flight_msat": 18446744073709552000,
  "their_channel_reserve_satoshis": 0,
  "our_channel_reserve_satoshis": 3180,
  "channel_reserve_satoshis": 0,
  "spendable_msatoshi": 314820000,
  "htlc_minimum_msat": 0,
  "their_to_self_delay": 144,
  "our_to_self_delay": 144,
  "to_self_delay": 144,
  "max_accepted_htlcs": 483,
  "status": [],
  "in_payments_offered": 0,
  "in_msatoshi_offered": 0,
  "in_payments_fulfilled": 0,
  "in_msatoshi_fulfilled": 0,
  "out_payments_offered": 0,
  "out_msatoshi_offered": 0,
  "out_payments_fulfilled": 0,
  "out_msatoshi_fulfilled": 0
}
```

### `getinfo` output
```json
{
  "id": "02060d0c8577cfc2a1962220a1cde4f623ca55ef80bd25e4be5a8b15fed78b11a3",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "178.62.237.239",
      "port": 9735
    }
  ],
  "binding": [
  ],
  "version": "",
  "blockheight": 534430,
  "network": "bitcoin"
}
```

**Comment by ZmnSCPxj** [comment]
The first thing I notice, is, neither `funding_txid` appears to exist on the blockchain.  Thus the reason why c-lightning is finding it difficult to close -- it seems not to have gotten opened in the first place.  Unfortunately we probably need to get the logs at the time it was opened, as well as the version at the time it was opened (if you updated at all since you opened, then it might be an issue of the version at the time you opened, not an issue of the latest version; I remember we had many problems with opening channels and then failing to actually successfully broadcast the transaction).

Can you give the result of `lightning-cli close 468d0fd8d3f5a769f85fd90c188db9620374cf99a387c9d277a2f8a94f9ee5b2 true`?

**Comment by martijnbolt** [comment]
I have exact the same problem. When I add true to my command i get this:

    {
          "tx": 
  
  
  
  
  
  "0200000001be20c8647f30a77d60c1acf41d674dbf51ff0e69be9a7781536e15cc7857812c0000000000eb9ec380012909040000000000220020288b7a6bc508cc185252f56296d4342c3a39d8de72558275aa841440db6647c3fadfb920",
              "txid": "c305cfc0681c5ba39c01e8305d0eaf7146eec77c7665d9c782d2355a6842eb91",
              "type": "unilateral"
    }

**Comment by darosior** [comment]
@ronaldmannak have you experienced that lately ? Otherwise I think this can be closed

**Comment by martijnbolt** [comment]
no. not anymore.
