### ISSUE TITLE
Public IP address change complications: Differences between listnodes and listpeers - Might potentially cause routing issues.

### ISSUE THREAD

**Issue by georgevaccaro** [ElementsProject/lightning#1781]
### Issue
My node's public IP address changed but apparently the addresses section of listnodes function insists on retaining the old (a few months old) IP address.  listpeers is correctly reflecting the new IP address.

On my lightningd launch script I'm using:

--bind-addr 0.0.0.0:9735 
--announce-addr NEWPUBLICIP:9735

(of course the node's actual public IP)

Daniel Williams helped me debug the situation and provided the following output excerpts (identifying information removed) via the LN Node "Adam Back's Vision :tophat:" after first connecting to my node:

listpeers:

    {
      "state": "GOSSIPING", 
      "id": "---------------------------------------------------------------------------------------------", 
      "alias": "-------------------------", 
      "color": "000000", 
      "netaddr": [
        "NEWIPADDRESS:9735"
      ], 
      "connected": true, 
      "owner": "lightning_gossipd"
    }

listnodes:

    {
      "nodeid": "---------------------------------------------------------------------------------------------", 
      "alias": "-------------------------", 
      "color": "000000", 
      "last_timestamp": ----------------, 
      "addresses": [
        {
          "type": "ipv4", 
          "address": "OLDIPADDRESS", 
          "port": 9735
        }
      ]
    }

### Steps to reproduce
To reproduce this, one should:
1. launch a hosted instance on some hosting provide that allows provisioning different IPs (amazon for example)
2. ensure TCP path for traffic on port 9735 will reach the node at it's public IP
3. install c-lightning v0.6 
4. launch the lightningd with current IP with --bind-addr 0.0.0.0 --announce-addr CURRENTIP:9735
5. connect to some other nodes
6. open some channels (likely optional)
7. stop lightningd
8. provision a different IP to the instance
9. launch lightningd with the new different IP with --bind-addr 0.0.0.0 --announce-addr NEWIP:9735
10. connect to the node from another node via the new IP address
11. On the connecting node (origin node, not the destination) issue the following command and capture the output pertaining to the newly launched node: 

    lightning-cli listpeers

12. On the connecting node (not the destination) issue the following command and capture the output pertaining to the newly launched node: 

    lightning-cli listnodes

What you should observe is that the listpeers output contains the new IP address - this is the desired behavior, while the listnodes output contains the old IP address - which is the incorrect behavior since the node is no longer reachable at that IP address.

### Known and potential impact

The known impact of this bug is that LN explorers, for example lnmainnet.gaben.win use the listnodes command (https://github.com/chemicstry/recksplorer/blob/master/server/lightning/clightning.js#L77) to put together their LN network map and will therefore have outdated information. I've observed this issue there which is what prompted my research.  1ML.com is exhibiting the same behavior but I've not dug into their code to see if it's also using listnodes.  My guess is yes.

The potential impact of this bug is that it could affect routing IF routing relies on the listnodes output or the same underlying data source, which I think would be a strong possibility.

I would be more than happy (enthusiastic even) to help in any way I can to clarify this issue, retest it or even contribute to finding a fix (though my C coding skills are a bit rusty).

### `getinfo` output

	{
	  "id": "---------------------------------------------------------------------------------------------", 
	  "port": 9735, 
	  "address": [
	    {
	      "type": "ipv4", 
	      "address": "NEWIPADDRESS", 
	      "port": 9735
	    }
	  ], 
	  "binding": [
	    {
	      "type": "ipv4", 
	      "address": "0.0.0.0", 
	      "port": 9735
	    }
	  ], 
	  "version": "v0.6", 
	  "blockheight": 534487, 
	  "network": "bitcoin"
	}

**Comment by cdecker** [comment]
No worries, while annoying, this isn't a real issue besides the ability of nodes to connect to peers without contacting a seed. If this information is outdated, they won't be able to connect, and even if a new node took over that IP address, they won't pass the authenticated handshake of the transport layer. The only real impact here is that users can't look up a peer they'd like to connect to on explorers, which we'd like to discourage anyway, since that leads to a few prominent nodes becoming single points of failure.

The fix in this case is to trawl through your own view of the network and check whether the `--announce-addr` matches any of the addresses in the `node_announcement`.

**Comment by cdecker** [comment]
Forgot to mention: excellent job on the extensive documentation in this issue :+1:

**Comment by dan-da** [comment]
@cdecker hmm, are you implying that it is correct behavior for the address reported by listnodes to differ from that of listpeers and/or getinfo?    If so, I'd like to understand the rationale for that.

**Comment by cdecker** [comment]
Yes, they have significantly different sources of information: `listpeers` and `getinfo` show the address we are actually connected to, respectively the IP address we ourselves detected, or are announcing.

In `listnodes` we are sourcing the information from `gossipd` and represents what nodes that aren't connected to us will see, and what we believe the other node's state is.

But it is also no, the state of the different methods should converge over time, problem is we don't currently notice the divergence automatically and will not re-issue an update to fix that. That's the open issue here :wink:
