### ISSUE TITLE
Small typo in Makefile

### ISSUE THREAD

**Issue by sstone** [ElementsProject/lightning#18]
There's a small typo in the main Makefile: -DHAS_CLTV=1 is now mispelled -DHAS_CTLV=1

**Comment by rustyrussell** [comment]
Fabrice <notifications@github.com> writes:
> There's a small typo in the main Makefile: -DHAS_CLTV=1 is now mispelled -DHAS_CTLV=1

Um, how embarrassing!

Nice catch!
Rusty.
