### ISSUE TITLE
Request: don't log fee-related messages in regtest mode

### ISSUE THREAD

**Issue by shesek** [ElementsProject/lightning#1806]
They fill up the logs and make it hard to find anything else, and regtest doesn't have fee estimation anyway.

**Comment by SimonVrouwe** [comment]
How about only logging fee-rates when they change?

**Comment by SimonVrouwe** [comment]
@shesek #1825 disables fee estimation and corresponding log messages, when you use the option (for example) `--dev-override-fee-rates 40000/20000/10000`

**Comment by NicolasDorier** [comment]
Should be reopened. `--dev-override-fee-rates` has been removed, reopening this issue.

**Comment by ZmnSCPxj** [comment]
Reopening as per @NicolasDorier
