### ISSUE TITLE
fee-base and fee-pers-satoshi - change during runtime

### ISSUE THREAD

**Issue by asocjal** [ElementsProject/lightning#1808]
------- get info outut -------
`{
  "id": "035a71a8d2e36f5ff894fd6f97225a493e0cdf013c60c3b1c6992be19bd901a9ca", 
  "port": 9735, 
  "address": [
    {
      "type": "ipv4", 
      "address": "176.107.130.62", 
      "port": 9735
    }
  ], 
  "version": "v0.5.2-2016-11-21-2610-g91d149b", 
  "blockheight": 535503, 
  "network": "bitcoin"
}`

Why can't I set up fee-base and fee-pers-satoshi values during channel creation?
Am I right, that according to BOLT every channel could have different values? Why can't they be assigned during runtime?

**Comment by freerko** [comment]
stumbled upon this issue and noticed that this feature got merged a few days ago in https://github.com/ElementsProject/lightning/pull/2342 (for milestone 0.7.1) so I guess this can be closed.
