### ISSUE TITLE
All amounts should be in msatoshi

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#1818]
For example, reserve is in satoshi, leading to confusion about whether we're over it or not.  Easier to be msatoshi everywhere....

**Comment by jwaugh** [comment]
Thank you, @rustyrussell for posting this issue for me. Glad we were able to get my issue sorted out. Wouldn't have done that if it had all been mSats instead. 👍

**Comment by jb55** [comment]
Even fundchannel?

**Comment by cdecker** [comment]
My logic so far was that everything on-chain should be satoshis, while off-chain is all msatoshi. There is one exception to this, which is `listfunds` where I thought it might be very weird showing msatoshi and satoshi amounts next to each other (`outputs` vs. `channels`). Where specifically was this mixed?

**Comment by cdecker** [comment]
Would it make sense to have amounts allow an optional unit suffix? So instead of saying `fundchannel [peer-id] 1000` you'd say `fundchannel [peer-id] 1000sat` or `fundchannel [peer-id] 10000000msat`, or is that even worse?

**Comment by jb55** [comment]
@cdecker I thought the same. Right now I do fundchannel nodeid $(bcalc -n 1000 bits to sats). It would be neat if units could be explicit...

**Comment by ZmnSCPxj** [comment]
The `struct amount_msat` and `parse_amount_msat` wraps this for us now, and also provides `msat`/`sat`/`btc` units.
