### ISSUE TITLE
empty address entries in listnodes json output.

### ISSUE THREAD

**Issue by dan-da** [ElementsProject/lightning#1835]
Here is an example:

```
    { 
      "nodeid": "02e6b17c5a7a2461df38d0a571d92660f38ed5bbc847166ee655a1d0f83c1aa5ac",
      "alias": "It's showtime, Synergy!",
      "color": "4b0082",
      "last_timestamp": 1533894254,
      "addresses": [
        { 
          "type": "torv3",
          "address": "ueo7nndq5jnsc3gg3fpnrj3v6ceedvrej5qr5lt6ppvrtd7xxk64qiid.onion", 
          "port": 9735
        },
        {
        },
        {
        }
      ]
    },
```

Notice there are 3 items in the addresses array, but the latter two are empty.

possibly related: I discovered that if I do `lightning-cli connect <id>` to this node without giving an address, and then listpeers, the address listed is an ipv4 -- which is not present in listnodes output.  So I am guessing that the empty addresses in fact represent real addresses which for some reason are not being fully serialized in the output json.

**Comment by dan-da** [comment]
Ok, I did a little sleuthing.  I made a debug patch to serialize the value of addr->type in json_add_address() if the type isn't recognized.

```
diff --git a/lightningd/json.c b/lightningd/json.c
index 45e180e..915c6d4 100644
--- a/lightningd/json.c
+++ b/lightningd/json.c
@@ -147,6 +147,8 @@ void json_add_address(struct json_result *response, const char *fieldname,
                json_add_string(response, "type", "torv3");
                json_add_string(response, "address", fmt_wireaddr_without_port(tmpctx, addr));
                json_add_num(response, "port", addr->port);
+       } else {
+               json_add_num(response, "addr_type_unknown", addr->type);
        }
        json_object_end(response);
 }
```

The output of listnodes for above example becomes:

```
    { 
      "nodeid": "02e6b17c5a7a2461df38d0a571d92660f38ed5bbc847166ee655a1d0f83c1aa5ac", 
      "alias": "It's showtime, Synergy!",
      "color": "4b0082", 
      "last_timestamp": 1533894254,
      "global_features": "",
      "addresses": [
        { 
          "type": "torv3", 
          "address": "ueo7nndq5jnsc3gg3fpnrj3v6ceedvrej5qr5lt6ppvrtd7xxk64qiid.onion", 
          "port": 9735
        },
        { 
          "addr_type_unknown": 463628295
        },
        { 
          "addr_type_unknown": 3132068558
        }
      ]
    },
```

There are additional occurrences, with various values for type.

```
$ grep unknown /tmp/out2 | sort -V
          "addr_type_unknown": 32650
          "addr_type_unknown": 332363118
          "addr_type_unknown": 428089352
          "addr_type_unknown": 463628295
          "addr_type_unknown": 908559772
          "addr_type_unknown": 1461097519
          "addr_type_unknown": 1487187946
          "addr_type_unknown": 1836906358
          "addr_type_unknown": 1876925628
          "addr_type_unknown": 1944284686
          "addr_type_unknown": 2062964306
          "addr_type_unknown": 2660969144
          "addr_type_unknown": 3120734693
          "addr_type_unknown": 3132068558
          "addr_type_unknown": 3332027673
          "addr_type_unknown": 3401866643
          "addr_type_unknown": 3643819815
          "addr_type_unknown": 3812938703
          "addr_type_unknown": 3934443499
          "addr_type_unknown": 4102107868
          "addr_type_unknown": 4234543599
```

In all cases, the first (and only) displayed address is either of type torv3 or ipv6.  dunno if this is relevant.

Valid values for type are:

```
$ grep _TYPE common/wireaddr.h
        ADDR_TYPE_PADDING = 0,
        ADDR_TYPE_IPV4 = 1,
        ADDR_TYPE_IPV6 = 2,
        ADDR_TYPE_TOR_V2 = 3,
        ADDR_TYPE_TOR_V3 = 4
```

Thoughts:
* json_add_address() should not be printing {} for unknown addr types.  easy "fix"
* json_add_address() should have an else case to handle unknown addr types.  Maybe just log a warning.
* I'm not 100% sure where addr->type value is originating from.  If from the network, then perhaps unknown addr types should be filtered out immediately when the information is received, or possibly use a heuristic to identify the address type for ourselves rather than blindly trusting info from peers.

**Comment by rustyrussell** [comment]
What version?  I recently fixed a parsing bug in addresses which could well look like this... c5b5f7496552bcb36432519bb6af09b14e65ff0b

**Comment by dan-da** [comment]
sorry I was running a build from July 30 before your parsing fix.

I just re-built from latest master and restarted.  Now I do see node entries with multiple correct address entries.  So the fix is confirmed to that extent.

However, I also see some nodes with 0 address entries.    Is that correct behavior and if so how/why?    Could it be because I have old bogus addresses stored that persisted across restart?  ( I kinda doubt persistence is the issue since the example node from before has 3 correct addresses soon after restart. )

example:

```
    {
      "nodeid": "0364675470920ac58896e82186c7a9618f1731ea9aa4b0a96f8e1f7b7a6de2d596", 
      "alias": "zappening", 
      "color": "68f442", 
      "last_timestamp": 1534204465, 
      "global_features": "", 
      "addresses": [
      ]
    },
   ...
    {
      "nodeid": "031b778e75285f5a3c5f3cb2e8b5d35c968ed1b2260dc96d666c8b1173a8b447d9", 
      "alias": "HAPPYSOUFFLE-11-21-2545-gd6bf793", 
      "color": "031b77", 
      "last_timestamp": 1524734800, 
      "global_features": "", 
      "addresses": [
      ]
    },
```

Upon review, I see that both of these nodes also had 0 addresses in my older build as well.

**Comment by dan-da** [comment]
tangentially related, I also see some entry node entries, eg:

```
    {
      "nodeid": "02b22815ec7a6b0ce23d4911257d7b09e1617df4aba7821197c1e8688ba5
40e5ba"
    },
    {
      "nodeid": "026c7d28784791a4b31a64eb34d9ab01552055b795919165e6ae886de637
632efb"
    }, 
```

Should I open a seperate issue for that?

**Comment by rustyrussell** [comment]
It's because they didnt' advertise any addresses (happens if they're behind NAT).  The ones with no details *at all* we only know because they advertized a channel, but never announced their node.

**Comment by dan-da** [comment]
@rustyrussell thx for explanation.  Sounds like working as designed.

**Comment by andrewtoth** [comment]
@rustyrussell What is the intended purpose of `listnodes`? It seems that returning nodes without any addresses or any details at all except `nodeid` is not beneficial if we are looking for nodes to connect to. Would it be better to filter out nodes without addresses or any details?
