### ISSUE TITLE
Don't enforce fees on the peer if we're using default fees

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#1836]
molz on IRC reported:

          "status": [
            "CHANNELD_NORMAL:update_fee 829 outside range 5000-400000",
            "ONCHAIN:Tracking our own unilateral close",
            "ONCHAIN:All outputs resolved: waiting 48 more blocks before forgetting channel"
          ],

          "status": [
            "CHANNELD_NORMAL:update_fee 253 outside range 5000-400000",
            "ONCHAIN:Tracking our own unilateral close",
            "ONCHAIN:3 outputs unresolved: in 90 blocks will spend DELAYED_OUTPUT_TO_US (9fd822a85fbc64d916536c9178b837ef30b9ff9d6ac9b48183eeddc20dfb7e61:0) using IGNORING_TINY_PAYMENT"
          ],

          "status": [
            "CHANNELD_NORMAL:update_fee 501 outside range 5000-400000",
            "ONCHAIN:Tracking our own unilateral close",
            "ONCHAIN:All outputs resolved: waiting 46 more blocks before forgetting channel"
          ],

          "status": [
            "CHANNELD_NORMAL:update_fee 720 outside range 5000-400000",
            "ONCHAIN:Tracking their unilateral close",
            "ONCHAIN:All outputs resolved: waiting 45 more blocks before forgetting channel"
          ],

          "status": [
            "CHANNELD_NORMAL:Received error from peer: channel 993fea0d48375990bad016139ec72fbe3533ae83138b52a83f04d7a18c9f18f2: update_fee 22856 outside range 253-8290",
            "ONCHAIN:Tracking their unilateral close",
            "ONCHAIN:All outputs resolved: waiting 50 more blocks before forgetting channel"
          ],

**Comment by molxyz** [comment]
@rustyrussell 
[crash.log.tail.zip](https://github.com/ElementsProject/lightning/files/2285237/crash.log.tail.zip)
