### ISSUE TITLE
In-progress payments should list attempts, errors received...

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#1851]
I am having to read debug logs to get an insight into why the payment is still pending.  listpayments shows:

```
    {
      "id": 6, 
      "payment_hash": "eae46f078ddcc70965dadbe75bb4ba1131780bfa57f59844b8dd0a275cde2a61", 
      "destination": "03193d512b010997885b232ecd6b300917e5288de8785d6d9f619a8952728c78e8", 
      "msatoshi": 100000, 
      "msatoshi_sent": 101082, 
      "created_at": 1534393918, 
      "status": "pending", 
      "description": ""
    }
```

**Comment by ZmnSCPxj** [comment]
Do you refer to the `pay` command here which performs retries on failure and thus stores the failures, or the more basic `sendpay`? Currently, `listpayments` lists the basic `sendpay` data, not the `pay` command status.

The `pay` command status is also ephemeral (only in memory, not in database), although I suppose, that is another issue.

**Comment by ZmnSCPxj** [comment]
Play plugin already does this I believe.  Closing.
