### ISSUE TITLE
Could not find a route c lighting to bitcoin lightning wallet android

### ISSUE THREAD

**Issue by mmvphil** [ElementsProject/lightning#1872]
Can't pay this invoice but I can pay others..

```
decodepay lnbc15351070p1pdhlvt7rzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7zp0auqqd6qqqqqqqqlgqqqqqeqqjqfppqpljnd3ma9fznhqge78svej2q3ufuy08ddq8w3jhxaqxqy9gcqpp5f3an5euv5306fmmh7v6yez8melpw7hp643axyw94dtrr3dmezz5sc0husrugm60wqpla676tsjaeemrmgcvhf2l72tfv6l9paml6335r9gvlv7dw9tkngy4lgdgz8a633q5fef4ysa6eea70wsuhu0gdelcp5f73sx
Bot{
"currency": "bc", 
"created_at": 1535095166, 
"expiry": 172800, 
"payee": "02771b69178c05a48c3e96093df0e03bb922ca9444441586771263ea4fd9652ddd", 
"msatoshi": 1535107, 
"description": "test", 
"min_final_cltv_expiry": 9, 
"fallbacks": [
{
"type": "P2WPKH", 
"addr": "bc1qpljnd3ma9fznhqge78svej2q3ufuy08d78u77l", 
"hex": "00140fe536c77d2a453b8119f1e0ccc9408f13c23ced"
}
], 
"routes": [
[
{
"pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f", 
"short_channel_id": "536559:1768:0", 
"fee_base_msat": 1000, 
"fee_proportional_millionths": 100, 
"cltv_expiry_delta": 144
}
]
], 
"payment_hash": "4c7b3a678ca45fa4ef77f3344c88fbcfc2ef5c3aac7a6238b56ac638b77910a9", 
"signature": "3045022100c3efc80f88de9ee007fdd7b4b84bb9cec7b461974abfe52d2cd7ca1eeffa8c68022032a19f679ae2aed3412bf435023f75188289ca6a487759cf7cf74397e3d0dcff"
}
```

```
pay lnbc15351070p1pdhlvt7rzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7zp0auqqd6qqqqqqqqlgqqqqqeqqjqfppqpljnd3ma9fznhqge78svej2q3ufuy08ddq8w3jhxaqxqy9gcqpp5f3an5euv5306fmmh7v6yez8melpw7hp643axyw94dtrr3dmezz5sc0husrugm60wqpla676tsjaeemrmgcvhf2l72tfv6l9paml6335r9gvlv7dw9tkngy4lgdgz8a633q5fef4ysa6eea70wsuhu0gdelcp5f73sx
Bot{ "code" : 205, "message" : "Could not find a route", "data" : 
{
"getroute_tries": 1, 
"sendpay_tries": 0, 
"failures": [
]
} }
```

**Comment by cdecker** [comment]
That's because the node doesn't announce its channels, but does provide an `r` field to hint a point of contact. We currently don't support `r` fields, but #1330 would add support for them.

**Comment by mmvphil** [comment]
K thanks deck.. also could u pls see https://www.reddit.com/r/Bitcoin/comments/9a3uzn/basic_lightning_network_question/ 
seems everyone uses lnd on reddit

**Comment by mmvphil** [comment]
STILL CAN'T FIND ROUTE even if recipeient uses public node!

ln command : /ln/lightning/cli/lightning-cli pay lnbc306089240p1pdekanfrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7zzz8qqqzwcqqqqqqqryqqqqqqgqjqfppq99qa8hwuywmrynmqn2s8qlhur898g3tzdq9v9skzxqy9gcqpp56ptq7qcpfsw6uj7r9s2cdkptzxsvnmjr7uq0wstrekd9rpxxmkwqf56asm00c0ja7htp4503aamxvkkulyca459t6zsq26mr5k6avzrq53fs2v2at844m09eejsjjagdgg5rlz9lmxz6nxhsz7eeupgnc6cph2f2a8
{ "code" : 205, "message" : "Could not find a route", "data" : 
{
  "getroute_tries": 1, 
  "sendpay_tries": 0, 
  "failures": [
  ]
} }

**Comment by mmvphil** [comment]
Did the caps hurt your eyes?
android 'bitcoin lightning wallet' shows it as public.. I have tried now half dozen channels with bitcoin lightning wallet i can't even receive any payments from them.  just always failed.
to be honest I have made a huge app that will use LN and as of this point im TOTALLY frustrated.. sorry for caps but to be honest its needed.. Maybe issues will be ironed out but I'm to the point of abandoning this project all together and giving up promoting lightning.. 
People tell me they have less issues on LND implementation but at this point I'm ready to throw in the towel.

**Comment by dslingo** [comment]
in my case i have r field in the invoice and also getting "Could not fint a route" error if paying to nonannounced channels

**Comment by dslingo** [comment]
see in the code that r field is not supported yet: /* FIXME: use b11->routes */

**Comment by dslingo** [comment]
its funny than major feature like payment is not working

**Comment by mmvphil** [comment]
STILL CAN'T FIND ROUTES AND i've just about given up on LN 
really if after 6 months we still haven't sussed out a way to find a route? ITS NOT FINDABLE!

**Comment by dslingo** [comment]
give more details about the problem. But if this is related to nondvertized nodes this functionality is under developent and will be ready soon. check this out: https://github.com/ElementsProject/lightning/issues/2206

**Comment by ZmnSCPxj** [comment]
Is this still relevant? We already support `r` fields now.

**Comment by ZmnSCPxj** [comment]
If no objections, I will close soon.
