### ISSUE TITLE
enhancement: add listchannels option to show only my channels.

### ISSUE THREAD

**Issue by dan-da** [ElementsProject/lightning#1873]
Presently listchannels can either lookup a single channel by id or show all channels in network.  I would like an option/flag to list only channels where my node  is either source of dest.

Ideally, one could filter by:
* my node is source,  (outgoing)
* my node is dest (incoming)
* my node is either source or dest (in/out)

A related thought for consideration is that some APIs provide a node-centric view and others provide a network centric view.   eg listpeers, listpayments, listconfigs, listinvoices are node-centric while listnodes and listchannels are network centric.  In order to provide consistency, perhaps the default behavior of listnodes and listchannels should be made node-centric by default, with a flag to enable full network listings.

**Comment by cdecker** [comment]
That's the exact use-case that `listpeers` should cover, and it gives you more information.

**Comment by dan-da** [comment]
fair enough.  although listpeers and listnodes use different data sources, as you previously [explained](https://github.com/ElementsProject/lightning/issues/1781#issuecomment-415175953).

Its not a pressing feature/issue, just something I noticed.  feel free to close.

**Comment by cdecker** [comment]
Ideally we can merge the two datasources in `listpeers`, so that it provides a superset for local channels.

**Comment by jb55** [comment]
@dan-da you could use `jq`:

```
NODEID=$(lightning-cli getinfo | jq .id) \
lightning-cli listchannels | jq '.channels[] | select(.source == '$NODEID' or .destination == '$NODEID')'
```

**Comment by dan-da** [comment]
nice one liner!

**Comment by cdecker** [comment]
I can't remember how I did before knowing `jq, it's just the best tool ever :-)
