### ISSUE TITLE
listnodes reports many ipv6 addresses as "::"

### ISSUE THREAD

**Issue by dan-da** [ElementsProject/lightning#1885]
I don't understand what's going on here, but it doesn't seem right.

Example:
```
    {
      "nodeid": "026ac9fcd64fb1aa1c491fc490634dc33da41d4a17b554e0adf1b32fee88ee9f28", 
      "alias": "leadingzero", 
      "color": "68f442", 
      "last_timestamp": 1535304915, 
      "global_features": "", 
      "addresses": [
        {
          "type": "ipv6", 
          "address": "::", 
          "port": 9735
        }
      ]
    },
```

Found 24 addresses like this.
```
$ lightning-cli listnodes | grep '"::"' | wc -l
24
```

A different example, ::2
```
    {
      "nodeid": "02b7207ed5d65c89646ac64a39a183dc6fbe45f63be59ad7442ce894cee5aea8dc", 
      "alias": "tobglight", 
      "color": "3392ff", 
      "last_timestamp": 1528834462, 
      "global_features": "", 
      "addresses": [
        {
          "type": "ipv4", 
          "address": "89.22.110.170", 
          "port": 9735
        }, 
        {
          "type": "ipv6", 
          "address": "::2", 
          "port": 9735
        }
      ]
    },
```

All ipv6 listed [here](https://github.com/dan-da/lightning-nodes/blob/c7d5c923070f6117479b3483dd2c8a9c0163f026/README.md#ipv6).

**Comment by dan-da** [comment]
fwiw, 8 of the 24 addresses contain the string `[LND]` in the alias.

**Comment by cdecker** [comment]
It looks like those addresses are all zeros, and your hunch about it being `lnd` might be interesting to follow. The JSON-RPC just reports the addresses it gets from `node_announcement`s, and doesn't filter out invalid ones (not that `::` is particularly invalid, it's just probably not useful at all). Might be something with the operator of those nodes specifying the wildcard bind address.

**Comment by dan-da** [comment]
ok, I will make an issue with LND folks.   

Is there any way to identify the software of the other nodes?  I don't see any identifiers in listpeers or listnodes output.  Is an identifier sent over the wire we can display?

Also, what is the right behavior for us here?   If the address obviously cannot be connected to, perhaps it should be filtered out, with a log warning when first seen.

Or is it better just to display as received?  maybe with a warning.   reasoning?

**Comment by cdecker** [comment]
> Is there any way to identify the software of the other nodes? I don't see any identifiers in listpeers or listnodes output. Is an identifier sent over the wire we can display?

No, we opted out of having a user agent identify itself. c-lightning will send its version in the ping payload however if it is running in developer mode.

> Also, what is the right behavior for us here? If the address obviously cannot be connected to, perhaps it should be filtered out, with a log warning when first seen.

That's a possibility, but that's likely to be a game of whack-a-mole, and in absence of other IP addresses we can't contact the node anyway.

**Comment by rustyrussell** [comment]
Note that you *could* force c-lightning to do this, if you mess up the arguments to `--announce-addr`.  But some seem to be lnd, so start there?

**Comment by darosior** [comment]
@dan-da I think this can be closed ? :)

**Comment by dan-da** [comment]
ok, closing.

as of now, there has been a significant reduction in these occurrences, but I still see 3:

```
lightning-cli listnodes | jq  '.nodes[] | select(.addresses[]?.address == "::").alias'
"Opcode"
"harpydude"
"cpt"
```
