### ISSUE TITLE
Why I can't find the implementation of towire_opening_funder()?

### ISSUE THREAD

**Issue by WillPerfect** [ElementsProject/lightning#1911]
I find a function named towire_opening_funder() in opening_control.c，but I can't find it's code. Where is it?
Another question: If a node has more than one addressWould all the addresses been used to fund a channel or only one address?

**Comment by ZmnSCPxj** [comment]
These functions are generated automatically, from `.csv` files. Perform `configure` and `make` will create the files that contain the implementation.  As they are automatically generated, it is usually not useful to see the content of the implementation, as it is more interesting to see the `.csv` files.

The `.csv` file will contain the "base name" of the message, and two functions `fromwire_message_name` and `towire_message_name` will be created from the `.csv` file.

>Another question: If a node has more than one addressWould all the addresses been used to fund a channel or only one address?

If needed to fund the channel completely, yes.
