### ISSUE TITLE
Set maxfeepercent to an arbitrary value

### ISSUE THREAD

**Issue by fedsten** [ElementsProject/lightning#1914]
With the purpose of testing some extremely tiny payments, I tried to set the `maxfeepercent` value above 100%, and obtained the following output:
```
{ "code" : -32602, "message" : "'maxfeepercent' should be a double in range [0.0, 100.0], not '1000'", "data" : 
{
  "maxfeepercent": "1000"
} }
```
Is there a way with `lightning-cli` to avoid the 100% limit and set an arbitrary `maxfeepercent` value?

**Comment by ZmnSCPxj** [comment]
Currently no, this implies you are willing to pay a fee several times greater than the actual payment, which makes little sense.

I suppose for testing, it may be useful, but, I am uncertain if it is good to simply remove the restriction..

**Comment by fedsten** [comment]
I think it can be useful for assets on the blockchain protocols (e.g. RGB), or more in general for any protocol using lightning to transmit information and not just bitcoins. 

One could argue that this limit can be removed in implementations of such protocols, keeping it in c-lightning to provide extra protection to users interested only in the monetary application of LN. On the other hand, changing the `maxfeepercent` value above 0.5% already requires a manual action from the user, so anybody setting it to an higher value probably does it for a reason, not by mistake.

**Comment by ZmnSCPxj** [comment]
Okay, I concur, let me see if I have time to implement this at all, should just require removal of a check.
