### ISSUE TITLE
Restoring channel states/porting LN wallet

### ISSUE THREAD

**Issue by coinsmith** [ElementsProject/lightning#1918]
Is there a way to restore a previously deleted LN node (due to a mishap/disk failure) with a backup of the .lightning/ folder? So far, I've rescanned the wallet, dev-rescan-outputs looks good, however, I don't see any payments made from this node. Listfunds shows the on chain inputs, but no channels.

**Comment by cdecker** [comment]
Backup is not supported, and unlikely to be supported beyond the recovery of on-chain funds any time soon. Attempting to restore channels from a backup may indeed result in you unintentionally broadcasting an old state, which would be recognized as an attempt to cheat by the other endpoint, resulting in a penalty transaction that transfers all of your funds to the peer.

We are currently trying to figure out a good way to provide backup functionality on the protocol level, but there is no good solution yet, unless we migrate to an eltoo based system.

**Comment by coinsmith** [comment]
Is it possible to run multiple instances of the same wallet/channels on different machines?

**Comment by cdecker** [comment]
Absolutely not, that's a really great way to get all of your funds swiped by the counterparty. Notice that is not c-lightning specific, all Lightning implementations will have this issue.

**Comment by coinsmith** [comment]
Ok thanks, hopefully we'll see a solution to this soon. Closing this.

**Comment by cdecker** [comment]
Definitely :+1:

**Comment by GamerSg** [comment]
Can confirm that this issue still exists as of latest commit on Jan 5 2019

Seems to occur if bitcoind is not fully sync'ed
Shutting down lightningd, deleting the sql db and restarting it results in a instant sync.

**Comment by cdecker** [comment]
Do not delete the database if you ever had any channels open, or you will lose funds! Some of the on-chain addresses are not purely HD-derived. The LN protocol forces us to use addresses with a complex derivation path with non-local information in case of unilateral closes, and that non-local information is in the DB. If you delete the DB you won't be able to see those funds anymore.
