### ISSUE TITLE
Network connection gets stuck between of my own two nodes

### ISSUE THREAD

**Issue by laanwj** [ElementsProject/lightning#1919]
### Issue and Steps to Reproduce

I have this strange issue between two of my own nodes, running the `master` version of lightingd:

`connect` between them works, but quite frequently, the connection gets appears to get stuck. This can happen already during `fundrawtransaction`.

In that case the command either hangs, or it succeeds, gets to `Funding tx XXX depth 6 of 3` in both sides but they shyly don't progress to the next step.

It takes a restart of both daemons (note: haven't tried restarting only one, or `disconnect`, that would be the next when it happens again.) When in state of hang, nothing appears in the debug log indicating a special condition.

Right now I just re-spawned them and they detected the channel between them but I expect it to break down due to lack of response at some point.

running commit `634f19a7b230edc686be56ab950b80784e56252c` on:
- Debian GNU/Linux 9 (stretch)
- FreeBSD 11.1p4
Bitcoin core commit `0df9b0aed23127acd12d9ed6a008c12be47b1cd9` on master branch, non-pruned nodes)

I'd like to help debug this (it might even be a network-level issue, or FreeBSD specific), but I don't have an idea where to start.

Edit: definitely seems to be the FreeBSD node at fault here, even though the server is quite fast, routing other payments through it seems sluggish at best

**Comment by cdecker** [comment]
We can try to step through the various levels and see where it hangs. Does `listpeers` show the peers as `connected: true`? If no we might have lost/closed the connection at which point I'd try break in `channeld` on things like `peer_failed` and `peer_failed_connection_lost`. If they think they are connected we can instrument `sync_crypto_write` and similar and see if there is any activity.

**Comment by laanwj** [comment]
As expected, the channel is closing again:
```
        {
          "type": "UNUSUAL",
          "time": "32206.046346667",
          "source": "02398b614028892474fc95ed64c48791f994975042d0bd7e9592d0ec4128bbace4 chan #338:",
          "log": "Peer permanent failure in CHANNELD_NORMAL: lightning_channeld: received ERROR channel 1578d841c53aa83b215bfc1e71f42cdb9705313c603dfd030ea3fbf05c2109eb: Offered HTLC 0 SENT_ADD_COMMIT cltv 540670 hit deadline"
        },
```
Both nodes are in datacenters, so it's unlikely to be a NAT issue. It might be a different low-level network routing issue ofcourse!

> Does listpeers show the peers as connected: true? 

One side of the connection thinks the connection is still open, the other things it's closed?!

> listpeers [id] will be useful in this case. 

Here's `listpeers [id] debug` for both sides of the connection:

https://0bin.net/paste/9xcflHFXXddWtGzj#ij8FRkHxiCrgmlqN8MkTJoWMmJVDjhK-pa0GAn2UYVE

https://0bin.net/paste/XOU8BxKU3hkAx6cy#0k62G-eDXqgp+iRJWKrLFgQSEjuUhAC+oFgjeDitwqA

**Comment by laanwj** [comment]
The network connection to `92.110.144.x:37968` that lightningd still thinks is open, does not appear in netstat
```
% netstat -an | grep 37968
...
```

**Comment by laanwj** [comment]
so on node A I do, to connect to node B
```bash
A% lcli connect 0250373555232cec757ea141273e75381c84cc3ab22f1e3a3ca5a2dc55b1904c24@92.110.x.x:9735
```
this works, a connection is established (I can see the `connected:"true"` in listpeers), and a ping is sent over the line, trying to ping over it however, hangs:
```bash
lcli ping 0250373555232cec757ea141273e75381c84cc3ab22f1e3a3ca5a2dc55b1904c24
(hangs)
```
netstat on node A sees the connection as being open
```
A% netstat -an | grep 92.110.x.x
tcp4       0      0 163.172.x.x.10853    92.110.x.x.9735     ESTABLISHED
```
so does the one on node B
```
B$ netstat -anp|grep 163.172.61.48
tcp      916      0 192.168.x.x:9735      163.172.x.x:10853     ESTABLISHED 6635/lightning_conn
```
Interestingly, the pings end up in node B's recvq (I can see the number increase every time I send), but are not processed. Also, the connection does not show up in node B's listpeers:
```
B$ lcli listpeers 02398b614028892474fc95ed64c48791f994975042d0bd7e9592d0ec4128bbace4
{
  "peers": [
  ]
}
```

**Comment by laanwj** [comment]
I have the feeling that this had the same cause as #1920, as I'm not experiencing the above issue anymore, will re-open if it comes back.
