### ISSUE TITLE
"ping" command hangs

### ISSUE THREAD

**Issue by laanwj** [ElementsProject/lightning#1920]
### Issue and Steps to Reproduce

I'm trying to use it to diagnose connection issues (#1919), however, I cannot successfully manually ping any of my connected peers from any of my lightning nodes. It looks like `ping <id>` always hangs.

lightningd as of `634f19a7b230edc686be56ab950b80784e56252c`

### `getinfo` output

```
{
  "id": "...",
  "alias": "...",
  "color": "...",
  "address": [
    {
      "type": "ipv4",
      "address": "...",
      "port": 9736
    },
    {
      "type": "ipv6",
      "address": "...",
      "port": 9736
    },
    {
      "type": "torv3",
      "address": "...",
      "port": 9736
    }
  ],
  "binding": [
    {
      "type": "ipv4",
      "address": "0.0.0.0",
      "port": 9736
    },
    {
      "type": "ipv6",
      "address": "::",
      "port": 9736
    }
  ],
  "version": "v0.6.1rc2",
  "blockheight": 540616,
  "network": "bitcoin"
}
```

**Comment by SimonVrouwe** [comment]
I have the same issue, since 634f19a7b230edc686be56ab950b80784e56252c, but works fine as of b52fb14 (2 commits earlier)

**Comment by SimonVrouwe** [comment]
hmm ... no after a clean build (`make distclean`) b52fb14  also hangs on `ping`.

**Comment by laanwj** [comment]
right—I don't know if the ping is being sent, and not being replied to, or not sent at all

although you'd say, between two nodes that run c-lightning and that I control myself it should work

I probably should add some debug logging code, I'm don't know enough about the underlying network code to easily diagnose this, though, or is there already a way to trace all packets sent/received?

**Comment by rustyrussell** [comment]
log-level=io, and then SIGUSR1 the process you want to log IO.

However, ping works fine for me on my node running -rc2.

**Comment by laanwj** [comment]
> However, ping works fine for me on my node running -rc2.

The strange thing is that here it doesn't work, even between nodes that work great otherwise. I'd expect it to not work in the botched case of #1919, but I don't have any reference of seeing the command ever work.
(I've tried pinging all `"connected":true` peers on three different nodes, no dice)

**Comment by laanwj** [comment]
> log-level=io, and then SIGUSR1 the process you want to log IO (lightning_channeld in this case).

to be clear: do I have to enable --log-level=io for the entire process (at start-up), or can I somehow do this for only this specific peer?

**Comment by laanwj** [comment]
OK: verified that with two **local** lightningd nodes on regtest, `ping` works fine

So it must be a network issue, of some kind. I'm so confused !

**Comment by SimonVrouwe** [comment]
After a lot of trial and error with my node which appears to have the same issue (hanging `ping` command), the solution that worked for me was delete (or move) the `gossip_store` file.

**Comment by SimonVrouwe** [comment]
@cdecker Something bad got into this `gossip_store` causing `ping` to hang?
[gossip_store_EVIL.zip](https://github.com/ElementsProject/lightning/files/2366400/gossip_store_EVIL.zip)

I found this out because `ping` did not hang when restarting the troubling node and immediately calling `dev-suppress-gossip` on that node. In my case the above problem with `ping` seemed specific to nodes/peers within my LAN and pinging to a public peer worked fine.
