### ISSUE TITLE
Node sends a lot of stale routing info

### ISSUE THREAD

**Issue by sstone** [ElementsProject/lightning#1934]
### Issue and Steps to Reproduce

When connecting or reconnecting to Satoshi's place, which is running c-lightning, we receive a lot of channel ids for channels that are closed (so we query for them and check them)

### `getinfo` output
Satoshi's place is running commit 795e0e1b210ea76b4d4644510031cd9dac9568a8,

**Comment by rustyrussell** [comment]
Thanks!  I found it; we keep track of recently-spent utxos (in case of reorg), but when we check if a utxo is known, we didn't check if it's actually known and *spent*!

This generally means if a peer sent us a channel_announcement after we'd eliminated it as dead, we restored it.  Writing test now...

**Comment by cdecker** [comment]
This will be fixed by #1945
