### ISSUE TITLE
Tor port is shown as 0.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#1939]
```
$ lightning-cli getinfo
{
  "id": "024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605", 
  "alias": "BLUEIRON-v0.6.1rc2-8-g10167ee", 
  "color": "024b9a", 
  "address": [
    {
      "type": "ipv4", 
      "address": "128.199.202.168", 
      "port": 9735
    }, 
    {
      "type": "ipv6", 
      "address": "2400:6180:0:d0::5cd2:a001", 
      "port": 9735
    }, 
    {
      "type": "torv2", 
      "address": "z4juqu4gv525fquo.onion", 
      "port": 0
    }
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }, 
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "v0.6.1rc2-8-g10167ee", 
  "blockheight": 541408, 
  "network": "bitcoin"
}
```

**Comment by rustyrussell** [comment]
```
$ cat .lightning/config 
network=bitcoin
log-file=/home/rusty/logs/lightningd.log
log-level=debug
addr=
addr=autotor:127.0.0.1:9051
```

**Comment by Saibato** [comment]
@rustyrussell  when we/you  dig in to this, keep in mind that V3 autoservice can also be enabled now,
as the lastest versions support it. 
And we/you should enable it.  there is also an display issue when using other ports different from 9735   

i use highly modified versions of c-ln for tor so maybe i can do some backport and make a PR for doku and autoservice V3. 
cheers

**Comment by Saibato** [comment]
in  `tor/autoservice.c `port is set to 0 this fixes the 0 display
as we always use for tor for now DEFAULT_PORT
line 99 ff

		name = tal_fmt(tmpctx, "%s.onion", line);
		onion = tal(ctx, struct wireaddr);
		if (!parse_wireaddr(name, onion, DEFAULT_PORT, false, NULL))
			status_failed(STATUS_FAIL_INTERNAL_ERROR,

:-)
