### ISSUE TITLE
Two lightningds on the same bitcoind, remote lagging behind local on blockheight

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#1946]
### Issue and Steps to Reproduce
Machine A:
* running `bitcoind`
* running `lightningd`

Machine B:
* running `lightningd` with parameters set to connect to Machine A's bitcoind RPC server
* the RPC connection works well, I can run `bitcoin-cli` from here and get correct information from Machine A

### `getinfo` output
Machine A:
```json
{
  "id": "03f4154f423524e20d5a17ecd9193934dbc72a3120aeaf3e6e0df7741a9aa64f26", 
  "alias": "GaloDoido", 
  "color": "141519", 
  "address": [
    {
      "type": "torv2", 
      "address": "ddyflrwx7lh7p7lp.onion", 
      "port": 1234
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "v0.6.1rc2-2-g634f19a", 
  "blockheight": 541954, 
  "network": "bitcoin"
}
```

Machine B:
```json
{
  "id": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff", 
  "alias": "BananaMaluca", 
  "color": "84f746", 
  "address": [
    {
      "type": "ipv4", 
      "address": "162.243.220.95", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "162.243.220.95", 
      "port": 9735
    }
  ], 
  "version": "v0.6.1rc2-37-g36eab5d", 
  "blockheight": 541940, 
  "network": "bitcoin"
}
```

Apparently the remote node is making progress, but at very slow pace -- 30 minutes ago it was on blockheight `541939`, but it's been on `541940` for many many minutes now. Is it broken or just slow? If it is just slow, could that be an issue with the RPC connection somehow?

**Comment by Kexkey** [comment]
Sub-question: is it supported using the same bitcoind instance for several lightningd instances?  Just want to make sure because I'm testing with this kind of setup and I have a lot of problems with channels/payments -- I want to pinpoint the culprit.

**Comment by fiatjaf** [comment]
Advanced one more block!

I now think this is just my internet connection that is much worse than I thought on Machine A.
I'll try a different setup and reopen this later if the problem persists.

**Comment by fiatjaf** [comment]
My slow connection issues are being partly addressed at https://github.com/rustyrussell/lightning/commit/1525a7b07deaba1e03d2b61a23a65351037b2612
