### ISSUE TITLE
Mysterious node operations and dissapearing funds since update

### ISSUE THREAD

**Issue by d4amenace** [ElementsProject/lightning#1953]
Hello, I am experiencing problems with my install on Ubuntu 16.04.  I recently updated with some channels in "onchain" closing status.  I did the update due to the btcd update to 16.03 due to the vuln.  When I restarted my node my channels were gone so were my wallets and any funds. Everything vanished.

Later, I decided to do a test deposit to a generated address from another wallet.  The wallet sent the funds and has plenty of confirmations but no btc appears in the ln node when i do the list funds.

Nothing is listed not even a wallet.  I know the wallet address and can pull that up when I do a dev-listaddr but the wallet still shows no funds.

**Comment by rustyrussell** [comment]
Crap!! This clearly Shouldn't Happen!  What version of c-lightning is this?

Do you have any logs?  Is there a crash.log in your ~/.lightning directory?

We have #c-lightning on Freenode (IRC), too.  We're timezone-diverse, so you did the right thing posting an issue here FWIW.

**Comment by sumBTC** [comment]
This must be a rare bug. I did the same thing as OP and for the same reason, also on Ubuntu 16.04 and with a channel closing on-chain, and haven't experienced any problems with any of the latest versions of the c-lightning software (on mainnet). Funds are all there and my (self-created) status list hasn't changed before or after the update.

Connected channels: 9
Disconnected channels: 2
Channels awaiting lockin: 0
Channels closing on-chain: 1
  Forgetting: 41 (blocks left)
Clearing HTLC to shut down channel: 0
Closing channels negotiating fee: 0
Broadcasted close not yet in block: 0
Waiting for accept channel: 0
Awaiting unilateral: 0
Gossiping: 0

**Comment by d4amenace** [comment]
I only found a crash log in the folder specified. Cannot upload here.  Is there any other log file I should look for that could help me track down the 3 closed channels funds?  The funds from the test deposit in paragraph 2 of my opening post are showing and available. 

The last time I could see the status of the channels was in the onchain state and it said they had a 77 block delay to close.....(btc block or LN block delay??) Could this delay be the reason the funds are in limbo.  In that case, shouldn't I still be able to see the channels and their states if they were being actively updated?

**Comment by d4amenace** [comment]
Also,  what is "our_to_self_delay:144"?

**Comment by cdecker** [comment]
@d4amenace how are you running your node? Notice that if you run it in docker you might just have created a completely new node (if you didn't mount the lightning directory somewhere on the host). Can you check the file creation time of `hsm_secret` against the restart time?

**Comment by d4amenace** [comment]
I installed using this guide....https://www.youtube.com/watch?v=LHonpK80k94&list=PLhWIQKZKupCZtcEcRP6pTGtZe3Xe4o2sm

I can find hsm_secret but I do not know how to check file creation time against restart time

**Comment by d4amenace** [comment]
Issue is resolved. User error.
