### ISSUE TITLE
Channel stuck in "Loaded from database"

### ISSUE THREAD

**Issue by andrewtoth** [ElementsProject/lightning#1973]
Channel status is "Loaded from database" after a restart. It remained for several days. Calling `close` on the channel gave the following output:
```
{ "code" : -1, "message" : "Channel close negotiation not finished before timeout" }
```
However, it did change the `state` of the peer to `CHANNELD_SHUTTING_DOWN`. However, no closing transaction has appeared on the blockchain.

**Comment by andrewtoth** [comment]
`getinfo`:
```
{
  "id": "03ce17310d651018306782fbe78f061255effbcb1be4a4cb3dd7b66ff6a1ce7463", 
  "alias": "ODDPENGUIN-", 
  "color": "03ce17", 
  "address": [
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }, 
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "v0.6.1", 
  "blockheight": 1414264, 
  "network": "testnet"
}
```

**Comment by cdecker** [comment]
Can you share the output of `listpeers`? The status staying in "Loaded from database" usually just means that it wasn't able to reconnect to the peer.

**Comment by andrewtoth** [comment]
`listpeers`:
```
...
   {
      "id": "024c4a95dd7075c70ad36cb5f2de5e17dc99fd5fba9c402420b0af6abbd0137f4f", 
      "connected": false, 
      "channels": [
        {
          "state": "CHANNELD_SHUTTING_DOWN", 
          "short_channel_id": "1413716:128:0", 
          "channel_id": "db0d8186cd530983e0b0e2469cd1049d4cd9644c2eb4e45933a58df325d6b676", 
          "funding_txid": "76b6d625f38da53359e4b42e4c64d94c9d04d19c46e2b0e0830953cd86810ddb", 
          "msatoshi_to_us": 500000000, 
          "msatoshi_to_us_min": 500000000, 
          "msatoshi_to_us_max": 500000000, 
          "msatoshi_total": 500000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 5000, 
          "our_channel_reserve_satoshis": 5000, 
          "spendable_msatoshi": 495000000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 144, 
          "max_accepted_htlcs": 483, 
          "status": [
            "Loaded from database"
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }, 
...
`

**Comment by andrewtoth** [comment]
I have tried closing this channel multiple times and it still responds with 
`{ "code" : -1, "message" : "Channel close negotiation not finished before timeout" }`
so I am unable to access the funds.
Is there any other information that would be useful in resolving this?

**Comment by mberionni** [comment]
Hi,
I'm in a similar situation (peer not connected) but I tried the "force close" and my channel is now in state state AWAITING_UNILATERAL already since yeterday.
The channel was originally created a few months ago.
Below is the output of listpeers.
Any help is appreciated :)

{
  "peers": [
    {
      "id": "02d28c3aac4b4f36746052a735831afbe65bc5698a7be5bd41b42fd1ddf2a1a358", 
      "connected": false, 
      "channels": [
        {
          "state": "AWAITING_UNILATERAL", 
          "short_channel_id": "1261498:30:0", 
          "channel_id": "0d64321a1c926f51ab91834b3bb3d1a42a5ea234722b36da28c796dab6479ebd", 
          "funding_txid": "bd9e47b6da96c728da362b7234a25e2aa4d1b33b4b8391ab516f921c1a32640d", 
          "msatoshi_to_us": 9900000, 
          "msatoshi_to_us_min": 9900000, 
          "msatoshi_to_us_max": 9900000, 
          "msatoshi_total": 10000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 0, 
          "our_channel_reserve_satoshis": 100, 
          "spendable_msatoshi": 9800000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 4, 
          "max_accepted_htlcs": 483, 
          "status": [
            "Loaded from database"
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    },

**Comment by mberionni** [comment]
In my case, I'm on mainnet, not test...

**Comment by cdecker** [comment]
> In my case, I'm on mainnet, not test...

Pretty sure you're on testnet:

```
"short_channel_id": "1261498:30:0",
```
:wink:

**Comment by cdecker** [comment]
Indeed I can't see a closing transaction for neither of the two channels. Could you both share the output of the following, which allows us to check for the closing transaction:

```
sqlite3 $HOME/.lightning/lightningd.sqlite3 "select hex(rawtx) from transactions"
```

**Comment by andrewtoth** [comment]
Here's the output:
https://pastebin.com/hx5JJJ0a

**Comment by cdecker** [comment]
@andrewtoth can you try to do a force close?

```
lightning-cli close -k id=024c4a95dd7075c70ad36cb5f2de5e17dc99fd5fba9c402420b0af6abbd0137f4f force=true
```

**Comment by mberionni** [comment]
> > In my case, I'm on mainnet, not test...
> 
> Pretty sure you're on testnet:
> 
> ```
> "short_channel_id": "1261498:30:0",
> ```
> Funding TX: https://testnet.smartbit.com.au/tx/bd9e47b6da96c728da362b7234a25e2aa4d1b33b4b8391ab516f921c1a32640d

I used to run on testnet.
Is it the case that the listpeers could show also old channels on testnet?

This is a more recent channel:

    {
      "id": "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266", 
      "connected": true, 
      "netaddr": [
        "23.237.77.11:57193"
      ], 
      "global_features": "", 
      "local_features": "", 
      "channels": [
        {
          "state": "CHANNELD_NORMAL", 
          "owner": "lightning_channeld", 
          "short_channel_id": "542582:1404:0", 
          "channel_id": "5e61be57fe8ce61b1e21480080b125c346a7150c48e9c0c128a07eb0ce79ed91", 
          "funding_txid": "91ed79ceb07ea028c1c0e9480c15a746c325b1800048211e1be68cfe57be615e", 
          "msatoshi_to_us": 50000000, 
          "msatoshi_to_us_min": 50000000, 
          "msatoshi_to_us_max": 50000000, 
          "msatoshi_total": 50000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 546, 
          "our_channel_reserve_satoshis": 546, 
          "spendable_msatoshi": 49454000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 144, 
          "our_to_self_delay": 144, 
          "max_accepted_htlcs": 483, 
          "status": [
            "CHANNELD_NORMAL:Reconnected, and reestablished.", 
            "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    },

**Comment by andrewtoth** [comment]
Force close gave me
```
{
  "tx": "0200000001db0d8186cd530983e0b0e2469cd1049d4cd9644c2eb4e45933a58df325d6b6760000000000887b27800169a0070000000000220020bdfc1e9ab9bae442ea2601fd52f805194713841511903f4872608a0d0c49f46da20ff020", 
  "txid": "80e9a08a13652a13dfb6306664edd22a2e10a7bf51c2efddbdeb55350095f499", 
  "type": "unilateral"
}
```

`listpeers` gives me
```
    {
      "id": "024c4a95dd7075c70ad36cb5f2de5e17dc99fd5fba9c402420b0af6abbd0137f4f", 
      "connected": false, 
      "channels": [
        {
          "state": "AWAITING_UNILATERAL", 
          "short_channel_id": "1413716:128:0", 
          "channel_id": "db0d8186cd530983e0b0e2469cd1049d4cd9644c2eb4e45933a58df325d6b676", 
          "funding_txid": "76b6d625f38da53359e4b42e4c64d94c9d04d19c46e2b0e0830953cd86810ddb", 
          "msatoshi_to_us": 500000000, 
          "msatoshi_to_us_min": 500000000, 
          "msatoshi_to_us_max": 500000000, 
          "msatoshi_total": 500000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 5000, 
          "our_channel_reserve_satoshis": 5000, 
          "spendable_msatoshi": 495000000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 144, 
          "max_accepted_htlcs": 483, 
          "status": [
            "Loaded from database"
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    },
```

The closing transaction has been broadcast, so it looks like I will have access to the funds now. However, the status is still "Loaded from database".

**Comment by andrewtoth** [comment]
`listpeers` now gives:
```
    {
      "id": "024c4a95dd7075c70ad36cb5f2de5e17dc99fd5fba9c402420b0af6abbd0137f4f", 
      "connected": false, 
      "channels": [
        {
          "state": "ONCHAIN", 
          "owner": "lightning_onchaind", 
          "short_channel_id": "1413716:128:0", 
          "channel_id": "db0d8186cd530983e0b0e2469cd1049d4cd9644c2eb4e45933a58df325d6b676", 
          "funding_txid": "76b6d625f38da53359e4b42e4c64d94c9d04d19c46e2b0e0830953cd86810ddb", 
          "msatoshi_to_us": 500000000, 
          "msatoshi_to_us_min": 500000000, 
          "msatoshi_to_us_max": 500000000, 
          "msatoshi_total": 500000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 5000, 
          "our_channel_reserve_satoshis": 5000, 
          "spendable_msatoshi": 495000000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 144, 
          "max_accepted_htlcs": 483, 
          "status": [
            "ONCHAIN:Tracking our own unilateral close", 
            "ONCHAIN:2 outputs unresolved: in 97 blocks will spend DELAYED_OUTPUT_TO_US (80e9a08a13652a13dfb6306664edd22a2e10a7bf51c2efddbdeb55350095f499:0) using OUR_DELAYED_RETURN_TO_WALLET"
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }, 
```
