### ISSUE TITLE
update readme install instructions

### ISSUE THREAD

**Issue by 9735dev** [ElementsProject/lightning#1977]
I received this message while configuring to build:

```
> ./configure --enable-developer
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pytest'
...
```

I did this and the message went away:
`sudo apt-get install python3-pytest`

Would adding `python3-pytest` to the [list of packages to be installed](https://github.com/ElementsProject/lightning#installation) be appropriate?

**Comment by wythe** [comment]
Did configure still succeed? If so, you can run:
`pip3 install -r tests/requirements.txt`
and rerun configure.  If you try to run `make pytest` without it, then you should see an error message instructing you to do just that.

If configure failed then we should probably fix that.

As far as your question is concerned, I believe the README is intended for users, whereas doc/HACKING.md is for developers.  So making users install pytest isn't really necessary. We **should**, however, clearly redirect developers over to the hacking guide and instruct them to install `tests/requirements.txt`.

**Comment by 9735dev** [comment]
configure appeared to still work even though it output the error message. your recommendation of what to run works; verified with:
- `sudo apt-get remove python3-pytest`
- `./configure` and got the error message
- `pip3 install -r tests/requirements.txt`
- `./configure` and did not get the error message
thanks!

**Comment by darosior** [comment]
Hello @9735dev, installations instructions have changed and I think this can be closed
