### ISSUE TITLE
[fundchannel] Disconnect from a channel

### ISSUE THREAD

**Issue by blastbeng** [ElementsProject/lightning#1978]
Hello,
i don't know if this is the right place to ask this question, but i hope someone will help me :)

I have a fully working lightning node, i've funded some channels but now i want to disconnect from some
If I disconnect from a channel will my BTC come back to my lightning address or how to recover my BTC and forget a channel? 
Is there a safe way to "stop" funding a channel?

Sorry for the noob question, i am new to lightning
Thanks

**Comment by wythe** [comment]
The `close` command is what you're looking for, not disconnect. Type:
`lightning-cli help close` to see the manpage.

This will close the channel and return funds to your wallet.  

These questions are appreciated, it helps identify gaps in the documentation.

**Comment by darosior** [comment]
Hello @blastbeng, hope your experience with lightning went well until then :-). I think you can close this one ?

**Comment by ZmnSCPxj** [comment]
Closing.
