### ISSUE TITLE
Possible incorrect directory in systemd configuration

### ISSUE THREAD

**Issue by sipsorcery** [ElementsProject/lightning#1979]
`make install` copies binaries to /usr/local/bin. The systemd script in the contrib directory is using /usr/bin:

```
/usr/bin/lightningd --daemon --conf /etc/lightningd/lightningd.conf --pid-file=/run/lightningd/lightningd.pid
```

Should they be both pointing to the same directory?

**Comment by cdecker** [comment]
Good question. The prefix is changeable and we probably don't want to include the `systemd` config in `make install` (that's what package managers and distro releases are for).

Generally speaking the stuff in `contrib` is there to help, but can mostly not be used "as is".

**Comment by sipsorcery** [comment]
Ok.
