### ISSUE TITLE
Incorrectly spelled words. It is lightning-cli rather than lightgning-cli.

### ISSUE THREAD

**Issue by toshirot** [ElementsProject/lightning#198]
I think "daemon/lightgning-cli newaddr" is misspelled. 
It is  "daemon/lightning-cli newaddr". 
 
 at https://github.com/ElementsProject/lightning#user-content-opening-a-channel-on-the-bitcoin-testnet

yes It's a small problem :)

**Comment by cdecker** [comment]
Thanks for reporting this, every issue counts ;-)
