### ISSUE TITLE
Transactions are not broadcasted

### ISSUE THREAD

**Issue by peername** [ElementsProject/lightning#1985]
I am experimenting with c-lightning on a testnet. I generated a  new address, sent some test bitcoins to it and now I opened a few channels.

24 hours later my channels are still not opened:

> CHANNELD_AWAITING_LOCKIN:Funding needs more confirmations.

The actual problem is that transactions are not broadcasted to the network.

How can I re-broadcast the transactions? Is it possible to get the transaction hex and re-boadcast it manually via bitcoind?

**Comment by peername** [comment]
testnet=1
server=1
rpcuser=aaa
rpcpassword=bbb
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
addresstype=p2sh-segwit

**Comment by peername** [comment]
I opened 10 channels. 8 of them are showing me this status:

"status": [
            "CHANNELD_AWAITING_LOCKIN:WIRE_ANNOUNCEMENT_SIGNATURES (259) before funding locked", 
            "ONCHAIN:Tracking our own unilateral close", 
            "ONCHAIN:2 outputs unresolved: in 141 blocks will spend DELAYED_OUTPUT_TO_US (5f7ff0ddf641f4795625bab8681ab41849ecbbdc37a7107dd208f7c8e7682f26:0) using OUR_DELAYED_RETURN_TO_WALLET"
          ]

**Comment by rustyrussell** [comment]
I'm guessing that's LND, sending us ANNOUNCEMENT_SIGNATURES before we've told it funding is locked.  There's a proposal to make this illegal in the spec (https://github.com/TheBlueMatt/lightning-rfc/commit/454604135aee4848697a36ff609e59cb69f6a53e) but I'll fix this now.
