### ISSUE TITLE
Create the equivalent of "delinvoice" for payments

### ISSUE THREAD

**Issue by sumBTC** [ElementsProject/lightning#1995]
As far as I know, there isn't a method for deleting failed or completed payments, like there is for invoices (like delinvoice, and delexpiredinvoice). The aim is to reduce the output of 

    lightning-cli listpayments

**Comment by darosior** [comment]
I think this can be marked good first issue ?

**Comment by sumBTC** [comment]
Now, I delete **all** payments via:

`sqlite3 -header -line lightningd.sqlite3 'DELETE FROM payments'`
`sqlite3 -header -line lightningd.sqlite3 'DELETE FROM invoices'`

in `.lightning/bitcoin`

**Comment by vincenzopalazzo** [comment]
@cdecker Maybe this Issue can be close by this PR https://github.com/ElementsProject/lightning/pull/3899

**Comment by cdecker** [comment]
Definitely, thanks for looking this us @vincenzopalazzo

**Comment by sumBTC** [comment]
Tested it and it works. Thanks to all involved but in particular @vincenzopalazzo!
