### ISSUE TITLE
Channel stuck in state CHANNELD_AWAITING_LOCKIN

### ISSUE THREAD

**Issue by thorie7912** [ElementsProject/lightning#2003]
### Issue and Steps to Reproduce

I recently created a channel with an active peer. The connection seems to be good but the channel won't seem to become ready. I've tried restarting lightningd but the results are the same. The channel was created just a few days ago, and has more than 160 confirmations. The bitcoind node seems to be running fine and seems to be fully up-to-date. Any idea what is going on with this channel?

```
   {
      "id": "02551a0f955f86c892682487cc9403c4caf09ec37ae427b4475ea62379e94b15fe",
      "connected": true,
      "netaddr": [
        "193.29.56.102:9735"
      ],
      "global_features": "",
      "local_features": "8a",
      "globalfeatures": "",
      "localfeatures": "8a",
      "channels": [
        {
          "state": "CHANNELD_NORMAL",
          "scratch_txid": "3ede9e19bd65129bf29db648a8f049e9ace5494c71ae7d2551f1b3b938a89749",
          "owner": "lightning_channeld",
          "short_channel_id": "544828:1521:0",
          "channel_id": "c96ed255d34d1a5d5a0c0c84c05c849bb8d65d86ea465a00a258717b89454fd9",
          "funding_txid": "d94f45897b7158a2005a46ea865dd6b89b845cc0840c0c5a5d1a4dd355d26ec9",
          "msatoshi_to_us": 10000000,
          "msatoshi_to_us_min": 10000000,
          "msatoshi_to_us_max": 10000000,
          "msatoshi_total": 10000000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709551615,
          "their_channel_reserve_satoshis": 546,
          "our_channel_reserve_satoshis": 546,
          "spendable_msatoshi": 9454000,
          "htlc_minimum_msat": 0,
          "their_to_self_delay": 144,
          "our_to_self_delay": 144,
          "max_accepted_htlcs": 483,
          "status": [
            "CHANNELD_AWAITING_LOCKIN:Reconnected, and reestablished.",
            "CHANNELD_AWAITING_LOCKIN:They've confirmed funding, we haven't yet."
          ],
          "in_payments_offered": 0,
          "in_msatoshi_offered": 0,
          "in_payments_fulfilled": 0,
          "in_msatoshi_fulfilled": 0,
          "out_payments_offered": 0,
          "out_msatoshi_offered": 0,
          "out_payments_fulfilled": 0,
          "out_msatoshi_fulfilled": 0,
          "htlcs": [
          ]
        }
      ]
    }
```

Do I just need to wait longer? It seems strange that after so many days it still won't open the channel.

### `getinfo` output

```
{
  "id": "026155a7b6ce3e22130920f612ec74cf5e04e33cf01678c1437eb4996a865e5b39",
  "alias": "ghostofsatoshi",
  "color": "026155",
  "address": [
    {
      "type": "ipv4",
      "address": "185.232.64.153",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv6",
      "address": "::",
      "port": 9735
    },
    {
      "type": "ipv4",
      "address": "0.0.0.0",
      "port": 9735
    }
  ],
  "version": "v0.6.1-125-gd6fcfe0",
  "blockheight": 545082,
  "network": "bitcoin"
}
```

**Comment by rustyrussell** [comment]
@cdecker ?  Is this a candidate for dev-rescan?  Is the tx not in the db, or did it somehow get lost from db to channeld?

**Comment by cdecker** [comment]
That's strange, there are a number of contradictory fields here:

 - `.channels[0].state = "CHANNELD_NORMAL"`
 - `.connected = true`
 - `.channels[0].status[0] = CHANNELD_AWAITING_LOCKIN`

From all I can see the channel should be operational, except that we somehow restored the billboard messages (assuming the JSON-RPC response was taken after the restart). The transaction is confirmed, so `dev-rescan` wont be able to recover.

@thorie7912 how did you notice the channel is inactive? Did a payment fail, or did you assume it doesn't work because of the status message? The former is worrisome since it'd indicate a missing state transition or mixup, the latter might just be us not clearing the billboard and is easy to fix.

**Comment by thorie7912** [comment]
I think the channel is not open, because I tried the following:

1. Checked the peer I have the channel open with: https://1ml.com/node/02551a0f955f86c892682487cc9403c4caf09ec37ae427b4475ea62379e94b15fe
2. Saw that they have a channel open with CoinGate https://1ml.com/node/0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3
3. Tried to find a route to that destination:
```
lightning-cli getroute 0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3 1 1
{ "code" : -1, "message" : "Could not find a route" }
```

Since it couldn't find a route, I'm guessing that the channel is not yet open?

**Comment by thorie7912** [comment]
I tried to close the channel, but got a timeout.

```
$ lightning-cli close 02551a0f955f86c892682487cc9403c4caf09ec37ae427b4475ea62379e94b15fe false 300
{ "code" : -1, "message" : "Channel close negotiation not finished before timeout" }
```

```
2018-10-12T18:02:57.240Z lightningd(12353): 02551a0f955f86c892682487cc9403c4caf09ec37ae427b4475ea62379e94b15fe chan #8: State changed from CHANNELD_NORMAL to CHANNELD_SHUTTING_DOWN
```

I might have to try a unilateral close.

**Comment by cdecker** [comment]
@thorie7912 this should have been resolved by now, did it work?

**Comment by thorie7912** [comment]
@cdecker Looks like it worked. Channel no longer appears and I have 9,137 satoshi in outputs from the original 10,000 satoshi i used to open the channel.

I'll close this ticket for now. I can't say for sure what went wrong, but it might have been a database consistency or incompatibility issue. I restored my old lightning wallet by using the .lightning folder that I was using about 9 months ago, with the latest master version of lightning. I thought it would be a safe operation, maybe it was - maybe it wasn't. Who knows.

I'll re-open if I encounter this issue again, hopefully not. I'm going to try re-installing lightningd from scratch and funding it from scratch (not restoring from backup anymore) since now I have my funds back into my normal bitcoin wallet.
