### ISSUE TITLE
Simply mark channels as closed instead of deleting them from the DB

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#2028]
This is an idea that I've been playing with for some time now, and in the context of the stats tables dangling off of the `channels` table it seems to be a good time to propose this again.

Currently whenever we close a channel and see it confirm past 100 confirmations we actually go and delete the channel from the `channels` table, basically losing all information that was associated with it since it cascades through the database to all other tables. This can result in a couple of strange behaviors that are not immediately apparent to the casual observer, due to the delay.

So my proposal here is to, instead of deleting the entry from the database, simply mark it as `SETTLED` and which would also not load it on restart. This has the same semantics as deleting the entries, but allows us to retrieve information about long settled channels after the fact, and not have some infos, such as channel stats and htlc stats, have dangling references.

I went ahead and measured how much more data a really busy channel would cost if we left it lying around and the end-result is negligible, as long as we clear the `channel_htlcs` table when marking the channel as settled. For 100k payments, the sending side has a 219 MB database, of which 201 MB is `channel_htlcs`, and 17 MB is the `payments` table. For the receiving side things look similar, with the `invoices` table being slightly bigger than the `payments` table on the sending side.

What do you think @rustyrussell @ZmnSCPxj and @niftynei?

**Comment by ZmnSCPxj** [comment]
LGTM

**Comment by ZmnSCPxj** [comment]
Is this still ongoing?

**Comment by cdecker** [comment]
> Is this still ongoing?

Didn't get started yet, since there didn't seem too much interest so far. Would like to do it eventually, but it's not a priority atm.
