### ISSUE TITLE
How to properly shut down my c-lightning node?

### ISSUE THREAD

**Issue by bitcoinshirt** [ElementsProject/lightning#2030]
### Issue and Steps to Reproduce

As a merchant, I have a very well-connected c-lightning node which we've been using for months. It has a decent amount of channels.

I want to switch to a different VPS, so I'd like to close this node and deploy a new one. After some reading I realized that migration will be a pain, so decided to shut it down and deploy a new node instead.

Is there anything that has to be done to make sure nobody gets "hurt" in this process? 

I already did `withdraw all.`

Should I close all channels, or just shut down the node? 
Don't want to break anything for the customers who have channels with us opened and funded, so it's better to ask.

### `getinfo` output

{
  "id": "039195c0969d69f9a25839cb44bd5e858bd9e3971638959f0e657bffa6692b43f1", 
  "alias": "bitcoinshirt", 
  "color": "039195", 
  "address": [
    {
      "type": "ipv4", 
      "address": "13.92.141.163", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "3c8001d-modded", 
  "blockheight": 546013, 
  "network": "bitcoin"
}

**Comment by cdecker** [comment]
If you can keep the old node running I'd suggest opening a new channel from the old node to the new node, with the maximum capacity. This maintains the connectivity of your existing channels, and allows people to continue using your services. If you can't keep the old node running, then doing a `close` for each channel and allowing some time for the channels to settle (a few days, to also give offline nodes a chance to close cleanly) is the way to go. Maybe also change your alias to indicate that you are draining that node, so maybe people that'd try to connect to you learn about it and go to the new node instead.

We currently don't have a drain-mode, but that might be a nice addition. It'd stop accepting new channels but still allow old channels to be operated until they naturally close by themselves.

**Comment by bitcoinshirt** [comment]
Thanks @cdecker just as I thought, but wanted to be sure.

Ideally, it would be the best for us to just migrate the c-lightning from one VPS to another, but after reading on the risks and my lack of technical knowledge, I thought it may be easier to just shut it down and start a new one, which is a shame since our main c-lightning has been working very well.

**Comment by cdecker** [comment]
Yes, migrations with LN are scary, that should be much better with eltoo where the failure case just closes the channel, and doesn't steal all of your funds.
