### ISSUE TITLE
Multiple LN nodes connected to one bitcoind

### ISSUE THREAD

**Issue by d4amenace** [ElementsProject/lightning#2035]
I guess this is more of a question of feasability.  Is it possible to install multiple C-Lightning nodes on a single server and all access the same bitcoind and do not interfere with each other?  Can this be done by simply changing the port of each instance of seperately installed C-Lightning?

**Comment by cdecker** [comment]
Yes, and yes :-)

`bitcoind` is solely used to get data from the blockchain, nothing else. Specifically c-lightning does not make use of `bitcoind`'s wallet, so it's safe to share, and if you want you can even use a read-only API replica of `bitcoind`.

**Comment by cdecker** [comment]
Node also don't have to be co-located with `bitcoind` on the same machine. You can use `--bitcoind-rpcconnect` to connect to a remote `bitcoind` instance.

If you have multiple c-lightning nodes on the same machine you need to specify different `--lightning-dir` parameters and `--port` so the nodes don't clobber the same resources.

P.S.: These questions are a great fit for https://bitcoin.stackexchange.com/ :-)
