### ISSUE TITLE
ModuleNotFoundError: No module named 'pytest'

### ISSUE THREAD

**Issue by AndiMacTen** [ElementsProject/lightning#2041]
I don't think this is directly caused by c-lightning but since I get this error on two independent machines, I thought to let you know.

`user@hostname:~/lightning$ ./configure`
`Traceback (most recent call last):`
`File "<string>", line 1, in <module>`
`ModuleNotFoundError: No module named 'pytest'`
`Compiling ccan/tools/configurator/configurator...done`
`Making autoconf users comfortable... yes`
`[...]`
`Setting PYTEST...`
`user@hostname:~/lightning$`

Can reproduce this behavior on a Ubuntu 18.04 and a freshly installed 18.10 machine.
Any ideas?

**Comment by Aaron-R-Meek** [comment]
Your python installation does not have pytest.py installed as a module.
If you a running python 2 then:
pip install pytest  ( or _pip --user install pytest_     if you are running as root )
if python3 then:
pip3 install pytest   ( or _pip3 --user install pytest_     if you are running as root )


arm

**Comment by AndiMacTen** [comment]
Thank you. installing pip3 pytest helps, also #2187

**Comment by tyagi5011** [comment]
thankyou for the help.... it works
