### ISSUE TITLE
Error with "sendpay" method in pylightning

### ISSUE THREAD

**Issue by darosior** [ElementsProject/lightning#2046]
Hi,

I'm currently writing a mobile wallet for c-lightning and I use pylightning in order to manage RPC calls. While checking payment UI I noticed that `sendpay`, defined as : 
```
    def sendpay(self, route, payment_hash, description=""):
        """
        Send along {route} in return for preimage of {payment_hash}
        """
        payload = {
            "route": route,
            "payment_hash": payment_hash,
            "description": description,
        }
        return self.call("sendpay", payload)
```
https://github.com/ElementsProject/lightning/blob/7eec2253e962e524f8fd92b74f411f0b99706ba9/contrib/pylightning/lightning/lightning.py#L264
calls the `sendpay` RPC method giving it the `description` parameters, which results in : 
```
error: {'message': "Unknown parameter 'description'", 'code': -32602}
```
since the `sendpay` method takes `route` `hash` `msatoshis` as parameters, but not any `description` (as described in https://github.com/ElementsProject/lightning/blob/master/doc/lightning-sendpay.7.txt)

**Comment by rustyrussell** [comment]
Weird.  Documentation is wrong.  But I don't understand why 'description' doesn't work for you.  It seems to work fine here?

**Comment by darosior** [comment]
I did some tests : 
```
sendpay(the_route, the_hash)
```
( as used in https://github.com/ElementsProject/lightning/blob/master/contrib/pylightning/lightning-pay) works well, but if I specify a description as the third argument I get the error.

**Comment by ZmnSCPxj** [comment]
We special-case this `description` argument currently, is this still an issue?

**Comment by darosior** [comment]
It's been a while since I tried but it's not an issue anymore, closing it.
