### ISSUE TITLE
Sendpay fails with intructions from howto

### ISSUE THREAD

**Issue by pik0r** [ElementsProject/lightning#205]
Hi everybody,
thank you for doing all the work!

I could successfully build lightningd on Ubuntu. I was able to establish a connection to another node and fund the channel. After creating an invoice I tried to send the amount following the howto in the Readme.

First of all, I think it should say "daemon/lightning-cli sendpay $route <rhash>" instead of specifiying the <amount> in the Readme.

I constructed the route json as:

> route=$(daemon/lightning-cli getroute 03d181c82639a0a1510dfde9e27149bdfd823dce62af32a1b0ebb0485f797ae48d 3000 0 | jq --raw-output .route)

> echo $route
> [ { "id": "03d181c82639a0a1510dfde9e27149bdfd823dce62af32a1b0ebb0485f797ae48d", "channel": "1175484:1:0", "msatoshi": 3000, "delay": 4 } ]

When trying to send

> daemon/lightning-cli sendpay $route a54952ee6414246c3b12af7c4889df1b45875b251d4ba8a44e27240a25dd9ac0

standard out:

> lightning-cli: reading response: Connection reset by peer

standard out from daemon:

> lightningd(28282): Invalid token in json input: '{ "method" : "sendpay", "id" : "lightning-cli-1347", "params" : [ [, {, "id":, "03d181c82639a0a1510dfde9e27149bdfd823dce62af32a1b0ebb0485f797ae48d",, "channel":, "1175484:1:0",, "msatoshi":, "3000,", "delay":, 4, "}", "]", "a54952ee6414246c3b12af7c4889df1b'

Thank you for your help!

**Comment by jl777** [comment]
sendpay needs the rhash for the invoice.

**Comment by cdecker** [comment]
I fixed the README, should work now. Thanks for the report @pik0r :wink:
