### ISSUE TITLE
multisig?

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#206]
Ignoring the issue of how to route to a multisig address (assuming we allow any pubkey in the MofN multisig address to act as the coordinator) is there a way to sendpay to a multisig pubkey?

The redeemscript would need to be changed to spend the multisig, but not sure if anything else would need to be changed.

My usecase needs a temporary holding account with unknown destinations to receive the funds and then later with group approval to send out the funds. A multisig destination would work, but maybe a bit to complex.

Alternatively, what about a way to require an additional set of MofN signatures (of a timestamped invoice?) to release payment?

**Comment by cdecker** [comment]
Not sure what you're trying to achieve with this. Is it that you'd like to have a node which is controlled by multiple owners which have to agree on the operations of the node? Or is it that the settlement transaction should transfer the final balance to a multisig address?

Either way I think this is more of a protocol discussion and less of an implementation discussion, so maybe the https://github.com/lightningnetwork/lightning-rfc might be better suited for it :wink: (closing for now, feel free to reopen if you disagree)
