### ISSUE TITLE
UPPERCASE INVOICES FAIL

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#2063]
### Problem

Blockstream's store uses UPPERCASE invoices (they also prepend LIGHTNING:), giving '"Invoices must start with ln"'

This broke with 0.6.2's extra "must start with ln" check :(

### `getinfo` output
{
 "id": "024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605", 
  "alias": "BLUEIRON-v0.6.2rc1", 
  "color": "024b9a", 
  "address": [
    {
      "type": "ipv4", 
      "address": "128.199.202.168", 
      "port": 9735
    }, 
    {
      "type": "ipv6", 
      "address": "2400:6180:0:d0::5cd2:a001", 
      "port": 9735
    }, 
    {
      "type": "torv2", 
      "address": "m7uhnmknr5ell2jt.onion", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }, 
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "v0.6.2rc1", 
  "blockheight": 548063, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0
}

**Comment by kristapsk** [comment]
Hmmm... I did successful purchase from Blockstream Store yesterday, with v0.6.2 at my end, and there were no uppercase letters in invoice.
