### ISSUE TITLE
https://1ml.com/ does not display Time Lock Delta ; Min HTLC ;Base Fee ;Fee Rate

### ISSUE THREAD

**Issue by Chozowarrior** [ElementsProject/lightning#2067]
All of my channels do not display Time Lock Delta ; Min HTLC ;Base Fee & Fee Rate. Is this a know issue with the 1ml.com website our is this an issue within my c-lightning node?

**Comment by cdecker** [comment]
Do you have an example for this? Generally speaking you should contact the operator of 1ml, since they might be in a better position to help you debug the situation.

**Comment by Chozowarrior** [comment]
An example would be https://1ml.com/channel/602150841537134592 with node 2. Below are the cli details for this channel. I will also address the issue with 1ml.
`{
  "channels": [
    {
      "source": "02c69a0b4cb468660348d6d457d9212563ad08fb94d424395da6796fb74a13f276",
      "destination": "03a5927b64b1ea8657d5b770d61a3e2d0554fdb5d568773e0d6a92907913ca21f6",
      "short_channel_id": "547653:774:0",
      "public": true,
      "satoshis": 4000000,
      "message_flags": 0,
      "channel_flags": 0,
      "flags": 0,
      "active": true,
      "last_update": 1541106082,
      "base_fee_millisatoshi": 1000,
      "fee_per_millionth": 1,
      "delay": 144
    },
    {
      "source": "03a5927b64b1ea8657d5b770d61a3e2d0554fdb5d568773e0d6a92907913ca21f6",
      "destination": "02c69a0b4cb468660348d6d457d9212563ad08fb94d424395da6796fb74a13f276",
      "short_channel_id": "547653:774:0",
      "public": true,
      "satoshis": 4000000,
      "message_flags": 1,
      "channel_flags": 1,
      "flags": 257,
      "active": true,
      "last_update": 1540842655,
      "base_fee_millisatoshi": 950,
      "fee_per_millionth": 1,
      "delay": 144
    }
  ]
}
`

**Comment by Chozowarrior** [comment]
Trying to run the connect command again does not seem to make a difference. Also this is the same for all the 52 public channels I am running. How can I check whether my channel is sending updates or not? At least funds are occasionally running through some channels.

**Comment by cdecker** [comment]
Ok, looking through the output of my own `listchannels` I get the following:

```
$ lcli listchannels | jq '.channels[] | select(.source == "03a5927b64b1ea8657d5b770d61a3e2d0554fdb5d568773e0d6a92907913ca21f6") | select(.destination == "02c69a0b4cb468660348d6d457d9212563ad08fb94d424395da6796fb74a13f276")'
{
  "source": "03a5927b64b1ea8657d5b770d61a3e2d0554fdb5d568773e0d6a92907913ca21f6",
  "destination": "02c69a0b4cb468660348d6d457d9212563ad08fb94d424395da6796fb74a13f276",
  "short_channel_id": "549833:2282:1",
  "public": true,
  "satoshis": 4600000,
  "message_flags": 1,
  "channel_flags": 1,
  "flags": 257,
  "active": true,
  "last_update": 1542054323,
  "base_fee_millisatoshi": 987,
  "fee_per_millionth": 1,
  "delay": 144
}
$ lcli listchannels | jq '.channels[] | select(.destination == "03a5927b64b1ea8657d5b770d61a3e2d0554fdb5d568773e0d6a92907913ca21f6") | select(.source == "02c69a0b4cb468660348d6d457d9212563ad08fb94d424395da6796fb74a13f276")'
{
  "source": "02c69a0b4cb468660348d6d457d9212563ad08fb94d424395da6796fb74a13f276",
  "destination": "03a5927b64b1ea8657d5b770d61a3e2d0554fdb5d568773e0d6a92907913ca21f6",
  "short_channel_id": "549833:2282:1",
  "public": true,
  "satoshis": 4600000,
  "message_flags": 0,
  "channel_flags": 0,
  "flags": 0,
  "active": true,
  "last_update": 1542052884,
  "base_fee_millisatoshi": 1000,
  "fee_per_millionth": 1,
  "delay": 144
}
```

The 257 in the channel [`flags`](https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-channel_update-message) got me to hunt down what might have happened. It turns out that 1ml does not handle `flags` correctly. It appears that they do not handle the case that the optional high bits are set. They should really fix that asap...

**Comment by niftynei** [comment]
To add some context, c-lightning now sends the `htlc_maximum_msat` field in `channel_update`s which is signaled via the `message_flag` being set to one.

**Comment by Chozowarrior** [comment]
Thanks for finding this! I will give them the information provided by you. However before I have not yet received any  feedback from 1ml when raising the issue.

**Comment by Chozowarrior** [comment]
@firewire0202 yes I got confirmation from their side that they will look into it.

**Comment by Chozowarrior** [comment]
This has now been fixed within 1ML
