### ISSUE TITLE
"Outgoing subdaemon died" every time trying to pay between nodes

### ISSUE THREAD

**Issue by jarret** [ElementsProject/lightning#2069]
I just upgraded my two nodes running on mainnet from `v0.6.0` to `v0.6.2`

There is single channel between them with sufficient funds either way. Node 2 has other channels, but Node 1 only has a channel to Node 2.

If I try to invoice for 1000 msatoshis on Node 1 and pay with Node 2, it fails with "Outgoing Subdaemon died". This also happens if I reverse these two nodes for invoice and payer.

Node 1:

```
(ins)jarret@hugo:~/lightningd-run$ ./lcli.sh getinfo
{
  "id": "0257ddebb85581c58e288d825fc58b3f61af44a32a4a01d184e7ba67e21cfdd8e6", 
  "alias": "Forkdrop.io Station Hugo", 
  "color": "ff4444", 
  "address": [
  ], 
  "binding": [
  ], 
  "version": "v0.6.2", 
  "blockheight": 548489, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0
}
jarret@hugo:~/lightningd-run$ ./lcli.sh invoice 1000 label5 description5
{
  "payment_hash": "041720492cf923a059db3a03aacb5d177ac89bc79775c369b1ea803ee3a1bf8c", 
  "expires_at": 1541196706, 
  "bolt11": "lnbc10n1pdae0vjpp5qstjqjfvly36qkwm8gp64j6azaav3x78ja6ux6d3a2qracaph7xqdq5v3jhxcmjd9c8g6t0dc6scqp2rzjqt3cnkrp4nvadatspjvudsea63rq6mc79a4638glfumtap0uvrudwzp9ugqqyacqqqqqqqlgqqqqqqgqpczxtky3de96zf8u957jzm0q3d8t9nhqy2l93hctsuuxv7egn9vvk496n848uluaxa8un9vnmx06wkzl0e3dx7tn8dzf5etfev4fjly5gq7plyl3"
}
```

Node 2:

```
ubuntu@zebra:~/btc-rust/lightningd-run$ ./lcli.sh getinfo
{
  "id": "02e389d861acd9d6f5700c99c6c33dd4460d6f1e2f6ba89d1f4f36be85fc60f8d7", 
  "alias": "Forkdrop.io Station Zebra", 
  "color": "ffc45a", 
  "address": [
    {
      "type": "ipv4", 
      "address": "34.217.191.117", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "172.31.43.161", 
      "port": 9735
    }
  ], 
  "version": "v0.6.2", 
  "blockheight": 548489, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0
}
ubuntu@zebra:~/btc-rust/lightningd-run$ ./lcli.sh pay lnbc10n1pdae0vjpp5qstjqjfvly36qkwm8gp64j6azaav3x78ja6ux6d3a2qracaph7xqdq5v3jhxcmjd9c8g6t0dc6scqp2rzjqt3cnkrp4nvadatspjvudsea63rq6mc79a4638glfumtap0uvrudwzp9ugqqyacqqqqqqqlgqqqqqqgqpczxtky3de96zf8u957jzm0q3d8t9nhqy2l93hctsuuxv7egn9vvk496n848uluaxa8un9vnmx06wkzl0e3dx7tn8dzf5etfev4fjly5gq7plyl3
{ "code" : 205, "message" : "Could not find a route", "data" : 
{
  "getroute_tries": 2, 
  "sendpay_tries": 1, 
  "failures": [
    {
      "message": "Outgoing subdaemon died", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 0, 
      "failcode": 4103, 
      "erring_node": "02e389d861acd9d6f5700c99c6c33dd4460d6f1e2f6ba89d1f4f36be85fc60f8d7", 
      "erring_channel": "533986:631:0", 
      "route": [
        {
          "id": "0257ddebb85581c58e288d825fc58b3f61af44a32a4a01d184e7ba67e21cfdd8e6", 
          "channel": "533986:631:0", 
          "msatoshi": 1001, 
          "delay": 10
        }
      ]
    }
  ]
} }
```

Logs of Node 2 are at: https://gist.github.com/jarret/cd51af4f20e04266eff36a093c6da4f9
Starting with `Trying to find a route from 02e389d861acd9d6f5700c99c6c33dd4460d6f1e2f6ba89d1f4f36be85fc60f8d7 to 0257ddebb85581c58e288d825fc58b3f61af44a32a4a01d184e7ba67e21cfdd8e6 for 1001 msatoshi`

It has

`Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (9)`

and then:

`Failing HTLC 18446744073709551615 due to peer death`

I understand there are other issues that reference `owning subdaemon lightning_channeld died`, and https://medium.com/@pierre_rochard/day-4-of-the-chaincode-labs-lightning-residency-f28b046fc1a6 gives the advice "Run it with log-level=debug. Don’t be scared if logs say something “died”, not necessarily bad." However, it is odd that this failure happens so permanently right after upgrade. Paying between these nodes with the same channel were working before.

**Comment by darosior** [comment]
@jarret I guess this can now be closed ?

**Comment by jarret** [comment]
I have not encountered this at all running 0.7.* releases.
