### ISSUE TITLE
finding balances

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#207]
I could not find a way to get a list of the utxo the wallet has automatically added. (I assume it doesnt rescan the chain)

Also, is there a way to get the current net balance. With all the invoices and pending state of things, it is quite complicated to even know how much the current balance is. I guess there would need to be a pending incoming/outgoing amount to clarify the current and expected future balance

**Comment by cdecker** [comment]
Good catch, that's definitely a good idea and I'll add a corresponding call to the JSON-RPC interface.
