### ISSUE TITLE
bug for mainnet

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#208]
in daemon/bitcoind.c: static char **gather_args(struct bitcoind *bitcoind,

it assumes there is a parameter like -testnet or -regtest and if there isnt, ie for mainnet, it messes up the command line. I fixed it locally with an if statement to guard the second item:

line 33:
	args[n++] = cast_const(char *, bitcoind->chainparams->cli);
        if ( bitcoind->chainparams->cli_args != 0 && bitcoind->chainparams->cli_args[0] != 0 )
            args[n++] = cast_const(char *, bitcoind->chainparams->cli_args);

Also, is there a reason unix specific pipes are used for cli interface and not something OS portable like accessing via the rpc port?

**Comment by cdecker** [comment]
We currently default to using regtest on purpose until segwit is active on mainnet. The params (just an empty string) for mainnet are present in `chainparams.c` and are called `--network=bitcoin` to disambiguate should we ever add other blockchains as well. The only downside to having an empty string as params is that now we get two consecutive spaces in the command that is shelled out, but that's minor I'd say.

Eventually we are hoping to ween off of shelling out to `bitcoin-cli` altogether and use a builtin client to perform RPC operations.

**Comment by jl777** [comment]
well, it might be minor, but I kept getting "method "" unknown" type of errors as the null string made the cli confused.

I have an OS portable libcurl interface that I could swap in for bitcoind.c, but wasnt sure if there were any special requirements. I think using rpc interface via curl would allow OS portable and coin portable lightningd.

for now I just made a pure BTC fork (with segwit hardcoded on) so I can experiment with things

**Comment by cdecker** [comment]
Oh, you're right, I was under the impression that we build a command line and then shell out, but we are in fact forking and calling `execve` so empty args are not good here, great catch! I'll fix that, or if you'd like to make a PR with your changes that'd be even better :wink: 

As for libcurl, we are using an async IO loop (https://github.com/rustyrussell/ccan/tree/master/ccan/io) so it's probably not that easy, but I'm not unhappy if I'm proven wrong on this one as well.

And lastly, please do not test `lightningd` on mainnet! Whatever funds you put on it currently run the risk of getting lost. I have some recovery tools available but they're pretty untested, and I would hate for you to lose funds. As a matter of fact I might introduce a failure on mainnet on purpose just to dissuade people from trying to.

**Comment by jl777** [comment]
yes, the io looks very unix dependent... Seems it will not be easy to get windows versions anytime soon. Maybe a background curl thread can interface to the ccan async io, but I use unix, so I dont feel up to doing such messy things.

Also, I am using mainnet, but for a brand new coin which has no value.
There already are many blocks to using it on mainnet, I had to fiddle a few things to get it to work, ie. it assumes you are on testnet in several places

**Comment by cdecker** [comment]
Damn, you found my stumbling stones to throw users off of using mainnet xD

If you find places that rely on the testnet assumption please show us so we can eliminate them and parameterize them using `chainparams`. For what it's worth I was able to use the current code on Litecoin mainnet.

**Comment by jl777** [comment]
lightning/lightningd.c: 123:     dstate->testnet = false;//true;
daemon/lightningd.c: 43:    ld->dstate.testnet = false;//true;

I changed the hardcodes from true to false as I am only testing on mainnet. I believe I did the first mainnet LN transfers on CHIPS (new fork) with LN thinking it is mainnet. For LTC it probably worked, but believed it was in testnet as the hardcoded value was testnet=true

Of course the testnet field in the network definition also should be changed, but that appears to be ignored now. Not sure if there were any other places.

It doesnt seem to change that much other than various confirmation times. If you need a test mainnet, you can use the CHIPS coin I setup for this. https://bitcointalk.org/index.php?topic=2078449.msg20771074#msg20771074
