### ISSUE TITLE
Unilateral close funds recovery 

### ISSUE THREAD

**Issue by Chozowarrior** [ElementsProject/lightning#2084]
I had a setup in which I connected my Bitcoin Lightning Wallet (Android) to my c-lightning node. This is the funding transaction ab0ab22c6c99733cbb516be2d6a654985f28aee283d0c379af7d5e54d7bec368 After a while however the phone wallet crashed and I was forced to close the channel from the unilaterally close the channel using "lightning-cli close 03aeb591c8a45ff9e077299aa6e3d630160bb510210c123180ed653090351f17ba true" resulting in closing transaction 5392bb648d480c0d926387cc06b60ad30bcf3b9dab1952c0387bc636a99fe026 (see raw output below). Now is there a way to recover the funds as the funds do not seem to be within one of the wallet addresses after restoring the seed on both end?

{
	"result": {
		"txid": "5392bb648d480c0d926387cc06b60ad30bcf3b9dab1952c0387bc636a99fe026",
		"hash": "9f171160d69030e1b3c0dd115558461026b1cc2514b542d4d7e32486995337b2",
		"version": 2,
		"size": 346,
		"vsize": 181,
		"locktime": 546431145,
		"vin": [
			{
				"txid": "ab0ab22c6c99733cbb516be2d6a654985f28aee283d0c379af7d5e54d7bec368",
				"vout": 1,
				"scriptSig": {
					"asm": "",
					"hex": ""
				},
				"txinwitness": [
					"",
					"3045022100bd18b595ed834de302e9b8a2390694994c4d9845d817ecc9a40faeb938d2ec82022001f21fbb7ff5d979886885b7ce21d8caf9eaba1b9a4ef97b7417d4f4376343d801",
					"3044022042b26fa9c87f99652b603b1e570a04ba13ff3207bbaa20ad18cd50f5769cab11022050094aa45e8c8cf5b0da62dc49428a79a45ea74119606b4ad865a13e2c140be801",
					"522102949608352ef30424e8f5c7100a5c06fa064dc09963a4987c866d0c64565dd8b221039b383525c6d9921064220338596fc462dd943c752bc01ba4d797acd91fb4c35e52ae"
				],
				"sequence": 2147505773
			}
		],
		"vout": [
			{
				"value": 0.00276445,
				"n": 0,
				"scriptPubKey": {
					"asm": "0 037c2cd05c32c44da880f6618d6535f5b160a7cec7313bb7a56a8f654cf95046",
					"hex": "0020037c2cd05c32c44da880f6618d6535f5b160a7cec7313bb7a56a8f654cf95046",
					"reqSigs": 1,
					"type": "witness_v0_scripthash",
					"addresses": [
						"bc1qqd7ze5zuxtzym2yq7esc6ef47kckpf7wcucnhda9d28k2n8e2prqx72qwa"
					]
				}
			},
			{
				"value": 0.00607552,
				"n": 1,
				"scriptPubKey": {
					"asm": "0 00668f32fbaf7cc7fe6711309dfc166993ebbaca",
					"hex": "001400668f32fbaf7cc7fe6711309dfc166993ebbaca",
					"reqSigs": 1,
					"type": "witness_v0_keyhash",
					"addresses": [
						"bc1qqpng7vhm4a7v0ln8zycfmlqkdxf7hwk2h3mv98"
					]
				}
			}
		],
		"hex": "0200000000010168c3bed7545e7daf79c3d083e2ae285f9854a6d6e26b51bb3c73996c2cb20aab01000000006d56008002dd37040000000000220020037c2cd05c32c44da880f6618d6535f5b160a7cec7313bb7a56a8f654cf95046404509000000000016001400668f32fbaf7cc7fe6711309dfc166993ebbaca0400483045022100bd18b595ed834de302e9b8a2390694994c4d9845d817ecc9a40faeb938d2ec82022001f21fbb7ff5d979886885b7ce21d8caf9eaba1b9a4ef97b7417d4f4376343d801473044022042b26fa9c87f99652b603b1e570a04ba13ff3207bbaa20ad18cd50f5769cab11022050094aa45e8c8cf5b0da62dc49428a79a45ea74119606b4ad865a13e2c140be80147522102949608352ef30424e8f5c7100a5c06fa064dc09963a4987c866d0c64565dd8b221039b383525c6d9921064220338596fc462dd943c752bc01ba4d797acd91fb4c35e52aea9e09120",
		"blockhash": "000000000000000000262753313ff8c5c54d02c34b2f64c8cc50f1e958a6fe86",
		"confirmations": 1641,
		"time": 1541093928,
		"blocktime": 1541093928
	},
	"error": null,
	"id": null
}

**Comment by ZmnSCPxj** [comment]
I notice that one side output (the side owned by the node doing the unilateral close) was claimed:

https://www.smartbit.com.au/tx/d999349d054227446b68a8adf99448dd6b32a80065ef825f37ea7d9f248a5002

You mentioned that you closed unilaterally on the C-lightning side.  The above transaction is C-lightning correctly claiming the funds after their timeout expired.

The other output remains unclaimed:
https://www.smartbit.com.au/address/bc1qqpng7vhm4a7v0ln8zycfmlqkdxf7hwk2h3mv98

The other output is presumably from your mobile wallet.  That cannot be claimed by C-lightning, since it was not owned by the C-lightning node.

Suggest closing as it is not issue with C-lightning per se, but with the mobile wallet "Bitcoin Lightning Wallet (Android)"

**Comment by Chozowarrior** [comment]
Thanks, this is indeed correct. Will check for a backup of channel data on the phone.
