### ISSUE TITLE
Loading lightning-dir from config file doesn't work

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#2089]
I was hoping I could use --conf to set the lightning-dir, so that I could launch lightningd like so:

```
lightningd --conf=mainnet.conf
```

in `mainnet.conf` I have:
```
lightning-dir=/home/jb55/.lightning-bitcoin
```

this doesn't seem to work, it tries to load `~/.lightning` instead which is my testnet directory.

when I do `lightningd --lightning-dir=/home/jb55/.lightning-bitcoin --conf=mainnet.conf` it works.

Some context: I'm creating a nixos module for clightning, which looks like this:

```nix
  services.clightning.networks = {
    testnet = {
      dataDir = "/home/jb55/.lightning";

      config = ''
        fee-per-satoshi=9000
        network=testnet
        log-level=debug
        alias=@jb55
        rgb=ff0000
      '';
    };

    mainnet = {
      dataDir = "/home/jb55/.lightning-bitcoin";

      config = ''
        bitcoin-rpcuser=rpcuser
        bitcoin-rpcpassword=rpcpassword
        fee-per-satoshi=9000
        network=bitcoin
        log-level=debug
        alias=@jb55
        rgb=ff0000
      '';
    };
  };


```

it would be nice to not need the `dataDir` attribute, and just specify all of my per-node config in a single file.

**Comment by jb55** [comment]
cc @arowser

**Comment by arowser** [comment]
@jb55  Its seems a path issue,  the working directory changed to default lightning-dir before read config file,  you can try #2097 or  use a absolute path, like:

    lightningd --conf=/xxx/c-lightning/mainnet.conf

**Comment by jb55** [comment]
I was actually using an absolute path, even though in my example I wasn't.

**Comment by jb55** [comment]
in other words, 

```
lightningd --conf=/nix/store/b8idhkfg7r9js0khw64fl5h7fjmhn9z8-clightning-mainnet.conf
```

with lightning-dir inside mainnet.conf wasn't working, but 

```
lightningd --lightning-dir=/home/jb55/.lightning-bitcoin --conf=/nix/store/b8idhkfg7r9js0khw64fl5h7fjmhn9z8-clightning-main.conf
```

does

**Comment by arowser** [comment]
What's error message when you using an absolute path

    lightningd --conf=/nix/store/b8idhkfg7r9js0khw64fl5h7fjmhn9z8-clightning-mainnet.conf
