### ISSUE TITLE
restoring state?

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#209]
It appears that none of the existing peers, channels, etc. are restored on a restart. Are there plans to make at least the currently open channels to be restored?

If the channel from the previous session is forgotten, then wouldnt the funds in the old channel be at risk?

**Comment by cdecker** [comment]
Yes and yes, we are working on peer, channel and HTLC persistence, it's definitely a high priority issue.

**Comment by jl777** [comment]
glad to hear! It does seem a money critical issue as I think the entire amount locked in the channel would be forfeited.

**Comment by cdecker** [comment]
This should be addressed by PR #222
