### ISSUE TITLE
Lightningd does not start with --plugin= command line argument

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#2116]
### Issue and Steps to Reproduce
Maybe this is a mac issue related to #2090 but I cannot start `lightningd` when passing an argument. 
first of all the documentation contradicts itself:
I find that the plugins need to be called with `--plugin=PATH` and with `--plugin PATH` the first version stops lightningd to start where as the second version will have lightningd starting up but ignoring the code from the hello world example plugin. 

as far as I understood the file `docs/plugin.md` I should have been able to make a call like `lightning-cli hello` or `lightning-cli --hello` or with `greeting` instead of `hello`. Also the `plugin.md` states that it adds command line arguments to lightningd but I guess that does not make sense as lightningd will already be started if everything goes successfully.

Would be great if you could help out quickly as I am about to finish the next youtube video and wanted to provide the code also as a c-lightning plugin

### `getinfo` output (if started without plugin argument)
```
ln1 getinfo
{
  "id": "02eea4a069fe8298b63ce0cfee67a68f85f594b0385b3b0f062ff92fcbeb0fa446", 
  "alias": "YELLOWSPAWN", 
  "color": "02eea4", 
  "num_peers": 0, 
  "num_pending_channels": 0, 
  "num_active_channels": 0, 
  "num_inactive_channels": 0, 
  "address": [
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "127.0.0.1", 
      "port": 9600
    }
  ], 
  "version": "v0.6.2-112-gb8bf887", 
  "blockheight": 0, 
  "network": "regtest", 
  "msatoshi_fees_collected": 0
}
```

**Comment by cdecker** [comment]
Thanks for reporting this, it turns out that I forgot to update the function names in the plugin after we renamed them to `getmanifest` and `init`. PR #2117 will fix that.

As for the `lightning-cli` passthrough to the plugin that is still being worked on in the `plugin-3` branch but very close to being finalized. I'm hoping to open the PR later today.

**Comment by renepickhardt** [comment]
Ok renaming functions makes sense I guess I will be able to test this locally. Would you say it is save to already test `plugin-3` branch to provide a plugin for the command line API? I don't even see a use case for plugins that extend the `lightningd` command line args
