### ISSUE TITLE
Direct channel should be preferred

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#2119]
Currently, route randomization means that sometimes we do not take the direct route.

However, it should be remembered that route randomization is intended to prevent third parties from learning all of our payments.

And if a one-channel route exists that is viable, we should instead consider paying it so that none of our payment information to the payee node is even leaked to intermediaries.
Thus, for this particular case (a route exists that is direct between payer to payee, and is viable for paying), route randomization is hurtful.

--

One might argue, that perhaps we might not want to let the payee node know that we are in fact directly connected, so using an alternate route will at least obscure this.

One can also argue that the payee probably already knows where we live in order to  deliver their goods to us, but at least we can prevent the payee from having an idea of where our node is on LN.

In addition, this is viable only if we regularly transact with the payee anyway.  For one-off purchases, being directly connected to the payee is largely immaterial.

--

I can implement this now with current payalgo.

However, we will need to change the payalgo almost completely in order to support ZKCP-preserving multipath payments anyway, so I wonder if I should instead defer this particular subfeature to the new payalgo.

**Comment by kristapsk** [comment]
I would also prefer use of a direct channel, if it is available. If others may not, probably this could be made configurable?

**Comment by kristapsk** [comment]
Today tried to pay another yalls.org invoice and it failed (still have direct channel with yours node open). Not able to pay at all when I have direct channel open sounds really like a bug to me. At least, if routing fails, it should fall back to direct route, if it exists.
```
{ "code" : 200, "message" : "Stopped retrying during payment attempt; continue monitoring with pay or listpayments", "data" : 
{
  "getroute_tries": 1, 
  "sendpay_tries": 1, 
  "id": 11, 
  "payment_hash": "f98639a3901b6dec7ebebf213dd29f3f9fe1134a07175b73087da64068b5c953", 
  "destination": "03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56", 
  "msatoshi": 150000, 
  "msatoshi_sent": 151396, 
  "created_at": 1543532561, 
  "status": "pending", 
  "description": "Read: Hi guys, New here just testing o", 
  "failures": [
  ]
} }
```
Related to #2108.

That `lightningd` process had crashed before (most likely my fault, disk partition got full) and probably I tried payment too early, before it restored connections to other nodes or something? (but I'm not sure that is the case)

**Comment by ZmnSCPxj** [comment]
That is not a bug; the payment stalled along the route.
It is unsafe to try alternate routes (even direct routes) while some other route has stalled; it is possible for the payee to "fake" such a stall, make you fall back to another route, then claim both payments.
If the payment actually failed (instead of stalling --- notice how `failures` is empty, meaning it is *not* a failure, only a stall) then c-lightning will retry, possibly with the direct route.

It *is* a reason to try the direct route first; there are fewer moving parts that could stall in a direct route.

**Comment by kristapsk** [comment]
Ahh, ok, so currently the only thing I can do is to wait and hope it will succeed at some point in the future?

**Comment by ZmnSCPxj** [comment]
That, or for the payment to time out and fail via the timeout path.

C-lightning has mitigation for stalls, but only for local connections --- the mitigation works if we are forwarding for someone else (and reduces the probability of stalls at our node) or on the first hop of a route.
It cannot work if it stalled on some other node that has not added this mitigation (older c-lightning, or current/older versions of other implementations; it has been recommended to them, but, I do not keep track closely to their development).
Finally it is "only" a mitigation, there is a few milliseconds window for a stall to occur, but this is much tighter than without the mitigation.
