### ISSUE TITLE
If plugins use std.out without proper json nothing is displayed

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#2146]
### Issue and Steps to Reproduce
when I write a plugin in python and I use `print("test")` in the best case the plugin does not start and give me an error because of: 
https://github.com/ElementsProject/lightning/blob/b7da41e674c06c4101b389842a14f695cb29520e/lightningd/plugin.c#L294

In the worst case this happens somewhere during the plugin and I will see nothing. Not on the shell and not in the logfiles. 

I tried to provide a patch to `plugin.c` but it seems like I did not find the correct place. It seems like `plugin->buffer` is not emptied but when adding a `log_debug(plugin->log, "received message: %s", plugin->buffer);` it did not get displayed. Though it worked when adding it to other places within plugin.c.  

This is particularly annoying since I am currently developing a small plugin that starts a flask server (not sure if plugins like this are actually a good idea at all) and developing becomes really cumbersome because every time flask crashes with internal server error or something similar I don't see any output. 

Also when having syntax errors in python or exceptions I can't see any output. This is really really annoying. 

My current workflow is that while developing the plugin I am mocking my c-lightning node and just run the plugin from the command line. But I guess that this should only be a temporary solution.

**Comment by renepickhardt** [comment]
I am surprised you do this on the python side. Also I never heard the word monkey patching. If you give me a high level idea how you would do that I could probably help out so that you can focus more on stuff happening on the c-side (:

**Comment by renepickhardt** [comment]
>This is generally a bad idea except when it is a good idea.

( :

**Comment by rustyrussell** [comment]
We now log when we get bad JSON from a plugin.  Does that resolve this issue?

**Comment by renepickhardt** [comment]
as far as I experienced it I didn't have trouble anymore (at least with the python client api)

**Comment by cdecker** [comment]
> as far as I experienced it I didn't have trouble anymore (at least with the python client api)

Done, push to prod! :wink:
