### ISSUE TITLE
CHANNELD_AWAITING_LOCKIN when there is no need if transaction has > 2 confirmations

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#215]
I understand there needs to be 2 confirmations for the funds to be usable, but if doing addfunds with an older transaction, it still waits for 2 confirmations from when the addfunds is call, not from when the transaction was confirmed.

Should be a simple bug to fix, but I figured this should be fixed upstream

[another possible issue is that it didnt automatically detect the new tx, i think it might be due to the fact it was the second (or third?) newaddr for this node]

**Comment by cdecker** [comment]
This is actually not a problem, lightningd does not track the confirmations of funds added using the `addfunds` RPC call, and the funds are immediately spendable. So there is no need to confirm transactions, either before or after invoking `addfunds`. The only time we require confirmations is during the channel establishment, and in this case the confirmations are required for the channel to be secure.

We will eventuall autodetect incoming transactions as well, removing the need to go and fetch the tx from the command line and feeding it in through the RPC, we just haven't come that far yet :-)

**Comment by cdecker** [comment]
The daemon does not need confirmations for incoming funds, but does not detect them on its own just yet. I've opened #257 to track progress on the detection.
