### ISSUE TITLE
listpeers should show how many blocks until confirmation in status

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#2150]
### Issue and Steps to Reproduce

Currently:
            "CHANNELD_AWAITING_LOCKIN:Funding needs more confirmations."

### `getinfo` output
v0.6.2

**Comment by darosior** [comment]
Hi,
I was looking for making a PR to solve this issue but I have some questions. 
How many confirmations are needed ? If it is more than one, do we start the count when the tx is included in a block or when it is broadcasted ?

**Comment by trueptolemy** [comment]
hi, @rustyrussell i pulled the PR#2334 and try to fix this. what do u think of this solution? thanks

**Comment by rustyrussell** [comment]
Fixed in #2405
