### ISSUE TITLE
pay should use the 'r' fields in invoice

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#2163]
### Issue and Steps to Reproduce
A bolt11 invoice can contain routing hints, but currently we ignore them.  We should try to use them, esp. if there's no other route!

**Comment by ZmnSCPxj** [comment]
#1330 had a solution where the payment algorithm attempted to use "contact points".  Each contact point would be an `r` field, as well as the actual payee (listed first in the array of contact points).  It would get each contact point in turn, and `getroute` to the first node in the route.  If a `getroute` failed, it would pop off the first contact point and move to the next contact point.

Similar solution can be remade, in either current payalgo or new pay plugin.

**Comment by rustyrussell** [comment]
This was fixed with the introduction of the pay plugin in 0.7.0
