### ISSUE TITLE
reconnection causes fatal signal 11

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#217]
I think there are some problems with reconnecting peers, especially when there are prior channels that were open.

 One or both sides ends up crashing:

+838.803191280 lightningd_handshake(11224):INFO: Peer out to 02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc
+838.803215804 lightningd(10246):jcon fd 14:DEBUG: Success
+838.803225654 lightningd(10246):INFO: peer 02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc: Peer has reconnected, state CHANNELD_NORMAL
+838.803263480 lightningd_handshake(11224):DEBUG: Status closed, but not exited. Killing
+838.803428150 lightningd_handshake(11224):DEBUG: finishing: (nil)
+838.803433504 lightningd(10246):jcon fd 14:IO-IN: 
+838.803439330 lightningd(10246):jcon fd 14:IO-OUT: 7b20226a736f6e727063223a2022322e30222c2022726573756c7422203a207b2022696422203a202230323737396235376236363730363737386161316337333038613831376463303830323935663363326136616633343962623131313462386265333238633238646322207d2c2022696422203a20226c696768746e696e672d636c692d313132313922207d0a
+838.803582188 lightningd(10246):jcon fd 14:DEBUG: Closing (Bad file descriptor)
+838.803591629 lightningd(10246):jcon fd 17:IO-IN: 7b20226d6574686f6422203a20226765746368616e6e656c73222c2022696422203a20226c696768746e696e672d636c692d3131323139222c2022706172616d
+838.803603503 lightningd(10246):jcon fd 17:IO-IN: 7322203a205b205d207d
+838.803778277 lightningd_gossip(10255):DEBUG: TRACE: req: type WIRE_GOSSIPCTL_GET_PEER_GOSSIPFD len 11
+838.803799924 lightningd_gossip(10255):INFO: REPLY WIRE_GOSSIPCTL_GET_PEER_GOSSIPFD_REPLY with 1 fds
+838.803813984 lightningd_channel(11139):DEBUG: Status closed, but not exited. Killing
+838.803959308 lightningd_channel(11139):DEBUG: finishing: 0x4090c4
+838.803967510 lightningd(10246):BROKEN: FATAL SIGNAL 11 RECEIVED

I traced it into: get_gossip_fd_for_channeld_reconnect that is calling subd_req macro and that is as far as I got. hopefully the above will make sense to you.

[I just noticed I might be connecting to a peer that is already connected, maybe that is what causes the crash? If this is the case, probably enough to just return that it is already connected instead of dieing]

**Comment by cdecker** [comment]
Thanks for reporting @jl777, is this still up to date? Duplicate connections should result in the old connection being dropped and the new one taking over the channel (just created a unit test that checks this).

It would be helpful if you could provide us with a core dump for segfaults. To get one run `ulimit -c unlimited` in the shell before starting `lightningd` and it'll create a dump in the current directory. Please also provide us with the commit you are testing.

**Comment by jl777** [comment]
It hasnt core dumped in a while. the recent changes have made it much less crashy, only issue is the "still in progress" state it gets into, but maybe it is due to illegal routes being used.

**Comment by cdecker** [comment]
That's good news, thanks, glad it got more stable. Running with the core dumps enabled would allow us to catch rare events, so it'd be a great help anyway.

Should I close the issue for now, since it seems hasn't happened for a while now?

**Comment by jl777** [comment]
yes, this one can be closd

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> Thanks for reporting @jl777, is this still up to date? Duplicate connections should result in the old connection being dropped and the new one taking over the channel (just created a unit test that checks this).
>
> It would be helpful if you could provide us with a core dump for segfaults. To get one run `ulimit -c unlimited` in the shell before starting `lightningd` and it'll create a dump in the current directory. Please also provide us with the commit you are testing.

Correction: It will core dump in the .lightning/ directory.

Cheers,
Rusty.
