### ISSUE TITLE
insufficient funds error, when there are sufficient confirmed funds

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#218]
+3707.888030979 lightningd(11266):jcon fd 14:IO-OUT: 7b20226a736f6e727063223a2022322e30222c2022726573756c7422203a207b20226368616e6e656c7322203a200a095b200a09097b2022736f7572636522203a2022303237373962353762363637303637373861613163373330386138313764633038303239356633633261366166333439626231313134623862653332386332386463222c202264657374696e6174696f6e22203a2022303362303365666366363437653664643438623934396535623166376539653036343235376135633438633264353662313333346232383362343833333866383231222c202261637469766522203a20747275652c20226665655f7065725f6b7722203a2031302c20226c6173745f75706461746522203a20313530323939363134382c2022666c61677322203a20302c202264656c617922203a2031302c202273686f72745f696422203a202232383037383a313a302f3022207d2c200a09097b2022736f7572636522203a2022303362303365666366363437653664643438623934396535623166376539653036343235376135633438633264353662313333346232383362343833333866383231222c202264657374696e6174696f6e22203a2022303237373962353762363637303637373861613163373330386138313764633038303239356633633261366166333439626231313134623862653332386332386463222c202261637469766522203a20747275652c20226665655f7065725f6b7722203a2031302c20226c6173745f75706461746522203a20313530323939363134382c2022666c61677322203a20312c202264656c617922203a2031302c202273686f72745f696422203a202232383037383a313a302f3122207d205d207d2c2022696422203a20226c696768746e696e672d636c692d313330313522207d0a
+3707.888093282 lightningd(11266):jcon fd 14:DEBUG: Closing (Bad file descriptor)
+3707.888239895 lightningd(11266):jcon fd 14:IO-IN: 7b20226d6574686f6422203a202273656e64706179222c2022696422203a20226c696768746e696e672d636c692d3133303135222c2022706172616d7322203a
+3707.888253647 lightningd(11266):jcon fd 14:IO-IN: 205b205b7b226964223a223032373739623537623636373036373738616131633733303861383137646330383032393566336332613661663334396262313131
+3707.888260507 lightningd(11266):jcon fd 14:IO-IN: 34623862653332386332386463222c226368616e6e656c223a2232383037383a313a30222c226d7361746f736869223a313030303030303030302c2264656c6179223a31307d5d2c2022643765333563626264623834363130313239376638636165326538626364633139656231663531353836633637656664343137386135
+3707.888276349 lightningd(11266):jcon fd 14:IO-IN: 34383063303238333530225d207d
+3707.888499767 lightningd(11266):INFO: Sending 1000000000 over 1 hops to deliver 1000000000
+3707.888617953 lightningd_channel(12759):DEBUG: TRACE: Adding HTLC 0 gave 5
+3707.888627417 lightningd_channel(12759):INFO: REPLY WIRE_CHANNEL_OFFER_HTLC_REPLY with 0 fds
+3707.888645480 lightningd(11266):BROKEN: FATAL SIGNAL 11 RECEIVED

I think Adding HTLC 0 gave 5 means insufficient funds, but I specifically did addfunds this session and waited for it to confirm. it looks like the peer reconnected and that cleared the state about the addfunds?

**Comment by cdecker** [comment]
That's strange (and the segfault is quite scary). I don't think this has anything to do with the `addfunds` call. Error 5 on an HTLC is `CHANNEL_ERR_CHANNEL_CAPACITY_EXCEEDED`, so my guess is that you funded the channel with 1000000 satoshi or slightly more, and then tried to transfer the full capacity. That won't work because there are some reserve values in the channel (you cannot have a user completely deplete its capacity in one direction otherwise they'd have no incentive to collaborate).

As for the segfault, could you run `lightningd` with `gdb` and provide us with a trace? Also which version are you running here (git commit)?

**Comment by jl777** [comment]
the channel was funded with 100 mil satoshis, ie. full coin. it has way more than the million satoshis for the spend.

It just feels as if resuming a node in an already setup network gets things really unstable. With the complex state machine logic, I am not familiar enough to troubleshoot it other than to say I cant get it to work in a complex real world simulation yet.

I am running it on a fork I made of it, but I only changed some coin parameters and cosmetic things. certainly not brave enough to mess around with the core logic (yet)

I think the signal 11 is self-inflicted. It ended up in a state that was unexpected and chose to just abort. I think it was closing a channel that was just being reconnected and got confused, something like that. When I debug this next I will get some gdb backtraces, but looking at the pending pull request it looks like there is a good chance that it will be much happier when I merge in the latest.

**Comment by jl777** [comment]
I think there is a bit of a confusion. What seems to be happening is that all of the value of an addfunds is used up even if a very small fundchannel is used. Maybe when the wallet starts managing the utxo directly this isnt an issue, but it wont allow an addfunds for a rawtransaction that has had any usage in any fundchannel, regardless of how small the fundchannel was.

In my case, I have a full 110 mil satoshi rawtransaction, a 1 million satoshi fundchannel and then all further fundchannels get an "Could not add outputs to wallet" as it seems to mark it as fully spent, even though only 1% of it was. Of course, maybe what is needed is simply the change utxo, but as it is I have no visiblity into what txid the change went to.

On a related issue, I am wondering how it would be possible to prove a lightning payment was made before the channel is closed to an external party. Maybe that is just not possible?

**Comment by jl777** [comment]
this specific bug was indeed due to not having the 1% reserve for the fundchannel, so I will close this one, but will open up another one due to the issues with not being able to spend all the funds
