### ISSUE TITLE
After update to latest release. When restarting lightningd service, last seen doesn't update on 1ML.com?

### ISSUE THREAD

**Issue by firewire0202** [ElementsProject/lightning#2199]
Updated to the latest release of c-lightning recently. The update finished as usual, and everything comes back ok, channels, peers, new version, balances, etc. But when restarting the lightningd service and then checking 1ML.com for a status update, it doesn't update last seen? Curious has anyone else run into this problem? It also maybe 1ML.com but I have tested with another lightning instance with LND and it updates last seen on 1ML.com fine.

I know this is may be a cosmetic thing, but curious if I may have missed something during the update? Don't want others thinking the node is down when it isn't..

**Comment by mmvphil** [comment]
Yeah I had to notify them when i put up another node.  I think they got a few glitches. Hope they get it worked out as it is a great site.

**Comment by cdecker** [comment]
How do you guys feel about closing this and hoping that this is fixed remotely? @conscott @firewire0202

**Comment by conscott** [comment]
Fine with me

**Comment by firewire0202** [comment]
Sorry for the late response. Closing. The issue was fixed on their end.
