### ISSUE TITLE
New install - wallet network check failed

### ISSUE THREAD

**Issue by mmvphil** [ElementsProject/lightning#2200]
running lightning gives me this.. 
------------
Wallet blockchain hash does not match network blockchain hash: 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943 != 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f. Are you on the right network? (--network={bitcoin, testnet, regtest, litecoin or litecoin-testnet})
lightningd: Wallet network check failed.

//blockchaininfo..
{
  "chain": "main",
  "blocks": 555033,
  "headers": 555033,
  "bestblockhash": "000000000000000000079ce33c59891c0535252ecde1a9ba54e02326d7959a26",
  "difficulty": 5106422924659.822,
  "mediantime": 1545540026,
  "verificationprogress": 0.9999994176935699,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000000474f97a92ad0d064062b156",
  "size_on_disk": 223729727270,
  "pruned": false,
  "softforks": [

//.. config

root@server:/lightning/lightningd# cat ~/.lightning/config
alias=TINKERTIGER
rgb=008000
network=bitcoin

**Comment by mmvphil** [comment]
Well by rm -rf ~/.lightning   I fixed it .. but still can't figure out how that happened.

**Comment by ZmnSCPxj** [comment]
It seems you ran it without `network=bitcoin` first. This is basic check to ensure  that you do not mix nrtworks in your `.lightning` directory

**Comment by mmvphil** [comment]
You mean the ORDER in the conf?

**Comment by ZmnSCPxj** [comment]
No. It means you or somebody with access to your account ran it without the option, *then* you ran it with the option.

**Comment by mmvphil** [comment]
WOW I didn't see that anywhere in the docs. Well at least it will be here
in the archives.

**Comment by ZmnSCPxj** [comment]
This comes up once every two months, we should really improve our docs.
