### ISSUE TITLE
Does not support data loss protection - BITCOIN LN Wallet -  still not fixed !

### ISSUE THREAD

**Issue by mmvphil** [ElementsProject/lightning#2220]
### Issue and Steps to Reproduce

Paying 
02c8ca5511b7646546728dda5788a365564a7916832815b72e5aa75ff60e722256@173.208.150.210:9735
from THE ONLY ANDROID LN WALLET THAT CAN BOTH SEND AND RECEIVE
MEANING _.. THE ONLY thing we got to drive actual normal use!_

**Still not available?  After 6 months?**  
I honestly don't know what to say other than i can't move forward trying to put out use cases if we can't work with the only android wallet that can both send and receive.

### `getinfo` output
  ... dead in the water

**Comment by cdecker** [comment]
This is utterly unhelpful, we are aware of the issue and we are working on it. The option was disabled due to c-lightning and lnd apparently having an incompatibility.

Duplicates #2170
