### ISSUE TITLE
some c-lightning nodes do not accept openChannel from LND

### ISSUE THREAD

**Issue by fluidvoice** [ElementsProject/lightning#2241]
Background
Can connect to a c-lighting node but cannot open a channel.
Works OK with other LND nodes.
I've talked to another LND user who says he has the same problem: https://i.imgur.com/qU1diFx.png

environment:
lnd 0.5.1-beta
Linux 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
Bitcoin Core Daemon version v0.17.0.1
Raspberry Pi (Raspiblitz project): https://github.com/rootzoll/raspiblitz

Steps to reproduce:
Connect and try to openChannel to:
03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e@199.96.236.9:9735

Actual behaviour
Openchannel times out/fails.
Disconnecting 199.96.236.9:9735, reason: Peer 199.96.236.9:9735 no answer for 5m0s -- disconnecting
unable to open channel to NodeKey(): peer disconnected
[lncli] rpc error: code = Unknown desc = peer disconnected

performing same to this node succeeds:
0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c@mainnet.node.lightningpowerusers.com:9735

showing my successfully opened channels (dunno if they are LND or not)...

admin@thundahub:~ $ lncli listchannels
{
"channels": [
{
"active": false,
"remote_pubkey": "02e55281b6555dc72275a4a6809df347edc02c23e43826a916dfa1702d86005170",
"channel_point": "c87357cfdbee9c6b7302809a278553d350d2b2a6c48b6bcba04383714f6eaba8:1",
"chan_id": "612964538441269249",
"capacity": "250000",
"local_balance": "245386",
"remote_balance": "0",
"commit_fee": "4614",
"commit_weight": "600",
"fee_per_kw": "6374",
"unsettled_balance": "0",
"total_satoshis_sent": "0",
"total_satoshis_received": "0",
"num_updates": "20",
"pending_htlcs": [
],
"csv_delay": 144,
"private": false
},
{
"active": false,
"remote_pubkey": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c",
"channel_point": "6c9f793113ab7cc32a60eaf3482a55f82d45df1f7b3ab19f68adef14fea3b327:0",
"chan_id": "613132763720777728",
"capacity": "30000",
"local_balance": "25385",
"remote_balance": "0",
"commit_fee": "4615",
"commit_weight": "600",
"fee_per_kw": "6375",
"unsettled_balance": "0",
"total_satoshis_sent": "0",
"total_satoshis_received": "0",
"num_updates": "10",
"pending_htlcs": [
],
"csv_delay": 144,
"private": false
}
]
}
[lnd.log.175.txt](https://github.com/ElementsProject/lightning/files/2744924/lnd.log.175.txt)

**Comment by Saibato** [comment]
@fluidvoice  had you noticed that 
;; ANSWER SECTION:  is
mainnet.node.lightningpowerusers.com. 60 IN A	74.108.13.152

but the node announces  199.96.236.9 
AFAICS connect to 74.108.13.152  is possible.
Maybe the node is behind a NAT and has not updated his node parameters on NAT address change??? 
can you try to use 74.108.13.152:9735 with your c-LN and fund a channel? 

hope that helped

**Comment by Saibato** [comment]
lnd AFAICS  0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c**7c** is
on  74.108.13.152

  {
      "id": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c", 
      "connected": true, 
      "netaddr": [
        "74.108.13.152:9735"
      ], 
      "global_features": "", 
   

but c-LN also
connect 03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f**7e** 74.108.13.152

gives
  }, 
    {
      "id": "03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f**7e**", 
      "connected": true, 
      "netaddr": [
        "199.96.236.9:9735" **// in fact  74.108.13.152**:9735
      ], 
      "global_features": "", 
      "local_features": "8a", 
      "globalfeatures": "", 
      "localfeatures": "8a", 
      "channels": [
      ]
    }

can you confirm this?

**Comment by fluidvoice** [comment]
what do you mean by "**in fact 74.108.13.152:9735**" ?

$ lncli getnodeinfo 03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e{
    "node": {
        "last_update": 1546498791,
        "pub_key": "03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e",
        "alias": "CryptoCloaksBTCPAY",
        "addresses": [
            {
                "network": "tcp",
                "addr": "199.96.236.9:9735"
            }
        ],
        "color": "#03e81a"
    },
    "num_channels": 6,
    "total_capacity": "4234018"
}

**Comment by Saibato** [comment]
i mean it should be possible to do lncli connect 03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e@**74.108.13.152:9735**
instead of
lncli connect 03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e@**199.96.236.9:9735**

one can see that  announcement **199.96.236.9** is not updated  to **74.108.13.152** by the c-LN
node
**03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e**
it still states 
"netaddr": [
"199.96.236.9:9735"  
],

when it is in fact now  74.108.13.152:9735

could you connect and fund?

**Comment by fluidvoice** [comment]
74.108.13.152:9735 has nothing to do with 199.96.236.9:9735. They are two different nodes.
199.96.236.9:9735 is alias **CryptoCloaksBTCPAY** (running c-LN which fails)
74.108.13.152:9735 is alias **LightningPowerUsers** (running LND which succeeds)
I still don't understand what you are saying with this... "it is in fact now 74.108.13.152:9735"

**Comment by Saibato** [comment]
yes, but both now AFAICS reachable on same ip 74.108.13.152

**Comment by fluidvoice** [comment]
> yes, but both now AFAICS reachable on same ip 74.108.13.152

you are determining this how?

**Comment by Saibato** [comment]
dig it and them
cli/lightning-cli --lightning-dir xxxxxx  connect 03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e 74.108.13.152

**Comment by fluidvoice** [comment]
doesn't work for me - as expected:
admin@thundahub:~ $ `lncli disconnect` 03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e
{

}
admin@thundahub:~ $ `lncli connect 03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e@74.108.13.152:9735`
[lncli] rpc error: code = Unknown desc = EOF

**Comment by fluidvoice** [comment]
> ok, now we have an issue...
> seem's that lnd handel's the announcement stricter than c-LN
> so if the announcement is wrong but ip ok LND refuses to connect.
> 
> Hmm

If c-LN is connecting to: **03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e@74.108.13.152**
that is a problem since that IP address is NOT correct for the **CryptoCloaksBTCPAY** node, but this is a different issue than what I'm reporting here.  
I'm connecting LND --> c-LN and you're talking about connecting c-LN --> LND.  
These two problems might be related or maybe not.

**Comment by Saibato** [comment]
this discussion may fix a real problem. but i think on the LND side as you can get a peer connect to an
outdated ip ,so lets go on...
i  do c-LN to c-LN (  CryptoCloaksBTCPAY 03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e@74.108.13.152 )

**Comment by Saibato** [comment]
@fluidvoice ok, so far we only know that new channel's c-LN  c-LN to CryptoCloaksBTCPAY  are possible
as we can see on 
https://1ml.com/node/03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e
but as you state not from an LND node.

so far you are correct
 and **i am  wrong** this is not related to the IP   199.96.236.9:9735 or 74.108.13.152

so we are setback zo c-LN c-LN works
LND c-LN not

**Comment by fluidvoice** [comment]
> @fluidvoice ok, so far we only know that new channel's c-LN c-LN to CryptoCloaksBTCPAY are possible
> as we can see on
> https://1ml.com/node/03e81a5b8af31bc00a1c1c08419d3272b4982db02feafd739904df2edfcbdf6f7e
> but as you state not from an LND node.
> 
> so far you are correct
> and **i am wrong** this is not related to the IP 199.96.236.9:9735 or 74.108.13.152
> 
> so we are setback to c-LN c-LN works
> LND c-LN not

Do you have a c-LN node I can try to open-chan with to get the debug logs on the c-LN side?

**Comment by Saibato** [comment]
@fluidvoice  "0341f5ff2992997613aff5675d6796232a63ab7f30136219774da8aba431df37c8@62.102.148.158:6201

**Comment by Saibato** [comment]
@fluidvoice the node 0341f5ff2992997613aff5675d6796232a63ab7f30136219774da8aba431df37c8 is up now, you can connect, and i hope solve the issue :+1:

**Comment by fluidvoice** [comment]
> @fluidvoice the node 0341f5ff2992997613aff5675d6796232a63ab7f30136219774da8aba431df37c8 is up now, you can connect, and i hope solve the issue

$ `lncli getnodeinfo 0341f5ff2992997613aff5675d6796232a63ab7f30136219774da8aba431df37c8`
[lncli] rpc error: code = Unknown desc = unable to find node

**Comment by Saibato** [comment]
can you try lncli connect 0341f5ff2992997613aff5675d6796232a63ab7f30136219774da8aba431df37c8@62.102.148.158:6201
?

**Comment by fluidvoice** [comment]
yes it succeeded...
{
	"funding_txid": "b5eecfe64daab6fa9e3be84e44c92929c8cf1a89e08aa796790048259e78a4c1"
}

**Comment by Saibato** [comment]
is see 038d3eb5339f78774697448ce2414b429b4xxxxxxxxxxxxxxxxxxxxxxxx that must be u so let's see what
happens...

**Comment by fluidvoice** [comment]
The connection and openChannel succeeded. So the problem is not reproduced on this node.

**Comment by Saibato** [comment]
my node is  
 ], 
  "version": "v0.6.3rc1", 
  "blockheight": 557943, 
  "network": "bitcoin", 
  "msatoshi_fees_collecte
 
have you figured out what  CryptoCloaksBTCPAY uses?
i can recompile if you like to get on the bottom of this?

**Comment by fluidvoice** [comment]
> my node is
> ],
> "version": "v0.6.3rc1",
> "blockheight": 557943,
> "network": "bitcoin",
> "msatoshi_fees_collecte
> 
> have you figured out what CryptoCloaksBTCPAY uses?
> i can recompile if you like to get on the bottom of this?

what commands does CryptoCloaksBTCPAY need to run to show his setup/config/versions?

**Comment by fluidvoice** [comment]
He's running BTCPay server:  https://github.com/btcpayserver/btcpayserver

**Comment by Saibato** [comment]
just a 
`lightning-cli  getinfo `
or 
`lightning-cli  --lightning-dir= _____his_path_____   getinfo`

**Comment by fluidvoice** [comment]
I bet this problem has something to do with his deployment. Like his BTCPay server instance deployed on a cloud server that is fouling things up.  Just a guess.

**Comment by Saibato** [comment]
we will see, AFAIK Nicolas has a stake in that so i think he will share  his opinion?
if you can find the version i can recompile but my BTCPay server was a early test and is offline now
so...

**Comment by Saibato** [comment]
can he use ` bitcoin-lightning-cli.sh getinfo` ? or is that only inside docker???
don't try if not sure, as we wont want to kill his node ;-)

the doku says Toolling
bitcoin-cli.sh: Access your Bitcoin node instance (for RPC)
bitcoin-lightning-cli.sh: Access your C-Lightning node instance (for RPC)
changedomain.sh: Change the domain of your BTCPayServer 

so ?

**Comment by fluidvoice** [comment]
> can he use ` bitcoin-lightning-cli.sh getinfo` ? or is that only inside docker???
> don't try if not sure, as we wont want to kill his node ;-)
> 
> the doku says Toolling
> bitcoin-cli.sh: Access your Bitcoin node instance (for RPC)
> bitcoin-lightning-cli.sh: Access your C-Lightning node instance (for RPC)
> changedomain.sh: Change the domain of your BTCPayServer
> 
> so ?

He told me he can SSH in. So I asked him to run the getinfo command. Waiting for reply.

**Comment by fluidvoice** [comment]
their wiki said how:
E.g. to list all commands: `./bitcoin-lightning-cli.sh help`
or show info about the node `./bitcoin-lightning-cli.sh getinfo`

**Comment by Saibato** [comment]
./bitcoin-lightning-cli.sh getinfo yes might work.
sadly it's not a DEVELOPER compile the pong of the ping  was without version

**Comment by Saibato** [comment]
since you still around, we had some issues a while ago with tor and lnd,  as this is also an old tor node 
and the ip is now public and announced, do you like to test, before i change name and exitpoint?

**Comment by NicolasDorier** [comment]
If you control `CryptoCloaksBTCPAY` and that you are running it on x64, you can try to swtich to the dev version by replacing, in $BTCPAY_DOCKER_COMPOSE

```diff
  clightning_bitcoin:
-    image: btcpayserver/lightning:v0.6.3-rc1
+   image: btcpayserver/lightning:v0.6.3-rc1-dev
```

Then `btcpay-up.sh`

**Comment by fluidvoice** [comment]
resolved in: https://github.com/ElementsProject/lightning/pull/2262#issue-244277814
