### ISSUE TITLE
Don't always throw away old transactions

### ISSUE THREAD

**Issue by bitonic-cjp** [ElementsProject/lightning#2242]
(If I'm wrong, please ignore this issue. I created this so that I don't forget to mention this.)

I suspect C-Lightning throws away old transactions from the transactions table once they're completely spent. I think this is undesirable if those transactions are unconfirmed, and may need to be re-broadcasted.

In my case, I had two channels, the new one being funded from the change utxo of the funding tx of the old one. The old one somehow never got confirmed, so the new one couldn't confirm either. The old one's funding tx wasn't in the transactions table. I could find its raw tx data in the logs though. I suspect it got removed when creating the new channel.

**Comment by cdecker** [comment]
We currently do not delete any transactions from the database, but you might still be correct that we do not store all transactions. I'll go through the transactions we send and make sure we store them in the DB.

**Comment by cdecker** [comment]
We now store all transactions before broadcasting them, and we also track transactions that are sent by peers that relate to any of our channels.
