### ISSUE TITLE
Local test done, how to move it to Digital Ocean?

### ISSUE THREAD

**Issue by Elmit2015** [ElementsProject/lightning#2246]
For learning I have setup lightning on my local machine. It was running 1 day, but not a single transaction. One channel is to 1ML, but when I wanted to claim my node, they asked me to send a certain amount to the channel (or a multiple of that). Since I have already feed the channel, I think I have to close the channel in order to feed it with the exact amount. However, to close gives me a "Channel close negotiation not finished before timeout"

Maybe that is the reason I have no success with the setup at all.

How can I move all to digital ocean? And continue to test there?

**Comment by cdecker** [comment]
You don't need to close all channels before migrating the node to a new host. But you need to be very careful about shutting down (and disabling) the node so it can't perform any updates after you take the snapshot/copy the data files.

It is probably best to shutdown `lightning-cli stop`, wait for the node to have completely stopped, then `mv` the `lightning-dir` to a new location, so even accidentally restarting the node will not cause updates, and then copying over that backup to the DO machine.

[This is not really a bug, so probably misplaced on the projects dev issue tracker, please use [StackOverflow](https://bitcoin.stackexchange.com/) for future queries of this kind.]

**Comment by cdecker** [comment]
In case you really want to close the channels, you can add the `force` parameter to cause a unilateral close in case the other endpoint is unresponsive:

```
lightning-cli close [peer_id] true
```
