### ISSUE TITLE
"Peer not ready for connection" when trying to fundchannel a second time

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#225]
Since it takes 2+ coin confirmations to establish a channel, in order to stream payments non-stop, I want to create a second channel ahead of time. That way, when the first channel is used up, I can quickly switch to the second channel.

Not sure if this is a protocol change, but I didnt see anywhere in the protocol where only once channel can be made between two peers (same direction).

I can imagine it would be a pain to implement, but maybe it would be possible to have a special "fund ahead" (like read-ahead) channel. It would be fine if this channel cannot have any payments or invoices or any actions at all other than just being made ready.

then when the active channel is closed, the fund ahead channel can become the active channel (via some special call or automatically).

I want to setup a test where millions of sendpays are done continuously and when I can calibrate the time required per sendpay, it would be a matter to have the addfunds transactions being large enough to be able to sustain continuous payments. Since things dont appear to be any where close to network saturating, it should be able to 10x the overall throughput by using 10 client nodes.

I doubt I can process 10,000 tx per second on one thread, but maybe if I have one thread per client on the host side, it could get close to that level?

**Comment by cdecker** [comment]
While the spec allows for multiple channels over a single connection, or even multiple connections to a single peer, we do not support that feature. For the case that you'd like to amortize the confirmation time I'd suggest creating multiple redundant routes, which also has the advantage of making you a forwarding peer, making the network more resilient and making you less reliant on a single peer staying up.

**Comment by jl777** [comment]
how can I create multiple redundant routes between two nodes? My network topology is where there is a host node that coordinates between the client nodes, so the clients are not in direct contact with each other.

I guess you are saying that if a matrix of connections were made, then there would be N channels funded and N routes to each node that is hopping through one other node...

**Comment by cdecker** [comment]
There is no way currently to create a redundant connection between two peers, but if you add a third node and connect your two existing ones to that node you have independent paths (one direct and one indirect) between any two nodes in your network.
