### ISSUE TITLE
Building from released sources zip does not work

### ISSUE THREAD

**Issue by kristapsk** [ElementsProject/lightning#2254]
Using https://github.com/ElementsProject/lightning/releases/download/v0.6.3/clightning-v0.6.3.zip.
```
$ ./configure --enable-plugins
(...)
$ make
fatal: Not a git repository (or any of the parent directories): .git
Makefile:6: *** "ERROR: git is required for generating version information".  Stop.
```
Of course, it works if I do `git checkout v0.6.3` in git, instead of using zip from [release page](https://github.com/ElementsProject/lightning/releases/tag/v0.6.3).

**Comment by rustyrussell** [comment]
This is produced from #2247 :
[clightning-v0.6.3.zip](https://github.com/ElementsProject/lightning/files/2752675/clightning-v0.6.3.zip)

**Comment by jb55** [comment]
weird I still get `ERROR: git is required for generating version information` with that zip

**Comment by jb55** [comment]
this might be related to nixos' sandbox builds and what folder it extracts it to though... seems to work when I unzip and build it normally

**Comment by kristapsk** [comment]
No error in the new zip, works for me.

**Comment by rustyrussell** [comment]
Confirmed:

`9b21f94634b9ce3ffd920ed3ce18da35db399d070e3c750b86e65414a34d3aeb  release/clightning-v0.6.3.zip`
