### ISSUE TITLE
Cannot be reached at port 9735

### ISSUE THREAD

**Issue by Elmit2015** [ElementsProject/lightning#2258]
I am trying to figure out why I cannot connect to the port 9735 from the wild Internet.

https://www.yougetsignal.com/tools/open-ports/ gives me for the IP address 220.133.223.206 and port 9735 "closed port"

My ASUS router forwards port 9735 from the Internet to an Internal machine 192.168.1.22 port 9735
Systemlog / Portforwarding tab shows:
```
Destination     Proto. Port range  Redirect to     Local port
ALL             TCP    9735        192.168.1.22  9735

```
On this machine telnet 127.0.0.1 9735
```
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
```
netstat -a -n |grep 9735
`tcp6       0      0 :::9735                 :::*                    LISTEN`     

sudo ufw status
```
Status: active

To                         Action      From
--                         ------      ----
9735                       ALLOW       Anywhere                  
9735 (v6)                  ALLOW       Anywhere (v6)             

9735                       ALLOW OUT   Anywhere                  
9735 (v6)                  ALLOW OUT   Anywhere (v6)
```

What am I missing?

**Comment by SimonVrouwe** [comment]
use option `--bind-addr=192.168.1.22:9735` `--announce-addr=<your_pub_ip>:9735`

**Comment by Elmit2015** [comment]
adding bind-addr and announce-addr resulted in:
```
lightning             | 2019-01-12T15:02:07.282Z lightning_hsmd(16): pid 16, msgfd 13
lightning             | 2019-01-12T15:02:07.532Z lightning_connectd(17): pid 17, msgfd 16
lightning             | 2019-01-12T15:02:07.532Z lightning_hsmd(16): Client: Received message 11 from client
lightning             | 2019-01-12T15:02:07.532Z lightning_hsmd(16): Client: Received message 9 from client
lightning             | 2019-01-12T15:02:07.532Z lightning_hsmd(16): new_client: 0
lightning             | 2019-01-12T15:02:10.288Z lightning_connectd(17): STATUS_FAIL_INTERNAL_ERROR: Failed to bind on 2 socket: Address not available
lightning             | lightningd: lightning_connectd failed (exit status 242), exiting.
```
adding autolisten results in the same

I removed bind-addr again and left autolisten=false

runs again, but https://www.yougetsignal.com/tools/open-ports/ shows 220.133.223.206 port 9735 is closed.

**Comment by SimonVrouwe** [comment]
Perhaps a stupid question, but did you check the local ip address of the machine? DHCP may have given new one.

**Comment by Elmit2015** [comment]
Thanks! It inspired me to the solution. I use static IP for my LAN to avoid such traps, ...
I tried then to use the docker IP, same ...
The solution was to use:
`- --bind-addr=0.0.0.0:9735`

Thanks!!!
