### ISSUE TITLE
Return formatted JSON from plugin response

### ISSUE THREAD

**Issue by conscott** [ElementsProject/lightning#2265]
Playing with the latest plugin code, and it would be nice to be able to create RPC commands that returns formatted JSON. For example, in this [balance plugin](https://github.com/conscott/c-lightning-plugins/blob/master/balance.py) I can return a dict / json, but I can't seem to get it to "pretty print"

In the current code it looks like...
```
$ lightning-cli balance

{"onchain_balance": "1.69527319", "channel_balance": "0.30596198", "total_balance": "2.00123517", "balance_outgoing": "0.30596198", "balance_incoming": "0.00403802", "total_invoices_paid": "0.00406900", "total_routing_fees_paid": "0.00000415", "total_paid_with_routing": "0.00407315", "total_received_invoices": "0.00002208
```
(Non-formatted)

But if I change the return value [here](https://github.com/conscott/c-lightning-plugins/blob/master/balance.py#L48) to be 
```python
return json.dumps(data, indent=4)
```
You end up with 
```
"{\n    \"onchain_balance\": \"1.69527319\",\n    \"channel_balance\": \"0.30596198\",\n    \"total_balance\": \"2.00123517\",\n    \"balance_outgoing\": \"0.30596198\",\n    \"balance_incoming\": \"0.00403802\",\n    \"total_invoices_paid\": \"0.00406900\",\n    \"total_routing_fees_paid\": \"0.00000415\",\n    \"total_paid_with_routing\": \"0.00407315\",\n    \"total_received_invoices\": \"0.00002208\"\n}"
```
Printing the '\n' instead of interpreting them as newlines. 

Ideally you could simply return the `dict` object and get...
```
$ lightning-cli balance
{
  "onchain_balance": 1.69527319,
  "channel_balance": 0.30596198,
  "total_balance": 2.00123517, 
  "balance_outgoing": 0.30596198, 
  "balance_incoming": 0.00403802, 
  "total_invoices_paid": 0.00406900, 
  "total_routing_fees_paid": 0.00000415, 
  "total_paid_with_routing": 0.00407315, 
  "total_received_invoices": 0.00002208
}

**Comment by conscott** [comment]
I was able to make this change with [this commit](https://github.com/conscott/lightning/commit/df310137a4084ac73e5c715843568044a1f0f685) but I feel it's a bit ugly

If python just does
```
json.dumps(result, indent=2, fp=sys.stdout)
```
The following object gets return to lightningd
```
"jsonrpc": "2.0",
"id": "lightning-cli-20868",
"result": {
    "greeting": "Hello conor",
    "asdf": 2
  }
}
```
And lightningd will just print the entire string contained in `result`, which ends up being
```
{
    "greeting": "Hello conor",
    "asdf": 2
  }
```
With everything after the initial `{` having two extra spaces of indents after the first line. 

The commit I have submitted just reduces the indentation level two spaces after the first `result: {`, however I imagine other plugins may also encounter this issue, so it may be better fixed in lightningd than in pylightning. 

Thoughts @cdecker ?

**Comment by cdecker** [comment]
I'm rather unconvinced that this is a real need, and that formatting of the final result on the shell ought to be done using a separate tool such as `jq`. The method you propose is rather costly since it serializes, splits and then iterates over lines again.

If we limit it to be the single call to `dumps` with `indent=2`, accepting the extra indent of 2 for now, but anything beyond that is probably more cost than it's worth.

**Comment by conscott** [comment]
Fair enough, going to close
