### ISSUE TITLE
using persistent peers version - getchannels does not return reconnected channel

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#227]
in getpeers it returns:
{ "unique_id" : 0, "state" : "CHANNELD_NORMAL", "netaddr" : "Unknown protocol 0", "peerid" : "02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc", "connected" : false, "channel" : "70332:1:0", "msatoshi_to_us" : 10125000000, "msatoshi_total" : 10125000000 }

a channel is there, this is from a restored channel. however in the getchannels it returns empty. I think you forgot to add the reconnected channels to the getchannels list

**Comment by cdecker** [comment]
No, the node will reconnect and reopen the channel if the node that restarted was the one with the incoming connection, i.e., the opening node will reattempt. The other node cannot reconnect since the port is a random high port.
