### ISSUE TITLE
Funds disappeared

### ISSUE THREAD

**Issue by lorenzoPrimi** [ElementsProject/lightning#2273]
### Issue and Steps to Reproduce
Hi all,
a few months ago I opened a lightning network node on the main net, opened three channels and fund each one of them with 100000 sat.
Now I want to withdraw these funds so I went to check the node, I found the three channels closed (on 1ml) or 1 on getfunds, and no funds on my wallet.
Can anybody help me understand what happened in this period to the node and the channels and where are the funds?
https://1ml.com/node/02267f6f4dbedb8bd75b81b4595dea2752a383b0d808b4fa0d2122b83b28f33ae9

### `getinfo` output
```
{
  "id": "02267f6f4dbedb8bd75b81b4595dea2752a383b0d808b4fa0d2122b83b28f33ae9", 
  "alias": "BetStatus", 
  "color": "005180", 
  "num_peers": 3, 
  "num_pending_channels": 2, 
  "num_active_channels": 1, 
  "num_inactive_channels": 0, 
  "address": [
    {
      "type": "ipv4", 
      "address": "5.135.156.14", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }, 
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "v0.6.3rc1-4-g9e4d405", 
  "blockheight": 558894, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0
}
```
### `listfunds` output
```
{
  "outputs": [
    {
      "txid": "c9c29c3eb806ae22f00ad4bf0df8e3a61ddf589c73e843e5672793e8d6a486a7", 
      "output": 0, 
      "value": 99515, 
      "address": "bc1qr0df0htdjfx7v6j4rnvzk3mzu6n4z0eewqa5yh", 
      "status": "confirmed"
    }, 
    {
      "txid": "46ee1ce2714be0cbe45d3d25399eecdf49c4daf47ac1e83e40ecf70f4a91190e", 
      "output": 0, 
      "value": 99018, 
      "status": "confirmed"
    }, 
    {
      "txid": "4584e6674185f678496f526cc8c6c8cf02aaf366d35c171b5a8c629ca5f8d13b", 
      "output": 0, 
      "value": 98403, 
      "address": "bc1qvjmg5as0f3dwnhneuf8ydqu595t8tsurpy7h0s", 
      "status": "confirmed"
    }
  ], 
  "channels": [
    {
      "peer_id": "02d246c519845e7b23b02684d64ca23b750958e0307f9519849ee2535e3637999a", 
      "short_channel_id": "517209:1104:1", 
      "channel_sat": 100000, 
      "channel_total_sat": 100000, 
      "funding_txid": "c9c29c3eb806ae22f00ad4bf0df8e3a61ddf589c73e843e5672793e8d6a486a7"
    }
  ]
}
```

**Comment by conscott** [comment]
Your funds are still there. On-chain funds available are listed in the `outputs` list you have posted above. 

If you inspect one of those `txid`, like [4584e6674185f678496f526cc8c6c8cf02aaf366d35c171b5a8c629ca5f8d13b](https://blockstream.info/tx/4584e6674185f678496f526cc8c6c8cf02aaf366d35c171b5a8c629ca5f8d13b) You can see the channel close tx, with a 100000 sat input (previous funding tx) and an output back to you at bc1qvjmg5as0f3dwnhneuf8ydqu595t8tsurpy7h0s, with a value 98403 sat, the difference being the tx fee of 1597 sat (about $0.06)

You can either reopen channels with these funds, or transfer them to another wallet with
```
lightning-cli withdrawl <destination btc address>  <amount satoshis>
```

**Comment by conscott** [comment]
Was the confusion here that you expected your bitcoin wallet to show a balance after the lightning channels closed?

c-lightning does not use the bitcoind wallet; it acts as an independent wallet, unlike some other lightning software which will interact directly with the bitcoin wallet.

**Comment by lorenzoPrimi** [comment]
Thanks @conscott for the answer. I'm here to learn and understand.
Yeah I was expecting them to be in my bitcoin-cli actually.
Two more questions:
How much can I withdraw? 
Why `listfunds` shows a channel while on 1ml it says closed?

**Comment by conscott** [comment]
You should be able to withdrawal up to... 99515 + 99018 + 98403 = 296936 sat - basically whatever is the sum of your outputs 

As for the channel listed, the only way to really know the channel state is to do a `lightning-cli listpeers` and look for the `channel.state` variable, which shows if it is pending/active/closing/closed. It's possible there was a non-cooperative close / some other case and you are just waiting for the close tx to be valid, or it could really be active. 1ML is not always accurate and typically takes a while to update channel state changes, so I would not consider it your source of truth. 

Was [this tx](64da676e85bccfc4f4cedea7d5e7d4184c5ac34d249ec92580d26a175d3073e5) you closing the channel?

**Comment by conscott** [comment]
Hope that helps!

**Comment by lorenzoPrimi** [comment]
Thank you very much, you have been really helpful to help me understand how lightning works!
