### ISSUE TITLE
Cant pay a LN invoice

### ISSUE THREAD

**Issue by Relaxo143** [ElementsProject/lightning#2282]
I tried paying an invoice with "lightning-cli pay <invoice>", but I get this strange error: 
{ "code" : -32601, "message" : "Unknown command '\"pay\"'" } 
It says theres no such command as pay?! What do I do?
getinfo output: 
```{
  "id": "02c919d62ab30b1a91c0c7c687d6d1a4665842ba2d8bea6a68c3dda189d0b8e0cb",
  "alias": "Pikachu Lightning Node",
  "color": "000000",
  "num_peers": 3,
  "num_pending_channels": 1,
  "num_active_channels": 2,
  "num_inactive_channels": 0,
  "address": [
    {
      "type": "ipv4",
      "address": "78.130.161.76",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv4",
      "address": "0.0.0.0",
      "port": 9735
    }
  ],
  "version": "v0.6.3rc1-88-g82ff580",
  "blockheight": 559315,
  "network": "bitcoin",
  "msatoshi_fees_collected": 0
}
```

**Comment by martijnbolt** [comment]
I have compiled a fresh install of lightingd today ( "version": "v0.7.0-278-gf82e779" ) and seem to have no pay command as well. Any tips?

**Comment by cdecker** [comment]
@martijnbolt please open a new issue or ask on https://bitcoin.stackexchange.com/, I nearly missed your comment in the flood of notifications, and closed issues are not shown by default in the GH interface :wink: 

Could you share the output of `lightning-cli listconfigs`? That'll tell us if `lightningd` picks up the `pay` plugin. Also do you have any particular command line options or config files that might be changing the defaults?

**Comment by martijnbolt** [comment]
thanks. see https://github.com/ElementsProject/lightning/issues/2607
