### ISSUE TITLE
v0.7.0 needs a name and @wythe doesn't read his email

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#2284]
### Issue and Steps to Reproduce

I pinged @wythe to name the 0.6.3 release but no reply in time.  Trying again for the 0.7 release, perhaps via GitHub...

**Comment by wythe** [comment]
Ok I'm here. Give me a sec to think of something!

**Comment by wythe** [comment]
"I came here to program lightning and all I did was parse JSON."

**Comment by wythe** [comment]
Or: "What's a rebase?"

**Comment by wythe** [comment]
Or "I wonder if ZmnSCPxj is really Satoshi".

Just some thoughts I've had.  Please take your pick. And thank you for the honor.
