### ISSUE TITLE
Can't compile from source (install: cannot stat 'plugins/pay')

### ISSUE THREAD

**Issue by sr-gi** [ElementsProject/lightning#2288]
I've been unable to compile from the source on master branch since a couple of days ago, getting the following error:

``
[ -z "plugins/pay" ] || install plugins/pay /usr/local/libexec/c-lightning/plugins
install: cannot stat 'plugins/pay': No such file or directory 
make: *** [install-program] Error 1  
rm external/libwally-core/src/secp256k1/libsecp256k1.la 
``

Removing `plugins/pay` from Makefile solves the issue (that line was added 4 days ago in 4a45caae32194e88e8e806d12230e66be55fd2b7) 

https://github.com/ElementsProject/lightning/blob/4a45caae32194e88e8e806d12230e66be55fd2b7/Makefile#L476

But to be honest I'm not familiar enough with the code yet to know the implications of doing so.

Any thoughts?

**Comment by cdecker** [comment]
Could there be a missing dependency on `plugins/pay` for the `install` target @rustyrussell?

@sr-gi are you calling `make install` directly or are you calling `make` followed by `make install`? `make` should pick up all the binaries and compile them, so running them one after the other should get you going again, until we fix the Makefile.

**Comment by sr-gi** [comment]
I was calling `make install` directly indeed, running `make` beforehand does the trick.

Thanks @cdecker!

**Comment by wythe** [comment]
Ah, now I understand why I also saw the error but then it went away.
