### ISSUE TITLE
close puts it in CHANNELD_SHUTTING_DOWN forever

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#229]
maybe it is related to restored channels, but I tried closing the channel in hopes it would get things back to a happy state.

Unfortunately, it just put the peer into CHANNELD_SHUTTING_DOWN forever

stop and resuming has it still in CHANNELD_SHUTTING_DOWN with no sign of any activity

**Comment by cdecker** [comment]
This should be addressed by the `onchaind` implementation which was missing at the time of filing this issue, could you test this again?

**Comment by jl777** [comment]
ok, will do

**Comment by jl777** [comment]
I dont see this anymore, will close it

**Comment by cdecker** [comment]
Thanks for thesting this again @jl777

**Comment by 2pac1** [comment]
I tried to close two channels with CLOSE command and when I run it for second time I see:
"Peer is in state CHANNELD_SHUTTING_DOWN"

**Comment by doffing81** [comment]
Same as @2pac1 here. Stuck in that state and constantly logging for those peers...

> TRACE: Failed connected out for {peer id}, will try again

Does closing a channel in this way broadcast the final state to the Blockchain?

**Comment by AndiMacTen** [comment]
Same as @doffing81 and @2pac1. My both channels are in CHANNELD_SHUTTING_DOWN for over a week now. I get a lot of 
> TRACE: Failed connected out for {peer id}, will try again 

messages but only for one of the connected peers.
``` 
cli/lightning-cli listpeers
{ "peers" :
        [
                { "id" : "035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8", "connected" : true, "netaddr" :
                        [ "78.63.23.25:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_SHUTTING_DOWN", "owner" : "lightning_channeld", "short_channel_id" : "504886:2396:0", "funding_txid" : "fde96ea8ca03c1f3afaf7ce746e968970997f5a06d37204261bc8c99e689748a", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },
                { "id" : "036fb07937b7282bedcbb017d05b75a435eb4b0fb7b2615f0d47e4ab0183182104", "connected" : false, "channels" :
                        [
                                { "state" : "CHANNELD_SHUTTING_DOWN", "short_channel_id" : "504881:2063:0", "funding_txid" : "1401dad826dad376bf45b0bd50cadb95bc0ce1eefec114365e664bbdb348fdba", "msatoshi_to_us" : 175000000, "msatoshi_total" : 175000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }
```
Am running the latest master.
Is this the right place to address this issue or open a new one?
