### ISSUE TITLE
Alpine docker images not building anymore on Docker Hub

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#2309]
It appears that we somehow broke the alpine docker images on Docker hub used to serve `elementsproject / lightningd`.

The build complains about `git` not being present, despite it being installed just a few lines above:

```
Makefile:7: *** "ERROR: git is required for generating version information". Stop.
```

This is during the call to `make`, and happens during the version extraction in the `Makefile`:

https://github.com/ElementsProject/lightning/blob/0da40540453712b836b2a2a5383c8625137964c7/Makefile#L3-L4

I have tried to build the image at that point, but was unable to reproduce the issue, and it builds correctly on my machine.

Maybe @NicolasDorier has an idea on what might have gone wrong?

**Comment by cdecker** [comment]
Turns out this is an issue with the [`COPY . .` line in the `Dockerfile`](https://github.com/ElementsProject/lightning/blob/0da40540453712b836b2a2a5383c8625137964c7/Dockerfile#L59). During clone `git` will retain a reference to the full clone path, which after the copy from host to guest, points to an invalid location. The `git describe` and `git submodule init` processes will attempt to use that reference and fall on their nose.

I have a fix that just clones after the `COPY` and it seems to be working correctly.

**Comment by NicolasDorier** [comment]
I am behind master on my branch, my makefile show

```
VERSION=$(shell git describe --always --dirty=-modded --abbrev=7)
```

And it was never an issue. Will try to replicate on master.

**Comment by cdecker** [comment]
No worries @NicolasDorier, I fixed it in PR #2311, by adding a clean clone step inbetween.

**Comment by NicolasDorier** [comment]
Will test, strange why was it working before

**Comment by cdecker** [comment]
It was working because we didn't fail on git failures for submodules before, but about 20 days ago the `$VERSION` was made mandatory.
