### ISSUE TITLE
Allow setting feerate on per-channel basis

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#2316]
As requested by ctrlbreak on IRC: documenting here.

- [ ] Add db fields for per-channel feebase + ppm
- [ ] Put these fields into struct channel
- [ ] Use the fields in forward_htlc instead of global values
- [ ] Show fields in listchannels
- [ ] Plumb db fields through to gossipd for advertising.
- [ ] Provide API eg. `setchannelfee <short-chanid-or-peerid> <base> <ppm>`
- [ ] Create tests, CHANGELOG.md, man page.
- [ ] Dance a happy dance.

**Comment by renepickhardt** [comment]
also another question: might it be reasonable to implement this as a plugin. In this way more hooks and events that people would eventually want to expose would have to be implemented in c-lightning

**Comment by m-schmoock** [comment]
Hey, I think I can have a look at this. But it would be, besides isolating issue https://github.com/ElementsProject/lightning/pull/2321 , my first contribution here, so please expect me being exeptionally fast :D

**Comment by m-schmoock** [comment]
Started working on it: 7c5cdee682ff4a4bdc2d6ce0f590ae32e5cf18aa

**Comment by m-schmoock** [comment]
@rustyrussell can you explain what "ppm" means in this context?

**Comment by niftynei** [comment]
@m-schmoock i believe it means 'part per millionth' -- the total fee is a 'percent' of the amount routed, in millionths plus the base

**Comment by m-schmoock** [comment]
Can we have a branch for this where a nobody like me is able to push?

**Comment by m-schmoock** [comment]
Here is my workspace: https://github.com/ElementsProject/lightning/compare/master...m-schmoock:feerate-per-channel

I will add the API function `setchannelfee` tomorrow.

**Comment by m-schmoock** [comment]
Hey, two quick questions: 

- [lightningd/lightningd.h line 43](https://github.com/ElementsProject/lightning/blob/master/lightningd/lightningd.h#L43) Is there a reason why the config.fee_per_satoshi value is a signed integer? 
- [lightningd/lightningd.h line 495ff](https://github.com/ElementsProject/lightning/blob/master/lightningd/peer_htlcs.c#L495) the comment tells that the fee is calculated using `fee_proportional_millionths / 1000000` but later in the code its `fee_per_satoshi / 1000000`. Is  ppm == fee_per_satoshi or is the comment misleading?

**Comment by cdecker** [comment]
> * [lightningd/lightningd.h line 43](https://github.com/ElementsProject/lightning/blob/master/lightningd/lightningd.h#L43) Is there a reason why the config.fee_per_satoshi value is a signed integer?

That's probably a left-over from the old idea of allowing negative fees. We abandoned quite a while ago.

> * [lightningd/lightningd.h line 495ff](https://github.com/ElementsProject/lightning/blob/master/lightningd/peer_htlcs.c#L495) the comment tells that the fee is calculated using `fee_proportional_millionths / 1000000` but later in the code its `fee_per_satoshi / 1000000`. Is  ppm == fee_per_satoshi or is the comment misleading?

Proportional fee and `fee_per_satoshi` are the same (proportional refers to the number of satoshis transferred). Just a bit of inconsistent naming :wink

**Comment by m-schmoock** [comment]
Thx. Addressed the first issue by PR https://github.com/ElementsProject/lightning/pull/2336

**Comment by m-schmoock** [comment]
Almost everything done: https://github.com/ElementsProject/lightning/pull/2342
Need a review and feedback

**Comment by m-schmoock** [comment]
https://github.com/ElementsProject/lightning/pull/2342 is merged. This can be closed
