### ISSUE TITLE
Explorers list channel as open, while my client doesn't show the channel.

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#2317]
As stated in the title, explorers list a channel opened 4 months ago as 'open', while the output of my 'listfunds' only shows 2 recent channels. I'd think it would show as closed, by now.

**Comment by cdecker** [comment]
That's probably the explorers not correctly pruning their view of the network. Since there is no explicit "this channel is now closed" message they have to passively notice that they're no longer open and mark them as closed.

Which explorer is it? And have you tried contacting them?

**Comment by Coinomatron** [comment]
Explorers are https://explore.casa and https://lightblock.me, haven't contacted them.
Do you know of any that have the full network history?

**Comment by lndnode** [comment]
> As stated in the title, explorers list a channel opened 4 months ago as 'open', while the output of my 'listfunds' only shows 2 recent channels. I'd think it would show as closed, by now.

Hi there,

Detecting the correct state of the channel is quite a challenging task and we are always working to improve it. Could you please send your channel id over?  So we could take a look. Might be that your node is stuck due to some internal issues, like insufficient free space etc. and therefore not sending the updates to the network as it is supposed to.

Regards.

**Comment by Coinomatron** [comment]
https://1ml.com/node/021f0f2a5b46871b23f690a5be893f5b3ec37cf5a0fd8b89872234e984df35ea32/channels

Output of current listfunds: 

{
  "outputs": [
    {
      "txid": "1f22d731164c81b04ad829dc7116333fd40fc3ac6037cdd123e53b44cf0e4743", 
      "output": 0, 
      "value": 49536, 
      "address": "bc1qvn867ur6vxffhyycxt0kc8w5f8cz3srpkpa762", 
      "status": "confirmed"
    }, 
    {
      "txid": "0b8f77d20480111a289c681fa950bf7155bdcd590025240823de6b5cea802270", 
      "output": 0, 
      "value": 62656, 
      "address": "bc1qnkgheucfstrq8wj9la4x86qnu4yfqnxp0sn0p2", 
      "status": "confirmed"
    }, 
    {
      "txid": "2dd090c61a89919cae1928e0f47361af1ac1bbc968356a0b514f562bc7858df4", 
      "output": 0, 
      "value": 4705, 
      "address": "bc1qnlefmftv35u5jpqwszawljccrv0f2yf0wtg9zn", 
      "status": "confirmed"
    }
  ], 
  "channels": [
    {
      "peer_id": "03fb822818be083e0a954db85257a2911a3d55458b8c1ea4124b157e865a836d12", 
      "short_channel_id": "560798x1455x0", 
      "channel_sat": 44905, 
      "channel_total_sat": 60000, 
      "funding_txid": "a24cfde7264411da1bd9b30e224ecc0e34ea040cc5023eade6984fea4d8defb6"
    }, 
    {
      "peer_id": "0260fab633066ed7b1d9b9b8a0fac87e1579d1709e874d28a0d171a1f5c43bb877", 
      "short_channel_id": "561531x1989x1", 
      "channel_sat": 67497, 
      "channel_total_sat": 69999, 
      "funding_txid": "0b8f77d20480111a289c681fa950bf7155bdcd590025240823de6b5cea802270"
    }
  ]
}
