### ISSUE TITLE
Add some slack to the timeouts in order to avoid failure due to block while forwarding

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#233]
There is an edge case when doing a sendpay. When a block comes in after the sending node calculates the locktime but before the receiving node does, then it triggers an error as there is no leeway at all in the locktime checks.

This in and of itself wouldnt be fatal as you could just do another sendpay, however the problem is that once a sendpay fails in this way, it seems to get stuck with a "still in progress" result after reestablishing the channel.

Of course, there is nothing progressing anymore, so the still in progress state is permanent. The only workaround I have found so far is to clear out the sql DB.

I think if a sendpay is not complete and there is no way to complete it, it should just be closed out (however that is best done) so another sendpay can be processed.

**Comment by cdecker** [comment]
Thanks for the report, but a more descriptive title might have helped. We can add some slack to the timeouts, but the problem may still persist over restarts in case of two or more blocks in quick succession.
