### ISSUE TITLE
how to eliminate "hop_hints" from a generated invoice

### ISSUE THREAD

**Issue by bidelakbari** [ElementsProject/lightning#2338]
I tried to generate a twitter friendly invoice the other day (less than 280 characters) but due to the "hop_hints" the char count was more than that. my question is how I can eliminate the hop_hints from the invoice hash? I read the man entry for "invoice" command but it didn't have such option

`getinfo` output
<pre><code>v0.6.3</code></pre>

**Comment by rustyrussell** [comment]
Hey, Ithanks for the bug report!

I never thought of this!  Hmm, there's a developer-only option in master called `dev-routes` which you can use to override the normal heuristics, eg. 'dev-routes=[]'.  But I never thought of a normal option to do this...

Yech, you could restart with `--offline`, generate the invoice, then restart without :(

**Comment by bidelakbari** [comment]
Great, thanks for the <code>--offline</code> tip. didn't know it is possible to start offline.
