### ISSUE TITLE
log-level in config file results in "unknown log level"

### ISSUE THREAD

**Issue by mloop1** [ElementsProject/lightning#2344]
### Issue and Steps to Reproduce
when adding the line ```log-level=debug``` or ```=info``` in the config file I get the following error when starting the daemon:
```lightningd --daemon```   
```lightning config file line 5: log-level: unknown log level```

### `getinfo` output
last week commit

**Comment by rustyrussell** [comment]
Huh... is there whitespace on the end of the line maybe?  Or is it literally:

```
log-level=debug
```

**Comment by mloop1** [comment]
it seems that was it.... thanks
