### ISSUE TITLE
Add bitcoin-cli -conf=... parameter to lightningd

### ISSUE THREAD

**Issue by analogic** [ElementsProject/lightning#235]
(or better add parameter that can add whatever one wants to forward to bitcoin-cli)

**Comment by cdecker** [comment]
May I know what you would like to use this for? You can already do this using the `--bitcoin-dir` flag. That will tell `bitcoin-cli` where to look for the config. You can simply create a copy of your config in a separate directory, edit it as you please and then point `lightningd` to it :wink:

**Comment by analogic** [comment]
I want use it at my own docker dev image - see https://github.com/analogic/bitcoin-regnet where I have configuration and data somewhere else. Right now as workaround I've used bitcoin-cli "wrapped" with shell script, but it is not clean solution. 

(still I am not able to run two c-lightning nodes at one system, is it possible right now?)

**Comment by rustyrussell** [comment]
analogic <notifications@github.com> writes:
> I want use it at my own docker dev image - see https://github.com/analogic/bitcoin-regnet where I have configuration and data somewhere else. Right now as workaround I've used bitcoin-cli "wrapped" with shell script, but it is not clean solution. 
>
> (still I am not able to run two c-lightning nodes at one system, is it possible right now?)

The tests do this, so yes.  You will need a different --port for one of
them though.

Cheers,
Rusty.

**Comment by cdecker** [comment]
Seems setting a `--lightning-dir` is exactly what you're looking for. I'll close this, but feel free to reopen if it doesn't work :-)
