### ISSUE TITLE
Channel stuck: CHANNELD_AWAITING_LOCKIN

### ISSUE THREAD

**Issue by billygarrison** [ElementsProject/lightning#2352]
### Issue and Steps to Reproduce
I had two channel opening transactions stuck in the mempool for the past couple days. When the mempool cleared, both transactions got confirmed in the same block. Only one of the channels actually opened though, the other says the state is "CHANNELD_AWAITING_LOCKIN".

The funding_txid for the channel has [32 confirmations](https://blockstream.info/tx/adb0e33d88aa2c5cb6168ea16cd46f492ee5387f3b4d295bcb2ec09588e6650e) at the time of this post.

`connect` and `ping` both work with the peer_id. And using 1ml.com I can see the peer has had one channel opened since my funding_tx was confirmed.

### `listpeers` output for that peer
```
      "channels": [
        {
          "state": "CHANNELD_AWAITING_LOCKIN",
          "scratch_txid": "04f5e9c4dcd919ac3bfd1571cba6901f5f61c1e5190543c215cc013884899509",
          "owner": "lightning_channeld",
          "short_channel_id": "562892:912:1",
          "channel_id": "0e65e68895c02ecb5b294d3b7f38e52e496fd46ca18e16b65c2caa883de3b0ac",
          "funding_txid": "adb0e33d88aa2c5cb6168ea16cd46f492ee5387f3b4d295bcb2ec09588e6650e",
          "private": false,
          "msatoshi_to_us": 840000000,
          "msatoshi_to_us_min": 840000000,
          "msatoshi_to_us_max": 840000000,
          "msatoshi_total": 840000000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709551615,
          "their_channel_reserve_satoshis": 8400,
          "our_channel_reserve_satoshis": 8400,
          "spendable_msatoshi": 831600000,
          "htlc_minimum_msat": 0,
          "their_to_self_delay": 144,
          "our_to_self_delay": 144,
          "max_accepted_htlcs": 483,
          "status": [
            "CHANNELD_AWAITING_LOCKIN:We've confirmed funding, they haven't yet."
          ],
          "in_payments_offered": 0,
          "in_msatoshi_offered": 0,
          "in_payments_fulfilled": 0,
          "in_msatoshi_fulfilled": 0,
          "out_payments_offered": 0,
          "out_msatoshi_offered": 0,
          "out_payments_fulfilled": 0,
          "out_msatoshi_fulfilled": 0,
          "htlcs": [
          ]
        }
      ]
```

### `listfunds` output for that channel
```
    {
      "peer_id": "021607cfce19a4c5e7e6e738663dfafbbbac262e4ff76c2c9b30dbeefc35c00643",
      "short_channel_id": "562892:912:1",
      "channel_sat": 840000,
      "channel_total_sat": 840000,
      "funding_txid": "adb0e33d88aa2c5cb6168ea16cd46f492ee5387f3b4d295bcb2ec09588e6650e"
    },
```

### `getinfo` output
```
{
  "id": "02843833374b6c42daa4b780df2066a9985cb8cf97bc4566dd63cf693d32cbf7b5",
  "alias": "BillyGarrison",
  "color": "009900",
  "num_peers": 10,
  "num_pending_channels": 1,
  "num_active_channels": 9,
  "num_inactive_channels": 0,
  "address": [
    {
      "type": "ipv4",
      "address": "47.55.123.202",
      "port": 9735
    }
  ],
  "binding": [
  ],
  "version": "v0.6.3",
  "blockheight": 562923,
  "network": "bitcoin",
  "msatoshi_fees_collected": 3375
}
```

I haven't tried to do a cooperative channel close yet. Waiting to see if there's anything I can do before closing the channel.

Also I checked out the lightningd database. The channel_configs record looks normal for that channel. In the channels table, `funding_locked_remote` is 0 (all other channels are 1). `local_feerate_per_kw` is 253 for that channel and 3700-7900 for all others.

PS: I understand that it isn't safe to query the database while lightningd is running because of file locking, but is it safe to copy the database and then query the copy of it, all while lightningd is running?

**Comment by billygarrison** [comment]
Update: I restarted lightningd and now `listpeers` gives:
```
          "status": [
            "CHANNELD_AWAITING_LOCKIN:Sent reestablish, waiting for theirs"
          ],
```

Other than the one channel that the peer opened after my funding tx was confirmed, there has been no channels added and many dropped from them (according to 1ml.com).

`ping` is no longer working, but `connect` still returns the id (perhaps because I've previously connected so it's just grabbing the id from the DB?)

Anyway, I'm going to unilaterally close the channel so feel free to close this if you don't have any questions/comments.

**Comment by cdecker** [comment]
There are a couple of scenarios in which a channel may get stuck in the `CHANNELD_AWAITING_LOCKIN` state:

 - The funding transaction hasn't confirmed yet, this is clearly not the case for you
 - The peer may not be connected, in which case we wait for the `funding_locked` message from them. Your node is saying it sent a reestablish message, so at some point it was connected
 - The peer has forgotten about the channel, because it took too long to confirm. This might be the case here, and the reestablish should have caused the peer to disconnect you. In this case a unilateral close is your only option.
 - The peer may be lagging behind the blockchain head, and simply not have seen the funding confirm. This is unlikely, as I understand it the channel has been in this state for quite a while.

So I think you might need to go down the `close` or even force `close` route.

> PS: I understand that it isn't safe to query the database while lightningd is running because of file locking, but is it safe to copy the database and then query the copy of it, all while lightningd is running?

Copying and querying the copy is definitely safe. We're doing that in tests as well. Querying the live database may crash the node, but since we commit to DB before doing any dangerous operations (exchanging signatures, preimages, ...) it should always recover from these crashes without further issues.

**Comment by billygarrison** [comment]
Thanks a lot for your insights @cdecker. I decided to force close the channel.

Regarding copying/querying the db, pardon my alarmist wording! It's great to know it is safe to do so.

Thanks again for your help, closing this issue now.

**Comment by cdecker** [comment]
> Regarding copying/querying the db, pardon my alarmist wording! It's great to know it is safe to do so.

Your absolutely right to make sure :+1:

**Comment by tinspin** [comment]
I'm getting "Peer transient failure in CHANNELD_AWAITING_LOCKIN: channeld: Owning subdaemon channeld died (62208)"!

What does this mean?
