### ISSUE TITLE
Getting "No route to host." while my system can route to host

### ISSUE THREAD

**Issue by askmike** [ElementsProject/lightning#2370]
### Issue and Steps to Reproduce

I'm trying to connect to a big node by running:

    lightning/cli/lightning-cli connect [id] [ip] [non standard port]

Which errors with:

    Connection establishment: No route to host

This seems strange as my system can ping that IP just fine:

    root@zap:~# ping [ip]
    PING [ip] ([ip]) 56(84) bytes of data.
    64 bytes from [ip]: icmp_seq=1 ttl=46 time=153 ms
    64 bytes from [ip]: icmp_seq=2 ttl=46 time=152 ms
    64 bytes from [ip]: icmp_seq=3 ttl=46 time=152 ms

### `getinfo` output

    "version": "v0.6.3rc1-152-gb99293f"

**Comment by m-schmoock** [comment]
@askmike Do you get the same if you use   `lightning-cli connect  id@host:port`   or    `lightning-cli connect id host port`. Also do you have a hostname you can try instead of IP ?

**Comment by askmike** [comment]
> Do you get the same if you use `lightning-cli connect id@host:port` or `lightning-cli connect id host port`.

I didn't know the first syntax was supported, but yes same error.

> Also do you have a hostname you can try instead of IP or the other way around?

I can't find any domain hooked up to that IP. I think I can safely disclose the node I'm trying to connect to (privacy wise), it's this one: https://1ml.com/node/03d9a5341083d9ae16fd4f6fc117ed8a7f25689c02d0e3f4a955d45105e5ba9c63

**Comment by m-schmoock** [comment]
I can connect to that host using this:

```
lightning-cli connect 03d9a5341083d9ae16fd4f6fc117ed8a7f25689c02d0e3f4a955d45105e5ba9c63@107.181.189.76:40829
{
  "id": "03d9a5341083d9ae16fd4f6fc117ed8a7f25689c02d0e3f4a955d45105e5ba9c63"
}
```

Just to be sure: are you trying the ping from the same machine lightning is on? 
Also, is lightningd running also on root? This is not recommended and required in any way...

**Comment by cdecker** [comment]
You can eliminate `lightningd` by calling `telnet [ip] [port]` to see if TCP connections can be established.

**Comment by askmike** [comment]
I'm pinging from the same machine, there is a firewall but my node has multiple connection with peers as well as channels open. I'm not using Docker or anything like that. Here are logs of trying to connect & ping:

    root@zap:~# lightning/cli/lightning-cli connect  03d9a5341083d9ae16fd4f6fc117ed8a7f25689c02d0e3f4a955d45105e5ba9c63@107.181.189.76:40829
    { "code" : -1, "message" : "107.181.189.76:40829: Connection establishment: No route to host. 107.181.189.76:40829: Connection establishment: No route to host. " }
    root@zap:~# ping 107.181.189.76
    PING 107.181.189.76 (107.181.189.76) 56(84) bytes of data.
    64 bytes from 107.181.189.76: icmp_seq=1 ttl=57 time=142 ms
    64 bytes from 107.181.189.76: icmp_seq=2 ttl=57 time=142 ms

**Comment by kristapsk** [comment]
You will get "no route to host" if the port is closed, even if the host responds to ICMP ping. That's not something c-lightning specific. You can test is this the problem by using telnet, as @cdecker suggested.

**Comment by askmike** [comment]
@cdecker 

telnet errors with the same error:

    root@zap:~# telnet 172.83.40.112 40829
    Trying 172.83.40.112...
    telnet: Unable to connect to remote host: No route to host

While curl is finding the host just fine:

    root@zap:~# curl 172.83.40.112
    curl: (52) Empty reply from server

**Comment by m-schmoock** [comment]
Quite sure its a local firewall issue at your side. See this for details: https://unix.stackexchange.com/questions/353452/no-route-to-host-with-nc-but-can-ping

**Comment by m-schmoock** [comment]
'Your "no route to host" while the machine is ping-able is the sign of a firewall that denies you access politely (i.e. with an ICMP message rather than just DROPping).'
