### ISSUE TITLE
Increase TCP backlog

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#2378]
In [this line](https://github.com/ElementsProject/lightning/blob/d96564ce3ee4d497eed41b0adb11de8c3cd03033/connectd/connectd.c#L1167), can we increase from 5 to 128?

Not having a larger backlog causes 
```
[Wed Feb 20 11:18:44 2019] TCP: request_sock_TCP: Possible SYN flooding on port 9735. Sending cookies.  Check SNMP counters.
[Thu Feb 21 15:58:59 2019] TCP: request_sock_TCP: Possible SYN flooding on port 9735. Sending cookies.  Check SNMP counters.

```

I modified that line and i stopped getting SYN flooding errors in my kernel log.

[RedHat covers this](https://access.redhat.com/solutions/30453#Valid) pretty well, if you want to read about it.

**Comment by cdecker** [comment]
Paging networking expert @rustyrussell  :-)

**Comment by m-schmoock** [comment]
@thestick613 maybe describe your setup when this occurs, are you stress testing the daemon or something?

Some things I noticed:

1. Currently `5` is a magic number in the code which should be defined somewhere else.
2. The value `5` seems small but okay for a lightning server. If you get more parallel connections (at the same time) and your connectd is not able to process them intime, there is something else fishy but not your backlog value.
3. Having a application userspace backlog of 128 seems too much, as we are not talking about a kernel setting, nor a daemon that is designed in any way to have that many parallel connection attempts under normal conditions. This is not a HTTP server ;)

**Comment by thestick613** [comment]
If you have a larger number of channels, a restart of lightningd can trigger this issue, because everyone else wants to talk with you at that point. I'm running it on a smaller box, and the CPU isn't able to keep up with everything at once. The 5 means that 5 is the maximum number of incoming connections towards that process that haven't been yet accepted.

[Bitcoind is a lot smarter](https://github.com/bitcoin/bitcoin/blob/b9b26d9c3615d15669ae0a049c1dede39a9e59a9/src/net.cpp#L2046), it reads the maximum number of connections from somewhere.

**Comment by m-schmoock** [comment]
Right, `SOMAXCONN` is defined in `sys/socket.h` which includes `bits/socket.h`. It is valid POSIX standard, so other than reducing maximum load incase of a ddos attack, there is no reason to go lower than SOMAXCONN value, right?

**Comment by thestick613** [comment]
You can actually increase it or decrease it on Linux like this:
`sysctl net.core.somaxconn=65536`
