### ISSUE TITLE
Invalid chain when opening a new channel

### ISSUE THREAD

**Issue by fedsten** [ElementsProject/lightning#2379]
I have used c-lightning in mainnet a lot last summer, opening few channels and successfully doing several transactions, but after few months of inactivity I found all my channels to be closed. I therefore attempted to open a new channel, encountering however the following error:

`
{ "code" : -1, "message" : "They sent error channel 22ae543309f5b1266cf615a1f54beb9ba1c8157ed26e7514688e71f1c1fea0f1: invalid chainHash (local=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000 remote=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000)" }`

That when opening with other nodes, it is sometime displayed as:

`{ "code" : -1, "message" : "They sent error channel 98189126177bf0460d7b3c7da2583a934ca03597e4f15b48f784f4102a60bcb0: Unknown chain=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f. Supported chain=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943" }`

I imagine that the difference depends on the the software used by the node I am trying to connect.

From the hashes shown, it seems that my node is in testnet mode instead of mainnet, however I have double checked and made sure that everything is in mainnet mode. In particular:

- Bitcoind is running on mainnet, and from `getblockchaininfo` shows  "chain": "main"

- The `config.save` file in the `.lightning` folder has the  `network=bitcoin` flag set

- When I launch c-lightning, I use the flag --network=bitcoin

- When c-lightning starts, it adds mainnet blocks

- From `getinfo`, I get the following:
```
  "version": "v0.6.3rc1-7-g6b5db38", 
  "blockheight": 564053, 
  "network": "bitcoin"
```

Moreover, few months ago the very same node was working on mainnet without any problem. At this point, I am really failing to understand why when trying to fund a channel I get the error message suggesting that the supported chain is the testnet. Is there some other configuration I may have to fix?

**Comment by cdecker** [comment]
Well the error message pretty much says all there is to know:
 - You're running on bitcoin mainnet (`000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f` is the genesis block for mainnet)
 - They are running on bitcoin testnet3 (`000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943` is the genesis block for testnet3)

Since we don't support multiple chains in a single instance you won't be able to establish a channel with that peer.

**Comment by fedsten** [comment]
My bad, I got confused by the way the error message was expressed and by the fact that I was convinced the nodes I was trying to connect to were mainnet nodes

**Comment by cdecker** [comment]
No problem, the error messages require some mind twisting :smiley:
