### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by stevenroose** [ElementsProject/lightning#2401]
At least one of the links on the README to the API documentation is broken:
https://github.com/ElementsProject/lightning/blob/master/doc/lightning-listpayments.7.txt

The `listpayments` call doesn't exist. It should be `listsendpays` I think.

**Comment by stevenroose** [comment]
Or listpayments. They both exist so one of them should probably be added.

**Comment by rustyrussell** [comment]
Thanks, this was me, I'll fix the link!
