### ISSUE TITLE
Cannot complete build

### ISSUE THREAD

**Issue by mcduck76** [ElementsProject/lightning#2404]
https://github.com/ElementsProject/lightning/blob/1dcc4823507df177bf11ca60ab7da988205139b1/common/amount.h#L35

Since this change build stops with error:

In file included from bitcoin/chainparams.h:7:0,
                 from bitcoin/chainparams.c:1:
./common/amount.h:36:11: error: initializer element is not constant
  ((struct amount_sat){(constant) + AMOUNT_MUST_BE_CONST(constant)})
           ^
bitcoin/chainparams.c:20:21: note: in expansion of macro ‘AMOUNT_SAT’
      .max_funding = AMOUNT_SAT((1 << 24) - 1),
                     ^
./common/amount.h:36:11: error: (near initialization for ‘networks[0].max_funding’)
  ((struct amount_sat){(constant) + AMOUNT_MUST_BE_CONST(constant)})
           ^
bitcoin/chainparams.c:20:21: note: in expansion of macro ‘AMOUNT_SAT’
      .max_funding = AMOUNT_SAT((1 << 24) - 1),

The build environment is CentOS 7.6, it used to be fine until this change.

**Comment by rustyrussell** [comment]
I tried googling, gcc version on Centos 7.6 must be really old?  Seriously, 4.8.5?  We're on 8.2 here!

Let me see how bad the damage is... :(

**Comment by mcduck76** [comment]
Thank you for the response, I was able to build the project with gcc 8.3.
