### ISSUE TITLE
Store the `announcement_signature` in the database to work around some impls not sending it on reconnect

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#2409]
Proposed by @SimonVrouwe [here](https://github.com/ElementsProject/lightning/issues/1778#issuecomment-467807053).

This should reduce the number of "Waiting for their announcement signature" channels dramatically.

**Comment by trueptolemy** [comment]
If you don't hurry, I want to have a try.

**Comment by cdecker** [comment]
Absolutely, go ahead. I can't add you as assignee until you accept my collaborator invitation, but consider yourself the owner of this issue :wink:

**Comment by trueptolemy** [comment]
> Absolutely, go ahead. I can't add you as assignee until you accept my collaborator invitation, but consider yourself the owner of this issue

thank u :) !

**Comment by jb55** [comment]
yikers, I haven't looked at my lightning node in awhile and saw this:

```
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[]
[
  "CHANNELD_NORMAL:Attempting to reconnect"
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[
  "CHANNELD_NORMAL:Attempting to reconnect"
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[
  "CHANNELD_NORMAL:Attempting to reconnect"
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[
  "CHANNELD_NORMAL:Reconnected, and reestablished.",
  "CHANNELD_NORMAL:Funding transaction locked. Waiting for their announcement signatures."
]
[
  "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
]
```

**Comment by niftynei** [comment]
@jb55 i'm not sure what i'm looking at here. are these all in the same channel status, or did you edit it the output to condense it to just the statuses?

**Comment by jb55** [comment]
yeah sorry that was just `lightning-cli listpeers | jq '.peers[] | .channels[].status'`

I noticed with lnvis that all my channels were closed, and all my peers have these statuses. thought that was strange and found this and related issues.

**Comment by jb55** [comment]
Actually I'm not sure if they're "closed", but they're not in the listchannels?

**Comment by niftynei** [comment]
if they're waiting for announcement signatures they won't be 'announced' (no `channel_announcement` is sent), which means there's no record of them in gossip, which means they won't show up as available for routing in any other nodes' routemap. i believe `listchannels` pulls from gossip, which would explain why it's not there either.

**Comment by jb55** [comment]
yeah none of my channels are getting announced because of this. will try #2619
