### ISSUE TITLE
Three questions about the function "do_read_wire_header"

### ISSUE THREAD

**Issue by trueptolemy** [ElementsProject/lightning#2411]
I have three questions about  the function [`do_read_wire_header`](https://github.com/ElementsProject/lightning/blob/1dcc4823507df177bf11ca60ab7da988205139b1/wire/wire_io.c#L23)  in "wire/wire_io.c". In fact, these questions puzzled me for some days...

I write my questions as  comments NO.1, NO.2 and NO.3 between these codes:

```
static int do_read_wire_header(int fd, struct io_plan_arg *arg)
{
    ssize_t ret;

    /* NO.1 : what does the INSIDE_HEADER_BIT mean？when should I set this bit? */
    size_t len = arg->u2.s & ~INSIDE_HEADER_BIT;
    u8 *p = *(u8 **)arg->u1.vp;

    ret = read(fd, p + len, HEADER_LEN - len);
    if (ret <= 0)
        return -1;
    arg->u2.s += ret;

    /* NO.2 : and what does the HEADER_LEN mean? which situation the date length
     * equals HEADER_LEN? */
    if (arg->u2.s == INSIDE_HEADER_BIT + HEADER_LEN) {
        arg->u2.s = wirelen_to_cpu(*(wire_len_t *)p);
        if (arg->u2.s >= INSIDE_HEADER_BIT) {
            errno = E2BIG;
            return -1;
        }
 
        if (arg->u2.s != HEADER_LEN)
            tal_resize((u8 **)arg->u1.vp, arg->u2.s);

        /* NO.3 : here you changed the type of arg->u1.vp from the pointer (to array) type to the
         * array type. I also don't understand the reason:( . */
        arg->u1.vp = *(u8 **)arg->u1.vp;
    }

    return arg->u2.s == 0;
}
```

Thanks for ur explanation:)

**Comment by rustyrussell** [comment]
Wow, so this is deep in the guts of that helper.  You shouldn't call this directly!

The main problem is the infrastructure only gives us two fields to store state in.  But we want to do two reads: one to get the header (which gives us the body length), then another to get the length.  So we have two stages: in the first stage, we use u2 to hold the length we've read so far, plus INSIDE_HEADER_BIT set to mean we're still reading the header.  In the second stage, u2 holds the length we have remaining to read (and INSIDE_HEADER_BIT will not be set).

So, in do_read_wire_header:

1. The INSIDE_HEADER_BIT is set before we start reading, in io_read_wire_.
2. HEADER_LEN is the length of the header we want to read, in our case 4 bytes.
3. u1.vp originally contains the pointer to the pointer to the buffer. Once we resize it (which can move the buffer), we set vp to point directly at the buffer, which is what the normal do_read_wire path expects.

Hope that helps!

**Comment by trueptolemy** [comment]
Thank you! @rustyrussell  I like your I/O model, so I can't help myself to read more and deep...:）
