### ISSUE TITLE
on-chain balance bug

### ISSUE THREAD

**Issue by k3tan25** [ElementsProject/lightning#2414]
I have 0.7rc2 installed.
I'm getting huge amounts of unconfirmed funds randomly deposited on chain. No idea why.
when I type lightning-cli listfunds
check out what I get:
{
  "outputs": [
    {
      "txid": "a000a0957005a29aa92fd36f0c4836891a5d82e1c24d8486882febd81ae048db", 
      "output": 1, 
      "value": 94100419788125, 
      "amount_msat": "94100419788125000msat", 
      "address": "bc1qj88xh6gptm40wfhvykcy9xfaw2kmypp4jtn9lq", 
      "status": "unconfirmed"
    }, 
    {
      "txid": "01d92f478e0e5f2a2f56e0cf811bdb7c03a98d3e043dc9ecce1993d8828dab3f", 
      "output": 1, 
      "value": 94449209041607, 
      "amount_msat": "94449209041607000msat", 
      "address": "bc1qk764kd5dwesjxzq2f88962au2wyu7husyz7m6h", 
      "status": "unconfirmed"
    }
  ], 

Should I use 0.6.3 instead?

**Comment by cdecker** [comment]
Thanks for reporting this @k3tan25. Can you share the output of the following:

```bash
sqlite3 ~/.lightning/lightningd.sqlite3 "SELECT hex(prev_out_tx), prev_out_index, value, type, status, keyindex, channel_id, hex(peer_id), confirmation_height, spend_height, HEX(scriptpubkey) from outputs;"
```

I'm wondering whether this is just a display issue, or whether the database became somehow inconsistent.

**Comment by k3tan25** [comment]
hey @cdecker 
What I managed to do is execute dev-rescan-outputs and it seemed to correct itself. I ended up closing all my channels. 2 are 'closing' and have been for quite a while (overnight). The rest of the channels closed successfully and I was able to withdraw my funds out of lightning node and onto my usual wallet.
The output to your command after having done the above is as follows:

```
DB133C64F2FEFCF97645E9DD1F606F4F68D4B22850FA2F22AED3B57175D8871A|1|1041913|5|2|1|||564941|564945|00149B73FEE6BC4C4E7D25BFDB9BB6CFFF20EA59C00F
245D27F8C4FBFAA63A8A7B973DB485DC98FDDCF1DE2CB7AD662A0F49CD6E2BE1|1|738986|5|2|5|||564945|564947|0014431C8A76B0153D4493ACC8F2D9C24F71057CB0C0
99D9D4E06D33B33AC31F2459EFCC1BC7ACAB53A93EE704AED4296B2DA4969CDA|1|686059|5|2|9|||564947|564949|0014C7A7B3899DFD509136436FFB29790AD9346F64A5
22D7D80258AB062A638A74A4A9BCC37013DFDC801816EAEDE5B4CC3DFDA89B06|1|633131|5|2|17|||564949|564951|0014AE2D094D99626B4FA5C99C08EF98B500572881DF
AC195EF8E8BAF01C6C7018438EB6AC6FB7BABC3432F34BEFDE0ABF279A6D68FA|1|580203|5|2|23|||564951|564978|00148135224E1DF83DA4B44E0C6C68988ECDC7885955
452AD2CD2834B52E8AF509338F021C6CBDC0923894D1AF4B2DC87C94BF96E640|1|527915|5|2|32|||564978|564981|0014936AC28E5BC26414B0774A2A87D794CAF9EDE9FA
93082401D50DDEA8B049066EB5F8CEC26AC2EF346F8F937FCA67F37F6FFF7088|0|736|5|2|30|||564977|565013|0014300E008CEEB03BE3844C42E5F59EFD2DBF09C536
DB48E01AD8EB2F8886844DC2E1825D1A8936480C6FD32FA99AA2057095A000A0|1|94100419788125|5|2|35|||||001491CE6BE9015EEAF726EC25B042993D72ADB20435
90C622D80FAA3E72C6F1569D353EF933493D0AB8F045FE2971A90C4717E89626|1|476121|5|2|53|||564981|565013|00140B37960D7C336C17A80034A4BFB2D4E1986FC093
3FAB8D82D89319CEECC93D043E8DA9037CDB1B81CFE0562F2A5F0E8E472FD901|1|94449209041607|5|2|65|||||0014B7B55B368D766123080A49CE5D2BBC5389CF5F90
9FBDCCAD67C06D65FF29021179395B321291341104EB6C4505CE934682D5AC21|0|48305|5|2|33|||565006|565013|0014DFF39B416A84B6509C446FA569A9CF4EDDD71CA5
25C0EAE4E0F5CE78EEE36F8607500DF1B25597BE4F37A5B29287D33B6D2CBC91|0|48305|5|2|18|||565006|565013|0014CA26ED8CCF1EB39F346725A633800169A36B785E
4139AD8262FB5A15ACF4AB13C5B62E75EB40946B28E66BC6D69FCAD3E65C9078|0|48305|5|2|24|||565006|565013|0014FD803395725EDEC89767152016B1BF83FA818C81
BE790FF744B1EF69515C412CB5BB1932AA56556AE7F3BBC76842FC7E6C7B559A|0|48305|5|2|54|||565006|565013|0014AF6D452E3A825001A5FDA6E384D628F5CDBB6A48
5EC41CA6C382C2C45075FEF07681F38E378D16AC9920CAAA43237E722219E98B|0|299140|5|2|6|||565016|565078|00145032A6F8FFA4B3D2F0D4EE8B5146258EE3BC6AF4
```
I'd allude you to those same figures `94100419788125` and `94449209041607`
My node (I think) has been kicked off the network. Showing as 'inactive' on 1ml.com, despite it being online.

`lightning-cli getinfo` as follows
```
{ 
  "num_peers": 8, 
  "num_pending_channels": 0, 
  "num_active_channels": 2, 
  "num_inactive_channels": 6, 
  "address": [
    {
      "type": "ipv4",  
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv4",  
      "port": 9735
    }
  ], 
  "version": "v0.7.0rc2", 
  "blockheight": 565093, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0, 
  "fees_collected_msat": "0msat"

```}
