### ISSUE TITLE
fundchannel hanging

### ISSUE THREAD

**Issue by mloop1** [ElementsProject/lightning#2417]
Hi,
I have a fundchannel command hanging for more than 15 minutes now.
Any idea what could the reasons be?
I have 5 pending channels and looking at processes I've 5 lightning_openingd processes, 1 of which has "Waiting channel"="wait_woken"

### `getinfo` output
```{
  "num_peers": 16, 
  "num_pending_channels": 5, 
  "num_active_channels": 11, 
  "num_inactive_channels": 0, 
  "version": "v0.7.0rc1", 
  "blockheight": 565082, 
  "network": "bitcoin"
```

**Comment by rustyrussell** [comment]
Strange!  listpeers will show some more status for each peer....

**Comment by mloop1** [comment]
list peers shows the following for the peer I'm trying to fund the channel:

```    {
      "id": "02aa6d04033505013665f96f31c097233947e7cc294558f32036a2f9988567c3e1", 
      "connected": true, 
      "netaddr": [
        "144.2.114.75:9735"
      ], 
      "global_features": "", 
      "local_features": "82", 
      "globalfeatures": "", 
      "localfeatures": "82", 
      "channels": [
        {
          "state": "OPENINGD", 
          "owner": "lightning_openingd", 
          "funding": "LOCAL", 
          "msatoshi_to_us": 800000000, 
          "to_us_msat": "800000000msat", 
          "msatoshi_total": 800000000, 
          "total_msat": "800000000msat"
        }
      ]
    }, 
```

Also on a sidenote a question about pending channels... I noticed they are still pending now... is there a reason why they stay pending and do not become active?

**Comment by Toninoso** [comment]
I have experienced channel funding hanging with recently built 0.7 as well. I am on testnet and made a mistake of connecting to mainnet nodes.

Initially mainnet nodes informed me that I am on a wrong blockchain when I tried to fund the channels.

At this point I didn't know how to disconnect from those nodes and didn't want to exit the daemon. Anyone knows how to do this?

Later, as I forgot which nodes are mainnet and which are testnet, I tried to fund the channels again, expecting that blockchain error will tell me if the node is testnet.

Now the channel funding command didn't return for a long enough time that I decided to try Ctrl-C. After that the mainnet node was 'magically' not in the list of connected nodes anymore.

**Comment by cdecker** [comment]
Nodes that don't have an open channel will not get reconnected automatically, so that explains the mainnet nodes vanishing. `fundchannel` may hang for a number of reasons if the remote node does not complete the opening dance. Most likely we are simply waiting for a response to a message of ours and the remote end just stopped responding.

We might want to add timeouts to `openingd` at least at the steps in which we are not yet committed to opening the channel (haven't signed and broadcast the `funding_tx` just yet).

**Comment by conscott** [comment]
+1 on funding timeout - just so happened to be playing with this today on testnet and ran into the issue.

The timeout for a `connectd` call can also be considerable (2 min+), so maybe a reasonable timeout can be set there as well.
