### ISSUE TITLE
Can I temporarily blacklist routes in the same way that `lightning-cli pay` does?

### ISSUE THREAD

**Issue by billygarrison** [ElementsProject/lightning#2419]
### Issue and Steps to Reproduce
Maybe someone has other advice. I've been trying to get manual routes working, and have been somewhat successful. Unfortunately, most of my `sendpay` commands end up returning an error `WIRE_TEMPORARY_CHANNEL_FAILURE`.

## Questions
- Is it normal to get so many `WIRE_TEMPORARY_CHANNEL_FAILURE` errors? What does this mean?
- To create a circular route, I first use `getroute` where `fromid` and `id` are nodes other than my own. If this ends up returning `WIRE_TEMPORARY_CHANNEL_FAILURE`, is there a way I can temporarily blacklist the route from `fromid` to `id` so that when I do `getroute` again, it returns a different route?
- The `WIRE_TEMPORARY_CHANNEL_FAILURE` error doesn't seem to resolve right away - resending the same route 30 seconds later doesn't fix it. If I get this error, should I just try to create a route that avoids that node?

### `getinfo` output
```
{
  "id": "02843833374b6c42daa4b780df2066a9985cb8cf97bc4566dd63cf693d32cbf7b5",
  "alias": "BillyGarrison",
  "color": "009900",
  "num_peers": 16,
  "num_pending_channels": 0,
  "num_active_channels": 15,
  "num_inactive_channels": 1,
  "address": [
    {
      "type": "ipv4",
      "address": "47.55.123.202",
      "port": 9735
    }
  ],
  "binding": [
  ],
  "version": "v0.6.3",
  "blockheight": 565119,
  "network": "bitcoin",
  "msatoshi_fees_collected": 6315
}
```

**Comment by rustyrussell** [comment]
Yes!  Call getroute using the 'excludes' parameter.  See the documentation... um, ok, let me *update* the doxumentation...

**Comment by rustyrussell** [comment]
But to answer your question: yes, it's common.  We only know the theoretical capacity of channels, not their current capacity (which side hold how much of the total balance). So expect failures.

In fact, this is exactly what the pay plugin does: get routes, try, exclude failing channels, retry.  If you can't get a route, it can't be done.

**Comment by billygarrison** [comment]
Great! Thanks a lot @rustyrussell !
