### ISSUE TITLE
How to upgrade docker clightning

### ISSUE THREAD

**Issue by Elmit2015** [ElementsProject/lightning#2426]
I tried to update clightning to the new version of 0.7 by

    docker-compose stop
    docker-compose rm clightning_bitcoin
    docker-compose up

However, it is still version 0.63 Where do I set that it is upgrading to 0.7?

Would this change in docker-compose.yml be correct?

  clightning_bitcoin:
    image: elementsproject/lightningd

to

  clightning_bitcoin:
    image: elementsproject/lightningd:latest

Do I miss something?

**Comment by leshik** [comment]
> Do I miss something?

Yes, `docker-compose` doesn't update images by default if the image in question already exists locally. Issue `docker-compose pull` before up.

**Comment by Elmit2015** [comment]
Nop, ... same result!!!!

**Comment by cdecker** [comment]
Thanks for reporting this @Elmit2015, I didn't have time yet to update the docker images. I just updated the `cdecker/lightningd` and `elementsproject/lightningd` images, so if your `docker-compose.yml` uses one of them then a `docker pull` should now work. If not could you share the image you are using, and I'll try to ping the maintainer.

**Comment by Elmit2015** [comment]
Yes, it works now. 
"version": "v0.7.0",
Thank you, very much.

**Comment by cdecker** [comment]
No problem, and sorry for the delay :wink:
