### ISSUE TITLE
Does gossip_store break after update to 0.7?

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#2443]
After I updated my lightningnode from 0.62 to 0.7 I experienced a decrease in the elements of `listchannels`. Only about 300 where it was like 60k before. After shutting down `lightningd` and making a backup of `gossip_store` and deleting the file from `.lightning` I was able to retrieve 60k channels again. there where also many entries in my log file stating `Bad gossip repeated timestamp for ...` I was not able to reproduce this bug but wanted to ask if others experienced similar problems or could confirm the bug? 

Generally I assume deleting `./lightning/gossip_store` should not be a problem correct?

**Comment by rustyrussell** [comment]
Yes, you can delete gossip_store at any time, and we'll reload gossip from peers (can take a few minutes, depending on connection speed).

When we bump gossip store versions (or can't read it all for some reason), we delete it, so an upgrade sometimes will delete and start again.  We don't track closely, but I expect that was changed between 0.6.2 and now.

**Comment by renepickhardt** [comment]
I can share the backup of the corrupt gossip store if that would help. Not sure if it is worthwhile digging into it. I wonder why it only showed really old channels with funding TX blickheight being 51.... And why it couldn't autodelete / update

**Comment by renepickhardt** [comment]
Hey @rustyrussell as promised a zip verion of the corrupted gossip store [corrupt_gossip_store.zip](https://github.com/ElementsProject/lightning/files/2932715/corrupt_gossip_store.zip)

the version seems to be 03 as it is supposed in the current c-lightning release. at least the first byte has the value 03 which according to my understanding of gossip.c should be the version.

**Comment by cdecker** [comment]
Just tried loading your `gossip_store` with the latest `master`, setting a break point on truncate but no truncation here.

**Comment by jsarenik** [comment]
Yet another `gossip_store.corrupted` from a `c-lightning` node running current master on mainnet is available encrypted at https://instant.bublina.eu.org/#62ec69f9222a24a0ff7ec8f9856b28003bd2daa5.

Ask me on IRC for the password to decrypt it.

**Comment by darosior** [comment]
I think it can be closed ? If new gossip store corruption happen it seems preferable to open a new issue with the right version number ?

**Comment by jsarenik** [comment]
See https://github.com/ElementsProject/lightning/issues/4125 for a new issue I just filed instead of adding to this one.

**Comment by cdecker** [comment]
Closing as this is rather old already, and likely not applicable anymore.
