### ISSUE TITLE
Pay timed out and payment stuck in pending

### ISSUE THREAD

**Issue by got3nks** [ElementsProject/lightning#2452]
The "pay" command didn't return any reply after 60 seconds and using the listpays command the invoice shows **"status": "pending"**.

Will it resolve automatically or is there any action required? Should we try to pay the invoice again?

**Comment by rustyrussell** [comment]
It means the payment got stuck somewhere along the path due to a node going down.  Unfortunately, when this happens there's no feedback (an issue addressed in 1.1 of the protocol).   It will fix itself eventually, however.

**Comment by got3nks** [comment]
So what should we do, wait until it either fails or succeed?

**Comment by got3nks** [comment]
Looks like it eventually failed
