### ISSUE TITLE
Upgraded to v0.7.0 and now get pylightning error

### ISSUE THREAD

**Issue by billygarrison** [ElementsProject/lightning#2454]
### Issue and Steps to Reproduce
I upgraded c-lightning by going to my lightning repo, using commands:
```
git pull
git checkout tags/v0.7.0
./configure
make
```
Then I uninstalled pylightning using pip (because I received an error when trying to use pip to upgrade). I added the lightning/contrib/pylightning folder to my $PYTHONPATH variable, which worked to get the package recognized by Python. But I get an error when I try to run the following simple script:
```
from lightning import LightningRpc
node = LightningRpc("/home/billy/.lightning/lightning-rpc")
node.getinfo()
```
Here's the traceback:
```
Traceback (most recent call last):
  File "test_test.py", line 1, in <module>
    from lightning import LightningRpc
  File "/home/billy/builds/lightning/contrib/pylightning/lightning/__init__.py", line 1, in <module>
    from .lightning import LightningRpc, RpcError, Millisatoshi
  File "/home/billy/builds/lightning/contrib/pylightning/lightning/lightning.py", line 249
    def __init__(self, *, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, strict=True, object_pairs_hook=None):
                        ^
SyntaxError: invalid syntax
```
When I go to line 249, it seems to be [this line](https://github.com/ElementsProject/lightning/blob/master/contrib/pylightning/lightning/lightning.py#L251) causing the error.

I was using pylightning v0.0.4 (oops) before so perhaps I am doing something wrong that has changed since then.

### `getinfo` output
```
{
  "id": "02843833374b6c42daa4b780df2066a9985cb8cf97bc4566dd63cf693d32cbf7b5",
  "alias": "BillyGarrison",
  "color": "009900",
  "num_peers": 16,
  "num_pending_channels": 0,
  "num_active_channels": 15,
  "num_inactive_channels": 1,
  "address": [
    {
      "type": "ipv4",
      "address": "47.55.123.202",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv4",
      "address": "0.0.0.0",
      "port": 9735
    }
  ],
  "version": "v0.7.0",
  "blockheight": 565977,
  "network": "bitcoin",
  "msatoshi_fees_collected": 7789,
  "fees_collected_msat": "7789msat"
}
```

**Comment by conscott** [comment]
I suspect this is an issue of python 2 vs 3, which version of python are you running the script with? You will want to specify python3. 

Another possible confusion installing with pip is that on some systems `pip install ...`  will default to python2, and you need to use `pip3 install ...` to actually install the package in python3 dirs. 

If you still have install errors with `pip3`, you can also install manually inside the repo with
```bash
# In the c-lightning repo
cd contrib/pylightning/
sudo python3 setup.py install  # may not need sudo depending on group permissions
```

**Comment by billygarrison** [comment]
Thank you @conscott that was the problem! I'll leave this open for now in case someone wants to add a Python version check into the code, or a warning in the readme.

**Comment by cdecker** [comment]
I wasn't aware we could even install the package in python2, I thought I had that distro disabled on pypi.

**Comment by billygarrison** [comment]
I installed using pip2 back when pylightning was 0.0.4, so maybe you could
then but not anymore?
