### ISSUE TITLE
Old pending channels are not being removed

### ISSUE THREAD

**Issue by btcontract** [ElementsProject/lightning#2456]
On Feb 24 there was an attempt to open a BLW -> CL channel, remote CL node URI is `02398b614028892474fc95ed64c48791f994975042d0bd7e9592d0ec4128bbace4@midbdlknuz3nrtkzohgxyqpntyokblbzdzrswkjvptebdh3ogdpcuwyd.onion:9736`.

BLW cancelled a channel creation at the last moment, right before a funding was about to be published, but remote CL peer already had a channel saved in "waiting for remote funding to be published" state. 

Since that time CL node refuses to open another channel and sends a "Multiple channels unsupported" `Error`.  It seems like CL does not clear these chanels (or has a very long waiting period?)

**Comment by cdecker** [comment]
Indeed the timeout is 2 weeks as courtesy for the remote end should they end up confirming the channel. If we didn't have a long timeout we'd be forcing them to unilaterally close which is more expensive.

https://github.com/ElementsProject/lightning/blob/6f71564bdd60608f24551de3c903c23c544a37b6/lightningd/lightningd.c#L203

**Comment by btcontract** [comment]
Channel was successfully opened today.
