### ISSUE TITLE
How to config remotely bitcoind node with ~/.lightning/config file

### ISSUE THREAD

**Issue by MartinDong** [ElementsProject/lightning#2458]
I have a bitcoind node server, now i want to config a lightning node on other server, so how to config remotely bitcoind node with ~/.lightning/config file.

This is my config file
```
alias=SLEEPYDRAGON
rgb=008000
network=testnet

log-level=debug
log-file=/home/lightning/.lightning/debug.log

#bitcoin-cli=remotely
bitcoin-rpcuser=dhy
bitcoin-rpcpassword=dhy
bitcoin-rpcconnect=192.168.1.101
bitcoin-rpcport=8332
plugin-dir=/home/lightning/libexec/c-lightning/plugins
```

**Comment by cdecker** [comment]
Does this produce an error:

```
bitcoin-cli -testnet --bitcoin-rpcconnect=192.168.1.101 --bitcoin-rpcuser=dhy --bitcoin-rpcpassword=dhy --bitcoin-rpcport=8332 echo hello
```

I think you are mixing testnet and mainnet judging from the 8332 port.

**Comment by MartinDong** [comment]
> Does this produce an error:
> 
> ```
> bitcoin-cli -testnet --bitcoin-rpcconnect=192.168.1.101 --bitcoin-rpcuser=dhy --bitcoin-rpcpassword=dhy --bitcoin-rpcport=8332 echo hello
> ```
> I think you are mixing testnet and mainnet judging from the 8332 port.

I know that, and i find #1741 issues, now i install bitcoin-cli on this server and change ~/.lightning/config 
```
log-level=debug
log-file=/home/lightning/.lightning/debug.log

bitcoin-cli=/home/lightning/bitcoin/bitcoin-cli
bitcoin-rpcuser=dhy
bitcoin-rpcpassword=dhy0
bitcoin-rpcconnect=192.168.2.101
bitcoin-rpcport=8332
plugin-dir=/home/lightning/libexec/c-lightning/plugins

alias=SLEEPYDRAGON
#rgb=008000
network=testnet
```
## Console print error
```
2019-03-08T02:10:09.395Z plugin-pay Could not register method "pay", a method with that name is already registered
2019-03-08T02:10:09.395Z plugin-pay Killing plugin: Failed to register options, methods, hooks, or subscriptions.
Could not connect to bitcoind using bitcoin-cli. Is bitcoind running?

Make sure you have bitcoind running and that bitcoin-cli is able to connect to bitcoind.

You can verify that your Bitcoin Core installation is ready for use by running:

    $ /home/lightning/bitcoin/bitcoin-cli -testnet -rpcconnect=192.168.2.101 -rpcport=8332 -rpcuser=bitpie -rpcpassword=bitpie0 echo 'hello world'
```

**Comment by MartinDong** [comment]
> Does this produce an error:
> 
> ```
> bitcoin-cli -testnet --bitcoin-rpcconnect=192.168.1.101 --bitcoin-rpcuser=dhy --bitcoin-rpcpassword=dhy --bitcoin-rpcport=8332 echo hello
> ```
> I think you are mixing testnet and mainnet judging from the 8332 port.

You are right ,thank you
