### ISSUE TITLE
Can't create connection to lightning node from eclair.

### ISSUE THREAD

**Issue by brandoncollins7** [ElementsProject/lightning#2463]
### Issue and Steps to Reproduce
I have set up a node and attempt to connect to it via eclair on testnet. The lightningd node displays: 

"2019-03-11T16:32:29.168Z lightningd(7): Connected json input" 

however nothing else happens and eclair eventually times out with the error:

"Failed to open channel:Ask timed out on [Actor[akka://system/user/$#2143873466]] after [30000 ms]"

### `getinfo` output
{
    "id": "02845f5298f42462de74cc7adede434333acade1819515209526fa031a4832130d",
    "port": 9735,
    "address": [
        {
            "type": "ipv4",
            "address": "52.15.194.28",
            "port": 14182
        }
    ],
    "binding": [],
    "version": "v0.6",
    "blockheight": 1484298,
    "network": "testnet"
}

**Comment by brandoncollins7** [comment]
Seems this had something to do with the examples "EXPOSE_TCP: "true"".... The text above seems conflicting with the example displayed, "EXPOSE_TCP default to false, if true, use expose c-lightning RPC on port 9835. (Use this only for testing)". I think the readme should be fixed?

**Comment by cdecker** [comment]
```
2019-03-11T16:32:29.168Z lightningd(7): Connected json input
```
Refers to a JSON-RPC connection, not a peer connecting.

Which readme are you referring to? This seems to be a docker port expose problem as you pointed out.
