### ISSUE TITLE
What's the best way to keep c-lightning up to date on the latest release?

### ISSUE THREAD

**Issue by scottshapiro** [ElementsProject/lightning#2468]
What's the best way to keep my node up to date on the latest release of c-lightning (e.g. without having to open my shell and git clone)? 

I don't believe there's a snapd package, and I'm not using Docker (maybe I should?).

**Comment by cdecker** [comment]
If you run on a debian derivative I'd suggest using the [PPA](https://launchpad.net/~lightningnetwork/+archive/ubuntu/ppa), or one of the release builds in the releases tab.

If you plan on developing you'll likely use the git version anyway :wink:

**Comment by scottshapiro** [comment]
PPA should also work on Ubuntu right?

**Comment by cdecker** [comment]
Yep, ubuntu is the actual target we are compiling these on ourselves :-)

**Comment by scottshapiro** [comment]
Nice. I'll check it out. Thanks!
