### ISSUE TITLE
Persist channel_announcement messages during restart

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#247]
This was pointed out in #237: if we restart all nodes that knew about a channel, then the channels get re-established, but the `channel_announcement`s are lost and hence are inexistent in the view of all other nodes in the network. Notice that this does not include scenarios where a single node knowing about the channel since it'll re-broadcast upon re-establishment.

The simplest way of fixing this is to store our node's `channel_announcement` messages to disk and then feed them back into `gossipd` upon restart. Another variant is that we store just the announcement sigs and feed that back to `channeld` on reconnect. The first one is easier, the second stores less data (168 bytes / channel vs. 430 bytes / channel). Optionally we could also store other messages, but they are likely stale anyway, and we'll get a full dump from peers anyway.

I'd propose a simple file-based append-only store for the full `channel_announcement` messages. Alternatively we could also store these in the DB, alongside the channel table.

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> This was pointed out in #237: if we restart all nodes that knew about a channel, then the channels get re-established, but the `channel_announcement`s are lost and hence are inexistent in the view of all other nodes in the network. Notice that this does not include scenarios where a single node knowing about the channel since it'll re-broadcast upon re-establishment.
>
> The simplest way of fixing this is to store our node's `channel_announcement` messages to disk and then feed them back into `gossipd` upon restart. Another variant is that we store just the announcement sigs and feed that back to `channeld` on reconnect. The first one is easier, the second stores less data (168 bytes / channel vs. 430 bytes / channel). Optionally we could also store other messages, but they are likely stale anyway, and we'll get a full dump from peers anyway.
>
> I'd propose a simple file-based append-only store for the full `channel_announcement` messages. Alternatively we could also store these in the DB, alongside the channel table.

I'd store them in the database (append-only doesn't work when channels
are closed).

**Comment by cdecker** [comment]
Sounds good, but then I'd limit it to the sigs and store them in a separate table, Hopefully I find a way to tweak our DB layer to allow blob writes, because I really don't want to have to hex encode 256 bytes before storing them in a DB.

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> Sounds good, but then I'd limit it to the sigs and store them in a separate table, Hopefully I find a way to tweak our DB layer to allow blob writes, because I really don't want to have to hex encode 256 bytes before storing them in a DB.

Don't prematurely optimize, just store the entire thing or whatever is
easiest, and put a FIXME on it.
