### ISSUE TITLE
Can't find on-chain wallet after attempting to open channel

### ISSUE THREAD

**Issue by jonathancaras** [ElementsProject/lightning#2472]
### Issue and Steps to Reproduce

1) created a new segwit address
2) funded that address
3) opened 2 channels
4) no longer have access to the segwit address created in step 1

iOS-Room-TV:node-launcher lightningnode$ lightning-cli newaddr p2sh-segwit
{
  "address": "bc1qvwq5x7wscvnqm8y7sah3v3u35kd2hy83yw35mw", 
  "p2sh-segwit": "3LXUznfAbQtoUxb72tuxgS6i1EquMdcQzH"
}

iOS-Room-TV:node-launcher lightningnode$ lightning-cli listfunds
{
  "outputs": [
    {
      "txid": "27c3765f7499b0326ced5d3921a9c94e3d8dc6662d3919f53ee815d58e5c2648", 
      "output": 1, 
      "value": 129959, 
      "amount_msat": "129959000msat", 
      "address": "3LXUznfAbQtoUxb72tuxgS6i1EquMdcQzH", 
      "status": "confirmed"
    }
  ], 
  "channels": [
  ]
}

iOS-Room-TV:node-launcher lightningnode$ lightning-cli connect 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c mainnet.node.lightningpowerusers.com 9735
{
  "id": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c"
}

iOS-Room-TV:node-launcher lightningnode$ lightning-cli fundchannel 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c 50000
{ "code" : -1, "message" : "They sent error channel dc40c891f594faf73428ecadda333eeef7426c237551a9779c67807951a976ec: 01" }
iOS-Room-TV:node-launcher lightningnode$ lightning-cli connect 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c mainnet.node.lightningpowerusers.com 9735
{
  "id": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c"
}
iOS-Room-TV:node-launcher lightningnode$ lightning-cli fundchannel 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c 50000
{ "code" : -1, "message" : "Peer already CHANNELD_AWAITING_LOCKIN" }
iOS-Room-TV:node-launcher lightningnode$ lightning-cli connect 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266 23.237.77.11 9735
{
  "id": "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266"
}
iOS-Room-TV:node-launcher lightningnode$ lightning-cli fundchannel 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266 50000
{
  "tx": "0200000000010148265c8ed515e83ef519392d66c68d3d4ec9a921395ded6c32b099745f76c327010000001716001463814379d0c3260d9c9e876f164791a59aab90f1ffffffff0250c3000000000000220020a501dbad042a92f417270da6c723c11eee66e2160d409aa53d0cfe841590759f0823010000000000160014272c0945fc1e50d8953b11b8ca8cdf0bb4015ae10247304402205781f69e3e78993967eecfc948a3bda8c5638fd876834867df30078b1d138e0802203d72e7a21525b2620443f4e882fe9dad3b3ce7d70fbc330417309c8b8a19a21701210324f2fbec30a90259807fe504fb793a0648cf9ffb0a23750202afa5b831bd735f00000000", 
  "txid": "742fa3614f0114941a086fda1d48a4adce8db6ed6017300b77a5c9e7c6215ae0", 
  "channel_id": "e05a21c6e7c9a5770b301760edb68dceada4481dda6f081a9414014f61a32f74"
}

iOS-Room-TV:node-launcher lightningnode$ lightning-cli listfunds
{
  "outputs": [
    {
      "txid": "742fa3614f0114941a086fda1d48a4adce8db6ed6017300b77a5c9e7c6215ae0", 
      "output": 1, 
      "value": 74504, 
      "amount_msat": "74504000msat", 
      "address": "bc1qyukqj30uregd39fmzxuv4rxlpw6qzkhppvd43j", 
      "status": "unconfirmed"
    }
  ], 
  "channels": [
    {
      "peer_id": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c", 
      "channel_sat": 0, 
      "our_amount_msat": "0msat", 
      "channel_total_sat": 500000, 
      "amount_msat": "500000000msat", 
      "funding_txid": "ae1ea9c96928a2c8dbe22d71a13559a757611eb8841a134631afec47d99ecc2a"
    }, 
    {
      "peer_id": "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266", 
      "channel_sat": 50000, 
      "our_amount_msat": "50000000msat", 
      "channel_total_sat": 50000, 
      "amount_msat": "50000000msat", 
      "funding_txid": "742fa3614f0114941a086fda1d48a4adce8db6ed6017300b77a5c9e7c6215ae0"
    }
  ]
}

### `getinfo` output

iOS-Room-TV:node-launcher lightningnode$ lightning-cli getinfo
{
  "id": "034c58fc409d2d5f78dfd587359fb48eec314e4b159b0b9ff730fdcc6a3b86f797", 
  "alias": "WRONGPHOTO", 
  "color": "034c58", 
  "num_peers": 2, 
  "num_pending_channels": 0, 
  "num_active_channels": 2, 
  "num_inactive_channels": 0, 
  "address": [
    {
      "type": "ipv6", 
      "address": "2a02:ed0:539e:3a00:588a:8c28:5d10:20d3", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }
  ], 
  "version": "v0.7.0-25-g9a25b5d", 
  "blockheight": 567146, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0, 
  "fees_collected_msat": "0msat"
}

**Comment by jonathancaras** [comment]
notice how the TX in outputs changed from being the funding of my onchain wallet, to representing the tx of the opening of a channel, which does not appear on the blockchain

**Comment by SimonVrouwe** [comment]
You can check if the funding tx is in your mempool : 
```
bitcoin-cli gettxout 742fa3614f0114941a086fda1d48a4adce8db6ed6017300b77a5c9e7c6215ae0 1
```
if it returns nothing, then it is not and you can try rebroadcast with:
```
bitcoin-cli sendrawtransaction 0200000000010148265c8ed515e83ef519392d66c68d3d4ec9a921395ded6c32b099745f76c327010000001716001463814379d0c3260d9c9e876f164791a59aab90f1ffffffff0250c3000000000000220020a501dbad042a92f417270da6c723c11eee66e2160d409aa53d0cfe841590759f0823010000000000160014272c0945fc1e50d8953b11b8ca8cdf0bb4015ae10247304402205781f69e3e78993967eecfc948a3bda8c5638fd876834867df30078b1d138e0802203d72e7a21525b2620443f4e882fe9dad3b3ce7d70fbc330417309c8b8a19a21701210324f2fbec30a90259807fe504fb793a0648cf9ffb0a23750202afa5b831bd735f00000000
```

**Comment by SimonVrouwe** [comment]
Just broadcast it for you successfully, should be confirmed soon. Maybe there is something in your log that shows why it didn't broadcast properly initially?

**Comment by jonathancaras** [comment]
Thanks, it is now confirmed. 

iOS-Room-TV:node-launcher lightningnode$ lightning-cli listfunds
{
  "outputs": [
    {
      "txid": "742fa3614f0114941a086fda1d48a4adce8db6ed6017300b77a5c9e7c6215ae0", 
      "output": 1, 
      "value": 74504, 
      "amount_msat": "74504000msat", 
      "address": "bc1qyukqj30uregd39fmzxuv4rxlpw6qzkhppvd43j", 
      "status": "confirmed"
    }
  ], 
  "channels": [
    {
      "peer_id": "0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c", 
      "short_channel_id": "567053x1990x0", 
      "channel_sat": 0, 
      "our_amount_msat": "0msat", 
      "channel_total_sat": 500000, 
      "amount_msat": "500000000msat", 
      "funding_txid": "ae1ea9c96928a2c8dbe22d71a13559a757611eb8841a134631afec47d99ecc2a"
    }, 
    {
      "peer_id": "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266", 
      "short_channel_id": "567345x250x0", 
      "channel_sat": 50000, 
      "our_amount_msat": "50000000msat", 
      "channel_total_sat": 50000, 
      "amount_msat": "50000000msat", 
      "funding_txid": "742fa3614f0114941a086fda1d48a4adce8db6ed6017300b77a5c9e7c6215ae0"
    }
  ]
}

Here is what I get when I run 
bitcoin-cli gettxout 742fa3614f0114941a086fda1d48a4adce8db6ed6017300b77a5c9e7c6215ae0 1


iOS-Room-TV:node-launcher lightningnode$ bitcoin-cli gettxout 742fa3614f0114941a086fda1d48a4adce8db6ed6017300b77a5c9e7c6215ae0 1
{
  "bestblock": "0000000000000000001b345ecb90469202ca9f3a2cb425d7fe54b0fefdb2389e",
  "confirmations": 287,
  "value": 0.00074504,
  "scriptPubKey": {
    "asm": "0 272c0945fc1e50d8953b11b8ca8cdf0bb4015ae1",
    "hex": "0014272c0945fc1e50d8953b11b8ca8cdf0bb4015ae1",
    "reqSigs": 1,
    "type": "witness_v0_keyhash",
    "addresses": [
      "bc1qyukqj30uregd39fmzxuv4rxlpw6qzkhppvd43j"
    ]
  },
  "coinbase": false
}

Question, how do I get access to my logs?
