### ISSUE TITLE
There should be a hook for accepting channel opens

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#2483]
In particular, people want to reject tiny channels.

**Comment by m-schmoock** [comment]
@rustyrussell I just read the IRC logs of the last meeting... 
> 20:42 < sstone> yes. I think pretty soon people will start refusing tiny incoming channels, and be more aggressive with unreliable nodes
> ...
> 20:58 < rusty> Yeah, I had someone complain c-lgihtning didn't implement minimum channel amount for accepting channels.  I'd never thought of it, TBH.

Only plugin hook or also config value? If the latter, what would be a reasonable default for a config value?

**Comment by m-schmoock** [comment]
I started working on this, will add config option for auto reject and a hook for plugins... First PR will follow soon

**Comment by m-schmoock** [comment]
@cdecker @rustyrussell 
I will submit two separate PRs one for the hook and one for a config value...

**Comment by m-schmoock** [comment]
**Update:** After starting working on this, I will set the `min_effective_htlc_capacity` via config. Default will then be `1000sat` which was the old internal magic number.

**Comment by m-schmoock** [comment]
This is the working branch for the config part: https://github.com/m-schmoock/lightning/tree/issue-2483-config-value

I think discovered some memory leak and remote crash problems which I need to track down first...

**Comment by m-schmoock** [comment]
@cdecker @rustyrussell For the plugin hook, is it feasible to implement the hook synchronously?

**Comment by cdecker** [comment]
Config value was merged :+1:
