### ISSUE TITLE
Pay an invoice already paid by other

### ISSUE THREAD

**Issue by hihidev** [ElementsProject/lightning#2488]
Assuming there are 3 nodes, A,B,C, and 2 channels, A<->B, C<->B.
B generates an invoice, then A pays for it by running `lightning-cli pay INVOICE`.
However, it seems C can also able to run `lightning-cli pay INVOICE` on the same invoice successfully, and fund is deduced in `listfunds` / `listpayments`.

Here's the result of `listpayments` from A and B.
```
{
  "payments": [
    {
      "id": 1, 
      "payment_hash": "bf7c7f229a9e37edf21ee29d4c9c2f4f90aa7a2c5057df8128cc94f5c4663838", 
      "destination": "0260d9119979caedc570ada883ff614c6efb93f7f7382e25d73ecbeba0b62df2d7", 
      "msatoshi": 5000000, 
      "msatoshi_sent": 5000000, 
      "created_at": 1553214509, 
      "status": "complete", 
      "payment_preimage": "1067ce4a8910221f6722efd08494fe46e02dc61a7f0b310619089ac0214dc785"
    }
  ]
}
```

```
{
  "payments": [
    {
      "id": 1, 
      "payment_hash": "bf7c7f229a9e37edf21ee29d4c9c2f4f90aa7a2c5057df8128cc94f5c4663838", 
      "destination": "0260d9119979caedc570ada883ff614c6efb93f7f7382e25d73ecbeba0b62df2d7", 
      "msatoshi": 5000000, 
      "msatoshi_sent": 5000000, 
      "created_at": 1553214399, 
      "status": "complete", 
      "payment_preimage": "1067ce4a8910221f6722efd08494fe46e02dc61a7f0b310619089ac0214dc785"
    }
  ]
}
```

Is it expected? Thanks!

**Comment by arowser** [comment]
Which version? the master branch should not support this,  and you said
"Here's the result of listpayments from A and B.", the B is receiver,
listpayments in B should return NULL.

**Comment by hihidev** [comment]
Oh sorry I mean it's the result from A and C, both A and C shows they can able to sent payment successfully.
A and C are running c-lightning v0.6.3rc1-161-g21afe1c-modded
B is a lnd node from http://lnd.fun.

**Comment by arowser** [comment]
So its expected, the lnd is support that,  but its not safe, and the lnd
not record the second payment now, see
https://github.com/lightningnetwork/lnd/issues/2208

**Comment by cdecker** [comment]
> Is it expected?

Yes, there is no way to enforce that `B` rejects a payment that it knows how to claim. If we were to reject the payment on the basis that it was already paid, people could start relying on that fact.

**Comment by hihidev** [comment]
Gotcha.
So it sounds like just a bug on lnd side that they don't show the 2nd payment in their funds?

It's quite bad that if a merchant accidentally send a paid invoice to 2nd customer, so 2nd customer send the payment to merchant using paid invoice, while merchant can't notice a new payment received.

**Comment by cdecker** [comment]
> So it sounds like just a bug on lnd side that they don't show the 2nd payment in their funds?

Not sure, do they actually accept the second attempt or are they a friendly neighbor and send the funds back? Only in the former case the bookkeeping will be off.
