### ISSUE TITLE
Feature Request: Include timestamp in `channel_htlcs` or `forwarded_payments` table

### ISSUE THREAD

**Issue by billygarrison** [ElementsProject/lightning#2491]
As far as I can tell, there's no way to know when your node forwarded a payment, aside from parsing the log data.

It would be very helpful for routing node operators to be able to know exactly when they have forwarded payments, so they could have a better understanding of how changing various aspects of their setup affects their routing traffic.

Currently, `forwarded_payments` contains the in and out HTLC IDs only. By joining them to `channel_htlcs`, we are able to get `cltv_expiry`, which doesn't tell us much about when we actually forwarded the payment. The only other sense of time is HTLC ID, which is still far from ideal.

It would be nice if we had an absolute timestamp, for example in `forwarded_payments` when we receive the forward request, or in `channel_htlcs` when we know the payment has either failed/succeeded.

As an example, it would be great to be able to create a simple time series plot showing cumulative fees through time. This would allow us to see the effects of changing fees, opening/closing channels, etc.

**Comment by m-schmoock** [comment]
Yes, I was also missing that recently and have been thinking about adding it, now we are two :D

@cdecker what do you think?
