### ISSUE TITLE
What happens if i generate an invoice and pay it myself, from the same node?

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#2495]
I'm really curious, but i'm afraid to test it with real funds.

**Comment by billygarrison** [comment]
I just tested it out on 0.7.0 and it worked like a normal payment. It routed through one of my peers first though, and then I guess straight back to me.

I was surprised to see that it chose to route through the peer with probably the highest fee rate. But this was only a 1000 msat payment so not a big deal. When I tried with a larger payment it did choose a route through a peer with a lower fee rate.

**Comment by ZmnSCPxj** [comment]
>I was surprised to see that it chose to route through the peer with probably the highest fee rate. But this was only a 1000 msat payment so not a big deal. When I tried with a larger payment it did choose a route through a peer with a lower fee rate.

This is probably a result of route randomization.

In any case, has the question been satisfactorily answered @thestick613 ?
