### ISSUE TITLE
c-lightning shuts down

### ISSUE THREAD

**Issue by FontaineDenton** [ElementsProject/lightning#2499]
### Issue and Steps to Reproduce
I set up c-lightning on my server and it runs fine, I exit the terminal come back to check on it the next day and it is always off, this has happened on multiple servers. Bitcoind runs just fine, c-lightning always stops. When I ran the older versions they did not have this issue.

### `getinfo` output
{
  "id": "03a339ce00a5b295c769404a19637c50993bc9dbd06b0263dc7f57d24cb80d6d8e", 
  "alias": "hodlco", 
  "color": "008000", 
  "num_peers": 2, 
  "num_pending_channels": 1, 
  "num_active_channels": 0, 
  "num_inactive_channels": 0, 
  "address": [
    {
      "type": "ipv4", 
      "address": "157.230.104.120", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }, 
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "v0.7.0-46-g3852704", 
  "blockheight": 1485953, 
  "network": "testnet", 
  "msatoshi_fees_collected": 0, 
  "fees_collected_msat": "0msat"
}

**Comment by billygarrison** [comment]
I could be wrong, but it's my understanding that lightningd "lives" in the terminal session, so closing the terminal would kill the session.

If you use tmux or screen, then you can start lightningd in one of those sessions and close the terminal.

**Comment by FontaineDenton** [comment]
Ok thanks for the simple fix
