### ISSUE TITLE
Funds from lightning to bitcoin; privkey which keep funds on the lightning

### ISSUE THREAD

**Issue by vadimVoloshanov** [ElementsProject/lightning#251]
Hello, how can I transfer funds from the "lightning" node to the "bitcoin" node. How to get a private key which keep the funds in the “lightning” node, what would then be imported into the “bitcoin” node.
For example, my "lightning" node received funds from other "lightning" node (by executed "sendpay"), the channel was closed, now I want these funds use at my "bitcoin" node(by execute “importprivkey” in the "bitcoin" node) that then send them on to the other bitcoin node.
Sorry for my English.

**Comment by jl777** [comment]
there is a withdraw command
the privkey is in the ~/.lightning folder and it uses HD derivation, but with the withdraw api it seems much simpler to just withdraw:

	{ "command" : "withdraw", "description" : "Send {satoshi} to the {destination} address via Bitcoin transaction" },

**Comment by vadimVoloshanov** [comment]
{destination} - is just bitcoin address?
For example: "daemon/lightning-cli withdraw 1000000 1BQ9qza7fn9snSCyJQB3ZcN46biBtkt4ee"?
And if we want import privat key to bitcoin, we can do this?
thanks for the answer

**Comment by jl777** [comment]
I havent tested the withdraw api, but i assume {destination} address means exactly that, a normal bitcoin address, the only difference is that you are sending in satoshis.

not sure the format the privkey is stored in, it might be encrypted.

**Comment by cdecker** [comment]
Yep, `withdraw` currently supports P2PKH addresses just fine, so you can just copy&paste an address from the bitcoin core client and we'll send the coins to that address (it'll tell you if it's not a P2PKH address).

We consider the address you sent the funds to owned by the lightning daemon, and importing them into another wallet may have adverse effects, e.g., we'd create funding transactions using spent outputs. If you really need to get the addresses used by `lightningd`, they are generated from the seed in the `hsm_secret` file, and we have a number of tools to replicate the derivation, which we will make available soon. But keep in mind these are dev-tools, and may lead to shooting youself in the foot :wink:
