### ISSUE TITLE
crash when doing fundchannel and then listpeers (0.7.0)

### ISSUE THREAD

**Issue by jogc** [ElementsProject/lightning#2510]
version: 0.7.0

[crash.log.20190328195552.zip](https://github.com/ElementsProject/lightning/files/3019933/crash.log.20190328195552.zip)

**Comment by jogc** [comment]
update: this actually happens every time i try opening a channel to a certain node

**Comment by m-schmoock** [comment]
I tried to reproduce this with a testcase, without any luck so far.
In case someone wants to pick up on this, this is the `json_fund_channel` stacktrace of the attached zip:

```
+84750.935989269 lightningd(608):BROKEN: FATAL SIGNAL 11 (version v0.7.0)       
+84750.936020069 lightningd(608):BROKEN: backtrace: common/daemon.c:45 (crashdump) 0x55f503479a8a
+84750.936035733 lightningd(608):BROKEN: backtrace: (null):0 ((null)) 0x7ff6b60238df
+84750.936051914 lightningd(608):BROKEN: backtrace: wallet/wallet.c:330 (wallet_select) 0x55f5034a2e4f
+84750.936071490 lightningd(608):BROKEN: backtrace: wallet/wallet.c:364 (wallet_select_coins) 0x55f5034a303f
+84750.936080734 lightningd(608):BROKEN: backtrace: common/wallet_tx.c:90 (wtx_select_utxos) 0x55f503482e6f
+84750.936094236 lightningd(608):BROKEN: backtrace: lightningd/opening_control.c:895 (json_fund_channel) 0x55f50345f6ae
+84750.936114229 lightningd(608):BROKEN: backtrace: lightningd/jsonrpc.c:616 (parse_request) 0x55f503456827
+84750.936133557 lightningd(608):BROKEN: backtrace: lightningd/jsonrpc.c:714 (read_json) 0x55f503456c50
+84750.936145847 lightningd(608):BROKEN: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x55f5034b4d09
+84750.936163993 lightningd(608):BROKEN: backtrace: ccan/ccan/io/io.c:395 (do_plan) 0x55f5034b5825
+84750.936182520 lightningd(608):BROKEN: backtrace: ccan/ccan/io/io.c:405 (io_ready) 0x55f5034b5863
+84750.936195735 lightningd(608):BROKEN: backtrace: ccan/ccan/io/poll.c:310 (io_loop) 0x55f5034b7444
+84750.936210586 lightningd(608):BROKEN: backtrace: lightningd/lightningd.c:829 (main) 0x55f5034592eb
+84750.936230613 lightningd(608):BROKEN: backtrace: (null):0 ((null)) 0x7ff6b601009a
+84750.936241939 lightningd(608):BROKEN: backtrace: (null):0 ((null)) 0x55f503443b99
+84750.936251606 lightningd(608):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

**Comment by jogc** [comment]
maybe the data dir got corrupted with time, i've had it since many versions ago. i'll do a fresh install later and see what happens.

**Comment by jogc** [comment]
did complete reinstall (compiled from git tag v0.7.0), make sure no old versions of binaries or plugins laying around. same result.

backed up and wiped my data directory except for hsm_secret. expected my on-chain funds to still be there so i can get them out, but they are not. listfunds show nothing now. dev-rescan-outputs doesn't seem to help. how can i get my on-chain funds out? when i'm using my non-wiped data directory, both fundchannel and withdraw makes lightningd instantly crash.

**Comment by SimonVrouwe** [comment]
You need to call `newaddr` a few times (as many times as addresses where used), that will add them to pool of addresses that are watched when a new block arrives. Then restart with `dev-rescan` with relative or absolute blockheight set to a height below where your funds are.

**Comment by cdecker** [comment]
> Then restart with dev-rescan with relative or absolute blockheight set to a height below where your funds are.

The command line option is `--rescan` and it takes both positive numbers (for rescans relative to the current blockchain height) and negative numbers (for rescans from an absolute height). So `--rescan=1000` will rescan the last 1000 blocks, while `--rescan=-500000` will rescan all blocks from height 500000 :wink:

**Comment by jogc** [comment]
i followed your instructions and got my funds back, thanks. also, wiping my data dir did indeed make it stop crashing. i'll leave it up to you to close this issue or not.
