### ISSUE TITLE
Error installing: "make: *** [ccan/ccan/cdump/tools/cdump-enumstr] Error 1"

### ISSUE THREAD

**Issue by DariusParvin** [ElementsProject/lightning#2522]
### Issue and Steps to Reproduce

I'm getting this error after running 'make'. I'm running it on AWS 
https://pastebin.com/8XEDQd91

last few lines:

/usr/bin/ld: cannot find -lgmp
/usr/bin/ld: cannot find -lsqlite3
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [ccan/ccan/cdump/tools/cdump-enumstr] Error 1

### `getinfo` output

don't have 'getinfo'. In case this helps, it's the instance on AWS i'm running:
  Operating System: Amazon Linux 2
       CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2
            Kernel: Linux 4.14.104-95.84.amzn2.x86_64
      Architecture: x86-64

**Comment by cdecker** [comment]
That looks like you are missing a few dependencies. If you are running on a debian or ubuntu you might want to install them using the following command (from the readme):

```
sudo apt-get update
sudo apt-get install -y \
  autoconf automake build-essential git libtool libgmp-dev \
  libsqlite3-dev python python3 net-tools zlib1g-dev libsodium-dev
```

Specifically your missing libraries are:

 - `/usr/bin/ld: cannot find -lgmp` -> `libgmp-dev`
 - `/usr/bin/ld: cannot find -lsqlite3` -> `libsqlite3-dev`
 - `/usr/bin/ld: cannot find -lz` -> `zlib1g-dev`

**Comment by DariusParvin** [comment]
Thanks a lot! Sorry I should have mentioned that apt-get wasn't available on the AWS instance so I used 'yum' instead. I must have been using a CentOS-based system on AWS (EC2). 

For these packages you can't simply replace 'apt-get' with 'yum', the equivalent packages have different names. I was able to get it working by using these names instead. Cheers

```
sudo yum install gmp-devel
sudo yum install sqlite-devel
sudo yum install openssl-devel

```

**Comment by cdecker** [comment]
Thanks for translating the package names to CentOS land :-)

I'll fix the [docs](https://lightning.readthedocs.io/INSTALL.html) to include that
