### ISSUE TITLE
Which commands tells me the balance of a channel

### ISSUE THREAD

**Issue by Elmit2015** [ElementsProject/lightning#2523]
I use c-lightning 0.7 for a while and get some traffic. 
getinfo shows the line:
`  "msatoshi_fees_collected": 5231048, 
`
Since c-lightning can only transfer in one direction, I need to observe what's the balance of the channel_SSSSS. 
getinfo gives me one line of collected fees. How do I get a list of all my channels, telling me how much I have on a receivinig channel and how much I still have on a sending channel?

**Comment by m-schmoock** [comment]
`lightning-cli listfunds`

**Comment by cdecker** [comment]
This question would be better suited for https://bitcoin.stackexchange.com/ :wink:

**Comment by darosior** [comment]
For reference, now most of us are using the [`summary` plugin](https://github.com/lightningd/plugins/tree/master/summary) for this __exact__ usecase.
