### ISSUE TITLE
getroute doesn't change route on sendpay failure

### ISSUE THREAD

**Issue by andrewtoth** [ElementsProject/lightning#2536]
From the man page for `waitsendpay`:
```
 On error, if the error occurred from a node other than the final destination, the route
       table will be updated so that getroute(7) should return an alternate route (if any).
```
However, after a `sendpay` and a `waitsendpay` that returns a failure with error from a channel that is not the final destination, calling `getroute` again returns the same route. No amount of `getroute -> sendpay -> waitsendpay` causes `getroute` to return an alternate route. Using the `pay` command, however, will successfully complete the payment. So there are definitely alternate routes available. This makes the `sendpay` command effectively useless, as it will fail on the first route and we are unable to find a new route.

**Comment by andrewtoth** [comment]
Currently I am working around this by adding the `erring_channel` and `erring_direction` to the `exclude` parameter of `getroute` after every failure.

**Comment by cdecker** [comment]
That is indeed the intended use: we no longer disable a channel for a random timeout upon temporary failure, but we expect the caller to use `exclude` to exclude failed channels.

We need to update the docs to reflect that change :+1:
