### ISSUE TITLE
lightning-cli within a php page gives permission error

### ISSUE THREAD

**Issue by Elmit2015** [ElementsProject/lightning#2548]
I use 0.7 with docker.

I try to use lightnig-cli from a web page. I added www-data to the docker group.

In php the line:

`$jsondata = shell_exec("/bin/lightning-cli fundchannel");`

seems to give me a permission error. How can I solve that?

**Comment by Saibato** [comment]
one solution is to give the lightning-rpc socket rw group or user rights from the PHP side
as example for simple PHP access see tor page [7xcomvycizikj5p7.onion](url)

**Comment by Elmit2015** [comment]
How to do that?

**Comment by cdecker** [comment]
You have quite a few layers there that you might want to unwind a bit:

 - Try calling `lightning-cli getinfo` from inside of the container (`sudo docker exec -ti bash` followed by `lightning-cli getinfo`)
 - Then try the same from outside of the container (`sudo docker exec lightning lightning-cli getinfo`)
 - Then try to put that into the PHP script and see if that works (before wrapping it in a script that rewrites the commands)
 - Then you can see if the entire stack works, including the script

If this fails at some point let us know the error you encounter and we can probably help you debug what part of the stack isn't working :wink:

**Comment by Elmit2015** [comment]
Sorry, I forgot a very important part. Running the php from command line works, but not when I run it within a php program on the web. The web browser runs as www-data

ps aux |grep nginx
```
root      1945  0.0  0.0 144952  4372 ?        Ss   Apr06   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data  1947  0.0  0.0 147252  8220 ?        S    Apr06   0:00 nginx: worker process
www-data  1949  0.0  0.0 147252 10040 ?        S    Apr06   0:06 nginx: worker process
www-data  1952  0.0  0.0 147252  6540 ?        S    Apr06   0:00 nginx: worker process
www-data  1953  0.0  0.0 147252  6540 ?        S    Apr06   0:00 nginx: worker process
```
grep www-data /etc/group
```
www-data:x:33:ronald
docker:x:999:ronald,www-data
```

**Comment by Elmit2015** [comment]
Of course it was my fault ;-)
I could not find the www-data working, so I added to log to the command, ... but that did not work, ... removing that solved the problem.

I got now one of the commands ready. Have a look at:
https://tools.elmit.com/Lightning/listnodes.php
https://tools.elmit.com/Lightning/listfunds.php

There are some empty columns, like globalfeatures and global_features. Are these place holders for future or forgotten to remove?
What should tell me "output" in listfunds - Outputs ?

**Comment by cdecker** [comment]
The `outputs` field in `listfunds` are your on-chain funds, while `channels` are your off-chain funds.

The duplication of some fields will soon be removed, they were left in there for the deprecation period to allow users to upgrade their software :wink: 

Am I correct in assuming this issue is resolved?

**Comment by Elmit2015** [comment]
yes, closed
