### ISSUE TITLE
Question/help : JSON-RPC verbose help

### ISSUE THREAD

**Issue by darosior** [ElementsProject/lightning#2555]
I noticed some messages stating `HELP! Please contribute a description for this json_command!` in the JSON-RPC `help` call (`lightning-cli -J help` or `curl` it) while doing a [C++ wrapper](https://github.com/darosior/lightning-cpp) for the JSON-RPC interface, so I wanted to make a PR to fill the `verbose` help for each call.

But first I wanted to know if there is any directive to what should figure in this field ? Should I basically copy the man (after the first sentence giving a short description) or should it be more concise ?
Also, some calls have already a detailed description (in the `description` field), what should figure in the `verbose` field then ? e.g. :
```shell
    {
        "command" : "getroute id msatoshi riskfactor [cltv] [fromid] [fuzzpercent] [exclude] [maxhops]",
        "description" : "Show route to {id} for {msatoshi}, using {riskfactor} and optional {cltv} (default 9). If specified search from {fromid} otherwise use this node as source. Randomize the route with up to {fuzzpercent} (default 5.0). {exclude} an array of short-channel-id/direction (e.g. [ '564334x877x1/0', '564195x1292x0/1' ]) from consideration. Set the {maxhops} the route can take (default 20).",
        "verbose" : "HELP! Please contribute a description for this json_command!"
    },
```
EDIT: It mays seems a little bit useless when using the CLI because there is the man page, but it would be helpful for an application (e.g. people using the wrapper ^^).

**Comment by cdecker** [comment]
We currently copy over the first few sentences of the man-page in an attempt to be helpful, though we may at some point just remove the verbose struct-member and point users to the man-page directly.
