### ISSUE TITLE
Keep getting "[lncli] rpc error: code = Unknown desc = peer disconnected" when attempting to open channels with certain nodes

### ISSUE THREAD

**Issue by Z-and** [ElementsProject/lightning#2556]
I've encountered this issue with about half the nodes I tried to open channels with. I can connect as peer without an issue but whenever I open a channel it stalls then eventually gives me the following output.

`[lncli] rpc error: code = Unknown desc = peer disconnected`

Below is my node status, everything looks to be okay. Not sure why this keeps happening.

```
    "identity_pubkey": "032f0d2d9f9b14b3a40488a1f2f255ecfd73b2272ae6d8399cbf067b0b55913281",
    "alias": "Zand",
    "num_pending_channels": 0,
    "num_active_channels": 5,
    "num_peers": 8,
    "block_height": 571088,
    "block_hash": "0000000000000000001d96002b130121b32b5b1d91bedbd637ae9900f1d9ce76",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "uris": [
        "032f0d2d9f9b14b3a40488a1f2f255ecfd73b2272ae6d8399cbf067b0b55913281@173.52.56.208:9735"
    ],
    "best_header_timestamp": "1554931014",
    "version": "0.5.2-beta commit=v0.5.2-beta",
    "num_inactive_channels": 1
```

**Comment by billygarrison** [comment]
This is the repo for c-lightning. For LND, check out https://github.com/lightningnetwork/lnd

**Comment by Z-and** [comment]
Wow sorry, not sure how it ended up here. Must not have been paying attention.
