### ISSUE TITLE
listchannels lists additional channel(s) when specifying source

### ISSUE THREAD

**Issue by billygarrison** [ElementsProject/lightning#2558]
### Issue and Steps to Reproduce
`lightning-cli listchannels source=$SOME_NODE_ID | grep $SOME_OTHER_NODE_ID` returns one result, as I expected.

But that channel doesn't show up when I use `lightning-cli listchannels | grep $SOME_OTHER_NODE_ID`.

I would expect `listchannels` to list all known channels, and specifying the source would return a subset of that list.

### `getinfo` output
```
{
  "id": "02843833374b6c42daa4b780df2066a9985cb8cf97bc4566dd63cf693d32cbf7b5",
  "alias": "BillyGarrison",
  "color": "009900",
  "num_peers": 24,
  "num_pending_channels": 0,
  "num_active_channels": 24,
  "num_inactive_channels": 0,
  "address": [
    {
      "type": "ipv4",
      "address": "142.134.28.93",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv4",
      "address": "0.0.0.0",
      "port": 9735
    }
  ],
  "version": "v0.7.0",
  "blockheight": 571113,
  "network": "bitcoin",
  "msatoshi_fees_collected": 17368,
  "fees_collected_msat": "17368msat"
}
```

**Comment by billygarrison** [comment]
FYI the source node ($SOME_NODE_ID) is: 0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4

And the other node ($SOME_OTHER_NODE_ID) is:
02809e936f0e82dfce13bcc47c77112db068f569e1db29e7bf98bcdd68b838ee84

**Comment by rustyrussell** [comment]
Yes, this is a known bug, triggered by > 32k channels.  We don't list them all in listchannels due to counter wrap!

The good news is that it's fixed in master....
