### ISSUE TITLE
How to run benchmark.py

### ISSUE THREAD

**Issue by wly1996** [ElementsProject/lightning#2600]
I am learning c-lightning now, and I want to know how to run the "/tests/benchmark.py" so that I can compare the efficiency between the original file and my own changes. Thank you so much!

**Comment by cdecker** [comment]
I usually run them using the following:

```
TEST_DEBUG=0 py.test -vvv tests/benchmark.py -s
```

Setting the variable `TEST_DEBUG=0` reduces the verbosity of the tests, while `-s` shows output as it is produced (using `tqdm` for progress bars, which you might need to `pip install tqdm`). You will also need all of the test dependencies (`pip install -r tests/requirements.txt`).

**Comment by wly1996** [comment]
Thank you so much,  because I am new to this project and Python. Could please tell me how to use these codes?

**Comment by wly1996** [comment]
After I run pip3 install pylightning, this finally works, sincerely thanks

**Comment by cdecker** [comment]
No problem :-)
