### ISSUE TITLE
Unknown command 'pay'

### ISSUE THREAD

**Issue by martijnbolt** [ElementsProject/lightning#2607]
### Issue 
./lightning-cli pay
{
   "code" : -32601,
   "message" : "Unknown command 'pay'"
}

### Steps to Reproduce
1) I've compiled a fresh download yesterday. Without any special args.

2) Then made a config file:
```
cat .lightning/config
network=bitcoin
alias=martijnbolt.com
rgb=983200
log-level=unusual
#debug or unusual
log-file=lightningd.log
```

3) I run without args as user
```
./lightningd &
```

### useful information
```
./lightning-cli listconfigs
{
   "# version" : "v0.7.0-278-gf82e779",
   "rgb" : "983200",
   "alias" : "martijnbolt.com",
   "pid-file" : "lightningd-bitcoin.pid",
   "log-level" : "UNUSUAL",
   "log-prefix" : "lightningd(17212):",
   "log-file" : "lightningd.log",
   "lightning-dir" : "/home/user/.lightning",
   "rpc-file" : "lightning-rpc",
   "daemon" : "false",
   "ignore-fee-limits" : false,
   "watchtime-blocks" : 144,
   "max-locktime-blocks" : 2016,
   "funding-confirms" : 3,
   "commit-fee-min" : 200,
   "commit-fee-max" : 2000,
   "commit-fee" : 500,
   "cltv-delta" : 14,
   "cltv-final" : 10,
   "commit-time" : 10,
   "fee-base" : 1000,
   "rescan" : 15,
   "fee-per-satoshi" : 10,
   "min-capacity-sat" : 10000,
   "offline" : "false",
   "autolisten" : true,
   "network" : "bitcoin",
   "allow-deprecated-apis" : true,
   "autocleaninvoice-cycle" : 0,
   "autocleaninvoice-expired-by" : 86400,
   "always-use-proxy" : false,
   "disable-dns" : "false"
}
```

### `getinfo` output
```
./lightning-cli getinfo | jq [.]
[
  {
    "id": "035eef0b6d7c23b22fe39188ce6668a4b746797aec59cbf650fde3d49e465c7514",
    "alias": "martijnbolt.com",
    "color": "983200",
    "num_peers": 2,
    "num_pending_channels": 0,
    "num_active_channels": 2,
    "num_inactive_channels": 0,
    "address": [],
    "binding": [
      {
        "type": "ipv6",
        "address": "::",
        "port": 9735
      },
      {
        "type": "ipv4",
        "address": "0.0.0.0",
        "port": 9735
      }
    ],
    "version": "v0.7.0-278-gf82e779",
    "blockheight": 573971,
    "network": "bitcoin",
    "msatoshi_fees_collected": 0,
    "fees_collected_msat": "0msat"
  }
]
```

**Comment by cdecker** [comment]
Thanks @martijnbolt, that is one of the most detailed reports we have ever gotten :-)

 - Where are you running `./lightningd` from? If you checked out in a directory `$SRC` are you running from inside `$SRC/lightningd` or directly from `$SRC`? 
 - Do you have a file `$SRC/plugins/pay`? If not try `make plugins/pay`, that should build the plugin.
 - If you're ok running this as root, you can also install `lightningd` system-wide using `sudo make install`. That should copy all the binaries to the correct paths in your system.

**Comment by martijnbolt** [comment]
Thanks! I figured you guys like details a lot :-)

installing system wide as root helped.

Now the pay module shows up:
root     27662  0.0  0.3   5356  2340 pts/0    S    13:28   0:00 /usr/local/bin/../libexec/c-lightning/plugins/pay

Thanks again!

**Comment by cdecker** [comment]
Awesome, glad it worked out :tada:
