### ISSUE TITLE
Segfault when reconnecting after an incomplete open flow

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#261]
While testing agains lnd we noticed that if the channel is rejected for whatever reason during the open_channel flow and the node reconnects then `lightningd` will segfault.

**Comment by rustyrussell** [comment]
Hmm, what's in crash.log?  If we fail during open, we should simply be forgetting the peer.

The other side reconnects before we've dealt with the failed open... ah, oops, I added a bug here.  Let me figure out how to test this case.  Think I'll need some new infrastructure.

**Comment by cdecker** [comment]
#263 should be helping here, but we may have a lingering issue when `lightningd` restarts and gets a reconnect. Will try to reproduce this with your new blackholing support.
