### ISSUE TITLE
listforwards > received_time, resolved_time return strange values...

### ISSUE THREAD

**Issue by gonzzza007** [ElementsProject/lightning#2621]
Hi! I don't get the logic of the new received_time, resolved_time data. Sometimes I get the timestamp, but sometimes something like 'time passed' is returned. Also when I parse this timestamp, i get year 2010. 

Here is the output of `listforwards` from my c-lightning node (v0.7.0-310-gbc5dbb6, Ubuntu 18.04.2 LTS)
{
           ...
         "status" : "settled",  
         "received_time" : 1266874889.150,  
         "resolved_time" : 0.362  
      },
      {
         ...
         "status" : "settled",
         "received_time" : 1.722,
         "resolved_time" : 1266874889.552
      },
      {
         ...
         "status" : "settled",
         "received_time" : 1266874888.617,
         "resolved_time" : 1266874889.568
      },

**Comment by cdecker** [comment]
Does this database predate the 0.7.0 release? If yes the database might simply be missing the fields. Can you share the output of the following:

```
sqlite3 ~/.lightning/lightningd.sqlite3 "select in_htlc_id, out_htlc_id, received_time, resolved_time from forwarded_payments"
```

That should show the raw data that is backing this JSON-RPC result.

**Comment by gonzzza007** [comment]
The output is 27kb, but here is the last couple of screens:
|||  
|||  
|||
|||
13413|13414||
13411|13412||
13415|13416||
13420|13421||
13422|13423||
13424|||
13426|||
13428|||
13430|||
13432|||
13434|||
13436|||
13438|||
13440|||
13442|||
13444|||
13446|||
13448|||
13450|||
13452|||
13454|||
13456|||
13458|||
13460|||
13462|||
13464|||
13466|||
13468|||
13471|||
13473|||
13475|13476||
13477|13478||
13479|13480||
13481|13482||
13483|13484||
13485|13486||
13487|13488||
13489|13490||
13492|13493||
13494|13495||
|13497||
|13499||
13500|||
13502|||
13504|||
13507||-1081067325|99058400
13509||-2045906293|-1074171808
13512|13513|-1315258757|-328188795
13515||277374087|-1491680811
||965909304|-908257452
|13520|918186405|-783665429
|13522|2120596677|-327582645
|13524|1989001756|-46752613
|13526|432499169|235257926
|13532|560938925|-1301877568
|13535|498086256|-1227163557
|13538|-1283536577|-464886060
13553||-559228498|362705565
13581|13582|1722881078|-156637806
13583|13584|-1092076550|-141391883
13586|13587|1878600230|-495736192

**Comment by gonzzza007** [comment]
ps. I am using this c-lightning node almost a year now.

**Comment by gonzzza007** [comment]
well thanks a lot guyz!

**Comment by ZmnSCPxj** [comment]
Maybe this?

https://github.com/ElementsProject/lightning/blob/09761cd4c967e50b41f98a6a32d3092d7d0a26bc/wallet/db.c#L1166-L1170

The numbers in the database look oddly low to me.
Possibly the `time_t` on the platform is 32-bit, and multiplying the `tv_sec` by `NSEC_IN_SEC` overflows.

A typical 2019 `tv_sec` would be 1546383647.  Multiply by `NSEC_IN_SEC` and it would definitely overflow a 32-bit number.  Probably need to convert to u64 *before* multiplying.

This will not fix the database retroactively but will at least fix future databases.
