### ISSUE TITLE
Opening 2nd LN-node channel to self, still no inbound capacity

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#2651]
Situation: node 1 with outgoing channels, node 2 with 1 channel to node 1 for inbound capacity. Still getting the error  "warning_capacity" : "No channels have sufficient incoming capacity" when making an invoice from node 1. 

Also, rebalance doesn't work on node 1, with the warning "code': 205, 'message': 'Could not find a route" 

Having a channel open in the direction of node 1 *should* provide for incoming capacity to node 1, or am I missing something?

**Comment by ZmnSCPxj** [comment]
Can you provide actual numbers?

Lightning requires a "channel reserve", I believe 1%, that cannot be spent.  Did you deduct this from the node 1 incoming capacity to determine the actual node 1 incoming capacity?

For the rebalance, please put in a separate report.  Does node 2 have any other channels?

**Comment by Coinomatron** [comment]
I don't think the channel reserve is part in this, node 2 (that opened a channel to node 1 for incoming capacity for node 1) has a reserve of 1780 sats on a channel amount of 177914 sats. I asked for a payment of 45000 sats, but got the capacity error on node 1. Node 1 has about 500000 sats in 3 different channels, all outgoing. Channel 4 is with node 2.

Node 2 doesn't have any other channels. 

I can make another issue for the rebalancing, but I think it has to do with node 1 not seeing the channel with node 2 as incoming capacity. They're both behind the same ip, on different ports though.

**Comment by cdecker** [comment]
> Node 2 doesn't have any other channels.

How are you expecting to rebalance? By creating an invoice on node 1 and paying it from node 2? The `warning_capacity` takes into account the current channel balances and will ignore unannounced channels, so if you don't have 6 confirmations that may be causing it.

**Comment by Coinomatron** [comment]
Hm, no it's well beyond 6 confirmations. In the command line on node 1, rebalancing wants 2 short_channel_id's, one for an inbound channel id and one for outbound channel id. Perhaps naive to think it would be sort of a circular payment, since I *thought* that opening a channel from node 2 to 1 would give node 1 inbound capacity. 

So I take it node 2 needs to have more channels for rebalancing to work. 

Apart from that, I don't understand why node 1 doesn't see the inbound channel's funds from node 2 as incoming capacity. What am I missing here?

**Comment by fiatjaf** [comment]
> Node 2 doesn't have any other channels.

To understand what is missing you must be able to imagine (or draw) a graph with many nodes in it. To receive anything from any other node in the network there has to be a path between the payer node and Node1.

In your case, there's not. In your case, only Node 2 can pay Node 1.

**Comment by Coinomatron** [comment]
Ok, I'll test it when I've added some channels to node 2. Thanks for the replies, closing for now.

**Comment by cdecker** [comment]
Oh, I see you were trying to use the rebalance plugin. That requires indeed that there is a cycle in the graph that can be used to rebalance.

**Comment by Coinomatron** [comment]
So the rebalancing doesn't work, since node 2 doesn't have any *incoming* capacity. Tried to open a channel to node 2 from node 1, but got "Peer already CHANNELD_NORMAL". How do two nodes then fund each other, if I get this error when trying to open mutual channels?

**Comment by ZmnSCPxj** [comment]
>How do two nodes then fund each other, if I get this error when trying to open mutual channels?

lightningd is currently constrained to only have one channel between any two peers.  Implementing splice "should" fix that, though specs work on splicing is still ongoing.
