### ISSUE TITLE
pay plugin regression: no longer reports `PAY_IN_PROGRESS`

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#2653]
Review of the code shows that we no longer return `PAY_IN_PROGRESS` from the `pay` plugin.

This is fine if payments never stall.

But if payments stall, it is impossible currently to differentiate:

1.  We timed out, but a payment attempt is still ongoing (and that payment attempt might remain stuck until the `CLTV` we imposed on making the `sendpay`).
2.  We timed out, while no payment attempt is ongoing.

Before `pay` was a plugin, we would correctly report `PAY_IN_PROGRESS` if we timed out while a payment was ongoing and intermediate hop nodes were dicking around with our money.

In current `pay` plugin, we always report `PAY_STOPPED_RETRYING` ***even if a payment attempt is pending***.

**Comment by fiatjaf** [comment]
What does this change from the UI point of view? How do you know if a payment has failed or succeeded after getting a response that days it's "in progress"? Does it deal with the case at https://github.com/ElementsProject/lightning/issues/2521?

**Comment by ZmnSCPxj** [comment]
https://github.com/ElementsProject/lightning/blob/7e7358ec1e327756aa89a81eb2cf454c5f889dcd/doc/lightning-pay.7.txt#L93-L94

Intent is that if you get `PAY_IN_PROGRESS` (error code 200) you use `listpays` to monitor its status, or reissue `pay` if you want to keep trying, or `waitsendpay` if you only want to wait for the last payment (`waitsendpay` has its own status and can return `PAY_IN_PROGRESS` too).

I wonder if we need to redesign the `pay` system to have a lower-level, explicitly-async interface for "real" UIs.

**Comment by rustyrussell** [comment]
This is a good catch; I've been looking at the same thing.  But I think we should *never* return while a payment is still in progress.  These days you can still submit more commands while one is pending, and it's far more intuitive than a "failure" which isn't really one.

**Comment by ZmnSCPxj** [comment]
Problem with "never return" is: how can higher-layer wallets provide information about the ongoing attempt to the user if it is stuck for several days?

Maybe we should go for the async approach I proposed long ago, something like:

* `startpay` - initiate the pay attempt.
* `querypay` - dequeue any messages (i.e. the current `failures` array) for a pay attempt.
* `waitpay` - dequeue any messages for a pay attempt, wait if the queue is empty.
* `stoppayretry` - stop retrying; cannot cancel ongoing payment attempt.

The last "message" from a pay attempt would then contain whether it ultimately succeeded or failed.

**Comment by ZmnSCPxj** [comment]
xref. https://github.com/ElementsProject/lightning/issues/1088#issuecomment-368432267

https://github.com/ElementsProject/lightning/issues/1088#issuecomment-368492974

https://github.com/ElementsProject/lightning/issues/1088#issuecomment-369904740

**Comment by fiatjaf** [comment]
Why are you thinking about user-facing UIs only? I heard from some @cdecker talk that c-lightning's first intended use-case was servers (I think the difference is subtle, but not null).

**Comment by fiatjaf** [comment]
Isn't the current `sendpay`/`waitsendpay` combination enough to build such async interface?

**Comment by rustyrussell** [comment]
They can call paystatus and get the ongoing status though.  That's the advantage of allowing parallel commands.

**Comment by ZmnSCPxj** [comment]
>Why are you thinking about user-facing UIs only? I heard from some @cdecker talk that c-lightning's first intended use-case was servers (I think the difference is subtle, but not null).

I am not thinking about "user-facing UIs ***only***".
That is why I said we should retain the existing `pay` with the improved behavior of "never return until we succeed/fail", but instead of that being the *only* interface, to have it as a wrapper of an intermediate-level interface.
`pay` == `on timeout { stoppayretry} ; startpay; while (!done) { waitpay; }`

>Isn't the current `sendpay`/`waitsendpay` combination enough to build such async interface?

Currently yes.  But the intent is that `sendpay` will be "very low level".  In the future, multipart payments (bass amp) will be possible, so should `sendpay` implement multipart or not?

> They can call paystatus and get the ongoing status though. That's the advantage of allowing parallel commands.

Yes, but we only allow parallel commands on *our* side.  Some RPC libraries may not allow parallel commands, for simplicity.  Even if they do, it may be easier to implement in a single-threaded program to always block, and they would have to make the call async anyway.

(arguable that clients *should* make an effort to make calls to us async on their side, of course)
