### ISSUE TITLE
Feature: withdraw to multiple addresses

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#2679]
Because batching is a good thing, especially if we want to support c*stodial services that might have multiple withdrawal requests from its victims.

It is also a good preparation for eventually implementing #1936 , which requires building transactions that pay to multiple outputs, by combining a multi-output withdraw with #2672 (by using our own wallet as the "external" wallet).

**Comment by trueptolemy** [comment]
@ZmnSCPxj  The present format is: `*txprepare*` `destination` `satoshi` `[feerate]` `[minconf]`.
What about letting `txprepare` also support another format:
`*txprepare*` `{{'destination': destination1, 'satoshi': amount1}, {'destination': destination2, 'satoshi': amount2}, {'destination': destination3, 'satoshi': amount3}}` `[feerate]` `[minconf]`

**Comment by ZmnSCPxj** [comment]
This makes `help` for `txprepare` rather ambiguous: which format do we inform?

It might be better to *switch* `txprepare` to the latter format and support the existing format for back-compatibility until we remove it in a later release, a la #2914

**Comment by ZmnSCPxj** [comment]
While `txprepare` now allows multiple outputs, there is no convenient user command for withdrawing to multiple addresses yet.
