### ISSUE TITLE
Feature: open channel with specific UTXO

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#2682]
In addition to `all` it would be nice if the `satoshi` argument for `fundchannel` can be a specific UTXO.

**Comment by kristapsk** [comment]
See #2105

**Comment by darosior** [comment]
I gave a try at this one. I think it would be a nice feature but as mentionned in #2105 it requires either a duplication or a modification of the utxos selection code : @cdecker does it worths it ?

**Comment by ZmnSCPxj** [comment]
Have multiple entry points into the wallet code, one where the wallet selects UTXOs, the other where the caller selects UTXOs.

**Comment by darosior** [comment]
> Have multiple entry points into the wallet code, one where the wallet selects UTXOs, the other where the caller selects UTXOs.

Thank you.
