### ISSUE TITLE
Check bitcoind version atstartup

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#2697]
Root cause of #2687 was that user had unsupported bitcoind version.  So we should probably determine what bitcoind versions we need and check for those specifically.

**Comment by molxyz** [comment]
@ZmnSCPxj   I have been running 3 c-lightning nodes on testnet, one with bitcoind v0.17.1 and two with bitcoind v0.18.0, no issues for me.  If you need proof I can provide.  Also, I'm pretty sure c-lightning can run with bitcoind v0.17.0 too.  Not sure which version of bitcoind can be unsupported?

**Comment by darosior** [comment]
> Root cause of #2687 was that user had unsupported bitcoind version. So we should probably determine what bitcoind versions we need and check for those specifically.

No, `estimatesmartfee`'s second parameter has always been here https://bitcoincore.org/en/doc/0.16.0/rpc/util/estimatesmartfee/ . Checking bitcoind version is not a bad idea though

**Comment by trueptolemy** [comment]
Need confirm, now the lowest version clightning supports is still version 0.15? or like darosior said, 0.16?

We need also call `getnetworkinfo` to check version field at the beginning. This process seems same as the check for blockchain.

**Comment by darosior** [comment]
> Need confirm, now the lowest version clightning supports is still version 0.15? or like darosior said, 0.16?
> 
> We need also call `getnetworkinfo` to check version field at the beginning. This process seems same as the check for blockchain.

I didn't say that clightning supports only until 0.16, just that the second parameter of `estimatesmartfee` has been here since `estimatesmartfee` has been considered usable (0.15 release). Introduction of the second parameter https://github.com/bitcoin/bitcoin/pull/10199/files#diff-9651347c8e00bed3ddc7631de569406dR830 .
Otherwise to try to help you with your question, if the second parameter of `estimatesmartfee` is the treshold condition for clightning support, then 0.15 should be fine.

**Comment by trueptolemy** [comment]
@ZmnSCPxj 
I checked APIs(`estimatesmartfee`, `sendrawtransaction`, `getblock`, `getblockcount`, `getblockhash`, `gettxout` and `getblockchaininfo`) of all the formal versions(except `rc` versions), that include v0.15.0, v0.15.0.1, v0.15.1, v0.15.2, v0.16.0, v0.16.1, v0.16.2, v0.16.3, v0.17.0, v0.17.0.1, v0.17.1 and v0.18.0, and can confirm the parameters of these APIs for such versions are all ok.

---
About v0.17.1 for #2687  , @darosior  are right, the v0.17.1 are supported, it's not the fault of parameters for `estimatesmartfee`.(and note: no more analogous issues about the version v0.17.1)

> 2019-05-31T18:22:32.564Z lightningd(10275): bitcoin-cli estimatesmartfee 2 CONSERVATIVE exited with status 1

The error code is `1`, and the `1` means

> `RPC_MISC_ERROR                  = -1,  //!< std::exception thrown in command handling`

A common reason in this case is `bitcoind` was down.

In other hand, the RPC command or parameters error should be:

> `RPC_INVALID_PARAMETER           = -8,  //!< Invalid, missing or duplicate parameter`

> `RPC_IN_WARMUP                   = -28, //!< Client still warming up`

> `RPC_METHOD_DEPRECATED           = -32, //!< RPC method is deprecate`

> `RPC_TYPE_ERROR                  = -3,  //!< Unexpected type was passed as parameter`

---
Thus, the unsupported version are still the versions older than v0.15.0 and we only need check if the version older than v0.15.0.

**Comment by trueptolemy** [comment]
And `getnetworkinfo` is also availiable for these versions.
