### ISSUE TITLE
Feature: Cancel a `fundchannel_start`ed channel after `fundchannel_complete`

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#2740]
Needed to fully implement `multfundchannel` #1936 

I would prefer extending `fundchannel_cancel` to also work after `fundchannel_complete` (as this simplifies a `multifundchannel` implementation: we can just install destructors that `fundchannel_cancel` everything that has been `fundchannel_start`ed, and delete the destructors once all `fundchannel_complete`s finish correctly, i.e. the "kickable RAII pattern"),

Alternately we can add a **non-`dev`** `forgetfundchannel` which `error`s the peer and then forgets the channel, but can only be called after `fundchannel_complete`.

+1 if we can implement a simple check to ensure that the funding tx has 0 confirmations still, as a basic "sanity check" of correct usage.

Either way we should immediately forget the channel if we receive `error` during `CHANNELD_AWAITING_LOCKIN` if we are fundee.

-----

This is needed to handle error cases in `mutlifundchannel`.

Suppose we want to fund to node `$A` and `$B`:

    ADDRA=$(fundchannel_start $A $AVAL)
    ADDRB=$(fundchannel_start $B $BVAL)

    TX=$(txpreparemultidest "[{\"destination\" : $ADDRA, \"amount\" : $AVAL}, {\"destination\": $ADDRB, \"amount\" : $BVAL}]")

    fundchannel_complete $A $TX
    if !fundchannel_complete $B $TX; then
        # Note: cancel $A after complete fundchannel of $A, because
        # we can never safely broadcast the tx now.
        fundchannel_cancel $A || true # ignore errors.
        txcancel $TX
    else
        txbroadcast $TX
    fi

**Comment by rsbondi** [comment]
I have been experimenting with doing mutlchannel funding in a [plugin](https://github.com/rsbondi/multifund).  What I discovered is that if you call `close` with the peer id, after `fundchannel_complete` this could be a workaround since no valid tx has been broadcast, but less than ideal since the channel is not actually forgotten, although it would be trivial for the plugin to update the database, not sure if there would be any side effects.

**Comment by ZmnSCPxj** [comment]
It is hacky and we have a pending issue to change `close` behavior (which might affect how this behaves). The peer also needs to learn that the channel is cancelled and it should not wait for the closing to confirm, else both peer and self have to edit their databases.

**Comment by trueptolemy** [comment]
I'd like to try first way, extending `fundchannel_cancel`, and see the effect :-)

**Comment by trueptolemy** [comment]
@ZmnSCPxj I find an uncertain place: should we check if the transaction has been broadcast? (by using `bitcoind_gettxout`).
And I also find this is the function of `dev-forget-channel`? Integrating `dev-forget-channel` into `fundchannel_cancel` seems the easier way.

**Comment by ZmnSCPxj** [comment]
> +1 if we can implement a simple check to ensure that the funding tx has 0 confirmations still, as a basic "sanity check" of correct usage.

So if it is easy to do this check, yes, we do check. If not easy, leave it to caller to use correctly.

The other side is receive of `error` during `CHANNELD_AWAITING_LOCKIN`.

**Comment by fiatjaf** [comment]
I don't understand what I was the solution to this issue. I have a pending channel from `fundchannel_complete` with a transaction I've never broadcasted. How can I get rid of it?

`fundchannel_cancel` gives me

```
{
   "code": -1,
   "message": "No channel funding in progress."
}
```

(the same happens when the other party calls that.)

`close` gives me

```
{
   "code": -1,
   "message": "Channel is in state AWAITING_UNILATERAL"
}
```

If the other party calls it they get an empty `{}`.

Here's the channel:

```
{                                                                                                                     
  "state": "AWAITING_UNILATERAL",                                                                                     
  "scratch_txid": "731dca13c7521f2733edc7dcb3b766311258720c66832c3b51c825148a28b8ca",                                 
  "channel_id": "5109814bb9f7685e11457978d4a55b3af60a1a307856fb86860cd670ff2d1d2b",                                   
  "funding_txid": "2a1d2dff70d60c8686fb5678301a0af63a5ba5d4787945115e68f7b94b810951",                                 
  "private": false,                                                                                                   
  "funding_allocation_msat": {                                                                                        
    "025a14b8ed40583d67aec92da19453e0b2d1fbbf75f96f85d3dd0ff61a51ee0490": 0,                                          
    "02bed1812d3824f7cc4ccd38da5d66a29fcfec146fe95e26cd2e0d3f930d653a8d": 800000000                                   
  },                                                                                                                  
  "funding_msat": {                                                                                                   
    "025a14b8ed40583d67aec92da19453e0b2d1fbbf75f96f85d3dd0ff61a51ee0490": "0msat",                                    
    "02bed1812d3824f7cc4ccd38da5d66a29fcfec146fe95e26cd2e0d3f930d653a8d": "800000000msat"                             
  },                                                                                                                  
  "msatoshi_to_us": 800000000,                                                                                        
  "to_us_msat": "800000000msat",                                                                                      
  "msatoshi_to_us_min": 800000000,                                                                                    
  "min_to_us_msat": "800000000msat",                                                                                  
  "msatoshi_to_us_max": 800000000,                                                                                    
  "max_to_us_msat": "800000000msat",                                                                                  
  "msatoshi_total": 800000000,                                                                                        
  "total_msat": "800000000msat",                                                                                      
  "dust_limit_satoshis": 546,                                                                                         
  "dust_limit_msat": "546000msat",                                                                                    
  "max_htlc_value_in_flight_msat": 18446744073709552000,                                                              
  "max_total_htlc_in_msat": "18446744073709551615msat",                                                               
  "their_channel_reserve_satoshis": 8000,                                                                             
  "their_reserve_msat": "8000000msat",                                                                                
  "our_channel_reserve_satoshis": 8000,                                                                               
  "our_reserve_msat": "8000000msat",                                                                                  
  "spendable_msatoshi": 789266000,                                                                                    
  "spendable_msat": "789266000msat",                                                                                  
  "htlc_minimum_msat": 0,                                                                                             
  "minimum_htlc_in_msat": "0msat",
  "their_to_self_delay": 144,
  "our_to_self_delay": 144,
  "max_accepted_htlcs": 30,
  "status": [
    "AWAITING_UNILATERAL:Will attempt reconnect in 2 seconds"
  ],
  "in_payments_offered": 0,
  "in_msatoshi_offered": 0,
  "in_offered_msat": "0msat",
  "in_payments_fulfilled": 0,
  "in_msatoshi_fulfilled": 0,
  "in_fulfilled_msat": "0msat",
  "out_payments_offered": 0,
  "out_msatoshi_offered": 0,
  "out_offered_msat": "0msat",
  "out_payments_fulfilled": 0,
  "out_msatoshi_fulfilled": 0,
  "out_fulfilled_msat": "0msat",
  "htlcs": []
}
```

Please help!

**Comment by darosior** [comment]
> {                                                                                                                     
  "state": "AWAITING_UNILATERAL",                                                                                     
  "scratch_txid": "731dca13c7521f2733edc7dcb3b766311258720c66832c3b51c825148a28b8ca",                                 
  "channel_id": "5109814bb9f7685e11457978d4a55b3af60a1a307856fb86860cd670ff2d1d2b",                                   
  "funding_txid": "2a1d2dff70d60c8686fb5678301a0af63a5ba5d4787945115e68f7b94b810951",                                 
  "private": false,       

The funding transaction never made it to the block chain, you can just get rid of the zombie channel with `dev-forget-channel`.

**Comment by fiatjaf** [comment]
How can I get that command?
