### ISSUE TITLE
`notify_disconnect` when remote peer sends `error`?

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#2741]
While studying to implement #2740, I tried to trace what `channeld` does when it receives an `error`.
As https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-January/000958.html suggests, instead of a new `funding_cancelled` message to free up a `multifundchannel` attempt in case one of the peers fails the funding process while the others have completed the initial commitment signing, we can use `error` instead to free up an attempt to open a channel, that fails for other reasons.

Briefly, a `multifundchannel` requires not only that we split up the funding process, but also that, if *some* of the peers succeed but *others* fail, we ***MUST*** fail the entire `multifundchannel` and tell the succeeded peers to stop wasting their time waiting for the channel to lock in, which will now never happen since we cannot broadcast the transaction.

I proposed the `funding_cancelled` message before, but it got bogged down in stupid arguments about resources and attacks on nodes rather than on the merits of the message itself, so the next best thing is to use the `error` message to tell the peer to forget a channel it accepted and signed commitments for, but which we are now very sure will never get confirmed because of other reasons (such as other peers failing the `multifundchannel`).

This is particularly bad for C-Lightning since we currently restrict each peer to have only one channel.  If our peer makes a `multifundchannel` attempt to us and we complete it faithfully, but another of *its* peers fails the same `multifundchannel`, then we will still hope for the funding to push through even if our peer wants to cancel it (unless we implement `funding_cancelled` or treat `error` during `CHANNELD_AWAITING_LOCKIN` as a proxy for `funding_cancelled`).

So I start the below analysis:

https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/channeld/channeld.c#L1858-L1870

Okay, so we find `handle_peer_gossip_or_error`: https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/common/read_peer_msg.c#L149-L151

And see this code: https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/common/read_peer_msg.c#L165-L173

`is_peer_error` clears `err` if the channel ID is unrecognized and is not all-0s.  If channel ID is unrecognized, and it is not all-0s (signifying "all channels failed") then the `error` should be ignored.

So if `err` is non-`NULL`, the remote node either said all channels failed, or the specific single channel that we support per peer is failed.  So we dive into `peer_failed_received_errmsg`:

https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/common/peer_failed.c#L52-L65

This basically sends the message `status_peer_error` to `lightningd`.  So we look for the handler of this message in `lightningd`. https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/lightningd/subd.c#L374-L384

The `errorcb` registered for `channeld` is here: https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/lightningd/channel_control.c#L304-L316

That is, `channel_errmsg`.  So we dive into `channel_errmsg`, and... what? https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/lightningd/peer_control.c#L393

Why does a peer `error`ing on us cause us to notify a disconnect?  Do we actually disconnect from an `error`ing peer?

Continuing further:

https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/lightningd/peer_control.c#L416-L418

So we proceed to `channel_fail_permanent` and we see also:

https://github.com/ElementsProject/lightning/blob/ea1c52f3806e64e4bcbf7dc644aab7787760cf61/lightningd/channel.c#L382

This does **not** disconnect to the peer --- it moves responsibility for the connection to `connectd`.

---

It seems to me that, if channel state is `CHANNELD_AWAITING_LOCKIN` and we are the fundee of the channel, `channel_errmsg` should simply forget the channel (the `error`ing node should be responsible for broadcasting its own unilateral close if it already broadcast the iniital funding transaction and it is not replaced with a better-fee version, which it should do itself before sending `error` to us anyway).

Of course, this behavior is bad when we move to dual-funded channels.  Maybe the "and we are the fundee of the channel" could be reworded to "and we did not put our own funds into the channel".

**Comment by darosior** [comment]
> That is, channel_errmsg. So we dive into channel_errmsg, and... what?

> This does not disconnect to the peer --- it moves responsibility for the connection to connectd.

FWIW I noticed that a fundchannel error causes a disconnection of the peer. Isn't it the intended behavior ?

**Comment by ZmnSCPxj** [comment]
In the `multifundchannel` case, suppose we want to fund to A and B with a single tx. A completes the protocol but B fails it before `commitment_signed`. We cannot safely broadcast the single tx now, but A is expecting it. If A is a C-Lightning node, then we cannot fund another channel with A (it is still waiting for the current channel with us), even though we know that we *could* complete the protocol with it. We can only send an `error` to tell it to forget the existing channel. Or wait for A to time out as a fubdee and forget the channel, but that is a long time (a week I think).

Or revive `funding_cancelled` message but that requires spec change.

If we do not implement keeping the connection live even after an `error` received then  large `multifundchannel` becomes risky: if even one of them fails, all of them disconnect? That is highly unreasonable.

**Comment by darosior** [comment]
> If we do not implement keeping the connection live even after an error received then large multifundchannel becomes risky: if even one of them fails, all of them disconnect? That is highly unreasonable.

Ok I understand now. Thank you.

**Comment by niftynei** [comment]
> If we do not implement keeping the connection live even after an error received then large multifundchannel becomes risky: if even one of them fails, all of them disconnect? That is highly unreasonable.

There's now an `openchannel_abort` message which will avoid disconnecting as well as communicating the intent to fail the opening of a channel.
