### ISSUE TITLE
Plugins not enabled in Docker produces: Unknown command 'pay'

### ISSUE THREAD

**Issue by JavierRSobrino** [ElementsProject/lightning#2748]
### Issue and Steps to Reproduce

I'm using Docker for both C-Lightning and Spark Wallet.

Spark wallet returns an error "Unknown command 'pay'" when trying to pay because the official docker image of c-lightning doesn't install or doesn't use the pay plugin by default.

Please compile and install all the plugins in the default image.

version: v0.7.0

Docker image:
v0.7.0 21 MB
Last update: 3 months ago

**Comment by cdecker** [comment]
This has effectively been fixed some time ago (before release 0.7.1) so any image created after that version should work correctly.

Please update your image and try again.
