### ISSUE TITLE
RPC in master is incompatible with pip upstream pylightning (hangs)

### ISSUE THREAD

**Issue by laanwj** [ElementsProject/lightning#2749]
It looks like recent changes to clightning upstream have made it incompatible with the current version of pylightning from pip. This was tested with:

- git commit e9ff8e4
- pylightning-0.0.7 (latest from pip)

strace output:
```
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/home/.../.lightning/lightning-rpc"}, 41) = 0
sendto(3, "{\"method\": \"getinfo\", \"params\": "..., 44, 0, NULL, 0) = 44
recvfrom(3, "{\"jsonrpc\":\"2.0\",\"id\":0,\"result\""..., 1024, 0, NULL, NULL) = 508
recvfrom(3, … (hangs forever)
```

It looks like it doesn't detect the new message separator so keeps waiting before returning the response. Using the exact version of pylightning from the repository works fine.

**Comment by cdecker** [comment]
Good catch, it was broken in commit https://github.com/ElementsProject/lightning/pull/2705/commits/aaaaf62b9cdfdb95059f5d8a8dd23e0025770d68. I'll release the new version which handles the cleaned up JSON formatting correctly.

**Comment by cdecker** [comment]
Updated:

```
pip install pylightning==0.0.7.3
```

@laanwj can you confirm that it worked?

**Comment by rustyrussell** [comment]
Yuck, I hadn't realized we would break that. Let's hack the extra space back in the JSON for another release.
