### ISSUE TITLE
I cannot find myself, where am I?

### ISSUE THREAD

**Issue by cryptid11** [ElementsProject/lightning#277]
```
root@alibaba:~# ln -s /root/repos/lightning/lightningd/lightningd /bin/lightningd
root@alibaba:~# lightningd --help
lightningd: I cannot find myself at (null) based on my name lightningd
```

pls help me, I need to find myself!

(`/root/repos/lightning/lightningd/lightningd --help` and `/bin/lightningd --help` are working)

**Comment by cryptid11** [comment]
Thanks, for speed! I have found myself now, and seems my name is "lightningd"!

**Comment by cdecker** [comment]
Existential crisis averted :smiley: 

Thanks for the report by the way ^^
