### ISSUE TITLE
Signal 6 crash when running listpeers

### ISSUE THREAD

**Issue by hsjoberg** [ElementsProject/lightning#2772]
### Issue and Steps to Reproduce

When running `listpeers`, c-lightning crashes with the log showing the following:

```
jun 25 10:05:03 raspberrypi lightningd[11067]: lightningd: bitcoin/tx.c:217: push_tx: Assertion `res == WALLY_OK' failed.
jun 25 10:05:03 raspberrypi lightningd[11067]: lightningd: FATAL SIGNAL 6 (version v0.7.1rc3)
jun 25 10:05:03 raspberrypi lightningd[11067]: 2019-06-25T10:05:03.370Z lightningd(11067): FATAL SIGNAL 6 (version v0.7.1rc3)
jun 25 10:05:07 raspberrypi systemd[1]: lightningd.service: Main process exited, code=killed, status=6/ABRT
jun 25 10:05:07 raspberrypi systemd[1]: lightningd.service: Unit entered failed state.
jun 25 10:05:07 raspberrypi systemd[1]: lightningd.service: Failed with result 'signal'.
```

Apparently an assertion in bitcoin/tx.c fails for some reason:
https://github.com/ElementsProject/lightning/blob/c1328b3fb78aa4fb43ca9dc27106aabe882f50d9/bitcoin/tx.c#L217

### `getinfo` output
```
{
   "id" : "03939ff69d65a13c4bb2585042e7eb7e75a7c77289ab5794d1b973721d86c6839c",
   "alias" : "CocoPi⚡",
   "color" : "f2a900",
   "num_peers" : 14,
   "num_pending_channels" : 0,
   "num_active_channels" : 14,
   "num_inactive_channels" : 0,
   "address" : [
      {
         "type" : "ipv4",
         "address" : "213.114.84.246",
         "port" : 9735
      },
      {
         "type" : "torv2",
         "address" : "hphtfkdy4zpefsnz.onion",
         "port" : 9735
      }
   ],
   "binding" : [
      {
         "type" : "ipv4",
         "address" : "192.168.1.106",
         "port" : 9735
      },
      {
         "type" : "ipv4",
         "address" : "127.0.0.1",
         "port" : 9735
      }
   ],
   "version" : "v0.7.1rc3",
   "blockheight" : 582357,
   "network" : "bitcoin",
   "msatoshi_fees_collected" : 19814,
   "fees_collected_msat" : "19814msat"
}
```

**Comment by ZmnSCPxj** [comment]
Looks like duplicates #2759

**Comment by hsjoberg** [comment]
@ZmnSCPxj you are probably right.
`sqlite3 ~/.lightning/lightningd.sqlite3 'SELECT HEX(last_tx) FROM channels;'` reveals this tx having no vout:
```
pi@raspberrypi:~/lightning $ bitcoin-cli decoderawtransaction 02000000018C5EA1E1AF45AF90B190A77FAC8AEB8DED95D27DAB8CACE9582BECA8FCC3B01700000000004D0AAE8000990DA420
{
  "txid": "a890b49a4981fd45f6e6d9ea05b2fe86bc75772047bb48f8f9078a16e6e1a80e",
  "hash": "a890b49a4981fd45f6e6d9ea05b2fe86bc75772047bb48f8f9078a16e6e1a80e",
  "version": 2,
  "size": 51,
  "vsize": 51,
  "weight": 204,
  "locktime": 547622297,
  "vin": [
    {
      "txid": "17b0c3fca8ec2b58e9ac8cab7dd295ed8deb8aac7fa790b190af45afe1a15e8c",
      "vout": 0,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "sequence": 2158889549
    }
  ],
  "vout": [
  ]
}
```

**Comment by tfthorpe** [comment]
I have the same problem, with an empty vout in one of my tx-s. I tried to follow the procedure in #2759 but I'm out of my depth with sqlite. The .dump command gives me a nice readable ascii format but I can't correlate any of the lines in the channels table with either the raw transaction or the decoded output from bitcoin-cli, so for now I'm stuck.
Would there be any workaround which stops c-lightning from crashing, even though it doesn't like the channel?

**Comment by rustyrussell** [comment]
I will add a workaround for rc4, since this is clearly not a once-off. Thanks.

**Comment by rustyrussell** [comment]
OK, can you tell me how old your c-lightning was (when you first installed it)?

Before 0.6.0, we had a case where we could create zero-output txs, but it seems unlikely that you all had installations that old.  Which means something else is creating them.

**Comment by tfthorpe** [comment]
" but it seems unlikely that you all had installations that old"
Well, my node's been up since mid Jan 18, if that helps... 
So you probably shouldn't worry about it. Thanks for the attention, though.

**Comment by rustyrussell** [comment]
Ah, OK.  Well, I have already implemented a workaround (don't print txids for those txs), and am now adding many more checks that we don't actually create such things again.

All good to have, anyway!

**Comment by rustyrussell** [comment]
Any chance you could quickly test that branch for me?

`git pull https://github.com/rustyrussell/lightning.git handle-zero-output-commitments`

**Comment by tfthorpe** [comment]
Yes, that seems to have fixed it, thanks.
Will try it more tomorrow, it's now 2am here.

**Comment by hsjoberg** [comment]
> OK, can you tell me how old your c-lightning was (when you first installed it)?
>
> Before 0.6.0, we had a case where we could create zero-output txs, but it seems unlikely that you all had installations that old. Which means something else is creating them.

@rustyrussell My node is from early 2018, so I have probably been running versions before 0.6. I don't think any channels from that time is still open though.

960bfb89f5272a392aa5235152b555bbfd8d82fc seems to fix the issue for me as well!
