### ISSUE TITLE
Shouldn't log_unusual for failed broadcast on unilateral close

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#2790]
### Issue and Steps to Reproduce

```
2019-07-03T09:26:52.806Z [UNUSUAL] lightningd(26941): Broadcasting tx 02000...000000: 25 error code: -25?error message:?Missing inputs?
```

Especially since we now tag [UNUSUAL] it's a bit scary-looking!

Reported-by: @JavierRSobrino

**Comment by darosior** [comment]
Isn't broadcast error unusual on unilateral close ?

**Comment by ZmnSCPxj** [comment]
To be more precise it is not unusual if the funding txo has been spent by another close tx. This can happen if both peers `error` at each other, causing both to unilaterally close. So we need to start parsing the response from bitcoin-cli.
