### ISSUE TITLE
Owning subdaemon lightning_openingd died (62208)

### ISSUE THREAD

**Issue by mloop1** [ElementsProject/lightning#2798]
Hi,
looking at my logs, the following lines are continously being appended to it (there are thousands of them):

2019-07-06T18:04:01.635Z lightningd(19865): lightning_openingd-0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105 chan #23280: Peer connection lost
2019-07-06T18:04:01.635Z lightningd(19865): 0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105 chan #23280: Owning subdaemon lightning_openingd died (62208)
2019-07-06T18:21:20.057Z lightningd(19865): lightning_openingd-02d2026f19b8f09c4724b12ed4bee30b651fcecb8d89479efd76699d83ed79610c chan #23281: Peer connection lost
2019-07-06T18:21:20.072Z lightningd(19865): 02d2026f19b8f09c4724b12ed4bee30b651fcecb8d89479efd76699d83ed79610c chan #23281: Owning subdaemon lightning_openingd died (62208)

Not sure what is going on as "0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105"  is not in my peers, nor showing up in 1ML.

Any idea is appreciated.

### `getinfo` output
   "version" : "v0.7.1",
   "blockheight" : 584200,
   "network" : "bitcoin",

**Comment by darosior** [comment]
> Hi,

Hi

> looking at my logs, the following lines are continously being appended to it (there are thousands of them):

thousands refering to the same peer ?

> 
> 2019-07-06T18:04:01.635Z lightningd(19865): lightning_openingd-0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105 chan #23280: Peer connection lost
> 2019-07-06T18:04:01.635Z lightningd(19865): 0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105 chan #23280: Owning subdaemon lightning_openingd died (62208)
> 2019-07-06T18:21:20.057Z lightningd(19865): lightning_openingd-02d2026f19b8f09c4724b12ed4bee30b651fcecb8d89479efd76699d83ed79610c chan #23281: Peer connection lost
> 2019-07-06T18:21:20.072Z lightningd(19865): 02d2026f19b8f09c4724b12ed4bee30b651fcecb8d89479efd76699d83ed79610c chan #23281: Owning subdaemon lightning_openingd died (62208)

There is (in my understanding, still new) one `lightning_openingd` by peer, so it's intended that the `lightning_openingd` dies if connection is lost.

> 
> Not sure what is going on as "0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105" is not in my peers, nor showing up in 1ML.

https://1ml.com/node/0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105

> 
> Any idea is appreciated.

A plausible scenario is that this peer just connected to you and then disappeared.

**Comment by mloop1** [comment]
> > Hi,
> 
> Hi
> 
> > looking at my logs, the following lines are continously being appended to it (there are thousands of them):
> 
> thousands refering to the same peer ?

yes, thousands referring to a few peers, happening already for more than 1 month.

> 
> > 2019-07-06T18:04:01.635Z lightningd(19865): lightning_openingd-0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105 chan #23280: Peer connection lost
> > 2019-07-06T18:04:01.635Z lightningd(19865): 0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105 chan #23280: Owning subdaemon lightning_openingd died (62208)
> > 2019-07-06T18:21:20.057Z lightningd(19865): lightning_openingd-02d2026f19b8f09c4724b12ed4bee30b651fcecb8d89479efd76699d83ed79610c chan #23281: Peer connection lost
> > 2019-07-06T18:21:20.072Z lightningd(19865): 02d2026f19b8f09c4724b12ed4bee30b651fcecb8d89479efd76699d83ed79610c chan #23281: Owning subdaemon lightning_openingd died (62208)
> 
> There is (in my understanding, still new) one `lightning_openingd` by peer, so it's intended that the `lightning_openingd` dies if connection is lost.
> 
> > Not sure what is going on as "0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105" is not in my peers, nor showing up in 1ML.
> 
> https://1ml.com/node/0318f342854597b2a9af86ae818b794264b3c32e07626ad402a5c47b673482d105
> 
> > Any idea is appreciated.
> 
> A plausible scenario is that this peer just connected to you and then disappeared.

In this case is it by design of having this message in the logs for months?

**Comment by cdecker** [comment]
This message just means that the peers disconnected (`Peer connection lost`) followed by a status message that the daemon that took care of that connection has exited correctly (`Owning subdaemon lightning_openingd died`).

I know it's rather annoying to have the logs fill up due to a misbehaving peer (they should really implement exponential backoff), but it's perfectly fine. If you'd like to stop them from connecting you can just block them via `iptables`:

```bash
iptables -A INPUT -s [peer_ip] -p tcp -j DROP
```

**Comment by mloop1** [comment]
ok, thanks for clarifying the circumstances under which this happens and that indeed is a normal operational message. 
I'll then close the issue

**Comment by mloop1** [comment]
> This message just means that the peers disconnected (`Peer connection lost`) followed by a status message that the daemon that took care of that connection has exited correctly (`Owning subdaemon lightning_openingd died`).
> 
> I know it's rather annoying to have the logs fill up due to a misbehaving peer (they should really implement exponential backoff), but it's perfectly fine. If you'd like to stop them from connecting you can just block them via `iptables`:
> 
> ```shell
> iptables -A INPUT -s [peer_ip] -p tcp -j DROP
> ```

How can I get the IP from this peer id? 02d2026f19b8f09c4724b12ed4bee30b651fcecb8d89479efd76699d83ed79610c

It's not on 1ML.com and lightning-cli ping returns "unknown peer"

**Comment by darosior** [comment]
> How can I get the IP from this peer id? 

You might be able to find it by `grep` the above id in the logs

**Comment by mloop1** [comment]
> > How can I get the IP from this peer id?
> 
> You might be able to find it by `grep` the above id in the logs

Hi, thanks, tried that, also with log-level=debug, but cannot see any IP

**Comment by darosior** [comment]
> > > How can I get the IP from this peer id?
> > 
> > 
> > You might be able to find it by `grep` the above id in the logs
> 
> Hi, thanks, tried that, also with log-level=debug, but cannot see any IP

Then I don't have any idea. You can always ban it next time it happens :-)
