### ISSUE TITLE
process_estimatefee causes segfault

### ISSUE THREAD

**Issue by throckmortonsign** [ElementsProject/lightning#28]
Seems bcli->args[3] should be bcli->args[2] on lines 194 and 206 of bitcoind.c.

My setup: 2 ubuntu VMs networked to eachother, one has bitcoind running, both have lightningd. lighning-cli connect [ip] [port] [tx] causes segfault on the machine that's connecting.

**Comment by throckmortonsign** [comment]
Of course I could be missing something obvious or just ran into something unimplemented. ;)

**Comment by rustyrussell** [comment]
(Sorry for the delay, I took a vacation).

Fun!  This code is horrible, I've refactored it instead.

Try the process_estimatefee-fix branch?

https://github.com/ElementsProject/lightning/tree/process_estimatefee-fix

Thanks!
