### ISSUE TITLE
Routing appears to be using edges in reverse

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#281]
It appears the route finding algorithm may end up using the parameters from the opposite direction. This was not observed so far since we tend to test with a uniform network, but it was observed both when communicating with lnd as well as with eclair.

**Comment by rustyrussell** [comment]
Hmm, either I don't understand, or something else is going on.  Unit test seems to pass:

https://github.com/rustyrussell/lightning/tree/pr281

**Comment by rustyrussell** [comment]
This was fixed in #318
