### ISSUE TITLE
Add `--bitcoin-rpcclienttimeout` CLI parameter

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#2817]
As discussed in https://github.com/ElementsProject/lightning/pull/2780 we should likely expose this option through the command line so that users can adapt it to their needs.

Open questions:
 - @ZmnSCPxj proposed subtracting the `--bitcoin-retry-timeout` (better yet, just take the maximum of the two), to make sure we actually trigger an error at the expected time, rather than `--bitcoin-retry-timeout` + `--bitcoin-rpcclienttimeout`

**Comment by BitcoinJiuJitsu** [comment]
[@s373nz ](https://github.com/s373nz) is keen to have a run at this bounty after discovering on Sphinx, can we assign @cdecker?

**Comment by s373nZ** [comment]
@cdecker @BitcoinJiuJitsu I believe I've got some local code to define and passthrough the argument to `bcli`.

In terms of the open question, are you saying that `--bitcoin-rpcclienttimeout` should be modified to `max(bitcoin_retry_timeout, bitcoin_rpcclienttimeout)`? Based on my reading of #2778, that might still cause a long wait time as per the default values and your comment here suggests a lower value:

https://github.com/ElementsProject/lightning/issues/2778#issuecomment-506960780

From reviewing the conversations in #2780 and #2778, my reading is that we want the `min()`. Am I misunderstanding?

**Comment by cdecker** [comment]
Very nice, thanks @s373nZ, I'll review the PR as soon as possible :+1:
