### ISSUE TITLE
Create '--conf=<file>' option for config file use

### ISSUE THREAD

**Issue by cdodd** [ElementsProject/lightning#283]
I'm looking at creating a systemd unit file for lightningd to run it as a service but I would need to put options in the service unit when calling the lightningd binary. Such as:

```
--bitcoin-datadir
--lightning-dir
--log-level
--network
--port
```

`network`, `port` and `log-level` being the ones I'd be most interested in configuring.

I would like lightningd to have similar behaviour to bitcoind in this regard, and be able to have these options read from a config file (defaulting to something like `~/.lightningd`). A user of the service then only needs to modify the config file, not the service unit.

I see a closed issue https://github.com/ElementsProject/lightning/issues/235 appearing to ask for a similar option, but I don't think this is the same requirement described above. I couldn't see any other issues with this kind of request.

**Comment by rustyrussell** [comment]
Craig Dodd <notifications@github.com> writes:
> I'm looking at creating a systemd unit file for lightningd to run it as a service but I would need to options in the service unit when calling the lightningd binary. Such as:
>
> ```
> --bitcoin-datadir
> --lightning-dir
> --log-level
> --network
> --port
> ```
>
> `network`, `port` and `log-level` being the ones I'd be most interested in configuring.
>
> I would like lightningd to have similar behaviour to bitcoind in this regard, and be able to have these options read from a config file (defaulting to something like `~/.lightningd`). A user of the service then only needs to modify the config file, not the service unit.

The default config file is `--lightning-dir`/config.  You can't run two
lightningds with the same `--lightning-dir`.

I think that your question implies you didn't know about the config
file?  The complete lack of documentation explains that.  MUSTFIX.

Thanks!
Rusty.

**Comment by cdodd** [comment]
Ah, thanks. Feel free to close this issue if you want.
