### ISSUE TITLE
Unable to see a channel and to find routes after the funding transaction is confirmed.

### ISSUE THREAD

**Issue by gradientskier** [ElementsProject/lightning#284]
Me and MyFriend are trying to setup a payment channel in the testnet using this c-lightning implementation (code at master), but we are actually experiencing few issues. 

I opened a channel using the instruction:

```
cli/lightning-cli fundchannel 0234722de6b30b42e78f2f61970f614335f96f0e5ec3ef30fd36a0750ac2c3295f 10000000
```
where 0234722de6b30b42e78f2f61970f614335f96f0e5ec3ef30fd36a0750ac2c3295f is the id of MyFriend.

We waited for the transaction confirmation in testnet. The transaction was confirmed, as shown by the blockexplorer, at https://live.blockcypher.com/btc-testnet/tx/8a5aa8cd9f64f986a95f3ea788553189570d13a7f80d5ded39d630dcf18ade06/

Everything was working fine, in fact a call to the getpeers returns a CHANNELD_NORMAL state.

```
{ "peers" : [ 
    { "unique_id" : 3, 
    "state" : "CHANNELD_NORMAL", 
    "netaddr" : "::ffff:47.91.92.125:43266", 
    "peerid" : "0234722de6b30b42e78f2f61970f614335f96f0e5ec3ef30fd36a0750ac2c3295f", 
    "connected" : true, 
    "owner" : "lightning_channeld", 
    "channel" : "1196170:6:1", 
    "msatoshi_to_us" : 10000000000, 
    "msatoshi_total" : 10000000000 } ] }
```

The problem is that both getchannels and getnodes return empty set and getroute says that it's impossible to find a route. We tried to restart the nodes, but the channel never appears. Are we missing something?

At this link you can find the output of some instructions that MyFriend executed (the other side of the channel):
https://pastebin.com/raw/FsswXfE2

Moreover, we are experiencing crashes at both sides, in particular when MyFriend tries to fund another channel. This is the crash log.
https://mega.nz/#!04sCTbRL!Z1vA-LyL4i7bvT5DCcDlJzu5NCZimdzYUMZYEyVqI6A

If you need more information, we can provide them to you.

Best!

**Comment by rustyrussell** [comment]
OK, I think what's happening is that we don't actually announce the channel until it's 6 deep.  @cdecker Can you verify?  Clearly, we should enter the local ones immediately.

There are also a few spinoff issues from this, I've filed separate bugs for each so I can squish!  Thanks!

**Comment by cdecker** [comment]
Yep, that's definitely the case. We do not announce channels until we have 6 confirmations, and we don't have a parallel path to add them to `gossipd` if the channels are local. Will fix that, since it's a common stumbling stone.
