### ISSUE TITLE
Feerates too different

### ISSUE THREAD

**Issue by Sealr0x** [ElementsProject/lightning#2864]
### Issue and Steps to Reproduce

On mainnet, running node v0.3.1 and mobile app on Android v0.4.7. 

Trying to set up a channel from mobile.

Getting this :

local/remote feerates are too different: remoteFeeratePerKw=788 localFeeratePerKw=8160 while processing msg=OpenChannel in state=WAIT_FOR_OPEN_CHANNEL

**Comment by cdecker** [comment]
Sorry, I fail to understand which version you are running. We do not have a version 0.3.1, and even if we had, we switched to the spec transport protocol with 0.6, and anything below that should not be able to even talk with anything that uses the spec transport.

Are you sure you are running c-lightning?
