### ISSUE TITLE
[test]: several pytest testcases failed if run as 32-bit on 64bit linux

### ISSUE THREAD

**Issue by arowser** [ElementsProject/lightning#2865]
### Issue and Steps to Reproduce
Not sure if a real issue, I found that when I try to run pytest with 32-bit lightningd  on a 64 bit linux machine.

export target_host=i686-linux-gnu                                                                                                                                                             
export MAKE_HOST=i686-linux-gnu                                                                                                                                                               
export AR=$target_host-ar                                                                                                                                                                     
export AS=$target_host-as                                                                                                                                                                     
export CC=$target_host-gcc                                                                                                                                                                    
export CXX=$target_host-g++                                                                                                                                                                   
export LD=$target_host-ld                                                                                                                                                                     
export STRIP=$target_host-strip                                                                                                                                                               
export DEVELOPER=0 
./configure && make 
make VALGRIND=0 pytest

### failed testcases
tests/test_connection.py::test_peerinfo FAILED  
tests/test_gossip.py::test_gossip_weirdalias FAILED 
tests/test_gossip.py::test_gossip_addresses FAILED  
tests/test_gossip.py::test_gossip_notices_close FAILED 
tests/test_gossip.py::test_gossip_store_load_complex FAILED 
tests/test_gossip.py::test_gossip_store_compact_on_load FAILED 
tests/test_invoices.py::test_invoice_routeboost FAILED 
tests/test_pay.py::test_pay_limits FAILED 
tests/test_plugin.py::test_htlc_accepted_hook_fail FAILED 
tests/test_plugin.py::test_htlc_accepted_hook_resolve FAILED 
tests/test_plugin.py::test_htlc_accepted_hook_forward_restart FAILED 

### 
```
========================================================================================== FAILURES ==========================================================================================
_______________________________________________________________________________________ test_peerinfo ________________________________________________________________________________________

node_factory = <utils.NodeFactory object at 0x7f6312f7b1d0>, bitcoind = <utils.BitcoinD object at 0x7f6312f7b358>

    def test_peerinfo(node_factory, bitcoind):
        l1, l2 = node_factory.line_graph(2, fundchannel=False, opts={'may_reconnect': True})
        lfeatures = 'aa'
        # Gossiping but no node announcement yet
        assert l1.rpc.getpeer(l2.info['id'])['connected']
        assert len(l1.rpc.getpeer(l2.info['id'])['channels']) == 0
        assert l1.rpc.getpeer(l2.info['id'])['localfeatures'] == lfeatures
    
        # Fund a channel to force a node announcement
        chan = l1.fund_channel(l2, 10**6)
        # Now proceed to funding-depth and do a full gossip round
        bitcoind.generate_block(5)
>       l1.daemon.wait_for_logs(['Received node_announcement for node ' + l2.info['id']])

tests/test_connection.py:1321: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <utils.LightningD object at 0x7f6311f43438>, regexs = ['Received node_announcement for node 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59'], timeout = 60

    def wait_for_logs(self, regexs, timeout=TIMEOUT):
        """Look for `regexs` in the logs.
    
        We tail the stdout of the process and look for each regex in `regexs`,
        starting from last of the previous waited-for log entries (if any).  We
        fail if the timeout is exceeded or if the underlying process
        exits before all the `regexs` were found.
    
        If timeout is None, no time-out is applied.
        """
        logging.debug("Waiting for {} in the logs".format(regexs))
        exs = [re.compile(r) for r in regexs]
        start_time = time.time()
        pos = self.logsearch_start
        while True:
            if timeout is not None and time.time() > start_time + timeout:
                print("Time-out: can't find {} in logs".format(exs))
                for r in exs:
                    if self.is_in_log(r):
                        print("({} was previously in logs!)".format(r))
>               raise TimeoutError('Unable to find "{}" in logs.'.format(exs))
E               TimeoutError: Unable to find "[re.compile('Received node_announcement for node 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59')]" in logs.

tests/utils.py:212: TimeoutError
----------------------------------------------------------------------------------- Captured stdout setup ------------------------------------------------------------------------------------
Running tests in /tmp/ltests-mhsgqtaf
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
Time-out: can't find [re.compile('Received node_announcement for node 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59')] in logs
```

### other info
If add 'import pdb; pdb.set_trace' before wait_for_logs function, the testcase will success.

@cdecker maybe known the reasons.

**Comment by rustyrussell** [comment]
Maybe try with TIMEOUT=120 prepended, in case it's just slow?
