### ISSUE TITLE
Broken plugins with addition of `dynamic` field

### ISSUE THREAD

**Issue by rsbondi** [ElementsProject/lightning#2869]
### Issue and Steps to Reproduce
I have several plugins built on glightning, anything build before 12e28c25543df873c378b51d94de2f7d83f0beb3 the plugins work fine, from this commit forward, I get nothing in the logs and commands either don't work or cause crash

A basic plugin like:

https://github.com/niftynei/glightning/blob/master/examples/plugin_example.go the `say-hi` command works but the log does not show.  

Based on the issues with my plugins it appears that the glightning rpc calls are broken but hard to tell without the logs

`git checkout 12e28c25543df873c378b51d94de2f7d83f0beb3`
`make`
launch with path to plugin or plugin added to config

### `getinfo` output
```json
{
    "id": "03a295eba0076a3714acf5fcd6413d70a59a58169351cc3374bfad90dbe904f6df",
    "alias": "CHILLYWATER",
    "color": "03a295",
    "num_peers": 2,
    "num_pending_channels": 1,
    "num_active_channels": 1,
    "num_inactive_channels": 0,
    "address": [
      {
        "type": "ipv6",
        "address": "2605:6000:1021:8081:c499:ed87:c4d8:6793",
        "port": 9735
      }
    ],
    "binding": [
      {
        "type": "ipv6",
        "address": "::",
        "port": 9735
      },
      {
        "type": "ipv4",
        "address": "0.0.0.0",
        "port": 9735
      }
    ],
    "version": "v0.7.1-140-g12e28c2",
    "blockheight": 1966,
    "network": "regtest",
    "msatoshi_fees_collected": 0,
    "fees_collected_msat": "0msat"
  }
```

**Comment by trueptolemy** [comment]
Rusty has two fix #2862 and will be merged soon. Maybe it will help you.

**Comment by darosior** [comment]
> Based on the issues with my plugins it appears that the glightning rpc calls are broken but hard to tell without the logs

Could you raise an exception or write to a file or whatever the content of the socket path variable ? It seems that the plugin cannot talk to `lightningd` (maybe print the configuration fields in `on_init`).

**Comment by rsbondi** [comment]
it never gets to `on_init`, my guess is that it registers the method just fine in `getmanifest` but the new `dynamic` is not sent by glightning, it seems that for backward compatibility, `dynamic` should not be required, but again, just speculating.

**Comment by rsbondi** [comment]
FYI, the problem still exists with #2862

**Comment by darosior** [comment]
> it never gets to on_init, my guess is that it registers the method just fine in getmanifest but the new dynamic is not sent by glightning, it seems that for backward compatibility, dynamic should not be required, but again, just speculating.

It its not, it's set to `false` by default hence why I assumed it would get to init.

**Comment by rsbondi** [comment]
[this](https://github.com/ElementsProject/lightning/blob/79d32ec2f29357463ca067b167c888eebaf4b124/lightningd/plugin.c#L1029) is the line that kills it, if I remove it I get the logs and the init gets called in the plugin with the rpc info.  I don't know if this means there is something to be done here @darosior  or in glightning @niftynei?

**Comment by ZmnSCPxj** [comment]
Probably needs a fix in glightning.

**Comment by darosior** [comment]
Yes it indeed needs a field in glightning. However I cant do Golang so I cant submit a PR, however I can help you through making it @rsbondi . You should search for the function handling the init response from `lightningd` and make it read also the `startup` field.

**Comment by rsbondi** [comment]
Moved to glightning
