### ISSUE TITLE
current master (cd91c0...) does not compile

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#2916]
There seems to be an issue with `peer_billboard` in `channeld/channel.c`:

```
git log
commit cd91c06ce9e869f8143a3993729bcf975dd120e9 (HEAD -> master, origin/master, origin/HEAD)
Author: darosior <darosior@protonmail.com>
Date:   Tue Aug 6 17:49:26 2019 +0200

    lightningd/notification: Add missing includes for 'forward_event'
    
    And update test mocks
```

when running make (after running make clean) I get: 
```
channeld/channeld.c: In function ‘billboard_update’:
channeld/channeld.c:214:2: error: ‘shutdown_status’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  peer_billboard(false, "%s%s%s", funding_status,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          announce_status, shutdown_status);
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
channeld/channeld.c:214:2: error: ‘announce_status’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
channeld/channeld.c:214:2: error: ‘funding_status’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors
<builtin>: recipe for target 'channeld/channeld.o' failed
make: *** [channeld/channeld.o] Error 1
```

**Comment by renepickhardt** [comment]
might have been my problem. Cloning to a new / clean git repo worked. I ran `make clean` before but still there seemed to be some leftovers. So we might have to check if everything is getting cleaned successfully.

**Comment by darosior** [comment]
You need to `./configure` / `make update-mocks`. When making the above commit, I wondered to add the `update-mocks` rule to the `default` one in the Makefile.

**Comment by rustyrussell** [comment]
update-mocks uses the linker output to work(!).  So it's fragile, and supposed to be developer-only.  However, a test was added which used it, so now everyone needs it.  However, I think I'll fix that instead, so it no longer is built by default or uses update-mocks, not sure which.
