### ISSUE TITLE
crash using latest git (towire_tlvs)

### ISSUE THREAD

**Issue by ScottTre** [ElementsProject/lightning#2974]
After the start the latest version crash.

[crash.txt](https://github.com/ElementsProject/lightning/files/3514957/crash.txt)

**Comment by rustyrussell** [comment]
I assume you used `--enable-experimental-features` to get this?  Can you send the contents of `wire/gen_peer_wire.c` please?  Mine doesn't have anything like that at line 625...

**Comment by rustyrussell** [comment]
See also #2956

**Comment by ScottTre** [comment]
Yes, it seems there is a problem with this sort thing, "make check" failed with "Python 2.7.12" also:

wire/test/run-tlvstream > /dev/null
run-tlvstream: ./wire/tlvstream.c:152: towire_tlvs: Assertion `types[i].type > types[i-1].type' failed.
Aborted
Makefile:455: recipe for target 'unittest/wire/test/run-tlvstream' failed
make: *** [unittest/wire/test/run-tlvstream] Error 134

**Comment by ZmnSCPxj** [comment]
Closing in favor of #2956 which has same root cause.
