### ISSUE TITLE
Make error on v0.7.2

### ISSUE THREAD

**Issue by kalibox** [ElementsProject/lightning#2978]
### Issue and Steps to Reproduce
Download v0.7.2.zip
unzip file
change directory to lightning folder
./configure
make
Makefile:7: *** "ERROR: git is required for generating version information".  Stop.

**Comment by kalibox** [comment]
Just to add- checking out via git doesn't produce this error and build process works OK.

**Comment by SimonVrouwe** [comment]
Does `git log` work inside the unzipped directory? Perhaps it is not a git repo.
Why not build from the checked-out repo: `git pull && git checkout v0.7.2 && ./configure && make`

**Comment by kalibox** [comment]
That's exactly what I've done for now. Pulled down the repo and built it from there. Works like a charm.

Just wanted to highlight the zip error in case folks use it to build and deploy that way. 

Thanks

**Comment by SimonVrouwe** [comment]
> Perhaps it is not a git repo.

No that doesn't seem the issue, the other package [clightning-v0.7.2.1-Ubuntu-16.04-i386.tar.gz](https://github.com/ElementsProject/lightning/releases) builds fine. What exactly is the target platform for [clightning-v0.7.2.1.zip](https://github.com/ElementsProject/lightning/releases)?

**Comment by rustyrussell** [comment]
Yes, this was fixed in v0.7.2.1 (and one reason for the point release!)

**Comment by kalibox** [comment]
Cool. Thanks!
