### ISSUE TITLE
Some minor build issue: /bin/sh: 1: mrkd: not found

### ISSUE THREAD

**Issue by SimonVrouwe** [ElementsProject/lightning#3000]
1. Almost every time building the repo via `make`, I get:
```
Makefile:424: warning: overriding recipe for target 'clean'
tools/Makefile:12: warning: ignoring old recipe for target 'clean'
mv: replace 'tools/headerversions', overriding mode 0755 (rwxr-xr-x)? 
```
After manually removing the file, `make` runs cleanly (doesn't build anything).

2. Then `sudo make install`:
```
Makefile:424: warning: overriding recipe for target 'clean'
tools/Makefile:12: warning: ignoring old recipe for target 'clean'
mkdir -p /usr/local/bin
mkdir -p /usr/local/libexec/c-lightning
mkdir -p /usr/local/libexec/c-lightning/plugins
mkdir -p /usr/local/share/man/man1
mkdir -p /usr/local/share/man/man5
mkdir -p /usr/local/share/man/man7
mkdir -p /usr/local/share/man/man8
mkdir -p /usr/local/share/doc/c-lightning
install cli/lightning-cli lightningd/lightningd /usr/local/bin
install lightningd/lightning_channeld lightningd/lightning_closingd lightningd/lightning_connectd lightningd/lightning_gossipd lightningd/lightning_hsmd lightningd/lightning_onchaind lightningd/lightning_openingd /usr/local/libexec/c-lightning
[ -z "plugins/pay plugins/autoclean" ] || install plugins/pay plugins/autoclean /usr/local/libexec/c-lightning/plugins
mrkd doc/lightning-invoice.7.md
/bin/sh: 1: mrkd: not found
make: *** [doc/Makefile:47: doc/lightning-invoice.7] Error 127
```
BTW I have no idea what package contains `mrkd` binary.

Then running `make`, I am back at 1.
This is my local repo with all git history, so I rather not wipe it.

**edit**: My system is a bit crappy Debian Buster, but worked fine until couple of weeks ago:
`4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux`

**Comment by darosior** [comment]
> BTW I have no idea what package contains mrkd binary.

`mrkd` is aimed to be `pip3 install`ed in order to update the manpages : it is present in `doc/requirements.txt` iirc.

**Comment by SimonVrouwe** [comment]
Thanks, it works now. Maybe it should be added to this list 
```
For development or running tests, get additional dependencies:

sudo apt-get install -y asciidoc valgrind python3-pip
sudo pip3 install -r tests/requirements.txt

```
in the [build](https://github.com/ElementsProject/lightning/blob/master/doc/INSTALL.md#to-build-on-ubuntu) instructions?

**Comment by darosior** [comment]
Indeed, I'll take care of that :-).

**Comment by billygarrison** [comment]
I just came across the same issue, building on Ubuntu 18.04.

I didn't install the following, because it seemed optional. Not sure if it is supposed to be required, but the wording makes it seem optional. I didn't do any development/testing, and still came across the `mrkd: not found` error.

> For development or running tests, get additional dependencies:
> ```
> sudo apt-get install -y valgrind python3-pip libpq-dev
> sudo pip3 install -r requirements.txt
> ```

So, if these packages are required to be installed, perhaps the install docs could be a bit clearer. If they are supposed to be optional, then please let me know so I can look into why it gave me the error.

@darosier

**Comment by darosior** [comment]
`mrkd` is required to build the manpages, it is not a dev dependency.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by billygarrison** [comment]
Is `mrkd` installed anywhere else or is the following required to build from source?:
```
sudo apt-get install -y valgrind python3-pip libpq-dev
sudo pip3 install -r requirements.txt
```

**Comment by dscotese** [comment]
Looks like sudo pip3 install mrkd will work, but I get `AttributeError: module 'mistune' has no attribute 'InlineLexer'`.  The software works, but I suppose the documentation might not be available or formatted properly.  `man lightningd` seems to work just fine, but I don't know what I need to look for to see if markd is doing its job. `man lightning-invoice` works as expected too, though that might be because I am installing on top of an old version.

**Comment by vincenzopalazzo** [comment]
@dscotese now we are using poetry and not with pip, this should solve your error, do you have tried?

**Comment by csralvall** [comment]
I don't think so. I ran `poetry install` in project directory and then `configure && make` and still get the error: `AttributeError: module 'mistune' has no attribute 'InlineLexer'`

**Comment by dscotese** [comment]
> @dscotese now we are using poetry and not with pip, this should solve your error, do you have tried?

I followed these instructions:
```
sudo apt-get update
sudo apt-get install -y \
  autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev \
  python3 python3-pip net-tools zlib1g-dev libsodium-dev gettext
pip3 install --upgrade pip
pip3 install --user poetry
poetry install
```
and that is how I got the error `/bin/sh: 1: mrkd: not found` which led me to this issue and the suggestion to `pip3 install mrkd`

**Comment by vincenzopalazzo** [comment]
Sorry for delay here, can you try please @dscotese @csralvall 

```
pip3 install poetry
poetry config virtualenvs.create false
poetry install
```

**Comment by dscotese** [comment]
`poetry install` apparently expects there to be a pyproject.toml file in a parent directory and I don't have one, so it spits out this report:
```
  RuntimeError

  Poetry could not find a pyproject.toml file in /usr/src/ubuntu or its parents

  at ~/.local/lib/python3.8/site-packages/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )
```
I went back to https://github.com/ElementsProject/lightning/blob/master/doc/INSTALL.md#to-build-on-ubuntu and followed the instructions starting with `sudo apt-get update` in case something up there would add pyproject.toml to a parent, but the result was the same.  Then I noticed that pyproject.toml is in the lightning folder and I was in its parent, so I `cd lightning`'d and then tried again and got permissions errors on `poetry install`.  I tried `sudo poetry install` and got `poetry: Command not found` and the same thing when I `su`'d and then tried 'poetry install'.

Also, I believe I made an error in my last comment so I [will] have corrected it [in a few minutes]...

**Comment by csralvall** [comment]
> Sorry for delay here, can you try please @dscotese @csralvall
> 
> ```
> pip3 install poetry
> poetry config virtualenvs.create false
> poetry install
> ```

@vincenzopalazzo 
I make it finally work with:
```bash
poetry shell
poetry env use <path-to-python3.8.10-installed-with-pyenv>
poetry install
./configure && make && make install
```

I tried your suggestion cloning the repo again, but it didn't work for me.
Let me know if you want the logs, but I think that the errors are related
to the fact that I already have a successful installation of the project.

**Comment by vincenzopalazzo** [comment]
```
poetry shell
poetry install
./configure && make && make install
```

This should work, if not can you post your error here?

**Comment by csralvall** [comment]
That works! Some of the last changes may have fixed the python version error, because now it works with python 3.10 and I don't have to provide a custom version for the repository. Thanks!
