### ISSUE TITLE
Add transfer persistence

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#302]
With #299 we can now persist HTLCs and invoices to the wallet, however if we are the origin of a transfer and restart before it completes we are in trouble. The JSON-RPC call cannot be notified for obvious reasons, and while we can mark the HTLC as completed we have no other indication that the transfer succeeded. So with this I'd like to introduce a small record that we initiated a transfer, store it in the wallet so we can inspect it even after the HTLC and channel has been cleared and have some indication about the current state. It should be the counterpart to the invoice on the receiving end, and could very well end up backing a wallet view.

**Comment by rustyrussell** [comment]
Yes, and this is important. We must never reuse an old payment hash. Would be nice to save dest id and payment preimage. This means we maintain current behaviour across restarts: trying to repay an old payment succeeds, but to a different destination fails with error?
