### ISSUE TITLE
channel active after reconnect

### ISSUE THREAD

**Issue by hirokuma** [ElementsProject/lightning#303]
I execute three lightningd on regtest.
After 6 block, all channels are `active: true` at `lightning-cli getchannels` .

    nodeA -(fund)--> nodeB <--(fund)- nodeC

After restarting nodeB, channel B-->A and B-->C are `active: true`, but A-->B and C-->B are `active: false`.
How to change `active: true` ?

**Comment by cdecker** [comment]
Good catch, this is due to the fact that upon disconnecting, the endpoints may send a `channel_update` that disabled the channel, but we never send a re-enabling `channel_update`. I'll take care of that :wink:
