### ISSUE TITLE
Error when compiling on Debian

### ISSUE THREAD

**Issue by sfmcnally** [ElementsProject/lightning#3055]
I can no longer compile lightning on Debian. I get the following error:

make: xgettext: Command not found
wallet/Makefile:43: recipe for target 'wallet/statements.po' failed
make: *** [wallet/statements.po] Error 127

**Comment by darosior** [comment]
Hello @sfmcnally , maybe you should install [`gettext`](https://www.gnu.org/software/gettext/) argument then :-).
```bash
apt install gettext
```

**Comment by sfmcnally** [comment]
I tried `apt install xgettext` and it said package not found. I didn't know I needed to drop the leading x.

**Comment by sfmcnally** [comment]
Made it a little farther and then...

wallet/db_sqlite3.o wallet/db_sqlite3.c
wallet/db_sqlite3.c: In function ‘trace_sqlite3’:
wallet/db_sqlite3.c:14:17: error: expected identifier or ‘(’ before ‘=’ token
  struct db_stmt = (struct db_stmt*)stmtv;
                 ^
wallet/db_sqlite3.c:15:17: error: passing argument 1 of ‘db_changes_add’ from incompatible pointer type [-Werror]
  db_changes_add(stmt, stmt);
                 ^
In file included from wallet/db_sqlite3.c:1:0:
./wallet/db_common.h:145:6: note: expected ‘struct db_stmt *’ but argument is of type ‘const char *’
 void db_changes_add(struct db_stmt *db_stmt, const char * expanded);
      ^
wallet/db_sqlite3.c: In function ‘db_sqlite3_exec’:
wallet/db_sqlite3.c:89:16: error: ‘db’ undeclared (first use in this function)
  sqlite3_trace(db->sql, trace_sqlite3, stmt);
                ^
wallet/db_sqlite3.c:89:16: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors
<builtin>: recipe for target 'wallet/db_sqlite3.o' failed
make: *** [wallet/db_sqlite3.o] Error 1

**Comment by darosior** [comment]
Did you `make clean` and re-`./configure`ed ?
```bash
make clean && ./configure && make -j N
```

**Comment by sfmcnally** [comment]
No dice. I've been able to compile with no problem almost since day 1. I don't know what changed. Here's the error when I run your suggested command. 

```
cc -DBINTOPKGLIBEXECDIR="\"../libexec/c-lightning\"" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -Wno-maybe-uninitialized -std=gnu11 -g -fstack-protector -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/libbacktrace-build -I external/libsodium/src/libsodium/include -I . -I/usr/local/include    -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DCOMPAT_V060=1 -DCOMPAT_V061=1 -DCOMPAT_V062=1 -DCOMPAT_V070=1 -DBINTOPKGLIBEXECDIR="\"../libexec/c-lightning\""  -c -o lightningd/lightningd.o lightningd/lightningd.c
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
<builtin>: recipe for target 'gossipd/gen_gossip_wire.o' failed
make: *** [gossipd/gen_gossip_wire.o] Error 4
make: *** Waiting for unfinished jobs....
<builtin>: recipe for target 'gossipd/gossip_store.o' failed
make: *** [gossipd/gossip_store.o] Error 4
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
<builtin>: recipe for target 'gossipd/routing.o' failed
make: *** [gossipd/routing.o] Error 4
make: *** wait: No child processes.  Stop.

```

**Comment by sfmcnally** [comment]
`cc -DBINTOPKGLIBEXECDIR="\"../libexec/c-lightning\"" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -Wno-maybe-uninitialized -std=gnu11 -g -fstack-protector -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/libbacktrace-build -I external/libsodium/src/libsodium/include -I . -I/usr/local/include    -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DCOMPAT_V060=1 -DCOMPAT_V061=1 -DCOMPAT_V062=1 -DCOMPAT_V070=1 -DBINTOPKGLIBEXECDIR="\"../libexec/c-lightning\""  -c -o lightningd/lightningd.o lightningd/lightningd.c
cc: internal compiler error: Killed (program cc1)
`

**Comment by darosior** [comment]
I don't know much about `gcc` errors but it seems like [you are running out of memory](https://www.google.com/search?q="gcc"+"Error+4"&oq="gcc"). What are the specs of your system ? What command did you run exactly ?

> I've been able to compile with no problem almost since day 1.

At what commit (/release) the build did start to fail then ?

**Comment by sfmcnally** [comment]
After a reboot and a couple attempts to compile, I'm getting this error. The system is a raspberry pi, but I've been running lightning on it for over a year without problems. when I run simply

`sudo make`

I get this error

`wallet/db_sqlite3.o wallet/db_sqlite3.c
wallet/db_sqlite3.c: In function ‘trace_sqlite3’:
wallet/db_sqlite3.c:14:17: error: expected identifier or ‘(’ before ‘=’ token
  struct db_stmt = (struct db_stmt*)stmtv;
                 ^
wallet/db_sqlite3.c:15:17: error: passing argument 1 of ‘db_changes_add’ from incompatible pointer type [-Werror]
  db_changes_add(stmt, stmt);
                 ^
In file included from wallet/db_sqlite3.c:1:0:
./wallet/db_common.h:145:6: note: expected ‘struct db_stmt *’ but argument is of type ‘const char *’
 void db_changes_add(struct db_stmt *db_stmt, const char * expanded);
      ^
wallet/db_sqlite3.c: In function ‘db_sqlite3_exec’:
wallet/db_sqlite3.c:89:16: error: ‘db’ undeclared (first use in this function)
  sqlite3_trace(db->sql, trace_sqlite3, stmt);
                ^
wallet/db_sqlite3.c:89:16: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors
<builtin>: recipe for target 'wallet/db_sqlite3.o' failed
make: *** [wallet/db_sqlite3.o] Error 1
`

**Comment by ZmnSCPxj** [comment]
Looks like a definite typo here: https://github.com/ElementsProject/lightning/blob/742bcdb2bcbd2ebdd0b1de4921e31214ba72d0d8/wallet/db_sqlite3.c#L14

Maybe should be nearer to:

    /* Prior to sqlite3 v3.14, we have to use tracing to dump statements */
    static void trace_sqlite3(void *stmtv, const char *expanded_stmt)
    {
    	struct db_stmt *stmt = (struct db_stmt*)stmtv;
    	db_changes_add(stmt, expanded_stmt);
    }

The second failure is worse:

https://github.com/ElementsProject/lightning/blob/742bcdb2bcbd2ebdd0b1de4921e31214ba72d0d8/wallet/db_sqlite3.c#L86-L90

This requires us to change the interface of `db_sqlite3_exec`, which requires a change in `struct db_config`.

Assigning to @cdecker.

**Comment by cdecker** [comment]
Wasn't expecting to see this, since it means we are compiling against an older version of sqlite3.

**Comment by cdecker** [comment]
I'll fix this up asap, sorry for the inconvenience @sfmcnally

**Comment by sfmcnally** [comment]
Thanks @cdecker. No inconvenience or need to apologize. Just trying to help chase down bugs and contribute whatever small part I can to development.
