### ISSUE TITLE
Can't configure: python3-mako not found

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#3077]
### Issue and Steps to Reproduce

I'm trying to build `lightningd` from source and get a missing dependency error:
```
$ ./configure
Compiling ccan/tools/configurator/configurator...done
checking for python3-mako... not found
You need the mako module for python3: see doc/INSTALL.md
```
However, `python3-mako` is installed:
```
$ sudo apt install python3-mako
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-mako is already the newest version (1.0.7+ds1-1).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
```
Removing and re-installing python3-mako doesn't help. How do I solve this?

OS info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by fiatjaf** [comment]
I don't understand, but I faced that issue, installed `python3-mako` just like you did and it worked for me. Maybe `make clean` then `./configure`?

**Comment by s-tikhomirov** [comment]
Thanks @fiatjaf, but that doesn't help, I still get the same error (`checking for python3-mako... not found`).

**Comment by ZmnSCPxj** [comment]
Your installation might be broken?  Could you try: `pip3 install mako`?

**Comment by fiatjaf** [comment]
The `configure` file uses this check: `python3 -c 'import mako'`.
Try running that and see what you get.

**Comment by s-tikhomirov** [comment]
The advice of @ZmnSCPxj helped, thanks a lot!

(after I ran `pip3 install mako`, `python3 -c 'import mako'` returns without any messages, if that's relevant)
