### ISSUE TITLE
Can't connect to lightningd from pylightning on regtest

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#3086]
### Issue and Steps to Reproduce

I'm trying to write a Python script to connect to a local c-lightning node on regtest. I'm running `bitcoind` (with regtest option set in config file) and `lightningd --network=regtest`. `lightning-cli getinfo` works (see output below).

Then I try to reproduce an example script from the [pylightning readme page](https://github.com/ElementsProject/lightning/blob/master/contrib/pylightning/README.md):
```
from lightning import LightningRpc
l5 = LightningRpc("/tmp/lightning5/lightning-rpc")
info5 = l5.getinfo()
```

I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sergei/.local/lib/python3.6/site-packages/lightning/lightning.py", line 526, in getinfo
    return self.call("getinfo")
  File "/home/sergei/.local/lib/python3.6/site-packages/lightning/lightning.py", line 217, in call
    sock.connect(self.socket_path)
ConnectionRefusedError: [Errno 111] Connection refused
```
UPD I thought maybe `pylightning` connects to testnet or mainnet rather than regtest by default, and added a `config` file into `/tmp/lightning5/lightning-rpc` with the line `network=regtest`, but the problem persists.

UPD2 This is my `config` file in `/tmp/lightning5/lightning-rpc` (user and password the same as in `~/.bitcoin/bitcoin.conf`):

```
network=regtest
bitcoin-rpcuser=<user>
bitcoin-rpcpassword=<password>
bitcoin-rpcconnect=127.0.0.1
bitcoin-rpcport=18443
```

### `getinfo` output
```
{
   "id": "024a46ccc718360ff5889b49436bc25b3d920f61511dac84b6ff46480062d5fda5",
   "alias": "HAPPYPENGUIN",
   "color": "024a46",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv6",
         "address": "<my IP address>",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.7.2.1-291-g14b55d0",
   "blockheight": 146,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "warning_bitcoind_sync": "Bitcoind is not up-to-date with network."
}
```

**Comment by s-tikhomirov** [comment]
The problem was my misunderstanding of what `lightning-rpc` is supposed to be. Solved.

**Comment by utzn42** [comment]
Hey, I've recently stumbled upon the same problem, trying to make RPC calls with Python while running lightningd in testnet mode. 

Could you maybe briefly explain your solution in a bit more detail? Thanks in advance.
