### ISSUE TITLE
Slow block sync?

### ISSUE THREAD

**Issue by LightningK0ala** [ElementsProject/lightning#3109]
I'm in the process of migrating the satoshis.place node to another machine. It got into a weird state at some point (power outage?) and it's having to resync blocks. My bitcoind is up to date but lightingd is lagging behind.

The lightning node is on a dedicated 4 vCPU + 4GB VM + nvme ssd drive and I'm seeing `Adding block xxxxx` in the logs at a fairly slow rate (about 0.6 per second). It's currently at around block 142029 and I'm worried it's going to take > 5 days to get up to sync. It's only hitting 30% CPU usage and has > 1.5GB memory spare. Any ideas on where the bottleneck is? Are blocks meant to sync this slow?

Running c-lightning 0.7.2, node is in a docker container.

**Comment by ZmnSCPxj** [comment]
Can you try compiling and running this program under the environment `lightningd` is running in?

```c
#include <stdio.h>
#include <unistd.h>
int main() {
  int max = sysconf(_SC_OPEN_MAX);
  printf("_SC_OPEN_MAX %d\n", max);
  return 0;
}
```

We know there is a slowdown related to closing file descriptors prior to running a `bitcoin-cli` command #3074  and is recently fixed in #3101, which is not yet in a release.

**Comment by LightningK0ala** [comment]
Thanks for the reply!
The output I got after compiling and running the program:
`_SC_OPEN_MAX 1024`

**Comment by LightningK0ala** [comment]
@ZmnSCPxj I just tried compiling and running from master and it's much quicker now. I'm getting about 10 blocks per second now :star: 

Thanks again!
