### ISSUE TITLE
lightningd no longer starts when using spruned instead of bitcoind.

### ISSUE THREAD

**Issue by dan-da** [ElementsProject/lightning#3143]
When running latest spruned (0.0.10) and latest lightningd (f019dc3d710eb37f42c18962685dbc31ca3e5ba6), lightningd exits soon after startup with this error:

```
$ lightningd 
Invalid 'initialblockdownload' field in getblockchaininfo '{
  "chain": "main",
  "warning": "spruned 0.0.10, emulating bitcoind v0.16",
  "blocks": 598500,
  "headers": 598500,
  "bestblockhash": "00000000000000000002957e1186941dffe9f1c9460c7e93351040aefca8800b",
  "difficulty": 0,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000000000",
  "mediantime": 1570562099,
  "verificationprogress": 0,
  "pruned": false
}
```

An [issue](https://github.com/gdassori/spruned/issues/103) was filed in spruned repo Aug 13 and has received no comments.  Also, latest commit in spruned repo is May 17.   Maybe no longer maintained?

Still, it would be nice to remain compatible.  How necessary is this initialblockdownload field?  Can it safely be ignored if not present?

note this is blocking testing/verification in #2779.

**Comment by trueptolemy** [comment]
https://github.com/gdassori/spruned/blob/171336b6f950f00d44fe9e598ac467c3fc17b735/spruned/application/spruned_vo_service.py#L250-L267

It looks the `getblockchaininfo` of spruned doesn't have `initialblockdownload` field. 
Maybe we can relax the requirements for `initialblockdownload`. Check it if exists.

**Comment by trueptolemy** [comment]
It's `spruned`'s issue. And it's not suitable for this problem to actively reduce `clightning`'s stability.
Sorry for that.
You can wait for @darosior 's nice PR(https://github.com/gdassori/spruned/pull/106) to be merged into `spruned` repo. Or you can change your own `spruned` like that PR.
Hope that helps!

**Comment by dan-da** [comment]
fair enough, thanks.
