### ISSUE TITLE
Makefile error with v0.7.3rc1: *** "ERROR: git is required for generating version information". Stop.

### ISSUE THREAD

**Issue by vincenzopalazzo** [ElementsProject/lightning#3154]
### Issue and Steps to Reproduce
I download the version v0.7.3rc1.zip  with this command

```
wget https://github.com/ElementsProject/lightning/archive/v0.7.3rc1.zip && unzip v0.7.3rc1.zip
cd lightning-0.7.3rc1 && ./configure && make
```

I get this error 

`Makefile:7: *** "ERROR: git is required for generating version information".  Stop.`

For resolving it, I try to change this line 
`VERSION=$(shell git describe --always --dirty=-modded --abbrev=7 2>/dev/null || pwd | sed -n 's,.*/clightning-\(v[0-9.rc]*\)$$,\1,p')`

with this

`VERSION=$(shell git describe --always --dirty=-modded --abbrev=7 2>/dev/null || pwd | sed -n 's,.*/lightning-\([0-9.rc]*\)$$,\1,p')`

Well go on but I get this error

```
/bin/sh: 1: ./tools/autogen.sh: not found
external/Makefile:54: recipe for target 'external/libwally-core/src/libwallycore.la' failed
make: *** [external/libwally-core/src/libwallycore.la] Error 127

```

I noted the external project are empty, I thy this code
`rm -r external/libwally-core && cd external/ && git clone https://github.com/ElementsProject/libwally-core.git && cd .. && make`

The installer run but I get this error
`external/Makefile:61: recipe for target 'external/jsmn/jsmn.c' failed
make: *** [external/jsmn/jsmn.c] Error 1
rm external/libwally-core/src/secp256k1/libsecp256k1.la
`

My question is now: I have run the command to build the lib wrong? so ` ./configure && make` if no, I want to create this issue, I don't know the make system for try to fix it, I hope this issue contains the right information to help you

**Comment by darosior** [comment]
Weird the first case was corrected in https://github.com/ElementsProject/lightning/pull/2926/commits/cb1120237844e7bbae5585d73ed8da491370bb55. Investigating the second one.

**Comment by vincenzopalazzo** [comment]
@darosior so for compile the version `rc` what command for compiling it I can use?

**Comment by darosior** [comment]
```bash
git clone https://github.com/ElementsProject/lightning
cd lightning && git fetch origin && git checkout v0.7.3rc1
./configure && make
```

**Comment by vincenzopalazzo** [comment]
Work!

Thanks

**Comment by darosior** [comment]
Thanks for testing the rc ;-)
