### ISSUE TITLE
Can't use dev-fast-gossip in configuration file

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#3160]
I tried to use `dev-fast-gossip=1` to activate the dev-fast-gossip in configuration but this does not work:

```
lightning config file line 6: dev-fast-gossip: doesn't allow an argument
```

**Comment by cdecker** [comment]
It's not a command line option that accepts an argument, it's a flag that has to be specified on the command line when starting the daemon. You need to remove the `=1` part of the option. This will work in your config:

```
dev-fast-gossip
```

**Comment by NicolasDorier** [comment]
it works!
