### ISSUE TITLE
Build v0.7.3rc1 on OSX fails - gossipd/test/../seeker.c:566:5: error

### ISSUE THREAD

**Issue by willcl-ark** [ElementsProject/lightning#3162]
OSX 10.14.6
C-Lightning v0.7.3rc1
Try to build...

error about 2 screens up from bottom:
`gossipd/test/../seeker.c:566:5: error: format '%zu' expects argument of type 'size_t', but argument 7 has type 'u64' {aka 'long long unsigned int'} [-Werror=format=]`

[build.log](https://github.com/ElementsProject/lightning/files/3726321/build.log)

**Comment by cdecker** [comment]
Should be addressed by #3158. @willcl-ark can you check?

**Comment by willcl-ark** [comment]
@cdecker Yes rc2 works for me
