### ISSUE TITLE
Dinner for c-lightning contributors

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#3187]
### Issue and Steps to Reproduce

We're having a c-lightning contributor dinner tonight in Berlin at 7. Find us for details!

**Comment by m-schmoock** [comment]
I'm sorry I can't attend since I booked my holidays few weeks before the LN conference was even announced . Have fun and see you next time for sure!

**Comment by practicalswift** [comment]
Thanks for the invitation! I can't attend but I hope you all have an amazing dinner!

**Comment by conscott** [comment]
Ah, I missed this email until now :(

**Comment by renepickhardt** [comment]
You forgot to add the output of `lightning-cli getinfo` it's really hard to debug this. Maybe we could reproduce this in future?

**Comment by cdecker** [comment]
> You forgot to add the output of `lightning-cli getinfo` it's really hard to debug this. Maybe we could reproduce this in future?

Agreed, best to add an integration test to run on every PR :-)

**Comment by darosior** [comment]
> Agreed, best to add an integration test to run on every PR :-)

Definitely to be included before 0.7.3!

**Comment by niftynei** [comment]
closing this, unable to reproduce locally :'(

**Comment by Saibato** [comment]
> closing this, unable to reproduce locally :'(

I have this feeling the bug hint was in the late dessert, irreproduceable tACK , Thx :heart_eyes:

**Comment by jb55** [comment]
awesome dinner, thanks for the invite!
