### ISSUE TITLE
consistent crash in listforwards

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#3189]
on 78c9d691117b6c27dfeffcfc575e2748cc25bebf

`lightning-cli listforwards` crashes my node every time after updating to master:

log:
https://jb55.com/s/842a84c59c6bea65.txt

**Comment by cdecker** [comment]
Ok, this took me a while to figure out: it seems that you had a forwarded a payment somewhere between commits 66a47d2761 (which started tracking forwardings) and d901304120 (which added the `received_time` column). This explains why you have a `NULL` value in that column while we only ever insert rows with that value set.

I thought about adding a `COMPAT_072` flag and add an `is_null` check, but I think that'd just postpone the same issue until we remove that compat flag. So I opted to create a migration that just emulates the sqlite3 behavior in postgres.
