### ISSUE TITLE
Have gossipd generate node_announcement automatically

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#320]
1. Change hsmd so gossip can ask for sigs on node_announcement.
2. Pass addresses, color and alias through to gossipd.
3. Have gossipd `handle_channel_announcement` return true if msg is about us, and new.
4. Move signing code from master to gossipd.

**Comment by rustyrussell** [comment]
Moved to 0.6, since it's happening with more regularity now.

**Comment by cdecker** [comment]
Agreed, will slice up the big PR I am currently debugging to fix this first, before addressing #284 which still has a flaky test when running in `valgrind`

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> Agreed, will slice up the big PR I am currently debugging to fix this first, before addressing #284 which still has a flaky test when running in `valgrind`

I've implemented, ran into reproducible gossip problem which is (I
think!) pre-existing.

Hope to push today...
