### ISSUE TITLE
`init` sends globalfeatures=0x08

### ISSUE THREAD

**Issue by nayuta-ueno** [ElementsProject/lightning#323]
[current c-lightning](https://github.com/ElementsProject/lightning/tree/ebdecebb1a89f7dcd8daa53c57ec58af32f7c40d) sends `globalfeatures=0x08` at `init` message.
[latest BOLT9](https://github.com/lightningnetwork/lightning-rfc/blob/58d4d9bca3ae5896eeea4b46324df27b8ecb0ce1/09-features.md#assigned-globalfeatures-flags) isn't assign global features.

   received raw message from c-lightning : `00100001080000`

Maybe, `init` sends `localfeatures=0x08` few weeks ago commit.

**Comment by rustyrussell** [comment]
Oops!  Yes, I flipped them when we tell gossipd what the features are!  Good spotting...
