### ISSUE TITLE
Be notfied once a onion failure happens (Allow offline invoice generation feature)

### ISSUE THREAD

**Issue by tiero** [ElementsProject/lightning#3235]
Background: I'm trying to implement the idea explained here https://lists.linuxfoundation.org/pipermail/lightning-dev/2019-June/002009.html

TL;DR an offline vending machine generates an BOLT11 invoice with ephemeral node pub key generated on the fly and put in the routing hints the actual route needed in order to reach our online node. 

If I would implement this, how I can detect the Onion Failure and subsequently use the encoded pre-image to actual redeem the invoice? A hook from lightingd would be perfect, so a plugin that redeem the HTLC can be developed on top

**Comment by cdecker** [comment]
I think the [`htlc_accepted`](https://lightning.readthedocs.io/PLUGINS.html#htlc-accepted) hook is what you're looking for. It'll get the onion, from which you can then extract all the fields (including the short-channel-id that was returned as the routing hint), and decide how to settle it using either `resolve` or `fail` as a result.
