### ISSUE TITLE
Version v0.7.3-113-gdda792c crashes all the time

### ISSUE THREAD

**Issue by sumBTC** [ElementsProject/lightning#3269]
### Issue and Steps to Reproduce

See this [file](http://82.217.214.215/out_fail.txt). Rebuilding the gossip_store didn't help

### `getinfo` output
`{
   "id": "026bc066924bca8a22e4baa751533bf2dda4161544d08dab544a001a5385ab0d0c",
   "alias": "myshtery",
   "color": "23375f",
   "num_peers": 5,
   "num_pending_channels": 1,
   "num_active_channels": 0,
   "num_inactive_channels": 4,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "192.168.178.20",
         "port": 9835
      }
   ],
   "version": "v0.7.3-113-gdda792c",
   "blockheight": 604360,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/user/.lightning_test"
}
`

**Comment by rustyrussell** [comment]
Good catch, and great report.  Reproducing now, then will write fix.

Thanks for the report!

**Comment by sumBTC** [comment]
I've seen the fix and understand why you're so glad I reported this: a c programmer's worst nightmare :-)
