### ISSUE TITLE
towire_tlv_uint writes a variable number of bytes

### ISSUE THREAD

**Issue by devrandom** [ElementsProject/lightning#3272]
In https://github.com/ElementsProject/lightning/blob/7283efa5b5a302208aef699a81903d51cb3ab45d/wire/towire.c#L47

we write a variable number of bytes (e.g. a single byte if the input is less than 256).  However, when deserializing, we will always read the type's length.

**Comment by devrandom** [comment]
For reference, he's the matching deserialization code.  Note that `*max`, `length` and `maxlen` seem to be always equal.

**Comment by rustyrussell** [comment]
This is by design: tu* are only used within TLVs, which explicitly indicate the length:

From https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md:

```
Inside TLV records which contain a single value, leading zeros in
integers can be omitted:

* `tu16`: a 0 to 2 byte unsigned integer
* `tu32`: a 0 to 4 byte unsigned integer
* `tu64`: a 0 to 8 byte unsigned integer
```

**Comment by devrandom** [comment]
Ah, the actual length is serialized and is passed in via `*max` by `fromwire_tlvs`.  Thank you, I was confused by the calling convention.
