### ISSUE TITLE
Node can't sync with bitcoind getblock

### ISSUE THREAD

**Issue by LightningK0ala** [ElementsProject/lightning#3282]
My c-lightning node is unable to accept payments.
Logs are showing `Deferring incoming commit until we sync` messages.

There's also messages about getblock failing:
```
2019-11-21T11:58:25.435Z UNUSUAL lightningd(6): bitcoin-cli -rpcconnect=REDACTED -rpcport=REDACTED -rpcuser=... -rpcpassword=... getblock 0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41 false exited with status 1

2019-11-21T11:59:02.431Z UNUSUAL lightningd(6): bitcoin-cli: finished bitcoin-cli -rpcconnect=REDACTED -rpcport=REDACTED -rpcuser=... -rpcpassword=... getblock 0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41 false (35994 ms)
```

`getinfo` is showing the last block height synced was 604332 (should be 604764 as of writting).

I'm also having trouble with an lnd node connected to the same bitcoin rpc.
I've enabled rpc logs on bitcoind and don't see any errors there. The node is synced and accepting rpc connections (I see the calls being made by c-lightning and lnd).

Bitcoin Core version: 0.18.0
c-lightning: master branch commit a420422

### Issue and Steps to Reproduce
Not sure how to reproduce this reliably. Can't find information on other people having a similar issue.

### `getinfo` output
```
{
   "id": "024655b768ef40951b20053a5c4b951606d4d86085d51238f2c67c7dec29c792ca",
   "alias": "satoshis.place",
   "color": "42f474",
   "num_peers": 101,
   "num_pending_channels": 5,
   "num_active_channels": 87,
   "num_inactive_channels": 8,
   "address": [
      {
         "type": "ipv4",
         "address": "88.98.213.236",
         "port": 9777
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.7.2.1-322-ga420422",
   "blockheight": 604332,
   "network": "bitcoin",
   "msatoshi_fees_collected": 218622,
   "fees_collected_msat": "218622msat",
   "warning_lightningd_sync": "Still loading latest blocks from bitcoind."
}
```

I'm thinking this is probably an issue on the bitcoin node side, but as far as I can tell it seems to be fine? Is it possible that the block is corrupt?

**Comment by jb55** [comment]
I wonder if this fixes it. here's 0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41 from my node:

```
curl -sL https://jb55.com/s/0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41.txt.gz | gunzip > 0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41
```

then using a fake `bitcoin-cli`:

```sh
#!/usr/bin/env bash

for arg in "$@"
do
  if [ $arg == "0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41" ]
  then
    exec cat 0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41
  fi
done

exec bitcoin-cli "$@"
```

**Comment by cdecker** [comment]
> There's also messages about getblock failing:
> 
> ```
> 2019-11-21T11:58:25.435Z UNUSUAL lightningd(6): bitcoin-cli -rpcconnect=REDACTED -rpcport=REDACTED -rpcuser=... -rpcpassword=... getblock 0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41 false exited with status 1
> 
> 2019-11-21T11:59:02.431Z UNUSUAL lightningd(6): bitcoin-cli: finished bitcoin-cli -rpcconnect=REDACTED -rpcport=REDACTED -rpcuser=... -rpcpassword=... getblock 0000000000000000000df010034374a27e83a716bd56069a927ee65675d70d41 false (35994 ms)
> ```

Could you try running that `getblock` command manually from the command line (with the appropriate `rpcuser` and `rpcpassword`)? If we get a corrupted result it's `bitcoind`, otherwise the result should still give us a clue (and we can compare it with the result from @jb55 at least).

**Comment by jb55** [comment]
just to be clear, this isn't a pruned node is it? I'm reminded of this issue https://github.com/ElementsProject/lightning/issues/1502

**Comment by LightningK0ala** [comment]
It's not a pruned node...
I ran `getblock` manually from the command line and got what seems like a valid response (see [pastebin](https://pastebin.com/9sEnqMZs)).

@jb55 the gunzipped link you sent looks like a long hex string? Was that meant to be a json? Not sure how i would jerry rig it for c-lightning rpc call to receive as a response. To clarify the bitcoin node is in a different machine from the lightning node.

**Comment by cdecker** [comment]
@LightningK0ala did you forget the `false` when running it? `false` tells `bitcoind` not to parse the block but to return the raw hex encoded block instead (that's what @jb55 posted as well).

Fwiw my result for the decoded block is identical to yours.

**Comment by LightningK0ala** [comment]
oh, I did forget the `false` flag, looks like it's the same :/

**Comment by LightningK0ala** [comment]
I figured out the issue. I rate limited the bandwidth on my bitcoin + c-lightning instances recently and that was causing a timeout on getblock. Unfortunately the error message from `bitcoin-cli` doesn't warn you that the command failed due to a timeout.

Anyway thanks so much for the help @jb55 @cdecker.

**Comment by cdecker** [comment]
> I figured out the issue. I rate limited the bandwidth on my bitcoin + c-lightning instances recently and that was causing a timeout on getblock. Unfortunately the error message from `bitcoin-cli` doesn't warn you that the command failed due to a timeout.

Thanks for the all-clear @LightningK0ala, any way we could help make these things more clear/easier to debug?

**Comment by LightningK0ala** [comment]
@cdecker I think the problem is that bitcoin rpc doesn't give a helpful status error for timeout, so I'm not sure how c-lightning would know if it was in fact a timeout.

But yea a timeout status code / message would have been more helpful :)
