### ISSUE TITLE
MacOS: Tests: Error installing psycopg2

### ISSUE THREAD

**Issue by willcl-ark** [ElementsProject/lightning#3291]
MacOS 10.15.1 (19B88)

### Issue and Steps to Reproduce
* clone repo
* activate venv
* attempt `pip install -r tests/requirements.txt`, results in following error:

[install_psycopg2.log](https://github.com/ElementsProject/lightning/files/3886836/install_psycopg2.log)

It seems that this is related to missing system postgresql, so after a `brew install postgresql` was successful I re-ran `pip install -r tests/requirements.txt` resulting in the longer error log:

[install_psycopg2_with_postgresql.log](https://github.com/ElementsProject/lightning/files/3886520/install_psycopg2-binary.log)

In order to fix this, I was required to install openssl via brew with `brew install openssl`, then export the LDFLAGS, CPPFLAGS and PKG_CONFIG_PATH into my local environment

Potential fixes:

1. Switch to `psycopg2-binary` package to allow install to proceed without error on MacOS. I have not tested the effects of this on the test suite, and assume that this "black box" fix probably won't be favourable.

2. I'm not sure if it's worth adding a tests-specific INSTALL.md to /tests/ as there seems to be some specific installation instructions, at least for MacOS? In this case, we could add `brew install openssl` to the MacOS section of this document, along with instruction to export the flags. If these are already included in regular INSTALL.md for other OS's, then we can just add it in there?

**Comment by cdecker** [comment]
Notice that tests/requirements.txt already has the binary package as dependency. I'll unite the various requirements files into a top-level one instead so we don't hide them as much :wink:

**Comment by willcl-ark** [comment]
In that case, I found bumping the binary version to 2.8.4 also fixed the issue

**Comment by willcl-ark** [comment]
@cdecker just to be clear in confirming that, with `postgresql` installed via brew, 

`pip install psycopg2-binary==2.8.3` -- Fails

`pip install psycopg2-binary==2.8.4` -- passes

So probably just need to bump that version (and possibly include postgresql as a test requirement?)

**Comment by cdecker** [comment]
Closing since we bumped that dependency :-)
