### ISSUE TITLE
feature: show status of each direction of each channel in listpeers

### ISSUE THREAD

**Issue by 9735dev** [ElementsProject/lightning#3304]
Currently, one has to grep the server log for the short channel id in order to determine the status of each direction of a node's channel. It would be useful to have this information displayed in the `listpeers` RPC output.

For more info that status that this issue is concerned with, see `channel_flags` at 
https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-channel_update-message

**Comment by whitslack** [comment]
You don't have to grep the server log. Just use the `listchannels <scid>` command.

**Comment by 9735dev** [comment]
@whitslack you're right, thanks. that is helpful. `channel_flags` and/or the `active` property of each channel object can provide this.
