### ISSUE TITLE
c-lightning upgrade (0.7.0 -> 0.7.3) generates gossip_store_compact: bad version

### ISSUE THREAD

**Issue by jaro2k** [ElementsProject/lightning#3305]
I swapped container from c-lightning version 0.7.0 to 0.7.3 by stopping old container (0.7.0) and creating a new with version 0.7.3 and let new container to use existing file-system where "lightning-dir" was pointing at: "/root/.lightning"

Everything seems to work fine except this message throwing during the container startup:

INFO lightningd(7): Updating database from version 92 to 114                                                       
**BROKEN** lightning_gossipd(20): gossip_store_compact: bad version                                                
UNUSUAL lightning_gossipd(20): Gossip store version 3 not 7: removing                                              
INFO lightningd(7): --------------------------------------------------                                             
INFO lightningd(7): Server started with public key 02ca4c46faa50b2d...
 alias Europe-Lightning-Hub.eu (color #ff45aa) and lightningd v0.7.3                                                                        

I restarted the container and the message remains similar:

**BROKEN** lightning_gossipd(20): gossip_store_compact: bad version                                                   
UNUSUAL lightning_gossipd(20): Gossip store version 0 not 7: removing                                                 

Is this something to worry about? How can I fix it?
Thank you

**Comment by rustyrussell** [comment]
Naah, it's fine; we throw away old gossip stores when we upgrade in an incompatible way, and then re-request them from other nodes.

**Comment by jaro2k** [comment]
Yes, that makes sense.. to display the message first one when this is detected. But in my case, I see this message shown every-time c-lightning is restarted. That's why I'm a bit suspicious on this behaviour. Tks.
