### ISSUE TITLE
Feerate should be msats, not sats.

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#3313]
Hi, this is from the documentation on: https://lightning.readthedocs.io/lightning-withdraw.7.html

Otherwise, feerate is a number, with an optional suffix: perkw means the number is interpreted as satoshi-per-kilosipa (weight), and perkb means it is interpreted bitcoind-style as satoshi-per-kilobyte. Omitting the suffix is equivalent to perkb.

The clients help says: "withdraw destination satoshi [feerate] [minconf] [utxos]"

This is confusing, as the command line only works with milisatoshis and not sats.

**Comment by darosior** [comment]
> This is confusing, as the command line only works with milisatoshis and not sats.

The `feerate` parameters takes sats, for example withdrawing with `feerate=253perkw` will make a transaction at the min relay fee.

**Comment by m-schmoock** [comment]
@Coinomatron Currently, commands related to onchain stuff (like withdrawal) use `sats` as unit and lightning network commands, such as `invoice`, will use `msat`. This is because we are actually having two different networks here with two different base units.

p.s. Hooray, if you want to rename `msat` to `dorian`   :D

**Comment by m-schmoock** [comment]
@Coinomatron Currently, commands related to onchain stuff (like withdrawal) use sats as unit and lightning network commands, such as invoice, will use msat. This is because we are actually having two different networks here with two different base units.

**Comment by Coinomatron** [comment]
Thanks for the feedback, closing.
