### ISSUE TITLE
Fix the docs URL in bitcoin-bot/changelog

### ISSUE THREAD

**Issue by vasild** [ElementsProject/lightning#3348]
Fix the URL in the `bitcoin-bot/changelog` message:
```
This PR is missing a changelog entry. https://lightning.readthedocs.io/HACKING.html#changelog-entries-in-commit-messages
```
to
https://lightning.readthedocs.io/STYLE.html#changelog-entries-in-commit-messages
(or https://github.com/ElementsProject/lightning/blob/master/doc/STYLE.md#changelog-entries-in-commit-messages)

**Comment by m-schmoock** [comment]
@cdecker your turn I guess

**Comment by cdecker** [comment]
Should be fixed. I'll keep this open for now until we have confirmation. Thanks @vasild for reporting this :+1:

**Comment by vasild** [comment]
It works - I deliberately left https://github.com/ElementsProject/lightning/pull/3349 without `Changelog-*` and now the hook says:
```
Pending — This PR is missing a changelog entry. https://lightning.readth...
```
with a tool-tip displaying the full message:
```
This PR is missing a changelog entry. https://lightning.readthedocs.io/STYLE.html#changelog-entries-in-commit-messages
```

I think this issue can be closed.

**Comment by cdecker** [comment]
Thanks for confirming @vasild :+1: Closing ^^
