### ISSUE TITLE
How to properly fund channels using bitcoind and c-lightning 8.0 - Docker Issue??

### ISSUE THREAD

**Issue by CMDRZOD** [ElementsProject/lightning#3373]
Hi there. I've created a wallet on my lightning node but I am having a hard time trying to fund any channels I open.

What I don't understand is how to properly send the funds from my internal wallet to the channel I've opened.

Do I have to use an external wallet on bitcoind? If so, how do I use fundchannel_complete?

How can I know the txout for fundchannel_complete if the transaction is not broadcast yet?

Please send me some pointers. Thanks for your help.
PS It seems fundchannel itself has been depreciated so now all tutorials on the web are no longer helpful.
I've tried to open channels to other nodes but I ended up having to dev-close-channel on them due to my funding never reaching the channel.
listfunds output:
{
   "outputs": [
      {
         "txid": "1674cb03916c88e4a0c7f4b2dfc075c3cdc8f4de7c1fbed0106c9cdfd4fcf425",
         "output": 1,
         "value": 9800000,
         "amount_msat": "9800000000msat",
         "address": "bc1qu4cgm93nnzqyu9yzmuu2q3977czuvtafwk7hgx",
         "status": "confirmed",
         "blockheight": 607622
      }
   ],
   "channels": []
}
More info:https://1ml.com/node/02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a
This node is very old and I've upgraded it many times. Maybe it's time to start fresh?

**Comment by pbcub2** [comment]
I dont know yet how this system works yet, but it looks like you dont have any channels?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by CMDRZOD** [comment]
Yeah I had some open, but like I say the channel would never confirm funding. Once I tried fundchannel_complete, I would use the funds listed above, using 1 for the txout. Using this method my funding would never confirm.

**Comment by pbcub2** [comment]
I was talking about in that output, the channels is empty, is that in relation to the transaction not being able to find a channel to fund through, or would that mean that for some reason your system doesnt have channels tied to the system? Idk, I'm just throwing out an idea.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by CMDRZOD** [comment]
I know what you're saying, and I think you're on the right path. How can I add channels to that funding tx to be able to apply those funds? Should I remove the funds back to my bitcoind wallet, and fund the channels individually?

I just need a bit of a tutorial, now that fundchannel no longer works I am lost lol. Appreciate the help.

**Comment by pbcub2** [comment]
If I can find a second to try to find some documentation, I will for ya. I'm glad I can throw out a idea that might be on the right path. If the system isnt allowing you to open persistent channels, the question then becomes "why?". Perhaps it's a system issue, perhaps it's a bigger issue. Also, shout out to GitHub, this is the first time I've figured out I can directly respond to these via email, which makes me efficient. 😎 Happy Debugging.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by CMDRZOD** [comment]
What I'm trying:
Connecting to this node: https://1ml.com/node/0394e00d56a9e54a3d29036d218a607eb87257c10a4109fbb964b5c5c03c405329

lightning-cli connect 0394e00d56a9e54a3d29036d218a607eb87257c10a4109fbb964b5c5c03c405
329@185.153.197.25:9735

lightning-cli fundchannel_start 0394e00d56a9e54a3d29036d218a607eb87257c10a4109fbb96
4b5c5c03c405329 900000
{
   "funding_address": "bc1qn8r3agvlt8qvvlv7cupqhhgzysd7vejac0e5f6tp6a22enmcgrlqd2xhj0",
   "scriptpubkey": "002099c71ea19f59c0c67d9ec7020bdd02241be6665dc3f344e961d754accf7840fe"
}
If I list funds at this point it is the same output as above, channels is empty.

list peers at this point: lightning-cli listpeers   
                                
{                                                                                                                         
 "peers": [
      {
         "id": "0394e00d56a9e54a3d29036d218a607eb87257c10a4109fbb964b5c5c03c405329",
         "connected": true,
         "netaddr": [
            "185.153.197.25:9735"
         ],
         "globalfeatures": "",
         "localfeatures": "81",
         "features": "81",
         "channels": [
            {
               "state": "OPENINGD",
               "owner": "lightning_openingd",
               "funding": "LOCAL",
               "status": [
                  "Funding channel start: awaiting funding_txid with output to 002099c71ea19f59c0c67d9ec7020bdd02241be6$
65dc3f344e961d754accf7840fe"
               ],
               "msatoshi_to_us": 900000000,
               "to_us_msat": "900000000msat",
               "msatoshi_total": 900000000,
               "total_msat": "900000000msat"
            }
         ]
      }
   ]


Just need to know the next step to fund this channel using bitcoind. Is this the right way to fund my channel from my internal lightning wallet? Thanks again.

**Comment by ZmnSCPxj** [comment]
> PS It seems fundchannel itself has been depreciated so now all tutorials on the web are no longer helpful.

This is untrue.  `fundchannel` should be used by users and all tutorials on the web should still be followed.

`fundchannel_start` and `fundchannel_complete` are low-level commands and should only be used if you have intimate knowledge of C-Lightning and the Lightning protocol.  If you do not read BOLT specs regularly, avoid using these commands!

Instead, try this: https://github.com/ElementsProject/lightning/blob/051b5bd1bf91085b0c94312c90ed053ef2790170/README.md#opening-a-channel

**Comment by pbcub2** [comment]
Thank you so much for your contribution and documentation reference. Learned something new about this system, avoid fundchannel without due caution. Good to know. 😎🙏

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ZmnSCPxj** [comment]
> avoid fundchannel without due caution.

This is incorrect.  ***Do*** use `fundchannel`.  What you have to avoid are the `_` variants: `fundchannel_start`, `fundchannel_complete`, and `fundchannel_cancel`.

**Comment by pbcub2** [comment]
I love being corrected. Again thank you.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by pbcub2** [comment]
Furthering context: I'm currently working UberEats as I'm currently homeless due to unforeseen circumstances. I'm trying to keep up with the lightening project as I plan on integrating it into my open source POS system, you just broke me right as I knocked on a door and the customer answered 😂😂. The reason why is because its been rare through my attempts to get back on my feet that I've been flat out corrected, most people just flat out call me crazy or dismiss me, or the good ones give me slightly different perspectives on my ideas; I crave being corrected and that's why you broke me, so it's a good thing. I'm always willing to throw out ideas even if I'm dead wrong because I would rather be wrong than not attempt anything, which is why I commented on this today despite being day one new to this project; theres no harm in trying. Thank you again for correcting me, I ask others to do the same as that's how I learn and become better.

The reason I got confused: I saw lightening-cli and went "ah, so we should try to keep it cli", so I guess I'm confused as to how to properly use these systems. Something Im sure I'll learn as I research more into the project.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ZmnSCPxj** [comment]
`lightning-cli` is a convenience wrapper for node operators to do monitoring stuff like `listfunds` and `listforwards` etc.  For programs that need to control a C-Lightning node, you generally break out a JSON-RPC library and connect to the C-Lightning RPC.

Regardless `fundchannel` should still exist on `lightning-cli`, are you unable to execute the plain `fundchannel` over `lightning-cli`?

**Comment by CMDRZOD** [comment]
> `lightning-cli` is a convenience wrapper for node operators to do monitoring stuff like `listfunds` and `listforwards` etc. For programs that need to control a C-Lightning node, you generally break out a JSON-RPC library and connect to the C-Lightning RPC.
> 
> Regardless `fundchannel` should still exist on `lightning-cli`, are you unable to execute the plain `fundchannel` over `lightning-cli`?

Yes this is correct. Output pasted below. fundchannel did not work in the last c-lightning release or the 8.0 git version I pulled today.

lightning-cli fundchannel 0394e00d56a9e54a3d29036d218a607eb87257c10a4109fbb964b5c5c03c405329@185.153.197.25:9735 5000
{
   "code": -32601,
   "message": "Unknown command 'fundchannel'"
}

**Comment by pbcub2** [comment]
I havent tried yet for me, I havent gotten my hands on a copy to play with yet. But I'm definitely interested in learning/discussing how I should go about integrating this. I plan creating my POS system as a web app that can be integrated easily into SaaS services, perhaps through a fork of BTCPayServer 🤷‍♂️. I know they use this project (because that's how I found it lol). I could also host a lightning server as a microservice to my overall structure and ping it with my requests.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by CMDRZOD** [comment]
The biggest reason I thought that fundchannel is gone, I can't find it in the help either. Just it's low level cousins I refer to above.

**Comment by ZmnSCPxj** [comment]
It probably means it is not being recognized in the plugins.  Can you find a `pay` command in the help?  We have started to move many bits of functionality into plugins that are delivered with the distribution, but there are sometimes some problems with starting the plugins.  How exactly do you run the `lightningd`? How did you compile and so on?

**Comment by CMDRZOD** [comment]
Just checked and there is no pay command either. I made a dockerfile to pull the latest lightning from git and run it through docker. 


FROM ubuntu:18.04
ENV LIGHTNINGD_VERSION=master

RUN apt-get update -qq && \
    apt-get install -qq -y software-properties-common && \
    add-apt-repository ppa:bitcoin/bitcoin -y && \
    apt-get install -qq -y --no-install-recommends --allow-unauthenticated python python3-mako zlib1g-dev python3 git m$
RUN apt-get install -y python3-pip python3-dev && \
    pip3 install dnspython networkx numpy pylightning

RUN git clone https://github.com/ElementsProject/lightning.git /opt/lightningd && \
    cd /opt/lightningd && \
    git checkout $LIGHTNINGD_VERSION && \
    ./configure --enable-developer && \
    make -j4 && cp lightningd/lightning* cli/lightning-cli /usr/bin/


ENV LIGHTNINGD_DATA=/root/.lightning
ENV LIGHTNINGD_RPC_PORT=9835

VOLUME [ "/root/.lightning" ]

EXPOSE 9735 9835
ENTRYPOINT  [ "/usr/bin/lightningd" ]

Then I run this docker file:

version: "3"
services:
  bitcoind:
    image: nicolasdorier/docker-bitcoin:0.18.1
    container_name: bitcoind
    environment:
      BITCOIN_EXTRA_ARGS: |
        testnet=0
        whitelist=192.168.6.250
        server=1
        dbcache=16384
        rpcuser=rpcuserhairhairhair
        rpcpassword=mypasswordnstuff
        addnode=192.168.6.250:8333
    expose:
      - "8333"
    ports:
      - "0.0.0.0:8333:8333"
    volumes:
      - "/home/hair/bitcoin-data:/data"
  clightning_bitcoin:
    image: d1d2da8778ec
    container_name: lightning-dev
    command:
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=rpcuserhairhairhair
      - --bitcoin-rpcpassword= mypasswordnstuff
      - --network=bitcoin
      - --alias=Nasty_Nardo
      - --rgb=FF4500
      - --log-level=debug
      - --announce-addr=23.17.160.159:9735
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9735"
    ports:
      - "0.0.0.0:9735:9735"
    volumes:
      - "/home/hair/bitcoin-data/.lightning:/root/.lightning"
      - "/home/hair/bitcoin-data:/etc/bitcoin"
    links:
      - bitcoind

Its a bit of a convoluted process and could be streamlined, but it works for me.

**Comment by ZmnSCPxj** [comment]
>     make -j4 && cp lightningd/lightning* cli/lightning-cli /usr/bin/

We have a `make install` that properly installs all binaries (though I am unsure if it will work within a Docker; @cdecker has more experience with Docker).  Your `cp` command only copies the base binaries and does not include the plugins, so that your installation does not include any plugins at all.

**Comment by CMDRZOD** [comment]
Alright I'll try to adjust my script to use make install. Really appreciate
the help and Happy Holidays!

**Comment by pbcub2** [comment]
I'm happy your issue seems to be resolved, I'm sorry I couldnt help you better, as mentioned I'm new to the project and gaining my footing. But I noticed something about this that made me want to comment. Happy Holidays man.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by CMDRZOD** [comment]
So had to make some changes to my first script. Now I have the plugin section in the help including the fundchannel and pay commands.  Will be experimenting with plugins like autopilot next! I will update once I've successfully established a channel. Whole Dockerfile below:

FROM ubuntu:18.04
ENV LIGHTNINGD_VERSION=master

RUN apt-get update -qq && \
    apt-get install -qq -y software-properties-common && \
    add-apt-repository ppa:bitcoin/bitcoin -y && \
    apt-get install -qq -y --no-install-recommends --allow-unauthenticated python python3-mako zlib1g-dev python3 git m$
RUN apt-get install -y python3-pip python3-dev && \
    pip3 install dnspython networkx numpy pylightning

RUN git clone https://github.com/ElementsProject/lightning.git /opt/lightningd && \
    cd /opt/lightningd && \
    git checkout $LIGHTNINGD_VERSION && \
    ./configure --enable-developer && \
    make -j4 && \
    make install


ENV LIGHTNINGD_DATA=/root/.lightning
ENV LIGHTNINGD_RPC_PORT=9835

VOLUME [ "/root/.lightning" ]

EXPOSE 9735 9835
ENTRYPOINT  [ "/usr/local/bin/lightningd" ]

**Comment by CMDRZOD** [comment]
Can confirm this is fixed, thank you everyone for the help. Merry Christmas!
