### ISSUE TITLE
Require all SQL parameters to be bound and explicitly set null if we don't have a value

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#338]
As pointed out by @rustyrussell this should help us detect an eventual off-by-one error in the parameter assignment.

**Comment by jsarenik** [comment]
How to find a case which does not use bound parameters or does not explicitly set null? Is it still in the code?

**Comment by jsarenik** [comment]
Ah, sorry, just realized the `v.0.6.1` tag means you will get to it after release. Sorry for bothering.

**Comment by cdecker** [comment]
No worries @jsarenik, we can definitely start working on this and merge it if it's ready earlier :-)

I'm not actually sure `sqlite3` has a way to enforce null parameters to be explicitly set, but a lot of our code looks like this:

```
...
if (a) {
    sqlite3_bind_int(stmt, 0, 42);
}
...
```

it'd be more readable to make if 

```
...
if (a) {
    sqlite3_bind_int(stmt, 0, 42);
} else {
    sqlite3_bind_null(stmt, 0);
}
...
```
in order to make that implicit null explicit.

**Comment by jsarenik** [comment]
```
~/src/lightning$ git grep -n -B1 "sqlite3_bind_" | grep "if (.*)\( {\)
*"
wallet/db.c-731-	if (!id) {
wallet/db.c-829-	if (!pks) {
wallet/invoices.c-301-	if (msatoshi)
wallet/wallet.c-90-	if (utxo->close_info) {
wallet/wallet.c-100-	if (utxo->blockheight) {
wallet/wallet.c-105-	if (utxo->spendheight)
wallet/wallet.c-889-	if (chan->scid)
wallet/wallet.c-908-	if (chan->remote_shutdown_scriptpubkey)
wallet/wallet.c-1121-	if (in->preimage)
wallet/wallet.c-1163-	if (out->in)
wallet/wallet.c-1171-	if (out->preimage)
wallet/wallet.c-1199-	if (payment_key)
wallet/wallet.c-1810-	if (failonionreply)
wallet/wallet.c-1819-	if (failnode)
wallet/wallet.c-1823-	if (failchannel) {
wallet/wallet.c-1831-	if (failupdate)
wallet/wallet.c-1973-	if (b->prev) {
wallet/wallet.c-2152-		if (blockheight) {
```

**Comment by jsarenik** [comment]
What about https://github.com/ElementsProject/lightning/blob/a06d37c1c3d8440abc50e5dfa5075db9336a818f/wallet/wallet.c#L889 ?

**Comment by jsarenik** [comment]
Also this does not have `bind_null`:

https://github.com/ElementsProject/lightning/blob/a06d37c1c3d8440abc50e5dfa5075db9336a818f/wallet/wallet.c#L908

**Comment by jsarenik** [comment]
And this

https://github.com/ElementsProject/lightning/blob/a06d37c1c3d8440abc50e5dfa5075db9336a818f/wallet/wallet.c#L1121

**Comment by jsarenik** [comment]
@cdecker can this one be closed already? I would suggest making a new issue or if Rusty's proposal for the much more ambitious plan described in #1588.

Or maybe leave it open until a source code check (in `make check-source`) is added that would check for any missing `bind_null`? What do you think?

**Comment by cdecker** [comment]
Good catch @jsarenik, totally forgot about this one :-)
