### ISSUE TITLE
FreeBSD make install: "mrkd" not known / incomplete documentation

### ISSUE THREAD

**Issue by minidisk1147** [ElementsProject/lightning#3381]
### Issue and Steps to Reproduce
On a FreeBSD 12.1 system, build lightning as described in the FreeBSD installation instructions.
"gmake install" exits with the following error:

if [ x"`git log doc/lightning-cli.1 | head -n1`" != x"`git log doc/lightning-cli.1.md | head -n1`" -o x"`git diff doc/lightning-cli.1.md`" != x"" ]; then mrkd doc/lightning-cli.1.md doc/lightning-cli.1; else touch doc/lightning-cli.1; fi
/bin/sh: mrkd: not found

### System Arch
FreeBSD 12.1-RELEASE-p1 GENERIC  amd64

### Workaround

     pkg install markdown
     ln -s /usr/loca/bin/markdown /usr/local/bin/mrkd
     gmake install

### Q:

What / Who is "mrkd"  (bsd-package, ports, github page)

**Comment by cdecker** [comment]
`mrkd` is a python package that converts markdown files to the man-page format. It can be installed using `pip` from pypi.

**Comment by minidisk1147** [comment]
Thanks for your response. I've tested with `mrkd` installed and would suggest small changes to INSTALL.md:

<pre>
diff --git a/doc/INSTALL.md b/doc/INSTALL.md
index 8bd10013..8304ab59 100644
--- a/doc/INSTALL.md
+++ b/doc/INSTALL.md
@@ -135,7 +135,8 @@ OS version: FreeBSD 11.1-RELEASE or above
 Get dependencies:

     # pkg install -y \
-      autoconf automake gettext git gmp gmake libtool python python3 sqlite3 libsodium py36-mako bash
+      autoconf automake gettext git gmp gmake libtool python python3 sqlite3 libsodium py36-mako py36-pip bash
+    # pip install mrkd

 If you don't have Bitcoin installed locally you'll need to install that
 as well:
@@ -149,6 +150,8 @@ Clone lightning:

 Build lightning:

+**Note**: Make sure you've set an utf-8 locale, e.g. `export LC_CTYPE=en_US.UTF-8`, otherwise manpage installation may fail.
+
     $ ./configure
     $ gmake
     $ gmake install
</pre>

**Comment by minidisk1147** [comment]
Works fine now.
Suggested some hints for building on FreeBSD
