### ISSUE TITLE
Persistent permissions for 'lightning-rpc'

### ISSUE THREAD

**Issue by Stadicus** [ElementsProject/lightning#3394]
In order to access the `lightning-rpc` socket with a different user, I would like to use group permissions `g+rw` set specifically on the socket (and nothing else in the lightning-dir).

As lightningd resets the permissions to `600` on every restart (probably by recreating the socket), I currently set these permissions with a script run by systemd after starting lightningd. It just waits 10s and then sets the permissions. Waiting a specific time is unreliable, though, as sometimes even 10s is not enough for the `lightning-rpc` socket to be recreated (e.g. if `bitcoind` is still warming up). And if there are external dependencies, maybe even waiting a few minutes might be not enough?

Is there a more elegant way to permanently set the `lightning-rpc` socket permissions, in my case to `660`?

**Comment by Stadicus** [comment]
Additional info: I also tried persisting the permissions using Access Control Lists, without success.

```bash
setfacl -d -m g::rx .lightning/bitcoin/
```
Directory listing
```bash
drwxr-x---+ 2 bitcoin bitcoin     4096 Jan  4 21:23 .
drwxr-x---  3 bitcoin bitcoin     4096 Jan  4 21:10 ..
-rw-------  1 bitcoin bitcoin 11201760 Jan  4 21:23 gossip_store
-rwx------  1 bitcoin bitcoin       32 Jan  4 21:00 hsm_secret
srw-------  1 bitcoin bitcoin        0 Jan  4 21:23 lightning-rpc
-rwx------  1 bitcoin bitcoin 11005952 Jan  4 21:23 lightningd.sqlite3
```

**Comment by cdecker** [comment]
Similar to https://github.com/ElementsProject/lightning/issues/1535 and https://github.com/ElementsProject/lightning/issues/1366.

One quick fix could be to have a plugin that calls `chmod` on `init`. But that's window-dressing, and I agree we should just keep the file across restarts, so manual changes are permanent.

**Comment by ZmnSCPxj** [comment]
My *possibly incorrect* understanding is that `bind` on the rpc-filename path creates an "overlay" of sorts, so that the disk filesystem at that path is never actually contacted by the kernel, thus it is *impossible* to persist.  So for example for an rpc-filename of `/home/bitcoin/.lightning/lightning-rpc` will not contact the disk at `/home`, instead it will be a kernel-level redirect of that path to the Unix socket subsytem.

Maybe @rustyrussell can give more accurate information.  Will dig for now....

**Comment by ZmnSCPxj** [comment]
@Stadicus would you consider #3437 a sufficient solution for your problem?

**Comment by Stadicus** [comment]
> @Stadicus would you consider #3437 a sufficient solution for your problem?

Thats the perfect feature to solve the issue we've been running into, easy to understand and configure, much appreciated.

**Comment by ZmnSCPxj** [comment]
Okay, closing.
