### ISSUE TITLE
fundchannel could return the maximum amount

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3402]
I'm trying to consolidate the funds from multiple closed channels into a new one.
I see the amounts in `listfunds` / `outputs`, i sum them, and i attempt to `fundchannel peer_id 1000000` with that amount. However, as expected, i get an error message:

```
{
   "code": 301,
   "message": "Cannot afford transaction"
} 
```

It would be nice if i could also the the correct amount in the error:

```
{
   "code": 301,
   "message": "Cannot afford transaction",
   "requested_amount": 1000000,
   "max_afforded_amount": 9871482
} 
```

**Comment by ZmnSCPxj** [comment]
You can use `all` in the `amount` to `fundchannel` to just get all the funds.  This will fail if it exceeds the wumbo limit 16777215sat, but then you could just specify the wumbo limit.

**Comment by cdecker** [comment]
@thestick613 can you confirm that this is what you wanted?

**Comment by thestick613** [comment]
Yes, it's ok.

**Comment by niftynei** [comment]
> This will fail if it exceeds the wumbo limit 16777215sat,

This is incorrect, if you specify 'all' and your wallet total is greater than the `max_funding`, we'll use the `max_funding` amount instead.

```
	/* Update funding to actual amount */
	if (fr->funding_all && amount_sat_greater(funding, chainparams->max_funding))
		funding = chainparams->max_funding;
```
via https://github.com/ElementsProject/lightning/blob/master/plugins/fundchannel.c#L381-L383

**Comment by ZmnSCPxj** [comment]
Yes, I noticed that belatedly.
