### ISSUE TITLE
Sendpay notifications not sent unless we have at least one waiter

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#3403]
It appears that the `sendpay_success` and `sendpay_failure` notifications are only sent if we also have at least one JSON connection actively waiting for the result. `notify_sendpay_failure` for example is only called from `sendpay_fail` which terminates a single `sendpay` command or a `waitsendpay` command. If there is no active command we don't call it, and therefore don't get a notification either:

https://github.com/ElementsProject/lightning/blob/899f5dee53203fb0fe49a0fcfc19c77454226261/lightningd/pay.c#L245-L266

The same is true for the success case (no waiter -> no notification). Furthermore if we have multiple waiters we may end up getting the notification multiple times... We also can't piggy back on `tell_waiters_failed` since we sometimes skip that and call `sendpay_fail` directly in a couple of places, replying only to a single `sendpay` or `waitsendpay` command.

We need to have a cleaner separation here: a command that retrieves a prior result, should be terminated directly and not result in a notification, while a notification should be issued whenever a payment attempt terminates independently of whether there is a waiter or not.

**Comment by ZmnSCPxj** [comment]
The "independent" `sendpay_fail` calls are reported when the payment is already in a particular failed state as soon as it is attempted, for example insufficient capacity on our direct channel, or the very first intermediate node is disconnected.

Aside from those, `payment_failed` is probably where you should hook the notifications.

`sendpay_fail` also gets called from `waitsendpay`.

I think you should hook failure at:

* `payment_failed`.  This handles the case where we successfully offerred the HTLC but the peer later fails it.
* `send_onion`.  Check the return value of `send_htlc_out` and if it is non-zero, trigger the notification.  This handles the case of immediate failure where we are unable to offer the HTLC at all.
