### ISSUE TITLE
Cryptographic handshake: Connection reset by peer.

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#3416]
### Issue and Steps to Reproduce
I was trying to check the availability of nodes to make better routing decisions. While doing that I tried to connect to every node on the network and discovered the error from the title several times. You can reuse the code from: https://github.com/renepickhardt/lightning-helpers/blob/master/availability/probe_online_nodes.py

I get several errors (as expected) because there is just a timeout of the connection. However I get several errors with a `crypotgraphic handshake` error for example this one: 

```
could not connect to 034389078da79098ffa96712a659fe58086a9f22e0b3dfd543d931e270037516e3 RPC call failed: method: connect, payload: {'id': '034389078da79098ffa96712a659fe58086a9f22e0b3dfd543d931e270037516e3'}, error: {'code': -1, 'message': '139.198.123.250:9835: Cryptographic handshake: Connection reset by peer. '}
```

I even reproduced it with loglevel-io and a new clear node:

```
$ lightningd --lightning-dir=/tmp/ln --network=bitcoin --bind-addr 127.0.0.1:9376 --log-level=io`
$ lightning-cli --lightning-dir=/tmp/ln connect 034389078da79098ffa96712a659fe58086a9f22e0b3dfd543d931e270037516e3 139.198.123.250 9835
```

which produces the following log output.
```
2020-01-15T12:17:36.399Z jsonrpc#25: [IN] 7b20226a736f6e72706322203a2022322e30222c20226d6574686f6422203a2022636f6e6e656374222c2022696422203a20226c696768746e696e672d636c69
2020-01-15T12:17:36.399Z jsonrpc#25: [IN] 2d3130303735222c2022706172616d7322203a5b2022303334333839303738646137393039386666613936373132613635396665353830383661396632326530
2020-01-15T12:17:36.399Z jsonrpc#25: [IN] 623364666435343364393331653237303033373531366533222c20223133392e3139382e3132332e323530222c20393833355d207d
2020-01-15T12:17:36.758Z DEBUG 034389078da79098ffa96712a659fe58086a9f22e0b3dfd543d931e270037516e3-connectd: Connected out, starting crypto
2020-01-15T12:17:41.498Z DEBUG lightningd: ... feerate estimate for normal hit floor 253
2020-01-15T12:17:41.498Z DEBUG lightningd: ... feerate estimate for slow hit floor 253
2020-01-15T12:18:11.505Z DEBUG gossipd: seeker: no peers, waiting
2020-01-15T12:18:11.541Z DEBUG lightningd: ... feerate estimate for normal hit floor 253
2020-01-15T12:18:11.541Z DEBUG lightningd: ... feerate estimate for slow hit floor 253
2020-01-15T12:18:37.112Z jsonrpc#25: [OUT] 7b226a736f6e727063223a22322e30222c226964223a226c696768746e696e672d636c692d3130303735222c226572726f72223a7b22636f6465223a2d312c226d657373616765223a223133392e3139382e3132332e3235303a393833353a2043727970746f677261706869632068616e647368616b653a20436f6e6e656374696f6e20726573657420627920706565722e20227d207d0a0a
2020-01-15T12:18:37.112Z DEBUG 034389078da79098ffa96712a659fe58086a9f22e0b3dfd543d931e270037516e3-connectd: Failed connected out: 139.198.123.250:9835: Cryptographic handshake: Connection reset by peer.
 ```

### `getinfo` output
```
{
   "id": "02a5d7aa269cec5aa53990d8424760cf4d2bed45a3608aef7d8d81489702f13266",
   "alias": "ANGRYSUCKER",
   "color": "02a5d7",
   "num_peers": 903,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "XXXXXXXX",
         "port": 9735
      },
      {
         "type": "ipv6",
         "address": "XXXXXXXXX",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.8.0",
   "blockheight": 612949,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/rpickhardt/.lightning/bitcoin"
}
```

**Comment by cdecker** [comment]
This is perfectly normal in the case we assumed a remote node ID that does not match the node's real ID. I've seen this a couple of times, when users reset their node (switching between testnet, regtest and mainnet nodes for example), but keep the IP, or the IP is recycled by the ISP (much less likely).

[BOLT 08](https://github.com/lightningnetwork/lightning-rfc/blob/master/08-transport.md) states in many places that if the handshake fails at any stage the connection is to be terminated, which is exactly what you're seeing:

Act One

> If v is an unrecognized handshake version, then the responder MUST abort the connection attempt.

> If the MAC check in this operation fails, then the initiator does not know the responder's static public key. If this is the case, then the responder MUST terminate the connection without any further messages.

Act Two

> If the MAC check in this operation fails, then the initiator MUST terminate the connection without any further messages.

Act Three:

> If the MAC check in this operation fails, then the responder MUST terminate the connection without any further messages.

**Comment by renepickhardt** [comment]
Yeah I also thought that the node might have changed its id but shouldn't the node at least be removed from gossip? in particular it is strange 1ml says that this node has active channels: 034389078da79098ffa96712a659fe58086a9f22e0b3dfd543d931e270037516e3 how can channels be announced and signed if the nodeid changes? 

I am a little confused now. But shouldn't it be impossible to keep channels open and change nodeid?

**Comment by cdecker** [comment]
> But shouldn't it be impossible to keep channels open and change nodeid?

It is, I'm not saying the node is inactive/deleted, but if an operator moves around some nodes, and they end up swapping IPs the result is what you're seeing.

> in particular it is strange 1ml says that this node has active channels

1ml is not authoritative xD The fact that the node is still publishing updates would explain why this node was not pruned from your local view of the network. Notice that an operator can have a node announce any IP they want (see `--announce-addr`), so a misconfigured node can also result in this.

> but shouldn't the node at least be removed from gossip?

Removal is passive, there is no "remove this channel, remove this node" message. Channels get pruned when there hasn't been an update for 2 weeks, and nodes get pruned if they have no active channels, i.e., their last channel is closed/pruned.
