### ISSUE TITLE
Add hooks for 'utxo' lifecycle

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/lightning#3426]
It'd be nice to be able to audit our wallet movements from a 3rd party plugin. To this end, I'd propose adding the following plugin notifications:

- `utxo_added`: new funds added to the wallet. notification payload should indicate source (new deposit, channel closure payout, reward from a penalty close, htlc sweep, etc)
- `utxo_spent`: utxo spent on chain. notification payload should indicate destination (external withdrawal, channel open, etc)

things to think about:
- should channel utxos be counted?

**Comment by ZmnSCPxj** [comment]
> should channel utxos be counted?

Better to send too much data than too little?

**Comment by niftynei** [comment]
superceded by #3588
