### ISSUE TITLE
`doc/TOR.md` does not mention the `statictor:` option for `--addr`

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#3430]
We already have the ability to make a persistent Tor address without having to modify the `torrc`, but `doc/TOR.md` does not mention it.  `lightningd-config.5` does, though.

If my understanding is correct, if the desire is to have a persistent hidden service and not announce any other method of contact, then assuming a standard Tor installation (9050 SOCKS5, 9051 control) on the same hardware:

    --proxy=127.0.0.1:9050 --bind-addr=127.0.0.1:9735 --addr=statictor:127.0.0.1:9051

Would that be correct @Saibato @cdecker ?

**Comment by Saibato** [comment]
Yup and BTW i would use --always-use-proxy=true , i left some work TODO so others can take part in the process of evolving c/ln and contribute from a user perspective.
