### ISSUE TITLE
listfunds does not display unconfirmed transactions

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#3451]
### Issue and Steps to Reproduce

I'm starting a new LN node and funding it from `bitcoind`. I send a transaction to the address returned by `lightning-cli newaddr`, but while the transaction is not confirmed, `lightning-cli listfunds` shows this:
```
{
   "outputs": [],
   "channels": []
}
```
I understand that the funds are usable only after the transaction is confirmed, but I suppose the current situation induces unnecessary stress for users (are my funds lost? Have I sent to the wrong address?). It probably would be better to show the unconfirmed outputs anyway with an `unconfirmed` status (after all, there should be a reason why `status: confirmed` is included in `listfunds`' output):
```
{
   "outputs": [
      {
         "txid": "cc87b88666c7d729268f3e787eba746113d7a8f0496c86ef0915f7bb8fc2f48b",
         "output": 1,
         "value": 3200000,
         "amount_msat": "3200000000msat",
         "address": "tb1q0kv6l6hd35995dpja2fsjg09y5s7f0w49csm6n",
         "status": "confirmed",
         "blockheight": 1664145
      }
   ],
   "channels": []
}
```

### `getinfo` output
```
{
   "id": "026e7cb4237b4042db75a991af29c2d7704780c8e7fbebe5fdbad8f38e958dfba5",
   "alias": "clightningM",
   "color": "026e7c",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9737
      }
   ],
   "version": "v0.8.0-40-g899f5de",
   "blockheight": 1664145,
   "network": "testnet",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/sergei/.lightning/testnet"
}
```

**Comment by cdecker** [comment]
The problem is that we scan blocks when catching up with the blockchain, but don't monitor the mempool. This means that the first time we see an incoming tx is when it is being confirmed. Either we start polling the mempool, which can be expensive given the mempool size, or we ask to get notified about transactions, which is lossy, and requires us to also attach to the ZMQ interface. This in turn means we have a deeper integration with `bitcoind` making it harder for alternative backends. Currently we rely solely on the JSON-RPC exposed by `bitcoind` which can easily be swapped out.

**Comment by cdecker** [comment]
That being said we can consider incoming TX notifications when we move the bitcoin backend into a plugin, and then the plugin can implement this optional part of the interface :wink: 

See https://github.com/ElementsProject/lightning/issues/3354 for details about that effort.

**Comment by andrewtoth** [comment]
I created a [plugin](https://github.com/andrewtoth/listmempoolfunds) that contains a new RPC, `listmempoolfunds`, that will show unconfirmed transactions.
