### ISSUE TITLE
Open channel to disconnected peer: fundchannel hangs

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#3456]
### Issue and Steps to Reproduce

If I try to open a channel with `fundchannel` to a disconnected peer, the CLI just hangs. I'd expect it to display an error message along the lines of: "The peer is disconnected. You have to connect to the peer to open a channel.". I observe the same behavior for totally unknown peers and for known but disconnected peers.

### `getinfo` output
```
{
   "id": "02f67d5b7185ac67172807fc8f9d6b000305e93793332ed5a2087478a69909371e",
   "alias": "clightningB",
   "color": "02f67d",
   "num_peers": 3,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 2,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9740
      }
   ],
   "version": "v0.8.0-40-g899f5de",
   "blockheight": 1664151,
   "network": "testnet",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/sergei/.lightningB/testnet"
}
```

**Comment by cdecker** [comment]
Since https://github.com/ElementsProject/lightning/pull/3314 was merged we will attempt to connect to a peer when we get a `fundchannel` call and we aren't connected to the node yet. This was added as a usability feature since we got the feedback that this makes it easier.
