### ISSUE TITLE
potential typo in CI script

### ISSUE THREAD

**Issue by NickeZ** [ElementsProject/lightning#3466]
Unless I'm blind you are checking the same condition twice here: https://github.com/ElementsProject/lightning/blob/038ee288a62dc225c7ed60bb670af7e474946838/.travis/build.sh#L46

**Comment by cdecker** [comment]
Yep, we commented it back in the PR but never followed up: https://github.com/ElementsProject/lightning/pull/3197#discussion_r363268155
