### ISSUE TITLE
closing_tx fee calc

### ISSUE THREAD

**Issue by nayuta-ueno** [ElementsProject/lightning#348]
I establishchannel between our-node and c-lightnig with below parameter (regtest):

* open_channel.feerate_per_kw = 7500 (our-node ==> c-lightning)

Some `normal operation` are success.
* last total msat = 600000000
  * out-node msat = 290000000
  * c-lightning msat = 310000000
  * no HTLC remain

When closing, I get `closing_signed.fee_satoshis = 10897` from c-lightning.
BOLT#2 describes [`lower than or equal to the base fee of the final commitment transaction`](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements-6), so I think maximum `fee_satoshis` =`724 * 7500 / 1000 = 5430`.

**Comment by rustyrussell** [comment]
Great catch!
