### ISSUE TITLE
Does close all channel possible?

### ISSUE THREAD

**Issue by jeffsnguyen** [ElementsProject/lightning#3499]
### Issue and Steps to Reproduce
Is there a command that can close all channel?

###

**Comment by ZmnSCPxj** [comment]
Not yet.  You could implement such in a plugin, however; `listpeers` for all channels in a `CHANNELD_NORMAL` `CHANNELD_AWAITING_LOCKIN` `OPENINGD` and `close` them all, then loop again (in case some other automated system opens new channels).  Though if you are using any kind of autopilot plugin, you probably want to integrate this in the autopilot as well.

**Comment by m-schmoock** [comment]
@ZmnSCPxj @cdecker @niftynei 

I don't think the command to close all channels should not be left as an 'you need a special plugin for this command' thing. Closing all channels is a basic and security relevant operation when someone decides to finish up with his node. For example if you think your host may be compromised or you want to relocate, but without using the same private keys, ... 

If you agree we can open a 'good first issue', that will allow `all` as channel `id` in the close command that will basically do a loop. Remaining logic regarding the cooperative/force can stay the same, so after the first gentlemen's round there may be offline or uncooperative channels left.

**Comment by ZmnSCPxj** [comment]
@m-schmoock it might be useful to prevent `fundchannel` (via `fundchannel_start`) while this closing loop is on-going, to prevent automated systems like autopilots from opening channels as well.

How about a pair of new commands:

    decommission

* Closes all channels and prevents new channels from being funded (by us or by peers).
* Channels will be force-closed.

    recommission

* Cancels a previous `decommission` command and allows new channels to be funded.

**Comment by m-schmoock** [comment]
Sounds very useful, I would add

> Channels will be force-closed, if offline or uncooperative.

**Comment by m-schmoock** [comment]
@ZmnSCPxj  I described this in detail in https://github.com/ElementsProject/lightning/issues/3550  , this issue can be closed.

**Comment by ZmnSCPxj** [comment]
Subsumed by #3550
