### ISSUE TITLE
Upgraded my test node from v0.8.0 to v0.8.1 and the node stopped working

### ISSUE THREAD

**Issue by sumBTC** [ElementsProject/lightning#3543]
### Issue and Steps to Reproduce
Upgraded my test node from `v0.8.0-1-gb14b2b0` to `v0.8.1-13-g79ba486`

All I did was: `git pull` and `make`

Node worked perfectly on that previous version (v.0.8.0)

Output:

`2020-02-22T08:32:03.557Z INFO database: Updating database from version 128 to 129
2020-02-22T08:32:09.669Z UNUSUAL plugin-bcli: Could not connect to 'lightning-rpc': Connection refused
2020-02-22T08:32:09.669Z INFO plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
2020-02-22T08:32:20.946Z INFO lightningd: --------------------------------------------------
2020-02-22T08:32:20.946Z INFO lightningd: Server started with public key 02aecde3b3dde450889755d4dbce538e6b9e9dfa7702d14b5bc5c4379e1b330392, alias myshtery (color #23354d) and lightningd v0.8.1-13-g79ba486
2020-02-22T08:32:20.952Z INFO plugin-sendinvoiceless.py: Plugin sendinvoiceless.py initialized`

The node doesn't make connections and in general doesn't seem to be doing anything at all!

What's `UNUSUAL plugin-bcli: Could not connect to 'lightning-rpc': Connection refused`?

Removed gossip-store and after a restart gossip-store doesn't  build and remains like this on `ls -l`

`-rw------- 1 user user 1 feb 22 10:04 gossip_store`

Remember this test node worked perfectly before the upgrade. Glad I now always update my test node first.

### `getinfo` output
{
   "id": "02aecde3b3dde450889755d4dbce538e6b9e9dfa7702d14b5bc5c4379e1b330392",
   "alias": "myshtery",
   "color": "23354d",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 0,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "192.168.178.20",
         "port": 9835
      }
   ],
   "version": "v0.8.1-13-g79ba486",
   "blockheight": 618482,
   "network": "bitcoin",
   "msatoshi_fees_collected": 152746383,
   "fees_collected_msat": "152746383msat",
   "lightning-dir": "/home/user/.lightning_test/bitcoin"
}

**Comment by darosior** [comment]
> What's `UNUSUAL plugin-bcli: Could not connect to 'lightning-rpc': Connection refused?`

It's the expected behavior: a new plugin (`bcli`) introduced in the last release needs to be initialized before we even start listening on the RPC socket, hence it fails the `connect()`.

> The node doesn't make connections and in general doesn't seem to be doing anything at all!

Weird, could you provide more logs ? All the logs you provided above are normal operations.

**Comment by sumBTC** [comment]
@darosior I don't think there are more logs. I always redirect the output of `lightningd` to a file and that's all there was in it. There isn't a crash file so I wouldn't know where more log info can be found. I can try to restart with `--log-level=DEBUG` but that will take a few days as my system got a unilateral close when I tried to return to the old version. Will try later. Good idea?

**Comment by sumBTC** [comment]
I'm trying to reproduce the problems I had before with the debugging mode on but everything seems to be working fine this time. Very strange. The gossip_store is rebuilding fine, although it takes a bit longer to start building but that's ok. For now I'll close this issue.

**Comment by sumBTC** [comment]
It seems c-lighting takes a bit longer before starting to build the gossip_store but apart from that everything works fine now. Still the UNUSUAL message for expected behavior should be corrected because it's confusing.
