### ISSUE TITLE
Can't call an RPC method from inside an `rpc_command` hook

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#3578]
### Issue and Steps to Reproduce

I've been testing a plugin that replaces `getroute` using the `rpc_command` command hook. The plugin reads information from `listchannels` RPC plus opens a database stored in a file inside `lightning-dir`.

I tried it a few times and it was working, but now all of a sudden it started crashing when I try to `pay`. The crash looks like this:

```
lightningd: FATAL SIGNAL 11 (version v0.8.0-316-gac5cba2)
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: /home/fiatjaf/lightning/lightningd/lightningd: Too many open files
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
/home/fiatjaf/lightning/lightningd/lightningd: libbacktrace: failed to read executable information
2020-03-07T02:19:44.719Z **BROKEN** lightningd: FATAL SIGNAL 11 (version v0.8.0-316-gac5cba2)
```

What could that mean?
I'm not 100% sure this is being caused by my plugin, but that's the only thing I could think of.

### `getinfo` output

```
{
   "id": "02bed1812d3824f7cc4ccd38da5d66a29fcfec146fe95e26cd2e0d3f930d653a8d",
   "alias": "etleneum.com",
   "color": "c2f1bb",
   "num_peers": 11,
   "num_pending_channels": 0,
   "num_active_channels": 10,
   "num_inactive_channels": 1,
   "address": [
      {
         "type": "ipv6",
         "address": "2a01:4f8:c0c:7671::1",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      }
   ],
   "version": "v0.8.0-316-gac5cba2",
   "blockheight": 620551,
   "network": "bitcoin",
   "msatoshi_fees_collected": 3168283,
   "fees_collected_msat": "3168283msat",
   "lightning-dir": "/home/fiatjaf/.lightning/bitcoin",
   "warning_bitcoind_sync": "Bitcoind is not up-to-date with network."
}
```

**Comment by cdecker** [comment]
Processes on linux usually get up to 1024 file descriptors they can have open at any time (this can be adjusted via `ulimit`). Running out of file descriptors usually means that you have too many connections / files / pipes / socketpairs open. This one is a strange one since it is `lightningd` that's running out of fds. This usually means that we're leaking file descriptors somewhere, maybe your plugin is opening a lot of RPC connections to `lightningd` and not closing them?

You can get an overview of what type these fds are by looking up where the symbolic links in `/proc/{lightningd-pid}/fd/*` are pointing to.

**Comment by fiatjaf** [comment]
I don't think I am opening a lot of RPC connections. It should be just intercepting `pay`, then computing stuff internally and finally calling `sendpay`.

I'll assume it's a bug on my code, however. In the future when I try this again if the error keeps happening I'll come here and reopen this.

**Comment by fiatjaf** [comment]
I'm writing another plugin that uses `rpc_command` and ran into the same problem.

The problem is that the plugin using `rpc_command` cannot call other RPC commands before returning a response to the `rpc_command` hook.

This is a bug, right?

**Comment by fiatjaf** [comment]
Added a failing test, because I have no idea of how to fix this or if it's even possible. Hopefully it is.

**Comment by fiatjaf** [comment]
This was never an intended feature.
