### ISSUE TITLE
Could not afford feerate 0 (vs max 0)

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#3606]
### Issue and Steps to Reproduce
Suddenly my node started issuing this:

```
0ef2f8228eaff-channeld-chan#10879: STATUS_FAIL_INTERNAL_ERROR: Could not afford feerate 0
 (vs max 0)
2020-03-25T23:54:26.014Z INFO 02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8
228eaff-chan#10879: Peer transient failure in CHANNELD_AWAITING_LOCKIN: channeld: Owning
subdaemon channeld died (9)
lightning_channeld: Could not afford feerate 0 (vs max 0) (version v0.8.0-316-gac5cba2)
0x55792b58fa13 send_backtrace
        common/daemon.c:39
0x55792b59cbac status_failed
        common/status.c:206
0x55792b57d197 send_commit
        channeld/channeld.c:971
0x55792b59d256 timer_expired
        common/timeout.c:39
0x55792b582abc main
        channeld/channeld.c:3008
0x7fbee77e51e2 ???
        ???:0
0x55792b57a899 ???
        ???:0
0xffffffffffffffff ???
        ???:0
```

It goes on and on, the error keeps happening many times per second, forever. I did nothing, just went to see the logs and it was like that.

The only thing I did some time before seeing this error was opening a channel (using `push_msat`) with my other node. The transaction for that channel, however, after many hours isn't mined yet. From manually inspecting the database I gathered the info that channel `10879` is indeed that channel.

### `getinfo` output
(I won't give my `getinfo` output because I can't get my node online, the constant stream of errors bugs me too much, but it should suffice to say I was using some `master` from perhaps a month ago, then upgraded it just now to 8c984fbf1df58a543e332be78d556319ea581ee2, but the error continued. -- **EDIT**: oops, I updated my codebase, but forgot to recompile and kept running the old version.)

**Comment by fiatjaf** [comment]
Now the transaction was mined. I turned lightningd on again to see if something had changed, but still the error keeps coming in the same way.

`listfunds` shows the following for that channel:

```
      {
         "peer_id": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
         "connected": true,
         "state": "CHANNELD_AWAITING_LOCKIN",
         "channel_sat": 5000,
         "our_amount_msat": "5000000msat",
         "channel_total_sat": 2175314,
         "amount_msat": "2175314000msat",
         "funding_txid": "9276c29415976412281ec1f7bf855c828fef730fe602e36b64638c39969d65f8",
         "funding_output": 0
      }
```

**Comment by fiatjaf** [comment]
New update: I've commented out this and was able to get the node running: https://github.com/ElementsProject/lightning/blob/8c984fbf1df58a543e332be78d556319ea581ee2/channeld/channeld.c#L957-L980

**Comment by fiatjaf** [comment]
Even though my trick made the channel look ok, in the end I couldn't use it because the sending node refused to add an HTLC because the other side wouldn't have the necessary funds to pay the fees for it (if I understand it well).

I tried commenting out the lines that did that check in the sending node, then the payment was sent. The receiving node, however (the same who was showing the errors above) didn't like that and returned `2020-03-26T12:25:20.672Z UNUSUAL 02bed1812d3824f7cc4ccd38da5d66a29fcfec146fe95e26cd2e0d3f930d653a8d-chan#4901: Peer permanent failure in CHANNELD_NORMAL: channeld: sent ERROR update_fee 300 unaffordable`, which caused the sending node to force-close the channel.

This was very sad.

**Comment by darosior** [comment]
Could you share the output of `lightning-cli getfeerate` and `bitcoin-cli estimatesmartfee 2 CONSERVATIVE` ?

The only way I see for `bcli` to give a `0` feerate would be to incorrectly parse the `estimatesmartfee` output..

**Comment by fiatjaf** [comment]
I see none of such things in the logs. Are you sure this is related to `getfeerate`? Shouldn't it be normalized after restarting the node? And then commenting out this https://github.com/ElementsProject/lightning/issues/3606#issuecomment-604372279 would have the effect described?

**Comment by darosior** [comment]
> I see none of such things in the logs.

Arf.. That's debug-level log, you must have run with info level.

> Are you sure this is related to getfeerate? 

No, especially because of the feerate floor. But that's the first gross guess as.... it's the source of the feerate!

> Shouldn't it be normalized after restarting the node?

Depends on your bitcoind, hence why I asked if your bitcoind fee estimation worked properly.

> And then commenting out this #3606 (comment) would have the effect described?

Commenting this was *obviously* a bad idea and would have led to an unilateral close sooner or later, no matter what we are discussing.
