### ISSUE TITLE
Unable to fund channel - "message": "unknown parameter: satoshi"

### ISSUE THREAD

**Issue by CMDRZOD** [ElementsProject/lightning#3624]
### Issue and Steps to Reproduce

For some reason I'm unable to fund a channel using the regular method. I keep getting this message:

{
   "code": -32602,
   "message": "unknown parameter: satoshi"
}

I'm using the proper command : lightning-cli fundchannel (channel) (satoshis)
eg: 
lightning-cli fundchannel 0219426a5b641ed05ee639bfda80c1e0199182944977686d1dd1ea2dcb89e5dd55 923                                     {                                                                                                                                                                      "code": -32602,                                                                                                                                                     "message": "unknown parameter: satoshi"                                                                                                                          }                                
I've tried ending the satoshi number with btc and sat and still the error persists.
I'm using the latest git clone from this weekend.

I imported my lightning files from another lightning instance recently in an attempt to setup tor reachability. I can connect to tor nodes without issue but the fund channel keeps failing for me.
### `getinfo` output
{
   "id": "02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a",
   "alias": clightning",
   "color": "046321",
   "num_peers": 9,
   "num_pending_channels": 0,
   "num_active_channels": 8,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv2",
         "address": "v2kdcetvslmdfcwr.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      }
   ],
   "version": "v0.8.1-175-g891adfc",
   "blockheight": 624596,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/home/.lightning/bitcoin"                                                                                                                 }

**Comment by darosior** [comment]
It's fixed by https://github.com/ElementsProject/lightning/pull/3615, you can use the last release until it's reviewed.

**Comment by darosior** [comment]
Arf, I forgot to add the fixes keyword in the PR. Now it's merged I think you can close this (after having successfully tested :) )

**Comment by CMDRZOD** [comment]
Just re cloned and built the software. Works as expected now. Thank you.
