### ISSUE TITLE
`pay` should refuse to pay payment requests that have expired

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#363]
We currently don't reject expired payment requests.

**Comment by shesek** [comment]
Is that only enforced on the side making the payment, or on the receiver's side as well?

**Comment by cdecker** [comment]
It currently is, giving some slack to allow the recipient to accept it past its expiry seems like a good idea.

**Comment by shesek** [comment]
What if the receiver does want to enforce this?

**Comment by rustyrussell** [comment]
Nadav Ivgi <notifications@github.com> writes:
> What if the receiver does want to enforce this?

This has been resolved; it's now enforced on both sides.

It wasn't clear when writing this (pre-bolt11) whether the expiry should
be handled by some external process sweeping for unpaid invoices, or
internally.  With BOLT11 having an explicit expity, it became clearer
IMHO.

Cheers!
Rusty.
