### ISSUE TITLE
Result for missing required arguments in plugins

### ISSUE THREAD

**Issue by sr-gi** [ElementsProject/lightning#3638]
### Issue and Steps to Reproduce

The output when a Python plugin misses a required argument does not follow the same UI as with built-in RPC method. For example:

```
l1-cli plugin-method
"Error while processing plugin-method: TypeError(\"missing a required argument: 'arg'\")"
```

While you would expect something similar to:

```
{
   "code": -32602,
   "message": "missing a required argument: arg"
}
```

From https://github.com/ElementsProject/lightning/blob/b51772ff68c237627f526be579f0b99c90082183/contrib/pyln-client/pyln/client/plugin.py#L83-L89

The `error` field is set as a string, with the `exc` set using `repr`. Setting the error as a `dict` and using `str` instead of `repr` would generate an output closer to the built-ins:

```
self.exc = exc
self._write_result({
    'jsonrpc': '2.0',
    'id': self.id,
    "error": {"error": "Error while processing {method}: {exc}".format(
        method=self.method, exc=str(exc)
    ),
}})
```

Output:

```
{
   "error": "Error while processing plugin-method: missing a required argument: 'arg'"
}
```
### `getinfo` output

```
{
   "id": "02a59ee414c69266f9779925af18299fb05c0915a2a5ef22c449ac4f9a96498245",
   "alias": "HOPPINGNET",
   "color": "02a59e",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 1,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 6060
      }
   ],
   "version": "v0.8.0rc2-447-gc99a0e8-modded",
   "blockheight": 557,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/tmp/l1-regtest/regtest"
}
```

**Comment by sr-gi** [comment]
It may be also worth mentioning that calling a rpc method from a Python plugin with a missing argument will leave a full traceback of the exception in the logs.

https://github.com/ElementsProject/lightning/blob/b51772ff68c237627f526be579f0b99c90082183/contrib/pyln-client/pyln/client/plugin.py#L445

**Comment by darosior** [comment]
Thanks for the very detailed report !

> It may be also worth mentioning that calling a rpc method from a Python plugin with a missing argument will leave a full traceback of the exception in the logs.

Yeah, I personally like that for debugging (I think it was intended, too).
