### ISSUE TITLE
0msat invoice creation

### ISSUE THREAD

**Issue by darosior** [ElementsProject/lightning#3641]
@fiatjaf reported this on IRC.

> 00:38 <fiatjaf> we can generate invoices with zero amounts now
00:39 <fiatjaf> is this ok?

**Comment by fiatjaf** [comment]
```
~> ~/lightning/cli/lightning-cli invoice 0 xxx 'this is a zero-amount invoice.'
{
   "payment_hash": "b42eede7824bf6e409da904f090cb92178e18a61374d17d4468e17a4b7ef4ef0",
   "expires_at": 1587131659,
   "bolt11": "lnbc01p0fq75tpp5kshwmeuzf0mwgzw6jp8sjr9ey9uwrznpxax304zx3ct6fdl0fmcqdpsw35xjueqd9ejqcfq0fjhymedv9kk7atwwssxjmnkda5kxefwxqyjw5qcqzyssp57hmpptj5wrky7dfnqtr9v6t9law3yu6rauuun0wrzrvm499a5heqrzjqt0pr36g7ke9elfvaqq3wmfey6laun0z8v0lg0nf9fdhdncxsp0y5zxkp5qqnsgqqqqqqqqqqqqqpjqqrc9qy9qsqflkek9mml8s2yv5h6wcnalex5ywfrradpxqsxh7fqjl54h0v07krsds52qpzj385zylffp02epj7k6sp65kjlgtl7p0ltt77txugpzqp64vyly"
}

~> ~/lightning/cli/lightning-cli decodepay lnbc01p0fq75tpp5kshwmeuzf0mwgzw6jp8sjr9ey9uwrznpxax304zx3ct6fdl0fmcqdpsw35xjueqd9ejqcfq0fjhymedv9kk7atwwssxjmnkda5kxefwxqyjw5qcqzyssp57hmpptj5wrky7dfnqtr9v6t9law3yu6rauuun0wrzrvm499a5heqrzjqt0pr36g7ke9elfvaqq3wmfey6laun0z8v0lg0nf9fdhdncxsp0y5zxkp5qqnsgqqqqqqqqqqqqqpjqqrc9qy9qsqflkek9mml8s2yv5h6wcnalex5ywfrradpxqsxh7fqjl54h0v07krsds52qpzj385zylffp02epj7k6sp65kjlgtl7p0ltt77txugpzqp64vyly
{
   "currency": "bc",
   "created_at": 1586526859,
   "expiry": 604800,
   "payee": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
   "msatoshi": 0,
   "amount_msat": "0msat",
   "description": "this is a zero-amount invoice.",
   "min_final_cltv_expiry": 144,
   "payment_secret": "f5f610ae5470ec4f353302c6566965ff5d127343ef39c9bdc310d9ba94bda5f2",
   "features": "028200",
   "routes": [
      [
         {
            "pubkey": "02de11c748f5b25cfd2ce801176d3926bfde4de23b1ff43e692a5b76cf06805e4a",
            "short_channel_id": "579085x2497x0",
            "fee_base_msat": 0,
            "fee_proportional_millionths": 200,
            "cltv_expiry_delta": 30
         }
      ]
   ],
   "payment_hash": "b42eede7824bf6e409da904f090cb92178e18a61374d17d4468e17a4b7ef4ef0",
   "signature": "304402204fed9b177bf9e0a23297d3b13eff26a11c918fad0981035fc904bf4addec7fac022038361450022944f4113e9485eac865eb6a01d52d2fa17ff05ff5afde59b88088"
}
```

**Comment by rustyrussell** [comment]
Just checked, we've *always* been able to make these (at least since 0.7.0, the oldest I checked).

Not sure if that's a feature, but seems like we shouldn't stop it now without good reason?

**Comment by cdecker** [comment]
This is a duplicate of #3141

**Comment by darosior** [comment]
> Not sure if that's a feature, but seems like we shouldn't stop it now without good reason?

Yep I was confused because I vaguely remembered someone talking about this and that we shouldn't do that. It's actually @Sword-smith in the issue cdecker linked above.

**Comment by Sword-Smith** [comment]
As I mentioned in #3141, this seems to violate [bolt11](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md) which specifies:

> 
> A writer:
> MUST encode amount as a positive decimal integer with no leading 0s.

**Comment by fiatjaf** [comment]
I think this is actually a place where BOLT11 should be changed. 0msat invoices can actually be useful.

**Comment by Sword-Smith** [comment]
> 
> 
> I think this is actually a place where BOLT11 should be changed. 0msat invoices can actually be useful.

Use cases that are not covered by the `any` option?
From Bolt11:
> amount: *optional* number in that currency, followed by an optional multiplier letter. The unit encoded here is the 'social' convention of a payment unit -- in the case of Bitcoin the unit is 'bitcoin' NOT satoshis.
(own emphasis)

So with the `any` amount, you can send an invoice that the recipient can pay any amount to.

**Comment by fiatjaf** [comment]
I was thinking of cases in which you want to pay exactly zero, but leave some fees in the path along the way.

Specifically I have a setup in which invoices may be very small but they will have a fake route hint that adds a ton of fees to be paid to the last route before the fake route and these fees are the actual payment.

But yeah, this is all crazy.

**Comment by Sword-Smith** [comment]
I don't fully understand why you would do this but my lack of understanding certainly is not enough to qualify it as crazy.

**Comment by darosior** [comment]
AFAICT this is not possible anymore:
```
$ lcreg1 invoice 0 xxx 'this is a zero-amount invoice.'
{
   "code": -32602,
   "message": "msatoshi: should be positive msat or 'any': invalid token '0'"
}
```
