### ISSUE TITLE
Onion V3 addresses only work on recent tor versions.

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3642]
Ubuntu 18.04 ships tor 0.2.9 by default, which doesn't recognise onion v3 addresses, which leads to some trouble with nodes that only advertise onion v3 addresses. There's quite a lot of them.

I think that:
 - the documentation on TOR should be updated, regarding the version.
 - lightningd should recognise nodes that only advertise .onion addresses and should warn the user that the connection error was caused by a lack of tor proxy.
 - lightningd should check the TOR version and warn if it's too old.

This is how it looks when the tor version is too old:

```
$ lightning-cli connect 02d4b432058ec31e38f6f35d22a487b7db04c4bf70f201f601b66f7b4358242b03@2b3d5dc7ejbnaqmrsdx3stopvswyhx7l2rtrddgqwgwhjn436k5hx7qd.onion:9735
{
   "code": 401,
   "message": "2b3d5dc7ejbnaqmrsdx3stopvswyhx7l2rtrddgqwgwhjn436k5hx7qd.onion:9735: Connection establishment: Operation now in progress. 2b3d5dc7ejbnaqmrsdx3stopvswyhx7l2rtrddgqwgwhjn436k5hx7qd.onion:9735: Connection establishment: Operation now in progress. "
}

$ torify nc anhvjzifi7oshenj5mqxmscsv3epux6kcesm2q2we6qhig2pcz2cuead.onion 9735
[Apr 12 14:55:58] ERROR torsocks[6198]: General SOCKS server failure (in socks5_recv_connect_reply() at socks5.c:516)
```

**Comment by Saibato** [comment]
hi, thx. please see progress on that in  #3643
