### ISSUE TITLE
Getroute returns impossible route

### ISSUE THREAD

**Issue by sumBTC** [ElementsProject/lightning#3654]
### Issue and Steps to Reproduce

Someone opened a channel with my node (BitcoinDayTrader.nl) and paid 2505 satoshi.

Channel balance in msatoshi is like this:
`alias_unknown 193,414,000 <-> 2,505,000 BitcoinDayTrader.nl`

If `nodeid` is the node id of `alias_unknown` (I know what the node id is but don't want to show it), then

`lightning-cli getroute nodeid 10000000 10`

gives:

`
{
   "route": [
      {
         "id": "nodeid",
         "channel": "blablaxblabla",
         "direction": 0,
         "msatoshi": 10000000,
         "amount_msat": "10000000msat",
         "delay": 9,
         "style": "legacy"
      }
   ]
}
`

How is it possible `getroute` give the single path route back, if there's not enough liquidity in the channel (10000 sat >> 2505 sat)? I expected `"Could not find a route"`. FYI I have the impression this node only has a single channel (to me), so there's no alternative route.

By the way: I managed to pay 500 satoshi via `sendinvoiceless` so things are working:

`lightning-cli sendinvoiceless nodeid 500000`

gives:

`"500000 msat delivered with 1001 msat fee over 2 hops"`

**EDIT:** This edit was wrong (removed), for `LightningTo.Me` it works perfectly. I get a different route if amount is too big for the direct channel. Maybe if there isn't an alternative route, the direct route is returned even if the amount is too larger for that channel.

`LightningTo.Me 1,950,438,781 <-> 49,561,219 BitcoinDayTrader.nl`

### `getinfo` output

` "version": "v0.8.1-175-g891adfc"`

**Comment by sumBTC** [comment]
I now understand `getroute` only sees total balance. Closing this issue.

**Comment by cdecker** [comment]
Indeed the `pay` plugin will ask for `listpeers` to exclude local channels eagerly if they have insufficient capacities. However this is little more than an optimization, since any route longer than 1 hop will require trial-and-error anyway :wink:

**Comment by sumBTC** [comment]
Thanks for your reply. I've made a quick and dirty (doesn't even use jq) bash shell hack around `getroute` that includes the information of my local channels to reduce the risk of not being able to pay if a player on my website wins. Well I hardly dare to show it but you can find it [here](https://BitcoinDayTrader.nl/getroute_mine.sh) and it seems to work well haha
