### ISSUE TITLE
Unilateral close test

### ISSUE THREAD

**Issue by nayuta-ueno** [ElementsProject/lightning#366]
I'd like to do a test `unilateral close` between `c-lightning` and our-node.
What command am I use at `lightning-cli` ?
(our-node don't send `update_fulfill_htlc` for `unilateral close` test.)

**Comment by rustyrussell** [comment]
Hi!  If you compile with DEVELOPER=1, you get access to the "dev-fail" command; this probably does what you want.  c-lightning will treat it as a permanent error and close the channel unilaterally.

**Comment by nayuta-ueno** [comment]
Thank you!

**Comment by nayuta-ueno** [comment]
Can `c-lightning` stop sending `update_fulfill_htlc` for test ?

**Comment by rustyrussell** [comment]
ueno <notifications@github.com> writes:
> Can `c-lightning` stop sending `update_fulfill_htlc` for test ?

Yes, you can use --dev-disconnect=.  This takes a file which says when
to disconnect based on sending packets, containing lines like:

@UPDATE_FULFILL_HTLC

The main letters are '-' to disconnect *before* sending the packet, +
to disconnect *after*.  If the next line in the file is "permfail" then
c-lightning will actually exit, too.

(You can do -UPDATE_FULFILL_HTLC*2 to drop the *second*
UPDATE_FULFILL_HTLC too).

**Comment by nayuta-ueno** [comment]
Thank you !
