### ISSUE TITLE
`pay` tries to pay an invoice with a wrong amount

### ISSUE THREAD

**Issue by kirelagin** [ElementsProject/lightning#3684]
Let me say right away that this is happening with v0.8.1. I haven’t tried with v0.8.2 yet, but I went through the git log, and couldn’t find anything that looked like it could have fixed this.

The problem is that when I try to pay an invoice, even though it is being parsed correctly, the node tries to send a transaction with an incorrect amount. Here is an example with a 20 msat invoice:

```text
$ lightning-cli pay 'lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6'
{
   "code": 203,
   "message": "failed: WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS (reply from remote)",
   "data": {
      "id": 48,
      "payment_hash": "43214c068e7271261626103bdd07d967e484395d9348bd0fe53a8cd9dbad9171",
      "destination": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
      "msatoshi": 1020,
      "amount_msat": "1020msat",
      "msatoshi_sent": 1020,
      "amount_sent_msat": "1020msat",
      "created_at": 1588291657,
      "status": "pending",
      "bolt11": "lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6",
      "erring_index": 1,
      "failcode": 16399,
      "failcodename": "WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS",
      "erring_node": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
      "erring_channel": "1697440x101x0",
      "erring_direction": 1,
      "raw_message": "400f00000000000003fc001a4871"
   }
}

$ lightning-cli decodepay 'lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6'
{
   "currency": "tb",
   "created_at": 1588291268,
   "expiry": 604800,
   "payee": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
   "msatoshi": 20,
   "amount_msat": "20msat",
   "description": "lightning-control transaction",
   "min_final_cltv_expiry": 10,
   "payment_secret": "9e0104bf32883a69c43b5b945cce0383874da5f882676d771e4f70adb65650a4",
   "features": "028200",
   "routes": [
      [
         {
            "pubkey": "02312627fdf07fbdd7e5ddb136611bdde9b00d26821d14d94891395452f67af248",
            "short_channel_id": "1693504x38x0",
            "fee_base_msat": 1000,
            "fee_proportional_millionths": 1,
            "cltv_expiry_delta": 40
         }
      ]
   ],
   "payment_hash": "43214c068e7271261626103bdd07d967e484395d9348bd0fe53a8cd9dbad9171",
   "signature": "3044022032324ac3bbb6de903e2634b72a5091083f1cb0c05185d32dbba30fa6aaf4741e022048fd18ddf5c091dd1306e8a1066689723607ab0af9995dfe87a726de4bd43d7f"
}

$ lightning-cli pay 'lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6'
{
   "code": 203,
   "message": "failed: WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS (reply from remote)",
   "data": {
      "id": 48,
      "payment_hash": "43214c068e7271261626103bdd07d967e484395d9348bd0fe53a8cd9dbad9171",
      "destination": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
      "msatoshi": 4021,
      "amount_msat": "4021msat",
      "msatoshi_sent": 4021,
      "amount_sent_msat": "4021msat",
      "created_at": 1588291712,
      "status": "pending",
      "bolt11": "lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6",
      "erring_index": 1,
      "failcode": 16399,
      "failcodename": "WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS",
      "erring_node": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
      "erring_channel": "1697440x101x0",
      "erring_direction": 1,
      "raw_message": "400f0000000000000fb5001a4871"
   }
}

$ lightning-cli pay 'lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6'
{
   "code": 203,
   "message": "failed: WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS (reply from remote)",
   "data": {
      "id": 48,
      "payment_hash": "43214c068e7271261626103bdd07d967e484395d9348bd0fe53a8cd9dbad9171",
      "destination": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
      "msatoshi": 2020,
      "amount_msat": "2020msat",
      "msatoshi_sent": 2020,
      "amount_sent_msat": "2020msat",
      "created_at": 1588291735,
      "status": "pending",
      "bolt11": "lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6",
      "erring_index": 1,
      "failcode": 16399,
      "failcodename": "WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS",
      "erring_node": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
      "erring_channel": "1697440x101x0",
      "erring_direction": 1,
      "raw_message": "400f00000000000007e4001a4871"
   }
}

$ lightning-cli pay 'lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6'
{
   "id": 48,
   "payment_hash": "43214c068e7271261626103bdd07d967e484395d9348bd0fe53a8cd9dbad9171",
   "destination": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
   "msatoshi": 20,
   "amount_msat": "20msat",
   "msatoshi_sent": 20,
   "amount_sent_msat": "20msat",
   "created_at": 1588292145,
   "status": "complete",
   "payment_preimage": "2abd39781b5e89d6b01f7281a6d0cc1a812fadae66fca19064e1157dc25bf205",
   "bolt11": "lntb200p1p02kekypp5gvs5cp5wwfcjv93xzqaa6p7evljggw2ajdyt6rl982xdnkadj9csdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp5ncqsf0ej3qaxn3pmtw29ensrswr5mf0csfnk6ac7fac2mdjk2zjqrzjqgcjvfla7plmm4l9mkcnvcgmmh5mqrfxsgw3fk2gjyu4g5hk0teysxwhgqqqqfsqqqqqqqlgqqqqqqgq9q9qy9qsqxgey4samkm0fq03xxjmj55y3pql3evxq2xzaxtdm5v86d2h5ws0y3lgcmh6upywazvrw3ggxv6yhyds84v90nx2al6r6wfk7f02r6lcqqjyst6"
}
```

No matter how many times I `decodepay` it, it is always correct, but the payments fail very often. It doesn’t seem to depend on time (i.e. how long I wait after issuing the invoice); the number of retries needed to pay it is always different (sometimes it works on the first try, sometimes I can retry 10 times in a row to no effect); I’m not sure about the amount, I am mostly trying with 20, but I have seen this with other amounts as well. The incorrect amounts I am seeing (with 20) are usually 1020, 1021, 2020, 2021, 3020, 3021, 4020, 4021.

There is nothing interesting in the debug log, it just prints something like:

```
lightningd: Sending 2021msat over 1 hops to deliver 2021msat
```

right away, so the amount seems to be wrong very early on.

The weirdest thing about it is that it fails more often than it goes through, so I’m not sure how this issue could go unnoticed, which makes me think that there might be something special about my setup (testnet, two nodes connected through a private channel, can’t think of anything else unusual).

```text
$ lightning-cli getinfo
{
   "id": "03d44f0feafb17d8ad785ea7e9a96b591bcf8a727c735d51ee16d564f779dbc7b5",
   "alias": "LOUDCALENDAR",
   "color": "03d44f",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "<snip>",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.8.1",
   "blockheight": 1722483,
   "network": "testnet",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/var/lib/clightning/testnet"
}
```

**Comment by SimonVrouwe** [comment]
The `msatoshi_sent` also includes the fees, each hop in the route charges:
`base_fee_millisatoshi` + `fee_per_millionth` * invoice_amount

The command `listchannel [short_channel_id]`shows these fees for both directions of a channel with short_channel_id.

Failing payments are very common because of bad connectivity, insufficient capacity or just failing nodes in between the route. But in your case the erring node is the recipient returning `WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS`. Maybe you can figure out the owner and check which node implementation he/she runs?

**Comment by cdecker** [comment]
Indeed we disable the fee limit of 0.5% of the transferred amount for very small payments (since these are mostly used as signal not actual payments).

Since most nodes use the default of 1sat for `base_fee` that'd explain why you are seeing 1000, 2000 or 3000 msats being added to your payment for 1, 2 and 3 hops respectively (proportional fee is too small to represent and gets dropped).

**Comment by kirelagin** [comment]
> But in your case the erring node is the recipient returning `WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS`. Maybe you can figure out the owner and check which node implementation he/she runs?

These are both my nodes, they are both running the same version of c-lightning. Furthermore, the node I am sending from is not connected to any other node than the one I am sending the payment to (as you can see, there is only one channel and (as you can’t see) it is to that target node).

To me the error indicates, that 2021 _is_ the actual sum that the target node would receive and thus it refuses the transaction, since the amount does not match the one in the invoice. Also, doesn’t the line:

```
lightningd: Sending 2021msat over 1 hops to deliver 2021msat
```

indicate that 2021 is the actual amount that will be delivered sans any possible fees?

**Comment by kirelagin** [comment]
In the meantime, I sprinkled more log statements and it is clear now that the amount gets corrupted after [this call to `route_msatoshi`](https://github.com/ElementsProject/lightning/blob/5e2053feea958ac773b5c8d51c0972802484ef3e/plugins/pay.c#L1072), i.e. before the call `pc->msat` is 20, after the call it becomes 1020 or something else.

**Comment by kirelagin** [comment]
Ok, I think now I get it. That happens because shadow routing kicks in. Most of the time `add_shadow_route` is called with `fee_base = 1000; fee_prop = 1`, so each call to it adds a 1000 to the amount, but at least once I saw it called with `fee_base = 489; fee_prop = 1000`, so that would explain other weird amounts.

In my specific case, I will just work it around by disabling shadow routing, because I don’t care about it. But, in general, I am not sure I understand how it is supposed to work, given that it results in failing payments.

**Comment by kirelagin** [comment]
Well, huh! It looks like I can’t disable shadow routing!

```text
$ lightning-cli pay $inv null null null 0.0 null null 0
{
   "code": 203,
   "message": "failed: WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS (reply from remote)",
   "data": {
      "id": 99,
      "payment_hash": "10d8212292b9303311f2adcba38e5feb0d5002f0ba0b10bbffa19cf5bedfb88e",
      "destination": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
      "msatoshi": 1020,
      "amount_msat": "1020msat",
      "msatoshi_sent": 1020,
      "amount_sent_msat": "1020msat",
      "created_at": 1588355191,
      "status": "pending",
      "bolt11": "lntb200p1p02ccrxpp5zrvzzg5jhycrxy0j4h968rjlavx4qqhshg93pwll5xw0t0klhz8qdp0d35kw6r5de5kueedvdhkuarjdakzqarjv9h8xctrw35k7msxqyjw5qcqp2sp53gj984wmfgk6fqc327e05gn8j7qkctpve48klks3nk3qumxvsxdqrzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cngxwhfvqqqrqqqqqqqqlgqqqqqeqqjq9qy9qsqs4nwyynmm77hgnznch09spx22hwj98lng7mv7vnekmymvl0e5k6nau5a6n68m7ael82zdcde802kwcgmhlsnekpqt9n07zazawdzl4cq2049nt",
      "erring_index": 1,
      "failcode": 16399,
      "failcodename": "WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS",
      "erring_node": "021c38ebb30aa17901aec609e98da063b4e433bfbe45656bddb34ea688192bd734",
      "erring_channel": "1697440x101x0",
      "erring_direction": 1,
      "raw_message": "400f00000000000003fc001a48c5"
   }
}
```

I might be misreading the documentation, but form what I read it seems that setting `exemptfee` to 0 should make sure the `maxfeepercent` is taken into account for my payment and setting `maxfeepercent` should, in turn, disallow shadow routing, because:

> Route randomization will never exceed `maxfeepercent` of the payment.

Am I missing something?

**Comment by kirelagin** [comment]
By the way, when trying this with larger amounts, the amount sent is different from the one requested in the invoice too, but the receiving node accepts the transaction – I suppose there is just some epsilon that it allows for.

**Comment by kirelagin** [comment]
So, just to sum up, since there are a lot of comments here now.

* Shadow routing breaks small payments as it adds “fake fees” that are way larger than the amounts paid, and the receiving node rejects these transactions.
* Shadow routing kicks in in the case where it clearly makes zero sense: when the sender and the receiver have a direct channel with zero fees.
* I don’t even understand how it is supposed to work, to be honest. I.e. where are those extra shadow msats supposed to go? Currently it looks like they just end up being sent to the receiver, so the end result is that the receiver receives more than they expected and... how does this help anyone? I guess the intention was not to increment the actual `amount_msat` but rather `msatoshi_sent`? I mean, it is possible that I am just missing something, so, I guess, documentation of this part could be better.
* (This one is subjective, but) this whole shadow routing story is very confusing, shouldn’t it be opt-in?
* There doesn’t seem to be any easy way to opt-out (_I think_, doing `getroute` and `sendpay` manually should work though) and the opt-out strategy that follow from the docs doesn’t work.

**Comment by darosior** [comment]
Good point for the documentation, I'm going to propose a patch to take maxfees into account when choosing the shadow route.

> I don’t even understand how it is supposed to work, to be honest.

Then "makes zero sense" may not be the perfect take ? :-)

> where are those extra shadow msats supposed to go?

To the payee

> how does this help anyone?

Along with increasing CLTV deltas, this fakes the usage of more routes than are effectively used and allows to *possibly* break some heuristic used to guess the position of a node in a route. Quoting the RFC:
> If a route is computed by simply routing to the intended recipient and summing the cltv_expiry_deltas, then it's possible for intermediate nodes to guess their position in the route. Knowing the CLTV of the HTLC, the surrounding network topology, and the cltv_expiry_deltas gives an attacker a way to guess the intended recipient. Therefore, it's highly desirable to add a random offset to the CLTV that the intended recipient will receive, which bumps all CLTVs along the route.

> In order to create a plausible offset, the origin node MAY start a limited random walk on the graph, starting from the intended recipient and summing the cltv_expiry_deltas, and use the resulting sum as the offset. This effectively creates a shadow route extension to the actual route and provides better protection against this attack vector than simply picking a random offset would.


> (This one is subjective, but) this whole shadow routing story is very confusing, shouldn’t it be opt-in?
> There doesn’t seem to be any easy way to opt-out (I think, doing getroute and sendpay manually should work though) and the opt-out strategy that follow from the docs doesn’t work.

We [decided not to](https://github.com/ElementsProject/lightning/pull/3212), to avoid a footgun for users.

**Comment by kirelagin** [comment]
> Then "makes zero sense" may not be the perfect take ? :-)

Yes, you are right, of course. I was just saying that I am very confused by this process of adding shadow routes on a payment between two nodes through a direct channel with no intermediate nodes, as my understanding was that shadow routing is meant to conceal information from intermediate nodes. Both the payer and the payee know the identities of each other, and there is a direct channel, so I don’t see the point in hiding some information from either of them. However, admittedly, even the RFC you quoted gives an example of a direct payment “B->C” with added shadow routes, and that only adds to my confusion 😕.

**Comment by darosior** [comment]
For sure this doesn't avoid intermediate nodes from guessing their position, as there are none.

> Both the payer and the payee know the identities of each other

No, just in your specific case.
A payee cannot tell if the payment came from its direct peer, or if its peer is the second-to-last node in a route. In this case _-and I may be overthinking this-_, a bigger `cltv_delta` means that maybe a route was computed (the origin node sets it) and a bigger `amount` may mean that someone used shadow routing (so a route was computed).

We randomize the addition of shadow routes though, so you can't really just say "ah a bigger amount and CLTV, that's because my peer is running C-lightning".

**Comment by kirelagin** [comment]
> A payee cannot tell if the payment came from its direct peer, or if its peer is the second-to-last node in a route.

Ok, now I get it. I was mistakenly assuming the the payment information includes the payer id, but, evidently, it doesn’t. Thanks for the explanation!
