### ISSUE TITLE
Amount exceeded 16777215sat even with --large-channels

### ISSUE THREAD

**Issue by mb300sd** [ElementsProject/lightning#3694]
### Issue and Steps to Reproduce
I'm still getting "Amount exceeded 16777215sat" even with --large-channels enabled.

Attempting to open channel with bitrefill (030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f), known to support large channels.

Version v0.8.2-6-g64b0487

**Comment by mb300sd** [comment]
lightning-cli listpeers 030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f | grep features
         "features": "02a2a1",

When is features recalculated? I tried closing the existing channel, and disconnecting the peer, but is it remembered in the database? Which bit represents large channel support?

**Comment by darosior** [comment]
> Which bit represents large channel support?

[The 19th (18) one](https://github.com/lightningnetwork/lightning-rfc/blob/master/09-features.md).

**Comment by mb300sd** [comment]
Are the feature bits cached for a peer somehow after all channels are closed, and disconnected? I'm assuming I have to close the channel, disconnect, and wait until the node completely disappears from listpeers before I can open a large channel. Is that correct? Node is fairly well connected and I can't find a node that supports it that I don't already have a channel with.

**Comment by mloop1** [comment]
> Are the feature bits cached for a peer somehow after all channels are closed, and disconnected? I'm assuming I have to close the channel, disconnect, and wait until the node completely disappears from listpeers before I can open a large channel. Is that correct? Node is fairly well connected and I can't find a node that supports it that I don't already have a channel with.

Hey, my node supports large-channels. Reach out if you want to connect!
