### ISSUE TITLE
Allow htlc_accepted hook to respond with UPDATE failure messages.

### ISSUE THREAD

**Issue by tnull** [ElementsProject/lightning#3705]
### Issue and Steps to Reproduce
I'm currently experimenting with a scenario in which I want to dynamically react to incoming HTLCs and, for example, adapt my channel policies. For this, I utilize the `htlc_accepted` hook offered by the plugin API and depending on the circumstances return a corresponding `failure_message`.

However, this currently does only work for failure messages that do not need additional parameters or require to append a channel update. That is, returning any failure message with the `UPDATE`/`0x1000` failure code (cf. [BOLT 04](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#failure-messages)) currently results in an invalid fail onion.

It would be great if the plugin API would offer the ability to specify the additional fields required by the failure message or at least populate them with sane default values so failures with the  `UPDATE` failure code could be returned by the `htlc_accepted` hook. 

For my testing purposes, I implemented the latter approach, [which can be seen here](https://github.com/tnull/lightning/commit/6598b5f254856cdd43f3d4d03654f2fc8ca4d036).

**Comment by cdecker** [comment]
Excellent idea, I'll see if I can add the full error payload as an argument.

**Comment by cdecker** [comment]
This was addressed in #3472
