### ISSUE TITLE
Fail channel if the htlc amount is below the minimum amount

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#371]
@pm47 pointed out that we do not enforce the following rules in BOLT02

> receiving an amount_msat equal to 0, OR less than its own htlc_minimum_msat:
>  SHOULD fail the channel.

Currently we just fail the incoming HTLC but not the channel.

**Comment by pm47** [comment]
Also, it seems c-lightning currently doesn't enforce a minimum value?

https://github.com/ElementsProject/lightning/blob/cfde208e8212e4943409e23ae6da1a4d10907a0a/lightningd/peer_control.c#L501

**Comment by rustyrussell** [comment]
AFAICT this is incorrect: we enforce both <= minimum, OR == 0, with peer_failed() which sends an error message (and currently kills the connection):

channel/full_channel.c:
```
	if (htlc->msatoshi == 0) {
		e = CHANNEL_ERR_HTLC_BELOW_MINIMUM;
		goto out;
	}
	if (htlc->msatoshi < htlc_minimum_msat(channel, recipient)) {
		e = CHANNEL_ERR_HTLC_BELOW_MINIMUM;
		goto out;
	}
```

and the caller:

```
	add_err = channel_add_htlc(peer->channel, REMOTE, id, amount_msat,
				   cltv_expiry, &payment_hash,
				   onion_routing_packet);
	if (add_err != CHANNEL_ERR_ADD_OK)
		peer_failed(io_conn_fd(peer->peer_conn),
			    &peer->pcs.cs,
			    &peer->channel_id,
			    "Bad peer_add_htlc: %u", add_err);
```
