### ISSUE TITLE
Channel between my two nodes mutual-closed, but I didn't ask it to close

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#3743]
Since yesterday or perhaps 2 days ago I've been getting a ton of channel closes, apparently they're all "mutual" but two peers I've talked to said they didn't close, and so didn't I. Even a [channel I had with my other node](https://ln.bigsun.xyz/channel/623255x1489x0) was mutual-closed, and I'm 100% sure I didn't issue any command to close channels.

```
~> ~/lightning/cli/lightning-cli getinfo
{
  "id": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
  "alias": "@lntxbot",
  "color": "296683",
  "num_peers": 18,
  "num_pending_channels": 2,
  "num_active_channels": 13,
  "num_inactive_channels": 3,
  "address": [
    {
      "type": "ipv6",
      "address": "2a01:4f8:c0c:7b31::1",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv6",
      "address": "::",
      "port": 9735
    },
    {
      "type": "ipv4",
      "address": "0.0.0.0",
      "port": 3597
    }
  ],
  "version": "v0.8.0-686-g1fb9a07",
  "blockheight": 631307,
  "network": "bitcoin",
  "msatoshi_fees_collected": 931259,
  "fees_collected_msat": "931259msat",
  "lightning-dir": "/home/fiatjaf/.lightning/bitcoin",
  "warning_lightningd_sync": "Still loading latest blocks from bitcoind."
}
```

**Comment by fiatjaf** [comment]
I don't know if this is related, but I also have been having a ton of pending HTLCs, mostly `in` and they never resolve or cancel:

```
~> ~/lightning/cli/lightning-cli listpeers | jq '.peers[] | {id: .id, channel: .channels[0].short_channel_id, htlcs: .channels[0].htlcs} | select((.htlcs | length) > 0)'
{
  "id": "0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f",
  "connected": false,
  "channel": "590675x1677x0",
  "htlcs": [
    {
      "direction": "in",
      "id": 2434,
      "msatoshi": 12860000,
      "amount_msat": "12860000msat",
      "expiry": 631126,
      "payment_hash": "585ecf90b7822ba9ee910af975d56aaf4da82180de188146cf6d4f90e5da927e",
      "state": "SENT_REMOVE_HTLC"
    },
    {
      "direction": "in",
      "id": 2436,
      "msatoshi": 12860000,
      "amount_msat": "12860000msat",
      "expiry": 631128,
      "payment_hash": "97a7391003e988f340f332f55ee40ab2b0de5be4196979df83e8e1bd5ecf30ac",
      "state": "SENT_REMOVE_HTLC"
    },
    {
      "direction": "in",
      "id": 2435,
      "msatoshi": 12860000,
      "amount_msat": "12860000msat",
      "expiry": 631127,
      "payment_hash": "3226fb320ba868aa3209f4005bc610f09db55a23b16f7bb8ce8793945afe161b",
      "state": "SENT_REMOVE_HTLC"
    }
  ]
}
{
  "id": "03ee180e8ee07f1f9c9987d98b5d5decf6bad7d058bdd8be3ad97c8e0dd2cdc7ba",
  "connected": false,
  "channel": "604091x1187x1",
  "htlcs": [
    {
      "direction": "in",
      "id": 1233,
      "msatoshi": 12860000,
      "amount_msat": "12860000msat",
      "expiry": 631129,
      "payment_hash": "a64eb9bca44821d61a3385e18a80553ca86085fb1e20def8dcc5321f5cd2a578",
      "state": "SENT_REMOVE_HTLC",
      "local_trimmed": true
    },
    {
      "direction": "in",
      "id": 1232,
      "msatoshi": 12860000,
      "amount_msat": "12860000msat",
      "expiry": 631128,
      "payment_hash": "4fd8d0d71172a86ae47d9920c57778eae00d16e3285580bce69bf74113b7d784",
      "state": "SENT_REMOVE_HTLC",
      "local_trimmed": true
    },
    {
      "direction": "in",
      "id": 1231,
      "msatoshi": 12860000,
      "amount_msat": "12860000msat",
      "expiry": 631128,
      "payment_hash": "c5cde730f69aacadaf489631d371f2a230956c26bd75a652589115b0666be002",
      "state": "SENT_REMOVE_HTLC",
      "local_trimmed": true
    },
    {
      "direction": "in",
      "id": 1234,
      "msatoshi": 483174370,
      "amount_msat": "483174370msat",
      "expiry": 631478,
      "payment_hash": "7a99bee2c28a9a821ed2478b0f9a548093d9e0a957bdc418a731f63e3b267bc6",
      "state": "SENT_REMOVE_HTLC"
    }
  ]
}
{
  "id": "03a503d8e30f2ff407096d235b5db63b4fcf3f89a653acb6f43d3fc492a7674019",
  "connected": false,
  "channel": "615637x1735x1",
  "htlcs": [
    {
      "direction": "in",
      "id": 485,
      "msatoshi": 101400,
      "amount_msat": "101400msat",
      "expiry": 630878,
      "payment_hash": "63eab8d9d12e4fba68ec79aba9e63752b9dc1f1f80c74724ab35c7b70ce48033",
      "state": "RCVD_REMOVE_REVOCATION",
      "local_trimmed": true
    },
    {
      "direction": "out",
      "id": 3802,
      "msatoshi": 671000,
      "amount_msat": "671000msat",
      "expiry": 630677,
      "payment_hash": "3ceb244734da4677f66833b62425e87758193999b9521552ff821d40675187cc",
      "state": "RCVD_REMOVE_HTLC",
      "local_trimmed": true
    }
  ]
}
{
  "id": "03d480ac7ad220371f1b9c2560be7eb8da6335d6a0d8cb1bc27db1a3958fd8c73f",
  "connected": true,
  "channel": "618533x1076x0",
  "htlcs": [
    {
      "direction": "out",
      "id": 41252,
      "msatoshi": 2529004,
      "amount_msat": "2529004msat",
      "expiry": 631433,
      "payment_hash": "6ea42c40d43fd594c428872d17e9faf3494618ed1d51a93bc44d562d2ae458b2",
      "state": "SENT_REMOVE_ACK_COMMIT",
      "local_trimmed": true
    }
  ]
}
{
  "id": "033868c219bdb51a33560d854d500fe7d3898a1ad9e05dd89d0007e11313588500",
  "connected": false,
  "channel": "621302x1998x0",
  "htlcs": [
    {
      "direction": "out",
      "id": 8993,
      "msatoshi": 6011225,
      "amount_msat": "6011225msat",
      "expiry": 630982,
      "payment_hash": "395f4c4322020fb4e24070009677a397c3f310e9b4cc37793eb712e239b5e6c2",
      "state": "RCVD_REMOVE_HTLC",
      "local_trimmed": true
    }
  ]
}
```

And then they don't have a correlated HTLC on a different channel, so it's clearly my fault (right):

```
~> ~/lightning/cli/lightning-cli listpeers | jq '.peers[].channels[].htlcs[].payment_hash' | sort
"3226fb320ba868aa3209f4005bc610f09db55a23b16f7bb8ce8793945afe161b"
"395f4c4322020fb4e24070009677a397c3f310e9b4cc37793eb712e239b5e6c2"
"3ceb244734da4677f66833b62425e87758193999b9521552ff821d40675187cc"
"4fd8d0d71172a86ae47d9920c57778eae00d16e3285580bce69bf74113b7d784"
"585ecf90b7822ba9ee910af975d56aaf4da82180de188146cf6d4f90e5da927e"
"63eab8d9d12e4fba68ec79aba9e63752b9dc1f1f80c74724ab35c7b70ce48033"
"7a99bee2c28a9a821ed2478b0f9a548093d9e0a957bdc418a731f63e3b267bc6"
"97a7391003e988f340f332f55ee40ab2b0de5be4196979df83e8e1bd5ecf30ac"
"a64eb9bca44821d61a3385e18a80553ca86085fb1e20def8dcc5321f5cd2a578"
"c5cde730f69aacadaf489631d371f2a230956c26bd75a652589115b0666be002"
```

**Comment by fiatjaf** [comment]
Oh, this is also relevant. I keep seeing these messages in the logs:

```
2020-05-22T15:49:58.690Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
2020-05-22T15:50:59.188Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
2020-05-22T15:51:35.698Z INFO 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c-channeld-chan#2582: Peer connection lost
2020-05-22T15:51:35.699Z INFO 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c-chan#2582: Peer transient failure in CHANNELD_AWAITING_LOCKIN: channeld: Owning subdaemon channeld died (62208)
2020-05-22T15:52:00.174Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
2020-05-22T15:53:01.124Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
2020-05-22T15:54:02.354Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
2020-05-22T15:55:04.217Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
2020-05-22T15:56:04.816Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
2020-05-22T15:56:37.565Z INFO 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c-channeld-chan#2582: Peer connection lost
2020-05-22T15:56:37.568Z INFO 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c-chan#2582: Peer transient failure in CHANNELD_AWAITING_LOCKIN: channeld: Owning subdaemon channeld died (62208)
2020-05-22T15:57:05.695Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
2020-05-22T15:58:06.402Z INFO 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f-chan#4790: Peer transient failure in CHANNELD_NORMAL: channeld: (ignoring) channel f176e0f0a519eb969037aaff8af9636adf1d7eec2e3ec1e0b1310e2b2d0fa8e1: Offered HTLC 2434 SENT_ADD_ACK_REVOCATION cltv 631126 hit deadline
```

Meaning that the HTLCs have expired already but we're ignoring them... why? (I mean: this is certainly a good thing, I prefer that these channels remain open until these issues are fixed, but it still puzzles me.)

**Comment by engenegr** [comment]
I have a node with such mutually closed channel.

Output lntxbot node reported by fiatjaf.
`lightning-cli listpeers 02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff`

```
{
   "peers": [
      {
         "id": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
         "connected": false,
         "channels": [
            {
               "state": "CLOSINGD_COMPLETE",
               "scratch_txid": "cd3825876d0e38da2500a89790232167d53649b77a8154d707668ab48a891f07",
               "channel_id": "28f81002d78aa14433f08d30927a805cefbd7060915e72fa2cde9ee50156b727",
               "funding_txid": "27b75601e59ede2cfa725e916070bdef5c807a92308df03344a18ad70210f828",
               "private": false,
               "funding_allocation_msat": {
                  "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff": 0,
                  "02e6479366043ef69d75682831947010843b2d94aef9131ba8ef492857d347b664": 2000000000
               },
               "funding_msat": {
                  "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff": "0msat",
                  "02e6479366043ef69d75682831947010843b2d94aef9131ba8ef492857d347b664": "2000000000msat"
               },
               "msatoshi_to_us": 2000000000,
               "to_us_msat": "2000000000msat",
               "msatoshi_to_us_min": 2000000000,
               "min_to_us_msat": "2000000000msat",
               "msatoshi_to_us_max": 2000000000,
               "max_to_us_msat": "2000000000msat",
               "msatoshi_total": 2000000000,
               "total_msat": "2000000000msat",
               "dust_limit_satoshis": 546,
               "dust_limit_msat": "546000msat",
               "max_htlc_value_in_flight_msat": 18446744073709551615,
               "max_total_htlc_in_msat": "18446744073709551615msat",
               "their_channel_reserve_satoshis": 20000,
               "their_reserve_msat": "20000000msat",
               "our_channel_reserve_satoshis": 20000,
               "our_reserve_msat": "20000000msat",
               "spendable_msatoshi": 1979774000,
               "spendable_msat": "1979774000msat",
               "htlc_minimum_msat": 0,
               "minimum_htlc_in_msat": "0msat",
               "their_to_self_delay": 144,
               "our_to_self_delay": 2016,
               "max_accepted_htlcs": 30,
               "status": [
                  "Loaded from database"
               ],
               "in_payments_offered": 0,
               "in_msatoshi_offered": 0,
               "in_offered_msat": "0msat",
               "in_payments_fulfilled": 0,
               "in_msatoshi_fulfilled": 0,
               "in_fulfilled_msat": "0msat",
               "out_payments_offered": 0,
               "out_msatoshi_offered": 0,
               "out_offered_msat": "0msat",
               "out_payments_fulfilled": 0,
               "out_msatoshi_fulfilled": 0,
               "out_fulfilled_msat": "0msat",
               "htlcs": []
            },
            {
               "state": "ONCHAIN",
               "scratch_txid": "e3c0d6167d9f4e606a549cb1e09eea0634e8837944acbaf652a3c2c580f9492b",
               "owner": "lightning_onchaind",
               "short_channel_id": "606778x661x0",
               "direction": 1,
               "channel_id": "34b99cad4c9dd2b311cc3cd7c96ee3960d60ea6fa44ab2c5d2bab43af58b0241",
               "funding_txid": "41028bf53ab4bad2c5b24aa46fea600d96e36ec9d73ccc11b3d29d4cad9cb934",
               "private": false,
               "funding_allocation_msat": {
                  "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff": 0,
                  "02e6479366043ef69d75682831947010843b2d94aef9131ba8ef492857d347b664": 1998809000
               },
               "funding_msat": {
                  "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff": "0msat",
                  "02e6479366043ef69d75682831947010843b2d94aef9131ba8ef492857d347b664": "1998809000msat"
               },
               "msatoshi_to_us": 1978489895,
               "to_us_msat": "1978489895msat",
               "msatoshi_to_us_min": 772274828,
               "min_to_us_msat": "772274828msat",
               "msatoshi_to_us_max": 1998809000,
               "max_to_us_msat": "1998809000msat",
               "msatoshi_total": 1998809000,
               "total_msat": "1998809000msat",
               "dust_limit_satoshis": 546,
               "dust_limit_msat": "546000msat",
               "max_htlc_value_in_flight_msat": 18446744073709551615,
               "max_total_htlc_in_msat": "18446744073709551615msat",
               "their_channel_reserve_satoshis": 19988,
               "their_reserve_msat": "19988000msat",
               "our_channel_reserve_satoshis": 19988,
               "our_reserve_msat": "19988000msat",
               "spendable_msatoshi": 1875238895,
               "spendable_msat": "1875238895msat",
               "htlc_minimum_msat": 0,
               "minimum_htlc_in_msat": "0msat",
               "their_to_self_delay": 144,
               "our_to_self_delay": 2016,
               "max_accepted_htlcs": 30,
               "status": [
                  "CHANNELD_NORMAL:Reconnected, and reestablished.",
                  "ONCHAIN:Tracking our own unilateral close",
                  "ONCHAIN:1 outputs unresolved: in 1860 blocks will spend DELAYED_OUTPUT_TO_US (e3c0d6167d9f4e606a549cb1e09eea0634e8837944acbaf652a3c2c580f9492b:1) using OUR_DELAYED_RETURN_TO_WALLET"
               ],
               "in_payments_offered": 438,
               "in_msatoshi_offered": 12770746019,
               "in_offered_msat": "12770746019msat",
               "in_payments_fulfilled": 147,
               "in_msatoshi_fulfilled": 5107097095,
               "in_fulfilled_msat": "5107097095msat",
               "out_payments_offered": 509,
               "out_msatoshi_offered": 42157927947,
               "out_offered_msat": "42157927947msat",
               "out_payments_fulfilled": 112,
               "out_msatoshi_fulfilled": 5127416200,
               "out_fulfilled_msat": "5127416200msat",
               "htlcs": [
                  {
                     "direction": "out",
                     "id": 503,
                     "msatoshi": 12860000,
                     "amount_msat": "12860000msat",
                     "expiry": 631127,
                     "payment_hash": "59cd3b8a6516c38f41b9de18c44b7173412bcc9788b71c0606fb4181a129482c",
                     "state": "RCVD_REMOVE_HTLC",
                     "local_trimmed": true
                  },
                  {
                     "direction": "out",
                     "id": 505,
                     "msatoshi": 12860000,
                     "amount_msat": "12860000msat",
                     "expiry": 631128,
                     "payment_hash": "e5230623dce97d0b594fa4b2acaede35560c9e4b35be8ddd135c6236ce596f70",
                     "state": "RCVD_REMOVE_HTLC",
                     "local_trimmed": true
                  },
                  {
                     "direction": "out",
                     "id": 504,
                     "msatoshi": 12860000,
                     "amount_msat": "12860000msat",
                     "expiry": 631127,
                     "payment_hash": "d87dadcd4b148d30fb9171d771208a46052be3567bd58796a9532af6afb0d9bb",
                     "state": "RCVD_REMOVE_HTLC",
                     "local_trimmed": true
                  }
               ]
            }
         ]
      }
   ]
}
```

**Comment by cdecker** [comment]
That is exactly because the HTLCs were hung, which requires us to settle the HTLC on-chain in order to be safe. I don't know what is causing the HTLCs to become stuck, but it might be a node crash along the route, a hodl invoice, or a plugin abusing the `htlc_accepted` hook.

It's a protocol related issue, that we don't currently have a solution for :frowning_face:

**Comment by cdecker** [comment]
> And then they don't have a correlated HTLC on a different channel, so it's clearly my fault (right):

That is indeed interesting, what plugins (if any) are you running on that node? It might actually be a symptom of https://github.com/ElementsProject/lightning/issues/3748

**Comment by fiatjaf** [comment]
> That is exactly because the HTLCs were hung

If this was the case shouldn't the channels be force-closed, unilateral etc.? What puzzled me was that they were mutual-closed, with no HTLCs onchain, and no OP_CSV outputs.

**Comment by fiatjaf** [comment]
> what plugins (if any) are you running on that node?

```
{
   "plugins": [
      {
         "name": "/home/fiatjaf/lightning/lightningd/../plugins/lntxbot",
         "active": true
      },
      {
         "name": "/home/fiatjaf/lightning/lightningd/../plugins/sparko",
         "active": true
      },
      {
         "name": "/home/fiatjaf/lightning/lightningd/../plugins/autoclean",
         "active": true
      },
      {
         "name": "/home/fiatjaf/lightning/lightningd/../plugins/cowsay.sh",
         "active": true
      },
      {
         "name": "/home/fiatjaf/lightning/lightningd/../plugins/keysend",
         "active": true
      },
      {
         "name": "/home/fiatjaf/lightning/lightningd/../plugins/bcli",
         "active": true
      },
      {
         "name": "/home/fiatjaf/lightning/lightningd/../plugins/pay",
         "active": true
      },
      {
         "name": "/home/fiatjaf/lightning/lightningd/../plugins/fundchannel",
         "active": true
      }
   ]
}
```

I thought I had no plugins using `htlc_accepted`, but now that I see the list `keysend` is there and maybe it was the one causing the issue? Hard to know now.

**Comment by cdecker** [comment]
> If this was the case shouldn't the channels be force-closed, unilateral etc.? What puzzled me was that they were mutual-closed, with no HTLCs onchain, and no OP_CSV outputs.

No, we'll try to negotiate a low fee and close without CSV timeouts on the direct outputs, there's no reason not to, after all the HTLC may have been held up somewhere else, and if the counterparty is available we safe fees and timeouts.



> > what plugins (if any) are you running on that node?
> 
> ```
> {
>    "plugins": [
>       {
>          "name": "/home/fiatjaf/lightning/lightningd/../plugins/lntxbot",
>          "active": true
>       },
>       {
>          "name": "/home/fiatjaf/lightning/lightningd/../plugins/sparko",
>          "active": true
>       },
>       {
>          "name": "/home/fiatjaf/lightning/lightningd/../plugins/autoclean",
>          "active": true
>       },
>       {
>          "name": "/home/fiatjaf/lightning/lightningd/../plugins/cowsay.sh",
>          "active": true
>       },
>       {
>          "name": "/home/fiatjaf/lightning/lightningd/../plugins/keysend",
>          "active": true
>       },
>       {
>          "name": "/home/fiatjaf/lightning/lightningd/../plugins/bcli",
>          "active": true
>       },
>       {
>          "name": "/home/fiatjaf/lightning/lightningd/../plugins/pay",
>          "active": true
>       },
>       {
>          "name": "/home/fiatjaf/lightning/lightningd/../plugins/fundchannel",
>          "active": true
>       }
>    ]
> }
> ```
> 
> I thought I had no plugins using `htlc_accepted`, but now that I see the list `keysend` is there and maybe it was the one causing the issue? Hard to know now.

Hm, keysend should be safe to use, it doesn't really do much with the HTLC other than rewriting the payload and returning. Any plugin crashes in the logs?

**Comment by engenegr** [comment]
This is insane that despite mutual close node wallet still can't use coins from closed channel.

```ONCHAIN:1 outputs unresolved: in 1860 blocks will spend DELAYED_OUTPUT_TO_US```

**Comment by fiatjaf** [comment]
> Any plugin crashes in the logs?

No, I did search for that extensively or anything else that looked odd. The only odd thing I found were [these entries](#issuecomment-632773149) (many many times).

But again, I didn't have verbose logging on because that is too verbose and fills up my log files too fast.

**Comment by rustyrussell** [comment]
> > If this was the case shouldn't the channels be force-closed, unilateral etc.? What puzzled me was that they were mutual-closed, with no HTLCs onchain, and no OP_CSV outputs.
> 
> No, we'll try to negotiate a low fee and close without CSV timeouts on the direct outputs, there's no reason not to, after all the HTLC may have been held up somewhere else, and if the counterparty is available we safe fees and timeouts.

We do?  I don't think so, since the spec says you can only mutual close with no outstanding HTLCs.  We cannot and do not try to mutual close in this case.

@fiatjaf is confused, this is a unilateral close.

**Comment by cdecker** [comment]
> We do? I don't think so, since the spec says you can only mutual close with no outstanding HTLCs. We cannot and do not try to mutual close in this case.
> 
> @fiatjaf is confused, this is a unilateral close.

You're right, that'd also explain the delay that @engenegr was seeing. The HTLCs are all about to be removed (contradicting my earlier assumption that it was a plugin which only acts on committed but not removed HTLCs), but it appears a new commitment was not signed in time, that could be explained by a disconnect (which would not have worked in combination with a mutual close either).

The HTLC IDs are very close together (a, a+1, a+2, ...) so they were likely in flight at the same time on the respective channels when it stopped updating, which also points to a disconnect rather than an internal error.

The downstream HTLCs most likely were settled correctly, hence they are no longer listed on the channels (but `listforwards` might add some information).

**Comment by engenegr** [comment]
Thank you very much for the explanation @cdecker.

I guess if disconnecting is expected but unavoidable, It might be possible to circumvent such situations by just to stopping node before network restart?

**Comment by cdecker** [comment]
> I guess if disconnecting is expected but unavoidable, It might be possible to circumvent such situations by just stopping node before network restart?

I'm afraid there is no solution to these types of closures (unlike the fee-spike closures which we could work around), it'll always be the case that a peer can crash or disconnect and not come back while we are handling an HTLC.

It should also be noted this only happens if the connection cannot be re-established before the timeout expires. If the peer comes back before the timeout expires we'd just continue normally and the HTLC would get resolved. So there is no need to drain a channel of its HTLCs before restarting (might not even be doable), because we need to be able to handle spontaneous power failures, crashes and WLAN hickups anyway :-)

**Comment by cdecker** [comment]
Digging a bit deeper into @fiatjaf's initial report we can find the [channel funding output](https://blockstream.info/tx/e1a80f2d2b0e31b1e0c13e2eec7e1ddf6a63f98affaa379096eb19a5f0e076f1?output:0) for short channel ID 590675x1677x0. We can then follow the spend to the close transaction [c0e671c86204c7](https://blockstream.info/tx/c0e671c86204c74ae86f10a8b17e474a0ac16ebbb82c5877be81c76ceafda46b?input:0) which has 5 outputs:

 - Outputs [0](https://blockstream.info/tx/c0e671c86204c74ae86f10a8b17e474a0ac16ebbb82c5877be81c76ceafda46b?output:0), [1](https://blockstream.info/tx/c0e671c86204c74ae86f10a8b17e474a0ac16ebbb82c5877be81c76ceafda46b?output:1) and [2](https://blockstream.info/tx/c0e671c86204c74ae86f10a8b17e474a0ac16ebbb82c5877be81c76ceafda46b?output:2) are clearly HTLC outputs. They are P2WSH outputs with values matching the HTLCs.
 - Output [3](https://blockstream.info/tx/c0e671c86204c74ae86f10a8b17e474a0ac16ebbb82c5877be81c76ceafda46b?output:3) is a P2WPKH, and therefore one of the direct outputs (presumably going to your counterparty on that channel).
 - Output [4](https://blockstream.info/tx/c0e671c86204c74ae86f10a8b17e474a0ac16ebbb82c5877be81c76ceafda46b?output:4) is a P2WSH output, which could really be anything, however it is unlikely to be a non-delayed direct output since that'd require the destination to have set a custom final scriptpubkey at channel creation, and so I think this is most likely a CSV-delayed `our_unilateral/to_us` P2WSH output. Once it is unlocked and spent we will be able to see more details.

I would expect the other channels to behave similarly.

**Comment by fiatjaf** [comment]
:embarrased:

**Comment by fiatjaf** [comment]
This was all a big confusion from my part, I was misled by an error on ln.bigsun.xyz on the identification of the type of channel closure and then @engenegr told me the channel was mutual-closed and I believed he had another reason to believe that, but actually he was also looking at the same site with the same error. Sorry about that.

**Comment by fiatjaf** [comment]
But still would be nice to know why the daemon was not able to connect to other peers. For example, in case of my two nodes with a channel between them I know they both were online all the time, except during restarts, and still they closed their channel. I believe @engenegr's node was also online all the time, and @tkijewski's too, and these are all publicly accessible nodes. I believe I even checked the `connected` status on `listpeers` between the two nodes I owned while the HTLCs were in-flight and it was ok.

**Comment by cdecker** [comment]
I'm afraid that with stuck HTLCs the problem may be several hops away, and still cause your channel to be killed. There's nothing we can do at this point, since a stuck HTLC may backpropagate more than 1 hop upstream from the failure point.

My napkin sketch is the following (`f` being the failing node):

```
min_{i} \Sum_{j..f} cltv_delta_j) s.t. htlc_cltv_f - blockheight
```

Not sure if that helps, but it's made a bit more complex by `cltv_delta_j` not being constant. I can try to come up with an example if that'd make it easier. It basically boils down to the htlc times out or is successful and is settled on-chain at the failing node, before the CLTV on your channel expires. That's the theoretical limitation, that can be achieved iff we watch the blockchain for preimages, which is on our roadmap.

Sorry I can't give a more definitive solution :frowning_face:
