### ISSUE TITLE
Command to figure out total spendable balance?

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3750]
Besides parsing the output of `listfunds`, shouldn't we have a way to see how much funds we can send, and how much we can receive?

**Comment by cdecker** [comment]
I think you want the `spendable_msat` field in the channels in `listpeers`:

```bash
$ lightning-cli listpeers | jq '.peers[].channels[].spendable_msat'
"2019900000msat"
```

It's really easy to either sum up the channels or to have a plugin do it for you and then calling the plugin to get the total.

**Comment by niftynei** [comment]
the `summary` plugin should cover this https://github.com/lightningd/plugins/tree/master/summary
