### ISSUE TITLE
Taken pointer in lightning_gossipd triggered by sendinvoiceless plugin

### ISSUE THREAD

**Issue by sumBTC** [ElementsProject/lightning#3757]
### Issue and Steps to Reproduce

See: https://bitkoins.nl/clightning/out.txt
See: https://bitkoins.nl/clightning/gossip_store.corrupt

EDIT: `lightning_gossipd: Outstanding taken pointers: (nil)`
doesn't sound good to me ;-)

### `getinfo` output

"version": "v0.8.2-178-g8d98b99"

**Comment by cdecker** [comment]
This is very strange indeed. The code that is reporting an error is this:

https://github.com/ElementsProject/lightning/blob/8d98b99bde55ad0844761b584311543c9051b6f7/common/daemon.c#L81-L92

(permalink to the commit you reported, but it is unchanged since then)

The code tests whether we have any taken pointers, assigning to `t`, checks whether `t` is `NULL`, and if not it aborts with an error message. From the error message it seems that the pointer is `NULL` / `(nil)`, so it should not have triggered the abort, but it does.

I have no idea how that could happen. Paging Dr @rustyrussell :-)

**Comment by ZmnSCPxj** [comment]
It could be `taken_any` returns a non-`NULL` pointer to the string `"(nil)"`.  So possibly we may need to look inside at `taken_any` as well.

**Comment by ZmnSCPxj** [comment]
Looking at `taken_any`, it does a `sprintf(buffer, "%p", takenarr[0])`.    So it could indeed end up pointing to a string `"(nil)"`, if `takenarr[0]` is NULL, `num_taken` is not 0, and there is no `labelarr`.  This implies somebody did a `take` on a `NULL`, I think.

**Comment by sumBTC** [comment]
Haha, indeed:

```
#include <stdio.h>

int main() {
  const char *t;

  t = "nil";

  if (t)
    printf("Outstanding taken pointers: %s", t);

  return 0;
}
```

**Comment by sumBTC** [comment]
By the way, [here](https://Bitkoins.nl/clightning/out.txt_crash_2) is another one from some time ago which maybe gives a little more information after the "(nil)".

**Comment by ZmnSCPxj** [comment]
A part that might be the culprit:

https://github.com/ElementsProject/lightning/blob/5db69f1b414f04c204f086424c96d10c20a8be39/gossipd/gossipd.c#L1499

The `channel_update` is loaded from this:

https://github.com/ElementsProject/lightning/blob/5db69f1b414f04c204f086424c96d10c20a8be39/gossipd/gossipd.c#L1481-L1497

Those `fromwire_` functions will load `NULL` into `channel_update` if the length of the channel update is 0 (which should not happen, but *shrug* it comes from remote node, which might be buggy or whatev).

The interesting bit is your logs:

```
2020-06-15T04:12:33.734Z INFO plugin-sendinvoiceless.py: RpcError: RPC call failed: method: waitsendpay, payload: {'payment_hash': '271163d996bb2fda734a70ea2f5ee08a5ed89992289f81b2bd93a5dfabb8a2e2', 'timeout': 46}, error: {'code': 204, 'message': 'failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)', 'data': {'id': 245, 'payment_hash': '271163d996bb2fda734a70ea2f5ee08a5ed89992289f81b2bd93a5dfabb8a2e2', 'destination': '02888244029c5909593038ab19f269947c720de3423e491791b46c7c92f76279b6', 'msatoshi': 1000, 'amount_msat': 1000msat, 'msatoshi_sent': 40009003, 'amount_sent_msat': 40009003msat, 'created_at': 1592194346, 'status': 'pending', 'erring_index': 3, 'failcode': 4103, 'failcodename': 'WIRE_TEMPORARY_CHANNEL_FAILURE', 'erring_node': '021f7430cce1b1ec01675bd575c0785ee2150d1d3167588b7e52a8050d2df2d28e', 'erring_channel': '623356x854x1', 'erring_direction': 0, 'raw_message': '10070000'}}
```

See the `raw_message` bit?  It says `10070000`.  That is hex: two bytes of message ID (0x1007) followed by two 0 bytes of length --- precisely what would cause `fromwire_temporary_channel_failure` to set `channel_update` to `NULL`.

Note in particular 0x1007 is:

https://github.com/ElementsProject/lightning/blob/5db69f1b414f04c204f086424c96d10c20a8be39/wire/extracted_onion_wire_csv#L21-L23

`UPDATE` is defined here:

https://github.com/ElementsProject/lightning/blob/5db69f1b414f04c204f086424c96d10c20a8be39/wire/onion_defs.h#L17

Thus `WIRE_TEMPORARY_CHANNEL_FAILURE` is 0x1007 (`UPDATE|7`).

We see as well that the bytes after the message code is the length of the channel update, which the remote node gave as 0, which causes the generated `fromwire_` function to set `channel_update` to `NULL`, whih gets passed into `take` and possibly utterly destroys the `take` system (maybe).

So what we can do is try to add this code:

    if (!channel_update)
            return NULL;

before:

https://github.com/ElementsProject/lightning/blob/5db69f1b414f04c204f086424c96d10c20a8be39/gossipd/gossipd.c#L1499

And try to see if `sendinvoiceless` triggers the bug again or not.

**Comment by ZmnSCPxj** [comment]
This seems further corroborated by inspecting `patch_channel_update`:

https://github.com/ElementsProject/lightning/blob/5db69f1b414f04c204f086424c96d10c20a8be39/gossipd/gossipd.c#L1450-L1466

If `channel_update` is a `take`n pointer to `NULL`, then it goes into the second branch, which calls into `tal_dup_arr`:

https://github.com/ElementsProject/lightning/blob/5db69f1b414f04c204f086424c96d10c20a8be39/common/utils.c#L145-L150

The culprit is this:

https://github.com/ElementsProject/lightning/blob/5db69f1b414f04c204f086424c96d10c20a8be39/common/utils.c#L147-L148

If the input pointer is `NULL` we return `NULL` as well, BUT if it is a `take`n `NULL` pointer, we do not pass it to the `taken` function, which is needed in order to clear the `take`n-ness of `NULL`.

So a better fix would be:

```c
void *tal_dup_talarr_(const tal_t *ctx, const tal_t *src, const char *label)   
{       
        if (!src)
                return taken(src); 
        return tal_dup_(ctx, src, 1, tal_bytelen(src), 0, label);              
}
```

This makes `tal_dup_talarr` correctly take `NULL` inputs.

**Comment by sumBTC** [comment]
@ZmnSCPxj thanks for all the explanations, really appreciated. Of course I don't get all the details but the general idea is clear: a take of a NULL pointer should be handled correctly. It will be hard to test whether this solves my issue because I have the impression the problematic node   (021f7430cce1b1ec01675bd575c0785ee2150d1d3167588b7e52a8050d2df2d28e) has solved his issue. He wins my trading game (too :-)) often and gets his reward via `sendinvoiceless` but lately all payments go well. So probably we were "lucky" to see this bug. Anyway, on logical grounds the commit seems to solve the issue and IMHO the issue can therefore be closed.

**Comment by ZmnSCPxj** [comment]
Hmm.  Well it "should" be possible to write a plugin used in testing that will force an onion failure of `WIRE_TEMPORARY_CHANNEL_FAILURE` with a length-0 `channel_update` in `htlc_accepted` hook, which should tickle this bug as well.  Let me try to see if I can tickle that bug this way.

**Comment by ZmnSCPxj** [comment]
Got a similar message with the proposed test. https://travis-ci.org/github/ZmnSCPxj/lightning/jobs/700837757#L2572

**Comment by sumBTC** [comment]
I found it in the log looking for "(nil)". Nice to know the bug can be reproduced (and it's not "just me" :-)). When I restarted after the crash, c-lightning rebuild the `gossip_store` and moved the old one to `gossip_store.corrupt`. Can you see how the two issues are related? To check whether they are really related, I looked again at the dates of the original files:
```
-rw-rw-r-- 1 user user 668185 mei 31 21:41 out.txt_crash
-rw------- 1 user user 23807951 mei 31 21:43 /home/user/.lightning/bitcoin/gossip_store.corrupt
```
As you can see, I restarted c-lightning within a few minutes after the crash and indeed it then moved the `gossip_store` to `gossip_store.corrupt`. But if I remember correctly sometimes after the "(nil)" crash the `gossip_store` was still fine.

**Comment by ZmnSCPxj** [comment]
I think we have the conservative policy that any crash of `lightning_gossipd` might corrupt the gossip store, so we assume the gossip store is corrupted.  It might not necessarily *be* corrupted.  Though do note that the code I pointed out is what extracts a new `channel_update` from a payment failure, and we generally store `channel_update`s into the store, so the abort at that point might also be what lead to corrupted gossip stores.  Not certain; speculation.
