### ISSUE TITLE
**BROKEN** database: Accessing a null column 1 in query SELEC

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3768]
Updated to latest version,
```
./configure
make -j 8

2020-06-14T17:01:42.191Z INFO database: Updating database from version 133 to 136
2020-06-14T17:01:42.193Z **BROKEN** database: Accessing a null column 1 in query SELECT   c.id, p.node_id, c.last_tx, c.funding_satoshi, c.fundingkey_remote, c.last_sig FROM channels c  LEFT OUTER JOIN peers p  ON p.id = c.peer_id;
lightningd: wallet/db.c:1376: db_column_node_id: Assertion `db_column_bytes(stmt, col) == sizeof(dest->k)' failed.
lightningd: FATAL SIGNAL 6 (version v0.8.2-237-gaaefbe2)
0x433ed3 send_backtrace
	common/daemon.c:38
0x433f5d crashdump
	common/daemon.c:51
0x7ff65b0fc4af ???
	???:0
0x7ff65b0fc428 ???
	???:0
0x7ff65b0fe029 ???
	???:0
0x7ff65b0f4bd6 ???
	???:0
0x7ff65b0f4c81 ???
	???:0
0x45f82e db_column_node_id
	wallet/db.c:1376
0x460664 migrate_last_tx_to_psbt
	wallet/db.c:1153
0x46045b db_migrate
	wallet/db.c:999
0x460544 db_setup
	wallet/db.c:1038
0x463a8d wallet_new
	wallet/wallet.c:62
0x414a34 main
	lightningd/lightningd.c:838
0x7ff65b0e782f ???
	???:0
0x404428 ???
	???:0
0xffffffffffffffff ???
	???:0
```

**Comment by thestick613** [comment]
Should i downgrade to the previous git version? I'd really like to put my node back online..

**Comment by cdecker** [comment]
Just ran into this issue myself. Bisecting gives the following result:

```
bb589e0eafc363494c317a2e0ec5168a948c86f5 is the first bad commit
commit bb589e0eafc363494c317a2e0ec5168a948c86f5
Author: niftynei <niftynei@gmail.com>
Date:   Thu May 21 22:45:14 2020 -0500

    psbt: database migration for converting last_tx to a psbt

    We update the `last_tx` in `channels` to be psbt format, instead
    of a linearized transaction.

    We need the amount of the input populated, which we have since
    this is the 'funding' amount. Ideally we'd also populate the funding
    scriptPubkey, but to do that we'd need to access the HSM module to fetch
    our local funding pubkey, which isn't initialized at the time that the
    database migrations are run.

    Since the only field the HSM uses currently when signing these is the
    amount field, it's ok to just leave it out.

    needs a test!

 wallet/db.c          | 76 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 wallet/db.h          |  1 +
 wallet/test/run-db.c |  7 +++++
 3 files changed, 84 insertions(+)
```

From this I'm guessing it's about the foreign key into the `peers` table being NULL. Checking with the `state` of the channels in question it confirms this because all channels are in state `CLOSED`.

I'd propose we qualify this migration by adding a `WHERE` that excludes channels in `CLOSED`. In addition I don't particularly see the point in forgetting our former peers, since they contribute only a tiny amount of extra data, so we could also remove the peer deletion on close to avoid future NULL references in other tables :wink:

**Comment by thestick613** [comment]
Well now it doesn’t compile. Should i open a new ticket?

ng-pay.7.md doc/lightning-pay.7; else touch doc/lightning-pay.7; fi
Traceback (most recent call last):
File "/usr/local/bin/mrkd", line 6, in <module>
  from mrkd import main
File "/usr/local/lib/python3.5/dist-packages/mrkd.py", line 40
return f'{self.double_emphasis(text)}({section})'
^
SyntaxError: invalid syntax
doc/Makefile:54: recipe for target 'doc/lightning-pay.7' failed
make: *** [doc/lightning-pay.7] Error 1

**Comment by thestick613** [comment]
Well now it doesn’t compile. Should i open a new ticket?

ng-pay.7.md doc/lightning-pay.7; else touch doc/lightning-pay.7; fi
Traceback (most recent call last):
File "/usr/local/bin/mrkd", line 6, in <module>
  from mrkd import main
File "/usr/local/lib/python3.5/dist-packages/mrkd.py", line 40
return f'{self.double_emphasis(text)}({section})'
^
SyntaxError: invalid syntax
doc/Makefile:54: recipe for target 'doc/lightning-pay.7' failed
make: *** [doc/lightning-pay.7] Error 1

**Comment by niftynei** [comment]
yes please.
