### ISSUE TITLE
rube goldberg machine of errors leading to an assertion error in wallet_stmt2channel

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#377]
Hey there,

I attempted to open a channel for the first time yesterday and somehow got into a horrible unstable state, with errors from: `Insufficient fee` to `Missing inputs` and now I get:

`wallet_stmt2channel: Assertion col == 34' failed.`

in gdb, col is `33`

some local state:

```
(gdb) print *chan->peer
$5 = {ld = 0x0, dbid = 1, id = {pubkey = {
      data = "l\"\005\364Ot+\225{\345\063;ݣY\201\357\aD\205.\316\001\244\"U(\022\260乔\027\060\242s\272(\362\230>q\306|sHuQ?\034\217\020Wʻs\321`_\263\211\211\024\221"}},
gfeatures = 0x0, lfeatures = 0x0, error = 0x0, their_shachain = {id = 3, chain = {min_index = 281474976710655, num_valid = 1, known = {{index = 281474976710655,
          hash = {u = {u32 = {3736373703, 1175627272, 578181866, 3065099815, 18326226, 2360348775, 2589804154, 271787864},
              u8 = "ǉ\264\336\b\246\022F\352Zv\"'\266\261\266Ң\027\001g\020\260\214zF]\232X'3\020"}}}, {index = 0, hash = {u = {u32 = {0, 0, 0, 0, 0, 0, 0, 0},
              u8 = '\000' <repeats 31 times>}}} <repeats 48 times>}}}, state = CLOSINGD_SIGEXCHANGE, funder = LOCAL, list = {next = 0x0, prev = 0x0}, owner = 0x0,
  log_book = 0x0, log = 0x0, channel_flags = 1 '\001', addr = {type = ADDR_TYPE_PADDING, addrlen = 0 '\000', addr = '\000' <repeats 15 times>, port = 0}, our_config = {
    id = 3, dust_limit_satoshis = 546, max_htlc_value_in_flight_msat = 18446744073709551615, channel_reserve_satoshis = 0, htlc_minimum_msat = 0, to_self_delay = 6,    
    max_accepted_htlcs = 483}, minimum_depth = 1, next_index = {2, 2}, next_htlc_id = 0, funding_txid = 0x2bccb70, funding_outnum = 0, funding_satoshi = 1000000,   
  push_msat = 0, remote_funding_locked = true, scid = 0x1a3a1b0, our_msatoshi = 0x1a3a990, last_tx = 0x0, last_sig = 0x0, last_htlc_sigs = 0x0, channel_info = 0x6a5c70,
  seed = 0x0, remote_shutdown_scriptpubkey = 0x2bd2b90 "", local_shutdown_idx = 0, last_was_revoke = false, last_sent_commit = 0x1a8a270, channel = 0x0}
```

`~/.lightning/crash.log`: https://jb55.com/s/47fa62ab637ea642.txt

I wish I could be more helpful and provide reproducible steps, but I was mostly messing around. I'll try to document my steps more thoroughly next time.

**Comment by rustyrussell** [comment]
Oops, this looks like you created the db with an old version then upgraded.  We don't have db stability yet, since we haven't done a release...

**Comment by cdecker** [comment]
Thanks @jb55, that's a concerning issue you found there. Which network is this on? Testnet and regtest almost never fail due to fee levels. If this is not mainnet, would you mind sharing the database file (`.lightning/lightning.sqlite3`)?

**Comment by cdecker** [comment]
> Oops, this looks like you created the db with an old version then upgraded. We don't have db stability yet, since we haven't done a release...

That shouldn't really happen, since we explicitly mention all columns in the select-query, so not finding a field would kill the query early. This sounds more like not incrementing `col` in a skipped/null field.

**Comment by jb55** [comment]
@cdecker I was on testnet. Here's the `~/.lightning/lightning.sqlite3` https://jb55.com/s/1fe039924c4f0efb.sqlite3

**Comment by cdecker** [comment]
Ok, managed to reproduce it. We aren't incrementing when reading the `local_shutdown_idx` field. I'll fix it and add a test tomorrow.

**Comment by jb55** [comment]
That seems to have fixed the crash. I'm still having missing inputs/fees errors. Here's the sqlite db on the other node I'm attempting to connect to. I assume this should be sufficient to reproduce the issue?
 https://jb55.com/s/82c96679c695e93a.sqlite3

thanks @cdecker !

**Comment by rustyrussell** [comment]
William Casarin <notifications@github.com> writes:
> That seems to have fixed the crash. I'm still having missing inputs/fees errors. Here's the sqlite db on the other node I'm attempting to connect to. I assume this should be sufficient to reproduce the issue?
>  https://jb55.com/s/82c96679c695e93a.sqlite3

So, the errors from bitcoind are misleading.  We tend to naively spam
bitcoind with every tx we've ever wanted to broadcast.

missing inputs:
        Transaction already in blockchain.

fee error:
        Other side sent a transaction, and your tx is not high enough
        fee to RBF it.

Cheers,
Rusty.

**Comment by jb55** [comment]
> So, the errors from bitcoind are misleading.  We tend to naively spam
> bitcoind with every tx we've ever wanted to broadcast.

ah ok. I'll try again and report back.

thanks!
