### ISSUE TITLE
'getroute' documentation and error message need updating

### ISSUE THREAD

**Issue by gwillen** [ElementsProject/lightning#38]
The 'getroute' documentation and error message only mention two parameters, but it actually takes three (they were not updated when the third one was added, or else the third one is supposed to be optional and is not.)

Also the cat picture instructions need to be updated.

**Comment by gwillen** [comment]
Also the 'getroute' manpage seems to have the args in the opposite direction from the one given in the cat picture instructions, not sure which is correct....

**Comment by rustyrussell** [comment]
Thanks, both fixed.  The man page in doc/ had it correct, fortunately.
