### ISSUE TITLE
Gives "Could not find a route" code 205 right away

### ISSUE THREAD

**Issue by johnblanc** [ElementsProject/lightning#3805]
I'm trying to pay my first invoice and get "Could not find a route" immediatelly in the terminal, like it's not even looking.
Both receiver and payer are c-lightning nodes, both have channels to well connected nodes, both are connected to couple well connected nodes. Amount is few thousand satoshis so capacity is not a problem.

On the other side both c-lightning nodes involved are running on qubes OS behind Tor.

**Comment by ZmnSCPxj** [comment]
IS this the same as #3806 ?

**Comment by johnblanc** [comment]
Yes, sorry for the double!
