### ISSUE TITLE
Defaults shown in --help are wrong

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#381]
Many zeroes there:

--cltv-final <arg>             Number of blocks for final ctlv_expiry
                                (default: 0)
--max-htlc-expiry <arg>        Maximum number of blocks to accept an HTLC before
                               expiry (default: 0)
--bitcoind-poll <arg>          Time between polling for new transactions
                                (default: 0s)
--commit-time <arg>            Time after changes before sending out COMMIT
                                (default: 0s)
--fee-base <arg>               Millisatoshi minimum to charge for HTLC
                                (default: 0)
--fee-per-satoshi <arg>        Microsatoshi fee for every satoshi in HTLC
                                (default: 0)

**Comment by ZmnSCPxj** [comment]
`--help` is handled during `opt_early_parse`, so we need to somehow get default values into the `ld->config` before that call.  However, whether we are using mainnet or testnet is also handled during `opt_early_parse`.

Configuration is later overwritten in `opt_parse_from_config`, so maybe:

        /* Set up configuration for help to display default values.  */
        /* Configuration will later be overwritten by opt_parse_from_config.  */
    #if DEVELOPER
        ld->config = testnet_config;
    #else
        ld->config = mainnet_config;
    #endif
        /* Get any configdir/testnet options first. */
        opt_early_parse(argc, argv, opt_log_stderr_exit);

**Comment by rustyrussell** [comment]
Fixed by #417 

FWIW, @ZmnSCPxj you can do this automatically by putting "Fixes: #417" in your commit message.

Thanks!!

**Comment by ZmnSCPxj** [comment]
Thank you for this information.  I suppose for this specific example, it should be, "Fixes: #381"?
