### ISSUE TITLE
shutdown_scriptpubkey behavior seems to not follow the bolt

### ISSUE THREAD

**Issue by joemphilips** [ElementsProject/lightning#3815]
### Issue and Steps to Reproduce

I've been trying to open the channel with [rust-lightning](https://github.com/rust-bitcoin/rust-lightning) in regtest docker-compose.
([Here's docker-compose file if you are interested](https://github.com/joemphilips/NRustLightning/blob/payment_integration_tests/tests/NRustLightning.Server.Tests/docker-compose.yml))

When I tried to open channel from c-lightning to rust-lightning, rl returns a following error message.
```
They sent error channel 28e53e353b543cd6da141d5c6ca4d9d82f6a526d1f41b6f24e2671c095439f93: Peer is signaling upfront_shutdown but we don't get any script. Use 0-length script to opt-out
```
> note that "They" refers to c-lightning and "we" is rust-lightning.

It seems obvious from the error message that c-lightning is not setting TLV field(shutdown_scriptpubkey) in open_channel.
BOLT 02 states following, so it seems this is a bug in c-lightning.
```
* if both nodes advertised the option_upfront_shutdown_script feature:
  * MUST include upfront_shutdown_script with either a valid shutdown_scriptpubkey as required by shutdown scriptpubkey, or a zero-length shutdown_scriptpubkey (ie. 0x0000).
```

To reproduce, run following.
```
git clone --recursive https://github.com/joemphilips/NRustLightning
git checkout payment_integration_tests
cd tests/NRustLightning.Server.Tests
docker-compose build && dotnet test --filter="FullyQualifiedName~CanOpenCloseChannels"
```

### `getinfo` output
```
{
   "id": "024236460ad239baa1ad169aab65dfcc566d5e6ddfab5349d5b7fcfeb75c22a69d",
   "alias": "SOMBERBEAM-7981f4c",
   "color": "024236",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "192.168.176.5",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "192.168.176.5",
         "port": 9735
      }
   ],
   "version": "7981f4c",
   "blockheight": 442,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/root/.lightning/regtest"
}
```

I tried both in v0.8.2.1 and master. This is a response when I used master build.

**Comment by ZmnSCPxj** [comment]
Funny 'cause we quote it right here:

https://github.com/ElementsProject/lightning/blob/7981f4c4d9970e7ed9da5881d9f3ab568ccc335c/openingd/openingd.c#L525-L535

Looking at `dev_upfront_shutdown_script`: https://github.com/ElementsProject/lightning/blob/7981f4c4d9970e7ed9da5881d9f3ab568ccc335c/openingd/openingd.c#L122-L131

Oh, it returns `NULL` by default.  Which basically means "do not send the TLV" to the code.

It should probably do the feature check inside `dev_upfront_shutdown_script`, and if both agreed on the feature, return a 0-length array instead of NULL.

**Comment by joemphilips** [comment]
Closing in favor of #3816

**Comment by ZmnSCPxj** [comment]
Re-opening, since we should close only when the commit is merged into master.

**Comment by rustyrussell** [comment]
Yep, keeps us honest!  Thanks @joemphilips !
