### ISSUE TITLE
Why are invoices over-paid on direct connection payments?

### ISSUE THREAD

**Issue by d4amenace** [ElementsProject/lightning#3824]
I have 2 nodes on seperate machines and IP addresses directly connected in a channel.  When I create an invoice for say 1000000 msatoshis on the **first** node:

lightning-cli invoice 1000000 test2 secondinteriptransfer
{
   "payment_hash": "64c0fcd5c52926bb1c224056a153460393c9c466159c1be9e5e07a0d1582c59c",
   "expires_at": 1594745102,
   "bolt11": "lnbc10u1p0sff5wpp5vnq0e4w99yntk8pzgpt2z56xqwfun3rxzkwph609upaq69vzckwqdpzwdjkxmmwv35kuar9wf5hqarjv9h8xen9wgxqyjw5qcqp2sp5pua6edy7h0ejg8nuuu32j52dj6mdk2wqz9ggpmgaw32uy882akeq9qy9qsqttzam9h8jkhell022j62auqtgs0x76twfcw89gaep6uq2qklcuskzsvxlpxrtfzfmm7cr7ym8xaaxwvkw4jeasnsqu29mpk5fdceafcpywrgyl",
   "warning_deadends": "No channel with a peer that is not a dead end"
}

And submit payment on the **second** node:

lightning-cli pay lnbc10u1p0sff5wpp5vnq0e4w99yntk8pzgpt2z56xqwfun3rxzkwph609upaq69vzckwqdpzwdjkxmmwv35kuar9wf5hqarjv9h8xen9wgxqyjw5qcqp2sp5pua6edy7h0ejg8nuuu32j52dj6mdk2wqz9ggpmgaw32uy882akeq9qy9qsqttzam9h8jkhell022j62auqtgs0x76twfcw89gaep6uq2qklcuskzsvxlpxrtfzfmm7cr7ym8xaaxwvkw4jeasnsqu29mpk5fdceafcpywrgyl
{
   "id": 5,
   "payment_hash": "64c0fcd5c52926bb1c224056a153460393c9c466159c1be9e5e07a0d1582c59c",
   "destination": "02b04bbf6ef6b629521a6140ef61ab2b6640c290f83aeccaf6260fe195cd687768",
   "msatoshi": 1002020,
   "amount_msat": "1002020msat",
   "msatoshi_sent": 1002020,
   "amount_sent_msat": "1002020msat",
   "created_at": 1594140362,
   "status": "complete",
   "payment_preimage": "c6a3618c2e836867abdd72d9794aaf751a429336cad1317a88dae3465214edc2",
   "bolt11": "lnbc10u1p0sff5wpp5vnq0e4w99yntk8pzgpt2z56xqwfun3rxzkwph609upaq69vzckwqdpzwdjkxmmwv35kuar9wf5hqarjv9h8xen9wgxqyjw5qcqp2sp5pua6edy7h0ejg8nuuu32j52dj6mdk2wqz9ggpmgaw32uy882akeq9qy9qsqttzam9h8jkhell022j62auqtgs0x76twfcw89gaep6uq2qklcuskzsvxlpxrtfzfmm7cr7ym8xaaxwvkw4jeasnsqu29mpk5fdceafcpywrgyl"
}

.....the node fulfills the invoice but **_OVERPAYS_** for some reason.   The only channel that the 2 nodes have is with each other.

_I should note that both nodes use the same bitcoin backend.  One is directly connected to it locally and the other is remotely connected to it....if that matters at all...._

**Comment by d4amenace** [comment]
Info from the receiving node:

lightning-cli listinvoices
{
   "invoices": [
      {
         "label": "test1",
         "bolt11": "lnbc10u1p0sffy3pp5kff2tjkzrglg6chd75q3mrcz5vmszj7l5ezkwyt8hkuy45r2pxvqdpqve5hyum5d9h8getjd9c8gunpdeekvetjxqyjw5qcqp2sp58wya2wa0st9j947vqvzgc3sje0n8472ksv03stkeszl4tskpakzq9qy9qsq0am5estmrv0pysufknrmdd7nq4j3remd7sz97p08hl6ppvkpkchzaftdmtc5yagyaqa5tea9lu47dqjr4dmrhlzu75hnj7rnj34ftfgpvna3sk",
         "payment_hash": "b252a5cac21a3e8d62edf5011d8f02a337014bdfa645671167bdb84ad06a0998",
         "msatoshi": 1000000,
         "amount_msat": "1000000msat",
         "status": "paid",
         "pay_index": 1,
         "msatoshi_received": 1004040,
         "amount_received_msat": "1004040msat",
         "paid_at": 1594140213,
         "payment_preimage": "d87e7105c5a37eae66ad740d837efcf1716dcd7a96e250660d74c8df8d4e05a1",
         "description": "firstinteriptransfer",
         "expires_at": 1594744593
      },
      {
         "label": "test2",
         "bolt11": "lnbc10u1p0sff5wpp5vnq0e4w99yntk8pzgpt2z56xqwfun3rxzkwph609upaq69vzckwqdpzwdjkxmmwv35kuar9wf5hqarjv9h8xen9wgxqyjw5qcqp2sp5pua6edy7h0ejg8nuuu32j52dj6mdk2wqz9ggpmgaw32uy882akeq9qy9qsqttzam9h8jkhell022j62auqtgs0x76twfcw89gaep6uq2qklcuskzsvxlpxrtfzfmm7cr7ym8xaaxwvkw4jeasnsqu29mpk5fdceafcpywrgyl",
         "payment_hash": "64c0fcd5c52926bb1c224056a153460393c9c466159c1be9e5e07a0d1582c59c",
         "msatoshi": 1000000,
         "amount_msat": "1000000msat",
         "status": "paid",
         "pay_index": 2,
         "msatoshi_received": 1002020,
         "amount_received_msat": "1002020msat",
         "paid_at": 1594140363,
         "payment_preimage": "c6a3618c2e836867abdd72d9794aaf751a429336cad1317a88dae3465214edc2",
         "description": "secondinteriptransfer",
         "expires_at": 1594745102
      }
   ]
}

**Comment by ZmnSCPxj** [comment]
First, let me describe *why* we overpay, whether distant or adjacent.

By overpaying, we make it harder for a forwarding node to guess the distance to the actual payee.  If we paid exact amount, then any forwarding node can make a good guess of how many hops, and possibly which hops, you are using to pay the destination, leaking your privacy.

On the other hand, how about *direct* payments?  There is no forwarding node, true, but you might not want the payee to know that the customer is a *direct* node: you might want to pretend that you are forwarding for somebody else.

Thus, we default to always having a chance to overpay.

Note that the overpayment will never exceed your `maxfeepercent`.

**Comment by d4amenace** [comment]
Thanks for that explanation.  A guess as to why my channel receivable would be less than the channel itself?

**Comment by ZmnSCPxj** [comment]
`msaatoshi_total` is 73000000, and `msatoshi_to_us` is  2006060. Then there is the reserve, `their_reserve_msat` is 730000, this value cannot be sent.  This leaves 70263940.  But from this capacity, we have an *additional* reserve, which is the **onchain** feerate for closing the channel unilaterally.  Thus, you only have 53566940 receivable, because 16697000 is *additionally* reserved for fees (the stat is not shown anywhere, you have to "just know" about it).
