### ISSUE TITLE
No "install" target in Makefile.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#383]

**Comment by ZmnSCPxj** [comment]
I would like to try doing this if you are amenable to converting the build system to autotools (that is, if it is okay to you, I will convert the build system to autoconf+automake, which will get `make install` "for free").

Is there any particular reason you started with GNU make?

**Comment by rustyrussell** [comment]
"ZmnSCPxj, ZmnSCPxj jxPCSmnZ" <notifications@github.com> writes:
> I would like to try doing this if you are amenable to converting the build system to autotools (that is, if it is okay to you, I will convert the build system to autoconf+automake, which will get `make install` "for free").
>
> Is there any particular reason you started with GNU make?

autotools will not lead to happiness.  It makes the code portable, not
ported :) It's also horrible at building makefiles, when the code spans
multiple directories (recursive make is evil).

In the longer run, I'd like to only use the external/ libraries only
when necessary.  But getting autotools to checkout and build the
submodules is pretty dark magic last I looked :(

It's genuinely easier to write ./configure in shell or python, and
use simple non-recursive Makefiles.  And there are more people who can
write all these languages than can weave M4.

Cheers,
Rusty.

**Comment by ZmnSCPxj** [comment]
I understand. In any case, would you mind if I take this?  I have started on adding an "install" target for Makefile, targeting GNU Make.

**Comment by ZmnSCPxj** [comment]
>autotools will not lead to happiness. It makes the code portable, not ported :) It's also horrible at building makefiles, when the code spans multiple directories (recursive make is evil).

I have not encountered problems with my own personal projects spanning multiple directories, with a single Makefile.am at the root, and have been quite happy myself with autotools as the default build tool I use.  Still, this is your project and I can respect your decision, and can work with GNU Make to add the "install" target (and presumably "uninstall", which autotools does not support).

An issue, is that technically, the subdaemons lightning_hsmd etc should be in $(libexecdir), as they are not part of the "user-facing" executables that are intended for the user to directly run, but lightningd itself expects its subdaemons to be in the same directory as itself.  For now I am installing $(ALL_PROGRAMS) into $(bindir), although it includes some programs that seem to be part of ccan, and I am uncertain, if they should be installed.

I will try to get something reviewable by this weekend, but if you think you can do this quicker, tell me and I shall try to pick some other issue instead.

**Comment by rustyrussell** [comment]
"ZmnSCPxj, ZmnSCPxj jxPCSmnZ" <notifications@github.com> writes:
>>autotools will not lead to happiness. It makes the code portable, not ported :) It's also horrible at building makefiles, when the code spans multiple directories (recursive make is evil).
>
> I have not encountered problems with my own personal projects spanning multiple directories, with a single Makefile.am at the root, and have been quite happy myself with autotools as the default build tool I use.  Still, this is your project and I can respect your decision, and can work with GNU Make to add the "install" target (and presumably "uninstall", which autotools does not support).
>
> An issue, is that technically, the subdaemons lightning_hsmd etc should be in $(libexecdir), as they are not part of the "user-facing" executables that are intended for the user to directly run, but lightningd itself expects its subdaemons to be in the same directory as itself.  For now I am installing $(ALL_PROGRAMS) into $(bindir), although it includes some programs that seem to be part of ccan, and I am uncertain, if they should be installed.
>
> I will try to get something reviewable by this weekend, but if you think you can do this quicker, tell me and I shall try to pick some other issue instead.

Delighted for the help!

Yes, libexecdir is the correct place.  Note that lightningd currently
looks in its own directory only; this behaviour is very convenient for
pre-install testing, but adding a fallback to a hardcoded execdir would
work.

Thanks!
Rusty.

**Comment by ZmnSCPxj** [comment]
Should I make a separate issue for the "lightningd also looks in ../libexec/ if it cannot find its subdaemons beside it" or should I add it to https://github.com/ElementsProject/lightning/pull/404 ?

(I would prefer to put the "correctly use libexec" in a separate issue following on this issue, but of course, it would be preferred, to install everything correctly in the first place)

**Comment by rustyrussell** [comment]
"ZmnSCPxj, ZmnSCPxj jxPCSmnZ" <notifications@github.com> writes:
> Should I make a separate issue for the "lightningd also looks in ../libexec/ if it cannot find its subdaemons beside it" or should I add it to https://github.com/ElementsProject/lightning/pull/404 ?
>
> (I would prefer to put the "correctly use libexec" in a separate issue following on this issue, but of course, it would be preferred, to install everything correctly in the first place)

I'd make an issue, even if you fix it in one of the commits in the
series on the way to something else.

We don't need to be insanely finegrained about stuff, at least for now.

Cheers,
Rusty.

**Comment by ZmnSCPxj** [comment]
I prefer to keep things small as I may suddenly disappear for no reason. So it is best, if I can complete the entire needs for an issue, in one or two coding sessions.
