### ISSUE TITLE
attempted to pay large mpp, another crash

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3848]
```
pay: FATAL SIGNAL 11 (version v0.9.0rc1-10-g65ca634)
0x417e1a send_backtrace
        common/daemon.c:38
0x417ea4 crashdump
        common/daemon.c:51
0x7ff39faa94af ???
        ???:0
0x7ff39fb37071 ???
        ???:0
0x7ff39fb390a5 ???
        ???:0
0x403eb6 utc_timestring
        plugins/pay.c:1392
0x40601b paystatus_add_payment
        plugins/pay.c:1510
0x4060d9 paystatus_add_payment
        plugins/pay.c:1535
0x4060d9 paystatus_add_payment
        plugins/pay.c:1535
0x406b6f json_paystatus
        plugins/pay.c:1612
0x409abe ld_command_handle
        plugins/libplugin.c:1054
0x409b85 ld_read_json_one
        plugins/libplugin.c:1097
0x409c14 ld_read_json
        plugins/libplugin.c:1116
0x426ccd next_plan
        ccan/ccan/io/io.c:59
0x42718d do_plan
        ccan/ccan/io/io.c:407
0x4271b8 io_ready
        ccan/ccan/io/io.c:417
0x428953 io_loop
        ccan/ccan/io/poll.c:445
0x409d96 plugin_main
        plugins/libplugin.c:1284
0x407086 main
        plugins/pay.c:2010
0x7ff39fa9482f ???
        ???:0
0x402e08 ???
        ???:0
0xffffffffffffffff ???
        ???:0
2020-07-18T12:01:38.900Z INFO plugin-pay: Killing plugin: Plugin exited before completing handshake.
```

I have a few of these:
2020-07-18T11:59:43.883Z UNUSUAL plugin-pay: Unable to parse `waitsendpay` result: {\"code\":209,\"message\":\"Payment failure reason unknown\"}
and a lot of errors, warnings, etc.

**Comment by cdecker** [comment]
> 2020-07-18T11:59:43.883Z UNUSUAL plugin-pay: Unable to parse `waitsendpay` result: {"code":209,"message":"Payment failure reason unknown"}

That was the reason for your previous report, we now no longer fail, instead just retry. It might happen a couple of times in a row because we can't locate the failing node/channel and exclude it.

The crash seems to happen in `paystatus`, I'll look into it :+1:

**Comment by cdecker** [comment]
Found the issue, we're not always setting the completion time. See #3849 for a fix.

Could you share some more logs? I'm wondering how come the reason is unknown, since it should be able to decode the error onion correctly. Could this be a node along the route that keeps mangling the routing onion somehow? If yes, that'd be an interesting case to study, and reproduce for future tests.
