### ISSUE TITLE
Fail to withdraw funds

### ISSUE THREAD

**Issue by onvej** [ElementsProject/lightning#385]
Hello,

I'm unable to withdraw funds received via a channel. I funded a channel between two nodes in a regtest, created and paid an invoice and successfully closed the channel.

Now I'm in the state:
```
  "peers": [ {
      "state": "ONCHAIND_MUTUAL",
      "netaddr": [],
      "peerid": "0306249dedc09e9c1926b143a42543118737070b6c05e3c52055a5f97679b3eed8",
      "connected": false,
      "channel": "1001:2:0",
      "msatoshi_to_us": 1000000000,
      "msatoshi_total": 10000000000
    }  ]
```
However, withdrawal of 1 satoshi ends up with an error:
`"Not enough funds available"`

I'm not sure whether it is a bug or I'm doing something wrong. Thank you for you help.

**Comment by cdecker** [comment]
That is correct, withdraw only works for funds that are not allocated to a channel, i.e., only funds that are returned by the `lightning-cli listfunds` query. In your case the channel has to be closed before you get sole control over the funds again, at which point you'll be able to withdraw them again.

**Comment by onvej** [comment]
Actually I closed the channel with the `lightning-cli close` query. I thought that the state ONCHAIND_MUTUAL means that the channel is closed and the funds are released. What is proper way to close the channel and withdraw the money?

**Comment by cdecker** [comment]
Oh I see, we aren't checking for funds coming in through blocks just yet ( #379  will fix that). For now try figuring out which transaction closed the channel and call `addfunds` with that.

**Comment by onvej** [comment]
Excellent, thank you for your help.

**Comment by cdecker** [comment]
Thank you for pointing out this issue ^^

**Comment by ZmnSCPxj** [comment]
As https://github.com/ElementsProject/lightning/pull/379 has been merged, has this issue been fixed?

**Comment by onvej** [comment]
I don't think so. I'm still having the same problem.

**Comment by cdecker** [comment]
Ok, I think I see where this fails. We're not yet checking for native P2WPKH outputs, so we need to add these as well.
