### ISSUE TITLE
JSON parse chokes on escaped quotes in strings

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#387]
The JSON parser is apparently not doing a good job at escaping strings:
```
lightningd(17291): Invalid token in json input: '{"method":"invoice","params":["603777911","Um3AE6UKOh5dk3aGQEg64","Lightning Shop: <span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>60.05</span> for 7 Pizza, 5 Guitar and 6 Cat",null],"id":10}'
```

Reported-by: @shesek

**Comment by rustyrussell** [comment]
It's deliberately preventing strings which have weird chars in them, such as escapes.

Now, we *could* hoist the strange_chars() check into the callers, and add a '*' prefix (or something) to json_get_params to say a parameter *may* be escaped, then use that for the invoice description, then provide a santize_json_string() helper to un-escape it as required.

But in this case, it looks like we caught a bug in the caller?  Putting HTML fields in the description is making assumptions about the clients (wallets) that I don't think are reasonable.

**Comment by shesek** [comment]
@rustyrussell you're right, the HTML was indeed a bug and shouldn't have been there (WooCommerce was returning the price in that format, I since fixed that), but this is still valid JSON. There might be a legitimate reason to have `"` or `\` inside the description field.

Can't c-lightning integrate a fully spec-compliant JSON parser library to handle that?

**Comment by rustyrussell** [comment]
Nadav Ivgi <notifications@github.com> writes:
> @rustyrussell you're right, the HTML was indeed a bug and shouldn't have been there (WooCommerce was returning the price in that format, I since fixed that), but this is still valid JSON. There might be a legitimate reason to have `"` or `\` inside the description field.
>
> Can't c-lightning integrate a fully spec-compliant JSON parser library to handle that?

Well, our parser is fully spec compliant.  I chose not to do full spec
compiance in our output originally, but rather refuse to pass through
anything weird.

That seemed safer if *other* users have JSON escape issues.  Thus the
few places where we take strings, I forbade it.

However, I agree; we should simply re-escape it when we output strings.

Hence this PR is left open...
