### ISSUE TITLE
Unable to connect from lnd 0.10.3

### ISSUE THREAD

**Issue by got3nks** [ElementsProject/lightning#3896]
We updated our node to version **v0.9.0-2-ge7d89cd** today and we got a report of a lnd 0.10.3 node being unable to connect to our node:

`[lncli] rpc error: code = Unknown desc = socks connect tcp 127.0.0.1:9050->x.x.x.x:9735: unknown error general SOCKS server failure`

Is there any compatibility issue?

**Comment by ZmnSCPxj** [comment]
SOCKS means the lnd node is trying to use a proxy.  It says `12.0.0.1:9050`, which usually means Tor.  Is your Tor up?  Note that a general SOCKS server failure is very very general and might mean that Tor is getting DDoSsed, or that your exit node somehow does not like the destination IP, or the exit node has run out of bandwidth or is under attack, or any of a number of issues.  If it is a SOCKS server failure it seems unlikely to be a compatiblity problem at the Lightning layer, try checking if restarting Tor helps.
