### ISSUE TITLE
Connect without address hint doesn't return

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#390]
The JSON-RPC call to `connect` without an address hint may fail because we don't know an address, but it currently does not return a JSON-RPC error, it just hangs there.

**Comment by cdecker** [comment]
Notice that this also happens when the remote peer is unreachable, we just continually attempt to connect but never return. IMHO we should just try for 1 minute and then give up.

**Comment by RvMp** [comment]
I would like to suggest to make it an option so people can decide how long they want to wait on connects. That way you can choose to only connect with nodes nearby (low latency). 

Strange example by the way:

```
* 037e086d4985902954ffb8f2e985d604988a1a971409ca3adda1ea99b9adc94a9a 139.162.249.85:10012 ipv4
```

```
lightning@dawson:~$ nc -zv 139.162.249.85 10012 
Connection to 139.162.249.85 10012 port [tcp/*] succeeded!
```

The port seems to be open but no response at all when trying to connect with lightning-cli connect
