### ISSUE TITLE
unable to build from source / missing external code?

### ISSUE THREAD

**Issue by minidisk1147** [ElementsProject/lightning#3900]
### Issue and Steps to Reproduce

- Download & unpack https://github.com/ElementsProject/lightning/archive/v0.9.0.tar.gz
- Try to ./configure ; make

Output:
```
[...]
cd external/libwally-core && ./tools/autogen.sh
/bin/sh: ./tools/autogen.sh: not found
gmake: *** [external/Makefile:71: external/x86_64-unknown-freebsd12.1/libwally-core-build/src/libwallycore.la] Error 127
[...]
```

### Workaround
Using "git clone" and "git checkout tags/v0.9.0" as source works :-)

**Comment by vincenzopalazzo** [comment]
I think that this issue is a duplicate.

Same error here https://github.com/ElementsProject/lightning/issues/3154

Fixed with 

>Workaround
Using "git clone" and "git checkout tags/v0.9.0" as source works :-)

**Comment by ZmnSCPxj** [comment]
That tarball is broken (this holds for all releases, incidentally --- do ***not*** get the "Source Code" tarball/zip).

The "real" source code tarball is: https://github.com/ElementsProject/lightning/releases/download/v0.9.0/clightning-v0.9.0.zip

Always use the "clightning-v\<release\>.zip` link, not the "Source code" links that are just `v\<release\>.zip` / `v\<release\>.tar.gz`

My understanding is that the "source code" archives are automatically added by github with no assurance those archives would work.

**Comment by minidisk1147** [comment]
Learned not to use github autogenerated tarballs, will read release notes instead.

**Comment by whileunless** [comment]
```
cd external/libwally-core && ./tools/autogen.sh
/bin/sh: 1: ./tools/autogen.sh: not found
make: *** [external/Makefile:83: external/build-x86_64-linux-gnu/libwally-core-build/src/libwallycore.la] Error 127
```
I'm having the same error with the tarball of the release 23.11.2
