### ISSUE TITLE
keysend payments show up in listpays with the bolt11 field set to the string "(null)"

### ISSUE THREAD

**Issue by shesek** [ElementsProject/lightning#3921]
```
{
   "pays": [
      {
         "bolt11": "(null)",
         "status": "complete",
         "preimage": "ac73f925be48cebeb1e3f6c7662a05caec1688680842594f1275ce5ece8fede3",
         "amount_msat": "500msat",
         "amount_sent_msat": "500msat"
      }
   ]
}
```

This trips up spark, which attempts to parse it and fails. (https://github.com/shesek/spark-wallet/issues/151)

**Comment by vincenzopalazzo** [comment]
Fiexd [here](https://github.com/ElementsProject/lightning/pull/3888)

Now the listpays return the destination value when the payment is made with keysend and return a bolt11 when the payment is made with pay plugin. In addition, the response contains the pyments_hash in both cases

**Comment by ZmnSCPxj** [comment]
Since `keysend` does not involve a BOLT11 invoice, there is nothing we can print in a `bolt11` field anyway.  Even the "fix" just involves not including a `bolt11` field, and if spark cannot handle the nonexistence of the `bolt11` field it would still crash.

**Comment by shesek** [comment]
@ZmnSCPxj I filed this issue to report that the `bolt11` field is returned as a `"(null)"` string instead of an actual `null`, not to have it included. Spark does ignore `listpays` entries with no bolt11 field, it was just getting confused by the `"(null)"` string value (the [fix](https://github.com/shesek/spark-wallet/commit/3eda345d17bb6a2881f2b121c005a9fef618424e) in was to treat these null strings the same as having no field at all).

@vincenzopalazzo Thanks! The addition of destination and payment_hash are pretty useful too. (I'm currently hashing the preimage to arrive at the payment_hash, would be nice if I didn't have to)

**Comment by ZmnSCPxj** [comment]
As mentioned #3888 should have fixed this, @shesek can you confirm?

**Comment by cdecker** [comment]
fwiw, I'm in the process of releasing a hotfix release that includes #3888, #3908 and #3909, which I'm sorry @shesek had to work around temporarily, my bad :frowning_face:

**Comment by shesek** [comment]
Can confirm, #3888 fixed this.
