### ISSUE TITLE
Funding channel with complete UTXO(s) from external wallet

### ISSUE THREAD

**Issue by kristapsk** [ElementsProject/lightning#3922]
Currently I can do `lightning-cli fundchannel XXX all` to spend all UTXO's from c-lightning internal wallet and then open a channel. Or I can specify UTXO's from internal wallet there as additional parameter.

It would be cool if I would be able to do the same easy way when funding a channel from external wallet using `fundchannel_start`. I could specify `all` as amount, some feerate and then specify UTXO's from an external wallet.

Right now I either need to do manual calculations with tx size in vbytes, feerate, etc, to get amount or I must first deposit funds into c-lightning internal wallet first which is unnecessary extra transaction.

Reason is privacy, sometimes I want to spend whole UTXO instead of having additional change output.

**Comment by ZmnSCPxj** [comment]
Since C-lightning is not aware of just *what* external wallet you are using, this is out-of-scope.

A plugin can be written that interacts with a specific external wallet to do fee calculations etc.  That is the entire point of the plugin system.

**Comment by kristapsk** [comment]
Idea was that you specify UTXO(s) and feerate, so it does not matter what kind of wallet you are using. But now I remembered about possibility of larger scripts than simple single sig in case of P2SH (like Blockstream Green), c-lightning can't know anything about that.

**Comment by ZmnSCPxj** [comment]
Correct, that is why you need to write specific code for a specific wallet anyway..  A wallet with PSBT support, for example, can do this perfectly fine, and should probably be able to do the fee estimation itself, etc., for the inputs it supports.  Internally, for example, our "internal" wallet is, as far as the `fundchannel` is concerned, "just" an external walle.  So you are better off taking advantage of C-lightning plugins and standard PSBT support in the external wallet you support to create a `fundchannel_electrum`, `fundchannel_greenwallet`, etc. command specific to the external wallet, which queries the external wallet using whatever APIs it supports.

`fundchannel_start` et al are powerful enough.
