### ISSUE TITLE
Left a lightning-cli close XXX command to run for 3 hours, but it didn't execute.

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3925]
I'm running latest git version.
Today i've closed 2 channels successfully:
`   "type": "mutual"
`
but the third one didn't execute, for whatever reason (I'm guessing node is offline). I left it running for 3 hours, and then i hit Ctrl+C. Is this normal? If so, there should probably be a timeout for this or some output generated, such as cannot reach node.

**Comment by ZmnSCPxj** [comment]
This is normal.  The default `unilateraltimeout` is 24 hours, for some reason.  This means `close` will suspend for 24 hours waiting for the node to come online in hope of negotiating a mutual close, after which it will just drop the channel onchain unilaterally (and unilateral closes will have an additional delay as well after they close before you can use the money, depending on the other node `to_self_delay` setting, which can go as high as two weeks for `lnd` defaults IIRC)..

Note that `^C` on `lightning-cli` will **not** cancel the closure: the channel ***will*** be closed, it is just a matter of waiting it out.  It might be possible to do something like `close XXX 1` to make it unilaterally close in 1 second (it is not possible to unilaterally close in 0 seconds, for some reason).

**Comment by thestick613** [comment]
That's nice, but some descriptive output from these commands would be really helpful!

**Comment by ZmnSCPxj** [comment]
Unfortunately due to how `lightning-cli` works we can only provide output at the end of the command.

**Comment by rustyrussell** [comment]
... we could abuse notifications to do this, however.
