### ISSUE TITLE
docs missing

### ISSUE THREAD

**Issue by Fonta1n3** [ElementsProject/lightning#3933]
I can not find any info on `listtransactions` other then the minimal output of `lightning-cli help listtransactions`, is there any docs anywhere? I do not see the command [here](https://lightning.readthedocs.io) or [here](https://github.com/ElementsProject/lightning/tree/master/doc).

**Comment by vincenzopalazzo** [comment]
Mh! I think there is something missing. If I know all I think all docs around about c-lightning use the description inside the doc directory of this repository.

**Comment by ZmnSCPxj** [comment]
Yes, some docs are missing.

* [ ] `listtransactions`
* [ ] `listnodes`
* [ ] `signpsbt`
* [ ] `sendpsbt`

The above is probably not an exhaustive list.

**Comment by vincenzopalazzo** [comment]
Can you assign to me this task? @ZmnSCPxj  :)

**Comment by vincenzopalazzo** [comment]
@ZmnSCPxj This is the complete list of the commands without docs

```json
{
   "path-doc": "/home/vincent/Github/lightning/doc",
   "commands": [
      "getinfo",
      "getlog",
      "help",
      "listconfigs",
      "listnodes",
      "listtransactions",
      "ping",
      "sendpsbt",
      "signpsbt",
      "stop"
   ]
}
```

**Comment by ZmnSCPxj** [comment]
Updated the list.

**Comment by rustyrussell** [comment]
This is now fixed, thanks to @vincenzopalazzo !
