### ISSUE TITLE
PostgreSQL requirements - Unable to find DB driver for postgres

### ISSUE THREAD

**Issue by martinbehrens** [ElementsProject/lightning#3937]
### Issue ###

lightningd fails with `Unable to find DB driver for postgres://user:pw@fqdn:5432/{dbname}` when trying to connect to a remote sql db.

What is required to satisfy lightningd in this case? Which psql version is required, recommended, tested? What is required to make it work with psql12?

### Environment ###
- OS:
```
CentOS Linux release 8.2.2004 (Core)
Linux 4.18.0-193.14.2.el8_2.x86_64
```
- Psql packages installed:
```
postgresql12-12.3-5PGDG.rhel8.x86_64
postgresql12-odbc-12.02.0000-1PGDG.rhel8.x86_64
postgresql12-libs-12.3-5PGDG.rhel8.x86_64
postgresql12-devel-12.3-5PGDG.rhel8.x86_64
```
- PATH:
```
[user@host]$ env
PATH=/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
[user@host]$ whereis psql
psql: /usr/bin/psql /usr/local/bin/psql /usr/share/man/man1/psql.1
[user@host]$ whereis lightningd
lightningd: /usr/local/bin/lightningd
```
### Steps to Reproduce

1. Clone, compile and install the project
2. Create a c-lightning config file with a `wallet=postgres://user:pw@fqdn:5432/{dbname}` string pointing to a remote database endpoint.
3. Install PostgreSQL12 with:
```
yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm -y
dnf -qy module disable postgresql
yum install postgresql12 postgresql12-libs postgresql12-devel postgresql12-odbc -y
```
4. Execute `/usr/local/bin/lightningd` and observe the error thrown:

`Unable to find DB driver for postgres://user:pw@fqdn:5432/{dbname}`

**Comment by cdecker** [comment]
Am I correct that the order was the following:

1. Compile c-lightning from the source
2. Install the postgresql libraries (including the development headers and libraries)

In that case it seems like the build has looked for the postgresql development headers when calling `./configure`, didn't find them and excluded the driver from being built. Could you try recompiling (including the `./configure` call before `make`) and see if it picks up the postgresql libraries when they are installed first?

**Comment by martinbehrens** [comment]
You are correct and thanks for picking this one up. I tried to reconfigure and recompile already. This is the full list of psql related packages installed ...
```
postgresql12-12.3-5PGDG.rhel8.x86_64
postgresql12-odbc-12.02.0000-1PGDG.rhel8.x86_64
postgresql12-libs-12.3-5PGDG.rhel8.x86_64
postgresql12-devel-12.3-5PGDG.rhel8.x86_64
libpqxx-devel-7.1.2-1.rhel8.x86_64
libpqxx-7.1.2-1.rhel8.x86_64
libpq5-12.3-10PGDG.rhel8.x86_64
```
while package postgresql12-devel.x86_64 contains development header files and libraries.

Now, executing a `make clean && ./configure --enable-developer && make` plus `make install` unfortunately nothing changes. Most most most likely due to `checking for postgres... no` while configuring. It seems configure doesn't pick up the libraries installed.

**Comment by fiatjaf** [comment]
You may have a library in `/usr/include/libpq-fe.h` but you need it on `/usr/include/postgresql/libpq-fe.h` (because for some reason c-lightning expects it to be imported with `#include  <postgresql/libpq-fe.h>`).

This should fix it:
```
sudo ln -s /usr/include/libpq-fe.h /usr/include/postgresql/libpq-fe.h
```

**Comment by martinbehrens** [comment]
> You may have a library in `/usr/include/libpq-fe.h` but you need it on `/usr/include/postgresql/libpq-fe.h` (because for some reason c-lightning expects it to be imported with `#include <postgresql/libpq-fe.h>`).
> 
> This should fix it:
> 
> ```
> sudo ln -s /usr/include/libpq-fe.h /usr/include/postgresql/libpq-fe.h
> ```

Nop, but a `sudo mkdir -p /usr/include/postgresql && sudo ln -s /usr/pgsql-12/include/libpq-fe.h /usr/include/postgresql/libpq-fe.h` did, so thanks @fiatjaf and @cdecker ! ;)

**Comment by cdecker** [comment]
Hurray for portable include paths. @fiatjaf any idea how we can make sure we pick the right inclusion path, independently of the distribution? Sounds a bit like a job for yet another ./configure` check that changes the inclusion path.

**Comment by fiatjaf** [comment]
Oops, sorry, I don't understand these library/C things at all! I found this workaround for me by just experimenting and fiddling around.

Now I realize that by revealing the path in which my `libpq-fe.h` was I gave a hint on which OS I'm using, terrible OPSEC :sleepy:.

**Comment by cdecker** [comment]
Ok, looks like we should just add a `./configure` step that locates the header files out of a list of possible locations and adds it to the include paths. Does that make sense @rustyrussell or is there a more elegant way of doing this?

**Comment by cdecker** [comment]
Found one more nugget: the official [docs] mention the `pq_config` tool which can be used to find the path:

```
$ pg_config --includedir
/usr/local/include
```

I'll try to get that working in the `configure` script.

[docs]: https://www.postgresql.org/docs/9.2/libpq-build.html

**Comment by martinbehrens** [comment]
Works but may have a catch: In my Centos 7 and 8 instances `/usr/pgsql-12/bin/` (where pg_config resides) is not in PATH per default, so `configure` picked up the location only after I manually exported it.

**Comment by lightningorb** [comment]
+1 on Ubuntu 22.04, happening with postgresql 12 and 14. Followed all the steps from the [backup](https://github.com/ElementsProject/lightning/blob/master/doc/BACKUP.md#postgresql-cluster) guide (bear in mind the [guide by @gabridome](https://github.com/gabridome/docs/blob/master/c-lightning_with_postgresql_reliability.md) link is broken).

```
uname -a
```

```
Linux 5.15.0-46-generic #49-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
```

Basically for psql:

```python
@task
def install(c):
    c.sudo("sudo apt install postgresql postgresql-client -y")
    if "active" not in c.run("systemctl status postgresql.service ").stdout:
        print("Installation failed")
        return
```

and for CLN

```python
@task
def install(c, version: str = "v0.11.2"):
    """
    Install cln, and configure it with systemd.
    """
    c.sudo("apt-get install -y build-essential")

    c.sudo("sudo apt-get update")
    c.sudo(
        "sudo apt-get install -y autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev python3 python3-pip net-tools zlib1g-dev libsodium-dev gettext libpq-dev"
    )
    if c.run("pg_config --includedir", warn=True).failed:
        print("Postgres not properly installed")
        return
    c.sudo("pip3 install --upgrade pip")
    c.sudo("pip3 install --user poetry")
    c.sudo("pip3 install --upgrade pip")
    c.sudo("pip3 install mako mistune==0.8.4 mrkd")

    c.sudo("rm -rf lightning")
    if c.run("test -d lightning", warn=True).failed:
        c.run("git clone https://github.com/ElementsProject/lightning.git")
    with c.cd("lightning"):
        c.run(f"git checkout {version}")
        c.run("./configure")
        if not c.run("grep 'HAVE_POSTGRES' config.vars").stdout.strip():
            print("Postgres not detected by configure script")
            return
        c.run("make")
        c.run("sudo make install")
    if c.run("test -d /etc/systemd/system/lightning.service", warn=True).failed:
        c.put(get_conf_file_path("lightning.service"), "/tmp/lightning.service")
        c.sudo("mv /tmp/lightning.service /etc/systemd/system/lightning.service")
    c.sudo("systemctl enable lightning")
```
