### ISSUE TITLE
fundpsbt should add fee output for elements tx

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/lightning#3940]
`fundpsbt` should add (or merge, as required) a fee output for elements txs -- it's required for validation and sending.

**Comment by ZmnSCPxj** [comment]
It would not be able to know the fees of the outputs that will be added later.

See this alternative API I proposed: https://github.com/ElementsProject/lightning/pull/3838#issuecomment-659773174

With the latter API, we can determine the fees for the outputs as well as the fee output.

**Comment by cdecker** [comment]
It doesn't really have to know the fees that any later addition of inputs would result in, as long as each external tool adds or subtracts their fees to the existing fee output. I like the idea of having the psbt representation be as consistent as possible at all times.

**Comment by ZmnSCPxj** [comment]
But it *does* have to know the fees of additional **outputs**, because it has to *allocate* inputs that can cover those fees as well.

**Comment by niftynei** [comment]
supersumed by #3998
