### ISSUE TITLE
onchaind didn't recognize own unilateral close output

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#395]
Can't figure out what this tx is (damn P2WSH outputs).  Attaching here for future analysis.

[lightningd-fail.zip](https://github.com/ElementsProject/lightning/files/1521398/lightningd-fail.zip)

**Comment by cdecker** [comment]
Was the node restarted? We might have forgotten that we are interested in the tx, and not passed it on from the `chaintopology`.

**Comment by rustyrussell** [comment]
No, it's all a continuous log.
