### ISSUE TITLE
keysend only working with other c-lightning nodes

### ISSUE THREAD

**Issue by Fonta1n3** [ElementsProject/lightning#3968]
I have been testing `keysend` and it quite reliably only seems to work with other c-lightning nodes.

This recipient for example has keysend enabled and is able to send me keysends but I am unable to return the favor and generally get an error:

```
error =     {
        "amount_msat" = 1000msat;
        "amount_sent_msat" = 0msat;
        code = 203;
        "created_at" = 1598181774;
        destination = 02f7dcc28e15c0b55238a0f7db02b2082b1c2fa5adf66ff96e79db8f7ae17fe7d3;
        "erring_index" = 4;
        "erring_node" = 02f7dcc28e15c0b55238a0f7db02b2082b1c2fa5adf66ff96e79db8f7ae17fe7d3;
        failcode = 16399;
        failcodename = "WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS";
        id = 343;
        message = "failed: WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS (reply from remote)";
        msatoshi = 1000;
        "msatoshi_sent" = 0;
        "payment_hash" = 1887be8ddb26b3336494899f0a58d068f4343ba4160c38d05ee28986426744ca;
        "raw_message" = 400f00000000000003e80009d777;
        status = pending;
    }
```

**Comment by rustyrussell** [comment]
Hmm.  Keysend is undocumented, so perhaps we implemented it wrong? @cdecker

**Comment by cdecker** [comment]
Indeed there is no official specification for keysend, so I had to reverse engineer it. It was working for a while, but I can't guarantee it hasn't changed on the lnd side. I'll see what I can do 👍

**Comment by d4amenace** [comment]
Don't know if this is helpful, but I was trying to do a keysend to my Eclair Mobile wallet version 0.4.12 and it to is failing.

**Comment by Fonta1n3** [comment]
From my experience it literally only works c-lightning to c-lightning although i haven’t tested since latest release.

**Comment by cdecker** [comment]
The error message got me thinking that the recipient might not support keysend at all, and checking with my local gossip (which might look different now), it doesn't seem the destination supports it:

```json
{
  "nodeid": "02f7dcc28e15c0b55238a0f7db02b2082b1c2fa5adf66ff96e79db8f7ae17fe7d3",
  "alias": "Satoshi Nakamoto",
  "color": "000000",
  "last_timestamp": 1606207493,
  "features": "02a2a1",
  "addresses": [
    {
      "type": "torv3",
      "address": "p3hv5427zr3obj2edec4uva3jvcs37jus5adpxpxy2xw4jwivfm5hvad.onion",
      "port": 9735
    }
  ]
}
```

(Notice that `0x02a2a1 >> 55 & 0x01 == 0x00`, i.e., the keysend bit 55 is not set)

So adding the check before initiating a payment, and failing with a more informative error message, like we do in #4236 should address this issue.
