### ISSUE TITLE
test_mpp_interference_2 broken?

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#3989]
It's failing.  It's not failing more often because it's marked !VALGRIND and slow_test.

I've disabled it for now, please fix!

**Comment by cdecker** [comment]
I added a fix to this in the `cleanups` branch, in PR #3996. The issue seems
to come down to a lack of synchronization to the blockchain, which results in
retries, which may cause an `MPP_TIMEOUT` on the recipient.
