### ISSUE TITLE
Missing OP_CSV in Figure 4 of the pdf

### ISSUE THREAD

**Issue by pm47** [ElementsProject/lightning#4]
Hello,

I think there *might* be something missing in the htlc outputs of the Figure 4.

The payee should wait for a delay before being able to use the R, therefore the output would be:
```
R-VALUE & OP_CSV & SIG-PAYEE
OR
HTLC-TIMEOUT & SIG-PAYER
OR
REVOCATION-B & SIG A
```
Sorry I don't know how to make a PR for this, the file htlc.eps looks chinese to me !
 
Cheers,

Pierre

**Comment by rustyrussell** [comment]
pm47 <notifications@github.com> writes:
> Hello,
>
> I think there *might* be something missing in the htlc outputs of the Figure 4.
>
> The payee should wait for a delay before being able to use the R, therefore the output would be:
> ```
> R-VALUE & OP_CSV & SIG-PAYEE
> OR
> HTLC-TIMEOUT & SIG-PAYER
> OR
> REVOCATION-B & SIG A
> ```
> Sorry I don't know how to make a PR for this, the file htlc.eps looks chinese to me !

Indeed, that diagram is oversimplfied.  If PAYEE == B, then B's side
needs a delay as you specified.  Similarly, if PAYEE == A, then B's
side needs a delay on HTLC-TIMEOUT.

This is specified in full in the Appendix.  But I should note it there
too...

Thanks!
Rusty.
