### ISSUE TITLE
opening failures leave peer turds

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#401]
bitcoin@bilbo:~/.lightning$ lightning-cli getpeers
{ "peers" : 
	[ 
		{ "state" : "OPENINGD", "netaddr" : 
			[  ], "peerid" : "03bc4b957d5ad27b797d6fffa863d74e7946723e67b9084842622fe5e635747569", "connected" : false }, 
		{ "state" : "OPENINGD", "netaddr" : 
			[  ], "peerid" : "03bc4b957d5ad27b797d6fffa863d74e7946723e67b9084842622fe5e635747569", "connected" : false }, 
		{ "state" : "CHANNELD_NORMAL", "netaddr" : 
			[ "148.252.86.248:53093" ], "peerid" : "02c28fdf8fed204522358ad1056e00f7fe6a0142d74f5589a172aeff93371c500d", "connected" : true, "owner" : "lightning_channeld", "channel" : "497346:551:1", "msatoshi_to_us" : 0, "msatoshi_total" : 80000000 }, 
		{ "state" : "CHANNELD_NORMAL", "netaddr" : 
			[  ], "peerid" : "036c74ac746b3a314f698aa234100e13892275df1632d14cd605d89badfe2c707e", "connected" : false, "channel" : "497278:1604:1", "msatoshi_to_us" : 49800000, "msatoshi_total" : 50000000 }, 
		{ "state" : "CHANNELD_AWAITING_LOCKIN", "netaddr" : 
			[ "64.71.8.130:55850" ], "peerid" : "0392de9959c87b521f1791a22ef42b60fb15eb9ec9036d46995d01a4c0f4ec0041", "connected" : true, "owner" : "lightning_channeld", "msatoshi_to_us" : 0, "msatoshi_total" : 70000000 } ] }

This was caused by trying to open twice with too little satoshis.

**Comment by instagibbs** [comment]
ACK, many turds in my list

**Comment by jb55** [comment]
I'm still getting opening turds...

**Comment by jb55** [comment]
Some clues:
```
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
lightningd(30333): peer 023d8ab0d84c21979224213452117b0c1ff3605bdf0e9da478f93db11b06d3471c: activate_peer(OPENINGD) with no funding txid?
```

**Comment by ktorn** [comment]
Same here, lots of of them due to failed channel opens, caused by mismatched fee thresholds (see #609).
