### ISSUE TITLE
MPP splits into too many parts. Please add option to change the 10k sats

### ISSUE THREAD

**Issue by mb300sd** [ElementsProject/lightning#4032]
### Issue and Steps to Reproduce

Attempting to make larger payments after upgrading to 0.9.0-1 causes the payment to split into 100s to 1000s of parts, when channel capacity was available to make it in 1-4. Large payments always fail now.

**Comment by vincenzopalazzo** [comment]
I think that this issue is under discussion with this issue https://github.com/ElementsProject/lightning/issues/3987. In addition, if you don't have necessity to use the MPP you can use the command `legacypay` but maybe you know already this option

**Comment by mb300sd** [comment]
Yes, legacypay still works. I was looking forward to being able to make payments greater then the legacy limit though, adding a parameter for split size would be very helpful.

**Comment by vincenzopalazzo** [comment]
@mb300sd Yep I agree with you, in the common cases the MPP work well but if you jump inside the PR you can find a lot of proposed to improve it.

But, I think that you are unable to use the pay command, this can be an issue and maybe @cdecker is the correct people that can give additional detail to you. :-)

**Comment by rustyrussell** [comment]
Numerous improvements to mpp in master, can you test?

**Comment by mb300sd** [comment]
Master is much better! Tested a nearly .5 btc payment between nodes and it worked perfectly.

**Comment by rustyrussell** [comment]
Great!  I'll close this then!
