### ISSUE TITLE
Startup failure "s32 field doesn't match size: expected 4, actual 8" with PostgreSQL

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#4050]
### Issue and Steps to Reproduce

Attempting to start C-Lightning 0.9.1 using the PostgreSQL backend results in the following fatal error:
```
s32 field doesn't match size: expected 4, actual 8
```

Tracing with GDB reveals that this message is coming from the new `fillin_missing_channel_id` function at [line 1256](https://github.com/ElementsProject/lightning/blob/v0.9.1/wallet/db.c#L1256).

The `channels.id` column is of type `BIGSERIAL` (i.e., `BIGINT`), but the [`db_postgres_column_int`](https://github.com/ElementsProject/lightning/blob/v0.9.1/wallet/db_postgres.c#L167) function enforces that the column width is 4 bytes. This obviously fails.

### Workaround
1. Change the `channels.id` column type to `INTEGER`.
    ```
    ALTER TABLE channels ALTER COLUMN id TYPE INTEGER;
    ```
1. Start lightningd so that the database upgrade can occur. The process will eventually fail to start with the following fatal error:
    ```
    u64 field doesn't match size: expected 8, actual 4
    ```
1. Change the `channels.id` column type back to `BIGINT`.
    ```
    ALTER TABLE channels ALTER COLUMN id TYPE BIGINT;
    ```
1. Start lightningd as normal.

**Comment by martinbehrens** [comment]
Able to replicate with v0.9.0 and v0.9.1 exactly as described. Workaround works as well, thanks @whitslack

**Comment by gabridome** [comment]
Nope. The workaround didn't work for me. 
I have tried with 0.9.1 but.
I have executed point 1., point 2., obtained the same message, executed point 3. but, when I restart lightningd, I always have

`s32 field doesn't match size: expected 4, actual 8` .

I also made a git pull to the last commit on master but the result is the same.
