### ISSUE TITLE
Build error on ppc64le

### ISSUE THREAD

**Issue by grubles** [ElementsProject/lightning#4054]
### Issue and Steps to Reproduce
Running `make` on Ubuntu 18.04 ppc64le encounters an error.

```
ld lightningd/lightningd
wallet/db.o:(.toc+0x0): undefined reference to '__stop_xautodata_db_backends'
wallet/db.o:(.toc+0x8): undefined reference to '__start_xautodata_db_backends'
collect2: error:  ld returned 1 exit status
Makefile:481: recipe for target 'lightningd/lightningd' failed
```

**Comment by rustyrussell** [comment]
Did you somehow compile with neither sqlite3 nor postgres support?

**Comment by grubles** [comment]
I did indeed not have `libsqlite3-dev` installed. I figured `./configure` would yell at me for missing a dependency.

After installing `libsqlite3-dev`, the build completed successfully.
