### ISSUE TITLE
Stuck with a "zombie" channel

### ISSUE THREAD

**Issue by Moller40** [ElementsProject/lightning#4057]
Got this error:

```
lightning-cli fundchannel 0279c11ed7a068d10dc1a38ae66d2d6461e269336c60368c021b1ddcdfe4b00bc4 384783 slow true 0
{
   "code": -1,
   "message": "Error broadcasting transaction: error code: -26\\nerror message:\\ninsufficient fee, rejecting replacement 0aac7cb5438b656dfcde60313427182d82186d883cc85883137c68875e9e020f, less fees than conflicting txs; 0.00000161 < 0.00000222 (code 66). Unsent tx discarded 02000000000101a1e02d666b4702c32d74aca779e26f89b1acd2e314d398f07a7d0ea43e8ef0dc0100000000fdffffff020fdf0500000000002200201e40fb577ca7bee799723c7c9456620d596e3d1183fc92496f82a5a05cc15d95242d090000000000160014ba30a84b6638e972ded98676cedc8f890cf7134702463043021f17f54305e34068913e83c90829bb351a987a33b10d0fd593673adf7102adf502207a745ee93ed76106e4562a43f864c82dd1a33f0594c64f62cdbc2bb9f9cc504c012103c84637d1ce9e68ec5caeda58bc8381db6cb8a17e7cad6951eaf31a40946e113d6fe50900"
}
```

Which I guess is fine, but now I'm stuck with a "zombie" channel in state CHANNELD_AWAITING_LOCKIN, since the tx was discarded and never sent.
How can/should I clean this up? With fundchannel_cancel?
Or is it a bug? Perhaps some cleanup of almost created channel should be done in the following function, the same way as you "Unreserve the inputs again":

```
static void sendpsbt_done(struct bitcoind *bitcoind UNUSED,
			  bool success, const char *msg,
			  struct sending_psbt *sending)
{
	struct lightningd *ld = sending->cmd->ld;
	struct json_stream *response;
	struct bitcoin_txid txid;
	struct amount_sat change;

	if (!success) {
		/* Unreserve the inputs again. */
		for (size_t i = 0; i < tal_count(sending->utxos); i++) {
			wallet_unreserve_utxo(ld->wallet,
					      sending->utxos[i],
					      get_block_height(ld->topology));
		}

		was_pending(command_fail(sending->cmd, LIGHTNINGD,
					 "Error broadcasting transaction: %s."
					 " Unsent tx discarded %s",
					 msg,
					 type_to_string(tmpctx, struct wally_tx,
							sending->wtx)));
		return;
	}

	wallet_transaction_add(ld->wallet, sending->wtx, 0, 0);

	/* Extract the change output and add it to the DB */
	wallet_extract_owned_outputs(ld->wallet, sending->wtx, NULL, &change);

	response = json_stream_success(sending->cmd);
	wally_txid(sending->wtx, &txid);
	json_add_hex_talarr(response, "tx", linearize_wtx(tmpctx, sending->wtx));
	json_add_txid(response, "txid", &txid);
	was_pending(command_success(sending->cmd, response));
}
```

**Comment by rustyrussell** [comment]
Somehow, you've used the same input for two things.  The new channel is upset that the funding tx didn't go through, but it's not smart enough to realize that it will *never* go through once the other tx does.

I can't find the tx `dcf08e3ea40e7d7af098d314e3d2acb1896fe279a7ac742dc302476b662de0a1` which claims to fund this though (neither testnet nor mainnet) so I'm not sure where that's gone?

You can use `dev-forget-channel` to force it to forget about the channel (only if --enable-developer is set though).

**Comment by Moller40** [comment]
I managed to clean this up. Actually I had two zombie channels. One in state CHANNELD_AWAITING_LOCKIN and one in CHANNELD_SHUTTING_DOWN.
On the first one `fundchannel_cancel` worked, and on the second I had to use `dev-forget-channel`.

The transaction hex is fake in my error above. Altered it a bit for privacy, sorry.

Not sure why I got in trouble, but I did try to spend an unconfirmed transaction when doing `fundchannel`. Maybe that is a problem sometimes? But have done it before and then it was just fine.

**Comment by rustyrussell** [comment]
Def possible if the unconfimed tx gets RBFd!

**Comment by ZmnSCPxj** [comment]
We really do not have any good handling for unconfirmed transactions.  My personal recommendation is to never spend from unconfirmed transactions with `lightningd` and always require deep confirmation (`minconf=3`).

This is undesirable of course, since if you did a `fundchannel` or `multifundchannel` your change is "stuck" until deep confirmation, but this should reduce the probability of inconsistency of the chainstate with our view of it.

**Comment by Moller40** [comment]
Yes, it would be great with proper handling of unconfirmed transactions. This thing that your change is "stuck" is annoying. Also when depositing it would be nice to be able to see that c-lightning at least detects that there are incoming on-chain transaction.

**Comment by niftynei** [comment]
@Moller40 is this ok to close?
