### ISSUE TITLE
Makefile hardcodes sha256sum, not available on FreeBSD

### ISSUE THREAD

**Issue by laanwj** [ElementsProject/lightning#4075]
The following error appears on FreeBSD during build: `/bin/sh: sha256sum: not found`.

I think it comes from:
```
Makefile:SHA256STAMP_CHANGED = [ x"`sed -n 's/.*SHA256STAMP://p' $@ 2>/dev/null`" != x"`cat $(sort $(filter-out FORCE,$^)) | sha256sum | cut -c1-64`" ]
Makefile:SHA256STAMP = echo '$(1) SHA256STAMP:'`cat $(sort $(filter-out FORCE,$^)) | sha256sum | cut -c1-64` >> $@
```
Unfortunately, FreeBSD  doesn't have `sha256sum` but a tool `sha256` which works slightly differently. There's no real standard for this. See e.g. the [install_db4.sh](https://github.com/bitcoin/bitcoin/blob/master/contrib/install_db4.sh#L32) script in bitcoin which attempts to detect this.

It doesn't actually prevent anything from being built so I think it's a low-priority problem.

**Comment by rustyrussell** [comment]
Yes, it only stops development files from being regenerated.  Still, worth fixing, thanks!

**Comment by Fonta1n3** [comment]
I noticed the same thing on macOS recently fwiw. 0.9.1
