### ISSUE TITLE
Postgres CI fails

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#4080]
### Issue and Steps to Reproduce
See #4079 

Forcing rerunning enough sometimes works, but we never get any output since it just RERUNs everything until it times out.

So if there are issues, they won't be fixed anyway.

**Comment by jsarenik** [comment]
Here is the current [full log with PostgreSQL](https://gist.github.com/jsarenik/7c4a7e34a3e19a947f13e023b214258b). I am still not sure what to focus on.

```
$ pg_config --version
PostgreSQL 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1)
```
