### ISSUE TITLE
mypy should be run by check-python

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#4085]
Otherwise we'll keep breaking all those type annotations!

**Comment by cdecker** [comment]
I didn't cover the tests yet, but the libraries pass the superficial `mypy` run in #4095. We're also just beginning with the type-annotations, if I amp up the checks with `mypy --strict` pyln-client alone produces 602 errors about missing or incomplete annotations, but we probably don't want to go full `--strict` anyway. As it is currently it helps identify and fix most type-related bugs, and incremental gains are more expensive and cumbersome to reach. We can ratchet up gradually :wink:
