### ISSUE TITLE
need a method to "withdraw max" or subtract fee from output

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/lightning#409]
otherwise user is left guessing fees to get their money out

**Comment by ZmnSCPxj** [comment]
Perhaps it would be better to implement RBF if feasible.

One idea, which I have not seen implemented in any wallet, is to support "transaction acceleration" for every on-chain transaction.  In the case of sends from the wallet, every transaction is marked RBF and an "accelerate" request would reduce the change amount and bump up fees (or fail if there is no change left).  In case of receive into wallet, an "accelerate" request would spend the received funds into an address controlled by the wallet and speed up the receive transaction via CPFP (further accelerations would bump the fee of the child transaction, which again should be RBF).  Possibly make two RPC commnads, one to get an idea of how much money will be spent to accelerate the transaction, and another to actually accelerate the transaction.

**Comment by instagibbs** [comment]
That sounds like an orthogonal issue to me. Currently there is no good way of "exiting" your money to another wallet, aside from guessing required feerate.
