### ISSUE TITLE
Issue on pruned nodes?

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#4099]
I don't remember having issues with c-lightning on pruned nodes but a user reported this:

https://github.com/btcpayserver/btcpayserver-docker/issues/373

Running v0.9.0

**Comment by cdecker** [comment]
That is to be expected: we retrieve historical blocks to verify a channel announcement for a channel opened in that block. If we can't retrieve it we'll drop the channel announcement and the next time we get the announcement we'll just try again.

**Comment by NicolasDorier** [comment]
@cdecker would it completely prevent clightning from working? Or is it just a problem for logs?

**Comment by cdecker** [comment]
It'll not add channels to its view of the network topology, but the network should be redundant enough to still be able to route correctly even if missing a couple of channels.

It's more annoying than anything else. Maybe we could remember which blocks we were unable to fetch for a while, and not try to fetch them again.

**Comment by NicolasDorier** [comment]
@taxmeifyoucan given what @cdecker is saying, it should still work. So if RTL does not work, this is probably a problem there, so I am closing this issue for now.
