### ISSUE TITLE
Can't do multifundchannel via Terminal

### ISSUE THREAD

**Issue by Moller40** [ElementsProject/lightning#4100]
When I try this via Terminal:

`lightning-cli multifundchannel -k destinations=[{id:02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b,amount:2000111},{id:03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f,amount:3000111}]
`

I get error:

`lightning-cli: Incorrect 'id' in response: null`

Is my notation wrong, or is there some other problem?
Also, it would be great if there were some examples in the documentation of how you should pass "an array of objects" via terminal command.

**Comment by cdecker** [comment]
Indeed you need to wrap the JSON argument in quotes:

```
lightning-cli multifundchannel -k destinations="[{id:02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b,amount:2000111},{id:03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f,amount:3000111}]"
```

This should work. An example in the docs would be great indeed.

**Comment by Moller40** [comment]
No, that does not help me. Same error quotes.

**Comment by cdecker** [comment]
Interesting, what shell is this?

**Comment by Moller40** [comment]
Yes now it worked! With the right combination of single quotes and double quotes, as you wrote:

```shell
lightning-cli multifundchannel -k destinations='[{"id":"02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b","amount":2000111},{"id":"03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f","amount":3000111}]'
```

My shell is -bash.

**Comment by cdecker** [comment]
Excellent, thanks @Moller40 for the all-clear :+1:
