### ISSUE TITLE
ligthningd cannot find bcli plugin

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#4107]
### Issue and Steps to Reproduce
I upgraded clightning to 0.9.1 (from 0.8.0) on Ubuntu 18.04.5 following [these instructions](https://bitcoin.stackexchange.com/questions/91502/how-to-securely-update-and-verify-c-lightning-release) (download the tar.gz, check the signatures, unpack, copy the binaries to `/usr/local/bin/`). Now I encounter the following error:

```
$ lightningd
error starting plugin '/usr/local/bin/../libexec/c-lightning/plugins/bcli': opening pipe: No such file or directory
```

Indeed, there is no `bcli` plugin in the plugins directory. Where am I supposed to obtain it from?

I user Bitcoin Core 0.20.1, if this is relevant.

### `getinfo` output

None, as clightning doesn't start.

**Comment by s-tikhomirov** [comment]
What's disappointing is that I can't return to the previously working version either: after I replaced the binaries back to 0.8.0, I get:

```
$ lightningd
lightningd: lightning_channeld: bad version 'v0.8.0-40-g899f5de
'
```

**Comment by fiatjaf** [comment]
The default plugins are in c-lightning's `plugins/` directory. If you manually copied the binaries to somewhere you must also copy the plugin binaries to `/usr/local/bin/../libexec/c-lightning/plugins/` or to your local lightning path (`~/.lightning/plugins/`).

**Comment by s-tikhomirov** [comment]
Oh, I misread the instructions. Fixed, thank you!
