### ISSUE TITLE
Feature Request: Is it possible to retrieve the xPub of the on-chain wallet?

### ISSUE THREAD

**Issue by saubyk** [ElementsProject/lightning#4110]
Is it possible to retrieve the xPub of the on-chain wallet?

- This can help simplify fund management on implementations like BTCPayserver, where currently the Lightning implementations run as a separate hot wallet from the main one.
- Enable other privacy improvements which BTCPayserver is interested in experimenting with (cc: @kukks)

**Comment by darosior** [comment]
That's on my TODO list fwiw.. (as part of outputting [descriptors for the onchain wallet in `hsm_tool`](https://github.com/ElementsProject/lightning/wiki#implementation-1))

**Comment by cdecker** [comment]
> That's on my TODO list fwiw.. (as part of outputting [descriptors for the onchain wallet in `hsm_tool`](https://github.com/ElementsProject/lightning/wiki#implementation-1))

Should I assign this to you then?

**Comment by darosior** [comment]
Yeah let's do it :-)
