### ISSUE TITLE
signmessage: unknown parameter (message not a JSONRPC2)

### ISSUE THREAD

**Issue by jsarenik** [ElementsProject/lightning#4118]
# Issue and Steps to Reproduce

Any characters which are not valid for JSONRPC2 (i.e. in [`common/param.c` around line that prints `unknown parameter`](https://github.com/ElementsProject/lightning/blob/master/common/param.c#L127)) is making `signmessage` end with error.

```
$ lightning-cli --testnet signmessage "ahoj" >/dev/null 2>&1 && echo this works
this works
$ lightning-cli --testnet signmessage "ahoj=" >/dev/null 2>&1 && echo this works || echo this does not
this does not
```

### `getinfo` output

I take this as a free opportunity to advertise my testnet node. Thank you!

```
{
   "id": "0256475d8eaa0b537992a8995129137f0702bc79a17b4749fffb402bf81348a595",
   "alias": "UNITEDENTOURAGE-v0.9.1-99-g71113",
   "color": "025647",
   "num_peers": 29,
   "num_pending_channels": 3,
   "num_active_channels": 25,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "217.195.164.4",
         "port": 19736
      },
      {
         "type": "torv3",
         "address": "e4jdloa4ca23nqzdag6bixyag6pq3qqpapa6m5a4cegwlic6wma7hlad.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9736
      },
      {
         "type": "ipv4",
         "address": "192.168.88.100",
         "port": 19736
      }
   ],
   "version": "v0.9.1-99-g711133e",
   "blockheight": 1860813,
   "network": "testnet",
   "msatoshi_fees_collected": 6755,
   "fees_collected_msat": "6755msat",
   "lightning-dir": "/home/nisim/.lightning/testnet"
}
```

**Comment by jsarenik** [comment]
Stumbled upon it by trying to sign message in generated by https://htlc.me when trying to add my node into their directory. Yes, htlc.me works again.

**Comment by ZmnSCPxj** [comment]
Are you using `lightning-cli` command instead of directly a JSON-RPC programmatic interface?  Because `lightning-cli` tries to autodetect between `--keys` and `--order`, and it detects `--keys` by checking for a `=` character in your argument.  In `--keys` mode it expects everything after the method name to be of the form `paramname=paramvalue`.  So it looks to `lightning-cli` that `ahoj` is a parameter name, with an empty string as value.

Try:

    lightning-cli --testnet --order signmessage ahoj=

**Comment by jsarenik** [comment]
That works. Thank you.
