### ISSUE TITLE
sudo make install

### ISSUE THREAD

**Issue by kalibox** [ElementsProject/lightning#4143]
Hi,

Just realised that v0.9.1 now requires sudo make install to complete the build process. This must have changed recently as up until v0.9.0.xx make install would suffice.

Is there another way around having to run sudo please?

Thanks

**Comment by fiatjaf** [comment]
You can just `make` and run it directly from the directory you've downloaded it.

Basically

```
./configure
make
./lightningd/lightningd [options]
./cli/lightning-cli getinfo
```

**Comment by kalibox** [comment]
Got it. Thank you @fiatjaf
