### ISSUE TITLE
Default network changing in 2020

### ISSUE THREAD

**Issue by jsarenik** [ElementsProject/lightning#4159]
### Issue and Steps to Reproduce

`lightningd` when run without network selection warns about following:

```
default network changing in 2020
```

### `getinfo` output

```
{
   "id": "029b579174dcece6b2f5712cd33d640d291138ba68467294e2079f16118bd25610",
   "alias": "SOMBERFIRE",
   "color": "029b57",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv6",
         "address": "2001:470:6f:200:c2f6:bf7c:c6c:bf6b",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.9.1-249-g3b69dce",
   "blockheight": 653356,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/nsm/.lightning/bitcoin",
   "warning_bitcoind_sync": "Bitcoind is not up-to-date with network."
}
```

**Comment by darosior** [comment]
That's expected behaviour, the default is going to be mainnet but i think we made the period last longer than the usual 6 months :)

**Comment by jsarenik** [comment]
@darosior Yes, that why i made this issue as a reminder. Following release will probably be the last one in 2020…

**Comment by jsarenik** [comment]
@niftynei 2020 here

**Comment by whitslack** [comment]
Didn't the default network change to "bitcoin" (i.e., "mainnet") in [release 0.8.0](https://github.com/ElementsProject/lightning/releases/tag/v0.8.0)?

> * Bitcoin mainnet is now the default network, no more `--network=bitcoin` needed for all you reckless users :wink:

**Comment by jsarenik** [comment]
@whitslack it did, but the config warning is still there:

```
$ git grep "default network changing"
common/configdir.c:                     warnx("WARNING: default network changing in 2020:"
$ git describe
v0.9.2-119-gf7cdf1dd9
```

**Comment by whitslack** [comment]
@darosior said, "the default is going to be mainnet." Technically that may be true, but what they didn't say is that the default is *already* mainnet and has been for some time.

**Comment by jsarenik** [comment]
When I am looking at the current `common/configdir.c` I think that it is OK as it is, just the tests should be changed so that they use `network=testnet` and not write those false-positive messages. The warning message could maybe stay (or even change to "WARNING: default network _has changed_ in 2020"…)

Ideas?
