### ISSUE TITLE
Remove <hsm password> entry on command line from hsmtool

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/lightning#4186]
Inputting passwords into command line options is a security hole -- it gets entered into your bash command history.

A better way to do it would be to disable ECHO, as we do in #4065.

**Comment by darosior** [comment]
Yeah, one way i thought of doing this in a not-so-backward-incompatible manner was to:
1) completely disregard the password field 
2) detect an encrypted hsm_secret (as we do in hsm_control.c) and interactively ask for a password in this case
3) in three releases, completely remove the disregarded `<hsm password>` field

**Comment by ZmnSCPxj** [comment]
Not just on `bash` history --- `ps` and `top` can show it to ***anyone*** on the same machine as you, if they happen to run those at a very opportune time.
