### ISSUE TITLE
Support reproducible/deterministic builds

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#423]
Reproducible builds help close the loop and assert that the binary releases match the source code they were built from. Not sure how hard this is going to be but it's a great assurance for our users.

**Comment by ZmnSCPxj** [comment]
@jsarenik : https://reproducible-builds.org/

**Comment by fanquake** [comment]
Was this fixed, or no longer an interest?

**Comment by cdecker** [comment]
We have had reproducible builds for quite some time, I'm just cleaning up some old issues :-)

Reprobuilds are only available for ubuntu:16.04 and amd64, but that'll cover 90% of our users.
