### ISSUE TITLE
In-flight channel funding goes missing after fundchannel_complete returned "Unknown peer"

### ISSUE THREAD

**Issue by bitbug42** [ElementsProject/lightning#4232]
### Issue and Steps to Reproduce
The issue happened while trying to open a channel to Wallet of Satoshi's node.

Prior to my attempt, I had a zombie channel lingering with them since about a month (the funding tx never confirmed and the funds were double-spent somewhere else in the meantime). `fundchannel_cancel` didn't respond, so I ran `dev-forget-channel`.

Now here comes my 2nd attempt to open a channel to them:

I tried to open a channel from another wallet using the `fundchannel_start` / `fundchannel_complete` workflow.

However, after broadcasting the tx, `fundchannel_complete` returned an `Unknown peer` error (despite no typo in the command). The peer was missing from `listpeers`.
After reconnecting to the peer and trying `fundchannel_complete` again, it returned `No channel funding in progress.`.

Luckily I was able to double-spend the funding tx in time and no funds were lost. 

Here's the history of commands:

```
# Remove the old channel from a previous failed attempt months ago
lightning-cli dev-forget-channel 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
{
   "forced": false,
   "funding_unspent": false,
   "funding_txid": "98e626550d8eef3fec8cb29eb19f6ef8f9d19dfbc4298d40397540f8d6bdf47d"
}

# Start a new funding attempt:
lightning-cli connect 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
{
   "id": "02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c",
   "features": "0aa2a1"
}

lightning-cli fundchannel_start 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c 4011130 1000perkb
{
   "funding_address": "bc1qggvwfta84vxt0tzyc0g9s047phq8gea89l0cv4km7t9rhudxmu0qay3rz2",
   "scriptpubkey": "00204218e4afa7ab0cb7ac44c3d0583ebe0dc07467a72fdf8656dbf2ca3bf1a6df1e"
}

lightning-cli fundchannel_complete 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c 56ac882f507e8a78ff179aa720bc7dae36639de700ca3b2696476d2c4af4e29e 0
{
   "code": 306,
   "message": "Unknown peer"
}

lightning-cli listpeers 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
{
   "peers": []
}

lightning-cli connect 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c@172.81.178.151:9735
{
   "id": "02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c",
   "features": "0aa2a1"
}

lightning-cli fundchannel_complete 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c 56ac882f507e8a78ff179aa720bc7dae36639de700ca3b2696476d2c4af4e29e 0
{
   "code": -1,
   "message": "No channel funding in progress."
}
```

### `getinfo` output

```
{
   "id": "032ebdae3314f072acd70e66e18572e6ba27f96918009369585e7cdcf36af3cf9e",
   "alias": "Joltfun.com GameShop",
   "color": "032ebd",
   "num_peers": 43,
   "num_pending_channels": 1,
   "num_active_channels": 40,
   "num_inactive_channels": 1,
   "address": [
      {
         "type": "ipv4",
         "address": "54.38.71.76",
         "port": 9889
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9889
      }
   ],
   "version": "v0.9.2",
   "blockheight": 659206,
   "network": "bitcoin",
   "msatoshi_fees_collected": [REDACTED],
   "fees_collected_msat": "[REDACTED]msat",
   "lightning-dir": "/ln/.lightning/bitcoin"
}
```

**Comment by ZmnSCPxj** [comment]
Not a bug.  Please see the following text in the `fundchannel_complete` manual (`man lightning-fundchannel_complete`):

```markdown
Note that the funding transaction MUST NOT be broadcast until after
channel establishment has been successfully completed, as the commitment
transactions for this channel are not secured until this command
successfully completes. Broadcasting transaction before can lead to
unrecoverable loss of funds.
```

As the manual says, do NOT broadcast the funding transaction until this command returns with success.  You can *create and sign* the funding transaction, just do not broadcast it.  Your third-party wallet needs to support some facility (such as PSBTs) where it can create a transaction and provide a txid without signing and btoadcasting it; if not, you should use the builtin onchain wallet instead, which provides `txprepare`/`txsend` as well as PSBT support.

**Comment by bitbug42** [comment]
My bad sorry, seems like I didn't wake up properly that day. Thank you very much for all the clarifications.

**Comment by ZmnSCPxj** [comment]
> To fund a channel from another wallet.

Fair enough.  I hope it does have the facility to prepare a transaction without broadcasting it, which was not common until PSBTs became cool.
