### ISSUE TITLE
SQLITE version issue

### ISSUE THREAD

**Issue by monty888** [ElementsProject/lightning#4274]
version :  0.9.2

system : Linux Mint 19 Tara

command : lightnngd

output : lightningd: SQLITE version mismatch: compiled 3011000, now 3022000

**Comment by monty888** [comment]
Guessing this is a environment issue. Happens both when built from source and from release tar extract. OS was upgraded from 18 recently but did have early clightning version working, unfortunetly I never checked that that version still worked post update.

**Comment by darosior** [comment]
This is only a mismatch between the `sqlite` version `lightningd` was linked to and the (new) one. To fix it, re-compile `lightningd` after a `sqlite` upgrade.

**Comment by monty888** [comment]
LOL, there was a version in /usr/local/bin so I was never running what I thought I was! Seems to work now thanks.
