### ISSUE TITLE
Pay plugin is crashing C-Lightning

### ISSUE THREAD

**Issue by saubyk** [ElementsProject/lightning#4288]
### Issue and Steps to Reproduce
```
lightning-cli pay bolt11=lntb120n1p0alpsvpp505fj6wte456trvlrs66zehmv49xf8r2wn5qm4rgqc2nylzxrp9nqdqsxyezqumpwssxxmr5cqzpgxqrrsssp5jlgayagt7z0jj675k2rug545a7pjheqvxn2gk7dp5gjcj0da2yns9qy9qsq67jrj05knzkp2g3h2hqx8e3pfdy09yyf6y8wyjmjp0888gc57mr5addj32m0lu76dmme7jfejguddklea4gxct06rnh6h9rj0sjd2mcq39epl9
```
### Output on the command prompt:
```
lightning-cli: reading response: socket closed
```
### C-Lightning Log:
```
2020-12-20T17:56:26.395Z INFO    lightningd: Server started with public key XXXX, alias XXXXX (color #008000) and lightningd v0.9.2
2020-12-20T17:56:26.414Z INFO    03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134-chan#2: State changed from FUNDING_SPEND_SEEN to ONCHAIN
2020-12-20T17:59:26.017Z INFO    0292f04ef62d32d30c3413d759c851f03726f696a5874b19c070b444789361165d-channeld-chan#81: Peer connection lost
2020-12-20T17:59:26.018Z INFO    0292f04ef62d32d30c3413d759c851f03726f696a5874b19c070b444789361165d-chan#81: Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (62208)
2020-12-20T18:00:25.976Z INFO    0292f04ef62d32d30c3413d759c851f03726f696a5874b19c070b444789361165d-channeld-chan#81: Peer connection lost
2020-12-20T18:00:25.977Z INFO    0292f04ef62d32d30c3413d759c851f03726f696a5874b19c070b444789361165d-chan#81: Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (62208)
2020-12-20T18:01:26.129Z INFO    0200a7f20e51049363cb7f2a0865fe072464d469dca0ac34c954bb3d4b552b6e95-channeld-chan#97: Peer connection lost
2020-12-20T18:01:26.130Z INFO    0200a7f20e51049363cb7f2a0865fe072464d469dca0ac34c954bb3d4b552b6e95-chan#97: Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (62208)
2020-12-20T18:02:26.069Z INFO    03e5a30acf806b1226b5e22152eed370a9698fe50f34a694ce1c7c06db143db715-channeld-chan#123: Peer connection lost
2020-12-20T18:02:26.070Z INFO    03e5a30acf806b1226b5e22152eed370a9698fe50f34a694ce1c7c06db143db715-chan#123: Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (62208)
pay: Could not load gossmap gossip_store: Invalid argument
2020-12-20T18:03:26.801Z INFO    plugin-pay: Killing plugin: Plugin exited before completing handshake.
2020-12-20T18:03:26.801Z **BROKEN** plugin-pay: Plugin marked as important, shutting down lightningd!
2020-12-20T18:03:26.830Z INFO    plugin-autoclean: Killing plugin: Plugin exited before completing handshake.
2020-12-20T18:03:26.830Z INFO    plugin-bcli: Killing plugin: Plugin exited before completing handshake.
2020-12-20T18:03:26.830Z INFO    plugin-keysend: Killing plugin: Plugin exited before completing handshake.
2020-12-20T18:03:26.830Z INFO    plugin-txprepare: Killing plugin: Plugin exited before completing handshake.
2020-12-20T18:03:26.830Z INFO    plugin-spenderp: Killing plugin: Plugin exited before completing handshake.
```

C-Lightning version:  v0.9.2, running on Mac OS (BigSur)

**Comment by whitslack** [comment]
So now, as of v0.9.3, neither `pay` nor `legacypay` work. Thus, I am no longer able to send payments out from my C-Lightning node at all. :sob:

* The `pay` command crashes the `pay` plugin, which causes `lightningd` to abort. (Sorry to everyone who was actively forwarding an HTLC through my node at that moment!)
* The `legacypay` command no longer works, always returning error code 206 with message similar to "Route wanted fee of 1500153500msat". (That's a fee of 0.0102% of my payment, which should be allowed since I specified `maxfeepercent=0.1`.)

**Comment by cdecker** [comment]
That's a 591.81 USD fee, putting the overall payment amount at 591 / 0.0102 = 58020.64 USD, which I doubt is really the case.

**Comment by whitslack** [comment]
No, the fee was 153500 msat. The payment was 1500000000 msat. I don't know why legacypay is thinking that the fee alone is equal to the entire amount (payment + fee), but I'd guess that's the bug.

**Comment by rustyrussell** [comment]
This is really confusing.  The gossip store ($HOME/.lightning/bitcoin/gossip_store for mainnet) may be corrupt (first byte should be 9), but otherwise I can't see how pay would ever get that error.

However, you can simply delete the `gossip_store` file and it will be recreated (by downloading from peers) in this case.

**Comment by whitslack** [comment]
> first byte should be 9

@rustyrussell: What do you mean by this? Are you saying that the first byte of `gossip_store` should *always* be 9? Do you mean ASCII digit '9' or raw byte 0x09? Either way, my `gossip_store` does not match.

```
# head -c512 /var/lib/lightning/bitcoin/gossip_store | hexdump -C
00000000  00 80 00 01 bc 13 95 c5  22 00 00 00 00 10 08 00  |........".......|
00000010  00 00 00 00 0f 42 40 01  b0 01 00 00 00 00 00 00  |.....B@.........|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 6f e2 8c  |.............o..|
00000120  0a b6 f1 b3 72 c1 a6 a2  46 ae 63 f7 4f 93 1e 83  |....r...F.c.O...|
00000130  65 e1 5a 08 9c 68 d6 19  00 00 00 00 00 0a 03 83  |e.Z..h..........|
00000140  00 05 a6 00 00 02 65 1f  a5 f3 f6 67 6c 6f 13 d8  |......e....glo..|
00000150  8b 3f fd 31 01 42 1c d3  bd 17 73 d4 af 92 24 2c  |.?.1.B....s...$,|
00000160  46 f0 f9 02 ef 39 02 98  f6 07 4a 45 4a 1f 53 45  |F....9....JEJ.SE|
00000170  cb 2a 7c 6f 9f ce 20 6c  d0 bf 67 5d 17 7c db f0  |.*|o.. l..g].|..|
00000180  ca 75 08 dd 28 85 2f 03  1b 84 c5 56 7b 12 64 40  |.u..(./....V{.d@|
00000190  99 5d 3e d5 aa ba 05 65  d7 1e 18 34 60 48 19 ff  |.]>....e...4`H..|
000001a0  9c 17 f5 e9 d5 dd 07 8f  03 1b 84 c5 56 7b 12 64  |............V{.d|
000001b0  40 99 5d 3e d5 aa ba 05  65 d7 1e 18 34 60 48 19  |@.]>....e...4`H.|
000001c0  ff 9c 17 f5 e9 d5 dd 07  8f 80 00 00 8e 08 e4 a1  |................|
000001d0  33 00 00 00 00 10 06 00  8a 01 02 7a 98 18 71 4a  |3..........z..qJ|
000001e0  ff ff 38 0e 6a be 89 97  41 81 1f 28 85 72 49 cc  |..8.j...A..(.rI.|
000001f0  84 cf 54 34 ec 37 56 50  a4 76 19 37 6b 94 dc 1a  |..T4.7VP.v.7k...|
00000200
```

Almost every time I start `lightningd`, my `gossip_store` gets deleted, and the log contains a line like:

```
2021-03-10T12:10:41.484Z **BROKEN** gossipd: gossip_store_compact: bad version
```

I also have many log lines like:

```
2021-03-12T00:44:02.323Z UNUSUAL 03…76-channeld-chan#139669: gossip_store: short read 368 of 432 @30432912
```

Within any single run of `lightningd`, the offsets of the short reads (the numbers after the `@` sign in the log messages) are strictly increasing. To me this suggests that the short reads are occurring at the end of the file. A comment in `undo_read(…)` says, "Shouldn't happen, but some filesystems are not as atomic as they should be!" The "should be" there seems to be an unfounded and perhaps uneducated prescription. There are [many good reasons](https://utcc.utoronto.ca/~cks/space/blog/unix/WriteNotVeryAtomic) why `write(2)` generally cannot (or should not aspire to) modify a file atomically. Consequently the comment in `append_msg(…)` in `gossipd/gossip_store.c` is misleading: "Use pwritev so it will appear in store atomically." `pwritev(2)` provides no such guarantee, although one could be forgiven for misunderstanding the manpage when it says, "The data transfers performed by `readv()` and `writev()` are atomic: the data written by `writev()` is written as a single block that is not intermingled with output from writes in other processes." What this means is that `writev(2)` and `pwritev(2)` transfer data from user space *to the file system* atomically. It does **not** mean that the file system makes the written data visible to other processes atomically. If you want that kind of guarantee, you need to use file locking. In the case of the gossip store, which only ever grows, you can probably get away with just ignoring any incomplete records at the end of the file. I think that's effectively what is happening already, but logging about an expected scenario at the `UNUSUAL` level is misleading. Anyway, I think that's a red herring that is unrelated to the observed corruption.

As for why the version byte at the beginning of the file is apparently being overwritten, I am still scratching my head. Perhaps it would be good to put an `assert(*len != 0)` in `append_msg(…)` just to be certain that nobody is trying to write a message at offset 0.

**Comment by rustyrussell** [comment]
*Nice analysis*!  You're right: while Linux will enforce this atomicity across local filesystems due to the way it caches file access, other systems are not obliged to do so: a subtlety I had missed!  So we should remove the warning message, but you're right that's orthogonal.

But the version byte: definitely should not be overwritten (and yes, a literal 0x09): a fun mystery!

But if it were being overwritten, I'd expect it to be a gossip msg header (be32 flags/len, be32 csum, be32 timestamp, bytes).  Yet we can see (as expected) a quite well-formed message header at byte offset 1.

Nonetheless, there are only two places we write to the gossip_store: this will catch both of them; everywhere else gets a read-only fd.

But I have a sneaking suspicion that this may be the old "mmap files while writing doesn't work as you expect" issue which I first recall in HPUX.  Though I've not seen corruption simply due to readers, it's a known sharp corner...

```diff
diff --git a/gossipd/gossip_store.c b/gossipd/gossip_store.c
index 1f7aec848..aa3ed5b8c 100644
--- a/gossipd/gossip_store.c
+++ b/gossipd/gossip_store.c
@@ -100,6 +100,9 @@ static bool append_msg(int fd, const u8 *msg, u32 timestamp,
 	u32 msglen;
 	struct iovec iov[2];
 
+	/* Don't ever overwrite the version header! */
+	assert(*len);
+
 	msglen = tal_count(msg);
 	hdr.len = cpu_to_be32(msglen);
 	if (push)
@@ -630,6 +633,9 @@ static u32 delete_by_index(struct gossip_store *gs, u32 index, int type)
 	/* Should never get here during loading! */
 	assert(gs->writable);
 
+	/* Should never try to overwrite version */
+	assert(index);
+
 #if DEVELOPER
 	const u8 *msg = gossip_store_get(tmpctx, gs, index);
 	assert(fromwire_peektype(msg) == type);
```

**Comment by whitslack** [comment]
> while Linux will enforce this atomicity across local filesystems due to the way it caches file access, other systems are not obliged to do so

@rustyrussell: I think you're incorrect about this. Did you read the blog post I linked? Imagine writing a large buffer, large enough that it forces the process making the `write` system call to perform synchronous write-back to disk. During that write-back, other processes will be able to observe the file in a state that reflects only part of the write, and indeed they may even observe blocks updated *out of order*, as there is no guarantee that dirty pages will be flushed to disk in the same order as they were dirtied. You might try to argue that the buffers you're writing are small enough not to be affected by this, but I think the only circumstance under which you would not be affected would be if your write does not span a page boundary.

**Comment by rustyrussell** [comment]
> > while Linux will enforce this atomicity across local filesystems due to the way it caches file access, other systems are not obliged to do so
> 
> @rustyrussell: I think you're incorrect about this. Did you read the blog post I linked? Imagine writing a large buffer, large enough that it forces the process making the `write` system call to perform synchronous write-back to disk. During that write-back, other processes will be able to observe the file in a state that reflects only part of the write, and indeed they may even observe blocks updated _out of order_, as there is no guarantee that dirty pages will be flushed to disk in the same order as they were dirtied. You might try to argue that the buffers you're writing are small enough not to be affected by this, but I think the only circumstance under which you would not be affected would be if your write does not span a page boundary.

Meanwhile, I got curious and wrote a test and you are correct.  It shows we absolutely hit this at page boundaries (indep of offset of write).  Here's my test code FWIW:

```C
#include <err.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <time.h>

int main(int argc, char *argv[])
{
	int fd;
	size_t len;
	char *buf;
	size_t reps;

	if (argc != 3)
		errx(1, "Usage: write-vs-read filename size");

	len = atol(argv[2]);
	buf = malloc(len);

	fd = open(argv[1], O_RDWR|O_CREAT|O_TRUNC, 0600);
	write(fd, "", 1);
	close(fd);

	switch (fork()) {
	case -1:
		err(1, "forking");

	case 0: {
		struct timespec msec;
		msec.tv_sec = 0;
		msec.tv_nsec = 1000000;
		fd = open(argv[1], O_RDWR);
		nanosleep(&msec, NULL);
		if (write(fd, buf, len) != len)
			err(1, "writing");
		exit(0);
	}
	}

	/* Parent. */
	while ((fd = open(argv[1], O_RDONLY)) == -1);

	for (reps = 0;; reps++) {
		ssize_t n;
		n = pread(fd, buf, len, 0);
		if (n == 1)
			continue;
		if (n != len)
			errx(1, "Read returned %zu!", n);
		break;
	}

	printf("Got full read after %zu reps\n", reps);
}
```
