### ISSUE TITLE
Add spent funds to the `listfunds` method

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#4291]
There are a number of cases that require having access to earlier
owned funds, such as computing the fee for the transactions we sent
from a plugin or app. In order to do that we can add a simple
`spent=true` flag (semantically: "include spent outputs as well as
unspent ones in the `outputs` array) to the `listfunds` method.

This is a good first issue, and should be limited to:

 - Adding the new parameter to the JSON-RPC method
 - Adjusting the call to `wallet_get_utxos` in the handler function
   `json_listfunds` to use `OUTPUT_STATE_ANY` as third argument if the
   parameter is set to `true`.
   
This was first brought up by @hosiawak in #4289

**Comment by ZmnSCPxj** [comment]
On the one hand, this outputs every onchain action.

On the other hand, onchain actions are expected to be much rarer than offchain actions.

**Comment by cdecker** [comment]
Are you concerned about the size of the response? I definitely share that concern but I think we need to have a generic pagination system anyway, so I'd punt that for now.

Given the size of the `listchannels` and `listnodes` results and the fact that they work remarkably well even though they cross daemon boundaries (which listfunds doesn't) I think we still have some breathing room.

**Comment by ZmnSCPxj** [comment]
Yes, quite correct.

**Comment by cdecker** [comment]
Earmarking this for @hosiawak since he wants to tackle this :-)

**Comment by hosiawak** [comment]
@cdecker I pushed #4296
