### ISSUE TITLE
Status: AWAITING UNILATERAL pending since months, after recover from old virtual machine

### ISSUE THREAD

**Issue by cortesia88** [ElementsProject/lightning#4298]
Hi all,
thank you for helping me, I successful recover all my channels but I still have one in a Status: AWAITING UNILATERAL closing since months, I already tried to rescan the previous blocks but I'm still in the same situation, I'm thinking maybe my node didn't broadcast the tx to the network, can you help me to take a look to the details from spark-wallet below:

Channel ID: 636444x1124x0
Full Channel ID: 39716cbb7695bb899275ef7ead8ed7426e676d01a2a2a25b417007824fc3ecdf
Status: AWAITING UNILATERAL
Ours: 41,599.052 sat
Theirs: 68,453.948 sat
Age: 26729 blocks (6 months)
Peer: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c (connected)
Funding TXID: dfecc34f820770415ba2a2a2016d676e42d78ead7eef759289bb9576bb6c7139
AWAITING_UNILATERAL:Attempting to reconnect
peer:
  id: 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c
  connected: true
  netaddr:
    - '172.81.178.151:9735'
  features: 0aa2a1
state: AWAITING_UNILATERAL
scratch_txid: 5f6e9372b365c31ef12525e7917ef7c9626d22c4e70c237b39b084d7324eb137
short_channel_id: 636444x1124x0
direction: 1
channel_id: 39716cbb7695bb899275ef7ead8ed7426e676d01a2a2a25b417007824fc3ecdf
funding_txid: dfecc34f820770415ba2a2a2016d676e42d78ead7eef759289bb9576bb6c7139
close_to_addr: bc1qwd6kd36f7zjz3y7y3nltf3esghtrwmlwvmynnx
close_to: 0014737566c749f0a42893c48cfeb4c73045d6376fee
private: false
funding_allocation_msat:
  02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c: 0
  03a414c331a660816cbcb937e797d9f2ea923ba1294d5efbbd97df26898674332c: 110053000
funding_msat:
  02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c: 0msat
  03a414c331a660816cbcb937e797d9f2ea923ba1294d5efbbd97df26898674332c: 110053000msat
msatoshi_to_us: 41599052
to_us_msat: 41599052msat
msatoshi_to_us_min: 41599052
min_to_us_msat: 41599052msat
msatoshi_to_us_max: 110053000
max_to_us_msat: 110053000msat
msatoshi_total: 110053000
total_msat: 110053000msat
dust_limit_satoshis: 546
dust_limit_msat: 546000msat
max_htlc_value_in_flight_msat: 18446744073709552000
max_total_htlc_in_msat: 18446744073709551615msat
their_channel_reserve_satoshis: 1100
their_reserve_msat: 1100000msat
our_channel_reserve_satoshis: 1100
our_reserve_msat: 1100000msat
spendable_msatoshi: 30744052
spendable_msat: 30744052msat
receivable_msatoshi: 67353948
receivable_msat: 67353948msat
htlc_minimum_msat: 0
minimum_htlc_in_msat: 0msat
their_to_self_delay: 144
our_to_self_delay: 144
max_accepted_htlcs: 30
in_payments_offered: 0
in_msatoshi_offered: 0
in_offered_msat: 0msat
in_payments_fulfilled: 0
in_msatoshi_fulfilled: 0
in_fulfilled_msat: 0msat
out_payments_offered: 1
out_msatoshi_offered: 68453948
out_offered_msat: 68453948msat
out_payments_fulfilled: 1
out_msatoshi_fulfilled: 68453948
out_fulfilled_msat: 68453948msat
htlcs: []

What can i do to close it?

**Comment by cortesia88** [comment]
"channels": [
      {
         "peer_id": "02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c",
         "connected": false,
         "state": "AWAITING_UNILATERAL",
         "short_channel_id": "636444x1124x0",
         "channel_sat": 41599,
         "our_amount_msat": "41599000msat",
         "channel_total_sat": 110053,
         "amount_msat": "110053000msat",
         "funding_txid": "dfecc34f820770415ba2a2a2016d676e42d78ead7eef759289bb9576bb6c7139",
         "funding_output": 0
      },

**Comment by cortesia88** [comment]
forget about it

**Comment by cdecker** [comment]
That channel was closed:

 - Funding outpoint: [dfecc34f820770415ba2a2a2016d676e42d78ead7eef759289bb9576bb6c7139](https://blockstream.info/tx/dfecc34f820770415ba2a2a2016d676e42d78ead7eef759289bb9576bb6c7139?output:0&expand)
 - Unilaterally closed by [4d5de116d08398f3436be5aa32aa82d7619428da514d33f8974ee070a5d68445:0](https://blockstream.info/tx/4d5de116d08398f3436be5aa32aa82d7619428da514d33f8974ee070a5d68445?input:0)
   - Return to wallet of breached party: [4d5de116d08398f3436be5aa32aa82d7619428da514d33f8974ee070a5d68445:0](https://blockstream.info/tx/4d5de116d08398f3436be5aa32aa82d7619428da514d33f8974ee070a5d68445?output:0)
   - Timelock return to wallet of breaching party: [[4d5de116d08398f3436be5aa32aa82d7619428da514d33f8974ee070a5d68445:1](https://blockstream.info/tx/4d5de116d08398f3436be5aa32aa82d7619428da514d33f8974ee070a5d68445?output:1)
     - Return to wallet of breaching party after timeout expired: [50d4711ccec30c65dc60a0bc0921eca6142548619f984070d3a2d513c107b1c8:0](https://blockstream.info/tx/50d4711ccec30c65dc60a0bc0921eca6142548619f984070d3a2d513c107b1c8?input:0)
