### ISSUE TITLE
how to debug featurebits from plugins?

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#4310]
### Issue and Steps to Reproduce

I'm setting the following on my plugin initialization:

```json
{
  "featurebits": {
    "node": "08000000"
  }
}
```

Which should give me the feature 27, right?

But then how do I know if it worked? There should be a `features` field on `getinfo` or something like that.

I tried to `connect` from another node to the node which should have the special feature, but it didn't work, it returned `"features": "02aaa2"`, so is it something wrong? There are no error messages on initialization regarding this.

### `getinfo` output

```json
{
   "id": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
   "alias": "@lntxbot",
   "color": "296683",
   "num_peers": 28,
   "num_pending_channels": 1,
   "num_active_channels": 23,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "5.2.67.89",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.9.2-77-g23d4e53",
   "blockheight": 664401,
   "network": "bitcoin",
   "msatoshi_fees_collected": 31959529,
   "fees_collected_msat": "31959529msat",
   "lightning-dir": "/home/fiatjaf/.lightning1/bitcoin"
}
```

**Comment by cdecker** [comment]
You're specifying the `node_announcement` featurebits, so to check that it works you'll have to do a `listnodes` which queries the gossip:

```
lightning-cli listnodes 02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff
{
   "nodes": [
      {
         "nodeid": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
         "alias": "@lntxbot",
         "color": "296683",
         "last_timestamp": 1606739175,
         "features": "8000000002aaa2",
         "addresses": [
            {
               "type": "ipv4",
               "address": "5.2.67.89",
               "port": 9735
            }
         ]
      }
   ]
}
```

Which shows the featurebit flags applied correctly. If you want to have the featurebit also set on the connection, you'll have to also add `init`. For the full details see the [doc][1]:

> The featurebits object allows the plugin to register featurebits that should be announced in a number of places in the protocol. They can be used to signal support for custom protocol extensions to direct peers, remote nodes and in invoices. Custom protocol extensions can be implemented for example using the sendcustommsg method and the custommsg hook, or the sendonion method and the htlc_accepted hook. The keys in the featurebits object are node for features that should be announced via the node_announcement to all nodes in the network, init for features that should be announced to direct peers during the connection setup, channel for features which should apply to channel_announcement, and invoice for features that should be announced to a potential sender of a payment in the invoice. The low range of featurebits is reserved for standardize features, so please pick random, high position bits for experiments. If you’d like to standardize your extension please reach out to the specification repository to get a featurebit assigned.

[1]: https://lightning.readthedocs.io/PLUGINS.html#the-getmanifest-method

**Comment by fiatjaf** [comment]
Thank you! I think that clarifies it.

**Comment by cdecker** [comment]
No problem :-)
