### ISSUE TITLE
Closing negotiations too restrictive

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#435]
I have been attempting to open and successfully close a testnet transaction between two of my computers. So far I got to the point where both computers successfully open a channel and are in the CHANNELD_NORMAL state. As a test, I tried a mutual close of the channels with `lightning-cli close` peer-b-id from peer-a. This put both peers in the CLOSINGD_SIGEXCHANGE state. I've done this twice and I've never been able to get it out of this state.

After restarting both nodes, I tried to reconnect to peer-b from peer-a (`02058ea66978d2e5c346642c45f3cec5a4c733897b59244fc29c3107e844f62608`), I get this on peer-b: 

```

lightningd(29128): peer 02058ea66978d2e5c346642c45f3cec5a4c733897b59244fc29c3107e844f62608: Peer has reconnected, state CLOSINGD_SIGEXCHANGE
lightning_gossipd(29137): TRACE: Forgetting remote peer 02058ea66978d2e5c346642c45f3cec5a4c733897b59244fc29c3107e844f62608
lightning_gossipd(29137): TRACE: req: type WIRE_GOSSIPCTL_HANDLE_PEER len 279
lightning_gossipd(29137): TRACE: handle_peer 02058ea66978d2e5c346642c45f3cec5a4c733897b59244fc29c3107e844f62608: new peer
lightning_gossipd(29137): TRACE: 02058ea66978d2e5c346642c45f3cec5a4c733897b59244fc29c3107e844f62608: we sent them a fatal error, closing
```

Error is : `Final fee 362 vs 329 at limits 363-535`

and then peer-a just hangs. also, "we sent them a fatal error" doesn't seem to be true, since a fatal error is not reported to peer-a. possibly related: #405

**Comment by jb55** [comment]
I'm on #413 + #414 but I've also replicated this on 0610f66c (current master)

**Comment by jb55** [comment]
A new development! I now get `channel ALL: bad reestablish msg: WIRE_ERROR 00110000000000000000000000000000000000000000000000000000000000000000002646696e616c206665652033363220767320333239206174206c696d697473203336332d353335` on attempted reconnect from peer-a to peer-b

**Comment by jb55** [comment]
after restarting again, I get a new error when attempting a reconnect:

```
channel ALL: Expected closing_signed: 0011b779498925872861a0f91a390acbd1dcf294b2353f5aeb29b2e002e7c8282c57002746696e616c206665652033363220767320333239206174206c696d697473203336332d35333500
```

**Comment by jb55** [comment]
Ok so peer-a is failing in `fromwire_channel_reestablish`, it's getting back `WIRE_ERROR` instead of `WIRE_CHANNEL_REESTABLISH` @ `fromwire_u16(&cursor, plen) != WIRE_CHANNEL_REESTABLISH`

This isn't helpful, I'll do some debugging on peer-b

**Comment by jb55** [comment]
I've fixed this is #437, not knowing if that's the best solution. Now I have more errors which I will open a new PR for.

**Comment by jb55** [comment]
peer->error is true but error is an empty string, which is suspect. I'm not sure if this is because the error isn't getting set properly or if there is simply no error 🤔 I'm testing a patch [here](https://github.com/jb55/lightning/pull/1) and will submit it once the tests pass.

**Comment by jb55** [comment]
I think my assumption was wrong, it looks like empty error strings are valid errors? Maybe I'm running into another issue I'm unaware of 🤔

**Comment by rustyrussell** [comment]
OK, so, the error in these cases is "Final fee 362 vs 329 at limits 363-535".

@roasbeef previously reported that we're far too restrictive in our closing negotiations.  But even if we are, we should be dropping to chain in this case, and closing that way.  Plus a nicer error report when this happens...

**Comment by ZmnSCPxj** [comment]
#847 should have fixed this issue I think? Or are there more things attached to this issue?

**Comment by jb55** [comment]
I'll close this for now until it pops up again
