### ISSUE TITLE
dev-* options in contrib/startup_regtest.sh cause script to fail

### ISSUE THREAD

**Issue by jharveyb** [ElementsProject/lightning#4400]
### Issue and Steps to Reproduce

With release 0.9.3 and bitcoind 0.21, running contrib/startup_regtest.sh fails, due to to lightningd startup failing.
The error message: `lightningd: /tmp/l1-regtest/config line 5: dev-fast-gossip: unrecognized option`

A similar error appears after removing the `dev-fast-gossip` option, with reference to `dev-bitcoind-poll=5`.
Removing the `dev-fast-gossip` and `dev-bitcoin-poll=5` options on lines 89 & 90 fixed the issue.

Alternatively, building with the `--enable-developer` flag also resolves this issue, but that requirement isn't mentioned in the main README.

**Comment by renepickhardt** [comment]
can confirm the issue and that both solutions work. 

Is it useful to have those too flags when working in regtest? In that case I would recommend to extend the readme. otherwise one could just remove those two entries to the configfile

**Comment by niftynei** [comment]
Good point, this is definitely a bug. These options turned on makes using/testing things with `startup_regtest` much much faster (blocks are processed much more quickly, the nodes exchange gossip faster, so routing payments across the nodes is possible much sooner).

Will submit a patch to fix shortly.
