### ISSUE TITLE
v0.9.3 crashes on OpenBSD 6.8

### ISSUE THREAD

**Issue by grubles** [ElementsProject/lightning#4401]
### Issue and Steps to Reproduce
When connecting to a peer after starting `lightningd`, the node appears to start pulling gossip data from the connected peer and then eventually crashes with this output:

```
assertion "now >= timers->base" failed: file "ccan/ccan/timer/timer.c", line 349, function "timers_expire"
Abort trap (core dumped)
```

**Comment by rustyrussell** [comment]
Um, that's really weird.  It implies time went backwards somehow.

And of course there's no sane way to install OpenBSD on Digital Ocean, so I have no idea how to reproduce this.

Hmm, I'll need to see if I can find space to install it in a VM on my laptop.

**Comment by rustyrussell** [comment]
Hmm, seems to work here.  I wonder if you're not using CLOCK_MONOTONIC for some reason: is HAVE_CLOCK_GETTIME=1 set in config.vars?

**Comment by grubles** [comment]
Yes, HAVE_CLOCK_GETTIME=1 is set in config.vars.


`nm lightningd/lightningd | grep gettime` returns `U clock_gettime` too.

I wonder if it's some weird hypervisor related thing messing with the time? I'm running OBSD in a Virtualbox VM. 

I'll try running it on bare metal on an extra laptop I have laying around.

**Comment by rustyrussell** [comment]
OK, I'll prepare you a patch which will give more information, and paper over the problem.  It's not good though!

**Comment by rustyrussell** [comment]
This will give details to stderr (and keep going rather than crash).

```diff
diff --git a/ccan/ccan/timer/timer.c b/ccan/ccan/timer/timer.c
index 48bded196..fb35b0879 100644
--- a/ccan/ccan/timer/timer.c
+++ b/ccan/ccan/timer/timer.c
@@ -339,6 +339,8 @@ static void timer_fast_forward(struct timers *timers, uint64_t time)
 		timer_add_raw(timers, i);
 }
 
+#include <inttypes.h>
+
 /* Returns an expired timer. */
 struct timer *timers_expire(struct timers *timers, struct timemono expire)
 {
@@ -346,6 +348,18 @@ struct timer *timers_expire(struct timers *timers, struct timemono expire)
 	unsigned int off;
 	struct timer *t;
 
+	if (now < timers->base) {
+		fprintf(stderr, "WARNING: "
+			"timemono %"PRIu64".%09lu (%"PRIu64" grains)"
+			" predates base %"PRIu64" grains (%"PRIu64".%09lu)\n",
+			(uint64_t)expire.ts.tv_sec,
+			(long)expire.ts.tv_nsec,
+			now,
+			timers->base,
+			(uint64_t)grains_to_time(timers->base).ts.tv_sec,
+			(long)grains_to_time(timers->base).ts.tv_nsec);
+		return NULL;
+	}
 	assert(now >= timers->base);
 
 	if (!timers->level[0]) {
```
