### ISSUE TITLE
build issue on mac os with enum side and constant NUM_SIDES

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/lightning#4409]
### Issue and Steps to Reproduce
download and build lightning on mac os. 

when running `make` it produces this error
```
common/htlc_wire.c:257:11: error: result of comparison of constant 2 with expression of type 'enum side' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
        if (side >= NUM_SIDES) {
            ~~~~ ^  ~~~~~~~~~
1 error generated.
```

I tried fixing it by chaning `htlc.h` and moving NUM_SIDES to the enum  but then new errors emerge: 
```
In file included from ./common/fee_states.h:5:
./common/htlc.h:70:10: error: enumeration value 'NUM_SIDES' not handled in switch [-Werror,-Wswitch]
        switch (side) {
                ^
./common/htlc.h:70:10: note: add missing switch cases
        switch (side) {
```

I remember some PR by @niftynei  and comment by @cdecker where it was discussed that having this inside the enum would trigger a lot of switch statements to be adopted thus the constant. 

The problem is not there in `v0.9.0` but on current master

### `getinfo` output
n/a because I can't compile

**Comment by cdecker** [comment]
Assuming this is `clang` on Mac OS? Can you share the version (`clang --version`)?

**Comment by renepickhardt** [comment]
```
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by rustyrussell** [comment]
Unless something has changed in a recent C standard, clang is wrong here.  enums can have any integer value, not just those defined.  Nonetheless, this is easy to fix.
