### ISSUE TITLE
Is `invoice_payment` notification called before the `invoice_payment` hook?

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#4434]
I didn't try this, just reading the code:

https://github.com/ElementsProject/lightning/blob/b563cafd838fd4e49fcea335f4d5af491997c3ca/lightningd/invoice.c#L420-L437

So we may get `invoice_payment` but then a hook goes there and fails the payment, so the notification was a lie?

**Comment by cdecker** [comment]
Good catch, will have to move the notification to the end of the hook call-chain then.
