### ISSUE TITLE
How to resubmit withdraw?

### ISSUE THREAD

**Issue by borisgeller** [ElementsProject/lightning#4443]
I issued a withdraw command with low fee, and the transaction was broadcasted, but miners didn't include it in blocks. Now the tx  can't be found anywhere except in my local bitcoind's mempool. Listfunds now shows empty wallet. When I try to withdraw again with a higher fee, it gives me error 301. 
The question is how to salvage the coins.

**Comment by borisgeller** [comment]
I resolved the issue in this way: closed bitcoind, deleted mempool.dat, issued dev-rescan-outputs and now coins are back.

**Comment by cdecker** [comment]
Alternatively you can also use `lightning-cli listtransactions` to retrieve the transaction you're looking for, take the raw hex string and submit it using any number of block explorers, e.g., using https://blockstream.info/tx/push :-)

That way you don't have to go through the disruptive stopping bitcoind and clearing of the mempool.

**Comment by borisgeller** [comment]
That didn't work because of low fee.
