### ISSUE TITLE
assert failure in CI

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#4455]
[46.gz](https://github.com/ElementsProject/lightning/files/6208514/46.gz)

**Comment by niftynei** [comment]
Bit of a race condition here; the peer fires off their `tx_signatures` and `commitment_signed` at roughly the same time. It's possible (but rare, apparently) that we'll process the `tx_signatures` before the commitment sigs, which would cause this.

We want to make super sure that we've gotten their commitment_sigs before we sign + broadcast though... fix incoming.
