### ISSUE TITLE
cannot double spend unconfirmed channel funding transaction

### ISSUE THREAD

**Issue by theRescuer** [ElementsProject/lightning#4456]
### Problem description
Hi,
More than 1 month and half ago (2021-02-10 15:46) I applied a way too low fee to a channel-funding transaction, so it stucks unconfirmed (0 conf) in the mempool.

I do not understand why, after such a long time, the transaction is still visible in mempool.space and other explorers.

TXID 9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6
1 Input (0.00500000 BTC)
2 Ouputs (Spent --> 0.00200000 BTC, Unpsent --> 0.00299468 BTC)

This transaction has been flagged as OPT-IN RBF-able but I can't find guidance on how to apply RBF with C-Lightning.

Is there a way to either apply RBF or to cancel this transaction by double spending it?

I've been looking around for guidance but I could not find any reference for this case.
The documentation shows the parameter lightning-fundchannel_cancel but I guess it is not applicable to this case.
https://bitcoin.stackexchange.com/questions/102180/can-a-channel-be-closed-while-the-funding-tx-is-still-stuck-in-the-mempool is not showing a complete process and, in my case Option "DEVELOPER=1" can't be enabled as the implemention runs on a standard docker (Lunanode) deploymment of BTCPay Server

### `getinfo` output
"version": "basedon-v0.9.3-1"

### `listpeers` output
"id": "0374eb2306a27dffd657c781065bd11785588f4811c4949070f8aed79e95a97db4",
         "connected": false,
         "channels": [
            {
               "state": "AWAITING_UNILATERAL",
               "scratch_txid": "0fd1763dc89f33605ace5f4fe9d6369f1517cf68ac2ecf38779958a290b26cdf",
               "channel_id": "e6432a7286036e8b3eaf228ae4f8f242fb96847eb12a71323fc084a99418b19f",
               "funding_txid": "9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6",
...
               "state_changes": [
                  {
                     "timestamp": "2021-02-21T13:27:05.142Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "AWAITING_UNILATERAL",
                     "cause": "protocol",
                     "message": "channeld: received ERROR channel e6432a7286036e8b3eaf228ae4f8f242fb96847eb12a71323fc084a99418b19f: funding failed due to internal error"
                  }
               ],
               "status": [
                  "AWAITING_UNILATERAL:Attempting to reconnect"
               ],

### `listfunds` output
   "outputs": [
      {
...
      {
         "txid": "9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6",
         "output": 1,
         "value": 299468,
         "amount_msat": "299468000msat",
         "scriptpubkey": "001458...",
         "address": "bc1qtpy...",
         "status": "unconfirmed",
         "reserved": false
      },
...
   "channels": [
      {
         "peer_id": "0374eb2306a27dffd657c781065bd11785588f4811c4949070f8aed79e95a97db4",
         "connected": false,
         "state": "AWAITING_UNILATERAL",
         "channel_sat": 200000,
         "our_amount_msat": "200000000msat",
         "channel_total_sat": 200000,
         "amount_msat": "200000000msat",
         "funding_txid": "9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6",
         "funding_output": 0
      }

**Comment by niftynei** [comment]
You can't RBF a funding transaction for v1 channel opens. RBFs change the txid and it would invalidate the commitment transaction you  and your peer exchanged. There's a way to RBF opens in the experimental v2 channel open protocol, but this sadly doesn't apply to this open.

Instead, you can attempt a Child-Pays-For-Parent with the output on the funding tx.

```
{
"txid": "9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6",
"output": 1,
"value": 299468,
"amount_msat": "299468000msat",
"scriptpubkey": "001458...",
"address": "bc1qtpy...",
"status": "unconfirmed",
"reserved": false
},
```

You can spend it back into your lightning wallet with the following, though I'm leaving figuring out what a 'good' feerate for the CPFP to you :)

```
$ lightning-cli withdraw $(lightning-cli newaddr | jq .bech32) all <<INSERT HIGH FEERATE HERE>> 0 '["9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6:1"]'
```

**Comment by theRescuer** [comment]
Thank you very much!
I think I cannot run it in one shot (as per your example). It appears jq is not part of the docker deployment and I need to find a way to dissect it. But I'll try to follow up on your advice going for CPFP.

**Comment by theRescuer** [comment]
Hi,
Sorry to bother again.
After generating the new address I tried
$ lightning-cli withdraw bc1... all 20000perkb 0 '["9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6:1"]'

The output is:
{
   "code": -32602,
   "message": "UTXO 9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6:1 already reserved"
}

Any advice?

**Comment by vincenzopalazzo** [comment]
Hi, @theRescuer,

>After generating the new address I tried

The message "already reserved" usually means that you have these transactions involved in some other channel and you can't use the same transaction to open two different channels at the same time.

>It appears jq is not part of the docker deployment and I need to find a way to dissect it.

I you are using an image base on Debian and you already use apt, you need to run the command `apt install jq -y`

**Comment by theRescuer** [comment]
Hi,
Sorry I was not accurate with my issue description:
The state move to reserved:true after first getting the error message:

{
   "code": -1,
   "message": "Error broadcasting transaction: error code: -25\\n
    error message:\\n
    bad-txns-inputs-missingorspent. Unsent tx discarded 02000000000101e6432a7286036e8b3eaf228ae4f8f242fb96847eb12a71323fc084a99418b19f0100000000fdffffff01438904000000000016001492fb7afc818167e6bd86d0869d55f0f79cefca5502473044022018797b08b527f7e64296c991fde4d80b4d7391f5fdc29b63f44331e13998f09c02202e6574d5e804521c2beaaaa396d1077a3c6996e579f9cb5304615592eccf957e012102dd103456e3ecbdec5837cd8e57f11990606960a510b0d13fe0f6dc3694e7fef3ca570a00"
}

I assume the transaction is no longer valid as it is no more showing up in the mempool.
By the way the output (of listfunds command) still appears as unconfirmed.
Does my interperetation sound realistic?
If so, is there a way to update the wallet balance (without developer option enabled)?

**Comment by niftynei** [comment]
> I assume the transaction is no longer valid as it is no more showing up in the mempool.

If the funding tx has fallen out of the mempool, that would explain the issue you're seeing.

You have two options here. Both of them require a bit of work to correct.

1) Re-broadcast the funding transaction and re-attempt the CPFP via 'withdraw'. I believe you can find the funding transaction in `listtransactions`, then rebroadcast the `rawtx` with `bitcoin-cli sendrawtransaction`. The output's reservation should expire, if not you can unreserve it and try again. (See `unreserveinputs`; it takes a psbt as input, which you can build with `utxopsbt` for the input you want to unreserve. Not the easiest to use interface, it's true.)

Here's the command that should help you dig out the original funding tx from your node's database + rebroadcast it.

```bash
$ lightning-cli listtransactions | grep -A 1 9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6
         "hash": "9fb11894a984c03f32712ab17e8496fb42f2f8e48a22af3e8b6e0386722a43e6",
         "rawtx": "0200000000010a30f71aa13d52f275...00000000",
         "blockheight": 673222,
$ bitcoin-cli sendrawtransaction 0200000000010a30f71aa13d52f275...00000000
```

2) Permanently cancel the open attempt by spending the funding tx's input. As long as the input to the funding tx is spent in a different transaction, the channel will never open.

3) Since the funding tx has fallen out of the (local) mempool, it's reasonable but not foolproof to assume that it's safe to forget this channel. Not foolproof because someone might have saved it and is waiting to rebroadcast it when the mempool clears up. This probably did not happen, but you can't be sure. If you forget the channel and for some reason the stuck funding tx finally does get mined, you will irrevocably lose those funds.  The way you avoid this is with option 2, spending the input to the funding tx elsewhere.

**Comment by theRescuer** [comment]
Thanks for your great support.
Playing around with explorers it looks like that input was already spent, so I am not following up on double spending.
I also tried to create a PSBT through the utxopsbt command and I get the same info.

**Comment by niftynei** [comment]
Awesome, sounds like you’re in the clear to forget that channel and
reattempt (if you want).
