### ISSUE TITLE
Export xpub

### ISSUE THREAD

**Issue by kalibox** [ElementsProject/lightning#4466]
Hi, is it possible to export the xpub from the wallet at all? Thanks.

**Comment by hosiawak** [comment]
You can do it using `lightning-hsmtool` eg.:

Read the help:

`lightning-hsmtool help`

and then dump your output descriptors (which include your xpubs):

`lightning-hsmtool dumponchaindescriptors hsm_secret`

**Comment by hosiawak** [comment]
You can then import these output descriptors to any wallet that supports them @kalibox

**Comment by jsarenik** [comment]
Or you can use `bitcoin-cli deriveaddresses "descriptor" ( range )` to get just the addresses and these you can import almost anywhere.

**Comment by kalibox** [comment]
> You can then import these output descriptors to any wallet that supports them @kalibox

Thank you :)
