### ISSUE TITLE
Cannot access on-chain funds

### ISSUE THREAD

**Issue by premghinde** [ElementsProject/lightning#4468]
### Issue and Steps to Reproduce
I was trying to close down all channels and move funds into another wallet after trying out lightning. I used Ride the Lightning to close the channels and waited for a number of confirmations on those txs.
I then used the cli to `withdraw` and all appeared successful with a json response showing a tx and txid value. The tx never appeared in the mempool however. It looks like the node thinks the tx has been broadcast, therefore locking the funds, but didn't actually broadcast the tx to move the funds where I wanted them.

I've tried to work with `hsm_secret` to to extract an xprv and pub set using https://github.com/jb55/clightning-dumpkeys but these values are not translatable into private keys that work.  

### `getinfo` output
```
{
   "id": "03b58313dc6f343eab61bc2dfdaca51d326a788fbc28c598eb58623919e859965c",
   "alias": "CommonLawIsTheAnswer",
   "color": "03b583",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "173.249.3.27",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "lizlserfjcrwggpuma6lcuamezuruaavb6pgja4ih2qepjtzrn5nnhyd.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "basedon-v0.9.3-1",
   "blockheight": 677883,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/root/.lightning/bitcoin"
}
```

**Comment by cdecker** [comment]
We stepped through some debugging steps together, and determined that the root cause was a withdrawal with insufficient fees, that didn't pass the local `bitcoind` mempool feerate.

Using `lightning-cli dev-rescan-outputs` we managed to mark the funds as unspent, and the reservations had already expired by themselves. A further withdrawal, this time with normal fees, worked and the funds are back in Prems onchain wallet.
