### ISSUE TITLE
`listpays` is not sorted

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#4481]
### Issue and Steps to Reproduce

```
lightning-cli listpays
```

Returns an unsorted list of payments.

### `getinfo` output

```
{
   "id": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
   "alias": "@lntxbot",
   "color": "296683",
   "num_peers": 37,
   "num_pending_channels": 2,
   "num_active_channels": 22,
   "num_inactive_channels": 2,
   "address": [
      {
         "type": "ipv4",
         "address": "5.2.67.89",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.9.3-107-ga020602",
   "blockheight": 679798,
   "network": "bitcoin",
   "msatoshi_fees_collected": 32991436,
   "fees_collected_msat": "32991436msat",
   "lightning-dir": "/home/fiatjaf/.lightning1/bitcoin"
}
```

**Comment by cdecker** [comment]
Very good catch, indeed the `listpays` command, implemented by the `pay` plugin maintains a map of `payment_hash` to payment details entries. Map iteration is unsorted, and so is the `listpays` output.

What would you expect to be the order returned? Would `created_at` be a reasonable sorting key?

**Comment by fiatjaf** [comment]
Yes, `created_at`. I'm currently using `jq` to sort myself but once I forgot to do that and was very confused. I imagine other people are also getting confused and I will be again myself.
