### ISSUE TITLE
unknown message from CL to LND

### ISSUE THREAD

**Issue by Crypt-iQ** [ElementsProject/lightning#4530]
User running lnd v0.12.1-beta reported that a peer running c-lightning 0.10.0 was sending unknown messages, and would receive the following log line: `unable to parse message of unknown type: <unknown>`.  Perhaps our wires are crossed RE feature bits or something?  Original post: https://github.com/lightningnetwork/lnd/issues/5294

**Comment by cdecker** [comment]
Most likely it's a plugin using the `custommsg` RPC method. Without the type number it's hard to tell.

**Comment by niftynei** [comment]
Guessing they might be WARNINGs. iirc they were introduced in or about v0.10.0

https://github.com/lightningnetwork/lightning-rfc/pull/834

**Comment by cdecker** [comment]
Sounds like it, the log level was `INF` which I guess is `info`, so not fatal and `warnings` correctly use the even-odd semantics of numeric types. So just a bit of noise, nothing serious.

**Comment by Crypt-iQ** [comment]
Got it, just felt I should check and see if anything was amiss.  Odd warnings is probably what's going on since it's not a fatal error for lnd.
