### ISSUE TITLE
Problem with the getroute syntax

### ISSUE THREAD

**Issue by guibressan** [ElementsProject/lightning#4531]
I'm trying to get a route to a specific node excluding a channel

lightning-cli getroute -k id=02c156b8cef8f475699e68ada71e939a5bbf53fb802461624b20c5cafebb838aa8 msatoshi=1000000 riskfactor=5 exclude='["677247x718x1"]'

{
   "code": -32602,
   "message": "exclude: should be short_channel_id or node_id: invalid token '\"677247x718x1\"'"
}

**Comment by urza** [comment]
I am having the same issue. How did you resolve this?

**Comment by urza** [comment]
So the short_channel_id must also cointain direction /0 or /1 eg this is correct:
`exclude='["684710x2075x0/1"]'`

**Comment by vincenzopalazzo** [comment]
@urza I guess that the problem is `''` on the exclude, it is an array and not a string.

The correct command could be
`clightning getroute -k id=02c156b8cef8f475699e68ada71e939a5bbf53fb802461624b20c5cafebb838aa8 msatoshi=1000000 riskfactor=5 exclude=["677247x718x1"]`

**Comment by urza** [comment]
@vincenzopalazzo it actually needed also the channel direction `/1` or `/0` then it was happy

**Comment by vincenzopalazzo** [comment]
@urza right, I did note that :-) sorry
