### ISSUE TITLE
**BROKEN** Running lightning_openingd: Too many open files

### ISSUE THREAD

**Issue by KettleRecognize** [ElementsProject/lightning#4534]
I noticed in my logs a BROKEN tag:
2021-05-15T20:26:52.453Z **BROKEN** CHANNEL_PUBLIC_KEY-chan#3485: Running lightning_openingd: Too many open files

I've replaced the actual public key of the peer opening a channel with my node, with CHANNEL_PUBLIC_KEY.

**Comment by cdecker** [comment]
Depending on your OS, and its configuration each process (and its children) are allowed to open at most a fixed number of file-descriptors. These are used for all kinds of things, and in this case it's likely that `openingd` tried to connect or receive a connection, and the allocation of the file-descriptor for the socket failed.

You can check the limit (for your user) using the following:

```
ulimit -n
```

And you can raise it (for your user) using this:

```
ulimit -n unlimited
```

Notice that depending on your OS you might not be allowed to go above a certain size (so `unlimited` might not actually mean unlimited) and you might not be allowed to set the limits yourself. The `root` user will be able to set policies using `sysctl`.
