### ISSUE TITLE
fundchannel_start not working?

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#4562]
hey team,

this is the first time I've tried the fundchannel_start command, but I couldn't get it working. here are my steps to reproduce:

1. lightning-cli connect 020a1df50b701331a29782093210460b10eee0ac5ef6a01b9c51dff9b8fddf5fb0@170.75.170.23

(this is bullbitcoin's node)

```bash
   > lightning-cli listpeers | jq '.peers[] | select(.id=="020a1df50b701331a29782093210460b10eee0ac5ef6a01b9c51dff9b8fddf5fb0")'
{
  "id": "020a1df50b701331a29782093210460b10eee0ac5ef6a01b9c51dff9b8fddf5fb0",
  "connected": true,
  "netaddr": [
    "170.75.170.23:9735"
  ],
  "features": "2022aaa2",
  "channels": []
}
   > lightning-cli fundchannel_start 020a1df50b701331a29782093210460b10eee0ac5ef6a01b9c51dff9b8fddf5fb0  4000000
{
   "code": 305,
   "message": "Peer not connected"
}
 
```

not sure if I'm doing anything wrong...

I have `experimental-dual-fund` enabled but not sure if that matters...

**Comment by jb55** [comment]
uhh I think I wanted openchannel_init.. nm

**Comment by niftynei** [comment]
> I have experimental-dual-fund enabled but not sure if that matters...

Definitely matters. If you've both got `experimental-dual-fund` enabled, `fundchannel_start` shouldn't work. Error message should be clearer though...

The new hotness (which `fundchannel` and `multifundchannel` abstract away for you) is `openchannel_init`, `openchannel_update`, and `openchannel_signed`.

**Comment by jb55** [comment]
ah I figured it might have had something to do with that, I haven't used any of these calls so I wasn't sure. thanks @niftynei
