### ISSUE TITLE
established channel is offline, when trying to manually connect to it, i get update_fee 253 outside range 2642-188120

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#4564]
Hello,

I'm running fairly recent c-lightning from git, with the feeadjust and rebalanceall plugins.
I have an old established channel:
`listpeers` shows:

         "id": "026d4a5a0cfa2cf1f6bbf59ea53701e7f8e0a4dfaedefc56760f1d2e86b5d5d615",
         "connected": false,
         "channels": [
            {
               "state": "CHANNELD_NORMAL",
               "scratch_txid": "85f0780323d5975593c7a804858877aa7f23128ba6132b2163d612a19a57bb7d",
               "last_tx_fee": "15139000msat",
               "feerate": {
                  "perkw": 20909,
                  "perkb": 83636
               },
               "short_channel_id": "673599x1396x1",
               "direction": 1,
               "channel_id": "559677e9b991bf0d162673cf5bd826ebc3affceca7f4d384391690eed5735090",
               "funding_txid": "915073d5ee90163984d3f4a7ecfcafc3eb26d85bcf7326160dbf91b9e9779655",
               "close_to_addr": "bc1qdn57jjcq7spkdd3khrf3flzdznnnalgsqf9rnw",
               "close_to": "00146ce9e94b00f40366b636b8d314fc4d14e73efd10",
               "private": false,
               "opener": "remote",
               "closer": null,
               "features": [
                  "option_static_remotekey"
               ],
               "funding_allocation_msat": {
                  "026d4a5a0cfa2cf1f6bbf59ea53701e7f8e0a4dfaedefc56760f1d2e86b5d5d615": 2000000000,
                  "03c492f46d8e0a6256bb9c5c42f2aed24717f70a3f39e0961419dee511688e3110": 0
               },
               "funding_msat": {
                  "026d4a5a0cfa2cf1f6bbf59ea53701e7f8e0a4dfaedefc56760f1d2e86b5d5d615": "2000000000msat",
                  "03c492f46d8e0a6256bb9c5c42f2aed24717f70a3f39e0961419dee511688e3110": "0msat"
               },
               "msatoshi_to_us": 1012967067,
               "to_us_msat": "1012967067msat",
               "msatoshi_to_us_min": 0,
               "min_to_us_msat": "0msat",
               "msatoshi_to_us_max": 1939635512,
               "max_to_us_msat": "1939635512msat",
                              "msatoshi_total": 2000000000,
               "total_msat": "2000000000msat",
               "fee_base_msat": "974msat",
               "fee_proportional_millionths": 9,
               "dust_limit_satoshis": 546,
               "dust_limit_msat": "546000msat",
               "max_htlc_value_in_flight_msat": 18446744073709551615,
               "max_total_htlc_in_msat": "18446744073709551615msat",
               "their_channel_reserve_satoshis": 20000,
               "their_reserve_msat": "20000000msat",
               "our_channel_reserve_satoshis": 20000,
               "our_reserve_msat": "20000000msat",
               "spendable_msatoshi": 992967067,
               "spendable_msat": "992967067msat",
               "receivable_msatoshi": 922371933,
               "receivable_msat": "922371933msat",
               "htlc_minimum_msat": 0,
               "minimum_htlc_in_msat": "0msat",
               "their_to_self_delay": 144,
               "our_to_self_delay": 240,
               "max_accepted_htlcs": 30,
               "state_changes": [
                  {
                     "timestamp": "2021-03-07T19:44:20.629Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_NORMAL",
                     "cause": "remote",
                     "message": "Lockin complete"
                  }
               ],
               "status": [
                  "CHANNELD_NORMAL:update_fee 253 outside range 2642-188120",
                  "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
               ],               
               "in_payments_offered": 940,
               "in_msatoshi_offered": 255843964129,
               "in_offered_msat": "255843964129msat",
               "in_payments_fulfilled": 21,
               "in_msatoshi_fulfilled": 4328034512,
               "in_fulfilled_msat": "4328034512msat",
               "out_payments_offered": 897,
               "out_msatoshi_offered": 136039763951,
               "out_offered_msat": "136039763951msat",
               "out_payments_fulfilled": 11,
               "out_msatoshi_fulfilled": 3315067445,
               "out_fulfilled_msat": "3315067445msat",
               "htlcs": []

If i try to manually `connect 026d4a5a0cfa2cf1f6bbf59ea53701e7f8e0a4dfaedefc56760f1d2e86b5d5d615`, i get:

```{
   "id": "026d4a5a0cfa2cf1f6bbf59ea53701e7f8e0a4dfaedefc56760f1d2e86b5d5d615",
   "features": "0252a1",
   "direction": "out",
   "address": {
      "type": "torv3",
      "address": "hyceaimfgeuphjeggtijyxzdnz7viemxzbx6tu6wuproibq5hhlbktid.onion",
      "port": 9735
   }
}
```

But lightnignd says:

```
2021-05-28T18:20:19.687Z INFO    026d4a5a0cfa2cf1f6bbf59ea53701e7f8e0a4dfaedefc56760f1d2e86b5d5d615-chan#76092: Peer transient failure in CHANNELD_NORMAL: channeld WARNING: update_fee 253 outside range 2642-188120

2021-05-28T18:20:19.687Z UNUSUAL 026d4a5a0cfa2cf1f6bbf59ea53701e7f8e0a4dfaedefc56760f1d2e86b5d5d615-channeld-chan#76092: Status closed, but waitpid 20421 says No child processes

```

What does this mean? Is it a setting from my node, from his node, or was there always something wrong with this channel?

**Comment by cdecker** [comment]
Your node is expecting a feerate in the range of 2642-188120 perkw, while your peer expects the smallest possible fee of 253 perkw. These feerates have to match up in order to ensure both parties that an eventual close or penalty transaction can confirm in time. With your fee lowballing the feerate your node may not be able to react if the peer attempts to cheat, so your node refuses to reestablish the channel.

As for potential causes, the remote node's backend may have restarted (`bitcoind` may drop its mempool on restart causing it to not have accurate estimates for some time) or they may have switched to `-blocksonly` ( not receiving or sending transactions also causes an empty mempool resulting in broken estimates), or their backend is just really broken.

**Comment by thestick613** [comment]
Thank you. It would be helpful if these kind of error messages would be more verbose when they show up in clightning.

**Comment by cdecker** [comment]
Would it make sense to keep the short error message and reference a longer description in our documentation? I'm thinking something in the direction of rust error messages: short, concise and with links for more details.

**Comment by svpi11** [comment]
> Your node is expecting a feerate in the range of 2642-188120 perkw, while your peer expects the smallest possible fee of 253 perkw. These feerates have to match up in order to ensure both parties that an eventual close or penalty transaction can confirm in time. With your fee lowballing the feerate your node may not be able to react if the peer attempts to cheat, so your node refuses to reestablish the channel.
> 
> As for potential causes, the remote node's backend may have restarted (`bitcoind` may drop its mempool on restart causing it to not have accurate estimates for some time) or they may have switched to `-blocksonly` ( not receiving or sending transactions also causes an empty mempool resulting in broken estimates), or their backend is just really broken.

I was having the same issue with one of my channel, so thanks for this explanation. How is it possible to manually change the feerate expected from my node side ? 
Thanks
