### ISSUE TITLE
`channel_update` before `announcement_signatures`

### ISSUE THREAD

**Issue by nayuta-ueno** [ElementsProject/lightning#457]
channel establishment between `c-lightning` and our node 

1. `funding_signed`, broadcast funding_tx, confirmation 1, exchange `funding_locked`
2. disconnect our node
3. reconnect our node
4. wait ...

`c-lightning` sends `channel_update`.

**Comment by cdecker** [comment]
This should have been addressed in #466, can you confirm that?

**Comment by nayuta-ueno** [comment]
sorry too late reply.
At current version, c-lightning don't send `channel_update` .
close this issue.

**Comment by nayuta-ueno** [comment]
I send and receive `channel_reestablish`(next_local_commitment_number is 1), but c-lightning send `funding_locked`.
I send `funding_locked`, but c-lightning disconnect with below log:

```
lightning_channeld(31110): STATUS_FAIL_PEER_IO: bad reestablish msg: WIRE_FUNDING_LOCKED 00242bf2dd397d353cf1bb5f4106a50a94fd9f64b2d72a01d8b9cceb471fe91241940372e5c5568709142fd7ea95bca4e706a88dd6e617e740cb64e14f5db53ea4fa67
lightningd(23251): peer 038b95a8c2dfa198bc22893375708e1c4aee1518d0d64e5e7022fccee9ac2be6bd: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)
```

BOLT#2:
```
A node:
    if next_local_commitment_number is 1 in both the channel_reestablish it sent and received:
        MUST retransmit funding_locked.
```

**Comment by nayuta-ueno** [comment]
Content related to the title has been resolved, close it
