### ISSUE TITLE
fundchannel creates transaction that doesn't meet min relay fee

### ISSUE THREAD

**Issue by jonasnick** [ElementsProject/lightning#458]
I picked node `(03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134, 34.250.234.192)` from https://explorer.acinq.co and connected to it. Then I ran `fundchannel` which returned transaction 
```
020000000001012f54f57da379e25a42d241ed06e5738a03290a0eb76841e713897bfc455111430000000000ffffffff0240420f000000000022002016ceb906b4a5687d8b18c732293d4e3f29dc150ea455156c3c47d976cc0e1164ad73c000000000016001444cc4fd7393ba4530356037ec1cc2e5cccb857f302483045022100d32ba2250354ae7c9622426f4e241e5244c682121c15d1772eed5e4d0a963d1202207a61c11dae2c7273e8321b9f573395c7094d16bf7c9418738d58bdaebe7ee7b012103e1fcd13c423eafb133738462baae532e3da4212b3f68bb5e5caf040aad07493900000000
```
As usual, in order to get the txid I take the raw transaction and run `bitcoin-cli -testnet sendrawtransaction <tx>`, but this time I got 
```
error code: -26                                                                                                                                                                                                     
error message:                                                                                                                                                                                                      
66: min relay fee not met      
```
The input amount of the transaction is `0.04987420` the output amount is `0.04987274` resulting in a fee of 146 satoshi for 153 vbytes. This is smaller than the minrelayfee of 1 satoshi per byte. My bitcoind returns for `estimatesmartfee 1008` 1086 satoshi.
The channel state switched to `CHANNELD_AWAITING_LOCKIN` despite the error while sending the transaction. 
[debug.log](https://github.com/ElementsProject/lightning/files/1571909/debug.log)

**Comment by rustyrussell** [comment]
lightningd(10): Immediate feerate 988 (was 988)
lightningd(10): Normal feerate 271 (was 271)
lightningd(10): Slow feerate 271 (was 271)

That's 271 satoshi per kilasipa (FWIW, that normal feerate is estimatesmartfee 4 ECONOMICAL, divide by 4).  Which for a vbytes of 153 = 612 sipa, gives 165 satoshi fee.

I'm digging now; our estimate of how big the tx will be is too small.

**Comment by jonasnick** [comment]
Is it a bug that the channel state switched to `CHANNELD_AWAITING_LOCKIN` despite getting an error from bitcoind while sending the transaction?

**Comment by cdecker** [comment]
Depends on the error. "-25 - Missing inputs" for example is simply an indication that the transaction was already sent by the other endpoint.
