### ISSUE TITLE
Cannot find a route or pay with direct peer.

### ISSUE THREAD

**Issue by urza** [ElementsProject/lightning#4584]
I closed channel with peer (mutual close). Then I opened new larger channel with the same peer.

The new channel is reported as opened in NORMAL state:

from listfunds:
```
 "connected": true,
 "state": "CHANNELD_NORMAL",
```

from listpeers:
```
"state_changes": [
    {
       "timestamp": "2021-06-03T22:33:49.937Z",
       "old_state": "CHANNELD_AWAITING_LOCKIN",
       "new_state": "CHANNELD_NORMAL",
       "cause": "user",
       "message": "Lockin complete"
    }
 ],
 "status": [
    "CHANNELD_NORMAL:Reconnected, and reestablished.",
    "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
 ],
```

The old channel is already forgotten (closed yesterday).
Peer is online and responding to LN ping.
All balance is on my side of channel.

When I try to pay to this peer it fails.
When I try to find a route to this peer with getroute, it results in 
```
{
   "code": 205,
   "message": "Could not find a route"
}
```
Which is clearly wrong, because we have direct channel.

**Comment by urza** [comment]
When I try to find route with smaller amount to this peer, it finds routes going through other nodes, but never the direct channel. When I try larger sum that is avaliable on this channel, it finds no route at all.

It looks like c-lightning is internally somehow not aware of this channel, probably on `get_route` level.

**Comment by urza** [comment]
Update: someone successfully used this channel in their route (about cca 9 % of the balance was moved to the other side) however my c-lightnig still pretends the channel doesn't exists :(
Or to be more precise, the channel is reported as normal but I cant use it in any payment or get_route.

**Comment by m-schmoock** [comment]
@urza can you do a `lightning-cli keysend ...` to that peer?

**Comment by urza** [comment]
@m-schmoock is keysend yousing some other logic than `pay `and `get_route`? I can't really test keysend that much because small amount would go through other nodes and large amount would be problematic without invoice in this case..

**Comment by urza** [comment]
I tried to probe a route between me and the peer on https://lnrouter.app/probe  and it only returned routes via other nodes, not our direct channel..
But the channel is visible on 1ml.com

So both form outside and from my c-lightnig it looks like the channel exists, but it is not acutally usable. Any ideas what to do highly welcome.

**Comment by m-schmoock** [comment]
I don't know the details but from experience `keysend` prefers direct connected channels.

**Comment by niftynei** [comment]
Sounds like the new channel isn't being added to your routing table/gossip map. I've tagged @cdecker who's more of an expert on this, he's afk for a bit however.

**Comment by urza** [comment]
I've been looking into my lightningd.sqlite3 file to see if I can find something odd there when comparing with other channels.

**One possibly strange thing is:**
 Value of `Max_htlc_value_in_flight_msat`  on `Channel_config_remote` is very large **negative** number. All other active channels have large positive number in this column. The absolute value (ignoring the negative sign) is larger then channel size.

**Another difference** is that this is the only channel that replaced previous channel with the same peer, and for example in table `Channel_state_changes` there are some operations with the **old** channel after some operations with the **new** channel:
(id 13 is the new channel, 6 is the old channel)
   
```
13 | 574582801 | 2 | 3 | 2 | Lockin complete
6 | -155453985 | 9 | 8 | 2 | Onchain funding spend
6 | -135423796 | 8 | 9 | 2 | Onchain init reply
```

So maybe this could somehow confuse c-lightning?

Unfortunately I don't speak C lang very well, otherwise I would try to look to how get_route works, but I am not even sure I located it properly :)

Btw, unrelated question, how do you decode byte[] fields in db into readable strings? I tried common encodings like Utf8, ascii, unicode, but none seem to work..

**Comment by urza** [comment]
Strange things.

I discovered that:

1. I can find route with `getroute` command, but only when I set `riskfactor=50` and more. Also the amount must be over some value to find the route, e.g. for 10 000 sats it **doesn't** find the route, but for 1 000 000 it does.

2. So after I discovered that `getroute` can find route to this peer that consisted of only this hop for 1 000 000 sats, I tried to pay with `sendpay` (passing it the route result) such invoice to peer. But it failed to pay that with some strange messages from lightningd:

```
2021-06-10T20:07:38.533Z **BROKEN** gossipd: Could not find hop to {MY NODE PUBKEY}
2021-06-10T20:07:38.534Z INFO    gossipd: Could't find short enough route {MY NODE PUBKEY}-{PEER PUBKEY}
2021-06-10T20:07:51.371Z **BROKEN** gossipd: Could not find hop to {MY NODE PUBKEY}
2021-06-10T20:07:51.371Z INFO    gossipd: Could't find short enough route {MY NODE PUBKEY}->{PEER PUBKEY}
2021-06-10T20:18:23.541Z INFO    lightningd: Sending 1000000000msat over 1 hops to deliver 1000000000msat
2021-06-10T20:18:25.258Z INFO    {PEER PUBKEY}-chan#13: htlc 45 failed from 0th node with code 0x400f (WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS)
```

Note that ligtningd is reporting that it can't find hop to my own node.

@cdecker @rustyrussell Any idea what is going on? Should I just give up and close the channel? I would like to understand what is wrong here, it looks like this might be some bug.

**Comment by cdecker** [comment]
That sounds like there could be a large basefee, which makes the channel ineligible for the smaller amount but ok for larger amounts where the fixed basefee doesn't dominate the fee. Can you share the feerates as seen but your node for the path you expect to be returned?

**Comment by urza** [comment]
@cdecker Ha! Seems like you are right. My ppm fee for that channel was 10x larger, probably one "0" by mistake. With this fixed getroute is returning routes as I would expect.

**Comment by urza** [comment]
Thanks  @cdecker  seems like my channel is working normally.

This, however, opens some questions. The ppm fee was se to 500 ppm instead of 50. With 500 ppm I wasn't able to `pay` or find route with `getroute` to my direct peer. I would expect that with direct peer I should be able to use that channel regardles. Why wasn't I? Why wasnt `getroute` able to find the route consisting of our one direct channel?

**Comment by urza** [comment]
I am closing this issue. My conclusion is that the behavior was unusual and might be indication of some bug in some edge case. I would say that it might be related to closing and opening new channels with the same peer. Maybe the new channel was not properly announced or something and when I changed fees it helped to "correct". AFAIK when the channel was opened I should have been able to send from me to my direct peer regardless of the fees and other factors.

**Comment by jsarenik** [comment]
@urza Maybe just leave this issue open for now, until @cdecker reflects on it. There is a lot of practical stuff in here and I agree that direct peers should not be stopped by ppm rate because direct peers do not pay fees to each other (at least in my experiments). Thank you!
