### ISSUE TITLE
Unable to/Slow start: UNUSUAL plugin-fetchinvoice: Killing plugin: timed out before replying to init

### ISSUE THREAD

**Issue by hosiawak** [ElementsProject/lightning#4586]
### Issue and Steps to Reproduce

I'm unable to start lightningd. It takes 11 minutes from the initial:

`2021-06-05T07:46:39.942Z DEBUG   lightningd: Opened log file lightningd.log`

to

`2021-06-05T07:57:40.903Z UNUSUAL plugin-fetchinvoice: Killing plugin: timed out before replying to init`
`2021-06-05T07:57:40.903Z **BROKEN** plugin-fetchinvoice: Plugin marked as important, shutting down lightningd!`

Most of these 11 minutes is spent in:

` wallet: Loading in HTLCs for channel`
`wallet: Restored 10 outgoing HTLCS`

I'm still running sqlite on this node. The db file size is ~ 3 GB.

Any help on how to mitigate it will be much appreciated.

**Comment by hosiawak** [comment]
After a bit of looking I found an option that can bypass this timeout:

`dev-builtin-plugins-unimportant`

It needs adding to `lightningd.conf`

This is a workaround for developers. Is this still an issue for regular users though and is this related to slow startup on sqlite ?

```
	stmt = db_prepare_v2(wallet->db, SQL("SELECT"
					     "  id"
					     ", channel_htlc_id"
					     ", msatoshi"
					     ", cltv_expiry"
					     ", hstate"
					     ", payment_hash"
					     ", payment_key"
					     ", routing_onion"
					     ", failuremsg"
					     ", malformed_onion"
					     ", origin_htlc"
					     ", shared_secret"
					     ", received_time"
					     ", we_filled"
					     " FROM channel_htlcs"
					     " WHERE direction= ?"
					     " AND channel_id= ?"
					     " AND hstate != ?"));
```

```
sqlite> .headers on
sqlite> pragma index_info('sqlite_autoindex_channel_htlcs_1');
seqno|cid|name
0|1|channel_id
1|2|channel_htlc_id
2|3|direction
```

```
sqlite> EXPLAIN QUERY PLAN SELECT id, direction, channel_htlc_id,channel_id, hstate FROM channel_htlcs WHERE direction=0 AND channel_id = 31 and hstate != 0;
QUERY PLAN
`--SEARCH TABLE channel_htlcs USING INDEX sqlite_autoindex_channel_htlcs_1 (channel_id=?)
```

This query exectues for several seconds per channel on my machine. It seems sqlite is not using this index fully, only the `channel_id` part because `channel_htlc_id` is missing in `WHERE`. If I add I get full utilisation of the index and immediate query results:

```
EXPLAIN QUERY PLAN SELECT id, direction, channel_htlc_id,channel_id, hstate FROM channel_htlcs WHERE direction=0 AND channel_id = 31 and channel_htlc_id = 2520 and hstat
e != 0;
QUERY PLAN
`--SEARCH TABLE channel_htlcs USING INDEX sqlite_autoindex_channel_htlcs_1 (channel_id=? AND channel_htlc_id=? AND direction=?)
```

Do we need another index on (channel_id, direction, hstate) ?

**Comment by cdecker** [comment]
Very interesting, that must be one busy node you run :-)

Sounds like you pretty much did all the leg work already on what we should do. I think adding a composite index on `(channel_id, hstate)` should work. Can you benchmark whether adding `direction` to it as well changes things considerably? There are only 2 possible values so it shouldn't make a huge difference.

**Comment by hosiawak** [comment]
After looking again at this I concluded that this must have been an intermittent hardware issue (disk) on my node.

Today when I restart lightningd I'm not seeing the slowdown. Looks like the query utilising only the channel_id part of the index is sufficient. Startup takes a couple of seconds.

I'll close this issue then and keep an eye on startup times.
