### ISSUE TITLE
feature request: list of recently-failed payments

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/lightning#4588]
Got a request to be able to see what the most recent payment failures were for a node, as a way to help decide where to place channels.

**Comment by vincenzopalazzo** [comment]
>Got a request to be able to see what the most recent payment failures were for a node

Maybe we can add a flag to the listpays to return a channel that has some status (I assume that this flag not exist at the moment)? I worked on del pay command and maybe this task can be not too difficult for me. If you want can assign to me it 😸 

With the flag and the listpays sorted by `create_at` #4518  we can solve the problem easily
