### ISSUE TITLE
pyln.client throws errors on pytests using rpc call `fundchannel` 

### ISSUE THREAD

**Issue by gijswijs** [ElementsProject/lightning#4592]
Lately I have been having issues running tests on a plugin that I am writing. You can reproduce the error by running a pytest on any plugin in https://github.com/lightningd/plugins repo that using the fundchannel rpc call.

```
pyln.client.lightning.RpcError: RPC call failed: method: fundchannel, payload: {'id': '022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59', 'amount': 1000000, 'announce': True}, error: {'code': -1, 'message': 'They sent error channel d73b9f4a10671fdf5d5cbc6f82191615042afa230563147840ce3df96b078555: You gave bad parameters: feerate_per_kw 253 below minimum 1875', 'data': {'id': '022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59', 'method': 'fundchannel_start'}}
```

I understand the error, but I am unsure where pyln gets its config from. Where is that minimum of 1875 set? I was under the impression that feerates where ignored in tests.

I am pretty sure this is not a bug, but just me not understanding it properly, but I've exhausted all options I could think of. Also I remember these test did work before, so maybe something has changed I am unaware of?

**Comment by vincenzopalazzo** [comment]
Hi @gijswijs,

What is your version of bitcoind? and also the network where you are testing your plugin?

>Where is that minimum of 1875 set?

On mainet and testnet this is defined from the estimation fee method by bitcoind, for regtest I don't know maybe the same?.

**Comment by gijswijs** [comment]
I am using bitcoind: v0.21.1

I got it working again today by *not* using `pip` to install the tools: `pip3 install pyln-client pyln-testing`, but instead use the `$PYTHONPATH` environment variable: `export PYTHONPATH=/path/to/lightning-repo/contrib/pyln-client:/path/to/lightning-repo/contrib/pyln-testing:$PYTHONPATH`

**Comment by gijswijs** [comment]
I was running lightningd in a real recent build from May 21st.
The latest version of pyln-client and pyln-testing that `pip3` installs is the 0.10.0 release from April 1st.

On April 7 some [changes were committed](ttps://github.com/ElementsProject/lightning/commit/fad4aee5dae5d38612690152c58e807d470582f5#diff-9b44bf4ca265364c48b46bd915e1cda4e1d869b6707797fb3e10520925a81446) that seem to have changed the behavior of fundchannel in pyln-client. So I think there was some conflict between the lightningd I was running and the pyln-client and pyln-testing that I installed using `pip3`. I didn't dig deeper to confirm my suspicion, but went out on a limb and closed this issue.

I just wasn't aware that I was running bleeding edge lightningd (in my test environment).

If you live at the bleeding edge, you die on the bleeding edge.
