### ISSUE TITLE
Unit confusion

### ISSUE THREAD

**Issue by casey** [ElementsProject/lightning#4593]
I mixed up msats and sats today while trying out c-lightning on testnet, and I wonder if this might be something worth thinking about.

In this case, I used `lightning invoice` to create and pay invoices, and then used `lightning close ADDR` to close the channel. When I looked at the closing transaction, I was expecting to see an on-chain output sent to `ADDR`. However, there wasn't any, and in fact, all the funds went to my counterparty.

What happened was that the invoices that I created and paid were in millisatoshis, when I thought that they were in satoshis.

I think that my confusion stemmed from the fact that some `lightning` commands take msats, and some take sats.

Of course, I should have done a better job of reading the docs, which list the correct units for each command. However, it might be worth thinking about how to make this mistake less likely to happen, since I suspect others might also make it, or at least be confused by the inconsistency.

It would be nice if all commands took the same unit when a bare integer is passed, and allowed using a suffix to select a different unit.

I personally would like it if all commands took satoshis by default, and allowed specifying msats with `Nmsat`, or a decimal (`xyz.abc`, where `xyx` is the number of satoshis `abc` is the number of millisatoshis.). I prefer satoshis because it's a common unit outside of the Lightning ecosystem, whereas msats are lightning-specific. Of course, this is a matter of personal preference.

Unfortunately, that would be a breaking change to the UI, and invocations that previously worked would still work but change meaning, which is probably the worst kind of breaking change.

An alternative to this would be to allow all commands to take suffixed-integers, and then phase-out bare integers. This would also be a breaking change, but it would have the advantage that invocations that worked before would break, and the invokers would presumably notice and fix them.

**Comment by cdecker** [comment]
Indeed we are migrating to suffixed amount in all the RPCs, so `123sat` or `123456msat` should already work everywhere. The bare integer format is currently being phased out, but not yet guarded by deprecation markers.

The logic for bare integers is that anything that touches onchain transactions is denominated in sats, while off-chain RPCs are in msats, though some commands aren't clearly one side or the other (fundchannel specifically which is both)
