### ISSUE TITLE
Reconnection issues after IP address change.

### ISSUE THREAD

**Issue by viaj3ro** [ElementsProject/lightning#4600]
I'm having this issue after an IP address change: https://github.com/lightningnetwork/lnd/issues/5377

>> if you change your IP address, your peers won't reconnect to you. They'll wait for you to connect to them and then will store your new IP address for future reconnections (ie they don't trust the new IP address from node_announcement alone)

> This leads to a situation where even some clearnet peers have to be manually reconnected which can be quite time consuming and TOR peers are stuck in a deadlock that can only manually be resolved by the node operator of each and every TOR peer. They would have to look up the new IP address of their offline peer on one of the lightning explorer websites and manually feed it to their node. This is unlikely to happen quickly, if at all.

How is c-lightning behaving in this situation?

**Comment by cdecker** [comment]
c-lightning will try to reconnect to the any address it knows about the peer, whether that comes from a previous connection or the gossip. So in case you changed your IP address we will attempt to connect to the old one but also listen for new `node_announcements` from your node to learn its new IP address. Upon learning a new address we will eventually connect to that address.

You can also attempt to reconnect manually should you know the new address by calling `connect` with the `node_id` and the new IP address. If there are additional sources of addresses we can integrate them to include them in our reconnection attempts.
