### ISSUE TITLE
Use `RETURNING` instead of `last_insert_id`

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#4631]
I'm trying to make c-lightning work with [CockroachDB](https://github.com/cockroachdb/cockroach), mostly because it has some built-in syncing capabilities that look easy enough for me (I haven't really tried) and I am too dumb to get Postgres replication done right.

I imagine it would be just plug and play on c-lightning since they have the same language as Postgres. So far I had to do two or three small changes, but the next one is slightly bigger: Unlike Postgres, CockroachDB doesn't support `lastval()` to retrieve the id of the last row inserted. The only way to get the id is by using the `RETURNING` statement in the `INSERT` query.

Since both Postgres and SQLite also support this, can we change the code to use that instead? If this is ok I can work on a PR.

(I'll also see later what else breaks, so I'll only open the PR if Cockroach is fully working, but I still wanted to check if this was desirable before starting.)

**Comment by cdecker** [comment]
Awesome work on getting cockroachdb to work with c-lightning, definitely looking forward to seeing this work :+1:

As you correctly point out the main issue is that `RETURNING` needs to be supported by all other DBs, which sadly in sqlite's case is not true for some platforms we support. SQlite [introduced](https://www.sqlite.org/lang_returning.html) support only in version 3.35.0 (2021-03-12), which no distro ships in an LTS release yet.

We have two options:

 - Vendor the sqlite3 source code in `external/` like we do with some other dependencies, at the cost of longer compile times, larger binaries, etc
 - Add a cockroachdb specific driver to the DB abstraction layer, and implement rewrite rules in `devtools/sql-rewrite.py` to add the `RETURNING` suffix and then stash it in the driver itself (https://www.cockroachlabs.com/docs/stable/insert.html?#insert-and-return-values).

I personally prefer the second, but am open to discussing vendoring as well if it doesn't burden maintenance too much :-)

**Comment by fiatjaf** [comment]
Oops, then the task is much bigger than I expected.

Maybe we should wait two years and then require SQLite 3.35? I once tried to compile SQLite myself and failed, for that reason I dislike the first option very much.

Gonna look into the first.

**Comment by fiatjaf** [comment]
I think there is a workaround that can be done on CockroachDB side. Will close this and try to go that route.

**Comment by JosephGoulden** [comment]
Hi @fiatjaf did you ever get this working? It's been three years now so all platforms should have at least SQlite version 3.35.0.

**Comment by fiatjaf** [comment]
No, I think I gave up.
