### ISSUE TITLE
Please clarify "multifundchannel"

### ISSUE THREAD

**Issue by hMsats** [ElementsProject/lightning#4642]
The option ```multifundchannel``` is totally unclear (to me). I know it's still experimental, but still.

To use it: 

"destinations is an array of objects, with the fields". What does an "array of objects" look like? I have no idea. PLEASE ADD AN EXAMPLE! For example, somewhere [here](https://lightning.readthedocs.io/lightning-multifundchannel.7.html).

Is it:

`lightning-cli id=123 amount=100000 id=456 amount=150000 feerate=5000perkb`

or something like this

`lightning-cli destinations={123 100000 456 150000} feerate=5000perkb`

Is it JSON related? A simple example would clear it all up.

Also, in the `lightning-cli help` add an example. The use of the "=" is also not obvious, could just as well have been a space. I know that now but in the past I had to find that out by googling. 

Finally: thanks for all the hard work 😀

**Comment by LightningHelper** [comment]
@rustyrussell

**Comment by LightningHelper** [comment]
@ZmnSCPxj ?

**Comment by LightningHelper** [comment]
Should look something like that:
https://github.com/ElementsProject/lightning/issues/4100#issuecomment-701004517
@cdecker

**Comment by hMsats** [comment]
Such an example is indispensable in: `lightning-cli help multifundchannel`

**Comment by LightningHelper** [comment]
I agree..

**Comment by openoms** [comment]
My favourite format (also json autoformatting tools help - like `CTRL`+`SHIFT`+`i` in VSCode):
```
₿ cl multifundchannel '[
    {
        "id": "nodeID1",
        "amount": "amount_in_sats"
    },
    {
        "id": "nodeID2",
        "amount": "amount_in_sats"
    },
    {
        "id": "nodeID3",
        "amount": "amount_in_sats"
    },
    {
        "id": "nodeID4",
        "amount": "amount_in_sats",
    }
]' 1000perkb
```

Returned output:
```
{
    "tx": "RAW............TX",
    "txid": "TX................ID",
    "channel_ids": [
        {
            "id": "nodeID1",
            "channel_id": "CHANNEL_ID2",
            "outnum": 3
        },
        {
            "id": "nodeID2",
            "channel_id": "CHANNEL_ID1",
            "outnum": 4
        },
        {
            "id": "nodeID3",
            "channel_id": "CHANNEL_ID4",
            "outnum": 1
        },
        {
            "id": "nodeID4",
            "channel_id": "CHANNEL_ID3",
            "outnum": 2
        }
    ],
    "failed": []
}
```

**Comment by Donach** [comment]
This is still not clarified in the documentation...

**Comment by vincenzopalazzo** [comment]
I guess the docs is clear?

>The multifundchannel RPC command opens multiple payment channels
with nodes by committing a single funding transaction to the blockchain
that is shared by all channels.

You can open N channel with a single funding transaction, we use this command inside the fundchannel, so you can consider it like a low level command

Closing this, because I think our docs is pretty clear

**Comment by Donach** [comment]
As ppl abov noted, it lacks any examples. I had quite troubel building the proper 'array' of destinations, eventually found out somewhere out of the docu, which was terring me it's not complete.
If you add a simple example, that would be totally enough :)

**Comment by vincenzopalazzo** [comment]
>If you add a simple example, that would be totally enough :)

Ok reopening and I will do tomorrow

**Comment by hMsats** [comment]
Thanks a lot for the example that has been added to the docs! Closing this issue.
