### ISSUE TITLE
`update_fail_htlc.reason` is not long enough to decode

### ISSUE THREAD

**Issue by nayuta-ueno** [ElementsProject/lightning#465]
1. Establish channel only 2 nodes(`A` and `B`)
2. `A` sends `update_add_htlc`(but, `outgoing_cltv_value` / `cltv_expiry` equal 0) to `B`
3. `A` and `B` exchange `commitment_signed`, `revoke_and_ack`.
4. `B` think `WIRE_FINAL_EXPIRY_TOO_SOON` (`c-lightning` log)
5. `B` sends `update_fail_htlc` to `A`

`update_fail_htlc.len` equal 2.
[BOLT4's format](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#returning-errors)(previous obscured) is longer than 2.

**Comment by rustyrussell** [comment]
As I read it final expiry_too soon has no data: it's just a type, which is 2 bytes?

**Comment by nayuta-ueno** [comment]
Maybe random 2bytes...

I think that `expiry_too_soon` shall be `failure_len` == 2.
But I receive `update_fail_htlc` reason length == 2, so cannot decode `reason`.

**Comment by cdecker** [comment]
@nayuta-ueno do you have an example of the error message so we can disect it together and clear up any misunderstanding?

If I read the spec correctly this is a valid error of type `expiry_too_soon` (aside from the HMAC of course)

```
0000000000000000000000000000000000000000000000000000000000000000 (hmac)
0002 (failure_len)
0011 (final_expiry_too_soon)
0004 (pad_len)
00000000 (padding)
```

I think maybe you are mixing `final_expiry_too_soon` and `expiry_too_soon`? The former is just 2 bytes which specify the type and an empty payload, while the latter requires a `channel_update` as payload.

**Comment by nayuta-ueno** [comment]
(using `regtest`)

c-lightning log:
```
lightningd(17687): peer 021b99745df3212c1dbbb8a06426b639faf3c3ce7f8b709a7853050206c8eb1114: got revoke 0: 1 changed
lightningd(17687): peer 021b99745df3212c1dbbb8a06426b639faf3c3ce7f8b709a7853050206c8eb1114: HTLC in 0 SENT_ADD_ACK_COMMIT->RCVD_ADD_ACK_REVOCATION
lightningd(17687): peer 021b99745df3212c1dbbb8a06426b639faf3c3ce7f8b709a7853050206c8eb1114: Expiry cltv too soon 487 < 487 + 6
lightningd(17687): peer 021b99745df3212c1dbbb8a06426b639faf3c3ce7f8b709a7853050206c8eb1114: failed htlc 0 code 0x0011 (WIRE_FINAL_EXPIRY_TOO_SOON)
```

I receive BOLT message:
```
0083eff68aae7d565ec2fb0c3a2ef944ac8b64747dbae860bf06f3e1b2b5b751b29f00000000000000000002ebad
```

decode
```
[update_fail_htlc]
channel-id: eff68aae7d565ec2fb0c3a2ef944ac8b64747dbae860bf06f3e1b2b5b751b29f
id: 0
len= 2
reason: ebad
```

**Comment by cdecker** [comment]
Could it be that this was resolved by merging #858?

**Comment by ZmnSCPxj** [comment]
Not @nayuta-ueno, but I believe #857 turns out to be a duplicate of this issue, and as #858 resolves it, I think we can close this issue too.

**Comment by nayuta-ueno** [comment]
Thanks @ZmnSCPxj !
I can not make an environment to test right now...
I think its OK.
