### ISSUE TITLE
Documentation missing for pay's localofferid argument

### ISSUE THREAD

**Issue by shesek** [ElementsProject/lightning#4665]
It is mentioned as the last argument for `pay` in `lightning-cli help`:

> `pay bolt11 [msatoshi] [label] [riskfactor] [maxfeepercent] [retry_for] [maxdelay] [exemptfee] [localofferid]`

But it doesn't show up in [`lightning-cli help pay`](https://github.com/ElementsProject/lightning/blob/master/doc/lightning-pay.7.md).

**Comment by shesek** [comment]
BOLT 12 does specify that the offer creator 'MUST set `description`' , but its unclear to me whether an empty string should satisfy this requirement or not. If not, I guess that `offer`/`offerout` should probably prevent the user from creating the offer to begin with?

**Comment by rustyrussell** [comment]
Yeah, it's sort of hidden for internal use at the moment (it's used when we try to pay out an invoice for a send_invoice offer, so that we close the offer as soon as the payment succeeds so we won't pay twice)

I will document it next release, when I know it's stable...
