### ISSUE TITLE
Offers with an empty description can be created but not decoded

### ISSUE THREAD

**Issue by shesek** [ElementsProject/lightning#4667]
Decoding them fails with: `string: Invalid signature: invalid token`.

Reproducible with: `lightning-cli decode $(lightning-cli offer 9 '' | jq -r .bolt12)`

I'm running v0.10.0.

**Comment by shesek** [comment]
BOLT 12 does specify that the offer creator 'MUST set `description`' , but its unclear to me whether an empty string should satisfy this requirement or not. If not, I guess that `offer`/`offerout` should probably prevent the user from creating the offer to begin with?

**Comment by rustyrussell** [comment]
Yes, empty string should *work*, though it's not exactly a description :)
