### ISSUE TITLE
A node send a close transcation that does not go into the mempool and at the same time another channel is opened

### ISSUE THREAD

**Issue by LightningHelper** [ElementsProject/lightning#4673]
Hi,
Something that I just noticed, I (node-A) had a channel with another node (node-B, B->A), and I wanted to open a new channel with node-B. As you know it is not possible to have 2 channels with the same node :/ - 
https://github.com/ElementsProject/lightning/issues/2001#issuecomment-884389007

So the node-B closed the channel, and at the moment that he send the closing transaction I could already open a new channel A->B. What would have happen if the transaction would have a too low of a fee and rejected from the mempool (I know it is not very likely, but is possible), will I then have 2 channels with this node? Or is it a bug. I assume that as long as you don't allow two channels with the same node, you should wait until the channel is closed before allowing a new channel to open. (Also what about reorg?) 

Thanks

**Comment by rustyrussell** [comment]
No, you can have two channels (or more!) with the same node, just not active at the same time.  As soon as you close one, you can open another.

**Comment by whitslack** [comment]
I think what Rusty is saying is that it doesn't matter whether the closing transaction ever confirms, for the purposes of opening another channel. C-Lightning will no longer service the first channel as though it were an open channel, regardless of whether the closing transaction ever confirms.

**Comment by LightningHelper** [comment]
Excellent, so there is no bug hiding and the edge case was considered.
