### ISSUE TITLE
when opening a new large channel, the maximum amount that i can send is 4294967

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#4695]
Is this right?

After a few back and forth payments in the channel, the amount increases.

**Comment by rustyrussell** [comment]
Set wumbo in config file?

**Comment by thestick613** [comment]
Yeah, i'm running with --wumbo.
I'm taking these values from:

                i_can_pay = (channel["spendable_msatoshi"]) // 1000
                i_can_be_payed = (channel["msatoshi_total"] - channel["msatoshi_to_us"] + channel["their_channel_reserve_satoshis"]) // 1000

I have multiple new channels i opened where i_can_pay is exactly 4294967. Once a few payments get routed to that channel, i_can_be_payed increases. Is this normal?

**Comment by thestick613** [comment]
So, are these values correct? I just opened a 10M channel to a node.
`listpeers` told me that i_can_pay was 4294967sat to that node.
I sent an invoice of 6M sat to that node and c-lightning didn't use that channel exclusively. It routed ~3M with it and the rest through other channels.
Is this expected? Is the `spendable_msatoshi` 4294967295msat limit real?

```
lightning-cli  listpeers | grep 4294967
               "receivable_msatoshi": 4294967295,
               "receivable_msat": "4294967295msat",
               "spendable_msatoshi": 4294967295,
               "spendable_msat": "4294967295msat",
               "receivable_msatoshi": 4294967295,
               "receivable_msat": "4294967295msat",
               "spendable_msatoshi": 4294967295,
               "spendable_msat": "4294967295msat",
               "receivable_msatoshi": 4294967295,
               "receivable_msat": "4294967295msat",
               "receivable_msatoshi": 4294967295,
               "receivable_msat": "4294967295msat",
               "spendable_msatoshi": 4294967295,
               "spendable_msat": "4294967295msat",
               "spendable_msatoshi": 4294967295,
               "spendable_msat": "4294967295msat",
               "receivable_msatoshi": 4294967295,
               "receivable_msat": "4294967295msat",
               "spendable_msatoshi": 4294967295,
               "spendable_msat": "4294967295msat",
               "receivable_msatoshi": 4294967295,
               "receivable_msat": "4294967295msat",
               "spendable_msatoshi": 4294967295,
               "spendable_msat": "4294967295msat",
               "receivable_msatoshi": 4294967295,
               "receivable_msat": "4294967295msat",
               "spendable_msatoshi": 4294967295,
               "spendable_msat": "4294967295msat",
```

**Comment by thestick613** [comment]
Found this: https://rusty-lightning.medium.com/bitcoin-lightning-faq-why-the-0-042-bitcoin-limit-2eb48b703f3
