### ISSUE TITLE
Feature request: Allow invoice creation with description_hash instead of description. 

### ISSUE THREAD

**Issue by Kukks** [ElementsProject/lightning#4705]
BOLT11 specifies that an invoice must be created with `description` OR `description_hash`. However, CLightning only allows `description.` A previous attempt was made by @fiatjaf in https://github.com/ElementsProject/lightning/pull/3045 but was abandoned. 

It seems like it should not be too hard to implement this (as fiatjaf actually has a plugin doing just this https://github.com/fiatjaf/sparko/tree/master/invoicewithdescriptionhash). Unfortunately, my C experience is laughable and would go far to get the ball rolling.

The reasoning for wanting this baked in instead of a plugin is because I would not expect or demand users on BTCPay to install a lightning plugin (requires handling some bash commands which may be too much for some) for a feature that is part of the base spec.

Use-case: [LNURL-pay](https://github.com/fiatjaf/lnurl-rfc/blob/luds/06.md)

**Comment by vincenzopalazzo** [comment]
I think that this functionality was removed in some release ago, as rusty describe in the PR.

>I ripped that functionality out a few versions ago. There's currently no transport which handles an external description, so the recommendation is to avoid description_hash for now.

And, according to with fiatjaf comment (reported below), the offers that are finally out can solve this problem in a better way?

>I didn't think that transport should be something standardized and specified in the BOLTs. But now if we're going to have "offers" that could be it.

P.S: Not a expert with LN-URI, I can missing somethings

**Comment by Kukks** [comment]
> I think that this functionality was removed in some release ago, as rusty describe in the PR.
> 
> > I ripped that functionality out a few versions ago. There's currently no transport which handles an external description, so the recommendation is to avoid description_hash for now.
> 
> And, according to with fiatjaf comment (reported below), the offers that are finally out can solve this problem in a better way?
> 
> > I didn't think that transport should be something standardized and specified in the BOLTs. But now if we're going to have "offers" that could be it.
> 
> P.S: Not a expert with LN-URI, I can missing somethings

The lightning implementation shouldn't be concerned of how I transport a trivial string, just provide a hash for the payee to verify it on their own.

Bolt12 may offer another way but I would like to also support other solutions which also utilize the bolt11 spec.

**Comment by laanwj** [comment]
> but FWIW here's a branch that adds an optional description_hash parameter to invoice 

So I did PR it, and I think the PR (#4892) is more or less ready, but it could use some testing and review/ACKs.
