### ISSUE TITLE
closing incorrectly using `fee_range`

### ISSUE THREAD

**Issue by t-bast** [ElementsProject/lightning#4715]
Our node received some warnings that seems to indicate a c-lightning node that wants to use https://github.com/lightningnetwork/lightning-rfc/pull/847 improperly: `Feerange 177sat-182sat below minimum acceptable 183sat`

I observe the following flow of messages:

```
  c-lightning                      eclair
       |                              |
       |          shutdown            |
       |----------------------------->|
       |          shutdown            |
       |<-----------------------------|
       |   closing_signed (183 sat)   |
       |----------------------------->|
       |   closing_signed (176 sat)   |
       |<-----------------------------|
       |           warning            |
       |----------------------------->|
```

And then the c-lightning node disconnects.
The `closing_signed` messages do **not** contain a tlv stream with a `fee_range`, so it should use the legacy closing negotiation flow instead of disconnecting and refusing to make progress.

I don't know what version of c-lightning our peer is using, I can share their `node_id` if that's useful.

**Comment by rustyrussell** [comment]
I saw this too, closing with a c-lightning node. It's complaining because it considers 183 the minimum valid fee.  It probably started at (say) 183-1000, then it sent 183, and when it gets 176 the possible range is now 175 - 182, which is below its minimum.

I *think* this is OK...
