### ISSUE TITLE
Severe performance regression in listchannels

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#4718]
### Issue and Steps to Reproduce

Choosing one SCID at random and requesting the half-channels for that SCID:
```
$ time scid="$(lightning-cli listpeers | jq -r '.peers[].channels[].short_channel_id' | shuf | head -n1)"

real    0m0.783s
user    0m0.156s
sys     0m0.028s

$ time lightning-cli listchannels "${scid}" >/dev/null

real    0m0.763s
user    0m0.000s
sys     0m0.002s
```

This used to be very fast — fast enough that my channel overview script could call `listchannels` for each and every one of my channels in a loop and would finish within a few seconds. After I upgraded to C-Lightning 0.10.1, suddenly my script became very slow, printing about a channel per second (or maybe slightly faster) and taking several minutes to dump out the info of all of my channels. To regain usable performance, I had to rewrite my script to make only two calls to `listchannels` (one to list all the inbound half-channels and one to list all the outbound half-channels) and then index into those results for each channel returned from `listpeers`, whereas previously I had been calling `listchannels` once per SCID.

I suspect that 1a7731cfbf87bbab077a6e77eb81f090300a9179 may be the cause of the regression, as that change makes `listchannels` perform a sub-call to `listpeers`, which is a slow operation because it asks the database backend to perform a sequential scan on the `channel_state_changes` table for each and every channel it returns. Moreover, it looks to my eye as though `listchannels` is fetching information about *all* peers even when only specific channels are being inquired about. That's an awful lot of wasted effort to look up all those state changes that aren't even used for anything.

While running my original channel overview script (before my rewrite), my PostgreSQL server process was pegging the CPU, and polling of the `pg_stat_activity` table showed that the server was nearly always busy executing this query: `SELECT timestamp, old_state, new_state, cause, message FROM channel_state_changes WHERE channel_id = $1 ORDER BY timestamp ASC;`. That comes from `json_add_channel(…)` in `lightningd/peer_control.c` calling `wallet_state_change_get(…)` in `wallet/wallet.c`. Running an `EXPLAIN SELECT` for that query reveals that it's doing a sequential scan of the `channel_state_changes` table. Indeed, there are no indices defined on that table.

My best guess about how to fix this would be for `listchannels` only to request info about the peers that it actually cares about, rather than requesting info about *all* peers. Either that or make `listpeers` accept an (undocumented?) argument to suppress the `state_changes` members in the returned results so that all those sequential scans of the `channel_state_changes` table aren't executed only to have their results discarded.

**Comment by rustyrussell** [comment]
Thanks for the report!  I only have about 40 peers, so it's blazingly fast here.

We could avoid this call if none of the interesting results are our own peers, but I think it's better to put in an index to speed up listpeers.  Unfortunately this call has grown to do "listlocalchannels" as well; might have been nicer to have this separate.

**Comment by whitslack** [comment]
> put in an index to speed up listpeers.

If you mean an index in the database, then that may help only slightly. You'd still effectively be doing a "client-side join," which is abysmal for performance. It'd be faster to perform **one** query of the `channel_state_changes` table to retrieve the state changes of **all** of the channels you're going to return from `listpeers`, rather than making one query per channel. I understand that the currently implemented function control flow does not make this convenient or pretty.

**Comment by rustyrussell** [comment]
Agreed it's awkward, and that doesn't actually help much in this case.  We'd be gathering all the info (e.g into a hashtable) then doing individual lookups as we go.  The db (with index) already does that internally, so it just saves some SQL interpretation time, which is not our problem here.

Ultimate answers include:
1. Split this API, it's dumb.
2. Switch from JSON RPC to GraphQL where you can specify what fields you actually want us to produce.

But meanwhile, if you do "CREATE INDEX channel_state_changes_channel_id ON channel_state_changes (channel_id);" does it restore performance?  That would be my anticipated fix; if you do it manually you can "DROP INDEX channel_state_changes_channel_id" afterwards and still be able to upgrade when the real fix is merged.

Thanks!

**Comment by whitslack** [comment]
> The db (with index) already does that internally, so it just saves some SQL interpretation time, which is not our problem here.

That's true only in the case of an in-process database such as SQLite. When using PostgreSQL, you also have to factor in the inter-process communication and the context switching and process scheduling latencies. Performing 750 queries sequentially to PostgreSQL over a Unix socket is going to suffer some noticeable latency versus performing one query and then collating the results in your own hashtable.

> But meanwhile, if you do "CREATE INDEX channel_state_changes_channel_id ON channel_state_changes (channel_id);" does it restore performance?

I'll give that a shot and report back. Probably tomorrow.

**Comment by rustyrussell** [comment]
Agreed.  We can go there if we need, but I'm lazy :)
