### ISSUE TITLE
Topology plugin spams "channel_update ignored: fee too large" warnings to stderr

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#4722]
### Issue and Steps to Reproduce

I happened to switch VTs back to my console today and noticed that agetty's login prompt had been scrolled off the screen by [`"channel_update %s ignored: fee %u/%u cltv %u too large"`](https://github.com/ElementsProject/lightning/blob/v0.10.1/common/gossmap.c#L505-L509) warnings emitted from the topology plugin. Those warnings are being emitted to stderr, which is `/dev/console` for my C-Lightning process since it is managed by OpenRC. It would be more appropriate to emit those warnings to the C-Lightning log, especially since they are unexceptional and do not require an administrator's attention.

### `getinfo` output
Release 0.10.1

**Comment by vincenzopalazzo** [comment]
I reproduce this bug with the new version of c-lightning, maybe it needs to be moved to the log stream?

**Comment by rustyrussell** [comment]
Yeah, it's a debugging hack which escaped the lab.  The gossmap code can't assume it's got logging access, so it dumps to stderr.
