### ISSUE TITLE
Strange peer in listpeers

### ISSUE THREAD

**Issue by LightningHelper** [ElementsProject/lightning#4733]
### Issue and Steps to Reproduce
Hello,
I have some peers in listpeers that do not have any channels do not exists in the graph, any idea what are those?

```
lightning-cli listpeers
.
.
.
      },
      {
         "id": "02729fe61278b96080c2b3e76dde76f5ef0b9f80d26717f4abfd7b35c86d085426",
         "connected": true,
         "netaddr": [
            "127.0.0.1:51670"
         ],
         "features": "0252a1",
         "channels": []
      }
   ]
}


```
02729fe61278b96080c2b3e76dde76f5ef0b9f80d26717f4abfd7b35c86d085426 is not available on 1ml and not in listnodes

`"version": "0.10.0"`

Should I just disconnect those peers?
Thanks

**Comment by niftynei** [comment]
These are peers that have established a connection to your node, but have not opened a channel.

You can add more of them to your list by running `lightning-cli connect <node_id>@<connstring>`.

`disconnect` should end their connection.

**Comment by LightningHelper** [comment]
Got it, thank you!
