### ISSUE TITLE
Feature suggestion: Better inspection of closed channels

### ISSUE THREAD

**Issue by urza** [ElementsProject/lightning#4734]
Inspecting closed channels is currently not easy with the cli. There is some information in db, but putting it together this way is obviously not ideal.

I noticed that this was already mentioned somewhere by @vincenzopalazzo but can't find it. 

Ideally I would like to be able to get this with clightning-cli somehow:

- list closed channels and their properties (e.g. was this public or private channel)
- type of close (mutual, unilateral)
- who initiated closing
- closing onchain tx id

**Comment by vincenzopalazzo** [comment]
Hi @urza, I started to work on one PR https://github.com/ElementsProject/lightning/pull/4568 to add this feature, but I think now it is a good moment to put this feature in the next release with this issue https://github.com/ElementsProject/lightning/issues/4729

It looks like already been taken, lets see what happens.

**Comment by rl-d** [comment]
@all, most of the data could be made available with an optional parameter to filter the peer channels by state (and I am happy to add that to issue #4729), but there would be two caveats with that approach:

1. after 100 blocks the channels wouldn't be reported anymore, and
2. the onchain tx id does not currently seem to be part of the peer channel data.

What is your advice?

**Comment by vincenzopalazzo** [comment]
I don't remember what are the data in the database about the closed channels, maybe @cdecker can help here. Or maybe you can tell MySQL to describe the table.

**Comment by rl-d** [comment]
Doing the documentation changes for this, I noticed there is a "scratch" tx id which I guess would be equivalent to @urza's onchain tx id of caveat #2 above. So I think the big points are covered at least.

If I've misunderstood anything, I stand to be corrected... thanks!

**Comment by rl-d** [comment]
It's been recommended that this be made a plugin, and the use case is such that it should list historical data (older than 100 blocks), so it's really out of scope for inclusion with issue #4729.

**Comment by cdecker** [comment]
Small correction: we no longer delete entries in the `channels` table as far as a I can see, so it should always be possible to retrieve at least some of the information in the table. We can definitely add an option to include closed channels as well, and should likely set that to true if we filter for `state=closed` as well.

**Comment by rl-d** [comment]
Thanks for the note @cdecker. I am working on a plugin that will implement a GraphQL interface for querying the data that the user is interested in, which (in light of your note) should satisfy this feature request nicely.

**Comment by urza** [comment]
Has there been any new development? What is the best way to inspect closed channels now? One of my channels was closed and I would like to know (using CLI):

- was it cooperative close?
- was it initiated by my node or my peer?
- are funds safu (onchain tx / address where my balance went)

**Comment by vincenzopalazzo** [comment]
There is a PR working in progress https://github.com/ElementsProject/lightning/pull/5022 after we have this one, I will try to include also the close channels with another PR

**Comment by urza** [comment]
Hello friends, was there some development in this area? Is there some way how to better inspect closed channels?

https://github.com/ElementsProject/lightning/issues/4734#issuecomment-1100421350

**Comment by vincenzopalazzo** [comment]
Hope to have this land https://github.com/ElementsProject/lightning/pull/5568 in this release and I will work on the close channel after that :-)
