### ISSUE TITLE
Add command to clean up inactive offers

### ISSUE THREAD

**Issue by jsarenik** [ElementsProject/lightning#4744]
### Issue and Steps to Reproduce

```
$ lightning-cli listoffers | grep active | grep false | uniq -c
      5          "active": false,
```

I would like to get rid of the inactive offers similarly to `delexpiredinvoice`.

### `getinfo` output

https://ln.bublina.eu.org/

**Comment by rustyrussell** [comment]
In general, I prefer not to delete records.  If an offer is unused and inactive, sure.

But the problem is that if we made invoices or payments they can refer to these offers (in the database), so if we delete the offer they will now lose information.  

This should definitely return the offers that were deleted, too.

**Comment by vincenzopalazzo** [comment]
>This should definitely return the offers that were deleted, too.

concept ack

>In general, I prefer not to delete records. If an offer is unused and inactive, sure.

>But the problem is that if we made invoices or payments they can refer to these offers (in the database), so if we delete the offer they will now lose information.

This looks a little bit dangerous for a user interface point of you, right? a user is assumed to delete all the offers and maybe don't want to remove the invoice related (we can make a propriety local_offer_id nullable?) I don't like that the Software will assume stuff, maybe we need to add another extra propriety (force = true?) to make sure that the user want delete also the invoices and payments related.

What do you think @rustyrussell ?

**Comment by jsarenik** [comment]
Closing.
