### ISSUE TITLE
wumbo still sets htlc_maximum_msat?

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#4746]
Reported on Telegram by Carlo:

my investigation into max_htlcs continues. I just opened a 0.17 channel with bullbitcoin.com (another c-lightning node I think). so the channel must be a wumbo channel, since it's larger than the cap. however, listchannels still gives me "htlc_maximum_msat": "4294967295msat" on both ends.

**Comment by carboncls** [comment]
Hi, thanks for opening this issue based on my report. Here is my environment:
Ubuntu LTS 20.04
c-lightning v0.10.1, installed from the github release page

The channel in question is between two c-lightning nodes, as `listpeers` reports `"DUALOPEND_OPEN_INIT"` (c-lightning currently is the only implementation to support this feature).
I used `multifund` to open this channel along with another, non-wumbo channel.

Additionally, to me it seems like many of my peers were wumbo-enabled, but "htlc_maximum_msat": "4294967295msat" always persisted, including to channels smaller than the cap.
