### ISSUE TITLE
topology debug output does not go to log-level

### ISSUE THREAD

**Issue by LightningHelper** [ElementsProject/lightning#4749]
### Issue and Steps to Reproduce
I've just updated to 0.10.1, and it seems that the topology output does not go to the debug file:

```
xxx:~$ lightningd --log-file=/log/log.txt --log-level=DEBUG
topology: channel_update 6****1 ignored: fee 1/141658111 cltv 34 too large
topology: channel_update 66***0 ignored: fee 0/500000000 cltv 100 too large
topology: channel_update 68***1 ignored: fee 0/500000000 cltv 100 too large
```

**Comment by vincenzopalazzo** [comment]
> 0.10.2

Maybe you mean the 0.10.1?

However, this should be fixed in the https://github.com/ElementsProject/lightning/pull/4730, so if you use the actual master, you should fix your issue.

**Comment by LightningHelper** [comment]
Yes. 0.10.1, sorry, I've fixed it. Anyway, closing as it is fixed
