### ISSUE TITLE
delinvoice not restricted to unpaid invoices

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#477]
The `delinvoice` RPC command is documented as the below:

    The *delinvoice* RPC command removes an unpaid invoice.  The caller
    should be particularly aware of the error case caused by a payment
    just before this command is invoked!

However, currently `delinvoice` also is able to delete paid invoices.

It seems there is no sensible reason to not allow deleting paid invoices, for instance, after the client has handled the payment and delivered the goods. Indeed, by my understanding, the switch to using `pay_index` instead of `label` in `waitinvoice` #474 is partly motivated by the possibility of deleting paid invoices: https://github.com/ElementsProject/lightning/pull/445#issuecomment-351973440

**Comment by rustyrussell** [comment]
Yes. Originally, invoices didn't have a timeout built-in, so I was scared of this race.

Now, what do we do about the race? We could refuse to delete an invoice which is still active, but that's annoying if there's some error and you really want to undo it.

I think we may need a flag here. paid, open, timed-out? Then the delete fails if it's not in the right state? Not sure though...

**Comment by ZmnSCPxj** [comment]
>I think we may need a flag here. paid, open, timed-out? Then the delete fails if it's not in the right state? Not sure though...

Do you mean, something like:

    SYNOPSIS
    --------
    *delinvoice* 'label' 'state'

    DESCRIPTION
    -----------
    The *delinvoice* RPC command deletes an invoice, as long as it is in
    the given 'state'. The 'state' can be the strings "UNPAID", "PAID", or
    "EXPIRED".

?

**Comment by ZmnSCPxj** [comment]
I'll do this after #597 gets either merged or closed.  I'll probably also do this after #502 so that I have an `EXPIRED` `enum invoice_status` to refer to.

Assuming #597 gets merged, the plan is to add an argument to `wallet_invoice_delete`: `bool wallet_invoice_delete(struct wallet *, const struct invoice *, enum wallet_status *)`.  The `delinvoice` command can accept `"any"` for the state, which outright deletes the invoice regardless of its current state.

**Comment by rustyrussell** [comment]
I've taken this as part of the JSONRPC fixes, since I want all the API breakage together....

**Comment by ZmnSCPxj** [comment]
Okay. I wanted to do this within `wallet_invoice_delete` and give it an additional `enum invoice_status *` (with NULL being "any"), but that would require adding `EXPIRED` status, which I intend to add at fixing #502.

But I suppose that would be an internal change and higher priority is to push the change to the RPC interface first, so OK.

Is the below draft for the interface change OK?


    SYNOPSIS
    --------
    *delinvoice* 'label' 'state'

    DESCRIPTION
    -----------
    The *delinvoice* RPC command deletes an invoice, as long as it is in
    the given 'state'. The 'state' can be the strings "UNPAID", "PAID", or
    "EXPIRED".  The 'state' can also be the string "any", in which case the
    invoice is deleted regardless of its state.

**Comment by rustyrussell** [comment]
Basically, yes.  Since I changed listinvoices to give 'status' I used the same name and values here for consistency.  See https://github.com/ElementsProject/lightning/pull/623/commits/ea1793a8cca5b8798419570451d6dd4a9a1d7e48
