### ISSUE TITLE
Building on Mac OS X

### ISSUE THREAD

**Issue by ddustin** [ElementsProject/lightning#4772]
The build bot uses an old version of python, 3.6.14. The 3.6 branch of python isn't compatible with Mac OS X 11.4+.

Is that version of python required to build and test the project?

I'm working through the issues to get stuff working on Mac one by one but just wanted to confirm later branches successfully build and test. I've currently been trying python 3.7.3, 3.9.1, and 3.9.6.

**Comment by vincenzopalazzo** [comment]
I think that there isn't a fixed required version of python3 to run the jobs

I'm developing with version 3.8.somethings

```
➜  ~ python3 --version               
Python 3.8.10
```

**Comment by cdecker** [comment]
We define 3.6.x as minimum, since we make extensive use of f-strings, but any version 3.6.0 or higher should work fine.

**Comment by ddustin** [comment]
Great thanks @vincenzopalazzo & @cdecker !
