### ISSUE TITLE
`Bad tx_signatures` in reply to `open_channel`

### ISSUE THREAD

**Issue by pm47** [ElementsProject/lightning#4787]
### Issue and Steps to Reproduce

c-lightning replies with `Bad tx_signatures` to eclair's `open_channel`. This seems related to dual-funding, which eclair doesn't support yet, and feature `option_dual_fund` is disabled. Not sure what is going on on c-lightning's side or why it expects a `tx_signatures` message.

```
Bad tx_signatures 00206fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d61900000000001e8f99144970082da3079c9a7b54829591d9e4b111f46ff399fa3cee6f563b910000000001312d000000000000000000000000000000022200000004a817c8000000000000030d40000000000000000100000a2702d0001e03b31f67c41f5ae9fce36100241950dca8c983b7ed95d38f461833207616d5673e021e9f88173e27eb38eeb3b179ab63e59b7877b45707bfb8234f6860ab7d819cef038eb83bdb432bf603d649e560a6f8a80478aed8eb717cc7bae709e896a681e0b7037e596c6685650e89f0250dba0c043a73572578e3d8b86d4d695ccfc319e65cf4026e9fbff32c8449c321748ef8d5d3b4f3c8e23c666b79c324e8ae037836223cc3021060634dedae10ce728fa4152aeea4d577d1f509e94097df3ef40b644fda900a010000
```

### `getinfo` output

Unknown, node is `020a1df50b701331a29782093210460b10eee0ac5ef6a01b9c51dff9b8fddf5fb0`.

**Comment by rustyrussell** [comment]
This definitely should not happen with the connectd changes, so I'm closing.
