### ISSUE TITLE
channels opened with c-lightning 0.10.1 are not working?

### ISSUE THREAD

**Issue by LightningHelper** [ElementsProject/lightning#4820]
### Issue and Steps to Reproduce
I opened a few new channels with 0.10.1, and they "feel" a bit strange to me.
First of all they did not forward and txs until now, but that might just be change.
**Second**, and more importantly, it seems that I can not re-balance them with the re-balance plugin. No matter what setting I use, it always try **one** route and get back:

```
{
   "status": "exception",
   "message": "Timeout reached"
}
```
I can still re-balance other channels that were opened with 0.10.0 with no problem. I even use the same in_scid

Has anyone managed to open a new channel with 0.10.1 and use it? or re-balance it? 

I'll be happy to share any more information that is needed,
thanks.

**Comment by cdecker** [comment]
Yes, I'm running v0.10.1 with quite a few channels, and am rebalancing regularly. Also the `lightningd/plugins` are tested against the development version on a regular basis to flag regressions, including the rebalance plugin.

Notice that there are any number of reasons rebalances may fail, in particular topological issues that prevent us from finding short cycles necessary for rebalancing. It can also be localised to a few channels if they happen to only have long cycles that go through them.

**Comment by LightningHelper** [comment]
Thanks @cdecker , but it is not that I can not find a route, it is that only one route is tested, and it fails with timeout:
Specifically here:
https://github.com/lightningd/plugins/blob/c16c564c2c5549b8f7236815490260c49e9e9bf4/rebalance/rebalance.py#L308-L311

```python
                plugin.rpc.sendpay(route, payment_hash, payment_secret=payment_secret)
                running_for = int(time.time()) - start_ts
                result = plugin.rpc.waitsendpay(payment_hash, max(retry_for - running_for, 0))
                time_sendpay += time.time() - time_start
```

plugin.rpc.waitsendpay fails every time with Timeout reached, not matter what setting I use.

**Comment by LightningHelper** [comment]
Ok, 
Not sure what happen, I've restarted the computer and now it tries more than one route.
`time_sendpay_avg:48.639384150505066`

**Comment by cdecker** [comment]
Yeah, could have been a faulty node in that rebalance route which was holding onto payments indefinitely, thus causing the timeout. As soon as that node gets block listed it should work again

**Comment by LightningHelper** [comment]
BTW, @cdecker  now I am getting:
```
{
   "status": "exception",
   "message": "Error with incoming channel"
}

```

Any idea?

**Comment by cdecker** [comment]
It just identifies the channel that failed as the last channel in the route, which is your incoming channel. The peer may be temporarily disconnected or not enough fees or not enough funds to forward the payment.

**Comment by LightningHelper** [comment]
Ok, it is working correctly, sorry for the mess, I think tor network had some problem over the weekend.
Thanks @cdecker

**Comment by cdecker** [comment]
Absolutely no problem, better get some help that turns out to not be needed, than getting stuck on something that we can help with 🙂


Tor seems to be flaky for all implementations, and we're working on it.
