### ISSUE TITLE
channel capacity is X sat, which is below Y msat

### ISSUE THREAD

**Issue by LightningHelper** [ElementsProject/lightning#4827]
### Issue and Steps to Reproduce
Due to this line:
https://github.com/ElementsProject/lightning/blob/b2df01dc73ea7a51ae2a495281bf4d775eafa0a4/openingd/common.c#L151
The output is:
`... channel capacity is 979817sat, which is below 1000000000msat"`

Does it really make sense to have the channel refereed by sat and then msat, it is confusing. I would change both to sats.

**Comment by vincenzopalazzo** [comment]
>Does it really make sense to have the channel refereed by sat and then msat, it is confusing. I would change both to sats.

Agree on this, can be confusing. I can produce a PR to implement it for the next week.
