### ISSUE TITLE
crashes with "database is locked"

### ISSUE THREAD

**Issue by x3nb63** [ElementsProject/lightning#4857]
### Issue and Steps to Reproduce

version is 0.10.1

but 0.9.3 did the same, maybe more often.

`lightningd` emergency exits itself cause the database says its locked during INSERT or UPDATE statements:

```
$ grep 'database is locked' crash.log.*
crash.log.20211009101318:+498.816259929 lightningdBROKEN: Error executing statement: wallet/wallet.c:3786: INSERT INTO transactions (  id, blockheight, txindex, rawtx) VALUES (?, ?, ?, ?);: database is locked
crash.log.20211009175028:+27421.465744630 lightningdBROKEN: Error executing statement: wallet/wallet.c:768: UPDATE shachains SET num_valid=?, min_index=? WHERE id=?: database is locked
crash.log.20211009175054:+17.143080552 lightningdBROKEN: Error executing statement: wallet/wallet.c:3540: INSERT INTO blocks (height, hash, prev_hash) VALUES (?, ?, ?);: database is locked
crash.log.20211009222937:+16702.140267710 lightningdBROKEN: Error executing statement: wallet/wallet.c:768: UPDATE shachains SET num_valid=?, min_index=? WHERE id=?: database is locked
crash.log.20211010034113:+18687.834439849 lightningdBROKEN: Error executing statement: wallet/wallet.c:768: UPDATE shachains SET num_valid=?, min_index=? WHERE id=?: database is locked
crash.log.20211011032432:+85389.796158637 lightningdBROKEN: Error executing statement: wallet/wallet.c:768: UPDATE shachains SET num_valid=?, min_index=? WHERE id=?: database is locked
```

Don't know how to reproduce. It happens few times a day, presumably related to how busy the node is, but that is a guess already - I failed to trigger it.

### My Digging

Looking generally I find SQLite has [a story](https://www.arysontechnologies.com/blog/fix-sqlite-error-database-locked/) with locks [or here](https://www.convertertools.org/blog/sqlite-database-is-locked-error-code-5/) - I can not say whether this applies.

Naturally I suspect _"race-condition because of threads"_  - but can't say anything either, not knowing lightningd's thread model...

On the hardware I can say its rather slow: 2 x 7200rpm HDD combined as zpool mirror. That is low latency compared to SSD. So, if lightningd is rarely used / never stress-tested on such disks, I guess such a thing can go unnoticed.

**Comment by ZmnSCPxj** [comment]
`lightningd` has no threads and is purely single-threaded.  In addition, only one process can access the database, the main `lightningd` executable.  Our code is also written so that multiple `SELECT` calls *should* be impossible.... modulo bugs, of course.

Is the HDD accessed locally or over NFS?  If over NFS that might cause problems as NFS has classically not followed some Unix conventions for locking on filesystems (though those are being worked on over time and my information may be out-of-date).  Locally should not have problems, ZFS should work properly as a Unix filesystem locally. Are you running ZFS on a Linux box with the ZFS in a module?  Ubuntu or non-Ubuntu?

**Comment by vincenzopalazzo** [comment]
>can something make threads you don't intent? such as a smart compiler?

No, I think there are nothings under the hood. However, do you use some particular plugin?

**Comment by x3nb63** [comment]
epiphany occurred and I understand why the patch always fails in my actual build procedure: the lines you quoted do not exist in the [v0.10.1 tag](https://github.com/ElementsProject/lightning/blob/v0.10.1/wallet/db_sqlite3.c#L25-L50) ...

Unless there is a default, it runs with _no timeout_ at all on my machine.

Is it safe to run master branch in production?

**Comment by ZmnSCPxj** [comment]
> Unless there is a default, it runs with *no timeout* at all on my machine.

The default is 0 seconds  (;;\^\^)v

**Comment by x3nb63** [comment]
thanks for explaining.

With 60 seconds timeout there is no crash this far.

I'll look into the backup plugin. The litestream method has another downside: using a content based incremental backup on its snapshots is _very_ inefficient on the backup volume. (backup size vs. data actually changed, that is)

**Comment by ZmnSCPxj** [comment]
IIRC the `backup` plugin also does incremental backups, so the backup size will be larger than the "live" size I think.

**Comment by x3nb63** [comment]
```
$ lightningd --version
09459a9
```

**Comment by cdecker** [comment]
> IIRC the `backup` plugin also does incremental backups, so the backup size will be larger than the "live" size I think.
> 
> It _could_ be written so that only the most recent set of db entries is kept separately, and when a new set is saved the previous set is written to a replica db, so that the backup is only a small amount larger than the live data, but I do not know if it _was_ written that way.

That is definitely one way of doing it, and we're also working on a variant that will work this way. The reason it was not the first implementation is that with this continuous replication into a replica DB we cannot encrypt the queries, since the backup server could not apply them. However, you're right, keeping a separate table or file with the in-flight query and applying it onces it's been confirmed is definitely something we should do asap.

**Comment by x3nb63** [comment]
that crash happened again, same version:
```
$ lightningd --version
09459a9
$ grep 'database is locked' crash.log.2021110* 
crash.log.20211101160350:+981638.015138198 lightningdBROKEN: Error executing statement: wallet/wallet.c:3724: INSERT INTO blocks (height, hash, prev_hash) VALUES (?, ?, ?);: database is locked
crash.log.20211102200719:+152.979660783 lightningdBROKEN: Error executing statement: wallet/wallet.c:3919: INSERT OR IGNORE INTO transaction_annotations (txid, idx, location, type, channel) VALUES (?, ?, ?, ?, ?);: database is locked
crash.log.20211104031348:+111976.347061380 lightningdBROKEN: Error executing statement: wallet/wallet.c:3724: INSERT INTO blocks (height, hash, prev_hash) VALUES (?, ?, ?);: database is locked
$
```

the first one was right in the middle of the day -> no backup I/O involved here, except for the attached `litestream` as described above.

the second one happened few minutes after restarting -> I assume it was catching up with the missed blocks from `bitcoind`, so it did more I/O, increasing its chance to crash

the third one was yet another ~2 days later, same as first. -> this time it did not miss that much from `bitcoind` ...

should I reopen this issue or is this a new one?

**Comment by ZmnSCPxj** [comment]
Looks like it would be better to just remove the `litestream` recommendation from `BACKUP.md`, if `litesteam` is indeed the one interfering here.

#4890 puts similar functionality right into `lightningd`, and also removes any potential races where `lightningd` commits to main and sends revocation keys before `litestream` can read and replicate to backup, but it is slated for 0.10.3.
