### ISSUE TITLE
Test suite might incorrectly run tests under Python 2 due to inconsistent pytest script naming

### ISSUE THREAD

**Issue by practicalswift** [ElementsProject/lightning#486]
The correct fix is probably to teach `configure` to identify the correct Python 3-based `pytest` script.

See discussion in #406.

**Comment by jsarenik** [comment]
Can the Python2 Pytest be version 3 itself?

**Comment by jsarenik** [comment]
Yes, it can. https://docs.pytest.org/en/latest/changelog.html

**Comment by jsarenik** [comment]
@practicalswift Please have a look at #1574 . Thanks!

**Comment by jsarenik** [comment]
I found it. https://github.com/bitcoin/bitcoin/issues/6100

i.e. `utACK` means untested ACK

**Comment by cdecker** [comment]
Fixed as per PR #1574
