### ISSUE TITLE
Should do a sanity check on channel lease amount

### ISSUE THREAD

**Issue by AutonomousOrganization** [ElementsProject/lightning#4861]
Was trying out the duel fund feature and opened a few successfully but came to a third. The first open attempt failed and it asked for a specific amount.  The channel opened but pushed 0.1BTC from my on chain funds into the remote side of the channel. 

Oh I see it now: their lease fee is set at 0.1BTC. Sigh #reckless indeed. My fault for not paying attention but I had opened a few already and msat makes all those zeros not seem scary. A confirmation from fundchannel would have saved me. 

```
      {
         "nodeid": "02cc19df07eefe1ec2606c69e5b4a9b0ee3d0bc5f0764d3e93085f215c33ade8c6",
         "alias": "Dagnela 🦄",
         "color": "ffa6f7",
         "last_timestamp": 1632736174,
         "features": "80008028226aa2",
         "addresses": [
            {
               "type": "torv3",
               "address": "tzmt6slqug7mh3yyrnelimfyptc2wrvxxbgfkyj6rd7uw7dibb2sbyad.onion",
               "port": 9735
            }
         ],
         "option_will_fund": {
            "lease_fee_base_msat": "10000000000msat", <-- :*(
            "lease_fee_basis": 100,
            "funding_weight": 666,
            "channel_fee_max_base_msat": "5000000msat",
            "channel_fee_max_proportional_thousandths": 100,
            "compact_lease": "029a00640064009896804c4b40"
         }
      },
```

**Comment by AutonomousOrganization** [comment]
I'd be mad at this scammer, but he has a unicorn in his name so I'll get over it

**Comment by cdecker** [comment]
Doing enforcement on limits on the API is always a bit of a tight rope act: we generally expect users to build UIs and tools that'd do the "ask user for permission" step, all we can really do is guess what is reasonable and enforce upper limits like we do with the payment fee for example. That then has a long tail of having to come up with good defaults which may also vary over time.

Thanks for pointing out this pitfall, we can discuss here what limits should look like 🙂

**Comment by SimonVrouwe** [comment]
> "lease_fee_base_msat": "10000000000msat", <-- :*(

It looks like there was a typo in the option name `lease-fee-base-msat`, it should be `lease-fee-base-sat`
https://github.com/ElementsProject/lightning/blob/52b1f5a8f454caf4b09ff14a432403ec94297609/plugins/funder.c#L1283-L1287

As without a unit arg it defaults to satoshis
https://github.com/ElementsProject/lightning/blob/52b1f5a8f454caf4b09ff14a432403ec94297609/plugins/funder.c#L1146-L1162
