### ISSUE TITLE
**BROKEN** Could not subdaemon channel: Too many open files

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#4868]
### Issue and Steps to Reproduce

My node was exhibiting some erroneous behavior due to failing to launch subdaemons due to hitting the open file descriptor resource limit. I tried raising the limit using `ulimit` as suggested by @cdecker in https://github.com/ElementsProject/lightning/issues/4534#issuecomment-845204561, but that had no effect. (The `lightningd` process still had both soft and hard limits of 1024 open files.) Come to find out, these limits are actually [hardcoded in `lightning/lightning.c`](https://github.com/ElementsProject/lightning/blob/v0.10.1/lightningd/lightningd.c#L863).

Please implement a configuration option to override this insufficient limit.

> [“640KB ought to be enough for anybody.” —Christian Decker](https://github.com/ElementsProject/lightning/commit/07e6f43e1da13975074bb84e63cb4bc0cdc82e3a)

Thanks to @TheBlueMatt for bringing the failure to my attention.

### `getinfo` output
This is C-Lightning 0.10.1.

**Comment by ZmnSCPxj** [comment]
The "correct" way to fix this would be to change our `close`ing loop by instead maintaining a set of fds we should close on `fork`.  I *conjecture* that all fds that `lightningd` "should" close after `fork` are passed to the `ccan/io` module, so maybe hooking there somehow would work?  @rustyrussell ?

We *could* use the `close_range` thing you proposed in the other thread, but it would be much nicer if something similar also existed in MacOS and/or FreeBSD.

**Comment by ZmnSCPxj** [comment]
Hmm! https://stackoverflow.com/a/918469

**Comment by ZmnSCPxj** [comment]
So let me propose an internal library for closing `fd`s without requiring (hopefully) some kind of large loop except for really old kernels.

```c
/* Call at program init.
 * This is needed in order to open an `fd` "early" to
 * a directory of open `fd`s:
 * see #5 in https://stackoverflow.com/questions/899038/getting-the-highest-allocated-file-descriptor
 * On systems where that is not necessary, this is a no-op.
 */
void closeallexcept_init(void);

/* Call after `fork`, in the child process.
 * Closes all file descriptors except for those listed.
 * The given set of `fd`s **must** be sorted in order
 * from lowest to highest.
 */
void closeallexcept(int numfds, int fds_not_to_close[]);
```

**Comment by ZmnSCPxj** [comment]
Not all APIs expose `O_CLOEXEC`, possibly?  Though there *is* `fcntl` `F_SETFD` for that... dunno really.  I *think* we do not use libraries that keep fds around, but maybe we are just hedging against some future where we *do* use one?

And we do keep open some `fd`s that talk to `hsmd` which is a privileged domain, so it might be safer to just close everything except what we explicitly want to pass to a subdaemon.

**Comment by ZmnSCPxj** [comment]
Whoa whoa whoa!

So I was looking at our big nasty `close` loop and saw this:

https://github.com/ElementsProject/lightning/blob/09459a97c7dfef0a48ed19cb542bd3a1704c267d/lightningd/subd.c#L169-L173

@rustyrussell  we hardcode a `101` here --- there is a small but distinct probability that an `fd` we want to pass in actually *is* `101`.  I presume `dev_disconnect_fd` usage is so rare, and "only in development" anyway, that this is considered acceptable, but still, maybe we can do something like the below?

```c
/* Dup any extra fds first */
while ((fd = va_arg(*ap, int *)) != NULL) {
        int actual_fd = *fd;
        /* If this were stdin, we moved it above! */
        if (actual_fd == STDIN_FILENO)
               actual_fd = stdin_is_now;
       /* Move dev_disconnect_fd if it would be overwritten. */
       if (fdnum == dev_disconnect_fd) {
               int new_fd = dup(dev_disconnect_fd);
               if (new_fd < 0)
                       goto child_errno_fail;
               close(dev_disconnect_fd);
               dev_disconnect_fd = new_fd;
       }
       if (!move_fd(actual_fd, fdnum))
               goto child_errno_fail;
       fdnum++;
}

/* Move dev_disconnect_fd as well.  */
if (dev_disconnect_fd != -1) {
        if (dev_disconnect_fd != fdnum) {
                if (!move_fd(dev_disconnect_fd, fdnum))
                        goto child_errno_fail;
                dev_disconnect_fd = fdnum;
        }
        fdnum++;
}

```

Then the `close` loop afterward would be equivalent to a call to `closefrom(fdnum)`.

Actually come to think of it there is also the chance that `stdin_is_now` could potentially be overwritten by the above remapping loop, so maybe it should be guarded as well?

So let me propose an alternate internal library for `closefrom`:

```c
/* closefrom_compat_init
 *
 * Call at the start of a program before allocating any `fd`s.
 */
void closefrom_compat_init(void);

/* closefrom_compat_getfd
 *
 * The closefrom emulation may require an FD to be kept open.
 * You may query this fd, for example if you are remapping FDs
 * to specific numbers by dup2, you may want to check if
 * this facility is using that specific number.
 * @return -1 if the emulation requires no FD to be kept open,
 * or the FD that needs to be kept open otherwise.
 */
int closefrom_compat_getfd(void);

/* closefrom_compat_remapfd
 *
 * The FD that needs to be kept open may occupy a number
 * that is being remapped to via dup2.
 * This call changes the FD number to a different one that
 * is not currently in use.
 *
 * Precondition: closefrom_compat_getfd() should not
 * have returned -1.
 * Postcondition: closefrom_compat_getfd() will return a
 * different value. 
 */
void closefrom_compat_remapfd(void);

/* closefrom_compat
 *
 * Emulates the closefrom syscall as efficiently as possible
 * on the system.
 * 
 * @fromfd - The first fd to close, all other fds afterwards
 * are also closed.
 */
void closefrom_compat(int fromfd);
```

**Comment by ZmnSCPxj** [comment]
Sent patches for `closefrom` to ccan@lists.ozlabs.org, heads up @rustyrussell !
