### ISSUE TITLE
**BROKEN** lightningd: Error executing statement: ERROR:  duplicate key value violates unique constraint "payments_pkey1"?DETAIL: Key (id)=(2) already exists.?

### ISSUE THREAD

**Issue by stefanwouldgo** [ElementsProject/lightning#4887]
### Issue and Steps to Reproduce

I upgraded from 0.10.1 to current master because I couldn't start 0.10.1 with bitcoin 0.22 anymore and I had found some similar issue that seemed to be caused by a plugin directory merge that has been reverted later on.

However, after Updating database from version 176 to 189 (using postgres, getting some warnings that only superuser can vacuum), I get the above error. Tried restarting, after some time (clboss doing a lot of stuff)  I get the same error.

**Comment by stefanwouldgo** [comment]
The fix appears to work. C-lighting is running again. However, the currval-query from above still returns the same error.

**Comment by mb300sd** [comment]
Was out of town for the weekend. Fix appears to work, I can make payments from the node again.
