### ISSUE TITLE
Adding partial index of unresolved HTLCs drastically reduces startup time

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#4901]
### Issue and Steps to Reproduce
Starting C-Lightning with a database containing a large number of heavily used channels can take a very long time, as the database queries in [`wallet_htlcs_load_in_for_channel`](https://github.com/ElementsProject/lightning/blob/v0.10.2/wallet/wallet.c#L2676-L2695) and [`wallet_htlcs_load_out_for_channel`](https://github.com/ElementsProject/lightning/blob/v0.10.2/wallet/wallet.c#L2724-L2744) can at best make use of the `channel_htlcs_channel_id_channel_htlc_id_direction_key` unique index to find the rows for each channel but must then read each such row to check its `hstate` value. This can require a very large number of random reads, and it only grows worse as the channels accumulate more historical HTLC records with age.

Introducing the following partial index drastically reduces startup time by requiring the HTLC restoring queries only to read the rows corresponding to *unresolved* HTLCs. The reduction in random reads can be by more than an order of magnitude. Maintaining the index is trivial, as it is always very small.

```
CREATE INDEX channel_htlcs_unresolved_idx
    ON channel_htlcs (channel_id)
    WHERE direction = 0 AND hstate <> 19 OR direction = 1 AND hstate <> 9;
```

### Empirical observations

The following observations record the elapsed time between the first "Restored __ incoming HTLCs" and the last "Restored __ outgoing HTLCs" during each startup occasion.

**Without new index**

* 2021-09-06T19:31:31.964Z − 2021-09-06T19:27:38.928Z = 233.036 s
* 2021-09-13T21:30:15.448Z − 2021-09-13T21:24:35.578Z = 339.870 s
* 2021-09-16T21:32:47.081Z − 2021-09-16T21:24:53.665Z = 473.416 s
* 2021-10-07T05:20:05.785Z − 2021-10-07T05:10:52.015Z = 553.770 s

**With new index**

* 2021-10-08T19:15:56.126Z − 2021-10-08T19:15:32.214Z = 23.912 s
* 2021-10-17T00:40:34.488Z − 2021-10-17T00:40:13.479Z = 21.009 s
* 2021-10-17T00:43:01.231Z − 2021-10-17T00:42:58.043Z = 3.188 s (hot caches)
* 2021-10-17T00:51:15.229Z − 2021-10-17T00:51:04.583Z = 10.646 s (warm caches)
* 2021-10-17T01:03:10.858Z − 2021-10-17T01:02:49.314Z = 21.544 s
* 2021-11-03T23:16:41.452Z − 2021-11-03T23:16:33.714Z = 7.738 s (upgrade to v0.10.2)

**Comment by cdecker** [comment]
Very interesting, thanks for the experimental evaluation. One thing we could also do is make use of the new `min_commitnum` and `max_commitnum` values to identify HTLCs that are likely still attached to the channel. An index over those two fields and an additional query condition could then be reused for the `onchaind` startup too, since that selects HTLCs associated with a specific commitnum. Would that have the same effect?

**Comment by ZmnSCPxj** [comment]
> Why would `onchaind` care about HTLCs that are already resolved? 

The counterparty could broadcast a revoked commitment tx that has already-resolved HTLCs.  `onchaind` needs to know the HTLC details (hash, timelock) to generate the Bitcoin SCRIPT that needs to be revealed in order to revoke the HTLC outputs as well.

**Comment by whitslack** [comment]
For what it's worth, I went in a different direction with this. Instead of a partial index, I now have my `channel_htlcs` table partitioned in multiple levels:

* ```
  CREATE TABLE channel_htlcs (…)
      PARTITION BY LIST (hstate);
  ```
  * ```
    CREATE TABLE channel_htlcs_resolved
        PARTITION OF channel_htlcs
        FOR VALUES IN (9, 19)
        PARTITION BY RANGE (id);
    ```
    * ```
      CREATE TABLE channel_htlcs_archived
          PARTITION OF channel_htlcs_resolved
          FOR VALUES FROM (0) TO (5000000)
          PARTITION BY HASH (channel_id);
      ```
      * ```
        CREATE TABLE channel_htlcs_archived_r0
            PARTITION OF channel_htlcs_archived (…)
            FOR VALUES WITH (MODULUS 8, REMAINDER 0);
        ```
      * ⋮ (7 more hash buckets)
    * ```
      CREATE TABLE channel_htlcs_recent
          PARTITION OF channel_htlcs_resolved (…)
          DEFAULT;
      ```
  * ```
    CREATE TABLE channel_htlcs_unresolved
        PARTITION OF channel_htlcs (…)
        DEFAULT;
    ```

What this all means:
* The majority of the churn occurs in the tiny `channel_htlcs_unresolved` partition. This is the only partition that needs to be searched when restoring unresolved HTLCs at startup, so it supplants my partial index.
* As HTLCs get resolved, they are moved to the `channel_htlcs_recent` partition. This partition is modified very frequently, but it doesn't often need to be searched.
* Whenever I'm about to take a new base backup of my system, I can "slide forward" the `id` cutoff between the partitions `channel_htlcs_recent` and `channel_htlcs_archived` to migrate all rows in the former partition into the latter partition. This will modify all of the hash buckets in the `channel_htlcs_archived` partition, so I only want to do it when taking a new base backup.
* As channels get closed, old HTLC records get expunged. This causes modification to only one hash bucket of the `channel_htlcs_archived` partition per channel that gets closed, thereby saving me from having to include the *entire* `channel_htlcs_archived` partition in my nightly incremental backup just because of one channel closure. (The incremental backup includes only the buckets that were touched during the previous day.)

Obviously this only works with PostgreSQL, and it would be overkill for most installations, so I'm not documenting my setup here as a suggestion but merely as an exposition.

**Comment by ZmnSCPxj** [comment]
It may still warrant at least partitioning "manually" (this is what I suggest in the edit of my previous comment), so that SQLITE3 databases also benefit.  From what I understand, we really only need to index the unresolved HTLCs separately from all the others.

At the minimum, maybe make a `doc/SCALING.md` @whitslack?  Though the document may get obsolete quickly as we start moving to PTLCs, and we could change the database structure in the future too...

**Comment by whitslack** [comment]
> From what I understand, we really only need to index the unresolved HTLCs separately from all the others.

That only helps with startup. There is still the issue @cdecker [raised](https://github.com/ElementsProject/lightning/issues/4901#issuecomment-961841365) regarding `onchaind`'s need to look up resolved HTLCs by commitment number that they may have spanned. My partitioning scheme doesn't attempt to address that.

**Comment by ZmnSCPxj** [comment]
I would consider channel closures (`onchaind` operation) as much more rare than periodic need to shut down for maintenance and updates, though I guess if you regularly have >1000 channels that might actually invert and channel closure might be more common than node shutdown.  So at least for a start, splitting out the table into two tables and just indexing one of them would work better for normal operation.

**Comment by whitslack** [comment]
> if you regularly have >1000 channels that might actually invert and channel closure might be more common than node shutdown.

Channel closure is an order of magnitude more common for me than node shutdown. I see at least one channel closure every day but only restart my node every few weeks.

A crucial point to note is that a channel closure event requires a database lookup for the historical HTLCs of exactly one channel, whereas a node startup requires a database lookup for the current HTLCs of *all* channels. The former only blocks for (potentially) a few seconds every once in a while, whereas the latter can block for many minutes all concentrated at one time, which makes for a much worse service disruption.

**Comment by ZmnSCPxj** [comment]
SQLITE3 actually supports partial indexes too: https://sqlite.org/partialindex.html

So as a general solution, maybe the query in your OP is enough for speeding up startup, both on SQLITE3 and on PostgreSQL?

**Comment by ZmnSCPxj** [comment]
Looking at the SQLITE3 docs though:

>SQLite does *not* have a sophisticated theorem prover with which to determine W⇒X.

"X" here is the `WHERE` clause of the `CREATE INDEX`, while "W" is the `WHERE` clause of a `SELECT` query.  It has to determine W⇒X to know that it can use the index for a particular query.

SQLITE3 gives this simplified rule instead:

> If W is AND-connected terms and X is OR-connected terms and if any term of W appears as a term of X, then the partial index is usable.

I believe the queries relevant to startup speed are the ones in `wallet_htlcs_load_in_for_channel` and `wallet_htlcs_load_out_for_channel`.  They have an `AND` set which includes `hstate != 19` and `hstate != 9`, respectively.

So I think this `CREATE INDEX` should work for both PostgreSQL and SQLITE3:

```SQL
CREATE INDEX channel_htlcs_unresolved_idx
    ON channel_htlcs (channel_id, direction)
    WHERE hstate != 19 OR hstate != 9;
```

@cdecker to confirm?

**Comment by whitslack** [comment]
@ZmnSCPxj: Agreed. From reading that, my understanding is that SQLite does not consider all subsets of the AND expression in W, only single-term subsets. Honestly my partial index condition in the OP is needlessly overconstrained since there should never be an HTLC record with `direction != 1 AND hstate = 9` or with `direction != 0 AND hstate = 19`.

**Comment by whitslack** [comment]
Wait a second, won't that partial index condition end up indexing *all* rows? A row with `hstate = 9` will match the condition `hstate != 9 OR hstate != 19`.

**Comment by whitslack** [comment]
Does SQLite support tuple constructors? If so, then you could define the partial index as

```
CREATE INDEX channel_htlcs_unresolved_idx
    ON channel_htlcs (channel_id)
    WHERE (direction, hstate) <> (0, 19)
        OR (direction, hstate) <> (1, 9);
```

and change the queries by replacing the `hstate != ?` term with `(direction, hstate) != (?, ?)`.

That would satisfy SQLite's simplistic planner by giving it a single AND term in W that it can match up with a single OR term in X.

**Comment by whitslack** [comment]
Okay, third try is the charm:

```
CREATE INDEX channel_htlcs_unresolved_idx
    ON channel_htlcs (channel_id, direction)
    WHERE hstate NOT IN (9, 19);
```

and replace `hstate != ?` in the queries with `hstate NOT IN (?, ?)`.

**Comment by ZmnSCPxj** [comment]
Maybe the query in `wallet_htlcs_load_in_for_channel` and friend can add parentheses?

```SQL
SELECT * -- eliding here
 FROM channel_htlcs
 WHERE channel_id = ?
 AND (direction = ?
 AND hstate != ?)
```

Then we can go with your original query:

```SQL
CREATE INDEX channel_htlcs_unresolved_idx
    ON channel_htlcs (channel_id)
    WHERE (direction = 0 AND hstate != 19) OR (direction = 1 AND hstate != 9);
```

**Comment by ZmnSCPxj** [comment]
Anyway lemme check both ways and see which one SQLITE3 likes

**Comment by whitslack** [comment]
I would expect the query optimizer to flatten `A and (B and C)` to `A and B and C` prior to considering indices. 🤷🏻‍♂️

**Comment by ZmnSCPxj** [comment]
Yeah, doesn't work.   Lemme see the `NOT IN`.

**Comment by ZmnSCPxj** [comment]
`NOT IN` works!

```
sqlite> explain query plan select * from channel_htlcs where channel_id = 'foo' and direction = 0 and hstate != 19;
QUERY PLAN
`--SEARCH TABLE channel_htlcs USING INDEX sqlite_autoindex_channel_htlcs_1 (channel_id=?)
sqlite> create index channel_htlcs_unresolved_ids on channel_htlcs(channel_id, direction) where hstate NOT IN (9, 19);
sqlite> explain query plan select * from channel_htlcs where channel_id = 'foo' and direction = 0 and hstate NOT IN (9, 19);
QUERY PLAN
`--SEARCH TABLE channel_htlcs USING INDEX channel_htlcs_unresolved_ids (channel_id=? AND direction=?)
```
