### ISSUE TITLE
How do I pay a bolt #11 invoice?

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#491]
How do I pay an invoice like `lntb..` and not using just rhash?

**Comment by ZmnSCPxj** [comment]
Use `pay` command:

    lightningd/lightning-cli pay lntb...

RPC is still a bit in flux and some things may change.

**Comment by Sgt-Miller** [comment]
Thanks!

**Comment by Sgt-Miller** [comment]
@ZmnSCPxj is there a list of all such commands?

**Comment by Sgt-Miller** [comment]
Nvm --help lists it. Should have read the docs
