### ISSUE TITLE
How do I run multiple instances in the same PC?

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#492]
If I'm not wrong, lightning-c stores its data and logs in `~/.lightning`
How can I change this if I want multiple instances with different datadir?

**Comment by Saibato** [comment]
fe
lightningd/lightningd --network=testnet --log-level=debug  --bitcoin-datadir /somedir/bitcoin_core  --alias name_b  --port 1234 // this will use .lightning dir on port 1234
and 
second
sudo lightningd/lightningd --network=testnet --log-level=debug  --lightning-dir /home/user/somenewdir  --bitcoin-datadir /somedir/bitcoin_core --alias name_a  // this will use  /home/user/somenewdir on port  9735
+
+
+

access by 

cli/lightning-cli getinfo
and the 
other one
by 
sudo cli/lightning-cli --lightning-dir  /home/user/somenewdir getinfo


works for me
maybe you have  to add different --ipaddr option for nonlocal tests
;-)

**Comment by cdecker** [comment]
Like @Saibato already suggested, you need to run the two (or more) instances with separate `--port`s and `--lightning-dir` arguments so they don't interfere with each other. The `lightning-cli` then also needs to be told where to find the instance you want to talk to. I usually create an alias to make accessing multiple instances easier:

```
alias lcli=lightning-cli
alias lcli1="lcli --lightning-dir=/path/to/.lightningd1
alias lcli2="lcli --lightning-dir=/path/to/.lightningd2
alias lcli3="lcli --lightning-dir=/path/to/.lightningd3
// ...
```

**Comment by Sgt-Miller** [comment]
Thanks!

**Comment by cdecker** [comment]
No problem, if you plan to run nodes on a regular basis you might want to check out the python helpers used in the integration suite (`tests/test_lightningd.py` and `tests/utils.py`)
