### ISSUE TITLE
c-lightning Backup

### ISSUE THREAD

**Issue by SirSir21** [ElementsProject/lightning#4923]
### `getinfo` output
Hello everyone. I have a problem with my c-lightning wallet or my channels. When I load the backup file, the channels are displayed on RTL, as soon as the wallet is 100% synchronized, they disappear again. I've done it three times with the result described above. The backup was created under v10.2cr2. I'm currently using v0.10.2. Could that be the problem, why do channels go away when they're 100% synced? Ps. I use Raspiblitz v1. 7.1

**Comment by vincenzopalazzo** [comment]
HI @SirSir21,

What is the status of each channel? are opened or the status it is `ONCHAIN`?

**Comment by SirSir21** [comment]
After the backup, as long as the wallet is not 100% synchronized, the status according to RTL is initially "Pending / Inactive" and the state is "Awaiting Unilateral Close". After a certain time the state is "Blockchain" and with 100% synchronization everything is gone again

**Comment by vincenzopalazzo** [comment]
It is totally normal, if you will close a channel, or the other peer closes the channel with you for the moment there is no way to retrieval a closed channel in c-lightning.

So, after ONCHAIN, your channel will be "lost" or better not displayed only because it is the history of the node, and it is not a channel anymore.

**Comment by SirSir21** [comment]
Ok, thanks for the explanation 🙏 I understand that, but I don't know what to do now to receive my funds? I am currently running a rescan. Could that help?

**Comment by openoms** [comment]
Recovery was successful using the `hsmtool guesstoremote`. Can be closed.
