### ISSUE TITLE
Nodes shouldn't publish their commitment when receiving outdated `channel_reestablish`

### ISSUE THREAD

**Issue by t-bast** [ElementsProject/lightning#4927]
When receiving a `channel_reestablish` that indicates that your peer has outdated data, you shouldn't close instantly.
You should only trigger the force-close when receiving an `error` message from your peer.
This gives them an opportunity to correct it and potentially prevent the force-close.

See https://github.com/lightning/bolts/issues/934 for details.

**Comment by whitslack** [comment]
I believe this was fixed in b698a5a5ef4acb8d90aec0f6dccc52fb6c37afb2 and this issue should be closed. @rustyrussell @cdecker

**Comment by cdecker** [comment]
Seems reasonable, and the fact that someone tripped up on it already suggests it is actually working 🥴
