### ISSUE TITLE
Signet uses wrong hrp for on-chain bech32 addresses

### ISSUE THREAD

**Issue by andrewtoth** [ElementsProject/lightning#4937]
After https://github.com/ElementsProject/lightning/pull/4929 the wallet expects the signet bech32 hrp to be `tbs`, while all other wallets expect `tb`. Thus we cannot withdraw or deposit on chain with signet native segwit.

Workaround for depositing is `lightning-cli --signet newaddr p2sh-segwit` to get a p2sh wrapped address.
Workaround for withdrawing is to ask for a p2sh-wrapped or legacy address from the recipient if possible, or use an intermediate wallet to receive between.

**Comment by vincenzopalazzo** [comment]
Mh! I need to say that I'm a little bit confused on what convention it is used for the signet, but inside the #4929 maybe we can do better, and add a deprecation phase of 6 months to support both address types.

ping @ZmnSCPxj

**Comment by ZmnSCPxj** [comment]
Supporting different hrp's between offchain and onchain is going to require an overhaul of the `bitcoin/chainparams.*` library, unfortunately, and all callers that ask for an hrp now need to be modified depending on what use they have.
