### ISSUE TITLE
Opening a second channel from eclair to c-lightning causes that and previously existing channel to be closed.

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#494]
So c-lightning supports one channel/peer.
When eclair tries to open a second channel, the first channel also closes.      
same as https://github.com/ACINQ/eclair/issues/351         
lightningd log - [lightningc.txt](https://github.com/ACINQ/eclair/files/1593420/lightningc.txt)

**Comment by ZmnSCPxj** [comment]
Can this be merged with #287? To my mind, to "fail gracefully" on the second channel open, should fail only the second channel open while keep existing channel.
