### ISSUE TITLE
`pip3 install --user -r requirements.txt` fails

### ISSUE THREAD

**Issue by benthecarman** [ElementsProject/lightning#4962]
I am attempting to run `pip3 install --user -r requirements.txt` and get this output

```bash
$ pip3 install --user -r requirements.txt
Processing ./contrib/pyln-client
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-j9g8nbya/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-j9g8nbya/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-j9g8nbya/pip-egg-info
         cwd: /tmp/pip-req-build-j9g8nbya/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-j9g8nbya/setup.py", line 12, in <module>
        setup(name='pyln-client',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-req-build-j9g8nbya/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/integration.py", line 65, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-req-build-j9g8nbya/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/__init__.py", line 177, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-req-build-j9g8nbya/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/__init__.py", line 135, in _do_parse
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for '/'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by benthecarman** [comment]
ran this and now am getting the following error:

```bash
pip3 install --upgrade pip && python3 -m pip install egg CherryPy==17.3.0 Flask==1.0.2 cheroot==8.2.1 ephemeral-port-reserve==1.1.0 flaky==3.4.0 pytest-benchmark==3.1.1 pytest-forked==0.2 pytest-timeout==1.3.3 pytest-xdist==1.22.2 pytest==3.8.1 python-bitcoinlib==0.10.2 tqdm==4.26.0 pytest-test-groups==1.0.3 flake8==3.5.0 pytest-rerunfailures==3.1 mrkd==0.1.6
```

```bash
ERROR: Cannot install -r requirements.txt (line 7), pyln-client and pyln-proto 0.6.3rc1.post5602 (from /home/ben/projects/lightning/contrib/pyln-proto) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pyln-proto 0.6.3rc1.post5602 (from /home/ben/projects/lightning/contrib/pyln-proto)
    pyln-client 0.6.3rc1.post5602 depends on pyln-proto
    pyln-bolt7 1.0.2.186 depends on pyln.proto>=0.9.3
    The user requested pyln-proto 0.6.3rc1.post5602 (from /home/ben/projects/lightning/contrib/pyln-proto)
    pyln-client 0.6.3rc1.post5602 depends on pyln-proto
    pyln-bolt7 1.0.1.137 depends on pyln.proto==0.8.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

```

**Comment by cdecker** [comment]
Yep, that's an issue with the way we detect the version number (with `setuptools-scm` and tags) and the way `pip` installs dependencies (copying just the subdirectory, without the `.git` directory which is required for git tags to work).

When publishing on PyPI we materialize the version number in a `__version__.py` file, which skips the git lookup, but intree we rely on git.

The solution is to use `pip install --use-feature=in-tree-build` (which will be the standard starting with [pip 21.3](https://pip.pypa.io/en/stable/news/#v21-3)). This means the source sub-tree is not copied into an isolated build environment and git continues to work.

**Comment by benthecarman** [comment]
I am using pip3 21.3.1 and still getting this error

Any other potential solution?

**Comment by andrewtoth** [comment]
@benthecarman the first error occurs because some linux distros (Ubuntu) have a default pip3 package that doesn't support in tree builds, so you need to run `pip3 install --upgrade pip` first. Also make sure that pip3 is using the correct upgraded version by verifying the output of `pip3 -V` is `21.3.1`. If the output is an older version, you need to find the correct version with `whereis pip3` and `alias pip3 <location of 21.3.1 pip3>`.

The second error seems to be a cached version of 0.6.3rc1 for pyln-proto. You can remove this caching by running `git clean -xfd`. You will have to rerun `./configure` after though. Then `pip3 install --user -r requirements.txt` should work.

**Comment by benthecarman** [comment]
@andrewtoth I am still getting the same error

**Comment by cdecker** [comment]
Can you `git fetch --tags` and try again? The issue may be that `setuptools-scm` bases it's version on the latest tag you have locally in you repository. If you were missing all tags since 0.6.3 it'd build a version name with that (0.6.3 + 5000 commits ~= current `master`). I've seen this on CI once where the clone didn't fetch tags and we got weird versions as a result.

**Comment by benthecarman** [comment]
> Can you `git fetch --tags` and try again? The issue may be that `setuptools-scm` bases it's version on the latest tag you have locally in you repository. If you were missing all tags since 0.6.3 it'd build a version name with that (0.6.3 + 5000 commits ~= current `master`). I've seen this on CI once where the clone didn't fetch tags and we got weird versions as a result.

Yep, that was it! My fork of the repo was old and never synced the tags I guess

**Comment by remyers** [comment]
> @benthecarman the first error occurs because some linux distros (Ubuntu) have a default pip3 package that doesn't support in tree builds, so you need to run `pip3 install --upgrade pip` first. Also make sure that pip3 is using the correct upgraded version by verifying the output of `pip3 -V` is `21.3.1`. If the output is an older version, you need to find the correct version with `whereis pip3` and `alias pip3 <location of 21.3.1 pip3>`.

Thanks! This worked for me; I just had to do a `source ~/.profile` to update PATH after upgrading pip3 and it worked. I was starting with a fresh install of Ubuntu 20.04.
