### ISSUE TITLE
Pending Channel  even after confirmation

### ISSUE THREAD

**Issue by pratapc65** [ElementsProject/lightning#4978]
### Issue and Steps to Reproduce

My node uses clboss  plugin to manage the lightning node.
clboss  opened a channel with Boltz and the transaction has more than 3 confirmations but the channel is still in pending status for past two days.
C lightning version : 10.2
### `getinfo` output
![image](https://user-images.githubusercontent.com/64409401/146540923-3fccc3b2-9782-499e-83dd-eaad09fe4b62.png)

**Comment by cdecker** [comment]
Is the peer online and connected? The pending count looks at the state of the channels, not just the on-chain funding transaction:

https://github.com/ElementsProject/lightning/blob/5bbe3feee77b039cdb83c11420d36edbd4c5cc26/lightningd/peer_control.c#L1715-L1729

This means that as long as the peer hasn't acknowledged that the channel is operational, by sending a `funding_locked` message, then the channel is still not operational for us either and is thus counted as pending. This is correct in that we can't use the channel either, but it may eventually become operational.

If the peer is disconnected, try reconnecting manually, it could be that we don't know a working peer IP address and thus can't auto-reconnect.

**Comment by pratapc65** [comment]
Hello Team, 
Thanks for the explanation.  The peer was online and  the channel connection  took a few days. The reason could be as you stated the peer did not immediately  acknowledge the opened channel.

**Comment by cdecker** [comment]
Great, glad it worked in the end. The symptoms indeed sound like a lagging peer.
