### ISSUE TITLE
invoice_payment event structure change

### ISSUE THREAD

**Issue by kiwiidb** [ElementsProject/lightning#4990]
### Issue and Steps to Reproduce

Is it correct that the event payload structure has changed? I'm receiving `invoice_payment` event payloads that are not backwards compatible:
```
{
  "invoice_payment": {
    "label": "xxx",
    "msat": "100000msat",
    "preimage": "xxx"
  }
}
```
I see that this is consistent with the docs but I could have sworn that I used to get more fields in this payload. In fact, my application that parsed the payload no longer works, because it expected "status" and "msatoshi" fields.
Golang equivalent of the inner JSON I used to get (under the "invoice_payment" field):
```
type PaymentReceivedSuccess struct {
	Label              string `json:"label"`
	Bolt11             string `json:"bolt11"`
	PaymentHash        string `json:"payment_hash"`
	Msatoshi           int    `json:"msatoshi"`
	AmountMsat         string `json:"amount_msat"`
	Status             string `json:"status"`
	PayIndex           int    `json:"pay_index"`
	MsatoshiReceived   int    `json:"msatoshi_received"`
	AmountReceivedMsat string `json:"amount_received_msat"`
	PaidAt             int    `json:"paid_at"`
	PaymentPreimage    string `json:"payment_preimage"`
	Description        string `json:"description"`
	ExpiresAt          int    `json:"expires_at"`
}

```
However, what is strange is that I still receive this payload, but in a seperate event, an event that has this as a bare bones payload, without an outer `invoice_payment` field. This also prevents my app from parsing it.

**Comment by SimonVrouwe** [comment]
Could you maybe state which version  of c-lightning is used and if the option `--allow-deprecated-apis` is enabled?
