### ISSUE TITLE
lightning-rpc file - not created in regtest

### ISSUE THREAD

**Issue by srmcatee1110** [ElementsProject/lightning#4992]
### Issue and Steps to Reproduce
I am using a setup of regtest specified in this tutorial:   [Tutorial](https://medium.com/@bitstein/setting-up-a-bitcoin-lightning-network-test-environment-ab967167594a)

I've tried to implement c-lightning-rest on the lnd1 instance as specified in the tutorial.
The error I get is:
Lightning client connection error error
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED /home/steve_r_mcatee/app-container/.lnd/
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
Emitted 'error' event on LightningClient instance at:
    at Socket.<anonymous> (/home/steve_r_mcatee/app-container/.lnd/c-lightning-REST/lightning-client-js.js:77:23)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/home/steve_r_mcatee/app-container/.lnd/'
}

Node.js v17.3.0

I'm looking for the lightning-rpc file.   Per the tutorial I've setup this:

export BITSTEIND_DIR="$HOME/app-container/.bitcoin"
alias bitsteind="bitcoind -datadir=$BITSTEIND_DIR"
alias bitstein-cli="bitcoin-cli -datadir=$BITSTEIND_DIR"

export LND1_DIR="$HOME/app-container/.lnd"
export LND2_DIR="$HOME/app-container/.lnd2"
alias lnd1="/home/user/lnd/lnd-linux-amd64-v0.14.0-beta/lnd --lnddir=$LND1_DIR";
alias lncli1="/home/user/lnd/lnd-linux-amd64-v0.14.0-beta/lncli -n regtest --lnddir=$LND1_DIR"
alias lnd2="/home/user/lnd/lnd-linux-amd64-v0.14.0-beta/lnd --lnddir=$LND2_DIR";
alias lncli2="/home/user/lnd/lnd-linux-amd64-v0.14.0-beta/lncli -n regtest --lnddir=$LND2_DIR --rpcserver=localhost:11009"

And config:
[Bitcoin]

bitcoin.active=1
bitcoin.regtest=1
bitcoin.node=bitcoind

[Bitcoind]

bitcoind.rpchost=localhost
bitcoind.rpcuser=lnd
bitcoind.rpcpass=P44whjVFi8uFiwrshSyxsALQCtV_QZs0JMJlhyqvqgY=
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

Finally the cl-rest-config.json file:

{
    "PORT": 3001,
    "DOCPORT": 4001,
    "PROTOCOL": "https",
    "EXECMODE": "test",
    "RPCCOMMANDS": ["*"]
}

What should I set LNRPCPATH to in the cl-rest-config.json file?   Or where would lightning-rpc file be?

Also, I've done a find ./ -name lightning-rpc once I've started all the nodes and file is not found.
Thanks for any help you can provide
### `getinfo` output
getinfo results from lnd1
{
    "version": "0.14.0-beta commit=v0.14.0-beta",
    "commit_hash": "df0b82f0165f19bde8832bacd1e35544b0a2990d",
    "identity_pubkey": "02644f2adcf6874d19568b32a57d3092507ce4ca666df50cc835f3463599a11171",
    "alias": "02644f2adcf6874d1956",
    "color": "#3399ff",
    "num_pending_channels": 0,
    "num_active_channels": 0,
    "num_inactive_channels": 0,
    "num_peers": 0,
    "block_height": 409,
    "block_hash": "0efe8ad2f396151daf3844d658398bbcc9a42a01636fa9b14703d68df8f1351e",
    "best_header_timestamp": "1640818658",
    "synced_to_chain": true,
    "synced_to_graph": false,
    "testnet": false,
    "chains": [
        {
            "chain": "bitcoin",
            "network": "regtest"
        }
    ],
    "uris": [
    ],
    "features": {
        "0": {
            "name": "data-loss-protect",
            "is_required": true,
            "is_known": true
        },
        "5": {
            "name": "upfront-shutdown-script",
            "is_required": false,
            "is_known": true
        },
        "7": {
            "name": "gossip-queries",
            "is_required": false,
            "is_known": true
        },
        "9": {
            "name": "tlv-onion",
            "is_required": false,
            "is_known": true
        },
        "12": {
            "name": "static-remote-key",
            "is_required": true,
            "is_known": true
        },
        "14": {
            "name": "payment-addr",
            "is_required": true,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        },
        "23": {
            "name": "anchors-zero-fee-htlc-tx",
            "is_required": false,
            "is_known": true
        },
        "30": {
            "name": "amp",
            "is_required": true,
            "is_known": true
        },
        "31": {
            "name": "amp",
            "is_required": false,
            "is_known": true
        },
        "45": {
            "name": "explicit-commitment-type",
            "is_required": false,
            "is_known": true
        },
        "2023": {
            "name": "script-enforced-lease",
            "is_required": false,
            "is_known": true
        }
    }
}

**Comment by vincenzopalazzo** [comment]
I'm missing some things for sure, but are you working on LND?

This is the c-lightning implementation, and I think that you are on the wrong repository

**Comment by srmcatee1110** [comment]
Sorry all.  Egg on my face.   That's what I get for not touching lightning for a couple of months.  My knowledge is out of date!!

I figured it out.  I'm using LND which now has REST built in.   The new version also build the PID differently which the old REST library did not do.

LND Rest Call API docs are here.  [https://api.lightning.community/#lnd-rest-api-reference]

**Comment by Geoelycom** [comment]
> 

Hello sir, 

I'm on core-lightning and followed the installation guide but I have close to a similar problem.  when I run 
 `bitcoind &
./lightningd/lightningd &
./cli/lightning-cli help
 `
i get the following
" lightning-cli: Connecting to 'lightning-rpc': No such file or directory" 
I have also checked the full folder of Core-lighting that I installed and can't find lightning-rpc file anywhere which is weird.
. Another error I get is from 
"Wrong network! Our Bitcoin backend is running on 'test', but we expect 'main'." 

I have also seen your answer to this second issue by a bloke with the same issue, but cdeker solution didn't work for me that worked for the bloke. so I don't know if anyone of these problems are connected but I would like any insight you can give me that can help me resolve this  thank you

**Comment by vincenzopalazzo** [comment]
>& ./lightningd/lightningd & ./cli/lightning-cli help

This is wrong, you need to give time to lightnind to set up all.

Run
```
./lightningd/lightningd 
./cli/lightning-cli getinfo
```

>. Another error I get is from
"Wrong network! Our Bitcoin backend is running on 'test', but we expect 'main'."

This depends from your condifuration, if you run bitcoin on testned you need to add `--testnet` flag to your `lightningd` command

**Comment by Geoelycom** [comment]
> 

I should run each command separately. not at once is what you mean sir?

my bitcoin Config file network is on testnet, I had the impression that I will see the same config file on C-lightning and that I can also set its network to testnet, but it's not available. a situation where I don't have to run the flag all the time.
I'll try this now and respond back if it solves the issue thank you very much.

**Comment by Geoelycom** [comment]
> 

at first when I run this alone.
`./lightningd/lightningd --testnet`

I get lightningd already running? Error PID file: Resource temporarily unavailable.

if I run it with `nohup lightningd --testnet &`
I get the following:
`[1] 34785
appending output to nohup.out
[1] +exit 11  nohup lightning --testnet`

when I now try to run `./cli/lightning-cli getinfo`  I get the same old error of 
connecting to lightning-rpc: no such file or directory found. regardless of how long I waited.
I'm a noob so forgive me if there is something that I should be doing that I am not.

**Comment by n-e-t-d-i-v-e-r** [comment]
got the same issue here. tried to install core lightning and RTL. If i run node cl-rest.js i get:

`Reading config file
error: WARN: /home/lightningd/.lightning/lightning-rpc is missing, using the bitcoin mainnet subdirectory at /home/lightningd/.lightning/bitcoin instead.
warn: --- Starting the cl-rest server ---
warn: --- cl-rest api server is ready and listening on :::3092 ---
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4091
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at doListen (net.js:1516:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 4091
}
`

May somebody write here in the solution pls?

**Comment by vincenzopalazzo** [comment]
No this is a separate issue, please open an new one
