### ISSUE TITLE
Continuously getting “No path found”

### ISSUE THREAD

**Issue by AngeloMetal** [ElementsProject/lightning#4999]
Disclaimer: I'm new at this field and I haven't yet understood the details of the LN. Actually I do have, but not in a _disgustingly exact manner_. 

Alright, so I'm trying to spend some of my channel's reserve so I can increase my receiving capacity. When I enter ``./lightning-cli --testnet pay [invoice]``  I get:

```
{
   "code": 210,
   "message": "Ran out of routes to try after 958 attempts: see `paystatus`",
   "attempts": [
      {
         "status": "pending",
         "partid": 1,
         "amount": "2500000000msat"
      },
      {
         "status": "failed",
         "failreason": "failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)",
         "partid": 2,
         "amount": "196114910msat",
         "parent_partid": 1
      },
...
lots of lines with failed statuses...
...
```

In my lightning daemon I get thousands of this kind of messages in the log:
```2022-01-04T14:50:53.034Z INFO    plugin-pay: cmd 148 partid 4: No path found```

What's the problem? Why does it fail to spend some of the channel's reserve?

**Comment by SimonVrouwe** [comment]
Probably your node is not well connected enough, or a channel in the route is unbalanced (not enough capacity on right side).

This is what I found for the error code `WIRE_TEMPORARY_CHANNEL_FAILURE` in [BOLT#4](https://github.com/lightning/bolts/blob/master/04-onion-routing.md#requirements-4)

- if during forwarding to its receiving peer, an otherwise unspecified,
  transient error occurs in the outgoing channel (e.g. channel capacity reached,
  too many in-flight HTLCs, etc.):
    - return a `temporary_channel_failure` error.

**Comment by vincenzopalazzo** [comment]
There is a way to help here, I'm working on some metrics in [lnmetrics](https://github.com/LNOpenMetrics) where there is the possibility to collect data inside a server, and with these data, we can help to explain the why you are receiving the No path found error.

To collect the data you need just to add this plugin inside your node [go-lnmetrics.reporter](https://github.com/LNOpenMetrics/go-lnmetrics.reporter) and you can see the data that are collected with the following document in [lnmetric.rfc](https://github.com/LNOpenMetrics/lnmetrics.rfc)

**Comment by cdecker** [comment]
Yeah, I'm afraid this is likely just network weather being unfavorable. The `pay` command will do its best to get the payment to the destination, but depending on the current situation in the network, the payment might not be able to complete successfully (driving a 2m high truck through a 1.5m tunnel just isn't going to work). The 958 attempts look like it tried really hard (or we are missing a corner case where we should be aborting earlier), but without having the full listing it's kind of hard to say what exactly went wrong.

**Comment by AngeloMetal** [comment]
I restarted daemon and it now works. What to say...

**Comment by cdecker** [comment]
Hehe, likely a peer that reconnected only after the restart, opening up new routes? Hard to say, but glad it works now.
