### ISSUE TITLE
Another reason for declining an htlc

### ISSUE THREAD

**Issue by pm47** [ElementsProject/lightning#5]
Hello,

Currently the only available ones are `insufficient_funds` and `cannot_route`.

But since the commitment tx must be publishable at any time, we might need to decline a new htlc because that would make the tx too big.

Should we introduce a new reason `too_many_pending_htlc`?

Thanks

Pierre

**Comment by rustyrussell** [comment]
pm47 <notifications@github.com> writes:
> Hello,
>
> Currently the only available ones are `insufficient_funds` and `cannot_route`.
>
> But since the commitment tx must be publishable at any time, we might need to decline a new htlc because that would make the tx too big.

Nice catch!

You should never propose such an HTLC, but we should be checking that in
the code.

Thanks!
Rusty.
PS.  I don't suppose your in Montreal now for Scaling Bitcoins?

**Comment by pm47** [comment]
You're welcome !

I won't be attending the conference (stuck in Paris !), but my friend Fabrice will, and if he gets a chance he will be happy to meet and tell you what we are up to

Cheers

Pierre

**Comment by cdecker** [comment]
Is this issue still up to date or shall we just close it?

**Comment by pm47** [comment]
No it's not, closing it
