### ISSUE TITLE
Close negotiation stuck, state CLOSINGD_SIGEXCHANGE

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#5007]
Closed a channel, now seems stuck in a negotiation that's looping. Can I fix this without risking funds on my side or should I just wait?

-channeld-chan#123: peer_out WIRE_CHANNEL_REESTABLISH
-channeld-chan#123: billboard: Sent reestablish, waiting for theirs
-channeld-chan#123: peer_in WIRE_CHANNEL_REESTABLISH
-channeld-chan#123: Got reestablish commit=2278 revoke=2277
-channeld-chan#123: next_revocation_number = 2277
2022-01-13T11:30:30.578Z DEBUG   hsmd: Client: Received message 18 from client
-channeld-chan#123: option_static_remotekey: fields are correct
-channeld-chan#123: peer_out WIRE_SHUTDOWN
-channeld-chan#123: billboard: Funding transaction locked. They need our announcement signatures. Shutdown messages exchanged.
-channeld-chan#123: billboard perm: Reconnected, and reestablished.
-channeld-chan#123: billboard: Funding transaction locked. They need our announcement signatures. Shutdown messages exchanged.
-closingd-chan#123: pid 625217, msgfd 63
2022-01-13T11:30:30.587Z DEBUG   hsmd: new_client: 123
2022-01-13T11:30:30.588Z DEBUG   hsmd: Client: Received message 3 from client
-closingd-chan#123: Expected closing weight = 672, fee 170sat (min 170sat, max 183sat)
-closingd-chan#123: out = 973203sat/36674sat
-closingd-chan#123: dustlimit = 546sat
-closingd-chan#123: fee = 170sat
-closingd-chan#123: fee negotiation step = 50%
-closingd-chan#123: billboard perm: Negotiating closing fee between 170sat and 183sat satoshi (ideal 170sat) using step 50%
-closingd-chan#123: Making close tx at = 973203sat/36674sat fee 170sat
2022-01-13T11:30:30.604Z DEBUG   hsmd: Client: Received message 21 from client
-closingd-chan#123: sending fee offer 170sat
-closingd-chan#123: peer_out WIRE_CLOSING_SIGNED
-closingd-chan#123: billboard: Waiting for their initial closing fee offer: ours was 170sat
-closingd-chan#123: peer_in WIRE_GOSSIP_TIMESTAMP_FILTER
-closingd-chan#123: peer_out WIRE_GOSSIP_TIMESTAMP_FILTER
-closingd-chan#123: peer_in WIRE_SHUTDOWN
-closingd-chan#123: peer_in WIRE_CLOSING_SIGNED
-closingd-chan#123: Making close tx at = 973203sat/36674sat fee 183sat
-closingd-chan#123: Received fee offer 183sat
-closingd-chan#123: ...offer is reasonable
-chan#123: Their actual closing tx fee is 184sat vs previous 184sat
-closingd-chan#123: Feerange init 0sat-183sat, remote higher
-closingd-chan#123: Feerange local update 170sat: now 171sat-183sat
-closingd-chan#123: Feerange remote update 183sat: now 171sat-182sat
-closingd-chan#123: Making close tx at = 973203sat/36674sat fee 176sat
2022-01-13T11:30:31.784Z DEBUG   hsmd: Client: Received message 21 from client
-closingd-chan#123: sending fee offer 176sat
-closingd-chan#123: peer_out WIRE_CLOSING_SIGNED
-closingd-chan#123: Feerange local update 176sat: now 177sat-182sat
-closingd-chan#123: billboard: Waiting for another closing fee offer: ours was 176 satoshi, theirs was 183 satoshi,
-closingd-chan#123: peer_in WIRE_WARNING
-closingd-chan#123: billboard perm: Received warning channel 662756471719ee57a2124a887da2b725cdc11a1627b4bfba4eb387fce4a314f0: Feerange 177sat-182sat below minimum acceptable 183sat
-chan#123: Peer transient failure in CLOSINGD_SIGEXCHANGE: closingd WARNING: warning channel 662756471719ee57a2124a887da2b725cdc11a1627b4bfba4eb387fce4a314f0: Feerange 177sat-182sat below minimum acceptable 183sat
-chan#123: Will try reconnect in 60 seconds
-closingd-chan#123: Status closed, but not exited. Killing
-connectd: disconnect

**Comment by Coinomatron** [comment]
Edit, seems similar to https://github.com/ElementsProject/lightning/issues/4684 
Will wait it out until the default unilateraltimeout hits, if still in error then, I'll reopen.

**Comment by Coinomatron** [comment]
It's been over 48 hours, still the same status. Tor node to clearnet, perhaps that matters.

**Comment by Coinomatron** [comment]
Closed it again with a short time out. State is AWAITING_UNILATERAL now.

**Comment by SimonVrouwe** [comment]
@Coinomatron I had a similar problem trying to close a channel using the `feerange` argument:
`lightning-cli -k close id=03efccf2c383d7bf340da9a3f02e2c23104a0e4fe8ac1a880c8e2dc92fbdacd9df feerange='[1012 1012]'`

ending up with receiving the warning: `Feerange 177sat-182sat below minimum acceptable 183sat`

Of course the feerange I gave was ridiculously low, but subsequent `close` calls **without** a feerange did not fix it, not even after restarting c-lightning, the peer just kept returning above warning and reconnected endlessly.

This problem seems not caused by c-lightning (I tested with 2 c-lightning nodes on pyln-testing setup), but by the remote node getting stuck in our first feerange offer? Above node id is actually @renepickhardt 's node, maybe he can disclose the implementation and version he is running?

**Comment by Coinomatron** [comment]
Ah, I had this issue with the same peer. Didn't set a closing fee initially, by the way, just used the close command. The second time I closed it after waiting 48 hours was with a short time-out (again without fee range) which did force close the channel.
