### ISSUE TITLE
Nodes/Channels missing in the graph

### ISSUE THREAD

**Issue by SeverinAlexB** [ElementsProject/lightning#5020]
### Issue and Steps to Reproduce
Sometimes, the lightning cli doesn't return node and channel information that should exist.

For example, DEK Dynamics [(1ml.com)](https://1ml.com/node/038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15) is online since ever and sends node/channel updates regularly. [Amboss](https://amboss.space/node/038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15) shows that DEKs channels receive updates regularly.

On my c-lightning node, `listnodes` and `listchannels` doesn't show any result if I search for this specific node and it's channels. I saw this behaviour before with other nodes. They sometimes spontaneously recover again after some hours.

@vincenzopalazzo sees this strange behaviour as well.
This bug affects lnrouter.app ability to show node information.

```
lightning-cli listnodes 038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15
{
   "nodes": []
}

lightning-cli listchannels 715001x1603x0
{
   "channels": []
}
```

### `getinfo` output

```
{
   "id": "***",
   "alias": "***",
   "color": "***",
   "num_peers": 25,
   "num_pending_channels": 1,
   "num_active_channels": 12,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "***",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "***",
         "port": 9735
      }
   ],
   "version": "0.10.1",
   "blockheight": 720468,
   "network": "bitcoin",
   "msatoshi_fees_collected": ***,
   "fees_collected_msat": "***",
   "lightning-dir": "/home/bitcoin/.lightning/bitcoin"
}

```

**Comment by cdecker** [comment]
I created a [small addition][lntopo] to the `lntopo` tool to trace a node and its channels. Tracing that node results in the attached file. I'll look at it later, but thought I should share this asap
[038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15-trace.txt](https://github.com/ElementsProject/lightning/files/7941989/038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15-trace.txt)


[lntopo]: https://github.com/lnresearch/topology/blob/22d8a00f93ed9b703a7fbb1e427a1bc59ef1446e/lntopo/__main__.py#L21-L46

**Comment by SimonVrouwe** [comment]
I can confirm above `listnodes` not showing 038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15 with my mainnet node.

Grep' ing in my log-file shows at least one node_announcement for mentioned node:
```
2022-02-15T20:38:35.035Z DEBUG   02fef95f77fe5c3ca3ec120e24f6f740603f5765edfea4d7554086dbba0de76ee6-gossipd: Received node_announcement for node 038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15
```
But it's not in the `gossip_store`, as checked with:
```
./dump-gossipstore gossip_store_2022-02-24.copy | grep -P '038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15'
```

The mentioned channel was closed (and deleted) on 2022-01-25.
```
2022-01-25T23:21:50.926Z DEBUG   gossipd: Deleting channel 715001x1603x0 due to the funding outpoint being spent
```
It seems at that same day all its channels where closed [1ml.com](https://1ml.com/node/038e5c338ab7149348952baf94a165c9e4a750d98619d4268b550081c9d3e9ec15), which also deletes its `channel_announcement` from gossipstore (but we don't log this).
https://github.com/ElementsProject/lightning/blob/1da9b30b9abd26e9861ae199c2754f3d9cf7249f/gossipd/routing.c#L443-L449

One 2022-02-01 it opened a new channel, but closed it again:
```
2022-02-22T20:27:59.802Z DEBUG   gossipd: Deleting channel 721337x1378x6 due to the funding outpoint being spent
```
Which makes its channel count zero again and deletes it from gossipstore and `listnodes`.

Conclusion
When a node's channel count drops to zero, it is removed from our view.

**Comment by SeverinAlexB** [comment]
Ohh wow, so he basically closed all his channels at the same time I checked and Amboss + 1ML didn't catch up on the gossip yet. Sorry to bring this to you guys attention then.

**Comment by jb55** [comment]
this was crashing [lnvis](https://github.com/jb55/lnvis) as well but it seems ok now.
