### ISSUE TITLE
Db migration - closed channels

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#5023]
Did a db migration to a new machine to protect against power outage and somehow the hsm secret file got changed. I really have no idea how this could have happened. After setting this straight, it looks like the channels to other c-lightning nodes went into a awaiting unilateral close state. The closing tx was never broadcast to the bitcoin chain, at least, that's what I gather from trouble shooting and sqlite db commands. The updated state in listpeers had the error 'multiple channels not supported'. Fortunately, I only had 4 peers with c-lightning, 3 of those have closed from their side upon request. 

The fourth however doesn't respond to closure requests. It's been 5 days and as I really would like to get those funds back, is there any way I can close that channel? When I use the close command, it spits out that the channel is in state awaiting unilateral.

**Comment by wtogami** [comment]
What version of c-lightning on the old and new machine?
Did you build a stable release or from master branch?

**Comment by Coinomatron** [comment]
Old machine v0.10.2-190-gb659fbb (jan.2)
New machine v0.10.2-241-gcf2c4c5 (jan.25)
Both compliled from master branch (main page github code git clone, if that's what you mean)

**Comment by Coinomatron** [comment]
To simplify things, I can see in 'listpeers' that the scratch_txid is one that is not broadcast to the Bitcoin chain. The close_to_addr field is one of my correct wallet addresses. Can I publish this unbroadcast tx via sendrawtransaction, to get the peer to close? As the output to me will go to a multisig first, my only hesitation is that lightningd may have changed the output due to the wrong hsm secret file. I don't know how to check if that multisig output belongs to my wallet.
