### ISSUE TITLE
New v0.10.3 backup method?

### ISSUE THREAD

**Issue by iamthen0nce** [ElementsProject/lightning#5026]
According to the [Readthedocs Backup guide](https://lightning.readthedocs.io/BACKUP.html#sqlite3-wallet-main-backup-and-remote-nfs-mount), there is a new way of doing so since v0.10.3, however this version hasn't been released yet.
Or am I missing something?
Or maybe it's just a typo and it's available since v0.10.2?
Clarification would be greatly appreciated!

**Comment by iamthen0nce** [comment]
Looking at [the source code](https://github.com/ElementsProject/lightning/blob/master/wallet/db_sqlite3.c), it does seem this feature is indeed included in v0.10.2, not v0.10.3!

**Comment by vincenzopalazzo** [comment]
It is included with the following PR https://github.com/ElementsProject/lightning/pull/4890

It will be in the next release, that it is not the v0.10.3 but the v0.11, and yes this is a typo

**Comment by Coinomatron** [comment]
I've been using this method for weeks, hadn't noticed the typo. du size output is exactly the same size as the db in .lightning/bitcoin/ as is the time modified. Anything I should worry about?

**Comment by iamthen0nce** [comment]
> I've been using this method for weeks, hadn't noticed the typo. du size output is exactly the same size as the db in .lightning/bitcoin/ as is the time modified. Anything I should worry about?

this would mean you built from master rather than getting a release which is the recommended way. shouldnt be too worried though.
