### ISSUE TITLE
run-sphinx --generate segfaults

### ISSUE THREAD

**Issue by practicalswift** [ElementsProject/lightning#503]
`run-sphinx` segfaults when no parameter is given to the `--generate` flag:

```
$ common/test/run-sphinx --generate
Segmentation fault (core dumped)
```

When passing parameters to the `--generate` flag the following output is given:

```
towire_u8 called!
Aborted (core dumped)
```

What is an example of a correct invocation of `run-sphinx --generate …` that will yield non-error output? :-)

**Comment by cdecker** [comment]
Right, `run-sphinx` used to be a self-contained executable that could generate and unwrap sphinx onion packets. It was mainly used to check compatibility with the golang implementation, which I was implementing in parallel. The `towire_u8` error refers to the use of generated stubs that, which were not used back then. So we have two options: a) remove the standalone functionality, or b) rip out the stubs and compile the tool with the correct dependencies.
