### ISSUE TITLE
AttributeError: module 'mistune' has no attribute 'InlineLexer'

### ISSUE THREAD

**Issue by felipelalli** [ElementsProject/lightning#5063]
When I try to run `make` I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/mrkd", line 5, in <module>
    from mrkd import main
  File "/usr/local/lib/python3.8/dist-packages/mrkd/__init__.py", line 23, in <module>
    class ReferenceLexer(mistune.InlineLexer):
AttributeError: module 'mistune' has no attribute 'InlineLexer'
make: *** [doc/Makefile:107: doc/lightning-cli.1] Error 1
```

**Comment by vincenzopalazzo** [comment]
Yes, this is a known problem where mistune is wrong fixed in the mrkd, to solve this problem you can install the requirements.lock file

So the command to solve this is `pip3 install -r requirements.lock`

**Comment by felipelalli** [comment]
Thanks @vincenzopalazzo ! It worked. But now I got this error when I tried to run the node:

```
2022-03-03T04:05:05.462Z INFO    plugin-fetchinvoice: Killing plugin: could not register hook 'onion_message_ourpath', either the nam
e doesn't exist or another plugin already registered it.
2022-03-03T04:05:05.463Z **BROKEN** plugin-fetchinvoice: Plugin marked as important, shutting down lightningd!
2022-03-03T04:05:05.480Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_channeld
lightningd: lightning_channeld: bad version 'v0.10.2
```

**Comment by vincenzopalazzo** [comment]
What version of c-lightning you are running?

**Comment by felipelalli** [comment]
v0.10.2

**Comment by vincenzopalazzo** [comment]
Sorry for the delay here.

You are building from the tagged version? or from the master.

This is a strange situation, basically, some plugins are trying to register to some event but this event doesn't exist.

Can you try to clean up the compilation, with the following commands, and report what you see?

```
make clean
./configure
make && sudo make install
```

**Comment by felipelalli** [comment]
Hi! I'm using a tagged version:

```
root@xpto:/usr/src/lightning# git describe
v0.10.2
```

**Comment by cmdruid** [comment]
Reporting that I am running into the same exact issue. Currently looking for a work-around.

**Comment by felipelalli** [comment]
After a total system / machine restart, the note started to work again. Thank you.
