### ISSUE TITLE
Tests all fail: TypeError: required field "lineno" missing from alias

### ISSUE THREAD

**Issue by ClayShoaf** [ElementsProject/lightning#5070]
### Issue and Steps to Reproduce
Any time a test is run from ./tests/ it exits with error: `TypeError: required field "lineno" missing from alias`

This appears to be a bug with older versions of pytest as per [this issue](https://github.com/pytest-dev/pytest/discussions/9195?sort=top#discussioncomment-1464910). It seems that ./requirements.txt installs an old version of pytest. 

I tried installing a newer version of pytest and the tests actually run, but almost all of them fail with the following (abridged) output:

```
=================================================== warnings summary ====================================================
noise/test_chat.py: 2947 warnings
  /home/user/github/lightning/contrib/pyln-testing/pyln/testing/utils.py:237: DeprecationWarning: notifyAll() is deprecated, use notify_all() instead
    self.logs_cond.notifyAll()

noise/test_chat.py: 163 warnings
  /home/user/.local/lib/python3.10/site-packages/cheroot/workers/threadpool.py:181: DeprecationWarning: getName() is deprecated, get the name attribute instead
    format(worker_name=worker.getName()),

noise/test_chat.py: 163 warnings
  /home/user/.local/lib/python3.10/site-packages/cheroot/workers/threadpool.py:179: DeprecationWarning: setName() is deprecated, set the name attribute instead
    worker.setName(

noise/test_chat.py: 160 warnings
  /home/user/.local/lib/python3.10/site-packages/cheroot/workers/threadpool.py:111: DeprecationWarning: getName() is deprecated, get the name attribute instead
    self.server.stats['Worker Threads'][self.getName()] = self.stats

noise/test_chat.py: 170 warnings
  /home/user/.local/lib/python3.10/site-packages/cheroot/workers/threadpool.py:323: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
    if thread is not threading.currentThread()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================ short test summary info ================================================
FAILED noise/test_chat.py::test_sendmsg_success - AttributeError: 'NoneType' object has no attribute 'terminate'
FAILED noise/test_chat.py::test_msg_and_keysend - AttributeError: 'NoneType' object has no attribute 'terminate'
FAILED noise/test_chat.py::test_forward_ok - AttributeError: 'NoneType' object has no attribute 'terminate'
FAILED noise/test_chat.py::test_read_tip - AttributeError: 'NoneType' object has no attribute 'terminate'
FAILED noise/test_chat.py::test_read_order - AttributeError: 'NoneType' object has no attribute 'terminate'
FAILED noise/test_chat.py::test_missing_tlv_fields - AttributeError: 'NoneType' object has no attribute 'terminate'
================================ 6 failed, 1 passed, 1 skipped, 3603 warnings in 22.47s =================================
```

I want to contribute to this repo, as well as the [plugins](https://github.com/lightningd/plugins) repo, but I feel like it would be in vain if I can't write/run any tests with meaningful output.

**Comment by vincenzopalazzo** [comment]
Hello,

For the python dependencies you can just run the `pip install -r requirements.lock`  and you should be started with the same dependence of the CI.

**Comment by ClayShoaf** [comment]
What is "the CI"? 

I just tried installing the requirements in `requirements.lock`, and it fails when trying to install the required version of `gprcio`.

```
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in /home/user/.local/lib/python3.10/site-packages
  Rolling back uninstall of grpcio
  Moving to /home/user/.local/lib/python3.10/site-packages/grpc/
   from /home/user/.local/lib/python3.10/site-packages/~rpc
  Moving to /home/user/.local/lib/python3.10/site-packages/grpcio-1.44.0.dist-info/
   from /home/user/.local/lib/python3.10/site-packages/~rpcio-1.44.0.dist-info
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

I have attached the full output. as a file.
[requirements_errors.log](https://github.com/ElementsProject/lightning/files/8193007/requirements_errors.log)

**Comment by vincenzopalazzo** [comment]
Mh, what is your os?

The error looks like `error: legacy-install-failure` related to Windows.

Can you try the following commands?

```
python -m pip install –upgrade pip
pip install –upgrade wheel
pip install –upgrade setuptools
pip install -r requirements.lock
```

Please take a look that the pip command should be different in your local conf, so sometimes it is `pip3` instead of `pip`

**Comment by ClayShoaf** [comment]
I upgraded everything as per your instructions (using `--upgrade`). Tried installing installing the requirements from requirements.lock and I'm still getting an error. It's failing to build the wheel for `grpcio` and `grpcio-tools`.

I am able to install the most recent version of  `grpcio` and `grpcio-tools`, which leads me to believe that it's a problem with these specific versions. I don't know what kind of output would be helpful, and trying to put in an issue for grpcio seems like it would be fruitless since it's not the latest version.

I don't know what the most helpful output to record would be, so let me know and I'll try to install that specific package with `-v` or something like that.

Btw, I use Arch.

**Comment by ClayShoaf** [comment]
Just tried on an Ubuntu machine and I got it working (after dealing with some Ubuntu-specific issues). I noticed Ubuntu is using `python 3.8.10` while Arch is using `python 3.10.2`. I wonder if that's what's causing the problem. Maybe a new bug that everyone gets to look forward to when non-rolling release distros catch up.

**Comment by ClayShoaf** [comment]
Tried using pyenv on arch to confirm and it works with python 3.8.10. I don't know if I should leave this issue open here, since it it a problem caused by the more recent python version, but it is specific to this project's required version of grpcio

**Comment by ClayShoaf** [comment]
Writing up some arch install instructions. After I test it enough, I'll submit a PR to add it to the install docs

**Comment by ClayShoaf** [comment]
Great, it looks like the whole installation process has changed to use poetry instead of a pip requirements file. This is causing other problems. I'll close this and play around with it more until I can properly articulate what my issue is.

For anyone finding this years down the line, you need to use something like pyenv to install a specific version of python for use in your local directory. If you're using Arch, in the main project directory do:

```
sudo pacman -S pyenv
pyenv install 3.8.10    #or whatever version of python your project uses
pyenv local 3.8.10     #this will set the version of python to use for your current directory and all subdirectories
```

Then to your .bashrc or .zshrc or whatever, you need to add:

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv init --path)"
```

then do:

```
source /path/to/[your rc file]
```

You can then check which version of python you are using by running:

```
python -V
```
