### ISSUE TITLE
Can’t withdraw sats - reserved to block after withdraw again

### ISSUE THREAD

**Issue by 21OrangePill** [ElementsProject/lightning#5132]
Hello,
here is my 1. issue 

https://github.com/ElementsProject/lightning/issues/5119

maybe it has to do with the same problem.

Im trying to withdraw Sats from my wallet with ‚lightning-cli with (adress) all‘

error message: 
„code“: 301,
„message“: „Could not afford all using 0 available UTXOs: all short“

Now the sats are blocked again and I have to wait, after the blocked time it’s the same again

![1D07390A-C5E9-488F-A3C9-9E4BF5CDA431](https://user-images.githubusercontent.com/94305839/160167714-6384660d-6b17-4382-86b4-bfbc6fad84f2.jpeg)
![1E773518-8728-490E-92FC-C1BB30E6008F](https://user-images.githubusercontent.com/94305839/160167721-8c102307-3be1-44e0-9c5b-0b714d628083.jpeg)

**Comment by BlackCoin21** [comment]
I have tried it again and now they are blocked again
![Uploading AF54412F-5470-4DD8-B1D8-6A967CC66047.jpeg…]()

**Comment by BlackCoin21** [comment]
I have tried it again and now they are blocked again

![C7177059-5E60-417F-8A22-BB29FAFB73DE](https://user-images.githubusercontent.com/94305839/160229220-3178ad2a-0d5f-4bbe-82ea-e9cbe5fac8b4.jpeg)

**Comment by 21OrangePill** [comment]
"Seedrestore" fixed this onchain problem
