### ISSUE TITLE
Not clear how to use gRPC 

### ISSUE THREAD

**Issue by kiwiidb** [ElementsProject/lightning#5162]
### Issue and Steps to Reproduce
I've already figured out I should add Rust to my Dockerfile and `make` seems to have picked it up:
```
...
 mrkd doc/lightning-hsmtool.8.md
(cd plugins; cargo build --quiet --examples)
cargo build --quiet --bin cln-grpc
cargo build --quiet --example cln-rpc-getinfo
cd external/libwally-core && ./tools/autogen.sh
...
```
However, `lightningd` won't start:
```
lightningd: --grpc-port=9737: unrecognized option
```

**Comment by rustyrussell** [comment]
Ah!  There are two problems:

1. It's not in the plugins/ toplevel directory, so ./lightningd/lightningd won't find it.
2. It's not in the install target, so even when installed it won't work.

Will fix...

**Comment by KayBeSee** [comment]
Has this been added?

I am running v0.11.0.1 and run `lightning-cli plugin list` but am not seeing it in the list of plugins.

```
{
   "command": "list",
   "plugins": [
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/autoclean",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/bcli",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/funder",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/topology",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/keysend",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/offers",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/pay",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/txprepare",
         "active": true
      },
      {
         "name": "/usr/local/bin/../libexec/c-lightning/plugins/spenderp",
         "active": true
      }
   ]
}
```

I also get the `clightning_1  | lightningd: /data/.lightning/config line 9: grpc-port=12345: unrecognized option` when I put `grpc-port=12345` in my config file.

**Comment by whitslack** [comment]
> Has this been added?

@KayBeSee: You need Rust installed on the system where you built Core Lightning. Check the output of `configure` to see whether Rust was detected.

**Comment by KayBeSee** [comment]
I am using the [docker image](https://hub.docker.com/r/elementsproject/lightningd) put out by elementsproject. Is there a way to add rust to that image?

**Comment by vincenzopalazzo** [comment]
>I am using the [docker image](https://hub.docker.com/r/elementsproject/lightningd) put out by elementsproject. Is there a way to add rust to that image?

I think now, maybe you can open an issue, and in the meanwhile, you can test this docker-compose? https://github.com/clightning4j/clightning4j-node/blob/main/examples/grpc-docker-compose.yml

**Comment by KayBeSee** [comment]
I was able to get that docker-compose file to work. It looks like the grpc plugin is enabled there. I will test running some commands against it tomorrow.
