### ISSUE TITLE
Running C-light in docker.  Questions about persistence....

### ISSUE THREAD

**Issue by d4amenace** [ElementsProject/lightning#5178]
I plan on running c-light in docker and am concerned about volumes that need to be created to persist necessary info (btc blocks, necessary lightning related files, etc...) for c-lightning when a container is stopped/started. Docker obviously doesn't persiste and I wanted to know what needs to be retained.

**Comment by vincenzopalazzo** [comment]
I usually keep all the directory `.lightning` persistent on the machine, and if you are running the bitcoin core inside the same container, maybe to need to store also `.bitcoin` directory persistent

This are examples of configuration https://github.com/clightning4j/clightning4j-node/tree/main/examples with my clightning4j tools

**Comment by d4amenace** [comment]
What is the typical size of a fully loaded lightning folder?   So, since I am connecting to a remote bitcoin node I wouldn't need to store anything in the `.bitcoin` folder right?

**Comment by vincenzopalazzo** [comment]
>So, since I am connecting to a remote bitcoin node I wouldn't need to store anything in the .bitcoin folder right?

If you have the Bitcoin core in a different location, you don't need to use bitcoin in the docker file.

>What is the typical size of a fully-loaded lightning folder?

With the last release of the c-lightning (v0.10.2) you have a recompact mode of the DB, so I don't want to say anything on the size, but not much, less than 1GB.

But this depends on the usage of the node.

**Comment by cdecker** [comment]
Size can vary, depending on plugins, choice of database and so on, but a simple node with not too much traffic usually stays at a couple hundred megabyte (my own db is currently at around 160MB, with a couple of channels).

**Comment by cmdruid** [comment]
My current strategy is to specify a separate data directory for lightning (and bitcoin), and store those on the persistent volume. If you do that, however, you will also want to symlink the `~/.lightning/bitcoin` rpc interface (or `~/.lightning/regtest`).

It's easier just to mount `~/.lightning` as a persistent volume, but I prefer the harder method because I do not want the config file to persist in any way, since it gets refreshed with every docker image build.

**Comment by cdecker** [comment]
The same could be achieved by using a different location for the config (.e.g, `/etc/lightningd/config`) and pass that as `--conf` in the `ENTRYPOINT` or `CMD`
