### ISSUE TITLE
AttributeError: module 'mistune' has no attribute 'InlineLexer' 

### ISSUE THREAD

**Issue by JCbette** [ElementsProject/lightning#5181]
After i use the command "pip3 install -r requirements.lock" in #5063, it still can't work. 
That's the detail:
jc@jc-VirtualBox:~/lightning1$ pip3 install --user -r requirements.lock
Requirement already satisfied: apturl==0.5.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 1)) (0.5.2)
Requirement already satisfied: bcrypt==3.1.7 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 2)) (3.1.7)
Requirement already satisfied: blinker==1.4 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 3)) (1.4)
Requirement already satisfied: Brlapi==0.7.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 4)) (0.7.0)
Requirement already satisfied: certifi==2019.11.28 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 5)) (2019.11.28)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 6)) (3.0.4)
Requirement already satisfied: Click==7.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 7)) (7.0)
Requirement already satisfied: colorama==0.4.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 8)) (0.4.3)
Requirement already satisfied: command-not-found==0.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 9)) (0.3)
Requirement already satisfied: cryptography==2.8 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 10)) (2.8)
Requirement already satisfied: cupshelpers==1.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 11)) (1.0)
Requirement already satisfied: dbus-python==1.2.16 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 12)) (1.2.16)
Requirement already satisfied: defer==1.0.6 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 13)) (1.0.6)
Requirement already satisfied: distro==1.4.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 14)) (1.4.0)
Requirement already satisfied: distro-info===0.23ubuntu1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 15)) (0.23ubuntu1)
Requirement already satisfied: duplicity==0.8.12.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 16)) (0.8.12.0)
Requirement already satisfied: entrypoints==0.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 17)) (0.3)
Requirement already satisfied: fasteners==0.14.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 18)) (0.14.1)
Requirement already satisfied: future==0.18.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 19)) (0.18.2)
Requirement already satisfied: httplib2==0.14.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 20)) (0.14.0)
Requirement already satisfied: idna==2.8 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 21)) (2.8)
Requirement already satisfied: Jinja2==3.1.1 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 22)) (3.1.1)
Requirement already satisfied: keyring==18.0.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 23)) (18.0.1)
Requirement already satisfied: language-selector==0.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 24)) (0.1)
Requirement already satisfied: launchpadlib==1.10.13 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 25)) (1.10.13)
Requirement already satisfied: lazr.restfulclient==0.14.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 26)) (0.14.2)
Requirement already satisfied: lazr.uri==1.0.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 27)) (1.0.3)
Requirement already satisfied: lockfile==0.12.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 28)) (0.12.2)
Requirement already satisfied: louis==3.12.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 29)) (3.12.0)
Requirement already satisfied: macaroonbakery==1.3.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 30)) (1.3.1)
Requirement already satisfied: Mako==1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 31)) (1.1.0)
Requirement already satisfied: MarkupSafe==2.1.1 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 32)) (2.1.1)
Requirement already satisfied: mistune==2.0.2 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 33)) (2.0.2)
Requirement already satisfied: monotonic==1.5 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 34)) (1.5)
Requirement already satisfied: mrkd==0.2.0 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 35)) (0.2.0)
Requirement already satisfied: netifaces==0.10.4 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 36)) (0.10.4)
Requirement already satisfied: oauthlib==3.1.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 37)) (3.1.0)
Requirement already satisfied: olefile==0.46 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 38)) (0.46)
Requirement already satisfied: paramiko==2.6.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 39)) (2.6.0)
Requirement already satisfied: pbr==5.8.1 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 40)) (5.8.1)
Requirement already satisfied: pexpect==4.6.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 41)) (4.6.0)
Requirement already satisfied: Pillow==7.0.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 42)) (7.0.0)
Requirement already satisfied: protobuf==3.6.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 43)) (3.6.1)
Requirement already satisfied: pycairo==1.16.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 44)) (1.16.2)
Requirement already satisfied: pycups==1.9.73 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 45)) (1.9.73)
Requirement already satisfied: Pygments==2.11.2 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 46)) (2.11.2)
Requirement already satisfied: PyGObject==3.36.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 47)) (3.36.0)
Requirement already satisfied: PyJWT==1.7.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 48)) (1.7.1)
Requirement already satisfied: pymacaroons==0.13.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 49)) (0.13.0)
Requirement already satisfied: PyNaCl==1.3.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 50)) (1.3.0)
Requirement already satisfied: pyRFC3339==1.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 51)) (1.1)
Requirement already satisfied: python-apt==2.0.0+ubuntu0.20.4.7 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 52)) (2.0.0+ubuntu0.20.4.7)
Requirement already satisfied: python-dateutil==2.7.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 53)) (2.7.3)
Requirement already satisfied: python-debian===0.1.36ubuntu1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 54)) (0.1.36ubuntu1)
Requirement already satisfied: pytz==2019.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 55)) (2019.3)
Requirement already satisfied: pyxdg==0.26 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 56)) (0.26)
Requirement already satisfied: PyYAML==5.3.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 57)) (5.3.1)
Requirement already satisfied: reportlab==3.5.34 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 58)) (3.5.34)
Requirement already satisfied: requests==2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 59)) (2.22.0)
Requirement already satisfied: requests-unixsocket==0.2.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 60)) (0.2.0)
Requirement already satisfied: SecretStorage==2.3.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 61)) (2.3.1)
Requirement already satisfied: simplejson==3.16.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 62)) (3.16.0)
Requirement already satisfied: six==1.14.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 63)) (1.14.0)
Requirement already satisfied: systemd-python==234 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 64)) (234)
Requirement already satisfied: testresources==2.0.1 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 65)) (2.0.1)
Requirement already satisfied: ubuntu-advantage-tools==27.6 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 66)) (27.6)
Requirement already satisfied: ubuntu-drivers-common==0.0.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 67)) (0.0.0)
Requirement already satisfied: ufw==0.36 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 68)) (0.36)
Requirement already satisfied: unattended-upgrades==0.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 69)) (0.1)
Requirement already satisfied: urllib3==1.25.8 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 70)) (1.25.8)
Requirement already satisfied: usb-creator==0.3.7 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 71)) (0.3.7)
Requirement already satisfied: wadllib==1.3.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 72)) (1.3.3)
Requirement already satisfied: xkit==0.0.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 73)) (0.0.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from launchpadlib==1.10.13->-r requirements.lock (line 25)) (45.2.0)
jc@jc-VirtualBox:~/lightning1$ make
CC: cc -DBINTOPKGLIBEXECDIR="../libexec/c-lightning" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -Wno-maybe-uninitialized -std=gnu11 -g -fstack-protector-strong -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I external/x86_64-linux-gnu/libbacktrace-build -I . -I/usr/local/include  -I/usr/include/postgresql    -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DCOMPAT_V060=1 -DCOMPAT_V061=1 -DCOMPAT_V062=1 -DCOMPAT_V070=1 -DCOMPAT_V072=1 -DCOMPAT_V073=1 -DCOMPAT_V080=1 -DCOMPAT_V081=1 -DCOMPAT_V082=1 -DCOMPAT_V090=1 -DCOMPAT_V0100=1 -DBUILD_ELEMENTS=1  -c -o
LD: cc   -Og  config.vars  -Lexternal/x86_64-linux-gnu -lwallycore -lsecp256k1 -ljsmn -lbacktrace -L/usr/local/lib -lm -lgmp -lsqlite3 -lz  -L/usr/lib/x86_64-linux-gnu -lpq -lsodium -o
mrkd doc/lightning-cli.1.md
Traceback (most recent call last):
  File "/home/jc/.local/bin/mrkd", line 5, in <module>
    from mrkd import main
  File "/home/jc/.local/lib/python3.8/site-packages/mrkd/__init__.py", line 23, in <module>
    class ReferenceLexer(mistune.InlineLexer):
AttributeError: module 'mistune' has no attribute 'InlineLexer'
make: *** [doc/Makefile:120: doc/lightning-cli.1] Error 1

**Comment by JCbette** [comment]
I'm sorry, maybe i press some strange buttons, i'will reupload the detail:
c@jc-VirtualBox:~/lightning1$ pip3 install --user -r requirements.lock
Requirement already satisfied: apturl==0.5.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 1)) (0.5.2)
Requirement already satisfied: bcrypt==3.1.7 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 2)) (3.1.7)
Requirement already satisfied: blinker==1.4 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 3)) (1.4)
Requirement already satisfied: Brlapi==0.7.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 4)) (0.7.0)
Requirement already satisfied: certifi==2019.11.28 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 5)) (2019.11.28)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 6)) (3.0.4)
Requirement already satisfied: Click==7.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 7)) (7.0)
Requirement already satisfied: colorama==0.4.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 8)) (0.4.3)
Requirement already satisfied: command-not-found==0.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 9)) (0.3)
Requirement already satisfied: cryptography==2.8 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 10)) (2.8)
Requirement already satisfied: cupshelpers==1.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 11)) (1.0)
Requirement already satisfied: dbus-python==1.2.16 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 12)) (1.2.16)
Requirement already satisfied: defer==1.0.6 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 13)) (1.0.6)
Requirement already satisfied: distro==1.4.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 14)) (1.4.0)
Requirement already satisfied: distro-info===0.23ubuntu1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 15)) (0.23ubuntu1)
Requirement already satisfied: duplicity==0.8.12.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 16)) (0.8.12.0)
Requirement already satisfied: entrypoints==0.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 17)) (0.3)
Requirement already satisfied: fasteners==0.14.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 18)) (0.14.1)
Requirement already satisfied: future==0.18.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 19)) (0.18.2)
Requirement already satisfied: httplib2==0.14.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 20)) (0.14.0)
Requirement already satisfied: idna==2.8 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 21)) (2.8)
Requirement already satisfied: Jinja2==3.1.1 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 22)) (3.1.1)
Requirement already satisfied: keyring==18.0.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 23)) (18.0.1)
Requirement already satisfied: language-selector==0.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 24)) (0.1)
Requirement already satisfied: launchpadlib==1.10.13 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 25)) (1.10.13)
Requirement already satisfied: lazr.restfulclient==0.14.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 26)) (0.14.2)
Requirement already satisfied: lazr.uri==1.0.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 27)) (1.0.3)
Requirement already satisfied: lockfile==0.12.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 28)) (0.12.2)
Requirement already satisfied: louis==3.12.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 29)) (3.12.0)
Requirement already satisfied: macaroonbakery==1.3.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 30)) (1.3.1)
Requirement already satisfied: Mako==1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 31)) (1.1.0)
Requirement already satisfied: MarkupSafe==2.1.1 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 32)) (2.1.1)
Requirement already satisfied: mistune==2.0.2 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 33)) (2.0.2)
Requirement already satisfied: monotonic==1.5 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 34)) (1.5)
Requirement already satisfied: mrkd==0.2.0 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 35)) (0.2.0)
Requirement already satisfied: netifaces==0.10.4 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 36)) (0.10.4)
Requirement already satisfied: oauthlib==3.1.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 37)) (3.1.0)
Requirement already satisfied: olefile==0.46 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 38)) (0.46)
Requirement already satisfied: paramiko==2.6.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 39)) (2.6.0)
Requirement already satisfied: pbr==5.8.1 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 40)) (5.8.1)
Requirement already satisfied: pexpect==4.6.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 41)) (4.6.0)
Requirement already satisfied: Pillow==7.0.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 42)) (7.0.0)
Requirement already satisfied: protobuf==3.6.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 43)) (3.6.1)
Requirement already satisfied: pycairo==1.16.2 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 44)) (1.16.2)
Requirement already satisfied: pycups==1.9.73 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 45)) (1.9.73)
Requirement already satisfied: Pygments==2.11.2 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 46)) (2.11.2)
Requirement already satisfied: PyGObject==3.36.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 47)) (3.36.0)
Requirement already satisfied: PyJWT==1.7.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 48)) (1.7.1)
Requirement already satisfied: pymacaroons==0.13.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 49)) (0.13.0)
Requirement already satisfied: PyNaCl==1.3.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 50)) (1.3.0)
Requirement already satisfied: pyRFC3339==1.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 51)) (1.1)
Requirement already satisfied: python-apt==2.0.0+ubuntu0.20.4.7 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 52)) (2.0.0+ubuntu0.20.4.7)
Requirement already satisfied: python-dateutil==2.7.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 53)) (2.7.3)
Requirement already satisfied: python-debian===0.1.36ubuntu1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 54)) (0.1.36ubuntu1)
Requirement already satisfied: pytz==2019.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 55)) (2019.3)
Requirement already satisfied: pyxdg==0.26 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 56)) (0.26)
Requirement already satisfied: PyYAML==5.3.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 57)) (5.3.1)
Requirement already satisfied: reportlab==3.5.34 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 58)) (3.5.34)
Requirement already satisfied: requests==2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 59)) (2.22.0)
Requirement already satisfied: requests-unixsocket==0.2.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 60)) (0.2.0)
Requirement already satisfied: SecretStorage==2.3.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 61)) (2.3.1)
Requirement already satisfied: simplejson==3.16.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 62)) (3.16.0)
Requirement already satisfied: six==1.14.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 63)) (1.14.0)
Requirement already satisfied: systemd-python==234 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 64)) (234)
Requirement already satisfied: testresources==2.0.1 in /home/jc/.local/lib/python3.8/site-packages (from -r requirements.lock (line 65)) (2.0.1)
Requirement already satisfied: ubuntu-advantage-tools==27.6 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 66)) (27.6)
Requirement already satisfied: ubuntu-drivers-common==0.0.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 67)) (0.0.0)
Requirement already satisfied: ufw==0.36 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 68)) (0.36)
Requirement already satisfied: unattended-upgrades==0.1 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 69)) (0.1)
Requirement already satisfied: urllib3==1.25.8 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 70)) (1.25.8)
Requirement already satisfied: usb-creator==0.3.7 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 71)) (0.3.7)
Requirement already satisfied: wadllib==1.3.3 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 72)) (1.3.3)
Requirement already satisfied: xkit==0.0.0 in /usr/lib/python3/dist-packages (from -r requirements.lock (line 73)) (0.0.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from launchpadlib==1.10.13->-r requirements.lock (line 25)) (45.2.0)
jc@jc-VirtualBox:~/lightning1$ make
CC: cc -DBINTOPKGLIBEXECDIR="../libexec/c-lightning" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -Wno-maybe-uninitialized -std=gnu11 -g -fstack-protector-strong -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I external/x86_64-linux-gnu/libbacktrace-build -I . -I/usr/local/include  -I/usr/include/postgresql    -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DCOMPAT_V060=1 -DCOMPAT_V061=1 -DCOMPAT_V062=1 -DCOMPAT_V070=1 -DCOMPAT_V072=1 -DCOMPAT_V073=1 -DCOMPAT_V080=1 -DCOMPAT_V081=1 -DCOMPAT_V082=1 -DCOMPAT_V090=1 -DCOMPAT_V0100=1 -DBUILD_ELEMENTS=1  -c -o
LD: cc   -Og  config.vars  -Lexternal/x86_64-linux-gnu -lwallycore -lsecp256k1 -ljsmn -lbacktrace -L/usr/local/lib -lm -lgmp -lsqlite3 -lz  -L/usr/lib/x86_64-linux-gnu -lpq -lsodium -o
mrkd doc/lightning-cli.1.md
Traceback (most recent call last):
  File "/home/jc/.local/bin/mrkd", line 5, in <module>
    from mrkd import main
  File "/home/jc/.local/lib/python3.8/site-packages/mrkd/__init__.py", line 23, in <module>
    class ReferenceLexer(mistune.InlineLexer):
AttributeError: module 'mistune' has no attribute 'InlineLexer'
make: *** [doc/Makefile:120: doc/lightning-cli.1] Error 1

**Comment by cmdruid** [comment]
What was your resolution for this?

**Comment by martindale** [comment]
What was the fix?

**Comment by MrHash** [comment]
This problem seems to be resolved by installing with `mistune==0.8.4` but in clightning versions >=0.12 it looks like mrkd and mistune are not required anymore https://github.com/ElementsProject/lightning/blob/master/CHANGELOG.md#0121---2022-09-13-web-8-init-dot-one
