### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '-ruquirements.lock'

### ISSUE THREAD

**Issue by JCbette** [ElementsProject/lightning#5182]
When i try to use the command form #5063 pip3 install --user -r requirements.lock, i meet the problems:
jc@jc-VirtualBox:~/lightning1$ pip3 install --user -r requirements.lock
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '-ruquirements.lock'

**Comment by vincenzopalazzo** [comment]
There is a new doc that use poetry https://github.com/ElementsProject/lightning/blob/master/doc/INSTALL.md#to-build-on-ubuntu

Can you try poetry?

**Comment by JCbette** [comment]
When i use the command "poetry install", here is a problem :
  • Installing mako (1.2.0)
  • Installing mrkd (0.2.0 781f05e): Failed

  CalledProcessError

  Command '['git', 'clone', '--recurse-submodules', '--', 'https://github.com/refi64/mrkd.git', '/home/jc/.cache/pypoetry/virtualenvs/cln-meta-project-db36GmWN-py3.8/src/mrkd']' returned non-zero exit status 128.

  at ~/.local/lib/python3.8/site-packages/poetry/utils/_compat.py:217 in run
      213│                 process.wait()
      214│                 raise
      215│             retcode = process.poll()
      216│             if check and retcode:
    → 217│                 raise CalledProcessError(
      218│                     retcode, process.args, output=stdout, stderr=stderr
      219│                 )
      220│         finally:
      221│             # None because our context manager __exit__ does not use them.

  • Installing mypy (0.931)
  • Installing pytest-custom-exit-code (0.3.0)
  • Installing pytest-test-groups (1.0.3)

And when i use the command "poetry run make", the problem happen again:

ld tests/plugins/test_selfdisable_after_getmanifest
mrkd doc/lightning-cli.1.md
Traceback (most recent call last):
  File "/home/jc/.local/bin/mrkd", line 5, in <module>
    from mrkd import main
  File "/home/jc/.local/lib/python3.8/site-packages/mrkd/__init__.py", line 23, in <module>
    class ReferenceLexer(mistune.InlineLexer):
AttributeError: module 'mistune' has no attribute 'InlineLexer'
make: *** [doc/Makefile:120: doc/lightning-cli.1] Error 1

**Comment by vincenzopalazzo** [comment]
Are you running this command in the last and clean version of c-lightning?

This error should never happen because of the poetry.lock there is a different version that fixed this bug, if this happens this meant that poetry are not using the lock file, and the only way is that you ran poetry out of the root directory

```
File "/home/jc/.local/lib/python3.8/site-packages/mrkd/init.py", line 23, in
class ReferenceLexer(mistune.InlineLexer):
AttributeError: module 'mistune' has no attribute 'InlineLexer'
make: *** [doc/Makefile:120: doc/lightning-cli.1] Error 1
```

Can you double-check?

**Comment by cdecker** [comment]
> Command '['git', 'clone', '--recurse-submodules', '--', 'https://github.com/refi64/mrkd.git', '/home/jc/.cache/pypoetry/virtualenvs/cln-meta-project-db36GmWN-py3.8/src/mrkd']' returned non-zero exit status 128.
> 
> at ~/.local/lib/python3.8/site-packages/poetry/utils/_compat.py:217 in run 213│ process.wait() 214│ raise 215│ retcode = process.poll() 216│ if check and retcode: → 217│ raise CalledProcessError( 218│ retcode, process.args, output=stdout, stderr=stderr 219│ ) 220│ finally: 221│ # None because our context manager **exit** does not use them.

Do you have `git` installed? Can you try running the command `git clone --recurse-submodules -- https://github.com/refi64/mrkd.git /tmp/mrkd`. That should help us debug why that failed.

Fwiw, it *did not* update `mrkd` to the version specified, hence the failure.

**Comment by JCbette** [comment]
Yes, i did't use the poetry in a clean version, but i reuse the command `poetry install` after i open the agent, it installed the mrkd successfully without using the command `git clone --recurse-submodules -- https://github.com/refi64/mrkd.git /tmp/mrkd`:

jc@jc-VirtualBox:~/lightning1$ poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing mrkd (0.2.0 781f05e)
jc@jc-VirtualBox:~/lightning1$ ./configure

And i finally build my lightning!
Anyway, i love both of you guys, i'm a student and it seems my homework is alive.

**Comment by vincenzopalazzo** [comment]
>Anyway, i love both of you guys, I'm a student and it seems my homework is alive.

Homework with c-lightning, why only my homework was boring? :) Have fun!

**Comment by cdecker** [comment]
Great, closing as resolved then. Seems like it was just a Github blip.
