### ISSUE TITLE
Can i use regtest with lightningd?

### ISSUE THREAD

**Issue by JCbette** [ElementsProject/lightning#5188]
I configure the `bitcoin.conf` with `regtest`:

> regtest = 1
> daemon = 1
> rpcuser = XXX
> rpcpassword=XXX
> server = 1
> rpcallowip=127.0.0.1
> txindex =1
> [regtest]
> rpcbind = 127.0.0.1

And try to initialize the lightningd:

> jc@jc-VirtualBox:~/lightning1$ ./lightningd/lightningd --network=regtest 
> 2022-04-15T11:14:12.010Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
> 2022-04-15T11:14:12.090Z INFO    lightningd: --------------------------------------------------
> 2022-04-15T11:14:12.090Z INFO    lightningd: Server started with public key 02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3, alias SLEEPYCHIPMUNK (color #02ce6f) and lightningd v0.11.0rc2-5-gc36cef0

But it just stop in here and without other logS, and the lightning-cli can't conect:

> jc@jc-VirtualBox:~/lightning1$ ./cli/lightning-cli help
> lightning-cli: Connecting to 'lightning-rpc': Connection refused

**Comment by vincenzopalazzo** [comment]
for this type of question maybe you are interested in discord channel https://discord.gg/eJn3qVwz ?

The solution is to tell the `lightning-cli` that you won't use the request

`./cli/lightning-cli --network=regtest help`

**Comment by JCbette** [comment]
I also get the result:

> jc@jc-VirtualBox:~/lightning1$ ./cli/lightning-cli --network=regtest help
> lightning-cli: Connecting to 'lightning-rpc': Connection refused

I think there may have some problems when i use the `./lightningd/lightningd --network=regtest` for it stop here without any other logs:

> jc@jc-VirtualBox:~/lightning1$ ./lightningd/lightningd --network=regtest
> 2022-04-15T14:45:45.186Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
> 2022-04-15T14:45:45.239Z INFO    lightningd: --------------------------------------------------
> 2022-04-15T14:45:45.241Z INFO    lightningd: Server started with public key 02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3, alias SLEEPYCHIPMUNK (color #02ce6f) and lightningd v0.11.0rc2-5-gc36cef0
>

**Comment by JCbette** [comment]
Maybe the lightningd needs a configuration file `.conf` that needs me to set by myself like bitcoind?

**Comment by JCbette** [comment]
> for this type of question maybe you are interested in discord channel https://discord.gg/eJn3qVwz ?
> 
> The solution is to tell the `lightning-cli` that you want to use the regtest netweork
> 
> `./cli/lightning-cli --network=regtest help`

**Comment by vincenzopalazzo** [comment]
The following line says that your node is up and running! 

>2022-04-15T14:45:45.241Z INFO lightningd: Server started with public key 02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3, alias SLEEPYCHIPMUNK (color #02ce6f) and lightningd v0.11.0rc2-5-gc36cef0

Not sure how you are managing regtest node, but at some point, you need to say to bitcoind to generate blocks. However, if you are making an assignment, why you are not running a core lightning node in testnet, and maybe use some plugin instead of bitcoind that helps you to speed up the node in less than 10 minutes?

In addition, what is the part that is causing you the confusion on the How to start readme file https://github.com/ElementsProject/lightning#getting-started ? maybe in this way we can find the problem that are causing you trouble

**Comment by JCbette** [comment]
@vincenzopalazzo 
[the](https://github.com/clightning4j/btcli4j) Is the plugin you mean? Thanks and i'll try it after i install the jdk. You know, i didn't run in testnet because i wait for synchronizing with it for a long time.

The problem confuse me is in [](https://lightning.readthedocs.io/INSTALL.html) about running lightning. But as the command in  [https://github.com/ElementsProject/lightning#getting-started](url) `lightningd --network=regtest --log-level=debug`, that is the logs...

> lightningd --network=regtest --log-level=debug
> 2022-04-16T01:19:49.981Z DEBUG   plugin-manager: started(3289) /usr/local/bin/../libexec/c-lightning/plugins/autoclean
> 2022-04-16T01:19:49.995Z DEBUG   plugin-manager: started(3290) /usr/local/bin/../libexec/c-lightning/plugins/bcli
> 2022-04-16T01:19:50.005Z DEBUG   plugin-manager: started(3291) /usr/local/bin/../libexec/c-lightning/plugins/fetchinvoice
> 2022-04-16T01:19:50.031Z DEBUG   plugin-manager: started(3292) /usr/local/bin/../libexec/c-lightning/plugins/funder
> 2022-04-16T01:19:50.038Z DEBUG   plugin-manager: started(3293) /usr/local/bin/../libexec/c-lightning/plugins/topology
> 2022-04-16T01:19:50.073Z DEBUG   plugin-manager: started(3294) /usr/local/bin/../libexec/c-lightning/plugins/keysend
> 2022-04-16T01:19:50.095Z DEBUG   plugin-manager: started(3295) /usr/local/bin/../libexec/c-lightning/plugins/offers
> 2022-04-16T01:19:50.106Z DEBUG   plugin-manager: started(3296) /usr/local/bin/../libexec/c-lightning/plugins/pay
> 2022-04-16T01:19:50.149Z DEBUG   plugin-manager: started(3297) /usr/local/bin/../libexec/c-lightning/plugins/txprepare
> 2022-04-16T01:19:50.154Z DEBUG   plugin-manager: started(3298) /usr/local/bin/../libexec/c-lightning/plugins/spenderp
> 2022-04-16T01:19:50.349Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_channeld
> 2022-04-16T01:19:50.351Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_closingd
> 2022-04-16T01:19:50.352Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_connectd
> 2022-04-16T01:19:50.354Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_gossipd
> 2022-04-16T01:19:50.356Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_hsmd
> 2022-04-16T01:19:50.357Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_onchaind
> 2022-04-16T01:19:50.359Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_openingd
> 2022-04-16T01:19:50.367Z DEBUG   hsmd: pid 3306, msgfd 35
> 2022-04-16T01:19:50.433Z DEBUG   connectd: pid 3307, msgfd 39
> 2022-04-16T01:19:50.433Z DEBUG   hsmd: new_client: 0
> 2022-04-16T01:19:50.465Z DEBUG   connectd: Created listener on [::]:19846
> 2022-04-16T01:19:50.465Z DEBUG   connectd: Failed to connect 10 socket: Network is unreachable
> 2022-04-16T01:19:50.465Z DEBUG   connectd: Created listener on 0.0.0.0:19846
> 2022-04-16T01:19:50.465Z DEBUG   connectd: REPLY WIRE_CONNECTD_INIT_REPLY with 0 fds
> 2022-04-16T01:19:50.465Z DEBUG   connectd: connectd_init_done
> 2022-04-16T01:19:50.487Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
> 2022-04-16T01:19:50.487Z DEBUG   lightningd: All Bitcoin plugin commands registered
> 2022-04-16T01:19:50.528Z DEBUG   lightningd: Adding block 191: 3a53f6e4fe6794fe9b5acda8c4cf459f0952e4d158d4003d15e9668a99b627ad
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Smoothed feerate estimate for opening initialized to polled estimate 250
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: ... feerate estimate for opening hit floor 253
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Feerate estimate for opening set to 253 (was 0)
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Smoothed feerate estimate for mutual_close initialized to polled estimate 250
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: ... feerate estimate for mutual_close hit floor 253
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Feerate estimate for mutual_close set to 253 (was 0)
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Smoothed feerate estimate for unilateral_close initialized to polled estimate 250
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: ... feerate estimate for unilateral_close hit floor 253
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Feerate estimate for unilateral_close set to 253 (was 0)
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Smoothed feerate estimate for delayed_to_us initialized to polled estimate 250
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: ... feerate estimate for delayed_to_us hit floor 253
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Feerate estimate for delayed_to_us set to 253 (was 0)
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Smoothed feerate estimate for htlc_resolution initialized to polled estimate 250
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: ... feerate estimate for htlc_resolution hit floor 253
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Feerate estimate for htlc_resolution set to 253 (was 0)
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Smoothed feerate estimate for penalty initialized to polled estimate 250
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: ... feerate estimate for penalty hit floor 253
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Feerate estimate for penalty set to 253 (was 0)
> 2022-04-16T01:19:50.534Z DEBUG   lightningd: Smoothed feerate estimate for min_acceptable initialized to polled estimate 125
> 2022-04-16T01:19:50.535Z DEBUG   lightningd: ... feerate estimate for min_acceptable hit floor 253
> 2022-04-16T01:19:50.535Z DEBUG   lightningd: Feerate estimate for min_acceptable set to 253 (was 0)
> 2022-04-16T01:19:50.535Z DEBUG   lightningd: Smoothed feerate estimate for max_acceptable initialized to polled estimate 2500
> 2022-04-16T01:19:50.535Z DEBUG   lightningd: Feerate estimate for max_acceptable set to 2500 (was 0)
> 2022-04-16T01:19:50.535Z DEBUG   wallet: Loaded 0 channels from DB
> 2022-04-16T01:19:50.536Z DEBUG   gossipd: pid 3316, msgfd 38
> 2022-04-16T01:19:50.537Z DEBUG   hsmd: new_client: 0
> 2022-04-16T01:19:50.605Z DEBUG   gossipd: gossip_store_compact_offline: 0 deleted, 0 copied
> 2022-04-16T01:19:50.605Z DEBUG   gossipd: total store load time: 0 msec
> 2022-04-16T01:19:50.605Z DEBUG   gossipd: gossip_store: Read 0/0/0/0 cannounce/cupdate/nannounce/cdelete from store (0 deleted) in 1 bytes
> 2022-04-16T01:19:50.605Z DEBUG   gossipd: seeker: state = STARTING_UP New seeker
> 2022-04-16T01:19:50.605Z DEBUG   gossipd: REPLY WIRE_GOSSIPD_INIT_REPLY with 0 fds
> 2022-04-16T01:19:50.606Z DEBUG   plugin-autoclean: autocleaning not active
> 2022-04-16T01:19:50.606Z DEBUG   connectd: REPLY WIRE_CONNECTD_ACTIVATE_REPLY with 0 fds
> 2022-04-16T01:19:50.607Z INFO    lightningd: --------------------------------------------------
> 2022-04-16T01:19:50.607Z INFO    lightningd: Server started with public key 02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3, alias SLEEPYCHIPMUNK (color #02ce6f) and lightningd v0.11.0rc2-6-gb359a24
> 2022-04-16T01:19:50.608Z DEBUG   plugin-fetchinvoice: Killing plugin: disabled itself at init: offers not enabled in config
> 2022-04-16T01:19:50.622Z DEBUG   lightningd: Adding block 192: 6fcef2d938d1bde57ef687089e4920255248d226e2c8d8534c99b6cf2f183b43
> 2022-04-16T01:19:50.650Z DEBUG   lightningd: Adding block 193: 134eb7dc46b10ae217cadec431cac7878a610014a5ba72a02255314df6291a2d
> 2022-04-16T01:19:50.685Z DEBUG   lightningd: Adding block 194: 4c9585c74cb0decf881b3d86285cc75bc5a195e23697455cfc68848f93132da2
> 2022-04-16T01:19:50.706Z DEBUG   lightningd: Adding block 195: 17d98db1a9867fdecec1c7753d3f481853281daf2bd756c76234135962ed9f97
> 2022-04-16T01:19:50.725Z DEBUG   lightningd: Adding block 196: 1c5f1d4a1af664b14cbb83d483d004062eecad0f2ee01ca81c8e8af175e1873b
> 2022-04-16T01:19:50.742Z DEBUG   lightningd: Adding block 197: 7c7582fcb5dc3b0bda0dccf065a33ba849a33ba51b49530d516ba4f1dbfe2127
> 2022-04-16T01:19:50.764Z DEBUG   lightningd: Adding block 198: 3b31078ec6062b180cc6aeeb1e62d5b07fcbf4eb6d1387e3a95c39005d35aaa0
> 2022-04-16T01:19:50.775Z DEBUG   lightningd: Adding block 199: 00f5843a5dcf09c2b8c49417693d804cc33ef555a9cda2da40ed54f2d5e54521
> 2022-04-16T01:19:50.789Z DEBUG   lightningd: Adding block 200: 481bd385ee00c0ed1c683866a8751707a2e82b445535cfe5b260e2daafe7b6c7
> 2022-04-16T01:19:50.802Z DEBUG   lightningd: Adding block 201: 6ff63d51c6deefbe51188dfc32858aaa3d9eb3ab6636645703eeb8131f2ad523
> 2022-04-16T01:19:50.825Z DEBUG   lightningd: Adding block 202: 4a2b7cb570b2fb416a3a1ca380b9b14dd600863d3e500f6824ab083f7f504465
> 2022-04-16T01:19:50.837Z DEBUG   lightningd: Adding block 203: 7d2e26a38450ad9fa4778913271cc2c1a0ba361b8e7d5934fb62bf8a838bcff7
> 2022-04-16T01:19:50.849Z DEBUG   lightningd: Adding block 204: 0da9969a7c312e3e42da60662002bc06d557f001ccb2aec55a1d608bbd3c32d0
> 2022-04-16T01:19:50.861Z DEBUG   lightningd: Adding block 205: 0ff4b4f330458b9cb66fc0afcab1bcd71fbec26c7ac4c037937284aaebbeeebd
> 2022-04-16T01:19:50.873Z DEBUG   lightningd: Adding block 206: 7a0e005ced3c9da36580e239ea2acc578155588296f1eaa201ca4412823e5f9a
> 2022-04-16T01:19:50.889Z DEBUG   lightningd: Adding block 207: 1e6b94bc5f8ec66464cad4629dac83644e5073f051ba8593144382a4836618fa
> 2022-04-16T01:19:50.903Z DEBUG   lightningd: Adding block 208: 50eb20988d0bc56663f2f142b58c4ad070227cad06d3ab05e78201019c581f01
> 2022-04-16T01:19:50.929Z DEBUG   lightningd: Adding block 209: 444f107d8ac04012d27b9e89194e3f362d00a42f4b85cfa137d957d594818e11
> 2022-04-16T01:19:50.954Z DEBUG   lightningd: Adding block 210: 1467b89d4d1a1f8ef9c6fa03aa4324d203e1d8bb2a674ee40c33ac60c1260d3b
> 2022-04-16T01:19:50.973Z DEBUG   lightningd: Adding block 211: 2ba12f152308158b043e8be77f0122144bb3b85ac9d7514dd966bb6188ec076d
> 2022-04-16T01:19:50.989Z DEBUG   lightningd: Adding block 212: 5ca6372e528740e89224bedd5d79fc42736034bd9ca98c5907a12cac6463005d
> 2022-04-16T01:19:51.012Z DEBUG   lightningd: Adding block 213: 7d6abfda29be523e9a6090e0c3171632f179b7fdf1d90692bf6b3536cbccec76
> 2022-04-16T01:19:51.024Z DEBUG   lightningd: Adding block 214: 00507f03dec01001149ad394c0ac50e7df19d4202025f63f75d6cc2a27d93852
> 2022-04-16T01:19:51.045Z DEBUG   lightningd: Adding block 215: 5ccf4f37d15eb9903dfcb38f682288db518c209441c0eb45fcd913f33b1472fc
> 2022-04-16T01:19:51.060Z DEBUG   lightningd: Adding block 216: 52d1f756bfa8b7537fe1952a20feb591393b9106baf790713db3240384bfd9b4
> 2022-04-16T01:19:51.081Z DEBUG   lightningd: Adding block 217: 2fef1d6492ffb83db6dae15f214cd93af0efc75b5b81d473b11ecc47e2a8a88b
> 2022-04-16T01:19:51.092Z DEBUG   lightningd: Adding block 218: 4b1374bb6731b6d25ac524128c7f4c9e228d4d8f838dca419aecbc7fc3d78318
> 2022-04-16T01:19:51.114Z DEBUG   lightningd: Adding block 219: 0e6345100d2cf7e52c450f1a8be145246d214fbea4351526a2dbe65bcd80a814
> 2022-04-16T01:19:51.126Z DEBUG   lightningd: Adding block 220: 2cfa8c77956ec075736d05260e93ab68993c23f36d04f1da4b6ae19314041861
> 2022-04-16T01:19:51.150Z DEBUG   lightningd: Adding block 221: 55f13a97c41c9ba167744b56fdbe8dfb404f244d58df85a85e1eb36e60445a45
> 2022-04-16T01:19:51.213Z DEBUG   gossipd: REPLY WIRE_GOSSIPD_NEW_BLOCKHEIGHT_REPLY with 0 fds
> 2022-04-16T01:20:20.556Z DEBUG   lightningd: ... feerate estimate for opening hit floor 253
> 2022-04-16T01:20:20.556Z DEBUG   lightningd: ... feerate estimate for mutual_close hit floor 253
> 2022-04-16T01:20:20.556Z DEBUG   lightningd: ... feerate estimate for unilateral_close hit floor 253
> 2022-04-16T01:20:20.556Z DEBUG   lightningd: ... feerate estimate for delayed_to_us hit floor 253
> 2022-04-16T01:20:20.556Z DEBUG   lightningd: ... feerate estimate for htlc_resolution hit floor 253
> 2022-04-16T01:20:20.556Z DEBUG   lightningd: ... feerate estimate for penalty hit floor 253
> 2022-04-16T01:20:20.556Z DEBUG   lightningd: ... polled feerate estimate for min_acceptable (125) smoothed to 196 (alpha=0.44)
> 2022-04-16T01:20:20.556Z DEBUG   lightningd: ... feerate estimate for min_acceptable hit floor 253
And i still can't use the command `lightning-cli`：

> jc@jc-VirtualBox:~/.bitcoin$ lightning-cli help
> lightning-cli: Connecting to 'lightning-rpc': Connection refused
> jc@jc-VirtualBox:~/.bitcoin$ lightning-cli newaddr
> lightning-cli: Connecting to 'lightning-rpc': Connection refused
>

**Comment by JCbette** [comment]
Should add a `config` in `.lightning/` and the problem will be resolved. So close.
