### ISSUE TITLE
"ERROR: git is required for generating version information".  Stop.

### ISSUE THREAD

**Issue by JCbette** [ElementsProject/lightning#5189]
I re-load the project and meet the problem

> Makefile:7: *** "ERROR: git is required for generating version information".  Stop.

When i use the command `$ sudo make install`

**Comment by vincenzopalazzo** [comment]
what system are you using?

try to run the command `git --version`

You should see some things like that

```
➜  ~ git --version      
git version 2.25.1

```

**Comment by JCbette** [comment]
yes, i get the correct output:

> jc@jc:~/lightning$ git --version
> git version 2.25.1

**Comment by vincenzopalazzo** [comment]
you are on arch linux?

**Comment by JCbette** [comment]
i am on a virtual machine with ubuntu 20.04

**Comment by vincenzopalazzo** [comment]
This is strange, somehow the make file at like 9 doesn't evaluate the `shell git` command.

Not sure what is happening, maybe @rustyrussell or @cdecker have a better idea of what is going on on the make file. I'm not an expert!

**Comment by JCbette** [comment]
Anyway, thank you so much!

**Comment by ohenrik** [comment]
I have the same issue on Ubuntu. Tried to install main branch and v0.10.2, both produced the same error

**Comment by JCbette** [comment]
Did you resolve the problem? Could you please tell me the command please? I have a little don't know what is your mean

**Comment by ohenrik** [comment]
If you are asking me, then no. I'll try again later today, but would really like some help on this if its possible.

**Comment by JCbette** [comment]
> If you are asking me, then no. I'll try again later today, but would really like some help on this if its possible.

All right, good luck to you! 
And keep in contact.

**Comment by vincenzopalazzo** [comment]
Can you try to run the following command

```
git config --global --add safe.directory `pwd`
make && make install
```

**Comment by JCbette** [comment]
It still can't work:

> jc@jc:~/lightning$ git config --global --add safe.directory 'pwd'
> jc@jc:~/lightning$ make && make install
> CC: cc -DBINTOPKGLIBEXECDIR="../libexec/c-lightning" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -Wno-maybe-uninitialized -std=gnu11 -g -fstack-protector-strong -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I external/x86_64-linux-gnu/libbacktrace-build -I . -I/usr/local/include  -I/usr/include/postgresql    -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DCOMPAT_V060=1 -DCOMPAT_V061=1 -DCOMPAT_V062=1 -DCOMPAT_V070=1 -DCOMPAT_V072=1 -DCOMPAT_V073=1 -DCOMPAT_V080=1 -DCOMPAT_V081=1 -DCOMPAT_V082=1 -DCOMPAT_V090=1 -DCOMPAT_V0100=1 -DBUILD_ELEMENTS=1  -c -o
> LD: cc   -Og  config.vars  -Lexternal/x86_64-linux-gnu -lwallycore -lsecp256k1 -ljsmn -lbacktrace -L/usr/local/lib -lm -lgmp -lsqlite3 -lz  -L/usr/lib/x86_64-linux-gnu -lpq -lsodium -o
> genidx doc/index.rst
> mkdir -p /usr/local/bin
> mkdir -p /usr/local/libexec/c-lightning
> mkdir: cannot create directory ‘/usr/local/libexec’: Permission denied
> make: *** [Makefile:711: installdirs] Error 1
> jc@jc:~/lightning$ sudo make && make install
> [sudo] password for jc: 
> Makefile:7: *** "ERROR: git is required for generating version information".  Stop.
>

**Comment by vincenzopalazzo** [comment]
This will solve your problem 

**git config --system --add safe.directory `pwd`'/*'**

with more information, the sudo make will access to the system configuration, and with my previous commit you change only the user configs

**Comment by JCbette** [comment]
> **git config --system --add safe.directory `pwd`'/*'**
Ok, i'll try for a while. 
Could you please help with my another problem #5209 in my another machine.

**Comment by JCbette** [comment]
> Please not you should include the pwd between ` and not '

What is this means?　The please was exactly denied...

> jc@jc:~$ git config --system --add safe.directory pwd'/*'
> error: could not lock config file /etc/gitconfig: Permission denied
>

**Comment by ohenrik** [comment]
@JCbette It means you need to run the command as with sudo: `sudo git config --system --add safe.directory pwd'/*'`.
