### ISSUE TITLE
Update_fee status, offline node

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#5190]
Someone opened a channel to me, but it keeps being offline. 'listfunds' also says it's not connected, but channel state says "CHANNEL NORMAL". Getting a fee status message I haven't seen before on listpeers and I'm beginning to suspect it has something to do with it being offline.

                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_NORMAL",
                     "cause": "remote",
                     "message": "Lockin complete"
                  }
               ],
               "status": [
                  "CHANNELD_NORMAL:update_fee 17752 outside range 253-12453 (currently 1360)",
                  "CHANNELD_NORMAL:Will attempt reconnect in 60 seconds"

**Comment by rustyrussell** [comment]
They are trying to set a high fee, we keep rejecting it:

```
update_fee 17752 outside range 253-12453 (currently 1360)
```

We should eventually come into agreement on fees. If not, the channel will never be usable. Do you know what software the other end is running?

**Comment by Coinomatron** [comment]
Thanks for the reply. As to what software the other is running, no clue. Set ignore-fee-limits=true has fixed the issue, any serious consequences to my other channels from this? The docs give a warning that channels might not be able to close if this is set to true. listchannels shows that his channel feerate is really low, so I guess this is was about the closing fee negotiation. If that's really high, not all too happy about that, but I won't be closing anyway any time soon.
