### ISSUE TITLE
node_announcement propagation has gotten worse!

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#5196]
Two examples: my node, which is running v0.11.0rc3+, and IRATEMONKEY, which is the same:

https://1ml.com/node/024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605
https://amboss.space/node/024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605 
https://lightningnetwork.plus/nodes/024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605 

https://1ml.com/node/032de5c0f28f9d7d10c0c0b5ec92e83f9bf40def2bf40181c0f4330c57e58a8605
https://amboss.space/node/032de5c0f28f9d7d10c0c0b5ec92e83f9bf40def2bf40181c0f4330c57e58a8605 
https://lightningnetwork.plus/nodes/032de5c0f28f9d7d10c0c0b5ec92e83f9bf40def2bf40181c0f4330c57e58a8605

You can see these (despite upgrading) are still not having their node_announcements propagating.

**Comment by rustyrussell** [comment]
This seems to be an issue with LND not liking the draft websocket address extension.

**Comment by carnhofdaki** [comment]
Thanks!

**Comment by jsarenik** [comment]
@fiatjaf Could this be related to issues with https://ln.fiatjaf.com/node/032de5c0f28f9d7d10c0c0b5ec92e83f9bf40def2bf40181c0f4330c57e58a8605 ?

Same for the other node: https://ln.fiatjaf.com/node/024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605
