### ISSUE TITLE
Bob can't pay to alices

### ISSUE THREAD

**Issue by JCbette** [ElementsProject/lightning#5209]
### Issue and Steps to Reproduce
I generate the invoice and can't pay with the bolt11:

> jc@jc-VirtualBox:~$ lightning-cli  invoice 5000msat 1 eat
> {
>    "payment_hash": "cb9d87a519260695d91d41012e531cd8387771766a16ab5d780b3c1390a24e40",
>    "expires_at": 1651148478,
>    "bolt11": "lnbcrt50n1p3xznp7sp54jz47uzcf8d2e787axh74tu5npc94a4z9t078yuvsetyl5tv55uspp5ewwc0fgeycrftkgagyqju5cumqu8wutkdgt2khtcpv7p8y9zfeqqdq9v4shgxqyjw5qcqp29qyysgqfhx7rpr0zhyvy84zkppmwj3f4mkp6pjevj3g9rzd5mvk3e07vyz8pt33mt4ul6a3estdzh7xl44v0uy34tx648zlcwy283pytm9fjggqy3fggn",
>    "payment_secret": "ac855f705849daacf8fee9afeaaf9498705af6a22adfe3938c86564fd16ca539",
>    "warning_capacity": "Insufficient incoming channel capacity to pay invoice"
> }
> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/.lightning/bob --conf=/home/jc/.lightning/bob/config pay lnbcrt50n1p3xznp7sp54jz47uzcf8d2e787axh74tu5npc94a4z9t078yuvsetyl5tv55uspp5ewwc0fgeycrftkgagyqju5cumqu8wutkdgt2khtcpv7p8y9zfeqqdq9v4shgxqyjw5qcqp29qyysgqfhx7rpr0zhyvy84zkppmwj3f4mkp6pjevj3g9rzd5mvk3e07vyz8pt33mt4ul6a3estdzh7xl44v0uy34tx648zlcwy283pytm9fjggqy3fggn
> {
>    "code": 210,
>    "message": "Destination 02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3 is not reachable directly and all routehints were unusable.",
>    "attempts": [
>       {
>          "status": "failed",
>          "failreason": "Destination 02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3 is not reachable directly and all routehints were unusable.",
>          "partid": 0,
>          "amount": "5000msat"
>       }
>    ]
> }

> 

That's the message after the paystatus:

> {
>    "pay": [
>       {
>          "bolt11": "lnbcrt50n1p3xznp7sp54jz47uzcf8d2e787axh74tu5npc94a4z9t078yuvsetyl5tv55uspp5ewwc0fgeycrftkgagyqju5cumqu8wutkdgt2khtcpv7p8y9zfeqqdq9v4shgxqyjw5qcqp29qyysgqfhx7rpr0zhyvy84zkppmwj3f4mkp6pjevj3g9rzd5mvk3e07vyz8pt33mt4ul6a3estdzh7xl44v0uy34tx648zlcwy283pytm9fjggqy3fggn",
>          "amount_msat": "5000msat",
>          "destination": "02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3",
>          "attempts": [
>             {
>                "strategy": "Initial attempt",
>                "start_time": "2022-04-21T12:22:11.644Z",
>                "age_in_seconds": 145,
>                "end_time": "2022-04-21T12:22:11.649Z",
>                "state": "completed",
>                "failure": {
>                   "code": 205,
>                   "message": "Call to getroute: Could not find a route"
>                }
>             }
>          ]
>       }
>    ]
> }

**Comment by JCbette** [comment]
I run in regtest, i don't know whether there are any problem, but there are the nodes' getinfo:

> jc@jc-VirtualBox:~$ lightning-cli getinfo
> {
>    "id": "02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3",
>    "alias": "SLEEPYCHIPMUNK",
>    "color": "02ce6f",
>    "num_peers": 1,
>    "num_pending_channels": 0,
>    "num_active_channels": 1,
>    "num_inactive_channels": 0,
>    "address": [],
>    "binding": [
>       {
>          "type": "ipv4",
>          "address": "10.0.2.15",
>          "port": 22228
>       }
>    ],
>    "version": "v0.11.0rc2-6-gb359a24",
>    "blockheight": 739,
>    "network": "regtest",
>    "msatoshi_fees_collected": 0,
>    "fees_collected_msat": "0msat",
>    "lightning-dir": "/home/jc/.lightning/regtest",
>    "our_features": {
>       "init": "080269a2",
>       "node": "800000080269a2",
>       "channel": "",
>       "invoice": "02000000024100"
>    }
> }

The bob's getinfo

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/.lightning/bob --conf=/home/jc/.lightning/bob/config getinfo
> {
>    "id": "02dde5b49226c49bebd39b6d068d6c9a94481dd203e26ebbe33385eee4e8257f9e",
>    "alias": "VIOLETCALENDAR",
>    "color": "02dde5",
>    "num_peers": 1,
>    "num_pending_channels": 0,
>    "num_active_channels": 1,
>    "num_inactive_channels": 0,
>    "address": [],
>    "binding": [
>       {
>          "type": "ipv4",
>          "address": "127.0.0.1",
>          "port": 22226
>       }
>    ],
>    "version": "v0.11.0rc2-6-gb359a24",
>    "blockheight": 739,
>    "network": "regtest",
>    "msatoshi_fees_collected": 0,
>    "fees_collected_msat": "0msat",
>    "lightning-dir": "/home/jc/.lightning/bob/regtest",
>    "our_features": {
>       "init": "080269a2",
>       "node": "800000080269a2",
>       "channel": "",
>       "invoice": "02000000024100"
>    }
> }

**Comment by JCbette** [comment]
The channel:

> jc@jc-VirtualBox:~$ lightning-cli listchannels
> {
>    "channels": [
>       {
>          "source": "02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3",
>          "destination": "02dde5b49226c49bebd39b6d068d6c9a94481dd203e26ebbe33385eee4e8257f9e",
>          "short_channel_id": "706x1x0",
>          "public": true,
>          "satoshis": 16777215,
>          "amount_msat": "16777215000msat",
>          "message_flags": 1,
>          "channel_flags": 0,
>          "active": true,
>          "last_update": 1650527099,
>          "base_fee_millisatoshi": 1,
>          "fee_per_millionth": 10,
>          "delay": 6,
>          "htlc_minimum_msat": "0msat",
>          "htlc_maximum_msat": "16609443000msat",
>          "features": ""
>       },
>       {
>          "source": "02dde5b49226c49bebd39b6d068d6c9a94481dd203e26ebbe33385eee4e8257f9e",
>          "destination": "02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3",
>          "short_channel_id": "706x1x0",
>          "public": true,
>          "satoshis": 16777215,
>          "amount_msat": "16777215000msat",
>          "message_flags": 1,
>          "channel_flags": 1,
>          "active": true,
>          "last_update": 1650535650,
>          "base_fee_millisatoshi": 1,
>          "fee_per_millionth": 10,
>          "delay": 6,
>          "htlc_minimum_msat": "0msat",
>          "htlc_maximum_msat": "16609443000msat",
>          "features": ""
>       }
>    ]
> }
>

**Comment by JCbette** [comment]
`listpeers`

> jc@jc-VirtualBox:~$ lightning-cli listpeers
> {
>    "peers": [
>       {
>          "id": "02dde5b49226c49bebd39b6d068d6c9a94481dd203e26ebbe33385eee4e8257f9e",
>          "connected": true,
>          "netaddr": [
>             "10.0.2.15:50472"
>          ],
>          "features": "080269a2",
>          "channels": [
>             {
>                "state": "CHANNELD_NORMAL",
>                "scratch_txid": "7288b8e81e12abf9d48cbc3a6fa13ec08313512212f2ed34ea755d160bd75a99",
>                "last_tx_fee": "183000msat",
>                "last_tx_fee_msat": "183000msat",
>                "feerate": {
>                   "perkw": 253,
>                   "perkb": 1012
>                },
>                "owner": "channeld",
>                "short_channel_id": "706x1x0",
>                "direction": 0,
>                "channel_id": "4cd3923f6a37d20391906c1cf3ad3157ad8c1dd1522710b8e41f7d0e28e252cd",
>                "funding_txid": "cd52e2280e7d1fe4b8102752d11d8cad5731adf31c6c909103d2376a3f92d34c",
>                "funding_outnum": 0,
>                "close_to_addr": "bcrt1qecemmnrzvdarheya0lxyp72czgefdj8rzdqgnf",
>                "close_to": "0014ce33bdcc62637a3be49d7fcc40f958123296c8e3",
>                "private": false,
>                "opener": "local",
>                "closer": null,
>                "features": [
>                   "option_static_remotekey"
>                ],
>                "funding_allocation_msat": {
>                   "02dde5b49226c49bebd39b6d068d6c9a94481dd203e26ebbe33385eee4e8257f9e": 0,
>                   "02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3": 16777215000
>                },
>                "funding_msat": {
>                   "02dde5b49226c49bebd39b6d068d6c9a94481dd203e26ebbe33385eee4e8257f9e": "0msat",
>                   "02ce6f6965df0a95631f9a5d0692823a4ccc61cb18dad297f346c025c17fd0dcc3": "16777215000msat"
>                },
>                "funding": {
>                   "local_msat": "16777215000msat",
>                   "remote_msat": "0msat",
>                   "pushed_msat": "0msat"
>                },
>                "msatoshi_to_us": 16777215000,
>                "to_us_msat": "16777215000msat",
>                "msatoshi_to_us_min": 16777215000,
>                "min_to_us_msat": "16777215000msat",
>                "msatoshi_to_us_max": 16777215000,
>                "max_to_us_msat": "16777215000msat",
>                "msatoshi_total": 16777215000,
>                "total_msat": "16777215000msat",
>                "fee_base_msat": "1msat",
>                "fee_proportional_millionths": 10,
>                "dust_limit_satoshis": 546,
>                "dust_limit_msat": "546000msat",
>                "max_htlc_value_in_flight_msat": 18446744073709551615,
>                "max_total_htlc_in_msat": "18446744073709551615msat",
>                "their_channel_reserve_satoshis": 167772,
>                "their_reserve_msat": "167772000msat",
>                "our_channel_reserve_satoshis": 167772,
>                "our_reserve_msat": "167772000msat",
>                "spendable_msatoshi": 4294967295,
>                "spendable_msat": "4294967295msat",
>                "receivable_msatoshi": 0,
>                "receivable_msat": "0msat",
>                "htlc_minimum_msat": 0,
>                "minimum_htlc_in_msat": "0msat",
>                "minimum_htlc_out_msat": "0msat",
>                "maximum_htlc_out_msat": "16609443000msat",
>                "their_to_self_delay": 6,
>                "our_to_self_delay": 6,
>                "max_accepted_htlcs": 483,
>                "state_changes": [
>                   {
>                      "timestamp": "2022-04-21T07:49:54.966Z",
>                      "old_state": "CHANNELD_AWAITING_LOCKIN",
>                      "new_state": "CHANNELD_NORMAL",
>                      "cause": "user",
>                      "message": "Lockin complete"
>                   }
>                ],
>                "status": [
>                   "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
>                ],
>                "in_payments_offered": 0,
>                "in_msatoshi_offered": 0,
>                "in_offered_msat": "0msat",
>                "in_payments_fulfilled": 0,
>                "in_msatoshi_fulfilled": 0,
>                "in_fulfilled_msat": "0msat",
>                "out_payments_offered": 0,
>                "out_msatoshi_offered": 0,
>                "out_offered_msat": "0msat",
>                "out_payments_fulfilled": 0,
>                "out_msatoshi_fulfilled": 0,
>                "out_fulfilled_msat": "0msat",
>                "htlcs": []
>             }
>          ]
>       }
>    ]
> }
>

**Comment by rustyrussell** [comment]
Looks like the channel balance is all on one side. See. "spendable_msat" in listpeers
