### ISSUE TITLE
Question about `listfunds` output

### ISSUE THREAD

**Issue by ClayShoaf** [ElementsProject/lightning#5213]
The naming of sat/msat amount is a little mismatched. Maybe there's a reason for it that I'm not aware of. I'm in regtest and when I `l1-cli listfunds`, in the channel section I see:

```
{
  "peer_id": "0215f8e75541e1899ee9f6241379c6867064bdbe8e5f591f48d0986d3f602002ef",
  "connected": true,
  "state": "CHANNELD_NORMAL",
  "short_channel_id": "1618x2x0",
  "channel_sat": 1111111,
  "our_amount_msat": "1111111000msat",
  "channel_total_sat": 1111111,
  "amount_msat": "1111111000msat",
  "funding_txid": "23b82cc9212d38f6fc52a02fce9b2515407dc3d650d12f4ed03c58fa4e406df3",
  "funding_output": 0
}
```

Is there a reason that sat is listed as "channel_sat"/"channel_total_sat" while msat is listed as "our_amount_msat"/"amount_msat"? It threw me off when I was first trying to decipher everything. I was going to put in a PR, but then I thought that other things might be built with this convention and it might break a lot of stuff. Is there a reason for it to be like this?

**Comment by cdecker** [comment]
The unit-less fields are part of the deprecated API, and can be disabled via `--allow-deprecated-apis=false`, and will eventually be removed in a future version. They're there for backwards compatibility only at the moment, and to allow tooling built on CLN to update without risking accidentally breaking them.

**Comment by ClayShoaf** [comment]
Ok, thank you.
