### ISSUE TITLE
Can i have two peers in a machine?

### ISSUE THREAD

**Issue by JCbette** [ElementsProject/lightning#5214]
### Issue and Steps to Reprodu

Work in regtest, Ubuntus 20.04.4
I have a lightning node with the config `addr=10.0.2.15:22228` and this my ifconfig:

> enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
>         inet6 fe80::26ae:ca91:ef87:a685  prefixlen 64  scopeid 0x20<link>
>         ether 08:00:27:b1:20:50  txqueuelen 1000  (Ethernet)
>         RX packets 522  bytes 214251 (214.2 KB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 571  bytes 70436 (70.4 KB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 16339  bytes 1708911 (1.7 MB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 16339  bytes 1708911 (1.7 MB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Then i creat a new -lightning-dir, and set the config `addr=10.0.2.15:22222` but have problem with:

> jc@jc-VirtualBox:~$ lightningd --lightning-dir=/home/jc/.lightning/cindy --conf=/home/jc/.lightning/cindy/cindy.config --log-level=debug
> 2022-04-22T02:14:01.356Z DEBUG   plugin-manager: started(3699) /usr/local/bin/../libexec/c-lightning/plugins/autoclean
> 2022-04-22T02:14:01.369Z DEBUG   plugin-manager: started(3700) /usr/local/bin/../libexec/c-lightning/plugins/bcli
> 2022-04-22T02:14:01.377Z DEBUG   plugin-manager: started(3701) /usr/local/bin/../libexec/c-lightning/plugins/fetchinvoice
> 2022-04-22T02:14:01.383Z DEBUG   plugin-manager: started(3702) /usr/local/bin/../libexec/c-lightning/plugins/funder
> 2022-04-22T02:14:01.412Z DEBUG   plugin-manager: started(3703) /usr/local/bin/../libexec/c-lightning/plugins/topology
> 2022-04-22T02:14:01.425Z DEBUG   plugin-manager: started(3704) /usr/local/bin/../libexec/c-lightning/plugins/keysend
> 2022-04-22T02:14:01.441Z DEBUG   plugin-manager: started(3705) /usr/local/bin/../libexec/c-lightning/plugins/offers
> 2022-04-22T02:14:01.461Z DEBUG   plugin-manager: started(3706) /usr/local/bin/../libexec/c-lightning/plugins/pay
> 2022-04-22T02:14:01.487Z DEBUG   plugin-manager: started(3707) /usr/local/bin/../libexec/c-lightning/plugins/txprepare
> 2022-04-22T02:14:01.511Z DEBUG   plugin-manager: started(3708) /usr/local/bin/../libexec/c-lightning/plugins/spenderp
> 2022-04-22T02:14:01.611Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_channeld
> 2022-04-22T02:14:01.612Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_closingd
> 2022-04-22T02:14:01.614Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_connectd
> 2022-04-22T02:14:01.616Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_gossipd
> 2022-04-22T02:14:01.618Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_hsmd
> 2022-04-22T02:14:01.619Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_onchaind
> 2022-04-22T02:14:01.621Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_openingd
> 2022-04-22T02:14:01.624Z DEBUG   hsmd: pid 3716, msgfd 35
> 2022-04-22T02:14:02.050Z DEBUG   connectd: pid 3717, msgfd 39
> 2022-04-22T02:14:02.050Z DEBUG   hsmd: new_client: 0
> 2022-04-22T02:14:02.068Z DEBUG   connectd: Failed to create 2 socket: Address already in use
> 2022-04-22T02:14:02.068Z DEBUG   connectd: REPLY WIRE_CONNECTD_INIT_REPLY with 0 fds
> 2022-04-22T02:14:02.068Z DEBUG   connectd: connectd_init_done
> 2022-04-22T02:14:02.068Z **BROKEN** connectd: Failed to bind socket for 10.0.2.15:22222: Address already in use

Then i ifconfig the ip with `sudo ifconfig enp0s3:2 10.0.3.14 netmask 255.255.255.0 up` :

> enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
>         inet6 fe80::26ae:ca91:ef87:a685  prefixlen 64  scopeid 0x20<link>
>         ether 08:00:27:b1:20:50  txqueuelen 1000  (Ethernet)
>         RX packets 530  bytes 215190 (215.1 KB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 587  bytes 72090 (72.0 KB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> enp0s3:2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.0.3.14  netmask 255.255.255.0  broadcast 10.0.2.255
>         ether 08:00:27:b1:20:50  txqueuelen 1000  (Ethernet)
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 17135  bytes 1781138 (1.7 MB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 17135  bytes 1781138 (1.7 MB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

And set the lightning config with `addr=10.0.3.14:22222` but still have the problem:
jc@jc-VirtualBox:~$ lightningd --lightning-dir=/home/jc/.lightning/cindy --conf=/home/jc/.lightning/cindy/cindy.config --log-

> level=debug
> 2022-04-22T02:21:20.703Z DEBUG   plugin-manager: started(3959) /usr/local/bin/../libexec/c-lightning/plugins/autoclean
> 2022-04-22T02:21:20.708Z DEBUG   plugin-manager: started(3960) /usr/local/bin/../libexec/c-lightning/plugins/bcli
> 2022-04-22T02:21:20.729Z DEBUG   plugin-manager: started(3961) /usr/local/bin/../libexec/c-lightning/plugins/fetchinvoice
> 2022-04-22T02:21:20.747Z DEBUG   plugin-manager: started(3962) /usr/local/bin/../libexec/c-lightning/plugins/funder
> 2022-04-22T02:21:20.769Z DEBUG   plugin-manager: started(3963) /usr/local/bin/../libexec/c-lightning/plugins/topology
> 2022-04-22T02:21:20.781Z DEBUG   plugin-manager: started(3964) /usr/local/bin/../libexec/c-lightning/plugins/keysend
> 2022-04-22T02:21:20.816Z DEBUG   plugin-manager: started(3965) /usr/local/bin/../libexec/c-lightning/plugins/offers
> 2022-04-22T02:21:20.836Z DEBUG   plugin-manager: started(3966) /usr/local/bin/../libexec/c-lightning/plugins/pay
> 2022-04-22T02:21:20.868Z DEBUG   plugin-manager: started(3967) /usr/local/bin/../libexec/c-lightning/plugins/txprepare
> 2022-04-22T02:21:20.892Z DEBUG   plugin-manager: started(3968) /usr/local/bin/../libexec/c-lightning/plugins/spenderp
> 2022-04-22T02:21:20.964Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_channeld
> 2022-04-22T02:21:20.968Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_closingd
> 2022-04-22T02:21:20.970Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_connectd
> 2022-04-22T02:21:20.971Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_gossipd
> 2022-04-22T02:21:20.981Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_hsmd
> 2022-04-22T02:21:20.984Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_onchaind
> 2022-04-22T02:21:20.988Z DEBUG   lightningd: testing /usr/local/libexec/c-lightning/lightning_openingd
> 2022-04-22T02:21:20.990Z DEBUG   hsmd: pid 3976, msgfd 35
> 2022-04-22T02:21:21.132Z DEBUG   connectd: pid 3977, msgfd 39
> 2022-04-22T02:21:21.132Z DEBUG   hsmd: new_client: 0
> 2022-04-22T02:21:21.159Z DEBUG   connectd: Failed to create 2 socket: Address already in use
> 2022-04-22T02:21:21.160Z DEBUG   connectd: REPLY WIRE_CONNECTD_INIT_REPLY with 0 fds
> 2022-04-22T02:21:21.160Z DEBUG   connectd: connectd_init_done
> 2022-04-22T02:21:21.160Z **BROKEN** connectd: Failed to bind socket for 10.0.3.14:22222: Address already in use

That means i can't create two nodes in my own one machine?

**Comment by vincenzopalazzo** [comment]
it is better to have your lightningd conf file!

**Comment by JCbette** [comment]
> it is better to have your lightningd conf file!

Thanks, i change the port and the lightning is running, and i find i can even use one ip to have two nodes with differents ports!
Maybe the question happen because there is another process running in my computer, the solves is just change the port...
Anyway, thank you and i close it.
