### ISSUE TITLE
Can't pay the invoice.

### ISSUE THREAD

**Issue by JCbette** [ElementsProject/lightning#5217]
### Issue
In regtest, with only two nodes and a channel.
After i have a normal channel, the node which connect the channel can pay the invoice from another, but the another can't pay the invoice from the connecter!
### Reproduce
Firstly, configure two nodes with:
Node AA:

> rpcuser=10
> rpcpassword=10
> [regtest]
> port=22220
> rpcport=18333
> addnode=127.0.0.1:22222
> rpcconnect=127.0.0.1

The lightning:

> bitcoin-datadir=/home/jc/work/AA
> bitcoin-rpcconnect=127.0.0.1
> bitcoin-rpcport=18333
> bitcoin-rpcuser=10
> bitcoin-rpcpassword=10
> log-file=/home/jc/work/AA/AA.light/light.log
> addr=127.0.0.1:22222

Node BB:

> rpcuser=10
> rpcpassword=10
> [regtest]
> port=22222
> rpcport=18334
> addnode=127.0.0.1:22220
> rpcconnect=127.0.0.1

The lightning:

> bitcoin-datadir=/home/jc/work/BB
> bitcoin-rpcconnect=127.0.0.1
> bitcoin-rpcport=18334
> bitcoin-rpcuser=10
> bitcoin-rpcpassword=10
> log-file=/home/jc/work/BB/BB.light/light.log
> addr=10.0.2.15:22222

Then send coins to the lightning's newaddr:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config newaddr
> {
>    "bech32": "bcrt1qvdwzakfcfmgruxlvwz2rlw3rfqtncdsyn9v8p0"
> }
> jc@jc-VirtualBox:~$ bitcoin-cli -datadir=/home/jc/work/AA -conf=AA.conf sendtoaddress bcrt1qvdwzakfcfmgruxlvwz2rlw3rfqtncdsyn9v8p0 300
> 6bd7e850bde563fdeb8891fea5b4d7ff6d69c2f2d758d4205f09674732433e60

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config newaddr
> {
>    "bech32": "bcrt1qstp3092j4vy5jyxa25rmg2t2s3cplqd6n86784"
> }
> jc@jc-VirtualBox:~$ bitcoin-cli -datadir=/home/jc/work/BB -conf=BB.conf sendtoaddress bcrt1qstp3092j4vy5jyxa25rmg2t2s3cplqd6n86784 200
> 38212522ab8bf34c3426991ef010c1cefd35757b110d83afdccb17ba485f3355
### getinfo
AA's getinfo:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config getinfo
> {
>    "id": "0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a",
>    "alias": "GREENRAGE",
>    "color": "0349fe",
>    "num_peers": 0,
>    "num_pending_channels": 0,
>    "num_active_channels": 0,
>    "num_inactive_channels": 0,
>    "address": [],
>    "binding": [
>       {
>          "type": "ipv4",
>          "address": "127.0.0.1",
>          "port": 22222
>       }
>    ],
>    "version": "v0.11.0rc2-6-gb359a24",
>    "blockheight": 231,
>    "network": "regtest",
>    "msatoshi_fees_collected": 0,
>    "fees_collected_msat": "0msat",
>    "lightning-dir": "/home/jc/work/AA/AA.light/regtest",
>    "our_features": {
>       "init": "080269a2",
>       "node": "800000080269a2",
>       "channel": "",
>       "invoice": "02000000024100"
>    }
> }

BB's getinfo:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config getinfo
> {
>    "id": "037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0",
>    "alias": "ORANGESOUFFLE",
>    "color": "037f9a",
>    "num_peers": 0,
>    "num_pending_channels": 0,
>    "num_active_channels": 0,
>    "num_inactive_channels": 0,
>    "address": [],
>    "binding": [
>       {
>          "type": "ipv4",
>          "address": "10.0.2.15",
>          "port": 22222
>       }
>    ],
>    "version": "v0.11.0rc2-6-gb359a24",
>    "blockheight": 231,
>    "network": "regtest",
>    "msatoshi_fees_collected": 0,
>    "fees_collected_msat": "0msat",
>    "lightning-dir": "/home/jc/work/BB/BB.light/regtest",
>    "our_features": {
>       "init": "080269a2",
>       "node": "800000080269a2",
>       "channel": "",
>       "invoice": "02000000024100"
>    }
> }
>

**Comment by JCbette** [comment]
Then AA connect to BB :

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config connect 037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0@10.0.2.15:22222
> {
>    "id": "037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0",
>    "features": "080269a2",
>    "direction": "out",
>    "address": {
>       "type": "ipv4",
>       "address": "10.0.2.15",
>       "port": 22222
>    }
> }

AA's listpeers:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config connect 037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0@10.0.2.15:22222
> {
>    "id": "037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0",
>    "features": "080269a2",
>    "direction": "out",
>    "address": {
>       "type": "ipv4",
>       "address": "10.0.2.15",
>       "port": 22222
>    }
> }

Yes, it is strange to see that the BB's listpeers have a wrong port with AA's.......

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config listpeers
> {
>    "peers": [
>       {
>          "id": "0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a",
>          "connected": true,
>          "netaddr": [
>             "10.0.2.15:43256"
>          ],
>          "features": "080269a2",
>          "channels": []
>       }
>    ]
> }

Generate for comfirming the listfunds:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config  listfunds
> {
>    "outputs": [
>       {
>          "txid": "6bd7e850bde563fdeb8891fea5b4d7ff6d69c2f2d758d4205f09674732433e60",
>          "output": 1,
>          "value": 30000000000,
>          "amount_msat": "30000000000000msat",
>          "scriptpubkey": "0014635c2ed9384ed03e1bec70943fba2348173c3604",
>          "address": "bcrt1qvdwzakfcfmgruxlvwz2rlw3rfqtncdsyn9v8p0",
>          "status": "confirmed",
>          "blockheight": 232,
>          "reserved": false
>       }
>    ],
>    "channels": []
> }
> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config listfunds
> {
>    "outputs": [
>       {
>          "txid": "38212522ab8bf34c3426991ef010c1cefd35757b110d83afdccb17ba485f3355",
>          "output": 0,
>          "value": 20000000000,
>          "amount_msat": "20000000000000msat",
>          "scriptpubkey": "001482c3179552ab094910dd5507b4296a84701f81ba",
>          "address": "bcrt1qstp3092j4vy5jyxa25rmg2t2s3cplqd6n86784",
>          "status": "confirmed",
>          "blockheight": 232,
>          "reserved": false
>       }
>    ],
>    "channels": []
> }

Then AA fundchannel:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config fundchannel id=037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0 amount=all feerate=normal utxos='["6bd7e850bde563fdeb8891fea5b4d7ff6d69c2f2d758d4205f09674732433e60:1"]'
> {
>    "tx": "02000000000101603e43324767095f20d458d7f2c2696dffd7b4a5fe9188ebfd63e5bd50e8d76b0100000000fdffffff02ffffff00000000002200202ef4da26e8200b727719ec0389ea111a682effe6e1c0f46ae03778d36aa158c767ab23fb06000000160014f5b12f194f93f43a7399a37d9eedabce4ff06c990247304402206414e5399c1b6594a483af7d92cca10ba4acfae4f7aa03b5cb946e60335da83402201ffdfee252efc82e90f7a0452cc5bf284b097114cc80032b9208870ea1f9325801210260c237c74bd6818ba4a6b819401a78451ade57d600bf1aef3c3ec6c550658ea123010000",
>    "txid": "745de14e181d16f79bc14abb345b73765f9bca5820db85c222988cb3f38b2835",
>    "channel_id": "35288bf3b38c9822c285db2058ca9b5f76735b34bb4ac19bf7161d184ee15d74",
>    "outnum": 0
> }

Generate until the channel change to normal:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config  listfunds
> {
>    "outputs": [
>       {
>          "txid": "745de14e181d16f79bc14abb345b73765f9bca5820db85c222988cb3f38b2835",
>          "output": 1,
>          "value": 29983222631,
>          "amount_msat": "29983222631000msat",
>          "scriptpubkey": "0014f5b12f194f93f43a7399a37d9eedabce4ff06c99",
>          "address": "bcrt1q7kcj7x20j06r5uue5d7eamdtee8lqmyeva6ra4",
>          "status": "confirmed",
>          "blockheight": 292,
>          "reserved": false
>       }
>    ],
>    "channels": [
>       {
>          "peer_id": "037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0",
>          "connected": true,
>          "state": "CHANNELD_NORMAL",
>          "short_channel_id": "292x1x0",
>          "channel_sat": 16777215,
>          "our_amount_msat": "16777215000msat",
>          "channel_total_sat": 16777215,
>          "amount_msat": "16777215000msat",
>          "funding_txid": "745de14e181d16f79bc14abb345b73765f9bca5820db85c222988cb3f38b2835",
>          "funding_output": 0
>       }
>    ]
> }
>

**Comment by JCbette** [comment]
AA can successly pay the invoice from BB:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config invoice 2000msat 1 eat
> {
>    "payment_hash": "48f65047478a55fa347c9a0e0d114885584c9f510e9747fd34f8da3fd46fa4bf",
>    "expires_at": 1651334219,
>    "bolt11": "lnbcrt20n1p3xggwtsp5ez6curqkmdy2x5fqzdlkm0yuer306ugjmdcd32ss5tjsmzl8eljqpp5frm9q3683f2l5drung8q6y2gs4vye863p6t50lf5lrdrl4r05jlsdq9v4shgxqyjw5qcqp29qyysgq2j9gpc2qzued3k0tsflnc7jfrzj76n7ddt8qrjgx2lewaulwl56ny2v9ccue8dlwu3jlxa4l6wq0rp7fdhspmmzfaw06p6jadw03rzqqknyp3k",
>    "payment_secret": "c8b58e0c16db48a35120137f6dbc9cc8e2fd7112db70d8aa10a2e50d8be7cfe4",
>    "warning_deadends": "Insufficient incoming capacity, once dead-end peers were excluded"
> }
> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config pay lnbcrt20n1p3xggwtsp5ez6curqkmdy2x5fqzdlkm0yuer306ugjmdcd32ss5tjsmzl8eljqpp5frm9q3683f2l5drung8q6y2gs4vye863p6t50lf5lrdrl4r05jlsdq9v4shgxqyjw5qcqp29qyysgq2j9gpc2qzued3k0tsflnc7jfrzj76n7ddt8qrjgx2lewaulwl56ny2v9ccue8dlwu3jlxa4l6wq0rp7fdhspmmzfaw06p6jadw03rzqqknyp3k
> {
>    "destination": "037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0",
>    "payment_hash": "48f65047478a55fa347c9a0e0d114885584c9f510e9747fd34f8da3fd46fa4bf",
>    "created_at": 1650729427.700,
>    "parts": 1,
>    "msatoshi": 2000,
>    "amount_msat": "2000msat",
>    "msatoshi_sent": 2000,
>    "amount_sent_msat": "2000msat",
>    "payment_preimage": "4f54563ec394529787bf5ceb811016b3febb978fdcacae0efd9c9dd4bb84b66b",
>    "status": "complete"
> }

But BB can't pay the invoice from AA....

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config invoice 3000msat 2 drink
> {
>    "payment_hash": "0b8ce5aea04db2d2de211ecea160abf7110c0fe7439bc54be17da2650e21d41a",
>    "expires_at": 1651334285,
>    "bolt11": "lnbcrt30n1p3xggsdsp5etc6qp8kdv4ku73yr883ws9ktdfmsc7u8t2ecjhulqtwrmuujhvqpp5pwxwtt4qfked9h3prm82zc9t7ugscrl8gwdu2jlp0k3x2r3p6sdqdqgv3exjmntxqyjw5qcqp29qyysgqkh4ch8ws22phx5u9p7s9cv95erz2njz2hweqkn74d8k8xeyv3jmsh2pfea9vl2gw3e4gphefpy04zpr060qvlrc5x77yyyt8tlw43ygqda4k4s",
>    "payment_secret": "caf1a004f66b2b6e7a2419cf1740b65b53b863dc3ad59c4afcf816e1ef9c95d8",
>    "warning_capacity": "Insufficient incoming channel capacity to pay invoice"
> }
> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config pay lnbcrt30n1p3xggsdsp5etc6qp8kdv4ku73yr883ws9ktdfmsc7u8t2ecjhulqtwrmuujhvqpp5pwxwtt4qfked9h3prm82zc9t7ugscrl8gwdu2jlp0k3x2r3p6sdqdqgv3exjmntxqyjw5qcqp29qyysgqkh4ch8ws22phx5u9p7s9cv95erz2njz2hweqkn74d8k8xeyv3jmsh2pfea9vl2gw3e4gphefpy04zpr060qvlrc5x77yyyt8tlw43ygqda4k4s
> {
>    "code": 210,
>    "message": "Destination 0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a is not reachable directly and all routehints were unusable.",
>    "attempts": [
>       {
>          "status": "failed",
>          "failreason": "Destination 0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a is not reachable directly and all routehints were unusable.",
>          "partid": 0,
>          "amount": "3000msat"
>       }
>    ]
> }

But the getroute is effective..

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config getroute 0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a 1 1
> {
>    "route": [
>       {
>          "id": "0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a",
>          "channel": "292x1x0",
>          "direction": 1,
>          "msatoshi": 1,
>          "amount_msat": "1msat",
>          "delay": 9,
>          "style": "tlv"
>       }
>    ]
> }
> 

And that's the paystatus:

> {
>    "pay": [
>       {
>          "bolt11": "lnbcrt30n1p3xggsdsp5etc6qp8kdv4ku73yr883ws9ktdfmsc7u8t2ecjhulqtwrmuujhvqpp5pwxwtt4qfked9h3prm82zc9t7ugscrl8gwdu2jlp0k3x2r3p6sdqdqgv3exjmntxqyjw5qcqp29qyysgqkh4ch8ws22phx5u9p7s9cv95erz2njz2hweqkn74d8k8xeyv3jmsh2pfea9vl2gw3e4gphefpy04zpr060qvlrc5x77yyyt8tlw43ygqda4k4s",
>          "amount_msat": "3000msat",
>          "destination": "0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a",
>          "attempts": [
>             {
>                "strategy": "Initial attempt",
>                "start_time": "2022-04-23T15:58:15.074Z",
>                "age_in_seconds": 133,
>                "end_time": "2022-04-23T15:58:15.079Z",
>                "state": "completed",
>                "failure": {
>                   "code": 205,
>                   "message": "Call to getroute: Could not find a route"
>                }
>             }
>          ]
>       }
>    ]
> }

**Comment by rustyrussell** [comment]
If Alice funds a channel to Bob, Bob has no funds in the channel and so cannot use it to pay Alice.

Common misunderstanding.

**Comment by JCbette** [comment]
> If Alice funds a channel to Bob, Bob has no funds in the channel and so cannot use it to pay Alice.

I think you are right, how can Bob sent funds to the channel so that he can offer to Alice?
Or is there any other command to funds a two-way channal?

**Comment by rustyrussell** [comment]
With core lightning you can use `experimental-dual-funding` to allow both sides to put funds in if they want (and both have support enabled).

More normal, on regtest, is simply to make a payment to balance the channel

**Comment by JCbette** [comment]
> With core lightning you can use `experimental-dual-funding` to allow both sides to put funds in if they want (and both have support enabled).
Thanks， i'll have a try now

**Comment by JCbette** [comment]
> With core lightning you can use `experimental-dual-funding` to allow both sides to put funds in if they want (and both have support enabled).

Why can't i find the help of the command?

jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config help experimental-dual-funding
No manual entry for lightning-experimental-dual-funding
man: ./../doc/lightning-experimental-dual-funding.7: No such file or directory
{
   "code": -32601,
   "message": "Unknown command 'experimental-dual-funding'"
}



> More normal, on regtest, is simply to make a payment to balance the channel

And does it means that the Aices pay the invoice first to Bob and then the Bob can  use the channel? It there any update command for the channel? Because i use Alice to pay so many times, but Bob still can't work...

**Comment by JCbette** [comment]
AA pay to BB

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config  pay lnbcrt10u1p3xf8y7sp5rmjqgf6usr62kmck0fymfxtnagkq3cxg0y653a3mwulwk9qkygcspp5c65vhqwytacwx4pzytl6sgscy0rv2ec6t950d8zzcp7hvg82rmtsdq9v4shgxqyjw5qcqp29qyysgqv2eeuyvn3xspqeemdeyg5z8p98cauxrrnz5wjl93drpla4nln5fre3x98gludut88ry336yqn47ttau8argx4p2n0ewh9d3rz6h49vspvs76m8
> {
>    "destination": "037f9a4362711ad6b5014a338d50e5f42f60d4731659312a6b67f4e06a6517f9b0",
>    "payment_hash": "c6a8cb81c45f70e3542222ffa8221823c6c5671a5968f69c42c07d7620ea1ed7",
>    "created_at": 1650760871.806,
>    "parts": 1,
>    "msatoshi": 1000000,
>    "amount_msat": "1000000msat",
>    "msatoshi_sent": 1000000,
>    "amount_sent_msat": "1000000msat",
>    "payment_preimage": "d6f03322dfea4f664a4ebab01ea077ebbf3a647a6ff1fb7fe9e6e0194b6358be",
>    "status": "complete"
> }

The channels show BB have some funds with `our_amount_msat`

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config listfunds
> {
>    "outputs": [
>       {
>          "txid": "38212522ab8bf34c3426991ef010c1cefd35757b110d83afdccb17ba485f3355",
>          "output": 0,
>          "value": 20000000000,
>          "amount_msat": "20000000000000msat",
>          "scriptpubkey": "001482c3179552ab094910dd5507b4296a84701f81ba",
>          "address": "bcrt1qstp3092j4vy5jyxa25rmg2t2s3cplqd6n86784",
>          "status": "confirmed",
>          "blockheight": 232,
>          "reserved": false
>       },
>       {
>          "txid": "b32a3dac034789c633a0edff4def888e63b574b1ed3c5f8afd33f8cf506a51e0",
>          "output": 1,
>          "value": 100000000000,
>          "amount_msat": "100000000000000msat",
>          "scriptpubkey": "00142a273287826253ddab9c91a475b747db0a46c1b7",
>          "address": "bcrt1q9gnn9puzvffam2uujxj8td68mv9ydsdh69mm4e",
>          "status": "confirmed",
>          "blockheight": 371,
>          "reserved": false
>       }
>    ],
>    "channels": [
>       {
>          "peer_id": "0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a",
>          "connected": true,
>          "state": "CHANNELD_NORMAL",
>          "short_channel_id": "292x1x0",
>          "channel_sat": 1002,
>          "our_amount_msat": "1002000msat",
>          "channel_total_sat": 16777215,
>          "amount_msat": "16777215000msat",
>          "funding_txid": "745de14e181d16f79bc14abb345b73765f9bca5820db85c222988cb3f38b2835",
>          "funding_output": 0
>       }
>    ]
> }

But BB still can't pay to AA:

> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/AA/AA.light --conf=/home/jc/work/AA/AA.light/AA.config  invoice 100msat 1 drink
> {
>    "payment_hash": "9b4cb83476d6e57cbb4f9c12b6109fb99973e9bbc08a08335031a5cd98611e17",
>    "expires_at": 1651365722,
>    "bolt11": "lnbcrt1n1p3xf8x6sp5swsa9ua297wwtwdvnpe098wsap76l2fpmyezmh0ztqjfl4jhtsaspp5ndxtsdrk6mjhew60nsftvyylhxvh86dmcz9qsv6sxxjumxrprctsdqgv3exjmntxqyjw5qcqp29qyysgqj6n8m276ft8qnu6h9aj5wshqslut2k2l95jsytsksmu3s8zdwplj7jr344qa04rdh0yjcp6ke4d7te7ycr9mue7ua53smdlghzmzuaqpu0jdx0",
>    "payment_secret": "83a1d2f3aa2f9ce5b9ac9872f29dd0e87dafa921d9322ddde258249fd6575c3b",
>    "warning_capacity": "Insufficient incoming channel capacity to pay invoice"
> }
> jc@jc-VirtualBox:~$ lightning-cli --lightning-dir=/home/jc/work/BB/BB.light --conf=/home/jc/work/BB/BB.light/BB.config pay lnbcrt1n1p3xf8x6sp5swsa9ua297wwtwdvnpe098wsap76l2fpmyezmh0ztqjfl4jhtsaspp5ndxtsdrk6mjhew60nsftvyylhxvh86dmcz9qsv6sxxjumxrprctsdqgv3exjmntxqyjw5qcqp29qyysgqj6n8m276ft8qnu6h9aj5wshqslut2k2l95jsytsksmu3s8zdwplj7jr344qa04rdh0yjcp6ke4d7te7ycr9mue7ua53smdlghzmzuaqpu0jdx0
> {
>    "code": 210,
>    "message": "Destination 0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a is not reachable directly and all routehints were unusable.",
>    "attempts": [
>       {
>          "status": "failed",
>          "failreason": "Destination 0349fedbf4fb6f66edbef742aa105e70c1204af1f061953f79366dad28bfe6fa2a is not reachable directly and all routehints were unusable.",
>          "partid": 0,
>          "amount": "100msat"
>       }
>    ]
> }
>

**Comment by JCbette** [comment]
Hi @rustyrussell 
Please give me a help, that's my homework and the time is pressing  (╥﹏╥)o

**Comment by vincenzopalazzo** [comment]
I think discord is the better place to talk about this issue!

**Comment by JCbette** [comment]
> I think discord is the better place to talk about this issue!

Emm yes, but i have ever asked questions there but no reply , so i come here hhh...

**Comment by vincenzopalazzo** [comment]
I'm on discord and I don't see your question, maybe you asked on irc? where I answered but you disconnected before

**Comment by JCbette** [comment]
I play [here](https://discord.gg/cKcP6UmD ) where you invite me before haha...
Maybe i disconnected first? My country should use the agent to surfing here... 
But that's ok, i have solved the problem by reading the` help file`, thank you sooo much!
