### ISSUE TITLE
Peers not being forgotten after disconnect

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/lightning#522]
I had two peers with multiple entries each in my `getpeers` response. Was told by @rustyrussell to report this.

**Comment by ZmnSCPxj** [comment]
I believe #975 should fix it as a side effect of https://github.com/ElementsProject/lightning/pull/975/commits/2d959d2270972e12faaad2a08aba4813cd541496 .

@rustyrussell confirm please?
