### ISSUE TITLE
sudo make install fails due to git config

### ISSUE THREAD

**Issue by carboncls** [ElementsProject/lightning#5221]
### Issue and Steps to Reproduce
Tried to upgrade to v0.11.0 by `git pull` and than `checkout tags/v0.11.0`. I followed the instructions on the installation guide, however, upon `sudo make install`, I get the following error:
Makefile:7: *** "ERROR: git is required for generating version information".  Stop.

`sudo git describe` returns:
fatal: unsafe repository ('/home/carlo/lightning' is owned by someone else)
To add an exception for this directory, call:

    git config --global --add safe.directory /home/carlo/lightning

After `sudo git config --global --add safe.directory /home/carlo/lightning && make install`, output is:
mkdir -p /usr/local/bin
mkdir -p /usr/local/libexec/c-lightning
mkdir -p /usr/local/libexec/c-lightning/plugins
mkdir -p /usr/local/share/man/man1
mkdir -p /usr/local/share/man/man5
mkdir -p /usr/local/share/man/man7
mkdir -p /usr/local/share/man/man8
mkdir -p /usr/local/share/doc/c-lightning
fatal: unsafe repository ('/home/carlo/lightning/external/libwally-core' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/carlo/lightning/external/libwally-core
Reinitializing submodules src/secp256k1 ...
fatal: unsafe repository ('/home/carlo/lightning/external/libwally-core' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/carlo/lightning/external/libwally-core
fatal: unsafe repository ('/home/carlo/lightning/external/libwally-core' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/carlo/lightning/external/libwally-core
make: *** [external/Makefile:53: submodcheck] Error 128

`sudo git config --system --add safe.directory `pwd`'/*'` is the same

### `getinfo` output
   "version": "v0.11.0rc1",
   "blockheight": 733480,
   "network": "bitcoin",
   "msatoshi_fees_collected": 97079903,
   "fees_collected_msat": "97079903msat",
   "lightning-dir": "/home/carlo/.lightning/bitcoin",
   "our_features": {
      "init": "80282a69a2",
      "node": "800080282a69a2",
      "channel": "",
      "invoice": "02000020024100"

**Comment by rustyrussell** [comment]
Yeah, git broke everything recently :(  You can workaround using `VERSION=v0.11.0` on the `make` line.

**Comment by TonyGiorgio** [comment]
This seems to still be an issue. 

```
$ sudo make install
Makefile:7: *** "ERROR: git is required for generating version information".  Stop.
```

```
  974  git clone https://github.com/ElementsProject/lightning.git
  975  cd lightning/
  976  git checkout tags/v0.11.2
  977  poetry install
  978  ./configure
  980  poetry run make
  981  sudo make install
```

```
$ git --version
git version 2.25.1
```
