### ISSUE TITLE
How to get last processed block from CLN during bitcoind IBD?

### ISSUE THREAD

**Issue by kristapsk** [ElementsProject/lightning#5231]
### Issue and Steps to Reproduce

I'm setting up a new Bitcoin + LN node on a VPS with limited disk space (~40G total), so I need to enable pruning in `bitcoind` from the start. As CLN needs to also process all blocks before pruning happens, plan is to configure both Bitcoin Core and CLN and then start them directly one after another. The thing is that it that Core is processing new blocks faster than CLN (at least on that VPS with Core v23.0 and CLN v0.11.0.1) and at some point it has pruned out too much (even with `prune=20000`). My current workaround is to `bitcoin-cli setnetworkactive false` from time to time during IBD, when both values start to differ too much, and wait until it catches up. 

Would like to automate this. Problem is that `blockheight` value in `lightning-cli getinfo` during IBD seems to be staying at zero. Is that a bug or feature?

Alternative is to set loglevel to debug and then grep for `lightningd: Adding block ` messages, but that does not look like the best way.

### `getinfo` output
```
{
   "id": "***",
   "alias": "***",
   "color": "***",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "n.n.n.n",
         "port": 9736
      }
   ],
   "binding": [],
   "version": "0.11.0.1",
   "blockheight": 0,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/cln/.lightning/bitcoin",
   "warning_bitcoind_sync": "Bitcoind is not up-to-date with network.",
   "our_features": {
      "init": "080269a2",
      "node": "800000080269a2",
      "channel": "",
      "invoice": "02000000024100"
   }
}
```

**Comment by ZmnSCPxj** [comment]
I think it is a feature.  Can you try `lightning-cli waitblockheight 0` and see if it gives you a more usable result?

**Comment by vincenzopalazzo** [comment]
The real alternative is to use a plugin that makes this job like https://github.com/clightning4j/btcli4j

You can make an architecture only with the claim of "bitcoin core seems faster than core lightning".

**Comment by kristapsk** [comment]
> Can you try `lightning-cli waitblockheight 0` and see if it gives you a more usable result?

That seems to do the trick!
```
$ lightning-cli waitblockheight 0
{
   "blockheight": 1608
}
$ lightning-cli waitblockheight 0
{
   "blockheight": 1826
}
```

> You can make an architecture only with the claim of "bitcoin core seems faster than core lightning".

M? Not sure I understand what you mean by this...

**Comment by vincenzopalazzo** [comment]
>M? Not sure I understand what you mean by this...

Sorry typo, I missed a `not`. Message updated!

My reasoning is there are other corner cases to run bitcoin core in pruning mode with lightning, that can make your architecture tricky to maintains

**Comment by kristapsk** [comment]
> My reasoning is there are other corner cases to run bitcoin core in pruning mode with lightning, that can make your architecture tricky to maintains

"Architecture" would be too strong word for this, just a hack to work around specific problem with Core processing new blocks too fast compared to CLN on a probably specific machine. And after IBD it also will help with other issues where problem is CLN lacking behind Core with block processing (of course, things like monitoring are needed on top of that too).

Anyway, this is with what I came up with at the end - https://github.com/kristapsk/cln-scripts/blob/1974bd203cea7043feac6aae9f7cd943b760f711/cln-prune-protector.sh.
