### ISSUE TITLE
bad reestablish revocation_number: x vs y

### ISSUE THREAD

**Issue by heyambob** [ElementsProject/lightning#5235]
### Issue and Steps to Reproduce

I might have got it around 5 times already less than a year of running. I don't think nobody tried to cheat nobody in these incidents, but what could have caused this to happen? I think mine always happen with my CLN peers.

I have a wild theory:

I used to use the default CLTV(34). I got tired of stuck htlc so I changed it to 40 to match LND long time ago. Once in a while I would get this forced close. Asked around, couldn't fine explanation. "Ok"  it rarely happens, I thought.

A few days ago I read Alex B recommends 144 CLTV to minimize stuck htlc and tried it. Within 24 hrs, I got several strange forced closes ranging from stuck htlc, the "internal error" from LND nodes, and this "bad reestablish revocation_number: 5496 vs 5559" from one of my CLN peers. 

A few days has passed, dust seemed to settle until I received this from another CLN peer of mine "channeld: sent ERROR bad reestablish revocation_number: 12181 vs 16321" . A lot different in numbers this time.

It's not clear who has 12181 and who has 16321. The log, at least, should provide more info.

I talked with another CLN user, said he just got it with an LND peer.

Hm.. is it possible that most CLN users having the CLTV default to 34 may run into this issue with LND users using 40 ? When I cranked it up to 144, it might have provoked it to happen more often.

### `getinfo` output

v0.11.0.1-2-gf40b6d

**Comment by heyambob** [comment]
update: so yesterday I changed CLTV back to 40, it was fine for almost 24hr until I got forced closes with other 3 of my CLN peers with this revocation_number issue. I'm reverting back to the default(34) before I run out of CLN peers.

If it's not CLTV, another thing that I did recently was upgrading to v0.11.0.1-2-gf40b6d from rc5

**Comment by svewa** [comment]
My node also force closes every few days with this error, indicating one peer is just a few revocation_numbers behind. I talked to some of them, they ran LND and did not have any backup/restore situation.

**Comment by niftynei** [comment]
> It's not clear who has 12181 and who has 16321. The log, at least, should provide more info.

Agreed, this message could be more clear. Here's an interpretation from the [code](https://github.com/ElementsProject/lightning/blob/master/channeld/channeld.c#L2975).

```
bad reestablish revocation_number: 5496 vs 5559
```

In this message, the `5496` is the revocation number the peer provided. The `5559` is the number your node has on file for this channel's current state.  Since your current state number is higher than where the peer thinks you are, your node is closing the channel.

**Comment by devastgh** [comment]
My 0.11 cln did force close recently to an lnd node as well, with very similar log entries. The lnd node did restart at the time, but there was no recovery/issue on their side apparently. My revocation numbers match, however there is a "?" there. Log from my side:

```
UNUSUAL xxxxxxxxxxxxxxxxxxxxxxxxxx-channeld-chan#1973: Retransmitted commitment_signed 614 but they already send revocation 614?
UNUSUAL xxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1973: Peer permanent failure in CHANNELD_NORMAL: channeld: received ERROR error channel xxxxxxxxxxxxxxxxxxxxxxxx: unable to resume channel, recovery required
INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1973: State changed from CHANNELD_NORMAL to AWAITING_UNILATERAL
```
