### ISSUE TITLE
checkmessage support broken in 0.11 - fails with verify: false when the pubkey is omitted

### ISSUE THREAD

**Issue by gdassori** [ElementsProject/lightning#5247]
Hello.
I'm experiencing a strange behavior of the `checkmessage` API.

Once checking with other people seems like I'm the only one in the following situation:

### Issue and Steps to Reproduce

`checkmessage` fails with `{"verified": false}` when the pubkey is omitted, even if the signature is correct.

```
guido@vmi82:~$ lightning-cli checkmessage test_message dhx66hpsyydtuowf9bd3yaijq86xhnwbz4h7kqqkfz1atm5iueru1ee6gfitbnbgntbn8smhb5oheqx8ayz8tih46hwumi9sdjx49kib
{
   "pubkey": "02a8f16a02fee11b151d08a204b0111da8d52db044a085e13d9b50896077865df6",
   "verified": false
}
```

And properly validates if the key is passed:
```
guido@vmi82:~$ lightning-cli checkmessage test_message dhx66hpsyydtuowf9bd3yaijq86xhnwbz4h7kqqkfz1atm5iueru1ee6gfitbnbgntbn8smhb5oheqx8ayz8tih46hwumi9sdjx49kib 02a8f16a02fee11b151d08a204b0111da8d52db044a085e13d9b50896077865df6
{
   "pubkey": "02a8f16a02fee11b151d08a204b0111da8d52db044a085e13d9b50896077865df6",
   "verified": true
}
```

@ShahanaFarooqui may want to know that it obv affects the RTL sign\verify process as well when the backend is Core Lightning.

### Version note:

```
 "version": "v0.11.0.1-10-g2ab2061",
```

**Comment by gdassori** [comment]
Hello Vincenzo, thanks for your time.
Actually, the same message verification has different outcomes. To ensure the verification, I have to add the public key after the very same command.

**Comment by vincenzopalazzo** [comment]
>So, I believed it should work even without passing the public key if the message is signed by the same node. Am I wrong?

No, you are right, but if you are not specified the pub key core lightning uses its own public key, but if you are verifying a message signed by another node you must provide the pubkey.

I answer your question? or maybe I'm missing something?

**Comment by vincenzopalazzo** [comment]
On bruce node

```
➜  ~ clightning checkmessage "from bruce node" rdhdcuerrhfnc4ixuxgutrmwekwfrcnz8f9wi33zjdoc45nb1pi3rdgmwiwt9bq8dxh4usth637htqa1bahk1cf38bjktqggwiw4jwdq          
{
   "pubkey": "03e2408a49f07d2f4083a47344138ef89e7617e63919202c92aa8d49b574a560ae",
   "verified": true
}
```

Sorry if I ask again, but maybe I'm missing something. Can you can the example of sign and verify message as I did? so I can reproduce your use case maybe?

**Comment by gdassori** [comment]
On the same node:

Signing:
```
$ lightning-cli signmessage "yet another message"
{
   "signature": "106d570deea117b9d3159fe8814d6d0a07a6273cd41aae0edad999dcd1187a091c37f238721e05e89c2542d1b36ac4a1b20393f471ab64cb8d80a5de33847f48",
   "recid": "01",
   "zbase": "ryeg4iap74otxqqunsx6tykppwfyxjt88ukbimoq5mc3uzgtdb7y18bz6eh8r8of7nqnkostspicjep1yqj9ehpmcufa5yff5a3ae94e"
}
```

Verify with no explicit pubkey:
```
$ lightning-cli checkmessage "yet another message" ryeg4iap74otxqqunsx6tykppwfyxjt88ukbimoq5mc3uzgtdb7y18bz6eh8r8of7nqnkostspicjep1yqj9ehpmcufa5yff5a3ae94e
{
   "pubkey": "02a8f16a02fee11b151d08a204b0111da8d52db044a085e13d9b50896077865df6",
   "verified": false
}
```

Verify passing the pubkey:
```
$ lightning-cli checkmessage "yet another message" ryeg4iap74otxqqunsx6tykppwfyxjt88ukbimoq5mc3uzgtdb7y18bz6eh8r8of7nqnkostspicjep1yqj9ehpmcufa5yff5a3ae94e 02a8f16a02fee11b151d08a204b0111da8d52db044a085e13d9b50896077865df6
{
   "pubkey": "02a8f16a02fee11b151d08a204b0111da8d52db044a085e13d9b50896077865df6",
   "verified": true
}
```
The local node:

```
$ lightning-cli getinfo
{
   "id": "02a8f16a02fee11b151d08a204b0111da8d52db044a085e13d9b50896077865df6",
   ...
```

**Comment by vincenzopalazzo** [comment]
Thanks for this example, can you add also your system information?

It is something that I need to look into more in deeply. Thanks!

**Comment by gdassori** [comment]
Sure. What do you need to know, is that enough?

```
Ubuntu 20.04 LTS
5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

If the same scenario works on your node, I'd speculate it may fail on fresh installations with no peers connected at all.

**Comment by ShahanaFarooqui** [comment]
@gdassori, @vincenzopalazzo We explicitly send `pubkey` to checkmessage. So RTL is not affected currently, but thank you for keeping us in the loop.

**Comment by vincenzopalazzo** [comment]
I found some things @gdassori, you have right!

https://github.com/ElementsProject/lightning/blob/d22fd599973175e3d1a484a7aa2efd9916116bc5/lightningd/signmessage.c#L195-L201

**Comment by rustyrussell** [comment]
https://lightning.readthedocs.io/lightning-checkmessage.7.html

If you don't pass a pubkey, it tries to see if it's signed by a known node. If not, it means that you can't tell if the signature is valid.

(i.e. a bogus signature often looks like a valid signature from a bogus pubkey).
