### ISSUE TITLE
pylightning release on pypi outdated

### ISSUE THREAD

**Issue by gdassori** [ElementsProject/lightning#5265]
Hello, the latest version of pylightning on pypi is the 0.0.7.3, 

```
$ bin/pip install pylightning==0.11.0
ERROR: Could not find a version that satisfies the requirement pylightning==0.11.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.7.1, 0.0.7.3)
ERROR: No matching distribution found for pylightning==0.11.0
```

while the latest pyln-client is 

`__version__ = "0.11.0"`

Do you have any plan on releasing recent versions on pypi?

Thank you.

**Comment by gdassori** [comment]
Hi Vincenzo, thanks for your time.

So it's just some minors behind. The pypi version (latest 0.10.x) still missing the description_hash new feature (deschashonly param) added in the 0.11. Would be awesome to have it updated so I can fix some issues with LNURL on LNBits w/ CoreLightning.

Thank you.

**Comment by vincenzopalazzo** [comment]
>So it's just some minors behind. The pypi version (latest 0.10.x) still missing the description_hash new feature (deschashonly param) added in the 0.11. Would be awesome to have it updated so I can fix some issues with LNURL on LNBits w/ CoreLightning.

a hack can be used with the raw `call` method

For the release, I ping @cdecker the python packages are his children :)
