### ISSUE TITLE
Possible mismatch between comments/code for signal() call

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#528]
[channeld](https://github.com/ElementsProject/lightning/blob/master/channeld/channel.c#L2509), [closingd](https://github.com/ElementsProject/lightning/blob/master/closingd/closing.c#L180), [onchaind](https://github.com/ElementsProject/lightning/blob/master/onchaind/onchain.c#L1979), and [openingd](https://github.com/ElementsProject/lightning/blob/master/openingd/opening.c#L771) have code like the below:

    /* We handle write returning errors! */
    signal(SIGCHLD, SIG_IGN);

This seems strange since to my understanding only lightningd launches sub-daemons (so channeld, closingd, onchaind, and openingd will never receive SIGCHLD anyway).  Is my understanding correct?

Also, "write returning errors" event seems to occur only if SIGPIPE is ignored.

In [lightningd](https://github.com/ElementsProject/lightning/blob/master/lightningd/lightningd.c#L247) we instead have:

    /* Ignore SIGPIPE: we look at our write return values*/
    signal(SIGPIPE, SIG_IGN);

Which seems sensible (ignoring SIGPIPE will let write() return EPIPE).

Both hsmd and gossipd do not seem to use signal() at all, should they?

**Comment by rustyrussell** [comment]
Great observation!

Yech, a thinko bug cut & paste all over the code.  This horrified me enough to take a few minutes to clean it all up...
