### ISSUE TITLE
gRPC Docs

### ISSUE THREAD

**Issue by benthecarman** [ElementsProject/lightning#5280]
It would be nice to have docs on how to use the new gRPC server.

Some non-obvious this I have noticied:

No default port, only enabled if port is set
Not packaged with the release
Various `.pem` files are used (needed to read the code to find these lol)

**Comment by KayBeSee** [comment]
Better documentation around the gRPC plugin would really help devs hit the ground running using c-lightning.

For other people coming across this issue, to enable the gRPC plugin, `grpc-port=8001` must be present in the config file in the `.lightning` directory.

Also, the explainers for the various `.pem` certificates that are created can be found [here](https://github.com/ElementsProject/lightning/blob/master/plugins/grpc-plugin/src/tls.rs#L29):

```
/// Ensure that we have a certificate authority, and child keypairs
/// and certificates for the server and the client. It'll generate
/// them in the provided `directory`. The following files are
/// included:
///
/// - `ca.pem`: The self-signed certificate of the CA
/// - `ca-key.pem`: The key used by the CA to sign certificates
/// - `server.pem`: The server certificate, signed by the CA
/// - `server-key.pem`: The server private key
/// - `client.pem`: The client certificate, signed by the CA
/// - `client-key.pem`: The client private key
///
/// The `grpc-plugin` will use the `server.pem` certificate, while a
/// client is supposed to use the `client.pem` and associated
/// keys. Notice that this isn't strictly necessary since the server
/// will accept any client that is signed by the CA. In future we
/// might add runes, making the distinction more important.
///
/// Returns the server identity and the root CA certificate.
```
