### ISSUE TITLE
Segmentation fault when closing a channel in OPENINGD state

### ISSUE THREAD

**Issue by alexej996** [ElementsProject/lightning#530]
I just started testing yesterday, so forgive me for my lack of understanding about the protocol.
I will start with what happened before the crash, although it might be unrelated.
I will also add the crash.log file to this report.

### Before the crash
I tried connecting to some peers yesterday without success and to some others later successfully.
Then I stopped the node in the evening and today started it again.
For some reason I couldn't connect to any nodes so I had no data when running getchannels and getnodes. Apparently I needed more funds to connect to peers (makes sense for opening channels, but I don't know why this would be the case for connecting), but I don't remember the exact error.
This made me assume that I was simply not connected to the network, but was still getting peers when running getpeers, even peers from my past unsuccessful attempts to connect to them the day before showed up today in the list with OPENINGD state, one node appeared twice as well.
In total there was 2 nodes in the OPENINGD state, with the first one showing up twice in getpeers list and one was in ONCHAIND_THEIR_UNILATERAL state, which I assume was the successfully opened one.

### The crash
As I had the same node showing up twice with getpeers command and was in OPENINGD state, I tried closing it. And this is when lightningd crashed with segmentation fault.

[crash.log](https://github.com/ElementsProject/lightning/files/1611432/crash.log)

**Comment by cdecker** [comment]
Pretty sure that this cannot be reproduced with the latest build.
