### ISSUE TITLE
Wrong port is gossiped, in addition to correct one

### ISSUE THREAD

**Issue by laanwj** [ElementsProject/lightning#5305]
I'm having an issue where the gossiped port is wrong, possibly part of the time. It's supposed to be 9736, but 9735 ends up in the list too:
```bash
% lcli listnodes [M]
{
   "nodes": [
      {
         "nodeid": "[M]",
…
         "addresses": [
            {
               "type": "ipv4",
               "address": "[A]",
               "port": 9735
            },
            {
               "type": "ipv4",
               "address": "[A]",
               "port": 9736
            },
            {
               "type": "ipv6",
               "address": "[B]",
               "port": 9736
            },
            {
               "type": "torv3",
               "address": "[C].onion",
               "port": 9736
            }
         ]
      }
   ]
}
```
I not only see this in my own `listnodes`, other nodes and services do, as well. I do not have anything running on port 9735, FWIW, there's only one lightningd on this system. I've only ever seen it happen for IPv4.

Relevant configuration is:
```bash
    --proxy 127.0.0.1:9050 \
    --addr '0.0.0.0:9736' \
    --addr '[::]:9736' \
    --announce-addr '[C].onion:9736' \
```

`getinfo` output shows, correctly:
```bash
{
   "id": "[M]",
…
   "address": [
      {
         "type": "ipv4",
         "address": "[A]",
         "port": 9736
      },
      {
         "type": "ipv6",
         "address": "[B]",
         "port": 9736
      },
      {
         "type": "torv3",
         "address": "[C].onion",
         "port": 9736
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9736
      },
      {
         "type": "ipv6",
         "address": "::",
         "port": 9736
      }
   ],
   "version": "v0.11.0.1-36-g74ddc15",
…
}
```

**Comment by laanwj** [comment]
amboss.space has a history for the node that shows 9735 appearing and disappearing, it's really strange:

![amboss](https://user-images.githubusercontent.com/126646/172310341-2282917a-77be-4ae6-817d-424264c83231.png)

None of these are intentional configuration changes.

**Comment by vincenzopalazzo** [comment]
Mh! I did not debug it, and I put here only a pointer that we had changed somethings in the default port but there was some refusal that this PR will remove https://github.com/ElementsProject/lightning/pull/5242

Maybe can help

**Comment by laanwj** [comment]
Thanks @kroese and @vincenzopalazzo .

It doesn't look like `-autolisten false` solved the issue. Will try with `disable-ip-discovery`.

**Comment by rustyrussell** [comment]
Hmm, @m-schmoock ?  This shouldn't happen; we can't really tell what port is exposed, so we guess.  But obviously we should not add anything if that IP is already advertized!

**Comment by m-schmoock** [comment]
Yes. I'll open up an PR.
Maybe disable discovery at all when something is announced manually.

Secondly we should 'guess' testnetport on testnet.

**Comment by m-schmoock** [comment]
Or maybe only do discovery on IP protocols that are not configured manually.
