### ISSUE TITLE
Is disable-ip-discovery obsolete?

### ISSUE THREAD

**Issue by kroese** [ElementsProject/lightning#5308]
I want to run CLN on a custom port, so according to the documentation I need to add:

`disable-ip-discovery`

to my config file, to prevent the wrong port from being announced. And I really need it disabled, because Im running LND on port 9735, so Im sure discovery will be confused by this when it sees this port is open.

I also added an `announce-addr` but it was unclear if this disables ip discovery automaticly. 

But now I get the error:

`line X: disable-ip-discovery: unrecognized option`

So is the documentation outdated?

**Comment by heyambob** [comment]
what version are you running ? from 0.11 it should work.

```
disable-ip-discovery
```

in the config file works for me

or you can pass 

```
--disable-ip-discovery
```

on the lightningd command line

or if you run tor only mode with

```
always-use-proxy=true
```

in the config, then it won't attempt to do ip discovery
