### ISSUE TITLE
v0.11.1 htlc_minimum_msat and htlc_maximum_msat strange behavior

### ISSUE THREAD

**Issue by overcoin** [ElementsProject/lightning#5314]
config file settings for htlcmini, htlcmax, and maxdusthtlc are ignored.

### Steps to Reproduce
1. Set in config file:
ignore-fee-limits=false
htlc-minimum-msat=1000
htlc-maximum-msat=100000000000
max-dust-htlc-exposure-msat=10000000

2. Reload lightningd and get lightning-cli listconfigs:
...
"htlc-minimum-msat": "10000000msat",
"htlc-maximum-msat": "10000000msat",
"max-concurrent-htlcs": 30,
"max-dust-htlc-exposure-msat": "10000000msat",
...

### `getinfo` output
...
   ],
   "version": "v0.11.1",
   "blockheight": 739953,
   "network": "bitcoin",
   "msatoshi_fees_collected": xxx,
   "fees_collected_msat": "xxxmsat",
   "lightning-dir": "/home/xxx/.lightning/bitcoin",
   "our_features": {
      "init": "080a69a2",
      "node": "800000080a69a2",
      "channel": "",
      "invoice": "02000000024100"
   }
...

**Comment by rustyrussell** [comment]
Thanks for the great bug report!

I actually fixed this in 01411d70be0ffc9645caf85ba01aef51315ff8fa, which is in master (for 0.12).  It's cosmetic; listconfigs always shows the setting of max_dust_htlc_exposure_msat for every msat field!

So I'm going to close it now.  

If you want to fix it manually yourself, it's pretty easy: change `ld->config.max_dust_htlc_exposure_msat` in add_config() in lightningd/options.c to `*(struct amount_msat *)opt->u.carg`.
