### ISSUE TITLE
IPv6 binding on custom port fails

### ISSUE THREAD

**Issue by kroese** [ElementsProject/lightning#5317]
When binding on IPv6 to port 9750 according to the documentation you must use:

`bind-addr: :::9750`

but this results in:

`lightningd: /data/.lightning/config line 22: bind-addr: Unable to parse address ':::9750': Name or service not known`

the only solution is to use:

`bind-addr: :9750`

but this wil bind on IPv4 as well.

**Comment by rustyrussell** [comment]
'[::]:9750' works.  I'll update the docs.  Parsing IPv6 with ports appended is hard :(
