### ISSUE TITLE
listforwards local_failed should include an "out_channel" field

### ISSUE THREAD

**Issue by devastgh** [ElementsProject/lightning#5329]
As title.
`listforwards failed` has this field, `listforwards local_failed` does not.
It would be beneficial for a node operator to know which direction my forwards are failing, especially locally.
As i understand, for `unknown next peer` local failure this field could be empty.

**Comment by rustyrussell** [comment]
Right, in some cases it doesn't know, but there's at least one common case where it does, and yet doesn't set this field!  (We tell channeld to send it out, and it says "nope, no capacity").

Good catch!
