### ISSUE TITLE
release source download build issue - /bin/sh: 1: ./tools/autogen.sh: not found

### ISSUE THREAD

**Issue by lavarok** [ElementsProject/lightning#5350]
I downloaded v0.11.2.tar.gz. Per source code install instructions for Ubuntu, I ran: poetry install, ./configure --disable-rust, then poetry run make. During "make" it fails here:

"
cd external/libwally-core && ./tools/autogen.sh
/bin/sh: 1: ./tools/autogen.sh: not found
make: *** [external/Makefile:73: external/x86_64-linux-gnu/libwally-core-build/src/libwallycore.la] Error 127
"

**Comment by vincenzopalazzo** [comment]
Wait wait, the release should not have all the info regarding the build. It should be processed in some fancy way by github.

My, you can do the `git checkout v0.11.2` and after that make the install procedure?

**Comment by lavarok** [comment]
> My, you can do the `git checkout v0.11.2` and after that make the install procedure?

Building from a git repo works fine. 

Are there different instructions for the source code asset listed under the release?

**Comment by vincenzopalazzo** [comment]
> Are there different instructions for the source code asset listed under the release?

These assets are not created by us at release time, but from github release, not sure what is missing inside them (maybe the submodule)?

I think there is no way to build it, and also I considerer not safe a zip not signed buy the core devs

**Comment by PeterMcQuaid** [comment]
Getting exact same error when running: $make and $poetry run make

Fails at "cd external/libwally-core && ./tools/autogen.sh"
with error:

gsed: can't read ./tools/build-aux/ltmain.sh: No such file or directory
gsed: can't read ./tools/build-aux/ltmain.sh: No such file or directory
gsed: can't read ./src/secp256k1/build-aux/ltmain.sh: No such file or directory
gsed: can't read ./src/secp256k1/build-aux/ltmain.sh: No such file or directory
make: *** [external/x86_64-apple-darwin22.3.0/libwally-core-build/src/libwallycore.la] Error 2

It appears this line is the problem (in autogen.sh):

autoreconf --install --force --warnings=all

with error:

autoreconf: error: 'configure.ac' is required

No clue how to solve. 
I am running Mac OSX Ventura 13.2.1, no M1 chip, with git checkout v22.11.1

**Comment by vincenzopalazzo** [comment]
Are you using git clone? @PeterMcQuaid 

This issue should be close because the zip file with the source code is not created by us

**Comment by PeterMcQuaid** [comment]
> Are you using git clone? @PeterMcQuaid
> 
> This issue should be close because the zip file with the source code is not created by us

Yes I used git clone. I am following all the steps from: https://github.com/ElementsProject/lightning/blob/master/doc/INSTALL.md#to-build-on-macos

**Comment by vincenzopalazzo** [comment]
ok can you open an issue related to the osx? and up all what you see in the command line?

**Comment by PeterMcQuaid** [comment]
> ok can you open an issue related to the osx? and up all what you see in the command line?

Done 

https://github.com/ElementsProject/lightning/issues/6082
