### ISSUE TITLE
CLN stops accepting incoming connections after a while

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#5353]
### Issue and Steps to Reproduce
For some time (hours to days) after starting CLN, incoming connections are accepted. However, after some time this no longer happens. The socket is apparently left open, but nobody calls `accept` on it. This is evidenced by a connection attempt using `telnet <hostname> 9735` hanging in the "Connecting" phase rather than immediately being accepted (correct operation) or refused (CLN stopped).

### `getinfo` output
This is on version 0.11.2.

**Comment by whitslack** [comment]
Ahh, found this in the log:
```
2022-06-27T22:14:53.233Z **BROKEN** connectd: Failed to create socketpair: Too many open files
```

I guess `connectd` needs several file descriptors per active channel? I'll bump up my ulimit and see if that solves it.

**Comment by wtogami** [comment]
Curious how many channels do you have to hit that limit?

**Comment by whitslack** [comment]
> Curious how many channels do you have to hit that limit?

@wtogami: `getinfo` claims 960 active channels, 3 pending channels, and 43 inactive channels. So it would appear that `connectd` uses more than 4 file descriptors per channel on average.

**Comment by wtogami** [comment]
> @wtogami: `getinfo` claims 960 active channels, 3 pending channels, and 43 inactive channels. So it would appear that `connectd` uses more than 4 file descriptors per channel on average, as my limit was 4096 FDs.

Congratulations?

I wonder if CLN can see its own file descriptor limit and log warnings about this.

**Comment by zerofeerouting** [comment]
Just to chime in: My limit is 4096 as well and I do not see `Too many open files` in my logs, despite having 1,190 channels.
