### ISSUE TITLE
Can't build due to git issues

### ISSUE THREAD

**Issue by TonyGiorgio** [ElementsProject/lightning#5388]
### Issue and Steps to Reproduce

Looks similar to https://github.com/ElementsProject/lightning/issues/5221 but it is still a problem with the latest version and a slightly different error. Not sure how to proceed, I've never had git problems before building a project.

```
    git clone https://github.com/ElementsProject/lightning.git
    cd lightning/
    git checkout tags/v0.11.2
    poetry install
    ./configure
    poetry run make
    sudo make install

Makefile:7: *** "ERROR: git is required for generating version information".  Stop.
```

```
$ git --version
git version 2.25.1
```

**Comment by grubles** [comment]
Seems identical to #5189. Could you try the `git` command here? https://github.com/ElementsProject/lightning/issues/5189#issuecomment-1108229331

**Comment by niftynei** [comment]
try running `make -j$(nproc)` before `sudo make install`

guessing here, but i think `sudo` is causing problems

**Comment by TonyGiorgio** [comment]
Ah sorry about that, I had not seen #5189 . I tried both those solutions above and it worked, thanks!
