### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#539]
When I run make I get this. Is that just a warning which can be ignored?    
``
`channeld/test/run-full_channel.c: In function ‘include_htlcs’:
channeld/test/run-full_channel.c:140:5: error: ‘msatoshi’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   e = channel_add_htlc(channel, sender, i, msatoshi, 500+i, &hash,
   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          dummy_routing, NULL);
          ~~~~~~~~~~~~~~~~~~~~
channeld/test/run-full_channel.c:140:5: error: ‘sender’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

**Comment by cdecker** [comment]
I think you can safely ignore this, the loop is guaranteed never to have `i>4` in the `switch`-statement before this line. Might be a good idea to silence it by making the `case 4:` a `default:`. Incidentally what compiler are you using here?

**Comment by Sgt-Miller** [comment]
>what compiler are you using here?    
gcc 7.2.0

**Comment by cdecker** [comment]
Wow, that's quite a new one, that I haven't tested myself. But as I mentioned it should be safe to ignore :-)
