### ISSUE TITLE
Crash on gossipd?

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#5395]
Upgraded to the latest repository build, overnight my node crashed, here's the first lines of the log output and crash error. 

-------------------------

2022-07-09T22:48:13.322Z DEBUG   0318ac9faa9629e7da08819bc8fe0dd2ae3044d69b1b2283a63479acffeb968483-gossipd: Received channel_update for channel 7417>
2022-07-09T22:48:14.002Z DEBUG   023e09c43b215bd3dbf483bcb409da3322ea5ea3b046f74698b89ee9ea785dd30a-gossipd: Received channel_update for channel 7047>
lightning_gossipd: gossipd/gossip_store.c:644: delete_by_index: Assertion `(be32_to_cpu(belen) & GOSSIP_STORE_LEN_DELETED_BIT) == 0' failed.
lightning_gossipd: FATAL SIGNAL 6 (version v0.11.0.1-207-g9d1b5a6)
0x560d25d22e03 send_backtrace
        common/daemon.c:33
0x560d25d22e9d crashdump
        common/daemon.c:46
0x7fd47eceb08f ??? 
        ???:0
0x7fd47eceb00b ???
        ???:0
0x7fd47ecca858 ???
        ???:0
0x7fd47ecca728 ???
        ???:0
0x7fd47ecdbfd5 ???
        ???:0
0x560d25d166df delete_by_index
        gossipd/gossip_store.c:644
0x560d25d171f8 gossip_store_delete
        gossipd/gossip_store.c:665
0x560d25d1cdc8 routing_add_node_announcement
        gossipd/routing.c:1730
0x560d25d1d113 handle_node_announcement
        gossipd/routing.c:1851
0x560d25d14311 handle_node_announce
        gossipd/gossipd.c:281
0x560d25d15a1a handle_recv_gossip
        gossipd/gossipd.c:507
0x560d25d15b0b connectd_req
        gossipd/gossipd.c:583
0x560d25d22f5e handle_read
        common/daemon_conn.c:31
0x560d25d52309 next_plan
        ccan/ccan/io/io.c:59
0x560d25d527d6 do_plan
        ccan/ccan/io/io.c:407
0x560d25d52873 io_ready
        ccan/ccan/io/io.c:417
0x560d25d54208 io_loop
        ccan/ccan/io/poll.c:453
0x560d25d15d0c main
        gossipd/gossipd.c:1130
0x7fd47eccc082 ???
        ???:0
0x560d25d1161d ???
        ???:0
0xffffffffffffffff ???
        ???:0
lightning_gossipd: FATAL SIGNAL (version v0.11.0.1-207-g9d1b5a6)
0x560d25d22e03 send_backtrace
        common/daemon.c:33
0x560d25d2983c status_failed
        common/status.c:221
0x560d25d2994e status_backtrace_exit
        common/subdaemon.c:18
0x560d25d22ea3 crashdump
        common/daemon.c:49
0x7fd47eceb08f ???
        ???:0
0x7fd47eceb00b ???
        ???:0
0x7fd47ecca858 ???
        ???:0
0x7fd47ecca728 ???
        ???:0
0x7fd47ecdbfd5 ???
        ???:0
0x560d25d166df delete_by_index
        gossipd/gossip_store.c:644
0x560d25d171f8 gossip_store_delete
        gossipd/gossip_store.c:665
0x560d25d1cdc8 routing_add_node_announcement
        gossipd/routing.c:1730
0x560d25d1d113 handle_node_announcement
        gossipd/routing.c:1851
0x560d25d14311 handle_node_announce
        gossipd/gossipd.c:281
0x560d25d15a1a handle_recv_gossip
        gossipd/gossipd.c:507
0x560d25d15b0b connectd_req
        gossipd/gossipd.c:583
0x560d25d22f5e handle_read
        common/daemon_conn.c:31
0x560d25d52309 next_plan
        ccan/ccan/io/io.c:59
0x560d25d527d6 do_plan
        ccan/ccan/io/io.c:407
0x560d25d52873 io_ready
        ccan/ccan/io/io.c:417
0x560d25d54208 io_loop
        ccan/ccan/io/poll.c:453
0x560d25d15d0c main
        gossipd/gossipd.c:1130
0x7fd47eccc082 ??? 
        ???:0
0x560d25d1161d ???
        ???:0
0xffffffffffffffff ???
        ???:0
2022-07-09T22:48:14.485Z **BROKEN** gossipd: FATAL SIGNAL 6 (version v0.11.0.1-207-g9d1b5a6)
2022-07-09T22:48:14.485Z **BROKEN** gossipd: backtrace: common/daemon.c:38 (send_backtrace) 0x560d25d22e4b
2022-07-09T22:48:14.485Z **BROKEN** gossipd: backtrace: common/daemon.c:46 (crashdump) 0x560d25d22e9d
2022-07-09T22:48:14.485Z **BROKEN** gossipd: backtrace: (null):0 ((null)) 0x7fd47eceb08f
2022-07-09T22:48:14.485Z **BROKEN** gossipd: backtrace: (null):0 ((null)) 0x7fd47eceb00b
2022-07-09T22:48:14.486Z **BROKEN** gossipd: backtrace: (null):0 ((null)) 0x7fd47ecca858
2022-07-09T22:48:14.486Z **BROKEN** gossipd: backtrace: (null):0 ((null)) 0x7fd47ecca728

----------------------------

**Comment by rustyrussell** [comment]
Thanks @endothermicdev is on this!

**Comment by rustyrussell** [comment]
See also: #5387

**Comment by Coinomatron** [comment]
Thanks, forgot to mention uname -a:
5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Coinomatron** [comment]
Crashed again. I tried the pre-compiled release, but that gave me an error on the wrong lightning db number and before that a missing libpq.so.5 dep. Thought I'd mention it, in case it's related. 

Crash log here: https://paste.sh/EUuh4mW1#zcc5-yVA2jPp0bKp3TzAkfJQ

**Comment by grubles** [comment]
I believe the wrong DB number issue is because periodically some commits will upgrade your CLN node's database, and downgrading is not possible. See here for a similar issue: https://github.com/ElementsProject/lightning/issues/2291

**Comment by Coinomatron** [comment]
Yea, I was hoping this 'minor' release wouldn't update the DB in such a way, but it has. If this keeps happening, I need to find a way to respawn on crashes either through cron or supervisord or something.

**Comment by Coinomatron** [comment]
Compiled, running. Thanks for the quick fix!
