### ISSUE TITLE
Stuck transactions after initial send

### ISSUE THREAD

**Issue by tdaede** [ElementsProject/lightning#54]
Payments to the 0218 peer appear to be stuck.

12MB logs from dev-crash:
https://people.xiph.org/~tdaede/crash_035f.log
https://people.xiph.org/~tdaede/crash_0218.log

View from 035f:

```
$ daemon/lightning-cli getpeers
{ "peers" : 
    [ 
        { "name" : "0218e799f5085d90716493c0f9b5b7373ae47a0fb0c8cfba7411786f216e0ed15a:", "state" : "STATE_NORMAL", "peerid" : "0218e799f5085d90716493c0f9b5b7373ae47a0fb0c8cfba7411786f216e0ed15a", "connected" : false, "our_amount" : 1924280000, "our_fee" : 67599999, "their_amount" : 0, "their_fee" : 1, "our_htlcs" : 
            [ 
                { "msatoshi" : 1, "expiry" : 
                    { "block" : 1011980 }, "rhash" : "a957ac4630cf76cdc03957789b36a145665e64ef1a18d2e6a5a23f56e899e17d", "state" : "SENT_ADD_HTLC" }, 
                { "msatoshi" : 1, "expiry" : 
                    { "block" : 1011980 }, "rhash" : "9e8a2bcb36e754eb287db677655fe783c914ac90eff276e3ba9fb8a56f0b2b4b", "state" : "SENT_ADD_HTLC" } ], "their_htlcs" : 
            [  ] }, 
        { "name" : "02915506c736ffec49ad58fc021779600dcd2b7a52ac97690571aea5b4d9be2706:", "state" : "STATE_NORMAL", "peerid" : "02915506c736ffec49ad58fc021779600dcd2b7a52ac97690571aea5b4d9be2706", "connected" : true, "our_amount" : 3954660000, "our_fee" : 40378000, "their_amount" : 0, "their_fee" : 100000, "our_htlcs" : 
            [  ], "their_htlcs" : 
            [  ] } ] }
```

View from 0218:

```
{ "peers" : 
    [ 
        { "name" : "035f4dafaf485d5b3245a784cc02587e745d450d15eaaf187cf68a4f149569c522:", "state" : "STATE_NORMAL", "peerid" : "035f4dafaf485d5b3245a784cc02587e745d450d15eaaf187cf68a4f149569c522", "connected" : false, "our_amount" : 0, "our_fee" : 1, "their_amount" : 1924280000, "their_fee" : 67599999, "our_htlcs" : 
            [  ], "their_htlcs" : 
            [  ] } ] }
```

**Comment by cdecker** [comment]
After discussing this issue on IRC we came to the conclusion that the `0218` node was restarted and it chose a different random port, making re-connecting impossible. Maybe we could write the port back into the config if we have chosen it randomly so that we at least always restart with the same port?

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> After discussing this issue on IRC we came to the conclusion that the
> `0218` node was restarted and it chose a different random port, making
> re-connecting impossible. Maybe we could write the port back into the
> config if we have chosen it randomly so that we at least always
> restart with the same port?

Rewriting config files is usually bad.  I would prefer that we don't
create the listening at all unless they specify a port in their config?

Cheers,
Rusty.

**Comment by cdecker** [comment]
I'm fine with that for now, with 0.6 we will also have a default port, so we won't have too many people not accepting incoming connections :-)

**Comment by tdaede** [comment]
I imagine the P2P discovery will eventually allow rediscovery when an IP or port changes. IP addresses could also change - it would be nice to have an "addnode" RPC call to update the peer address table.

The other problem is that it wasn't obvious what was making it stuck, but now I know to check both getpeers and getnodes. Might be nice for lightning-pay to do the same.

**Comment by cdecker** [comment]
As soon as we have the new routing announcement protocol from #88 I'll also update existing channels so that reconnecting works.
