### ISSUE TITLE
test_gossip_store_compact_on_load

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/lightning#5410]
test_gossip_store_compact_on_load

```
expected: >       wait_for(lambda: l2.daemon.is_in_log(r'gossip_store_compact_offline: [5-8] deleted, 9 copied'))
actual: 2022-07-06T05:04:10.014Z DEBUG   gossipd: gossip_store_compact_offline: 9 deleted, 9 copied
```

**Comment by endothermicdev** [comment]
I haven't been able to replicate this flake locally.  The gossip store should look something like this under the nominal case:

1 DELETED Private channel_announcement
2 DELETED private channel_update
3 DELETED private channel_update
4 Push channel_announcement
5 channel amount
6 DELETED push channel_update
7 DELETED push channel_update
8 Push node_announcement
9 node_announcement
10 Push channel_update
11 private channel_announcement
12 DELETED private channel_update
13 DELETED private channel_update
14 Push channel_update
15 private channel_update
16 private channel_update

I thought this may be related to the gossip spam rewrite, but there were no spam entries in the CI logs, so I haven't found a connection.  For debugging purposes, I would like to add a call to devtools/dump-gossipstore before the compact occurs (if that sounds reasonable.)  I've done this locally, but without encountering the flake.

**Comment by niftynei** [comment]
#5483 hit this. log from the test fail attached.

[5_Build.txt](https://github.com/ElementsProject/lightning/files/9283883/5_Build.txt)

**Comment by niftynei** [comment]
archiving this
