### ISSUE TITLE
tests: add a "delete database" on the db fixture

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/lightning#5420]
a bunch of tests rely on being able to wipe the node database. we only run these on sqlite3 right now, it'd be great to make a generalized "wipe_db()" function on the db fixture in the tests so that we can run these tests seamlessly w/ any db backend.

e.g.

```
@unittest.skipIf(os.getenv('TEST_DB_PROVIDER', 'sqlite3') != 'sqlite3', "deletes database, which is assumed sqlite3")
def test_emergencyrecover(node_factory, bitcoind):
    ...
    os.unlink(os.path.join(l1.daemon.lightning_dir, TEST_NETWORK, "lightningd.sqlite3"))
```

**Comment by Sarthak027** [comment]
Hey, I'd like to work on this issue. 
Can I work on it?

**Comment by vincenzopalazzo** [comment]
@Sarthak027 please take it :)

**Comment by Sarthak027** [comment]
> @Sarthak027 please take it :)
assign me on this!

**Comment by Sarthak027** [comment]
> I'm a beginner can you help me to contribute to this?

**Comment by Vayras** [comment]
@niftynei Found this issue listed on the sphinx site , I wish to contribute towards this , can I work on this?, Thanks

**Comment by niftynei** [comment]
Sure @Vayras

**Comment by ecurrencyhodler** [comment]
This issue has been completed!! Can we get a bounty pay out? https://community.sphinx.chat/bounty/1213

**Comment by ecurrencyhodler** [comment]
I'm getting some weird redirects. I think it's tied specifically to the "new button" bounty. 
https://github.com/ElementsProject/lightning/assets/32662508/94d2ba22-409f-44ed-88c5-a501c0594741
