### ISSUE TITLE
HTLC expiry etc. must be checked against config.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#546]
`channeld/full_channel.c:484:	/* FIXME: check expiry etc. against config. */`

We need to check that the HTLC we or they are offering is acceptable according to the config of the other side (eg. amount too small).

**Comment by jBarz** [comment]
I wanted to deep dive into how HTLCs work so I was wondering if I could tackle this if no one else is :-)

**Comment by ZmnSCPxj** [comment]
Go for it.

**Comment by rustyrussell** [comment]
We actually seem to do all this now.  Closing.
