### ISSUE TITLE
Gossipd should not always need addrhint

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#547]
gossipd/gossip.c:1428:		/* FIXME: now try node table, dns lookups... */

- [x] We need to search for peers in existing gossip
- [ ] We need to do DNS bootstrap (#246 )

This will also help #390 and #527

**Comment by jb55** [comment]
What is the list of addrhints for? Don't we already have a list of peers which have pubkeys and addresses?

**Comment by jb55** [comment]
Oh I see it's sent when added from the cli...

**Comment by jb55** [comment]
Since we store addresses in the DB now, perhaps a quick fix for previously connected peers would be to simply resend addrhints to gossipd?

**Comment by jb55** [comment]
I implemented the previous comment here: #566 which fixes #527

**Comment by ZmnSCPxj** [comment]
I believe the first item is covered by #566?
