### ISSUE TITLE
gossipd needs to check for unsupported features

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#548]
`gossipd/routing.c:552:	// FIXME: Check features!`

`gossipd/routing.c:754:	// FIXME: Check features!`

We need to ignore announces with unknown even features as per BOLT

**Comment by ZmnSCPxj** [comment]
I would like to take this issue.

My plan is the below:

1.  Add new files `common/features.c` and `common/features.h`.  Move the features-related code from `lightningd/peer_control.c`/`lightningd/peer_control.h` to this.
2.  Implement the checking inside `gossipd` from this.
