### ISSUE TITLE
Need listforwards pruning

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#5498]
### Issue and Steps to Reproduce
https://twitter.com/zerofeerouting/status/1555425084201963520?t=zQWM6QUgOJjfmDuhkue_CQ&s=19

**Comment by zerofeerouting** [comment]
Related to #4687 

> I would really like to emphasize the importance of this. Especially with listforwards we're talking hundreds of thousands, if not millions of entries. Would also be great being able to filter results doing start_date=-2d or end_date=-12h.

**Comment by niftynei** [comment]
#5594 maybe?

**Comment by rustyrussell** [comment]
Fixed in #5594
