### ISSUE TITLE
lnd interoperability: "unable to start peer: invalid remote features: missing feature dependency: 45"

### ISSUE THREAD

**Issue by C-Otto** [ElementsProject/lightning#5500]
See https://github.com/lightningnetwork/lnd/issues/6802. No idea if that's an lnd or CLN issue.

**Comment by C-Otto** [comment]
Introduced by https://github.com/lightningnetwork/lnd/commit/a6c62eb71e6380c3b96d673a60c1712355342bb8 (in lnd, not released).

**Comment by C-Otto** [comment]
The lnd commit introduced support for feature 47, which depends on feature 45. When connecting to a CLN node, the CLN node sends a list of required (and optional?) features. For the more recent versions of CLN, it seems the features sent are:

`1 5 7 8 11 13 14 17 19 21 27 29 47 51`

Note that 47 is included, but not 45, which is required for lnd. This seems to be a CLN bug?

**Comment by C-Otto** [comment]
Bolt 9 doesn't state any dependency, so I guess this is a lnd bug after all :)

**Comment by rustyrussell** [comment]
Otoh, we *do* support this feature, so should set it.

I have a patch queued for this next release, do we apply now?

**Comment by rustyrussell** [comment]
And frankly, feature *should* be dependent on spec
