### ISSUE TITLE
onchaind: restart in case of reorg.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#551]
`lightningd/peer_control.c:1117:		/* FIXME!`

By design, onchaind only deals with chain extensions: it needs to be restarted (from the first spend of the funding tx) if one of the transactions is reorged out.

**Comment by ZmnSCPxj** [comment]
https://github.com/ElementsProject/lightning/blob/master/lightningd/peer_control.c#L1368 seems to suggest that this behavior is already what we do on master, so maybe this issue can be closed?

**Comment by ZmnSCPxj** [comment]
This comment suggests that this is already implemented: https://github.com/ElementsProject/lightning/blob/b3d4e161b5b361bb0b86fb35530d994908412633/lightningd/peer_control.c#L1392-L1393

**Comment by cdecker** [comment]
Strange, that comment is part of a 6 month old commit, maybe we simply didn't remove the `FIXME`? @rustyrussell

**Comment by rustyrussell** [comment]
That's true for a reorg that removes the spending transaction, yes.

But we still don't hand the case where another transaction is reorged, eg one of the HTLC spends.

**Comment by cdecker** [comment]
Commit fe22aa861fbb844e455e646472a139dab8c51346 seems to have solved this, but didn't close the issue. @rustyrussell can this be closed?

**Comment by rustyrussell** [comment]
Yes.
