### ISSUE TITLE
The purpose of dynamically detected public IP addresses in 0.12.0 'getinfo' output?

### ISSUE THREAD

**Issue by overcoin** [ElementsProject/lightning#5553]
I understand that in 0.12.0 release dynamically detected public IP addresses are added to `getinfo` output. I can see that the port of my public IP address is constantly changing. What is the purpose of dynamically changing the port if router firewall is blocking this ports?

**Comment by cdecker** [comment]
The IP discovery was proposed by @m-schmoock in https://github.com/lightning/bolts/pull/917. It's purpose is to discover our external address if we don't specify one. The port is likely random since you are connecting out, and we should likely not use the port for outgoing connections at all, since we just get a random one back that was assigned to us by our OS.

**Comment by m-schmoock** [comment]
@overcoin
The `getinfo` output should include the dynamically detected IP address and a statically 'assumed' mainnet port 9735.
Can you give me your node `getinfo` output maybe including your nodeid so I can check gossip and explorers on what your node announces?

**Comment by overcoin** [comment]
@cdecker
Thanks for pointing to lightning/bolts#917. It is useful.

@m-schmoock
getinfo output:
===
"id": "XXX",
   "alias": "XXX",
   "color": "XXX",
   "num_peers": 69,
   "num_pending_channels": 0,
   "num_active_channels": 64,
   "num_inactive_channels": 2,
   "address": [
      {
         "type": "ipv4",
         "address": "XXX",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "XXX.onion",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "65.108.134.61",
         "port": 40510
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "192.168.88.XXX",
         "port": 9735
      }
   ],
   "version": "v0.12.0",
   "blockheight": 752367,
   "network": "bitcoin",
   "fees_collected_msat": XXX,
   "lightning-dir": "/home/XXX/.lightning/bitcoin",
   "our_features": {
      "init": "08a000080a69a2",
      "node": "88a000080a69a2",
      "channel": "",
      "invoice": "02000000024100"
   }
===
Please, note that dynamically detected IP address mentioned above is not mine. I'm sending to you private details by email. Thank you beforehand for looking into that.

**Comment by m-schmoock** [comment]
@overcoin this is strange. From the config file you send me via mail I can see that your node explicitly announces `84.40.94.170:9735`. The thing is, with version 0.12 announcement if discovered IPs is disabled when you already have usable addresses.

Are you absolutely sure that you are running a 0.12 release?

**Comment by overcoin** [comment]
@m-schmoock
Please, don't put my IP on a public place! This is why I've sent to you private data via email.

Yes, I'm quite positive  I'm running v0.12.0 following the standard procedure:
git clone git clone https://github.com/ElementsProject/lightning.git
cd lightning
git checkout v0.12.0
git verify-tag v0.12.0

then compiling:
pip3 install --upgrade pip
pip3 install mako mistune==0.8.4 mrkd
./configure
make
sudo make install

Do you think it is possible getinfo output showing v0.12.0 while I'm running some other version?

**Comment by m-schmoock** [comment]
Sorry, deleted my last post.

**Comment by m-schmoock** [comment]
And yes, you are running 0.12.

**Comment by overcoin** [comment]
There was no need to delete the entire post. You should only edit it to delete my public IP. It is okay, no worries.

**Comment by overcoin** [comment]
Just for the record... Now getinfo ioutput is changed. It is showing dynamically detected public IP addresses is back to my public IP address port 59828. I didn't do any config changes or restarts on my node.

**Comment by devastgh** [comment]
> Just for the record... Now getinfo output is changed. It is showing dynamically detected public IP address is back to my public IP address port 59828. I didn't do any config changes or restarts on my node.

The port number in getinfo is a visual "bug". Actually that port number is true, but it's the port of your outgoing connections. You node will announce the default port (9735 on mainnet). Maybe instead of assuming the port number, we could use the binding port number, as that way people could run autodiscovery on non-default ports as well, but that also needs the `--ip-discovery=true/false(/auto)` switch.

**Comment by m-schmoock** [comment]
@overcoin Sorry, for responding a bit late.
So, I checked your currently only announcing the IP you gave your node by config.
Did you use the `--disable-ip-discovery`switch?
I think there is no need to disable it, as you defined an IP via config already, and that should switch discovery off already.

It may be the case, as mentioned by devastgh, that this is 'visual bug' that only tells you that it would announce that if enabled. Also the port that is you outgoing port, which is dynamically. Also, I know for sure that this will not be anounced.
I'll investigate this and open up a ticket, if so.

There will be a follow up that will deprecate the `--disable-ip-discovery` switch and replace it by `--ip-discovery`  `true/false/auto`.

@devastgh I don't like the idea of using the binding port, I already thought about that. The local binding port can be completely different, especially when talking about containerized services in docker using some kind of network bridge proxy etc.
Instead, maybe we add the option to set the 'to be announced public port' differently than `9735`.

**Comment by devastgh** [comment]
> @devastgh I don't like the idea of using the binding port, I already thought about that. The local binding port can be completely different, especially when talking about containerized services in docker using some kind of network bridge proxy etc. Instead, maybe we add the option to set the 'to be announced public port' differently than `9735`.

Makes sense. However it might need some new option like `ip-discovery-port` as it would make a mess to somehow try to insert it into the current addressing scheme.

**Comment by m-schmoock** [comment]
@overcoin 
Indeed this is a visual bug and nothing was announced.
Still needs to be addressed in #5584. Thanks for the finding.

**Comment by m-schmoock** [comment]
Also `getinfo` shows outbound ports on discovered IPs instead of `chainparams_get_ln_port(chainparams)` (which means `9735`), because the port is currently set by gossipd.

**Comment by m-schmoock** [comment]
@overcoin 
I think this can be closed now.
Master is fixed, you can cherrypick #5585 and #5585 if you wish or wait for next release.
