### ISSUE TITLE
pyln-client 0.12.0 doesn't work with cln 0.11.1

### ISSUE THREAD

**Issue by infcodey** [ElementsProject/lightning#5558]
With pyln-client 0.12.0 and cln 0.11.1, and  "allow-deprecated-apis": true,

Running 
```
from pyln.client import LightningRpc
lightning_node_instance = LightningRpc("/home/{user}/.lightning/bitcoin/lightning-rpc")
invoice = lightning_node_instance.invoice(10, "1", "1")
```
gives the following error: 
```
pyln.client.lightning.RpcError: RPC call failed: method: invoice, payload: {'amount_msat': 10, 'label': '1', 'description': '1'}, error: {'code': -32602, 'message': 'unknown parameter: amount_msat, this may be caused by a failure to autodetect key=value-style parameters. Please try using the -k flag and explicit key=value pairs of parameters.'}
```

**Comment by vincenzopalazzo** [comment]
Ok!  think here there is no clear solution! if you work with an older version of cln you should use the python client for this version!

When you will go to upgrade cln the python API will not change but under the hood the python lib applies the deprecation logic, and this is the more sane solution that we can provide :)

**Comment by rustyrussell** [comment]
Yes, this is kind of expected.  pyln-X needs cln >= X to work reliably.
