### ISSUE TITLE
`setchannel` is missing in cln-rpc and cln-grpc crates

### ISSUE THREAD

**Issue by HaosGames** [ElementsProject/lightning#5569]
The method `setchannel` is missing in both the cln-rpc and the cln-grpc crate.

**Comment by vincenzopalazzo** [comment]
we should make a list of commands that cln-rpc and friend support! maybe we can unlock some good first issue too.

What do your think @cdecker ?

**Comment by whitslack** [comment]
Was this addressed by 51e243308761e056d0da23e596b7dfedbb909db1?

**Comment by HaosGames** [comment]
Yes, it was. Thank you
