### ISSUE TITLE
`mako` dep broken due module on found

### ISSUE THREAD

**Issue by vincenzopalazzo** [ElementsProject/lightning#5570]
I noted this on CI relate to lnprototest, I open the issue just to keep track of this error, and also I make sure that the error is node generate by the `python-mako` ubuntu dep

```
wiregen hsmd/hsmd_wiregen.h
cc ccan/ccan/cdump/tools/cdump-enumstr.c
cc ccan/ccan/cdump/cdump.c
Traceback (most recent call last):
  File "tools/generate-wire.py", line 27, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
make: *** [Makefile:337: hsmd/hsmd_wiregen.h] Error 1
make: *** Waiting for unfinished jobs....
wiregen hsmd/hsmd_wiregen.h
Traceback (most recent call last):
  File "tools/generate-wire.py", line 27, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
make: *** [Makefile:337: hsmd/hsmd_wiregen.h] Error 1
```

I can take a look into it later in the week

**Comment by niftynei** [comment]
caused by a poetry install failure, think we've fixed this now?

**Comment by vincenzopalazzo** [comment]
Yeah this was before the fix, unfortunately, I had not enough permission to manage labels or milestones, but I think this PR could be also take in consideration to fix poetry instead or remove it https://github.com/ElementsProject/lightning/pull/5606
