### ISSUE TITLE
TypeError in pyln-client get_json_id()

### ISSUE THREAD

**Issue by MiWCryptAnalytics** [ElementsProject/lightning#5609]
I noticed that a py plugin (rebalance) will silently fail to load with the newer py lib.
From debug logging, I can see that it is raising a TypeError on the str cat operation:
TypeError: unsupported operand type(s) for +: 'int' and 'str'

https://github.com/ElementsProject/lightning/blob/248d60d7bd7e9a1961e70a3579ea93a0d496d6cc/contrib/pyln-client/pyln/client/lightning.py#L338

Can I recommend an fstring instead?
eg:  
`this_id = f'{cmdprefix}/{this_id}'`

**Comment by rustyrussell** [comment]
Are you using the master branch of the python lib with the 0.12.0 version of the code?

**Comment by MiWCryptAnalytics** [comment]
Yes, 0.12.0 client via docker image and I copied the py libs from master branch into my plugin volume to provide runtime dependencies

**Comment by MiWCryptAnalytics** [comment]
❤️ Thanks rusty! f-strings are great!
