### ISSUE TITLE
Cannot connect using JSON-RPC. lightning-rpc file is empty

### ISSUE THREAD

**Issue by asocjal** [ElementsProject/lightning#561]
I'm not familiar with JSON-RPC, but looking on pylightning I found out that is uses file files from some tmp directory:

>     l1 = LightningRpc("/tmp/lightning1/lightning-rpc")
    l5 = LightningRpc("/tmp/lightning5/lightning-rpc")

Should I use such files instead of user, pwd, ip and port?

I have lightning-rpc file in "/home/cd/.lightning/lightning-rpc", but this file is empty. Is this correct? lightning-cli works on my machine.

**Comment by jb55** [comment]
> I have lightning-rpc file in "/home/cd/.lightning/lightning-rpc", but this file is empty. Is this correct? lightning-cli works on my machine. 

lightning-rpc is a unix socket. You can communicate with it using the
unix socket api. I have a Haskell example[1] of communicating with it
but that's probably not helpful. With some googling it shouldn't be hard
to do something similar in your language of choice.

[1] https://github.com/jb55/rustydice/blob/b2a1e750de0f07d418a7de51f98f33ca2d2ec822/src/Network/RPC/Internal.hs#L24

**Comment by asocjal** [comment]
Thanks a lot! Now it works. Can you please answer me one more question? Is there any mechanism to get callback? Is there such mechanism to wait for something (for example - invoice paid) or I need to ask deamon every one second to know if invoice was paid?

**Comment by ZmnSCPxj** [comment]
Use `waitanyinvoice` RPC. It is not quite a callback --- you are intended to have a separate loop/process/thread/greenthread which just calls `waitanyinvoice` repeatedly on its own RPC connection. https://github.com/ElementsProject/lightning/blob/master/doc/lightning-waitanyinvoice.7.txt

**Comment by asocjal** [comment]
Thanks for help! My proposition is to close issue.
