### ISSUE TITLE
[Feature request] TCP socket transport for RPC

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#562]
I am planning to use Lightning-C for BTCPay so merchant can accept lightning payments.

BTCPay has lot's of dependencies (litecoind, bitcoind, NBxplorer, Postgres), so all developers just use a 
 `docker-compose` file I created for their local development which setup everything.
Developers debug/tests BTCPay on their own OS, and BTCPay connect to dependencies inside the docker service. Doing so make it possible for developers to use Linux or Mac environment for dev purpose without having to waste time explaining how to setup dependencies depending on the OS.

Lightning-C supports only pipe transport for RPC, so using lightning would require all contributors to BTCPay to develop on Mac or Linux, and worse than that: I would not be able to package this dependency into a container and access it from another container. So I would not be able to use `docker-compose` for one-click deployment of BTCPay.

To start development I would need one of the following:

* Support of TCP socket transport instead of pipe for RPC
* A docker container which run lightningd + a utility exposing the pipe as a socket so lightning can be accessed from the outside

**Comment by NicolasDorier** [comment]
Actually this might do the trick https://stackoverflow.com/questions/25433264/using-netcat-to-pipe-unix-socket-to-tcp-socket

**Comment by NicolasDorier** [comment]
Issue solved by https://github.com/ElementsProject/lightning-charge

**Comment by jb55** [comment]
I was looking into this for an app I'm building, I would like the lightning node to not be on the VPS, but would still like the VPS to be able to communicate with the lightning node for isolation purposes. I was about to look into socat/netcat for the rpc socket... @NicolasDorier how does lightning-charge solve this?

**Comment by jb55** [comment]
I was able to get it working over tcp with these socat commands:

server:
```bash
socat -d -d TCP-LISTEN:7878,fork,reuseaddr UNIX-CONNECT:/home/user/.lightning/lightning-rpc
```

client:
```bash
socat -d -d UNIX-LISTEN:/tmp/lightning,reuseaddr,fork TCP:172.24.242.111:7878

lightning-cli --rpc-file=/tmp/lightning listpeers
```

in this case I'm making this tunnel over a VPN, obviously not a good idea to do this on a public network.

**Comment by niftynei** [comment]
i use a `ssh` port-forwarding between a VPS and my private node. `charge` lives on the same private server as the lightning-node. apache forwards requests to its public domain over a `ssh` tunnel to its socket on the private server.  the `ssh` tunnels originate from the private server.

**Comment by shesek** [comment]
An alternative solution is forwarding the unix socket over an ssh tunnel, like so:

```
$ ssh -nNT -L /local/path/for/lightning-rpc:/home/remoteuser/.lightning/lightning-rpc remoteuser@somehost
```

**Comment by jb55** [comment]
I find ssh tunnels not so reliable, socat over vpn seems to be working pretty solid so far.
