### ISSUE TITLE
[feature-request]: New gRPC methods

### ISSUE THREAD

**Issue by niteshbalusu11** [ElementsProject/lightning#5634]
### Issue and Steps to Reproduce

@cdecker  sorry for the long list, the following methods could really help me out.

Please add/build out new gRPC methods:

- [X] ListClosedChannels
- [ ] openChannelAbort
- [ ] fundChannelCancel
- [ ] multiFundChannel
- broadcastChainTransaction

Subscriptions:

- [X] staticBackups
- [X] forwards
- channel events (opens/closes)
- [X] payments (send/receive)
- chain transactions
- Subscribe to probes

**Comment by theborakompanioni** [comment]
>     * ListClosedChannels

This is already included with https://github.com/ElementsProject/lightning/commit/bff3b1ca8ce89f912bcf956976ce111523cac82d :muscle: 

>     * broadcastChainTransaction

This might have happened in https://github.com/ElementsProject/lightning/commit/04e7e285d7169485a480c3ec7abd3358ef82561b  :rocket:, depending on if this is what you meant..

I am going to take a leap and throw 'listConfigs` in the list..
- [ ] `listConfigs`

Should I open a separate issue?

**Comment by cdecker** [comment]
I made the RPC methods into a check-list, and checked the ones that are already present. Some of the methods you list need disambiguation, as there is no method `broadcastChainTransaction` and `ProbeNode`. Did you copy those from another implementation, it isn't quite clear which method you need.

**Comment by niteshbalusu11** [comment]
> I made the RPC methods into a check-list, and checked the ones that are already present. Some of the methods you list need disambiguation, as there is no method `broadcastChainTransaction` and `ProbeNode`. Did you copy those from another implementation, it isn't quite clear which method you need.

I removed probe (doesn't make sense to have that).
`broadcastChainTransaction` just wanted to an RPC method that can take a raw tx and broadcast it.
