### ISSUE TITLE
"amount_msat" not recognized by lightning-cli

### ISSUE THREAD

**Issue by ZenenTreadwell** [ElementsProject/lightning#5644]
I encountered this bug while I was getting LnBits up and running on my server. LnBits leverages python's LightningRpc module to interface with the lightning server, and when it used the .invoice() function there was an error thrown by the lightning-cli. 

```
{
   "code": -32602,
   "message": "unknown parameter: amount_msat, this may be caused by a failure to autodetect key=value-style parameters. Please try using the -k flag and explicit key=value pairs of parameters."
}
```
This had nothing to do with the key=value pairs. It comes from pyln translating the "msatoshi" parameter into "amount_msat", which is not recognized by lightning-cli (at least in v0.11.2).  

### Issue and Steps to Reproduce
1. checkout branch `release-0.11.2` and build lightning-cli
2a. open a python interpreter
2b. from pyln.client import LightningRpc
2c. ln = LightningRpc('/path/to/your/lightning-rpc')
2d. ln.invoice(amount_msat=100, label="test", description="bugtest")

expected results should be the above error.

I have fixed the problem locally but I am hesitant to open up a PR because it seems like some of these changes are intentional, and I don't know if it's better to change the lightning-cli interface or the client interface.

**Comment by vincenzopalazzo** [comment]
What pyln-client package of python package do you have installed in the system?

**Comment by ZenenTreadwell** [comment]
Ah, that could do it. I'm using pyln-client v0.12 and cln v0.11. Aren't minor changes supposed to retain backwards compatibility though?

**Comment by vincenzopalazzo** [comment]
No, with cln 11 the suggested python version is the v0.11 or the close one, in particular with the 0.12 there is some problem related to some refactoring that we made

**Comment by ZenenTreadwell** [comment]
Okay, I think that this might be the problem relating to that refactoring. Is there interest in adding backwards compatibility as a patch?

**Comment by vincenzopalazzo** [comment]
I do not think so, this problem was already discussed here https://github.com/ElementsProject/lightning/issues/5558

**Comment by ZenenTreadwell** [comment]
I see. I tried looking up "amount_msat" among the issues but nothing came up. If that ticket was resolved, this one might as well be too.
