### ISSUE TITLE
Missing a step when funding a channel

### ISSUE THREAD

**Issue by bruceleeroy18** [ElementsProject/lightning#565]
I am missing a step somewhere in funding a channel. I generate an address, and then send testnet coins to the address. After confirmation I attempt to, "bitcoin-cli -testnet sendtoaddress 'address' 'amount' " Then I get an insufficient fund error. (What am I missing here? it feels obvious).

**Comment by Sgt-Miller** [comment]
The amount is in btc, not satoshi
What does bitcoin-cli -testnet  getbalance      
say?

**Comment by ZmnSCPxj** [comment]
To be more specific:

1.  `bitcoin-cli` always accepts a floating-point number in BTC units.
2.  `lightning-cli fundchannel` accepts a 64-bit integer in satoshi units (trailing ".0" are errored, so even "1000.0" triggers an error)
3.  `lightning-cli pay`, `lightning-cli sendpay`, `lightning-cli invoice` accept a 64-bit integer in millisatoshi units (again errors on ".0", must be a flat integer).

**Comment by bruceleeroy18** [comment]
Thanks for the help. I knew it was something obvious that my eyes were not catching. I actually tried to fund the lightning-cli newaddr directly from the faucet. I would then obviously get an empty balance from my bitcoin-cli getbalance, and an insufficient fund from the bitcoin-cli sendtoaddress. 

Now the intermediate steps are fine, but upon using cli/lightning-cli addfunds. I get "could not add outputs to wallet."

(I am a novice so any help is appreciated)

**Comment by ZmnSCPxj** [comment]
The README is a bit old and `addfunds` is no longer necessary I believe --- a previous pull request added the facility to automatically monitor incoming onchain funds.  Try `listfunds` (no arguments) to see if lightningd already discovered the incoming onchain funds you sent to it.

**Comment by cdecker** [comment]
Yep, `lightnignd` now recognizes its own funds, it may take one confirmations to show up, but eventually `listfunds` should show that the internal wallet has some funds available.

**Comment by bruceleeroy18** [comment]
Thanks for all the help!
