### ISSUE TITLE
Payment fails if htlc-minimum-msat value is more than 1000 msat

### ISSUE THREAD

**Issue by sancoder** [ElementsProject/lightning#5651]
### Issue and Steps to Reproduce
I configured my node with `htlc-minimum-msat=10000000` in the config file.
After opening only one channel I cannot pay anything. Any payment attempt fails with
`lightning-cli: Malformed response 'INFO    plugin-pay: cmd 167 partid 0: Destination NODEID is not reachable directly and all routehints were unusable.`

Searched through source code for this message. Found it in libplugin-pay.c, in function routehint_check_reachable.
If I read it correctly, the function tries first to get a route for payment in the amount of 1000 msats, and if dijkstra() returns "no route" response my error is raised.

lightning-cli getroute works fine.

**Comment by sancoder** [comment]
Just confirmed the bug is because of the parameter.
After adjusting parameter value to 1000 msat, the pay request fails with other error. Meaning I got passed that bug.

Another bug here is about `Malformed response`.
My config is that lightningd is started by systemd, with command line parameter `--log-file=-`.
I guess there is some confusion in the code of c-lightning as `Malformed response` is meant to be written into log file. But waiting party on another end of the wire expects a JSON, not a log line.

**Comment by SimonVrouwe** [comment]
Just to be sure, was the channel sufficiently balanced? Please check the channel's `spendable_msat` field, which depends on `their_reserve_msat`.

What version of c-lightning are you running? Any `--experimental-features` enables?

**Comment by vincenzopalazzo** [comment]
>lightning-cli getroute works fine.

works fine means that you get an answer, or you got a valid route where the payment can pass through?

>Please check the channel's spendable_msat field, which depends on their_reserve_msat.

I think @SimonVrouwe got the source of the problem?

**Comment by vincenzopalazzo** [comment]
Closing it for now, but feel free to reopen it if you still have this problem

**Comment by sancoder** [comment]
Sorry, missed previous responses. I don't know if I have an issue right now, not using CLN anymore.
1. The channel was fresh and unbalanced. All liquidity was on my side since it was me who opened the channel.
2. getroute command works fine means I get the route, I get valid route. The payment cannot go through, and that's why I opened this bug.
3. I was using the latest version of CLN, compiled by myself. No experimental features were used.

I think my initial analysis points to the place where the bug is located. Closing "due to inactivity" means nobody fixed anything.
So yes, I would reopen this bug. 
Let me explain once again:
Current algorithm for routing a payment in CLN searches for valid route for a small payment first. If a valid route for small payment is found, the algorithm continues. The problem is that if I configure my node with parameter htlc-minimum-msat > 1000 msat, the search for valid route for a small payment fails. It fails because the search algorithm tries to find a route for 1000 msat payment. Since my node had only one channel with htlc-minimum-msat > 1000 msat, there is no possible route for such a small payment. And this is the reason why the payment failed.

**Comment by sancoder** [comment]
Added comment.

--
  Sincerely,
  Anton Shevchenko
  ***@***.***
