### ISSUE TITLE
Non user channel closure

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#5659]
Channel closed a few days ago with message:

message": "channeld: sent ERROR bad reestablish revocation_number: 377 vs 424

I'm on version v0.11.0.1-231-gddf8fbd. 

Not sure if it's of interest, but thought I'd post it anyway.

**Comment by whitslack** [comment]
It means your peer had restored an outdated backup, and your node helpfully told them they're out of date and closed the channel. There's nothing you can do about someone else's poor backup practices.

**Comment by Coinomatron** [comment]
Thanks!
