### ISSUE TITLE
Payment recording discussion

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#570]
While implementing any-amount invoices #534 #545 I found that `struct wallet_payment` objects are created and saved in the database during invoice creation.

However, we should consider just exactly what we mean by this wallet payment structure and so on.

1. @rustyrussell mentioned to separate the structure for incoming and outgoing payments, and to not make the incoming payment structure until the invoice is paid.
2. @cdecker mentioned to record all in a single table, so that we have pending incoming payments (from invoices), completed incoming payments, and completed outgoing payments.
3. @rustyrussell also mentioned that we should record the actual value paid to our invoices, since (1) BOLT11 allows overpayment and (2) any-amount invoices can be paid with any amount.

**Comment by ZmnSCPxj** [comment]
Assuming #573 is merged, we should probably add `msatoshi_paid` column to the `invoices` table.

I wonder if we should consider reorganizing `struct invoices` and `struct invoice` code away from `lightning/invoice.c` into a new `wallet/invoices.c` file.  Then reorganize the object structure so that a `struct wallet` owns a `struct invoices` object, which owns all the `struct invoice` objects.  Then clients of the invoices system get read-only access to `struct invoice` via the interface:

1.  `const struct invoice *wallet_invoice_get_by_rhash(struct wallet*, const struct rhash*)`
2.  `const struct invoice *wallet_invoice_get_by_label(struct wallet*, const char *)`
3.  `void wallet_invoice_resolve(struct wallet*, const struct invoice *, u64 msatoshi_paid)`
4.  `void wallet_invoice_waitone(struct wallet*, const struct invoice*, void (*cb)(void*, const struct invoice *), void*)` <- immediately calls callback if expired or paid already.
5.  `void wallet_invoice_waitany(struct wallet*, u64 pay_index, void (*cb)(void*, const struct invoice *), void*)`
6.  `bool wallet_invoice_delete(struct wallet*, const struct invoice*, enum invoice_state)` <- should probably add a new `invoice_state`, expired?
7.  `const struct invoice *wallet_invoice_iterate(struct wallet*, const struct invoice* prev)` <- to use: `const struct invoice *iterator = NULL; while((iterator = wallet_invoice_iterate(wallet, iterator))) { /* ... */ }`
8. `const struct invoice *wallet_invoice_create(struct wallet*, u64 *msatoshi TAKES, const char *label TAKES, const char *description TAKES)`

This removes the ambiguity of just how much `wallet_invoice_save` needs to save; instead all of the above functions have access directly to the database, being part of the wallet subsystem.
The above functions will handle updating the database directly.  This would also simplify slightly when we decide to remove the in-memory list structure for something else.

**Comment by rustyrussell** [comment]
OK, I thought this would be a trivial thing to add, and I really wanted to do it ASAP because it alters the JSON API.  It turned out a bit epic, and I'd really appreciate your review on the PR, @ZmnSCPxj !
