### ISSUE TITLE
How to generate invoice for larger amount without MPP?

### ISSUE THREAD

**Issue by urza** [ElementsProject/lightning#5724]
I created invoice for amount over 5 mio sats and CLN created bolt11 invoice for me.

This invoice was intended for my direct peer (we have channel) with enough balance on his side to pay the invoice. However because generated invoice was MPP, the payment failed. 
(We both use CLN 0.12.x)

Here is a beginning the the failed payment response:

```
"code": 210,
   "message": "Ran out of routes to try after 38 attempts: see `paystatus`",
   "attempts": [
      {
         "status": "pending",
         "partid": 1,
         "amount": "5086008000msat",
         "amount_msat": "5086008000msat"
      },
      {
         "status": "failed",
         "failreason": "failed: WIRE_MPP_TIMEOUT (reply from remote)",
         "partid": 2,
         "amount": "2391212892msat",
         "amount_msat": "2391212892msat",
         "parent_partid": 1
      },
      {
         "status": "failed",
         "failreason": "No path found",
         "partid": 3,
         "amount": "1931516984msat",
         "amount_msat": "1931516984msat",
         "parent_partid": 1
      },
etc
```

Then I split the amount into two separate bolt11 invoices with smaller amounts, that were not created as MPP, they both went through successfully.

**1. What is the limit over which CLN creates MPP invoices?
2. Can this be avoided? Can I instruct CLN to create simple invoice without MPP even with larger amount?**

**Comment by devastgh** [comment]
I'm not sure it has anything to do with the invoice, but cln cannot pay any invoice bigger than x sats directly to a peer. See #5417

**Comment by grubles** [comment]
As a temporary workaround I believe you can disable MPP altogether in your CLN config file.

**Comment by urza** [comment]
Same issue discussed here: https://github.com/ElementsProject/lightning/issues/5724

**Comment by cdecker** [comment]
Duplicates #5417
