### ISSUE TITLE
getpeers shows a port number which is different than what the peer's actual port number is

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#575]
Context : lnc0 is on 10000 and lnc1 is on 10001.      
Check the last command `lnc1 getpeers`. it says that `0246..` (lnc0) is on port 55426?  

`$ lnc0 getinfo`  
  `{ "id" : "0246afb72f5418e768d05c2f62073915c6439b3fde3c1fe4767714320bcc839b58", "port" : 10000, "address" : 
	[ 
		{ "type" : "ipv6", "address" : "2405:204:6095:33c0:3ded:cfa1:f769:4de6", "port" : 10000 } ], "version" : "v0.5.2-2016-11-21-1465-g72841056", "blockheight" : 808 }
`

`
$ lnc1 getinfo`
  `{ "id" : "0376466a30e400fdab561d01a8ab890eb59ab8257b9d4875c0060d10f6dbd7e144", "port" : 10001, "address" : 
	[ 
		{ "type" : "ipv6", "address" : "2405:204:6095:33c0:3ded:cfa1:f769:4de6", "port" : 10001 } ], "version" : "v0.5.2-2016-11-21-1465-g72841056", "blockheight" : 808 }
`

`
$ lnc0 connect 0376466a30e400fdab561d01a8ab890eb59ab8257b9d4875c0060d10f6dbd7e144 127.0.0.1:10001`
  `{ "id" : "0376466a30e400fdab561d01a8ab890eb59ab8257b9d4875c0060d10f6dbd7e144" }
`

`
$ lnc0 getpeers`
  `{ "peers" : 
	[ 
		{ "state" : "GOSSIPING", "peerid" : "0376466a30e400fdab561d01a8ab890eb59ab8257b9d4875c0060d10f6dbd7e144", "netaddr" : 
			[ "127.0.0.1:10001" ], "connected" : true, "owner" : "lightning_gossipd" } ] }
`

`
$ lnc1 getpeers`
  `{ "peers" : 
	[ 
		{ "state" : "GOSSIPING", "peerid" : "0246afb72f5418e768d05c2f62073915c6439b3fde3c1fe4767714320bcc839b58", "netaddr" : 
			[ "[::ffff:127.0.0.1]:55426" ], "connected" : true, "owner" : "lightning_gossipd" } ] }
`

**Comment by cdecker** [comment]
That is correct, on the outgoing side a random port is selected to communicate with the remote end. That port will never match the port the listening socket is bound to, since it is randomly selected from the high range 32k+, whereas services usually listen on the low range.

See https://en.wikipedia.org/wiki/Ephemeral_port for more information :wink: 

Closing for now, but feel free to reopen or continue discussing here

**Comment by Sgt-Miller** [comment]
Thank-you!
