### ISSUE TITLE
Error Upgrading database to new 22 release

### ISSUE THREAD

**Issue by CMDRZOD** [ElementsProject/lightning#5760]
Added --database-upgrade=true to my clightning run command to allow the new version to start. After doing this I get this output:

2022-11-30T20:08:04.605Z INFO    lightningd: Updating database from version 199 to 212
Converting channels.short_channel_id '607622x1712x0' gave 2 changes != 1?

After this clightning does not start. 
My node:
https://1ml.com/node/02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a/channels?order=newest

**Comment by rustyrussell** [comment]
OK, it's totally safe to downgrade for now (since db did NOT get updated!) while I look at this...

**Comment by CMDRZOD** [comment]
Yes I immediately went back to 12.1 without an issue.

**Comment by rustyrussell** [comment]
Hmm, OK, somehow your node has two channels with the same scid. That doesn't seem possible, but this is an ancient, closed channel.

I'll log at BROKEN level instead of aborting...

**Comment by CMDRZOD** [comment]
Thank you! Will wait for next release to try again.
