### ISSUE TITLE
`cln-rpc` broke semver in release 0.1.1?

### ISSUE THREAD

**Issue by dpc** [ElementsProject/lightning#5765]
Hello!

### Issue and Steps to Reproduce

Not a big deal, but just wanted to let you know that `cln-rpc` seems to be breaking semver by having by having backward-incompatible changes in a patch release, from what we can see in our CI: https://github.com/fedimint/fedimint/pull/932

**Comment by vincenzopalazzo** [comment]
Mh I do not think we follow some semi version rule :/

**Comment by cdecker** [comment]
We certainly strive for semantic versioning semantics for libraries, but we do reserve the magic version 0 semantics: 

> Magic zero
> But there is an exception for packages with major version equal to zero, e.g. 0.1.2.
> 
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

This is necessary since the libraries are very much in flux and restricting changes to only allow backwards compatible changes would result in a broken or experimental API being carried forward for a long time, while at the same time deferring changes that would be desirable.

**Comment by dpc** [comment]
It's really not a big deal, and I don't intend to give anyone a hard time about it, but purely because we are already talking about it - my understanding was that in Rust the "magic zero" would work for `0.0.x` but not in in `0.x.y`

From https://doc.rust-lang.org/cargo/reference/semver.html:

> This guide uses the terms "major" and "minor" assuming this relates to a "1.0.0" release or later. Initial development releases starting with "0.y.z" can treat changes in "y" as a major release, and "z" as a minor release. "0.0.z" releases are always major changes. This is because Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.

I don't know if that's a deviation from a original semver meaning on part of Rust community, etc. Just sharing what I know.

**Comment by cdecker** [comment]
Oh, I see, I must've misinterpreted the magic zero version, I thought it was referring to minor versions, not patch versions. Well, not much we can do about that now, we'll have to say `0.1.x` does not have any API guarantees, hopefully that high-flux phase ends pretty soon, and we have a stable API.

**Comment by dpc** [comment]
I don't think there's anything actionable here, so closing. If you need it open for some tracking purposes, feel free to reopen. Thanks!

**Comment by cdecker** [comment]
Thank you for catching this, always appreciated.
