### ISSUE TITLE
JSON-RPC should not require "jsonrpc" "2.0" in deprecated mode yet.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#5782]
https://github.com/ElementsProject/lightning/issues/5657#issuecomment-1336737325

Apparently BTCPayServer still wants this, so removal is premature.

**Comment by vincenzopalazzo** [comment]
Can someone point me to this in the BTCPayServer code where the call to cln wrapped happens? I think this required less than 2 line of code to fix it, maybe we can avoid reverting it?

cc @NicolasDorier

**Comment by NicolasDorier** [comment]
https://github.com/ElementsProject/lightning/pull/5783#issuecomment-1338501847
