### ISSUE TITLE
Add a new flag to keep IP announcement with DNS announce-addr

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#5795]
In Core lightning 0.10.2, if `announce-addr` was pointing to a DNS address, then clightning would resolve the DNS address and announce the IP address to P2P and in `getinfo` `.addresses`.

Since we bumped to 22.11, Core lightning isn't resolving the IP address. Instead it is using DNS announcement on P2P and `getinfo` `.addresses` show a dns entry.

This change completely broke most of our core lightning users (https://twitter.com/BtcpayServer/status/1600673006891982849)

Please add a flag to keep the old behavior. Until then, users who updated are kind of locked out of the network.

Because we use the `getinfo` `.addresses` to build the node info to show to BTCPay customers, and most customers don't have a wallet supporting the DNS name, then most can't connect to the merchant's node. (I think LND doesn't support it)

**Comment by rustyrussell** [comment]
Agreed. I didn't realize that people were using names in their configs, which caused a silent change when this happened (and more when it hit experimental).

**Comment by NicolasDorier** [comment]
Tested https://github.com/ElementsProject/lightning/pull/5796 and it works, can close this issue once merged.
