### ISSUE TITLE
Channel not auto closing (other node SCB'ed)

### ISSUE THREAD

**Issue by svewa** [ElementsProject/lightning#5818]
running v22.11rc3, ~230 channels

So this other node broke, and the owner used the SCB to recover his funds. My node noticed this, but didn't close the channel. Closing it manually seems to have worked now.

Partial listnodes output: 
```
"state_changes": [
                  {
                     "timestamp": "2022-02-18T12:37:04.689Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_NORMAL",
                     "cause": "user",
                     "message": "Lockin complete"
                  }
               ],
               "status": [
                  "CHANNELD_NORMAL:bad reestablish revocation_number: 0 vs 41393",
                  "CHANNELD_NORMAL:Sent reestablish, waiting for theirs"
               ],
```

**Comment by btweenthebars** [comment]
see here: https://github.com/ElementsProject/lightning/issues/5876

**Comment by whitslack** [comment]
This is the correct behavior. Your node should not force-close merely because of receiving an outdated `channel_reestablish`. It is the responsibility of the *other* node (the one that restored the SCB) to send an `error` message if it wants your node to force-close.

**Comment by rustyrussell** [comment]
Um, sure.  Meanwhile, he should be able to force it!
