### ISSUE TITLE
Abnormal CPU/IO Usage (thousands of Bad gossip order: WIRE_CHANNEL_UPDATE before announcement)

### ISSUE THREAD

**Issue by pldrouin** [ElementsProject/lightning#5826]
I have an issue since I opened a single channel on my node. lightningd and lightning-gossipd have been using an abnormal amount of CPU and IO it seems:

top - 00:31:48 up 11 min,  6 users,  load average: 1.04, 0.68, 0.48
Tasks: 175 total,   1 running, 174 sleeping,   0 stopped,   0 zombie
%Cpu(s): 29.0 us, 12.4 sy,  0.0 ni, 57.1 id,  0.9 wa,  0.0 hi,  0.7 si,  0.0 st
MiB Mem :   7862.9 total,     87.0 free,   1717.7 used,   6058.2 buff/cache
MiB Swap:   7872.0 total,   7872.0 free,      0.0 used.   6020.7 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                     
   1633 cln       20   0   71608  69236   5460 S  49.0   0.9   0:22.59 lightningd                                                                                                                                  
   1671 cln       20   0   20196  18856   3232 S  34.4   0.2   0:13.67 lightning_gossi                                                                                                                             
    747 bitcoin   20   0 3342684 633720 230944 S  13.2   7.9   1:36.80 bitcoind                                                                                                                                    

With debug information turned on,  I see thousands of lines like these in fast succession

Updated pending announce with update 759871x572x1/0
Received channel_announcement for channel 759871x1337x0

and lots of lines like these as well

Bad gossip order: WIRE_CHANNEL_UPDATE before announcement 766980x708x1/1
Bad gossip order: WIRE_CHANNEL_UPDATE before announcement 765702x318x0/0

What is going on here?
Thanks!

### `getinfo` output
{
   "id": "****************************************************************************************************",
   "alias": "*********",
   "color": "*********",
   "num_peers": 2,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": "****************************************************************.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      }
   ],
   "version": "v22.11-modded",
   "blockheight": 767533,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/opt/local/lightningd/bitcoin",
}

**Comment by grubles** [comment]
Are you using a low end device like a Raspberry Pi? Syncing the LN gossip data can take a while on devices like those.

**Comment by pldrouin** [comment]
> Are you using a low end device like a Raspberry Pi? Syncing the LN gossip data can take a while on devices like those.

I am using a RPI4 with 8 GB of RAM, SSD with UASP. So you are saying this can be all normal then? How long can this go on?

**Comment by grubles** [comment]
The RAM doesn't matter quite as much as the CPU cores. I believe `lightning_gossipd` is single threaded (correct me if I'm wrong), so the slow ARM core it's running on will take a while.

**Comment by grubles** [comment]
I think that's due to how `top` displays CPU usage per process. 40% on a 4-core CPU means it's using 100% of one core. If it were using all four cores simultaneously, `top` would display it as 400%.

As an example, here's a snapshot of CLN running on my 32-thread machine. `topology` (part of CLN) is definitely not using 68% of those 32-threads! It's only utilizing ~1 thread. 
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                
 407013 cln       20   0  726592 669120  38080 R  68.2   1.0 361:04.58 topology                                                                                                               
 407006 cln       20   0  341632 337792   7104 S  47.0   0.5 260:14.35 lightningd 
 ```

**Comment by grubles** [comment]
If you enable the visual CPU chart in `top`, you can see the individual threads being utilized.


![Screenshot from 2022-12-15 11-03-46](https://user-images.githubusercontent.com/7411154/207909129-3bd2f020-b475-4795-8420-676d50378f2b.png)

**Comment by pldrouin** [comment]
I was not referring to the CPU usage in the header, but at the process level

`top - 11:04:36 up 10:44,  7 users,  load average: 2.47, 2.37, 2.38
Tasks: 175 total,   1 running, 174 sleeping,   0 stopped,   0 zombie
%Cpu(s): 40.8 us, 12.1 sy,  0.0 ni, 45.3 id,  1.3 wa,  0.0 hi,  0.5 si,  0.0 st
MiB Mem :   7862.9 total,    105.1 free,   2002.7 used,   5755.1 buff/cache
MiB Swap:   7872.0 total,   7872.0 free,      0.0 used.   5735.9 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                     
1156646 bitcoin   20   0 4204832 645932 132336 S **107.6**   8.0  80:03.75 bitcoind                                                                                                                                    
1156815 cln       20   0  105844 101160   3176 S  **35.2**   1.3  67:20.26 lightningd                                                                                                                                  
1156818 cln       20   0   20508  12748   1504 S   **7.6**   0.2  12:06.89 bcli             `

**Comment by grubles** [comment]
Maybe your node is done syncing the gossip data? I would guess it's polling your `bitcoind` for data based on that snapshot. If you have debug logging enabled, you can get a good idea of what's happening.

**Comment by pldrouin** [comment]
Ok thanks. So should I expect syncing to last a while (multiple hours) as well if I restart the lightning process in the future, or is it only related to the fact that it is a new LN node?

**Comment by grubles** [comment]
No it should take much less time going forward. It will update itself continually while your CLN node is running, and when you stop your node and restart, it will update itself too. The greater Lightning Network is pretty large now, so it takes a little while at first. :-)

**Comment by pldrouin** [comment]
Ok thanks for your help and all the info, I am glad to hear that everything looks normal and should settle down! :D

**Comment by pldrouin** [comment]
Hmm. I just looked at the load in details using htop, and what I see is that bcli writes to the disk at 10 MB/s constantly. However the bitcoin data directory of CLN is using only 80 MB. What are all these write operations for if disk space use is so small? Is there a way to increase memory use to minimize disk IO?
