### ISSUE TITLE
Arm ci  cross build not run correctly.

### ISSUE THREAD

**Issue by arowser** [ElementsProject/lightning#5854]
### Issue and Steps to Reproduce

Its seems arm ci cross build not run correctly
https://github.com/ElementsProject/lightning/actions/runs/3771339418/jobs/6411745162#step:5:399

**Comment by vincenzopalazzo** [comment]
I'm afraid to ask but what is the reason for your assertion? I can understand why?

**Comment by arowser** [comment]
The ci should cross build with  arm-linux-gnueabihf-gcc, but the arm-linux-gnueabihf-gcc never be used in build.sh if you check the build logs.
In fact the ci build a x86 binary to test.
I try to fix it by #5855

**Comment by vincenzopalazzo** [comment]
Ok now it make sense, I suggest you to add some comments also in the PR because sometimes it is not easy to catch what you are trying to fix

**Comment by vincenzopalazzo** [comment]
I need to work on cross compiling stuff, so I will take a look

**Comment by vincenzopalazzo** [comment]
Closing this by the following assertion https://github.com/ElementsProject/lightning/pull/5855#issuecomment-1722874001

if it is not true please open it again :)
