### ISSUE TITLE
Update CLN via docker ends in warning:  "Refusing to irreversibly upgrade db" 

### ISSUE THREAD

**Issue by cryptoteun** [ElementsProject/lightning#5870]
### Issue and Steps to Reproduce

I run CLN in Docker. I wanted to upgrade CLN from docker image v0.12.1 to v22.11.1. The versions published on Docker hub.

But when starting the container with the new image i get the following error:

> Refusing to irreversibly upgrade db from version 199 to 212 in non-final version v22.11.1 
> (use --database-upgrade=true to override) 

I understand the workaround, but I guess there is some check wrong after the new semver ?

**Comment by vincenzopalazzo** [comment]
Yeah, this should work well with the tagger release, let's try to fix this for the next release, thank you for reporting!
