### ISSUE TITLE
Feature request: use HashMap instead of Vector in Plugin

### ISSUE THREAD

**Issue by evd0kim** [ElementsProject/lightning#5873]
Vector seems to be really inconvenient when plugin needs to get an access to a specific parameter.

So instead
```Rust
#[derive(Clone)]
pub struct Plugin<S>
where
    S: Clone + Send,
{
    /// The state gets cloned for each request
    state: S,
    /// "options" field of "init" message sent by cln
    options: Vec<ConfigOption>,
    /// "configuration" field of "init" message sent by cln
    configuration: Configuration,
    /// A signal that allows us to wait on the plugin's shutdown.
    wait_handle: tokio::sync::broadcast::Sender<()>,

    sender: tokio::sync::mpsc::Sender<serde_json::Value>,
}
```

it might be

```Rust
#[derive(Clone)]
pub struct Plugin<S>
where
    S: Clone + Send,
{
    /// The state gets cloned for each request
    state: S,
    /// "options" field of "init" message sent by cln
    options: HashMap<String, ConfigOption>,
    /// "configuration" field of "init" message sent by cln
    configuration: Configuration,
    /// A signal that allows us to wait on the plugin's shutdown.
    wait_handle: tokio::sync::broadcast::Sender<()>,

    sender: tokio::sync::mpsc::Sender<serde_json::Value>,
}
```

**Comment by vincenzopalazzo** [comment]
it is possible access to the plugin with the following code

```rust
let opt = plugin.option("name_option");
```

but I agree it is possible use the hash map and avoid to run the linear search inside the vector

**Comment by cdecker** [comment]
As pointed out in #5886 we are unlikely to benefit from using a `HashMap`: for the small number of options plugins typically expose (<50) the constant overhead of a `HashMap` (both memory-wise and performance-wise) will likely overshadow the asymptotic performance.

Which structure we use should mostly be an implementation detail, and we should expose everything that is needed through accessors as @vincenzopalazzo points out, allowing us to swap should a microbenchmark point out that there is a better structure.
