### ISSUE TITLE
macos poetry run make freezing?

### ISSUE THREAD

**Issue by mdance** [ElementsProject/lightning#5888]
### Issue and Steps to Reproduce
On the latest version of macos, when I attempt to run poetry run make it seems to be hanging at:

md2man doc/reckless.7.md
genidx doc/index.rst
(cd plugins; cargo build --quiet --examples)

If I hit cntr+c, and manually cd plugins; cargo build --examples, I'm seeing:

    Updating crates.io index
error: failed to select a version for the requirement `env_logger = "^0.10"`
candidate versions found which didn't match: 0.9.3, 0.9.2, 0.9.1, ...
location searched: crates.io index
required by package `cln-rpc v0.1.2 (/Users/md/Projects/bitcoin/lightning/cln-rpc)`

**Comment by cdecker** [comment]
Interesting, according to crates.io 0.10 should be available: https://crates.io/crates/env_logger/versions


I'll try to reproduce 👍

**Comment by mdance** [comment]
I resolved it by running rustup update

**Comment by vincenzopalazzo** [comment]
Closing as resolved
