### ISSUE TITLE
Assertion when automatically closing channel

### ISSUE THREAD

**Issue by tdaede** [ElementsProject/lightning#59]
On both sides:

```
lightningd: daemon/peer.c:165: bitcoin_commit: Assertion `!peer->local.commit->tx->input[0].witness' failed.
lightningd(29329): FATAL SIGNAL 6 RECEIVED
Fatal signal 6. Log dumped in crash.log
Aborted (core dumped)
```

035f opened the channel.
[crash_segwit_035f.txt](https://github.com/ElementsProject/lightning/files/555042/crash_segwit_035f.txt)
[crash_segwit_0218.txt](https://github.com/ElementsProject/lightning/files/555046/crash_segwit_0218.txt)

**Comment by rustyrussell** [comment]
Thanks for the report!  OK, here's what happened.  The fee prediction went below the fee rate for the
current commitment transaction, so we freaked out and dumped to chain.  This is an issue with testnet, which should probably be disabled there, but it leads us to an interesting place!

So, we dump to chain, but seems like they do too (and they win).  Anyway, next block, we hit the same "fee rate too low" issue and try to re-broadcast our commitment tx, and BOOM.

The fee-too-low check should be (1) disabled for testnet, and (2) never fire twice.  I'll fix those now!
