### ISSUE TITLE
Delay closing to give peer a chance for errors / peer-backup-restore

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#5903]
connectd should continue to receive messages for, say, 5 seconds after sending an error.  This gives a chance for them to send an error, or WIRE_YOUR_PEER_BACKUP.

**Comment by vincenzopalazzo** [comment]
Mh wondering if this will impact the lnprototest at some point

**Comment by rustyrussell** [comment]
We chose a different solution here: send the messages before the reestablish, which is even better.
