### ISSUE TITLE
Cannot use `scid_alias` for unannounced channels that aren't zero-conf

### ISSUE THREAD

**Issue by t-bast** [ElementsProject/lightning#5908]
It looks like `cln` rejects unannounced channels that are using `scid_alias` without `zero_conf`.
I don't see a compelling reason for that, `scid_alias` is really useful outside of `zero_conf`?

I believe it simply needs to be added to the variants here: https://github.com/ElementsProject/lightning/blob/82c94330a55d5925d802df86d43bf44e779d2738/common/channel_type.c#L126

But I may be missing side-effects this would have elsewhere in the codebase...

**Comment by TonyGiorgio** [comment]
I'm also seeing this issue when opening a channel from an LDK node to CLN while using `scid_alias` without `zero_conf`.

**Comment by rustyrussell** [comment]
Indeed!

This should be fixed by https://github.com/ElementsProject/lightning/pull/6136 which is merged for the pending release.
