### ISSUE TITLE
Rebalance between channels same peer bug?

### ISSUE THREAD

**Issue by Coinomatron** [ElementsProject/lightning#5923]
I have 2 channels with the same peer. When I rebalance between them, the cli reports a successful transfer and a (low) fee taken, but there is no change to the balances of either channel. The peer runs LND.

**Comment by devastgh** [comment]
You cannot do that. So it's pointless to even try. You cannot specify which channel your peer use for the next hop, only the next nodeid is specified, the peer if free to use any channels he has with that node. This is not a bug, it is simply how this works.

**Comment by Coinomatron** [comment]
But it's two separate channels id's, what does it matter if it's to the same peer? And why does it report a succesful rebalance? Anyway, since it's not really important, closing the issue.
