### ISSUE TITLE
make can raise `bin/sh: line 1: 1.2.md: No such file or directory`

### ISSUE THREAD

**Issue by m-schmoock** [ElementsProject/lightning#5941]
### Issue and Steps to Reproduce
At least on some systems, calling `make` can raise an shell error `bin/sh: line 1: 1.2.md: No such file or directory`
This seems to be caused by `doc/Makefile` line 215 which has been brought in by 744d111 in early December 2022.

```make
doc/index.rst: $(MANPAGES:=.md)
	@$(call VERBOSE, "genidx $@", \
	  find doc -maxdepth 1 -name '*\.[0-9]\.md' | \
	  cut -b 5- | LC_ALL=C sort | \
	  sed 's/\(.*\)\.\(.*\).*\.md/\1 <\1.\2.md>/' | \
	  python3 devtools/blockreplace.py doc/index.rst manpages --language=rst --indent "   " \
	)
```

### make output
```shell
LD: cc     config.vars  -Lexternal/x86_64-pc-linux-gnu -lwallycore -lsecp256k1 -ljsmn -lbacktrace -lsodium -L/usr/local/include -lm -lgmp -lsqlite3  -lz  -L/usr/lib -lpq -o
/bin/sh: line 1: 1.2.md: No such file or directory
```

Sometimes (maybe because of parallel compiling) this error is not at the end of the output but a couple of lines before.

**Comment by rustyrussell** [comment]
Ack https://github.com/m-schmoock/lightning/commit/7a8de76603f813a1554043330fcc8d87c403ed02
