### ISSUE TITLE
Feature request: Ability to revoke runes with commando

### ISSUE THREAD

**Issue by Semisol** [ElementsProject/lightning#5962]
Since each rune has an ID according to the docs, a node can maintain a list of all revoked IDs and check against that, which is useful if a rune is compromised or you do not want to allow it anymore.

**Comment by rustyrussell** [comment]
This was implemented in #6124 BTW!

**Comment by Elmago34** [comment]
> Since each rune has an ID according to the docs, a node can maintain a list of all revoked IDs and check against that, which is useful if a rune is compromised or you do not want to allow it anymore.
