### ISSUE TITLE
listpeerchannels is an "unknown command"

### ISSUE THREAD

**Issue by BTCBellyButton** [ElementsProject/lightning#5982]
### Issue and Steps to Reproduce

lightning-cli listpeerchannels
{
   "code": -32601,
   "message": "Unknown command 'listpeerchannels'"

### Running version:
v22.11.1

Not sure if I am doing something wrong, it's a deprecated command, or not yet released. 
Not clear from the doc page: https://lightning.readthedocs.io/lightning-listpeerchannels.7.html even if the note "_deprecated, removal in v23.05_" for **local_msat** makes you think it should be an available command in the current release...

:question:

**Comment by vincenzopalazzo** [comment]
Ops we introduce it inside the upcoming release, version v23.02. You are lucky, we had an rc1 version just tagged a couple of hours a go, maybe you can give it a try?

>Not sure if I am doing something wrong, it's a deprecated command, or not yet released.
 
The only things wrong here are that our docs are based on top of maser, and you are not running the master version :) sorry about that

**Comment by BTCBellyButton** [comment]
All Cool! Maybe just add a line with the note "coming soon!".

No problem. I kind of figured it out.  :D
