### ISSUE TITLE
Unable to connect to node "Blockstream Store" after upgrading to v23.02rc3

### ISSUE THREAD

**Issue by hMsats** [ElementsProject/lightning#6024]
### Issue and Steps to Reproduce

After upgrading from v22 to v23.02rc3, I'm no longer able to connect to node "Blockstream Store" (02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f) and 2 others (Europe-Lightning-Hub.eu, DeutscheBank|CLN) which I believe are all older versions of Core Lightning. With all these nodes I have a channel and no problems before the upgrade. Other lightning implementations seem to be working fine (17 nodes in total). The `connect` command appears to be working correctly: 

```
lightning-cli connect 02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f
{
   "id": "02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f",
   "features": "08a000080a69a2",
   "direction": "out",
   "address": {
      "type": "ipv4",
      "address": "35.232.170.67",
      "port": 9735
   }
}
```
but no real connection is established (part of `listpeers`):
```
{
   "peers": [
      {
         "id": "02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f",
         "connected": false,
```

**EDIT:** found this in the output:
```
2023-02-18T10:00:43.206Z INFO    02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f-chan#49332: Peer transient failure in CHANNELD_NORMAL: Disconnected
2023-02-18T10:00:43.253Z INFO    02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f-channeld-chan#49332: Peer connection lost
2023-02-18T10:00:43.253Z INFO    02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f-chan#49332: Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (62208)
2023-02-18T10:00:43.253Z INFO    02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f-connectd: Received WIRE_WARNING: warning: Feature 28 requires feature 20

```
also note that I run with 
```
experimental-dual-fund
experimental-offers
```

### `getinfo` output
```
{
   "id": "02888244029c5909593038ab19f269947c720de3423e491791b46c7c92f76279b6",
   "alias": "bitcoinserver.nl",
   "color": "028882",
   "num_peers": 16,
   "num_pending_channels": 0,
   "num_active_channels": 20,
   "num_inactive_channels": 1,
   "address": [
      {
         "type": "ipv4",
         "address": "83.81.143.79",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "2bh7psr4dinasuz3d6jm5o56ebkmlnotqqptoesikzvsyqxwmaneyiad.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "192.168.178.20",
         "port": 9735
      }
   ],
   "version": "v23.02rc3",
   "blockheight": 777157,
   "network": "bitcoin",
   "msatoshi_fees_collected": 450252745,
   "fees_collected_msat": "450252745msat",
   "lightning-dir": "/media/ssd/.lightning/bitcoin",
   "our_features": {
      "init": "08a0802a0269a2",
      "node": "88a0802a0269a2",
      "channel": "",
      "invoice": "02000022024100"
   }
}
```

**Comment by cdecker** [comment]
The disconnect seems to be on the remote end, hopefully we get a warning at least? Can you set `--log-level=io` and store the logs? That way we see what messages are exchanged.

**Comment by hMsats** [comment]
Thanks for the fast response! You can find the (enormous amount of) output [here](https://bitcoinserver.nl/out.txt).

**Comment by endothermicdev** [comment]
There was a breaking change in the dual-funding spec and CLN 23.02rc3 has updated to reflect it.  It looks like the remote node is complaining that you don't have feature bit 20 `option_anchor_outputs` set (no longer required by dual-funding) which it thinks you should need.  Options are to disable dual funding, or to reenable bit 20.  Because it's a breaking change there's going to be some issues until old CLN experimental nodes update to match to current spec.

**Comment by hMsats** [comment]
Yes, turning off `experimental-dual-fund` solved the problem! I only used it once to test it but normally I don't because it's now possible to open more than one channel to the same node. You developers can decide to close this issue or keep it open to solve it in some clever way. THANKS TO ALL!

**Comment by vincenzopalazzo** [comment]
Thank @endothermicdev I think this is just a network settlement problem, when most of the peer will upgrade, this error will be gone!

Closing it as answered

**Comment by PsySc0rpi0n** [comment]
I have the same issue and even after commenting the `enable-dual-funding` option in config, I still can't connect to @vincenzopalazzo node. I see messages like this in the logs:


```
2023-02-19T22:59:17.234Z DEBUG03e2408a49f07d2f4083a47344138ef89e7617e63919202c92aa8d49b574a560ae-connectd: Connect OUT
53639 2023-02-19T22:59:17.235Z DEBUG   03e2408a49f07d2f4083a47344138ef89e7617e63919202c92aa8d49b574a560ae-connectd: peer_out WIRE_INIT
53640 2023-02-19T22:59:17.892Z DEBUG   03e2408a49f07d2f4083a47344138ef89e7617e63919202c92aa8d49b574a560ae-connectd: peer_in WIRE_INIT
53641 2023-02-19T22:59:17.893Z DEBUG   03e2408a49f07d2f4083a47344138ef89e7617e63919202c92aa8d49b574a560ae-gossipd: seeker: disabling gossip
53642 2023-02-19T22:59:17.893Z INFO    03e2408a49f07d2f4083a47344138ef89e7617e63919202c92aa8d49b574a560ae-chan#83: Peer transient failure in CHANNELD_NORMAL: Disconnected
53643 2023-02-19T22:59:17.893Z DEBUG   03e2408a49f07d2f4083a47344138ef89e7617e63919202c92aa8d49b574a560ae-lightningd: Peer says it sees our address as: 79.137.202.181:19475
```

**Comment by vincenzopalazzo** [comment]
Your is an unrelated problem, from my logs 

```
2023-02-20T09:34:37.757Z INFO    03fef777d58a529df02a3fb267690e0c9033767b555cc1c63844bb2d3498789f91-chan#263: Peer transient failure in CHANNELD_NORMAL: Disconnected
2023-02-20T09:34:41.775Z INFO    03fef777d58a529df02a3fb267690e0c9033767b555cc1c63844bb2d3498789f91-chan#263: Peer transient failure in CHANNELD_NORMAL: channeld WARNING: update_fee 5796 outside range 253-2278 (currently 5513)
```

**Comment by PsySc0rpi0n** [comment]
> 

Yes but I also saw that same message for other channels I had offline after upgrading to v23.11.1 and before disabling experimental-dualfund...
So, it might be related at least! I just know that our channel is offline 90% of the time! It doesn't happen with any other peer. I already restarted Tor and still no improvement!

**Comment by chrisguida** [comment]
I'm having this problem as well, on the official 23.02 release. Is this just an interoperability issue between v22 and v23? I need dual funding to work :/

**Comment by endothermicdev** [comment]
Did you compile with --enable-experimental-features (i.e., ./configure --enable-experimental-features)?  In order to upset a <=v22.11 CLN node, I think you would have to compile _without_ experimental features enabled, but then still set the dual funding flag (manually or in your config.)  If you compiled with experimental features and set the experimental-dual-fund flag, you should still be able to connect to older nodes.

**Comment by chrisguida** [comment]
Interesting, no, I've never needed to compile with that flag, is that new in v23?

Here's the current `configure` call:

`./configure --enable-static --disable-readline --disable-threadsafe --disable-load-extension`

**Comment by chrisguida** [comment]
Pulled that straight from the official Dockerfile:

https://github.com/ElementsProject/lightning/blob/master/Dockerfile#L85

**Comment by btweenthebars** [comment]
am on v22.11.1 compiled with EXPERIMENTAL_FEATURES=0. I have disabled all the experimental features including dualfund, but I'm still seeing "Feature 28 requires feature 20" on 4 peers. I ran out of ideas to make these channels work

**Comment by chrisguida** [comment]
@btweenthebars it's probably your peers that have the issue. this issue did not present for me on v22.

**Comment by btweenthebars** [comment]
I think it affects every channels that opened with DUALOPEND whether they are liquidity ads purchase or not. Is this consider a bug to be addressed or a pressure to motivate people to upgrade ?

**Comment by chrisguida** [comment]
It seems that dual funding has been moved behind a build flag for a reason I cannot understand. I don't know why this was done or what will be done about it, if anything. AFAICT the fix is for all your dual funding peers to rebuild with the aforementioned build flag.

**Comment by PsySc0rpi0n** [comment]
> There was a breaking change in the dual-funding spec and CLN 23.02rc3 has updated to reflect it. It looks like the remote node is complaining that you don't have feature bit 20 `option_anchor_outputs` set (no longer required by dual-funding) which it thinks you should need. Options are to disable dual funding, or to reenable bit 20. Because it's a breaking change there's going to be some issues until old CLN experimental nodes update to match to current spec.

What if this happens with LND nodes? I have at least one such case!
