### ISSUE TITLE
option to allow high fees for particular node ids

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#6030]
This would allow workarounds to #6028 and the ongoing "I can't maintain a channel with ACINQ" problem.  We have --ignore-fee-limits but that's a big, dangerous hammer!

**Comment by devastgh** [comment]
I think the elegant solution would be implementing #5770 ? I was told this would fix the fee mismatch issues.

**Comment by rustyrussell** [comment]
Closed-by: #6398
