### ISSUE TITLE
Commando cmd format

### ISSUE THREAD

**Issue by d4amenace** [ElementsProject/lightning#6044]
I have been trying to properly setup a commando call with multiple paramaters and nothing seems to work.

`lightning-cli commando peer_id=03995d1e174654654165416651456dajfkajojfdaf5494036e3490ac3aab3fe43d9 "method=invoice" [params="100" : "hjdfohdh" : "iuiu"] rune=zThVwe0rMNIsjljfdkkdjkjdjjdkjjd____lkdnVtPDY= `

Can someone tell me what is the proper format for this?  It seems the error is in the setup for multiple parameters......

**Comment by vincenzopalazzo** [comment]
The params is a json object, and also you had used the wrong syntax

try to use the following one `"params": { "amount_msat": 100, ... }`

**Comment by d4amenace** [comment]
```
root@rn_one:/# lightning-cli commando peer_id=0463565365365365368a43feed9417dc5c85a5939f7036e3490ac3aab3fe43d9 "method=invoice" "params": { "amount_msat" : 1000, "label" : iuiu} rune=zThVwe0rMNI1DNaVzrqagtreqtreqtreqtrqEcQ9MSZwbnVtPDY=  -k
lightning-cli: Expected key=value in 'params:': Success
```

no luck

**Comment by vincenzopalazzo** [comment]
Sorry I put the wrong json payload, I modified the previous comment.

However, now core lightning sends you a more precise message regarding the params options, you can see all the options supported by running `lightning-cli --help`

```
-H|--human-readable       Human-readable output
-F|--flat                 Flatten output ('x.y.x=' format)
-J|--json                 JSON output (default unless 'help')
-R|--raw                  Raw, unformatted JSON output
-k|--keywords             Use format key=value for <params>
-o|--order                Use params in order for <params>
-N|--notifications <arg>  Set notification level, or none (default: info)
-l|--filter <arg>         Set JSON reply filter (default: (nil))
-c|--commando <arg>       Send this as a commando command to nodeid:rune
```

Another error is with `"method=invoice"` this should be `method=invoice`, this required several iterations, if you want just a copy and paste solution I should jump on my node and experiment a little bit with your previous command

**Comment by d4amenace** [comment]
```
# lightning-cli commando peer_id=03995462546bn52nb652bn43feed9417dc5c85a5939f7036e3490ac3aab3fe43d9 method=invoice params="{ \"amount_msat\": 1000, \"label\": ajdkjalj }" rune=zThVwe0rMNI1DN15b1b1b1345b14PBbjNk5EcQ9MSZwbnVtPDY= 
lightning-cli: Some parameters are malformed, cannot create a valid JSON-RPC request: { "jsonrpc" : "2.0", "method" : "commando", "id" : "lightning-cli-286", "params" :{ "peer_id" : "03995d1e15b151b41b541bf7036e3490ac3aab3fe43d9", "method" : "invoice", "params" : { "amount_msat": 1000, "label": ajdkjalj }, "rune" : "zThVwe0rMNI1DNaV15b4151bcQ9MSZwbnVtPDY="} }

```

**Comment by d4amenace** [comment]
```
root@rn_one:/# lightning-cli commando 039947923788478372843879a8a43feed9417dc5c85a5939f7036e3490ac3aab3fe43d9 invoice [100] zThVwe0rMNI1DNaVzrgfsgfsgPBbjNk5EcQ9MSZwbnVtPDY= 
{
   "code": -32602,
   "message": "missing required parameter: label"
}

```

I got this far but I can't add the second flag.

**Comment by vincenzopalazzo** [comment]
the label  is a string, that contains a JSON object, so:

- `[100]`: this is no a string and not a json object, better this way "{ key: value }"
-  `ajdkjalj`: this is not a valid type in json, but `"ajdkjalj"` it is.

**Comment by d4amenace** [comment]
Thanks.  I would have never figured that out... Not good at JSON layout.
