### ISSUE TITLE
initial_commit_tx can create a 0-output tx without errors

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#605]
Currently [initial_commit_tx](https://github.com/ElementsProject/lightning/blob/4214c5ad57bbf7b632be5ee780824ca4e7acdeec/common/initial_commit_tx.c#L57) can create a zero output transaction without errors.

This can happen if both of these conditions fail:

https://github.com/ElementsProject/lightning/blob/4214c5ad57bbf7b632be5ee780824ca4e7acdeec/common/initial_commit_tx.c#L125

https://github.com/ElementsProject/lightning/blob/4214c5ad57bbf7b632be5ee780824ca4e7acdeec/common/initial_commit_tx.c#L138

This is an invalid transaction, so we should be reporting an error here.

**Comment by rustyrussell** [comment]
This was fixed in 21fbae6df8d10e846d0afaa3c79beeef9d9ae5ce: "openingd: ensure that initial channel can cover fees and reserve."
