### ISSUE TITLE
autoclean does not remove local_failed

### ISSUE THREAD

**Issue by denis2342** [ElementsProject/lightning#6058]
I used the autoclean command to remove some old failed forwards and the documentation says it also cleans local_failed. But I still have 800000 local_failed which are older than the seconds option I gave to autoclean.

**Comment by vincenzopalazzo** [comment]
what version of cln are you using?

**Comment by denis2342** [comment]
oh, v23.02

**Comment by vincenzopalazzo** [comment]
Nice thanks!

Can you also publish your autoclean config (if any)? I will try to reproduce on my system.

**Comment by denis2342** [comment]
I used "lightning-cli autoclean-once failedforwards 604800"

**Comment by denis2342** [comment]
this is my DB (to make sure I reported here correct):

```
clightning=# select state, count(*) from forwards group by state;
 state | count  
-------+--------
     0 |      1
     1 |   1353
     2 |  34293
     3 | 843588
(4 rows)

```

**Comment by denis2342** [comment]
in plugins/autoclean.c in function listforwards_done() there is a check for resolved_time. But I can't see such an entry in any of the local_failed forwards. with this entry missing num_uncleaned is increased and the loop is continued without cleaning anything.
