### ISSUE TITLE
How to pass params to bcli plugin through config file

### ISSUE THREAD

**Issue by Yihen-Liu** [ElementsProject/lightning#6105]
### Issue and Steps to Reproduce

1. I start bitcoind successed with command as follow:
 /path/to/bitcoin/workspace/bitcoind -conf=/path/to/bitcoin/workspace/conf/bitcoin.conf

2. I have aliase bitcoin-cli to '/path/to/bitcoin/workspace/bitcoin-cli -conf=/path/to/bitcoin/workspace/conf/bitcoin.conf'

3. core-lightning config file as follow:
```
network=regtest
log-level=debug
log-file=/path/to/core-lightning/workspace/data/l1-regtest/log
addr=localhost:7171
allow-deprecated-apis=false
plugin=/path/to/core-lightning/workspace/plugins/bcli
```

4. bitcoind config file as follow:
 ```
regtest=1
daemon=1
dnsseed=0
upnp=0

# always run a server, even with bitcoin-qt
server=1
rpcallowip=0.0.0.0/0
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28333
zmqpubrawblock=tcp://127.0.0.1:28335
# add by Rivers
zmqpubrawtx2=tcp://127.0.0.1:28334

whitelist=0.0.0.0/0
txindex=1
addressindex=1
timestampindex=1
spentindex=1
uacomment=bitcore
rpcworkqueue=128
dbcache=16384

rpcuser=user
rpcpassword=password

datadir=/path/to/bitcoin/workspace/data

fallbackfee=0.0002

#https://bitcoin.stackexchange.com/questions/66892/what-are-the-debug-categories
debug=1
logthreadnames=1
debugexclude=tor
# listen on different ports than default testnet
[regtest]
rpcbind=127.0.0.1
port=19000
rpcport=18443
```

5. start core-lightning as follow：
/path/to/to/lightning/workspace/lightningd --lightning-dir=/path/to/lightning/workspace/data/l1-regtest
### `getinfo` output
Could not connect to bitcoind using bitcoin-cli. Is bitcoind running?

Make sure you have bitcoind running and that bitcoin-cli is able to connect to bitcoind.

You can verify that your Bitcoin Core installation is ready for use by running:

    $ bitcoin-cli -regtest echo 'hello world'

In my opinion, The reason is that I don't pass correct param to bitcoin-cli though bcli plug.  who can tell me how to pass param to bitcoin-cli through bcli plug.

I am a new CLN user. please help me.

**Comment by vincenzopalazzo** [comment]
This is odd

>plugin=/path/to/core-lightning/workspace/plugins/bcli

How do you run bitcoind? Have you put the `--regtest` in front of `bitcoind`?

**Comment by Yihen-Liu** [comment]
@vincenzopalazzo  Yes,  I set regtest=1 in the bitcoin.conf;

**Comment by Yihen-Liu** [comment]
when I setup the lightningd in source code dir, it works well.
