### ISSUE TITLE
`fetchinvoice` RPC Error -  quantity parameter required

### ISSUE THREAD

**Issue by aaronbarnardsound** [ElementsProject/lightning#6116]
### Issue and Steps to Reproduce
The `fetchinvoice` RPC does not seem to accept the `quantity` parameter:

`lightning-cli fetchinvoice -k offer='lno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrcgqffqszsx2a5kgem9wsfqxctnvs2qzpqkyypn7jale4nm6r7gtpyej2dry4wsvwveac3lf30p9w93pz0px2e7gzq' quantity=2`

```json
{
   "code": -32602,
   "message": "quantity parameter required"
}
```

### `getinfo` output

```json
{
   "id": "037196806b4a00b5035db861f70a42e2d90e3900757403b183a81e4c35154389e8",
   "alias": "dave",
   "color": "037196",
   "num_peers": 4,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "dns",
         "address": "dave",
         "port": 19846
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "172.23.0.6",
         "port": 19846
      }
   ],
   "version": "v22.11-modded",
   "blockheight": 157,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/clightning/.lightning/regtest",
   "our_features": {
      "init": "08a0800a0269a2",
      "node": "88a0800a0269a2",
      "channel": "",
      "invoice": "02000002024100"
   }
}
```

** Edited

**Comment by vincenzopalazzo** [comment]
what version are you running?

I able to generate it 

```
➜  VincentSSD clightning --testnet invoicerequest -k amount=21 description='Have some sats' label='21 gift'                                                                                
{
   "invreq_id": "ba6d9139a11c20012b1a52adae07b74b11827c55fcf43448c55f0952721c6971",
   "active": true,
   "single_use": true,
   "bolt12": "lnr1qqgr9c0u3cu599vwlge9ttejry0g7zswfpshvefqwdhk6efqwdshgu6sypp5jl7hlqnf2ugg7j3slkwwcwht57vhyzzwjr4dq84rxzgqqqqqq5spz4vzzqann5wa7y7wfpk7wn57gns98rukqsq6nmr42d96nnlyzqxk2sngsrcyq9qpftjm3xfw9s6a7d8hnncwtvpnmgg0th2ygn8gw5ackwapr3zaqtht2dwr4ejgpl9ny6v5krwcrfzqldvu8p35cnasyvve0tt2qqzs",
   "used": false,
   "label": "21 gift"
}
```

based on commit 906279a46e6b795f61056abb8a5e19d83cd3774b

**Comment by aaronbarnardsound** [comment]
@vincenzopalazzo Sorry I updated the issue. I got confused and created an issue for the `label` which I had already created and issue for and you had already created a fix! So the issue is with the `fetchinvoice` rpc and the `quantity` param.

**Comment by vincenzopalazzo** [comment]
Are you ranning cln with this patch https://github.com/ElementsProject/lightning/pull/6090 ?

This error looks pretty odd we are testing this case

**Comment by vincenzopalazzo** [comment]
Ah no you are not `"version": "v22.11-modded"`

**Comment by aaronbarnardsound** [comment]
Ok looks like I already created an issue for this one! Closing this as it was already fixed on the [original issue](https://github.com/ElementsProject/lightning/issues/6089)
