### ISSUE TITLE
fundchannel with feerate=urgent leads to transaction getting stuck in mempool

### ISSUE THREAD

**Issue by lightningorb** [ElementsProject/lightning#6129]
`fundchannel` with a feerate set to 'urgent' leads to 5 sat/vb which, given the current state of the mempool leads to the transaction getting stuck in the mempool.

It seems these:

- `slow`
- `normal`
- `urgent`

feerate values are not being calculated properly given the current state of the mempool. The documentation states that `urgent (aim for next block)` which is not the case.

**Comment by lightningorb** [comment]
Also the documentation for setting the feerate manually is not clear:

```
Otherwise, feerate is a number, with an optional suffix: perkw means the number is interpreted as satoshi-per-kilosipa (weight), and perkb means it is interpreted bitcoind-style as satoshi-per-kilobyte. Omitting the suffix is equivalent to perkb.
```

It's not straightforward translating sat per vb from mempool.space into `fundchannel` feerate values. Could you please provide some examples.

**Comment by lightningorb** [comment]
Example this is a batch open performed with feerate=urgent

![image](https://user-images.githubusercontent.com/24770400/227883632-0e21b538-7ffb-447e-bcf4-39f2e41ad25b.png)

**Comment by rustyrussell** [comment]
> `fundchannel` with a feerate set to 'urgent' leads to 5 sat/vb which, given the current state of the mempool leads to the transaction getting stuck in the mempool.
> 
> It seems these:
> 
>     * `slow`
> 
>     * `normal`
> 
>     * `urgent`
> 
> 
> feerate values are not being calculated properly given the current state of the mempool. The documentation states that `urgent (aim for next block)` which is not the case.

Indeed, it's actually using the 6 block estimate for "urgent".    This was an accidental side-effect of lowering fee estimates for v0.10.1! :grimacing: 

The next release allows "2blocks" so you can control this more sanely, and I will fix the documentation for "urgent" to be correct.  I'll also add docs about pervB -> perkb!
