### ISSUE TITLE
Unable to connect to node on Tor or Clearnet - Old Node

### ISSUE THREAD

**Issue by CMDRZOD** [ElementsProject/lightning#6132]
I have an older node. I moved and am now on an ISP which uses CGNAT. I have been attempting to make my node reachable over IPv6 to bypass Tor. Since attempting to get IPv6 working my node is now unreachable with either method.

This is the error I (and others using core lightning) recieve:

For Tor:

`hair@ddk:~/.lightning$ lightning-cli connect 02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a@odyrmuri4auq5qrb2qpa6l2svuxmiqyeqtvycyr2u5s5veekru4qkiad.onion:9735
{
   "code": 401,
   "message": "All addresses failed: odyrmuri4auq5qrb2qpa6l2svuxmiqyeqtvycyr2u5s5veekru4qkiad.onion:9735: Exchanging init messages: Operation now in progress. "
}`

IPv6:
`lightning-cli connect 02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a@[2605:59c8:673:ff00:2efd:a1ff:fedc:f8d4]:9735
{
   "code": 401,
   "message": "All addresses failed: [2605:59c8:673:ff00:2efd:a1ff:fedc:f8d4]:9735: Connection establishment: Connection refused. "
}`

My friend running a CLN node was able to connect to mine successfully, however his c-lightning node got the same error as above.

I know ports are open, I have used nmap and see c-lightning watching port 9735. getinfo output:
{                                                                                                                                                              
[1/19191]   
"id": "02a20247f515d978cbf9e9ce6a4287b5931d724068b7b88bbaead6380db3dd8e9a",                                                                                             "alias": "Nasty_Nardo",
   "color": "095821",
   "num_peers": 217,
   "num_pending_channels": 0,
   "num_active_channels": 211,
   "num_inactive_channels": 8,
   "address": [
      {
         "type": "ipv6",
         "address": "2605:59c8:673:ff00:2efd:a1ff:fedc:f8d4",                                                                                                                    "port": 9375
      },
      {
         "type": "torv3",
         "address": "odyrmuri4auq5qrb2qpa6l2svuxmiqyeqtvycyr2u5s5veekru4qkiad.onion",                                                                                            "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      },
      {
         "type": "ipv6",
         "address": "2605:59c8:673:ff00:2efd:a1ff:fedc:f8d4",                                                                                                                    "port": 9375
      }
   ],
   "version": "23.02.2",
   "blockheight": 783033,
   "network": "bitcoin",
   "msatoshi_fees_collected": 750548244,
   "fees_collected_msat": "750548244msat",
   "lightning-dir": "/home/hair/.lightning/bitcoin",
   "our_features": {
      "init": "08a000280269a2",
      "node": "88a000280269a2",
      "channel": "",
      "invoice": "02000020024100"
   }
} 

Really at my wits end for what the issue could be.

I currently have a few other IPv6 services running on this machine, all reachable from outside my LAN. Any hints as to what is going on with my node would be appreciated.

**Comment by CMDRZOD** [comment]
Just to be clear, this node can connect to Tor and IPv6 nodes but for whatever reason will not allow incoming connections on either.

**Comment by psychoet** [comment]
To be a bit more accurate on the following statement, I am running both LND (v0.15.5-beta, Tor only) and CLN (v22.11.1, IPv4 clearnet + Tor hybrid), and only LND node can connect to @CMDRZOD's node.

> "My friend running a CLN (x) -> LND (o) node was able to connect to mine successfully, however his c-lightning node got the same error as above."

**Comment by bleetube** [comment]
@CMDRZOD your lightningd say it has been configured to listen on port **9375** but you are trying to connect on 9735.

**Comment by CMDRZOD** [comment]
Yes I've since correct that and am still unable to connect through IPv6 or tor.

**Comment by CMDRZOD** [comment]
Hi there. This is continuing to be an issue for me. A node operator using LND encountered the following issues when connecting to my node:
![20230515_055955](https://github.com/ElementsProject/lightning/assets/8326725/586dd8a0-ef5c-4773-806c-af61abbe3ac1)
![20230515_055952](https://github.com/ElementsProject/lightning/assets/8326725/1466c499-a59d-416a-9b58-d64840a77f18)

I've attempted troubleshooting for hours but cannot nail down what is causing my node to be unreachable through tor and/or ipv6. 
Node startup command:
![image](https://github.com/ElementsProject/lightning/assets/8326725/2ff853d7-24df-47af-97b8-c747c313c4c9)

Suggestions and troubleshooting steps would be helpful. I can see the ports are open but outside nodes cannot connect to me.

**Comment by CMDRZOD** [comment]
Hi There. I am continuing to have inbound connectivity issues. These are screen grabs from an LND node attempting to connect to mine.

![20230515_055955](https://github.com/ElementsProject/lightning/assets/8326725/ce2e2ec8-3c00-4e7e-9119-6d09e27dd1fa)
![20230515_055952](https://github.com/ElementsProject/lightning/assets/8326725/90f4ce84-dcf7-46de-ab94-f1292a523763)

I have spent hours troubleshooting this inbound connection error but cannot seem to figure it out. It complains about Tor whether using ipv6 or tor to connect to my node. Screengrab of my node startup options:
![image](https://github.com/ElementsProject/lightning/assets/8326725/e79b794a-a7b3-4682-a909-141bfc90bb02)

Any insights or troubleshooting tips are welcome. Would love to have my node reachable again.

**Comment by CMDRZOD** [comment]
Just lost almost 150 channels in 72 hours. Happened after update to latest 23.05.

![image](https://github.com/ElementsProject/lightning/assets/8326725/18b2f732-8adf-4a0c-904c-3556ff278cd9)

**Comment by CMDRZOD** [comment]
Error message when I attempt to connect from a remote node:

![image](https://github.com/ElementsProject/lightning/assets/8326725/b66538d0-7e4a-4e45-ab7b-f8684ff0e350)
