### ISSUE TITLE
We need a paid_timestamp field in invoice

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#615]
As mentioned in #573 this will allow a nice ordered summary of invoices vs payments (ie. wallet activity)

**Comment by ZmnSCPxj** [comment]
I will take this item, although I will have to defer this to after #597 gets merged or closed.

**Comment by ZmnSCPxj** [comment]
ALTER TABLE invoices
      ADD COLUMN paid_timestamp INTEGER;
    -- Needed since we probably want to sort by timestamp
    -- NOT unique
    CREATE INDEX invoices_paid_timestamp
        ON invoices(paid_timestamp);
    -- Give some dummy timestamp for paid invoices.
    UPDATE TABLE invoices
       SET paid_timestamp = strftime('%s', 'now')
     WHERE state = 1;
