### ISSUE TITLE
v23.02.2 lightning-fundchannel command [feerate] if set as a custom number always defaults to min 1.0 sat/vB

### ISSUE THREAD

**Issue by overcoin** [ElementsProject/lightning#6161]
### Issue and Steps to Reproduce

command: fundchannel   id   amount   [feerate]
feerate is a custom number and omitting the suffix should be equivalent to perkb

1.
lightning-cli fundchannel [peer id obtained from connect] 0.5btc 2
was broadcasted with 1.0 sat/vB
raw transaction (hex):
02000000000101647892d4670f03fd713d67a965502aec75fcf334be01f4d3d6041b3d287957370000000000fdffffff0266a2e11100000000160014aab442b81595d8ecab175e2ba3f7884d7956902580f0fa020000000022002057b7e361489c7ef0ad3aad7f5b8916dc4dd96bac1552a54026064c051f6c2549024730440220482090f28c9560fd2ce70e42c342fca4cd8226424e7e49c948d69f09b484cc0702201b8f98c34e00f1d7c2f3f9c3e1ffbf08cc0cce23e58458c32430e4dc9481e656012103b6308399ae9eea118c69f7858891465cc6736b0b896c252c0f27d23b37c5ec838cf50b00

2. Atempted CPFP with a second fundchannel command
lightning-cli fundchannel [another peer id obtained from connect] 0.5btc 5
was broadcasted with 1.0 sat/vB as well
raw transaction (hex):
02000000000101647892d4670f03fd713d67a965502aec75fcf334be01f4d3d6041b3d287957370000000000fdffffff0266a2e11100000000160014b6f4b4e87483e74fd957563c93d3818896da072780f0fa0200000000220020f5d385126dfb8125136c356fa360864b56076c447623ae772a4a99c27db7a1810247304402205a5048267fcc27e662de41922465fc217240f6af80d436df2ce79fdccc4c828202204e54e4628236e0325b93f9a03a4c2d358a9594c79d0904b6430c47e2bbc7f45a012103b6308399ae9eea118c69f7858891465cc6736b0b896c252c0f27d23b37c5ec8394f50b00

Now second tx sendrawtransaction generates RPC error: {"code":-26,"message":"insufficient fee, rejecting replacement). How should I resolve this situation?

### `getinfo` output
...
   "num_peers": 2,
   "num_pending_channels": 2,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
...
   "version": "v23.02.2",
   "blockheight": 784319,
   "network": "bitcoin",

**Comment by rustyrussell** [comment]
feerate here is in sats per *kb*!  You need to multiply by 1000?
