### ISSUE TITLE
withdraw: 'amount' and 'destination' are reversed

### ISSUE THREAD

**Issue by ktorn** [ElementsProject/lightning#620]
The online help for 'withdraw':

> Send {satoshi} (or 'all') to the {destination} address via Bitcoin transaction

After several `"Invalid satoshis"` errors I realised that the RPC method actually expects the reverse order: {destination} {satoshi}.

In order to avoid confusion I think the order of the params should match.

**Comment by instagibbs** [comment]
I'd rather the description somehow reversed, but that could be a bit of a mouthful compared to what is more natural to read.

**Comment by ktorn** [comment]
Exactly, I tried to think of a good wording and couldn't come up with it.

Also, from the cli I find it slightly more intuitive to type the amount first followed by the copy/pasting of the destination, but I guess that's personal opinion.
