### ISSUE TITLE
failed withdraw from c-l 

### ISSUE THREAD

**Issue by Alex-CodeLab** [ElementsProject/lightning#6211]
### Issue and Steps to Reproduce
I tried to withdraw from cl, but the the transaction (txid) never showed up the mempool. 
It returned  the `tx`, `txid` and `psbt` .
Usually this works just fine, but one time it didn't. 
(probably the result of a slow internet connection) 
 
Question:
- if it is still somewhere pending in c-l, how do I check that?
- if it is still somewhere pending in c-l, how do I remove/cancel it ? 

(I hope it just failed and completely disappeared, and not somehow retry sending again later)

(I tried restarting, without effect. I now turned off the node)

**Comment by vincenzopalazzo** [comment]
there is a possibility to have some logs of what it going on on your machine?

**Comment by Alex-CodeLab** [comment]
there is nothing in CL or Bitcoin debug.log, 
only thing I can see is some timeout/connection issues in syslog:


      Apr 27 12:16:43 node tor[645]: Apr 27 12:16:43.000 [warn] Hidden service 2e2......   exceeded launch limit with 10 intro points in the last 274 seconds. Intro circuit launches are limited to 10 per 300 seconds. [283 similar message(s) suppressed in last 300 seconds]
      Apr 27 12:16:43 node tor[645]: Apr 27 12:16:43.000 [warn] Service configured in "/home/bitcoin/tor/lightningd-service_v2/":
      Apr 27 12:16:43 node tor[645]: Apr 27 12:16:43.000 [warn]   Intro point 0 at [scrubbed]: circuit is open
      Apr 27 12:16:43 node tor[645]: Apr 27 12:16:43.000 [warn] Service configured in [EPHEMERAL]:
      Apr 27 12:16:43 node tor[645]: Apr 27 12:16:43.000 [warn]   Intro point 0 at [scrubbed]: circuit is open
      Apr 27 12:16:43 node tor[645]: Apr 27 12:16:43.000 [warn]   Intro point 1 at [scrubbed]: circuit is open
      Apr 27 12:16:43 node tor[645]: Apr 27 12:16:43.000 [warn]   Intro point 2 at [scrubbed]: circuit is open
      Apr 27 12:17:01 node CRON[4794]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
      Apr 27 12:18:42 node systemd-timesyncd[426]: Timed out waiting for reply from 188.40.142.18:123 (0.debian.pool.ntp.org).
      Apr 27 12:18:53 node systemd-timesyncd[426]: Timed out waiting for reply from 172.105.65.216:123 (0.debian.pool.ntp.org).


(C-L does not seem to log successful withdraw either)

**Comment by Alex-CodeLab** [comment]
Closed for now, because I can't investigate. 
However, it could be useful to test behaviour on flaky networks and log failures.
