### ISSUE TITLE
Releases don't include architecture type

### ISSUE THREAD

**Issue by callebtc** [ElementsProject/lightning#6228]
Looking at the releases, I can see no architecture type.

For instance, although I'm using Ubuntu 22, I won't be able to run the release because I'm on `arm64`.

Please release binaries for multiple architectures (including Linux `arm64` and macOS `arm64`).
 
![image](https://user-images.githubusercontent.com/93376500/235865351-2af958cd-f038-4468-8c37-5cf5738fd81d.png)

**Comment by vincenzopalazzo** [comment]
Ah right! this would be valuable, but I guess are all x86 in the release, we do not have any official support for arm
