### ISSUE TITLE
Node is not able to spend fraudulent commitment transaction

### ISSUE THREAD

**Issue by polespinasa** [ElementsProject/lightning#6233]
Hi,

I'm doing a study on how some Lightning node implementations respond when they are attacked broadcasting an old commitment transaction that does not represent the last state. But I have a problem when the malicious node wants to spend the commitment transaction output.

Note: I'm doing this using a simulator called [Polar](https://lightningpolar.com/).

### Scenario

The scenario is the following one:

Alice (victim)  <-----> Bob (malicious)
     &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
&nbsp;&nbsp;&nbsp;&nbsp; -------> Bitcoin Core <-------

So we have two nodes with an open channel and both connected to the same Bitcoin Core node.

The transaction flows happen in the following way:

1. Bob opens the channel.
2. Bob pays X sats to Alice
3. Alice pays Y sats to Bob (where Y < X) (Bob saves this commitment transaction and it's the one that will be transmitted to the blockchain)
4. Bob pays Z sats to Alice (where X > Z > Y) 
5. Alice loses connection and the node stays offline
6. Bob transmits the transaction from step 3

### Issue
**After a lot of blocks mined, Bob does not see the UTXO available for him and cannot spend it.**
Note: Alice stays offline so she cannot launch a penalty transaction.

### Steps to Reproduce

Note: The steps without a command added are done through the [Polar](https://lightningpolar.com/) UI. You can reproduce the same using the shell.

1. Create a scenario as described in the first section
2. Bob opens a channel to Alice with N sats
3. Bob pays a big amount of sats to Alice
4. Alice pays back a big amount of sats to Bob
5. Bob checks peer ID: `lightning-cli listchannels`
6. Bob saves the commitment transaction from step 4 using command: `lightning-cli dev-sign-last-tx {peer-id}`
7. Bob pays again to Alice
8. Turn off Alice node
9. Using the BitcoinCore node broadcast the output of step 6 (fraudulent commitment transaction in raw): `bitcoin-cli sendrawtransaction {output step 6}`
10. The BitcoinCore mines some blocks to validate the transactions
11. You should mine enough blocks to exceed the time look.

After this, I'm not able to spend that transaction from Bob node.
Note: Alice should not send a penalty transaction as she is offline

### Aditional Information

Please see here the raw transactions from funding channel transaction and the malicious commitment transaction:

- Channel funding transaction: 0200000000010133846b8f9089bf6524eb9dbe30f1bff419177e9fbc50c64d95c17781c052f0e90100000000fdffffff02f6cf03000000000016001446aad9992293ca3858ff0e0f1460ea0164a3c05890d0030000000000220020f7d252dbb9bfcc9492c49c24411767947ea97f1134d304a711eabd1ff5e01f590247304402206124a5818cbf8928fb15bbe5f82eacbc00439623a8e995ebbe17315fe64f70b8022078151912126de69ec77725c89d2a58391cd18f315d8251ae7989fd02f212534c012103921dbef36a655990050d3d255dba0c037b3b7678f25aaa6ebd87e4854f14f2ea6b000000

- Malicious commitment transaction: 020000000001015ba3867406230306ad6dc4256b724726e492ba80fb0452667a26fa59f0531e72010000000010159a8002102700000000000016001472d78c794b0ca0a8597034329b0b35fd87f8b8e5c9a8030000000000220020514da04829460e97323765c857a063e992c2c453c21b88cd530bd03fba8ebfbb040047304402203087c68e155d91d09f3c09dacf1f1ab59220a93854165de4aa9b7fff0c52748602204fa0a5814c4cff59bfc1acc3a493cb8497ad5d5d42736adca5d5fb9c82103bdf014830450221008da0c1454d9ad48cf6270cbd686cae87314f84be4261448b947cd1157183f2aa022060d87ffe5a49c16c1eed1e055b76eec8c1e9843fa4fc3a07947e9ebbaa7f76630147522102ee8b8a7d5d9988bad85c17fa328f7f7f41552d80d76f30bd3554852185b87bf421032b34c0e8906d19a84487f8884df4cf8f99afb047cea02664fca0ace534b0fd8752ae809d0d20

You can also see attached to this post Bob logs. I'm not able to correct interpret them, but in line 2818 there's a message saying: `did *we* cheat`? This has caught my attention.

Please if you need more information in order to help me don't hesitate to ask.
If you need specific information I would be grateful if you could also tell me which command to run on the node so that I can send you the necessary information as I am not very familiar with the node's CLI.

Thanks in advance!
[logs.txt](https://github.com/ElementsProject/lightning/files/11401868/logs.txt)

**Comment by vincenzopalazzo** [comment]
Mh is this use case more suitable for https://github.com/rustyrussell/lnprototest ?

**Comment by polespinasa** [comment]
Hi,

The issue is that the Node does not remember older states, he only saves the needed info to create a penalty transaction so he does not know how to spend the older commitment transaction.

I resolved this doing a backup of the lightningd.sqlite3 database and restoring it to the commitment transaction state.

**Comment by vincenzopalazzo** [comment]
>The issue is that the Node does not remember older states

Well IMHO this is a feature :)

**Comment by polespinasa** [comment]
> > The issue is that the Node does not remember older states
> 
> Well IMHO this is a feature :)

I agree, it is not a problem. Wrong word. In fact, it's a good feature to avoid issues and hinder attacks.
I was trying to say it was a problem for what I was trying to do :)
