### ISSUE TITLE
Installation error without automake

### ISSUE THREAD

**Issue by ekerstein** [ElementsProject/lightning#624]
I was following the instructions to install and I got an error when I tried to run make.

~/lightning $ make
cd external/libwally-core && ./tools/autogen.sh && ./configure CC="cc" --enable-static=yes --enable-module-recovery --enable-shared=no --libdir=`pwd`/.. && make
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
external/Makefile:40: recipe for target 'external/libwally-core/src/libwallycore.la' failed
make: *** [external/libwally-core/src/libwallycore.la] Error 1

I fixed this by installing automake: sudo apt-get install automake

Perhaps you should add that to the installation dependencies.

**Comment by renepickhardt** [comment]
I am on Ubuntu 18.04 and ran into the same error. I had installed `auotmake` before but after I had the error and google put me here I double checked also I double checked that `libgmp-dev` was installed on my sytem:

```
configure: error: ./configure failed for src/secp256k1
external/Makefile:45: recipe for target 'external/libwally-core/src/libwallycore.la' failed
make: *** [external/libwally-core/src/libwallycore.la] Error 137
rpickhardt@Ubuntu-1804-bionic-64-minimal:~/bitcoin/lightning$ sudo apt-get install automake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
automake is already the newest version (1:1.15.1-3ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
rpickhardt@Ubuntu-1804-bionic-64-minimal:~/bitcoin/lightning$ sudo apt-get install libgmp-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgmp-dev is already the newest version (2:6.1.2+dfsg-2).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
```

The current installation guide said to install pip repos with sudo (git blame says this line was added by @cdecker 
 and @jsarenik ) c.f.: 
  https://github.com/ElementsProject/lightning/blob/b28d71a9a575dc3a814b73849f868b3a03013637/doc/INSTALL.md#50  

this libwalley thing seemed to be python related if it was a user rights problem so I ran `sudo make` which went further but resultet with this  problem: 
```
external/Makefile:77: recipe for target 'external/libbacktrace.a' failed
make: *** [external/libbacktrace.a] Error 137
rm external/libwally-core/src/secp256k1/libsecp256k1.la
```

I looked at https://github.com/ElementsProject/lightning/blob/27a186be9ca0e552472041c71b012a7ef57c53fb/external/Makefile#L75 which looked fine to me. 

so I tried `sudo chmod -R $USER:$USER .` and then ran `make` again (this time without sudo and that worked out.)

my linux system was very clean (online bitcoin core and docker installed but in particular docker should not have changed anything) So I wonder weather the documentation of installing pip dependencies with sudo should be changed. Also when running those commands from the installation guide I received: 
 
```
sudo pip3 install python-bitcoinlib
The directory '/home/rpickhardt/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rpickhardt/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-bitcoinlib
  Downloading https://files.pythonhosted.org/packages/30/03/fb7df95fe89baede202cf3fe65e65bea4bf863061b5e8f59b12dab538240/python_bitcoinlib-0.10.1-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 5.0MB/s 
Installing collected packages: python-bitcoinlib
Successfully installed python-bitcoinlib-0.10.1

```

**Comment by cdecker** [comment]
@renepickhardt did you try to compile by mounting the source directory as a bind mount in a docker image and then compile it in there? In that case the dockerized build could end up creating files owned by `root` instead of your local user (depending on what user is configured inside the docker image), which can result in these weird ownerships.

`python-bitcoinlib` being installed as root should not do anything in your source director, so I don't see how that could have any effect.

**Comment by renepickhardt** [comment]
I did not run this setup within docker. I just mentioned that the server is clean besides some docker containers. I was also confused about the root issues in particular that make creates an error when running as root. 

I am not sure if anyone is able to reproduce the issue. Also I was able to handle it since lightning is up and running on mainnet (at least as far as I understand it). I just posted here in case others run into similar problems and want to see the fix. I think I was able to peer to your node. Mine should be: 

```
rpickhardt@Ubuntu-1804-bionic-64-minimal:~/bitcoin/lightning/cli$ ./lightning-cli getinfo
{
  "id": "036f464b54416ea583dcfae3872d28516dbe85414ed838513b1c34fb3a4aee4e7a", 
  "port": 9735, 
  "address": [
    {
      "type": "ipv6", 
      "address": "2a01:4f8:201:1113::2", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }
  ], 
  "version": "v0.5.2-2016-11-21-2796-g27a186be", 
  "blockheight": 525628, 
  "network": "bitcoin"
} 
```

**Comment by jsarenik** [comment]
Thank you for this report, Rene! I'll have a look at it later today, also
in connection with Rusty's latest pull request.

**Comment by jsarenik** [comment]
Or is it fully resolved? Seems so. Sorry for spam then.
