### ISSUE TITLE
Still some msat suffixes

### ISSUE THREAD

**Issue by hMsats** [ElementsProject/lightning#6244]
### Issue and Steps to Reproduce

`local_funds_msat` etc. still have suffix msat in `lightning-cli listpeers`

Example:
```
          "funding": {
                  "local_funds_msat": "500000000msat",
                  "remote_funds_msat": "0msat",
                  "pushed_msat": 0
               },
```

### `getinfo` output

"version": "v23.05rc3"

**Comment by vincenzopalazzo** [comment]
Oh that is a really nice catch! thanks

**Comment by vincenzopalazzo** [comment]
Patch up https://github.com/ElementsProject/lightning/pull/6245

Thanks @hMsats <3

**Comment by hMsats** [comment]
@vincenzopalazzo thanks Vincenzo! Better avoid a "Great Msat Migration" part 2 :-)
