### ISSUE TITLE
Can't start lightningd - error: couldn't connect to server

### ISSUE THREAD

**Issue by ekerstein** [ElementsProject/lightning#625]
I'm getting an error when starting lightningd. bitcoin-cli works fine in my console. I'm running default bitcoin settings.

+0.037390646 lightningd(31095):DEBUG: Trying to guess public addresses...
+0.037771255 lightningd(31095):DEBUG: Address 192.168.1.4:9735 is not routable
+0.037800557 lightningd(31095):DEBUG: Failed to connect 10 socket: Network is unreachable
+0.039292006 lightningd(31095):DEBUG: testing /home/ekerstein/lightning/lightningd/lightning_channeld
+0.041616928 lightningd(31095):DEBUG: testing /home/ekerstein/lightning/lightningd/lightning_closingd
+0.044469818 lightningd(31095):DEBUG: testing /home/ekerstein/lightning/lightningd/lightning_gossipd
+0.046641110 lightningd(31095):DEBUG: testing /home/ekerstein/lightning/lightningd/lightning_hsmd
+0.048730405 lightningd(31095):DEBUG: testing /home/ekerstein/lightning/lightningd/lightning_onchaind
+0.052219632 lightningd(31095):DEBUG: testing /home/ekerstein/lightning/lightningd/lightning_openingd
+0.103585673 lightningd(31095):DEBUG: HSM TRACE: Client: Received message 11 from client
+0.114625874 lightningd(31095):DEBUG: Loaded 0 invoices from DB
+0.114802486 lightningd(31095):DEBUG: HSM TRACE: Client: Received message 9 from client
+0.115118499 lightning_gossipd(31103):DEBUG: pid 31103, msgfd 12
+0.115249154 lightningd(31095):DEBUG: Loaded 0 channels from DB
+0.118530525 lightningd(31095):BROKEN: bitcoin-cli exited with code 1: error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

+0.118765983 lightningd(31095):BROKEN: FATAL SIGNAL 6 RECEIVED
+0.124553188 lightningd(31095):BROKEN: backtrace: lightningd/log.c:436 (log_crash) 0x40ffe9
+0.124574966 lightningd(31095):BROKEN: backtrace: (null):0 ((null)) 0x7f1efcb334af
+0.124595571 lightningd(31095):BROKEN: backtrace: (null):0 ((null)) 0x7f1efcb33428
+0.124601093 lightningd(31095):BROKEN: backtrace: (null):0 ((null)) 0x7f1efcb35029
+0.124609495 lightningd(31095):BROKEN: backtrace: lightningd/log.c:525 (fatal) 0x410423
+0.124748366 lightningd(31095):BROKEN: backtrace: lightningd/bitcoind.c:685 (wait_for_bitcoind) 0x4054ea
+0.124897751 lightningd(31095):BROKEN: backtrace: lightningd/chaintopology.c:726 (setup_topology) 0x4079f6
+0.125008520 lightningd(31095):BROKEN: backtrace: lightningd/lightningd.c:326 (main) 0x40e952
+0.125015893 lightningd(31095):BROKEN: backtrace: (null):0 ((null)) 0x7f1efcb1e82f
+0.125021298 lightningd(31095):BROKEN: backtrace: (null):0 ((null)) 0x403138
+0.125026058 lightningd(31095):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff

race: (null):0 ((null)) 0xffffffffffffffff

):0 ((null)) 0x7f355f61082f
+0.082966040 lightningd(30455):BROKEN: backtrace: (null):0 ((null)) 0x403138
+0.082968721 lightningd(30455):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff

**Comment by centaur1** [comment]
You might try adding:
--network=bitcoin

to the 
./lightningd/lightningd 

e.g.
./lightningd/lightningd --network=bitcoin

**Comment by ekerstein** [comment]
That worked! Thank you, it seems like not including the network will cause an error.

**Comment by cdecker** [comment]
Without the explicit opt-in it'll fall back to testnet.
