### ISSUE TITLE
lightning_gossipd: FATAL SIGNAL 7

### ISSUE THREAD

**Issue by GamerSg** [ElementsProject/lightning#6320]
I upgraded my rpi4 firmware/kernel and now cannot start lightningd which crashes with this error. I was previously on v23.02 and pulled latest sources and recompiled hoping it would work but to no avail.

$nice -n 1 lightningd --lightning-dir=$lndir
lightning_gossipd: FATAL SIGNAL 7 (version v23.05-115-g2d53707)
lightning_gossipd: FATAL SIGNAL (version v23.05-115-g2d53707)
lightningd: gossipd failed (exit status 242), exiting.

Everything was working fine before the upgrade which was done through
$sudo rpi-update

$uname -a
Linux raspberrypi 6.1.32-v8+ #1656 SMP PREEMPT Wed Jun  7 11:37:17 BST 2023 aarch64 GNU/Linux

**Comment by vincenzopalazzo** [comment]
Can you share more logs that tell us what it is wrong with your pi?

**Comment by cdecker** [comment]
Closing due to lack of information and long radio silence.
