### ISSUE TITLE
Building on Alpine no longer works

### ISSUE THREAD

**Issue by gruve-p** [ElementsProject/lightning#6321]
### Issue and Steps to Reproduce

Since this commit: https://github.com/ElementsProject/lightning/commit/36200a65937e28df5344b2355d2075381a69ce32 the master branch no longer builds on Alpine.
You can replicate it yourself by triggering this workflow: https://github.com/ElementsProject/lightning/blob/master/.github/workflows/ci_build.yml

### error output

```
cc wallet/wallet.c
cc wallet/walletrpc.c
cc wallet/reservation.c
cc wallet/db_sqlite3_sqlgen.c
cc wallet/db_postgres_sqlgen.c
cc common/addr.c
cc common/bolt11.c
cc common/bolt11_json.c
cc common/bolt12.c
cc common/configdir.c
cc common/configvar.c
cc common/scb_wiregen.c
common/configvar.c: In function 'configvar_remove':
common/configvar.c:118:9: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  118 |         ssize_t prev = -1;
      |         ^~~~~~~
      |         size_t
make: *** [Makefile:292: common/configvar.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by vincenzopalazzo** [comment]
The compiling test should be enable, let try to do it

Thanks to reporting it
