### ISSUE TITLE
Infinite DB loop on invoices table

### ISSUE THREAD

**Issue by telelvis** [ElementsProject/lightning#6339]
### Issue and Steps to Reproduce
Hello!
As discussed a bit in discord , I don't know how, but I managed to create the following invoice, using zeus mobile app & sparko on CLN side . 
Below is an output of `.json insert ; select * from invoices;`, I omitted payment_key, gut feeling it's sensitive:

> INSERT INTO "table" VALUES(1,0,2000000,X'61b2c829e8824860f439007b914606279668fbeccc23b1e50ca72eee99ef3abe',X'XXX','zeus.188720.87378213642',3372447143,NULL,NULL,NULL,'lnbc20u1pjgrv7vsp5e66h3umqledeu6gx58l739jmw5y8rczjkv42pgsrmqy7ft7w9t7qpp5vxevs20gsfyxpapeqpaez3sxy7tx37lves3mregv5uhwax0082lqdqqxq8pjgrswmcqpj9qx3qysgq3qf02hpm9m5jqq5h0hgndc87a2h36nez999mpty6kddkwm7k4hcsplghdftsxu9mj9a9lywv8k0tm2kz9yfpmyc3e6glwye8sypfsqsp64qgln','',X'02000022024100',NULL);

On startup CLN goes into infinite cycle of database queries, that look like this when printed to stdout, I slightly modified db/db_sqlite3.c to printf stmt->query->query:

> 2023-06-15T18:27:50.210Z DEBUG   lightningd: io_break: connect_init_done
2023-06-15T18:27:50.210Z DEBUG   lightningd: io_loop: connectd_init
SELECT blobval FROM vars WHERE name='genesis_hash'SELECT blobval FROM vars WHERE name='node_id'SELECT intval FROM vars WHERE name= ? LIMIT 1SELECT MIN(height), MAX(height) FROM blocks;SELECT id  FROM invoices WHERE state = ?   AND expiry_time <= ?UPDATE invoices   SET state = ? WHERE state = ?   AND expiry_time <= ?;SELECT MIN(expiry_time)  FROM invoices WHERE state = ?;UPDATE vars SET intval = intval + 1 WHERE name = 'data_version' AND intval = ?SELECT id  FROM invoices WHERE state = ?   AND expiry_time <= ?UPDATE invoices   SET state = ? WHERE state = ?   AND expiry_time <= ?;SELECT MIN(expiry_time)  FROM invoices WHERE state = ?;UPDATE vars SET intval = intval + 1 WHERE name = 'data_version' AND intval = ?SELECT id  FROM invoices WHERE state = ?   AND expiry_time <= ?UPDATE invoices   SET state = ? WHERE state = ?   AND expiry_time <= ?;SELECT MIN(expiry_time)  FROM invoices WHERE state = ?;UPDATE vars SET intval = intval + 1 WHERE name = 'data_version' AND intval = ?SELECT id  FROM invoices WHERE state = ?   AND expiry_time <= ?UPDATE invoices   SET state = ? WHERE state = ?   AND expiry_time <= ?;SELECT MIN(expiry_time)  FROM invoices WHERE state = ?;

And it goes on and on.
If I do `delete from invoices`, CLN starts ok.

### `getinfo` output

>./lightning-cli --version
v23.05-115-g2d53707-modded

**Comment by vincenzopalazzo** [comment]
This is super strange!
 
I am assuming that you are using sqllite as db?

**Comment by telelvis** [comment]
Yes, this is sqlite3 indeed!

**Comment by rustyrussell** [comment]
OK, so the invoices expires in 2076.  It works here, but I can see how it could overflow and get us very upset!

Are you on a 32-bit machine by chance?

**Comment by telelvis** [comment]
That's right ! Here is info about it:

```
Raspberry Pi 2 Model B Rev 1.1

@raspberrypi:~$ lscpu
Architecture:                    armv7l
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           5
Model name:                      Cortex-A7
Stepping:                        r0p5
CPU max MHz:                     900.0000
CPU min MHz:                     600.0000
BogoMIPS:                        38.40
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
```

Is 32 bit officially supported?  docs.corelightning.org do not explicitly mention required cpu architecture
Few people use it in 2023, probably I should just move on for my own safety..

**Comment by rustyrussell** [comment]
No, this is cool!  But I'm clearly doing a u32 somewhere in the code that the u64 missed: you needed a really big expiry to hit it.

And yeah, you're in the minority.  Still, thanks for the report!

**Comment by telelvis** [comment]
thank you! I built & ran PR branch, I can confirm it's fixed!
