### ISSUE TITLE
funds disappeared while funding a channel

### ISSUE THREAD

**Issue by elichai** [ElementsProject/lightning#634]
I tried funding a channel on testnet and the command got stuck so I did `ctrl+c`,
then when I ran `listfunds` I got nothing but no channel was opened and the money was still in the same address: https://www.blocktrail.com/tBTC/address/2NBE1k9euA3D6gbYb7z9F2mrwduf6gaWrjX

Sounds like something you don't want happening on mainnet, I think you should at least add a `dumpprivkey` function or something like that.

Thanks.

**Comment by instagibbs** [comment]
a dumpprivkey command sounds like a good idea

**Comment by cdecker** [comment]
`dumpprivkey` only works if the importing wallet supports P2WPKH addresses. You can re-enable the output by opening the sqlite database and setting the status of the output to to `0`:

```
$ sqlite3 ~/.lightning/lightningd.sqlite3
SELECT hex(prev_out_tx), prev_out_index, status FROM outputs;
UPDATE outputs SET statuts=0 WHERE hex(prev_out_tx) = 'dbd749a4cb75b122e9a89a02653c14e6572883fb684c8644d230cedee516fb0e'; 
```
The first query will show all known outputs and their status, while the second marks the output as available again. Notice that the hash is in big-endian (inverted w.r.t. bitcoind), so just copy paste the one from the first query.

**Comment by cdecker** [comment]
One more thing: what's the output of `getpeers`, I'm wondering whether we should store the funding transaction in the DB as well and re-broadcast it so we eventually end up with the channel being established. That'd make the marking of funds as spent and the tx being stored for broadcast atomic and this can't happen anymore.

**Comment by cdecker** [comment]
This was most likely a combination or #803 and the funds being marked as spent by the funding TX. After PR #864 you can now use the `dev-rescan-outputs` JSON-RPC command to re-synchronize with the UTXO as tracked by `bitcoind`
