### ISSUE TITLE
Missing one side of a channel to ACINQ

### ISSUE THREAD

**Issue by daywalker90** [ElementsProject/lightning#6344]
I have a channel with ACINQ and since about 2-3 weeks my graph is missing the channel with the direction ACINQ -> ME.

I already tried restarting and deleting the graph file. 

If i query my node's graph with listchannels and either source=ACINQPUBKEY or destination=ACINQPUBKEY i get about 2718 for source=ACINQPUBKEY and 2802 for destination=ACINQPUBKEY, but only 1 for listchannels MY_CHAN_ID_WITH_ACINQ.

Is there something i can do and who do i have to annoy for this to get fixed?
This makes things like rebalancing impossible.

cln 23.05.1

**Comment by cdecker** [comment]
It is worth noting that you are missing ACINQ's side of the `channel_updates`. Each endpoint is responsible for their outgoing direction, so your CLN node is correctly managing its own `channel_update` and we're missing the one from ACINQ to you.

It may make rebalancing hard (you can only rebalance using the outgoing direction, not the incoming one without ACINQs update), but more concerning is that it also means you can't add routehints to your invoices indicating which channels the payer could use to reach you.

It'd be interesting to see if the message is missing just from your node or was generally lost in the network. Do you mind sharing the short channel ID (here or in a DM)?

**Comment by daywalker90** [comment]
776755x557x1

**Comment by rustyrussell** [comment]
Hmm, it's still missing from mempool.space, as well as my node.

The good news is that 23.08 *will* aggressively gossip the peer's update_channel, if they send you one (as of https://github.com/ElementsProject/lightning/pull/6412)
