### ISSUE TITLE
Route around unusable 0-hop channels?

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#635]
Right now I have a channel open with Blockstream (02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432) this is unusable. I'm stuck in a CLOSINGD_SIGEXCHANGE state where neither of us can pay the required fees to close.

I do have a potential route around this channel, through some intermediary nodes:

![jan17-114556](https://user-images.githubusercontent.com/45598/35063556-4d321136-fb7c-11e7-9780-6f51efa3ff94.png)

When I getroute it only returns the CLOSINGD_SIGEXCHANGE channel, which is unusable. I would hope it could find an alternative route instead.

After this is fixed I will be able to buy some stickers.

**Comment by jb55** [comment]
When I try to pay I get:
```
first peer not ready: WIRE_UNKNOWN_NEXT_PEER
```

**Comment by jb55** [comment]
getroute returns:

```
$ lightning-cli getroute 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 77816792 1
{ "route" : 
	[ 
		{ "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "channel" : "504663:526:0", "msatoshi" : 77816792, "delay" : 9 } ] }
```

**Comment by ZmnSCPxj** [comment]
At some point, fixing #550 should fix this too.

Note that `gossipd` is the one who maintains the network map, and it is currently completely unaware of local channel state (and even does not treat its own node as special --- the core routing algorithm can accept routing between any arbitrary two nodes that `gossipd` knows about).

Possibly a future, smarter implementation would be: `lightningd` chooses a valid local channel to use (one in `CHANNELD_NORMAL`, has enough money on local side, and is most unbalanced in favor of us? this is essentially an allocation algo, with heuristics like best-fit, worst-fit, first-fit etc...), then asks `gossipd` to route from the other peer of the selected local channel to the payee (and indicates `gossipd` to not pass through the local node).  That way the overall routing algorithm is aware of local channel state.

The above generalized algorithm would also be useable for rebalancing channels.  For example if you have 3 local channels with 5 mBTC each and need to pay somebody with 12mBTC, you would first consolidate your local channels by routing 5 mBTC from channel 1 to channel 0 and 2mBTC from channel 2 to channel 0, and then proceed to pay from channel 0.

**Comment by hopitas** [comment]
Same problem here.


`                { "state" : "CLOSINGD_SIGEXCHANGE", "netaddr" :
                        [ "104.198.32.198:9735" ], "peerid" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "connected" : false, "channel" : "504636:1199:0", "msatoshi_to_us" : 15000000, "msatoshi_total" : 15000000 },`
