### ISSUE TITLE
Support lcli connect nodeid@ip:port 

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#636]
maybe connect could be smart enough to detect this popular connection string style?

**Comment by cdecker** [comment]
Might be a good idea, though we need to address #574 first in that case.

**Comment by ZmnSCPxj** [comment]
@cdecker, please assign to me.  #1022 duplicates this, and I have run out of things to do (modulo waiting for feedback to current PRs, as well as CPFP+RBF for accelerating own transactions), and it seems popular enough to get duplicated.
