### ISSUE TITLE
make default target not include the target to generate code from the schema

### ISSUE THREAD

**Issue by ddustin** [ElementsProject/lightning#6365]
When changing the RPC, the documentation auto generate doesn't seem to trigger. Doing these commands seems to generate the RPC documentation manually.

```
PYTHONPATH=contrib/msggen python3 contrib/msggen/msggen/__main__.py

python -m grpc_tools.protoc -I cln-grpc/proto cln-grpc/proto/node.proto --python_out=contrib/pyln-testing/pyln/testing/ --grpc_python_out=contrib/pyln-testing/pyln/testing/ --experimental_allow_proto3_optional
python -m grpc_tools.protoc -I cln-grpc/proto cln-grpc/proto/primitives.proto --python_out=contrib/pyln-testing/pyln/testing/ --experimental_allow_proto3_optional

find contrib/pyln-testing/pyln/testing/ -type f -name "*.py" -print0 | xargs -0 sed -i  's/^import \(.*\)_pb2 as .*__pb2/from . import \1_pb2 as \1__pb2/g'
```

These commands are ripped from the toplevel Makefile. Something seems to be making these not fire automatically during make.

**Comment by vincenzopalazzo** [comment]
Mh, for what rpc are you changing the docs? Some of the RPC are not mapped to the GRPC code gen

**Comment by ddustin** [comment]
Instagibbs & I both ran into the same issue. You can see it happen on my PR https://github.com/ElementsProject/lightning/pull/6253 and his https://github.com/ElementsProject/lightning/pull/6035

**Comment by instagibbs** [comment]
unsure if it's why, but I'm still having issues on my taproot PR I can't really diagnose

**Comment by vincenzopalazzo** [comment]
Ok, someone can test this https://github.com/ElementsProject/lightning/pull/6372 ?
