### ISSUE TITLE
Stabilize minfee from bitcoind

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#6380]
Since bitcoind restarts drop the minfee to minimal, we should refuse to drop minfee for some period.

See https://github.com/bitcoin/bitcoin/issues/27555

**Comment by vincenzopalazzo** [comment]
looks like duplicate https://github.com/ElementsProject/lightning/issues/6259

**Comment by rustyrussell** [comment]
Yes, closing in favor of #6259
