### ISSUE TITLE
Install instructions for debian?

### ISSUE THREAD

**Issue by plorph** [ElementsProject/lightning#64]
Should I be able to use install on debian similar to ubuntu? I'm having issues getting the libbase58-dev package, apparently it isn't for debian wheezy (latest version). Do I need to re-configure sources or something to get that package? thanks

**Comment by rustyrussell** [comment]
jonny <notifications@github.com> writes:
> Should I be able to use install on debian similar to ubuntu? I'm
> having issues getting the libbase58-dev package, apparently it isn't
> for debian wheezy (latest version). Do I need to re-configure sources
> or something to get that package? thanks

I haven't tried on Debian, but maybe you can find libbase58-dev in
backports?

Unfortunately I don't have a handy Debian machine to test on.

Good luck!
Rusty.

**Comment by braydonf** [comment]
Looks like it's available with these sources:
- https://packages.debian.org/stretch/libbase58-dev (testing)
- https://packages.debian.org/sid/libbase58-dev (unstable)

**Comment by cdecker** [comment]
`libbase58` is rather tiny and I would just add it as a git submodule until it is in the stable repos for the major distributions.

**Comment by cdecker** [comment]
Since 3e6bb958eb106357516d1b769041e02c290a0bc8 we have libbase58 as a submodule, closing this.
