### ISSUE TITLE
unknown variant `SENT_ADD_ACK_COMMIT` when calling ListPeerChannels.

### ISSUE THREAD

**Issue by 2Fast2BCn** [ElementsProject/lightning#6411]
@cdecker Similar to #6318:

rpc error: code = Unknown desc = Error calling method ListPeerChannels: RpcError { code: None, message: \"Malformed response from lightningd: unknown variant `SENT_ADD_ACK_COMMIT`, expected one of `SENT_ADD_HTLC`, `SENT_ADD_COMMIT`, `RCVD_ADD_REVOCATION`, `RCVD_ADD_ACK_COMMIT`, `SENT_ADD_ACK_REVOCATION`, `RCVD_ADD_ACK_REVOCATION`, `RCVD_REMOVE_HTLC`, `RCVD_REMOVE_COMMIT`, `SENT_REMOVE_REVOCATION`, `SENT_REMOVE_ACK_COMMIT`, `RCVD_REMOVE_ACK_REVOCATION`\" }

**Comment by cdecker** [comment]
But the variant is in there:

https://github.com/ElementsProject/lightning/blob/0ceee9390a682a7e3a1ecd7529c8b0099f0f8d1a/cln-rpc/src/primitives.rs#L46

Which version of the crate are you using?

**Comment by 2Fast2BCn** [comment]
It has been reported to us by someone using Torq on their CLN v23.05.2
