### ISSUE TITLE
local/remote feerates are too different: remoteFeeratePerKw=265 localFeeratePerKw=53760"

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#643]
This doesn't seem right.
```
./cli/lightning-cli fundchannel 03c4b20397d476a0d008e61022c96803ada3c11918fff8133db4f7d27273710e03 16000000
"Error packet: channel 45ea28830152b04ac83b10f7eb53c7f6147190de43ed5215b0f398d3d4602994: local/remote feerates are too different: remoteFeeratePerKw=265 localFeeratePerKw=53760"

```

**Comment by cdecker** [comment]
Which network is this on?

**Comment by cdecker** [comment]
Yup, testnet is really bad for fee estimations, you can ignore fees with `--ignore-fee-limits` on testnet, but it should be on by default there. Which commit are you using? It might be the remote side giving you the error, so that might not completely fix the issue.

**Comment by thestick613** [comment]
latest, i guess:

```
./lightningd/lightningd --version
v0.5.2-2016-11-21-1591-ga06f0df
aka. Bitcoin Savings & Trust Daily Interest II
Built with: 
./cli/lightning-cli --version
v0.5.2-2016-11-21-1591-ga06f0df
aka. Bitcoin Savings & Trust Daily Interest II
Built with: 

```

**Comment by cdecker** [comment]
Those are pretty recent alright. Alternatively you can always use `--override-fee-rates` to set the feerates manually, since you seem to control both ends of the channel.

**Comment by cdecker** [comment]
Ah, I see the error is produced on the other end by an eclair wallet, so I guess you can't really set the fees to whatever you want, try setting `--override-fee-rates=1000/500/265` or something like that.

**Comment by thestick613** [comment]
I don't control both ends of the channel, just mine. Do i need to set up that flag in lightningd or in lightning-cli? I'm going to assume lightningd.

**Comment by cdecker** [comment]
Yep, `lightningd` needs to get started with that.

**Comment by parmax** [comment]
I try use --ignore-fee-limits and --override-fee-rates and but not working it

./cli/lightning-cli listpeers | grep -v GOSSIP | grep state | cut -d'"' -f4 | sort | uniq -c | sort -nr
     12 OPENINGD
      2 CHANNELD_NORMAL

When i open channel from eclair mobile wallet to my c-lightning instance the channel change state from wait_for_accept_channel to closed but not channel_normal.

Howto debug it and help to fix?

**Comment by ZmnSCPxj** [comment]
This is because the error was coming from the other side.  So its remote is your local, and its local is your remote.

**Comment by cdecker** [comment]
Closing as stale.
