### ISSUE TITLE
MacOS (OSX) build instructions

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#645]
I'll update this description with my progress so far on MacOS 10.13.2:

```sh
brew install gmp gnu-sed libsodium

make
```

**Comment by cdecker** [comment]
How are you running the build? If I'm not mistaken `errno=13` on file open indicates a file access permission problem? @rustyrussell can probably help out more with the compile instructions.

**Comment by Sjors** [comment]
That was a permission error. Making more progress now, will update.

**Comment by Sjors** [comment]
Getting the following error:
```
*** Warning: Linking the shared library libwallycore.la against the
*** static library secp256k1/.libs/libsecp256k1.a is not portable!
copying selected object files to avoid basename conflicts...
[....]
ld: warning: ignoring file ./.libs/libwallycore.a, file was built for archive which is not the architecture being linked (x86_64): ./.libs/libwallycore.a
undef: _bip39_mnemonic_to_bytes
undef: _bip39_mnemonic_validate
undef: _wally_bzero
Undefined symbols for architecture x86_64:
  "_bip39_mnemonic_to_bytes", referenced from:
      _run_tests in lto.o
  "_bip39_mnemonic_validate", referenced from:
      _run_tests in lto.o
  "_wally_bzero", referenced from:
      _main in lto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [test_clear] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [external/libwally-core/src/libwallycore.la] Error 2
rm external/libwally-core/src/secp256k1/libsecp256k1.la
```

Full log in [gist](https://gist.github.com/Sjors/ee0aa69db0c7cb7400cd5f6bb8ed7f9f).

**Comment by bitstein** [comment]
I get this error as well.

**Comment by cdecker** [comment]
The magicians from `libwally` are contemplating to remove LTO from their build, since it seems to break on a lot of compilers, I'll keep you posted, and please share if you find a way to fix it :-)

**Comment by Sjors** [comment]
I just successfully compiled on OSX 🎉

Getting the occasional `FATAL SIGNAL 11 RECEIVED` though. I'll test a bit more.

**Comment by Sjors** [comment]
```
lightningd/lightningd --network=regtest --port=9000 --log-level=debug
...
lightningd(65314): Adding block 102: 0cfee4338935b2cbc980351985bf0448b952ee481d36e4f5495b355f8a77ec84
lightningd(65314): Unable to estimate CONSERVATIVE/2 fee
...
lightningd(65314): Connected json input
lightningd(65314): FATAL SIGNAL 11 RECEIVED
```

The error seem to happen when I perform any RPC call, e.g. `cli/lightning-cli help`

I'm using the latest master of `bitcoind`.

Same issue on testnet.

**Comment by cdecker** [comment]
@Sjors can I close this issue, since the original reported issue seems to be resolved?

**Comment by Sjors** [comment]
The original issue was about missing instructions though.

**Comment by cdecker** [comment]
Ok, I'll leave this open then

**Comment by Sjors** [comment]
Added `libsodium`, which seems required at least as of #1102.

**Comment by Sjors** [comment]
Instructions are there now.
