### ISSUE TITLE
DB upgrade errors in master

### ISSUE THREAD

**Issue by grubles** [ElementsProject/lightning#6459]
CLN at c98711ad28bdb13ba8e2b6f4e9620df2cdaa024f

```
2023-07-28T18:11:42.738Z INFO    lightningd: Updating database from version 228 to 229
2023-07-28T18:11:42.738Z **BROKEN** lightningd: Error executing statement: wallet/db.c:1684: UPDATE vars SET name = 'last_invoices_created_index' WHERE name = 'last_invoice_created_index': UNIQUE constraint failed: vars.name
```

**Comment by rustyrussell** [comment]
This is possible if you ran between the creation of this field and the update :(

The correct fix is to set last_invoice_created_index to r max of last_invoice_created_index and last_invoices_created_index, then remove last_invoices_created_index.

UPDATE vars SET name = 'last_invoices_created_index' WHERE name = 'last_invoice_created_index':

**Comment by grubles** [comment]
Hm ok. All that happened was the node was shut down and then restarted with ``--database-upgrade=true` after building master. 

Attempting to run that command against the (backed-up) `lightningd.sqlite3` db now results in this:

```
Error: UNIQUE constraint failed: vars.name
```

**Comment by rustyrussell** [comment]
No, this is correct, was on mobile, that was the command which fails.

I am reproducing this now, to make sure my fix will actually work.  The alternative is to give you a one-liner, but I really want to test it anyway...

**Comment by grubles** [comment]
I see what you mean now. Ok I'm running 6463 now and the node is back online.
