### ISSUE TITLE
Feature Request: bech32 funding address

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#648]
`cli/lightning-cli newaddr` currently generates a legacy p2sh address. It would be nice and slightly cheaper if it could also generate a `bech32` funding address.

**Comment by jb55** [comment]
I'll take this one.

**Comment by jb55** [comment]
Plan:

1. Add address type parameter to newaddr (done in 070f9e44009066bf6a95f74ed7a189f3e947245d)
2. Update `funding_tx` to support [!is_p2sh](https://github.com/ElementsProject/lightning/blob/feb734086b9d890883baac542023d8416975ce19/common/funding_tx.c#L33) inputs via `input[i].witness = bitcoin_witness_p2wpkh`

am I missing anything? any tests I should look at?

**Comment by jb55** [comment]
I should be fine after I write some bech32 funding + channel tests, should catch anything I might have missed.

**Comment by jb55** [comment]
It doesn't look like this is necessary:

> Update funding_tx to support !is_p2sh inputs via input[i].witness = bitcoin_witness_p2wpkh

pr incoming
