### ISSUE TITLE
getinfo command missing network name

### ISSUE THREAD

**Issue by alvenca** [ElementsProject/lightning#649]
$ cli/lightning-cli getinfo
{ "id" : "025a8b46f17a79aeeb40f47e124d62d299831a7e102fe54c3aa62f6cee731c12a6", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "176.58.113.228", "port" : 9735 }, 
		{ "type" : "ipv6", "address" : "2a01:7e00::f03c:91ff:fe1c:7ee3", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1574-g575b733e-dirty", "blockheight" : 1259539 }

Was removed here https://github.com/ElementsProject/lightning/commit/329269d9d052f559efc37d0d525af6063ff6d2d8

Can it be reintroduced?

**Comment by cdecker** [comment]
Sure, let me create the PR and it should be back soon ^^
