### ISSUE TITLE
hsmd, splicing: Capabilities bug?

### ISSUE THREAD

**Issue by ksedgwic** [ElementsProject/lightning#6496]
In `v23.08rc1`:

Is this a bug?
https://github.com/ElementsProject/lightning/blob/master/hsmd/libhsmd.c#L109-L110

- If there is meant to be a splicing capability, wouldn't it be `HSM_CAP_SIGN_SPLICE_TX`?
- Otherwise, wouldn't it be grouped with `HSM_CAP_MASTER`?

**Comment by ksedgwic** [comment]
Here, they wire numbers are used:
https://github.com/ElementsProject/lightning/blob/master/hsmd/libhsmd.c#L2022-L2028

**Comment by ksedgwic** [comment]
But the other "capabilities" are different, I think

**Comment by ksedgwic** [comment]
Work here: https://github.com/ElementsProject/lightning/pull/6498

**Comment by ksedgwic** [comment]
I think this is fixed

**Comment by vincenzopalazzo** [comment]
You are right @ksedgwic 

Fixed in https://github.com/ElementsProject/lightning/pull/6522
