### ISSUE TITLE
If we kill channeld because it's too slow, we don't disconnect?

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#6506]
Testing with ACINQ, they did not reply in a timely manner and we killed channeld.  However, listpeerchannels still shows "connected: true" and we didn't restart channeld, so it failed payments from then on, and didn't try to reconnect.

We should either restart channeld, or disconnect.

**Comment by wtogami** [comment]
https://github.com/ElementsProject/lightning/issues/6500#issuecomment-1665282056
See flowchart by PM
