### ISSUE TITLE
custommsg not reliable?

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#6513]
From @nepet , via @cdecker . It seems that sending a custom message is not reliable.

I believe I know this why this may be, so I'm creating an issue so it's not lost. 

In particular, connectd takes pains not to buffer: a message comes in from subd, it is handed to the peer and we stop listening to the subd until that is done (and vice versa). This avoids the "infinite buffer bloat" problem, and provides proper back pressure.

However, if we inject a message, it might wait until this logic is triggered. We should wake up the peer explicitly.

**Comment by rustyrussell** [comment]
Ok, this is not the cause: I tried to reproduce it, and failed. We always write to the peer, it's reading that alternates.

**Comment by nepet** [comment]
Unfortunately, I was not able to reproduce this in a reliable way. 
I did some testing with a few hundred peers and it seemed that invoking `sendcustommsg` directly from the lightning-cli worked reliably all the time.
Also, I found a potential dead-lock on the plugin that had the trouble in the first place, when `sendcustommsg` returned with an error.

**Comment by rustyrussell** [comment]
OK, I'm closing for now.  Feel free to reopen if you get something!

**Comment by vincenzopalazzo** [comment]
>Also, I found a potential dead-lock on the plugin that had the trouble in the first place, when sendcustommsg returned with an error. 

It is a Rust plugin? or a go one? there is any way that I can look at it?

**Comment by vincenzopalazzo** [comment]
Yeah this was my intuition too
