### ISSUE TITLE
Cannot find myself

### ISSUE THREAD

**Issue by nstamato** [ElementsProject/lightning#654]
I have lightningd running on ubuntu 17.10 on the main net, and everything seems to be ok (no obvious errors, I can transfer funds to it) until I try to find a route or I need to pay an invoice (to Blockstream), getting the error:

`lightning_gossipd(18040): TRACE: Trying to find a route from 029113620f929df927a4877ae6727b214418c366bf09ebbd4552eda235f48c00f5 to 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 for 170088341 msatoshi
lightning_gossipd(18040): TRACE: find_route: cannot find myself (02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432)`

I opened a connection manually to the Blockstream node, and while I see the info with getpeers, any attempt to "getroute" to the Blockstream itself, I get the "cannot find myself" error. 

` $cli/lightning-cli getinfo
{ "id" : "029113620f929df927a4877ae6727b214418c366bf09ebbd4552eda235f48c00f5", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "68.129.210.251", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1590-g9ed7041c", "blockheight" : 504901 }`

I'm suspecting there's something wrong in my setup and I'm using --ipaddr to lightningd with my public IP otherwise I get:

`lightningd(18825): Trying to guess public addresses...
lightningd(18825): Address 192.168.1.156:9735 is not routable
lightningd(18825): Failed to connect 10 socket: Network is unreachable`

Any ideas? Thanks!

**Comment by ZmnSCPxj** [comment]
Have you done `fundchannel` to some existing mainnet Lightning node?  Routing is unaware of self if self has no channels yet.

Try to do `getchannels` (or `listchannels`after #623 gets merged) and tell us what it returns.

**Comment by nstamato** [comment]
I haven't funded any channel yet, I was under the impression that a channel would be created and funded via the `pay` command automatically.

The `getchannels` command returns a number of channels (although none with myself as the source) e.g 

`{ "source" : "039514e5d704c59a0eba65d25fc5fe559a1641243ccdf80c980b1fc10ca9c30ca2", "destination" : "029e536db01d310948bba46d8563ece3b2d92b41059ceb5a6454d1cf9466f9d2b8", "short_channel_id" : "504054:495:1", "flags" : 1, "active" : true, "public" : true, "last_update" : 1516291900, "base_fee_millisatoshi" : 1000, "fee_per_millionth" : 1, "delay" : 144 }...`

I'll fund a channel and try again. If this is expected behavior and I'm using the simply API wrong, please feel free to ignore!

**Comment by ZmnSCPxj** [comment]
No indeed, `pay` requires a channel to the network.  In fact if it fails to route it will just error instead of retrying a different route, and as of right now it fails and you try again it is likely to retry the same route, which is something we should fix "soonish".  For now, create a channel directly to Blockstream store.

**Comment by nstamato** [comment]
Indeed, that did it. Everything looks like expected now and I can pay the invoice. Thanks again.
