### ISSUE TITLE
gossipd: unbounded memory usage in `dump_our_gossip` > `queue_peer_from_store`

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#6540]
### Issue and Steps to Reproduce

I haven't had time to bisect this yet, but I know that reverting the recent batch of gossipd commits eliminated the problem, so the problem must have been introduced somewhere among these commits:
* d16797ce587c3407aec6221e5bdeba8e50ea7713 gossipd: add dying marker to channel_announcement/channel_update.
* 63b622ec62264c6e2ec7c97d76fd0d25fd3eb3d3 gossipd: clean up dump_our_gossip.
* 7409a93d17f50358877ca22b5d09171446e587df gossipd: when we dump our own gossip, include our node_announcement.
* 55d6a13ffc4a9d6327dd0a6be664fd955c1ccad0 gossipd: aggressively advertize *both* sides of channel_update.
* af7e641445985a143511e9607da60532ea66ca1c gossipd: don't "unmark" dying channels' updates if we receive them.
* 4a4da00d2874dc7633fe9e631806b7644abf4a55 gossipd: handle upgrade from version 11 gossip_store
* 4b4937b9bd3e1ce1422b53581b6a2f3c52f9c0c7 gossipd: tell lightningd about all our previous channel_updates at startup.
* 8f196b2d7b626b2e94f722090bf2737ce7fdfb0b gossipd: actually update own node announcement if needed
* 955afdeea8f54080173eee4be4eecd07d5960436 gossipd: set timer for node_announcement regen

After roughly an hour of running my node, the `lightning_gossipd` process was consuming over 700 MiB of RAM. Reverting the above commits tamed it (down to around 60 MiB and possibly still growing but much more slowly).

After I noticed the apparently unbounded growth, I attached Heaptrack to the process and let it collect for a little while. Here's the suspect call graph:
![Screenshot_20230809_060948](https://github.com/ElementsProject/lightning/assets/797782/3fd2ee91-06e5-435a-8989-5b01fc178f68)

**Comment by rustyrussell** [comment]
Ah, looks like dump_our_gossip.  It used to just send every channel_announcement and channel_update to every peer, now it sends the channel_announcements, two channel_updates and the node_announcement.

This, ofc, is O(N^2).  It always was, but your node is pretty big so you feel it, now N is 50% larger than it was.

The Right Fix is to stream this slowly (which means maintaining this in connectd, not gossipd), but the Immediate Fix is to not do this for every peer.

**Comment by whitslack** [comment]
> This, ofc, is O(N^2). It always was, but your node is pretty big so you feel it, now N is 50% larger than it was.

@rustyrussell: Something isn't right about that math. My node has been up for about 48 hours now, and `lightning_gossipd` is sitting stable at ~65 MiB of memory usage. If the impact of the new changes were really a 50% increase in *N*, then O(*N*<sup>2</sup>) scaling would suggest that the new version's memory usage should have stabilized around 146 MiB, but it had shot well past that and was continuing to rise long after the elapsed time at which the reverted version stabilized. I think you're overlooking an actual leak, not merely quadratic scaling with a larger factor.
