### ISSUE TITLE
Implement a recovery plugin

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#6544]
We have:
* --recover
* Peer backup
* --offline
* emergency.recover
* rescan (for finding our funds)

We should implement a "recovery" plugin which handles:
- Detecting that we need recovery: when a peer sends a reestablish which is IN THE FUTURE, we currenrtly log a message and mark the channel not to go onchain.  We should instead, begin a recover process.
- Trying to recover from various sources.

Stretch goals:
- [ ] Enhance peer backup to contain more information
- [ ] Mutual close for channels
- [ ] Scan for funds
- [ ] Continue channels for a while if we can / user chooses?
- [ ] Ability to do peer backup for random nodes in return for sats
- [ ] Ability for recovery plugin to use that to pay for peer backup / try it for restoration

**Comment by daywalker90** [comment]
good idea, if i could recover the sats i lost here https://github.com/ElementsProject/lightning/issues/6045 that would be awesome!

**Comment by rustyrussell** [comment]
There is also a requirement to have a *runtime* recover command:

- Only works if node is unused (no channels, no funds, no addresses issued)
- Restarts with --recover=...

**Comment by cdecker** [comment]
Addressed in #6853
