### ISSUE TITLE
listpeers should show the reserve values.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#655]
Someone accidentally pushed 80k msat to me, and I am tryiong to figure out how much of it I can send back to them!

**Comment by rustyrussell** [comment]
Note also: error was fairly cryptic:

"failed: INVALID 0 (WIRE_TEMPORARY_CHANNEL_FAILURE: Capacity exceeded)"

**Comment by jb55** [comment]
I'll take this one

**Comment by molxyz** [comment]
@rustyrussell  you meant to say 80k satoshis, or 80 million satoshis, correct?  "msat" is confusing here.

**Comment by maximusmaximus** [comment]
@rustyrussell What does this mean? "failed: INVALID 0 (WIRE_TEMPORARY_CHANNEL_FAILURE: Capacity exceeded)"
