### ISSUE TITLE
Unpublished channel with LND peer leading to incoming direction getting disabled.

### ISSUE THREAD

**Issue by owtyahyg6** [ElementsProject/lightning#6555]
I have unpublished channels with an LND peer and after sending most of the liquidity towards the peer, it looks like the peer stops sending channel updates, leading to the direction towards my node getting disabled, which then causes new invoices to be unusable because CLN does no longer generate route hints for this peer. A forced disconnect with the peer does not solve the issue, but updating the peer updating its channel fees does fix it. Maybe the direction flag should be ignored for unpublished channels.

**Comment by rustyrussell** [comment]
Seems like we could work around this by ignoring the "disabled" flag on private channel updates when creating route hints.
