### ISSUE TITLE
bitcoin-cli exec failed: Bad file descriptor

### ISSUE THREAD

**Issue by Dave86ch** [ElementsProject/lightning#6562]
Hello everyone, I have a beginner's question. 

I've installed Bitcoin Core on my Windows 11, and now I'm attempting to run a Lightning node on wsl2. I've cloned the Elements repository and have been following a tutorial. I've reached this point:

```bitcoin-cli exec failed: Bad file descriptor2023-08-14T10:34:24.303Z **BROKEN** plugin-bcli: bitcoin-cli exec failed: Bad file descriptor
2023-08-14T10:34:24.304Z INFO    plugin-bcli: Killing plugin: exited before we sent init
The Bitcoin backend died.
```

I believe I might need to modify my Bitcoin Core's bitcoin.conf file to connect the Lightning node to my Bitcoin node. I'm feeling a bit lost. 
Can someone provide guidance on how to proceed? 🙏

Could it be because I didn't complete the bitcoin.conf file in the Bitcoin Core Windows directory? I created it, but at the moment, it's empty. I noticed there are some variables related to the Lightning node that I need to complete, but I have no idea where to find them.
I feel like I'm missing a passage related to the connection between lightning and bitcoin core.

**Comment by Dave86ch** [comment]
It's highly probable that there's an issue related to the Lightning Network's WSL2 accessing bitcoin-cli on Bitcoin Core on a Windows 11 machine. 
Do you have any ideas on what I need to do to allow the Lightning Network on WSL2 to access bitcoin-cli?

**Comment by niftynei** [comment]
hey dave! try setting the lightningd config `--bitcoin-datadir` to the location where your bitcoin data is?

**Comment by chrisguida** [comment]
What if the `bitcoind` node is remote? @niftynei

**Comment by chrisguida** [comment]
I had this error when trying to connect a lightning node to a mutinynet `bitcoind`. problem was that i was not hosting the bitcoin rpc on the expected signet rpc port.

Specifying `bitcoin-rpcport` in the config fixed the problem on ubuntu, but for some reason the problem persists on nixos.

**Comment by chrisguida** [comment]
@Dave86ch wsl networking can be a bit complicated, as i believe it has its own VLAN. but as long as you have both bitcoind and lightningd running in the same environment, it should just work™, though you should double check to make sure the rpc user, password, host, and port are the same between bitcoind and lightningd.

**Comment by chrisguida** [comment]
And actually @niftynei 's advice to point lightningd at your bitcoind datadir should enable you to leave everything else blank i think? if not it may be necessary to explicitly set a rpcuser and rpcpassword in bitcoin.conf.
