### ISSUE TITLE
`wallet_payment` `path_secrets` is never written to db

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#657]
Nothing in `wallet/wallet.c` writes this column, even though it is loaded from db.

**Comment by ZmnSCPxj** [comment]
Actually, I want to bring up now, *should* `path_secrets` be saved? I think `wallet_payment` is only saved to db on success, but `path_secrets` is only relevant on failure?

**Comment by rustyrussell** [comment]
Yes.  And test_payment_failed should be checking the result, but it isn't!

In particular log should contain:
"htlc %"PRIu64" failed from %ith node with code 0x%04x (%s)"

and the future should raise a Valueerror with the string WIRE_UNKNOWN_PAYMENT_HASH!

**Comment by ZmnSCPxj** [comment]
A reason I ask is because, since it is not saved in the db yet, I want to also include the route information `short_channel_id` of the hop also, for #638, into this `path_secrets` field, if possible.  This will let us report the failing channel to gossipd.
