### ISSUE TITLE
Bug Report: Ride The Lightning - Payment Failure with Core Lightning

### ISSUE THREAD

**Issue by TowyTowy** [ElementsProject/lightning#6589]
I encountered a payment failure while attempting to send 300,000 SATS to a specified LN wallet using the Ride The Lightning (RTL) interface, which utilizes Core Lightning as its backend. The error message indicates that the payment failed due to running out of routes after 34 attempts.

Error Details:

Error Code: 500
Error Message: Ran Out Of Routes To Try After 34 Attempts: See paystatus
API URL: ./api/cln/payments
Context:
I initiated a payment of 300,000 SATS using the RTL interface with the following details:

Recipient LN Wallet Address: lnbc3m1pjwrl5rpp5e94mev7yc4cdl2re42xuqd7pxm0k2a2lk4ngxytghgndjle5802sdqqcqpjsp5a5rl5lns86yf4pq0e39n670d8txdh5d8dxh82mqy2p5r4d4e8hvq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqmqz9gxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcllmpua4z2zsm6cqqqqlgqqqqqeqqjq50sm9zr4ggptawvcvj3cn2jme8qma9p064pdd28qf5veeaajdvzszy6msa0alr7spa62dlqwjpfw6vgzavk4fut8zqd7urw095wvd5sp304q5k

Outbound Liquidity: I have a total of 700,000 SATS in outbound liquidity distributed across 4 channels.

**Comment by vincenzopalazzo** [comment]
It is possible have the result of paystatus by filtering by this specific invoice? 

> Outbound Liquidity: I have a total of 700,000 SATS in outbound liquidity distributed across 4 channels.

Do you have enough liquidity for send the payment (it is balanced in the correct way?)

**Comment by TowyTowy** [comment]
Where do I find the paystatus in Ride the Lightning (UI)?

Well I believe I do if I have 700,000 in outbound liquidity, right?

**Comment by TowyTowy** [comment]
Okay, I found out how to get paystatus, I looked at it but I was unable to see anything interesting.

**Comment by rustyrussell** [comment]
There have been several pay fixes in 23.08, so I expect that this will improve with that...

**Comment by TowyTowy** [comment]
Okay, I am crossing my fingers!

**Comment by TowyTowy** [comment]
Just updated, no luck... Still happens, but it seems to have something to do with my LNBig channels, the rest work sort of fine most of the time.
