### ISSUE TITLE
Docker image for arm32v7

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#6596]
Currently core lightning's images are available for amd64 & arm64v8. And we also want to extend it for arm32v7.

But it fails with below issues:
- On debian:bullseye, it fails to build a wheel distribution of cryptography because it only supports GLIBCXX till version 3.4.28. And building the wheel requires minimum v3.4.29.

- On debian:bookworm, it fails to build cln-grpc with errors; (a)`failed to determine package fingerprint for build script for cln-grpc v0.1.3 (/opt/lightningd/cln-grpc)` & (b) `could not read directory '/opt/lightningd': Value too large for defined data type; class=Os (2)`.
These errors usually occur together when either project dependency or a build script assumes the environment to be a 64-bit env.

**Comment by NicolasDorier** [comment]
Adding the `include` key to `[package]` seems to fix `failed to determine package fingerprint for build script`. Unsure why it is happening only on armv7.

https://github.com/rust-lang/cargo/issues/10311

**Comment by NicolasDorier** [comment]
Unknow if it works, I just stopped the process after 2H hanging. I will try to remove grpc from the build.

**Comment by NicolasDorier** [comment]
Removing cln-grpc from the plugins compiled worked for me. We aren't using it anyway.

**Comment by NicolasDorier** [comment]
After removing grpc, here is the next issue.
```
ImportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/lib/python3.9/dist-packages/grpc_tools/_protoc_compiler.cpython-39-arm-linux-gnueabihf.so)
```

**Comment by daywalker90** [comment]
I can add this:
It's definitely possible to compile cln-grpc for armv7. I did it using [cross](https://github.com/cross-rs/cross) and this Cross.toml:
```toml
[build]
pre-build = [
    "apt update && apt install -y unzip",
    "curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip && unzip protoc-21.12-linux-x86_64.zip -d /usr/",
    "chmod 755 /usr/bin/protoc"
]
```
then
```
cross build --release --target armv7-unknown-linux-gnueabihf
```

**Comment by NicolasDorier** [comment]
well would be glad for that to work, my fork had to make quite a few changes for arm32 to compile... (still compiling though 2h30min in... :D)

https://github.com/btcpayserver/lightning/commit/7cb9c2e94d8182dfaee4d8aeecd597930ce618cc

**Comment by NicolasDorier** [comment]
I am trying to use cross compile tools to speed up the build. This may fix this issue as well.

**Comment by NicolasDorier** [comment]
Tried to use cross compile tools. Same issue with armv7 :(

**Comment by NicolasDorier** [comment]
Found a hack to build grpc on arm7

```
sed -i '/documentation = "https:\/\/docs.rs\/cln-grpc"/a include = ["**\/*.*"]' cln-grpc/Cargo.toml
```

**Comment by ShahanaFarooqui** [comment]
Closing with https://github.com/ElementsProject/lightning/pull/7214

**Comment by Raimo33** [comment]
> Found a hack to build grpc on arm7
> 
> ```
> sed -i '/documentation = "https:\/\/docs.rs\/cln-grpc"/a include = ["**\/*.*"]' cln-grpc/Cargo.toml
> ```

Is this hack still the only way?
