### ISSUE TITLE
Erroneous "Cannot afford funding transaction"?

### ISSUE THREAD

**Issue by drmoore718** [ElementsProject/lightning#661]
Getting a "Cannot afford funding transaction" when trying to open a channel.  'bitcoin-cli getbalance' says I have 3.39702068.  Funding for maximum amount, 16777215.  'bitcoin-cli listunspent' shows 3 UTXOs, all with 6 confs.

**Comment by ZmnSCPxj** [comment]
lightningd has its own wallet. Use `lightning-cli getfunds` to see the onchain money you have in ligtningd. Use `lightning-cli newaddr` to get a receive address for the lightningd wallet.

**Comment by drmoore718** [comment]
Sigh, that would explain it - I've been playing around with lnd, forgot that c-lightning works this way.
