### ISSUE TITLE
doc: add splice out example

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#6613]
The current splicing docs (`splice_init`, `splice_signed` and `splice_update`) have examples for splicing _in_. I'm still trying to wrap my head around them. But I think it would be useful to add a splice out example. I have a feeling that's easier since you don't (?) need the initial `fundpsbt` step.

**Comment by Sjors** [comment]
By the way, I'm assuming the idea is to eventually also have a simple `splice` command that just works(tm)?

Or maybe seperate ones for splicing in and out, closely mimicking `withdraw`:

* `splice_out channel_id destination satoshi [feerate] [minconf]`
* `splice_in channel_id satoshi [feerate] [minconf] [utxos]`

**Comment by ddustin** [comment]
Adding the `--` technique usage example to the splice_init documentation in PR #6677.
