### ISSUE TITLE
lightningd(PID): bitcoin-cli -testnet getblock  exited with status 5

### ISSUE THREAD

**Issue by practicalswift** [ElementsProject/lightning#664]
I've encountered the following error message:

```
lightningd(PID): bitcoin-cli -testnet getblock  exited with status 5
```

Notice the missing block id in `bitcoin-cli -testnet getblock [block_id]`.

**Comment by cdecker** [comment]
Do you have the output of the preceding `getblockhash`?

**Comment by practicalswift** [comment]
@cdecker I'm afraid the logs are gone. Sorry for the terrible bug report :-)

**Comment by cdecker** [comment]
No problem at all :-) Shall we keep this one open in case it manifests itself again?

**Comment by practicalswift** [comment]
@cdecker You decide - I'm fine with both alternatives :-)

**Comment by cdecker** [comment]
Ok, let's close this for now and reopen when it reappears :smile:
