### ISSUE TITLE
Feature Request: fund channel with all available funds, or a specific output

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#665]
Avoids the need for a change address, especially if you want to put all available funds in a single channel.

**Comment by gdistasi** [comment]
I agree, this is a very useful feature.

**Comment by windsok** [comment]
Agree. I accidentally sent ~8000 satoshis to a change address when doing my first channel opening. My own fault, but an easier way to force spending all available funds and not producing a change UTXO would be useful.

**Comment by Sjors** [comment]
With fees ticking up again, it's now spending ~€1.50 to open a channel, this becomes more relevant.

**Comment by cdecker** [comment]
Marking as good first issue, shouldn't be too hard and it's a good exercise in getting acquainted with the source.

**Comment by ZmnSCPxj** [comment]
Suggestion for those who want to consider taking this issue: `withdraw` command supports `all` input to withdraw all funds; it may be useful to unify the code with `withdraw`, then support selecting an output by "txid:outnum" form in the unified code (to fund using a specific output).  This implies adding a wrapper around `wallet_select_coins`/`wallet_select_all`.

**Comment by wythe** [comment]
I added support to fundchannel to accept "all". For now, I just made `json_fund_channel` look as close to a copy of `json_withdraw` as possible.  Now, as @ZmnSCPxj  suggests, I will unify the code and also support selecting a specific output.

It worked on testnet for me, and I added a `test_funding_all` python test.  

Its all on my `fund_all` branch.  Should I make a pull request and mark as work-in-progress?

**Comment by ZmnSCPxj** [comment]
Yes, please make pull request, thank you!  It could be marked WIP if you intend to also add the specific-output support in the same pull request but we could also do a separate pull request for the specific-output support.

**Comment by wythe** [comment]
Ok sounds like a plan. Will do.

**Comment by wythe** [comment]
I hear you @robtex.  Maybe another option, closest fit:
`fundchannel fit 10000 16000`

I also am experimenting with providing a list of utxos instead of just a single one.

**Comment by cdecker** [comment]
I'd rather not make this RPC call any more complex than necessary. We can always add a new RPC command, and then we can externalize the coinselection completely, i.e., pass in a list of outputs that should be selected for the funding, and a value, similar to `createrawtransaction` in `bitcoind`.

**Comment by wythe** [comment]
Yeah that makes sense.  Should I even add support for specifying the single utxo?

**Comment by wythe** [comment]
Yes.

**Comment by jb55** [comment]
This is implemented now, can this be closed?

**Comment by Sjors** [comment]
Ah, I totally missed that. This was added in #1399 even though the description says it wasn't? Nice!

> No new functionality, just a continuation of my work toward completing #665
