### ISSUE TITLE
fundchannel failed with feerate_per_kw 27478 below minimum 29067

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/lightning#666]
I worked around it by manually setting fees through `dev-setfees`, but that probably shouldn't be necessary.

**Comment by rustyrussell** [comment]
Hi!  Do you have logs?  And where were you opening channel to?  Looks like your side and the remote disagreed on fee levels, with the remote being much higher...

**Comment by Sjors** [comment]
Fwiw I haven't had the need to use `dev-setfees` recently.

**Comment by cdecker** [comment]
Most of the fee issues seem to have been addressed by PR #1650.
