### ISSUE TITLE
`psbt_contribs_changed` modifies its inputs and loses the final witness field

### ISSUE THREAD

**Issue by devrandom** [ElementsProject/lightning#6672]
### Issue and Steps to Reproduce

VLS provides signatures in the `final_witness` input field.  `psbt_contribs_changed` modifies its input, losing the witness stack elements stored this field.  This probably happens in `sort_inputs`.

I believe you are not running into this with libhsmd signing because you are using the partial signatures field instead of the final witness field.

Also, this code path is specific to splicing, and does not occur with single funding.  I didn't check dual-funding.

**Comment by vincenzopalazzo** [comment]
I discussed this with @ksedgwic on Matrix. Looks like the error is gone if we remove this https://github.com/lightning-signer/c-lightning/commit/19027e59f8570a1d9d4af0b0b1e00dfa174380c2 code

I do not know what is the reason for this code, but I am guessing that a plugin can change a PSBT and here we are making sure that it is sane. However, this looks like a bug if we break VLS. There should be another way.

cc @niftynei Can you help me understand the reason for this code? I get the logic right?

**Comment by ksedgwic** [comment]
Found the specific problem (it's near the sort, but the sort is fine):
- `psbt_contribs_changed` -> `input_identical` -> `linearize_input` which calls:
```
	wally_psbt_input_set_final_witness(&psbt->inputs[0], NULL);
```

**Comment by vincenzopalazzo** [comment]
Ah, do you have the pointer for the spec? we should add it inside the code if it is spec related
