### ISSUE TITLE
Backup: Add feature to verify backup

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#6711]
Add a new rpc command to enhance backup functionality by allowing the user to verify their already existing backups.

**Comment by adi2011** [comment]
Nice idea...
Should we verify the emergency.recover file or peer storage backup in this?

**Comment by ShahanaFarooqui** [comment]
Let us start with `emergency.recover` first. If users/devs find it useful, then we can extend it to list all our peer storage backups and verify them as well.

**Comment by adi2011** [comment]
Resolved, @ShahanaFarooqui?

**Comment by ShahanaFarooqui** [comment]
Thanks, Closing this issue with PR #6773, although I had to go through the PR to understand how to get `emergency.recover` contents. Posting this line for future reference and will update the documentation with another PR.

- an *emergency\_recover* string generated by `lightning-hsmtool getemergencyrecover <emergency.recover-path>` (starts with `clnemerg1`).
