### ISSUE TITLE
hsmd: hsmd_ready_channel is confusing name

### ISSUE THREAD

**Issue by ksedgwic** [ElementsProject/lightning#6717]
### Issue and Steps to Reproduce

- Originally VLS used `hsmd_ready_channel` as an early call during channel setup.
- Later the BOLT-2 spec changed the name of `funding_locked` to `channel_ready`.

This is very confusing because the `hsmd_ready_channel` is not directly related to the new `channel_ready`.

We should rename `hsmd_ready_channel` to `hsmd_setup_channel`.

Since the API is defined by msgtype integers this change would be forward and backward compatible, nothing other than the name is changing.

**Comment by vincenzopalazzo** [comment]
That sounds good to me, how does the deprecated policy look from the hsmd point of view?

Looks like that we should just increase the `hsm_version`, right?

**Comment by ksedgwic** [comment]
I don't think this change (in isolation) requires incrementing `hsm_version` because it doesn't change any message signatures or behavior.  It is a "source code only" naming change.

That said, there are very likely other changes (other new methods) being introduced this round which will  require increasing `hsm_version` (and adding to capabilities) so my earlier point in this reply is likely moot ...

**Comment by vincenzopalazzo** [comment]
Aaah right right! You also mentioned here, sorry

>Since the API is defined by msgtype integers this change would be forward and backward compatible, nothing other than the name is changing.

So this should do the job https://github.com/ElementsProject/lightning/pull/6724
