### ISSUE TITLE
Allow non-strict forwarding

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#6718]
We added channel multiplexing in v22.11, which opened up the possibility of non-strict forwarding, but we haven't implemented it yet.

Non-strict forwarding allows a forwarding node to use an alternative channel than the one specified in the onion payload to reach the next hop. This allows the forwarding node to more efficiently manage their funds, but also allow to increase the success probability of payments by switching to a non-depleted channel when the channel the sender intended to use was depleted.

The code in question is here:

https://github.com/ElementsProject/lightning/blob/577161a4fa0c26201a69d9d4fa5b2a0fee1073ca/lightningd/peer_htlcs.c#L744-L771

It should:
 - [ ] Prefer the channel the sender specified if it can forward the payment
 - [ ] Fail over to another channel with the same peer if the specified channel isn't available

Out of scope:
 - Exposing a customization interface for operators. This can still be achieve via the `htlc_accepted` hook rewriting the forward payload, which would be respected due to part 1. above.

**Comment by ecurrencyhodler** [comment]
Looks like @rustyrussell completed this issue here: https://github.com/ElementsProject/lightning/blob/master/lightningd/peer_htlcs.c#L1253

**Comment by cdecker** [comment]
Thanks for the heads up @ecurrencyhodler, closing as completed.
