### ISSUE TITLE
splice: need to sync with signer on funding locked

### ISSUE THREAD

**Issue by devrandom** [ElementsProject/lightning#6722]
## Overview

In general, a validating signer may be under a different operational environment than the node, and therefore may have a different source of on-chain data.  The signer may therefore temporarily disagree on whether a funding or splice transaction is locked (buried).  We would like to ensure agreement between the signer and the node on how to progress a channel's state.

## Analysis

During a splice or channel establishment v2, we can have `N` RBF candidates, and need to sign commitment transactions for each candidate.  At other times, only `1` signature is required.

The node communicates `channel_ready` or `splice_locked` to the peer when it detects a funding transaction is buried.  Once the peer replies, the channel moves from requiring `N` signatures to requiring `1` signature.  A further splice may be also be initiated at this point.

If the node and signer disagree on whether the funding is locked, the signer would require `N` signatures, while the node will only receive `1` signature from the peer.  This would result in a stall of the channel state, because the signer will refuse to make progress.

## Potential Design

Two signer API calls are needed:

- `check_outpoint(outpoint) -> bool` - check if the signer agrees that a funding candidate outpoint is buried
- `lock_outpoint(outpoint)` - change the funding/splice state to locked

### Rationale

- the node wants to do a "preflight check" via `check_outpoint`, so that it can send the `splice_locked` message without actually locking the funding candidate.  if it doesn't pre-check, and it discovers that the signer disagrees after the peer says `splice_locked`, it won't be able to progress the commitment state because the signer will expect `N` sigs, but the peer will only produce `1`
- the node can't lock before the peer agrees (can't use `lock_outpoint` directly), because then we won't be able to satisfy the peer with `N` signature if the peer isn't ready to lock
- note that the peer may take arbitrarily longer to lock than us, because they are allowed to have a different lock criteria

## Notes

- the actual probability of the signer being out of sync with the node about chain data can be kept low by requiring less blocks for locking on the signer side

**Comment by vincenzopalazzo** [comment]
>In general, a validating signer may be under a different operational environment than the node, and therefore may have a different source of on-chain data. The signer may therefore temporarily disagree on whether a funding or splice transaction is locked (buried). We would like to ensure agreement between the signer and the node on how to progress a channel's state.

Aaaah you unlock another way to look at the hsmd :) thanks

Ok let me write down what I understand of your solution proposed. but take in consideration that I need to check how splicing works from the transaction negotiation point of view.

>the node wants to do a "preflight check" via check_outpoint, so that it can send the splice_locked message without actually locking the funding candidate. if it doesn't pre-check, and it discovers that the signer disagrees after the peer says splice_locked, it won't be able to progress the commitment state because the signer will expect N sigs, but the peer will only produce 1

In other words the `check_outpoint` is a way that core lightning needs to have to confirm that the signer is on the same page before sending the `splice_locked`, right? otherwise, the mess with the signature required happens.

>the node can't lock before the peer agrees (can't use lock_outpoint directly), because then we won't be able to satisfy the peer with N signature if the peer isn't ready to lock

`lock_outpoint` is something similar but will change the state of the outpoint. I do not understand here (and this is my limitation because I am missing something). Who can not use the `lock_outpoint`?

BTW, if I am not missing anything from the basic usage of the API, it is possible to have the same result with `lock_outpoint(outpoint) -> bool` and returning false when:

- `check_outpoint(outpoint) -> bool` return false
- `lock_outpoint(outpoint)` fails in some why (can fails yes?)

This looks like less back and forth that will be good in the case I have an hsmd in a tiny device connected to the network?

**Comment by devrandom** [comment]
so this is basically a 2-phase commit between the signer the node and the peer.  the reason for this is that everybody must agree on the lock, otherwise one of them will want `N` signatures (on the splice candidates), and another will produce only `1` signature.  `check_outpoint` is the "prepare" for the signer, and `lock_outpoint` is the "commit".  if `check_outpoint` returns true, `lock_outpoint` must not fail.

the reason you cannot use `lock_outpoint` directly is because this will cause the signer to lock while the peer might not be ready to lock (e.g. it requires more on-chain confirmations).  if you tell the signer to lock, it will start producing `1` signature per commitment.  but if the peer is not ready at this point, it will require `N` signatures on commitment transactions, and you won't be able to advance the commitment state, potentially for a long time.

(just a reminder - while the `N` candidates transactions of the splice are pending, you should still be able to use the channel as normal.  in the scenario above you won't be able to.)

**Comment by ksedgwic** [comment]
@vincenzopalazzo I'm also sketching these, have to update w/ this spec, will leave pointers when they are fixed ...

**Comment by ksedgwic** [comment]
@devrandom Is it safe to presume that both of these calls will be made in channel context?

(to be made from "master context" they need additional channel identifying args (see `hsmd_get_channel_basepoints` for example))

**Comment by devrandom** [comment]
> @devrandom Is it safe to presume that both of these calls will be made in channel context?
> 
> (to be made from "master context" they need additional channel identifying args (see `hsmd_get_channel_basepoints` for example))

that is more natural, and it's unfortunate that `get_channel_basepoints` is not in the channel context

**Comment by ksedgwic** [comment]
@vincenzopalazzo The last three commits on the draft PR are maybe up to date; working to see them in integration next ...

https://github.com/lightning-signer/c-lightning/pull/95/commits
