### ISSUE TITLE
splice: signer must be informed of splice parameters

### ISSUE THREAD

**Issue by devrandom** [ElementsProject/lightning#6723]
## Overview

The signer needs to know when the splice operation starts and the splice parameters for each splice transaction candidate.

The channel establishment v2 (dual funding) code path already notifies the signer via the hsmd API `hsmd_ready_channel` calls (note the name clashes with the new name for `funding_locked` in the spec - see #6717).  However, the splicing code path does not.

See also #6722 for locking of a splice candidate in the signer.

## Design

Call `ready_channel` in the splicing code path after each splice candidate is negotiated.

The following parameters may vary from the previous confirmed funding transaction (initial or splice):

- `remote_funding_pubkey`

The following parameters may vary between splice RBF candidates:

- `channel_value`
- `push_value`
- `funding_outpoint`

It is an error to modify other fields.

**Comment by vincenzopalazzo** [comment]
You are right, I just noted it!

I will add in the milestone for the next release, we should have some room to put the patch before the closing window

**Comment by ksedgwic** [comment]
@devrandom after the rename a `s/ready_channel/setup_channel/g`, right?

**Comment by ksedgwic** [comment]
@vincenzopalazzo I have a partially implemented "sketch" of this in a WIP branch: https://github.com/lightning-signer/c-lightning/commit/be52416df1c06412f23f5c9e6c611394a40e7653

Specifically the amount is not hooked up yet; I like to watch the diagnostics as I hook it up to make sure they make sense ...

The draft (local) PR: https://github.com/lightning-signer/c-lightning/pull/95

NOTE - we don't really merge these Draft PR, we use them to pre-test upstream submissions, clean them up and then eventually hard reset an appropriate `remote-hsmd-` branch/tag onto them

**Comment by vincenzopalazzo** [comment]
I will try to cherrypick your changes and open a PR on mainline by the end of the week, thanks to share the solution
