### ISSUE TITLE
Default fee is 546 satoshi

### ISSUE THREAD

**Issue by Lamar1337** [ElementsProject/lightning#673]
For early adopters out on mainnet, could you kindly adjust the default fee to 1000 mSAT (1 satoshi) for channels? Let's please keep fees as low as possible, and force node owners to manually update this if they'd like to charge more.

Current policy appears like this by default:
"node1_policy": {
        "time_lock_delta": 14,
        "min_htlc": "1000",
        "fee_base_msat": "546000",
        "fee_rate_milli_msat": "10"
    },

Suggested policy:
"node1_policy": {
        "time_lock_delta": 14,
        "min_htlc": "1000",
        "fee_base_msat": "1000",
        "fee_rate_milli_msat": "10"
    },

Thank you! :-)

**Comment by cdecker** [comment]
Sounds good to me ^^
