### ISSUE TITLE
Sendpay failing with WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS

### ISSUE THREAD

**Issue by harvhat** [ElementsProject/lightning#6738]
### Issue and Steps to Reproduce

I am attempting to pay an bolt11 invoice using ```sendpay``` through a specific route to a neighbor node (which is running LND) .  In this case the route is through the direct connecting channel, however the payment always fails with

 code: 203
 message: failed: WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS (reply from remote)

I have tried using lightning-cli and pyln.client with the same results. Using ```pay``` works but I need to be able to dictate a specific route.

the pyln.client code is:

```
from pyln.client import LightningRpc, RpcError
ln = LightningRpc("/home/bitcoin/.lightning/bitcoin/lightning-rpc")

bolt11= "lnbc1...u"

payinv=ln.decodepay(bolt11)
payee = payinv["payee"]
amount_msat = payinv["amount_msat"]
payment_secret = payinv["payment_secret"]
payment_hash = payinv["payment_hash"]

route = ln.getroute(payee, amount_msat, 1, fuzzpercent=0.0)["route"]

try:
    ln.sendpay(route, payment_hash, payment_secret=payment_secret)
    result = ln.waitsendpay(payment_hash)
    if result.get('status') == "complete":
        print("It worked!")
    else:
        print("hmmm")

except RpcError as e:
    print(e.error["code"])
    print(e.error["message"])
```

### `getinfo` output

```
{
   "id": "02f6f9c5d2c55cf36e96daf7cd2a2b8c21a111f0d9def02722b8ce599fb9294f0f",
   "alias": "StreamPipe",
   "color": "35ff00",
   "num_peers": 3,
   "num_pending_channels": 0,
   "num_active_channels": 2,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": "mgb3m4z5goxe6rqv34ud4onkfy25xvqgou3aygmh773lgaxjzv6haqad.onion",
         "port": 9736
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9736
      }
   ],
   "version": "v23.02.2",
   "blockheight": 810255,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/bitcoin/.lightning/bitcoin",
   "our_features": {
      "init": "08a000080269a2",
      "node": "88a000080269a2",
      "channel": "",
      "invoice": "02000000024100"
   }
}
```

**Comment by cdecker** [comment]
This is a misunderstanding of how LN works: to terminate a payment successfully the recipient has to know the matching preimage to the payment hash, as well as a variety of other details. It appears that the node that is receiving the payment is rejecting it because the invoice expired, or the amount in the HTLC does not match the invoiced amount, or the CLTV delta is exceeded. Try looking at the receiving node about what it complains.

**Comment by cdecker** [comment]
Yep, the final node also needs to have a timeout that is in the future. As such please adjust the CLTV expiries in your route to leave approximately 9 - 18 blocks of time for the recipient to also settle, before the refund becomes active.
