### ISSUE TITLE
Difficult to reach agreement of unilateral closing fee

### ISSUE THREAD

**Issue by tsjk** [ElementsProject/lightning#6756]
### Issue and Steps to Reproduce
At times I have several nodes that fail to connect because an agreement of the unilateral closing fee cannot be reached.

The error is visible in the logs with entries of the type:
```
INFO    <remode_node_id>-chan#<sequence_nr>: Peer transient failure in CHANNELD_NORMAL: channeld WARNING: warning channel <channel_id>: update_fee x outside range a-b (currently y)
```

where `x < a`. Often `x < y`, but this doesn't matter.

The log entries appear on connect attempts, which may be either manual or recurring retries.

I realized that in my particular case this means that my node is suggesting a fee that is lower than what the peer can accept. I've seen that, if I call `feerates perkw`, it says that `unilateral_close` equals `x`. However, I have also observed cases where `unilateral_close >> x`, but I guess this means that there is some lag between the current estimates and what is proposed on connection.

I think that it might make sense to introduce some user configuration here together with detection of what the remote peer's bounds are, so that one can set leniency in accordance to one's risk assessment. I for one would accept a higher fee, but might be averse to fees that risk my funds getting stuck on closure. Others might make different judgements.

### `getinfo` output
```
$ lightning-cli getinfo
{
   "id": "<snip>",
   "alias": "<snip>",
   "color": "000000",
   "num_peers": <snip>,
   "num_pending_channels": 0,
   "num_active_channels": <snip>,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "<snip>",
         "port": <snip>
      },
      {
         "type": "torv3",
         "address": "<snip>",
         "port": <snip>
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v23.05.2",
   "blockheight": 811505,
   "network": "bitcoin",
   "fees_collected_msat": <snip>,
   "lightning-dir": "/home/lightning/.lightning/bitcoin",
   "our_features": {
      "init": "08a0880a2269a2",
      "node": "88a0880a2269a2",
      "channel": "",
      "invoice": "02000002024100"
   }
}
```

**Comment by vincenzopalazzo** [comment]
This should be fixed in https://github.com/ElementsProject/lightning/pull/6833
