### ISSUE TITLE
pay: most payments fail

### ISSUE THREAD

**Issue by kilrau** [ElementsProject/lightning#6793]
### Issue and Steps to Reproduce
Most payments (as small as 10000 sats) we are trying to send via CLN's `pay` gRPC are failing with `Reason: Ran out of routes to try after 18 attempts: see paystatus` which is why we are not using CLN for sending payments in production right now, only receiving. Only opening this issue now because we wanted to make sure it's not sth incredibly stupid on our side. Couldn't find anything obvious.

Observations:
- Quite often we see a large amount of mpp shards (like 15) where 1 or 2 fail that make the entire payment fail. This is the most evident thing we are observing - why so many shards?
- Via gRPC CLN gives up trying very fast. Like within seconds.
- The number of attempts sending the same amount to the same destination varies greatly:
```
PaymentPending
PaymentFailed

Reason: Ran out of routes to try after 48 attempts: see `paystatus`
---
PaymentPending
PaymentFailed
Reason: Ran out of routes to try after 61 attempts: see `paystatus`
---
PaymentPending
PaymentFailed
Reason: Ran out of routes to try after 18 attempts: see `paystatus`
```
- Smaller manual payments via `lightning-cli` sometimes work fine, whereas they mostly fail on gRPC (just a hunch)
- Not all gRPC payments fail, some go through, but it's sth like >90% failure rate
- Routing and all other things work fine
- Our CLN node definitely is large and well connected enough by now to reliably send the payments we are trying to send
- Nothing helpful in the logs

We are absolutely clueless on what's going on and if it's simply the amount of mpp shards that make things fail. Any hints appreciated.

### `getinfo` output
```
{
   "id": "02d96eadea3d780104449aca5c93461ce67c1564e2e1d73225fa67dd3b997a6018",
   "alias": "Boltz|CLN",
   "color": "ff9800",
   "num_peers": 88,
   "num_pending_channels": 0,
   "num_active_channels": 80,
   "num_inactive_channels": 1,
   "address": [
      {
         "type": "ipv4",
         "address": "45.86.229.190",
         "port": 9736
      },
      {
         "type": "ipv6",
         "address": "2a10:1fc0:3::270:a9dc",
         "port": 9736
      },
      {
         "type": "torv3",
         "address": "oo5tkbbpgnqjopdjxepyfavx3yemtylgzul67s7zzzxfeeqpde6yr7yd.onion",
         "port": 9736
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9736
      },
      {
         "type": "ipv6",
         "address": "::1",
         "port": 9736
      }
   ],
   "version": "v23.08.1",
   "blockheight": 812772,
   "network": "bitcoin",
   "fees_collected_msat": 80795360,
   "lightning-dir": "/home/bitcoin/.lightning/bitcoin",
   "our_features": {
      "init": "08a0000a8a69a2",
      "node": "88a0000a8a69a2",
      "channel": "",
      "invoice": "02000002024100"
   }
}
```
https://amboss.space/node/02d96eadea3d780104449aca5c93461ce67c1564e2e1d73225fa67dd3b997a6018

**Comment by kilrau** [comment]
Adding questions @michael1011 previously asked on discord:
- is there a way to force it to make it split less aggressively? Like eg only to at most 2 parts
- I am seeing pay terminate and fail wayyy before the limit set by retry_for. Ran out of routes to try after 54 attempts: see paystatus would that error mean that all possible routes have been tried and failed? I can't imagine that to be true, because different attempts of paying the same invoice show different numbers

**Comment by kingonly** [comment]
Are you sending to nodes with private channels?

**Comment by kilrau** [comment]
It's pretty big nodes we tried sending to so far so high probability that these have private channels, yes.

**Comment by kingonly** [comment]
Does the invoice has routing hints is basically what I'm asking.

**Comment by kilrau** [comment]
Yes almost all do. Will do some test using invoices without routing hints.

**Comment by kilrau** [comment]
Update: no difference when paying 100k sats invoices *without routing hints*.
![image](https://github.com/ElementsProject/lightning/assets/19181985/a7dccb45-aa52-4253-9771-0e9f5a927965)

Again the destination is a big node and we are definitely well connected enough to pay 100k sats invoices.

**Comment by kilrau** [comment]
Another test that simply confirms that there is no difference between lightning-cli and grpc (as expected):
- lightning-cli pay <100k sats invoice> - failed after 4 attempts.
```
{
   "code": 210,
   "message": "Ran out of routes to try after 4 attempts: see `paystatus`",
   "attempts": [
      {
         "status": "failed",
         "failreason": "failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)",
         "partid": 0,
         "amount_msat": 100000000
      },
      {
         "status": "failed",
         "failreason": "failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)",
         "partid": 1,
         "amount_msat": 100000000,
         "parent_partid": 0
      },
      {
         "status": "failed",
         "failreason": "failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)",
         "partid": 2,
         "amount_msat": 100000000,
         "parent_partid": 1
      },
      {
         "status": "failed",
         "failreason": "failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)",
         "partid": 3,
         "amount_msat": 100000000,
         "parent_partid": 2
      }
   ]
}
```
`paystatus` also reveals that CLN wanted to try 10 times but it only tried 4 times. I don't know why.
- paying 10x 10k sats invoices via grpc worked flawlessly again.

Again same destination, same 5000 ppm routing fee limit for both.

**Comment by kilrau** [comment]
Test if routing hints play a role: they don't

Same behavior with invoices that contain routing hints:
* paying 100k sats invoice - failed
* paying 10x10k sats invoice - success and again used the same route for all 10 payments

Again same destination, same 5000 ppm routing fee limit for both.

**Comment by kilrau** [comment]
Ran similar tests today and .. it doesn't reproduce as reliably as before. Sometimes the first 100k payments or even larger goes through :/

Same as before destination, same 5000 ppm routing fee limit as before.

Any ideas what else I could try?

**Comment by vincenzopalazzo** [comment]
>Any ideas what else I could try?

When the payment fails it is possible that we choose the wrong path and we keep choosing the wrong one over and over again.

Or is it possible that some channels as disabled? e.g: On chain fee disagreement?

From your messages, I am not able to track down what is happening, but I think it is also difficult from the pay command to track what is going for you due that we hide the complexity under the hood

**Comment by kilrau** [comment]
> choose the wrong path and we keep choosing the wrong one over and over again

I would love to follow exactly which routes are being tried and see with which errors they fail but I simply couldn't find how. How can I?

**Comment by kilrau** [comment]
Just to leave this final comment for anyone from the CLN team picking this up: `pay` in its current form is absolutely unreliable, either give this a proper look or switch it out for something else that ships by default with CLN. Happy to help and share experiences we made with `mpay` :v:

**Comment by vincenzopalazzo** [comment]
@kilrau maybe the reny-pay will be a good target for this, maybe @Lagrang3 is the correct person to explore this path

**Comment by Lagrang3** [comment]
> @kilrau maybe the reny-pay will be a good target for this, maybe @Lagrang3 is the correct person to explore this path

Thanks for bringing this up. @kilrau, I am working on `renepay` a new payment plugin that doesn't produce arbitrary MPPs but instead uses @renepickhardt's algorithm; there is a short description of how this works in the [documentation](https://docs.corelightning.org/reference/lightning-renepay) and the original PR #6376.
Unfortunately, the plugin right now is somewhat unstable. But I am working on it to fix the most evident bugs before release 24.02.

**Comment by s373nZ** [comment]
I just installed Boltz Client to test it out today and ran into this. Here is some information in case it's helpful. It is worth noting that my node has a channel open to `026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2`. @kilrau has informed on Discord that this target node is LND and is usually setup to handle swaps > 1m sats, while there is a CLN node that handles swaps for smaller amounts. My swap is for 100k sats, so it should target the smaller node.

## Observations
1. In the attached `paystatus` JSON log, the `erring_node` is this LND node in the last 3/4 attempts
2. `erring_channel` is different each time
3. Only four attempts where made, although the `strategy` message on the last attempt indicates "Still have 7 attempts left"

Let me know if I can provide more information to help diagnose.

```
boltz@minibolt:/data/boltz$ boltzcli createreverseswap --currency LBTC 100000
You will receive the withdrawal to the specified onchain address
The fees for this service are:
  - Service fee: 0.2%
  - Boltz lockup fee: 276 satoshis
  - Claim fee: 143 satoshis

? Do you want to continue? Yes
Swap Status: swap.created
Swap ID: 7TSb3cusMVrs

Swap Status: swap.created
Error: rpc error: code = Unknown desc = Error calling method Pay: RpcError { code: Some(210), message: "Ran out of routes to try after 4 attempts: see `paystatus`", data: None }
```
[boltz-paystatus-failed.json](https://github.com/ElementsProject/lightning/files/14617222/boltz-paystatus-failed.json)

**Comment by cdecker** [comment]
Thanks for keeping the information flowing. Debugging these is always hard because you wont hear back once you fixed it, so that's a big help.

Did you guys have a chance to test again now that #7188 is merged in `master` to see if it (partially) addresses the issue. @JssDWt found a really well hidden bug that my accounting code had that would result in the channel capacity estimates getting lower and lower as attempts go on.

**Comment by vincenzopalazzo** [comment]
The patch from @JssDWt is included inside the point release? https://github.com/ElementsProject/lightning/releases/tag/v24.02.2

I did not check the diff from the previous one, but if it is included we should advertize inside the release description, right?

**Comment by strnly** [comment]
Cross posting to confirm this is not unique to @kilrau 

https://github.com/ElementsProject/lightning/issues/7180#issuecomment-2147351631

**Comment by urza** [comment]
Some more anecdotal evidence from me. Default `pay` failing lately a lot for me. Installed `mpay ` (after fighting with python a bit:) and can confirm `mpay ` can pay what the default `pay` can't.

**Comment by urza** [comment]
mpay is awesome, can we have it for bolt12 invoices as well? 😅

https://github.com/BoltzExchange/boltz-backend/issues/565

**Comment by cdecker** [comment]
Closing in favor of #7180
