### ISSUE TITLE
WIRE_PERMANENT_NODE_FAILURE while trying to send a payment

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#680]
I posted this in c-lightning irc twice , but got disconnected, so sorry if you are seeing this for the 3rd time.   
It was a transaction over many hops. No one tried to cheat(regtest) so why is there a "revocation" in the log?
Heres the log : 
https://ghostbin.com/paste/ozygd

**Comment by ZmnSCPxj** [comment]
This is a known bug thay should have been fixed by #670.

Revocation is normal. Perhaps you are thinking of punishment/justice transaction? Revocation invalidates an old tx/state, punishment is what you do in response to a revoked tx appearing onchain.

**Comment by Sgt-Miller** [comment]
Ouch, yes, got confused with the terms for a moment.
