### ISSUE TITLE
Closing transaction stuck with low fees

### ISSUE THREAD

**Issue by rachyandco** [ElementsProject/lightning#6801]
### Issue and Steps to Reproduce

I am using C-Lightning within BTCPayServer.

After force closing a Channel, the Channel remains on "ONCHAIN" status in the inactive section. The closing TX has more than 3400 confirmations and the next TX is still pending since 2 weeks with a very low fee (1.01 sat/vB)

Closing TX: https://mempool.space/tx/ff87b41cab20efe34a2b61e51ad78f30460ea2982abe6a12c826186fd09920dd

Follow up TX: https://mempool.space/tx/ff87b41cab20efe34a2b61e51ad78f30460ea2982abe6a12c826186fd09920dd

this UTXO does not show in the 'listfunds' yet.

![Screenshot from 2023-10-22 17-40-43](https://github.com/ElementsProject/lightning/assets/2358699/e0991c65-7740-4024-8951-550e723d97fd)

What can be done?  

Is there a method to generate a TX using this UTXO in order to apply CPFP method? Is there a method to reopen a channel with this unconfirmed UTXO?

'dev-rescan-outputs' is not doing anything either.

### 'listpeerchannels' output

```
         "status": [
            "ONCHAIN:Tracking our own unilateral close",
            "ONCHAIN:1 outputs unresolved: waiting confirmation that we spent DELAYED_OUTPUT_TO_US (eb2e373deeee36b610037dafe8ca401d557d4ca37e2374e33e77884bafd53c3c:1) using OUR_DELAYED_RETURN_TO_WALLET"
         ],

```

### `getinfo` output

```
   "version": "basedon-v23.08",
```

**Comment by rachyandco** [comment]
The gods of bitcoin have spoken, the UTXO finally is available in the node. They needed to be summoned by this issue. Closing the issue.

**Comment by RoZZa4EveR** [comment]
I have the same problem

https://mempool.space/cs/tx/4f107a1fd23324681555eb305f5bae17a64c92876055d5f249417959fbd4fd7b

Can you help?
