### ISSUE TITLE
`connect` stuck eternally when trying to connect to an already connected node

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#681]
`connect` gets stuck forever when      
1) I try to connect to a node which has already been `connect` ed 
or
2) Wrong port is specified.

**Comment by cdecker** [comment]
Thanks for reporting this @Sgt-Miller, the duplicate connect is definitely a bug, for the wrong port, that's not so clear: we re-attempt the connection a number of times if the initial connection fails, so shall we return an error, but connection still succeeds on the next attempt, or shall we wait until a connection attempt goes through?

**Comment by AndWav** [comment]
I got stuck when trying connect to "random" node in https://explorer.acinq.co/

i.e.:
cli/lightning-cli connect 03f0b9924fb2d3b86f1d779dd6599daf9c54440c370b99de024d79154fee6598d5 85.23.163.87
cli/lightning-cli connect 02d1020154c06a4519a05e55e4b8713546fc2765cec2ae1b113d666397cdcd2a81 176.9.89.217

v0.5.2-2016-11-21-1646-g73c31757
