### ISSUE TITLE
Error when using 12 words for lightning-hsmtool generatehsm

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#6847]
`lightning-hsmtool generatehsm` command throws error when I provide the list of 12 space separated words but according to instructions `at least 12 words` should be valid:

`Invalid mnemonic: "endorse steak topple sound ketchup state buyer figure planet moment noise sample"`

**Comment by rustyrussell** [comment]
Bad mneumonic: checksum invalid!
