### ISSUE TITLE
How do I change `riskfactor` in `pay`?

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#685]
`	{ "command" : "pay", "description" : "Send payment in {bolt11} with optional {msatoshi}, {description} and {riskfactor}" }, `         
How do I change `riskfactor` while not changing `msatoshi` from lightning-cli?
Right now I get a "msatoshi parameter unnecessary".    
Thanks.

**Comment by ZmnSCPxj** [comment]
Not possible in current lightning-cli. What is missing is a way to pass a null on lightning-cli. I should probably go do that.
