### ISSUE TITLE
Core lightning fails on Umbrel restart if bitcoin is not synced

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#6924]
Core lightning fails on Umbrel restart if bitcoin is not synced with below error:

```
Core-Lightning starting
2023-12-07T05:47:12.951Z INFO    connectd: Static Tor service onion address: "wz" bound from extern port 9735
2023-12-07T05:48:38.026Z UNUSUAL plugin-bcli: Waiting for bitcoind to warm up...
2023-12-07T05:48:38.035Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
bitcoind has gone backwards from 820093 to 820080 blocks!
```

Reference Issues:
https://community.umbrel.com/t/problem-with-core-lightning-not-working-after-reboot/13908
https://github.com/ElementsProject/cln-application/issues/33

It will be better if CLN waits for bitcoind to sync rather than failing immediately.

**Comment by cdecker** [comment]
Notice that this is not a sync issue, but rather CLN identifying that the `bitcoind` daemon did something that is unlikely to be correct: lost some blocks. If this were just a reorg then `bitcoind` would still show the number of blocks in the branch it switched to, it would never go backwards.

This is likely a `bitcoind` that restarted verifying from scratch, and if CLN were to run against it and wait, it could end up doing so, and being unresponsive for hours if not days at a time.

This is an `abort()` that is on purpose: it's very noisy, in an attempt to grab some human's attention, so they can fix the underlying issue.

I would not consider this a bug.
