### ISSUE TITLE
channeld crash on HTLC failure decode

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#693]
lightning_channeld: Fatal signal 11
0x5639addc674d crashdump
	common/subdaemon.c:30
0x7f4b92e6e7ef ???
	???:0
0x7f4b92f89783 ???
	???:0
0x5639ade06d6d crypto_hash_sha256_update
	crypto_hash/sha256/cp/hash_sha256.c:212
0x5639ade04f08 crypto_auth_hmacsha256_update
	crypto_auth/hmacsha256/cp/hmac_hmacsha256.c:79
0x5639addc4624 compute_hmac
	common/sphinx.c:138
0x5639addc47e6 generate_key
	common/sphinx.c:160
0x5639addc5ce9 wrap_onionreply
	common/sphinx.c:523
0x5639addb422b handle_fail
	channeld/channel.c:2266
0x5639addb464d req_in
	channeld/channel.c:2359
0x5639addb52ff main
	channeld/channel.c:2600
0x7f4b92e593f0 ???
	???:0
0x5639addadfb9 ???
	???:0
0xffffffffffffffff ???
	???:0
lightningd: lightning_gossipd failed (exit status 131), exiting.

Here's the uniquified log:
[out-10859.txt](https://github.com/ElementsProject/lightning/files/1649473/out-10859.txt)

**Comment by kallerosenbaum** [comment]
Happened to me too:

```
lightning_gossipd: Fatal signal 11
0x414dc8 crashdump
        common/subdaemon.c:30
0x7fa7c74f74af ???
        ???:0
0x44cf92 secp256k1_pubkey_load
        src/secp256k1.c:127
0x456baa secp256k1_ecdsa_verify
        src/secp256k1.c:316
0x41ebf3 check_signed_hash
        bitcoin/signature.c:134
0x40f77f check_channel_update
        gossipd/routing.c:546
0x410971 handle_channel_update
        gossipd/routing.c:928
0x403b42 handle_gossip_msg
        gossipd/gossip.c:484
0x404ac7 owner_msg_in
        gossipd/gossip.c:829
0x42e02f next_plan
        ccan/ccan/io/io.c:59
0x42eb06 do_plan
        ccan/ccan/io/io.c:387
0x42eb44 io_ready
        ccan/ccan/io/io.c:397
0x430413 io_loop
        ccan/ccan/io/poll.c:310
0x408600 main
        gossipd/gossip.c:2046
0x7fa7c74e282f ???
        ???:0
0x402828 ???
        ???:0
0xffffffffffffffff ???
        ???:0
2018-02-14T00:29:34.855Z lightning_gossipd(31758): STATUS_FAIL_INTERNAL_ERROR: FATAL SIGNAL 11
lightningd: lightning_gossipd failed (exit status 131), exiting.
```
