### ISSUE TITLE
migrating from c-lightning-REST to clnrest.py

### ISSUE THREAD

**Issue by 4ezb2** [ElementsProject/lightning#6931]
### short bug description:

after migrating to the "new" built-in plugin clnrest.py instead of using [c-lightning-REST](https://github.com/Ride-The-Lightning/c-lightning-REST), my lightningd logs show the following error: 
```
Warning: option `ssl_version` is deprecated and it is ignored. Use ssl_context instead.
```
### my failed attempt to solve issue

changing linenumber 160 from `ssl_version` to `ssl_context` in /lightning/plugins/clnrest/clnrest.py results in this log:
```
Error: Value is not callable: _SSLMethod.PROTOCOL_TLSv1_2
```
### final words
any pointers or help to resolve this issue would be much appreciated. other than this little warning message, my migration was successful thanks to the very helpful documentation provided by you guys.

**Comment by 4ezb2** [comment]
any pointers or help resolving this would be much appreciated

**Comment by ShahanaFarooqui** [comment]
Replacing `ssl_version` with `"ssl": ssl.SSLContext(protocol=ssl.PROTOCOL_TLS_SERVER)` fixes the issue.

Curl example with https: 
```
curl --cacert /path/to/certs/ca.pem --header 'Rune: ZrAK...E9MA==' --request POST --url https://127.0.0.1:3010/v1/getinfo
```

**Comment by 4ezb2** [comment]
Much appreciated. Thanks. Can confirm that your fix works!
