### ISSUE TITLE
grpc: Missing command `AddPsbtOutput`

### ISSUE THREAD

**Issue by dangeross** [ElementsProject/lightning#6986]
Command `AddPsbtOutput` is missing from cln-grpc and cln-rpc.

**Comment by Vayras** [comment]
Hey @dangeross Can I get some info on this issue, I actually would like to work on this one but I would really like to know more about this issue, Thanks

**Comment by ErikDeSmedt** [comment]
Core Lightning exposes a couple of API's. The most important one is the `rpc`-interface which is feature-complete.

The issue mentions `cln-rpc` which is a [rust-crate](https://crates.io/crates/cln-rpc) that can be used to query the `rpc`-interface. The code of this crate is located in the `cln-rpc` folder. The `cln-grpc` that exposes the same API using gRPC. It implements both a client and a server.

The `addpsbtoutput` exists in the rpc-interface but has no counterpart in the `cln-rpc` and the `cln-grpc` crate yet.

Most of the code in the `cln-rpc` and `cln-grpc` crate is auto-generated.
To fix the issue you must

1. Create the appropriate schema in `doc/schemas`. Consult the [docs](https://docs.corelightning.org/reference/lightning-addpsbtoutput) to know what fields you should add. Hint, each field requires an added annotation. The next version of Core Lightning will be `24.05`
2. Run `msggen` to generate the code
- `python contrib/msggen/msggen/__main__.py bundle $PWD/doc/schemas`
- `python contrib/msggen/msggen/__main__.py generate`
3. Review and commit the generated code

**Comment by s373nZ** [comment]
I created an initial PR for this in #7108.
