### ISSUE TITLE
Support named arguments in lightning-cli

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#699]
Some of the commands already have multiple optional arguments which means we currently need to add skip parameters to be able to provide later positional arguments.

Named arguments would allow us to just specify the needed parameters and keep the others default, it can also help disambiguate when positions are ambiguous or we want to ensure we don't break anything with a future update.

**Comment by cdecker** [comment]
Right, should have mentioned `lightning-cli` here.

**Comment by rustyrussell** [comment]
Note that we really want to fix the FIXME in JSON processing where we ignore unknown parameters!

**Comment by ZmnSCPxj** [comment]
Probably use an explicit `--key`option. If set then all arguments must be named with `:` between name and value. Note that we cannot mix positional and named arguments since the former passes in an array while the latter passes in an object.

**Comment by ZmnSCPxj** [comment]
As #829 is already merged in and includes support of named arguments at `lightning-cli`, maybe this can be closed? @cdecker
