### ISSUE TITLE
CLNRest: Unable to subscribe to all events

### ISSUE THREAD

**Issue by bleetube** [ElementsProject/lightning#6994]
I want to use the rest api.  The clnrest plugin throws `Unable to subscribe to all events` on my node.  Versions:

* lightningd v23.11.2
* Python 3.11.6
* bitcoin-cli v26.0.0
* bitcoind (a separate machine running nix-bitcoin) v25.1.0

```
$ lightningd
2024-01-14T17:16:23.927Z INFO    lightningd: v23.11.2
2024-01-14T17:16:26.382Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
Warning: option `ssl_version` is deprecated and it is ignored. Use ssl_context instead.
2024-01-14T17:16:30.049Z INFO    plugin-clnrest.py: REST server running at https://127.0.0.1:3010
2024-01-14T17:16:30.273Z INFO    lightningd: --------------------------------------------------
2024-01-14T17:16:30.273Z INFO    lightningd: Server started with public key ... and lightningd v23.11.2
2024-01-14T17:16:30.696Z UNUSUAL plugin-clnrest.py: Unable to subscribe to all events. Feature available with CLN v23.08 and above: No subscription for block_added found.
2024-01-14T17:16:31.587Z INFO    plugin-clnrest.py: Killing plugin: exited during normal operation
2024-01-14T17:16:31.587Z **BROKEN** plugin-clnrest.py: Plugin marked as important, shutting down lightningd!
```

The plugin appears to hang when run in console:

```
$ python src/lightning/plugins/clnrest/clnrest.py

```

From the Discord chat I've heard that it should print out a message when I run the plugin directly like that, but it does not.

This is probably a red herring, but when I run `strace` on the previous command it looks like it stops normally on a SIGINT. ChatGPT says:

> The script attempts to read from a file descriptor (read(0, 0x5617831e7fd0, 1024)) but gets interrupted (ERESTARTSYS), indicating that the system call was interrupted by a signal (likely SIGINT).

## Environment

I build from source (on Archlinux, btw). I have a virtual environment with the packages from `plugins/clnrest/requirements.txt`. Here is my `.lightning/config`:

```sh
network=bitcoin
bind-addr=127.0.0.1:9735
announce-addr=...:9735
proxy=127.0.0.1:9050
always-use-proxy=false
experimental-onion-messages
experimental-dual-fund
experimental-offers
fetchinvoice-noconnect
clnrest-port=3010
plugin=/home/lightning/src/plugins/prometheus/prometheus.py
```

### `getinfo` output

```json
{
  "id": "...",
  "alias": "...",
  "color": "...",
  "num_peers": X,
  "num_pending_channels": 0,
  "num_active_channels": X,
  "num_inactive_channels": 0,
  "address": [
    {
      "type": "ipv4",
      "address": "x",
      "port": 9735
    }
  ],
  "binding": [
    {
      "type": "ipv4",
      "address": "127.0.0.1",
      "port": 9735
    }
  ],
  "version": "v23.11.2",
  "blockheight": 825775,
  "network": "bitcoin",
  "fees_collected_msat": X,
  "lightning-dir": "/home/lightning/.lightning/bitcoin",
  "our_features": {
    "init": "08a0802a0a69a2",
    "node": "88a0802a0a69a2",
    "channel": "",
    "invoice": "02000022024100"
  },
  "api_version": "0.10.7"
}
```

My workaround will be to continue using c-lightning-REST for now.

**Comment by rustyrussell** [comment]
OK, I suspect you are using an old pyln-client library!  Try `pip install pyln-client`?

**Comment by bleetube** [comment]
At a [fast glance](https://gist.github.com/bleetube/5422e4aeca7d8bb55b679a6cc43f81b9), I think that was it! I needed the `-U` flag to actually upgrade the package. Now I get cli output when I try to run the script. 

I don't quite have clnrest going yet, but I need to do a deeper review of my config before I can close this out.

**Comment by bleetube** [comment]
The root cause seems to be my python environment. I thought I had ruled that out, but then I have managed to get a cli response from the plugin. This indicates it was my fault to begin with. I need to figure out how to get a clean python venv to work from a systemd unit, otherwise I'm going to be running lightningd from a tmux shell lol. I'll close this soon, but I'm pretty sure I did this to myself somehow.

**Comment by bleetube** [comment]
Yep, confirmed it was my python environment. I needed to start fresh.

```shell
lightningd
2024-02-02T02:13:24.571Z INFO    lightningd: v23.11.2
2024-02-02T02:13:26.940Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
Warning: option `ssl_version` is deprecated and it is ignored. Use ssl_context instead.
2024-02-02T02:13:30.142Z INFO    plugin-clnrest.py: REST server running at https://127.0.0.1:3010
```

**Comment by bleetube** [comment]
This is unrelated, but since I mentioned it, I fixed up my systemd service so it will use the clean python venv:
```ini
[Unit]
Description=Core Lightning

[Service]
User=lightning
Group=lightning
EnvironmentFile=/home/lightning/.env
ExecStart=/usr/local/bin/lightningd
RestartSec=300
Restart=always

[Install]
WantedBy=multi-user.target
```

Content of `.env`:
```sh
NOSTR_KEY=...
PATH=/home/lightning/venv/lightning/bin:/home/lightning/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
```

In the past I was trying to just extend the existing `$PATH` by appending it after my python path there, but turns out when systemd sources those vars it does not handle the variable. Thus it has to be completely overwritten afaict.
