### ISSUE TITLE
Can't close channels in state STATE_ERR_INFORMATION_LEAK

### ISSUE THREAD

**Issue by tdaede** [ElementsProject/lightning#70]
```
lightning-cli close 0297377f0d4c18c61a451b8d57525a305f92d3d74638891e6eadf4f3c82c66dc8e
"Peer is already closing: state STATE_ERR_INFORMATION_LEAK"
```
This causes that peer to never be able to connect to me again:
```
OUT-159.203.218.14:6331: Connected out to 159.203.218.14:6331 id 032282512a55842274728d58d371e1186a558071d6de509e32e5d6e765b0d3da7b, changing prefix
032282512a55842274728d58d371e1186a558071d6de509e32e5d6e765b0d3da7b: reconnect ack 4 > 0
032282512a55842274728d58d371e1186a558071d6de509e32e5d6e765b0d3da7b: Sending PKT_ERROR: invalid ack
032282512a55842274728d58d371e1186a558071d6de509e32e5d6e765b0d3da7b: Peer breakdown: nothing to do
032282512a55842274728d58d371e1186a558071d6de509e32e5d6e765b0d3da7b: Disconnected
```

**Comment by rustyrussell** [comment]
Thomas Daede <notifications@github.com> writes:
> ```
> lightning-cli close 0297377f0d4c18c61a451b8d57525a305f92d3d74638891e6eadf4f3c82c66dc8e
> "Peer is already closing: state STATE_ERR_INFORMATION_LEAK"
> ```

That's because you should never be able to get into state
ERR_INFORMATION_LEAK.

This is probably a WONT_FIX. How did you get there though?

Thanks,
Rusty.

**Comment by tdaede** [comment]
I opened a channel and made one transaction. Unfortunately it only entered that state sometime later. Hopefully if I reproduce it I can get some better info. The sending node was also the same node I uploaded the dir for earlier (including privkeys).

If WONTFIXing this, it might be nice to at least have some sort of network message that says "your node is banned" or something.

**Comment by cdecker** [comment]
Closing since the legacy daemon has been removed.
