### ISSUE TITLE
Docs:  why is it that amount_msat is optional in listsendpay

### ISSUE THREAD

**Issue by Lagrang3** [ElementsProject/lightning#7001]
According to the documentation of `listsendpay` the field `amount_msat` is optional.

I don’t see why this should be optional.

Can anyone tell me under which circumstance `amount_msat` is not present in the RPC response? or/and  how can I interpret if the field `amount_msat` is missing from the response?
I mean from a developer point of view, if I need to know the value of `amount_msat` from the `listsendpay` call, and I get nothing, what can I deduce from this?

**Comment by vincenzopalazzo** [comment]
I think @cdecker know the correct answer :)
