### ISSUE TITLE
Retries of revoke_and_ack need to use explicit hsmd_revoke_commitment_tx

### ISSUE THREAD

**Issue by ksedgwic** [ElementsProject/lightning#7026]
### Issue and Steps to Reproduce

This is related to https://github.com/ElementsProject/lightning/pull/7010

Currently `make_revocation_msg` uses `get_per_commitment_point` to fetch the needed old commitment secret and next point.  But in the following case this causes an error (https://gitlab.com/lightning-signer/validating-lightning-signer/-/issues/450):

1. CLN attempts to send `hsmd_revoke_commitment_tx` to the signer but everything is restarted before the signer sees it.
2. On restart CLN retries the `revoke_and_ack`, but uses `get_per_commitment_point` to get the old secret.  The signer fails with:
```
get_per_commitment_secret: cannot revoke commitment_number 4 when next_holder_commit_num is 5
```

Instead, if channeld uses `hsmd_revoke_commitment_tx` in `make_revocation_msg` (which returns the needed values) all is well.  The `hsmd_revoke_commitment_tx` call is idempotent.

**Comment by vincenzopalazzo** [comment]
I think this is fixed in https://github.com/ElementsProject/lightning/pull/7027
