### ISSUE TITLE
Unable to estimate various fees

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#703]
Latest version as of a bit ago.  Top of log file:

commit 1616fcbffe137d9db18cfd396ec7ee1fbf365ae5
Author: frennkie <mail@rhab.de>
Date:   Sun Jan 21 10:40:17 2018 +0100

    change getchannels to listchannels

Debug output:
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Adding block 00000000000000000030029aa22bfd9b20265e965f8cb3563f4b0e66a7e862e6
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Adding block 0000000000000000005074f80fce04395dbd9a2af086b96437e31591a9810a14
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee
lightningd(4111): Unable to estimate CONSERVATIVE/2 fee
lightningd(4111): Unable to estimate ECONOMICAL/4 fee
lightningd(4111): Unable to estimate ECONOMICAL/100 fee

**Comment by alaniz3** [comment]
Yeah I have the same issue.

**Comment by cdecker** [comment]
How long has `bitcoind` been running? It might refuse to estimate fees if it hasn't had a chance to see the current fee levels on the network, e.g., when it has only just been started. Usually this goes away after a few hours.

**Comment by alaniz3** [comment]
I've been running bitcoind on the VM I'm doing my testing on for only a few hours after sync. Makes sense. Cheers!

**Comment by cdecker** [comment]
I'm not actually sure how long it takes for the fee estimation algorithm to warm up, so let me know when it does ^^

**Comment by alaniz3** [comment]
Those messages seem to have already disappeared from my debug log, I started syncing bitcoind on testnet about 3-4h ago on a fresh VM, had it fully synced about 1.5-2h ago. Hope it helps!

**Comment by vedran6** [comment]
I tried using the `--default-fee-rate ` option to manually feed an estimate to `lightningd`, but it didn't seem to do anything (it kept complaining about being unable to estimate fees). Is there a way to bootstrap this information somehow?

**Comment by Ulmo** [comment]
I think it's able to estimate fees now on mine.  I think you're right:  bitcoind needed time.

**Comment by cdecker** [comment]
> Is there a way to bootstrap this information somehow?

Not currently, `bitcoind` just needs some time to learn about the mempool size and the fee distribution in the mempool to make adequate predictions.

It'll continue to check for estimates (and complain) even though `--default-fee-rate` was set, that's on purpose :-)

**Comment by sidaudhi** [comment]
Been having this issue for the past 4 hours now. 
![image](https://user-images.githubusercontent.com/6974736/52523126-ea1c4480-2cb3-11e9-837f-9d055fda4ea3.png)
Could there be a RAM / CPU issue? Both are within very decent limits.
