### ISSUE TITLE
Large amount of forwarding and routing logs on my node which I suspect are locking up c-lightning and causing my server to run out of RAM

### ISSUE THREAD

**Issue by clarketowson** [ElementsProject/lightning#7045]
Hi Everyone,

I run a lightning node CHILLYCALENDAR which has been operational since mid to late 2021 and has over 100 channels opened: 

https://lightningnetwork.plus/nodes/025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693

I was running BTCPay Server 1.3.5 with c-lightning on the node and I updated it this morning to the latest version of BTCPay Server v1.12.5+a86165ac0 and the upgrade was successful.  It did however take quite some time (almost 15 minutes) to pull the postgres database.

These are the versions I now have installed of the various software that comes with BTCPay Server:

btcpayserver/docker-gen:0.10.7                           
btcpayserver/btcpayserver:1.12.5                        
saubyk/c-lightning-rest:0.10.6                          
btcpayserver/lightning:v23.08                           
btcpayserver/docker-gen:0.10.7                           
btcpayserver/bitcoin:26.0                                
nicolasdorier/nbxplorer:2.5.0                            
btcpayserver/postgres:13.13                              
btcpayserver/tor:0.4.8.10                                                                                        
shahanafarooqui/rtl:0.14.1                               
nginx:1.25.3-bookworm    

Prior to the upgrade I was experiencing significant delays whilst running the bitcoin-lightning-cli.sh command.  I suspected this was caused by the very large amount of forwarding and routing logs my node has generated over the last 3 years since being online.  Prior to the upgrade I backed up BTCPay so I could restore it if anything went wrong.  The resulting backup file was 5.3GB in size.  Mostly log files I suspect.  

I have a cron job which copies the lightning database to another location.  The lightningd.sqlite3 database file is 6.4GB in size.

After the upgrade this morning I went into RTL and started attempting to send funds in and out and RTL had a spinning ball/wheel and sat there when attempting to decode the lightning invoice.  On chain payments also locked up.  I have not attempted much command line use of c-lightning yet to see if doing those tasks via the command line will lock up the server but I suspect it will because it did before I upgraded the server.

The issues are so bad that after the upgrade the server slowed down so much it ran out of RAM and I needed to reboot it.

This is the last command I was able to run before the server became completely unresponsive:

free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi        14Gi       127Mi       115Mi       318Mi        67Mi
Swap:         7.7Gi       7.7Gi          0B

Upon reboot all looks good:

free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi       4.1Gi       459Mi       194Mi        10Gi        10Gi
Swap:         7.7Gi       129Mi       7.6Gi

I have an additional 2 BTCPay Servers.  I do not experience any issues on those servers.  The only difference is they have been up for a much shorter time than my primary server and their log files are much less.

Is there a way to effectively prune the postgres database that stores all the log files from c-lightning?  If so how may I go about doing that in a safe manner?

Do you have any other techniques I could implement?

How does c-lightning process the routing and forwarding logs under the hood?  

Any advice is very much appreciated.  I'm sure it will help other node operators as well who are also running busy nodes.

With Best Regards,

Clarke

Clarke Towson, BCMS (Bachelor of Computer & Mathematical Science)
CEO
INTJ Billing
 
m: +61 432 359 166
a: 7 Cullen Court Spotswood Victoria 3015 AUSTRALIA
w: https://intjbilling.com/
e: [clarketowson@intjbilling.com](mailto:clarketowson@intjbilling.com)

Bitcoin Lightning Network Node Name: CHILLYCALENDAR 
Node Public Key: 025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693 
Status Page: https://intjbilling.com/INTJBillingStatusPage.php 

amboss.space: https://amboss.space/node/025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693 
1ml.com: https://1ml.com/node/025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693
Lightning network+: https://lightningnetwork.plus/nodes/025124c73ef7ecf527e0114ead02a0cc6e3ecbc0c99474ee3f5506c4503b089693

**Comment by grubles** [comment]
You may want to give `autoclean-once` a try. 

```
$ lightning-cli help autoclean-once
```

**Comment by clarketowson** [comment]
Thanks @grubles that looks like exactly what I need to do.

Best Wishes,

Clarke

**Comment by clarketowson** [comment]
The command worked.  My RTL is much faster now and I can send out payments from my node.

Thanks so much for the advice!

Best Regards,

Clarke

**Comment by grubles** [comment]
Happy to help!

**Comment by vincenzopalazzo** [comment]
Closing as solved
