### ISSUE TITLE
plugin-autoclean: succeededforwards del failed - couldn't find the forward

### ISSUE THREAD

**Issue by overcoin** [ElementsProject/lightning#7048]
## Getinfo:
 "version": "v23.11.1"

## In the log file:
UNUSUAL plugin-autoclean: succeededforwards del failed: {\"code\":1401,\"message\":\"Could not find that forward\"}

## Cleanup control options in config file:
autoclean-succeededforwards-age=86400
autoclean-failedforwards-age=86400
autoclean-succeededpays-age=86400
autoclean-failedpays-age=86400
autoclean-paidinvoices-age=86400
autoclean-expiredinvoices-age=86400

Why is autoclean plugin trying to clean a forward that doesn't exist?

**Comment by rustyrussell** [comment]
This is because very old forwards didn't have all fields, so we can end up trying to delete it twice.  Should be fine, if it keeps happening we'll need to track exactly what's going on...
