### ISSUE TITLE
If you fund a channel before 6 confirms

### ISSUE THREAD

**Issue by tinspin** [ElementsProject/lightning#707]
The transaction will not broadcast, but lightningd thinks it has and your fund_tx will be CHANNELD_AWAITING_LOCKIN forever.

**Comment by otaviobps** [comment]
Not true, I funded more than 3 channels before 6 confirmations and all of them are CHANNELD_NORMAL.

One of the channels I funded is with CHANNELD_AWAITING_LOCKIN status, but another person is having the same problem with the same node, so the error is on this node side.

**Comment by cdecker** [comment]
`fundchannel` should provide you with a transaction (hexserialized) and a txid, do you have them somewhere, so we can check whether it was broadcast and confirmed?

**Comment by tinspin** [comment]
{ "tx" : "0200000000010124b820f32df566a8ef87e98e4f6891b97af11657b6b6a69a30b2e760cc98b0a900000000171600142f48667baedd5d556958a442d6f3ccfebf899077ffffffff029873000000000000160014b5a764aabf529933f1d02294c5ef85eab9092c5650c30000000000002200206ad56b11af188fbc94c478752494ca285c5ad6b6bec27d1bf7e378bc5e4826d00247304402202be3d58c3c9aba04d3929437b14c2a0f753b83f6cd6f22e99cca076777f4947802204bf34d591c9500eedfd0f4f8149f18c6b97b366933fd7c32d8b3cb0ddfcb1f7e0121033b8c1df4bcc32fcdef8a53f78f648321693016fbfcfa00677c8c706d4c6f12a800000000", "txid" : "d20a349e0eb1afa4fb82d1727abf7d7aa0e38fe78771ab0dc1b3d87f44be740f" }

**Comment by tinspin** [comment]
Ok, maybe it's the node I'm connecting to... but it doesn't matter if a bad node can make my lightningd think it has less funds than it has on the blockchain then stuff is seriously broken.

**Comment by cdecker** [comment]
The transaction was not broadcast for some reason. What's the config of your `bitcoind` (removing the auth info)?

**Comment by tinspin** [comment]
server=1
rpcuser=XXX
rpcpassword=XXX
rpctimeout=30
rpcport=8332
rpcallowip=192.168.1.0/24
rpcallowip=127.0.0.1
walletnotify=/home/XXX/notify.sh
prune=550

**Comment by cdecker** [comment]
Hm, strange, the last time this happened `bitcoind` was configured not to broadcast transactions, but that doesn't seem to be the case here. Anyway, the tx is now waiting to be confirmed and once you have 2 confirmations the channel should move to `CHANNELD_NORMAL`.

**Comment by jb55** [comment]
can confirm my funding tx's no longer broadcast... not sure if something was changed?

**Comment by jb55** [comment]
ugh now it does. ghost of Schrödinger is haunting me

**Comment by jb55** [comment]
So the issue isn't that it's not broadcasting. I noticed it created a funding transaction from inputs which were not in the blockchain:

```
02000000000101d4b113cad34b83f87851b9d33589dbbc32aa02ae072c6888207a28cc68a269dd0100000000ffffffff02404b4c00000000002200200e1e57f81d6ed51e08540a68fa30f35ced0fa74237c1f2830fac4d797028b5a2e99c4d00000000001600144a914fada6bfbf7e047cb53927e1491dd039763b02473044022041b0dbc12f7684edb1084962740e59cf1f49a4541176a55f1baf9d9e00bd932102202a1cb9110b7c60952c0183735e16a15cc4c1432af9d2fbeb703f54790defd991012102691a6c6060662c35441ecb0897e8acd72d7ca13414ed0680f7244d18d5f7a44900000000
```

**Comment by jb55** [comment]
Perhaps we could have better error handling here to detect failed broadcasts and to act accordingly...

**Comment by tinspin** [comment]
My transaction now has 10 confirms but my lightningd is still clueless... also I transferred more to the lightningd on the same address that it hasn't seen either. How do lightningd and bitcoind communicate?

**Comment by cdecker** [comment]
The code has changed quite substantially in the meantime. Most of the time this was due to either being disconnected, or the other endpoint lagging behind on the blockchain.
