### ISSUE TITLE
Transaction with `blockheight: 0`

### ISSUE THREAD

**Issue by aaronbarnardsound** [ElementsProject/lightning#7070]
### Issue and Steps to Reproduce
Sometimes a transaction in the response from the `listtransactions` rpc has a `blockheight` value of `0`. I have seen this for transactions that do not exist when looking up on a block explorer (replaced?), but for my most recent transaction initiated via the `withdraw` rpc method it has `blockheight: 0` and yet when I check the tx on a block explorer it has a block height of `829916`.

### `getinfo` output

```json
{
   "id": "<ID",
   "alias": "<ALIAS>",
   "color": "<Color>"
   "version": "v23.08.1-modded",
   "blockheight": 830347,
   "network": "bitcoin",
   "lightning-dir": "/mnt/ssd/lightning/bitcoin",
   "our_features": {
      "init": "08a0802a0269a2",
      "node": "88a0802a0269a2",
      "channel": "",
      "invoice": "02000022024100"
   }
}
```

**Comment by cdecker** [comment]
This usually just means that CLN has not yet processed the block that confirmed the transaction, and therefore it shows the unconfirmed state indicated by `"blockheight": 0`/
