### ISSUE TITLE
hsmd: hsmd_sign_any_cannouncement and HSM_MIN_VERSION inconsistency

### ISSUE THREAD

**Issue by ksedgwic** [ElementsProject/lightning#7074]
- `hsmd_sign_any_cannouncement_req` was added in `v24.02`
- it isn't set in `hsmd_init_reply_v4:capabilities`
- it seems it is called unconditionally?

Seems it either should be set in capabilities and called conditionally or `HSM_MIN_VERSION` should be increased to 5.

**Comment by rustyrussell** [comment]
ISTR it was introduced at the same time as another change,  but we should add it to capabilites to be neat?

**Comment by vincenzopalazzo** [comment]
>ISTR it was introduced at the same time as another change, but we should add it to capabilites to be neat?

I agree, and I also think that increasing the hsmd version would be good?

**Comment by ksedgwic** [comment]
> I agree, and I also think that increasing the hsmd version would be good?

The version is already bumped in this release (from 4 to 5) for the explicit revoke.  Wouldn't think we needed to bump it again.

**Comment by ksedgwic** [comment]
> ISTR it was introduced at the same time as another change, but we should add it to capabilites to be neat?

Adding to capabilities make sense.  But can the calls to it be conditional?  If not then we need to live with increasing `MIN_HSMD_VERSION`, no?

**Comment by rustyrussell** [comment]
It's not clear what we do if the hsm can't sign announcements.  We could complain and ask them to upgrade, otherwise we have to have a workaround by handing it to channeld to ask it to ask hsmd, which would be notably ugly.

I think you're right, MIN_HSMD_VERSION=5 it is?  Is that OK for you?

**Comment by ksedgwic** [comment]
> I think you're right, MIN_HSMD_VERSION=5 it is? Is that OK for you?

Yes, that increasing the version seems fine.
