### ISSUE TITLE
gci: Consider adding a nightly CI workflow for reprobuilds

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#7117]
It would be very helpful to have a nightly workflow in our
actions. This could be run over night (well, someone's night),
ensuring that the reprobuilds always work. In addition it alleviates
the problem release captains face during every release:

 1. The developer tags the release
 2. Then uploads the tag
 3. Builds the reprobuild, but during the build something got changed
 4. The version string now is something like `v24.02-modded` due to
	the dirty tree.
	
The CI could tell us ahead of time if a given reprobuild would result
in such a broken version string, and we would be able to always
cross-check the reprobuilds, avoiding accidental back and forth during
the release.

**Comment by BitcoinJiuJitsu** [comment]
Open CLN bounty on this:
https://community.sphinx.chat/p/clt2n32tu2rjujq1jn6g/bounties/2158/2

**Comment by s373nZ** [comment]
@BitcoinJiuJitsu I just submitted PR #7651 in hopes of winning this bounty. Please feel free to assign to me.
