### ISSUE TITLE
"Bad gossip order: could not find channel" issue is not resolved

### ISSUE THREAD

**Issue by overcoin** [ElementsProject/lightning#7153]
### Issue and Steps to Reproduce
Log file is full of lines like the following one after upgrade:
024-03-16T18:46:06.744Z UNUSUAL lightningd: Bad gossip order: could not find channel xxxxxx for peer's channel update

### `getinfo` output
"version": "v24.02.1-modded"

Confirming issue https://github.com/ElementsProject/lightning/issues/7152 for it was a clean build not related to docker from the checked out latest tag v24.02.1.

I'd also propose additional key to getinfo output named "db_version" containing  sqlite/postgres and the respective version number.

**Comment by king-11** [comment]
Does that mean the clean build issue is still existent in `v24.02.1`

**Comment by cdecker** [comment]
No, this is the peer sending us gossip out of order, there is no way to fix it on our end, the message is there to explain why some messages get dropped. The fix is on the sender implementation.

**Comment by cdecker** [comment]
@king-11 @overcoin as for the `-modded` suffix, you need to `poetry run make clean default` and you should get a clean build. That results in a clean repository before building. If after the build there are files in `git status` let us know and well fixed that again.

**Comment by overcoin** [comment]
**~/lightning$ poetry run make clean default**

RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at ~/.local/lib/python3.9/site-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]

**~/lightning$ git status**

HEAD detached at v24.02.2
nothing to commit, working tree clean
---
Looks like I have to recreate the python/poetry environment and reinstall dependencies respectively?
