### ISSUE TITLE
blinded paths: no final cltv delta included for multi-hop paths

### ISSUE THREAD

**Issue by carlaKC** [ElementsProject/lightning#7179]
### Issue and Steps to Reproduce
Multi-hop blinded paths created to cover private channels don't seem to include a `final_cltv_expiry` in their `cltv_expiry_delta`. 

With the following setup, where LND1's `cltv_delta` is 80, I get an invoice with `cltv_expiry_delta` = 80 (so, no final cltv expiry.
`LND0 -- LND1 --(private)-- CL0`

Perhaps I'm misunderstanding the output of this API and you need to add your own final delta here (?), but we should be including a min expiry [per the example in the spec](https://github.com/lightning/bolts/blob/master/proposals/route-blinding.md#blinded-payments). 

### Command Output

Create an offer on CL0, fetch an invoice with CL1: 
```
{
   "type": "bolt12 invoice",
   "offer_id": "ccd52145c40b1780a3bc7d45469981a4b8793a5d09fa2b07c24bd934502284f2",
   "offer_chains": [
      "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f"
   ],
   "offer_amount_msat": 1000,
   "offer_description": "test1",
   "offer_node_id": "034f36602f6374bc0915788f57637f4cf7ad62a6ed90158a0c36fc7c707f4fd3fa",
   "invreq_metadata": "f9454f9ecdca605812aa76c547730701",
   "invreq_payer_id": "0262ed7e8770e1c3ab83fc0105c8ff74c0950e3c5c82971a3307cb14be1fb51ab8",
   "invreq_chain": "06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f",
   "invoice_paths": [
      {
         "first_node_id": "03aab370bca1ffb15a0ee104adc6e63b49be071e3c499ca8b0e5593273e432cd0a",
         "blinding": "02b07feea9ea3e13887bcebac795848b4982fa7bd6dfc078ace704a9cdb2123200",
         "payinfo": {
            "fee_base_msat": 1000,
            "fee_proportional_millionths": 1,
            "cltv_expiry_delta": 80,
            "features": ""
         },
         "path": [
            {
               "blinded_node_id": "0254ed835ba7bd2fe06ee356142e8a3516415b9b4f499e53be084be93aae094322",
               "encrypted_recipient_data": "335b322b6869dfcafb29214db9a9e8e0db10a047a63ab8a1065c9a2a3ea3254ba6aac1428c1bafc655a374b3"
            },
            {
               "blinded_node_id": "0204a66b079aa1687e7aaf0587b461079db4c67f37a82131bd31750375c35fb813",
               "encrypted_recipient_data": "f0288a6752da750956874d18a4c7345a5bdd891cc57119d557600dbf7f4baacd2a6f763db699c099774c4972327f61d6614a"
            }
         ]
      }
   ],
   "invoice_created_at": 1711545572,
   "invoice_relative_expiry": 7200,
   "invoice_payment_hash": "8c30000df5aee4faaa8cdb7c1b1d369fbd7ee9d0e1c395c41c00d53eb69ff1ca",
   "invoice_amount_msat": 1000,
   "invoice_node_id": "034f36602f6374bc0915788f57637f4cf7ad62a6ed90158a0c36fc7c707f4fd3fa",
   "signature": "aa42a339593cb6d3e90cc35dad11480491674b34189bcf963bbe1827b9ac9e14acc3593f2f08df441eb5cc23104a4f1ba8aae083dd84ba942f6fca550d6eab76",
   "valid": true
}
```

**Comment by rustyrussell** [comment]
I'm not sure what API you are using here?  We don't add blinded paths to offers at all, so a private-only node is unreachable.

It's been years since I've touched this code except for minor refactors.  I really need to swap that all back in...

**Comment by carlaKC** [comment]
> I'm not sure what API you are using here? We don't add blinded paths to offers at all, so a private-only node is unreachable.

I'm manually deconstructing the offers flow to get a blinded path to test against LND's sending/forwarding of blinded paths. I create the offer on one CLN node, manually connect another CLN node and then use `fetchinvoice` to get a bolt 12 invoice for the offer which LND can pay (by decoding it and grabbing the blinding point). 

Should be reproducible by setting up a node with only private channels then fetching an invoice for an offer!

**Comment by vincenzopalazzo** [comment]
>Should be reproducible by setting up a node with only private channels then fetching an invoice for an offer!

if you have a testnet node I can help to do interop with cln offers

**Comment by carlaKC** [comment]
> if you have a testnet node I can help to do interop with cln offers

I just did all this in regtest / local dev setup, don't think testnet is necessary?

**Comment by vincenzopalazzo** [comment]
>I just did all this in regtest / local dev setup, don't think testnet is necessary?

well generally no but if you want try to do it with my node yes :)
