### ISSUE TITLE
Update contrib/lightning-pay to accept bolt11s

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#718]
Following #633:

1. Still use getroute, sendpay to prompt routing fees
2. Parse id, amount and payment hash from decodepay and pass to getroute/sendpay

I believe bolt11s have route hints so we can use that as well?

**Comment by ZmnSCPxj** [comment]
Yes, but `getroute` does not accept that yet, so for now, acceptable to ignore route hints.

**Comment by cdecker** [comment]
Well, `pay` ignores them as well, since it'd require us to temporarily add edges to our view of the network, so the behavior will effectively be the same :-)

**Comment by izgzhen** [comment]
I'd like to help on this issue :)

**Comment by ZmnSCPxj** [comment]
Note that #1088 will change `pay` and `sendpay` drastically, so please check that continuously as you do this....

**Comment by izgzhen** [comment]
I wonder if it would be better to rewrite `lightning-pay` in Python as part of `pylightning` instead?

BASH is not so readable and parse JSON using BASH sounds too awkward for me ...

**Comment by ZmnSCPxj** [comment]
Can be done. Shell script is not really intended as a real programming language and is borderline Turing tarpit.
