### ISSUE TITLE
Upgrading **BROKEN** wallet/wallet.c:2594: INSERT INTO channels

### ISSUE THREAD

**Issue by JavierRSobrino** [ElementsProject/lightning#7183]
After upgrading from 23.11.2 to 24.02.1, I obtain the following error:

```
lightningd_build  | 2024-03-28T17:27:39.815321629Z Error executing statement: wallet/wallet.c:2594: INSERT INTO channels (  peer_id, first_blocknum, id, revocation_basepoint_local, payment_basepoint_local, htlc_basepoint_local, delayed_payment_basepoint_local, funding_pubkey_local, require_confirm_inputs_remote, require_confirm_inputs_local) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);: UNIQUE constraint failed: channels.id
lightningd_build  | 2024-03-28T17:27:39.815333462Z 2024-03-28T17:27:39.815Z **BROKEN** lightningd: Error executing statement: wallet/wallet.c:2594: INSERT INTO channels (  peer_id, first_blocknum, id, revocation_basepoint_local, payment_basepoint_local, htlc_basepoint_local, delayed_payment_basepoint_local, funding_pubkey_local, require_confirm_inputs_remote, require_confirm_inputs_local) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);: UNIQUE constraint failed: channels.id

```

I had to downgrade and restore the backup I made just before updating in order for my node to continue operating.

**Comment by nakoshi-satamoto** [comment]
This might be related, see this and if this solution works for you

https://github.com/ElementsProject/lightning/issues/7162

**Comment by adi2011** [comment]
Hi @JavierRSobrino, can you please check the logs and see if this error occurs after your node logs "Detected a channel with lost state, Entering Recovery mode!"?

**Comment by KBPROC** [comment]
I have also encountered this issue after an OS update and restart. 
Searched and found 'lightningd --disable-plugin=recover' which has my node running again.
The issue appears to be well understood but I'm wondering what risk there is running with recover disabled?
I did generate a debug log file but suspect the next release will include a fix. Please advise. Thanks.

**BROKEN** lightningd: Error executing statement: wallet/wallet.c:2594: INSERT INTO channels (  peer_id, first_blocknum, id, revocation_basepoint_local, payment_basepoint_local, htlc_basepoint_local, delayed_payment_basepoint_local, funding_pubkey_local, require_confirm_inputs_remote, require_confirm_inputs_local) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);: UNIQUE constraint failed: channels.id
Error executing statement: wallet/wallet.c:2594: INSERT INTO channels (  peer_id, first_blocknum, id, revocation_basepoint_local, payment_basepoint_local, htlc_basepoint_local, delayed_payment_basepoint_local, funding_pubkey_local, require_confirm_inputs_remote, require_confirm_inputs_local) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);: UNIQUE constraint failed: channels.id
Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.

**Comment by adi2011** [comment]
This should be resolved now.
@JavierRSobrino @KBPROC, Pls do lmk if this error `INSERT INTO channels ( peer_id, first_blocknum, id, revocation_basepoint_local, payment_basepoint_local, htlc_basepoint_local, delayed_payment_basepoint_local...` still persists.

**Comment by vincenzopalazzo** [comment]
@adi2011 If understood correctly we merge the code that fixed this issue right? So maybe we can close the issue?

**Comment by adi2011** [comment]
Yes @vincenzopalazzo, this should be resolved now...

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/ElementsProject/lightning/pull/7216
