### ISSUE TITLE
schema: routes missing from decode/decodepay generated code

### ISSUE THREAD

**Issue by daywalker90** [ElementsProject/lightning#7186]
The schemas for `decode` and `decodepay` contain code for `routes` but the generated code (e.g. in cln-rpc/grpc) for `decode`/`decodepay` responses does not have the `routes` field. I don't see why and also can't find a related error when generating.

https://github.com/ElementsProject/lightning/blob/master/doc/schemas/lightning-decode.json
https://github.com/ElementsProject/lightning/blob/master/doc/schemas/lightning-decodepay.json

**Comment by daywalker90** [comment]
Ok i've seen they are excluded in OverridePatch but i want them still :)

**Comment by cdecker** [comment]
Sure, we can add them, they were just a bit too nested, and we expected to be able to generalize it with the result of the `getroute` command IIRC.

The goal is to add them, we just need to find the time to do so :-)

**Comment by endothermicdev** [comment]
I believe this was closed with #7317.
