### ISSUE TITLE
**BROKEN** 02b21ca992bf95e3f324302265ad86cec24f36166fd7afca44efa0809aaa8b25c5-chan#312: Cannot broadcast our commitment tx: they have a future one

### ISSUE THREAD

**Issue by Rassah** [ElementsProject/lightning#7187]
### Issue and Steps to Reproduce
Channel was force closed months ago. During node start logs show:
**BROKEN** 02b21ca992bf95e3f324302265ad86cec24f36166fd7afca44efa0809aaa8b25c5-chan#312: Cannot broadcast our commitment tx: they have a future one

The closing transaction has been mined back in January. 
lightning-cli listclosedchannels 02b21ca992bf95e3f324302265ad86cec24f36166fd7afca44efa0809aaa8b25c5 result is
{
   "closedchannels": []
}

lightning-cli listpeers 02b21ca992bf95e3f324302265ad86cec24f36166fd7afca44efa0809aaa8b25c5 result includes
"state_changes": [
                  {
                     "timestamp": "2023-10-26T14:15:45.455Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_NORMAL",
                     "cause": "remote",
                     "message": "Lockin complete"
                  },
                  {
                     "timestamp": "2024-01-09T11:08:32.320Z",
                     "old_state": "CHANNELD_NORMAL",
                     "new_state": "AWAITING_UNILATERAL",
                     "cause": "local",
                     "message": "channeld: sent Awaiting unilateral close"
                  },
                  {
                     "timestamp": "2024-01-09T11:33:49.191Z",
                     "old_state": "AWAITING_UNILATERAL",
                     "new_state": "FUNDING_SPEND_SEEN",
                     "cause": "local",
                     "message": "Onchain funding spend"
                  },
                  {
                     "timestamp": "2024-01-09T11:33:49.323Z",
                     "old_state": "FUNDING_SPEND_SEEN",
                     "new_state": "ONCHAIN",
                     "cause": "local",
                     "message": "Onchain init reply"
                  },
                  {
                     "timestamp": "2024-01-09T12:08:20.360Z",
                     "old_state": "ONCHAIN",
                     "new_state": "FUNDING_SPEND_SEEN",
                     "cause": "local",
                     "message": "Onchain funding spend"
                  },

with last part repeating over and over up through today. At the very end is
 "status": [
                  "ONCHAIN:Owning subdaemon onchaind died (61952)"
               ],

using bitcoin-cli Iistfunds, the funds are still listed under "channels" with the same "peer_id"
"connected": false,
"state": "ONCHAIN",
"our_amount_msat": 1559141212,

So it seems CLN thinks the funds are still stuck in a channel somehow, even though the closing transaction has been mined already.

How do I recover the funds in this channel?

**Comment by nakoshi-satamoto** [comment]
This might be related, see this and if this solution works for you

https://github.com/ElementsProject/lightning/issues/7162

**Comment by Rassah** [comment]
I am able to start my Lightning node fine without issues. And using lightning-cli withdraw all only collected the funds I already had available. The funds in the closed channel are still locked, even though the closing transaction confirmed at the beginning of January. I'm afraid that if I forget about this channel, such as with the dev command, these funds may become unrecoverable.

**Comment by rustyrussell** [comment]
Did you restore your database at some point?  That's the only way we should ever believe our peer is ahead of us.

If you lose your database, you may not be able to recover funds in theory, but in modern setups it is possible to do so.  (And you should get a big nasty message if we cannot).

Is there anything from `onchaind` in your logs?

**Comment by Rassah** [comment]
Database was not restored. It was a new node set up from scratch that has been running for almost a year. I didn't find any onchaind in the logs, but I'm not sure where all but the last 10,000 entries are. This is CLN running on Start9

**Comment by rustyrussell** [comment]
Hmm, can you restart with log-level=debug and send me the logs?  Email rusty@blockstream.com works if you prefer...

**Comment by Rassah** [comment]
I emailed the log file directly. Hoping you can help. There's a lot of money locked in that node.

**Comment by rustyrussell** [comment]
Thanks.  This is the recovery plugin, @adi2011.  Looks like it's misbehaving?

**Comment by adi2011** [comment]
Hmm there is one more issue similar to this.  Can you please forward the log file so that I can have a look at it. @rustyrussell

**Comment by Rassah** [comment]
I was able to launch the node with "disable-plugin=recover" in the config
file. My issue now is all the channels that were foreclosed a long time
ago, some in January, that are still haning there and not releasing funds.
Any ideas for how to get that money back?

Michael Tozoni

**Comment by cdecker** [comment]
There seems to be nothing actionable here, as the ID collision in recovery is already being tracked / fixed in another issue. Closing this for now.
