### ISSUE TITLE
lightning-cli fails to connect to lightningd when using --lightningdir on daemon

### ISSUE THREAD

**Issue by ianthius** [ElementsProject/lightning#719]
I created a lightning node then later shut it down and made a new one. I renamed the old .lightning folder to .lightning_old and later tried to bring up the old node by using --lightningdir to bring it up. However, I could not connect to the lightningd with the lightning-cli. Apprently I was supposed to use --lightningdir on the cli as well but didn't know this.

@rustyrussell Perhaps a better error message would be prudent to send folks in the right direction here.

**Comment by cdecker** [comment]
The option is called `--lightning-dir` and needs to match between the two tools, otherwise the cli won't be able to connect.
