### ISSUE TITLE
AWAITING_UNILATERAL

### ISSUE THREAD

**Issue by btcpuertorico** [ElementsProject/lightning#7195]
Hello.

Had two channel opening attempts using Zeus where fees were set to low because of a bug. Had to RBF to try to get the transaction confirmed but it didn't seem to do it on time and now are on AWAITING_UNILATERAL for quite a while. 

"our_to_self_delay": 144

already expired.

**Comment by cdecker** [comment]
The `AWAITING_UNILATERAL` state means the funds never really left your wallet, and the reservation will already have expired as well. As such there is nothing to do here, you can ignore that entry, it is there only to ensure we have the data to close should the funding transaction be unexpectedly confirmed late.

**Comment by btcpuertorico** [comment]
So why they show as closing and the funds are unavailable? 

![image](https://github.com/ElementsProject/lightning/assets/63824372/2f99ee2f-ab4a-43ca-a904-f57a8b6bda0c)
