### ISSUE TITLE
`v24.02.2` lacks signature and data files

### ISSUE THREAD

**Issue by scgbckbone** [ElementsProject/lightning#7199]
Release artifacts cannot be verified

**Comment by scgbckbone** [comment]
https://github.com/ElementsProject/lightning/releases/tag/v24.02.2

**Comment by liv-io** [comment]
Just ran into the same issue.
The `SHA256SUMS-v24.02.1` and ` SHA256SUMS-v24.02.1.asc` files are missing.

I cannot write @cdecker a message over Twitter/X.

**Comment by cdecker** [comment]
Apologies for the delay, I was travelling, and the build was taking a bit longer than expected. The files have been added now.
