### ISSUE TITLE
Installing from source v24.02.2 and running into conflicts on Debian 12

### ISSUE THREAD

**Issue by overcoin** [ElementsProject/lightning#7203]
### Issue and Steps to Reproduce
uname -a
Linux fullnode 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux

**Following installation docs and getting dependancies:**
pip3 install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in ./.local/lib/python3.9/site-packages (24.0)

pip3 install --user poetry
...
Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Installing collected packages: packaging
  Attempting uninstall: packaging
    Found existing installation: packaging 23.1
    Uninstalling packaging-23.1:
      Successfully uninstalled packaging-23.1
Successfully installed packaging-20.9

**To build cln to just install a tagged or master version you can use the following commands:**
pip3 install mako
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mako in /usr/lib/python3/dist-packages (1.1.3)

pip3 install -r plugins/clnrest/requirements.txt
...
Installing collected packages: packaging
  Attempting uninstall: packaging
    Found existing installation: packaging 20.9
    Uninstalling packaging-20.9:
      Successfully uninstalled packaging-20.9
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.13 requires packaging<21.0,>=20.4, but you have packaging 23.1 which is incompatible.

The result is a modded version and many **BROKEN** and UNUSUAL lightningd: Bad gossip order lines in the log.

### `getinfo` output
"version": "v24.02.2-modded"

**Comment by daywalker90** [comment]
my recommended way to build a clean cln on debian 12:


`git clone https://github.com/ElementsProject/lightning`

or make sure your worktree is clean!

`git checkout v24.02.2`

`python -m venv venv` or `source venv/bin/activate` if a virtual env already exists

`pip3 install --upgrade pip poetry`
`poetry install`

if you have rust installed:
`export RUST_PROFILE=release`

`./configure`
`make`
check version:
`lightningd/lightningd --version`
then switch to root (little quirk i discovered where you can't just run `sudo make install`):
`sudo su`
`make install`

**Comment by overcoin** [comment]
Thanks for sharing this @daywalker90.

Using python venv avoids poetry dependency conflict and "modded" issue is now resolved. One note though. Instead of `python -m venv venv ` in Debian correct command is `sudo apt install virtualenv` if venv has never been used before and then `python3 -m venv venv`.

Deleting gossip_store is not a solution. Bad gossip order lines still create clutter on the log file. Obviously, this has to be addressed in gossip 2.0 development.

BTW, thank you for the summars pluigin. It is a very useful tool.

**Comment by daywalker90** [comment]
Thanks :)
Yeah me and some others noticed some gossip log entries aswell. I only meant to delete gossip_store if it causes a crash.

**Comment by ShahanaFarooqui** [comment]
Closing it as no further action is required.
