### ISSUE TITLE
GRPC: include reference to a channel in listpays and listinvoices responses

### ISSUE THREAD

**Issue by Jhoyola** [ElementsProject/lightning#7204]
In Torq we are trying keep track of latest events of each channel. When there is a forward, we can link it to a channel since there is _out_channel_ and _in_channel_ in _listforwards_.

However in **_listpays_** and **_listinvoices_** any information about the channel used is missing. So we would either need the short_channel_id or HTLCs of the payment/invoice in the response of _listpays_ and _listinvoices_.

**Comment by cdecker** [comment]
There is no 1-to-1 relationship between payment and a channel. A single payment may be related to any number of HTLCs, from 0 for a local payment, to hundreds if we needed to split a very large payment. So the best we can do is: call list pays, extract the payment hash, and then listhtlcs to filter the HTLCs matching the payment hash. That is likely better done outside of the API as the overhead would be quite considerable if we were to do it on every list pays or list invoices call.

**Comment by Jhoyola** [comment]
Okkay, thanks. I think we considered that approach before. We are just a bit worried about the load of listhtlcs for channels with very large amounts of traffic, since that call does not have paging.

**Comment by cdecker** [comment]
Hm, I think in that case we should rather teach listhtlcs to filter by payment hash. That'd minimize the load, and works like a left join.

**Comment by Jhoyola** [comment]
That would be great!

**Comment by cdecker** [comment]
Ok, I will open a new issue for that specifically 👍
