### ISSUE TITLE
Unparsable offer: invalid bech32 string: invalid token

### ISSUE THREAD

**Issue by ibmgeniuz** [ElementsProject/lightning#7205]
### Issue
I tried to fetch the details of an invoice and I got the error `ValueError: Error calling /cln.Node/FetchInvoice: status: Unknown, message: "Error calling method FetchInvoice: RpcError { code: Some(-32602), message: \"offer: Unparsable offer: invalid bech32 string: invalid token '\\\"bc1u1pnpp57zpp5rhncywvwhnsc52tnrwspt0f38ps59g6su9wf0nqwpd8g39tjkmmsdqqcqzzsxqyz5vqsp55wvwe5mfqw0xa60se0ma4vs3c4mftkfv4exng2j392wfvv8ah7pq9qyyssqnutj2wsjv4u4uej6p964387j5s9g4utjuuh20g3ea0wj745sg00xw7nzeq5yw8fkwqvpm437xhgs3lly7wcxv5dy4tx47sw7dz8z30gphn9wg5\\\"'\", data: None }", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 08 Apr 2024 20:01:44 GMT", "content-length": "0"} }`  My code for getting the invoice is:

### Steps to reproduce
- Install the `glclient` for python
- Create or retrieve a node 
- Either create an invoice using the created node or any external lightning wallet
- Get the `bolt11` from the invoice. Eg: `lnbc1u1pnp2z30sp52k69x0x8rh94292cparwa5aj6f8qmqymq9al9sj6qahtd46wrduqpp5upxhgj2p85vggq9glqlwulmwg570pscs22ckkupy5x3y2s903lhqdpd23jhxarfdenjqenjdakjqcnfw33k76twyphx2arhdaexkxqyjw5qcqzys9qxpqysgqm65s4c930q6uh2m5l92qvjxcvulsezplp6uv3jf83ejm475d8fwngsskw49wm68chz6p9j7q49ess20kw5d2spns3ca6nl7pvurv88cqu0hg8f`
- See code below for fetching the invoice using the `fetch_invoice` function from the node. I supplied the `bolt11` from the step above as the value for offer.  See error above. 

```python
def fetch_invoice(self, bolt11: str) -> Invoice:
    return self.node.fetch_invoice(offer=bolt11)
```

### What I tried 
- I thought the `offer` parameter may be something different from `bolt11`. I decided to supply the `bolt11` to the code `pay` function of the node below to see if I would get a different error. However, I got the same error. Indicating the probably `offer` and `bolt11` are the same. 
- I cut the `ln` part of the bech32 as another way to test. Still didn't work. Hence the error starting with `bc1...`. The error happens with normal bolt11 starting with `lnbc1...` too. 

```python
def pay_invoice(self, bolt11: str, amount_msat: Optional[clnpb.Amount] = None, maxfee: Optional[clnpb.Amount] = None, maxfeepercent: Optional[float] = None):
    return self.node.pay(bolt11=bolt11, amount_msat=amount_msat, maxfee=maxfee, maxfeepercent=maxfeepercent)
```

### What I need help with
I need help with the proper format to supply value for `offer` and `bolt11` for `fetch_invoice` and `pay` functions respectively.
I am aware that the error shows 

Thank you!

**Comment by daywalker90** [comment]
`offer` and `fetch_invoice`  are bolt12

what you have is a valid `bolt11` invoice. (Don't remove the `ln`)

I doubt you got the exact same error when supplying the `bolt11` to `pay`. My guess is you provided an `amount_msat` when the `bolt11` you posted already contains an `amount_msat` and therefore you must not pass the `amount_msat` to `pay`. Or it is because you specified both `maxfee` and `maxfeepercent` which is also not allowed.
See documentation for `pay` here:
https://docs.corelightning.org/reference/lightning-pay

**Comment by ibmgeniuz** [comment]
@daywalker90 I actually got the same error. Also as you can see from the parameters `amount_msat`, `maxfee` and `maxfeepercent` are all optional and I didn't supply them in my test. I supplied only the `bolt11` and got the error.

" `offer` and `fetch_invoice` are bolt12 " : Is there a way to convert bolt11 to bolt12. Is it needed before I can fetch the details of the invoice? Or that will mean I cannot use the function? If I can't use it, what will be the correct way to fetch a `bolt11` invoice details? 

" (Don't remove the `ln` ) " : That was just a desperate attempt to see if cutting some part of the invoice will work but in almost all my tests I had `ln` intact.

**Comment by daywalker90** [comment]
I'm not aware of a way to convert a bolt11 to bolt12. 
The reason why bolt12 exists is basically because you _can't_ just "fetch" a bolt11 :). You would have to ask that peer via a 3rd party way to give you an invoice. Today there is LNURL for example to do that.

The error you got from `fetchinvoice` was:
`invalid bech32 string: invalid token`

When i decode your bolt11 strings i get the data just fine:
your first bolt11:

```
lightning-cli decodepay lnbc1u1pnpp57zpp5rhncywvwhnsc52tnrwspt0f38ps59g6su9wf0nqwpd8g39tjkmmsdqqcqzzsxqyz5vqsp55wvwe5mfqw0xa60se0ma4vs3c4mftkfv4exng2j392wfvv8ah7pq9qyyssqnutj2wsjv4u4uej6p964387j5s9g4utjuuh20g3ea0wj745sg00xw7nzeq5yw8fkwqvpm437xhgs3lly7wcxv5dy4tx47sw7dz8z30gphn9wg5
{
   "currency": "bc",
   "created_at": 1712378818,
   "expiry": 86400,
   "payee": "0324ba2392e25bff76abd0b1f7e4b53b5f82aa53fddc3419b051b6c801db9e2247",
   "amount_msat": 100000,
   "description": "",
   "min_final_cltv_expiry": 80,
   "payment_secret": "a398ecd369039e6ee9f0cbf7dab211c57695d92cae4d342a512a9c9630fdbf82",
   "features": "024200",
   "payment_hash": "1de782398ebce18a29731ba015bd31386142a350e15c97cc0e0b4e889572b6f7",
   "signature": "30450221009f17253a1265795e665a0975589fd2a40a8af172e72ea7a239ebdd2f569043de0220677a62c828471d3670181dd63e35d108ffe4f3b06651a4aacd5f41de688e28bd"
}
```

your second bolt11:
```
lightning-cli decodepay lnbc1u1pnp2z30sp52k69x0x8rh94292cparwa5aj6f8qmqymq9al9sj6qahtd46wrduqpp5upxhgj2p85vggq9glqlwulmwg570pscs22ckkupy5x3y2s903lhqdpd23jhxarfdenjqenjdakjqcnfw33k76twyphx2arhdaexkxqyjw5qcqzys9qxpqysgqm65s4c930q6uh2m5l92qvjxcvulsezplp6uv3jf83ejm475d8fwngsskw49wm68chz6p9j7q49ess20kw5d2spns3ca6nl7pvurv88cqu0hg8f
{
   "currency": "bc",
   "created_at": 1712654895,
   "expiry": 604800,
   "payee": "03862ea8511d397dd720f37a0c38d3fae58db7509e1ae76a5e61056db022960008",
   "amount_msat": 100000,
   "description": "Testing from bitcoin network",
   "min_final_cltv_expiry": 144,
   "payment_secret": "55b4533cc71dcb5515580f46eed3b2d24e0d809b017bf2c25a076eb6d74e1b78",
   "features": "02024100",
   "payment_hash": "e04d7449413d188400a8f83eee7f6e453cf0c31052b16b7024a1a24540af8fee",
   "signature": "3045022100dea90ae0b17835cbab74f9540648d8673f0c883f0eb8c8c9278e65bafa8d3a5d0220344216754aede8f8b8b412cbc0a9730829f6751aa806708e3ba9ffc16706c39f"
}
```

So there must be another problem in your code

**Comment by ibmgeniuz** [comment]
@daywalker90 You actually indirectly answered my question by providing the response you got from my bolt11. I chose the wrong function. Thus `fetchinvoice` instead of `decodepay` because `decodepay` seem to do what I expected. I assumed that `fetchinvoice` rather got the details of the invoice. Thank you for the response.

**Comment by ibmgeniuz** [comment]
@daywalker90 I will try the `pay` function with the bolt to see what I get. If that works, then I believe this issue is resolved.
