### ISSUE TITLE
AWAITING_UNILATERAL

### ISSUE THREAD

**Issue by btcpuertorico** [ElementsProject/lightning#7207]
Funds NOT available

Hello.

Had two channel opening attempts using Zeus where fees were set to low because of a bug. Had to RBF to try to get the transaction confirmed but it didn't seem to do it on time and now are on AWAITING_UNILATERAL for quite a while. 

"our_to_self_delay": 144

already expired.

_Originally posted by @btcpuertorico in https://github.com/ElementsProject/lightning/issues/7195_

**Comment by cdecker** [comment]
Due to the high fee environment some channel closes and sweeps may take a long time. Can you share the output of `listpeerchannels`? That'd allow us to verify that indeed it just is a slow sweep confirmation.

**Comment by btcpuertorico** [comment]
listpeerchannels{
   "channels": [
      {
         "peer_id": "02fe153690061fa27049bae0faa236ddb95df98c514416a350449c24a8018851dc",
         "peer_connected": true,
         "reestablished": true,
         "channel_type": {
            "bits": [
               12,
               46
            ],
            "names": [
               "static_remotekey/even",
               "scid_alias/even"
            ]
         },
         "updates": {
            "local": {
               "htlc_minimum_msat": 0,
               "htlc_maximum_msat": 990000000,
               "cltv_expiry_delta": 34,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10
            },
            "remote": {
               "htlc_minimum_msat": 0,
               "htlc_maximum_msat": 990000000,
               "cltv_expiry_delta": 34,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10
            }
         },
         "last_stable_connection": 1718357441,
         "state": "CHANNELD_NORMAL",
         "scratch_txid": "7d979cec273e0b47c140a60fe6847c6497e8f72a336b6486daadbbefa078a5b3",
         "last_tx_fee_msat": 5901000,
         "lost_state": false,
         "feerate": {
            "perkw": 8150,
            "perkb": 32600
         },
         "owner": "channeld",
         "short_channel_id": "833613x1353x0",
         "direction": 1,
         "channel_id": "0ee04a6d3566f0d5e6b2105a6e54c028dbcecb1613b0f9f9bc44814740c82544",
         "funding_txid": "4425c840478144bcf9f9b01316cbcedb28c0546e5a10b2e6d5f066356d4ae00e",
         "funding_outnum": 0,
         "close_to_addr": "bc1pctsgvudjwdx65a2cdgpvn6x75lwmf9497mmxdh9007cg6u9qwsyss5jdg4",
         "close_to": "5120c2e08671b2734daa75586a02c9e8dea7ddb496a5f6f666dcaf7fb08d70a07409",
         "private": true,
         "opener": "local",
         "alias": {
            "local": "12005789x12781420x51796",
            "remote": "940170x834855x10384"
         },
         "features": [
            "option_static_remotekey",
            "option_scid_alias"
         ],
         "funding": {
            "local_funds_msat": 1000000000,
            "remote_funds_msat": 0,
            "pushed_msat": 0
         },
         "to_us_msat": 394114852,
         "min_to_us_msat": 394114852,
         "max_to_us_msat": 1000000000,
         "total_msat": 1000000000,
         "fee_base_msat": 1000,
         "fee_proportional_millionths": 10,
         "dust_limit_msat": 546000,
         "max_total_htlc_in_msat": 18446744073709551615,
         "their_reserve_msat": 10000000,
         "our_reserve_msat": 10000000,
         "spendable_msat": 366706852,
         "receivable_msat": 595885148,
         "minimum_htlc_in_msat": 0,
         "minimum_htlc_out_msat": 0,
         "maximum_htlc_out_msat": 990000000,
         "their_to_self_delay": 144,
         "our_to_self_delay": 144,
         "max_accepted_htlcs": 30,
         "state_changes": [
            {
               "timestamp": "2024-03-07T18:49:07.756Z",
               "old_state": "CHANNELD_AWAITING_LOCKIN",
               "new_state": "CHANNELD_NORMAL",
               "cause": "user",
               "message": "Lockin complete"
            }
         ],
         "status": [
            "CHANNELD_NORMAL:Reconnected, and reestablished.",
            "CHANNELD_NORMAL:Channel ready for use."
         ],
         "in_payments_offered": 6,
         "in_offered_msat": 1461090074,
         "in_payments_fulfilled": 1,
         "in_fulfilled_msat": 254086731,
         "out_payments_offered": 168,
         "out_offered_msat": 11195540393,
         "out_payments_fulfilled": 21,
         "out_fulfilled_msat": 859971879,
         "htlcs": []
      },
      {
         "peer_id": "02bfe975eb18b29455ee6d5c3a2dc6c8097cb4d9a38fb440ded1e464b33ccc9f60",
         "peer_connected": true,
         "reestablished": false,
         "channel_type": {
            "bits": [
               12
            ],
            "names": [
               "static_remotekey/even"
            ]
         },
         "updates": {
            "local": {
               "htlc_minimum_msat": 1,
               "htlc_maximum_msat": 702499000,
               "cltv_expiry_delta": 34,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10
            }
         },
         "state": "AWAITING_UNILATERAL",
         "scratch_txid": "58669fdc154f67ca71331b1eeaeda7dc495390e9d99d341a1f1f43854295a1d2",
         "last_tx_fee_msat": 183000,
         "lost_state": false,
         "feerate": {
            "perkw": 253,
            "perkb": 1012
         },
         "direction": 1,
         "channel_id": "309ce87eacc6893dd5833515cbb9d0780cde32b69535e39d97a6e126e812d399",
         "funding_txid": "99d312e826e1a6979de33595b632de0c78d0b9cb153583d53d89c6ac7ee89c30",
         "funding_outnum": 0,
         "close_to_addr": "bc1p4cc3a7vkpvlytvpg8rauewjtx2j9lxsm8x0xegale9wkvp4235aq3krldt",
         "close_to": "5120ae311ef9960b3e45b02838fbccba4b32a45f9a1b399e6ca3bfc95d6606aa8d3a",
         "private": true,
         "opener": "local",
         "closer": "local",
         "alias": {
            "local": "3528519x2857932x9576"
         },
         "features": [
            "option_static_remotekey"
         ],
         "funding": {
            "local_funds_msat": 709594000,
            "remote_funds_msat": 0,
            "pushed_msat": 0
         },
         "to_us_msat": 709594000,
         "min_to_us_msat": 709594000,
         "max_to_us_msat": 709594000,
         "total_msat": 709594000,
         "fee_base_msat": 1000,
         "fee_proportional_millionths": 10,
         "dust_limit_msat": 546000,
         "max_total_htlc_in_msat": 18446744073709551615,
         "their_reserve_msat": 7095000,
         "our_reserve_msat": 7095000,
         "spendable_msat": 701959000,
         "receivable_msat": 0,
         "minimum_htlc_in_msat": 0,
         "minimum_htlc_out_msat": 1,
         "maximum_htlc_out_msat": 702499000,
         "their_to_self_delay": 144,
         "our_to_self_delay": 144,
         "max_accepted_htlcs": 30,
         "state_changes": [
            {
               "timestamp": "2024-02-28T11:46:18.525Z",
               "old_state": "CHANNELD_AWAITING_LOCKIN",
               "new_state": "CHANNELD_SHUTTING_DOWN",
               "cause": "user",
               "message": "User or plugin invoked close command"
            },
            {
               "timestamp": "2024-03-01T10:20:52.737Z",
               "old_state": "CHANNELD_SHUTTING_DOWN",
               "new_state": "AWAITING_UNILATERAL",
               "cause": "user",
               "message": "Forcibly closed by `close` command timeout"
            }
         ],
         "status": [
            "Loaded from database"
         ],
         "in_payments_offered": 0,
         "in_offered_msat": 0,
         "in_payments_fulfilled": 0,
         "in_fulfilled_msat": 0,
         "out_payments_offered": 0,
         "out_offered_msat": 0,
         "out_payments_fulfilled": 0,
         "out_fulfilled_msat": 0,
         "htlcs": []
      },
      {
         "peer_id": "02bfe975eb18b29455ee6d5c3a2dc6c8097cb4d9a38fb440ded1e464b33ccc9f60",
         "peer_connected": true,
         "reestablished": true,
         "channel_type": {
            "bits": [
               12,
               22
            ],
            "names": [
               "static_remotekey/even",
               "anchors_zero_fee_htlc_tx/even"
            ]
         },
         "updates": {
            "local": {
               "htlc_minimum_msat": 1,
               "htlc_maximum_msat": 990000000,
               "cltv_expiry_delta": 34,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10
            },
            "remote": {
               "htlc_minimum_msat": 1000,
               "htlc_maximum_msat": 1000000000,
               "cltv_expiry_delta": 80,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 1
            }
         },
         "last_stable_connection": 1718357441,
         "state": "CHANNELD_NORMAL",
         "scratch_txid": "f0e17e0ea4ac5b9497eed1e475d73b7905559afc6908495eb587f3e0d329e869",
         "last_tx_fee_msat": 6514000,
         "lost_state": false,
         "feerate": {
            "perkw": 5795,
            "perkb": 23180
         },
         "owner": "channeld",
         "short_channel_id": "842364x2487x0",
         "direction": 1,
         "channel_id": "48c61b147c15bb751a09063c54654903567fa9040687a8a4abd5107d69c80954",
         "funding_txid": "5409c8697d10d5aba4a8870604a97f56034965543c06091a75bb157c141bc648",
         "funding_outnum": 0,
         "close_to_addr": "bc1pwkwsp5cfqvqazaggczr2tax270kw2wn60ckz59078ht4m5rnnqlqsjyuac",
         "close_to": "5120759d00d3090301d17508c086a5f4caf3ece53a7a7e2c2a15fe3dd75dd073983e",
         "private": false,
         "opener": "local",
         "alias": {
            "local": "10918710x10989750x26524"
         },
         "features": [
            "option_static_remotekey",
            "option_anchors_zero_fee_htlc_tx"
         ],
         "funding": {
            "local_funds_msat": 1000000000,
            "remote_funds_msat": 0,
            "pushed_msat": 0
         },
         "to_us_msat": 21661783,
         "min_to_us_msat": 21661783,
         "max_to_us_msat": 1000000000,
         "total_msat": 1000000000,
         "fee_base_msat": 1000,
         "fee_proportional_millionths": 10,
         "dust_limit_msat": 546000,
         "max_total_htlc_in_msat": 18446744073709551615,
         "their_reserve_msat": 10000000,
         "our_reserve_msat": 10000000,
         "spendable_msat": 0,
         "receivable_msat": 968338217,
         "minimum_htlc_in_msat": 0,
         "minimum_htlc_out_msat": 1,
         "maximum_htlc_out_msat": 990000000,
         "their_to_self_delay": 144,
         "our_to_self_delay": 144,
         "max_accepted_htlcs": 30,
         "state_changes": [
            {
               "timestamp": "2024-05-06T19:49:52.320Z",
               "old_state": "CHANNELD_AWAITING_LOCKIN",
               "new_state": "CHANNELD_NORMAL",
               "cause": "user",
               "message": "Lockin complete"
            }
         ],
         "status": [
            "CHANNELD_NORMAL:Reconnected, and reestablished.",
            "CHANNELD_NORMAL:Channel ready for use."
         ],
         "in_payments_offered": 14,
         "in_offered_msat": 2972572223,
         "in_payments_fulfilled": 2,
         "in_fulfilled_msat": 20001000,
         "out_payments_offered": 124,
         "out_offered_msat": 7988440877,
         "out_payments_fulfilled": 10,
         "out_fulfilled_msat": 998339217,
         "htlcs": []
      },
      {
         "peer_id": "031b301307574bbe9b9ac7b79cbe1700e31e544513eae0b5d7497483083f99e581",
         "peer_connected": false,
         "channel_type": {
            "bits": [
               12,
               46
            ],
            "names": [
               "static_remotekey/even",
               "scid_alias/even"
            ]
         },
         "updates": {
            "local": {
               "htlc_minimum_msat": 1,
               "htlc_maximum_msat": 990000000,
               "cltv_expiry_delta": 34,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10
            },
            "remote": {
               "htlc_minimum_msat": 1,
               "htlc_maximum_msat": 990000000,
               "cltv_expiry_delta": 34,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10
            }
         },
         "last_stable_connection": 1713328875,
         "state": "AWAITING_UNILATERAL",
         "scratch_txid": "62fe302511566e9d3c4d302a2c6ecee3ce7f991a308359da6327168be11a2e46",
         "last_tx_fee_msat": 183000,
         "lost_state": false,
         "feerate": {
            "perkw": 253,
            "perkb": 1012
         },
         "short_channel_id": "832034x2735x0",
         "direction": 1,
         "channel_id": "f473943e8ceffe855c7c1d2b55e9bfb2b88131ba40b410a335483b3857b9ab52",
         "funding_txid": "52abb957383b4835a310b440ba3181b8b2bfe9552b1d7c5c85feef8c3e9473f4",
         "funding_outnum": 0,
         "close_to_addr": "bc1ptr2dsfa7zf9rlv04skq8w0gnm5px6s3vhzm7zwgr6sywwhfpjcjqxl6j2h",
         "close_to": "512058d4d827be124a3fb1f58580773d13dd026d422cb8b7e13903d408e75d219624",
         "private": true,
         "opener": "local",
         "alias": {
            "local": "2636238x3832832x56796",
            "remote": "16000000x0x5796"
         },
         "features": [
            "option_static_remotekey",
            "option_scid_alias"
         ],
         "funding": {
            "local_funds_msat": 1000000000,
            "remote_funds_msat": 0,
            "pushed_msat": 0
         },
         "to_us_msat": 1000000000,
         "min_to_us_msat": 1000000000,
         "max_to_us_msat": 1000000000,
         "total_msat": 1000000000,
         "fee_base_msat": 1000,
         "fee_proportional_millionths": 10,
         "dust_limit_msat": 546000,
         "max_total_htlc_in_msat": 18446744073709551615,
         "their_reserve_msat": 10000000,
         "our_reserve_msat": 10000000,
         "spendable_msat": 873918730,
         "receivable_msat": 0,
         "minimum_htlc_in_msat": 0,
         "minimum_htlc_out_msat": 1,
         "maximum_htlc_out_msat": 990000000,
         "their_to_self_delay": 144,
         "our_to_self_delay": 144,
         "max_accepted_htlcs": 30,
         "state_changes": [
            {
               "timestamp": "2024-02-25T21:19:10.796Z",
               "old_state": "CHANNELD_AWAITING_LOCKIN",
               "new_state": "CHANNELD_NORMAL",
               "cause": "user",
               "message": "Lockin complete"
            },
            {
               "timestamp": "2024-02-29T18:11:49.660Z",
               "old_state": "CHANNELD_NORMAL",
               "new_state": "AWAITING_UNILATERAL",
               "cause": "protocol",
               "message": "Offered HTLC 1 RCVD_ADD_REVOCATION cltv 832567 hit deadline"
            }
         ],
         "status": [
            "Loaded from database"
         ],
         "in_payments_offered": 0,
         "in_offered_msat": 0,
         "in_payments_fulfilled": 0,
         "in_fulfilled_msat": 0,
         "out_payments_offered": 2,
         "out_offered_msat": 115367270,
         "out_payments_fulfilled": 0,
         "out_fulfilled_msat": 0,
         "htlcs": [
            {
               "direction": "out",
               "id": 1,
               "amount_msat": 100179565,
               "expiry": 832567,
               "payment_hash": "866b4ed12b7bef43d9cb56f73e9b6a58ea41003cea32119ca59d5ddddc2ae254",
               "state": "RCVD_ADD_REVOCATION"
            },
            {
               "direction": "out",
               "id": 0,
               "amount_msat": 15187705,
               "expiry": 832857,
               "payment_hash": "00c7159b2f5dd5d6fdcac7c50eccefcc90272cad679fb94c5cadd0a344836bcf",
               "state": "RCVD_ADD_REVOCATION"
            }
         ]
      },
      {
         "peer_id": "026ec3e3438308519a75ca4496822a6c1e229174fbcaadeeb174704c377112c331",
         "peer_connected": true,
         "reestablished": true,
         "channel_type": {
            "bits": [
               12
            ],
            "names": [
               "static_remotekey/even"
            ]
         },
         "updates": {
            "local": {
               "htlc_minimum_msat": 1,
               "htlc_maximum_msat": 990000000,
               "cltv_expiry_delta": 34,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10
            },
            "remote": {
               "htlc_minimum_msat": 1000,
               "htlc_maximum_msat": 1000000000,
               "cltv_expiry_delta": 100,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 168
            }
         },
         "last_stable_connection": 1718357445,
         "state": "CHANNELD_NORMAL",
         "scratch_txid": "444475d159da2a9d086740c3ce06d315e752faff17bb9bbe454e827fab3040ed",
         "last_tx_fee_msat": 5901000,
         "lost_state": false,
         "feerate": {
            "perkw": 8150,
            "perkb": 32600
         },
         "owner": "channeld",
         "short_channel_id": "824400x2215x0",
         "direction": 1,
         "channel_id": "7dfef995db881302f745eec6e8ce652c6b26cbfa778dddf8a626fb2a58429d1c",
         "funding_txid": "1c9d42582afb26a6f8dd8d77facb266b2c65cee8c6ee45f7021388db95f9fe7d",
         "funding_outnum": 0,
         "close_to_addr": "bc1ps42p9wkz3djqe0y0aqak7mmt5dgh9d59dc6su3usqkqztmgpd7gsm0su4d",
         "close_to": "5120855412bac28b640cbc8fe83b6f6f6ba35172b6856e350e4790058025ed016f91",
         "private": false,
         "opener": "local",
         "alias": {
            "local": "10217276x11001179x52947",
            "remote": "16000000x0x143"
         },
         "features": [
            "option_static_remotekey"
         ],
         "funding": {
            "local_funds_msat": 1000000000,
            "remote_funds_msat": 0,
            "pushed_msat": 0
         },
         "to_us_msat": 399102261,
         "min_to_us_msat": 27062609,
         "max_to_us_msat": 1000000000,
         "total_msat": 1000000000,
         "fee_base_msat": 1000,
         "fee_proportional_millionths": 10,
         "dust_limit_msat": 546000,
         "max_total_htlc_in_msat": 18446744073709551615,
         "their_reserve_msat": 10000000,
         "our_reserve_msat": 10000000,
         "spendable_msat": 371694261,
         "receivable_msat": 590897739,
         "minimum_htlc_in_msat": 0,
         "minimum_htlc_out_msat": 1,
         "maximum_htlc_out_msat": 990000000,
         "their_to_self_delay": 144,
         "our_to_self_delay": 144,
         "max_accepted_htlcs": 30,
         "state_changes": [
            {
               "timestamp": "2024-01-05T00:30:29.474Z",
               "old_state": "CHANNELD_AWAITING_LOCKIN",
               "new_state": "CHANNELD_NORMAL",
               "cause": "user",
               "message": "Lockin complete"
            }
         ],
         "status": [
            "CHANNELD_NORMAL:Reconnected, and reestablished.",
            "CHANNELD_NORMAL:Channel ready for use."
         ],
         "in_payments_offered": 61025,
         "in_offered_msat": 7471075577921,
         "in_payments_fulfilled": 73,
         "in_fulfilled_msat": 2605344462,
         "out_payments_offered": 246,
         "out_offered_msat": 12976451777,
         "out_payments_fulfilled": 45,
         "out_fulfilled_msat": 3206242201,
         "htlcs": []
      }
   ]
}

**Comment by cdecker** [comment]
So this is about channel 1 I guess. The important information is this:

```
Offered HTLC 1 RCVD_ADD_REVOCATION cltv 832567 hit deadline
```

Your node or your peer detected a timeout and initiated a.unilateral close, which causes the initiators funds to be locked. Depending on fees, that may take some time, and the funds will be returned to your wallet once the timeout expires.

**Comment by cdecker** [comment]
Oh fun, I probably should have looked up the funding tx. The channel never confirmed so there is nothing to clean up. The funding inputs has likely been doublespent, and there is nothing to do here. You could clean things up with dev-forget-channel or whatever the method is, but I'd suggest against that, and just ignoring the entry in the result.
