### ISSUE TITLE
grpc api: Same fee limit handling for keysend and pay

### ISSUE THREAD

**Issue by michaelWuensch** [ElementsProject/lightning#7227]
### Issue 
The handling of fee limits is inconsistent on different api endpoints.
The lightning-pay api endpoint exposes maxfee, maxfeepercent and exemptfee fee as parameters. (https://docs.corelightning.org/reference/lightning-pay)
The lightning-keysend api enpoint only exposes maxfeepercent and exemptfee. (https://docs.corelightning.org/reference/lightning-keysend)

Please add maxfee to lightning-keysend to simplify and unify api handling.

**Comment by BitcoinJiuJitsu** [comment]
Open bounty on this:
https://community.sphinx.chat/p/clt2n32tu2rjujq1jn6g/bounties/2158/2
