### ISSUE TITLE
Invalid delta>0 assertion in plugins/renepay/mcf.c

### ISSUE THREAD

**Issue by owtyahyg6** [ElementsProject/lightning#7228]
As tested with v24.02.2, the assertion 
assert(delta>0)
on line 1412 in plugins/renepay/mcf.c does not always hold, it causes the renepay plugin to crash sometimes. Tested on FreeBSD 14.0-RELEASE-p5 arm64

**Comment by Lagrang3** [comment]
Hi @owtyahyg6, thanks for reporting on this.

There was a previous issue about that same assertion (https://github.com/ElementsProject/lightning/issues/7150), thus this issue might be a duplicate. The fix (https://github.com/ElementsProject/lightning/pull/7159) is in the master branch but after version 24.02.2.
