### ISSUE TITLE
grpc: Blocks and Minimum missing for feerate

### ISSUE THREAD

**Issue by michaelWuensch** [ElementsProject/lightning#7229]
### Issue and Steps to Reproduce
According to https://docs.corelightning.org/reference/lightning-feerates feerates can be set to blocks or minimum which was added in 23.05.
I generated my api code with protos from 23.11.2 but those two options are missing.

Please add these options for cln-grpc as well.
Without those options I am unable to use the same nice payment flow that I already have in BitBanana with LND.

**Comment by daywalker90** [comment]
Strange, i can see both [floor](https://github.com/ElementsProject/lightning/blob/76cd32387a400a2aee607edaf1e0a06e92e1402f/cln-grpc/proto/node.proto#L1525) and [blockcount](https://github.com/ElementsProject/lightning/blob/76cd32387a400a2aee607edaf1e0a06e92e1402f/cln-grpc/proto/node.proto#L1537) in the v23.11.2 node.proto

**Comment by michaelWuensch** [comment]
@daywalker90 
The problem is it is missing in the primitives. I want to set the feerate for the withdraw endpoint, but cannot create a feerate object with the desired values to pass as input for the withdraw command:
https://github.com/ElementsProject/lightning/blob/76cd32387a400a2aee607edaf1e0a06e92e1402f/cln-grpc/proto/primitives.proto#L72

**Comment by daywalker90** [comment]
Hm you mean like this?
```python
def test_grpc_feerates(bitcoind, node_factory):
    LOGGER = logging.getLogger(__name__)
    """ Check that conversions of this rather complex type work.
    """
    grpc_port = reserve()
    l1, l2 = node_factory.line_graph(
        2,
        opts=[{"grpc-port": str(grpc_port)}, {}],
        announce_channels=True,  # Do not enforce scid-alias
    )
    l1.fundwallet(10_000_000)

    stub = l1.grpc
    feerates = stub.Feerates(clnpb.FeeratesRequest(style="PERKB"))
    LOGGER.info(f"{feerates}")
    newaddr = stub.NewAddr(clnpb.NewaddrRequest())
    LOGGER.info(f"{newaddr}")
    withdraw = stub.Withdraw(
        clnpb.WithdrawRequest(
            destination=newaddr.bech32,
            satoshi=clnpb.AmountOrAll(amount=clnpb.Amount(msat=500_000_000)),
            feerate=clnpb.Feerate(perkb=feerates.perkb.floor),
        )
    )
    LOGGER.info(f"{withdraw}")
    withdraw = stub.Withdraw(
        clnpb.WithdrawRequest(
            destination=newaddr.bech32,
            satoshi=clnpb.AmountOrAll(amount=clnpb.Amount(msat=500_000_000)),
            feerate=clnpb.Feerate(perkb=feerates.perkb.estimates[0].blockcount),
        )
    )
    LOGGER.info(f"{withdraw}")
```

Because that works for me.

**Comment by michaelWuensch** [comment]
Ah, thank you so much. This was my mistake.
With your help I was finally able to implement it in Java.
![image](https://github.com/ElementsProject/lightning/assets/15313630/3d74762c-94f4-420c-b5fb-ce822402b252)
