### ISSUE TITLE
Address behind router not routable

### ISSUE THREAD

**Issue by jimgolian** [ElementsProject/lightning#723]
bitcoind is running and is synchonized. I am trying to run lightning with the first command and I get this error:

lightningd/lightningd --log-level=debug

    lightningd(3684): Trying to guess public addresses...

    lightningd(3684): Address 192.168.1.12:9735 is not routable

    lightningd(3684): Failed to connect 10 socket: Network is unreachable

My bitcoin.conf file has these lines:

    server=1

    rpcuser=aUser

    rpcpassword=aPassword

Any help would be appreciated. My computer is behind a router.  I am thinking since the IP is generated from a router it is not reachable from the public internet.  Is there a way to make lightning work behind a router using a private ip address like 192.168.1.12?  Or, maybe there is a router setting to forward IPs and/or ports to the private IP address.

**Comment by bjd** [comment]
I am also running lightningd behind a router, just make sure to forward port 9735 to the host running lightningd and add `--ipaddr <your public ip>` to the lightningd command line.

**Comment by jimgolian** [comment]
Thank you.  I am one step closer.  Now it says:

xxx@xxx-desktop:~/lightning$ lightningd/lightningd --ipaddr xx.xx.xx.xx  --log-level=debug
lightningd(2607): Not guessing addresses: manually set
lightningd(2607): testing /home/jim/lightning/lightningd/lightning_channeld
lightningd(2607): testing /home/jim/lightning/lightningd/lightning_closingd
lightningd(2607): testing /home/jim/lightning/lightningd/lightning_gossipd
lightningd(2607): testing /home/jim/lightning/lightningd/lightning_hsmd
lightningd(2607): testing /home/jim/lightning/lightningd/lightning_onchaind
lightningd(2607): testing /home/jim/lightning/lightningd/lightning_openingd
lightningd(2607): HSM TRACE: Client: Received message 11 from client
lightningd(2607): Loaded 0 invoices from DB
lightningd(2607): HSM TRACE: Client: Received message 9 from client
lightning_gossipd(2615): pid 2615, msgfd 12
lightningd(2607): Loaded 0 channels from DB
bitcoin-cli exited with code 1: error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

lightningd(2607): bitcoin-cli exited with code 1: error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

Any ideas?

**Comment by jimgolian** [comment]
It worked!  Thank you!

I also had to add rpcport=8332 and rebooted my machine.  Then when I ran lightning it worked.
