### ISSUE TITLE
Docker node instantly crashes

### ISSUE THREAD

**Issue by agilob** [ElementsProject/lightning#724]
When I start the command:

```
docker run \
	-v /home/bitcoin/.lightning:/root/.lightning \
	-v home/bitcoin/.bitcoin:/root/.bitcoin \
	-p 9735:9735 \
	cdecker/lightningd:latest
```
Docker instance crashes instantly with no logs:

```
Error grabbing logs: EOF
```

Both `.bitcoin` and `.lightning` folders are created in provided home directory, but they're empty.

**Comment by cdecker** [comment]
Please notice that the docker images are unsupported and aren't even maintained in this repo.

Does the following print something:

```
sudo docker run \
        -v /tmp/.lightning:/root/.lightning \
        -v /tmp/.bitcoin:/root/.bitcoin \
        -p 9735:9735 \
        cdecker/lightningd:latest lightningd --help
```

The Dockerfile does not have an entrypoint set, so you'll have to specify `lightningd` on the command line. Without it it'll start `bash` but without a TTY attached (`-t` option after `docker`) it'll exit immediately again. This is not a crash, but expected behavior.

**Comment by agilob** [comment]
```
docker run \  
        -v /tmp/.lightning:/root/.lightning \
        -v /tmp/.bitcoin:/root/.bitcoin \
        -p 9735:9735 \
        cdecker/lightningd:latest lightningd --help
docker: Error response from daemon: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused".
ERRO[0010] error waiting for container: context canceled
```

>docker images are unsupported 

Readme in this repo doesn't say it.

>aren't even maintained in this repo

Docker image was updated 17 hours ago, but the dockerfile repo 20 days ago, I decided to open issue here.

Thanks for more info, I should be able to start it now

**Comment by drfalcon** [comment]
When I start the command:

`docker run --rm --name lightning --network container:bitcoind_mainnet -v /scratch/bitcoin/mainnet/bitcoind:/root/.bitcoin -v /scratch/bitcoin/mainnet/clightning:/root/.lightning --entrypoint /usr/bin/lightningd cdecker/lightningd:master --network=bitcoin --rgb=(mycode) --alias=(mynodename) --ipaddr=(myIP) --log-level=debug`

It says:

`Unable to find image 'cdecker/lightningd:master' locally
docker: Error response from daemon: manifest for cdecker/lightningd:master not found.
See 'docker run --help'`

**Comment by cdecker** [comment]
@drfalcon see #1064 for details. The short answer is that the `cdecker/lightningd:master` tag was removed in favor of `cdecker/lightningd:latest`, since the `master` tag was confusing people.
