### ISSUE TITLE
BOLT12 - lightningd resolves the incorrect invoice_label due to case insensitivity in offer description

### ISSUE THREAD

**Issue by farscapian** [ElementsProject/lightning#7278]
I have two BOLT12 offers defined, both of which have the same amount (any) and description, except that in offer_a, the description is lower-case, in offer_b, the description is all uppercase. 

When I pay to offer_b which has an upper case description, lightning resolves the invoice from offer_a.

cc @vincenzopalazzo

**Comment by rustyrussell** [comment]
I can't reproduce this.  Which doesn't surprise me, since we don't really treat those strings at any point.

What are you paying with?  Did it mess up somehow?

Here's my simple test:

```
def test_pay_offer_case_sensitive(node_factory, bitcoind):
    l1, l2 = node_factory.line_graph(2, opts={'experimental-offers': None})

    offer1 = l2.rpc.offer(amount='any', description='simple test')
    offer2 = l2.rpc.offer(amount='any', description='simple Test')

    assert l1.rpc.decode(offer1['bolt12'])['offer_description'] == 'simple test'
    assert l1.rpc.decode(offer2['bolt12'])['offer_description'] == 'simple Test'

    inv1 = l1.rpc.fetchinvoice(offer=offer1['bolt12'], amount_msat=100)
    inv2 = l1.rpc.fetchinvoice(offer=offer2['bolt12'], amount_msat=100)

    assert l1.rpc.decode(inv1['invoice'])['offer_description'] == 'simple test'
    assert l1.rpc.decode(inv2['invoice'])['offer_description'] == 'simple Test'

    l1.rpc.pay(inv1['invoice'])
    assert only_one(l2.rpc.listoffers(offer1['offer_id'])['offers'])['used'] is True
    assert only_one(l2.rpc.listoffers(offer2['offer_id'])['offers'])['used'] is False
```

**Comment by vincenzopalazzo** [comment]
yes @rustyrussell in Austin I wrote your same test and I was not able to reproduce, and I ask @farscapian to look the step to reproduce it

**Comment by farscapian** [comment]
Guys I am sorry waste your time on this. I was unable to replicate the issue on my side. I was certain at the time I had found a bug, but I apparently I had just confused myself. It's been known to happen.

**Comment by vincenzopalazzo** [comment]
np was easy to write a test for it
