### ISSUE TITLE
Add an API-Method which returns the emergency.recover file

### ISSUE THREAD

**Issue by rox1338** [ElementsProject/lightning#7283]
### What?
An API-Method which returns the emergency.recover file.

### Why?
It would be very useful for application builders (which are building apps on top of CLN) which are using the GRPC-Interface and want to build a Backup-feature.
They can get the file via the API and e.g. create a backup on a different physical location.

### Additional info
Already talked to @adi2011 about the matter.

**Comment by BitcoinJiuJitsu** [comment]
Open CLN bounty on this:
https://community.sphinx.chat/p/clt2n32tu2rjujq1jn6g/bounties/2158/2

**Comment by rox1338** [comment]
Why a bounty?
I think @adi2011 is willing to implement it, if it is deemed useful.

**Comment by adi2011** [comment]
Yes, I'll implement it this week.

**Comment by rox1338** [comment]
Any news?

**Comment by adi2011** [comment]
Sorry for the delay @rox1338. The PR is up for review now :)

**Comment by NishantBansal2003** [comment]
This PR can be closed with reference to the merged PR #7539
