### ISSUE TITLE
Invalid JSON Format bitcoin plugin estimated fee RPC

### ISSUE THREAD

**Issue by vincenzopalazzo** [ElementsProject/lightning#7294]
### Issue and Steps to Reproduce
I was debugging an issue with the folgore plugin, and I noted that the new estimated fee is not defining a valid json

```json
{
	"feerate_floor": 1,
	"feerates": {
		{ "blocks": 2, "feerate": 1 },
		{ "blocks": 6, "feerate": 1 },
		{ "blocks": 12, "feerate": 1 }
		{ "blocks": 100, "feerate": 1 }
	}
}
```

the `feerates` is an object of an object, but the inner object is not a value `key-value` pair, so this breaks modern parsers

My suggestion is to move the object as follows

```json
{
	"feerate_floor": 1,
	"feerates": {
		"2": 1,
		"6": 1,
		"12": 1,
		"100": 1,
	}
}
```

---
An online parser like https://jsonformatter.org/ generate the following error

```
Parse error on line 3:
...1,	"feerates": {		{ "blocks": 2, "feer
---------------------^
Expecting 'STRING', '}', got '{'
```

**Comment by endothermicdev** [comment]
Which version is this?  Is this running with allow-deprecated-apis=false?

**Comment by vincenzopalazzo** [comment]
The current master, and yes I am running the `allow-deprecated-apis=false` but the modern version contains the broken json :/

**Comment by vincenzopalazzo** [comment]
Oh I trusted the documentation :) without looking at the implementation! Ok this was a implementation bug ahah
