### ISSUE TITLE
We are getting kicked off Freenode

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#73]
I was contacted by a Freenode staff member, informing me that the channel will get kicked off the network at the end of the week.

**Comment by dexX7** [comment]
May I ask why?

**Comment by cdecker** [comment]
Freenode does not allow bots to use their network if they are not geared towards communicating with humans. Our nodes where using the network mainly to communicate with each other. That is also the reason why Bitcoin was kicked off after a while.

**Comment by cdecker** [comment]
Closing in favor of the tracking issue #88
