### ISSUE TITLE
Pending Payment

### ISSUE THREAD

**Issue by pandabit** [ElementsProject/lightning#732]
I sent a payment several hours ago but and the status still shows pending. The invoice expired and I closed the channel to see if that would clear or reset my account, but I'm still showing a pending status when I run `listpayments`. Any ideas on what I should do?

**Comment by ZmnSCPxj** [comment]
This is a potential race condition where a remote node is online while forwarding, but shuts down by the time a response on the payee end occurs (or a node later in the route fails).  You need to ask the ultimate payee if it received the payment or not.

Note that we cannot simply forget the payment even after the invoice has expired: the ultimate payee still knows the secret payment key whose hash is embedded in the invoice, and you will need to trust the payee has properly forgotten the secret payment before you can safely forget the payment on our node.  And really we cannot forget it either: the payment will timeout once the total CLTV is achieved.

So I think it is a problem of education.  Payments may result in one of the following:

1.  Definite success.
2.  Definite failure.
3.  Uncertain; we will know within N blocks if it succeeded or failed, or know after N blocks if it definitely failed.

One can argue that `pay` does not really provide the above information, especially for the third case.

**Comment by pandabit** [comment]
Thank you for the insight. Would it return the funds if the payee`delinvoice`? Or, is this a case where it pends until N blocks is achieved?

**Comment by ZmnSCPxj** [comment]
It will pend until N blocks is achieved.  If the payee `delinvoice`, then it will assuredly fail... after N blocks.

The timeout itself is not reportable on the RPC currently, but I think it is the `cltv_expiry` field of the `struct htlc_out` that is created when we start a payment should contain the block height at which we know a payment definitely fails.  Probably need to be reportable on the RPC.

**Comment by fixone** [comment]
I have a similar situation, but opposite - I tested receiving payments with the eclair android wallet. I've done about 10 tries - all are listed as pending (some for 24hours or so), but the most confusing part is that in a few of cases the wallet shows FAILED, while lightningd sees the payments (just that they are pending). Is there a way to confirm/fail these pending transactions?

**Comment by ZmnSCPxj** [comment]
@fixone do you mean that you have opened channels, or actually paid?  Do you have a direct channel from your Eclair to your c-lightning node?  When `lightningd` receives, it is very atomic and lightningd will generally attempt to claim the money as fast as possible.  In addition, lightningd should not be using payments to keep track of incoming payments anymore, maybe your lightningd is from last week?

**Comment by fixone** [comment]
I have funded channels, both from my node to a few other nodes (they are seen here https://explorer.acinq.co/#/n/03090a05c61445357d4677956604eb4c06548dc8baaaaa1290ad3d2d16daf30975) as well as from my wallet to 2-3 nodes (here's one of the funding tx https://api.blockcypher.com/v1/btc/test3/txs/a93ae7caf255e695f733a30bbadb3bdffe4964f359bd2bda48218da559ce67cd for a channel with 02fed8bbae3c4d4a2973dabc6569301fc399e87e5cb353d891658aaace96e344a1)
