### ISSUE TITLE
Missing dependency lopsq.co 

### ISSUE THREAD

**Issue by TekkadanPlays** [ElementsProject/lightning#7325]
### Issue and Steps to Reproduce:
Downloaded release, missing lopsq.co from build clightning-v24.02.2-Ubuntu-20.04.tar.xz 

Error while loading shared libraries: libpq.so.5 when installing latest release

**Comment by vincenzopalazzo** [comment]
looks like you are missing some libraries, try to follow https://askubuntu.com/questions/1372562/how-to-install-libpq-dev-14-0-1-on-ubuntu-21-10
