### ISSUE TITLE
Potential secret rune returned in error message when rune has a formatting issue

### ISSUE THREAD

**Issue by Amperstrand** [ElementsProject/lightning#7338]
in LNbits, I entered the following configuration:
```
CLNREST_PAY_RUNE=ngjBkosZ_tij1j8-NWGXq8nS4zN25Xbyt9EE9TGqRS09MzcyJm1ldGhvZD1yZW5lcGF5JnBpbnZib2x0MTFfYW1vdW50PDEwMDEmcmF0ZT0x"
```

There is an error in the above: it is a valid rune, but it includes an extra `"`

When LNBits calls core lightning with this rune, core lightning responds:

```
'{"code": -32602, "message": "rune: should be base64 string: invalid token \'\\"ngjBkosZ_tij1j8-NWGXq8nS4zN25Xbyt9EE9TGqRS09MzcyJm1ldGhvZD1yZW5lcGF5JnBpbnZib2x0MTFfYW1vdW50PDEwMDEmcmF0ZT0x\\\\\\"\\"\'"}
```

Then LNBits displays this to the end user:

<img width="950" alt="image" src="https://github.com/ElementsProject/lightning/assets/141745238/473bdbf0-d958-48d8-a15c-6d134b0ddda5">

This is a problem because even though the rune is incorrectly formatted, it is still a valid rune that is sensitive and should not be shown to a non-privileged end user.

Possible solutions:
 * change LNbits so that error messages from the lightning backend are not passed to the end user
 * don't show the the string that is being decoded in the error message because it may contain a secret or part of a secret.

If you consider a wallet that accepts a seedphrase as its input, an appropriate error message to log would be something like `"invalid seedphrase entered"` and not `"some nearly correct seedphrase that is missing a word is not a valid seedphrase"`

**Comment by vincenzopalazzo** [comment]
Looks like we should not return a rune in an error case.

Thanks for reporting it

**Comment by rustyrussell** [comment]
> If you consider a wallet that accepts a seedphrase as its input, an appropriate error message to log would be something like "invalid seedphrase entered" and not "some nearly correct seedphrase that is missing a word is not a valid seedphrase"

That is TERRIBLE UX!  I want the wallet to tell me that the second word isn't a valid seed word.

If LNBits can be made to submit an invalid command to CLN, something is wrong!  I would be very concerned that a user who can do this can also make the CLN node do some unauthorized action in this case.

LNBits should consider any of the basic JSONRPC 2.0 errors to be an *internal* error:

	JSONRPC2_INVALID_REQUEST = -32600,
	JSONRPC2_METHOD_NOT_FOUND = -32601,
	JSONRPC2_INVALID_PARAMS = -32602,

Perhaps log it, but do *NOT* report the error string to the user in this case.

**Comment by Amperstrand** [comment]
To be fair, this is not part of LNBits as of today but part of an experimental pull request I am working on to make LNBits use runes.

I thing that exposing the error to the end user might make sense in some circumstances. For example if the rune limits the user to at most make 5 requests per minute, the user should be told that the invoice creation failed because it is being rate-limited. The same is true if a route is not found: the user could be given feedback that the lightning payment failed because a route could not be found instead of a dreaded [Error code -41: an unknown error has occured](https://xkcd.com/1024/) message.

In the example of the experimental LNBits call, the user is not allowed to arbitrarily send commands to CLN. What happened was that I by mistake added a `"` to the rune because I copy-pasted the rune from a terminal window.

So it all boils down to: can we expect error codes from CLN to trickle down to end users of a product or service that uses CLN as its back end. If so, CLN error messages must not contain data that have a risk of containing sensitive data.

Another way to look at it is that this was a mistake that I personally will never make again. But is there a non-zero risk that someone else might at some point enter `"rune"` instead of `rune` in their config file, thereby inadvertently displaying a nearly valid rune to an end user of their product so that the user can use the rune for something other then it was indended for?
