### ISSUE TITLE
Interop: INVALID_ONION_HMAC

### ISSUE THREAD

**Issue by JssDWt** [ElementsProject/lightning#7347]
### Background

There is an interop issue with LND that causes INVALID_ONION_HMAC errors. It consistently reproduces with the following setup:

LND sender -> LND routing node -> CLN routing node -> CLN recipient

It does NOT reproduce with
- 4 LND nodes
- 4 CLN nodes
- 1 LND node and 1 CLN node
- LND sender, LND routing node, CLN recipient
- CLN sender, LND routing node, CLN routing node, CLN recipient

### LND issue
I added this issue in the LND repository too, see there for all details, including logs:
https://github.com/lightningnetwork/lnd/issues/8785

**Comment by darioAnongba** [comment]
Hi all, we're the ones getting the bug in production in case I can be of any help. This issue is preventing affected nodes running on Greenlight infrastructure to receive payments from Alby or Blink (only ones tested so far).

**Comment by endothermicdev** [comment]
It looks like the presence of a route hint in the invoice is leading LND to create a legacy onion payload for the intermediate CLN node... which we removed support for [two years ago](https://github.com/ElementsProject/lightning/pull/5058).  @rustyrussell has drafted a patch to convert the legacy payload to a TLV, which will allow the htlc to be processed normally.  We'll get this in the 24.05 release.  Thanks for the report!

**Comment by JssDWt** [comment]
Also it looks like the node announcement wasn't seen by the sender, which seems related to https://github.com/ElementsProject/lightning/issues/7276
