### ISSUE TITLE
How to name my node?

### ISSUE THREAD

**Issue by jimgolian** [ElementsProject/lightning#735]
Can we put a command to name our node as a cli/lightning-cli parameter, and also add it to the help command section?

**Comment by ZmnSCPxj** [comment]
Currently none, but the name can be set as a command-line parameter of `lightningd`:

    lightningd --alias=STEALFROMMEPLZ

It is also possible to save the command-line parameters in a file inside the lightning-dir (usually `~/.lightning/`), in a file named `config`.  So `~/.lightning/config` can contain such command-line arguments:

    --alias=STEALFROMMEPLZ
    --rgb=FF00FF

You can get help using `lightningd --help`.

**Comment by jimgolian** [comment]
It worked.  Just wanted to note for any others that there are two lightning directory at the same level.  "`.lightning`" (prefixed with a dot) and the other with the same name without the dot "`lightning`".  The config file needs to be in "`.lightning`".

Also the parameters need to be there without the "--".  For example:

```
alias=STEALFROMMEPLZ
rgb=FF0000
```
