### ISSUE TITLE
Please provide a way to enable disabled BOLT12 offer

### ISSUE THREAD

**Issue by psychoet** [ElementsProject/lightning#7360]
Currently, there is no way to enable disabled BOLT12 offers.

I have created an experimental offer for withdrawal mining revenue from OCEAN pool, but disabled it since I thought it would be possible to enable it again or create another offer for the same purpose.
But in this case, the offer is bonded to the bitcoin address itself with specific message, so new one cannot be generated (only returns 'already existing offer' message.)

Can you provide a way to enable the disabled offer? I don't know why it is designed in an irreversible way...

**Comment by rustyrussell** [comment]
It's really "delete", but we don't actually delete offers as they're linked in payments (if you've used it).  However, you can create a new one with a different description?  The following command will reenable it meanwhile:

1. Stop your lightning node.
2. sqlite3 ~/.lightning/bitcoin/lightningd.sqlite3 "UPDATE offers SET status=1 WHERE status=0;"
3. Restart your node.
