### ISSUE TITLE
docs: broken formatting

### ISSUE THREAD

**Issue by urza** [ElementsProject/lightning#7367]
Something is wrong with docs formatting

![image](https://github.com/ElementsProject/lightning/assets/189804/160853c5-2637-4587-89ff-e28ad19c85f3)

https://docs.corelightning.org/reference/lightning-decode#return-value

**Comment by ShahanaFarooqui** [comment]
@urza Thanks for reporting the issue. The issue was generate by #6995, fixed with https://github.com/ElementsProject/lightning/commit/f5f2ab17a0304b84aae34a300b6a73bc3a008d13.
