### ISSUE TITLE
When restoring channel after restart i have errors

### ISSUE THREAD

**Issue by parmax** [ElementsProject/lightning#737]
I need restart lighting daemon.
After it i have errors with restore channel.

```
lightning_channeld(2133): STATUS_FAIL_PEER_IO: bad reestablish msg: WIRE_ERROR 00110000000000000000000000000000000000000000000000000000000000000000003b6c696768746e696e675f6368616e6e656c643a207570646174655f6665652031206f7574736964652072616e67652031303539372d333032373035
lightningd(1622): peer 0387e3780a4325eb38421fb83000a6f6c0ffa4a69ea0c81db3f00e8e5015c9e8a1: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)
lightning_channeld(2135): STATUS_FAIL_PEER_IO: bad reestablish msg: WIRE_ERROR 00110000000000000000000000000000000000000000000000000000000000000000003b6c696768746e696e675f6368616e6e656c643a207570646174655f6665652031206f7574736964652072616e67652031303539372d333032373035
lightningd(1622): peer 0387e3780a4325eb38421fb83000a6f6c0ffa4a69ea0c81db3f00e8e5015c9e8a1: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)

```
I added log of daemon with  --log-level=debug run options.
[debug.log](https://github.com/ElementsProject/lightning/files/1655862/debug.log)

What i help fix it?

**Comment by cdecker** [comment]
The peer has closed the channel with the following error message:

> lightning_channeld: update_fee 1 outside range 10597-302705

The error is in the `WIRE_ERROR` packet and shown as hex encoded string, we should probably decode and show that error instead :-)

**Comment by parmax** [comment]
Why happen it?

**Comment by cdecker** [comment]
Could it be that `bitcoind` was restarted in the meantime, or that the fees were changed using one of the `--dev-` JSON-RPC commands?

**Comment by parmax** [comment]
I don't know how it happened. I need fix it. How to do it?

**Comment by cdecker** [comment]
You can try either the `close [nodeid]` JSON-RPC command or the `dev-fail [nodeid]` JSON-RPC command to force the channel to be closed and funds will be returned after 144 blocks.

**Comment by fetihh** [comment]
@cdecker i get an error message like this:

`"code" : -1, "message" : "channel ALL: lightning_channeld: Peer sent error channel fbc76fcf614313001c8675468aaa3379dcfef9ad2726a8fb261a77be991d309e: update_fee 29107 outside range 972-11470`

what do i have to do to reconnect? how to set a command? and how much should I set a fee?

**Comment by fetihh** [comment]
@cdecker Please write answers

**Comment by cdecker** [comment]
This is an error about on-chain fee estimates being too different between the two endpoints. Usually keeping `bitcoind` running longer before starting `lightningd` will fix this since it allows `bitcoind` to learn about fees better. Notice that this may be an issue when connecting to another implementation since they may be using different fee estimation emchanisms.

Not much we can do here, other than hoping that the fee estimates sync up.

**Comment by fetihh** [comment]
I understand. Thank you very much decker
