### ISSUE TITLE
Pull upstream libwally to include LTO removal

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#738]
The `libwally-core` team have been busy making it compatible with BSDs and other OSs, let's pull in those changes and see if it fixes the compilation woes some people are reporting (#695, #653, #645, #533, #432).

**Comment by bitstein** [comment]
I'm ready to test on OS X 10.13.2 as soon as this is available!

**Comment by practicalswift** [comment]
An updated `libwally` would be very nice! 👍
