### ISSUE TITLE
offers: still not getting invoice back from CLN 

### ISSUE THREAD

**Issue by orbitalturtle** [ElementsProject/lightning#7382]
### Issue and Steps to Reproduce

Even with https://github.com/ElementsProject/lightning/pull/7304 in 24.05, in our testing with LNDK we're still having some trouble getting an invoice back from CLN in multi-hop test networks. We see an "unknown first peer" error in the logs on CLN's end and CLN doesn't respond with an invoice. I assume this means it's having trouble reaching the introduction node provided by us in the invoice request?

The full logs are:

```
2024-06-10T03:42:46.120Z DEBUG   hsmd: Client: Received message 1 from client
2024-06-10T03:42:46.120Z DEBUG   0251a47081369215be561618e56cc5438a9d6134d27c6538bba0e7b55761116a90-hsmd: Got WIRE_HSMD_ECDH_REQ
2024-06-10T03:42:46.120Z DEBUG   hsmd: Client: Received message 1 from client
2024-06-10T03:42:46.121Z DEBUG   lightningd: Got onionmsg reply_path
2024-06-10T03:42:46.128Z DEBUG   hsmd: Client: Received message 25 from client
2024-06-10T03:42:46.128Z DEBUG   plugin-offers: sendonionmessage gave JSON error: {\"code\":-1,\"message\":\"Unknown first peer\"}
```

I confirmed that CLN has the introduction node in it's network graph (with lightning-cli listnodes), but it still isn't connecting to it. I've also confirmed that when we manually connect CLN to the introduction node that LNDK chooses, the payment succeeds.

For reproducing the issue, we've been using LNDK to make payments. One way to set up a network is with bolt12-playground: https://github.com/LN-Zap/bolt12-playground

It's also possible there's something wrong with our network setup or something we're doing in LNDK.

Thanks for any help!

**Comment by orbitalturtle** [comment]
Just wanted to add a little more context to this. This is an example CLN offer that we're having trouble paying: 

`lno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrcgqgn3qzsggfxy7n6swpg8q93pqd62djtse2ujku5gar5uvd5hfm53emy7y48ngvhf3mzfmeyc3rja5`

Decoding it, it doesn't specify a blinded path and uses itself as the intro node.

So another question I have is, is there something we need to do to coax CLN to use a blinded path when it generates an offer?

**Comment by thomash-acinq** [comment]
This issue also occur when the reply path starts at the CLN node like in this example:
Alice wants to pay CLN, Alice finds a route Alice -> Bob -> CLN and sends an invoice request with the reply path CLN -> Bob -> Alice. Then CLN needs to reply to a blinded route that starts at itself and it fails with the above error.

**Comment by orbitalturtle** [comment]
> This issue also occur when the reply path starts at the CLN node

+1 I've been getting the same error in that scenario as well
