### ISSUE TITLE
Wss-proxy plugin fails to initialise with tor-only

### ISSUE THREAD

**Issue by CahirBoyle** [ElementsProject/lightning#7386]
### Issue and Steps to Reproduce

When running a tor only network configuration like that described by RaspiBolt:

> proxy=127.0.0.1:9050
bind-addr=0.0.0.0:9736
addr=statictor:127.0.0.1:9051/torport=9736
always-use-proxy=true

Plus the adjusted wss-proxy configurations:

> wss-bind-addr=127.0.0.1:5002
wss-certs=/home/lightning/.lightning/bitcoin

The wss-proxy fails to initialise showing:

> plugin-manager: started(2996512) /home/lightning/lightning/plugins/wss-proxy/wss-proxy
plugin-wss-proxy: Initiating websocket secure server...
plugin-wss-proxy: Killing plugin: disabled itself at init: Error in parsing options: 'NoneType' object is not subscriptable

**Comment by 8de2fdb0** [comment]
well I think the wss-proxy is just not documented enough

try to use following config options:
```
 --addr=0.0.0.0: 9736
 --bind-addr=ws:127.0.0.1:18080
```

the `wss-proxy` plugin is expecting the `bind-addr` option to start with `ws:` 
see: https://github.com/ElementsProject/lightning/blob/35101c072ad1a987bc076397421655bb4171b10d/plugins/wss-proxy/wss-proxy.py#L74

Or it fails throwing the error you posted.

**Comment by 8de2fdb0** [comment]
@ShahanaFarooqui thanks
