### ISSUE TITLE
Bi-directional payment channel support

### ISSUE THREAD

**Issue by alaniz3** [ElementsProject/lightning#739]
I'm sorry if this seems naive but I don't think there is support for bi-directional payment channels? Is there any plans on implementing this or if its already implemented can someone point me to some docs or some help as to how to use and create them?

**Comment by cdecker** [comment]
The channels are bidirectional, payments can flow both ways, what causes you to think they are uni-directional?

**Comment by alaniz3** [comment]
I'm getting this response when trying to send funds back to a node from which I have received a payment (and have an open channel with) `failed: INVALID 0 (WIRE_TEMPORARY_CHANNEL_FAILURE: Capacity exceeded)`. Note both nodes are running on the same machine but in different instances (different lightning-dirs).

**Comment by cdecker** [comment]
That is as expected, if you have node `n1` open a channel to node `n2` then all funds are initially owned by `n1`, so `n2` cannot send to `n1` using that channel. Transfer a some funds to `n2` by having `n1` pay invoices from `n2`. After that `n2` has a usable balance on that channel. Notice that you cannot transfer the full balance back to `n1` since we have a reserve under which its stake may not drop.

**Comment by alaniz3** [comment]
I will try to reproduce the issue but iirc I had paid invoices from `n1` to `n2` and then I was trying to send some funds back from `n2` to `n1`. Let me get on my machine and test it out again :)

**Comment by cdecker** [comment]
Just checked, `listpeers` will tell you the `channel_reserve_satoshis`, so you won't be able to have either of the nodes drop below that amount on a channel.

**Comment by alaniz3** [comment]
So you're right it was due to the amounts. I don't seem to have `channel_reserve_satoshis` under `listpeers`, did this get added recently? (Last time I built was about 4-5 days ago).

**Comment by cdecker** [comment]
Yeah, `listpeers` went through a few changes lately, and that field was added. Glad it worked :+1: 

Closing for now, feel free to re-open or comment here should you need additional info ^^

**Comment by alaniz3** [comment]
Awesome, will rebuild and test it out! Thanks for your help :)

**Comment by cdecker** [comment]
Thank you for testing :-)
