### ISSUE TITLE
BOLT12: can't fetch invoice from offer (without description)

### ISSUE THREAD

**Issue by urza** [ElementsProject/lightning#7405]
Trying to fetch invoice from this offer created by LDK:

lno1qsgxeghagrrs3fygrz74wxpskwfpsyxvqttftvqu0f5sneckep3lkwdut7mmhhpcyjmlmnjn4hze8ed7pq88xqs35u5wdnnnhpw53ntuems6qs8hggqac250urm6dl9vlpq9f2q2ucpq9kpa4r734cduc7lkt7gl0dcqn0ku648u9q9v643jsl6ec2kkgge4qqemsc8plk5hd96ljealz9cs9d3exlxw8jg876k2sv25kyk2dgyw7r3ry7fnn4f32d4g5lqy8n3qtqfr7zcecqm4ur8msqhfkuw0a3t75njaksj22ch9zhr43j6fjfntzqmgyacl6gqpq5lxewmaz5v5ktqww0qlv7m25kckyyp5zf4cqk35j2mfa23t9c8ukmtpu66vjca5d8xvp6zu3wuup7y28ss

` cln fetchinvoice lno1qsgxeghagrrs3fygrz74wxpskwfpsyxvqttftvqu0f5sneckep3lkwdut7mmhhpcyjmlmnjn4hze8ed7pq88xqs35u5wdnnnhpw53ntuems6qs8hggqac250urm6dl9vlpq9f2q2ucpq9kpa4r734cduc7lkt7gl0dcqn0ku648u9q9v643jsl6ec2kkgge4qqemsc8plk5hd96ljealz9cs9d3exlxw8jg876k2sv25kyk2dgyw7r3ry7fnn4f32d4g5lqy8n3qtqfr7zcecqm4ur8msqhfkuw0a3t75njaksj22ch9zhr43j6fjfntzqmgyacl6gqpq5lxewmaz5v5ktqww0qlv7m25kckyyp5zf4cqk35j2mfa23t9c8ukmtpu66vjca5d8xvp6zu3wuup7y28ss 100000`

ends with this error:

{
   "code": -32602,
   "message": "offer: Unparsable offer: Offer does not contain a description: invalid token '\"lno1qsgxeghagrrs3fygrz74wxpskwfpsyxvqttftvqu0f5sneckep3lkwdut7mmhhpcyjmlmnjn4hze8ed7pq88xqs35u5wdnnnhpw53ntuems6qs8hggqac250urm6dl9vlpq9f2q2ucpq9kpa4r734cduc7lkt7gl0dcqn0ku648u9q9v643jsl6ec2kkgge4qqemsc8plk5hd96ljealz9cs9d3exlxw8jg876k2sv25kyk2dgyw7r3ry7fnn4f32d4g5lqy8n3qtqfr7zcecqm4ur8msqhfkuw0a3t75njaksj22ch9zhr43j6fjfntzqmgyacl6gqpq5lxewmaz5v5ktqww0qlv7m25kckyyp5zf4cqk35j2mfa23t9c8ukmtpu66vjca5d8xvp6zu3wuup7y28ss\"'"
}

**Comment by jkczyz** [comment]
> This appears to be a duplicate of #7402

AFAICT, this offer doesn't conform to a recent spec change that allows no description when no amount is given.

**Comment by vincenzopalazzo** [comment]
Yes, looks like those are two different errors, and I think @jkczyz already added some suggestions, thanks!

**Comment by vincenzopalazzo** [comment]
For context, this issue reports a bug in parsing a minimal offer, with the error message `offer: Unparsable offer: Offer does not contain a description: invalid token`. Meanwhile, issue #7402 reports `string: invalid offer data: invalid token`.

Further investigation is needed to determine if these are the same problem. During the meeting, @rustyrussell mentioned that there might be an issue with the blinded path.

**Comment by vincenzopalazzo** [comment]
```
➜  ~ lightning-cli --testnet fetchinvoice lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx
{
   "code": -32602,
   "message": "offer: Unparsable offer: Offer does not contain a description: invalid token '\"lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqsespexwyy4tcadvgg89l9aljus6709kx235hhqrk6n8dey98uyuftzdqzrtkahuum7m56dxlnx8r6tffy54004l7kvs7pylmxx7xs4n54986qyqeeuhhunayntt50snmdkq4t7fzsgghpl69v9csgparek8kv7dlp5uqr8ymp5s4z9upmwr2s8xu020d45t5phqc8nljrq8gzsjmurzevawjz6j6rc95xwfvnhgfx6v4c3jha7jwynecrz3y092nn25ek4yl7xp9yu9ry9zqagt0ktn4wwvqg52v9ss9ls22sqyqqestzp2l6decpn87pq96udsvx\"'"
}
```

We have the same problem with phoenix if we fetch the offer from https://starblocks.acinq.co/donate

cc @t-bast

**Comment by michael1011** [comment]
Same with offers from Phoenix:

```
lightning-cli decode lno1zrxq8pjw7qjlm68mtp7e3yvxee4y5xrgjhhyf2fxhlphpckrvevh50u0qtuzuc7vrxw3ptvmvzs7lqmyp94rhmfdg6gpef65rs2xxl2mzr2ksqszz0xxdd9y6653lwugyjqg6nwjerz4wcdskllmkp9fl4kp4d5z0hfqqvlxj7wm32qk0pavw6cr3kfn6unhzy9r25vlp4nmmy0gfck4ur7qk0xz43lhmnlx59qfxmdh6ue6y65s7rw4qdtdltt5gzratf3hnr668laqtcrk5tyzfz8a8ckq4dlpd40alv646qqsf6pgykhxlayyswqmjffpgehjjs
{
   "code": -32602,
   "message": "string: Offer does not contain a description: invalid token (see logs for details)"
}
```

**Comment by vincenzopalazzo** [comment]
This is fixed by https://github.com/ElementsProject/lightning/pull/7433

But now there is the blinded path work that need to be done somehow

**Comment by Sjors** [comment]
I also ran into the "Offer does not contain a description" when trying to `decode` or `fetchinvoice` my Phoenix bolt12 from CLN v24.05. I might test the fix PR...

**Comment by pycanis** [comment]
Has the fix been released yet?
