### ISSUE TITLE
Is anyone working on a open source minimal GUI for c-lightning?

### ISSUE THREAD

**Issue by alaniz3** [ElementsProject/lightning#742]
I was wondering if this existed. I remember seeing @cdecker use a minimal web based UI on a recent World Crypto News Network LN demo, is that available somewhere?

**Comment by alaniz3** [comment]
Just realised this exists here https://github.com/cdecker/kugelblitz, closing.

**Comment by cdecker** [comment]
That's a horrible pile of JS that needs urgent updates :wink: So feel free to contribute or start a new UI

**Comment by alaniz3** [comment]
Sounds good, I'll have a look at your code but I'm not very familiar with golang, might port it over to python-django. But great, good to know there's some need for a minimal UI!
