### ISSUE TITLE
Failed to send and receive Bitcoin via green wallet lightning account. Failed to empty my green wallet lightning account. 

### ISSUE THREAD

**Issue by realsunbros** [ElementsProject/lightning#7423]
![IMG_20240621_223747](https://github.com/ElementsProject/lightning/assets/173516728/680cbee1-a852-4db4-ba10-930419d56868)

I've tried multiple times sending & receiving Bitcoin via my green wallet lightning account but it keeps failing. Then I try to emptying my green wallet lightning account to my bitcoin address yet still failed. How can I fix this issue?

**Comment by vincenzopalazzo** [comment]
Mh this is more an issue of https://github.com/Blockstream/green_android (probably you are on ios)

Well idk if it is a green issue of something down the tech stack that they are using, but idk what we can do from our side

**Comment by cdecker** [comment]
Yep, this is a Green issue, that may have a cause in the Breez SDK (seeing that it is a hodl invoice) and/or Greenlight (seeing that GL operates the CLN nodes that provide the LN functionality). Please file an issue there first, as these projects likely have more context for the issue at hand.
