### ISSUE TITLE
Add new rpc `listaddresses` to list all addresses issued by the wallet

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#7439]
Add a command to list all addresses issued by the wallet till date or filter addresses for a supplied address.

**Comment by michael1011** [comment]
That would be a great feature!

> or filter addresses for a supplied address.

Not exactly sure what you mean by that. A check if an address was created by the CLN wallet?

> all addresses issued by the wallet till date

Simple pagination would be sufficient for our use case
