### ISSUE TITLE
can listchannels show the channel direction and size(weight)?

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#745]
I have noticed that a lot of payments fail because although the two nodes are somewhat connected to the network, there isn't enough capacity between them, or the shortest found path is actually exhausted. The channel state between two nodes isn't broadcasted to the whole network, so if two nodes connected by a channel have made a lot of payments between them, only they themselves know the current possible capacity between them. If capacity is exhausted in one direction, only one node will be able to pay the other one.

I wanted to analyze the LN testnet, and figure out what percent of nodes can pay 10000 satoshi (1$) to any other node in the network. The higher the number, the healthier the network. `lightning-cli`'s listchannel outputs the `source`, `destination` but it doesn't show anything about capacity or the direction of the channel. Can we get the size of the channel on `listchannels`?

**Comment by Sgt-Miller** [comment]
capacity of a channel is not broadcasted publicly. You can only know capacity with peers you have channels with.      
About first para, #550 should fix it

**Comment by cdecker** [comment]
Since we check that funding tx outputs actually exist on-chain we can also annotate channels with their total capacity, but not with the current capacity, i.e., who owns how much, since that is private information.

**Comment by nstamato** [comment]
@cdecker Is there some reason why the channel is not annotated with the total capacity already? Having that would help with immediately disregarding a route that can't handle a payment by virtue of total capacity and moving on. I guess that would be fixed by #550 anyway, but we could make the process a little faster but making this check before returning anyway. Would this be useful?

**Comment by cdecker** [comment]
We try to keep the gossip messages as small as possible, but I'll definitely add the annotation after the funding tx lookup.

**Comment by cdecker** [comment]
Opened #817 to track progress.

**Comment by thestick613** [comment]
@Sgt-Miller then how does [recksplorer](https://lnmainnet.gaben.win) know the total capacity?

**Comment by thestick613** [comment]
<img width="1276" alt="screen shot 2018-01-28 at 10 38 32" src="https://user-images.githubusercontent.com/1608525/35480479-7b6c8a1a-0417-11e8-9cb0-6621657f31a0.png">

And it also looks like it knows the capacity of specific channels. You can see this by clicking on them.

**Comment by Sgt-Miller** [comment]
@thestick613 , meant "current" capacity. It knows how much is in each channel but not which side it is in.
