### ISSUE TITLE
lightning-cli: dumpprivkey command request

### ISSUE THREAD

**Issue by alaniz3** [ElementsProject/lightning#746]
I think it would be nice to be able to dump the private keys of the addresses that lightningd generates. This would greatly aide backup key management.

**Comment by fixone** [comment]
wouldn't that be achieved by backing-up the hsm_secret?

**Comment by alaniz3** [comment]
Yeah but I'm just thinking from for example a tipbot perspective (or other psuedo-centralised LN providers) it would be nice to be able to be able to retrieve the private keys at the level of the RPC API.

**Comment by Saibato** [comment]
Rant:YaY and a web interface with give me all your channel and future coins just tell me your peer ID !!! Its bip32 share once lose forever.
As long as there is no spending password and the hsm_secret is uncrypted and the seed is fixed on all nodes out there this is a security nightmare.
In the future one might think about sharing some derived ext_pubs or masters to manage some channel pools from 3dpartys
Dont trust verify!!!

**Comment by ZmnSCPxj** [comment]
#1762 is closed, and exports the privkey via external tool that has direct read access to `hsm_secret`, thus closes Saibato attempt to steal privkey via RPC.  Can we close this?

**Comment by ZmnSCPxj** [comment]
If no objections in a few days, I will close.
