### ISSUE TITLE
Cannot compile with rust

### ISSUE THREAD

**Issue by aprilinph** [ElementsProject/lightning#7463]
Debian bookworm 12.6
Rustc 1.79.0
Gcc 12.2.0

Have tried v.24.05 and v24.02.2
Make ends with:

`python3 -m grpc_tools.protoc -I cln-grpc/proto cln-grpc/proto/node.proto --python_out=contrib/pyln-grpc-proto/pyln/grpc/ --grpc_python_out=contrib/pyln-grpc-proto/pyln/grpc/ --experimental_allow_proto3_optional Missing value for flag: --experimental_allow_proto3_optional make: *** [Makefile:390: contrib/pyln-grpc-proto/pyln/grpc/primitives_pb2.py] Error 1 `

**Comment by vincenzopalazzo** [comment]
I think you have an old version of protoc, but no idea how to upgrade it. It depends on how you install protoc in the first place

**Comment by aprilinph** [comment]
Thanks! Yes, turned out to be an old version in OS, so that even in virtual environment it was being used.
