### ISSUE TITLE
Lightningd isn't keeping up with block height of bitcoind

### ISSUE THREAD

**Issue by ianthius** [ElementsProject/lightning#749]
I have been running a node for a few days. Recently it got out of date with the blockheight. It was only showing a blockheight of 505701 when the true blockheight was about 505766.

I saved the logs and then restarted the node. Then the block height became even less! (505671) It's not moving from there.

I am running on a pruned node. Have logs from current stale node and from previous when it was 505766.

**Comment by ianthius** [comment]
@cdecker maybe this is relevant from my logs, launching it again:

lightningd(1474): bitcoin-cli getblock 00000000000000000038e70ff9f4dabeeb3a61abf53f3fbef8e9220a6f63da12
 exited with status 1

**Comment by vedran6** [comment]
I have encountered the same issue. The sequence of events played out exactly the same, except I'm running a non-pruned node and on testnet. I had to restart the client several times before the block height got unstuck.

**Comment by laanwj** [comment]
I had the same issue, but after restarting `lightningd` it went away. I'm not running a pruning node on testnet.

Someone else also told me they're having this problem, on a non-pruned testnet node on a raspberry pi 3, but they keep having the issue - restarting the daemon, nor bitcoin core seems to advance it.

**Comment by ianthius** [comment]
Mine is also still stuck. but now on 505747. So it's a bit bizarre.

**Comment by Saibato** [comment]
I have this also on mainnet full node raspberry 3

**Comment by cdecker** [comment]
That is rather strange, so far we've only seen the short channel ID verification fail on pruned nodes, due to the funding tx being in the pruned set. That's to be expected and shouldn't impact users since it just means they're missing some channels in their local view.

Now it appears that some users running pruned nodes will be unable to catch up with the chain, because they try to rescan form a height that was pruned (nodes will rescan starting from their first channel open, which may end up being pruned).

Even more "interesting" is that some full nodes are not keeping up. I'll add some more instrumentation to the `getblock` call so we can see what happens there.

**Comment by cryptapus** [comment]
I have a pruned (`prune=550`) bitcoind v0.15.0.1 on mainnet with a couple of channels in `CHANNELD_AWAITING_LOCKIN`. Interestingly, after restarting lightningd `lightning-cli dev-blockheight` seems to be giving consistent -96 block lag (for instance 505892 on bitcoind, 505796 on lightningd). It doesn't seem to update dev-blockheight until after restarting lightningd.

Maybe relevant log data:

    lightningd(4773): bitcoin-cli getblock 00000000000000000038e70ff9f4dabeeb3a61abf53f3fbef8e9220a6f63da12 exited with status 1

**Comment by cdecker** [comment]
Ok a number of people have reported the lagging issue or the blockchain sync getting stuck. I'm working on adding a bit more instrumentation.

@cryptapus that message is related to verifying that channel 501408:487:1 is valid, not really part of the blockchain sync at all.

**Comment by pooleja** [comment]
Seeing this as well.  It seems like when I restart the lightningd it will get stuck on different blocks.  I also saw the same issue as @laanwj with the outputs, so maybe it is related?  I can't seem to get it to catch back up at this time.

**Comment by thestick613** [comment]
You might have ran out of hdd space, as running lightningd with DEBUG log level will fill up a few gb daily.

**Comment by cdecker** [comment]
@rustyrussell managed to find a bug in the sync logic, which is now merged into `master` so maybe you can try to pull and compile with the latest head.

**Comment by cryptapus** [comment]
@cdecker with your latest commits, still didn't have any success on my pruned node. It seemed to track well until I added funds and attempted to `fundchannel`. Then it stopped tracking my pruned node.

Interestingly, I then transfered my `.lightning` to a full node, started it up, and was left in a state of `{ "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "...`

I then checked to see if the funding_txid existed on an explorer, it did not, so I did a `sendrawtransaction` with the output of `fundchannel` on my bitcoind and now it's there. Hopefully that's helpful.

Of coarse I didn't bother recording the rawtransaction on my previous attempts and those are still stuck at `"CHANNELD_AWAITING_LOCKIN"`... I don't suppose there's any way of finding them again to push manually...

**Comment by cdecker** [comment]
Ok, so am I understanding correctly that the patch now works on an unpruned node, but pruned nodes are left in the cold? In addition some of the funding transactions were not broadcast and are now nowhere to be found?

In that case it should be ok, to use `sqlite3` to mark the outputs as available again, and deleting the channels in `CHANNELD_AWAITING_LOCKIN` from the `channels` table.

Delete the stale channels from the DB:
```
DELETE FROM channels WHERE state=2;
```

Then go through the outputs in the `outputs` table:

```
SELECT hex(prev_out_tx), prev_out_index, status FROM outputs WHERE status=2;
```

(remember to invert the hash to match the bitcoin format). Then ask `bitcoind` for it, e.g.,:

```
$ bitcoin-cli gettxout e4ca686470cf098484f85269e6aa05975616d6d5fb7a02fbac5ef5499c55fb13 1
{
  "bestblock": "0000000000000000002d6cca6761c99b3c2e936f9a0e304b7c7651a993f461de",
  "confirmations": 537,
  "value": 0.00030000,
  "scriptPubKey": {
    "asm": "0 6d209aa5ba251a6339ac6e1f69314da7edc32bfe09c534845ebf39b2231fcc09",
    "hex": "00206d209aa5ba251a6339ac6e1f69314da7edc32bfe09c534845ebf39b2231fcc09",
    "type": "witness_v0_scripthash"
  },
  "coinbase": false
}
```

If that returns a JSON response then you can mark that output as unspent:

```
UPDATE outputs SET status=0 WHERE hex(prev_out_tx)="13fb559c49f55eacfb027afbd5d616569705aae66952f8848409cf706468cae4" AND prev_out_index=1
```

It's rather involved, but it'll get your funds back :-)

**Comment by cryptapus** [comment]
@cdecker thanks for the tip. I was able to recover, but noticed something maybe interesting. I had tried to open a few channels so there were extra outputs in my `outputs` table that didn't exist. I would guess change from opening attempts, I just deleted them and recovered.

**Comment by cdecker** [comment]
Yeah, funding a tx will result in change being added to your `outputs` table, even before we see it in a block.

**Comment by cdecker** [comment]
@ianthius can you confirm that with `master` the blockchain is being synced correctly?

**Comment by ianthius** [comment]
Sadly the latest master did not fix my problem. Its slowly going back in time though! now I am in 505013... And I am losing funds as it goes. lol

**Comment by cdecker** [comment]
@ianthius can you try with a non-pruned node? If the blocks from the first establishment of the channel to the tip get pruned we can't catch up with the network.

**Comment by gdassori** [comment]
With a non-pruned node the issue persist with the current master.
