### ISSUE TITLE
First peer not ready

### ISSUE THREAD

**Issue by pandabit** [ElementsProject/lightning#751]
When I send a payment I'm getting hit with:

> first peer not ready: WIRE_UNKNOWN_NEXT_PEER"

Is there a way to clear the first peer?

**Comment by jb55** [comment]
Probably duplicate of #635

**Comment by cdecker** [comment]
What did you use to initiate the payment? `getroute` + `sendpay`, or directly `pay`, or the wrapper in `contrib/lightning-pay`?

**Comment by fenix2222** [comment]
I have the same issue. Channel is funded and tax has more than 10 confirmations. What I use “pay” command I get the above error. What can I do to fix it?

**Comment by cdecker** [comment]
Working on it ^^

**Comment by pandabit** [comment]
It comes up when I run `cli/lightning-cli pay <bolt 11>`

**Comment by cdecker** [comment]
I'd guess that the peer that it is trying to route through shows up as `connected=false`. #751 should fix that by marking the channel as unavailable when the underlying TCP connection gets closed.
