### ISSUE TITLE
Backoff failing subdaemons?

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#753]
Some users on the [Lightning Discord](https://discord.gg/xMby78P) are turning on `no-reconnect` because `channeld` likes to spam reconnect attempts. Would it hurt to add some state that backs-off failing subdaemons?

**Comment by jb55** [comment]
This might only make sense for channeld though...

**Comment by cdecker** [comment]
I wanted to do an exponential back-off when the last attempt did not stabilize, might be time to do that now :-)

**Comment by ZmnSCPxj** [comment]
I believe we already back off by quite a bit on reconnect attempts? Is this still needed?

**Comment by jb55** [comment]
I can't recall having an issue anymore, so perhaps...
