### ISSUE TITLE
Funding UTXO no longer registering

### ISSUE THREAD

**Issue by laanwj** [ElementsProject/lightning#754]
Running commit feb734086b9d890883baac542023d8416975ce19 (today's master).

On my testnet lightning node I tried to fund a channel, which failed, but now the funding UTXO doesn't seem to be returning to my wallet.

These transactions funded valid channels, earlier:
- [c0c0f4e2c596caa044633e4fa7a7fc97b2f9187a93d7e42dc7d4cc6497574e25](https://live.blockcypher.com/btc-testnet/tx/c0c0f4e2c596caa044633e4fa7a7fc97b2f9187a93d7e42dc7d4cc6497574e25/#output-index-1) (0.01 tBTC spent, 0.0898598 tBTC change)
- [ae7912e9e2ef40b5338ab0c406e7f0dad95419910e3271a01e698175e04a6bce](https://live.blockcypher.com/btc-testnet/tx/ae7912e9e2ef40b5338ab0c406e7f0dad95419910e3271a01e698175e04a6bce/) (0.01 tBTC spent, t0.07984904 BTC change)
- [cc117ccb5146d5201d436f79ca0d8d9db40a4b7827e143f47516781b6a030ae7](https://live.blockcypher.com/btc-testnet/tx/cc117ccb5146d5201d436f79ca0d8d9db40a4b7827e143f47516781b6a030ae7/) (0.01 tBTC spent, 0.06983828 tBTC change)

Every time I use 0.01 tBTC to fund a channel, so there should be change left.

The 0.06983828 tBTC change output of the last transaction in the chain doesn't seem to be spent, and has 83 confirmations. But `listfunds` shows:
```
{ "outputs" : 
        [  ] }
```
It might or might not have to do with a temporary [hiccup in blockchain processing](https://github.com/ElementsProject/lightning/issues/749#issuecomment-360055647), but it's past that now and lightningd and bitcoind are synchronized.

**Comment by laanwj** [comment]
I'm afraid that this just happened again. It seems that `fundchannel` hangs, the peer connection stays stuck in `OPENINGD` state, and (I surmise) the utxo is considered spent, without an actual funding transaction being sent.

Is there a way to manually recover from these, e.g. mark these as unspent again?

**Comment by gdassori** [comment]
If I have understand properly, as a workaround to unlock the unspents, you have to edit the sqlite3 file into ~/.lightning and mark the corresponding output to status 0. 

Also delete the related channel from channels table.

**Comment by laanwj** [comment]
That seems to have worked, thanks. E.g.
```
sqlite> update outputs set status=0 where hex(prev_out_tx)=="E70A036A1B781675F443E127784B0AB49D8D0DCA796F431D20D54651CB7C11CC";
```
(keeping in mind that `hex(prev_out_tx)` is reversed compared to the JSON output)
I've also deleted the channel and peer.

**Comment by Ulmo** [comment]
Thanks, this was useful.

**Comment by cdecker** [comment]
This seems to be a duplicate of #749, i.e., `lightningd` not keeping up with the blockchain.

**Comment by laanwj** [comment]
@cdecker I'm not sure that's the case, as I mentioned the problem still existed when it caught up with the blockchain.

**Comment by cdecker** [comment]
It did? Ok, then this might indeed be a new one. Would you mind testing with the latest `master` anyway? That should be able to stay synced with the blockchain now.

**Comment by laanwj** [comment]
Closing this issue, I have no way of reproducing this and have edited the database enough to be sure that there's no way to get useful post-mortem diagnostics from it.
