### ISSUE TITLE
`getroutes`: amounts and delays are wrong

### ISSUE THREAD

**Issue by daywalker90** [ElementsProject/lightning#7550]
I'm trying the new `getroutes` @rustyrussell and i encountered this:

regtest l1->l2->l3

```
[GetroutesRoutes { amount_msat: Amount { msat: 100000000 }, path: [GetroutesRoutesPath { amount_msat: Amount { msat: 100001001 }, delay: 11, direction: 1, next_node_id: PublicKey(*snip*), short_channel_id: ShortChannelId(114349209354240) }, GetroutesRoutesPath { amount_msat: Amount { msat: 100001001 }, delay: 11, direction: 0, next_node_id: PublicKey(*snip*), short_channel_id: ShortChannelId(114349209419776) }], probability_ppm: 900044 }]
```

with auto layers applied. Notice how the second `Amount` in the `path` is not `Amount { msat: 100000000 }` but `Amount { msat: 100001001 }` instead. So the l2 node does not get paid and errors rightfully with WIRE_FEE_INSUFFICIENT.

**Comment by daywalker90** [comment]
using cln-rpc from master + https://github.com/ElementsProject/lightning/pull/7549

**Comment by daywalker90** [comment]
looking at the `getroutes` tests this seems to be expected behaviour?! If that's actually the case then it would be very different from `getroute` and what `sendpay` expects as a path structure!

**Comment by rustyrussell** [comment]
OK, so getroutes() is different than getroute().  I should document this properly.

It's optimized towards onion creation, i.e. these are what you would put in the intermediary onions.  So, it's the path to the destination, not including the destination.  This will work better with `injectpayonion` (which I have yet to write(.  But to be fair, it should also include the final_ctlv value, too.
