### ISSUE TITLE
`askrene-inform-channel`: maximum_msat minimum_msat mismatch

### ISSUE THREAD

**Issue by daywalker90** [ElementsProject/lightning#7553]
Documentation says:
`askrene-inform-channel layer short_channel_id direction [maximum_msat] [minimum_msat]`

```
lightning-cli askrene-inform-channel test 1x2x3 0 1
{
   "constraint": {
      "layer": "test",
      "short_channel_id": "1x2x3",
      "direction": 0,
      "timestamp": 1723380012,
      "minimum_msat": 1
   }
}
```

Notice how this did not return with `"maximum_msat": 1`

**Comment by Lagrang3** [comment]
So the order in the documentation is wrong?

**Comment by daywalker90** [comment]
That's probably the most likely issue, hopefully internally there is no mixup.
