### ISSUE TITLE
Is CI not checking for memory leaks?

### ISSUE THREAD

**Issue by Lagrang3** [ElementsProject/lightning#7565]
After this issue #7560, it occurred to me that I have been pushing code that the CI have not checked for memory leaks.
As far as I know, I can enforce memory leak detection by setting the environment variable `LIGHTNING_DEV_MEMLEAK`, at least
that is what is written in `common/memleak.c`.

Locally I run pyln tests like this:
```
LIGHTNINGD_DEV_MEMLEAK=1 pytest tests/test_renepay.py -x
```
But CI is clearly not doing this check for memory leaks, otherwise #7560 would have been caught by it during PR review.

**Comment by rustyrussell** [comment]
Checking...

**Comment by rustyrussell** [comment]
Good catch!
