### ISSUE TITLE
Opening a payment channel from Testnet Lightning Faucet (TLF) to lightningd does not work

### ISSUE THREAD

**Issue by practicalswift** [ElementsProject/lightning#757]
Opening a channel from the Testnet Lightning Faucet (https://faucet.lightning.community/) to a `lightningd` node fails with the following error message:

```
lightningd(…): Peer …: Opening negotiation failed: feerate_per_kw 25000 above maximum 8860
```

Opening a channel from https://faucet.lightning.community/ to a `lnd` node works as expected.

The Lightning Faucet provides a very nice onboarding experience for new users on testnet. Having it compatible with `lightningd`'s default settings would be awesome.

**Comment by cdecker** [comment]
IMHO the fees should be ignored on testnet https://github.com/ElementsProject/lightning/blob/2f179fb6cb3b66ae83ba5ab12a2f5ea586e7e10b/lightningd/options.c#L358-L361

Maybe we have some wires crossed here?

**Comment by practicalswift** [comment]
@cdecker What would be the appropriate way to get access `ignore_fee_limits` from within `fundee_channel(…)`?

**Comment by cdecker** [comment]
These things are passed to subdaemons with init messages. But I don't see the `ignore_fee_limits` being passed to `towire_opening_init` so it could be that I'm mixing up cli params, and this is intended for commit tx fees? @rustyrussell would this be the correct param to pass to `openingd`?

**Comment by medisoft** [comment]
I have the same problem when trying to connect from my android phone with eclair wallet to c-lightning node

Opening negotiation failed: feerate_per_kw 53760 above maximum 1415

**Comment by cdecker** [comment]
> Opening negotiation failed: feerate_per_kw 53760 above maximum 1415

I'd guess that this is on mainnet though? In that case don't disable the fee estimation, it's important for security. Give the nodes a bit more time to hone in on a good estimate.
