### ISSUE TITLE
v24.08rc2 - bitcoin-cli not a valid config option

### ISSUE THREAD

**Issue by nakoshi-satamoto** [ElementsProject/lightning#7595]
I'm trying to test v24.08rc2
When I attempt to start lightningd I get an error message saying that "bitcoin-cli" is an unknown configuration option. This is a valid config option in v24.05 though, my bitcoin-cli is in a specific filepath that needs declared. Was this config changed in 24.08rc2 to something else?

**Comment by nakoshi-satamoto** [comment]
Example of my current config

bitcoin-cli=/home/satoshi/bitcoin-27.3/bin/bitcoin-cli

**Comment by nakoshi-satamoto** [comment]
lightningd: Config file /home/user/.lightning/config line 8: bitcoin-cli=/home/satoshi/bitcoin-27.0/bin/bitcoin-cli: unknown option

**Comment by vincenzopalazzo** [comment]
Can you post your logs? it is possible that some plugin like [bcli.c](https://github.com/ElementsProject/lightning/blob/master/plugins/bcli.c) is dying?

**Comment by nakoshi-satamoto** [comment]
When I go back to version 24.05 it works as normally. In this case the log shows nothing for 24.08rc2, I can re-attempt later in debug mode and post logs here.

**Comment by nakoshi-satamoto** [comment]
No other data in log file when attempted in debug

`2024-08-21T16:12:35.311Z INFO    lightningd: v24.08rc2
2024-08-21T16:12:35.311Z DEBUG   lightningd: Opened log file /home/satoshi/.lightning/ln-log.txt
2024-08-21T16:12:35.326Z DEBUG   plugin-manager: started(1446405) /home/user/apps/peerswap/peerswap
2024-08-21T16:12:35.341Z DEBUG   lightningd: io_break: check_plugins_manifests
2024-08-21T16:12:35.341Z DEBUG   lightningd: io_loop_with_timers: plugins_init
`

standard output shows
`lightningd: Config file /home/user/.lightning/config line 8: bitcoin-cli=/home/satoshi/apps/bitcoin-core/bitcoin-27.0/bin/bitcoin-cli: unknown option
`

**Comment by nakoshi-satamoto** [comment]
v24.08rc2 is not accepting required config settings necessary to work with Bitcoin Core.

**Comment by nakoshi-satamoto** [comment]
so what is the path to bcli then @Lagrang3 ? I never had to declare the path to that in the earlier versions.

**Comment by Lagrang3** [comment]
I am looking into the code, it seems that lightningd searches for the builtin plugins relative to his own path `../plugins`

**Comment by nakoshi-satamoto** [comment]
I found it

corelightning-24.05/usr/libexec/c-lightning/plugins

I'll test today when I get a chance with this path declared as a plugin in the config

**Comment by grubles** [comment]
Couldn't you symlink the binary to somewhere in your PATH?

**Comment by nakoshi-satamoto** [comment]
Declaring the path of the plugin does not work either, I get this
error starting plugin '/home/satoshi/clightning/corelightning-v24.08rc3/usr/libexec/c-lightning/plugins': opening pipe: Permission denied

**Comment by nakoshi-satamoto** [comment]
> Couldn't you symlink the binary to somewhere in your PATH?

And what would be the proper way to do that? This seems like a hakish work around. Would users of core lightning be expected to do the same?

**Comment by nakoshi-satamoto** [comment]
> Declaring the path of the plugin does not work either, I get this error starting plugin '/home/satoshi/clightning/corelightning-v24.08rc3/usr/libexec/c-lightning/plugins': opening pipe: Permission denied

I see I  made an error by not including /bcli at the end of that path. I did so and now I get this

lightningd: Could not run /usr/libexec/c-lightning/lightning_channeld: No such file or directory

**Comment by nakoshi-satamoto** [comment]
So Core Lightning only works if it is installed system-wide rather than from a local filepath, and only works if it is the same for Bitcoin Core?

**Comment by Lagrang3** [comment]
> So Core Lightning now only works if it is installed system-wide rather than from a local filepath, and only works if it is the same for Bitcoin Core?

No. It's not that. My node's binaries are in a custom path. And you shouldn't have to hack your way around.

**Comment by nakoshi-satamoto** [comment]
Thanks everyone. If I need to do symlinking I can, although not ideal. @Lagrang3  I'm curious what you are doing differently than me. Are you using bitcoin core in a custom path also? I'm using both Bitcoin Core and Core Lightning in a custom path.

I'm hopeful that this pre-release might also fix the payment issues I was having, why I was wanting to test this.

**Comment by Lagrang3** [comment]
yes. I have core lightning and bitcoin binaries in custom paths.
To upgrade I go through the steps `./configure --prefix=MYCUSTOMPATH && make && make install` that produce a directory structure like this:
```
$ tree /opt/lightning/24.08/
/opt/lightning/24.08/
├── bin
│   ├── lightning-cli
│   ├── lightningd
│   ├── lightning-hsmtool
│   └── reckless
├── libexec
│   └── c-lightning
│       ├── lightning_channeld
│       ├── lightning_closingd
│       ├── lightning_connectd
│       ├── lightning_dualopend
│       ├── lightning_gossipd
│       ├── lightning_hsmd
│       ├── lightning_onchaind
│       ├── lightning_openingd
│       ├── lightning_websocketd
│       └── plugins
│           ├── autoclean
│           ├── bcli
│           ├── bookkeeper
│           ├── chanbackup
│           ├── cln-askrene
│           ├── cln-renepay
...
```
which is exactly what you get when you extract the release binaries.

**Comment by Lagrang3** [comment]
I think we should add log messages to inform that builtin plugins are not loaded. We don't have those as far as I can tell from testing now.

**Comment by nakoshi-satamoto** [comment]
> I think we should add log messages to inform that builtin plugins are not loaded and also inform where are we trying to look for them. We don't have those as far as I can tell from testing now.

Great idea

**Comment by Lagrang3** [comment]
I hit it locally with the release binaries:
```
$ /home/lagrange/tmp/cln-24.08-release/bin/lightningd "--network=$network" "--lightning-dir=$LIGHTNING_DIR/l1" "--bitcoin-datadir=$BITCOIN_DIR" "--database-upgrade=true"
lightningd: Config file /tmp/lightning/l1/config line 1: bitcoin-cli=/opt/bitcoin/bin/bitcoin-cli: unknown option
```

Instead I had no issues with binaries compiled from source.

**Comment by rustyrussell** [comment]
> I have been running this under a filepath of /home/satoshi/clightning/corelightning-v24.08rc3/ (an example)

Right.  CLN has two modes, one is that it expects to be in the build directory (good for developers), the other in the --prefix directory it was configured with.

I'm surprised that this used to work!  But thanks for the report, I'll make it work!

**Comment by nakoshi-satamoto** [comment]
I compiled and it returns the same error. Can we bring back the bitcoin-cli= config option to declare a custom path for bitcoin-cli?
Right now the new version of CLN only supports bitcoin core if it is installed system wide at a specific filepath.

**Comment by nakoshi-satamoto** [comment]
I made a softlink of /usr/local/bin/bitcoin-cli to the bitcoin-cli in my custom path. Yeah this still does not work
when I run lightningd I get error
lightningd: Could not run /usr/local/libexec/c-lightning/lightning_channeld: Permission denied

I am trying to run v24.08rc3 that I compiled.

**Comment by nakoshi-satamoto** [comment]
The last issue "permission denied" is a different issue. I think it resulted from me installing with "sudo make install" while my umask was set to 027 instead of 022. I fixed the permissions with chmod.

I am now running v24.08rc3.

How easy would it be to bring back the bitcoin-cli= option in the lightning config file? This would eliminate the need of people to have to make symbolic links or compile with a custom path.

**Comment by Fonta1n3** [comment]
Hmm I am now getting the exact same issue when installing on Mac via brew. v24.05
