### ISSUE TITLE
Alternative port not gossiped correctly?

### ISSUE THREAD

**Issue by laanwj** [ElementsProject/lightning#760]
I started a testnet lightning node on port 9736, with
```bash
$ lightningd --ipaddr=<ip> --port=9736 ...
```
However, when I query the info, it insists the network address is on port 9735
```
$ lightning-cli getinfo
{ "id" : "...", "port" : 9736, "address" : 
        [ 
                { "type" : "ipv4", "address" : "...", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1659-gfeb73408", "blockheight" : 1260295, "network" : "testnet" }
```
Also the port shown on explorer.acinq.com is 9735, not 9736. I did correctly forward the port.

**Comment by cdecker** [comment]
Hi @laanwj, thanks for reporting this. I'm unable to reproduce this with my tests https://github.com/cdecker/lightning/commit/28b15591b7efe9bbc685fdc6d9096dd546378fd3, they seem to pass the correct port down to `gossipd` and they seem to get announced correctly.

Could you check which port `gossipd` actually listens on, e.g., using `netstat -anp | grep gossipd`? Could there be a `~/.lightning/config` file that specifies the default port?

**Comment by laanwj** [comment]
It listens on the correct port. I have another instance of lightningd listening on the other port, might that be the issue?
```
tcp6       0      0 :::9735                 :::*                    LISTEN      12343/lightning_gos 
tcp6       0      0 :::9736                 :::*                    LISTEN      724/lightning_gossi 
```

> Could there be a ~/.lightning/config file that specifies the default port?

No, there's nothing overriding the port.

**Comment by cdecker** [comment]
Which of the two runs with `--lightning-dir=~/.lightning/`? `lightning-cli` will talk to that instance by default.

**Comment by laanwj** [comment]
The one that listens at 9735 -- getinfo from both is here:
```
$ /home/user/src/clightning/cli/lightning-cli getinfo
{ "id" : "...", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "...", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1659-gfeb73408", "blockheight" : 506042, "network" : "bitcoin" }

 $ /home/user/src/clightning/cli/lightning-cli --lightning-dir=/home/user/.lightning.testnet getinfo
{ "id" : "...", "port" : 9736, "address" : 
        [ 
                { "type" : "ipv4", "address" : "...", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1659-gfeb73408", "blockheight" : 1260476, "network" : "testnet" }
```

So the `"port" : X` is different for both instances (which it needs to be, otherwise they'd collide), however the `"address":` is the same for both. Strange!

**Comment by cdecker** [comment]
Is the address a publicly routable one? I'm having a hard time reproducing this, my output looks like this when running with `--port=16331`:

```
{ "id" : "0279b30bfdb379d48205722441e3bbbc0987261f3e4a1d4d3e884d2e169c5b50ce", "port" : 16331, "address" : 
        [ 
                { "type" : "ipv6", "address" : "<public-ipv6-address>", "port" : 16331 } ], "version" : "v0.5.2-2016-11-21-1663-g25bcaeb-dirty", "blockheight" : 1260510, "network" : "testnet" }
```

**Comment by laanwj** [comment]
The machine's own IP is not publicly routable, however I specify a publicly routable IP using `--ipaddr=<ip>`, and the ports are forwarded from a router. I tried connecting to the ip:port from outside and it works.

**Comment by laanwj** [comment]
Where is the stuff in "address": determined? I could add some tracing to see how it ends up with the wrong port.

**Comment by laanwj** [comment]
I think I found the issue.
- This works :+1:
```bash
$ lightningd --port=9736 --ipaddr=92.110.144.95
```
- This works :+1:
```bash
$ lightningd --ipaddr=92.110.144.95:9736 --port=9736
```
- This does not work :x:
```bash
$ lightningd --ipaddr=92.110.144.95 --port=9736
```
So the order of arguments matters.

**Comment by cdecker** [comment]
Oh wow, nice catch @laanwj, I'll fix that ASAP.
