### ISSUE TITLE
CLN app crash on Umbrel Home

### ISSUE THREAD

**Issue by gerrylove0820** [ElementsProject/lightning#7617]
Good afternoon and hope you guy are having a great day, I am Gerry from Miami and I have been venturing on the space, but I’m still learning every single day about bitcoin and lightning, recently my CLN app crashed on Umbrel home server that I have been using for two years now, app wasn’t open at all and decided to uninstall and installed back again, I have never close my Chanel with boltz wish I opened using information from http://1Ml.com and got liquid wallet through greenlight wallet from block stream, the thing is that when I do installed back I get all different node name and all the funds on my previous node disappear, I try to do some research to see if there is any project that touches same issues with not luck, I wonder if you guys have some insight or type of recommendation to lead with this issue, thanks

**Comment by gerrylove0820** [comment]
Lost node name Violentset

**Comment by ShahanaFarooqui** [comment]
Regarding uninstalling & reinstalling event: I would recommend to contact Umbrel team as it should not have happened without your permission.

Regarding getting your channels and funds back from your old node: 

- If you have backed-up [both](https://docs.corelightning.org/docs/backup),  your HSM Secret and DB, then you can follow the recovery instructions from [here](https://docs.corelightning.org/docs/recovery#using-database).

- If you only have the HSM Secret backup then you can follow funds recovery instructions from [here](https://github.com/ElementsProject/cln-application/discussions/34).

**Comment by gerrylove0820** [comment]
How do I know if I have a back up off my HSM secret and DBGerry Rodriguez On Sep 1, 2024, at 5:03 PM, ShahanaFarooqui ***@***.***> wrote:﻿
Regarding uninstalling & reinstalling event: I would recommend to contact Umbrel team as it should not have happened without your permission.
Regarding getting your channels and funds back from your old node:


If you have backed-up both,  your HSM Secret and DB, then you can follow the recovery instructions from here.


If you only have the HSM Secret backup then you can follow funds recovery instructions from here.

**Comment by Impa10r** [comment]
@gerrylove0820 if you did not backup them manually, you don't have the backup. Reinstall wiped your node. RIP 2m sats. 

In Umbrel 1.1 it very tricky to get access to the app data/bitcoin folder. You need su account, as sudo does not work. CLN is cruel for beginners. Use LND next time, it lets you save 12 words recovery seed.

**Comment by ShahanaFarooqui** [comment]
Closing this issue now. For future reference, [link](https://github.com/getumbrel/umbrel-apps/issues/1443#issuecomment-2342433578) for node backup instructions on Umbrel.

**Comment by Impa10r** [comment]
> Closing this issue now. For future reference, [link](https://github.com/getumbrel/umbrel-apps/issues/1443#issuecomment-2342433578) for node backup instructions on Umbrel.

Thanks. Maybe put these instructions into the Umbrel App itself?
