### ISSUE TITLE
Multiarch docker builds of pre-releases

### ISSUE THREAD

**Issue by mrfelton** [ElementsProject/lightning#7622]
Would be great if the docker builds (https://hub.docker.com/r/elementsproject/lightningd/tags) were all multiarch. Currently, it seems that only the main releases support multiple platforms, whilst the pre-releases only support `linux/amd64`. That creates friction for people that would like to help test the pre-release, and limits usefulness of the docker image to people that are running on linux.

All docker builds should support linux and mac.

**Comment by ShahanaFarooqui** [comment]
Till now we were not publishing release candidates on Docker. I might have published an RC for testing but it was not officially supported. We recently added this support in PR #7571 and fixed the triggering event in PR #7625. So it should be available from next release onwards.
