### ISSUE TITLE
Core lightning crashes with FATAL SIGNAL 11

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#7645]
Core lightning v24.08 is crashing with FATAL SIGNAL 11 if `alias` is missing.

References:
![Crash-1](https://github.com/user-attachments/assets/d4e58ab4-f96a-4494-9ba7-b6727102fb97)
![Crash-2](https://github.com/user-attachments/assets/10907035-1dbb-43d7-9440-c4e43b7f5fab)

**Comment by cdecker** [comment]
Looks like the culprit is `*channel->alias[LOCAL]`. Are we missing an alias at this time? We should be filling them in if they are missing, but maybe this is a channel loaded from the DB and predates aliases?

**Comment by surfac3** [comment]
in case you would need some data or logs feel free to tell me what should i run and ill post in here.

I am the one who expirienced the issue.

**Comment by surfac3** [comment]
I tried to update to latest master -  CLN v24.08-10-g78b9ccf

but havent helped

**Comment by rustyrussell** [comment]
This is a different crash.  We are somehow not setting the local alias, presumably a historical channel.

**Comment by whitslack** [comment]
@rustyrussell: How could this have happened if the database migration of b5bd9072457b6e6a93687f40064859bdbdaac347 had executed?

**Comment by surfac3** [comment]
I have pulled the latest master and the fix works! 

Succesfuly pulled CLN v24.08-13-g5bd3d51 and it purrs like a kitten
