### ISSUE TITLE
`cln-grpc`: Specify a host and port

### ISSUE THREAD

**Issue by ErikDeSmedt** [ElementsProject/lightning#7654]
### Feature Request

The grpc-plugin always binds to the `0.0.0.0` address.
This is inconvenient if you want to only use the grpc-plugin locally.
I want to bind to `127.0.0.1`

It would be nice to have a `--grpc-host` parameter

**Comment by vincenzopalazzo** [comment]
I agree, for security reason, we should bind the plugin by default to 127.0.0.1

**Comment by rustyrussell** [comment]
This was closed by https://github.com/ElementsProject/lightning/pull/7479
