### ISSUE TITLE
connection: false

### ISSUE THREAD

**Issue by BTCxPinto** [ElementsProject/lightning#766]
Getting this error for all my channels-  "connected" : false,

what do i need to do to fix it?

**Comment by fenix2222** [comment]
Getting the same error. Once I funded the channel, after 6 confirmations I checked the status and both of my channels have `connected: false` and `state: ONCHAIND_OUR_UNILATERAL`. When I try to send payment I get `first peer not ready: WIRE_UNKNOWN_NEXT_PEER`. And if I use listchannes, my channels have `public: false`.

**Comment by cdecker** [comment]
Sounds like you attempted to close the channel while disconnected, and now the peers will refuse to open a new connection until the closed channel is settled, e.g., about 1 day.

As for the routing, that'll be fixed by #756 :-)

Closing as a duplicate of #635

**Comment by fenix2222** [comment]
I am not trying to close the channel. I have never gotten it working in the first place. As soon as it is funded (at least 1 confirmation), it goes to `connected: false`
