### ISSUE TITLE
"lightning-cli withdraw" doesn't seem to work

### ISSUE THREAD

**Issue by jamesgmorgan** [ElementsProject/lightning#769]
Specifying either "all" or a valid# of satoshi both get "Invalid satoshis" error:

  ubuntu@ip-172-16-254-233:$ lightning-cli listfunds
  { "outputs" : 
	[ 
		{ "txid" : 
  "ea58ebaf55144f61684b5421d8c8ba210365c289d163e2454a4a9ce296626de8", "output" : 0, 
  "value" : 147191 } ] }

  ubuntu@ip-172-16-254-233:$ lightning-cli withdraw all 
  16P2BzxWuKWRL3ZRNGszLgnodgyoGb6e5D
  "Invalid satoshis"

  ubuntu@ip-172-16-254-233:$ lightning-cli withdraw 147000 
  16P2BzxWuKWRL3ZRNGszLgnodgyoGb6e5D
  "Invalid satoshis"

**Comment by ZmnSCPxj** [comment]
You have the arguments in the incorrect order.

    lightning-cli withdraw 
16P2BzxWuKWRL3ZRNGszLgnodgyoGb6e5D all

The help was changed recently to reflect the correct order: https://github.com/ElementsProject/lightning/commit/b13c65dacb55e79e1148493fa6c794af678c8660

**Comment by cdecker** [comment]
Sorry for twisting the help message there.

**Comment by jamesgmorgan** [comment]
Ah I should have thought to guess that!  Thanks @ZmnSCPxj @cdecker
