### ISSUE TITLE
made 3 addresses with newaddr, funded them from the testnet faucet, but they don't appear in listfunds after >6 confirmations

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#771]
I'm not sure how to debug this, but i think it's because the c-lightning internal database instance that i have been using is very old.

**Comment by cdecker** [comment]
Did you have a channel opened before? It might be addressed by PR #770 which I'll merge shortly.

**Comment by thestick613** [comment]
I have had multiple channels opened and even a closed one. Will the funds appear after that? :)

**Comment by thestick613** [comment]
Well, magically, they appeared right now, so it seems #770 fixes it.
