### ISSUE TITLE
Add support for Bitcoin testnet4

### ISSUE THREAD

**Issue by Schnema1** [ElementsProject/lightning#7723]
**Issue:**
Core lighting can not connect to bitcoin testnet4

**Reproduce**
Download the latest bitcoin release. For now it is v28rc2. This Version supports testnet4. 

Change bitcoin config to:
chain=testnet4

Lighting conf:
Note the rpcport for testnet4 is 48332 

I'm unable to implement the changes as I have only little programming and git skills. But I can add the information I collected so far:

CDecker in telegram:
"Do we even have a testnet4 entry in the chainparams.c file? If not we might want to add it."

-> No, there is only the testnet3 config. Changing the port in this file does not fix the problem. 

I think the relevant information is here:
https://bips.dev/94/

"Existing software that implements support for Testnet 3 would only require addition of the network parameters (magic number, genesis block, etc.) to be able to follow Testnet 4."

I don't know where these network parameters have to be added in core lightning nor where to find the right values. This is the reason for this feature request.

**Comment by vincenzopalazzo** [comment]
I am closing this because there is another issue that it is asking the same thing https://github.com/ElementsProject/lightning/issues/7303
