### ISSUE TITLE
Can not find GPG key ID: DCA40B7128DA62A8 on any pgp key server

### ISSUE THREAD

**Issue by overcoin** [ElementsProject/lightning#7743]
v24.08 is signed by ShahanaFarooqui. This tag was signed with the committer’s verified signature but I can not find GPG key ID: DCA40B7128DA62A8 on any pgp key server.

**Comment by cdecker** [comment]
All Keys used for signatures by maintainers are stored here: https://github.com/ElementsProject/lightning/tree/master/contrib/keys

**Comment by ShahanaFarooqui** [comment]
@overcoin, my release and tag signing keys are already available in `contrib/keys/sfarooqui.txt`.

The latest release has been signed with a new key, `A327573C97589BF5`, which is already available on several key servers. I just uploaded my tag signing key, `DCA40B7128DA62A8`, to `keyserver.ubuntu.com`, `pgp.mit.edu`, and `hkps://keys.openpgp.org`.
