### ISSUE TITLE
`connectd` consistently taking 100% cpu

### ISSUE THREAD

**Issue by JssDWt** [ElementsProject/lightning#7757]
### Issue and Steps to Reproduce
`connectd` is consistently taking 100% cpu. It causes regular disconnects to peers. These disconnects happen because pings are not returned in time, causing the peer to disconnect.

Here's a snapshot of the `connectd` process captured with `perf`
![perf](https://github.com/user-attachments/assets/6aaa4e05-3449-4784-a989-7809ff080c2a)

The CPU consumption happened with cln 24.02.1. It still occurs with cln v24.08.1. This perf trace is from v24.08.1.

**Comment by rustyrussell** [comment]
Hmm, `perf report` would be more useful.  Even better would be to attach with `gdb` and use the `bt` command to get a backtrace (assuming it's in the troubling part).

**Comment by yaslama** [comment]
> Hmm, `perf report` would be more useful. Even better would be to attach with `gdb` and use the `bt` command to get a backtrace (assuming it's in the troubling part).

I sent you privately the perf.data file
