### ISSUE TITLE
change peer address

### ISSUE THREAD

**Issue by frbitten** [ElementsProject/lightning#7759]
I have a peer that was initially connected via TOR and I would like to change the address without using Tor.

Is there a way to change the peer address without closing the channel?

**Comment by cdecker** [comment]
Sure, call `connect node_id@new_ip` and you should be good.

**Comment by frbitten** [comment]
> Sure, call `connect node_id@new_ip` and you should be good.

I was testing just this and posting the error in the original post. I don't understand why the Tor connection error occurs if I don't use Tor and the connection address is not Tor.
