### ISSUE TITLE
Rune rate is not working as expected

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/lightning#7790]
The rate restriction on the rune causes the error `Invalid rune: Not permitted: too soon` after the first command execution.

How to Reproduce:

1: Run the following command to create a rune with a rate limit of 100 requests per minute:
```
lightning-cli createrune -k restrictions='[["rate=100"]]'
```

2: Use the generated rune to make repeated calls in a script:
```
#!/bin/bash
COMMAND="lightning-cli --regtest --lightning-dir=/.../.lightning commando \"pubkey\" \"getinfo\" \"[]\" \"rune-from-step-1\""
for i in {1..10}; do
    echo "Executing command iteration $i"
    eval $COMMAND
done
``` 
3: The getinfo command successfully responds on the first iteration, but subsequent iterations fail with the error:
```
{"code": 19537, "message": "Invalid rune: Not permitted: too soon"}
```

**Comment by johngribbin** [comment]
Just want to add that I see the same issue when testing runes for Remote. I was initially testing with a rune that had a rate limit of 120, so I upped it to 1000.

When I simultaneously fetch UTXOs, invoices, and transactions (three RPC calls), I get this error: Invalid rune: Not permitted: too soon. 

I increase the rate to 10,000 and the error goes away. A user reported that he too was able to resolve the issue by increate the rate limit to 10,000 - but this doesn't seem right. 

Thanks

**Comment by ShahanaFarooqui** [comment]
TIL that reading the documentation carefully can save so much debugging time :D! According to the [createrune](https://docs.corelightning.org/reference/lightning-createrune) documentation:

```
rate: the rate limit, per minute, e.g. "rate=60" is equivalent to "per=1sec".
```

This means that with a rate of 100/minute in above example, we are allowed one call every 0.6 seconds (60/100). We can also confirm this by adding a sleep timer in the script to control the command frequency:

```
#!/bin/bash
COMMAND="lightning-cli --regtest --lightning-dir=/.../.lightning commando \"pubkey\" \"getinfo\" \"[]\" \"rune-from-step-1\""
for i in {1..10}; do
    echo "Executing command iteration $i"
    eval $COMMAND
    sleep 0.6
done
```

Using a sleep interval of >=0.6 seconds results in all successful responses, while setting it to 0.5 seconds causes alternating successes and `Not permitted: too soon` errors.

For a rate limit of 10,000/minute, each request needs to wait at least 6 milliseconds (1 RPC/6 ms). I assume that the processor’s response time is slow enough that the timer resets before the next call, resulting in successful responses and creating the impression that the issue is resolved.

Closing the issue now since no further action is required.
