### ISSUE TITLE
cln-plugin-grpc: log spam: Failed to broadcast notification

### ISSUE THREAD

**Issue by JssDWt** [ElementsProject/lightning#7836]
### Issue and Steps to Reproduce
The grpc plugin logs a `Failed to broadcast notification` warning [here](https://github.com/ElementsProject/lightning/blob/bc9834c45981d868ffb2984e9fd610e36b8fa568/plugins/grpc-plugin/src/main.rs#L142). But the sender it's sending will never have a receiver: [source](https://github.com/ElementsProject/lightning/blob/bc9834c45981d868ffb2984e9fd610e36b8fa568/plugins/grpc-plugin/src/main.rs#L77)

Remove the log or initialize the receiver.

### `getinfo` output
v24.08

**Comment by vincenzopalazzo** [comment]
I will try to spend some time on this in the week because I would like to put this warning in production to avoid my log notification going crazy!

Thanks for reporting it

**Comment by rustyrussell** [comment]
Example (from CI):

```
lightningd-1 2024-11-25T10:42:37.539Z DEBUG   lightningd: Adding block 101: 7c721343fbf7d27734638c01bc816f775dda04b7cb555397a5546ec8a86c8896
lightningd-1 2024-11-25T10:42:37.548Z DEBUG   plugin-cln-grpc: Received a message: CustomNotification(Object {\"jsonrpc\": String(\"2.0\"), \"method\": String(\"block_added\"), \"params\": Object {\"block_added\": Object {\"hash\": String(\"7c721343fbf7d27734638c01bc816f775dda04b7cb555397a5546ec8a86c8896\"), \"height\": Number(101)}}})
lightningd-1 2024-11-25T10:42:37.548Z DEBUG   plugin-cln-grpc: Dispatching custom notification Object {\"jsonrpc\": String(\"2.0\"), \"method\": String(\"block_added\"), \"params\": Object {\"block_added\": Object {\"hash\": String(\"7c721343fbf7d27734638c01bc816f775dda04b7cb555397a5546ec8a86c8896\"), \"height\": Number(101)}}}
lightningd-1 2024-11-25T10:42:37.548Z UNUSUAL plugin-cln-grpc: Failed to broadcast notification SendError(BlockAdded(BlockAddedNotification { hash: 0x7c721343fbf7d27734638c01bc816f775dda04b7cb555397a5546ec8a86c8896, height: 101 }))
```
