### ISSUE TITLE
Automatically reconnect to previous peers on process restart

### ISSUE THREAD

**Issue by vedran6** [ElementsProject/lightning#786]
1. I opened a connection with a peer (`lightning-cli connect 03e...`).
2. While still in the `GOSSIPING` state, I stopped `lightningd` via the cli.
3. I restarted `lightningd` and the usual process of rewindings blocks and UTXO discovery took place. However, when invoking the `listpeers` cli command I noticed that I was disconnected from that peer. The output was as follows:

```json
{ "peers" : 
	[ 
		{ "id" : "03e38d5fabd53c15f0d3bc37c2e5d332dad8cf34cb4332035bdcfbc71a246c1675", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] } ] }
```
4. I had to manually invoke the `connect` command again (already invoked once, during step 1), and only then did the `listpeers` output indicate we are connected:

```json
{ "peers" : 
	[ 
		{ "state" : "GOSSIPING", "id" : "03e38d5fabd53c15f0d3bc37c2e5d332dad8cf34cb4332035bdcfbc71a246c1675", "netaddr" : 
			[ "178.199.30.191:9735" ], "connected" : true, "owner" : "lightning_gossipd" } ] }
```

The issue can be reproduced deterministically every time. Is this expected behavior or a bug? It appears to me that `lightningd` should reconnect to previously connected peers automatically.

**Comment by vedran6** [comment]
It appears that invoking the `connect` command again and then restarting the process caused a peer duplication in the `listpeers` command.

**Comment by jb55** [comment]
It will reconnect if it has an ip address hint, which we save in the database *after* creating a channel.

This is kind of a hack, we should be able to resolve an address from a pubkey eventually (see #246, #547)

**Comment by ZmnSCPxj** [comment]
We already do connect back to peers on restart, but only if we have channels to them.  I believe this is sufficient.

@rustyrussell also recently added code that would delete peers from the table if we no longer have channels to them, in order to prevent the duplication in the `listpeers` command.  This does mean that closing a channel will also mean we no longer talk to the peer.  Maybe this can be closed?

**Comment by ZmnSCPxj** [comment]
I believe we already do this; closing.
