### ISSUE TITLE
plugin-cln-xpay: Not redirecting pay (unknown arg \"maxfeepercent\") and overly verbose log entries

### ISSUE THREAD

**Issue by tobomobo** [ElementsProject/lightning#7926]
### Issue and Steps to Reproduce
running v24.11 on Raspiblitz (x86 Proxmox VM)

When enabling `xpay` and trying to pay an invoice with Zeus, the redirect does not work because `maxfeepercent` is an unknown argument for `xpay`. Paying the same bolt11 invoice with `lightning-cli xpay -k invstring=lnbc...` works immediately.

Also when `xpay-handle-pay` is true I get the following 'spam' in my logs

<img width="658" alt="SCR-20241210-kyuc" src="https://github.com/user-attachments/assets/8c421a40-4b64-4ee7-a233-8fbc79971cea">

### `getinfo` output
{
   "id": "XXX",
   "alias": "XXX",
   "color": "XXX",
   "num_peers": 10,
   "num_pending_channels": 0,
   "num_active_channels": X,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": "XXX.onion",
         "port": 9736
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9736
      }
   ],
   "version": "v24.11",
   "blockheight": 874093,
   "network": "bitcoin",
   "fees_collected_msat": X,
   "lightning-dir": "/home/bitcoin/.lightning/bitcoin",
   "our_features": {
      "init": "08a0880a8a59a1",
      "node": "88a0880a8a59a1",
      "channel": "",
      "invoice": "02000002024100"
   }
}

**Comment by Lagrang3** [comment]
`xpay` doesn't have the `maxfeepercent` option. To fix this, the hook that translates the call to `pay` into `xpay` must
replace the `maxfeepercent` into a `maxfee` value.
I can do this. I've just recently did this with renepay.

**Comment by Lagrang3** [comment]
Connected to Zeus, I can pay after adding the patch #7936.
Still there is some UI detail to fix.
The payment goes through but Zeus screen shows an error screen with no message.
I think this is related to the fact that xpay does not reply with a `status: complete` field.
