### ISSUE TITLE
Fee jumped ""channel ALL: lightning_closingd: Their fee jumped 14661 to 13410 when ours was 14035""

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#801]
I got this error connecting to peer 039a8f88dca257f4f67a2c65bfcc6ab1d398488334d3b3a78d514c8e3f6638a903:

"channel ALL: lightning_closingd: Their fee jumped 14661 to 13410 when ours was 14035"

In the log:

lightningd(13304): peer 039a8f88dca257f4f67a2c65bfcc6ab1d398488334d3b3a78d514c8e3f6638a903: Peer has reconnected, state CLOSINGD_SIGEXCHANGE
lightningd(13304):jcon fd 28: Failing: channel ALL: lightning_closingd: Their fee jumped 14661 to 13410 when ours was 14035

"Their fee jumped 14661 to 13410 when ours was 14035" repeats in the log 5 times (presumably whenever I tried to reconnect).  I think I might have found in the log where it went bad:

[logecerpt.txt](https://github.com/ElementsProject/lightning/files/1669769/logecerpt.txt)

What's going on?  How do I get more information about this for debugging?  Is this supposed to happen?

**Comment by rustyrussell** [comment]
What was remote end? They're supposed to get closer to our offer, not jump over it!

**Comment by Ulmo** [comment]
I'm confused by this sentence:

"Their fee jumped 14661 to 13410 when ours was 14035"

So the fee was -1251, jumped 14661 to 13410, when ours was 14035.  If it was -1251, then it getting closer to our 14035 means it's getting better, right?

But, your interpretation isn't what the sentence says.  What your interpretation would be written this way:

"Their fee jumped from 14661 to 13410 when ours was 14035."

**Comment by cdecker** [comment]
Should be fixed by #847
