### ISSUE TITLE
[Feature request] Argument for specifying a different bitcoin RPC host

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#804]
I was trying to use lightningd with docker where bitcoin RPC is on another container.
Sadly, by default lightningd only connect to localhost.

To support my use case, I needed to add `rpcconnect` to the `bitcoin.conf` file used by the underlying `bitcoin-cli`. This is quite of a hack for something that should be here out of the box.

Here my current hack:
https://github.com/NicolasDorier/lightning-charge/blob/8946d01130e548fd0a8bce7741dee9758912460e/bin/docker-entrypoint.sh#L29

**Comment by ZmnSCPxj** [comment]
Duplicates #329

**Comment by NicolasDorier** [comment]
Closing, duplicate.
