### ISSUE TITLE
invoice returns two values expiry_time and expires_at

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#806]
$ cln1 invoice 1 expired_test2 "testing expired" 50
{ "payment_hash" : "ecc8fa03fb1697413f6299d402b0892f3a40cb2656f0a5a3f9186a769a241224", "expiry_time" : 1517069031, "expires_at" : 1517069031, "bolt11" : "lntb10p1pdxeg44pp5any05qlmz6t5z0mzn82q9vyf9uaypjex2mc2tglerp48dx3yzgjqdqcw3jhxarfdenjqetcwp5hyetyxqzpjcqpxucw40ph3a4gmuq8g5mnl8m6wt9x08ugtt0wex8fkj89truz4gzcsw4ugajkrs65lwjhc67ah6jr5chtza0plarhz0jzarjkrh49739cqxulggh" }       
There seems to be no difference between `expiry_time` and `expires_at`. Whats supposed to be the difference?

**Comment by cdecker** [comment]
This is part of the JSON-RPC migration, in which we have consolidated the results returned by JSON-RPC calls. `expiry_time` is the old name, whereas `expires_at` is the new name. Eventually `expiry_time` will be removed since it is only an alias.

**Comment by cdecker** [comment]
You can filter out the old variants by passing in `--allow-deprecated-apis=false` when starting `lightningd`.
