### ISSUE TITLE
Node responds to pong > 65532 with lesser bytes

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#811]
A node receiving a ping message:

    SHOULD fail the channels if it has received significantly in excess of one ping per 30 seconds.
    if num_pong_bytes is less than 65532:
        MUST respond by sending a pong message, with byteslen equal to num_pong_bytes.
    otherwise (num_pong_bytes is not less than 65532):
        MUST ignore the ping.

Its not ignoring though. I'm not sure whats happening
cln0 dev-ping 03f045c016ce9bc8fb797aa0617599aae0a712eed6842f499fb6fcb9b329ef7e71 1 65545
gives a totlen of 13?

**Comment by cdecker** [comment]
That's easy, the number overflows over the size of a `uint16` so you end up with `65545 - 65532 = 13` bytes :wink:
