### ISSUE TITLE
Ability to disconnect with a peer

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#812]
How do I disconnect with a peer when I don't have a channel with it? I'm just gossiping and no longer want to gossip with it

**Comment by Sjors** [comment]
Or in my case, I accidentally connected to a testnet peer.

**Comment by jBarz** [comment]
I can try to work on this if no one else is.

**Comment by cdecker** [comment]
Go for it @jBarz :+1:

**Comment by ZmnSCPxj** [comment]
Closed in #1181
