### ISSUE TITLE
Can we reconnect to the channel after withdraw

### ISSUE THREAD

**Issue by skenan** [ElementsProject/lightning#830]
Process:
I created a channel with another peer:
* The fund in channel is 2000 msat
* The balance left is 8000 msat

Then I just withdraw the 8000 msat to my original bitcoin address without closing the channel.

The channel is still open, I can see that with `lightning-cli listpeers`

But I can't see the channel with `lightning-cli listchannels`

I wonder if I can reconnect the channel since it's still open. Or I have to close the peer to get my fund?

**Comment by cdecker** [comment]
I think you're mixing several different concepts. `listpeers` shows your directed peers in all possible states, whether they are connected or not. `listchannels` shows the publicly available channels, not just your direct peers. For your channel to show up in `listchannels` it needs to have at least 6 confirmations and both endpoints have to have opted into making this a public channel.

The balance that you're seeing and withdrawing, is the balance that you alone control, i.e., the balance that is not part of any channels. So `withdraw`ing those funds do not do anything to your channel, which will stay open until you or your peer closes it. To get the funds out of the channel, you'd first `close` it, wait for your funds to become available again and then `withdraw` them to your bitcoin wallet.

**Comment by skenan** [comment]
@cdecker  Thanks for your explanation! But after I did the withdraw, I was not able to reuse the money in the channel except closing it, is this a expected behavior?

**Comment by ZmnSCPxj** [comment]
@skenan yes.

Money in a Lightning channel is not money onchain.  The `withdraw` command requires onchain funds.  To get money from a Lightning channel to onchain, first you need to close one or more of your channels.

There is proposal to directly move onchain and offchain funds. https://github.com/lightningnetwork/lightning-rfc/issues/280 and also this mailinglist post: https://lists.linuxfoundation.org/pipermail/lightning-dev/2017-December/000865.html

**Comment by skenan** [comment]
@ZmnSCPxj Thank you. I can close this issue.
