### ISSUE TITLE
funding_txid wasn't transmitted and isn't on blockchain but funds were removed from wallet

### ISSUE THREAD

**Issue by sfmcnally** [ElementsProject/lightning#831]
funding transaction isn't recorded in blockchain even as unconfirmed. It has been at least 4 hours since the fundchannel command claimed to have executed sucessfully. My node id is:

02fe079f0737c4d5b7bd5add5e4ce1bdc2f0b79fcbe4b45aad8388f05b54ac1df8

here is the result of listpeers:

{ "id" : "0387e3780a4325eb38421fb83000a6f6c0ffa4a69ea0c81db3f00e8e5015c9e8a1", "connected" : true, "netaddr" : 
			[ "148.251.82.174:9735" ], "channels" : 
			[ 
				{ "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "adec6492d7ebb0740902913cc56544985af5d995736ca346c52fddabde396315", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

**Comment by jacobyandmeyers** [comment]
Can confirm.  Transactions are not appearing on blockchain and have left wallet.  Several examples below (including one working channel).  Have already restarted lightningd will now reboot (restart bitcoin) and reconnect to nodes to observe behavior.


 { "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "2565d11fa348e0bf8a9e5f24f715c65da6299c099710798ad7a041f67d93a56b", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

{ "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "91953b10bd7408196e67f4fdb1f2072dc71e7e0aeb730b6c061edc018039f70f", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

 { "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "2ce8ddca0a9f88ca68e6217f8e5213337fc7686cd0c9432947bec7ed4d668a7f", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

{ "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "e78839db7d71b50b7719742c17d6c60e87de51006e553aaf85db1d1de0d17a3c", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

{ "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "cb11bef8ea76a6f58f4338243b64825206142b5dd49da9b26a57b15efa2ef567", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

 { "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "ff0ed9edd4cf57c647228ebbfbaadb45c0cbdc9a624efb5318c0471b22c59c8b", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

 { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "506513:2245:1", "funding_txid" : "f3a89d5ba04b06062000f88aacc851b93d9335523d4cf95a5d90913441c0e6e3", "msatoshi_to_us" : 229410250, "msatoshi_total" : 400000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

**Comment by ZmnSCPxj** [comment]
Duplicates #803

**Comment by cdecker** [comment]
We have recently merged PR #842 that should allow `lightningd` to correctly broadcast transactions again. In addition we created PR #864 so that users can sync with the UTXO set as seen by `bitcoind` which will thus recover funds that were marked as spent by an unsuccessful funding attempt.

@jacobyandmeyers @sfmcnally  could you pull the latest `master`, compile and use `dev-rescan-outputs` to recover funds and attempt to open a new channel (with another peer)?

**Comment by sfmcnally** [comment]
`listfunds` returned this before `dev-rescan-outputs`

{ "outputs" : 
	[ 
		{ "txid" : "e9fbf8c1cb34da8d8dc650b8db35448e73b729625c830c39bd871387ca295f3c", "output" : 0, "value" : 34094 } ] }

and this after:

{ "outputs" : 
	[ 
		{ "txid" : "fd939b51a160eaf3deb22c74b9b905e778e0840556459e70f5ccdb1ad5c1c55c", "output" : 1, "value" : 259518 }, 
		{ "txid" : "75097027c71e45688a0025cb62824588d849dab1fd5ccf63008de2824b6c5a10", "output" : 0, "value" : 87991 }, 
		{ "txid" : "958ca3ab5680972286ce2d7dce72583fb590fd373a2c34b997f291da234ac4c6", "output" : 0, "value" : 62353 } ] }

So that worked. I'll try a new channel next.

**Comment by jacobyandmeyers** [comment]
I still have a backup of the DB but just this morning wiped all of the outputs (except one) and broadcast a new funding transaction in testbed0.   There are still some funds left in the old DB that I did not bother with so I will spin up testbed11 with that old DB.   What I think "should" happen is that the one output that was valid will now be invalid (since I just spent from it).  The remaining outputs that have valid funds should be available again.

I will wait for this new transaction to fully confirm then rebuild from master and use dev-rescan-outputs in testbed0 as well.

FWIW, I am convinced that by not waiting for each channel to completely open, rapidly funding several channels, I created a race condition that was unrecoverable with the current set of tools.  dev-rescan-outputs will be super helpful in this respect.  It may be useful to review sequencing of channel funding txs.

**Comment by sfmcnally** [comment]
Here's the result of `fundchannel`:

lightning-cli fundchannel 02c119d2fd2e98a88f50d0d2ee4213255b7b8ec2be3a95f9aabd6afb09dd25b083 150000
lightningd(4547): peer 02c119d2fd2e98a88f50d0d2ee4213255b7b8ec2be3a95f9aabd6afb09dd25b083: State changed from UNINITIALIZED to OPENINGD
lightningd(4547): peer 02c119d2fd2e98a88f50d0d2ee4213255b7b8ec2be3a95f9aabd6afb09dd25b083: State changed from OPENINGD to CHANNELD_AWAITING_LOCKIN
{ "tx" : "020000000001015cc5c1d51adbccf5709e45560584e078e705b9b9742cb2def3ea60a1519b93fd0100000000ffffffff026b49010000000000160014c9ef812ed2022eb3cd6184a57888369079f06f5ef04902000000000022002025f40f0173ee057d69da460e4995f8e212995d63de10f7da44746a2598cc075602483045022100a503f9a36b7b914942956ec0f64b044201d9d47f259baea777d594b99ffacb4b02204a0c7dd2fedb8cba58a5cb4e969cdda667f2c7b9c944ac092138bc864a88140e012103128db3db09d8485674ef273905a158c07d40af9560d2956aa8c5554d01e7478100000000", "txid" : "144698a9c2e0a3106f3d9b9de53143647f0fd282377cea438756a368a7f2a858"

We'll see if that one takes.

**Comment by sfmcnally** [comment]
that one is at least showing up as unconfirmed, so that is promising. 
[https://blockchain.info/tx/144698a9c2e0a3106f3d9b9de53143647f0fd282377cea438756a368a7f2a858](url)

**Comment by sfmcnally** [comment]
@cdecker success:

lightningd(4547): peer 02c119d2fd2e98a88f50d0d2ee4213255b7b8ec2be3a95f9aabd6afb09dd25b083: State changed from CHANNELD_AWAITING_LOCKIN to CHANNELD_NORMAL

**Comment by sfmcnally** [comment]
I still have some funds stuck in channels that are stuck in channels that are `CHANNELD_AWAITING_LOCKIN`.  I tried to `close` them and `dev-fail` them and now they are repeatedly trying to broadcast a closing transaction that fails with error 25 `missing inputs`. See below. 
{ "peers" : 
	[ 
		{ "id" : "034f1ec90e841677f8463600c5468f4e0409ae7d04b24885eb6f01912b85e295c3", "connected" : false, "channels" : 
			[ 
				{ "state" : "CHANNELD_AWAITING_LOCKIN", "funding_txid" : "e9fbf8c1cb34da8d8dc650b8db35448e73b729625c830c39bd871387ca295f3c", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "029efce538a7f6ba7873b1bd00e0028ca39a658b96af326d349fa45bfa34226073", "connected" : true, "netaddr" : 
			[ "173.71.149.66:9735" ], "channels" : 
			[ 
				{ "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "506897:1628:1", "funding_txid" : "958ca3ab5680972286ce2d7dce72583fb590fd373a2c34b997f291da234ac4c6", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "031c527494f295220d26a1814c18e7db3f4f03203ce1a53a0b74b52ed570a3972a", "connected" : false, "channels" : 
			[ 
				{ "state" : "CHANNELD_AWAITING_LOCKIN", "funding_txid" : "c4092b5757099739e2dfeee9da736d634ea4989cc21ac8cb5a8e4b464dec3ae2", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "0387e3780a4325eb38421fb83000a6f6c0ffa4a69ea0c81db3f00e8e5015c9e8a1", "connected" : false, "channels" : 
			[ 
				{ "state" : "CHANNELD_AWAITING_LOCKIN", "funding_txid" : "adec6492d7ebb0740902913cc56544985af5d995736ca346c52fddabde396315", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "02c119d2fd2e98a88f50d0d2ee4213255b7b8ec2be3a95f9aabd6afb09dd25b083", "connected" : true, "netaddr" : 
			[ "98.186.249.155:9735" ], "channels" : 
			[ 
				{ "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "507123:1172:1", "funding_txid" : "144698a9c2e0a3106f3d9b9de53143647f0fd282377cea438756a368a7f2a858", "msatoshi_to_us" : 150000000, "msatoshi_total" : 150000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }


lightningd(4547): Broadcasting tx 020000000001013c5f29ca871387bd390c835c6229b7738e4435dbb850c68d8dda34cbc1f8fbe90100000000ee561b8001c3120100000000002200205996394b748c45a947d18fed25459feeae83e51c62200f479320f328651fe4bd0400483045022100b511e5ec0b1431ed1789d0e7739aac6eeebca5c3b38002829452b5dd5856c6990220452fdee9aa42c3248ab8c19159b1ad113e05dac4819ccb23d62f25e67b21f90701483045022100e1df32e6a21bbb366725a2bdad8e75c677cfadbe9a63b99517706aea6253c21d022037d75af87c02dcf5aa8cce684e362694dac38c7e70bc5c02e5fdf1a36ab742cd0147522102caf78081c90b9a15f6ea3b08b30e30ae5980cade207d5860acbfc42ccf4f3b0521039b59f7d5f3f14ae51d186e91ac6089c08d158ad94050df7cee3a51e0525aa60952ae72d9ef20: 25 error code: -25
error message:
Missing inputs

lightningd(4547): Broadcasting tx 02000000000101e23aec4d464b8e5acbc81ac29c98a44e636d73dae9eedfe239970957572b09c400000000002c6b988001710c0100000000002200207a49410c2dedb412af4c706ba811821ca57650b51699ebe29ea132756ca59e51040047304402207a7c7c36f1287a463916fa0cae807f5a303f672d584d5b67153f8ab873976a6b0220273a47739ab9594e2a41d1570b8c03b09a05a3c987ff635df28cb40e98880e130147304402202fd2e5137bf5f966ffa79cb6d8dee8248876566b4a4be8599a83973e7f74293b0220153f37d43abf77110376ea664e03763edf4019df72d9255302c61ca87aa69eab014752210331523589801e7ffa3219e0ce119d9fd67bc5bf8c1c7ddb23b924ca36db0165ec2103b059e57858045571a62e1fb33101043438ce41451c07fe454fd7bba0ff8f531152aefb3d9020: 25 error code: -25
error message:
Missing inputs

lightningd(4547): Broadcasting tx 02000000000101156339deabdd2fc546a36c7395d9f55a984465c53c91020974b0ebd79264ecad00000000003530368001867f0100000000002200205c44ab47439eba495f486239888430b81e315a7bb192c3819a7297db794a4d6f04004830450221009e5b7c6095922d754462b5cd6204ee3a629103f599f5c53077393274117cbf1a02206372735122fde7963fec268770e4dbba6062fcae8406159f87c88266ca2210e901473044022061d8412876235ca893cfd7c898065a59cb90014b08a1e18d2c128a724fb0fc9a022062ae2b712b99c27db854b60e3ce047211470d44081112fd92085bac99fe3c9c801475221036116c806190959b3fd69bce1248eb0c97d605f88a09095830d455c60a881eda3210392ce215659b2310d3d8403463836ca10504424a2776d9707fb720906988c1b7a52ae429bfc20: 25 error code: -25
error message:
Missing inputs

**Comment by cdecker** [comment]
@sfmcnally the missing inputs on `dev-fail` is to be expected, the funding TX was never broadcast after all. Will need to add a command to forget a specific channel, otherwise they'll linger forever.

With both of you not running into the original problem anymore I think we can close this issue, thanks for the help :+1:
