### ISSUE TITLE
Ability to increase fund in a connected channel

### ISSUE THREAD

**Issue by ziyang0621** [ElementsProject/lightning#835]
I have funded a channel with a node to buy stickers from Blockstream store. 

I want to put more Bitcoin to the channel to buy more stuff. However seems there is no command to do that, I tried **lightning-cli fundchannel <node_id> <amount>** command, but it returns **{ "code" : -1, "message" : "Peer already CHANNELD_NORMAL" }**.

So do I have to close the channel first then open a channel again with that node? Or should have add a new command to fund to an existing channel.

**Comment by ZmnSCPxj** [comment]
Better for you to connect to another peer with a new channel, really, as it would better support the network and would also make you a tiny hub able to route payments.  At least that would offset a little the onchain funds you would spend to open a new channel.

Spec needs to be modified first to make this feature implementable.  See: https://github.com/lightningnetwork/lightning-rfc/issues/280

Defer to later, when we can actually fix lightning-rfc issue 280 in spec version 1.1.

**Comment by ZmnSCPxj** [comment]
Also, currently, c-lightning is one-peer-one-channel. Other Lightning software (lnd, Eclair) do not have this limitation.  So for c-lightning specifically, you need to have a channel with another node. The Blockstream store is itself powered by c-lightning also, so even if you use lnd or Eclair you will not be able to make more than one channel with the Blockstream node.

**Comment by cdecker** [comment]
Closing this since it belongs in https://github.com/lightningnetwork/lightning-rfc
