### ISSUE TITLE
Unable to establish stable connection to make payment to blockstream store

### ISSUE THREAD

**Issue by fenix2222** [ElementsProject/lightning#843]
### Issue and Steps to Reproduce
I have been trying to buy stickers off blockstream store for a week now with no success. Keep getting various issues. My bitcoin node is running fine. My lightning node has different issues.

Issue # 1
I connected to 0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917 node and got successful connection. Then I funded a channel and waitied for 6 confirmations. When I tried to pay for the stickers using bolt11, payment failed and I the channel got into ONCHAIND_THEIR_UNILATERAL state. I was hoping for it to eventually close after 144 blocks, but it has been 3 days now and my funds are still locked with channel in ONCHAIND_THEIR_UNILATERAL state.

While I encountered this issue, I tried to establish another channel with 0235447c7485ff2b945bac5fbc366d54a87389bab8cacf1b64b26ec01e96bd165a. Same issue happened.

Issue # 2
When both channels from issue above got stuck, I tried 3rd time and connected to 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432. This channel was successfully funded and its state is CHANNELD_NORMAL. However, I still cannot pay. If I run getroute, I get no route and when I list channels my node is not listed.

Issue # 3
I tried to open a fourth channel with 035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8. I funded the channel and got a transaction ID as d62d8f530a9fc68ab05c7596883fa7096f9dfaf1a5460103e3b40cb007e5da99. Channel is in CHANNELD_AWAITING_LOCKIN state, but transaction is not available and I cannot find it anywhere and it has been more than 24 hours.

So now I have 4 channels: 1 in CHANNELD_NORMAL, 1 in CHANNELD_AWAITING_LOCKIN and 2 in ONCHAIND_THEIR_UNILATERAL states and none of them are useful while all my funds are locked on all of them.

I tried stopping the lightningd few times, pulled latest code many times and rebuilt it using `make`. Still same issue. How can I fix this?

### `getinfo` output
```
cli/lightning-cli getinfo
{ "id" : "02a0b3f4049964e02cc5f31b479f2fbebb70941377620a5451fdc7edddd3bdf443", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "178.62.85.122", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1724-g0223d83", "blockheight" : 506748, "network" : "bitcoin" }
```

### `listpeers` output
```
cli/lightning-cli listpeers
{ "peers" : 
	[ 
		{ "id" : "035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8", "connected" : true, "netaddr" : 
			[ "78.63.23.25:9735" ], "channels" : 
			[ 
				{ "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "d62d8f530a9fc68ab05c7596883fa7096f9dfaf1a5460103e3b40cb007e5da99", "msatoshi_to_us" : 150000000, "msatoshi_total" : 150000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917", "connected" : false, "channels" : 
			[ 
				{ "state" : "ONCHAIND_THEIR_UNILATERAL", "short_channel_id" : "506489:1287:1", "funding_txid" : "3f9f4447e42f872c2874bf8745baa28ef300174371be3765cf1f261bf609fa5c", "msatoshi_to_us" : 200000000, "msatoshi_total" : 200000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "connected" : true, "netaddr" : 
			[ "104.198.32.198:9735" ], "channels" : 
			[ 
				{ "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "506477:1663:1", "funding_txid" : "327c6406a6ef175d2bf7513557161165960ee58126b79be3aad3736dce621d3c", "msatoshi_to_us" : 180000000, "msatoshi_total" : 180000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "0235447c7485ff2b945bac5fbc366d54a87389bab8cacf1b64b26ec01e96bd165a", "connected" : false, "channels" : 
			[ 
				{ "state" : "ONCHAIND_THEIR_UNILATERAL", "short_channel_id" : "506135:1532:1", "funding_txid" : "07375a21b5eb77ebba50c7d39f28a97145e9562e5e2c38bceb7bac6494a222f4", "msatoshi_to_us" : 170000000, "msatoshi_total" : 170000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "state" : "GOSSIPING", "id" : "03447c9f9d17a6f082dcf4cf97e8949e3fe6fd704baa54560aef0d742593659d15", "netaddr" : 
			[ "[::ffff:104.131.56.241]:49038" ], "connected" : true, "owner" : "lightning_gossipd" }, 
		{ "state" : "GOSSIPING", "id" : "02829de2d8762ac70f6a243c7e210e1a41d7bc9fe909d09f120b7f0b0252c83858", "netaddr" : 
			[ "[::ffff:74.71.22.170]:52579" ], "connected" : true, "owner" : "lightning_gossipd" } ] }
```

**Comment by kubilay902** [comment]
Maybe you should change the topic to "maintaining channel stability and fund management" because I have the same issues too. 
`5 CHANNELD_NORMAL
1 ONCHAIND_OUR_UNILATERAL
1 CLOSINGD_COMPLETE
1 CHANNELD_AWAITING_LOCKIN`

I dont know how to delete old peers from my list, I dont know how to get my funds back. :) So maintaining and managing channels is a bit problematic from my side.

**Comment by fenix2222** [comment]
@cdecker Any comments? I am stuck with 4 channels where all are useless and don't know how to close them to try again.

**Comment by cdecker** [comment]
Can you update to the latest `master` version and restart? We have fixed most of the issues that were causing unilateral closes and channels being stuck in `awaiting_lockin`.

You can also use `dev-rescan-outputs` to re-enable outputs that were marked as spent by stuck channels.

**Comment by fenix2222** [comment]
@cdecker Updated to the latest. Channels didn't change, still have 4 unusable channels. I was able to successfully open the 5th channel. Connected, funded it. It was fine. As soon as I tried to pay for blockstreamstore stickers channel got to ONCHAIND_THEIR_UNILATERAL state. So now I have 3 of those :). So the problem is: as soon as execute pay, command just hangs and doesn't return anything. I left it hanging for an hour, by that time my invoce at the store has already expired. So I can never pay. Why is that a problem? I do have enough funds in the channel, prior to payment `getroute` gives me a route, so I am assuming there is a route to that node.

**Comment by cdecker** [comment]
Can you provide us with the logs of `lightningd` while performing the `pay` that fails the channel?

**Comment by fenix2222** [comment]
@cdecker How can I close all 3 channels with ONCHAIND_THEIR_UNILATERAL. It has been more than a week for these channels sitting in that stage. If I can close those to get my funds back, than I can try to pay again for the stickers.

**Comment by cdecker** [comment]
The funds should be back in your `listfunds` output, we just haven't cleared the terminated channels from the `listpeers` output. Can you cross-check the output of `listpeers` with `listfunds`? You should see the `funding_txid` in `listpeers`, be able to look it up in a blockexplorer and see the closing transaction spending that output. Then the closing transaction ID should also show up in `listfunds` since it returned the funds directly to you.

**Comment by fenix2222** [comment]
@cdecker I have gotten a latest code now. Now `pay` command doesn't freeze but gives me this
```
{ "code" : 204, "message" : "failed: WIRE_TEMPORARY_CHANNEL_FAILURE (First peer not ready)", "data" : { "erring_index" : 0, "failcode" : 4103, "erring_node" : "43f4bdd3ddedc7fd51540a6277139470bbbe2f9f471bf3c52ce0649904f4b3a070d56594be825a8cc18c778e57abeed99ca64a4dde623da59ee90a7ced454b37", "erring_channel" : "508529:1522:0" } }
```

I am assuming there is an issue with a route. How can I pick a different route for `pay` command, I can't seem to find a parameter.

**Comment by fenix2222** [comment]
Any updates?

**Comment by cdecker** [comment]
We have changed the way we handle payment failures quite a bit lately, can you pull and build the latest `master` and retry? It should attempt to perform the payment until it either succeeds or it fails with no more paths to try.

**Comment by cdecker** [comment]
Closing this issue as outdated, since the routing issues have been addressed and payments are reattempted a number of times.
