### ISSUE TITLE
channeld: crashing due to WIRE_ERROR

### ISSUE THREAD

**Issue by BTCKitty** [ElementsProject/lightning#844]
Similar to issue #592
### Issue and Steps to Reproduce
Tried sending a payment and this is what happened:
lightningd(16742): peer 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)
lightning_channeld(16969): STATUS_FAIL_PEER_IO: bad reestablish msg: WIRE_ERROR 00110000000000000000000000000000000000000000000000000000000000000000000e496e7465726e616c206572726f72
lightningd(16742): peer 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)
lightning_channeld(16973): STATUS_FAIL_PEER_IO: bad reestablish msg: WIRE_ERROR 00110000000000000000000000000000000000000000000000000000000000000000000e496e7465726e616c206572726f72
lightningd(16742): peer 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)
lightning_channeld(16979): STATUS_FAIL_PEER_IO: bad reestablish msg: WIRE_ERROR 00110000000000000000000000000000000000000000000000000000000000000000000e496e7465726e616c206572726f72
lightningd(16742): peer 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)
lightning_channeld(16985): STATUS_FAIL_PEER_IO: bad reestablish msg: WIRE_ERROR 00110000000000000000000000000000000000000000000000000000000000000000000e496e7465726e616c206572726f72
lightningd(16742): peer 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)
lightning_channeld(16994): STATUS_FAIL_PEER_IO: bad reestablish msg: WIRE_ERROR 00110000000000000000000000000000000000000000000000000000000000000000000e496e7465726e616c206572726f72

### `getinfo` output
"version" : "v0.5.2-2016-11-21-1659-gfeb7340", "blockheight" : 506789, "network" : "bitcoin"

**Comment by rustyrussell** [comment]
Hmm, the other end is sending "Internal error".  That's a real problem (for them!).

If it hasn't resolved, you can 'dev-fail 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432' and it should drop to chain.
