### ISSUE TITLE
lightningd issues when using a pruned bitcoin node

### ISSUE THREAD

**Issue by marzig76** [ElementsProject/lightning#853]
### Issue and Steps to Reproduce

I have a pruned node (--prune=1024) that's fully synced.  When I initially started lightningd, it synced up just fine.  When I ran `lightningd dev-blockheight`, it showed `{ "blockheight" : 506637 }` which was current at the time.  I shut down the Lightning node for a few days, but left my Bitcoin node running.

When I started my Lightning node back up a few days later, I noticed that the block height never updated.  My Bitcoin node is fully synced (at block 506901 as of this comment).  If I run `lightningd dev-blockheight`, I still get the same `{ "blockheight" : 506637 }`. 

I noticed that when I now start my Lightning node, it says:

```
lightningd(13588): bitcoin-cli getblock 00000000000000000028683ca594897bdb15b13c172a3a22b736abc68f15d935
 exited with status 1
```
And then just sits there, doing nothing.  

That block hash is from over 3 weeks ago, before I ever even started playing around with Lightning.

Is c-lightning supposed to work with pruned nodes?  If not, then we can close the issue and move on.

### `getinfo` output

`{ "id" : "xxxx", "port" : 9735, "address" : 
	[  ], "version" : "v0.5.2-2016-11-21-1693-g24ba5d6", "blockheight" : 506637, "network" : "bitcoin" }
`

I obscured my "id", but the address field above was actually already blank.

**Comment by marzig76** [comment]
If I run `bitcoin-cli getblock 00000000000000000028683ca594897bdb15b13c172a3a22b736abc68f15d935` myself, I get this (which is expected):

`error code: -1
error message:
Block not available (pruned data)
`

**Comment by ZmnSCPxj** [comment]
No, lightningd is currently not made to work pruned, but maybe @cdecker plans to change that in the (far?) future. On startup lightningd starts scanning 100 blocks before its last known blockheight (to my knowledge), so I am unsure why it starts from 3 weeks ago.

**Comment by cdecker** [comment]
If the first channel was opened/confirmed at height `h`, then `lightningd` will rescan all blocks starting from height `h-100`. If we didn't open a channel yet, then we just set `h` to the current tip height.

Yes, we don't really support pruned nodes just yet, but we'll change that some time in the future.

**Comment by marzig76** [comment]
Thanks.

So I did open and fund a channel before this issue started happening, which is stuck in the state `CHANNELD_AWAITING_LOCKIN`.

I assume I'll have to re-sync my Bitcoin node (with no pruning) in order to get access to these funds?

**Comment by marzig76** [comment]
Upon further research, it looks like this is a duplicate of bug [749](https://github.com/ElementsProject/lightning/issues/749).

Also, @cdecker, [this comment](https://github.com/ElementsProject/lightning/issues/749#issuecomment-360161835) of yours looks like it will resolve the issue of my stuck channels.  I'll try this later.  Closing this out.

Thanks for the help.

**Comment by cdecker** [comment]
@marzig76 I also have a new RPC command that does that UTXO sync automatically, so no need to manually edit the DB.

**Comment by marzig76** [comment]
@cdecker 

I used the sqlite3 trick and got my funds out without an issue.  Thank you.  However, I am curious, which RPC call does the UTXO sync?

**Comment by ZmnSCPxj** [comment]
@marzig76 PR #864

**Comment by marzig76** [comment]
@ZmnSCPxj thanks
