### ISSUE TITLE
Mainnet: Node operation stalled, processing strange transactions

### ISSUE THREAD

**Issue by windsok** [ElementsProject/lightning#856]
### Issue and Steps to Reproduce
I noticed my mainnet node has stopped all normal operation and is now only processing strange transactions originating from the node 024f5f1ddd1cf78afb23dcd2895d665f1f287ddc2ad1445a01a60e8cc5356b61b3

This has been happening for about the last hour, possibly longer.

My log shows about 3-4 messages per second that look like the following, and the log now shows nothing else but these messages:

```
lightningd(25104): peer 024f5f1ddd1cf78afb23dcd2895d665f1f287ddc2ad1445a01a60e8cc5356b61b3: Got depth change 0->32 for d25637d7c81d4e45976da99a429bfe03dd3c3193c614985c07b4e0f14431f7d0
lightningd(25104): peer 024f5f1ddd1cf78afb23dcd2895d665f1f287ddc2ad1445a01a60e8cc5356b61b3: Got depth change 0->32 for d25637d7c81d4e45976da99a429bfe03dd3c3193c614985c07b4e0f14431f7d0
lightningd(25104): peer 024f5f1ddd1cf78afb23dcd2895d665f1f287ddc2ad1445a01a60e8cc5356b61b3: Got depth change 0->32 for 5af11eb2ae7a4717e70bdcdd7467c8411f8453d6ea5a82ac4a8e7f55d77e0128
lightningd(25104): peer 024f5f1ddd1cf78afb23dcd2895d665f1f287ddc2ad1445a01a60e8cc5356b61b3: Got depth change 0->32 for d25637d7c81d4e45976da99a429bfe03dd3c3193c614985c07b4e0f14431f7d0
lightningd(25104): peer 024f5f1ddd1cf78afb23dcd2895d665f1f287ddc2ad1445a01a60e8cc5356b61b3: Got depth change 0->32 for d25637d7c81d4e45976da99a429bfe03dd3c3193c614985c07b4e0f14431f7d0
lightningd(25104): peer 024f5f1ddd1cf78afb23dcd2895d665f1f287ddc2ad1445a01a60e8cc5356b61b3: Got depth change 0->32 for d25637d7c81d4e45976da99a429bfe03dd3c3193c614985c07b4e0f14431f7d0
```

some further examples here: https://gist.github.com/windsok/465e10ac77f8d39d7f222de77cbd2c10

### `getinfo` output
getinfo, and all cli commands stall and do not return.

**Comment by cdecker** [comment]
This was potentially addressed by PR #833, could you please pull the latest `master`, recompile and test again?

**Comment by windsok** [comment]
Thanks, done. Node is warming up now. I'll check it again later and let you know

**Comment by windsok** [comment]
@cdecker that does seem to have fixed it, thanks!
