### ISSUE TITLE
sendpay STATUS_FAIL_PEER_BAD: commit_sig with no changes

### ISSUE THREAD

**Issue by alvenca** [ElementsProject/lightning#859]
On mainnet, I've had this error with "sendpay" command, with a couple of different channels and remote nodes, although I do not know which implementation they are running.

lightning_channeld(9881): STATUS_FAIL_PEER_BAD: commit_sig with no changes

Extended log (corrected truncated lines)
https://gist.github.com/alvenca/5fba11ef52e3ba785cbd8c84c7f2229c

The channels is immediately dropped to ONCHAIND_OUR_UNILATERAL 

I can't reproduce it with a "pay" command because the route is custom made to execute a self-payment through severals hops. I think this is not the root cause because I previously tested the route creation on testnet and got the delays right, etc (no WIRE_FINAL_INCORRECT_CLTV_EXPIRY errors) and executed this kind of payements ok on mainnet. But I mention it for completeness.

Maybe some kind of desynchronization? Any ideas?

### `getinfo` output
{
  "id": "03f3ba88c3e9e68b10f8c1e877252a157291ddc24aa378e9cb6f8b3bd0fed2e706",
  "port": 9735,
  "address": [
    {
      "type": "ipv4",
      "address": "X.X.X.X",
      "port": 9735
    }
  ],
  "version": "v0.5.2-2016-11-21-1734-g64bdee6b",
  "blockheight": 506997,
  "network": "bitcoin"
}

**Comment by alvenca** [comment]
Sorry for the incomplete information: In this case remote node was 
035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8 (#RECKLESS)
and it seems it's running lnd. Maybe @chemicstry could check his logs.

The other time I remember remote was 039514e5d704c59a0eba65d25fc5fe559a1641243ccdf80c980b1fc10ca9c30ca2 (Bitrefill) but don't know what are they running.

**Comment by cdecker** [comment]
I think `lnd` tried to send a commit to us without any changes, which the [spec prohibits](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements-11) IIRC. Maybe @roasbeef or @rustyrussell can confirm this?
