### ISSUE TITLE
c-lightning is raising the undead!!

### ISSUE THREAD

**Issue by crabel99** [ElementsProject/lightning#862]
### Issue and Steps to Reproduce
`lightningd` is spawning zombies! I noticed I had a bunch of zombie processes after running `top` 
[zombies.txt](https://github.com/ElementsProject/lightning/files/1683269/zombies.txt)

To see if I could kill the parent process I ran `pstree -paul` with the following result:
[tree.txt](https://github.com/ElementsProject/lightning/files/1683283/tree.txt)

The parent was the PID of the process that I have running. This happens every time I run `lightningd`.

Platform: MacPro (Early 2009)
OS: Ubuntu 16.0.4 LTS
Bitcoin: 0.15.1
lightningd: v0.5.2-2016-11-21-1727-g1a297a7

### `getinfo` output
[getinfo.txt](https://github.com/ElementsProject/lightning/files/1683304/getinfo.txt)

**Comment by cdecker** [comment]
Duplicate of #779
