### ISSUE TITLE
`sendpay` should give back more details on failure

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#866]
Arguably, one use case for the low-level `sendpay` interface is to have the caller create its own routes using its own routing algorithms. However if `sendpay` fails the caller would need to know exactly how it failed --- what onion reply failcode was returned, who returned it, what channel was it referring to.

Thus for `sendpay` failures we need to provide detailed `code`:

* -1 Catchall nonspecific error
* -2 A previous `pay` or `sendpay` is still in progress.
* -3 Already paid with this rhash.
* -4 Unparseable onion reply.  Caller should try a completely different route. There will be a `data` field, an object with the single field `onionreply` which contains the reply as hex.
* -5 Non-retryable routing error.  Permanent error at the payee.  There will be a `data` field, with a routing-failure object.
* -6 Retryable routing error.  Caller should try an alternate route.  There will be a `data` field, with a routing-failure object.

A routing-failure object contains:

* `origin_index` the index on the route of the node which failed. 0 for the first node, and so on, or -1 if the local node failed (e.g. not enough capacity on the channel to the first hop node). This is provided in case the caller makes a route that passes through the same node multiple times.
* `erring_node` the pubkey id of the indicated node as a hex string.
* `erring_channel` the short channel id of the channel after the indicated node. Not present if `origin_index` points to the last (payee) node.
* `failcode` the failure code as a JSON number. Refer to BOLT4.
* `channel_update` the channel update message from the failing node, if failcode has UPDATE bit set (refer to BOLT 4) and `origin_index` is not -1 (the local node), as a hex string.

**Comment by rustyrussell** [comment]
I think we should offset the error codes, say100 to 199 for pay/sendpay, and put them in a header by themselves somewhere.

Afaict they don't need to be negative, and I really prefer apis where I can deduce the call from the error code.

And it leaves error code 0-99 for generic errors.

**Comment by ZmnSCPxj** [comment]
@rustyrussell OK, I have started this idea, with all errors in a header (including the JSON-RPC 2.0 standard errors currently embedded in `lightningd/jsonrpc.c`).  I propose offset 200-299 for pay/sendpay, simply since most Bitcoin addresses are "P2xx" as in "pay to xx".

**Comment by ZmnSCPxj** [comment]
#define PAY_IN_PROGRESS 200
    #define PAY_RHASH_ALREADY_USED 201
    #define PAY_UNPARSEABLE_ONION 202
    #define PAY_DESTINATION_PERM_FAIL 203
    #define PAY_TRY_OTHER_ROUTE 204
    #define PAY_ROUTE_NOT_FOUND 205
    #define PAY_ROUTE_TOO_EXPENSIVE 206

The last two errors `PAY_ROUTE_NOT_FOUND` and `PAY_ROUTE_TOO_EXPENSIVE` will only occur with `pay` command (alternatively we can make `PAY_ROUTE_NOT_FOUND` a common error `COMMON_ROUTE_NOT_FOUND` between `pay` and `getroute`).  `PAY_ROUTE_TOO_EXPENSIVE` is for when `pay` will accept a percentage limit (default 0.5%) of additional fees paid.

We probably need to expose `JSONRPC2_PARAM_ERROR`, or maybe better create a `command_fail_param` for other parameter errors like "msatoshi not a number" and so on.  But those can be over another PR.

**Comment by rustyrussell** [comment]
Ack!
