### ISSUE TITLE
Do not continue reconnecting if the last failure was permanent

### ISSUE THREAD

**Issue by laanwj** [ElementsProject/lightning#871]
I get the following, repeatedly, in the log of my mainnet lightning node:
```
lightningd(23449): lightning_channeld(<peerid>): STATUS_FAIL_PEER_IO: bad reestablish revocation_number: 316 vs 366
lightningd(23449): peer <peerid>: Peer transient failure in CHANNELD_NORMAL: Owning subdaemon lightning_channeld died (33792)
```
This happens after the node aborted with a repeated "missing inputs" error (I don't have the exact log of that anymore, sorry.) It looks like that caused my node to be out of whack with another peer, but that doesn't stop it from trying.

**Comment by cdecker** [comment]
Yeah, we need to stop reconnecting if we terminated with a permanent failure. That particular one indicates that the two endpoints disagree on the version of the state.

**Comment by cdecker** [comment]
I took the liberty of making this a broader issue that we can use to track progress.

**Comment by ZmnSCPxj** [comment]
Is this still an issue?

**Comment by laanwj** [comment]
I don't have any way to test, sorry.

**Comment by ZmnSCPxj** [comment]
@cdecker ? Is this "broader issue" still existing?

**Comment by cdecker** [comment]
I think we can close, it got better once we had the backoff mechanism and then I think we fixed it completely by transitioning the channel into a failing state and disabling reconnection completely
