### ISSUE TITLE
listchannels empty but CHANNELD_NORMAL with listpeers

### ISSUE THREAD

**Issue by corbelantoine** [ElementsProject/lightning#874]
Hi,

I have two nodes, I created a channel with 200000sat from one of them and sent 10000sat to the second node using lightning. I tried to send the fund back but couldn't, I tried with smaller amount and it worked until I tried to change the fees using the command dev-setfees. I first tried to set all fees to 0 and tried to pay again, it didn't work so I set it back to the old value { "immediate" : 43144, "normal" : 39223, "slow" : 8609 }. I tried this on both side because I thought I couldn't find the whole amount because of fees.
Now that I set my fees back to normal I can't find a valid route between my nodes. listpeers shows a CHANNELD_NORMAL on both side but listchannels is empty, also on both sides.

I have two questions: 
Why couldn't I send the whole remaining balance from the second node back to the first one?
Why can't I send any transaction from my nodes, with any amount and from both sides, and why is my channel list empty.

I also get this error message from time to time:
`error message:
66: min relay fee not met`
when my first node tries to broadcast a tx (error 26)
my second node tries as well at the same time but I get this error:
`error message:
Missing inputs` (error 25)

Thanks!

**Comment by cdecker** [comment]
The specification has a [reserve value](https://github.com/lightningnetwork/lightning-rfc/blob/2c3466a2af8e62215b9240f9932256a509652b5d/02-peer-protocol.md#the-open_channel-message) (that you might see in `listpeers`. This is a balance that no node may go below (see the spec for the rationale).

Please don't use `dev-*` commands unless you know exactly what their effect is, they are extremely dangerous. In this case you were trying to set off-chain fees, but `dev-setfees` sets the on-chain fees...

**Comment by cdecker** [comment]
`min relay fee` refers to the reduced fees you specified using `dev-setfees`, `missing inputs` just means that `bitcoind` already knows about the tx. Was this on testnet or mainnet?

**Comment by corbelantoine** [comment]
channel_reserve_satoshis is set to 0 on both side
Ok, I didn't know about the dev-setfees. How can I fix this to go back to old fees? Setting fees back to old values doesn't seems to work.

Finally, I still can't send any transaction on this channel because no route is found. Anyway to resolve this other than closing the channel?

**Comment by cdecker** [comment]
Wondering about that myself to be honest, the channel should appear in `listpeers`, could you restart and post `getinfo`, `listpeers` and `listchannels` here?

**Comment by corbelantoine** [comment]
Restarted only the lightning node

1st node:
`lightningd(16547): lightning_channeld(034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48): STATUS_FAIL_PEER_BAD: Can't find HTLC 3 to resend
lightningd(16547): peer 034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48: Peer permanent failure in CHANNELD_NORMAL: lightning_channeld: Can't find HTLC 3 to resend` Directly when starting, I also get the min fee not met error

getinfo:
`{ "id" : "03dee28e54a8ffe935f50a4fecd59c20982437edb033f890af7c3f9c1a97a4738d", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "34.217.102.107", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1769-g3d91bf2", "blockheight" : 507159, "network" : "bitcoin" }`
`{ "peers" : 
	[ 
		{ "id" : "034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48", "connected" : false, "channels" : 
			[ 
				{ "state" : "CHANNELD_NORMAL", "short_channel_id" : "507123:1118:1", "funding_txid" : "d66d46ff94520bda50fb496bbb8f43f409c353c55d97651649847c151b16b795", "msatoshi_to_us" : 191200000, "msatoshi_total" : 200000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }`
listchannels:
`{ "channels" : 
	[  ] }`

2nd node:
`lightning_channeld(03dee28e54a8ffe935f50a4fecd59c20982437edb033f890af7c3f9c1a97a4738d): STATUS_FAIL_PEER_BAD: Received ERROR channel 95b7161b157c84491665975dc553c309f4438fbb6b49fb50da0b5294ff466dd7: Can't find HTLC 3 to resend
lightningd(100729): peer 03dee28e54a8ffe935f50a4fecd59c20982437edb033f890af7c3f9c1a97a4738d: Peer permanent failure in CHANNELD_NORMAL: lightning_channeld: Received ERROR channel 95b7161b157c84491665975dc553c309f4438fbb6b49fb50da0b5294ff466dd7: Can't find HTLC 3 to resend` directly when starting as well as the Missing inputs error

getinfo:
`{ "id" : "034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "52.166.255.170", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1751-g7a651c6", "blockheight" : 507159, "network" : "bitcoin" }`

`{ "id" : "034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "52.166.255.170", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1751-g7a651c6", "blockheight" : 507159, "network" : "bitcoin" }
xlightning@xlightning:~$ lightning-cli listpeers
{ "peers" : 
	[ 
		{ "id" : "03dee28e54a8ffe935f50a4fecd59c20982437edb033f890af7c3f9c1a97a4738d", "connected" : false, "channels" : 
			[ 
				{ "state" : "CHANNELD_NORMAL", "short_channel_id" : "507123:1118:1", "funding_txid" : "d66d46ff94520bda50fb496bbb8f43f409c353c55d97651649847c151b16b795", "msatoshi_to_us" : 8800000, "msatoshi_total" : 200000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "connected" : false, "channels" : 
			[ 
				{ "state" : "ONCHAIND_THEIR_UNILATERAL", "owner" : "lightning_onchaind", "short_channel_id" : "507037:1184:0", "funding_txid" : "a47d183ffc4debcfd0a7339d652cda8af71bf8d86fc6e54aa5c69d43bc0c76df", "msatoshi_to_us" : 200000000, "msatoshi_total" : 200000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }`

listchannels:
`{ "channels" : 
	[  ] }`

**Comment by cdecker** [comment]
OK, I think I see what's happening here: you're not connected. Connect to a node in the network and the topology gossip will synchronize. Once sync is complete you will see all channels using the `listpeers` command.

**Comment by corbelantoine** [comment]
I could see channels afterward with the command listchannel, I don't know why it worked...
I tried to close the channel using the close command but it looks like it doesn't broadcast to the network.
I get this error when I try to connect to the other node (even if I already opened a channel, which is stuck in CHANNELD_SHUTTING_DOWN state)

`{ "code" : -1, "message" : "channel ALL: lightning_channeld: Peer sent ERROR: channel ALL: lightning_channeld: Received ERROR channel ALL: lightning_channeld: Can't find HTLC 3 to resend" }`

**Comment by corbelantoine** [comment]
It looks like my node can't broadcast the closing transaction because the fee is too low. So how can I replace the current closing transaction?

I tried tu push it myself but I got the same error:
`0200000000010195b7161b157c84491665975dc553c309f4438fbb6b49fb50da0b5294ff466dd60100000000d3aaec800260220000000000002200206d579ebb8aec89dd0a1d60e31c165d14a60619bb61cc07ac9dbc32971c229208e0ea020000000000160014605dd6eacd82b8500aa77b474a109f7de5a7abc2040048304502210099dad3dc267a1cd50012f1a5480532208725c35c92692842c7ffdf200d265be402201903c7eea56504a4864d1cffa0bb5f9b293dd1e2ff6db2cf5e57c12edcbef5fa01473044022063201e6ecf327facec9243d749534e477e5e05867b47e1c549079f22f62940b6022060e05c808416fb6e11c7364e32e27fa61cf83b1316cfb08fcb1fd2c45000a8820147522102f9bd936303cc6621e1610777d1fe49ef24ace1504ebf1d72bdd3c31ce845c656210355941a9a3d199c2948cc731bd7be1764e4a7805de7df0015841962630cedefad52aee4df2a20`

**Comment by corbelantoine** [comment]
I tried closing another channel connected to me and I could (https://blockchain.info/fr/tx-index/329715941). So how can I submit again the closing transaction with different fees?

**Comment by cdecker** [comment]
Just checked that closing transaction, it has no fee at all attached? You could try to `dev-fail` the channel, but that might actually have some hefty fees attached.

**Comment by corbelantoine** [comment]
There is no way to create another transaction and "override" the old one not yet validated, like we do when we want to cancel a transaction.

**Comment by cdecker** [comment]
This being a close transaction that spends the funding transaction you'd need both endpoints to sign the transaction replacing the close transaction. This is a multisig output that needs to be collaboratively spent. You don't happen to know the other endpoint? If so you could try to have him do a CPFP to bump the fee.

**Comment by corbelantoine** [comment]
It looks like the closing transaction is not even signed. How do I do this manually? There is no command to sign tx like "signrawtransaction" on bitcoin node.
Because of the minimal fee I can't even broadcast the tx to the network, how could I create a CPFP with a non-existant transaction?

**Comment by cdecker** [comment]
`dev-fail` should create a transaction that is printed in the logs, could you send that one to me? You might need to set the `log-level` to `debug`

**Comment by corbelantoine** [comment]
I put everything so you can see the failing messages

`lightning-cli dev-fail 034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48
lightningd(11795): Connected json input
lightningd(11795): peer 034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48: Peer internal error CHANNELD_SHUTTING_DOWN: 
lightningd(11795): 	peer 034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48: ... Failing due to dev-fail command
lightningd(11795): peer 034d49f44ac3090d05b9c17127ef28d81fd8f931e8d8351141db746b842cd48b48: Peer permanent failure in CHANNELD_SHUTTING_DOWN: Internal error
lightningd(11795): 	 (tx 88bfb4beaf6055425d5b9788528e29acc412754e0da243af696386d299867059)
lightningd(11795): sendrawtransaction: 0200000000010195b7161b157c84491665975dc553c309f4438fbb6b49fb50da0b5294ff466dd60100000000d3aaec80026022000000000000160014d702bd3fdb2e09f2c56d827f4b9639f75ca08b07e0ea020000000000220020dd94248bb97c0af9fedcdb2f391b6b2c7e4c453e87a5f55dbdcefde2236d47770400473044022022afde4031b4ac41f3324c729b98b2ce6f0cd54e556668eaa20013e659f059c302206ee6a151726f2659a5b0c2a46969ec5b2afa9c9e2dfdfc3e7687541fab495fc301483045022100cabe0099e890516dbc5c5c79661bea3e292c5aae98f5ae2b3df19223992552e602207e6bf16d1d51133e22959b7faa13a2da1b7eb1b2fde4605d5602b906fb8758530147522102f9bd936303cc6621e1610777d1fe49ef24ace1504ebf1d72bdd3c31ce845c656210355941a9a3d199c2948cc731bd7be1764e4a7805de7df0015841962630cedefad52aee4df2a20
lightningd(11795):jcon fd 14: Success
lightning_gossipd(11803): TRACE: req: type WIRE_GOSSIP_DISABLE_CHANNEL len 12
lightning_gossipd(11803): TRACE: Unable to find channel 507123:1118:1/1
{  }`

**Comment by cdecker** [comment]
Yeah, since you used `dev-setfees 0` you now have a unilateral close transaction that has no fees attached, and will not be broadcast...

**Comment by corbelantoine** [comment]
So no way to broadcast it?

**Comment by cdecker** [comment]
Should be fixed by #1398 and #1404.
