### ISSUE TITLE
getinfo - adress empty

### ISSUE THREAD

**Issue by M-e-s-s-i-a-h** [ElementsProject/lightning#876]
### Issue and Steps to Reproduce

lightning-cli getinfo
{ "id" : "038a09e4bef5ccd22c94d6f07a878d496c6fd2c501349cb7be90ada06fcde5132c", "port" : 9735, "address" : 
        [  ], "version" : "v0.5.2-2016-11-21-1746-g7101db0", "blockheight" : 507148, "network" : "bitcoin" }

URI "unknown" @ https://lnmainnet.gaben.win/

Possible reason:
My node is located on my private network with port forwards (8333&9735) from router.

### `getinfo` output
above

**Comment by cdecker** [comment]
The IP address is autodetected if not specified on the command line with `--ipaddr`. If you only have a private IP and haven't specified one manually you will not have an address announced. So this works as expected.
