### ISSUE TITLE
SENT_REMOVE_COMMIT neither fail nor fulfill?

### ISSUE THREAD

**Issue by shesek** [ElementsProject/lightning#891]
I'm getting the following error with b7856e351212d97604fc1090e457456a5feb1fad, after successfully opening a channel and routing a few payments. The other peer is running @btcontract's [eclair-based android lightning wallet](http://lightning-wallet.com/).

```
peer 026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6: Peer has reconnected, state CHANNELD_NORMAL
HSM TRACE: Client: Received message 1 from client
HSM TRACE: Client: Received message 9 from client
lightning_channeld(026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6): pid 3178, msgfd 22
peer 026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6: Already have funding locked in
peer 026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6: Ignoring fee limits!
lightning_channeld(026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6): TRACE: init REMOTE: remote_per_commit = 02f99c71d7586c5815448db8ade8f5d7af0e07f45d38b22cc1db63ca8325a25da0, old_remote_per_commit = 023fdf434244059af0784ec734d51a2dad095406cdd5259d0de8749f0ff3ce67a1 next_idx_local = 9 next_idx_remote = 10 revocations_received = 8 feerates 50000/50000 (range 1-4294967295)
lightning_channeld(026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6): TRACE: Restoring HTLC 0/1: id=4 msat=2002025 cltv=1262210 payment_hash=2d8424c8a4859954f5e8dae979c9481297f318208a3c8772a00694fa9e6aacc2
lightning_channeld(026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6): TRACE: NEW:: HTLC REMOTE 4 = SENT_REMOVE_COMMIT/RCVD_REMOVE_COMMIT
lightning_channeld(026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6): TRACE: in HTLC 4 SENT_REMOVE_COMMIT neither fail nor fulfill?
lightning_channeld(026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6): STATUS_FAIL_INTERNAL_ERROR: Could not restore HTLCs
lightning_channeld(026b65cb276c915b3525f610a8f80190a8545acf151b1fe8159a97791d2c254ce6): Status closed, but not exited. Killing
```

**Comment by cdecker** [comment]
Looks like a broken reestablish flow, could be that we didn't discard an HTLC that wasn't committed yet? Otherwise the peer should have re-sent it iirc

**Comment by rustyrussell** [comment]
This is restoring from db though: we tell channeld there's an HTLC in state SENT_REMOVE_COMMIT, but we don't tell it why (it *must* be either fulfilled or failed).   I looked into the blockstream store db (assuming that this bug report is from there?) and there's no trace of this peer or HTLC.

@shesek If you have the db, would appreciate it....

**Comment by shesek** [comment]
The bug report is not related to Blockstream's store, and I'm afraid I don't have this db anymore :(

I'll try connecting eclair<->c-lightning again and see if I can reproduce this, will update here when I have more info.

**Comment by cdecker** [comment]
@shesek shall we close the issue temporarily until it resurfaces (or better, it doesn't)?

**Comment by shesek** [comment]
Sorry, haven't been able to test this yet. Yeah, let's close for now, will re-open with more details if I stumble into this again.
