### ISSUE TITLE
When i open channel between eclair and c-lightning i found still state OPENINGD

### ISSUE THREAD

**Issue by parmax** [ElementsProject/lightning#900]
I use eclair mobile wallet on android and c-lightning on ubuntu.
When i open channel from eclair mobile wallet to c-lightning i have switch state from wait_for_accept_channel to closed

When i open channel from c-lightning to eclair node 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134@34.250.234.192:9735
i found still state OPENINGD

**Comment by cdecker** [comment]
Duplicate of #890
