### ISSUE TITLE
FATAL SIGNAL 6 RECEIVED (onchaind is unable to recover after cheating)

### ISSUE THREAD

**Issue by gdassori** [ElementsProject/lightning#905]
As reproduced here:
https://github.com/gdassori/lightning/commit/3718ff499582ab6a57a23da7360a4264429f9060

when peer1 cheats peer2, everything works as expected on peer2 side, and funds are credited, as penalty transaction mechanism work as expected.
peer1, instead, crash and it's unable to recovery

Log:
```
b'2018-02-03T12:52:36.438Z lightningd(11136): Adding block 470: 55647efb099996f08ae06f0522caa65af0c002954722d4061149e94b99eea925'
b'2018-02-03T12:52:36.456Z lightningd(11136): lightning_onchaind(022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59): TRACE: Output 1: 002091fb9e7843a03e66b4b1173482a0eb394f03a35aae4c28e8b4b1f575696bd793'
b'2018-02-03T12:52:36.458Z lightningd(11136): lightning_onchaind(022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59): STATUS_FAIL_INTERNAL_ERROR: Could not find resolution for output 0'
b'2018-02-03T12:52:36.465Z lightningd(11136): Subdaemon lightning_onchaind hit error'
b'2018-02-03T12:52:36.486Z lightningd(11136): FATAL SIGNAL 6 RECEIVED'
```

**Comment by cdecker** [comment]
Well, `peer1` isn't supposed to recover, by cheating it lost all claims to any of its funds. Hence `onchaind` will die because it can't recover funds.

**Comment by ZmnSCPxj** [comment]
"Not a bug, a feature, it discourages people from cheating using lightningd!"
