### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by doffing81** [ElementsProject/lightning#91]
daemon/json.c: In function ‘json_tok_u64’:
daemon/json.c:54:2: error: size of unnamed array is negative
  BUILD_ASSERT(sizeof(l) >= sizeof(*num));
  ^
<builtin>: recipe for target 'daemon/json.o' failed
make: *** [daemon/json.o] Error 1

**Comment by cdecker** [comment]
Very interesting, what architecture are you building this on?

**Comment by doffing81** [comment]
Ubuntu Mate 16.04.  Should I avoid Mate?

**Comment by doffing81** [comment]
4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:50:36 UTC 2016 i686 athlon i686 GNU/Linux

**Comment by cdecker** [comment]
Good catch, it appears that you are compiling on a 32bit machine, and we never tried that. On your machine the size of an `unsigned long` might be 32 bits, and not 64 which is what we assumed. I'll try to reconstruct this on a 32bit VM :-)

**Comment by rustyrussell** [comment]
Reproduced with CC="gcc -m32" here; running tests in 32-bit mode now to double-check...

**Comment by rustyrussell** [comment]
@cdecker Hmm, weird:
$  daemon/test/test-routing --verbose
...
lightningd: Computed MAC does not match expected MAC, the message was modified.
lightningd: Computed MAC does not match expected MAC, the message was modified.
lightningd: Computed MAC does not match expected MAC, the message was modified.

**Comment by rustyrussell** [comment]
I'll move that to another issue for tracking: #94
