### ISSUE TITLE
How to set ipaadr/alias to a node?

### ISSUE THREAD

**Issue by grobelr** [ElementsProject/lightning#910]
Is there an easy way (via lightning-cli) to set an ip address, color and alias of your node?

I got my nodeID and figured out how the node's name was set, but how to change?

**Comment by thestick613** [comment]
Launch `lightningd` with `--alias=your_alias` and `--ipaddr=1.2.3.4`?

**Comment by grobelr** [comment]
Nice! 
I got some errors running these commands (error connecting with bitcoin-cli server). I'm debugging it right now, maybe something wrong with docker not lightning itself..

**Comment by mdcdr** [comment]
Is it possible to listen on multiple addresses?
--ipaddr=1.2.3.4 --ipaddr=2001::.. doesn't work. It seems it takes only last parameter.

**Comment by ZmnSCPxj** [comment]
@mdcdr, no, it is not possible yet.

**Comment by cdecker** [comment]
Closing since original question was answered.
