### ISSUE TITLE
Channels closing by itself: ONCHAIND_OUR_UNILATERAL

### ISSUE THREAD

**Issue by 2pac1** [ElementsProject/lightning#915]
Hello, 
 
 I have opened 2 channels recently (one yesterday, one today).
Both have gone into ONCHAIND_OUR_UNILATERAL state by themselves.
Second one, I opened to Blockstream justnow, and it showed as opened, but now it has turned into ONCHAIND_OUR_UNILATERAL.

Blockstream's channel from today:

	{ "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "connected" : false, "channels" : 
			[ 
				{ "state" : "ONCHAIND_OUR_UNILATERAL", "owner" : "lightning_onchaind", "short_channel_id" : "507735:585:0", "funding_txid" : "5c4b8e0cfd820871d993a70222b1a464a72333e74359fc53fb0b245057ac1d2e", "msatoshi_to_us" : 52635000, "msatoshi_total" : 52635000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }

This is one from yesterday:

{ "id" : "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1", "connected" : false, "channels" : 
			[ 
				{ "state" : "ONCHAIND_OUR_UNILATERAL", "owner" : "lightning_onchaind", "short_channel_id" : "507596:2037:1", "funding_txid" : "9c544ea0aeafdffb04162b2c0f2ea952510ba9d0e83b536fece95b84321c1745", "msatoshi_to_us" : 37654000, "msatoshi_total" : 60000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] }, 

============

Why is this happening?

My getinfo:
lightning-cli getinfo
{ "id" : "02cf007fe65109016491999b64f85d7d7db5a09b902f0a83f03a82ce3789c78233", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "178.62.208.226", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1814-g5f2cd7c1", "blockheight" : 507742, "network" : "bitcoin" }

**Comment by rustyrussell** [comment]
Hi!

Looks like something went wrong, and it dropped onto chain.  Do you have the complete logs?  If it's still running you can get logs with `lightning-clu getlog debug`, for example.

**Comment by ianthius** [comment]
When a channel goes into this state, where is the transaction ID store for the transaction that moves the channel back on chain?

**Comment by rustyrussell** [comment]
It's in the logs, however, we should really have a "summary" in listpeers which gives you what has happened at a glance.

**Comment by Sjors** [comment]
I'm getting lots of ONCHAIND_OUR_UNILATERAL's recently. Maybe due to my custom fee settings? Here's the [log](
[023d280ae29f84dcfd289eb66b57227fea3a7bde97ec2869923d3c4d5c6a426028.log](https://github.com/ElementsProject/lightning/files/1736759/023d280ae29f84dcfd289eb66b57227fea3a7bde97ec2869923d3c4d5c6a426028.log)
) for a fresh node (--daemon --fee-base=1000 --fee-per-satoshi=100) vs. `023d280ae29f84dcfd289eb66b57227fea3a7bde97ec2869923d3c4d5c6a426028`.

Maybe @alecalve has the other side...

**Comment by alecalve** [comment]
I'm running my node with debug logging enabled now. I'll look at the logs from my side later today.

**Comment by Sjors** [comment]
@alecalve you can probably still get these log entries using `lightning-cli getlog debug`, although the JSON output is a bit unpractical without further processing.

It's not just your node though:
* 0247604546e9380d47b3de1420d18b6aa46ea6ed10b8ddf1d07dd8685d686a84df gave me a ONCHAIND_THEIR_UNILATERAL
* 0250373555232cec757ea141273e75381c84cc3ab22f1e3a3ca5a2dc55b1904c24 is ONCHAIND_OUR_UNILATERAL

**Comment by alecalve** [comment]
Oh sorry, what I meant is that I have these entries, I've been running my node with debug enabled for two weeks now.

**Comment by fetihh** [comment]
@Sjors hi, I also have problems with ONCHAIND_OUR_UNILATERAL and ONCHAIND_THEIR_UNILATERAL. I think it's about the fee settings. Have you found a solution to this problem?

**Comment by Sjors** [comment]
I removed my custom fees and now at least my connection with 023d280ae29f84dcfd289eb66b57227fea3a7bde97ec2869923d3c4d5c6a426028 has been open for a few days. But this won't make me rich! :-)

**Comment by cdecker** [comment]
One thing to note is that it's not complaining about the fees you are setting with `--fee-base=1000 --fee-per-satoshi=100` (which are the off-chain fees) rather it is complaining about the on-chain fee estimates being too different between the endpoints. Usually keeping `bitcoind` running for a while before attempting to open a channel will settle these problems.

**Comment by fetihh** [comment]
That's better understood thanks

**Comment by Sjors** [comment]
@cdecker I'm pretty sure my bitcoind instance had been running for at least a week before I opened those channels. I'll the custom fees again though, see if it keeps happening.

**Comment by cdecker** [comment]
@Sjors that's annoying, we definitely need a fix to the on-chain fee issue.

**Comment by ZMeridianZ** [comment]
Could be a coincidence but I noticed that after changing my fees using `--dev-setfees` one of my actively funded channels switched to `ONCHAIND_OUR_UNILATERAL`.

**Comment by cdecker** [comment]
Yeah, `dev-setfees` is about onchain fees, and will kill your channel if outside of the peer's range. It is dangerous (which is why it's a `def-*` RPC call, don't use them!) and you may end up with a channel that cannot be closed due to insufficient onchain fees.
