### ISSUE TITLE
Code Review: possible leak in `channeld/channel.c` main loop

### ISSUE THREAD

**Issue by ZmnSCPxj** [ElementsProject/lightning#929]
The end of the while loop performs `tal_free` on `msg` variable:

https://github.com/ElementsProject/lightning/blob/b3534462e0392fbace73657cf6bbe8b46ca6ebdb/channeld/channel.c#L2695

This suggests that `req_in`, `peer_in` and `gossip_in` all do not free the given `msg`.

However, there are cases where we `continue;` the `while` loop after calling `req_in` or `gossip_in`:

https://github.com/ElementsProject/lightning/blob/b3534462e0392fbace73657cf6bbe8b46ca6ebdb/channeld/channel.c#L2618-L2625

https://github.com/ElementsProject/lightning/blob/b3534462e0392fbace73657cf6bbe8b46ca6ebdb/channeld/channel.c#L2633-L2639

This suggests to me that `msg` is leaked in the above cases.

Is my analysis correct?

**Comment by Saibato** [comment]
Maybe you found a big one
tested continue and the tal_free after while exit.
ie free msg  if !NULL after the while exit;

But oh wonder the while if i provoke continue to gen the leak never returned at all 
Maybe we need "break" where we write "continue;" ?

when i replace continue with break i get the expected continue behavior
then i free the msg;
\^^/

**Comment by ZmnSCPxj** [comment]
@Saibato, why would you free only at loop exit? `msg` is created inside the loop, it should be freed before the loop jumps back to its top.  Correction, is to `tal_free(mem)` before each `continue` that `mem` is not NULL.

**Comment by Saibato** [comment]
yes i see it should be freed as long as in loop an not break, to handle the statuschange
but if continue jump to } evals next he while then exits the free is not called or?
what if continue be relaced with  goto label_tal_free; ?

label_tal_free: tal_free(msg);

**Comment by Saibato** [comment]
@ZmnSCPxj  oh you already had made an PR that should fix it :+1: 
I have the strange phenom that the continue only evals the while after called once  the rest of the loop is opted out  maybe its my compliler? i have to check this futher.
