### ISSUE TITLE
Two null-param'd listpeers calls in a row crash daemon

### ISSUE THREAD

**Issue by icota** [ElementsProject/lightning#934]
### Issue and Steps to Reproduce

Send this via the RPC interface:
`{"id":1,"jsonrpc":"2.0","method":"listpeers","params":[null]}`
Returns as expected. Send another:
`{"id":2,"jsonrpc":"2.0","method":"listpeers","params":[null]}`
lightning steps on `assert(!jcon->current)` in `parse_request`. 

Reason being the second call never gets to `gossipd_getpeers_complete` and from there to its destructor. I'll be so bold and suggest this is a bug in `gossipd`

**Comment by icota** [comment]
I'm not sure but I think my description and steps might be misleading. I see now the assertion failure also occurs on any call whose id is not 1 (or is generally not the first call?), whether params array is null or just plain empty:

`{"id":1,"jsonrpc":"2.0","method":"listpeers","params":[]}` ---> A-OK

`{"id":2,"jsonrpc":"2.0","method":"listpeers","params":[]}` ---> CRASH

**Comment by cdecker** [comment]
Thanks for reporting this @icota. I'm having a bit of trouble reproducing this. How are you calling the RPC (python RPC client, `lightning-cli`, JS RPC client, ...). Calling `lightning-cli listpeers` in a loop (which internally then passes an empty params array) doesn't crash. Are the two calls concurrent?

**Comment by icota** [comment]
It's a C++ RPC client. The calls are not concurrent they are in sequence but I can't reproduce with `lightning-cli` either. I'm guessing that's cause my client doesn't close the connection after every call.

**Comment by icota** [comment]
Here's the output when it occurs:
```
2018-02-07T11:28:28.272Z lightningd(24586): Connected json input
2018-02-07T11:28:31.857Z lightning_gossipd(24594): TRACE: req: type WIRE_GOSSIP_GETPEERS_REQUEST len 4
2018-02-07T11:28:31.857Z lightning_gossipd(24594): REPLY WIRE_GOSSIP_GETPEERS_REPLY with 0 fds
2018-02-07T11:28:31.857Z lightningd(24586):jcon fd 14: Success
lightningd: lightningd/jsonrpc.c:562: parse_request: Assertion `!jcon->current' failed.
2018-02-07T11:28:31.857Z lightningd(24586): FATAL SIGNAL 6 RECEIVED
2018-02-07T11:28:31.865Z lightningd(24586): backtrace: lightningd/log.c:473 (log_crash) 0x7471114d41
2018-02-07T11:28:31.865Z lightningd(24586): backtrace: (null):0 ((null)) 0x7f16a7f4a13f
2018-02-07T11:28:31.866Z lightningd(24586): backtrace: (null):0 ((null)) 0x7f16a7f4a0bb
2018-02-07T11:28:31.866Z lightningd(24586): backtrace: (null):0 ((null)) 0x7f16a7f4bf5c
2018-02-07T11:28:31.866Z lightningd(24586): backtrace: (null):0 ((null)) 0x7f16a7f41f16
2018-02-07T11:28:31.866Z lightningd(24586): backtrace: (null):0 ((null)) 0x7f16a7f41fc1
2018-02-07T11:28:31.866Z lightningd(24586): backtrace: lightningd/jsonrpc.c:562 (parse_request) 0x74711112fc
2018-02-07T11:28:31.866Z lightningd(24586): backtrace: lightningd/jsonrpc.c:794 (read_json) 0x7471111f15
2018-02-07T11:28:31.866Z lightningd(24586): backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x747116024c
2018-02-07T11:28:31.866Z lightningd(24586): backtrace: ccan/ccan/io/io.c:420 (io_do_always) 0x7471160e1d
2018-02-07T11:28:31.867Z lightningd(24586): backtrace: ccan/ccan/io/poll.c:228 (handle_always) 0x7471162424
2018-02-07T11:28:31.867Z lightningd(24586): backtrace: ccan/ccan/io/poll.c:249 (io_loop) 0x74711624b7
2018-02-07T11:28:31.867Z lightningd(24586): backtrace: lightningd/lightningd.c:351 (main) 0x74711134ff
2018-02-07T11:28:31.867Z lightningd(24586): backtrace: (null):0 ((null)) 0x7f16a7f341c0
2018-02-07T11:28:31.867Z lightningd(24586): backtrace: (null):0 ((null)) 0x7471106b29
2018-02-07T11:28:31.867Z lightningd(24586): backtrace: (null):0 ((null)) 0xffffffffffffffff
Fatal signal 6. 0x7471114e33 log_crash
        lightningd/log.c:499
0x7f16a7f4a13f ???
        ???:0
0x7f16a7f4a0bb ???
        ???:0
0x7f16a7f4bf5c ???
        ???:0
0x7f16a7f41f16 ???
        ???:0
0x7f16a7f41fc1 ???
        ???:0
0x74711112fc parse_request
        lightningd/jsonrpc.c:562
0x7471111f15 read_json
        lightningd/jsonrpc.c:794
0x747116024c next_plan
        ccan/ccan/io/io.c:59
0x7471160e1d io_do_always
        ccan/ccan/io/io.c:420
0x7471162424 handle_always
        ccan/ccan/io/poll.c:228
0x74711624b7 io_loop
        ccan/ccan/io/poll.c:249
0x74711134ff main
        lightningd/lightningd.c:351
0x7f16a7f341c0 ???
        ???:0
0x7471106b29 ???
        ???:0
0xffffffffffffffff ???
        ???:0
Log dumped in crash.log
lightning_channeld: Writing out status 32768 len 27: Broken pipe
Aborted (core dumped)
```

**Comment by icota** [comment]
I've done some more investigating and it seems `listpeers` cannot be concurrent with any other calls. What I've previously failed to note is that my client makes other API calls at the same time. Now it works fine if I make the `listpeers` call blocking. This doesn't happen with any other calls, they don't mind being fired in rapid succession.

**Comment by icota** [comment]
Also reproducible by running `socat - UNIX-CONNECT:~/.lightning/lightning-rpc`. Pasting this into terminal:
```
{ "id": 1, "jsonrpc": "2.0", "method": "listpayments", "params": [  ] }
{ "id": 2, "jsonrpc": "2.0", "method": "listpayments", "params": [  ] }
{ "id": 3, "jsonrpc": "2.0", "method": "listpayments", "params": [  ] }
{ "id": 4, "jsonrpc": "2.0", "method": "listpayments", "params": [  ] }
{ "id": 5, "jsonrpc": "2.0", "method": "listpayments", "params": [  ] }
{ "id": 6, "jsonrpc": "2.0", "method": "listpayments", "params": [  ] }
```
... works fine.
```
{"id":1,"jsonrpc":"2.0","method":"listpeers","params":[]}
{"id":2,"jsonrpc":"2.0","method":"listpeers","params":[]}
{"id":3,"jsonrpc":"2.0","method":"listpeers","params":[]}
{"id":4,"jsonrpc":"2.0","method":"listpeers","params":[]}
{"id":5,"jsonrpc":"2.0","method":"listpeers","params":[]}
{"id":6,"jsonrpc":"2.0","method":"listpeers","params":[]}
```
reproduces this issue.

**Comment by cdecker** [comment]
We don't mux calls in the JSON-RPC currently, meaning that two concurrent calls to the same command, that then are handed off to another daemon, e.g., `getroute`, `listchannels`, `listpeers`, `listnodes` which all call out to `gossipd`, will likely encounter this issue. So that may be causing the issue.

**Comment by ZmnSCPxj** [comment]
@cdecker maybe we can clear `jcon->current` at `command_still_pending`, and remove the `assert(jcon->current == cmd)` assertions?  Also on freeing, instead of `jcon->current = tal_free(cmd)` we should do `if (jcon->current == cmd) jcon->current = tal_free(cmd); else tal_free(cmd);`

There are places in `wallet/invoices.c` where a command completes in response to another command, e.g. `waitinvoice` returning when the invoice is `delinvoice`d.  Our tests do not trip on this, as, the `waitinvoice` is invoked using a different connection from the `deliinvoice`.

JSON RPC is inherently async in any case, and commands may be delivered before responses from previous commands are completed.

**Comment by cdecker** [comment]
I don't think we should be mixing json-rpc requests at all. This might work for `listpeers`, but already `listpeers <id>` called concurrently and with different IDs will produce very strange behavior. So the `assert` should definitely stay.

**Comment by ZmnSCPxj** [comment]
I am less certain we should not be mixing JSON RPC requests.  Nothing in the JSON RPC 2.0 spec disallows a client sending commands before replies are sent by the server; indeed one car argue that the purpose of the `id` parameter is to allow such a pattern.

A simple solution would be to somehow queue the commands at the JSON-RPC level, but that would fail with the below:

    { "method": "invoice", "params": [100, "foo", "foo"], "jsonrpc": "2.0", "id": 0 }
    { "method": "waitinvoice", "params": ["foo"], "jsonrpc" : "2.0", "id": 1 }
    { "method": "delinvoice", "params": ["foo"], "jsonrpc" : "2.0", "id": 2 }

In a simple queue of commands, processing will stall at the `waitinvoice`, without the processing of commands afterward, including the `delinvoice` that would free the `waitinvoice`.  One could imagine that an application uses only a single connection, and uses `waitinvoice` to get a notification of an invoice getting paid, while expecting to be able to perform future `invoice` etc. managing commands on the same connection.

So maybe we should allow mixing of JSON-RPC requests and add the queueing to lightningd->gossipd instead.

**Comment by ZmnSCPxj** [comment]
> but already `listpeers <id>` called concurrently and with different IDs will produce very strange behavior. 

@cdecker My basic reading of the `subd` code suggests that `subd_req` will expect replies to be in the same order as requests.

Requests are queued in order (added to tail of list):
https://github.com/ElementsProject/lightning/blob/cc9ca8282106cfd3979af9442a495a8a36b024e2/lightningd/subd.c#L98-L99

On receiving a reply, we search starting with the list head:
https://github.com/ElementsProject/lightning/blob/cc9ca8282106cfd3979af9442a495a8a36b024e2/lightningd/subd.c#L108-L117

My basic reading of the `gossipd` code suggests that gossipd is a simple server: it receives a message and then handles it completely before looking at the next message.  

So multiple parallel `listpeers` on multiple JSON-RPC connections should work correctly, assuming my understanding of the subd code is correct.

**Comment by cdecker** [comment]
The problem is that `jcon` contains the `id` of the request, it is not passed on, so if we match the reply to the wrong request it'll get that request's `id`, which is definitely wrong. `listpeers 1` concurrent with `listpeers 2` can result in the first call getting the reply for the second call, which now contains details for the wrong peer.

You are right that the order should be preserved by respecting the queue, so I'm a bit out of explanations tbh.

**Comment by practicalswift** [comment]
@icota Nice find! Thanks for reporting!
