### ISSUE TITLE
32-bit machines make check fails

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#94]
$ daemon/test/test-routing --verbose
...
lightningd: Computed MAC does not match expected MAC, the message was modified.
lightningd: Computed MAC does not match expected MAC, the message was modified.
lightningd: Computed MAC does not match expected MAC, the message was modified.

**Comment by cdecker** [comment]
I was able to reproduce the problem with the `test/test_sphinx` binary. It appears that the ephemeral pubkey isn't getting blinded correctly after unwrapping the first time (and any time thereafter). This causes the HMAC keys to be generated differently, hence the error. Investigating further.
