### ISSUE TITLE
Could not find a route

### ISSUE THREAD

**Issue by hughfuve** [ElementsProject/lightning#954]
### Issue and Steps to Reproduce
Everything was working fine a couple of days ago, but after I pulled the latest and built today.
I cant find route to myself. so I cant pay invoices generated on my own servers.

### `getinfo` output
:~/lightning$ cli/lightning-cli getinfo
{ "id" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "50.39.181.19", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1890-ge046194", "blockheight" : 1280171, "network" : "testnet" }

### `pay` output
~/lightning$ cli/lightning-cli pay lntb12082180p1pd8cpskpp5kpput9s73y9tggu0j69uenh0yx3qs38pjm8y7hkaava2r8srpnqqdzdw3jhxarwv46zqer9wchxuempwp6ks6fwvdhk6w3qxqhrzvpq24f5ggrxdusxzmnyyppkzupq0qsrzcqpxm9kz9us2mcvmucetsj4lpewyuz3a4xk3e2x7ar96wx5zz6e9ckdrjqzh8srl88mn2akxz8svtsk2u78k42xrxkfxz2kv8h0uv78akmcqrwpdxr      { "code" : 205, "message" : "Could not find a route" }

### `decodepay` output
~/lightning$ cli/lightning-cli decodepay lntb12082180p1pd8cpskpp5kpput9s73y9tggu0j69uenh0yx3qs38pjm8y7hkaava2r8srpnqqdzdw3jhxarwv46zqer9wchxuempwp6ks6fwvdhk6w3qxqhrzvpq24f5ggrxdusxzmnyyppkzupq0qsrzcqpxm9kz9us2mcvmucetsj4lpewyuz3a4xk3e2x7ar96wx5zz6e9ckdrjqzh8srl88mn2akxz8svtsk2u78k42xrxkfxz2kv8h0uv78akmcqrwpdxr
{ "currency" : "tb", "timestamp" : 1518077462, "created_at" : 1518077462, "expiry" : 3600, "payee" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246", "msatoshi" : 1208218, "description" : "testnet xxxxxxxxxxxxx: 0.10 USD fo and Cap x 1", "min_final_cltv_expiry" : 6, "payment_hash" : "b043c5961e890ab4238f968bccceef21a20844e196ce4f5eddeb3aa19e030cc0", "signature" : "3045022100d96c22f20ade19be632b84abf0e5c4e0a3da9ad1ca8dee8cba71a8216b25c59a02203900573c07f39f73576c611e0c5c2cae78f6aa8c33592612acc3ddfc678fdb6f" }

### 'getroute` output
~/lightning$ cli/lightning-cli getroute 02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246 10000 1
{ "code" : -1, "message" : "Could not find a route" }

### `listchannels` output
~/lightning$ cli/lightning-cli listchannels | grep 02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246
                { "source" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "destination" : "02f42dec365c9f3f2e16173710fea1e29c35fb21424189840b45d3cb688e16772f",
	 "short_channel_id" : "1278758:3:0",
	 "flags" : 0,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518077424,
	 "base_fee_millisatoshi" : 1,
	 "fee_per_millionth" : 10,
	 "delay" : 6 },
	
                { "source" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "destination" : "037a611163d5fb0a58834a480a473b5cb929ab90c435340abc7cd1ead8de985c95",
	 "short_channel_id" : "1278807:12:0",
	 "flags" : 0,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518017636,
	 "base_fee_millisatoshi" : 1,
	 "fee_per_millionth" : 10,
	 "delay" : 6 },
	
                { "source" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "destination" : "0231eee2441073c86d38f6085aedaf2bb7ad3d43af4c0e2669c1edd1a7d566ce31",
	 "short_channel_id" : "1278774:20:0",
	 "flags" : 1,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518077424,
	 "base_fee_millisatoshi" : 1,
	 "fee_per_millionth" : 10,
	 "delay" : 6 },
	
                { "source" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "destination" : "031bfe54ce29635932bb3dc0df4a841e518f76167dfcb23f85617104d8f069bf3c",
	 "short_channel_id" : "1279128:257:0",
	 "flags" : 0,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518077424,
	 "base_fee_millisatoshi" : 1,
	 "fee_per_millionth" : 10,
	 "delay" : 6 },
	
                { "source" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "destination" : "03f113414ebdc6c1fb0f33c99cd5a1d09dd79e7fdf2468cf1fe1af6674361695d2",
	 "short_channel_id" : "1279128:255:0",
	 "flags" : 0,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518077424,
	 "base_fee_millisatoshi" : 1,
	 "fee_per_millionth" : 10,
	 "delay" : 6 },
	
                { "source" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "destination" : "031163f819b2864cebe201694f3bfa10ed2af546b45d681af76804d0f2d77bf989",
	 "short_channel_id" : "1278760:22:0",
	 "flags" : 0,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518077423,
	 "base_fee_millisatoshi" : 1,
	 "fee_per_millionth" : 10,
	 "delay" : 6 },
	
                { "source" : "02f42dec365c9f3f2e16173710fea1e29c35fb21424189840b45d3cb688e16772f",
	 "destination" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "short_channel_id" : "1278758:3:0",
	 "flags" : 1,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518014471,
	 "base_fee_millisatoshi" : 1000,
	 "fee_per_millionth" : 1,
	 "delay" : 144 },
	
                { "source" : "031bfe54ce29635932bb3dc0df4a841e518f76167dfcb23f85617104d8f069bf3c",
	 "destination" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "short_channel_id" : "1279128:257:0",
	 "flags" : 1,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518011261,
	 "base_fee_millisatoshi" : 1000,
	 "fee_per_millionth" : 1,
	 "delay" : 144 },
	
                { "source" : "03f113414ebdc6c1fb0f33c99cd5a1d09dd79e7fdf2468cf1fe1af6674361695d2",
	 "destination" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "short_channel_id" : "1279128:255:0",
	 "flags" : 1,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518011261,
	 "base_fee_millisatoshi" : 1000,
	 "fee_per_millionth" : 1,
	 "delay" : 144 },
	
                { "source" : "0231eee2441073c86d38f6085aedaf2bb7ad3d43af4c0e2669c1edd1a7d566ce31",
	 "destination" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "short_channel_id" : "1278774:20:0",
	 "flags" : 0,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518015125,
	 "base_fee_millisatoshi" : 1000,
	 "fee_per_millionth" : 1,
	 "delay" : 144 },
	
                { "source" : "037a611163d5fb0a58834a480a473b5cb929ab90c435340abc7cd1ead8de985c95",
	 "destination" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "short_channel_id" : "1278807:12:0",
	 "flags" : 1,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518016248,
	 "base_fee_millisatoshi" : 1000,
	 "fee_per_millionth" : 1,
	 "delay" : 144 },
	
                { "source" : "031163f819b2864cebe201694f3bfa10ed2af546b45d681af76804d0f2d77bf989",
	 "destination" : "02bcffafd63e065580f1273a9375166c1bfe2859515cc7649c5f6644478bac1246",
	 "short_channel_id" : "1278760:22:0",
	 "flags" : 1,
	 "active" : true,
	 "public" : true,
	 "last_update" : 1518014342,
	 "base_fee_millisatoshi" : 1000,
	 "fee_per_millionth" : 1,
	 "delay" : 144 },

### `listpeers` output
:~/lightning$ cli/lightning-cli listpeers
{ "peers" :
        [
                { "id" : "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134", "connected" : true, "netaddr" :
                        [ "34.250.234.192:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "26993cd490b0ec256cf5455934a0037edefac975b2c1c37c49c0b33f6d25d13b", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] },
                { "id" : "03f113414ebdc6c1fb0f33c99cd5a1d09dd79e7fdf2468cf1fe1af6674361695d2", "connected" : true, "netaddr" :
                        [ "5.102.147.62:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "1279128:255:0", "funding_txid" : "7799436a95c22b82a6565e0225bbc7232165c0ac84e8a7278445ea26fb2157a6", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] },
                { "id" : "031bfe54ce29635932bb3dc0df4a841e518f76167dfcb23f85617104d8f069bf3c", "connected" : true, "netaddr" :
                        [ "18.218.207.229:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "1279128:257:0", "funding_txid" : "98e4d5d883148284a1516f29275c83044a692323bcd548ba1c5f090d57ed2ebd", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] },
                { "id" : "037a611163d5fb0a58834a480a473b5cb929ab90c435340abc7cd1ead8de985c95", "connected" : false, "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "short_channel_id" : "1278807:12:0", "funding_txid" : "3531989b6ba5ad27ed2cb07049e40033beff82bfde30e8e063d5292f578e13de", "msatoshi_to_us" : 94318435, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] },
                { "id" : "0231eee2441073c86d38f6085aedaf2bb7ad3d43af4c0e2669c1edd1a7d566ce31", "connected" : true, "netaddr" :
                        [ "77.251.249.36:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "1278774:20:0", "funding_txid" : "d77edda3bdd15340d83f10de1c4070ea10b170f2cbb1b6cd0050cbed48609064", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] },
                { "id" : "031163f819b2864cebe201694f3bfa10ed2af546b45d681af76804d0f2d77bf989", "connected" : true, "netaddr" :
                        [ "54.236.31.248:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "1278760:22:0", "funding_txid" : "4305232bd7a0f534ad51fc81dc67483c8a2e97ff6a22471d8e1393752e87d9a3", "msatoshi_to_us" : 777042788, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] },
                { "id" : "02f42dec365c9f3f2e16173710fea1e29c35fb21424189840b45d3cb688e16772f", "connected" : true, "netaddr" :
                        [ "86.24.91.84:9735" ], "channels" :
                        [
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "1278758:3:0", "funding_txid" : "8ade2f5b46b2aa0c9dd42d314f67f5795d8b54946122138edf94586784f85c03", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] },
                { "state" : "GOSSIPING", "id" : "0340cf8abc53ca6f9b79bcf37211dfc55ed139ab1fd29868c07ef746c7f3f6726f", "netaddr" :
                        [ "[::ffff:209.58.168.232]:55457" ], "connected" : true, "owner" : "lightning_gossipd" } ] }

### `listinvoices` output
~/lightning$ cli/lightning-cli listinvoices
{ "invoices" :
        [
                { "label" : "LJ52RpWvitZ1pCVFQnLCk",
	 "payment_hash" : "20dd052765e95ec3d2e022ba0f1a50eca14e6c3aaf9339aaf536ae8538e14f56",
	 "msatoshi" : 10000,
	 "status" : "paid",
	 "pay_index" : 2,
	 "msatoshi_received" : 10000,
	 "paid_timestamp" : 1517929800,
	 "paid_at" : 1517929800,
	 "expiry_time" : 1517930712,
	 "expires_at" : 1517930712 },
	
                { "label" : "LjQHaqeXnG2kgJUUlqI4s",
	 "payment_hash" : "d82d89f74de5c5b4935f6bcd72bde7651714459e98a1371933897144fbc3bad8",
	 "msatoshi" : 143790,
	 "status" : "paid",
	 "pay_index" : 1,
	 "msatoshi_received" : 143790,
	 "paid_timestamp" : 1517929358,
	 "paid_at" : 1517929358,
	 "expiry_time" : 1517931967,
	 "expires_at" : 1517931967 },
	
                { "label" : "h~TqzZT6FHZ5fQGRn8gL2",
	 "payment_hash" : "a0b5167ed1ba25a56592006ad3735b0a75c144037fe4cd70aabd2d049d6d4bed",
	 "msatoshi" : 10000,
	 "status" : "paid",
	 "pay_index" : 3,
	 "msatoshi_received" : 10000,
	 "paid_timestamp" : 1517940235,
	 "paid_at" : 1517940235,
	 "expiry_time" : 1517943801,
	 "expires_at" : 1517943801 },
	
                { "label" : "9pnGKBRNx60q61ZaxxWxw",
	 "payment_hash" : "de4b27569079f5f13573b5fe4842b8176d1126bd334a0f63f575e2ed4a8475f1",
	 "msatoshi" : 10000,
	 "status" : "paid",
	 "pay_index" : 4,
	 "msatoshi_received" : 10000,
	 "paid_timestamp" : 1517948662,
	 "paid_at" : 1517948662,
	 "expiry_time" : 1517952244,
	 "expires_at" : 1517952244 },
	
                { "label" : "test2",
	 "payment_hash" : "42123d01ac2fbb18bad3c86f35bc3e4a007bb72ab3d083eb6e4b06bd26e9ff78",
	 "msatoshi" : 90000000,
	 "status" : "paid",
	 "pay_index" : 5,
	 "msatoshi_received" : 90000000,
	 "paid_timestamp" : 1517999039,
	 "paid_at" : 1517999039,
	 "expiry_time" : 1518002618,
	 "expires_at" : 1518002618 },
	
                { "label" : "Qly7pW4LfvoaCTZcg5BF9",
	 "payment_hash" : "b043c5961e890ab4238f968bccceef21a20844e196ce4f5eddeb3aa19e030cc0",
	 "msatoshi" : 1208218,
	 "status" : "unpaid",
	 "expiry_time" : 1518081062,
	 "expires_at" : 1518081062 } ] }

**Comment by hughfuve** [comment]
so cant route to myself, but I was able to route and pay an invoice from HTLC.me on node..
031163f819b2864cebe201694f3bfa10ed2af546b45d681af76804d0f2d77bf989@54.236.31.248

### `listinvoices` tail
 { "label" : "avspNIKXu0vPxg5qss5dg", "payment_hash" : "8df48e8bb398e4a27f92dd237afe53f9d1513a0d2af6a054624604d1991e7f33", "msatoshi" : 1208753, "status" : "paid", "pay_index" : 6, "msatoshi_received" : 1208753, "paid_timestamp" : 1518081248, "paid_at" : 1518081248, "expiry_time" : 1518084822, "expires_at" : 1518084822 } ] }

**Comment by ZmnSCPxj** [comment]
Not supported.

https://github.com/ElementsProject/lightning/blob/e04619457bf4d96aed57c233efb793443e7b50f9/gossipd/routing.c#L408-L412

You cannot pay yourself, since the most efficient path to doing that is to do nothing.

**Comment by hughfuve** [comment]
LOL, So it should never have worked, when it did?

was kind of handy for quick tests... but thanks, I think I'll just comment that out.

**Comment by ZmnSCPxj** [comment]
Huh? https://github.com/ElementsProject/lightning/commit/a97d30115510213aac634d8473cf1ed7d32d8858 was a year ago.  How old was your build?

Or did you build a route from yourself to yourself manually, then removed that self-routing?  Self-payment is possible if you build the route yourself.  Routing to yourself, not at all possible.
