### ISSUE TITLE
old channeld process laying around? (reopen)

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#978]
### Issue and Steps to Reproduce

I have to reopen this because #976 was erronously marked as a duplicate due to a bug in github text writing that censors two sides of a triangle pointy brackets and confuses moderators.  Here it is again:

An old channeld process is laying around from a previous invocation of lightningd.  Note that is NOT marked defunct as it is in #779.  I also have defunct processes, but I don't care about those (because in my experience over the decades, those are minor).  Note the date of the old channeld process:  Jan28.  Note the date of the new lightningd:  Feb09.

    $ ps uxf # I deleted some irrelevent lines
    ulmo     32068  0.0  0.0  11220  1992 pts/2    S    Jan28   0:00 /usr/local/libexec/c-lightning/lightning_channeld
    ulmo     29376  3.2  3.1 143964 127068 pts/1   S    Feb09 123:24  |   |   \_ lightningd --network bitcoin --log-level=debug --ignore-fee-limits=false --log-file=/home/ulmo/log/log.29267.5 --alias=Ionic.Release
    ulmo     29377  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_chann] <defunct>
    ulmo     29378  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_closi] <defunct>

    $ ls -l /proc/32068/fd
    total 0
    lrwx------ 1 ulmo staff 64 Feb 11 17:07 0 -> socket:[9163785]
    lrwx------ 1 ulmo staff 64 Feb 11 17:07 1 -> /dev/pts/2
    lrwx------ 1 ulmo staff 64 Feb 11 17:06 2 -> /dev/pts/2
    lrwx------ 1 ulmo staff 64 Feb 11 17:07 3 -> socket:[9160832]
    lrwx------ 1 ulmo staff 64 Feb 11 17:07 4 -> socket:[9161772]
    lrwx------ 1 ulmo staff 64 Feb 11 17:07 5 -> socket:[9161520]

The older process is probably from an older version. I attempt to update lightningd in a reasonable manner for every new long term invocation.

### `getinfo` output

{ "id" : "kindofnotyourbusiness", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "1111.2222.3333.4444", "port" : 9735 }, 
                { "type" : "ipv6", "address" : "face::kind:of:not:your:business", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1904-g2a979a2", "blockheight" : 508694, "network" : "bitcoin" }

**Comment by cdecker** [comment]
Thanks @Ulmo, sorry for prematurely closing the other issue as a duplicate, now I see the difference. Honestly I have no idea how a child process could survive the death of its parent without the double-fork magic.

**Comment by rustyrussell** [comment]
Completely allowed, but it should die when the fd closes.  Let me look...

**Comment by rustyrussell** [comment]
Nothing significant has changed since then, but I can't see how channeld would survive its parent (or gossipd!) going away.

In theory we could be blocked on writing to the peer, but in practice that's quite unlikely.
