### ISSUE TITLE
"unable to create channel reservation for chain"

### ISSUE THREAD

**Issue by FeedTheWeb** [ElementsProject/lightning#989]
### Issue and Steps to Reproduce
connected to a node, trying to fund the channel, but get this error.  
https://dpaste.de/FVWg

it stays in state 'GOSSIPING' for a while, and then it disappears.

**Comment by cdecker** [comment]
Seems you are connecting to an `lnd` node on a different network:

 - You are on testnet3 [000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943](https://testnet.smartbit.com.au/block/000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943)
 - The other `lnd` node is on mainnet [000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f](https://www.smartbit.com.au/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f)

**Comment by FeedTheWeb** [comment]
ok. Somone gave me the node details to connect to, I assumed it was on testnet. 
Will try a different node ;)
